Squid Web Cache: squid/src/AccessLogEntry.h File Reference
AccessLogEntry.h File Reference
#include "anyp/PortCfg.h"
#include "base/CodeContext.h"
#include "comm/Connection.h"
#include "error/Error.h"
#include "HierarchyLogEntry.h"
#include "http/ProtocolVersion.h"
#include "http/RequestMethod.h"
#include "HttpHeader.h"
#include "icp_opcode.h"
#include "ip/Address.h"
#include "LogTags.h"
#include "MessageSizes.h"
#include "Notes.h"
#include "proxyp/forward.h"
#include "sbuf/forward.h"
#include "adaptation/icap/Elements.h"
#include "ssl/gadgets.h"
#include "ssl/support.h"
Classes
class AccessLogEntry
class AccessLogEntry::HttpDetails
This subclass holds log info for HTTP protocol TODO: Inner class declarations should be moved outside TODO: details of HTTP held in the parent class need moving into here.
class AccessLogEntry::IcpDetails
This subclass holds log info for ICP protocol TODO: Inner class declarations should be moved outside.
class AccessLogEntry::HtcpDetails
This subclass holds log info for HTCP protocol TODO: Inner class declarations should be moved outside.
class AccessLogEntry::SslDetails
logging information specific to the SSL protocol
class AccessLogEntry::CacheDetails
This subclass holds log info for Squid internal stats TODO: Inner class declarations should be moved outside TODO: some details relevant to particular protocols need shuffling to other sub-classes TODO: this object field need renaming to 'squid' or something.
class AccessLogEntry::Headers
This subclass holds log info for various headers in raw format TODO: shuffle this to the relevant protocol section.
class AccessLogEntry::AdaptationDetails
This subclass holds general adaptation log info. TODO: Inner class declarations should be moved outside.
class AccessLogEntry::IcapLogEntry
This subclass holds log info for ICAP part of request TODO: Inner class declarations should be moved outside.
Functions
void accessLogLogTo (CustomLog *, const AccessLogEntryPointer &, ACLChecklist *checklist=nullptr)
void accessLogLog (const AccessLogEntryPointer &, ACLChecklist *)
void accessLogRotate (void)
void accessLogClose (void)
void accessLogInit (void)
const char * accessLogTime (time_t)
Function Documentation
accessLogClose()
void accessLogClose (void)
Definition at line 159 of file access_log.cc.
References SquidConfig::accesslogs, Config, log(), SquidConfig::Log, and logfileClose().
Referenced by mainReconfigureStart(), and SquidShutdown().
accessLogInit()
void accessLogInit (void)
Definition at line 274 of file access_log.cc.
References accessLogRegisterWithCacheManager(), SquidConfig::accesslogs, Log::Format::CLF_NONE, Config, Notes::empty(), Log::LogConfig::hasAdaptToken, Log::LogConfig::hasIcapToken, Format::LFT_ADAPTATION_ALL_XACT_TIMES, Format::LFT_ADAPTATION_LAST_ALL_HEADERS, Format::LFT_ADAPTATION_LAST_HEADER, Format::LFT_ADAPTATION_LAST_HEADER_ELEM, Format::LFT_ADAPTATION_SUM_XACT_TIMES, Format::LFT_ICAP_TOTAL_TIME, Format::LFT_NOTE, log(), SquidConfig::Log, LOG_ENABLE, logfileOpen(), LogfileStatus, Adaptation::Config::metaHeaders(), Format::Token::next, and Log::TheConfig.
Referenced by mainInitialize(), and mainReconfigureFinish().
accessLogLog()
void accessLogLog (const AccessLogEntryPointer & al, ACLChecklist * checklist)
Definition at line 136 of file access_log.cc.
References accessLogLogTo(), SquidConfig::accesslogs, Config, SquidConfig::Log, LOG_ENABLE, and LogfileStatus.
Referenced by htcpLogHtcp(), icpLogIcp(), Comm::TcpAcceptor::logAcceptError(), and ClientHttpRequest::logRequest().
accessLogLogTo()
void accessLogLogTo (CustomLog * log, const AccessLogEntryPointer & al, ACLChecklist * checklist = nullptr)
Definition at line 66 of file access_log.cc.
References Acl::Answer::allowed(), Log::Format::CLF_COMBINED, Log::Format::CLF_COMMON, Log::Format::CLF_CUSTOM, Log::Format::CLF_ICAP_SQUID, Log::Format::CLF_NONE, Log::Format::CLF_REFERER, Log::Format::CLF_SQUID, Log::Format::CLF_USERAGENT, AccessLogEntry::HttpDetails::content_type, Format::Dash, dash_str, ACLChecklist::fastCheck(), fatalf(), AccessLogEntry::hier, HierarchyLogEntry::host, AccessLogEntry::http, Log::Format::HttpdCombined(), Log::Format::HttpdCommon(), SBuf::isEmpty(), log(), logfileLineEnd(), logfileLineStart(), Log::Format::SquidCustom(), SQUIDHOSTNAMELEN, Log::Format::SquidIcap(), Log::Format::SquidNative(), Log::Format::SquidReferer(), Log::Format::SquidUserAgent(), AccessLogEntry::url, and xstrncpy().
Referenced by accessLogLog(), and icapLogLog().
accessLogRotate()
void accessLogRotate (void)
Definition at line 145 of file access_log.cc.
References SquidConfig::accesslogs, Config, log(), and SquidConfig::Log.
Referenced by mainRotate().
accessLogTime()
const char * accessLogTime (time_t)