Squid Web Cache: squid/src/log/access_log.cc File Reference
access_log.cc File Reference
#include "squid.h"
#include "AccessLogEntry.h"
#include "acl/Checklist.h"
#include "sbuf/Algorithms.h"
#include "adaptation/Config.h"
#include "base/PackableStream.h"
#include "CachePeer.h"
#include "error/Detail.h"
#include "errorpage.h"
#include "format/Token.h"
#include "globals.h"
#include "hier_code.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "log/access_log.h"
#include "log/Config.h"
#include "log/CustomLog.h"
#include "log/File.h"
#include "log/Formats.h"
#include "MemBuf.h"
#include "mgr/Registration.h"
#include "rfc1738.h"
#include "sbuf/SBuf.h"
#include "SquidConfig.h"
#include "Store.h"
#include "eui/Eui48.h"
#include "eui/Eui64.h"
#include <unordered_map>
Functions
void accessLogLogTo (CustomLog *log, const AccessLogEntryPointer &al, ACLChecklist *checklist)
void accessLogLog (const AccessLogEntryPointer &al, ACLChecklist *checklist)
void accessLogRotate (void)
void accessLogClose (void)
static void accessLogRegisterWithCacheManager (void)
void accessLogInit (void)
Variables
int LogfileStatus = LOG_DISABLE
Function Documentation
accessLogClose()
void accessLogClose (void)
Definition at line 159 of file access_log.cc.
References SquidConfig::accesslogs, Config, log(), SquidConfig::Log, and logfileClose().
Referenced by mainReconfigureStart(), and SquidShutdown().
accessLogInit()
void accessLogInit (void)
Definition at line 274 of file access_log.cc.
References accessLogRegisterWithCacheManager(), SquidConfig::accesslogs, Log::Format::CLF_NONE, Config, Notes::empty(), Log::LogConfig::hasAdaptToken, Log::LogConfig::hasIcapToken, Format::LFT_ADAPTATION_ALL_XACT_TIMES, Format::LFT_ADAPTATION_LAST_ALL_HEADERS, Format::LFT_ADAPTATION_LAST_HEADER, Format::LFT_ADAPTATION_LAST_HEADER_ELEM, Format::LFT_ADAPTATION_SUM_XACT_TIMES, Format::LFT_ICAP_TOTAL_TIME, Format::LFT_NOTE, log(), SquidConfig::Log, LOG_ENABLE, logfileOpen(), LogfileStatus, Adaptation::Config::metaHeaders(), Format::Token::next, and Log::TheConfig.
Referenced by mainInitialize(), and mainReconfigureFinish().
accessLogLog()
void accessLogLog (const AccessLogEntryPointer & al, ACLChecklist * checklist)
Definition at line 136 of file access_log.cc.
References accessLogLogTo(), SquidConfig::accesslogs, Config, SquidConfig::Log, LOG_ENABLE, and LogfileStatus.
Referenced by htcpLogHtcp(), icpLogIcp(), Comm::TcpAcceptor::logAcceptError(), and ClientHttpRequest::logRequest().
accessLogLogTo()
void accessLogLogTo (CustomLog * log, const AccessLogEntryPointer & al, ACLChecklist * checklist)
Definition at line 66 of file access_log.cc.
References Acl::Answer::allowed(), Log::Format::CLF_COMBINED, Log::Format::CLF_COMMON, Log::Format::CLF_CUSTOM, Log::Format::CLF_ICAP_SQUID, Log::Format::CLF_NONE, Log::Format::CLF_REFERER, Log::Format::CLF_SQUID, Log::Format::CLF_USERAGENT, AccessLogEntry::HttpDetails::content_type, Format::Dash, dash_str, ACLChecklist::fastCheck(), fatalf(), AccessLogEntry::hier, HierarchyLogEntry::host, AccessLogEntry::http, Log::Format::HttpdCombined(), Log::Format::HttpdCommon(), SBuf::isEmpty(), log(), logfileLineEnd(), logfileLineStart(), Log::Format::SquidCustom(), SQUIDHOSTNAMELEN, Log::Format::SquidIcap(), Log::Format::SquidNative(), Log::Format::SquidReferer(), Log::Format::SquidUserAgent(), AccessLogEntry::url, and xstrncpy().
Referenced by accessLogLog(), and icapLogLog().
accessLogRegisterWithCacheManager()
static void accessLogRegisterWithCacheManager (void) static
Definition at line 266 of file access_log.cc.
Referenced by accessLogInit().
accessLogRotate()
void accessLogRotate (void)
Definition at line 145 of file access_log.cc.
References SquidConfig::accesslogs, Config, log(), and SquidConfig::Log.
Referenced by mainRotate().
Variable Documentation
LogfileStatus
int LogfileStatus = LOG_DISABLE
Definition at line 63 of file access_log.cc.
Referenced by accessLogInit(), and accessLogLog().