Squid Web Cache: squid/src/acl/external/kerberos_ldap_group/support.h File Reference
support.h File Reference
#include "compat/krb5.h"
#include <cstring>
Classes
struct gdstruct
struct ndstruct
struct lsstruct
struct main_args
struct hstruct
struct ldap_creds
Macros
#define KERBEROS_LDAP_GROUP_VERSION "1.4.0sq"
#define LDAP_DEPRECATED 1
#define PROGRAM "kerberos_ldap_group"
Functions
void log (char *format,...)
void error (char *format,...)
void warn (char *format,...)
void init_args (struct main_args *margs)
void clean_args (struct main_args *margs)
const char * LogTime (void)
int check_memberof (struct main_args *margs, char *user, char *domain)
int get_memberof (struct main_args *margs, char *user, char *domain, char *group)
char * get_netbios_name (struct main_args *margs, char *netbios)
int create_gd (struct main_args *margs)
int create_nd (struct main_args *margs)
int create_ls (struct main_args *margs)
size_t get_ldap_hostname_list (struct main_args *margs, struct hstruct **hlist, size_t nhosts, char *domain)
size_t get_hostname_list (struct hstruct **hlist, size_t nhosts, char *name)
size_t free_hostname_list (struct hstruct **hlist, size_t nhosts)
Variables
int log_enabled
Macro Definition Documentation
KERBEROS_LDAP_GROUP_VERSION
#define KERBEROS_LDAP_GROUP_VERSION "1.4.0sq"
Definition at line 36 of file support.h.
LDAP_DEPRECATED
#define LDAP_DEPRECATED 1
Definition at line 44 of file support.h.
PROGRAM
#define PROGRAM "kerberos_ldap_group"
Definition at line 169 of file support.h.
Function Documentation
check_memberof()
int check_memberof (struct main_args * margs, char * user, char * domain)
clean_args()
void clean_args (struct main_args * margs)
create_gd()
int create_gd (struct main_args * margs)
create_ls()
int create_ls (struct main_args * margs)
create_nd()
int create_nd (struct main_args * margs)
error()
void error (char * format, ...)
Referenced by ConnStateData::abortChunkedRequestBody(), Snmp::Inquirer::aggregate(), Format::Format::assemble(), Security::PeerConnector::bail(), Http::Tunneler::bailOnResponseError(), Http::Tunneler::bailWith(), ClientHttpRequest::calloutsError(), Ssl::chainCertificatesToSSLContext(), CheckFieldDataLength(), CheckSectionLength(), Adaptation::Icap::Options::configure(), FwdState::connectedToPeer(), HttpStateData::continueAfterParsingHeader(), Security::ServerOptions::createStaticServerContext(), Ftp::Client::failed(), Ftp::Relay::failed(), Ftp::Relay::failedErrorMessage(), Ftp::Client::failedHttpStatus(), Ftp::Gateway::failedHttpStatus(), Rock::Rebuild::failure(), Adaptation::ServiceGroup::finalizeMsg(), Ftp::Relay::forwardError(), IpCacheLookupForwarder::forwardLookup(), Adaptation::Ecap::ServiceRep::handleFinalizeFailure(), ConnStateData::handleIdleClientPinnedTlsRead(), Http::Tunneler::handleReadyRead(), ConnStateData::handleRequestBodyData(), Http::Tunneler::handleWrittenRequest(), httpHeaderNoteParsedEntry(), idnsCallback(), idnsCallbackOnEarlyError(), main(), FwdState::noteConnection(), TunnelStateData::noteConnection(), Http::Stream::noteIoError(), Security::BlindPeerConnector::noteNegotiationDone(), Ssl::IcapPeerConnector::noteNegotiationDone(), Ssl::PeekingPeerConnector::noteNegotiationDone(), TunnelStateData::noteSecurityPeerConnectorAnswer(), store_client::noteSwapInDone(), operator<<(), Adaptation::Ecap::HeaderRep::parse(), Http::Message::parse(), Adaptation::Icap::TrailerParser::parse(), Adaptation::Icap::Xaction::parseHttpMsg(), Adaptation::Icap::ModXact::parsePart(), HttpReply::parseTerminatedPrefix(), Adaptation::Icap::ModXact::prepEchoing(), ConnStateData::requestTimeout(), HttpReply::sanityCheckStartLine(), TunnelStateData::saveError(), Mgr::Forwarder::sendError(), Snmp::Forwarder::sendError(), SetField(), ConnStateData::stopReceiving(), ConnStateData::stopSending(), strwordtok(), File::sysCallFailure(), ConnStateData::terminateAll(), TestHttpReply::testSanityCheckFirstLine(), TestHttpRequest::testSanityCheckStartLine(), FwdState::tunnelEstablishmentDone(), TunnelStateData::tunnelEstablishmentDone(), Mmapping::unmap(), ConnStateData::updateError(), ClientHttpRequest::updateError(), TunnelStateData::usePinned(), Adaptation::Icap::Options::valid(), and xstrerr().
free_hostname_list()
size_t free_hostname_list (struct hstruct ** hlist, size_t nhosts)
get_hostname_list()
size_t get_hostname_list (struct hstruct ** hlist, size_t nhosts, char * name)
get_ldap_hostname_list()
size_t get_ldap_hostname_list (struct main_args * margs, struct hstruct ** hlist, size_t nhosts, char * domain)
get_memberof()
int get_memberof (struct main_args * margs, char * user, char * domain, char * group)
get_netbios_name()
char * get_netbios_name (struct main_args * margs, char * netbios)
init_args()
void init_args (struct main_args * margs)
log()
void log (char * format, ...)
Referenced by accessLogClose(), accessLogInit(), accessLogLogTo(), accessLogRotate(), configDoConfigure(), debugOpenLog(), dump_access_log(), free_access_log(), hashPrime(), icapLogClose(), icapLogOpen(), icapLogRotate(), isPowTen(), Fs::Ufs::RebuildState::rebuildFromSwapLog(), Log::Format::SquidCustom(), and Fs::Ufs::UFSSwapLogParser::SwapLogEntries().
LogTime()
const char * LogTime (void) inline
Definition at line 94 of file negotiate_kerberos.h.
warn()
void warn (char * format, ...)
Referenced by redirectHandleReply().
Variable Documentation
log_enabled
int log_enabled extern