Squid Web Cache: squid/src/adaptation/ecap/Host.cc File Reference
Host.cc File Reference
#include "squid.h"
#include "adaptation/ecap/Host.h"
#include "adaptation/ecap/MessageRep.h"
#include "adaptation/ecap/ServiceRep.h"
#include "base/TextException.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "MasterXaction.h"
Functions
static SBuf EssentialVersion (const SBuf &raw)
Strips libecap version components not affecting compatibility decisions.
static bool SupportedVersion (const char *vTheir, const char *them)
static int SquidLogLevel (libecap::LogVerbosity lv)
Variables
static libecap::shared_ptr< Adaptation::Ecap::Host > TheHost
the host application (i.e., Squid) wrapper registered with libecap
Function Documentation
EssentialVersion()
static SBuf EssentialVersion (const SBuf & raw) static
Definition at line 86 of file Host.cc.
References SBuf::find(), SBuf::npos, and SBuf::substr().
Referenced by SupportedVersion().
SquidLogLevel()
static int SquidLogLevel (libecap::LogVerbosity lv) static
Definition at line 136 of file Host.cc.
References DBG_CRITICAL, DBG_DATA, and DBG_IMPORTANT.
Referenced by Adaptation::Ecap::Host::openDebug().
SupportedVersion()
static bool SupportedVersion (const char * vTheir, const char * them) static
If "their" libecap version is not compatible with what Squid has been built with, then complain and return false.
Definition at line 99 of file Host.cc.
References DBG_CRITICAL, debugs, and EssentialVersion().
Referenced by Adaptation::Ecap::Host::noteVersionedService(), and Adaptation::Ecap::Host::Register().
Variable Documentation
TheHost
libecap::shared_ptr<Adaptation::Ecap::Host> TheHost static
Definition at line 41 of file Host.cc.
Referenced by Adaptation::Ecap::Host::Register().