Squid Web Cache: squid/src/sbuf/Algorithms.h File Reference
Algorithms.h File Reference
#include "sbuf/SBuf.h"
#include <algorithm>
#include <numeric>
Classes
class SBufEqual
SBuf equality predicate for STL algorithms etc.
class SBufStartsWith
SBuf "starts with" predicate for STL algorithms etc.
class SBufAddLength
struct std::hash< SBuf >
default hash functor to support std::unordered_map<SBuf,*>
class CaseInsensitiveSBufHash
class CaseInsensitiveSBufEqual
Namespaces
namespace std
STL namespace.
Functions
template<class ContainerIterator >
SBuf & JoinContainerIntoSBuf (SBuf &dest, const ContainerIterator &begin, const ContainerIterator &end, const SBuf &separator, const SBuf &prefix=SBuf(), const SBuf &suffix=SBuf())
template<class ContainerIterator >
SBuf JoinContainerToSBuf (const ContainerIterator &begin, const ContainerIterator &end, const SBuf &separator, const SBuf &prefix=SBuf(), const SBuf &suffix=SBuf())
convenience wrapper of JoinContainerIntoSBuf with no caller-supplied SBuf
Function Documentation
JoinContainerIntoSBuf()
template<class ContainerIterator > SBuf & JoinContainerIntoSBuf (SBuf & dest, const ContainerIterator & begin, const ContainerIterator & end, const SBuf & separator, const SBuf & prefix = SBuf(), const SBuf & suffix = SBuf())
Join container of SBufs and append to supplied target
append to the target SBuf all elements in the [begin,end) range from an iterable container, prefixed by prefix, separated by separator and followed by suffix. Prefix and suffix are added also in case of empty iterable
Returns
the modified dest
Definition at line 68 of file Algorithms.h.
References SBuf::append(), SBuf::length(), SBufReservationRequirements::minSpace, and SBuf::reserve().
Referenced by compileREs(), and JoinContainerToSBuf().
JoinContainerToSBuf()
template<class ContainerIterator > SBuf JoinContainerToSBuf (const ContainerIterator & begin, const ContainerIterator & end, const SBuf & separator, const SBuf & prefix = SBuf(), const SBuf & suffix = SBuf())
Definition at line 98 of file Algorithms.h.
References JoinContainerIntoSBuf().
Referenced by ACLUserData::dump(), and TestSBufList::testSBufListJoin().