Squid Web Cache: squid/lib/snmplib/asn1.c File Reference
asn1.c File Reference
#include "squid.h"
#include "asn1.h"
#include "snmp_api_error.h"
Functions
u_char * asn_build_header (u_char *data, int *datalength, u_char type, int length)
u_char * asn_parse_int (u_char *data, int *datalength, u_char *type, int *intp, int intsize)
u_char * asn_parse_unsigned_int (u_char *data, int *datalength, u_char *type, u_int *intp, int intsize)
u_char * asn_build_int (u_char *data, int *datalength, u_char type, int *intp, int intsize)
u_char * asn_build_unsigned_int (u_char *data, int *datalength, u_char type, u_int *intp, int intsize)
u_char * asn_parse_string (u_char *data, int *datalength, u_char *type, u_char *string, int *strlength)
u_char * asn_build_string (u_char *data, int *datalength, u_char type, u_char *string, int strlength)
u_char * asn_parse_header (u_char *data, int *datalength, u_char *type)
u_char * asn_build_header_with_truth (u_char *data, int *datalength, u_char type, int length, int truth)
u_char * asn_parse_length (u_char *data, u_int *length)
u_char * asn_build_length (u_char *data, int *datalength, int length, int truth)
u_char * asn_parse_objid (u_char *data, int *datalength, u_char *type, oid *objid, int *objidlength)
u_char * asn_build_objid (u_char *data, int *datalength, u_char type, oid *objid, int objidlength)
u_char * asn_build_null (u_char *data, int *datalength, u_char type)
u_char * asn_build_exception (u_char *data, int *datalength, u_char type)
Function Documentation
asn_build_exception()
u_char * asn_build_exception (u_char * data, int * datalength, u_char type)
Definition at line 854 of file asn1.c.
References asn_build_header_with_truth().
Referenced by snmp_var_EncodeVarBind().
asn_build_header()
u_char * asn_build_header (u_char * data, int * datalength, u_char type, int length)
Definition at line 93 of file asn1.c.
References asn_build_header_with_truth().
Referenced by snmp_msg_Encode(), and snmp_var_EncodeVarBind().
asn_build_header_with_truth()
u_char * asn_build_header_with_truth (u_char * data, int * datalength, u_char type, int length, int truth)
Definition at line 513 of file asn1.c.
References asn_build_length(), NULL, snmp_set_api_error(), and SNMPERR_ASN_ENCODE.
Referenced by asn_build_exception(), asn_build_header(), asn_build_int(), asn_build_null(), asn_build_objid(), asn_build_string(), and asn_build_unsigned_int().
asn_build_int()
u_char * asn_build_int (u_char * data, int * datalength, u_char type, int * intp, int intsize)
Definition at line 245 of file asn1.c.
References asn_build_header_with_truth(), int, NULL, snmp_set_api_error(), and SNMPERR_ASN_ENCODE.
Referenced by snmp_msg_Encode(), snmp_pdu_encode(), and snmp_var_EncodeVarBind().
asn_build_length()
u_char * asn_build_length (u_char * data, int * datalength, int length, int truth)
Definition at line 570 of file asn1.c.
References ASN_LONG_LEN, NULL, snmp_set_api_error(), and SNMPERR_ASN_ENCODE.
Referenced by asn_build_header_with_truth().
asn_build_null()
u_char * asn_build_null (u_char * data, int * datalength, u_char type)
Definition at line 820 of file asn1.c.
References asn_build_header_with_truth().
Referenced by snmp_var_EncodeVarBind().
asn_build_objid()
u_char * asn_build_objid (u_char * data, int * datalength, u_char type, oid * objid, int objidlength)
Definition at line 727 of file asn1.c.
References ASN_BIT8, asn_build_header_with_truth(), MAX_OID_LEN, NULL, snmp_set_api_error(), SNMPERR_ASN_DECODE, and SNMPERR_ASN_ENCODE.
Referenced by snmp_pdu_encode(), and snmp_var_EncodeVarBind().
asn_build_string()
u_char * asn_build_string (u_char * data, int * datalength, u_char type, u_char * string, int strlength)
Definition at line 433 of file asn1.c.
References asn_build_header_with_truth(), NULL, snmp_set_api_error(), and SNMPERR_ASN_DECODE.
Referenced by snmp_msg_Encode(), snmp_pdu_encode(), and snmp_var_EncodeVarBind().
asn_build_unsigned_int()
u_char * asn_build_unsigned_int (u_char * data, int * datalength, u_char type, u_int * intp, int intsize)
Definition at line 311 of file asn1.c.
References asn_build_header_with_truth(), int, NULL, snmp_set_api_error(), and SNMPERR_ASN_ENCODE.
Referenced by snmp_pdu_encode(), and snmp_var_EncodeVarBind().
asn_parse_header()
u_char * asn_parse_header (u_char * data, int * datalength, u_char * type)
Definition at line 470 of file asn1.c.
References asn_parse_length(), int, IS_EXTENSION_ID, NULL, snmp_set_api_error(), and SNMPERR_ASN_DECODE.
Referenced by snmp_msg_Decode(), snmp_pdu_decode(), and snmp_var_DecodeVarBind().
asn_parse_int()
u_char * asn_parse_int (u_char * data, int * datalength, u_char * type, int * intp, int intsize)
Definition at line 114 of file asn1.c.
References asn_parse_length(), int, NULL, snmp_set_api_error(), and SNMPERR_ASN_DECODE.
Referenced by snmp_msg_Decode(), snmp_pdu_decode(), and snmp_var_DecodeVarBind().
asn_parse_length()
u_char * asn_parse_length (u_char * data, u_int * length)
Definition at line 539 of file asn1.c.
References ASN_LONG_LEN, int, NULL, snmp_set_api_error(), and SNMPERR_ASN_DECODE.
Referenced by asn_parse_header(), asn_parse_int(), asn_parse_objid(), asn_parse_string(), and asn_parse_unsigned_int().
asn_parse_objid()
u_char * asn_parse_objid (u_char * data, int * datalength, u_char * type, oid * objid, int * objidlength)
Definition at line 638 of file asn1.c.
References ASN_BIT8, asn_parse_length(), int, MAX_SUBID, NULL, snmp_set_api_error(), and SNMPERR_ASN_DECODE.
Referenced by snmp_pdu_decode(), and snmp_var_DecodeVarBind().
asn_parse_string()
u_char * asn_parse_string (u_char * data, int * datalength, u_char * type, u_char * string, int * strlength)
Definition at line 387 of file asn1.c.
References asn_parse_length(), int, NULL, snmp_set_api_error(), and SNMPERR_ASN_DECODE.
Referenced by snmp_msg_Decode(), snmp_pdu_decode(), and snmp_var_DecodeVarBind().
asn_parse_unsigned_int()
u_char * asn_parse_unsigned_int (u_char * data, int * datalength, u_char * type, u_int * intp, int intsize)
Definition at line 179 of file asn1.c.
References asn_parse_length(), int, NULL, snmp_set_api_error(), and SNMPERR_ASN_DECODE.
Referenced by snmp_pdu_decode(), and snmp_var_DecodeVarBind().