Squid Web Cache: squid/src/base/AsyncCbdataCalls.h File Reference
AsyncCbdataCalls.h File Reference
#include "base/AsyncCall.h"
#include "base/CbcPointer.h"
Classes
class UnaryCbdataDialer< Argument1 >
Functions
template<class Argument1 >
UnaryCbdataDialer< Argument1 > cbdataDialer (typename UnaryCbdataDialer< Argument1 >::Handler *handler, Argument1 *arg1)
Function Documentation
cbdataDialer()
template<class Argument1 > UnaryCbdataDialer< Argument1 > cbdataDialer (typename UnaryCbdataDialer< Argument1 >::Handler * handler, Argument1 * arg1)
Definition at line 40 of file AsyncCbdataCalls.h.
Referenced by Ftp::Relay::Relay(), statefulhelper::cancelReservation(), store_client::noteNews(), Helper::Client::openSessions(), statefulhelper::openSessions(), Mgr::StoreToCommWriter::start(), and FwdState::start().