Squid Web Cache: squid/src/base/AsyncCall.h File Reference
AsyncCall.h File Reference
#include "base/CodeContext.h"
#include "base/forward.h"
#include "base/InstanceId.h"
#include "event.h"
#include "RefCount.h"
Classes
class AsyncCall
class CallDialer
class AsyncCallT< DialerClass >
Macros
#define ScheduleCallHere(call) ScheduleCall(__FILE__, __LINE__, (call))
Functions
std::ostream & operator<< (std::ostream &os, AsyncCall &call)
template<class Dialer >
RefCount< AsyncCallT< Dialer > > asyncCall (int aDebugSection, int aDebugLevel, const char *aName, const Dialer &aDialer)
bool ScheduleCall (const char *fileName, int fileLine, const AsyncCall::Pointer &)
Macro Definition Documentation
ScheduleCallHere
#define ScheduleCallHere (call) ScheduleCall(__FILE__, __LINE__, (call))
Call scheduling helper.
Definition at line 166 of file AsyncCall.h.
Function Documentation
asyncCall()
template<class Dialer > RefCount< AsyncCallT< Dialer > > asyncCall (int aDebugSection, int aDebugLevel, const char * aName, const Dialer & aDialer)
Definition at line 156 of file AsyncCall.h.
Referenced by Mgr::Forwarder::Forwarder(), Snmp::Forwarder::Forwarder(), Mgr::Inquirer::Inquirer(), Snmp::Inquirer::Inquirer(), Ftp::Relay::Relay(), Mgr::StoreToCommWriter::StoreToCommWriter(), _comm_close(), Adaptation::AccessCheck::AccessCheckCallbackWrapper(), Rock::IoState::callBack(), CallJob(), statefulhelper::cancelReservation(), EventScheduler::checkEvents(), clientStartListeningOn(), Log::TcpLogger::Close(), Client::delayRead(), AsyncJob::deleteThis(), BodyPipe::expectNoConsumption(), Client::handleMoreAdaptedBodyAvailable(), CollapsedForwarding::Init(), ClientHttpRequest::noteMoreBodyDataAvailable(), store_client::noteNews(), Mgr::StoreToCommWriter::NoteStoreCopied(), IpcIoFile::open(), HappyConnOpener::openFreshConnection(), Helper::Client::openSessions(), statefulhelper::openSessions(), BodyPipe::postConsume(), HttpStateData::proceedAfter1xx(), Http::One::Server::processParsedRequest(), Adaptation::Ecap::XactionRep::resume(), BodyPipe::scheduleBodyDataNotification(), BodyPipe::scheduleBodyEndNotification(), Mgr::StoreToCommWriter::scheduleCommWrite(), Ipc::UdsOp::setTimeout(), Mgr::Inquirer::start(), Mgr::StoreToCommWriter::start(), FwdState::start(), Ftp::Relay::stopOriginWait(), and Adaptation::Icap::Xaction::useIcapConnection().
operator<<()
std::ostream & operator<< (std::ostream & os, AsyncCall & call) inline
Definition at line 96 of file AsyncCall.h.
References AsyncCall::print().
ScheduleCall()
bool ScheduleCall (const char * fileName, int fileLine, const AsyncCall::Pointer & call)
Call scheduling helper. Use ScheduleCallHere if you can.
Definition at line 94 of file AsyncCall.cc.
References AsyncCall::codeContext, CodeContext::Current(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncCall::id, AsyncCallQueue::Instance(), and AsyncCallQueue::schedule().
Referenced by CallJob().