Squid Web Cache: squid/src/base/AsyncJob.cc File Reference
AsyncJob.cc File Reference
#include "squid.h"
#include "base/AsyncCall.h"
#include "base/AsyncJob.h"
#include "base/AsyncJobCalls.h"
#include "base/PackableStream.h"
#include "base/TextException.h"
#include "cbdata.h"
#include "mem/PoolingAllocator.h"
#include "MemBuf.h"
#include "mgr/Registration.h"
#include "Store.h"
#include <ostream>
#include <unordered_set>
Functions
InstanceIdDefinitions (AsyncJob, "job")
static auto & AllJobs ()
a set of all AsyncJob objects in existence
Function Documentation
AllJobs()
static auto & AllJobs () static
Definition at line 30 of file AsyncJob.cc.
Referenced by AsyncJob::AsyncJob(), AsyncJob::~AsyncJob(), and AsyncJob::ReportAllJobs().
InstanceIdDefinitions()
InstanceIdDefinitions (AsyncJob , "job")