Squid Web Cache: squid/src/base/AsyncCall.cc File Reference
AsyncCall.cc File Reference
#include "squid.h"
#include "base/AsyncCall.h"
#include "base/AsyncCallQueue.h"
#include "base/CodeContext.h"
#include "cbdata.h"
#include "debug/Stream.h"
#include <ostream>
Functions
InstanceIdDefinitions (AsyncCall, "call")
bool ScheduleCall (const char *fileName, int fileLine, const AsyncCall::Pointer &call)
Function Documentation
InstanceIdDefinitions()
InstanceIdDefinitions (AsyncCall , "call")
ScheduleCall()
bool ScheduleCall (const char * fileName, int fileLine, const AsyncCall::Pointer & call)
Call scheduling helper. Use ScheduleCallHere if you can.
Definition at line 94 of file AsyncCall.cc.
References AsyncCall::codeContext, CodeContext::Current(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncCall::id, AsyncCallQueue::Instance(), and AsyncCallQueue::schedule().
Referenced by CallJob().