Squid Web Cache: squid/src/base/AsyncJobCalls.h File Reference
AsyncJobCalls.h File Reference
#include "base/AsyncJob.h"
#include "base/CbcPointer.h"
#include "debug/Messages.h"
#include "debug/Stream.h"
Classes
class JobDialer< Job >
class NullaryMemFunT< Job >
class UnaryMemFunT< Job, Data, Argument1 >
Macros
#define CallJobHere(debugSection, debugLevel, job, Class, method)
#define CallJobHere1(debugSection, debugLevel, job, Class, method, arg1)
#define JobCallback(dbgSection, dbgLevel, Dialer, job, method)
Convenience macro to create a Dialer-based job callback.
Functions
template<class Dialer >
AsyncCall::Pointer CallJob (int debugSection, int debugLevel, const char *fileName, int fileLine, const char *callName, const Dialer &dialer)
schedule an async job call using a dialer; use CallJobHere macros instead
template<class C >
NullaryMemFunT< C > JobMemFun (const CbcPointer< C > &job, typename NullaryMemFunT< C >::Method method)
template<class C , class Argument1 >
UnaryMemFunT< C, Argument1 > JobMemFun (const CbcPointer< C > &job, typename UnaryMemFunT< C, Argument1 >::Method method, Argument1 arg1)
Macro Definition Documentation
CallJobHere
#define CallJobHere (debugSection, debugLevel, job, Class, method)
Value:
    CallJob((debugSection), (debugLevel), __FILE__, __LINE__, \
        (#Class "::" #method), \
        JobMemFun<Class>((job), &Class::method))
Definition at line 59 of file AsyncJobCalls.h.
CallJobHere1
#define CallJobHere1 (debugSection, debugLevel, job, Class, method, arg1)
Value:
    CallJob((debugSection), (debugLevel), __FILE__, __LINE__, \
        (#Class "::" #method), \
        JobMemFun((job), &Class::method, (arg1)))
Definition at line 64 of file AsyncJobCalls.h.
JobCallback
#define JobCallback (dbgSection, dbgLevel, Dialer, job, method)
Value:
    asyncCall((dbgSection), (dbgLevel), #method, \
        Dialer(CbcPointer<Dialer::DestClass>(job), &method))
Definition at line 70 of file AsyncJobCalls.h.
Function Documentation
CallJob()
template<class Dialer > AsyncCall::Pointer CallJob (int debugSection, int debugLevel, const char * fileName, int fileLine, const char * callName, const Dialer & dialer)
Definition at line 51 of file AsyncJobCalls.h.
References asyncCall(), and ScheduleCall().
JobMemFun() [1/2]
template<class C > NullaryMemFunT< C > JobMemFun (const CbcPointer< C > & job, typename NullaryMemFunT< C >::Method method)
Definition at line 134 of file AsyncJobCalls.h.
Referenced by AsyncJob::deleteThis().
JobMemFun() [2/2]
template<class C , class Argument1 > UnaryMemFunT< C, Argument1 > JobMemFun (const CbcPointer< C > & job, typename UnaryMemFunT< C, Argument1 >::Method method, Argument1 arg1)
Definition at line 141 of file AsyncJobCalls.h.