Squid Web Cache: squid/src/acl/AtStepData.cc File Reference
AtStepData.cc File Reference
#include "squid.h"
#include "acl/AtStepData.h"
#include "acl/Checklist.h"
#include "base/EnumIterator.h"
#include "cache_cf.h"
#include "ConfigParser.h"
#include "debug/Stream.h"
#include "sbuf/Stream.h"
#include "wordlist.h"
#include <algorithm>
Functions
static const char * StepName (const XactionStep xstep)
static XactionStep StepValue (const char *name)
Function Documentation
StepName()
static const char * StepName (const XactionStep xstep) inline static
Definition at line 22 of file AtStepData.cc.
References assert, enumBegin_, and enumEnd_.
Referenced by ACLAtStepData::dump(), and StepValue().
StepValue()
static XactionStep StepValue (const char * name) static
Definition at line 40 of file AtStepData.cc.
References assert, Here, StepName(), and ToSBuf().
Referenced by ACLAtStepData::parse().