Squid Web Cache: squid/src/auth/Gadgets.cc File Reference
Gadgets.cc File Reference
#include "squid.h"
#include "acl/Acl.h"
#include "acl/FilledChecklist.h"
#include "auth/AclProxyAuth.h"
#include "auth/basic/User.h"
#include "auth/Config.h"
#include "auth/CredentialsCache.h"
#include "auth/digest/User.h"
#include "auth/Gadgets.h"
#include "auth/negotiate/User.h"
#include "auth/ntlm/User.h"
#include "auth/Scheme.h"
#include "auth/User.h"
#include "auth/UserRequest.h"
#include "client_side.h"
#include "globals.h"
#include "http/Stream.h"
#include "HttpReply.h"
#include "HttpRequest.h"
Functions
int authenticateActiveSchemeCount (void)
int authenticateSchemeCount (void)
static void authenticateRegisterWithCacheManager (Auth::ConfigVector *config)
void authenticateInit (Auth::ConfigVector *config)
void authenticateRotate (void)
void authenticateReset (void)
std::vector< Auth::User::Pointer > authenticateCachedUsersList ()
Function Documentation
authenticateActiveSchemeCount()
int authenticateActiveSchemeCount (void)
Definition at line 38 of file Gadgets.cc.
References debugs, Auth::Config::schemes, and Auth::TheConfig.
Referenced by ACLProxyAuth::valid(), and ACLExternal::valid().
authenticateCachedUsersList()
std::vector< Auth::User::Pointer > authenticateCachedUsersList ()
Definition at line 108 of file Gadgets.cc.
References Auth::SchemeConfig::Find().
Referenced by Auth::User::CredentialsCacheStats().
authenticateInit()
void authenticateInit (Auth::ConfigVector * config)
Definition at line 70 of file Gadgets.cc.
References authenticateRegisterWithCacheManager().
Referenced by fake_auth_setup(), mainInitialize(), mainReconfigureFinish(), and mainRotate().
authenticateRegisterWithCacheManager()
static void authenticateRegisterWithCacheManager (Auth::ConfigVector * config) static
Definition at line 63 of file Gadgets.cc.
Referenced by authenticateInit().
authenticateReset()
void authenticateReset (void)
Remove all idle authentication state. Intended for use by reconfigure.
Removes the username cache contents and global configuration state. Stops just short of detaching the auth components completely.
Currently active requests should finish. Howevee new requests will not use authentication unless something causes the global config to be rebuilt. Such as a configure load action adding config and re-running authenticateInit().
Definition at line 94 of file Gadgets.cc.
References authenticateRotate(), debugs, Auth::Config::schemes, and Auth::TheConfig.
Referenced by mainReconfigureStart(), and SquidShutdown().
authenticateRotate()
void authenticateRotate (void)
Definition at line 85 of file Gadgets.cc.
References Auth::Config::schemes, and Auth::TheConfig.
Referenced by authenticateReset(), and mainRotate().
authenticateSchemeCount()
int authenticateSchemeCount (void)
Definition at line 53 of file Gadgets.cc.
References debugs, and Auth::Scheme::GetSchemes().
Referenced by ACLProxyAuth::valid(), and ACLExternal::valid().