Squid Web Cache: squid/src/auth/Acl.cc File Reference
Acl.cc File Reference
#include "squid.h"
#include "acl/Acl.h"
#include "acl/FilledChecklist.h"
#include "auth/Acl.h"
#include "auth/AclProxyAuth.h"
#include "auth/UserRequest.h"
#include "client_side.h"
#include "fatal.h"
#include "http/Stream.h"
#include "HttpRequest.h"
Functions
Acl::Answer AuthenticateAcl (ACLChecklist *ch, const Acl::Node &acl)
Function Documentation
AuthenticateAcl()
Acl::Answer AuthenticateAcl (ACLChecklist * ch, const Acl::Node & acl)
Return values
ACCESS_AUTH_REQUIRED credentials missing. challenge required.
ACCESS_DENIED user not authenticated (authentication error?)
ACCESS_DUNNO user authentication is in progress
ACCESS_DENIED user not authorized
ACCESS_ALLOWED user authenticated and authorized
Definition at line 28 of file Acl.cc.
References ACCESS_ALLOWED, ACCESS_AUTH_REQUIRED, ACCESS_DENIED, ACCESS_DUNNO, ACLFilledChecklist::al, AUTH_ACL_CANNOT_AUTHENTICATE, AUTH_ACL_CHALLENGE, AUTH_ACL_HELPER, AUTH_AUTHENTICATED, ACLFilledChecklist::auth_user_request, Http::AUTHORIZATION, ACLFilledChecklist::conn(), DBG_IMPORTANT, debugs, fatal(), Filled(), ConnStateData::getAuth(), RefCount< C >::getRaw(), ACLChecklist::goAsync(), Http::PROXY_AUTHORIZATION, ACLFilledChecklist::request, ACLFilledChecklist::src_addr, ACLProxyAuth::StartLookup(), and Auth::UserRequest::tryToAuthenticateAndSetAuthUser().
Referenced by ACLExternal::aclMatchExternal(), ACLProxyAuth::match(), and ACLMaxUserIP::match().