Squid Web Cache: squid/src/auth/Gadgets.h File Reference
Gadgets.h File Reference
#include "auth/User.h"
#include "hash.h"
Typedefs
typedef void AUTHSSTATS(StoreEntry *)
Functions
void authenticateInit (Auth::ConfigVector *)
void authenticateReset (void)
void authenticateRotate (void)
void authenticateFreeProxyAuthUserACLResults (void *data)
int authenticateActiveSchemeCount (void)
int authenticateSchemeCount (void)
void authenticateOnCloseConnection (ConnStateData *conn)
std::vector< Auth::User::Pointer > authenticateCachedUsersList ()
Typedef Documentation
AUTHSSTATS
typedef void AUTHSSTATS(StoreEntry *)
Definition at line 21 of file Gadgets.h.
Function Documentation
authenticateActiveSchemeCount()
int authenticateActiveSchemeCount (void)
Definition at line 38 of file Gadgets.cc.
References debugs, Auth::Config::schemes, and Auth::TheConfig.
Referenced by ACLProxyAuth::valid(), and ACLExternal::valid().
authenticateCachedUsersList()
std::vector< Auth::User::Pointer > authenticateCachedUsersList ()
Definition at line 108 of file Gadgets.cc.
References Auth::SchemeConfig::Find().
Referenced by Auth::User::CredentialsCacheStats().
authenticateFreeProxyAuthUserACLResults()
void authenticateFreeProxyAuthUserACLResults (void * data)
authenticateInit()
void authenticateInit (Auth::ConfigVector * config)
Definition at line 70 of file Gadgets.cc.
References authenticateRegisterWithCacheManager().
Referenced by fake_auth_setup(), mainInitialize(), mainReconfigureFinish(), and mainRotate().
authenticateOnCloseConnection()
void authenticateOnCloseConnection (ConnStateData * conn)
authenticateReset()
void authenticateReset (void)
Remove all idle authentication state. Intended for use by reconfigure.
Removes the username cache contents and global configuration state. Stops just short of detaching the auth components completely.
Currently active requests should finish. Howevee new requests will not use authentication unless something causes the global config to be rebuilt. Such as a configure load action adding config and re-running authenticateInit().
Definition at line 94 of file Gadgets.cc.
References authenticateRotate(), debugs, Auth::Config::schemes, and Auth::TheConfig.
Referenced by mainReconfigureStart(), and SquidShutdown().
authenticateRotate()
void authenticateRotate (void)
Definition at line 85 of file Gadgets.cc.
References Auth::Config::schemes, and Auth::TheConfig.
Referenced by authenticateReset(), and mainRotate().
authenticateSchemeCount()
int authenticateSchemeCount (void)
Definition at line 53 of file Gadgets.cc.
References debugs, and Auth::Scheme::GetSchemes().
Referenced by ACLProxyAuth::valid(), and ACLExternal::valid().