Squid Web Cache: squid/src/base/Random.h File Reference
Random.h File Reference
#include <random>
Functions
std::mt19937::result_type RandomSeed32 ()
std::mt19937_64::result_type RandomSeed64 ()
a 64-bit version of RandomSeed32()
Function Documentation
RandomSeed32()
std::mt19937::result_type RandomSeed32 ()
A 32-bit random value suitable for seeding a 32-bit random number generator. Computing this value may require blocking device I/O but does not require waiting to accumulate entropy. Thus, this function:
may be called at runtime (e.g., the first time a given r.n.g. is needed)
should not be called frequently (e.g., once per transaction is too often)
should not be used as a source of randomness (use a r.n.g. instead)
Definition at line 13 of file Random.cc.
Referenced by authenticateDigestNonceNew(), eventAddIsh(), Fs::Ufs::UFSSwapDir::HandleCleanEvent(), idnsQueryID(), random_vector(), and RandomSeed64().
RandomSeed64()
std::mt19937_64::result_type RandomSeed64 ()
Definition at line 35 of file Random.cc.
References RandomSeed32().
Referenced by RandomUuid::RandomUuid().