Squid Web Cache: squid/src/auth/basic/NCSA/basic_ncsa_auth.cc File Reference
basic_ncsa_auth.cc File Reference
#include "squid.h"
#include "auth/basic/NCSA/crypt_md5.h"
#include "helper/protocol_defines.h"
#include "rfc1738.h"
#include <string>
#include <unordered_map>
Typedefs
typedef std::unordered_map< std::string, std::string > usermap_t
Functions
static void read_passwd_file (const char *passwdfile)
int main (int argc, char **argv)
Variables
usermap_t usermap
Typedef Documentation
usermap_t
typedef std::unordered_map<std::string, std::string> usermap_t
Definition at line 41 of file basic_ncsa_auth.cc.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 81 of file basic_ncsa_auth.cc.
References change_time, crypt(), crypt_md5(), HELPER_INPUT_BUFFER, md5sum(), read_passwd_file(), rfc1738_unescape(), SEND_ERR, SEND_OK, and usermap.
read_passwd_file()
static void read_passwd_file (const char * passwdfile) static
Definition at line 45 of file basic_ncsa_auth.cc.
References HELPER_INPUT_BUFFER, passwdfile, usermap, and xstrerr().
Referenced by main().
Variable Documentation
usermap
usermap_t usermap
Definition at line 42 of file basic_ncsa_auth.cc.
Referenced by main(), and read_passwd_file().