Squid Web Cache: squid/src/auth/basic/SSPI/basic_sspi_auth.cc File Reference
basic_sspi_auth.cc File Reference
#include "squid.h"
#include "auth/basic/SSPI/valid.h"
#include "helper/protocol_defines.h"
#include "rfc1738.h"
#include "util.h"
Functions
static void usage (const char *name)
static void process_options (int argc, char *argv[])
int main (int argc, char **argv)
Variables
static char NTGroup [256]
char * NTAllowedGroup
char * NTDisAllowedGroup
int UseDisallowedGroup = 0
int UseAllowedGroup = 0
int debug_enabled = 0
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 110 of file basic_sspi_auth.cc.
References debug(), errormsg, HELPER_INPUT_BUFFER, LoadSecurityDll(), NTGroup, NTLM_PACKAGE_NAME, NTV_NO_ERROR, NULL, process_options(), rfc1738_unescape(), SEND_ERR, SEND_OK, SSP_BASIC, UnloadSecurityDll(), and Valid_User().
process_options()
static void process_options (int argc, char * argv[]) static
Definition at line 71 of file basic_sspi_auth.cc.
References debug_enabled, Default_NTDomain, getopt(), NTAllowedGroup, NTDisAllowedGroup, optarg, optopt, safe_free, usage(), UseAllowedGroup, UseDisallowedGroup, and xstrdup.
Referenced by main().
usage()
static void usage (const char * name) static
Definition at line 59 of file basic_sspi_auth.cc.
Variable Documentation
debug_enabled
int debug_enabled = 0
Definition at line 50 of file basic_sspi_auth.cc.
Referenced by debug(), and process_options().
NTAllowedGroup
char* NTAllowedGroup
Definition at line 46 of file basic_sspi_auth.cc.
Referenced by process_options(), and Valid_User().
NTDisAllowedGroup
char* NTDisAllowedGroup
Definition at line 47 of file basic_sspi_auth.cc.
Referenced by process_options(), and Valid_User().
NTGroup
char NTGroup[256] static
Definition at line 45 of file basic_sspi_auth.cc.
Referenced by main().
UseAllowedGroup
int UseAllowedGroup = 0
Definition at line 49 of file basic_sspi_auth.cc.
Referenced by process_options(), and Valid_User().
UseDisallowedGroup
int UseDisallowedGroup = 0
Definition at line 48 of file basic_sspi_auth.cc.
Referenced by process_options(), and Valid_User().