Squid Web Cache: squid/src/auth/basic/SMB/basic_smb_auth.cc File Reference
basic_smb_auth.cc File Reference
#include "squid.h"
#include "helper/protocol_defines.h"
#include "rfc1738.h"
#include "util.h"
#include <cstring>
Classes
struct SMBDOMAIN
Macros
#define NMB_UNICAST 1
#define NMB_BROADCAST 2
Functions
static void print_esc (FILE *p, char *s)
int main (int argc, char *argv[])
Variables
struct SMBDOMAIN * firstdom = nullptr
struct SMBDOMAIN * lastdom = nullptr
Macro Definition Documentation
NMB_BROADCAST
#define NMB_BROADCAST 2
Definition at line 35 of file basic_smb_auth.cc.
NMB_UNICAST
#define NMB_UNICAST 1
Definition at line 34 of file basic_smb_auth.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 87 of file basic_smb_auth.cc.
References SMBDOMAIN::authfile, SMBDOMAIN::authshare, debug_enabled, firstdom, HELPER_INPUT_BUFFER, lastdom, SMBDOMAIN::name, SMBDOMAIN::next, NMB_BROADCAST, NMB_UNICAST, SMBDOMAIN::nmbaddr, SMBDOMAIN::nmbcast, SMBDOMAIN::passthrough, print_esc(), rfc1738_unescape(), SEND_ERR, SEND_OK, SMBDOMAIN::sname, xmalloc, and xstrdup.
print_esc()
static void print_esc (FILE * p, char * s) static
Definition at line 57 of file basic_smb_auth.cc.
References HELPER_INPUT_BUFFER.
Referenced by main().
Variable Documentation
firstdom
struct SMBDOMAIN* firstdom = nullptr
Definition at line 48 of file basic_smb_auth.cc.
Referenced by main().
lastdom
struct SMBDOMAIN* lastdom = nullptr
Definition at line 49 of file basic_smb_auth.cc.
Referenced by main().