Squid Web Cache: squid/src/ssl/bio.cc File Reference
bio.cc File Reference
#include "squid.h"
#include "base/IoManip.h"
#include "ssl/support.h"
#include "base/Raw.h"
#include "comm.h"
#include "fd.h"
#include "fde.h"
#include "globals.h"
#include "ip/Address.h"
#include "parser/BinaryTokenizer.h"
#include "ssl/bio.h"
Functions
static int squid_bio_write (BIO *table, const char *buf, int size)
wrapper for Bio::write()
static int squid_bio_read (BIO *table, char *buf, int size)
wrapper for Bio::read()
static int squid_bio_puts (BIO *table, const char *str)
implements puts() via write()
static long squid_bio_ctrl (BIO *table, int cmd, long arg1, void *arg2)
other BIO manipulations (those without dedicated callbacks in BIO table)
static int squid_bio_create (BIO *bi)
initializes BIO table after allocation
static int squid_bio_destroy (BIO *table)
cleans BIO table before deallocation
static void squid_ssl_info (const SSL *ssl, int where, int ret)
wrapper for Bio::stateChanged()
void applyTlsDetailsToSSL (SSL *ssl, Security::TlsDetails::Pointer const &details, Ssl::BumpMode bumpMode)
Variables
static BIO_METHOD SquidMethods
Function Documentation
applyTlsDetailsToSSL()
void applyTlsDetailsToSSL (SSL * ssl, Security::TlsDetails::Pointer const & details, Ssl::BumpMode bumpMode)
Definition at line 570 of file bio.cc.
References SBuf::append(), Ssl::bumpMode(), Ssl::bumpPeek, SBuf::c_str(), SBuf::isEmpty(), SSL_CIPHER_find(), and Security::Tls1p2orEarlier().
Referenced by Ssl::PeekingPeerConnector::initialize().
squid_bio_create()
static int squid_bio_create (BIO * h) static
Definition at line 447 of file bio.cc.
References BIO_set_data().
Referenced by Ssl::Bio::Create().
squid_bio_ctrl()
static long squid_bio_ctrl (BIO * h, int cmd, long arg1, void * arg2) static
Definition at line 498 of file bio.cc.
References assert, BIO_get_data(), BIO_get_init(), BIO_set_data(), BIO_set_init(), Security::Io::BIO_TO_SERVER, debugs, Ssl::Bio::fd(), and Ssl::Bio::flush().
Referenced by Ssl::Bio::Create().
squid_bio_destroy()
static int squid_bio_destroy (BIO * data) static
Definition at line 463 of file bio.cc.
References BIO_get_data(), and BIO_set_data().
Referenced by Ssl::Bio::Create().
squid_bio_puts()
static int squid_bio_puts (BIO * h, const char * str) static
Definition at line 490 of file bio.cc.
References assert, and squid_bio_write().
Referenced by Ssl::Bio::Create().
squid_bio_read()
static int squid_bio_read (BIO * h, char * buf, int size) static
Definition at line 481 of file bio.cc.
References assert, BIO_get_data(), Ssl::Bio::read(), and size.
Referenced by Ssl::Bio::Create().
squid_bio_write()
static int squid_bio_write (BIO * h, const char * buf, int num) static
Definition at line 472 of file bio.cc.
References assert, BIO_get_data(), size, and Ssl::Bio::write().
Referenced by Ssl::Bio::Create(), and squid_bio_puts().
squid_ssl_info()
static void squid_ssl_info (const SSL * ssl, int where, int ret) static
Definition at line 561 of file bio.cc.
References BIO_get_data().
Referenced by Ssl::Bio::Link().
Variable Documentation
SquidMethods
BIO_METHOD SquidMethods static
Initial value:
= {
    BIO_TYPE_SOCKET,
    "squid",
    squid_bio_write,
    squid_bio_read,
    squid_bio_puts,
    nullptr,
    squid_bio_ctrl,
    squid_bio_create,
    squid_bio_destroy,
    NULL
}
Initialization structure for the BIO table with Squid-specific methods and BIO method wrappers.
Definition at line 48 of file bio.cc.
Referenced by Ssl::Bio::Create().