Squid Web Cache: squid/src/CacheDigest.cc File Reference
CacheDigest.cc File Reference
#include "squid.h"
#include "md5.h"
#include "StatCounters.h"
#include "Store.h"
#include "store_key_md5.h"
#include "CacheDigest.h"
#include "util.h"
Classes
struct CacheDigestStats
Functions
static void cacheDigestHashKey (const CacheDigest *cd, const cache_key *key)
static void cacheDigestStats (const CacheDigest *cd, CacheDigestStats *stats)
void cacheDigestGuessStatsUpdate (CacheDigestGuessStats *stats, int real_hit, int guess_hit)
void cacheDigestGuessStatsReport (const CacheDigestGuessStats *stats, StoreEntry *sentry, const SBuf &label)
void cacheDigestReport (CacheDigest *cd, const SBuf &label, StoreEntry *e)
Variables
static uint32_t hashed_keys [4]
Function Documentation
cacheDigestGuessStatsReport()
void cacheDigestGuessStatsReport (const CacheDigestGuessStats * stats, StoreEntry * sentry, const SBuf & label)
Definition at line 209 of file CacheDigest.cc.
References assert, CacheDigestGuessStats::falseHits, CacheDigestGuessStats::falseMisses, SBuf::isEmpty(), SQUIDSBUFPH, SQUIDSBUFPRINT, storeAppendPrintf(), CacheDigestGuessStats::trueHits, CacheDigestGuessStats::trueMisses, and xpercent().
Referenced by peerDigestStatsReport(), and statPeerSelect().
cacheDigestGuessStatsUpdate()
void cacheDigestGuessStatsUpdate (CacheDigestGuessStats * stats, int real_hit, int guess_hit)
Definition at line 191 of file CacheDigest.cc.
References assert, CacheDigestGuessStats::falseHits, CacheDigestGuessStats::falseMisses, CacheDigestGuessStats::trueHits, and CacheDigestGuessStats::trueMisses.
cacheDigestHashKey()
static void cacheDigestHashKey (const CacheDigest * cd, const cache_key * key) static
Definition at line 279 of file CacheDigest.cc.
References debugs, hashed_keys, CacheDigest::mask_size, and storeKeyText().
Referenced by CacheDigest::add(), and CacheDigest::contains().
cacheDigestReport()
void cacheDigestReport (CacheDigest * cd, const SBuf & label, StoreEntry * e)
Definition at line 243 of file CacheDigest.cc.
References assert, CacheDigestStats::bit_count, CacheDigestStats::bit_on_count, CacheDigest::bits_per_entry, CacheDigestStats::bseq_count, CacheDigestStats::bseq_len_sum, cacheDigestStats(), CacheDigest::capacity, CacheDigest::count, CacheDigest::del_count, PRIu64, SQUIDSBUFPH, SQUIDSBUFPRINT, storeAppendPrintf(), xdiv(), and xpercentInt().
Referenced by peerDigestStatsReport(), and storeDigestReport().
cacheDigestStats()
static void cacheDigestStats (const CacheDigest * cd, CacheDigestStats * stats) static
Definition at line 149 of file CacheDigest.cc.
References assert, CacheDigestStats::bit_count, CacheDigestStats::bit_on_count, CacheDigestStats::bseq_count, CacheDigestStats::bseq_len_sum, CBIT_TEST, CacheDigest::mask, and CacheDigest::mask_size.
Referenced by cacheDigestReport(), and CacheDigest::usedMaskPercent().
Variable Documentation
hashed_keys
uint32_t hashed_keys[4] static
Definition at line 35 of file CacheDigest.cc.
Referenced by CacheDigest::add(), cacheDigestHashKey(), and CacheDigest::contains().