Squid Web Cache: squid/src/CacheDigest.h File Reference
CacheDigest.h File Reference
#include "mem/forward.h"
#include "store_key_md5.h"
Classes
class CacheDigest
Functions
void cacheDigestGuessStatsUpdate (CacheDigestGuessStats *stats, int real_hit, int guess_hit)
void cacheDigestGuessStatsReport (const CacheDigestGuessStats *stats, StoreEntry *sentry, const SBuf &label)
void cacheDigestReport (CacheDigest *cd, const SBuf &label, StoreEntry *e)
Function Documentation
cacheDigestGuessStatsReport()
void cacheDigestGuessStatsReport (const CacheDigestGuessStats * stats, StoreEntry * sentry, const SBuf & label)
Definition at line 209 of file CacheDigest.cc.
References assert, CacheDigestGuessStats::falseHits, CacheDigestGuessStats::falseMisses, SBuf::isEmpty(), SQUIDSBUFPH, SQUIDSBUFPRINT, storeAppendPrintf(), CacheDigestGuessStats::trueHits, CacheDigestGuessStats::trueMisses, and xpercent().
Referenced by peerDigestStatsReport(), and statPeerSelect().
cacheDigestGuessStatsUpdate()
void cacheDigestGuessStatsUpdate (CacheDigestGuessStats * stats, int real_hit, int guess_hit)
Definition at line 191 of file CacheDigest.cc.
References assert, CacheDigestGuessStats::falseHits, CacheDigestGuessStats::falseMisses, CacheDigestGuessStats::trueHits, and CacheDigestGuessStats::trueMisses.
cacheDigestReport()
void cacheDigestReport (CacheDigest * cd, const SBuf & label, StoreEntry * e)
Definition at line 243 of file CacheDigest.cc.
References assert, CacheDigestStats::bit_count, CacheDigestStats::bit_on_count, CacheDigest::bits_per_entry, CacheDigestStats::bseq_count, CacheDigestStats::bseq_len_sum, cacheDigestStats(), CacheDigest::capacity, CacheDigest::count, CacheDigest::del_count, PRIu64, SQUIDSBUFPH, SQUIDSBUFPRINT, storeAppendPrintf(), xdiv(), and xpercentInt().
Referenced by peerDigestStatsReport(), and storeDigestReport().