Squid Web Cache: squid/src/CachePeers.cc File Reference
CachePeers.cc File Reference
#include "squid.h"
#include "CachePeers.h"
#include "SquidConfig.h"
#include <algorithm>
Functions
const CachePeers & CurrentCachePeers ()
void DeleteConfigured (CachePeer *const peer)
destroys the given peer after removing it from the set of configured peers
Function Documentation
CurrentCachePeers()
const CachePeers & CurrentCachePeers ()
All configured cache_peers that are still available/relevant.
Returns
an empty container if no cache_peers were configured or all configured cache_peers were removed (e.g., by DeleteConfigured()).
Definition at line 43 of file CachePeers.cc.
References Config, and SquidConfig::peers.
Referenced by carpInit(), configDoConfigure(), findCachePeerByName(), findUsableParentAtHostname(), getDefaultParent(), getFirstUpParent(), getRoundRobinParent(), getWeightedRoundRobinParent(), htcpHandleClr(), neighbors_init(), neighborsCount(), neighborsHtcpClear(), peer_Inst(), peerClearRR(), peerDnsRefreshStart(), peerSourceHashInit(), peerUserHashInit(), PeerSelector::selectAllParents(), snmp_meshPtblFn(), statPeerSelect(), PeerPoolMgrsRr::syncConfig(), and whichPeer().
DeleteConfigured()
void DeleteConfigured (CachePeer *const peer)
Definition at line 53 of file CachePeers.cc.
References Assure, Config, SquidConfig::peers, and CachePeers::remove().
Referenced by neighbors_init(), and neighborsUdpAck().