Squid Web Cache: squid/src/CachePeer.h File Reference
CachePeer.h File Reference
#include "acl/forward.h"
#include "base/CbcPointer.h"
#include "base/forward.h"
#include "enums.h"
#include "http/StatusCode.h"
#include "icp_opcode.h"
#include "ip/Address.h"
#include "security/PeerOptions.h"
#include <iosfwd>
Classes
class CachePeer
struct CachePeer::icp_
Functions
void NoteOutgoingConnectionSuccess (CachePeer *const peer)
void NoteOutgoingConnectionFailure (CachePeer *const peer)
std::ostream & operator<< (std::ostream &, const CachePeer &)
identify the given cache peer in cache.log messages and such
Function Documentation
NoteOutgoingConnectionFailure()
void NoteOutgoingConnectionFailure (CachePeer *const peer) inline
reacts to a failed attempt to establish a connection to an origin server or cache_peer
Parameters
peer nil if the connection is to an origin server
Definition at line 246 of file CachePeer.h.
References CachePeer::noteFailure().
Referenced by Security::PeerConnector::countFailingConnection(), HappyConnOpener::handleConnOpenerAnswer(), and PeerPoolMgr::handleOpenedConnection().
NoteOutgoingConnectionSuccess()
void NoteOutgoingConnectionSuccess (CachePeer *const peer) inline
reacts to a successful establishment of a connection to an origin server or cache_peer
Parameters
peer nil if Squid established a connection to an origin server
Definition at line 237 of file CachePeer.h.
References CachePeer::noteSuccess().
Referenced by FwdState::successfullyConnectedToPeer().
operator<<()
std::ostream & operator<< (std::ostream & os, const CachePeer & p)
Definition at line 127 of file CachePeer.cc.
References CachePeer::name.