Squid Web Cache: squid/src/cache_cf.h File Reference
cache_cf.h File Reference
Functions
void configFreeMemory (void)
void self_destruct (void)
void add_http_port (char *portspec)
void parse_int (int *var)
void parse_onoff (int *var)
void parse_eol (char *volatile *var)
void parse_wordlist (wordlist **list)
void requirePathnameExists (const char *name, const char *path)
void parse_time_t (time_t *var)
void parseBytesOptionValue (size_t *bptr, const char *units, char const *value)
Parse bytes number from a string.
Variables
const char * cfg_directive
During parsing, the name of the current squid.conf directive being parsed.
const char * cfg_filename
int config_lineno
char config_input_line [BUFSIZ]
Function Documentation
add_http_port()
void add_http_port (char * portspec)
Definition at line 3698 of file cache_cf.cc.
References assert, HttpPortList, parsePortProtocol(), and parsePortSpecification().
Referenced by mainHandleCommandLineOption().
configFreeMemory()
void configFreeMemory (void)
Definition at line 3900 of file cache_cf.cc.
References Config, SquidConfig::defaultPeerContext, free_all(), Dns::ResolveClientAddressesAsap, SquidConfig::ssl_client, SquidConfig::sslContext_, and Ssl::unloadSquidUntrusted().
Referenced by Configuration::Parse().
parse_eol()
void parse_eol (char *volatile * var)
Definition at line 2886 of file cache_cf.cc.
References ConfigParser::NextQuotedOrToEol(), safe_free, self_destruct(), xisspace, and xstrdup.
parse_int()
void parse_int (int * var)
Definition at line 2528 of file cache_cf.cc.
References GetInteger().
Referenced by parse_obsolete(), and parse_pipelinePrefetch().
parse_onoff()
void parse_onoff (int * var)
Definition at line 2568 of file cache_cf.cc.
References DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::NextToken(), and self_destruct().
Referenced by Auth::SchemeConfig::parse(), parse_configuration_includes_quoted_values(), parse_obsolete(), and parse_YesNoNone().
parse_time_t()
void parse_time_t (time_t * var)
Definition at line 2940 of file cache_cf.cc.
References TexcHere, and ToSBuf().
Referenced by parse_icap_service_failure_limit().
parse_wordlist()
void parse_wordlist (wordlist ** list)
Definition at line 3122 of file cache_cf.cc.
References ConfigParser::NextQuotedToken(), and wordlistAdd().
Referenced by Auth::SchemeConfig::parse(), parse_externalAclHelper(), parse_removalpolicy(), and ConfigParser::ParseWordList().
parseBytesOptionValue()
void parseBytesOptionValue (size_t * bptr, const char * units, char const * value)
Parse bytes from a string. Similar to the parseBytesLine function but parses the string value instead of the current token value.
Definition at line 1383 of file cache_cf.cc.
References String::assign(), parseBytesUnits(), self_destruct(), and xatoi().
Referenced by Security::ServerOptions::parse(), and FormattedLog::parseOptions().
requirePathnameExists()
void requirePathnameExists (const char * name, const char * path)
Definition at line 3914 of file cache_cf.cc.
References assert, BUFSIZ, SquidConfig::chroot_dir, Config, DBG_CRITICAL, debugs, fatalf(), opt_parse_cfg_only, opt_send_signal, and xstrerr().
Referenced by configDoConfigure(), ipcCreate(), and Auth::SchemeConfig::parse().
self_destruct()
void self_destruct (void)
Definition at line 275 of file cache_cf.cc.
References ConfigParser::destruct(), and LegacyParser.
Referenced by ErrorDynamicPageInfo::ErrorDynamicPageInfo(), configDoConfigure(), dump_wccp2_amethod(), dump_wccp2_method(), acl_ip_data::FactoryParse(), GetInteger(), GetInteger64(), GetPercentage(), GetService(), GetShort(), Acl::InnerNode::lineParse(), ConfigParser::NextToken(), Fs::Ufs::UFSSwapDir::optionIOParse(), Store::Disk::optionObjectSizeParse(), DelaySpec::parse(), IcmpConfig::parse(), ACLAdaptationServiceData::parse(), ACLAnnotationData::parse(), ACLCertificateData::parse(), ACLHasComponentData::parse(), ACLIntRange::parse(), ACLSquidErrorData::parse(), ACLTimeData::parse(), ACLExternal::parse(), Security::ServerOptions::parse(), Auth::SchemeConfig::parse(), parse_access_log(), parse_acl_tos(), parse_address(), parse_authparam(), parse_AuthSchemes(), parse_CpuAffinityMap(), parse_eol(), parse_externalAclHelper(), parse_ftp_epsv(), parse_HeaderWithAclList(), parse_hostdomaintype(), parse_icap_service_failure_limit(), parse_IpAddress_list(), parse_memcachemode(), parse_obsolete(), parse_on_unsupported_protocol(), parse_onoff(), parse_peer(), parse_pipelinePrefetch(), parse_port_option(), parse_sslproxy_cert_adapt(), parse_sslproxy_cert_sign(), parse_sslproxy_ssl_bump(), parse_string(), parse_TokenOrQuotedString(), parse_tristate(), parse_uri_whitespace(), parse_UrlHelperTimeout(), parse_wccp2_amethod(), parse_wccp2_method(), parse_wccp2_service(), parse_wccp2_service_info(), ConfigParser::ParseBool(), parseBytesLine(), parseBytesLine64(), parseBytesLineSigned(), parseBytesOptionValue(), ACLHasComponentData::parseComponent(), Helper::ChildConfig::parseConfig(), Log::LogConfig::parseFormats(), XactionInitiator::ParseInitiators(), parseOneConfigFile(), Store::Disk::parseOptions(), parsePortCfg(), parsePortSpecification(), Rock::SwapDir::parseRateOption(), MessageDelayConfig::parseResponseDelayPool(), Rock::SwapDir::parseSizeOption(), Rock::SwapDir::parseTimeOption(), ConfigParser::RegexStrtokFile(), ConfigParser::TokenParse(), ConfigParser::UnQuote(), xatof(), xatoi(), xatol(), xatoll(), and xatos().
Variable Documentation
cfg_directive
const char* cfg_directive extern
Definition at line 269 of file cache_cf.cc.
Referenced by aclParseAclList(), ConfigParser::closeDirective(), HttpUpgradeProtocolAccess::configureGuard(), ConfigParser::CurrentLocation(), ConfigParser::optionalAclList(), parse_acl_access(), parse_ftp_epsv(), parse_port_option(), FormattedLog::parseOptions(), parsePortProtocol(), ConfigParser::rejectDuplicateDirective(), and FormattedLog::setLogformat().
cfg_filename
const char* cfg_filename extern
Definition at line 270 of file cache_cf.cc.
Referenced by aclParseAccessLine(), aclParseArpData(), aclParseDenyInfoLine(), aclParseEuiData(), compileOptimisedREs(), ConfigParser::CurrentLocation(), ConfigParser::destruct(), Adaptation::ServiceConfig::grokBool(), Adaptation::ServiceConfig::grokExtension(), Adaptation::ServiceConfig::grokLong(), Adaptation::ServiceConfig::grokOnOverload(), Adaptation::ServiceConfig::grokUri(), Adaptation::ServiceConfig::parse(), ACLRegexData::parse(), ACLTimeData::parse(), parse_http_header_access(), parse_http_header_replace(), Log::LogConfig::parseFormats(), parseOneConfigFile(), Adaptation::Config::parseService(), removeUnnecessaryWildcards(), and SetConfigFilename().
config_input_line
char config_input_line[BUFSIZ] extern
Definition at line 272 of file cache_cf.cc.
Referenced by aclParseAccessLine(), aclParseAclList(), aclParseArpData(), aclParseDenyInfoLine(), aclParseEuiData(), compileOptimisedREs(), ConfigParser::destruct(), Acl::InnerNode::lineParse(), Acl::AllOf::parse(), ACLRegexData::parse(), ACLTimeData::parse(), parse_http_header_access(), parse_http_header_replace(), parse_icap_service_failure_limit(), ParseAclWithAction(), parseBytesLine(), parseBytesLine64(), parseBytesLineSigned(), Acl::Node::ParseNamed(), parseOneConfigFile(), and removeUnnecessaryWildcards().
config_lineno
int config_lineno extern
Definition at line 271 of file cache_cf.cc.
Referenced by aclParseAccessLine(), aclParseArpData(), aclParseDenyInfoLine(), aclParseEuiData(), compileOptimisedREs(), ConfigParser::CurrentLocation(), ConfigParser::destruct(), Adaptation::ServiceConfig::grokBool(), Adaptation::ServiceConfig::grokExtension(), Adaptation::ServiceConfig::grokLong(), Adaptation::ServiceConfig::grokOnOverload(), Adaptation::ServiceConfig::grokUri(), Adaptation::ServiceConfig::parse(), ACLRegexData::parse(), ACLTimeData::parse(), parse_cachemgrpasswd(), parse_http_header_access(), parse_http_header_replace(), Log::LogConfig::parseFormats(), parseOneConfigFile(), Adaptation::Config::parseService(), and removeUnnecessaryWildcards().