Squid Web Cache: squid/src/carp.cc File Reference
carp.cc File Reference
#include "squid.h"
#include "base/RunnersRegistry.h"
#include "CachePeer.h"
#include "CachePeers.h"
#include "carp.h"
#include "HttpRequest.h"
#include "mgr/Registration.h"
#include "neighbors.h"
#include "PeerSelectState.h"
#include "SquidConfig.h"
#include "Store.h"
#include <cmath>
Classes
class CarpRr
reacts to RegisteredRunner events relevant to this module
Macros
#define ROTATE_LEFT(x, n) (((x) << (n)) | ((x) >> (32-(n))))
Functions
static auto & CarpPeers ()
CARP cache_peers ordered by their CARP weight.
static int peerSortWeight (const void *a, const void *b)
static void carpRegisterWithCacheManager (void)
static void carpInit (void)
DefineRunnerRegistrator (CarpRr)
CachePeer * carpSelectParent (PeerSelector *ps)
static void carpCachemgr (StoreEntry *sentry)
Variables
static OBJH carpCachemgr
Macro Definition Documentation
ROTATE_LEFT
#define ROTATE_LEFT (x, n) (((x) << (n)) | ((x) >> (32-(n))))
Definition at line 25 of file carp.cc.
Function Documentation
carpCachemgr()
static void carpCachemgr (StoreEntry * sentry) static
Definition at line 227 of file carp.cc.
References CarpPeers(), and storeAppendPrintf().
carpInit()
static void carpInit (void) static
Definition at line 52 of file carp.cc.
References assert, CarpPeers(), carpRegisterWithCacheManager(), CurrentCachePeers(), double, int, PEER_PARENT, peerSortWeight(), and ROTATE_LEFT.
Referenced by CarpRr::syncConfig(), and CarpRr::useConfig().
CarpPeers()
static auto & CarpPeers () static
Definition at line 29 of file carp.cc.
Referenced by carpCachemgr(), carpInit(), and carpSelectParent().
carpRegisterWithCacheManager()
static void carpRegisterWithCacheManager (void) static
Definition at line 46 of file carp.cc.
References carpCachemgr, and Mgr::RegisterAction().
Referenced by carpInit().
carpSelectParent()
CachePeer * carpSelectParent (PeerSelector * ps)
Definition at line 150 of file carp.cc.
References AnyP::Uri::absolutePath(), SBuf::append(), SBuf::appendf(), assert, CarpPeers(), debugs, HttpRequest::effectiveRequestUri(), SBuf::find(), AnyP::Uri::getScheme(), AnyP::Uri::host(), AnyP::UriScheme::image(), SBuf::isEmpty(), SBuf::length(), SBuf::npos, peerHTTPOkay(), AnyP::Uri::port(), SBuf::rawContent(), PeerSelector::request, ROTATE_LEFT, SBuf::substr(), and HttpRequest::url.
Referenced by PeerSelector::selectSomeParent().
DefineRunnerRegistrator()
DefineRunnerRegistrator (CarpRr)
peerSortWeight()
static int peerSortWeight (const void * a, const void * b) static
Definition at line 38 of file carp.cc.
References CachePeer::weight.
Referenced by carpInit().
Variable Documentation
carpCachemgr
OBJH carpCachemgr static
Definition at line 35 of file carp.cc.
Referenced by carpRegisterWithCacheManager().