Squid Web Cache: squid/src/ssl/cert_validate_message.cc File Reference
cert_validate_message.cc File Reference
#include "squid.h"
#include "acl/FilledChecklist.h"
#include "globals.h"
#include "helper.h"
#include "sbuf/Stream.h"
#include "security/CertError.h"
#include "ssl/cert_validate_message.h"
#include "ssl/ErrorDetail.h"
#include "ssl/support.h"
#include "util.h"
Functions
static STACK_OF (X509) *PeerValidationCertificatesChain(const Security
static int get_error_id (const char *label, size_t len)
Function Documentation
get_error_id()
static int get_error_id (const char * label, size_t len) static
Definition at line 84 of file cert_validate_message.cc.
References xisdigit.
Referenced by Ssl::CertValidationMsg::tryParsingResponse().
STACK_OF()
static STACK_OF (X509) const static
Retrieves the certificates chain used to verify the peer. This is the full chain built by OpenSSL while verifying the server certificate or, if this is not available, the chain sent by server.
Returns
the certificates chain or nil
Last resort: certificates chain sent by server
Definition at line 24 of file cert_validate_message.cc.
References assert, ssl_ex_index_ssl_cert_chain, and STACK_OF().
Referenced by STACK_OF().