Squid Web Cache: squid/src/acl/external/unix_group/check_group.cc File Reference
check_group.cc File Reference
#include "squid.h"
#include "helper/protocol_defines.h"
#include "rfc1738.h"
#include "util.h"
#include <cctype>
#include <cstring>
Functions
static int validate_user_pw (char *username, char *groupname)
static int validate_user_gr (char *username, char *groupname)
static void usage (char *program)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 148 of file check_group.cc.
References debug_enabled, getopt(), HELPER_INPUT_BUFFER, HLP_MSG, optarg, optind, optopt, rfc1738_unescape(), SEND_BH, SEND_ERR, SEND_OK, usage(), validate_user_gr(), validate_user_pw(), and xisprint.
usage()
static void usage (char * program) static
Definition at line 130 of file check_group.cc.
validate_user_gr()
static int validate_user_gr (char * username, char * groupname) static
Definition at line 108 of file check_group.cc.
Referenced by main().
validate_user_pw()
static int validate_user_pw (char * username, char * groupname) static
Definition at line 87 of file check_group.cc.
Referenced by main().