Squid Web Cache: Adaptation::Icap::ModXact Class Reference
Adaptation::Icap::ModXact Class Reference abstract
#include <ModXact.h>
Classes
class State
Public Types
typedef CbcPointer< AsyncJob > Pointer
typedef CbcPointer< BodyProducer > Pointer
typedef CbcPointer< BodyConsumer > Pointer
Public Member Functions
ModXact (Http::Message *virginHeader, HttpRequest *virginCause, AccessLogEntry::Pointer &alp, ServiceRep::Pointer &s)
~ModXact () override
void noteMoreBodySpaceAvailable (BodyPipe::Pointer) override
void noteBodyConsumerAborted (BodyPipe::Pointer) override
void noteMoreBodyDataAvailable (BodyPipe::Pointer) override
void noteBodyProductionEnded (BodyPipe::Pointer) override
void noteBodyProducerAborted (BodyPipe::Pointer) override
void startShoveling () override
starts sending/receiving ICAP messages
void handleCommWrote (size_t size) override
void handleCommRead (size_t size) override
void handleCommWroteHeaders ()
void handleCommWroteBody ()
void noteServiceReady ()
void noteServiceAvailable ()
void callException (const std::exception &e) override
called when the job throws during an async call
void detailError (const ErrorDetail::Pointer &errDetail) override
record error detail in the virgin request if possible
void clearError () override
clear stored error details, if any; used for retries/repeats
AccessLogEntry::Pointer masterLogEntry () override
The master transaction log entry.
void disableRetries ()
void disableRepeats (const char *reason)
bool retriable () const
bool repeatable () const
void noteCommConnected (const CommConnectCbParams &io)
called when the connection attempt to an ICAP service completes (successfully or not)
void noteCommWrote (const CommIoCbParams &io)
void noteCommRead (const CommIoCbParams &io)
void noteCommTimedout (const CommTimeoutCbParams &io)
void noteCommClosed (const CommCloseCbParams &io)
void callEnd () override
called right after the called job method
void dnsLookupDone (std::optional< Ip::Address >)
ServiceRep & service ()
void initiator (const CbcPointer< Initiator > &i)
sets initiator
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
InOut virgin
InOut adapted
HttpRequest * icapRequest
sent (or at least created) ICAP request
HttpReply::Pointer icapReply
received ICAP reply, if any
int attempts
the number of times we tried to get to the service, including this time
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void noteInitiatorAborted () override
void handleSecuredPeer (Security::EncryptorAnswer &answer)
void openConnection ()
void closeConnection ()
bool haveConnection () const
void scheduleRead ()
void scheduleWrite (MemBuf &buf)
void updateTimeout ()
void cancelRead ()
bool parseHttpMsg (Http::Message *msg)
bool mayReadMore () const
bool doneWithIo () const
const char * status () const override
internal cleanup; do not call directly
void setOutcome (const XactOutcome &xo)
void tellQueryAborted (bool final)
void sendAnswer (const Answer &answer)
void clearInitiator ()
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
void stopProducingFor (RefCount< BodyPipe > &, bool atEof)
void stopConsumingFrom (RefCount< BodyPipe > &)
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
Adaptation::Icap::ServiceRep::Pointer theService
SBuf readBuf
bool commEof
bool reuseConnection
bool isRetriable
can retry on persistent connection failures
bool isRepeatable
can repeat if no or unsatisfactory response
bool ignoreLastWrite
bool waitingForDns
expecting a ipcache_nbgethostbyname() callback
AsyncCall::Pointer reader
AsyncCall::Pointer writer
AccessLogEntry::Pointer alep
icap.log entry
AccessLogEntry & al
short for *alep
timeval icap_tr_start
timeval icap_tio_start
timeval icap_tio_finish
CbcPointer< Initiator > theInitiator
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
CBDATA_CHILD (ModXact)
void start () override
called by AsyncStart; do not call directly
const HttpRequest & virginRequest () const
locates the request, either as a cause or as a virgin message itself
void estimateVirginBody ()
void makeAdaptedBodyPipe (const char *what)
void waitForService ()
bool doneSending () const
void startWriting ()
void writeMore ()
void writePreviewBody ()
void writePrimeBody ()
void writeSomeBody (const char *label, size_t size)
void decideWritingAfterPreview (const char *previewKind)
determine state.writing after we wrote the entire preview
void startReading ()
void readMore ()
bool doneReading () const override
bool doneWriting () const override
size_t virginContentSize (const VirginBodyAct &act) const
const char * virginContentData (const VirginBodyAct &act) const
bool virginBodyEndReached (const VirginBodyAct &act) const
void makeRequestHeaders (MemBuf &buf)
void makeAllowHeader (MemBuf &buf)
void makeUsernameHeader (const HttpRequest *request, MemBuf &buf)
void addLastRequestChunk (MemBuf &buf)
void openChunk (MemBuf &buf, size_t chunkSize, bool ieof)
void closeChunk (MemBuf &buf)
void virginConsume ()
void finishNullOrEmptyBodyPreview (MemBuf &buf)
void decideOnPreview ()
void decideOnRetries ()
bool shouldAllow204 ()
bool shouldAllow206any ()
bool shouldAllow206in ()
bool shouldAllow206out ()
bool canBackupEverything () const
void prepBackup (size_t expectedSize)
void backup (const MemBuf &buf)
void parseMore ()
void parseHeaders ()
void parseIcapHead ()
void parseHttpHead ()
bool parseHead (Http::Message *head)
void decideOnParsingBody ()
void parseBody ()
void parseIcapTrailer ()
void maybeAllocateHttpMsg ()
void handle100Continue ()
bool validate200Ok ()
void handle200Ok ()
void handle204NoContent ()
void handle206PartialContent ()
void handleUnknownScode ()
void bypassFailure ()
void startSending ()
void disableBypass (const char *reason, bool includeGroupBypass)
void prepEchoing ()
void prepPartialBodyEchoing (uint64_t pos)
void echoMore ()
void updateSources ()
Update the Http::Message sources.
bool doneAll () const override
whether positive goal has been reached
void swanSong () override
void stopReceiving ()
void stopSending (bool nicely)
void stopWriting (bool nicely)
void stopParsing (const bool checkUnparsedData=true)
void stopBackup ()
void fillPendingStatus (MemBuf &buf) const override
void fillDoneStatus (MemBuf &buf) const override
bool fillVirginHttpHeader (MemBuf &) const override
template<class Part >
bool parsePart (Part *part, const char *description)
void packHead (MemBuf &httpBuf, const Http::Message *head)
void encapsulateHead (MemBuf &icapBuf, const char *section, MemBuf &httpBuf, const Http::Message *head)
bool gotEncapsulated (const char *section) const
bool expectHttpHeader () const
whether ICAP response header indicates HTTP header presence
bool expectHttpBody () const
whether ICAP response header indicates HTTP body presence
bool expectIcapTrailers () const
whether ICAP response header indicates ICAP trailers presence
void checkConsuming ()
void finalizeLogInfo () override
void useTransportConnection (const Comm::ConnectionPointer &)
void useIcapConnection (const Comm::ConnectionPointer &)
react to the availability of a fully-ready ICAP connection
void dieOnConnectionFailure ()
void tellQueryAborted ()
void maybeLog ()
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
SizedEstimate virginBody
VirginBodyAct virginBodyWriting
VirginBodyAct virginBodySending
uint64_t virginConsumed
Preview preview
Http1::TeChunkedParser * bodyParser
bool canStartBypass
bool protectGroupBypass
int64_t replyHttpHeaderSize
int64_t replyHttpBodySize
int adaptHistoryId
adaptation history slot reservation
TrailerParser * trailerParser
ChunkExtensionValueParser extensionParser
class Adaptation::Icap::ModXact::State state
AccessLogEntry::Pointer alMaster
Master transaction AccessLogEntry.
JobWait< Comm::ConnOpener > transportWait
waits for a transport connection to the ICAP server to be established/opened
JobWait< Ssl::IcapPeerConnector > encryptionWait
waits for the established transport connection to be secured/encrypted
Comm::ConnectionPointer connection
open and, if necessary, secured connection to the ICAP server (or nil)
AsyncCall::Pointer closer
Detailed Description
Definition at line 141 of file ModXact.h.
Member Typedef Documentation
Pointer [1/3]
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Pointer [2/3]
typedef CbcPointer<BodyProducer> BodyProducer::Pointer inherited
Definition at line 25 of file BodyPipe.h.
Pointer [3/3]
typedef CbcPointer<BodyConsumer> BodyConsumer::Pointer inherited
Definition at line 45 of file BodyPipe.h.
Constructor & Destructor Documentation
ModXact()
Adaptation::Icap::ModXact::ModXact (Http::Message * virginHeader, HttpRequest * virginCause, AccessLogEntry::Pointer & alp, ServiceRep::Pointer & s)
Definition at line 54 of file ModXact.cc.
References assert, debugs, Adaptation::Icap::Xaction::icapReply, HttpReply::protoPrefix, Adaptation::Icap::InOut::setCause(), Adaptation::Icap::InOut::setHeader(), Adaptation::Icap::Xaction::status(), and virgin.
~ModXact()
Adaptation::Icap::ModXact::~ModXact () override
Definition at line 1282 of file ModXact.cc.
Member Function Documentation
addLastRequestChunk()
void Adaptation::Icap::ModXact::addLastRequestChunk (MemBuf & buf) private
Definition at line 369 of file ModXact.cc.
backup()
void Adaptation::Icap::ModXact::backup (const MemBuf & buf) private
bypassFailure()
void Adaptation::Icap::ModXact::bypassFailure () private
Definition at line 687 of file ModXact.cc.
References debugs, and Must.
callEnd()
void Adaptation::Icap::Xaction::callEnd () override virtual inherited
called right after the called job method
Reimplemented from AsyncJob.
Definition at line 379 of file Xaction.cc.
References AsyncJob::callEnd(), and debugs.
callException()
void Adaptation::Icap::ModXact::callException (const std::exception & e) override virtual
Reimplemented from AsyncJob.
Definition at line 661 of file ModXact.cc.
References Adaptation::Icap::Xaction::callException(), debugs, Here, and TextException::id().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBackupEverything()
bool Adaptation::Icap::ModXact::canBackupEverything () const private
Definition at line 1689 of file ModXact.cc.
References TheBackupLimit.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
cancelRead()
void Adaptation::Icap::Xaction::cancelRead () protected inherited
Definition at line 487 of file Xaction.cc.
References Must, and Comm::ReadCancel().
CBDATA_CHILD()
Adaptation::Icap::ModXact::CBDATA_CHILD (ModXact) private
checkConsuming()
void Adaptation::Icap::ModXact::checkConsuming () private
Definition at line 636 of file ModXact.cc.
References debugs.
clearError()
void Adaptation::Icap::ModXact::clearError () override virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 1999 of file ModXact.cc.
References HttpRequest::clearError().
clearInitiator()
void Adaptation::Initiate::clearInitiator () protected inherited
Definition at line 74 of file Initiate.cc.
closeChunk()
void Adaptation::Icap::ModXact::closeChunk (MemBuf & buf) private
Definition at line 381 of file ModXact.cc.
References MemBuf::append().
closeConnection()
void Adaptation::Icap::Xaction::closeConnection () protected inherited
Definition at line 218 of file Xaction.cc.
References comm_remove_close_handler(), commUnsetConnTimeout(), debugs, Adaptation::Icap::xoError, and Adaptation::Icap::xoGone.
decideOnParsingBody()
void Adaptation::Icap::ModXact::decideOnParsingBody () private
Definition at line 1137 of file ModXact.cc.
References debugs, Must, and Http::One::TeChunkedParser::parseExtensionValuesWith().
decideOnPreview()
void Adaptation::Icap::ModXact::decideOnPreview () private
Definition at line 1630 of file ModXact.cc.
References debugs, min(), Must, Adaptation::Icap::Config::preview_enable, TheBackupLimit, and Adaptation::Icap::TheConfig.
decideOnRetries()
void Adaptation::Icap::ModXact::decideOnRetries () private
Definition at line 1706 of file ModXact.cc.
decideWritingAfterPreview()
void Adaptation::Icap::ModXact::decideWritingAfterPreview (const char * previewKind) private
Definition at line 292 of file ModXact.cc.
References debugs.
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
detailError()
void Adaptation::Icap::ModXact::detailError (const ErrorDetail::Pointer & errDetail) override virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 1987 of file ModXact.cc.
References HttpRequest::detailError(), and ERR_ICAP_FAILURE.
dieOnConnectionFailure()
void Adaptation::Icap::Xaction::dieOnConnectionFailure () private inherited
Definition at line 306 of file Xaction.cc.
References debugs, MakeNamedErrorDetail(), and TexcHere.
Referenced by Adaptation::Icap::Xaction::dnsLookupDone().
disableBypass()
void Adaptation::Icap::ModXact::disableBypass (const char * reason, bool includeGroupBypass) private
Definition at line 713 of file ModXact.cc.
References debugs.
disableRepeats()
void Adaptation::Icap::Xaction::disableRepeats (const char * reason) inherited
Definition at line 123 of file Xaction.cc.
References debugs.
Referenced by Adaptation::Icap::Launcher::launchXaction().
disableRetries()
void Adaptation::Icap::Xaction::disableRetries () inherited
Definition at line 116 of file Xaction.cc.
References debugs.
Referenced by Adaptation::Icap::Launcher::launchXaction().
dnsLookupDone()
void Adaptation::Icap::Xaction::dnsLookupDone (std::optional< Ip::Address > addr) inherited
Definition at line 187 of file Xaction.cc.
References assert, CallJobHere, Adaptation::Service::cfg(), Adaptation::Icap::Config::connect_timeout(), DBG_IMPORTANT, debugs, Adaptation::Icap::Xaction::dieOnConnectionFailure(), getOutgoingAddress(), Adaptation::ServiceConfig::host, JobCallback, Adaptation::Icap::Xaction::noteCommConnected(), Adaptation::ServiceConfig::port, Ip::Address::port(), Comm::Connection::remote, String::termedBuf(), and Adaptation::Icap::TheConfig.
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Adaptation::Icap::ModXact::doneAll () const override private virtual
Reimplemented from AsyncJob.
Definition at line 524 of file ModXact.cc.
References Adaptation::Icap::Xaction::doneAll().
doneReading()
bool Adaptation::Icap::ModXact::doneReading () const inline override private virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 207 of file ModXact.h.
References Adaptation::Icap::Xaction::commEof, Adaptation::Icap::ModXact::State::doneParsing(), and state.
doneSending()
bool Adaptation::Icap::ModXact::doneSending () const private
Definition at line 604 of file ModXact.cc.
doneWithIo()
bool Adaptation::Icap::Xaction::doneWithIo () const protected inherited
Definition at line 533 of file Xaction.cc.
doneWriting()
bool Adaptation::Icap::ModXact::doneWriting () const inline override private virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 208 of file ModXact.h.
References Adaptation::Icap::ModXact::State::doneWriting(), and state.
echoMore()
void Adaptation::Icap::ModXact::echoMore () private
Definition at line 571 of file ModXact.cc.
References debugs, Must, and size.
encapsulateHead()
void Adaptation::Icap::ModXact::encapsulateHead (MemBuf & icapBuf, const char * section, MemBuf & httpBuf, const Http::Message * head) private
Definition at line 1577 of file ModXact.cc.
References HttpHeader::addEntry(), Packable::appendf(), MemBuf::contentSize(), HttpHeader::delById(), RefCount< C >::getRaw(), head, Http::Message::header, Http::Message::http_ver, HttpHeaderInitPos, Http::Message::inheritProperties(), HttpRequest::method, Must, Http::PROXY_AUTHENTICATE, HttpHeader::putStr(), HttpHeader::removeHopByHopEntries(), HttpReply::sline, Http::UPGRADE, and HttpRequest::url.
estimateVirginBody()
void Adaptation::Icap::ModXact::estimateVirginBody () private
Definition at line 1814 of file ModXact.cc.
References Http::Message::body_pipe, BodyPipe::buf(), debugs, Http::Message::expectingBody(), Http::Message::header, MemBuf::max_capacity, Http::METHOD_NONE, Must, size, and TheBackupLimit.
expectHttpBody()
bool Adaptation::Icap::ModXact::expectHttpBody () const private
Definition at line 1119 of file ModXact.cc.
expectHttpHeader()
bool Adaptation::Icap::ModXact::expectHttpHeader () const private
Definition at line 1114 of file ModXact.cc.
expectIcapTrailers()
bool Adaptation::Icap::ModXact::expectIcapTrailers () const private
Definition at line 1124 of file ModXact.cc.
References Http::ALLOW, DBG_IMPORTANT, debugs, Must, String::size(), and Http::TRAILER.
fillDoneStatus()
void Adaptation::Icap::ModXact::fillDoneStatus (MemBuf & buf) const override private virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 1780 of file ModXact.cc.
References MemBuf::append(), Packable::appendf(), and Adaptation::Icap::Xaction::fillDoneStatus().
fillPendingStatus()
void Adaptation::Icap::ModXact::fillPendingStatus (MemBuf & buf) const override private virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 1740 of file ModXact.cc.
References MemBuf::append(), Packable::appendf(), and Adaptation::Icap::Xaction::fillPendingStatus().
fillVirginHttpHeader()
bool Adaptation::Icap::ModXact::fillVirginHttpHeader (MemBuf & mb) const override private virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 1977 of file ModXact.cc.
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
finalizeLogInfo()
void Adaptation::Icap::ModXact::finalizeLogInfo () override private virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 1311 of file ModXact.cc.
References assert, Http::Message::body_pipe, Adaptation::Service::cfg(), HttpRequest::client_addr, HttpReply::content_type, Adaptation::Icap::Xaction::finalizeLogInfo(), Http::Message::hdr_sz, HTTPMSGLOCK(), HttpRequest::icapHistory(), ICP_INVALID, Adaptation::Icap::History::log_uri, Adaptation::Icap::History::logType, max(), Adaptation::ServiceConfig::method, Must, prepareLogWithRequestDetails(), BodyPipe::producedSize(), String::size(), HttpReply::sline, Adaptation::Icap::History::ssluser, Http::StatusLine::status(), String::termedBuf(), and zero.
finishNullOrEmptyBodyPreview()
void Adaptation::Icap::ModXact::finishNullOrEmptyBodyPreview (MemBuf & buf) private
Definition at line 1726 of file ModXact.cc.
References Must.
gotEncapsulated()
bool Adaptation::Icap::ModXact::gotEncapsulated (const char * section) const private
Definition at line 1805 of file ModXact.cc.
handle100Continue()
void Adaptation::Icap::ModXact::handle100Continue () private
Definition at line 892 of file ModXact.cc.
References Must.
handle200Ok()
void Adaptation::Icap::ModXact::handle200Ok () private
Definition at line 911 of file ModXact.cc.
handle204NoContent()
void Adaptation::Icap::ModXact::handle204NoContent () private
Definition at line 919 of file ModXact.cc.
handle206PartialContent()
void Adaptation::Icap::ModXact::handle206PartialContent () private
Definition at line 925 of file ModXact.cc.
References debugs, and Must.
handleCommRead()
void Adaptation::Icap::ModXact::handleCommRead (size_t size) override virtual
Implements Adaptation::Icap::Xaction.
Definition at line 563 of file ModXact.cc.
References current_time, and Must.
handleCommWrote()
void Adaptation::Icap::ModXact::handleCommWrote (size_t size) override virtual
Implements Adaptation::Icap::Xaction.
Definition at line 208 of file ModXact.cc.
References debugs.
handleCommWroteBody()
void Adaptation::Icap::ModXact::handleCommWroteBody ()
Definition at line 474 of file ModXact.cc.
handleCommWroteHeaders()
void Adaptation::Icap::ModXact::handleCommWroteHeaders ()
Definition at line 218 of file ModXact.cc.
References Must.
handleSecuredPeer()
void Adaptation::Icap::Xaction::handleSecuredPeer (Security::EncryptorAnswer & answer) protected inherited
Definition at line 717 of file Xaction.cc.
References assert, Security::EncryptorAnswer::conn, debugs, Security::EncryptorAnswer::error, Comm::Connection::fd, fd_table, CbcPointer< Cbc >::get(), Comm::Connection::isOpen(), MakeNamedErrorDetail(), Comm::Connection::noteClosure(), TexcHere, and Security::EncryptorAnswer::tunneled.
Referenced by Adaptation::Icap::Xaction::useTransportConnection().
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
handleUnknownScode()
void Adaptation::Icap::ModXact::handleUnknownScode () private
Definition at line 1047 of file ModXact.cc.
References TexcHere.
haveConnection()
bool Adaptation::Icap::Xaction::haveConnection () const protected inherited
Definition at line 540 of file Xaction.cc.
initiator()
void Adaptation::Initiate::initiator (const CbcPointer< Initiator > & i) inherited
Definition at line 54 of file Initiate.cc.
References Must, and CbcPointer< Cbc >::valid().
Referenced by Adaptation::Initiator::initiateAdaptation().
makeAdaptedBodyPipe()
void Adaptation::Icap::ModXact::makeAdaptedBodyPipe (const char * what) private
Definition at line 1854 of file ModXact.cc.
References debugs, and Must.
makeAllowHeader()
void Adaptation::Icap::ModXact::makeAllowHeader (MemBuf & buf) private
Definition at line 1515 of file ModXact.cc.
References Packable::appendf(), and debugs.
makeRequestHeaders()
void Adaptation::Icap::ModXact::makeRequestHeaders (MemBuf & buf) private
Definition at line 1375 of file ModXact.cc.
References HttpRequest::adaptHistory(), NotePairs::add(), MemBuf::append(), Packable::appendf(), base64_encode_final(), base64_encode_init(), base64_encode_len, base64_encode_update(), MemBuf::clean(), HttpRequest::client_addr, MemBuf::content(), MemBuf::contentSize(), HttpRequest::extacl_passwd, HttpRequest::extacl_user, Time::FormatRfc1123(), Adaptation::History::getXxRecord(), NotePairs::hasPair(), Http::Message::header, Adaptation::ServiceConfig::host, HttpRequest::indirect_client_addr, MemBuf::init(), Ip::Address::isAnyAddr(), Ip::Address::isNoAddr(), SBuf::length(), Adaptation::Config::masterx_shared_name, MAX_IPSTRLEN, MAX_LOGIN_SZ, Adaptation::Config::metaHeaders(), Adaptation::History::metaHeaders, Adaptation::ServiceConfig::method, Adaptation::ServiceConfig::methodStr(), Must, Adaptation::ServiceConfig::port, Http::PROXY_AUTHENTICATE, Http::PROXY_AUTHORIZATION, String::rawBuf(), SBuf::rawContent(), Adaptation::Icap::Config::reuse_connections, Adaptation::Config::send_client_ip, Adaptation::Config::send_username, String::size(), squid_curtime, SQUIDSTRINGPH, SQUIDSTRINGPRINT, Adaptation::Icap::TheConfig, Ip::Address::toStr(), Adaptation::ServiceConfig::uri, and Adaptation::Config::use_indirect_client.
makeUsernameHeader()
void Adaptation::Icap::ModXact::makeUsernameHeader (const HttpRequest * request, MemBuf & buf) private
Definition at line 1548 of file ModXact.cc.
References Packable::appendf(), HttpRequest::auth_user_request, base64_encode_final(), base64_encode_init(), base64_encode_len, base64_encode_update(), Adaptation::Icap::Config::client_username_encode, Adaptation::Icap::Config::client_username_header, HttpRequest::extacl_user, MAX_LOGIN_SZ, String::size(), String::termedBuf(), Adaptation::Icap::TheConfig, and Auth::UserRequest::username().
masterLogEntry()
AccessLogEntry::Pointer Adaptation::Icap::ModXact::masterLogEntry () inline override virtual
Reimplemented from Adaptation::Icap::Xaction.
Definition at line 182 of file ModXact.h.
References alMaster.
maybeAllocateHttpMsg()
void Adaptation::Icap::ModXact::maybeAllocateHttpMsg () private
Definition at line 726 of file ModXact.cc.
References TexcHere, Adaptation::Icap::xoModified, and Adaptation::Icap::xoSatisfied.
maybeLog()
void Adaptation::Icap::Xaction::maybeLog () private inherited
Definition at line 604 of file Xaction.cc.
References IcapLogfileStatus, icapLogLog(), and LOG_ENABLE.
mayReadMore()
bool Adaptation::Icap::Xaction::mayReadMore () const protected inherited
Definition at line 517 of file Xaction.cc.
References SQUID_TCP_SO_RCVBUF.
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteBodyConsumerAborted()
void Adaptation::Icap::ModXact::noteBodyConsumerAborted (BodyPipe::Pointer) override virtual
Implements BodyProducer.
Definition at line 1275 of file ModXact.cc.
References MakeNamedErrorDetail().
noteBodyProducerAborted()
void Adaptation::Icap::ModXact::noteBodyProducerAborted (BodyPipe::Pointer) override virtual
Implements BodyConsumer.
Definition at line 1251 of file ModXact.cc.
References Must.
noteBodyProductionEnded()
void Adaptation::Icap::ModXact::noteBodyProductionEnded (BodyPipe::Pointer) override virtual
Implements BodyConsumer.
Definition at line 1238 of file ModXact.cc.
References Must.
noteCommClosed()
void Adaptation::Icap::Xaction::noteCommClosed (const CommCloseCbParams & io) inherited
Definition at line 359 of file Xaction.cc.
References MakeNamedErrorDetail().
Referenced by Adaptation::Icap::Xaction::useIcapConnection().
noteCommConnected()
void Adaptation::Icap::Xaction::noteCommConnected (const CommConnectCbParams & io) inherited
Definition at line 253 of file Xaction.cc.
References CommCommonCbParams::conn, CommCommonCbParams::flag, and Comm::OK.
Referenced by Adaptation::Icap::Xaction::dnsLookupDone().
noteCommRead()
void Adaptation::Icap::Xaction::noteCommRead (const CommIoCbParams & io) inherited
Definition at line 426 of file Xaction.cc.
References CommCommonCbParams::conn, debugs, Comm::ENDFILE, CommCommonCbParams::flag, Comm::INPROGRESS, Must, Comm::OK, Comm::ReadNow(), CommIoCbParams::size, SQUID_TCP_SO_RCVBUF, CommCommonCbParams::xerrno, Adaptation::Icap::xoRace, and xstrerr().
Referenced by Adaptation::Icap::Xaction::scheduleRead().
noteCommTimedout()
void Adaptation::Icap::Xaction::noteCommTimedout (const CommTimeoutCbParams & io) inherited
Definition at line 347 of file Xaction.cc.
References assert, debugs, and Here.
Referenced by Adaptation::Icap::Xaction::updateTimeout().
noteCommWrote()
void Adaptation::Icap::Xaction::noteCommWrote (const CommIoCbParams & io) inherited
Definition at line 329 of file Xaction.cc.
References debugs, CommCommonCbParams::flag, Must, Comm::OK, and CommIoCbParams::size.
Referenced by Adaptation::Icap::Xaction::scheduleWrite().
noteInitiatorAborted()
void Adaptation::Icap::Xaction::noteInitiatorAborted () override protected virtual inherited
Implements Adaptation::Initiate.
Definition at line 546 of file Xaction.cc.
References debugs, MakeNamedErrorDetail(), and Adaptation::Icap::xoGone.
noteMoreBodyDataAvailable()
void Adaptation::Icap::ModXact::noteMoreBodyDataAvailable (BodyPipe::Pointer) override virtual
Implements BodyConsumer.
Definition at line 1229 of file ModXact.cc.
noteMoreBodySpaceAvailable()
void Adaptation::Icap::ModXact::noteMoreBodySpaceAvailable (BodyPipe::Pointer) override virtual
Implements BodyProducer.
Definition at line 1264 of file ModXact.cc.
References Must.
noteServiceAvailable()
void Adaptation::Icap::ModXact::noteServiceAvailable ()
Definition at line 168 of file ModXact.cc.
References Must.
Referenced by waitForService().
noteServiceReady()
void Adaptation::Icap::ModXact::noteServiceReady ()
Definition at line 151 of file ModXact.cc.
References Must, and TexcHere.
Referenced by waitForService().
openChunk()
void Adaptation::Icap::ModXact::openChunk (MemBuf & buf, size_t chunkSize, bool ieof) private
Definition at line 376 of file ModXact.cc.
References Packable::appendf().
openConnection()
void Adaptation::Icap::Xaction::openConnection () protected inherited
Definition at line 161 of file Xaction.cc.
References assert, Adaptation::Service::cfg(), debugs, Adaptation::Icap::ServiceRep::getIdleConnection(), Adaptation::ServiceConfig::host, icapLookupDnsResults(), ipcache_nbgethostbyname(), Must, Adaptation::ServiceConfig::port, Adaptation::Icap::Config::reuse_connections, String::termedBuf(), and Adaptation::Icap::TheConfig.
packHead()
void Adaptation::Icap::ModXact::packHead (MemBuf & httpBuf, const Http::Message * head) private
Definition at line 1624 of file ModXact.cc.
References head.
parseBody()
void Adaptation::Icap::ModXact::parseBody () private
Definition at line 1157 of file ModXact.cc.
References BodyPipeCheckout::buf, BodyPipeCheckout::checkIn(), debugs, and Must.
parseHead()
bool Adaptation::Icap::ModXact::parseHead (Http::Message * head) private
Definition at line 1105 of file ModXact.cc.
References head.
parseHeaders()
void Adaptation::Icap::ModXact::parseHeaders () private
Definition at line 742 of file ModXact.cc.
References debugs, and Must.
parseHttpHead()
void Adaptation::Icap::ModXact::parseHttpHead () private
Definition at line 1057 of file ModXact.cc.
References Must.
parseHttpMsg()
bool Adaptation::Icap::Xaction::parseHttpMsg (Http::Message * msg) protected inherited
Definition at line 497 of file Xaction.cc.
References debugs, error(), Http::Message::hdr_sz, Must, Http::Message::parse(), Http::Message::reset(), and Http::scNone.
parseIcapHead()
void Adaptation::Icap::ModXact::parseIcapHead () private
Definition at line 785 of file ModXact.cc.
References HttpRequest::adaptHistory(), HttpRequest::adaptLogHistory(), debugs, httpHeaderHasConnDir(), Adaptation::Config::masterx_shared_name, Must, Adaptation::History::recordMeta(), Http::scContinue, Http::scCreated, Http::scNoContent, Http::scOkay, Http::scPartialContent, String::size(), TexcHere, Adaptation::History::updateNextServices(), Adaptation::History::updateXxRecord(), and Http::X_NEXT_SERVICES.
parseIcapTrailer()
void Adaptation::Icap::ModXact::parseIcapTrailer () private
Parses ICAP trailers and stops parsing, if all trailer data have been received.
Definition at line 874 of file ModXact.cc.
References debugs.
parseMore()
void Adaptation::Icap::ModXact::parseMore () private
Definition at line 646 of file ModXact.cc.
References debugs.
parsePart()
template<class Part > bool Adaptation::Icap::ModXact::parsePart (Part * part, const char * description) private
parses a message header or trailer
Returns
true on success
false if more data is needed
Exceptions
TextException on unrecoverable error
Definition at line 1087 of file ModXact.cc.
References debugs, error(), Must, and Http::scNone.
prepBackup()
void Adaptation::Icap::ModXact::prepBackup (size_t expectedSize) private
prepEchoing()
void Adaptation::Icap::ModXact::prepEchoing () private
Definition at line 945 of file ModXact.cc.
References Http::Message::body_pipe, BodyPipe::bodySize(), BodyPipe::bodySizeKnown(), MemBuf::clean(), MemBuf::content(), MemBuf::contentSize(), debugs, error(), RefCount< C >::getRaw(), Http::Message::header, Http::Message::inheritProperties(), MemBuf::init(), Must, Http::scNone, MemBuf::terminate(), and Adaptation::Icap::xoEcho.
prepPartialBodyEchoing()
void Adaptation::Icap::ModXact::prepPartialBodyEchoing (uint64_t pos) private
Called when we received use-original-body chunk extension in 206 response. We actually start sending (echoing or not) in startSending().
Definition at line 1018 of file ModXact.cc.
References debugs, Must, and Adaptation::Icap::xoPartEcho.
readMore()
void Adaptation::Icap::ModXact::readMore () private
Definition at line 542 of file ModXact.cc.
References debugs, and SQUID_TCP_SO_RCVBUF.
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
repeatable()
bool Adaptation::Icap::Xaction::repeatable () const inline inherited
Definition at line 53 of file Xaction.h.
References Adaptation::Icap::Xaction::isRepeatable.
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
retriable()
bool Adaptation::Icap::Xaction::retriable () const inline inherited
Definition at line 52 of file Xaction.h.
References Adaptation::Icap::Xaction::isRetriable.
scheduleRead()
void Adaptation::Icap::Xaction::scheduleRead () protected inherited
Definition at line 413 of file Xaction.cc.
References JobCallback, Must, Adaptation::Icap::Xaction::noteCommRead(), Comm::Read(), and SQUID_TCP_SO_RCVBUF.
scheduleWrite()
void Adaptation::Icap::Xaction::scheduleWrite (MemBuf & buf) protected inherited
Definition at line 316 of file Xaction.cc.
References JobCallback, Must, Adaptation::Icap::Xaction::noteCommWrote(), and Comm::Write().
sendAnswer()
void Adaptation::Initiate::sendAnswer (const Answer & answer) protected inherited
Definition at line 79 of file Initiate.cc.
References Adaptation::Initiator::noteAdaptationAnswer(), and ScheduleCallHere.
service()
Adaptation::Icap::ServiceRep & Adaptation::Icap::Xaction::service () inherited
Definition at line 110 of file Xaction.cc.
References Must.
setOutcome()
void Adaptation::Icap::Xaction::setOutcome (const XactOutcome & xo) protected inherited
Definition at line 560 of file Xaction.cc.
References debugs, and Adaptation::Icap::xoUnknown.
shouldAllow204()
bool Adaptation::Icap::ModXact::shouldAllow204 () private
Definition at line 1661 of file ModXact.cc.
shouldAllow206any()
bool Adaptation::Icap::ModXact::shouldAllow206any () private
Definition at line 1670 of file ModXact.cc.
References Adaptation::Icap::Config::allow206_enable, and Adaptation::Icap::TheConfig.
shouldAllow206in()
bool Adaptation::Icap::ModXact::shouldAllow206in () private
Definition at line 1677 of file ModXact.cc.
shouldAllow206out()
bool Adaptation::Icap::ModXact::shouldAllow206out () private
Definition at line 1683 of file ModXact.cc.
start()
void Adaptation::Icap::ModXact::start () override private virtual
Reimplemented from AsyncJob.
Definition at line 88 of file ModXact.cc.
References Adaptation::History::recordXactStart(), and Adaptation::Icap::Xaction::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
startReading()
void Adaptation::Icap::ModXact::startReading () private
Definition at line 531 of file ModXact.cc.
References Must.
startSending()
void Adaptation::Icap::ModXact::startSending () private
Definition at line 765 of file ModXact.cc.
References Adaptation::Answer::Forward().
startShoveling()
void Adaptation::Icap::ModXact::startShoveling () override virtual
Implements Adaptation::Icap::Xaction.
Definition at line 189 of file ModXact.cc.
References MemBuf::content(), current_time, debugs, MemBuf::init(), Must, and MemBuf::terminate().
startWriting()
void Adaptation::Icap::ModXact::startWriting () private
Definition at line 179 of file ModXact.cc.
status()
const char * Adaptation::Icap::Xaction::status () const override protected virtual inherited
for debugging, starts with space
Reimplemented from AsyncJob.
Definition at line 635 of file Xaction.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), and MemBuf::terminate().
Referenced by ModXact().
stopBackup()
void Adaptation::Icap::ModXact::stopBackup () private
Definition at line 514 of file ModXact.cc.
References debugs.
stopConsumingFrom()
void BodyConsumer::stopConsumingFrom (RefCount< BodyPipe > & p) protected inherited
Definition at line 118 of file BodyPipe.cc.
References assert, and debugs.
Referenced by ClientHttpRequest::~ClientHttpRequest(), Client::checkAdaptationWithBodyCompletion(), Client::cleanAdaptation(), Client::doneSendingRequestBody(), ClientHttpRequest::endRequestSatisfaction(), Client::handleRequestBodyProducerAborted(), BodySink::noteBodyProducerAborted(), ClientHttpRequest::noteBodyProducerAborted(), BodySink::noteBodyProductionEnded(), Client::serverComplete(), and Client::swanSong().
stopParsing()
void Adaptation::Icap::ModXact::stopParsing (const bool checkUnparsedData = true) private
Definition at line 1209 of file ModXact.cc.
References debugs, and Must.
stopProducingFor()
void BodyProducer::stopProducingFor (RefCount< BodyPipe > & p, bool atEof) protected inherited
Definition at line 107 of file BodyPipe.cc.
References assert, and debugs.
Referenced by ConnStateData::~ConnStateData(), Client::cleanAdaptation(), ConnStateData::finishDechunkingRequest(), Client::noteBodyConsumerAborted(), and Client::serverComplete2().
stopReceiving()
void Adaptation::Icap::ModXact::stopReceiving () private
stopSending()
void Adaptation::Icap::ModXact::stopSending (bool nicely) private
Definition at line 610 of file ModXact.cc.
References debugs, and Must.
stopWriting()
void Adaptation::Icap::ModXact::stopWriting (bool nicely) private
Definition at line 482 of file ModXact.cc.
References debugs.
swanSong()
void Adaptation::Icap::ModXact::swanSong () override private virtual
Reimplemented from AsyncJob.
Definition at line 1289 of file ModXact.cc.
References debugs, MakeNamedErrorDetail(), Adaptation::History::recordXactFinish(), and Adaptation::Icap::Xaction::swanSong().
tellQueryAborted() [1/2]
void Adaptation::Icap::Xaction::tellQueryAborted () private inherited
Definition at line 591 of file Xaction.cc.
References CallJobHere1.
tellQueryAborted() [2/2]
void Adaptation::Initiate::tellQueryAborted (bool final) protected inherited
Definition at line 87 of file Initiate.cc.
References Adaptation::Answer::Error().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
updateSources()
void Adaptation::Icap::ModXact::updateSources () private
Definition at line 2010 of file ModXact.cc.
References Must, Http::Message::srcIcap, and Http::Message::srcIcaps.
updateTimeout()
void Adaptation::Icap::Xaction::updateTimeout () protected inherited
Definition at line 395 of file Xaction.cc.
References commSetConnTimeout(), commUnsetConnTimeout(), Adaptation::Icap::Config::io_timeout(), JobCallback, Must, Adaptation::Icap::Xaction::noteCommTimedout(), and Adaptation::Icap::TheConfig.
useIcapConnection()
void Adaptation::Icap::Xaction::useIcapConnection (const Comm::ConnectionPointer & conn) private inherited
Definition at line 290 of file Xaction.cc.
References assert, asyncCall(), comm_add_close_handler(), Comm::IsConnOpen(), and Adaptation::Icap::Xaction::noteCommClosed().
useTransportConnection()
void Adaptation::Icap::Xaction::useTransportConnection (const Comm::ConnectionPointer & conn) private inherited
React to the availability of a transport connection to the ICAP service. The given connection may (or may not) be secured already.
Definition at line 268 of file Xaction.cc.
References assert, asyncCallback, Adaptation::Icap::Config::connect_timeout(), Comm::Connection::fd, fd_table, Adaptation::Icap::Xaction::handleSecuredPeer(), Comm::IsConnOpen(), and Adaptation::Icap::TheConfig.
validate200Ok()
bool Adaptation::Icap::ModXact::validate200Ok () private
Definition at line 883 of file ModXact.cc.
virginBodyEndReached()
bool Adaptation::Icap::ModXact::virginBodyEndReached (const VirginBodyAct & act) const private
Definition at line 395 of file ModXact.cc.
References Adaptation::Icap::VirginBodyAct::active(), and Adaptation::Icap::VirginBodyAct::offset().
virginConsume()
void Adaptation::Icap::ModXact::virginConsume () private
Definition at line 424 of file ModXact.cc.
References BodyPipe::buf(), BodyPipe::consume(), MemBuf::contentSize(), debugs, min(), Must, MemBuf::potentialSpaceSize(), size, and BodyPipe::status().
virginContentData()
const char * Adaptation::Icap::ModXact::virginContentData (const VirginBodyAct & act) const private
Definition at line 416 of file ModXact.cc.
References Adaptation::Icap::VirginBodyAct::active(), Must, and Adaptation::Icap::VirginBodyAct::offset().
virginContentSize()
size_t Adaptation::Icap::ModXact::virginContentSize (const VirginBodyAct & act) const private
Definition at line 404 of file ModXact.cc.
References Adaptation::Icap::VirginBodyAct::active(), Must, and Adaptation::Icap::VirginBodyAct::offset().
virginRequest()
const HttpRequest & Adaptation::Icap::ModXact::virginRequest () const private
Definition at line 386 of file ModXact.cc.
References Must.
waitForService()
void Adaptation::Icap::ModXact::waitForService () private
Definition at line 109 of file ModXact.cc.
References debugs, JobCallback, Must, noteServiceAvailable(), noteServiceReady(), Adaptation::srvBlock, Adaptation::srvWait, and TexcHere.
writeMore()
void Adaptation::Icap::ModXact::writeMore () private
Definition at line 238 of file ModXact.cc.
References debugs, Must, and TexcHere.
writePreviewBody()
void Adaptation::Icap::ModXact::writePreviewBody () private
Definition at line 274 of file ModXact.cc.
References debugs, min(), Must, size, and size_t.
writePrimeBody()
void Adaptation::Icap::ModXact::writePrimeBody () private
Definition at line 305 of file ModXact.cc.
References debugs, Must, size, and size_t.
writeSomeBody()
void Adaptation::Icap::ModXact::writeSomeBody (const char * label, size_t size) private
Definition at line 319 of file ModXact.cc.
References MemBuf::append(), MemBuf::clean(), MemBuf::contentSize(), debugs, MemBuf::hasContent(), MemBuf::init(), min(), Must, and size.
Member Data Documentation
adapted
InOut Adaptation::Icap::ModXact::adapted
Definition at line 172 of file ModXact.h.
adaptHistoryId
int Adaptation::Icap::ModXact::adaptHistoryId private
Definition at line 319 of file ModXact.h.
al
AccessLogEntry& Adaptation::Icap::Xaction::al protected inherited
Definition at line 152 of file Xaction.h.
alep
AccessLogEntry::Pointer Adaptation::Icap::Xaction::alep protected inherited
Definition at line 151 of file Xaction.h.
alMaster
AccessLogEntry::Pointer Adaptation::Icap::ModXact::alMaster private
Definition at line 373 of file ModXact.h.
Referenced by masterLogEntry().
attempts
int Adaptation::Icap::Xaction::attempts inherited
Definition at line 67 of file Xaction.h.
Referenced by Adaptation::Icap::Launcher::launchXaction().
bodyParser
Http1::TeChunkedParser* Adaptation::Icap::ModXact::bodyParser private
Definition at line 303 of file ModXact.h.
canStartBypass
bool Adaptation::Icap::ModXact::canStartBypass private
Definition at line 305 of file ModXact.h.
closer
AsyncCall::Pointer Adaptation::Icap::Xaction::closer private inherited
Definition at line 168 of file Xaction.h.
commEof
bool Adaptation::Icap::Xaction::commEof protected inherited
Definition at line 141 of file Xaction.h.
Referenced by doneReading(), and Adaptation::Icap::OptXact::doneReading().
connection
Comm::ConnectionPointer Adaptation::Icap::Xaction::connection private inherited
Definition at line 166 of file Xaction.h.
encryptionWait
JobWait<Ssl::IcapPeerConnector> Adaptation::Icap::Xaction::encryptionWait private inherited
Definition at line 163 of file Xaction.h.
extensionParser
ChunkExtensionValueParser Adaptation::Icap::ModXact::extensionParser private
Definition at line 323 of file ModXact.h.
icap_tio_finish
timeval Adaptation::Icap::Xaction::icap_tio_finish protected inherited
Definition at line 156 of file Xaction.h.
Referenced by Adaptation::Icap::Xaction::Xaction().
icap_tio_start
timeval Adaptation::Icap::Xaction::icap_tio_start protected inherited
Definition at line 155 of file Xaction.h.
Referenced by Adaptation::Icap::Xaction::Xaction().
icap_tr_start
timeval Adaptation::Icap::Xaction::icap_tr_start protected inherited
Definition at line 154 of file Xaction.h.
Referenced by Adaptation::Icap::Xaction::Xaction().
icapReply
HttpReply::Pointer Adaptation::Icap::Xaction::icapReply inherited
Definition at line 64 of file Xaction.h.
Referenced by ModXact().
icapRequest
HttpRequest* Adaptation::Icap::Xaction::icapRequest inherited
Definition at line 63 of file Xaction.h.
Referenced by Adaptation::Icap::Xaction::Xaction().
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
ignoreLastWrite
bool Adaptation::Icap::Xaction::ignoreLastWrite protected inherited
Definition at line 145 of file Xaction.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
isRepeatable
bool Adaptation::Icap::Xaction::isRepeatable protected inherited
Definition at line 144 of file Xaction.h.
Referenced by Adaptation::Icap::Xaction::repeatable().
isRetriable
bool Adaptation::Icap::Xaction::isRetriable protected inherited
Definition at line 143 of file Xaction.h.
Referenced by Adaptation::Icap::Xaction::retriable().
preview
Preview Adaptation::Icap::ModXact::preview private
Definition at line 301 of file ModXact.h.
protectGroupBypass
bool Adaptation::Icap::ModXact::protectGroupBypass private
Definition at line 306 of file ModXact.h.
readBuf
SBuf Adaptation::Icap::Xaction::readBuf protected inherited
Definition at line 140 of file Xaction.h.
reader
AsyncCall::Pointer Adaptation::Icap::Xaction::reader protected inherited
Definition at line 148 of file Xaction.h.
replyHttpBodySize
int64_t Adaptation::Icap::ModXact::replyHttpBodySize private
size of dechunked HTTP body in ICAP reply or -1 if there is not any encapsulated message data
Definition at line 317 of file ModXact.h.
replyHttpHeaderSize
int64_t Adaptation::Icap::ModXact::replyHttpHeaderSize private
size of HTTP header in ICAP reply or -1 if there is not any encapsulated message data
Definition at line 312 of file ModXact.h.
reuseConnection
bool Adaptation::Icap::Xaction::reuseConnection protected inherited
Definition at line 142 of file Xaction.h.
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
state
class Adaptation::Icap::ModXact::State Adaptation::Icap::ModXact::state private
Referenced by doneReading(), and doneWriting().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
theInitiator
CbcPointer<Initiator> Adaptation::Initiate::theInitiator protected inherited
Definition at line 51 of file Initiate.h.
theService
Adaptation::Icap::ServiceRep::Pointer Adaptation::Icap::Xaction::theService protected inherited
Definition at line 138 of file Xaction.h.
trailerParser
TrailerParser* Adaptation::Icap::ModXact::trailerParser private
Definition at line 321 of file ModXact.h.
transportWait
JobWait<Comm::ConnOpener> Adaptation::Icap::Xaction::transportWait private inherited
Definition at line 160 of file Xaction.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
virgin
InOut Adaptation::Icap::ModXact::virgin
Definition at line 171 of file ModXact.h.
Referenced by ModXact().
virginBody
SizedEstimate Adaptation::Icap::ModXact::virginBody private
Definition at line 297 of file ModXact.h.
virginBodySending
VirginBodyAct Adaptation::Icap::ModXact::virginBodySending private
Definition at line 299 of file ModXact.h.
virginBodyWriting
VirginBodyAct Adaptation::Icap::ModXact::virginBodyWriting private
Definition at line 298 of file ModXact.h.
virginConsumed
uint64_t Adaptation::Icap::ModXact::virginConsumed private
Definition at line 300 of file ModXact.h.
waitingForDns
bool Adaptation::Icap::Xaction::waitingForDns protected inherited
Definition at line 146 of file Xaction.h.
writer
AsyncCall::Pointer Adaptation::Icap::Xaction::writer protected inherited
Definition at line 149 of file Xaction.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/ModXact.h
squid/src/adaptation/icap/ModXact.cc