Squid Web Cache: Adaptation::Ecap::ServiceRep Class Reference
Adaptation::Ecap::ServiceRep Class Reference
#include <ServiceRep.h>
Public Types
typedef libecap::shared_ptr< libecap::adapter::Service > AdapterService
typedef RefCount< Service > Pointer
typedef String Id
Public Member Functions
ServiceRep (const ServiceConfigPointer &aConfig)
~ServiceRep () override
void finalize () override
bool probed () const override
bool up () const override
Adaptation::Initiate * makeXactLauncher (Http::Message *virginHeader, HttpRequest *virginCause, AccessLogEntry::Pointer &alp) override
bool wantsUrl (const SBuf &urlPath) const override
void noteFailure () override
virtual const char * status () const
void detach () override
bool detached () const override
whether detached() was called
virtual bool broken () const
bool wants (const ServiceFilter &filter) const
const ServiceConfig & cfg () const
Protected Member Functions
void tryConfigureAndStart ()
attempts to configure and start eCAP service; the caller handles exceptions
bool handleFinalizeFailure (const char *error)
ServiceConfig & writeableCfg ()
Private Attributes
AdapterService theService
bool isDetached
ServiceConfigPointer theConfig
Detailed Description
Definition at line 33 of file ServiceRep.h.
Member Typedef Documentation
AdapterService
typedef libecap::shared_ptr<libecap::adapter::Service> Adaptation::Ecap::ServiceRep::AdapterService
Definition at line 39 of file ServiceRep.h.
Id
typedef String Adaptation::Service::Id inherited
Definition at line 31 of file Service.h.
Pointer
typedef RefCount<Service> Adaptation::Service::Pointer inherited
Definition at line 30 of file Service.h.
Constructor & Destructor Documentation
ServiceRep()
Adaptation::Ecap::ServiceRep::ServiceRep (const ServiceConfigPointer & aConfig) explicit
Definition at line 163 of file ServiceRep.cc.
~ServiceRep()
Adaptation::Ecap::ServiceRep::~ServiceRep () override
Definition at line 169 of file ServiceRep.cc.
Member Function Documentation
broken()
bool Adaptation::Service::broken () const virtual inherited
Definition at line 30 of file Service.cc.
cfg()
const ServiceConfig & Adaptation::Service::cfg () const inline inherited
Definition at line 51 of file Service.h.
References Adaptation::Service::theConfig.
Referenced by Adaptation::Service::Service(), Adaptation::ServiceGroup::checkUniqueness(), Adaptation::Icap::Xaction::dnsLookupDone(), Adaptation::ServiceGroup::finalize(), Adaptation::Icap::Xaction::finalizeLogInfo(), Adaptation::Icap::ModXact::finalizeLogInfo(), Adaptation::ServiceGroup::findService(), Adaptation::Icap::OptXact::makeRequest(), Adaptation::Icap::Xaction::openConnection(), Adaptation::DynamicServiceChain::Split(), and Adaptation::Iterator::step().
detach()
void Adaptation::Ecap::ServiceRep::detach () override virtual
called when removed from the config; the service will be auto-destroyed when the last refcounting user leaves
Implements Adaptation::Service.
Definition at line 303 of file ServiceRep.cc.
detached()
bool Adaptation::Ecap::ServiceRep::detached () const override virtual
Implements Adaptation::Service.
Definition at line 308 of file ServiceRep.cc.
finalize()
void Adaptation::Ecap::ServiceRep::finalize () override virtual
Reimplemented from Adaptation::Service.
Definition at line 179 of file ServiceRep.cc.
References DBG_IMPORTANT, debugs, Adaptation::Service::finalize(), Adaptation::Ecap::FindAdapterService(), and Must.
handleFinalizeFailure()
bool Adaptation::Ecap::ServiceRep::handleFinalizeFailure (const char * error) protected
handles failures while configuring or starting an eCAP service; returns false if the error must be propagated to higher levels
Definition at line 222 of file ServiceRep.cc.
References DBG_CRITICAL, DBG_IMPORTANT, debugs, and error().
makeXactLauncher()
Adaptation::Initiate * Adaptation::Ecap::ServiceRep::makeXactLauncher (Http::Message * virginHeader, HttpRequest * virginCause, AccessLogEntry::Pointer & alp) override virtual
Implements Adaptation::Service.
Definition at line 260 of file ServiceRep.cc.
References AsyncServices, debugs, Adaptation::Ecap::XactionRep::master(), Must, EventLoop::registerEngine(), and EventLoop::Running.
noteFailure()
void Adaptation::Ecap::ServiceRep::noteFailure () override virtual
Implements Adaptation::Service.
Definition at line 173 of file ServiceRep.cc.
References assert.
probed()
bool Adaptation::Ecap::ServiceRep::probed () const override virtual
Implements Adaptation::Service.
Definition at line 241 of file ServiceRep.cc.
status()
const char * Adaptation::Ecap::ServiceRep::status () const virtual
Definition at line 281 of file ServiceRep.cc.
References MemBuf::append(), MemBuf::content(), MemBuf::reset(), and MemBuf::terminate().
tryConfigureAndStart()
void Adaptation::Ecap::ServiceRep::tryConfigureAndStart () protected
Definition at line 204 of file ServiceRep.cc.
References AsyncServices, DBG_IMPORTANT, and debugs.
up()
bool Adaptation::Ecap::ServiceRep::up () const override virtual
Implements Adaptation::Service.
Definition at line 246 of file ServiceRep.cc.
wants()
bool Adaptation::Service::wants (const ServiceFilter & filter) const inherited
Definition at line 36 of file Service.cc.
References AnyP::Uri::absolutePath(), Adaptation::ServiceFilter::method, Adaptation::ServiceFilter::point, Adaptation::ServiceFilter::request, and HttpRequest::url.
Referenced by Adaptation::ServiceGroup::findService().
wantsUrl()
bool Adaptation::Ecap::ServiceRep::wantsUrl (const SBuf & urlPath) const override virtual
Implements Adaptation::Service.
Definition at line 251 of file ServiceRep.cc.
References SBuf::c_str(), and Must.
writeableCfg()
ServiceConfig & Adaptation::Service::writeableCfg () inline protected inherited
Definition at line 62 of file Service.h.
References Adaptation::Service::theConfig.
Member Data Documentation
isDetached
bool Adaptation::Ecap::ServiceRep::isDetached private
Definition at line 58 of file ServiceRep.h.
theConfig
ServiceConfigPointer Adaptation::Service::theConfig private inherited
Definition at line 65 of file Service.h.
Referenced by Adaptation::Service::Service(), Adaptation::Service::cfg(), and Adaptation::Service::writeableCfg().
theService
AdapterService Adaptation::Ecap::ServiceRep::theService private
Definition at line 57 of file ServiceRep.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/ServiceRep.h
squid/src/adaptation/ecap/ServiceRep.cc