Squid Web Cache: Log::LogConfig Class Reference
Log::LogConfig Class Reference
#include <Config.h>
Public Member Functions
::Format::Format * findCustomFormat (const char *logformatName) const
bool knownFormat (const char *logformatName) const
void parseFormats ()
void dumpFormats (StoreEntry *e, const char *name)
Static Public Member Functions
static const char * BuiltInFormatName (Format::log_type type)
static Format::log_type FindBuiltInFormat (const char *logformatName)
Public Attributes
char * logfile_daemon
File path to logging daemon executable.
::Format::Format * logformats
Linked list of custom log formats.
bool hasAdaptToken
bool hasIcapToken
Detailed Description
Definition at line 20 of file Config.h.
Member Function Documentation
BuiltInFormatName()
const char * Log::LogConfig::BuiltInFormatName (Format::log_type type) static
Returns
the name of the given built-in logformat type (or nil)
Definition at line 18 of file Config.cc.
References Log::Format::CLF_COMBINED, Log::Format::CLF_COMMON, Log::Format::CLF_CUSTOM, Log::Format::CLF_ICAP_SQUID, Log::Format::CLF_NONE, Log::Format::CLF_REFERER, Log::Format::CLF_SQUID, Log::Format::CLF_UNKNOWN, and Log::Format::CLF_USERAGENT.
Referenced by FormattedLog::dumpOptions().
dumpFormats()
void Log::LogConfig::dumpFormats (StoreEntry * e, const char * name) inline
Definition at line 38 of file Config.h.
References Format::Format::dump(), and logformats.
FindBuiltInFormat()
Log::Format::log_type Log::LogConfig::FindBuiltInFormat (const char * logformatName) static
Returns
either a named built-in logformat ID or CLF_UNKNOWN
Definition at line 52 of file Config.cc.
References assert, Log::Format::CLF_COMBINED, Log::Format::CLF_COMMON, Log::Format::CLF_ICAP_SQUID, Log::Format::CLF_REFERER, Log::Format::CLF_SQUID, Log::Format::CLF_UNKNOWN, Log::Format::CLF_USERAGENT, DBG_CRITICAL, and debugs.
Referenced by FormattedLog::setLogformat().
findCustomFormat()
Format::Format * Log::LogConfig::findCustomFormat (const char * logformatName) const
Returns
a named (previously configured) custom log format object or nil
Definition at line 87 of file Config.cc.
References assert.
knownFormat()
bool Log::LogConfig::knownFormat (const char * logformatName) const
whether the given format name is supported, either as a built-in or a (previously configured) custom logformat
Definition at line 98 of file Config.cc.
parseFormats()
void Log::LogConfig::parseFormats ()
Definition at line 104 of file Config.cc.
References cfg_filename, config_lineno, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::DisableMacros(), ConfigParser::EnableMacros(), Format::Format::next, ConfigParser::NextQuotedOrToEol(), ConfigParser::NextToken(), Format::Format::parse(), and self_destruct().
Member Data Documentation
hasAdaptToken
bool Log::LogConfig::hasAdaptToken
Definition at line 50 of file Config.h.
Referenced by accessLogInit().
hasIcapToken
bool Log::LogConfig::hasIcapToken
Definition at line 54 of file Config.h.
Referenced by accessLogInit().
logfile_daemon
char* Log::LogConfig::logfile_daemon
Definition at line 44 of file Config.h.
logformats
::Format::Format* Log::LogConfig::logformats
Definition at line 47 of file Config.h.
Referenced by dumpFormats().
The documentation for this class was generated from the following files:
squid/src/log/Config.h
squid/src/log/Config.cc