Squid Web Cache: TestIpAddress Class Reference
TestIpAddress Class Reference
Protected Member Functions
void testDefaults ()
void testInAddrConstructor ()
void testInAddr6Constructor ()
void testSockAddrConstructor ()
void testSockAddr6Constructor ()
void testHostentConstructor ()
void testStringConstructor ()
void testCopyConstructor ()
void testsetEmpty ()
void testBooleans ()
void testAddrInfo ()
void testtoStr ()
void testtoUrl_fromInAddr ()
void testtoUrl_fromSockAddr ()
void testgetReverseString ()
void testMasking ()
void testBugNullingDisplay ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestIpAddress)
CPPUNIT_TEST (testDefaults)
CPPUNIT_TEST (testInAddrConstructor)
CPPUNIT_TEST (testInAddr6Constructor)
CPPUNIT_TEST (testSockAddrConstructor)
CPPUNIT_TEST (testSockAddr6Constructor)
CPPUNIT_TEST (testHostentConstructor)
CPPUNIT_TEST (testStringConstructor)
CPPUNIT_TEST (testCopyConstructor)
CPPUNIT_TEST (testsetEmpty)
CPPUNIT_TEST (testBooleans)
CPPUNIT_TEST (testAddrInfo)
CPPUNIT_TEST (testtoStr)
CPPUNIT_TEST (testtoUrl_fromInAddr)
CPPUNIT_TEST (testtoUrl_fromSockAddr)
CPPUNIT_TEST (testgetReverseString)
CPPUNIT_TEST (testMasking)
CPPUNIT_TEST (testBugNullingDisplay)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 30 of file testIpAddress.cc.
Member Function Documentation
CPPUNIT_TEST() [1/17]
TestIpAddress::CPPUNIT_TEST (testAddrInfo) private
CPPUNIT_TEST() [2/17]
TestIpAddress::CPPUNIT_TEST (testBooleans) private
CPPUNIT_TEST() [3/17]
TestIpAddress::CPPUNIT_TEST (testBugNullingDisplay) private
CPPUNIT_TEST() [4/17]
TestIpAddress::CPPUNIT_TEST (testCopyConstructor) private
CPPUNIT_TEST() [5/17]
TestIpAddress::CPPUNIT_TEST (testDefaults) private
CPPUNIT_TEST() [6/17]
TestIpAddress::CPPUNIT_TEST (testgetReverseString) private
CPPUNIT_TEST() [7/17]
TestIpAddress::CPPUNIT_TEST (testHostentConstructor) private
CPPUNIT_TEST() [8/17]
TestIpAddress::CPPUNIT_TEST (testInAddr6Constructor) private
CPPUNIT_TEST() [9/17]
TestIpAddress::CPPUNIT_TEST (testInAddrConstructor) private
CPPUNIT_TEST() [10/17]
TestIpAddress::CPPUNIT_TEST (testMasking) private
CPPUNIT_TEST() [11/17]
TestIpAddress::CPPUNIT_TEST (testsetEmpty) private
CPPUNIT_TEST() [12/17]
TestIpAddress::CPPUNIT_TEST (testSockAddr6Constructor) private
CPPUNIT_TEST() [13/17]
TestIpAddress::CPPUNIT_TEST (testSockAddrConstructor) private
CPPUNIT_TEST() [14/17]
TestIpAddress::CPPUNIT_TEST (testStringConstructor) private
CPPUNIT_TEST() [15/17]
TestIpAddress::CPPUNIT_TEST (testtoStr) private
CPPUNIT_TEST() [16/17]
TestIpAddress::CPPUNIT_TEST (testtoUrl_fromInAddr) private
CPPUNIT_TEST() [17/17]
TestIpAddress::CPPUNIT_TEST (testtoUrl_fromSockAddr) private
CPPUNIT_TEST_SUITE()
TestIpAddress::CPPUNIT_TEST_SUITE (TestIpAddress) private
CPPUNIT_TEST_SUITE_END()
TestIpAddress::CPPUNIT_TEST_SUITE_END () private
testAddrInfo()
void TestIpAddress::testAddrInfo () protected
Definition at line 667 of file testIpAddress.cc.
References Ip::Address::FreeAddr(), and Ip::Address::getAddrInfo().
testBooleans()
void TestIpAddress::testBooleans () protected
Definition at line 350 of file testIpAddress.cc.
References Ip::Address::matchIPAddr(), Ip::Address::setAnyAddr(), and Ip::Address::setNoAddr().
testBugNullingDisplay()
void TestIpAddress::testBugNullingDisplay () protected
Definition at line 731 of file testIpAddress.cc.
References Ip::Address::getInAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), MAX_IPSTRLEN, Ip::Address::port(), Ip::Address::toHostStr(), Ip::Address::toStr(), and Ip::Address::toUrl().
testCopyConstructor()
void TestIpAddress::testCopyConstructor () protected
Definition at line 204 of file testIpAddress.cc.
References Ip::Address::getSockAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), and Ip::Address::port().
testDefaults()
void TestIpAddress::testDefaults () protected
Definition at line 83 of file testIpAddress.cc.
References Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), and Ip::Address::port().
testgetReverseString()
void TestIpAddress::testgetReverseString () protected
Definition at line 552 of file testIpAddress.cc.
References Ip::Address::getReverseString(), and MAX_IPSTRLEN.
testHostentConstructor()
void TestIpAddress::testHostentConstructor () protected
Definition at line 234 of file testIpAddress.cc.
References Ip::Address::getInAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), Ip::Address::port(), and xgethostbyname().
testInAddr6Constructor()
void TestIpAddress::testInAddr6Constructor () protected
Definition at line 119 of file testIpAddress.cc.
References Ip::Address::getInAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), and Ip::Address::port().
testInAddrConstructor()
void TestIpAddress::testInAddrConstructor () protected
Definition at line 97 of file testIpAddress.cc.
References Ip::Address::getInAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), and Ip::Address::port().
testMasking()
void TestIpAddress::testMasking () protected
Definition at line 586 of file testIpAddress.cc.
References Ip::Address::applyMask(), Ip::Address::cidr(), Ip::Address::getInAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), MAX_IPSTRLEN, Ip::Address::setAnyAddr(), Ip::Address::setNoAddr(), and Ip::Address::toStr().
testsetEmpty()
void TestIpAddress::testsetEmpty () protected
Definition at line 321 of file testIpAddress.cc.
References Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), Ip::Address::port(), and Ip::Address::setEmpty().
testSockAddr6Constructor()
void TestIpAddress::testSockAddr6Constructor () protected
Definition at line 172 of file testIpAddress.cc.
References Ip::Address::getSockAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), and Ip::Address::port().
testSockAddrConstructor()
void TestIpAddress::testSockAddrConstructor () protected
Definition at line 143 of file testIpAddress.cc.
References Ip::Address::getSockAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), and Ip::Address::port().
testStringConstructor()
void TestIpAddress::testStringConstructor () protected
Definition at line 258 of file testIpAddress.cc.
References Ip::Address::getInAddr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isIPv6(), Ip::Address::isNoAddr(), Ip::Address::isSockAddr(), and Ip::Address::port().
testtoStr()
void TestIpAddress::testtoStr () protected
Definition at line 462 of file testIpAddress.cc.
References MAX_IPSTRLEN, Ip::Address::setAnyAddr(), Ip::Address::setNoAddr(), and Ip::Address::toStr().
testtoUrl_fromInAddr()
void TestIpAddress::testtoUrl_fromInAddr () protected
Definition at line 486 of file testIpAddress.cc.
References MAX_IPSTRLEN, and Ip::Address::toUrl().
testtoUrl_fromSockAddr()
void TestIpAddress::testtoUrl_fromSockAddr () protected
Definition at line 515 of file testIpAddress.cc.
References MAX_IPSTRLEN, and Ip::Address::toUrl().
The documentation for this class was generated from the following file:
squid/src/tests/testIpAddress.cc