Squid Web Cache: Security::KeyData Class Reference
Security::KeyData Class Reference
TLS certificate and private key details from squid.conf.
#include <KeyData.h>
Public Member Functions
void loadFromFiles (const AnyP::PortCfg &, const char *portType)
load the contents of certFile and privateKeyFile into memory cert, pkey and chain
Public Attributes
SBuf certFile
path of file containing PEM format X.509 certificate
SBuf privateKeyFile
path of file containing private key in PEM format
Security::CertPointer cert
public X.509 certificate from certFile
Security::PrivateKeyPointer pkey
private key from privateKeyFile
Security::CertList chain
any certificates which must be chained from cert
Private Member Functions
bool loadCertificates ()
bool loadX509PrivateKeyFromFile ()
Detailed Description
Definition at line 20 of file KeyData.h.
Member Function Documentation
loadCertificates()
bool Security::KeyData::loadCertificates () private
load the signing certificate and its chain, if any, from certFile
Returns
true if the signing certificate was obtained
Definition at line 23 of file KeyData.cc.
References SBuf::c_str(), cert, certFile, chain, CurrentException(), DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, Security::ErrorString(), Debug::Extra(), Ssl::ReadCertificate(), Ssl::ReadOptionalCertificate(), Security::LockingPointer< T, UnLocker, Locker >::reset(), and Security::SelfSigned().
loadFromFiles()
void Security::KeyData::loadFromFiles (const AnyP::PortCfg & port, const char * portType)
Definition at line 182 of file KeyData.cc.
References DBG_IMPORTANT, debugs, and port.
loadX509PrivateKeyFromFile()
bool Security::KeyData::loadX509PrivateKeyFromFile () private
Read X.509 private key from file.
Definition at line 139 of file KeyData.cc.
References Ssl::AskPasswordCb(), Config, DBG_IMPORTANT, debugs, SquidConfig::Program, Ssl::ReadPrivateKeyFromFile(), and SquidConfig::ssl_password.
Member Data Documentation
cert
Security::CertPointer Security::KeyData::cert
Definition at line 31 of file KeyData.h.
Referenced by Ssl::chainCertificatesToSSLContext(), and loadCertificates().
certFile
SBuf Security::KeyData::certFile
Definition at line 27 of file KeyData.h.
Referenced by loadCertificates(), and Security::PeerOptions::parse().
chain
Security::CertList Security::KeyData::chain
Definition at line 35 of file KeyData.h.
Referenced by Ssl::chainCertificatesToSSLContext(), and loadCertificates().
pkey
Security::PrivateKeyPointer Security::KeyData::pkey
Definition at line 33 of file KeyData.h.
privateKeyFile
SBuf Security::KeyData::privateKeyFile
Definition at line 28 of file KeyData.h.
Referenced by Security::PeerOptions::parse().
The documentation for this class was generated from the following files:
squid/src/security/KeyData.h
squid/src/security/KeyData.cc