Squid Web Cache: SharedMemory Class Reference
SharedMemory Class Reference
Storage Filesystems | Storage Filesystems » UFS Storage Filesystem » diskd Storage Filesystem (UFS Based)
#include <DiskdIOStrategy.h>
Public Member Functions
void put (ssize_t)
void * get (ssize_t *)
void init (int ikey, int magic2)
SharedMemory ()
Public Attributes
int nbufs
char * buf
char * inuse_map
int id
Detailed Description
Definition at line 17 of file DiskdIOStrategy.h.
Constructor & Destructor Documentation
SharedMemory()
SharedMemory::SharedMemory () inline
Definition at line 24 of file DiskdIOStrategy.h.
Member Function Documentation
get()
void * SharedMemory::get (ssize_t * shm_offset)
Definition at line 223 of file DiskdIOStrategy.cc.
References assert, buf, CBIT_SET, CBIT_TEST, DBG_IMPORTANT, debugs, diskd_stats, inuse_map, diskd_stats_t::max_shmuse, nbufs, SHMBUF_BLKSZ, and diskd_stats_t::shmbuf_count.
Referenced by DiskdFile::create(), DiskdFile::open(), DiskdFile::read(), DiskdIOStrategy::unlinkFile(), and DiskdFile::write().
init()
void SharedMemory::init (int ikey, int magic2)
Definition at line 258 of file DiskdIOStrategy.cc.
References buf, CBIT_SET, DBG_CRITICAL, debugs, diskd_stats, fatal(), int, inuse_map, MYNAME, nbufs, put(), SHMBUF_BLKSZ, diskd_stats_t::shmbuf_count, xcalloc(), and xstrerr().
Referenced by DiskdIOStrategy::init().
put()
void SharedMemory::put (ssize_t offset)
Definition at line 209 of file DiskdIOStrategy.cc.
References assert, CBIT_CLR, CBIT_TEST, diskd_stats, inuse_map, nbufs, SHMBUF_BLKSZ, and diskd_stats_t::shmbuf_count.
Referenced by DiskdIOStrategy::callback(), init(), and DiskdIOStrategy::SEND().
Member Data Documentation
buf
char* SharedMemory::buf
Definition at line 27 of file DiskdIOStrategy.h.
Referenced by get(), init(), DiskdFile::readDone(), and DiskdIOStrategy::unlinkDone().
id
int SharedMemory::id
Definition at line 29 of file DiskdIOStrategy.h.
inuse_map
char* SharedMemory::inuse_map
Definition at line 28 of file DiskdIOStrategy.h.
Referenced by get(), init(), and put().
nbufs
int SharedMemory::nbufs
Definition at line 26 of file DiskdIOStrategy.h.
Referenced by get(), init(), and put().
The documentation for this class was generated from the following files:
squid/src/DiskIO/DiskDaemon/DiskdIOStrategy.h
squid/src/DiskIO/DiskDaemon/DiskdIOStrategy.cc