Squid Web Cache: DelayPools Class Reference
DelayPools Class Reference
Squid Components » Delay Pools API
#include <DelayPools.h>
Static Public Member Functions
static void Init ()
static void Update (void *)
static unsigned short pools ()
static void pools (unsigned short pools)
static void FreePools ()
static unsigned char * DelayClasses ()
static void registerForUpdates (Updateable *)
static void deregisterForUpdates (Updateable *)
Static Public Attributes
static DelayPool * delay_data = nullptr
Static Private Member Functions
static void Stats (StoreEntry *)
static void InitDelayData ()
static void FreeDelayData ()
static void RegisterWithCacheManager (void)
Static Private Attributes
static time_t LastUpdate = 0
static unsigned short pools_
static std::vector< Updateable * > toUpdate
Detailed Description
Definition at line 34 of file DelayPools.h.
Member Function Documentation
DelayClasses()
static unsigned char * DelayPools::DelayClasses () static
deregisterForUpdates()
void DelayPools::deregisterForUpdates (Updateable * anObject) static
Definition at line 515 of file delay_pools.cc.
Referenced by Aggregate::~Aggregate(), ClassCHostPool::~ClassCHostPool(), DelayTagged::~DelayTagged(), DelayUser::~DelayUser(), DelayVector::~DelayVector(), and VectorPool::~VectorPool().
FreeDelayData()
void DelayPools::FreeDelayData () static private
Definition at line 476 of file delay_pools.cc.
References delay_data.
FreePools()
void DelayPools::FreePools () static
Definition at line 555 of file delay_pools.cc.
References pools().
Referenced by DelayConfig::freePoolCount(), and SquidShutdown().
Init()
void DelayPools::Init () static
Definition at line 458 of file delay_pools.cc.
References getCurrentTime().
Referenced by mainInitialize().
InitDelayData()
void DelayPools::InitDelayData () static private
Definition at line 465 of file delay_pools.cc.
References delay_data, eventAdd(), and Update().
pools() [1/2]
unsigned short DelayPools::pools () static
Definition at line 564 of file delay_pools.cc.
Referenced by DelayId::DelayClient(), DelayConfig::dumpPoolCount(), FreePools(), DelayConfig::parsePoolAccess(), DelayConfig::parsePoolClass(), DelayConfig::parsePoolCount(), DelayConfig::parsePoolRates(), and Stats().
pools() [2/2]
void DelayPools::pools (unsigned short pools) static
Definition at line 570 of file delay_pools.cc.
References DBG_CRITICAL, and debugs.
registerForUpdates()
void DelayPools::registerForUpdates (Updateable * anObject) static
Definition at line 508 of file delay_pools.cc.
Referenced by Aggregate::Aggregate(), ClassCHostPool::ClassCHostPool(), DelayTagged::DelayTagged(), DelayUser::DelayUser(), DelayVector::DelayVector(), and VectorPool::VectorPool().
RegisterWithCacheManager()
void DelayPools::RegisterWithCacheManager (void) static private
Definition at line 452 of file delay_pools.cc.
References Mgr::RegisterAction().
Stats()
void DelayPools::Stats (StoreEntry * sentry) static private
Definition at line 541 of file delay_pools.cc.
References delay_data, pools(), SQUIDSBUFPH, SQUIDSBUFPRINT, CompositePoolNode::stats(), storeAppendPrintf(), and DelayPool::theComposite().
Update()
void DelayPools::Update (void *) static
Definition at line 483 of file delay_pools.cc.
References eventAdd(), and squid_curtime.
Referenced by InitDelayData().
Member Data Documentation
delay_data
DelayPool * DelayPools::delay_data = nullptr static
Definition at line 46 of file DelayPools.h.
Referenced by DelayId::DelayClient(), DelayConfig::dumpPoolCount(), FreeDelayData(), InitDelayData(), DelayConfig::parsePoolAccess(), DelayConfig::parsePoolClass(), DelayConfig::parsePoolRates(), and Stats().
LastUpdate
time_t DelayPools::LastUpdate = 0 static private
Definition at line 51 of file DelayPools.h.
pools_
unsigned short DelayPools::pools_ static private
Definition at line 52 of file DelayPools.h.
toUpdate
std::vector< Updateable * > DelayPools::toUpdate static private
Definition at line 54 of file DelayPools.h.
The documentation for this class was generated from the following files:
squid/src/DelayPools.h
squid/src/delay_pools.cc