Squid Web Cache: Note::Value Class Reference
Note::Value Class Reference
Stores a value for the note.
#include <Notes.h>
Public Types
enum Method { mhReplace , mhAppend }
typedef RefCount< Value > Pointer
Public Member Functions
Value (const char *aVal, const bool quoted, const char *descr, const Method method=mhReplace)
~Value () override
Value (const Value &)=delete
Value & operator= (const Value &)=delete
Method method () const
const SBuf & value () const
Public Attributes
ACLList * aclList
The access list used to determine if this value is valid for a request.
Private Member Functions
const SBuf & format (const AccessLogEntryPointer &al)
Private Attributes
Format::Format * valueFormat
Compiled annotation value format.
SBuf theValue
SBuf theFormattedValue
The expanded value produced by format(), empty for non-quoted values.
Method theMethod
Friends
class Note
Detailed Description
Definition at line 44 of file Notes.h.
Member Typedef Documentation
Pointer
typedef RefCount<Value> Note::Value::Pointer
Definition at line 47 of file Notes.h.
Member Enumeration Documentation
Method
enum Note::Value::Method
Enumerator
mhReplace
mhAppend
Definition at line 50 of file Notes.h.
Constructor & Destructor Documentation
Value() [1/2]
Note::Value::Value (const char * aVal, const bool quoted, const char * descr, const Method method = mhReplace)
Definition at line 37 of file Notes.cc.
References SBuf::c_str(), Here, Format::Format::parse(), theValue, ToSBuf(), and valueFormat.
~Value()
Note::Value::~Value () override
Definition at line 31 of file Notes.cc.
References aclDestroyAclList(), aclList, and valueFormat.
Value() [2/2]
Note::Value::Value (const Value &) delete
Member Function Documentation
format()
const SBuf & Note::Value::format (const AccessLogEntryPointer & al) private
Returns
the formatted value with expanded logformat macros (quoted values).
the original value (non-quoted values).
Definition at line 50 of file Notes.cc.
References MemBuf::content(), and MemBuf::reset().
method()
Method Note::Value::method () const inline
Definition at line 57 of file Notes.h.
References theMethod.
operator=()
Value & Note::Value::operator= (const Value &) delete
value()
const SBuf & Note::Value::value () const inline
Definition at line 58 of file Notes.h.
References theValue.
Friends And Related Symbol Documentation
Note
friend class Note friend
Definition at line 48 of file Notes.h.
Member Data Documentation
aclList
ACLList* Note::Value::aclList
Definition at line 60 of file Notes.h.
Referenced by ~Value().
theFormattedValue
SBuf Note::Value::theFormattedValue private
Definition at line 70 of file Notes.h.
theMethod
Method Note::Value::theMethod private
Specifies how theValue will be applied to the existing annotation with the same key: it either replaces the existing value or is appended to the list of existing values.
Definition at line 74 of file Notes.h.
Referenced by method().
theValue
SBuf Note::Value::theValue private
Configured annotation value, possibly with macros.
Definition at line 68 of file Notes.h.
Referenced by Value(), and value().
valueFormat
Format::Format* Note::Value::valueFormat private
Definition at line 67 of file Notes.h.
Referenced by Value(), and ~Value().
The documentation for this class was generated from the following files:
squid/src/Notes.h
squid/src/Notes.cc