Squid Web Cache: ACLData< M > Class Template Reference
ACLData< M > Class Template Reference abstract
Configured ACL parameter(s) (e.g., domain names in dstdomain ACL).
#include <Data.h>
Public Member Functions
ACLData ()=default
ACLData (ACLData< M > &&)=delete
virtual ~ACLData ()
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual bool match (M)=0
virtual SBufList dump () const =0
virtual void parse ()=0
virtual void prepareForUse ()
virtual bool empty () const =0
Detailed Description
template<class M>
class ACLData< M >
Definition at line 17 of file Data.h.
Constructor & Destructor Documentation
ACLData() [1/2]
template<class M > ACLData< M >::ACLData () default
ACLData() [2/2]
template<class M > ACLData< M >::ACLData (ACLData< M > &&) delete
~ACLData()
template<class M > virtual ACLData< M >::~ACLData () inline virtual
Definition at line 23 of file Data.h.
Member Function Documentation
dump()
template<class M > virtual SBufList ACLData< M >::dump () const pure virtual
Implemented in ACLAnnotationData, ACLAtStepData, ACLCertificateData, ACLDomainData, ACLHasComponentData, ACLHierCodeData, ACLHTTPHeaderData, ACLIntRange, ACLMethodData, ACLNoteData, ACLProtocolData, ACLRegexData, ACLSquidErrorData, ACLSslErrorData, ACLStringData, ACLTimeData, and ACLUserData.
Referenced by ACLExtUser::dump(), ACLHTTPHeaderData::dump(), and ACLProxyAuth::dump().
empty()
template<class M > virtual bool ACLData< M >::empty () const pure virtual
Implemented in ACLAnnotationData, ACLAtStepData, ACLCertificateData, ACLDomainData, ACLHasComponentData, ACLHierCodeData, ACLHTTPHeaderData, ACLIntRange, ACLMethodData, ACLNoteData, ACLProtocolData, ACLRegexData, ACLSquidErrorData, ACLSslErrorData, ACLStringData, ACLTimeData, and ACLUserData.
Referenced by ACLExtUser::empty(), ACLHTTPHeaderData::empty(), and ACLProxyAuth::empty().
lineOptions()
template<class M > virtual const Acl::Options & ACLData< M >::lineOptions () inline virtual
Reimplemented in ACLHTTPHeaderData, ACLRegexData, and ACLUserData.
Definition at line 26 of file Data.h.
References Acl::NoOptions().
Referenced by ACLExtUser::lineOptions(), ACLHTTPHeaderData::lineOptions(), and ACLProxyAuth::lineOptions().
match()
template<class M > virtual bool ACLData< M >::match (M) pure virtual
Implemented in ACLHasComponentData, ACLProtocolData, ACLDomainData, ACLStringData, ACLRegexData, ACLUserData, ACLServerNameData, ACLHTTPHeaderData, ACLSslErrorData, ACLSquidErrorData, ACLHierCodeData, ACLMethodData, ACLIntRange, ACLAnnotationData, ACLNoteData, ACLTimeData, ACLCertificateData, and ACLAtStepData.
Referenced by ACLExtUser::match(), ACLHTTPHeaderData::match(), Acl::ServerNameMatcher::matchDomainName(), and ACLProxyAuth::matchForCache().
parse()
template<class M > virtual void ACLData< M >::parse () pure virtual
Implemented in ACLAdaptationServiceData, ACLAnnotationData, ACLAtStepData, ACLCertificateData, ACLDomainData, ACLHasComponentData, ACLHierCodeData, ACLHTTPHeaderData, ACLIntRange, ACLMethodData, ACLNoteData, ACLProtocolData, ACLRegexData, ACLSquidErrorData, ACLSslErrorData, ACLStringData, ACLTimeData, and ACLUserData.
Referenced by ACLExtUser::parse(), ACLHTTPHeaderData::parse(), and ACLProxyAuth::parse().
prepareForUse()
template<class M > virtual void ACLData< M >::prepareForUse () inline virtual
Definition at line 31 of file Data.h.
The documentation for this class was generated from the following file:
squid/src/acl/Data.h