Squid Web Cache: Adaptation::Ecap::MessageRep Class Reference
Adaptation::Ecap::MessageRep Class Reference
#include <MessageRep.h>
Public Member Functions
MessageRep (Http::Message *rawHeader)
~MessageRep () override
libecap::shared_ptr< libecap::Message > clone () const override
libecap::FirstLine & firstLine () override
const libecap::FirstLine & firstLine () const override
libecap::Header & header () override
const libecap::Header & header () const override
void addBody () override
libecap::Body * body () override
const libecap::Body * body () const override
void tieBody (Ecap::XactionRep *x)
Adaptation::Message & raw ()
const Adaptation::Message & raw () const
Private Attributes
Adaptation::Message theMessage
libecap::FirstLine * theFirstLineRep
HeaderRep * theHeaderRep
BodyRep * theBodyRep
Detailed Description
Definition at line 153 of file MessageRep.h.
Constructor & Destructor Documentation
MessageRep()
Adaptation::Ecap::MessageRep::MessageRep (Http::Message * rawHeader) explicit
Definition at line 363 of file MessageRep.cc.
References Adaptation::Message::body_pipe, Adaptation::Message::header, Must, theBodyRep, theFirstLineRep, theHeaderRep, and theMessage.
~MessageRep()
Adaptation::Ecap::MessageRep::~MessageRep () override
Definition at line 382 of file MessageRep.cc.
Member Function Documentation
addBody()
void Adaptation::Ecap::MessageRep::addBody () override
Definition at line 434 of file MessageRep.cc.
References Must.
body() [1/2]
const libecap::Body * Adaptation::Ecap::MessageRep::body () const override
Definition at line 452 of file MessageRep.cc.
body() [2/2]
libecap::Body * Adaptation::Ecap::MessageRep::body () override
Definition at line 428 of file MessageRep.cc.
clone()
libecap::shared_ptr< libecap::Message > Adaptation::Ecap::MessageRep::clone () const override
Definition at line 390 of file MessageRep.cc.
References Http::Message::body_pipe, and Http::Message::header.
firstLine() [1/2]
const libecap::FirstLine & Adaptation::Ecap::MessageRep::firstLine () const override
Definition at line 410 of file MessageRep.cc.
firstLine() [2/2]
libecap::FirstLine & Adaptation::Ecap::MessageRep::firstLine () override
Definition at line 404 of file MessageRep.cc.
header() [1/2]
const libecap::Header & Adaptation::Ecap::MessageRep::header () const override
Definition at line 422 of file MessageRep.cc.
header() [2/2]
libecap::Header & Adaptation::Ecap::MessageRep::header () override
Definition at line 416 of file MessageRep.cc.
raw() [1/2]
Adaptation::Message & Adaptation::Ecap::MessageRep::raw () inline
Definition at line 171 of file MessageRep.h.
References theMessage.
Referenced by Adaptation::Ecap::XactionRep::answer(), and Adaptation::Ecap::XactionRep::status().
raw() [2/2]
const Adaptation::Message & Adaptation::Ecap::MessageRep::raw () const inline
Definition at line 172 of file MessageRep.h.
References theMessage.
tieBody()
void Adaptation::Ecap::MessageRep::tieBody (Ecap::XactionRep * x)
Definition at line 442 of file MessageRep.cc.
References Must.
Referenced by Adaptation::Ecap::XactionRep::useAdapted().
Member Data Documentation
theBodyRep
BodyRep* Adaptation::Ecap::MessageRep::theBodyRep private
Definition at line 178 of file MessageRep.h.
Referenced by MessageRep().
theFirstLineRep
libecap::FirstLine* Adaptation::Ecap::MessageRep::theFirstLineRep private
Definition at line 176 of file MessageRep.h.
Referenced by MessageRep().
theHeaderRep
HeaderRep* Adaptation::Ecap::MessageRep::theHeaderRep private
Definition at line 177 of file MessageRep.h.
Referenced by MessageRep().
theMessage
Adaptation::Message Adaptation::Ecap::MessageRep::theMessage private
Definition at line 175 of file MessageRep.h.
Referenced by MessageRep(), raw(), and raw().
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/MessageRep.h
squid/src/adaptation/ecap/MessageRep.cc