Squid Web Cache: Mgr::IntParam Class Reference
Mgr::IntParam Class Reference
#include <IntParam.h>
Public Types
enum Type { ptInt = 1 , ptString }
typedef RefCount< QueryParam > Pointer
Public Member Functions
IntParam ()
IntParam (const std::vector< int > &anArray)
void pack (Ipc::TypedMsgHdr &msg) const override
store parameter into msg
void unpackValue (const Ipc::TypedMsgHdr &msg) override
load parameter value from msg
const std::vector< int > & value () const
Public Attributes
Type type
Private Attributes
std::vector< int > array
Detailed Description
Definition at line 22 of file IntParam.h.
Member Typedef Documentation
Pointer
typedef RefCount<QueryParam> Mgr::QueryParam::Pointer inherited
Definition at line 24 of file QueryParam.h.
Member Enumeration Documentation
Type
enum Mgr::QueryParam::Type inherited
Enumerator
ptInt
ptString
Definition at line 23 of file QueryParam.h.
Constructor & Destructor Documentation
IntParam() [1/2]
Mgr::IntParam::IntParam ()
Definition at line 17 of file IntParam.cc.
IntParam() [2/2]
Mgr::IntParam::IntParam (const std::vector< int > & anArray)
Definition at line 22 of file IntParam.cc.
Member Function Documentation
pack()
void Mgr::IntParam::pack (Ipc::TypedMsgHdr & msg) const override virtual
Implements Mgr::QueryParam.
Definition at line 28 of file IntParam.cc.
References Ipc::TypedMsgHdr::putInt(), and Ipc::TypedMsgHdr::putPod().
unpackValue()
void Mgr::IntParam::unpackValue (const Ipc::TypedMsgHdr & msg) override virtual
Implements Mgr::QueryParam.
Definition at line 38 of file IntParam.cc.
References Ipc::TypedMsgHdr::getInt(), and Must.
value()
const std::vector< int > & Mgr::IntParam::value () const
Definition at line 48 of file IntParam.cc.
Referenced by Mgr::Inquirer::applyQueryParams().
Member Data Documentation
array
std::vector<int> Mgr::IntParam::array private
Definition at line 32 of file IntParam.h.
type
Type Mgr::QueryParam::type inherited
Definition at line 37 of file QueryParam.h.
Referenced by Mgr::Inquirer::applyQueryParams().
The documentation for this class was generated from the following files:
squid/src/mgr/IntParam.h
squid/src/mgr/IntParam.cc