Squid Web Cache: TestEvent Class Reference
TestEvent Class Reference
Protected Member Functions
void testCreate ()
void testDump ()
void testFind ()
void testCheckEvents ()
void testSingleton ()
void testCancel ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestEvent)
CPPUNIT_TEST (testCreate)
CPPUNIT_TEST (testDump)
CPPUNIT_TEST (testFind)
CPPUNIT_TEST (testCheckEvents)
CPPUNIT_TEST (testSingleton)
CPPUNIT_TEST (testCancel)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 20 of file testEvent.cc.
Member Function Documentation
CPPUNIT_TEST() [1/6]
TestEvent::CPPUNIT_TEST (testCancel) private
CPPUNIT_TEST() [2/6]
TestEvent::CPPUNIT_TEST (testCheckEvents) private
CPPUNIT_TEST() [3/6]
TestEvent::CPPUNIT_TEST (testCreate) private
CPPUNIT_TEST() [4/6]
TestEvent::CPPUNIT_TEST (testDump) private
CPPUNIT_TEST() [5/6]
TestEvent::CPPUNIT_TEST (testFind) private
CPPUNIT_TEST() [6/6]
TestEvent::CPPUNIT_TEST (testSingleton) private
CPPUNIT_TEST_SUITE()
TestEvent::CPPUNIT_TEST_SUITE (TestEvent) private
CPPUNIT_TEST_SUITE_END()
TestEvent::CPPUNIT_TEST_SUITE_END () private
testCancel()
void TestEvent::testCancel () protected
Definition at line 65 of file testEvent.cc.
References CalledEvent::calls, EventScheduler::cancel(), EventScheduler::checkEvents(), AsyncCallQueue::fire(), CalledEvent::Handler(), AsyncCallQueue::Instance(), and EventScheduler::schedule().
testCheckEvents()
void TestEvent::testCheckEvents () protected
Definition at line 145 of file testEvent.cc.
References CalledEvent::calls, EventScheduler::checkEvents(), AsyncEngine::EVENT_IDLE, AsyncCallQueue::fire(), CalledEvent::Handler(), AsyncCallQueue::Instance(), and EventScheduler::schedule().
testCreate()
void TestEvent::testCreate () protected
Definition at line 46 of file testEvent.cc.
testDump()
void TestEvent::testDump () protected
Definition at line 81 of file testEvent.cc.
References MemBuf::append(), EventScheduler::checkEvents(), MemBuf::content(), MemBuf::contentSize(), EventScheduler::dump(), AsyncCallQueue::fire(), CalledEvent::Handler(), MemBuf::init(), AsyncCallQueue::Instance(), EventScheduler::schedule(), and size_t.
testFind()
void TestEvent::testFind () protected
Definition at line 133 of file testEvent.cc.
References EventScheduler::find(), CalledEvent::Handler(), and EventScheduler::schedule().
testSingleton()
void TestEvent::testSingleton () protected
Definition at line 166 of file testEvent.cc.
References EventScheduler::GetInstance().
The documentation for this class was generated from the following file:
squid/src/tests/testEvent.cc