Squid Web Cache: Adaptation::Icap::VirginBodyAct Class Reference
Adaptation::Icap::VirginBodyAct Class Reference
#include <ModXact.h>
Public Member Functions
VirginBodyAct ()
void plan ()
void disable ()
bool active () const
bool disabled () const
uint64_t offset () const
void progress (size_t size)
Private Types
enum State { stUndecided , stActive , stDisabled }
Private Attributes
int64_t theStart
State theState
Detailed Description
Definition at line 60 of file ModXact.h.
Member Enumeration Documentation
State
enum Adaptation::Icap::VirginBodyAct::State private
Enumerator
stUndecided
stActive
stDisabled
Definition at line 80 of file ModXact.h.
Constructor & Destructor Documentation
VirginBodyAct()
Adaptation::Icap::VirginBodyAct::VirginBodyAct ()
Definition at line 1892 of file ModXact.cc.
Member Function Documentation
active()
bool Adaptation::Icap::VirginBodyAct::active () const inline
Definition at line 69 of file ModXact.h.
References stActive, and theState.
Referenced by Adaptation::Icap::ModXact::virginBodyEndReached(), Adaptation::Icap::ModXact::virginContentData(), and Adaptation::Icap::ModXact::virginContentSize().
disable()
void Adaptation::Icap::VirginBodyAct::disable ()
Definition at line 1902 of file ModXact.cc.
disabled()
bool Adaptation::Icap::VirginBodyAct::disabled () const inline
Definition at line 70 of file ModXact.h.
References stDisabled, and theState.
offset()
uint64_t Adaptation::Icap::VirginBodyAct::offset () const
Definition at line 1917 of file ModXact.cc.
References Must.
Referenced by Adaptation::Icap::ModXact::virginBodyEndReached(), Adaptation::Icap::ModXact::virginContentData(), and Adaptation::Icap::ModXact::virginContentSize().
plan()
void Adaptation::Icap::VirginBodyAct::plan ()
Definition at line 1895 of file ModXact.cc.
References Must.
progress()
void Adaptation::Icap::VirginBodyAct::progress (size_t size)
Definition at line 1907 of file ModXact.cc.
References Must, and size.
Member Data Documentation
theStart
int64_t Adaptation::Icap::VirginBodyAct::theStart private
Definition at line 78 of file ModXact.h.
theState
State Adaptation::Icap::VirginBodyAct::theState private
Definition at line 81 of file ModXact.h.
Referenced by active(), and disabled().
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/ModXact.h
squid/src/adaptation/icap/ModXact.cc