Squid Web Cache: AnyP::PortCfg Class Reference
AnyP::PortCfg Class Reference
#include <PortCfg.h>
Public Types
typedef RefCount< CodeContext > Pointer
Public Member Functions
PortCfg ()
PortCfg (PortCfg &&)=delete
~PortCfg () override
PortCfg * ipV4clone () const
creates the same port configuration but listening on any IPv4 address
ScopedId codeContextGist () const override
std::ostream & detailCodeContext (std::ostream &os) const override
appends human-friendly context description line(s) to a cache.log record
Static Public Member Functions
static const Pointer & Current ()
static void Reset ()
forgets the current context, setting it to nil/unknown
static void Reset (const Pointer)
changes the current context; nil argument sets it to nil/unknown
Public Attributes
PortCfgPointer next
Ip::Address s
AnyP::ProtocolVersion transport
transport protocol and version received by this port
char * name
char * defaultsite
TrafficMode flags
flags indicating what type of traffic to expect via this port.
bool allow_direct
Allow direct forwarding in accelerator mode.
bool vhost
uses host header
bool actAsOrigin
update replies to conform with RFC 2616
bool ignore_cc
Ignore request Cache-Control directives.
bool connection_auth_disabled
Don't support connection oriented auth.
bool ftp_track_dirs
whether transactions should track FTP directories
int vport
virtual port support. -1 if dynamic, >0 static
int disable_pmtu_discovery
bool workerQueues
whether listening queues should be worker-specific
Comm::TcpKeepAlive tcp_keepalive
Comm::ConnectionPointer listenConn
Security::ServerOptions secure
TLS configuration options for this listening port.
Stopwatch busyTime
time spent in this context (see also: busy_time)
Private Member Functions
PortCfg (const PortCfg &other)
Static Private Member Functions
static void ForgetCurrent ()
static void Entering (const Pointer &codeCtx)
static void Leaving ()
Detailed Description
Definition at line 23 of file PortCfg.h.
Member Typedef Documentation
Pointer
typedef RefCount<CodeContext> CodeContext::Pointer inherited
Definition at line 55 of file CodeContext.h.
Constructor & Destructor Documentation
PortCfg() [1/3]
AnyP::PortCfg::PortCfg ()
Definition at line 28 of file PortCfg.cc.
References AnyP::PROTO_HTTP.
PortCfg() [2/3]
AnyP::PortCfg::PortCfg (PortCfg &&) delete
~PortCfg()
AnyP::PortCfg::~PortCfg () override
Definition at line 48 of file PortCfg.cc.
References Comm::IsConnOpen(), and safe_free.
PortCfg() [3/3]
AnyP::PortCfg::PortCfg (const PortCfg & other) explicit private
Definition at line 59 of file PortCfg.cc.
References assert, listenConn, and next.
Member Function Documentation
codeContextGist()
ScopedId AnyP::PortCfg::codeContextGist () const override virtual
Returns
a small, permanent ID of the current context gists persist forever and are suitable for passing to other SMP workers
Implements CodeContext.
Definition at line 95 of file PortCfg.cc.
Current()
const CodeContext::Pointer & CodeContext::Current () static inherited
Returns
the known global context or, to indicate unknown context, nil
Definition at line 33 of file CodeContext.cc.
Referenced by CallAndRestore_(), CallSubscription< Call_ >::callback(), CallContextCreator(), clientConnectionsClose(), clientHttpConnectionsOpen(), commStartHalfClosedMonitor(), CurrentCodeContextDetail(), HappyOrderEnforcer::enqueue(), CommQuotaQueue::enqueue(), StoreEntry::invokeHandlers(), neighborsUdpPing(), peerDnsRefreshStart(), Security::KeyLog::record(), CodeContext::Reset(), ScheduleCall(), Ftp::StartListening(), Ftp::StopListening(), tunnelDelayedClientRead(), and tunnelDelayedServerRead().
detailCodeContext()
std::ostream & AnyP::PortCfg::detailCodeContext (std::ostream & os) const override virtual
Implements CodeContext.
Definition at line 103 of file PortCfg.cc.
References Debug::Extra().
Entering()
void CodeContext::Entering (const Pointer & codeCtx) static private inherited
Switches the current context to the given known context. Improves debugging output by replacing omni-directional "Reset" with directional "Entering".
Definition at line 55 of file CodeContext.cc.
References CodeContext::busyTime, CodeContext::codeContextGist(), debugs, CodeContext::ForgetCurrent(), and Stopwatch::resume().
Referenced by CodeContext::Reset().
ForgetCurrent()
void CodeContext::ForgetCurrent () static private inherited
Forgets the current known context, possibly triggering its destruction. Preserves the gist of the being-forgotten context during its destruction. Knows nothing about the next context – the caller must set it.
Definition at line 42 of file CodeContext.cc.
References assert.
Referenced by CodeContext::Entering(), and CodeContext::Leaving().
ipV4clone()
AnyP::PortCfg * AnyP::PortCfg::ipV4clone () const
Definition at line 85 of file PortCfg.cc.
References debugs, and AnyP::UriScheme::image().
Leaving()
void CodeContext::Leaving () static private inherited
Forgets the current known context. Improves debugging output by replacing omni-directional "Reset" with directional "Leaving".
Definition at line 68 of file CodeContext.cc.
References debugs, and CodeContext::ForgetCurrent().
Referenced by CodeContext::Reset(), and CodeContext::Reset().
Reset() [1/2]
void CodeContext::Reset () static inherited
Definition at line 77 of file CodeContext.cc.
References CodeContext::Leaving().
Referenced by ClientHttpRequest::ClientHttpRequest(), CodeContextGuard::CodeContextGuard(), CodeContextGuard::~CodeContextGuard(), CallAndRestore_(), CallContextCreator(), checkTimeouts(), clientConnectionsClose(), clientHttpConnectionsOpen(), comm_close_complete(), Http::Stream::finished(), AsyncCallQueue::fire(), StoreEntry::invokeHandlers(), neighborsUdpPing(), peerCountMcastPeersCreateAndSend(), peerDnsRefreshStart(), ConnStateData::postHttpsAccept(), Ftp::StartListening(), Ftp::StopListening(), tunnelDelayedClientRead(), and tunnelDelayedServerRead().
Reset() [2/2]
void CodeContext::Reset (const Pointer codeCtx) static inherited
Definition at line 84 of file CodeContext.cc.
References CodeContext::Current(), CodeContext::Entering(), and CodeContext::Leaving().
Member Data Documentation
actAsOrigin
bool AnyP::PortCfg::actAsOrigin
Definition at line 49 of file PortCfg.h.
allow_direct
bool AnyP::PortCfg::allow_direct
Definition at line 47 of file PortCfg.h.
busyTime
Stopwatch CodeContext::busyTime inherited
Definition at line 76 of file CodeContext.h.
Referenced by Format::Format::assemble(), and CodeContext::Entering().
connection_auth_disabled
bool AnyP::PortCfg::connection_auth_disabled
Definition at line 52 of file PortCfg.h.
defaultsite
char* AnyP::PortCfg::defaultsite
Definition at line 43 of file PortCfg.h.
disable_pmtu_discovery
int AnyP::PortCfg::disable_pmtu_discovery
Definition at line 57 of file PortCfg.h.
flags
TrafficMode AnyP::PortCfg::flags
Definition at line 45 of file PortCfg.h.
ftp_track_dirs
bool AnyP::PortCfg::ftp_track_dirs
Definition at line 54 of file PortCfg.h.
ignore_cc
bool AnyP::PortCfg::ignore_cc
Definition at line 50 of file PortCfg.h.
listenConn
Comm::ConnectionPointer AnyP::PortCfg::listenConn
The listening socket details. If Comm::ConnIsOpen() we are actively listening for client requests. use listenConn->close() to stop.
Definition at line 67 of file PortCfg.h.
Referenced by PortCfg().
name
char* AnyP::PortCfg::name
Definition at line 42 of file PortCfg.h.
next
PortCfgPointer AnyP::PortCfg::next
Definition at line 38 of file PortCfg.h.
Referenced by PortCfg().
s
Ip::Address AnyP::PortCfg::s
Definition at line 40 of file PortCfg.h.
secure
Security::ServerOptions AnyP::PortCfg::secure
Definition at line 70 of file PortCfg.h.
tcp_keepalive
Comm::TcpKeepAlive AnyP::PortCfg::tcp_keepalive
Definition at line 60 of file PortCfg.h.
transport
AnyP::ProtocolVersion AnyP::PortCfg::transport
Definition at line 41 of file PortCfg.h.
vhost
bool AnyP::PortCfg::vhost
Definition at line 48 of file PortCfg.h.
vport
int AnyP::PortCfg::vport
Definition at line 56 of file PortCfg.h.
workerQueues
bool AnyP::PortCfg::workerQueues
Definition at line 58 of file PortCfg.h.
The documentation for this class was generated from the following files:
squid/src/anyp/PortCfg.h
squid/src/anyp/PortCfg.cc