Squid Web Cache: CallbackData Class Reference
CallbackData Class Reference
an old-style void* callback parameter
#include <cbdata.h>
Public Member Functions
CallbackData ()
CallbackData (void *data)
CallbackData (const CallbackData &other)
CallbackData (CallbackData &&other)
~CallbackData ()
CallbackData & operator= (const CallbackData &other)
CallbackData & operator= (CallbackData &&other)
bool valid () const
void * validDone ()
Private Attributes
void * data_
raw callback data, maybe invalid
Detailed Description
Definition at line 383 of file cbdata.h.
Constructor & Destructor Documentation
CallbackData() [1/4]
CallbackData::CallbackData () inline
Definition at line 386 of file cbdata.h.
CallbackData() [2/4]
CallbackData::CallbackData (void * data) inline
Definition at line 387 of file cbdata.h.
CallbackData() [3/4]
CallbackData::CallbackData (const CallbackData & other) inline
Definition at line 388 of file cbdata.h.
CallbackData() [4/4]
CallbackData::CallbackData (CallbackData && other) inline
Definition at line 389 of file cbdata.h.
~CallbackData()
CallbackData::~CallbackData () inline
Definition at line 390 of file cbdata.h.
References cbdataReferenceDone, and data_.
Member Function Documentation
operator=() [1/2]
CallbackData & CallbackData::operator= (CallbackData && other) inline
Definition at line 393 of file cbdata.h.
References cbdataReferenceDone, and data_.
operator=() [2/2]
CallbackData & CallbackData::operator= (const CallbackData & other)
Definition at line 305 of file cbdata.cc.
References cbdataReference, cbdataReferenceDone, and data_.
valid()
bool CallbackData::valid () const inline
Definition at line 395 of file cbdata.h.
References cbdataReferenceValid(), and data_.
Referenced by IpCacheLookupForwarder::finalCallback().
validDone()
void * CallbackData::validDone () inline
Definition at line 396 of file cbdata.h.
References cbdataReferenceValidDone, and data_.
Referenced by IpCacheLookupForwarder::finalCallback(), and store_client::finishCallback().
Member Data Documentation
data_
void* CallbackData::data_ private
Definition at line 399 of file cbdata.h.
Referenced by ~CallbackData(), operator=(), operator=(), valid(), and validDone().
The documentation for this class was generated from the following files:
squid/src/cbdata.h
squid/src/cbdata.cc