Squid Web Cache: Security::KeyLogger Class Reference
Security::KeyLogger Class Reference
manages collecting and logging secrets of a TLS connection to tls_key_log
#include <KeyLogger.h>
Public Member Functions
void checkpoint (const Connection &, const Acl::ChecklistFiller &)
Private Member Functions
void maybeLog (const Connection &, const Acl::ChecklistFiller &)
(slowly checks logging preconditions and) logs if possible
bool shouldLog (const Acl::ChecklistFiller &) const
(slowly checks) whether logging is possible now
Private Attributes
CommunicationSecrets secrets
connection secrets learned so far
bool done_ = false
whether to prevent further logging attempts
bool wanted_ = false
whether we know that the admin wants us to log this connection keys
Detailed Description
Definition at line 23 of file KeyLogger.h.
Member Function Documentation
checkpoint()
void Security::KeyLogger::checkpoint (const Connection & sconn, const Acl::ChecklistFiller & caller) inline
(quickly decides whether logging might be needed and) logs if possible this method is a performance optimization wrapper for slower maybeLog()
Definition at line 50 of file KeyLogger.h.
References done_, and maybeLog().
Referenced by ConnStateData::acceptTls().
maybeLog()
void Security::KeyLogger::maybeLog (const Connection & sconn, const Acl::ChecklistFiller & caller) private
Definition at line 22 of file KeyLogger.cc.
References Config, done_, Security::CommunicationSecrets::gotAll(), Security::CommunicationSecrets::learnNew(), SquidConfig::Log, Security::KeyLog::record(), secrets, shouldLog(), and SquidConfig::tlsKeys.
Referenced by checkpoint().
shouldLog()
bool Security::KeyLogger::shouldLog (const Acl::ChecklistFiller & caller) const private
Definition at line 44 of file KeyLogger.cc.
References FormattedLog::aclList, Acl::Answer::allowed(), Security::KeyLog::canLog(), Config, debugs, ACLChecklist::fastCheck(), Acl::ChecklistFiller::fillChecklist(), SquidConfig::Log, and SquidConfig::tlsKeys.
Referenced by maybeLog().
Member Data Documentation
done_
bool Security::KeyLogger::done_ = false private
Definition at line 41 of file KeyLogger.h.
Referenced by checkpoint(), and maybeLog().
secrets
CommunicationSecrets Security::KeyLogger::secrets private
Definition at line 38 of file KeyLogger.h.
Referenced by maybeLog().
wanted_
bool Security::KeyLogger::wanted_ = false mutable private
Definition at line 44 of file KeyLogger.h.
The documentation for this class was generated from the following files:
squid/src/security/KeyLogger.h
squid/src/security/KeyLogger.cc