Squid Web Cache: HttpHeaderEntry Class Reference
HttpHeaderEntry Class Reference
#include <HttpHeader.h>
Public Member Functions
HttpHeaderEntry (Http::HdrType id, const SBuf &name, const char *value)
~HttpHeaderEntry ()
HttpHeaderEntry * clone () const
void packInto (Packable *p) const
int getInt () const
int64_t getInt64 () const
size_t length () const
expected number of bytes written by packInto(), including ": " and CRLF
Static Public Member Functions
static HttpHeaderEntry * parse (const char *field_start, const char *field_end, const http_hdr_owner_type msgType)
Public Attributes
Http::HdrType id
SBuf name
String value
Private Member Functions
MEMPROXY_CLASS (HttpHeaderEntry)
Detailed Description
Definition at line 50 of file HttpHeader.h.
Constructor & Destructor Documentation
HttpHeaderEntry()
HttpHeaderEntry::HttpHeaderEntry (Http::HdrType id, const SBuf & name, const char * value)
Definition at line 1493 of file HttpHeader.cc.
References assert, Http::BAD_HDR, debugs, Http::HeaderLookupTable, headerStatsTable(), id, Http::HeaderLookupTable_t::lookup(), Http::HeaderTableRecord::name, name, Http::OTHER, and value.
~HttpHeaderEntry()
HttpHeaderEntry::~HttpHeaderEntry ()
Definition at line 1511 of file HttpHeader.cc.
References assert, Http::BAD_HDR, debugs, headerStatsTable(), id, name, and value.
Member Function Documentation
clone()
HttpHeaderEntry * HttpHeaderEntry::clone () const
Definition at line 1639 of file HttpHeader.cc.
References name, String::termedBuf(), and value.
Referenced by copyOneHeaderFromClientsideRequestToUpstreamRequest(), HttpReply::make304(), and HttpHeader::update().
getInt()
int HttpHeaderEntry::getInt () const
Definition at line 1655 of file HttpHeader.cc.
References httpHeaderNoteParsedEntry(), httpHeaderParseInt(), String::termedBuf(), and value.
Referenced by HttpHeader::getInt().
getInt64()
int64_t HttpHeaderEntry::getInt64 () const
Definition at line 1667 of file HttpHeader.cc.
References httpHeaderNoteParsedEntry(), httpHeaderParseOffset(), String::termedBuf(), and value.
Referenced by copyOneHeaderFromClientsideRequestToUpstreamRequest(), and HttpHeader::getInt64().
length()
size_t HttpHeaderEntry::length () const inline
Definition at line 64 of file HttpHeader.h.
References SBuf::length(), name, String::size(), and value.
Referenced by HttpHeader::addEntry().
MEMPROXY_CLASS()
HttpHeaderEntry::MEMPROXY_CLASS (HttpHeaderEntry) private
packInto()
void HttpHeaderEntry::packInto (Packable * p) const
Definition at line 1645 of file HttpHeader.cc.
References Packable::append(), assert, SBuf::length(), name, String::rawBuf(), SBuf::rawContent(), String::size(), and value.
Referenced by HttpHeader::packInto().
parse()
HttpHeaderEntry * HttpHeaderEntry::parse (const char * field_start, const char * field_end, const http_hdr_owner_type msgType) static
Definition at line 1525 of file HttpHeader.cc.
References SBuf::append(), String::assign(), Http::BAD_HDR, Config, debugs, getStringPrefix(), HeaderEntryParsedCount, Http::HeaderLookupTable, headerStatsTable(), hoReply, hoRequest, Http::HeaderTableRecord::id, id, Http::HeaderLookupTable_t::lookup(), min(), Http::HeaderTableRecord::name, SquidConfig::onoff, Http::OTHER, SquidConfig::relaxed_header_parser, CharacterSet::TCHAR, String::termedBuf(), value, and xisspace.
Referenced by HttpHeader::parse().
Member Data Documentation
id
Http::HdrType HttpHeaderEntry::id
Definition at line 66 of file HttpHeader.h.
Referenced by HttpHeaderEntry(), ~HttpHeaderEntry(), HttpHeader::addEntry(), clientReplyContext::buildReplyHeader(), clientCheckPinning(), copyOneHeaderFromClientsideRequestToUpstreamRequest(), HeaderManglers::find(), HttpHeader::getContRange(), HttpHeader::getLastStr(), HttpHeader::getList(), HttpHeader::getRange(), HttpHeader::getStr(), HttpHeader::getTime(), HttpHeader::hasNamed(), HttpHeader::packInto(), parse(), HttpHeader::removeHopByHopEntries(), and HttpHeader::update().
name
SBuf HttpHeaderEntry::name
Definition at line 67 of file HttpHeader.h.
Referenced by HttpHeaderEntry(), ~HttpHeaderEntry(), HttpHeader::addEntry(), clone(), copyOneHeaderFromClientsideRequestToUpstreamRequest(), HttpHeader::delAt(), HeaderManglers::find(), HttpHeader::hasNamed(), length(), packInto(), HttpHeader::packInto(), HttpHeader::removeConnectionHeaderEntries(), and HttpHeader::update().
value
String HttpHeaderEntry::value
Definition at line 68 of file HttpHeader.h.
Referenced by HttpHeaderEntry(), ~HttpHeaderEntry(), clientReplyContext::buildReplyHeader(), clientCheckPinning(), clone(), copyOneHeaderFromClientsideRequestToUpstreamRequest(), HttpHeader::delAt(), HttpHeader::getContRange(), HttpHeader::getETag(), getInt(), getInt64(), HttpHeader::getLastStr(), HttpHeader::getList(), HttpHeader::getRange(), HttpHeader::getStr(), HttpHeader::getStrOrList(), HttpHeader::getTime(), HttpHeader::getTimeOrTag(), Ftp::Server::handleRequest(), HttpHeader::hasNamed(), httpHdrMangle(), length(), packInto(), parse(), and Ftp::Relay::sendCommand().
The documentation for this class was generated from the following files:
squid/src/HttpHeader.h
squid/src/HttpHeader.cc
squid/src/tests/stub_HttpHeader.cc