Squid Web Cache: Aggregate Class Reference
Aggregate Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Classes
class AggregateId
Public Types
typedef RefCount< Aggregate > Pointer
Public Member Functions
void * operator new (size_t byteCount)
void operator delete (void *address)
Aggregate ()
~Aggregate () override
virtual DelaySpec * rate ()
virtual DelaySpec const * rate () const
void stats (StoreEntry *sentry) override
void dump (StoreEntry *entry) const override
void update (int incr) override
void parse () override
DelayIdComposite::Pointer id (CompositeSelectionDetails &) override
void delayRead (const AsyncCallPointer &)
Static Public Member Functions
static int UseCount ()
Protected Member Functions
void kickReads ()
Protected Attributes
DelayedAsyncCalls deferredReads
Private Member Functions
MEMPROXY_CLASS (CompositePoolNode)
Static Private Member Functions
static Mem::AllocatorProxy & Pool ()
Private Attributes
DelayBucket theBucket
DelaySpec spec
Friends
class AggregateId
Detailed Description
Definition at line 43 of file delay_pools.cc.
Member Typedef Documentation
Pointer
typedef RefCount<Aggregate> Aggregate::Pointer
Definition at line 48 of file delay_pools.cc.
Constructor & Destructor Documentation
Aggregate()
Aggregate::Aggregate ()
Definition at line 377 of file delay_pools.cc.
References DelayBucket::init(), rate(), DelayPools::registerForUpdates(), and theBucket.
Referenced by CommonPool::Factory().
~Aggregate()
Aggregate::~Aggregate () override
Definition at line 383 of file delay_pools.cc.
References DelayPools::deregisterForUpdates().
Member Function Documentation
delayRead()
void CompositePoolNode::delayRead (const AsyncCallPointer & aRead) inherited
Definition at line 80 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::delay().
Referenced by Aggregate::AggregateId::delayRead().
dump()
void Aggregate::dump (StoreEntry * entry) const override virtual
Implements CompositePoolNode.
Definition at line 404 of file delay_pools.cc.
References DelaySpec::dump(), and rate().
id()
DelayIdComposite::Pointer Aggregate::id (CompositeSelectionDetails &) override virtual
Implements CompositePoolNode.
Definition at line 423 of file delay_pools.cc.
References rate().
kickReads()
void CompositePoolNode::kickReads () protected inherited
Definition at line 88 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::schedule().
Referenced by update(), DelayTagged::update(), and DelayVector::update().
MEMPROXY_CLASS()
CompositePoolNode::MEMPROXY_CLASS (CompositePoolNode) private inherited
operator delete()
void Aggregate::operator delete (void * address) inline
Definition at line 45 of file delay_pools.cc.
operator new()
void * Aggregate::operator new (size_t byteCount) inline
Definition at line 45 of file delay_pools.cc.
parse()
void Aggregate::parse () override virtual
Implements CompositePoolNode.
Definition at line 417 of file delay_pools.cc.
References DelaySpec::parse(), and rate().
Pool()
static Mem::AllocatorProxy & Aggregate::Pool () inline static private
Definition at line 45 of file delay_pools.cc.
rate() [1/2]
virtual DelaySpec * Aggregate::rate () inline virtual
Definition at line 51 of file delay_pools.cc.
References spec.
Referenced by Aggregate(), dump(), ClassCBucket::hostPosition(), id(), ClassCBucket::initHostIndex(), parse(), stats(), ClassCBucket::update(), and update().
rate() [2/2]
virtual DelaySpec const * Aggregate::rate () const inline virtual
Definition at line 53 of file delay_pools.cc.
References spec.
stats()
void Aggregate::stats (StoreEntry * sentry) override virtual
Implements CompositePoolNode.
Definition at line 389 of file delay_pools.cc.
References rate(), DelayBucket::stats(), DelaySpec::stats(), storeAppendPrintf(), and theBucket.
update()
void Aggregate::update (int incr) override virtual
Implements CompositePoolNode.
Definition at line 410 of file delay_pools.cc.
References CompositePoolNode::kickReads(), rate(), theBucket, and DelayBucket::update().
UseCount()
static int Aggregate::UseCount () inline static
Definition at line 45 of file delay_pools.cc.
Friends And Related Symbol Documentation
AggregateId
friend class AggregateId friend
Definition at line 79 of file delay_pools.cc.
Member Data Documentation
deferredReads
DelayedAsyncCalls CompositePoolNode::deferredReads protected inherited
Definition at line 60 of file CompositePoolNode.h.
Referenced by CompositePoolNode::delayRead(), and CompositePoolNode::kickReads().
spec
DelaySpec Aggregate::spec private
Definition at line 82 of file delay_pools.cc.
Referenced by rate(), and rate().
theBucket
DelayBucket Aggregate::theBucket private
Definition at line 81 of file delay_pools.cc.
Referenced by Aggregate(), stats(), and update().
The documentation for this class was generated from the following file:
squid/src/delay_pools.cc