Squid Web Cache: Eui::Eui64 Class Reference
Eui::Eui64 Class Reference
#include <Eui64.h>
Public Member Functions
Eui64 ()
bool operator== (const Eui64 &t) const
bool operator< (const Eui64 &t) const
const unsigned char * get (void)
bool set (const char *src, const int len)
void clear ()
bool decode (const char *asc)
bool encode (char *buf, const int len) const
bool lookup (const Ip::Address &c)
bool lookupNdp (const Ip::Address &c)
bool lookupSlaac (const Ip::Address &c)
Private Attributes
unsigned char eui [SZ_EUI64_BUF]
Detailed Description
Definition at line 34 of file Eui64.h.
Constructor & Destructor Documentation
Eui64()
Eui::Eui64::Eui64 () inline
Definition at line 38 of file Eui64.h.
References clear().
Member Function Documentation
clear()
void Eui::Eui64::clear () inline
Definition at line 52 of file Eui64.h.
References eui, and SZ_EUI64_BUF.
Referenced by Eui64(), and set().
decode()
bool Eui::Eui64::decode (const char * asc)
Decode an ascii representation of an EUI-64 address.
Parameters
asc ASCII representation of an EUI-64 address
eth Binary representation of the EUI_64 address
Return values
false Conversion to binary failed. Invalid address
true Conversion completed successfully
Definition at line 22 of file Eui64.cc.
References debugs, eui, and eui64_aton().
Referenced by aclParseEuiData().
encode()
bool Eui::Eui64::encode (char * buf, const int len) const
Encode an ascii representation (asc) of an EUI-64 address.
Parameters
buf Buffer to receive ASCII representation of an EUI-64 address
len Length of the buffer space available. Must be >= SZ_EUI64_BUF bytes or the encode will fail.
eui Binary representation of the EUI-64 address
Return values
false Conversion to ASCII failed.
true Conversion completed successfully.
Definition at line 34 of file Eui64.cc.
References debugs, and SZ_EUI64_BUF.
Referenced by Format::Format::assemble().
get()
const unsigned char * Eui::Eui64::get (void)
lookup()
bool Eui::Eui64::lookup (const Ip::Address & c)
Definition at line 47 of file Eui64.cc.
Referenced by Comm::TcpAcceptor::acceptInto(), and ACLEui64::match().
lookupNdp()
bool Eui::Eui64::lookupNdp (const Ip::Address & c)
Definition at line 78 of file Eui64.cc.
References DBG_CRITICAL, and debugs.
lookupSlaac()
bool Eui::Eui64::lookupSlaac (const Ip::Address & c)
Definition at line 58 of file Eui64.cc.
References debugs, Ip::Address::getInAddr(), Ip::Address::isSiteLocal6(), Ip::Address::isSiteLocalAuto(), and SZ_EUI64_BUF.
operator<()
bool Eui::Eui64::operator< (const Eui64 & t) const inline
Definition at line 41 of file Eui64.h.
References eui, and SZ_EUI64_BUF.
operator==()
bool Eui::Eui64::operator== (const Eui64 & t) const inline
Definition at line 40 of file Eui64.h.
References eui, and SZ_EUI64_BUF.
set()
bool Eui::Eui64::set (const char * src, const int len) inline
Definition at line 45 of file Eui64.h.
References clear(), eui, and SZ_EUI64_BUF.
Member Data Documentation
eui
unsigned char Eui::Eui64::eui[SZ_EUI64_BUF] private
Definition at line 85 of file Eui64.h.
Referenced by clear(), decode(), operator<(), operator==(), and set().
The documentation for this class was generated from the following files:
squid/src/eui/Eui64.h
squid/src/eui/Eui64.cc