Squid Web Cache: Adaptation::Ecap::Host Class Reference
Adaptation::Ecap::Host Class Reference
#include <Host.h>
Public Types
typedef libecap::shared_ptr< libecap::Message > MessagePtr
Public Member Functions
std::string uri () const override
void describe (std::ostream &os) const override
void noteVersionedService (const char *libEcapVersion, const libecap::weak_ptr< libecap::adapter::Service > &s) override
std::ostream * openDebug (libecap::LogVerbosity lv) override
void closeDebug (std::ostream *debug) override
MessagePtr newRequest () const override
MessagePtr newResponse () const override
Static Public Member Functions
static void Register ()
register adaptation host
Private Member Functions
Host ()
Host (const Host &)
not implemented
Host & operator= (const Host &)
not implemented
Detailed Description
Definition at line 24 of file Host.h.
Member Typedef Documentation
MessagePtr
typedef libecap::shared_ptr<libecap::Message> Adaptation::Ecap::Host::MessagePtr
Definition at line 33 of file Host.h.
Constructor & Destructor Documentation
Host() [1/2]
Adaptation::Ecap::Host::Host () private
Definition at line 43 of file Host.cc.
References Http::CONTENT_LENGTH, Adaptation::Ecap::metaBypassable, AnyP::PROTO_FTP, AnyP::PROTO_HTCP, AnyP::PROTO_HTTP, AnyP::PROTO_HTTPS, AnyP::PROTO_ICP, AnyP::PROTO_ICY, AnyP::PROTO_UNKNOWN, AnyP::PROTO_URN, AnyP::PROTO_WAIS, AnyP::PROTO_WHOIS, Adaptation::Ecap::protocolHtcp, Adaptation::Ecap::protocolIcp, Adaptation::Ecap::protocolIcy, Adaptation::Ecap::protocolUnknown, Http::REFERER, Http::TRANSFER_ENCODING, and Http::VIA.
Host() [2/2]
Adaptation::Ecap::Host::Host (const Host &) private
Member Function Documentation
closeDebug()
void Adaptation::Ecap::Host::closeDebug (std::ostream * debug) override
Definition at line 161 of file Host.cc.
References debug(), and Debug::Finish().
describe()
void Adaptation::Ecap::Host::describe (std::ostream & os) const override
Definition at line 79 of file Host.cc.
References PACKAGE_NAME, and PACKAGE_VERSION.
newRequest()
Adaptation::Ecap::Host::MessagePtr Adaptation::Ecap::Host::newRequest () const override
Definition at line 168 of file Host.cc.
newResponse()
Adaptation::Ecap::Host::MessagePtr Adaptation::Ecap::Host::newResponse () const override
Definition at line 175 of file Host.cc.
noteVersionedService()
void Adaptation::Ecap::Host::noteVersionedService (const char * libEcapVersion, const libecap::weak_ptr< libecap::adapter::Service > & s) override
Definition at line 121 of file Host.cc.
References Must, Adaptation::Ecap::RegisterAdapterService(), and SupportedVersion().
openDebug()
std::ostream * Adaptation::Ecap::Host::openDebug (libecap::LogVerbosity lv) override
Definition at line 151 of file Host.cc.
References Debug::Enabled(), SquidLogLevel(), and Debug::Start().
operator=()
Host & Adaptation::Ecap::Host::operator= (const Host &) private
Register()
void Adaptation::Ecap::Host::Register () static
Definition at line 181 of file Host.cc.
References SupportedVersion(), and TheHost.
Referenced by Adaptation::Ecap::Config::finalize().
uri()
std::string Adaptation::Ecap::Host::uri () const override
Definition at line 73 of file Host.cc.
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/Host.h
squid/src/adaptation/ecap/Host.cc