Squid Web Cache: Ssl::OneNameMatcher Class Reference
Ssl::OneNameMatcher Class Reference
GeneralNameMatcher for matching a single AnyP::Host given at construction time.
Public Member Functions
OneNameMatcher (const AnyP::Host &needle)
bool match (const Ssl::GeneralName &) const
whether the given name satisfies algorithm conditions
Protected Member Functions
bool matchDomainName (const Dns::DomainName &) const override
bool matchIp (const Ip::Address &) const override
Protected Attributes
AnyP::Host needle_
a name we are looking for
Detailed Description
Definition at line 61 of file support.cc.
Constructor & Destructor Documentation
OneNameMatcher()
Ssl::OneNameMatcher::OneNameMatcher (const AnyP::Host & needle) inline explicit
Definition at line 64 of file support.cc.
Member Function Documentation
match()
bool Ssl::GeneralNameMatcher::match (const Ssl::GeneralName & name) const inherited
Definition at line 84 of file support.cc.
References Assure, AnyP::Host::domainName(), AnyP::Host::ip(), Ssl::GeneralNameMatcher::matchDomainName(), and Ssl::GeneralNameMatcher::matchIp().
Referenced by Ssl::HasMatchingSubjectName().
matchDomainName()
bool Ssl::OneNameMatcher::matchDomainName (const Dns::DomainName & rawName) const override protected virtual
Implements Ssl::GeneralNameMatcher.
Definition at line 95 of file support.cc.
References Assure, SBuf::consume(), debugs, and mdnRejectSubsubDomains.
matchIp()
bool Ssl::OneNameMatcher::matchIp (const Ip::Address & ip) const override protected virtual
Implements Ssl::GeneralNameMatcher.
Definition at line 117 of file support.cc.
References debugs.
Member Data Documentation
needle_
AnyP::Host Ssl::OneNameMatcher::needle_ protected
Definition at line 71 of file support.cc.
The documentation for this class was generated from the following file:
squid/src/ssl/support.cc