Squid Web Cache: Adaptation::Message Class Reference
Adaptation::Message Class Reference
#include <Message.h>
Public Types
typedef Http::Message Header
Public Member Functions
Message ()
Message (Header *aHeader)
~Message ()
void clear ()
void set (Header *aHeader)
Static Public Member Functions
static void ShortCircuit (Message &src, Message &dest)
Public Attributes
Header * header
BodyPipePointer body_pipe
Private Member Functions
Message (const Message &)
Message & operator= (const Message &)
Detailed Description
Definition at line 25 of file Message.h.
Member Typedef Documentation
Header
typedef Http::Message Adaptation::Message::Header
Definition at line 29 of file Message.h.
Constructor & Destructor Documentation
Message() [1/3]
Adaptation::Message::Message ()
Definition at line 17 of file Message.cc.
Message() [2/3]
Adaptation::Message::Message (Header * aHeader)
Definition at line 21 of file Message.cc.
References set().
~Message()
Adaptation::Message::~Message ()
Definition at line 26 of file Message.cc.
Message() [3/3]
Adaptation::Message::Message (const Message &) private
Member Function Documentation
clear()
void Adaptation::Message::clear ()
Definition at line 32 of file Message.cc.
References HTTPMSGUNLOCK().
operator=()
Message & Adaptation::Message::operator= (const Message &) private
set()
void Adaptation::Message::set (Header * aHeader)
Definition at line 39 of file Message.cc.
References HTTPMSGLOCK().
Referenced by Message(), and ShortCircuit().
ShortCircuit()
void Adaptation::Message::ShortCircuit (Message & src, Message & dest) static
Definition at line 50 of file Message.cc.
References body_pipe, Http::Message::body_pipe, BodyPipe::clearConsumer(), Http::Message::clone(), BodyPipe::consumedSize(), header, Must, and set().
Member Data Documentation
body_pipe
BodyPipePointer Adaptation::Message::body_pipe
Copy of header->body_pipe, in case somebody moves the original. TODO: Find and fix the code that moves (if any) and remove this.
Definition at line 46 of file Message.h.
Referenced by Adaptation::Ecap::MessageRep::MessageRep(), ShortCircuit(), and Adaptation::Ecap::XactionRep::status().
header
Header* Adaptation::Message::header
Definition at line 42 of file Message.h.
Referenced by Adaptation::Ecap::MessageRep::MessageRep(), and ShortCircuit().
The documentation for this class was generated from the following files:
squid/src/adaptation/Message.h
squid/src/adaptation/Message.cc