Squid Web Cache: DelayUserBucket Class Reference
DelayUserBucket Class Reference
Squid Components » Delay Pools API
#include <DelayUser.h>
Public Types
typedef RefCount< DelayUserBucket > Pointer
Public Member Functions
void stats (StoreEntry *) const
DelayUserBucket (Auth::User::Pointer)
~DelayUserBucket () override
Public Attributes
DelayBucket theBucket
Auth::User::Pointer authUser
Private Member Functions
MEMPROXY_CLASS (DelayUserBucket)
Detailed Description
Definition at line 25 of file DelayUser.h.
Member Typedef Documentation
Pointer
typedef RefCount<DelayUserBucket> DelayUserBucket::Pointer
Definition at line 30 of file DelayUser.h.
Constructor & Destructor Documentation
DelayUserBucket()
DelayUserBucket::DelayUserBucket (Auth::User::Pointer aUser)
Definition at line 124 of file DelayUser.cc.
References debugs.
~DelayUserBucket()
DelayUserBucket::~DelayUserBucket () override
Definition at line 129 of file DelayUser.cc.
References authUser, and debugs.
Member Function Documentation
MEMPROXY_CLASS()
DelayUserBucket::MEMPROXY_CLASS (DelayUserBucket) private
stats()
void DelayUserBucket::stats (StoreEntry * entry) const
Definition at line 136 of file DelayUser.cc.
References authUser, DelayBucket::stats(), storeAppendPrintf(), and theBucket.
Referenced by DelayUserStatsVisitor::operator()().
Member Data Documentation
authUser
Auth::User::Pointer DelayUserBucket::authUser
Definition at line 36 of file DelayUser.h.
Referenced by ~DelayUserBucket(), DelayUserCmp(), and stats().
theBucket
DelayBucket DelayUserBucket::theBucket
Definition at line 35 of file DelayUser.h.
Referenced by DelayUser::Id::Id(), and stats().
The documentation for this class was generated from the following files:
squid/src/DelayUser.h
squid/src/DelayUser.cc