Squid Web Cache: Http::HeaderLookupTable_t Class Reference
Http::HeaderLookupTable_t Class Reference
#include <RegisteredHeaders.h>
Public Member Functions
HeaderLookupTable_t ()
const HeaderTableRecord & lookup (const char *buf, const std::size_t len) const
look record type up by name (C-string and length)
const HeaderTableRecord & lookup (const std::string &key) const
look record type up by name (std::string)
const HeaderTableRecord & lookup (const SBuf &key) const
look record type up by name (SBuf)
const HeaderTableRecord & lookup (Http::HdrType id) const
look record type up by header ID
Private Member Functions
void initCache ()
Private Attributes
std::vector< const HeaderTableRecord * > idCache
Static Private Attributes
static const HeaderTableRecord BadHdr {"*INVALID*:", Http::HdrType::BAD_HDR, Http::HdrFieldType::ftInvalid, HdrKind::None}
used to signal "not found" from lookups
Detailed Description
Class for looking up registered header definitions
Look up HeaderTableRecord's by name or registered header ID.
Actual records are defined in file RegisteredHeadersHash.gperf, which is compiled using gperf to RegisteredHeadersHash.cci which is then included in RegisteredHeaders.cc.
Definition at line 177 of file RegisteredHeaders.h.
Constructor & Destructor Documentation
HeaderLookupTable_t()
Http::HeaderLookupTable_t::HeaderLookupTable_t ()
Definition at line 40 of file RegisteredHeaders.cc.
References initCache().
Member Function Documentation
initCache()
void Http::HeaderLookupTable_t::initCache () private
Definition at line 46 of file RegisteredHeaders.cc.
References assert, HttpHeaderDefinitionsTable, idCache, MAX_HASH_VALUE, MIN_HASH_VALUE, and TOTAL_KEYWORDS.
Referenced by HeaderLookupTable_t().
lookup() [1/4]
const HeaderTableRecord & Http::HeaderLookupTable_t::lookup (const char * buf, const std::size_t len) const
Definition at line 32 of file RegisteredHeaders.cc.
References BadHdr, Http::HeaderTableRecord::id, HttpHeaderHashTable::lookup(), and Http::OTHER.
Referenced by HttpHeaderEntry::HttpHeaderEntry(), clientFollowXForwardedForCheck(), HttpHeader::hasNamed(), httpHeaderFieldStatDumper(), lookup(), lookup(), Http::operator<<(), ACLHTTPHeaderData::parse(), HttpHeaderEntry::parse(), parse_HeaderWithAclList(), and HeaderManglers::track().
lookup() [2/4]
const HeaderTableRecord & Http::HeaderLookupTable_t::lookup (const SBuf & key) const inline
Definition at line 187 of file RegisteredHeaders.h.
References SBuf::length(), lookup(), and SBuf::rawContent().
lookup() [3/4]
const HeaderTableRecord & Http::HeaderLookupTable_t::lookup (const std::string & key) const inline
Definition at line 183 of file RegisteredHeaders.h.
References lookup().
lookup() [4/4]
const HeaderTableRecord & Http::HeaderLookupTable_t::lookup (Http::HdrType id) const inline
Definition at line 191 of file RegisteredHeaders.h.
References idCache.
Member Data Documentation
BadHdr
const HeaderTableRecord Http::HeaderLookupTable_t::BadHdr {"*INVALID*:", Http::HdrType::BAD_HDR, Http::HdrFieldType::ftInvalid, HdrKind::None} static private
Definition at line 198 of file RegisteredHeaders.h.
Referenced by lookup().
idCache
std::vector<const HeaderTableRecord *> Http::HeaderLookupTable_t::idCache private
Definition at line 197 of file RegisteredHeaders.h.
Referenced by initCache(), and lookup().
The documentation for this class was generated from the following files:
squid/src/http/RegisteredHeaders.h
squid/src/http/RegisteredHeaders.cc
squid/src/tests/stub_libhttp.cc