Squid Web Cache: SupportOrVeto Class Reference
SupportOrVeto Class Reference
a boolean flag that is false by default and becomes permanently false if vetoed
#include <SupportOrVeto.h>
Public Member Functions
bool decision () const
either the current explicit decision or, by default, false
operator bool () const
either the current explicit decision or, by default, false
void support ()
void veto ()
makes decision() false regardless of past or future support() calls
Private Attributes
std::optional< bool > decision_
current decision (if any)
Detailed Description
Definition at line 15 of file SupportOrVeto.h.
Member Function Documentation
decision()
bool SupportOrVeto::decision () const inline
Definition at line 19 of file SupportOrVeto.h.
References decision_.
Referenced by operator bool().
operator bool()
SupportOrVeto::operator bool () const inline
Definition at line 22 of file SupportOrVeto.h.
References decision().
support()
void SupportOrVeto::support () inline
Makes (or keeps) decision() true in the absence of veto() calls. No effect if veto() has been called.
Definition at line 26 of file SupportOrVeto.h.
References decision_.
Referenced by clientInterpretRequestHeaders(), TestRock::createEntry(), peerDigestRequest(), storeDigestRewriteStart(), and TestUfs::testUfsSearch().
veto()
void SupportOrVeto::veto () inline
Definition at line 29 of file SupportOrVeto.h.
References decision_.
Referenced by clientInterpretRequestHeaders(), RequestFlags::disableCacheUse(), ClientRequestContext::hostHeaderVerifyFailed(), and HttpStateData::httpBuildRequestHeader().
Member Data Documentation
decision_
std::optional<bool> SupportOrVeto::decision_ private
Definition at line 33 of file SupportOrVeto.h.
Referenced by decision(), support(), and veto().
The documentation for this class was generated from the following file:
squid/src/base/SupportOrVeto.h