Squid Web Cache: Adaptation::Ecap::StatusLineRep Class Reference
Adaptation::Ecap::StatusLineRep Class Reference
#include <MessageRep.h>
Public Types
typedef libecap::Name Name
typedef libecap::Area Area
Public Member Functions
StatusLineRep (HttpReply &aMessage)
void statusCode (int code) override
int statusCode () const override
void reasonPhrase (const Area &phrase) override
Area reasonPhrase () const override
libecap::Version version () const override
void version (const libecap::Version &aVersion) override
Name protocol () const override
void protocol (const Name &aProtocol) override
Static Protected Member Functions
static AnyP::ProtocolType TranslateProtocolId (const Name &name)
Private Attributes
HttpReply & theMessage
Detailed Description
Definition at line 111 of file MessageRep.h.
Member Typedef Documentation
Area
typedef libecap::Area Adaptation::Ecap::StatusLineRep::Area
Definition at line 115 of file MessageRep.h.
Name
typedef libecap::Name Adaptation::Ecap::StatusLineRep::Name
Definition at line 114 of file MessageRep.h.
Constructor & Destructor Documentation
StatusLineRep()
Adaptation::Ecap::StatusLineRep::StatusLineRep (HttpReply & aMessage)
Definition at line 285 of file MessageRep.cc.
Member Function Documentation
protocol() [1/2]
libecap::Name Adaptation::Ecap::StatusLineRep::protocol () const override
Definition at line 330 of file MessageRep.cc.
References Adaptation::Ecap::FirstLineRep::protocol().
protocol() [2/2]
void Adaptation::Ecap::StatusLineRep::protocol (const Name & aProtocol) override
Definition at line 336 of file MessageRep.cc.
References Adaptation::Ecap::FirstLineRep::protocol().
reasonPhrase() [1/2]
Adaptation::Ecap::StatusLineRep::Area Adaptation::Ecap::StatusLineRep::reasonPhrase () const override
Definition at line 312 of file MessageRep.cc.
reasonPhrase() [2/2]
void Adaptation::Ecap::StatusLineRep::reasonPhrase (const Area & phrase) override
Definition at line 304 of file MessageRep.cc.
statusCode() [1/2]
int Adaptation::Ecap::StatusLineRep::statusCode () const override
Definition at line 297 of file MessageRep.cc.
statusCode() [2/2]
void Adaptation::Ecap::StatusLineRep::statusCode (int code) override
Definition at line 291 of file MessageRep.cc.
TranslateProtocolId()
AnyP::ProtocolType Adaptation::Ecap::FirstLineRep::TranslateProtocolId (const Name & name) static protected inherited
Definition at line 189 of file MessageRep.cc.
References AnyP::PROTO_UNKNOWN.
version() [1/2]
libecap::Version Adaptation::Ecap::StatusLineRep::version () const override
Definition at line 318 of file MessageRep.cc.
References Adaptation::Ecap::FirstLineRep::version().
version() [2/2]
void Adaptation::Ecap::StatusLineRep::version (const libecap::Version & aVersion) override
Definition at line 324 of file MessageRep.cc.
References Adaptation::Ecap::FirstLineRep::version().
Member Data Documentation
theMessage
HttpReply& Adaptation::Ecap::StatusLineRep::theMessage private
Definition at line 131 of file MessageRep.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/MessageRep.h
squid/src/adaptation/ecap/MessageRep.cc