Squid Web Cache: HttpHdrSc Class Reference
HttpHdrSc Class Reference
#include <HttpHdrSc.h>
Public Member Functions
bool parse (const String *str)
void packInto (Packable *p) const
void updateStats (StatHist *) const
HttpHdrScTarget * getMergedTarget (const char *ourtarget)
void setMaxAge (char const *target, int max_age)
Private Member Functions
MEMPROXY_CLASS (HttpHdrSc)
HttpHdrScTarget * findTarget (const char *target)
Private Attributes
std::list< HttpHdrScTarget, PoolingAllocator< HttpHdrScTarget > > targets
Detailed Description
Definition at line 24 of file HttpHdrSc.h.
Member Function Documentation
findTarget()
HttpHdrScTarget * HttpHdrSc::findTarget (const char * target) private
Definition at line 279 of file HttpHdrSc.cc.
References targets.
Referenced by getMergedTarget(), parse(), and setMaxAge().
getMergedTarget()
HttpHdrScTarget * HttpHdrSc::getMergedTarget (const char * ourtarget)
Definition at line 290 of file HttpHdrSc.cc.
References findTarget(), and HttpHdrScTarget::mergeWith().
Referenced by HttpStateData::processSurrogateControl().
MEMPROXY_CLASS()
HttpHdrSc::MEMPROXY_CLASS (HttpHdrSc) private
packInto()
void HttpHdrSc::packInto (Packable * p) const
Definition at line 223 of file HttpHdrSc.cc.
References assert, and targets.
Referenced by HttpHeader::putSc().
parse()
bool HttpHdrSc::parse (const String * str)
Definition at line 73 of file HttpHdrSc.cc.
References assert, HttpHdrScTarget::clearContent(), HttpHdrScTarget::clearMaxAge(), HttpHdrScTarget::clearMaxStale(), HttpHdrScTarget::content_, debugs, findTarget(), httpHeaderParseInt(), httpHeaderParseQuotedString(), HttpHdrScTarget::isSet(), HttpHdrScTarget::maxAge(), HttpHdrScTarget::maxStale(), HttpHdrScTarget::noStore(), HttpHdrScTarget::noStoreRemote(), safe_free, SC_CONTENT, SC_ENUM_END, SC_MAX_AGE, SC_NO_STORE, SC_NO_STORE_REMOTE, SC_OTHER, scLookupTable, HttpHdrScTarget::setMask(), strListGetItem(), targets, and xstrndup().
Referenced by httpHdrScParseCreate().
setMaxAge()
void HttpHdrSc::setMaxAge (char const * target, int max_age)
Definition at line 233 of file HttpHdrSc.cc.
References findTarget(), HttpHdrScTarget::maxAge(), and targets.
updateStats()
void HttpHdrSc::updateStats (StatHist * hist) const
Definition at line 245 of file HttpHdrSc.cc.
References targets.
Referenced by HttpHeader::getSc().
Member Data Documentation
targets
std::list<HttpHdrScTarget, PoolingAllocator<HttpHdrScTarget> > HttpHdrSc::targets private
Definition at line 38 of file HttpHdrSc.h.
Referenced by findTarget(), packInto(), parse(), setMaxAge(), and updateStats().
The documentation for this class was generated from the following files:
squid/src/HttpHdrSc.h
squid/src/HttpHdrSc.cc