Squid Web Cache: Security::Sslv2Record Class Reference
Security::Sslv2Record Class Reference
draft-hickman-netscape-ssl-00. Section 4.1. SSL Record Header Format
Public Member Functions
Sslv2Record (Parser::BinaryTokenizer &tk)
Public Attributes
SBuf fragment
Detailed Description
Definition at line 49 of file Handshake.cc.
Constructor & Destructor Documentation
Sslv2Record()
Security::Sslv2Record::Sslv2Record (Parser::BinaryTokenizer & tk) explicit
Definition at line 197 of file Handshake.cc.
References Parser::BinaryTokenizer::area(), head, Must, Parser::BinaryTokenizerContext::success(), and Parser::BinaryTokenizer::uint16().
Member Data Documentation
fragment
SBuf Security::Sslv2Record::fragment
Definition at line 54 of file Handshake.cc.
Referenced by Security::HandshakeParser::parseVersion2Record().
The documentation for this class was generated from the following file:
squid/src/security/Handshake.cc