Squid Web Cache: TestAuthUserRequest Class Reference
TestAuthUserRequest Class Reference
#include <testAuth.h>
Protected Member Functions
void scheme ()
void construction ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestAuthUserRequest)
CPPUNIT_TEST (scheme)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 44 of file testAuth.h.
Member Function Documentation
construction()
void TestAuthUserRequest::construction () protected
CPPUNIT_TEST()
TestAuthUserRequest::CPPUNIT_TEST (scheme) private
CPPUNIT_TEST_SUITE()
TestAuthUserRequest::CPPUNIT_TEST_SUITE (TestAuthUserRequest) private
CPPUNIT_TEST_SUITE_END()
TestAuthUserRequest::CPPUNIT_TEST_SUITE_END () private
scheme()
void TestAuthUserRequest::scheme () protected
Definition at line 180 of file testAuth.cc.
References fake_auth_setup(), find_proxy_auth(), Auth::Scheme::GetSchemes(), and Debug::Levels.
The documentation for this class was generated from the following files:
squid/src/tests/testAuth.h
squid/src/tests/testAuth.cc