Squid Web Cache: UnaryJobCallbackDialer< Job, Argument1 > Class Template Reference
UnaryJobCallbackDialer< Job, Argument1 > Class Template Reference
#include <AsyncCallbacks.h>
Public Types
using Base = UnaryMemFunT< Job, Argument1, Argument1 & >
typedef void(Job::* Method) (Argument1 &)
typedef Job DestClass
typedef CbcPointer< Job > JobPointer
using Answer = Argument1
Public Member Functions
UnaryJobCallbackDialer (const CbcPointer< Job > &aJob, typename Base::Method aMethod)
Argument1 & answer () final
callback results setter
void print (std::ostream &os) const override
virtual bool canDial (AsyncCall &call)
void dial (AsyncCall &call)
Public Attributes
Method method
Argument1 arg1
JobPointer job
Protected Member Functions
void doDial () override
Detailed Description
template<class Job, typename Argument1>
class UnaryJobCallbackDialer< Job, Argument1 >
CallDialer for single-parameter callback methods of AsyncJob classes.
See also
UnaryCbcCallbackDialer and UnaryFunCallbackDialer.
Definition at line 134 of file AsyncCallbacks.h.
Member Typedef Documentation
Answer
using WithAnswer< Argument1 >::Answer = Argument1 inherited
Definition at line 21 of file AsyncCallbacks.h.
Base
template<class Job , typename Argument1 > using UnaryJobCallbackDialer< Job, Argument1 >::Base = UnaryMemFunT<Job, Argument1, Argument1&>
Definition at line 139 of file AsyncCallbacks.h.
DestClass
template<class Job > typedef Job JobDialer< Job >::DestClass inherited
Definition at line 29 of file AsyncJobCalls.h.
JobPointer
template<class Job > typedef CbcPointer<Job> JobDialer< Job >::JobPointer inherited
Definition at line 30 of file AsyncJobCalls.h.
Method
typedef void(Job::* UnaryMemFunT< Job, Argument1 , Argument1 & >::Method) (Argument1 &) inherited
Definition at line 111 of file AsyncJobCalls.h.
Constructor & Destructor Documentation
UnaryJobCallbackDialer()
template<class Job , typename Argument1 > UnaryJobCallbackDialer< Job, Argument1 >::UnaryJobCallbackDialer (const CbcPointer< Job > & aJob, typename Base::Method aMethod) inline
Definition at line 141 of file AsyncCallbacks.h.
Member Function Documentation
answer()
template<class Job , typename Argument1 > Argument1 & UnaryJobCallbackDialer< Job, Argument1 >::answer () inline final virtual
Implements WithAnswer< Argument1 >.
Definition at line 145 of file AsyncCallbacks.h.
References UnaryMemFunT< Job, Argument1, Argument1 & >::arg1.
canDial()
template<class Job > bool JobDialer< Job >::canDial (AsyncCall & call) virtual inherited
Reimplemented in CommCbMemFunT< C, Params_ >, BodyProducerDialer, and BodyConsumerDialer.
Definition at line 161 of file AsyncJobCalls.h.
References AsyncCall::cancel().
Referenced by CommCbMemFunT< C, Params_ >::canDial(), BodyProducerDialer::canDial(), and BodyConsumerDialer::canDial().
dial()
template<class Job > void JobDialer< Job >::dial (AsyncCall & call) inherited
Definition at line 171 of file AsyncJobCalls.h.
References Critical, debugs, AsyncCall::debugSection, and AsyncCall::name.
doDial()
void UnaryMemFunT< Job, Argument1 , Argument1 & >::doDial () inline override protected virtual inherited
Implements JobDialer< Job >.
Definition at line 123 of file AsyncJobCalls.h.
print()
void UnaryMemFunT< Job, Argument1 , Argument1 & >::print (std::ostream & os) const inline override virtual inherited
Implements CallDialer.
Definition at line 116 of file AsyncJobCalls.h.
Member Data Documentation
arg1
Argument1 UnaryMemFunT< Job, Argument1 , Argument1 & >::arg1 inherited
Definition at line 120 of file AsyncJobCalls.h.
job
template<class Job > JobPointer JobDialer< Job >::job inherited
Definition at line 38 of file AsyncJobCalls.h.
Referenced by BodyProducerDialer::canDial(), BodyConsumerDialer::canDial(), NullaryMemFunT< Job >::doDial(), and UnaryMemFunT< Job, Data, Argument1 >::doDial().
method
Method UnaryMemFunT< Job, Argument1 , Argument1 & >::method inherited
Definition at line 119 of file AsyncJobCalls.h.
The documentation for this class was generated from the following file:
squid/src/base/AsyncCallbacks.h