Squid Web Cache: Ipc::SharedListenRequest Class Reference
Ipc::SharedListenRequest Class Reference
a request for a listen socket with given parameters
#include <SharedListen.h>
Public Member Functions
SharedListenRequest (const OpenListenerParams &, RequestId aMapId)
sender's constructor
SharedListenRequest (const TypedMsgHdr &hdrMsg)
from recvmsg()
void pack (TypedMsgHdr &hdrMsg) const
prepare for sendmsg()
Public Attributes
int requestorId
kidId of the requestor
OpenListenerParams params
actual comm_open_sharedListen() parameters
RequestId mapId
to map future response to the requestor's callback
Detailed Description
Definition at line 46 of file SharedListen.h.
Constructor & Destructor Documentation
SharedListenRequest() [1/2]
Ipc::SharedListenRequest::SharedListenRequest (const OpenListenerParams & aParams, RequestId aMapId)
Definition at line 73 of file SharedListen.cc.
SharedListenRequest() [2/2]
Ipc::SharedListenRequest::SharedListenRequest (const TypedMsgHdr & hdrMsg) explicit
Definition at line 81 of file SharedListen.cc.
References Ipc::TypedMsgHdr::checkType(), Ipc::TypedMsgHdr::getPod(), and Ipc::mtSharedListenRequest.
Member Function Documentation
pack()
void Ipc::SharedListenRequest::pack (TypedMsgHdr & hdrMsg) const
Definition at line 87 of file SharedListen.cc.
References Ipc::mtSharedListenRequest, Ipc::TypedMsgHdr::putPod(), and Ipc::TypedMsgHdr::setType().
Referenced by SendSharedListenRequest().
Member Data Documentation
mapId
RequestId Ipc::SharedListenRequest::mapId
Definition at line 58 of file SharedListen.h.
Referenced by Ipc::Coordinator::handleSharedListenRequest(), and SendSharedListenRequest().
params
OpenListenerParams Ipc::SharedListenRequest::params
Definition at line 56 of file SharedListen.h.
Referenced by Ipc::Coordinator::handleSharedListenRequest(), Ipc::Coordinator::openListenSocket(), and SendSharedListenRequest().
requestorId
int Ipc::SharedListenRequest::requestorId
Definition at line 54 of file SharedListen.h.
Referenced by Ipc::Coordinator::handleSharedListenRequest(), and Ipc::Coordinator::openListenSocket().
The documentation for this class was generated from the following files:
squid/src/ipc/SharedListen.h
squid/src/ipc/SharedListen.cc