Squid Web Cache: DelayTagged Class Reference
DelayTagged Class Reference
Squid Components » Delay Pools API
#include <DelayTagged.h>
Classes
class Id
Public Types
typedef RefCount< DelayTagged > Pointer
Public Member Functions
DelayTagged ()
~DelayTagged () override
void stats (StoreEntry *sentry) override
void dump (StoreEntry *entry) const override
void update (int incr) override
void parse () override
DelayIdComposite::Pointer id (CompositeSelectionDetails &) override
void delayRead (const AsyncCallPointer &)
Protected Member Functions
void kickReads ()
Protected Attributes
DelayedAsyncCalls deferredReads
Private Member Functions
MEMPROXY_CLASS (DelayTagged)
Private Attributes
DelaySpec spec
Splay< DelayTaggedBucket::Pointer > buckets
Friends
class Id
Detailed Description
Definition at line 41 of file DelayTagged.h.
Member Typedef Documentation
Pointer
typedef RefCount<DelayTagged> DelayTagged::Pointer
Definition at line 46 of file DelayTagged.h.
Constructor & Destructor Documentation
DelayTagged()
DelayTagged::DelayTagged ()
Definition at line 19 of file DelayTagged.cc.
References DelayPools::registerForUpdates().
~DelayTagged()
DelayTagged::~DelayTagged () override
Definition at line 26 of file DelayTagged.cc.
References buckets, DelayTaggedFree, and DelayPools::deregisterForUpdates().
Member Function Documentation
delayRead()
void CompositePoolNode::delayRead (const AsyncCallPointer & aRead) inherited
Definition at line 80 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::delay().
Referenced by Aggregate::AggregateId::delayRead().
dump()
void DelayTagged::dump (StoreEntry * entry) const override virtual
Implements CompositePoolNode.
Definition at line 74 of file DelayTagged.cc.
References DelaySpec::dump(), and spec.
id()
DelayIdComposite::Pointer DelayTagged::id (CompositePoolNode::CompositeSelectionDetails & details) override virtual
Implements CompositePoolNode.
Definition at line 111 of file DelayTagged.cc.
References SBuf::length(), and CompositePoolNode::CompositeSelectionDetails::tag.
kickReads()
void CompositePoolNode::kickReads () protected inherited
Definition at line 88 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::schedule().
Referenced by Aggregate::update(), update(), and DelayVector::update().
MEMPROXY_CLASS()
DelayTagged::MEMPROXY_CLASS (DelayTagged) private
parse()
void DelayTagged::parse () override virtual
Implements CompositePoolNode.
Definition at line 104 of file DelayTagged.cc.
References DelaySpec::parse(), and spec.
stats()
void DelayTagged::stats (StoreEntry * sentry) override virtual
Implements CompositePoolNode.
Definition at line 54 of file DelayTagged.cc.
References buckets, DelaySpec::restore_bps, spec, DelaySpec::stats(), and storeAppendPrintf().
update()
void DelayTagged::update (int incr) override virtual
Implements CompositePoolNode.
Definition at line 95 of file DelayTagged.cc.
References buckets, CompositePoolNode::kickReads(), and spec.
Friends And Related Symbol Documentation
Id
friend class Id friend
Definition at line 76 of file DelayTagged.h.
Member Data Documentation
buckets
Splay<DelayTaggedBucket::Pointer> DelayTagged::buckets private
Definition at line 79 of file DelayTagged.h.
Referenced by DelayTagged::Id::Id(), ~DelayTagged(), stats(), and update().
deferredReads
DelayedAsyncCalls CompositePoolNode::deferredReads protected inherited
Definition at line 60 of file CompositePoolNode.h.
Referenced by CompositePoolNode::delayRead(), and CompositePoolNode::kickReads().
spec
DelaySpec DelayTagged::spec private
Definition at line 78 of file DelayTagged.h.
Referenced by DelayTagged::Id::Id(), dump(), parse(), stats(), and update().
The documentation for this class was generated from the following files:
squid/src/DelayTagged.h
squid/src/DelayTagged.cc