Squid Web Cache: Ipc::BaseMultiQueue Class Reference
Ipc::BaseMultiQueue Class Reference abstract
#include <Queue.h>
Public Member Functions
BaseMultiQueue (const int aLocalProcessId)
virtual ~BaseMultiQueue ()
void clearReaderSignal (const int remoteProcessId)
clears the reader notification received by the local process from the remote process
void clearAllReaderSignals ()
clears all reader notifications received by the local process
template<class Value >
bool pop (int &remoteProcessId, Value &value)
picks a process and calls OneToOneUniQueue::pop() using its queue
template<class Value >
bool push (const int remoteProcessId, const Value &value)
calls OneToOneUniQueue::push() using the given process queue
template<class Value >
bool peek (int &remoteProcessId, Value &value) const
peeks at the item likely to be pop()ed next
template<class Value >
void stat (std::ostream &) const
prints current state; suitable for cache manager reports
QueueReader::Balance & localBalance ()
returns local reader's balance
const QueueReader::Balance & balance (const int remoteProcessId) const
returns reader's balance for a given remote process
QueueReader::Rate & localRateLimit ()
returns local reader's rate limit
const QueueReader::Rate & rateLimit (const int remoteProcessId) const
returns reader's rate limit for a given remote process
int inSize (const int remoteProcessId) const
number of items in incoming queue from a given remote process
int outSize (const int remoteProcessId) const
number of items in outgoing queue to a given remote process
Protected Member Functions
virtual const OneToOneUniQueue & inQueue (const int remoteProcessId) const =0
incoming queue from a given remote process
OneToOneUniQueue & inQueue (const int remoteProcessId)
virtual const OneToOneUniQueue & outQueue (const int remoteProcessId) const =0
outgoing queue to a given remote process
OneToOneUniQueue & outQueue (const int remoteProcessId)
virtual const QueueReader & localReader () const =0
QueueReader & localReader ()
virtual const QueueReader & remoteReader (const int remoteProcessId) const =0
QueueReader & remoteReader (const int remoteProcessId)
virtual int remotesCount () const =0
virtual int remotesIdOffset () const =0
Protected Attributes
const int theLocalProcessId
process ID of this queue
Private Attributes
int theLastPopProcessId
the ID of the last process we tried to pop() from
Detailed Description
Base class for lockless fixed-capacity bidirectional queues for a limited number processes.
Definition at line 167 of file Queue.h.
Constructor & Destructor Documentation
BaseMultiQueue()
Ipc::BaseMultiQueue::BaseMultiQueue (const int aLocalProcessId)
Definition at line 152 of file Queue.cc.
~BaseMultiQueue()
virtual Ipc::BaseMultiQueue::~BaseMultiQueue () inline virtual
Definition at line 171 of file Queue.h.
Member Function Documentation
balance()
const Ipc::QueueReader::Balance & Ipc::BaseMultiQueue::balance (const int remoteProcessId) const
Definition at line 180 of file Queue.cc.
References Ipc::QueueReader::balance.
clearAllReaderSignals()
void Ipc::BaseMultiQueue::clearAllReaderSignals ()
Definition at line 172 of file Queue.cc.
References Ipc::QueueReader::clearSignal(), debugs, and Ipc::QueueReader::id.
clearReaderSignal()
void Ipc::BaseMultiQueue::clearReaderSignal (const int remoteProcessId)
Definition at line 159 of file Queue.cc.
inQueue() [1/2]
Ipc::OneToOneUniQueue & Ipc::BaseMultiQueue::inQueue (const int remoteProcessId) protected
Definition at line 194 of file Queue.cc.
inQueue() [2/2]
virtual const OneToOneUniQueue & Ipc::BaseMultiQueue::inQueue (const int remoteProcessId) const protected pure virtual
Implemented in Ipc::FewToFewBiQueue, and Ipc::MultiQueue.
Referenced by inSize(), peek(), pop(), and stat().
inSize()
int Ipc::BaseMultiQueue::inSize (const int remoteProcessId) const inline
Definition at line 204 of file Queue.h.
References inQueue(), and Ipc::OneToOneUniQueue::size().
localBalance()
QueueReader::Balance & Ipc::BaseMultiQueue::localBalance () inline
Definition at line 192 of file Queue.h.
References Ipc::QueueReader::balance, and localReader().
localRateLimit()
QueueReader::Rate & Ipc::BaseMultiQueue::localRateLimit () inline
Definition at line 198 of file Queue.h.
References localReader(), and Ipc::QueueReader::rateLimit.
localReader() [1/2]
Ipc::QueueReader & Ipc::BaseMultiQueue::localReader () protected
Definition at line 210 of file Queue.cc.
localReader() [2/2]
virtual const QueueReader & Ipc::BaseMultiQueue::localReader () const protected pure virtual
Implemented in Ipc::FewToFewBiQueue, and Ipc::MultiQueue.
Referenced by localBalance(), localRateLimit(), pop(), and stat().
outQueue() [1/2]
Ipc::OneToOneUniQueue & Ipc::BaseMultiQueue::outQueue (const int remoteProcessId) protected
Definition at line 202 of file Queue.cc.
outQueue() [2/2]
virtual const OneToOneUniQueue & Ipc::BaseMultiQueue::outQueue (const int remoteProcessId) const protected pure virtual
Implemented in Ipc::FewToFewBiQueue, and Ipc::MultiQueue.
Referenced by outSize(), push(), and stat().
outSize()
int Ipc::BaseMultiQueue::outSize (const int remoteProcessId) const inline
Definition at line 207 of file Queue.h.
References outQueue(), and Ipc::OneToOneUniQueue::size().
peek()
template<class Value > bool Ipc::BaseMultiQueue::peek (int & remoteProcessId, Value & value) const
Definition at line 568 of file Queue.h.
References inQueue(), Ipc::OneToOneUniQueue::peek(), remotesCount(), remotesIdOffset(), and theLastPopProcessId.
pop()
template<class Value > bool Ipc::BaseMultiQueue::pop (int & remoteProcessId, Value & value)
Definition at line 540 of file Queue.h.
References debugs, inQueue(), localReader(), Ipc::OneToOneUniQueue::pop(), remotesCount(), remotesIdOffset(), Ipc::OneToOneUniQueue::size(), theLastPopProcessId, and theLocalProcessId.
push()
template<class Value > bool Ipc::BaseMultiQueue::push (const int remoteProcessId, const Value & value)
Definition at line 558 of file Queue.h.
References debugs, outQueue(), Ipc::OneToOneUniQueue::push(), remoteReader(), Ipc::OneToOneUniQueue::size(), and theLocalProcessId.
rateLimit()
const Ipc::QueueReader::Rate & Ipc::BaseMultiQueue::rateLimit (const int remoteProcessId) const
Definition at line 187 of file Queue.cc.
References Ipc::QueueReader::rateLimit.
remoteReader() [1/2]
Ipc::QueueReader & Ipc::BaseMultiQueue::remoteReader (const int remoteProcessId) protected
Definition at line 218 of file Queue.cc.
remoteReader() [2/2]
virtual const QueueReader & Ipc::BaseMultiQueue::remoteReader (const int remoteProcessId) const protected pure virtual
Implemented in Ipc::FewToFewBiQueue, and Ipc::MultiQueue.
Referenced by push().
remotesCount()
virtual int Ipc::BaseMultiQueue::remotesCount () const protected pure virtual
Implemented in Ipc::FewToFewBiQueue, and Ipc::MultiQueue.
Referenced by peek(), pop(), and stat().
remotesIdOffset()
virtual int Ipc::BaseMultiQueue::remotesIdOffset () const protected pure virtual
Implemented in Ipc::FewToFewBiQueue, and Ipc::MultiQueue.
Referenced by peek(), pop(), and stat().
stat()
template<class Value > void Ipc::BaseMultiQueue::stat (std::ostream & os) const
Definition at line 586 of file Queue.h.
References inQueue(), localReader(), outQueue(), remotesCount(), remotesIdOffset(), and theLocalProcessId.
Member Data Documentation
theLastPopProcessId
int Ipc::BaseMultiQueue::theLastPopProcessId private
Definition at line 231 of file Queue.h.
Referenced by peek(), and pop().
theLocalProcessId
const int Ipc::BaseMultiQueue::theLocalProcessId protected
Definition at line 228 of file Queue.h.
Referenced by Ipc::FewToFewBiQueue::findOldest(), pop(), push(), and stat().
The documentation for this class was generated from the following files:
squid/src/ipc/Queue.h
squid/src/ipc/Queue.cc