Squid Web Cache: Mgr::StringParam Class Reference
Mgr::StringParam Class Reference
#include <StringParam.h>
Public Types
enum Type { ptInt = 1 , ptString }
typedef RefCount< QueryParam > Pointer
Public Member Functions
StringParam ()
StringParam (const String &aString)
void pack (Ipc::TypedMsgHdr &msg) const override
store parameter into msg
void unpackValue (const Ipc::TypedMsgHdr &msg) override
load parameter value from msg
const String & value () const
Public Attributes
Type type
Private Attributes
String str
Detailed Description
Definition at line 22 of file StringParam.h.
Member Typedef Documentation
Pointer
typedef RefCount<QueryParam> Mgr::QueryParam::Pointer inherited
Definition at line 24 of file QueryParam.h.
Member Enumeration Documentation
Type
enum Mgr::QueryParam::Type inherited
Enumerator
ptInt
ptString
Definition at line 23 of file QueryParam.h.
Constructor & Destructor Documentation
StringParam() [1/2]
Mgr::StringParam::StringParam ()
Definition at line 15 of file StringParam.cc.
StringParam() [2/2]
Mgr::StringParam::StringParam (const String & aString)
Definition at line 20 of file StringParam.cc.
Member Function Documentation
pack()
void Mgr::StringParam::pack (Ipc::TypedMsgHdr & msg) const override virtual
Implements Mgr::QueryParam.
Definition at line 26 of file StringParam.cc.
References Ipc::TypedMsgHdr::putPod(), and Ipc::TypedMsgHdr::putString().
unpackValue()
void Mgr::StringParam::unpackValue (const Ipc::TypedMsgHdr & msg) override virtual
Implements Mgr::QueryParam.
Definition at line 33 of file StringParam.cc.
References Ipc::TypedMsgHdr::getString().
value()
const String & Mgr::StringParam::value () const
Definition at line 39 of file StringParam.cc.
Member Data Documentation
str
String Mgr::StringParam::str private
Definition at line 32 of file StringParam.h.
type
Type Mgr::QueryParam::type inherited
Definition at line 37 of file QueryParam.h.
Referenced by Mgr::Inquirer::applyQueryParams().
The documentation for this class was generated from the following files:
squid/src/mgr/StringParam.h
squid/src/mgr/StringParam.cc