Squid Web Cache: Adaptation::Icap::ServiceRep Class Reference
Adaptation::Icap::ServiceRep Class Reference abstract
#include <ServiceRep.h>
Classes
struct Client
Public Types
typedef RefCount< ServiceRep > Pointer
typedef String Id
Public Member Functions
ServiceRep (const ServiceConfigPointer &aConfig)
~ServiceRep () override
void finalize () override
bool probed () const override
bool up () const override
bool availableForNew () const
a new transaction may start communicating with the service
bool availableForOld () const
a transaction notified about connection slot availability may start communicating with the service
Initiate * makeXactLauncher (Http::Message *virginHeader, HttpRequest *virginCause, AccessLogEntry::Pointer &alp) override
void callWhenAvailable (AsyncCall::Pointer &cb, bool priority=false)
void callWhenReady (AsyncCall::Pointer &cb)
bool wantsUrl (const SBuf &urlPath) const override
bool wantsPreview (const SBuf &urlPath, size_t &wantedSize) const
bool allows204 () const
bool allows206 () const
Comm::ConnectionPointer getIdleConnection (bool isRetriable)
void putConnection (const Comm::ConnectionPointer &conn, bool isReusable, bool sendReset, const char *comment)
void noteConnectionUse (const Comm::ConnectionPointer &conn)
void noteConnectionFailed (const char *comment)
void noteFailure () override
void noteNewWaiter ()
New xaction waiting for service to be up or available.
void noteGoneWaiter ()
An xaction is not waiting any more for service to be available.
bool existWaiters () const
if there are xactions waiting for the service to be available
bool doneAll () const override
whether positive goal has been reached
void callException (const std::exception &e) override
called when the job throws during an async call
void detach () override
bool detached () const override
whether detached() was called
void noteTimeToUpdate ()
void noteTimeToNotify ()
void noteAdaptationAnswer (const Answer &answer) override
virtual bool broken () const
bool wants (const ServiceFilter &filter) const
const ServiceConfig & cfg () const
virtual void noteAdaptationAclCheckDone (Adaptation::ServiceGroupPointer group)
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
Security::ContextPointer sslContext
Security::FuturePeerContext tlsContext
Security::SessionStatePointer sslSession
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
ServiceConfig & writeableCfg ()
CbcPointer< Initiate > initiateAdaptation (Initiate *x)
< starts freshly created initiate and returns a safe pointer to it
void clearAdaptation (CbcPointer< Initiate > &x)
clears the pointer (does not call announceInitiatorAbort)
void announceInitiatorAbort (CbcPointer< Initiate > &x)
inform the transaction about abnormal termination and clear the pointer
bool initiated (const CbcPointer< AsyncJob > &job) const
Must(initiated(initiate)) instead of Must(initiate.set()), for clarity.
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual void start ()
called by AsyncStart; do not call directly
virtual void swanSong ()
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Types
typedef std::vector< Client > Clients
Private Member Functions
CBDATA_CHILD (ServiceRep)
ICAP::Method parseMethod (const char *) const
ICAP::VectPoint parseVectPoint (const char *) const
void suspend (const char *reason)
bool hasOptions () const
bool needNewOptions () const
time_t optionsFetchTime () const
void scheduleUpdate (time_t when)
void scheduleNotification ()
void startGettingOptions ()
void handleNewOptions (Options *newOptions)
void changeOptions (Options *newOptions)
void checkOptions ()
void announceStatusChange (const char *downPhrase, bool important) const
void setMaxConnections ()
Set the maximum allowed connections for the service.
int excessConnections () const
The number of connections which excess the Max-Connections limit.
int availableConnections () const
void busyCheckpoint ()
const char * status () const override
internal cleanup; do not call directly
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
Clients theClients
Options * theOptions
CbcPointer< Adaptation::Initiate > theOptionsFetcher
time_t theLastUpdate
std::deque< Client > theNotificationWaiters
int theBusyConns
int theAllWaiters
int theMaxConnections
the maximum allowed connections to the service
bool connOverloadReported
whether we reported exceeding theMaxConnections
IdleConnList * theIdleConns
idle persistent connection pool
FadingCounter theSessionFailures
const char * isSuspended
bool notifying
bool updateScheduled
bool wasAnnouncedUp
bool isDetached
ServiceConfigPointer theConfig
Detailed Description
Definition at line 59 of file ServiceRep.h.
Member Typedef Documentation
Clients
typedef std::vector<Client> Adaptation::Icap::ServiceRep::Clients private
Definition at line 127 of file ServiceRep.h.
Id
typedef String Adaptation::Service::Id inherited
Definition at line 31 of file Service.h.
Pointer
typedef RefCount<ServiceRep> Adaptation::Icap::ServiceRep::Pointer
Definition at line 65 of file ServiceRep.h.
Constructor & Destructor Documentation
ServiceRep()
Adaptation::Icap::ServiceRep::ServiceRep (const ServiceConfigPointer & aConfig) explicit
Definition at line 34 of file ServiceRep.cc.
References setMaxConnections(), and theIdleConns.
~ServiceRep()
Adaptation::Icap::ServiceRep::~ServiceRep () override
Definition at line 51 of file ServiceRep.cc.
References Must, and SWALLOW_EXCEPTIONS.
Member Function Documentation
allows204()
bool Adaptation::Icap::ServiceRep::allows204 () const
Definition at line 346 of file ServiceRep.cc.
References Must.
allows206()
bool Adaptation::Icap::ServiceRep::allows206 () const
Definition at line 352 of file ServiceRep.cc.
References Must.
announceInitiatorAbort()
void Adaptation::Initiator::announceInitiatorAbort (CbcPointer< Initiate > & x) protected inherited
Definition at line 38 of file Initiator.cc.
References CallJobHere.
Referenced by ClientHttpRequest::~ClientHttpRequest(), and Client::cleanAdaptation().
announceStatusChange()
void Adaptation::Icap::ServiceRep::announceStatusChange (const char * downPhrase, bool important) const private
Definition at line 523 of file ServiceRep.cc.
References debugs.
availableConnections()
int Adaptation::Icap::ServiceRep::availableConnections () const private
The available connections slots to the ICAP server
Returns
the available slots, or -1 if there is no limit on allowed connections
Definition at line 200 of file ServiceRep.cc.
References DBG_IMPORTANT, debugs, max(), and Adaptation::srvForce.
availableForNew()
bool Adaptation::Icap::ServiceRep::availableForNew () const
Definition at line 307 of file ServiceRep.cc.
References Must.
availableForOld()
bool Adaptation::Icap::ServiceRep::availableForOld () const
Definition at line 317 of file ServiceRep.cc.
References Must.
broken()
bool Adaptation::Service::broken () const virtual inherited
Definition at line 30 of file Service.cc.
busyCheckpoint()
void Adaptation::Icap::ServiceRep::busyCheckpoint () private
If there are xactions waiting for the service to be available, notify as many xactions as the available connections slots.
Definition at line 248 of file ServiceRep.cc.
References Adaptation::Icap::ServiceRep::Client::callback, debugs, and ScheduleCallHere.
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void Adaptation::Icap::ServiceRep::callException (const std::exception & e) override virtual
Reimplemented from AsyncJob.
Definition at line 568 of file ServiceRep.cc.
References debugs.
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
callWhenAvailable()
void Adaptation::Icap::ServiceRep::callWhenAvailable (AsyncCall::Pointer & cb, bool priority = false)
Definition at line 403 of file ServiceRep.cc.
References Adaptation::Icap::ServiceRep::Client::callback, debugs, Must, and Adaptation::Icap::ServiceRep::Client::service.
callWhenReady()
void Adaptation::Icap::ServiceRep::callWhenReady (AsyncCall::Pointer & cb)
Definition at line 421 of file ServiceRep.cc.
References Adaptation::Icap::ServiceRep::Client::callback, debugs, Must, and Adaptation::Icap::ServiceRep::Client::service.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
CBDATA_CHILD()
Adaptation::Icap::ServiceRep::CBDATA_CHILD (ServiceRep) private
cfg()
const ServiceConfig & Adaptation::Service::cfg () const inline inherited
Definition at line 51 of file Service.h.
References Adaptation::Service::theConfig.
Referenced by Adaptation::Service::Service(), Adaptation::ServiceGroup::checkUniqueness(), Adaptation::Icap::Xaction::dnsLookupDone(), Adaptation::ServiceGroup::finalize(), Adaptation::Icap::Xaction::finalizeLogInfo(), Adaptation::Icap::ModXact::finalizeLogInfo(), Adaptation::ServiceGroup::findService(), Adaptation::Icap::OptXact::makeRequest(), Adaptation::Icap::Xaction::openConnection(), Adaptation::DynamicServiceChain::Split(), and Adaptation::Iterator::step().
changeOptions()
void Adaptation::Icap::ServiceRep::changeOptions (Options * newOptions) private
Definition at line 455 of file ServiceRep.cc.
References debugs, and squid_curtime.
checkOptions()
void Adaptation::Icap::ServiceRep::checkOptions () private
Definition at line 470 of file ServiceRep.cc.
References String::append(), DBG_IMPORTANT, debugs, int, Adaptation::methodStr(), and squid_curtime.
clearAdaptation()
void Adaptation::Initiator::clearAdaptation (CbcPointer< Initiate > & x) protected inherited
Definition at line 32 of file Initiator.cc.
References CbcPointer< Cbc >::clear().
Referenced by ClientHttpRequest::handleAdaptedHeader(), ClientHttpRequest::noteAdaptationAnswer(), and Client::noteAdaptationAnswer().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
detach()
void Adaptation::Icap::ServiceRep::detach () override virtual
called when removed from the config; the service will be auto-destroyed when the last refcounting user leaves
Implements Adaptation::Service.
Definition at line 719 of file ServiceRep.cc.
References debugs.
detached()
bool Adaptation::Icap::ServiceRep::detached () const override virtual
Implements Adaptation::Service.
Definition at line 726 of file ServiceRep.cc.
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Adaptation::Icap::ServiceRep::doneAll () const inline override virtual
Reimplemented from AsyncJob.
Definition at line 101 of file ServiceRep.h.
References AsyncJob::doneAll().
excessConnections()
int Adaptation::Icap::ServiceRep::excessConnections () const private
Definition at line 224 of file ServiceRep.cc.
existWaiters()
bool Adaptation::Icap::ServiceRep::existWaiters () const inline
Definition at line 98 of file ServiceRep.h.
References theAllWaiters.
finalize()
void Adaptation::Icap::ServiceRep::finalize () override virtual
Reimplemented from Adaptation::Service.
Definition at line 61 of file ServiceRep.cc.
References debugs, DEFAULT_ICAP_PORT, DEFAULT_ICAPS_PORT, Adaptation::Service::finalize(), Adaptation::Config::oldest_service_failure, Adaptation::Icap::TheConfig, and xgetservbyname().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
getIdleConnection()
Comm::ConnectionPointer Adaptation::Icap::ServiceRep::getIdleConnection (bool isRetriable)
Returns
an idle persistent ICAP connection or nil
Definition at line 119 of file ServiceRep.cc.
References debugs.
Referenced by Adaptation::Icap::Xaction::openConnection().
handleNewOptions()
void Adaptation::Icap::ServiceRep::handleNewOptions (Options * newOptions) private
Definition at line 576 of file ServiceRep.cc.
References debugs, and min().
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
hasOptions()
bool Adaptation::Icap::ServiceRep::hasOptions () const private
Definition at line 297 of file ServiceRep.cc.
initiateAdaptation()
CbcPointer< Adaptation::Initiate > Adaptation::Initiator::initiateAdaptation (Initiate * x) protected inherited
Definition at line 23 of file Initiator.cc.
References Adaptation::Initiate::initiator().
Referenced by ClientHttpRequest::startAdaptation(), and Client::startAdaptation().
initiated()
bool Adaptation::Initiator::initiated (const CbcPointer< AsyncJob > & job) const inline protected inherited
Definition at line 52 of file Initiator.h.
References CbcPointer< Cbc >::set().
Referenced by ClientHttpRequest::startAdaptation(), and Client::startAdaptation().
makeXactLauncher()
Adaptation::Initiate * Adaptation::Icap::ServiceRep::makeXactLauncher (Http::Message * virginHeader, HttpRequest * virginCause, AccessLogEntry::Pointer & alp) override virtual
Implements Adaptation::Service.
Definition at line 672 of file ServiceRep.cc.
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
needNewOptions()
bool Adaptation::Icap::ServiceRep::needNewOptions () const private
Definition at line 450 of file ServiceRep.cc.
noteAdaptationAclCheckDone()
void Adaptation::Initiator::noteAdaptationAclCheckDone (Adaptation::ServiceGroupPointer group) virtual inherited
AccessCheck calls this back with a possibly nil service group to signal whether adaptation is needed and where it should start.
Reimplemented in Client, and ClientHttpRequest.
Definition at line 17 of file Initiator.cc.
References Must.
noteAdaptationAnswer()
void Adaptation::Icap::ServiceRep::noteAdaptationAnswer (const Answer & answer) override virtual
called with the initial adaptation decision (adapt, block, error); virgin and/or adapted body transmission may continue after this
Implements Adaptation::Initiator.
Definition at line 538 of file ServiceRep.cc.
References Adaptation::Answer::akError, Adaptation::Answer::akForward, Adaptation::Icap::Options::configure(), DBG_IMPORTANT, debugs, RefCount< C >::getRaw(), Adaptation::Answer::kind, Adaptation::Answer::message, and Must.
noteConnectionFailed()
void Adaptation::Icap::ServiceRep::noteConnectionFailed (const char * comment)
Definition at line 179 of file ServiceRep.cc.
References debugs.
noteConnectionUse()
void Adaptation::Icap::ServiceRep::noteConnectionUse (const Comm::ConnectionPointer & conn)
Definition at line 173 of file ServiceRep.cc.
References Comm::Connection::fd, fd_table, Comm::IsConnOpen(), and Must.
noteFailure()
void Adaptation::Icap::ServiceRep::noteFailure () override virtual
Implements Adaptation::Service.
Definition at line 96 of file ServiceRep.cc.
References debugs, Adaptation::Config::oldest_service_failure, Adaptation::Config::service_failure_limit, and Adaptation::Icap::TheConfig.
noteGoneWaiter()
void Adaptation::Icap::ServiceRep::noteGoneWaiter ()
Definition at line 239 of file ServiceRep.cc.
Referenced by Adaptation::Icap::ConnWaiterDialer::~ConnWaiterDialer().
noteNewWaiter()
void Adaptation::Icap::ServiceRep::noteNewWaiter () inline
Definition at line 96 of file ServiceRep.h.
References theAllWaiters.
noteTimeToNotify()
void Adaptation::Icap::ServiceRep::noteTimeToNotify ()
Definition at line 382 of file ServiceRep.cc.
References Adaptation::Icap::ServiceRep::Client::callback, debugs, Must, and ScheduleCallHere.
noteTimeToUpdate()
void Adaptation::Icap::ServiceRep::noteTimeToUpdate ()
Definition at line 368 of file ServiceRep.cc.
References debugs.
Referenced by ServiceRep_noteTimeToUpdate().
optionsFetchTime()
time_t Adaptation::Icap::ServiceRep::optionsFetchTime () const private
Definition at line 648 of file ServiceRep.cc.
References debugs, Adaptation::Config::service_revival_delay, squid_curtime, and Adaptation::Icap::TheConfig.
parseMethod()
ICAP::Method Adaptation::Icap::ServiceRep::parseMethod (const char *) const private
parseVectPoint()
ICAP::VectPoint Adaptation::Icap::ServiceRep::parseVectPoint (const char *) const private
probed()
bool Adaptation::Icap::ServiceRep::probed () const override virtual
Implements Adaptation::Service.
Definition at line 292 of file ServiceRep.cc.
putConnection()
void Adaptation::Icap::ServiceRep::putConnection (const Comm::ConnectionPointer & conn, bool isReusable, bool sendReset, const char * comment)
Definition at line 148 of file ServiceRep.cc.
References Comm::Connection::close(), comm_reset_close(), debugs, Comm::IsConnOpen(), and Must.
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
scheduleNotification()
void Adaptation::Icap::ServiceRep::scheduleNotification () private
Definition at line 444 of file ServiceRep.cc.
References CallJobHere, and debugs.
scheduleUpdate()
void Adaptation::Icap::ServiceRep::scheduleUpdate (time_t when) private
Definition at line 610 of file ServiceRep.cc.
References DBG_IMPORTANT, debugs, eventAdd(), eventDelete(), eventFind(), ServiceRep_noteTimeToUpdate(), and squid_curtime.
setMaxConnections()
void Adaptation::Icap::ServiceRep::setMaxConnections () private
Definition at line 185 of file ServiceRep.cc.
References Config, and SquidConfig::workers.
Referenced by ServiceRep().
start()
void AsyncJob::start () protected virtual inherited
Reimplemented in Adaptation::AccessCheck, Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::OptXact, Adaptation::Icap::Xaction, Adaptation::Iterator, ConnStateData, Ftp::Client, Ftp::Gateway, Ftp::Relay, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, HttpStateData, Ipc::Coordinator, Ipc::Forwarder, Ipc::Inquirer, Ipc::Strand, Ipc::UdsSender, Log::TcpLogger, Mgr::ActionWriter, Mgr::Filler, Mgr::Inquirer, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Ftp::Server, Http::One::Server, Server, Snmp::Inquirer, and Ipc::Port.
Definition at line 59 of file AsyncJob.cc.
Referenced by Adaptation::AccessCheck::start(), Adaptation::Icap::Launcher::start(), Adaptation::Icap::Xaction::start(), Adaptation::Iterator::start(), ConnStateData::start(), Http::Tunneler::start(), Ipc::UdsSender::start(), PeerPoolMgr::start(), Security::PeerConnector::start(), Ipc::Port::start(), and AsyncJob::Start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
startGettingOptions()
void Adaptation::Icap::ServiceRep::startGettingOptions () private
Definition at line 598 of file ServiceRep.cc.
References debugs, and Must.
status()
const char * Adaptation::Icap::ServiceRep::status () const override private virtual
for debugging, starts with space
Reimplemented from AsyncJob.
Definition at line 679 of file ServiceRep.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), and MemBuf::terminate().
suspend()
void Adaptation::Icap::ServiceRep::suspend (const char * reason) private
Definition at line 280 of file ServiceRep.cc.
References DBG_IMPORTANT, debugs, Adaptation::Config::service_revival_delay, squid_curtime, and Adaptation::Icap::TheConfig.
swanSong()
virtual void AsyncJob::swanSong () inline protected virtual inherited
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::ModXactLauncher, Adaptation::Icap::OptXact, Adaptation::Icap::Xaction, Adaptation::Initiate, Adaptation::Iterator, ConnStateData, Client, Ftp::Relay, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, Ipc::Forwarder, Ipc::Inquirer, Ipc::UdsSender, Log::TcpLogger, Mgr::Filler, Mgr::Forwarder, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Server, and Snmp::Forwarder.
Definition at line 61 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), Client::swanSong(), Ftp::Relay::swanSong(), Http::Tunneler::swanSong(), Comm::ConnOpener::swanSong(), Comm::TcpAcceptor::swanSong(), Rock::HeaderUpdater::swanSong(), HappyConnOpener::swanSong(), Ipc::UdsSender::swanSong(), Log::TcpLogger::swanSong(), PeerPoolMgr::swanSong(), Security::PeerConnector::swanSong(), and Server::swanSong().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
up()
bool Adaptation::Icap::ServiceRep::up () const override virtual
Implements Adaptation::Service.
Definition at line 302 of file ServiceRep.cc.
wants()
bool Adaptation::Service::wants (const ServiceFilter & filter) const inherited
Definition at line 36 of file Service.cc.
References AnyP::Uri::absolutePath(), Adaptation::ServiceFilter::method, Adaptation::ServiceFilter::point, Adaptation::ServiceFilter::request, and HttpRequest::url.
Referenced by Adaptation::ServiceGroup::findService().
wantsPreview()
bool Adaptation::Icap::ServiceRep::wantsPreview (const SBuf & urlPath, size_t & wantedSize) const
Definition at line 331 of file ServiceRep.cc.
References Must, and Adaptation::Icap::Options::xferPreview.
wantsUrl()
bool Adaptation::Icap::ServiceRep::wantsUrl (const SBuf & urlPath) const override virtual
Implements Adaptation::Service.
Definition at line 325 of file ServiceRep.cc.
References Must, and Adaptation::Icap::Options::xferIgnore.
writeableCfg()
ServiceConfig & Adaptation::Service::writeableCfg () inline protected inherited
Definition at line 62 of file Service.h.
References Adaptation::Service::theConfig.
Member Data Documentation
connOverloadReported
bool Adaptation::Icap::ServiceRep::connOverloadReported mutable private
Definition at line 144 of file ServiceRep.h.
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
isDetached
bool Adaptation::Icap::ServiceRep::isDetached private
Definition at line 191 of file ServiceRep.h.
isSuspended
const char* Adaptation::Icap::ServiceRep::isSuspended private
Definition at line 148 of file ServiceRep.h.
notifying
bool Adaptation::Icap::ServiceRep::notifying private
Definition at line 150 of file ServiceRep.h.
sslContext
Security::ContextPointer Adaptation::Icap::ServiceRep::sslContext
Definition at line 114 of file ServiceRep.h.
sslSession
Security::SessionStatePointer Adaptation::Icap::ServiceRep::sslSession
Definition at line 117 of file ServiceRep.h.
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
theAllWaiters
int Adaptation::Icap::ServiceRep::theAllWaiters private
number of xactions waiting for a connection slot (notified and not) the number is decreased after the xaction receives notification
Definition at line 141 of file ServiceRep.h.
Referenced by existWaiters(), and noteNewWaiter().
theBusyConns
int Adaptation::Icap::ServiceRep::theBusyConns private
number of connections given to active transactions
Definition at line 138 of file ServiceRep.h.
theClients
Clients Adaptation::Icap::ServiceRep::theClients private
Definition at line 129 of file ServiceRep.h.
theConfig
ServiceConfigPointer Adaptation::Service::theConfig private inherited
Definition at line 65 of file Service.h.
Referenced by Adaptation::Service::Service(), Adaptation::Service::cfg(), and Adaptation::Service::writeableCfg().
theIdleConns
IdleConnList* Adaptation::Icap::ServiceRep::theIdleConns private
Definition at line 145 of file ServiceRep.h.
Referenced by ServiceRep().
theLastUpdate
time_t Adaptation::Icap::ServiceRep::theLastUpdate private
Definition at line 133 of file ServiceRep.h.
theMaxConnections
int Adaptation::Icap::ServiceRep::theMaxConnections private
Definition at line 142 of file ServiceRep.h.
theNotificationWaiters
std::deque<Client> Adaptation::Icap::ServiceRep::theNotificationWaiters private
FIFO queue of xactions waiting for a connection slot and not yet notified about it; xaction is removed when notification is scheduled
Definition at line 137 of file ServiceRep.h.
theOptions
Options* Adaptation::Icap::ServiceRep::theOptions private
Definition at line 131 of file ServiceRep.h.
theOptionsFetcher
CbcPointer<Adaptation::Initiate> Adaptation::Icap::ServiceRep::theOptionsFetcher private
Definition at line 132 of file ServiceRep.h.
theSessionFailures
FadingCounter Adaptation::Icap::ServiceRep::theSessionFailures private
Definition at line 147 of file ServiceRep.h.
tlsContext
Security::FuturePeerContext Adaptation::Icap::ServiceRep::tlsContext
Definition at line 116 of file ServiceRep.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
updateScheduled
bool Adaptation::Icap::ServiceRep::updateScheduled private
Definition at line 151 of file ServiceRep.h.
wasAnnouncedUp
bool Adaptation::Icap::ServiceRep::wasAnnouncedUp mutable private
Definition at line 190 of file ServiceRep.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/ServiceRep.h
squid/src/adaptation/icap/ServiceRep.cc