Squid Web Cache: Rock::LoadingParts Class Reference
Rock::LoadingParts Class Reference
Public Types
using Sizes = Ipc::StoreMapItems< uint64_t >
using Versions = Ipc::StoreMapItems< uint32_t >
using Mores = Ipc::StoreMapItems< Ipc::StoreMapSliceId >
using Flags = Ipc::StoreMapItems< LoadingFlags >
Public Member Functions
LoadingParts (const SwapDir &dir, const bool resuming)
~LoadingParts ()
LoadingParts (LoadingParts &&)=delete
Sizes & sizes () const
Versions & versions () const
Mores & mores () const
Flags & flags () const
Private Attributes
Sizes::Owner * sizesOwner
LoadingEntry::size for all entries.
Versions::Owner * versionsOwner
LoadingEntry::version for all entries.
Mores::Owner * moresOwner
LoadingSlot::more for all slots.
Flags::Owner * flagsOwner
all LoadingEntry and LoadingSlot flags
Detailed Description
information about store entries being loaded from disk (and their slots) used for identifying partially stored/loaded entries
Definition at line 163 of file RockRebuild.cc.
Member Typedef Documentation
Flags
using Rock::LoadingParts::Flags = Ipc::StoreMapItems<LoadingFlags>
Definition at line 169 of file RockRebuild.cc.
Mores
using Rock::LoadingParts::Mores = Ipc::StoreMapItems<Ipc::StoreMapSliceId>
Definition at line 168 of file RockRebuild.cc.
Sizes
using Rock::LoadingParts::Sizes = Ipc::StoreMapItems<uint64_t>
Definition at line 166 of file RockRebuild.cc.
Versions
using Rock::LoadingParts::Versions = Ipc::StoreMapItems<uint32_t>
Definition at line 167 of file RockRebuild.cc.
Constructor & Destructor Documentation
LoadingParts() [1/2]
Rock::LoadingParts::LoadingParts (const SwapDir & dir, const bool resuming)
Definition at line 225 of file RockRebuild.cc.
References assert, Ipc::StoreMapItems< C >::fill(), flags(), mores(), sizes(), and versions().
~LoadingParts()
Rock::LoadingParts::~LoadingParts ()
Definition at line 242 of file RockRebuild.cc.
LoadingParts() [2/2]
Rock::LoadingParts::LoadingParts (LoadingParts &&) delete
Member Function Documentation
flags()
Flags & Rock::LoadingParts::flags () const inline
Definition at line 180 of file RockRebuild.cc.
References flagsOwner, and Ipc::Mem::Owner< Class >::object().
Referenced by LoadingParts().
mores()
Mores & Rock::LoadingParts::mores () const inline
Definition at line 179 of file RockRebuild.cc.
References moresOwner, and Ipc::Mem::Owner< Class >::object().
Referenced by LoadingParts().
sizes()
Sizes & Rock::LoadingParts::sizes () const inline
Definition at line 177 of file RockRebuild.cc.
References Ipc::Mem::Owner< Class >::object(), and sizesOwner.
Referenced by LoadingParts().
versions()
Versions & Rock::LoadingParts::versions () const inline
Definition at line 178 of file RockRebuild.cc.
References Ipc::Mem::Owner< Class >::object(), and versionsOwner.
Referenced by LoadingParts().
Member Data Documentation
flagsOwner
Flags::Owner* Rock::LoadingParts::flagsOwner private
Definition at line 193 of file RockRebuild.cc.
Referenced by flags().
moresOwner
Mores::Owner* Rock::LoadingParts::moresOwner private
Definition at line 190 of file RockRebuild.cc.
Referenced by mores().
sizesOwner
Sizes::Owner* Rock::LoadingParts::sizesOwner private
Definition at line 186 of file RockRebuild.cc.
Referenced by sizes().
versionsOwner
Versions::Owner* Rock::LoadingParts::versionsOwner private
Definition at line 187 of file RockRebuild.cc.
Referenced by versions().
The documentation for this class was generated from the following file:
squid/src/fs/rock/RockRebuild.cc