Squid Web Cache: VectorMap< Key, Value > Class Template Reference
VectorMap< Key, Value > Class Template Reference
Squid Components » Delay Pools API » Delay Pools Internal
Public Member Functions
VectorMap ()
unsigned int size () const
unsigned char findKeyIndex (Key const key) const
bool indexUsed (unsigned char const index) const
unsigned int insert (Key const key)
Public Attributes
Key key_map [IND_MAP_SZ]
Value values [IND_MAP_SZ]
Private Attributes
unsigned int nextMapPosition
Detailed Description
template<class Key, class Value>
class VectorMap< Key, Value >
Definition at line 87 of file delay_pools.cc.
Constructor & Destructor Documentation
VectorMap()
template<class Key , class Value > VectorMap< Key, Value >::VectorMap ()
Definition at line 584 of file delay_pools.cc.
Member Function Documentation
findKeyIndex()
template<class Key , class Value > unsigned char VectorMap< Key, Value >::findKeyIndex (Key const key) const
returns the used position, or the position to allocate
Definition at line 679 of file delay_pools.cc.
References assert, and size.
Referenced by VectorPool::id(), ClassCHostPool::id(), VectorPool::keyAllocated(), and ClassCHostPool::keyAllocated().
indexUsed()
template<class Key , class Value > bool VectorMap< Key, Value >::indexUsed (unsigned char const index) const
Definition at line 671 of file delay_pools.cc.
References size.
Referenced by VectorPool::keyAllocated(), and ClassCHostPool::keyAllocated().
insert()
template<class Key , class Value > unsigned int VectorMap< Key, Value >::insert (Key const key)
Definition at line 596 of file delay_pools.cc.
References assert.
Referenced by VectorPool::id(), and ClassCHostPool::id().
size()
template<class Key , class Value > unsigned int VectorMap< Key, Value >::size () const
Definition at line 589 of file delay_pools.cc.
Referenced by VectorPool::stats(), ClassCHostPool::stats(), VectorPool::update(), and ClassCHostPool::update().
Member Data Documentation
key_map
template<class Key , class Value > Key VectorMap< Key, Value >::key_map[IND_MAP_SZ]
Definition at line 99 of file delay_pools.cc.
Referenced by VectorPool::stats(), and ClassCHostPool::stats().
nextMapPosition
template<class Key , class Value > unsigned int VectorMap< Key, Value >::nextMapPosition private
Definition at line 103 of file delay_pools.cc.
values
template<class Key , class Value > Value VectorMap< Key, Value >::values[IND_MAP_SZ]
Definition at line 100 of file delay_pools.cc.
Referenced by VectorPool::id(), ClassCHostPool::id(), VectorPool::stats(), ClassCHostPool::stats(), VectorPool::update(), and ClassCHostPool::update().
The documentation for this class was generated from the following file:
squid/src/delay_pools.cc