Squid Web Cache: Store::SwapMetaUnpacker Class Reference
Store::SwapMetaUnpacker Class Reference
Store entry metadata view providing a for-range loop meta field iterator API.
Public Types
using Iterator = SwapMetaIterator
Public Member Functions
SwapMetaUnpacker (const char *buf, ssize_t bufferLength, size_t &swap_hdr_sz)
Iterator cbegin () const
Iterator cend () const
Iterator begin () const
Iterator end () const
Private Attributes
const char * metas
metadata field(s)
size_t metasSize
number of bytes in the metas buffer
Detailed Description
Definition at line 54 of file SwapMetaIn.cc.
Member Typedef Documentation
Iterator
using Store::SwapMetaUnpacker::Iterator = SwapMetaIterator
Definition at line 60 of file SwapMetaIn.cc.
Constructor & Destructor Documentation
SwapMetaUnpacker()
Store::SwapMetaUnpacker::SwapMetaUnpacker (const char * buf, ssize_t bufferLength, size_t & swap_hdr_sz)
Definition at line 211 of file SwapMetaIn.cc.
References Assure, Assure2, Debug::Extra(), Here, Less(), size, Store::SwapMetaPrefixSize, ToSBuf(), and Store::UnpackPrefix().
Member Function Documentation
begin()
Iterator Store::SwapMetaUnpacker::begin () const inline
Definition at line 63 of file SwapMetaIn.cc.
References cbegin().
cbegin()
Iterator Store::SwapMetaUnpacker::cbegin () const inline
Definition at line 61 of file SwapMetaIn.cc.
References metas, and metasSize.
Referenced by begin().
cend()
Iterator Store::SwapMetaUnpacker::cend () const inline
Definition at line 62 of file SwapMetaIn.cc.
References metas, and metasSize.
Referenced by end().
end()
Iterator Store::SwapMetaUnpacker::end () const inline
Definition at line 64 of file SwapMetaIn.cc.
References cend().
Member Data Documentation
metas
const char* Store::SwapMetaUnpacker::metas private
Definition at line 67 of file SwapMetaIn.cc.
Referenced by cbegin(), and cend().
metasSize
size_t Store::SwapMetaUnpacker::metasSize private
Definition at line 68 of file SwapMetaIn.cc.
Referenced by cbegin(), and cend().
The documentation for this class was generated from the following file:
squid/src/store/SwapMetaIn.cc