Squid Web Cache: ACLCertificateData Class Reference
ACLCertificateData Class Reference
Squid Components » Access Controls
#include <CertificateData.h>
Public Member Functions
ACLCertificateData (Ssl::GETX509ATTRIBUTE *, const char *attributes, bool optionalAttr=false)
bool match (X509 *) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Public Attributes
const char * validAttributesStr
std::list< std::string > validAttributes
Parsed list of valid attribute names.
bool attributeIsOptional
True if the attribute is optional (-xxx options)
SBuf attribute
ACLStringData values
Private Member Functions
MEMPROXY_CLASS (ACLCertificateData)
Private Attributes
Ssl::GETX509ATTRIBUTE * sslAttributeCall
The callback used to retrieve the data from X509 cert.
Detailed Description
Definition at line 21 of file CertificateData.h.
Constructor & Destructor Documentation
ACLCertificateData()
ACLCertificateData::ACLCertificateData (Ssl::GETX509ATTRIBUTE * sslStrategy, const char * attributes, bool optionalAttr = false)
Definition at line 19 of file CertificateData.cc.
References validAttributes.
Member Function Documentation
dump()
SBufList ACLCertificateData::dump () const override virtual
Implements ACLData< X509 * >.
Definition at line 65 of file CertificateData.cc.
References attribute, ACLStringData::dump(), validAttributesStr, and values.
empty()
bool ACLCertificateData::empty () const override virtual
Implements ACLData< X509 * >.
Definition at line 143 of file CertificateData.cc.
References ACLStringData::empty(), and values.
lineOptions()
virtual const Acl::Options & ACLData< X509 * >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLCertificateData::match (X509 * cert) override virtual
Implements ACLData< X509 * >.
Definition at line 51 of file CertificateData.cc.
References attribute, SBuf::c_str(), debugs, SBuf::isEmpty(), ACLStringData::match(), sslAttributeCall, and values.
MEMPROXY_CLASS()
ACLCertificateData::MEMPROXY_CLASS (ACLCertificateData) private
parse()
void ACLCertificateData::parse () override virtual
Implements ACLData< X509 * >.
Definition at line 76 of file CertificateData.cc.
References attribute, attributeIsOptional, DBG_CRITICAL, debugs, ACLStringData::insert(), SBuf::isEmpty(), ACLStringData::parse(), self_destruct(), Acl::SetKey(), ConfigParser::strtokFile(), validAttributes, validAttributesStr, and values.
prepareForUse()
virtual void ACLData< X509 * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
attribute
SBuf ACLCertificateData::attribute
Definition at line 41 of file CertificateData.h.
Referenced by dump(), match(), and parse().
attributeIsOptional
bool ACLCertificateData::attributeIsOptional
Definition at line 40 of file CertificateData.h.
Referenced by parse().
sslAttributeCall
Ssl::GETX509ATTRIBUTE* ACLCertificateData::sslAttributeCall private
Definition at line 46 of file CertificateData.h.
Referenced by match().
validAttributes
std::list<std::string> ACLCertificateData::validAttributes
Definition at line 38 of file CertificateData.h.
Referenced by ACLCertificateData(), and parse().
validAttributesStr
const char* ACLCertificateData::validAttributesStr
A '|'-delimited list of valid ACL attributes. A "*" item means that any attribute is acceptable. Assumed to be a const-string and is never duped/freed. Nil unless ACL form is: acl Name type attribute value1 ...
Definition at line 36 of file CertificateData.h.
Referenced by dump(), and parse().
values
ACLStringData ACLCertificateData::values
Definition at line 42 of file CertificateData.h.
Referenced by dump(), empty(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/CertificateData.h
squid/src/acl/CertificateData.cc