Squid Web Cache: MemStoreRr Class Reference
MemStoreRr Class Reference
Public Types
typedef void(RegisteredRunner::* Method) ()
a pointer to one of the above notification methods
Public Member Functions
MemStoreRr ()
void finalizeConfig () override
void claimMemoryNeeds () override
void useConfig () override
~MemStoreRr () override
virtual void bootstrapConfig ()
virtual void startReconfigure ()
virtual void syncConfig ()
virtual void startShutdown ()
virtual void endingShutdown ()
virtual void finishShutdown ()
Meant for cleanup of services needed by the already destroyed objects.
Protected Member Functions
void create () override
called when the runner should create a new memory segment
virtual void open ()
Private Attributes
Ipc::Mem::Owner< Ipc::Mem::PageStack > * spaceOwner
free slices Owner
MemStoreMap::Owner * mapOwner
primary map Owner
Ipc::Mem::Owner< MemStoreMapExtras > * extrasOwner
PageIds Owner.
Detailed Description
reports our needs for shared memory pages to Ipc::Mem::Pages; decides whether to use a shared memory cache or checks its configuration; and initializes shared memory segments used by MemStore
Definition at line 979 of file MemStore.cc.
Member Typedef Documentation
Method
typedef void(RegisteredRunner::* RegisteredRunner::Method) () inherited
Definition at line 94 of file RunnersRegistry.h.
Constructor & Destructor Documentation
MemStoreRr()
MemStoreRr::MemStoreRr () inline
Definition at line 983 of file MemStore.cc.
~MemStoreRr()
MemStoreRr::~MemStoreRr () override
Definition at line 1057 of file MemStore.cc.
References extrasOwner, mapOwner, and spaceOwner.
Member Function Documentation
bootstrapConfig()
virtual void RegisteredRunner::bootstrapConfig () inline virtual inherited
Called right before parsing squid.conf. Meant for initializing/preparing configuration parsing facilities.
Reimplemented in NtlmAuthRr.
Definition at line 46 of file RunnersRegistry.h.
Referenced by SquidMain().
claimMemoryNeeds()
void MemStoreRr::claimMemoryNeeds () override virtual
Called after finalizeConfig(). Meant for announcing memory reservations before memory is allocated.
Reimplemented from RegisteredRunner.
Definition at line 1002 of file MemStore.cc.
References Ipc::Mem::PageId::cachePage, MemStore::EntryLimit(), and Ipc::Mem::NotePageNeed().
create()
void MemStoreRr::create () override protected virtual
Implements Ipc::Mem::RegisteredRunner.
Definition at line 1036 of file MemStore.cc.
References assert, Ipc::Mem::PageStack::Config::capacity, Ipc::Mem::PageStack::Config::createFull, MemStore::Enabled(), MemStore::EntryLimit(), ExtrasLabel, extrasOwner, Ipc::Mem::PageStack::IdForMemStoreSpace(), Ipc::StoreMap::Init(), MapLabel, mapOwner, Must, Ipc::Mem::PageStack::Config::pageSize, Ipc::Mem::PageStack::Config::poolId, shm_new, SpaceLabel, and spaceOwner.
endingShutdown()
virtual void RegisteredRunner::endingShutdown () inline virtual inherited
Called after shutdown_lifetime grace period ends and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented in Auth::CredentialCacheRr, ConnStateData, Dns::ConfigRr, and IdleConnList.
Definition at line 84 of file RunnersRegistry.h.
Referenced by SignalEngine::FinalShutdownRunners().
finalizeConfig()
void MemStoreRr::finalizeConfig () override virtual
Called after parsing squid.conf. Meant for setting configuration options that depend on other configuration options and were not explicitly configured.
Reimplemented from RegisteredRunner.
Definition at line 1008 of file MemStore.cc.
References Config, YesNoNone::configure(), YesNoNone::configured(), DBG_IMPORTANT, debugs, Ipc::Mem::Segment::Enabled(), fatal(), SquidConfig::memMaxSize, SquidConfig::memShared, Ipc::Mem::PageSize(), MemStore::Requested(), and UsingSmp().
finishShutdown()
virtual void RegisteredRunner::finishShutdown () inline virtual inherited
Definition at line 91 of file RunnersRegistry.h.
Referenced by RunRegistered(), SquidShutdown(), TestRock::tearDown(), and watch_child().
open()
virtual void Ipc::Mem::RegisteredRunner::open () inline protected virtual inherited
called when the runner should open a previously created segment, not needed if segments are opened in constructor or init methods
Reimplemented in CollapsedForwardingRr, and SharedMemPagesRr.
Definition at line 95 of file Segment.h.
startReconfigure()
virtual void RegisteredRunner::startReconfigure () inline virtual inherited
Called after receiving a reconfigure request and before parsing squid.conf. Meant for modules that need to prepare for their configuration being changed [outside their control]. The changes end with the syncConfig() event.
Reimplemented in Dns::ConfigRr, HtcpRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 67 of file RunnersRegistry.h.
Referenced by mainReconfigureStart().
startShutdown()
virtual void RegisteredRunner::startShutdown () inline virtual inherited
Called after receiving a shutdown request and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented in ConnStateData, Rock::Rebuild, HtcpRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 78 of file RunnersRegistry.h.
Referenced by SignalEngine::doShutdown().
syncConfig()
virtual void RegisteredRunner::syncConfig () inline virtual inherited
Called after parsing squid.conf during reconfiguration. Meant for adjusting the module state based on configuration changes.
Reimplemented in Auth::CredentialCacheRr, CarpRr, HtcpRr, PeerSourceHashRr, PeerUserHashRr, PeerPoolMgrsRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 71 of file RunnersRegistry.h.
Referenced by mainReconfigureFinish().
useConfig()
void MemStoreRr::useConfig () override virtual
Called after claimMemoryNeeds(). Meant for activating modules and features using a finalized configuration with known memory requirements.
Reimplemented from Ipc::Mem::RegisteredRunner.
Definition at line 1029 of file MemStore.cc.
References assert, Config, YesNoNone::configured(), SquidConfig::memShared, and Ipc::Mem::RegisteredRunner::useConfig().
Member Data Documentation
extrasOwner
Ipc::Mem::Owner<MemStoreMapExtras>* MemStoreRr::extrasOwner private
Definition at line 996 of file MemStore.cc.
Referenced by ~MemStoreRr(), and create().
mapOwner
MemStoreMap::Owner* MemStoreRr::mapOwner private
Definition at line 995 of file MemStore.cc.
Referenced by ~MemStoreRr(), and create().
spaceOwner
Ipc::Mem::Owner<Ipc::Mem::PageStack>* MemStoreRr::spaceOwner private
Definition at line 994 of file MemStore.cc.
Referenced by ~MemStoreRr(), and create().
The documentation for this class was generated from the following file:
squid/src/MemStore.cc