Squid Web Cache: CbDataListIterator< C > Class Template Reference
CbDataListIterator< C > Class Template Reference
#include <CbDataList.h>
Public Member Functions
CbDataListIterator (CbDataListContainer< C > const &list)
const C & next ()
bool end ()
Private Attributes
CbDataList< C > * next_entry
Detailed Description
template<class C>
class CbDataListIterator< C >
Definition at line 51 of file CbDataList.h.
Constructor & Destructor Documentation
CbDataListIterator()
template<class C > CbDataListIterator< C >::CbDataListIterator (CbDataListContainer< C > const & list) inline
Definition at line 54 of file CbDataList.h.
Member Function Documentation
end()
template<class C > bool CbDataListIterator< C >::end () inline
Definition at line 61 of file CbDataList.h.
References CbDataListIterator< C >::next_entry.
Referenced by ACLSquidErrorData::dump(), and ACLSquidErrorData::match().
next()
template<class C > const C & CbDataListIterator< C >::next () inline
Definition at line 55 of file CbDataList.h.
References CbDataList< C >::element, CbDataList< C >::next, and CbDataListIterator< C >::next_entry.
Referenced by ACLSquidErrorData::dump(), and ACLSquidErrorData::match().
Member Data Documentation
next_entry
template<class C > CbDataList<C>* CbDataListIterator< C >::next_entry private
Definition at line 66 of file CbDataList.h.
Referenced by CbDataListIterator< C >::end(), and CbDataListIterator< C >::next().
The documentation for this class was generated from the following file:
squid/src/base/CbDataList.h