Squid Web Cache: Ssl::PeekingPeerConnector Class Reference
Ssl::PeekingPeerConnector Class Reference abstract
A PeerConnector for HTTP origin servers. Capable of SslBumping.
#include <PeekingPeerConnector.h>
Public Types
typedef CbcPointer< PeerConnector > Pointer
Public Member Functions
PeekingPeerConnector (HttpRequestPointer &aRequest, const Comm::ConnectionPointer &aServerConn, const Comm::ConnectionPointer &aClientConn, const AsyncCallback< Security::EncryptorAnswer > &aCallback, const AccessLogEntryPointer &alp, time_t timeout=0)
bool initialize (Security::SessionPointer &) override
Security::FuturePeerContext * peerContext () const override
void noteWantWrite () override
void noteNegotiationError (const Security::ErrorDetailPointer &) override
Called when the SSL_connect function aborts with an SSL negotiation error.
void noteNegotiationDone (ErrorState *error) override
void handleServerCertificate ()
void checkForPeekAndSplice ()
void checkForPeekAndSpliceDone (Acl::Answer)
Callback function for ssl_bump acl check in step3 SSL bump step.
void checkForPeekAndSpliceMatched (const Ssl::BumpMode finalMode)
Handles the final bumping decision.
Ssl::BumpMode checkForPeekAndSpliceGuess () const
Guesses the final bumping decision when no ssl_bump rules match.
void serverCertificateVerified ()
void startTunneling ()
Abruptly stops TLS negotiation and starts tunneling.
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void cbCheckForPeekAndSpliceDone (Acl::Answer, void *data)
A wrapper function for checkForPeekAndSpliceDone for use with acl.
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
bool noteFwdPconnUse
hack: whether the connection requires fwdPconnPool->noteUses()
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void start () override
Preps connection and SSL state. Calls negotiate().
bool doneAll () const override
whether positive goal has been reached
void swanSong () override
const char * status () const override
internal cleanup; do not call directly
void fillChecklist (ACLFilledChecklist &) const override
configure the given checklist (to reflect the current transaction state)
void commTimeoutHandler (const CommTimeoutCbParams &)
The connection read timeout callback handler.
void commCloseHandler (const CommCloseCbParams &params)
The comm_close callback handler.
void negotiate ()
bool sslFinalized ()
void handleNegotiationResult (const Security::IoResult &)
Called after each negotiation step to handle the result.
void noteWantRead ()
bool isSuspended () const
Whether TLS negotiation has been paused and not yet resumed.
void suspendNegotiation (const Security::IoResult &lastError)
void resumeNegotiation ()
Resumes TLS negotiation paused by suspendNegotiation()
void handleMissingCertificates (const Security::IoResult &lastError)
Either initiates fetching of missing certificates or bails with an error.
void startCertDownloading (SBuf &url)
Start downloading procedure for the given URL.
void certDownloadingDone (DownloaderAnswer &)
Called by Downloader after a certificate object downloaded.
Comm::ConnectionPointer const & serverConnection () const
mimics FwdState to minimize changes to FwdState::initiate/negotiateSsl
void bail (ErrorState *error)
sends the given error to the initiator
void sendSuccess ()
sends the encrypted connection to the initiator
void callBack ()
a bail(), sendSuccess() helper: sends results to the initiator
void disconnect ()
a bail(), sendSuccess() helper: stops monitoring the connection
void countFailingConnection ()
updates connection usage history before the connection is closed
void bypassCertValidator ()
If called the certificates validator will not used.
void recordNegotiationDetails ()
EncryptorAnswer & answer ()
convenience method to get to the answer fields
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
HttpRequestPointer request
peer connection trigger or cause
Comm::ConnectionPointer serverConn
TCP connection to the peer.
AccessLogEntryPointer al
info for the future access.log entry
AsyncCallback< EncryptorAnswer > callback
answer destination
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
CBDATA_CHILD (PeekingPeerConnector)
void tunnelInsteadOfNegotiating ()
Inform caller class that the SSL negotiation aborted.
CBDATA_INTERMEDIATE ()
unsigned int certDownloadNestingLevel () const
the number of concurrent PeerConnector jobs waiting for us
void sslCrtvdHandleReply (Ssl::CertValidationResponsePointer &)
Process response from cert validator helper.
Security::CertErrors * sslCrtvdCheckForErrors (Ssl::CertValidationResponse const &, ErrorDetailPointer &)
Check SSL errors returned from cert validator against sslproxy_cert_error access list.
bool computeMissingCertificateUrls (const Connection &)
finds URLs of (some) missing intermediate certificates or returns false
void negotiateSsl ()
Comm::SetSelect() callback. Direct calls tickle/resume negotiations.
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Static Private Member Functions
static void NegotiateSsl (int fd, void *data)
A wrapper for Comm::SetSelect() notifications.
Private Attributes
Comm::ConnectionPointer clientConn
TCP connection to the client.
AsyncCall::Pointer closeHandler
we call this when the connection closed
bool splice
whether we are going to splice or not
bool serverCertificateHandled
whether handleServerCertificate() succeeded
Security::KeyLogger keyLogger
managers logging of the being-established TLS connection secrets
time_t negotiationTimeout
the SSL connection timeout to use
time_t startTime
when the peer connector negotiation started
bool useCertValidator_
std::queue< SBuf > urlsOfMissingCerts
The list of URLs where missing certificates should be downloaded.
unsigned int certsDownloads
the number of downloaded missing certificates
Ssl::X509_STACK_Pointer downloadedCerts
successfully downloaded intermediate certificates (omitted by the peer)
Security::IoResultPointer suspendedError_
outcome of the last (failed and) suspended negotiation attempt (or nil)
JobWait< Downloader > certDownloadWait
waits for the missing certificate to be downloaded
Static Private Attributes
static const unsigned int MaxCertsDownloads = 10
The maximum number of missing certificates a single PeerConnector may download.
static const unsigned int MaxNestedDownloads = 3
The maximum number of inter-dependent Downloader jobs a worker may initiate.
Detailed Description
Definition at line 20 of file PeekingPeerConnector.h.
Member Typedef Documentation
Pointer
typedef CbcPointer<PeerConnector> Security::PeerConnector::Pointer inherited
Definition at line 53 of file PeerConnector.h.
Constructor & Destructor Documentation
PeekingPeerConnector()
Ssl::PeekingPeerConnector::PeekingPeerConnector (HttpRequestPointer & aRequest, const Comm::ConnectionPointer & aServerConn, const Comm::ConnectionPointer & aClientConn, const AsyncCallback< Security::EncryptorAnswer > & aCallback, const AccessLogEntryPointer & alp, time_t timeout = 0)
Definition at line 29 of file PeekingPeerConnector.cc.
References HttpRequest::clientConnectionManager, Must, Security::PeerConnector::request, tlsBump3, and CbcPointer< Cbc >::valid().
Member Function Documentation
answer()
Security::EncryptorAnswer & Security::PeerConnector::answer () protected inherited
Definition at line 503 of file PeerConnector.cc.
References assert.
bail()
void Security::PeerConnector::bail (ErrorState * error) protected inherited
Definition at line 510 of file PeerConnector.cc.
References error(), and Must.
bypassCertValidator()
void Security::PeerConnector::bypassCertValidator () inline protected inherited
Definition at line 156 of file PeerConnector.h.
References Security::PeerConnector::useCertValidator_.
callBack()
void Security::PeerConnector::callBack () protected inherited
Definition at line 561 of file PeerConnector.cc.
References Assure, debugs, and ScheduleCallHere.
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
cbCheckForPeekAndSpliceDone()
void Ssl::PeekingPeerConnector::cbCheckForPeekAndSpliceDone (Acl::Answer aclAnswer, void * data) static
Definition at line 52 of file PeekingPeerConnector.cc.
References CallJobHere1.
Referenced by checkForPeekAndSplice().
CBDATA_CHILD()
Ssl::PeekingPeerConnector::CBDATA_CHILD (PeekingPeerConnector) private
CBDATA_INTERMEDIATE()
Security::PeerConnector::CBDATA_INTERMEDIATE () private inherited
certDownloadingDone()
void Security::PeerConnector::certDownloadingDone (DownloaderAnswer & downloaderAnswer) protected inherited
Definition at line 630 of file PeerConnector.cc.
References debugs, fd_table, Ssl::findIssuerCertificate(), Ssl::findIssuerUri(), Comm::IsConnOpen(), SBuf::length(), Must, DownloaderAnswer::outcome, SBuf::rawContent(), and DownloaderAnswer::resource.
Referenced by Security::PeerConnector::startCertDownloading().
certDownloadNestingLevel()
unsigned int Security::PeerConnector::certDownloadNestingLevel () const private inherited
Definition at line 607 of file PeerConnector.cc.
checkForPeekAndSplice()
void Ssl::PeekingPeerConnector::checkForPeekAndSplice ()
Initiates the ssl_bump acl check in step3 SSL bump step to decide about bumping, splicing or terminating the connection.
Definition at line 69 of file PeekingPeerConnector.cc.
References ACCESS_ALLOWED, BIO_get_data(), Ssl::bumpBump, Ssl::bumpClientFirst, Ssl::bumpNone, Ssl::bumpPeek, Ssl::bumpServerFirst, Ssl::bumpSplice, Ssl::bumpStare, Ssl::ServerBio::canBump(), Ssl::ServerBio::canSplice(), cbCheckForPeekAndSpliceDone(), fd_table, ACLFilledChecklist::Make(), and ACLFilledChecklist::NonBlockingCheck().
checkForPeekAndSpliceDone()
void Ssl::PeekingPeerConnector::checkForPeekAndSpliceDone (Acl::Answer aclAnswer)
Definition at line 60 of file PeekingPeerConnector.cc.
References Acl::Answer::allowed(), and Acl::Answer::kind.
checkForPeekAndSpliceGuess()
Ssl::BumpMode Ssl::PeekingPeerConnector::checkForPeekAndSpliceGuess () const
Definition at line 128 of file PeekingPeerConnector.cc.
References Ssl::bumpBump, Ssl::bumpSplice, Ssl::bumpStare, and debugs.
checkForPeekAndSpliceMatched()
void Ssl::PeekingPeerConnector::checkForPeekAndSpliceMatched (const Ssl::BumpMode finalMode)
Definition at line 92 of file PeekingPeerConnector.cc.
References BIO_get_data(), Ssl::bumpBump, Ssl::bumpSplice, Ssl::bumpTerminate, debugs, ERR_SECURE_CONNECT_FAIL, fd_table, Ssl::ServerBio::holdWrite(), Must, Security::PeerConnector::noteWantWrite(), Ssl::ServerBio::recordInput(), and Http::scForbidden.
commCloseHandler()
void Security::PeerConnector::commCloseHandler (const CommCloseCbParams & params) protected inherited
Definition at line 109 of file PeerConnector.cc.
References CommCommonCbParams::data, debugs, ERR_SECURE_CONNECT_FAIL, CommCommonCbParams::fd, MakeNamedErrorDetail(), and Http::scServiceUnavailable.
Referenced by Security::PeerConnector::PeerConnector().
commTimeoutHandler()
void Security::PeerConnector::commTimeoutHandler (const CommTimeoutCbParams &) protected inherited
Definition at line 129 of file PeerConnector.cc.
References debugs, ERR_SECURE_CONNECT_FAIL, MakeNamedErrorDetail(), and Http::scGatewayTimeout.
Referenced by Security::PeerConnector::noteWantRead().
computeMissingCertificateUrls()
bool Security::PeerConnector::computeMissingCertificateUrls (const Connection & sconn) private inherited
Definition at line 712 of file PeerConnector.cc.
References assert, debugs, and Ssl::missingChainCertificatesUrls().
countFailingConnection()
void Security::PeerConnector::countFailingConnection () protected inherited
Definition at line 534 of file PeerConnector.cc.
References assert, fd_table, fwdPconnPool, NoteOutgoingConnectionFailure(), and PconnPool::noteUses().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
disconnect()
void Security::PeerConnector::disconnect () protected inherited
Definition at line 544 of file PeerConnector.cc.
References comm_remove_close_handler(), commUnsetConnTimeout(), and Comm::IsConnOpen().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Security::PeerConnector::doneAll () const override protected virtual inherited
Reimplemented from AsyncJob.
Definition at line 63 of file PeerConnector.cc.
References AsyncJob::doneAll().
fillChecklist()
void Security::PeerConnector::fillChecklist (ACLFilledChecklist &) const override protected virtual inherited
Implements Acl::ChecklistFiller.
Reimplemented in Ssl::IcapPeerConnector.
Definition at line 91 of file PeerConnector.cc.
References ACLFilledChecklist::al, fd_table, Security::LockingPointer< T, UnLocker, Locker >::resetWithoutLocking(), ACLFilledChecklist::serverCert, and ACLFilledChecklist::syncAle().
Referenced by Ssl::IcapPeerConnector::fillChecklist().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
handleMissingCertificates()
void Security::PeerConnector::handleMissingCertificates (const Security::IoResult & lastError) protected inherited
Definition at line 686 of file PeerConnector.cc.
References assert, Ssl::VerifyCallbackParameters::At(), Ssl::VerifyCallbackParameters::callerHandlesMissingCertificates, fd_table, Comm::IsConnOpen(), and Must.
handleNegotiationResult()
void Security::PeerConnector::handleNegotiationResult (const Security::IoResult & result) protected inherited
Definition at line 259 of file PeerConnector.cc.
References Security::IoResult::category, debugs, Security::IoResult::errorDetail, Debug::Extra(), Security::IoResult::ioError, Security::IoResult::ioSuccess, Security::IoResult::ioWantRead, and Security::IoResult::ioWantWrite.
handleServerCertificate()
void Ssl::PeekingPeerConnector::handleServerCertificate ()
Updates associated client connection manager members if the server certificate was received from the server.
Definition at line 385 of file PeekingPeerConnector.cc.
References fd_table.
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
initialize()
bool Ssl::PeekingPeerConnector::initialize (Security::SessionPointer & serverSession) override virtual
Returns
true on successful TLS session initialization
Reimplemented from Security::PeerConnector.
Definition at line 151 of file PeekingPeerConnector.cc.
References applyTlsDetailsToSSL(), asHex(), BIO_get_data(), Ssl::bumpPeek, Ssl::bumpStare, SBuf::c_str(), debugs, fd_table, Security::PeerConnector::initialize(), Comm::IsConnOpen(), Ssl::ServerBio::mode(), Must, AnyP::PROTO_NONE, Ssl::Bio::rBufData(), Ssl::ServerBio::recordInput(), Ssl::ServerBio::setClientFeatures(), Ssl::setClientSNI(), ssl_ex_index_server, and ssl_ex_index_ssl_peeked_cert.
isSuspended()
bool Security::PeerConnector::isSuspended () const inline protected inherited
Definition at line 101 of file PeerConnector.h.
References Security::PeerConnector::suspendedError_.
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
negotiate()
void Security::PeerConnector::negotiate () protected inherited
Performs a single secure connection negotiation step. It is called multiple times until the negotiation finishes or aborts.
Definition at line 213 of file PeerConnector.cc.
References Ssl::VerifyCallbackParameters::At(), Security::Connect(), DBG_IMPORTANT, debugs, fd_table, Security::IoResult::ioSuccess, Comm::IsConnOpen(), and Must.
negotiateSsl()
void Security::PeerConnector::negotiateSsl () private inherited
Definition at line 455 of file PeerConnector.cc.
References CallJobHere.
NegotiateSsl()
void Security::PeerConnector::NegotiateSsl (int fd, void * data) static private inherited
Definition at line 445 of file PeerConnector.cc.
noteNegotiationDone()
void Ssl::PeekingPeerConnector::noteNegotiationDone (ErrorState *) override virtual
Called when the SSL negotiation to the server completed and the certificates validated using the cert validator.
Parameters
error if not NULL the SSL negotiation was aborted with an error
Reimplemented from Security::PeerConnector.
Definition at line 239 of file PeekingPeerConnector.cc.
References Ssl::CommonHostName(), debugs, ERR_GATEWAY_FAILURE, error(), fd_table, Here, Comm::IsConnOpen(), and Http::scInternalServerError.
noteNegotiationError()
void Ssl::PeekingPeerConnector::noteNegotiationError (const Security::ErrorDetailPointer & detail) override virtual
Reimplemented from Security::PeerConnector.
Definition at line 323 of file PeekingPeerConnector.cc.
References BIO_get_data(), Ssl::ServerBio::bumpMode(), Ssl::bumpPeek, Ssl::bumpSplice, Ssl::bumpStare, debugs, Ssl::ServerBio::encryptedCertificates(), fd_table, Ssl::ServerBio::holdWrite(), Security::PeerConnector::noteNegotiationError(), Ssl::ServerBio::resumingSession(), and ssl_ex_index_ssl_error_detail.
noteWantRead()
void Security::PeerConnector::noteWantRead () protected inherited
Called when the openSSL SSL_connect function request more data from the remote SSL server. Sets the read timeout and sets the Squid COMM_SELECT_READ handler.
Definition at line 462 of file PeerConnector.cc.
References COMM_SELECT_READ, commSetConnTimeout(), Security::PeerConnector::commTimeoutHandler(), debugs, Comm::IsConnOpen(), JobCallback, Comm::MortalReadTimeout(), Must, and Comm::SetSelect().
noteWantWrite()
void Ssl::PeekingPeerConnector::noteWantWrite () override virtual
Called when the openSSL SSL_connect function needs to write data to the remote SSL server. Sets the Squid COMM_SELECT_WRITE handler.
Reimplemented from Security::PeerConnector.
Definition at line 306 of file PeekingPeerConnector.cc.
References BIO_get_data(), Ssl::ServerBio::bumpMode(), Ssl::bumpPeek, Ssl::bumpStare, debugs, fd_table, Ssl::ServerBio::holdWrite(), and Security::PeerConnector::noteWantWrite().
peerContext()
Security::FuturePeerContext * Ssl::PeekingPeerConnector::peerContext () const override virtual
peer's security context
Returns
nil if Squid is built without TLS support (XXX: Prevent PeerConnector creation in those cases instead)
Implements Security::PeerConnector.
Definition at line 145 of file PeekingPeerConnector.cc.
recordNegotiationDetails()
void Security::PeerConnector::recordNegotiationDetails () protected inherited
Called after negotiation finishes to record connection details for logging
Definition at line 193 of file PeerConnector.cc.
References BIO_get_data(), fd_table, Comm::IsConnOpen(), Must, and Ssl::ServerBio::receivedHelloDetails().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
resumeNegotiation()
void Security::PeerConnector::resumeNegotiation () protected inherited
Definition at line 746 of file PeerConnector.cc.
References fd_table, Must, SQUID_TLS_ERR_CONNECT, and Ssl::VerifyConnCertificates().
sendSuccess()
void Security::PeerConnector::sendSuccess () protected inherited
Definition at line 525 of file PeerConnector.cc.
References assert, and Comm::IsConnOpen().
serverCertificateVerified()
void Ssl::PeekingPeerConnector::serverCertificateVerified ()
Runs after the server certificate verified to update client connection manager members
Definition at line 407 of file PeekingPeerConnector.cc.
References Ssl::CommonHostName(), debugs, fd_table, Security::LockingPointer< T, UnLocker, Locker >::get(), Security::LockingPointer< T, UnLocker, Locker >::resetAndLock(), and Security::LockingPointer< T, UnLocker, Locker >::resetWithoutLocking().
serverConnection()
Comm::ConnectionPointer const & Security::PeerConnector::serverConnection () const inline protected inherited
Definition at line 138 of file PeerConnector.h.
References Security::PeerConnector::serverConn.
Referenced by Security::BlindPeerConnector::peerContext().
sslCrtvdCheckForErrors()
Security::CertErrors * Security::PeerConnector::sslCrtvdCheckForErrors (Ssl::CertValidationResponse const & resp, ErrorDetailPointer & errDetails) private inherited
Checks errors in the cert. validator response against sslproxy_cert_error. The first honored error, if any, is returned via errDetails parameter. The method returns all seen errors except SSL_ERROR_NONE as Security::CertErrors.
Definition at line 385 of file PeerConnector.cc.
References assert, SquidConfig::cert_error, Config, debugs, Ssl::CertValidationResponse::errors, fd_table, Comm::IsConnOpen(), Must, and CbDataList< C >::push_back_unique().
sslCrtvdHandleReply()
void Security::PeerConnector::sslCrtvdHandleReply (Ssl::CertValidationResponsePointer & validationResponse) private inherited
Definition at line 334 of file PeerConnector.cc.
References debugs, ErrorState::detailError(), Debug::Enabled(), ERR_GATEWAY_FAILURE, ERR_SECURE_CONNECT_FAIL, Helper::Error, fd_table, Comm::IsConnOpen(), Must, Helper::Okay, RawPointer(), Http::scInternalServerError, Http::scServiceUnavailable, server, ssl_ex_index_server, and ssl_ex_index_ssl_errors.
Referenced by Security::PeerConnector::sslFinalized().
sslFinalized()
bool Security::PeerConnector::sslFinalized () protected inherited
Called after negotiation has finished. Cleans up TLS/SSL state. Returns false if we are now waiting for the certs validation job. Otherwise, returns true, regardless of negotiation success/failure.
Definition at line 289 of file PeerConnector.cc.
References asyncCallback, DBG_IMPORTANT, debugs, Ssl::CertValidationRequest::domainName, ERR_GATEWAY_FAILURE, Ssl::CertValidationRequest::errors, fd_table, Comm::IsConnOpen(), Must, Http::scInternalServerError, Ssl::CertValidationRequest::ssl, ssl_ex_index_server, ssl_ex_index_ssl_errors, Security::PeerConnector::sslCrtvdHandleReply(), Ssl::CertValidationHelper::Submit(), and Ssl::TheConfig.
start()
void Security::PeerConnector::start () override protected virtual inherited
Reimplemented from AsyncJob.
Definition at line 70 of file PeerConnector.cc.
References assert, debugs, ERR_CONNECT_FAIL, fd_table, Comm::IsConnOpen(), Http::scBadGateway, and AsyncJob::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
startCertDownloading()
void Security::PeerConnector::startCertDownloading (SBuf & url) protected inherited
Definition at line 620 of file PeerConnector.cc.
References asyncCallback, and Security::PeerConnector::certDownloadingDone().
startTunneling()
void Ssl::PeekingPeerConnector::startTunneling ()
Definition at line 286 of file PeekingPeerConnector.cc.
References BIO_get_data(), debugs, fd_table, and switchToTunnel().
status()
const char * Security::PeerConnector::status () const override protected virtual inherited
for debugging, starts with space
Reimplemented from AsyncJob.
Definition at line 584 of file PeerConnector.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), Comm::IsConnOpen(), MemBuf::reset(), and MemBuf::terminate().
suspendNegotiation()
void Security::PeerConnector::suspendNegotiation (const Security::IoResult & lastError) protected inherited
Suspends TLS negotiation to download the missing certificates
Parameters
lastError an error to handle when resuming negotiations
Definition at line 736 of file PeerConnector.cc.
References debugs, and Must.
swanSong()
void Security::PeerConnector::swanSong () override protected virtual inherited
Reimplemented from AsyncJob.
Definition at line 569 of file PeerConnector.cc.
References assert, ERR_GATEWAY_FAILURE, Http::scInternalServerError, and AsyncJob::swanSong().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
tunnelInsteadOfNegotiating()
void Ssl::PeekingPeerConnector::tunnelInsteadOfNegotiating () private
Member Data Documentation
al
AccessLogEntryPointer Security::PeerConnector::al protected inherited
Definition at line 167 of file PeerConnector.h.
callback
AsyncCallback<EncryptorAnswer> Security::PeerConnector::callback protected inherited
Definition at line 170 of file PeerConnector.h.
certDownloadWait
JobWait<Downloader> Security::PeerConnector::certDownloadWait private inherited
Definition at line 216 of file PeerConnector.h.
certsDownloads
unsigned int Security::PeerConnector::certsDownloads private inherited
Definition at line 206 of file PeerConnector.h.
clientConn
Comm::ConnectionPointer Ssl::PeekingPeerConnector::clientConn private
Definition at line 69 of file PeekingPeerConnector.h.
closeHandler
AsyncCall::Pointer Ssl::PeekingPeerConnector::closeHandler private
Definition at line 70 of file PeekingPeerConnector.h.
downloadedCerts
Ssl::X509_STACK_Pointer Security::PeerConnector::downloadedCerts private inherited
Definition at line 210 of file PeerConnector.h.
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
keyLogger
Security::KeyLogger Security::PeerConnector::keyLogger private inherited
Definition at line 198 of file PeerConnector.h.
MaxCertsDownloads
const unsigned int Security::PeerConnector::MaxCertsDownloads = 10 static private inherited
Definition at line 192 of file PeerConnector.h.
MaxNestedDownloads
const unsigned int Security::PeerConnector::MaxNestedDownloads = 3 static private inherited
Definition at line 195 of file PeerConnector.h.
negotiationTimeout
time_t Security::PeerConnector::negotiationTimeout private inherited
Definition at line 201 of file PeerConnector.h.
noteFwdPconnUse
bool Security::PeerConnector::noteFwdPconnUse inherited
Definition at line 62 of file PeerConnector.h.
Referenced by FwdState::secureConnectionToPeer().
request
HttpRequestPointer Security::PeerConnector::request protected inherited
Definition at line 165 of file PeerConnector.h.
Referenced by Security::BlindPeerConnector::BlindPeerConnector(), and PeekingPeerConnector().
serverCertificateHandled
bool Ssl::PeekingPeerConnector::serverCertificateHandled private
Definition at line 72 of file PeekingPeerConnector.h.
serverConn
Comm::ConnectionPointer Security::PeerConnector::serverConn protected inherited
Definition at line 166 of file PeerConnector.h.
Referenced by Security::PeerConnector::PeerConnector(), and Security::PeerConnector::serverConnection().
splice
bool Ssl::PeekingPeerConnector::splice private
Definition at line 71 of file PeekingPeerConnector.h.
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
startTime
time_t Security::PeerConnector::startTime private inherited
Definition at line 202 of file PeerConnector.h.
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
suspendedError_
Security::IoResultPointer Security::PeerConnector::suspendedError_ private inherited
Definition at line 214 of file PeerConnector.h.
Referenced by Security::PeerConnector::isSuspended().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
urlsOfMissingCerts
std::queue<SBuf> Security::PeerConnector::urlsOfMissingCerts private inherited
Definition at line 205 of file PeerConnector.h.
useCertValidator_
bool Security::PeerConnector::useCertValidator_ private inherited
whether the certificate validator should bypassed
Definition at line 203 of file PeerConnector.h.
Referenced by Security::PeerConnector::bypassCertValidator().
The documentation for this class was generated from the following files:
squid/src/ssl/PeekingPeerConnector.h
squid/src/ssl/PeekingPeerConnector.cc