Squid Web Cache: Adaptation::Ecap::Config Class Reference
Adaptation::Ecap::Config Class Reference
General eCAP configuration.
#include <Config.h>
Public Types
typedef std::vector< ServiceConfigPointer > ServiceConfigs
Public Member Functions
Config ()
~Config () override
bool finalize () override
void parseService (void)
void freeService (void)
void dumpService (StoreEntry *, const char *) const
ServiceConfigPointer findServiceConfig (const String &)
Static Public Member Functions
static void Finalize (bool enable)
static void ParseServiceSet (void)
static void ParseServiceChain (void)
static void ParseAccess (ConfigParser &parser)
static void FreeAccess (void)
static void DumpAccess (StoreEntry *, const char *)
static Notes & metaHeaders ()
The list of configured meta headers.
Public Attributes
int onoff
int service_failure_limit
time_t oldest_service_failure
int service_revival_delay
ServiceConfigs serviceConfigs
Static Public Attributes
static bool Enabled = false
static char * masterx_shared_name = nullptr
static int service_iteration_limit = 16
static int send_client_ip = false
static int send_username = false
static int use_indirect_client = true
static bool needHistory = false
HttpRequest adaptation history should recorded.
Protected Member Functions
Adaptation::ServiceConfig * newServiceConfig () const override
creates service configuration object that will parse and keep cfg info
virtual void clear ()
Removes any reference to the services from configuration.
void removeService (const String &service)
Removes the given service from all service groups.
void removeRule (const String &id)
Removes access rules of the given service or group.
Private Member Functions
Config (const Config &)
Config & operator= (const Config &)
Adaptation::ServicePointer createService (const ServiceConfigPointer &cfg) override
Static Private Member Functions
static void ParseServiceGroup (ServiceGroupPointer group)
static void FreeServiceGroups (void)
static void DumpServiceGroups (StoreEntry *, const char *)
Detailed Description
Definition at line 38 of file Config.h.
Member Typedef Documentation
ServiceConfigs
typedef std::vector<ServiceConfigPointer> Adaptation::Config::ServiceConfigs inherited
Definition at line 62 of file Config.h.
Constructor & Destructor Documentation
Config() [1/2]
Adaptation::Ecap::Config::Config ()
Definition at line 18 of file Config.cc.
~Config()
Adaptation::Ecap::Config::~Config () override virtual
Reimplemented from Adaptation::Config.
Definition at line 22 of file Config.cc.
Config() [2/2]
Adaptation::Ecap::Config::Config (const Config &) private
Member Function Documentation
clear()
void Adaptation::Config::clear () protected virtual inherited
Definition at line 127 of file Config.cc.
References Adaptation::AllGroups(), Adaptation::AllRules(), debugs, and size.
createService()
Adaptation::ServicePointer Adaptation::Ecap::Config::createService (const ServiceConfigPointer & cfg) override private virtual
Implements Adaptation::Config.
Definition at line 43 of file Config.cc.
DumpAccess()
void Adaptation::Config::DumpAccess (StoreEntry * entry, const char * name) static inherited
Definition at line 305 of file Config.cc.
References Adaptation::AllRules(), dump_acl_access(), LOCAL_ARRAY, SQUIDSTRINGPH, and SQUIDSTRINGPRINT.
dumpService()
void Adaptation::Config::dumpService (StoreEntry * entry, const char * name) const inherited
Definition at line 163 of file Config.cc.
References Adaptation::AllServices(), Adaptation::ServiceConfig::bypass, String::caseCmp(), Adaptation::ServiceConfig::connectionEncryption, Security::PeerOptions::encryptTransport, Adaptation::ServiceConfig::key, Adaptation::ServiceConfig::methodStr(), Adaptation::ServiceConfig::protocol, Adaptation::ServiceConfig::secure, SQUIDSTRINGPH, SQUIDSTRINGPRINT, storeAppendPrintf(), Adaptation::ServiceConfig::uri, and Adaptation::ServiceConfig::vectPointStr().
Referenced by dump_ecap_service_type(), and dump_icap_service_type().
DumpServiceGroups()
void Adaptation::Config::DumpServiceGroups (StoreEntry * entry, const char * name) static private inherited
Definition at line 276 of file Config.cc.
References Adaptation::AllGroups(), SQUIDSTRINGPH, SQUIDSTRINGPRINT, and storeAppendPrintf().
finalize()
bool Adaptation::Ecap::Config::finalize () override virtual
Creates and starts the adaptation services. In the case the adaptation mechanism is disabled then removes any reference to the services from access rules and service groups, and returns false.
Returns
true if the services are ready and running, false otherwise
Reimplemented from Adaptation::Config.
Definition at line 27 of file Config.cc.
References Adaptation::AllServices(), Adaptation::Ecap::CheckUnusedAdapterServices(), Adaptation::Config::finalize(), and Adaptation::Ecap::Host::Register().
Referenced by mainInitialize(), and mainReconfigureFinish().
Finalize()
void Adaptation::Config::Finalize (bool enable) static inherited
Definition at line 236 of file Config.cc.
References Adaptation::AllGroups(), Adaptation::AllRules(), Adaptation::AllServices(), debugs, FinalizeEach(), and Important.
Referenced by mainInitialize(), and mainReconfigureFinish().
findServiceConfig()
Adaptation::ServiceConfigPointer Adaptation::Config::findServiceConfig (const String & service) inherited
Definition at line 97 of file Config.cc.
FreeAccess()
void Adaptation::Config::FreeAccess (void) static inherited
Definition at line 296 of file Config.cc.
References Adaptation::AllRules().
freeService()
void Adaptation::Config::freeService (void) inherited
Definition at line 152 of file Config.cc.
References Adaptation::DetachServices().
Referenced by free_ecap_service_type(), free_icap_service_type(), and SquidShutdown().
FreeServiceGroups()
void Adaptation::Config::FreeServiceGroups (void) static private inherited
Definition at line 267 of file Config.cc.
References Adaptation::AllGroups().
metaHeaders()
Notes & Adaptation::Config::metaHeaders () static inherited
Definition at line 35 of file Config.cc.
References Adaptation::Config::metaHeaders().
Referenced by accessLogInit(), Adaptation::Icap::ModXact::makeRequestHeaders(), Adaptation::Config::metaHeaders(), Adaptation::Ecap::XactionRep::metaValue(), Adaptation::Ecap::XactionRep::start(), and Adaptation::Ecap::XactionRep::visitEachMetaHeader().
newServiceConfig()
Adaptation::ServiceConfig * Adaptation::Ecap::Config::newServiceConfig () const override protected virtual
Reimplemented from Adaptation::Config.
Definition at line 37 of file Config.cc.
operator=()
Config & Adaptation::Ecap::Config::operator= (const Config &) private
ParseAccess()
void Adaptation::Config::ParseAccess (ConfigParser & parser) static inherited
Definition at line 284 of file Config.cc.
References Adaptation::AllRules(), Adaptation::FindRuleByGroupId(), ConfigParser::NextToken(), and Adaptation::AccessRule::parse().
Referenced by parse_adaptation_access_type(), and parse_icap_access_type().
parseService()
void Adaptation::Config::parseService (void) inherited
Definition at line 141 of file Config.cc.
References cfg_filename, config_lineno, fatalf(), and Adaptation::ServiceConfig::parse().
Referenced by parse_ecap_service_type(), and parse_icap_service_type().
ParseServiceChain()
void Adaptation::Config::ParseServiceChain (void) static inherited
Definition at line 253 of file Config.cc.
References Adaptation::Config::ParseServiceGroup().
Referenced by parse_adaptation_service_chain_type().
ParseServiceGroup()
void Adaptation::Config::ParseServiceGroup (ServiceGroupPointer group) static private inherited
Definition at line 259 of file Config.cc.
References Adaptation::AllGroups(), assert, and Adaptation::ServiceGroup::parse().
Referenced by Adaptation::Config::ParseServiceChain(), and Adaptation::Config::ParseServiceSet().
ParseServiceSet()
void Adaptation::Config::ParseServiceSet (void) static inherited
Definition at line 247 of file Config.cc.
References Adaptation::Config::ParseServiceGroup().
Referenced by parse_adaptation_service_set_type(), and parse_icap_class_type().
removeRule()
void Adaptation::Config::removeRule (const String & id) protected inherited
Definition at line 109 of file Config.cc.
References Adaptation::AllRules(), debugs, and Adaptation::AccessRule::groupId.
removeService()
void Adaptation::Config::removeService (const String & service) protected inherited
Definition at line 66 of file Config.cc.
References Adaptation::AllGroups(), debugs, Adaptation::ServiceGroup::id, Adaptation::ServiceGroup::removedServices, and Adaptation::ServiceGroup::services.
Member Data Documentation
Enabled
bool Adaptation::Config::Enabled = false static inherited
Definition at line 42 of file Config.h.
Referenced by Adaptation::AccessCheck::Start().
masterx_shared_name
char * Adaptation::Config::masterx_shared_name = nullptr static inherited
Definition at line 45 of file Config.h.
Referenced by Adaptation::Icap::ModXact::makeRequestHeaders(), Adaptation::Ecap::XactionRep::option(), Adaptation::Icap::ModXact::parseIcapHead(), Adaptation::Ecap::XactionRep::updateHistory(), and Adaptation::Ecap::XactionRep::visitEachOption().
needHistory
bool Adaptation::Config::needHistory = false static inherited
Definition at line 60 of file Config.h.
Referenced by ACLAdaptationServiceData::parse(), Adaptation::Iterator::start(), and Adaptation::Iterator::step().
oldest_service_failure
time_t Adaptation::Config::oldest_service_failure inherited
Definition at line 55 of file Config.h.
Referenced by dump_icap_service_failure_limit(), Adaptation::Icap::ServiceRep::finalize(), free_icap_service_failure_limit(), Adaptation::Icap::ServiceRep::noteFailure(), and parse_icap_service_failure_limit().
onoff
int Adaptation::Config::onoff inherited
Definition at line 53 of file Config.h.
Referenced by mainInitialize(), and mainReconfigureFinish().
send_client_ip
int Adaptation::Config::send_client_ip = false static inherited
Definition at line 47 of file Config.h.
Referenced by Adaptation::Ecap::XactionRep::clientIpValue(), and Adaptation::Icap::ModXact::makeRequestHeaders().
send_username
int Adaptation::Config::send_username = false static inherited
Definition at line 48 of file Config.h.
Referenced by Adaptation::Icap::ModXact::makeRequestHeaders().
service_failure_limit
int Adaptation::Config::service_failure_limit inherited
Definition at line 54 of file Config.h.
Referenced by dump_icap_service_failure_limit(), free_icap_service_failure_limit(), Adaptation::Icap::ServiceRep::noteFailure(), and parse_icap_service_failure_limit().
service_iteration_limit
int Adaptation::Config::service_iteration_limit = 16 static inherited
Definition at line 46 of file Config.h.
Referenced by Adaptation::Iterator::step().
service_revival_delay
int Adaptation::Config::service_revival_delay inherited
Definition at line 56 of file Config.h.
Referenced by Adaptation::Icap::ServiceRep::optionsFetchTime(), and Adaptation::Icap::ServiceRep::suspend().
serviceConfigs
ServiceConfigs Adaptation::Config::serviceConfigs inherited
Definition at line 63 of file Config.h.
use_indirect_client
int Adaptation::Config::use_indirect_client = true static inherited
Definition at line 49 of file Config.h.
Referenced by Adaptation::Ecap::XactionRep::clientIpValue(), and Adaptation::Icap::ModXact::makeRequestHeaders().
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/Config.h
squid/src/adaptation/ecap/Config.cc