Squid Web Cache: BlockingDiskIOModule Class Reference
BlockingDiskIOModule Class Reference
#include <BlockingDiskIOModule.h>
Public Types
typedef std::vector< DiskIOModule * >::iterator iterator
typedef std::vector< DiskIOModule * >::const_iterator const_iterator
Public Member Functions
BlockingDiskIOModule ()
void init () override
void gracefulShutdown () override
char const * type () const override
DiskIOStrategy * createStrategy () override
Static Public Member Functions
static BlockingDiskIOModule & GetInstance ()
static void SetupAllModules ()
static void ModuleAdd (DiskIOModule &)
static void FreeAllModules ()
static DiskIOModule * Find (char const *type)
static DiskIOModule * FindDefault ()
static std::vector< DiskIOModule * > const & Modules ()
Static Protected Member Functions
static void RegisterAllModulesWithCacheManager (void)
Static Private Member Functions
static std::vector< DiskIOModule * > & GetModules ()
Static Private Attributes
static BlockingDiskIOModule Instance
static std::vector< DiskIOModule * > * _Modules = nullptr
Detailed Description
Definition at line 14 of file BlockingDiskIOModule.h.
Member Typedef Documentation
const_iterator
typedef std::vector<DiskIOModule*>::const_iterator DiskIOModule::const_iterator inherited
Definition at line 37 of file DiskIOModule.h.
iterator
typedef std::vector<DiskIOModule*>::iterator DiskIOModule::iterator inherited
Definition at line 36 of file DiskIOModule.h.
Constructor & Destructor Documentation
BlockingDiskIOModule()
BlockingDiskIOModule::BlockingDiskIOModule ()
Definition at line 13 of file BlockingDiskIOModule.cc.
References DiskIOModule::ModuleAdd().
Member Function Documentation
createStrategy()
DiskIOStrategy * BlockingDiskIOModule::createStrategy () override virtual
Implements DiskIOModule.
Definition at line 33 of file BlockingDiskIOModule.cc.
Find()
DiskIOModule * DiskIOModule::Find (char const * type) static inherited
Definition at line 114 of file DiskIOModule.cc.
References DiskIOModule::GetModules(), and DiskIOModule::type().
Referenced by Fs::Ufs::UFSSwapDir::UFSSwapDir(), DiskIOModule::FindDefault(), Rock::SwapDir::init(), Rock::SwapDir::needsDiskStrand(), and TestUfs::testUfsSearch().
FindDefault()
DiskIOModule * DiskIOModule::FindDefault () static inherited
Find any usable disk module. This will look for the 'best' available module for this system.
Best IO options are in order:
Definition at line 124 of file DiskIOModule.cc.
References DiskIOModule::Find().
FreeAllModules()
void DiskIOModule::FreeAllModules () static inherited
Called when a graceful shutdown is to occur of each fs module.
Definition at line 104 of file DiskIOModule.cc.
References DiskIOModule::GetModules(), and DiskIOModule::gracefulShutdown().
Referenced by SquidShutdown().
GetInstance()
BlockingDiskIOModule & BlockingDiskIOModule::GetInstance () static
Definition at line 19 of file BlockingDiskIOModule.cc.
References Instance.
Referenced by DiskIOModule::SetupAllModules().
GetModules()
std::vector< DiskIOModule * > & DiskIOModule::GetModules () static private inherited
Definition at line 91 of file DiskIOModule.cc.
References DiskIOModule::_Modules.
Referenced by DiskIOModule::Find(), DiskIOModule::FreeAllModules(), DiskIOModule::ModuleAdd(), DiskIOModule::Modules(), and DiskIOModule::SetupAllModules().
gracefulShutdown()
void BlockingDiskIOModule::gracefulShutdown () override virtual
Implements DiskIOModule.
Definition at line 29 of file BlockingDiskIOModule.cc.
init()
void BlockingDiskIOModule::init () override virtual
Implements DiskIOModule.
Definition at line 25 of file BlockingDiskIOModule.cc.
ModuleAdd()
void DiskIOModule::ModuleAdd (DiskIOModule & instance) static inherited
Definition at line 72 of file DiskIOModule.cc.
References assert, DiskIOModule::GetModules(), and DiskIOModule::type().
Referenced by BlockingDiskIOModule(), DiskDaemonDiskIOModule::DiskDaemonDiskIOModule(), DiskThreadsDiskIOModule::DiskThreadsDiskIOModule(), IpcIoDiskIOModule::IpcIoDiskIOModule(), and MmappedDiskIOModule::MmappedDiskIOModule().
Modules()
std::vector< DiskIOModule * > const & DiskIOModule::Modules () static inherited
Definition at line 85 of file DiskIOModule.cc.
References DiskIOModule::GetModules().
RegisterAllModulesWithCacheManager()
static void DiskIOModule::RegisterAllModulesWithCacheManager (void) static protected inherited
SetupAllModules()
void DiskIOModule::SetupAllModules () static inherited
Poke all compiled modules for self-setup
Definition at line 45 of file DiskIOModule.cc.
References GetInstance(), DiskDaemonDiskIOModule::GetInstance(), DiskThreadsDiskIOModule::GetInstance(), IpcIoDiskIOModule::GetInstance(), MmappedDiskIOModule::GetInstance(), and DiskIOModule::GetModules().
Referenced by SquidMain().
type()
char const * BlockingDiskIOModule::type () const override virtual
Implements DiskIOModule.
Definition at line 41 of file BlockingDiskIOModule.cc.
Member Data Documentation
_Modules
std::vector< DiskIOModule * > * DiskIOModule::_Modules = nullptr static private inherited
Definition at line 57 of file DiskIOModule.h.
Referenced by DiskIOModule::GetModules().
Instance
BlockingDiskIOModule BlockingDiskIOModule::Instance static private
Definition at line 26 of file BlockingDiskIOModule.h.
Referenced by GetInstance().
The documentation for this class was generated from the following files:
squid/src/DiskIO/Blocking/BlockingDiskIOModule.h
squid/src/DiskIO/Blocking/BlockingDiskIOModule.cc