Squid Web Cache: Acl::Node Class Reference
Acl::Node Class Reference abstract
Squid Components » Access Controls
#include <Node.h>
Public Types
using Pointer = RefCount< Node >
Public Member Functions
void * operator new (size_t)
void operator delete (void *)
Node ()
Node (Node &&)=delete
virtual ~Node ()
void context (const SBuf &aName, const char *configuration)
sets user-specified ACL name and squid.conf context
bool matches (ACLChecklist *checklist) const
void parseFlags ()
configures Acl::Node options, throwing on configuration errors
virtual void parse ()=0
parses node representation in squid.conf; dies on failures
virtual char const * typeString () const =0
virtual bool isProxyAuth () const
virtual SBufList dump () const =0
virtual bool empty () const =0
virtual bool valid () const
int cacheMatchAcl (dlink_list *cache, ACLChecklist *)
virtual int matchForCache (ACLChecklist *checklist)
virtual void prepareForUse ()
void dumpWhole (const char *directiveName, std::ostream &)
Static Public Member Functions
static void ParseNamedAcl (ConfigParser &, NamedAcls *&)
parses acl directive parts that follow directive name (i.e. "acl")
static void Initialize ()
static Acl::Node * FindByName (const SBuf &)
A configured ACL with a given name or nil.
Public Attributes
SBuf name
char * cfgline = nullptr
Private Member Functions
virtual int match (ACLChecklist *checklist)=0
Matches the actual data in checklist against this Acl::Node.
virtual bool requiresAle () const
whether our (i.e. shallow) match() requires checklist to have a AccessLogEntry
virtual bool requiresRequest () const
whether our (i.e. shallow) match() requires checklist to have a request
virtual bool requiresReply () const
whether our (i.e. shallow) match() requires checklist to have a reply
virtual const Acl::Options & options ()
virtual const Acl::Options & lineOptions ()
Static Private Member Functions
static void ParseNamed (ConfigParser &, NamedAcls &, const SBuf &name)
parses acl directive parts that follow aclname
Detailed Description
A configurable condition. A node in the ACL expression tree. Can evaluate itself in FilledChecklist context. Does not change during evaluation.
Definition at line 25 of file Node.h.
Member Typedef Documentation
Pointer
using Acl::Node::Pointer = RefCount<Node>
Definition at line 29 of file Node.h.
Constructor & Destructor Documentation
Node() [1/2]
Acl::Node::Node ()
Definition at line 177 of file Acl.cc.
References debugs.
Node() [2/2]
Acl::Node::Node (Node &&) delete
~Node()
Acl::Node::~Node () virtual
Definition at line 464 of file Acl.cc.
References debugs, and safe_free.
Member Function Documentation
cacheMatchAcl()
int Acl::Node::cacheMatchAcl (dlink_list * cache, ACLChecklist * checklist)
Definition at line 401 of file Acl.cc.
References acl_proxy_auth_match_cache::acl_data, dlink_node::data, debugs, dlinkAddTail(), dlink_list::head, acl_proxy_auth_match_cache::link, acl_proxy_auth_match_cache::matchrv, and dlink_node::next.
Referenced by ACLProxyAuth::matchProxyAuth().
context()
void Acl::Node::context (const SBuf & aName, const char * configuration)
Definition at line 220 of file Acl.cc.
References safe_free, and xstrdup.
Referenced by aclParseAccessLine(), aclParseAclList(), Acl::AllOf::parse(), and ParseAclWithAction().
dump()
virtual SBufList Acl::Node::dump () const pure virtual
Implemented in Acl::AllOf, ACLARP, Acl::NotNode, Acl::ConnectionsEncrypted, Acl::ConnMark, ACLEui64, ACLExtUser, ACLHTTPStatus, Acl::InnerNode, ACLIP, ACLMaxConnection, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, Acl::ParameterizedNode< ACLTimeData >, ACLRandom, Acl::TransactionInitiator, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
dumpWhole()
void Acl::Node::dumpWhole (const char * directiveName, std::ostream & os)
Prints aggregated "acl" (or similar) directive configuration, including the given directive name, ACL name, ACL type, and ACL parameters. The printed parameters are collected from all same-name "acl" directives.
Definition at line 371 of file Acl.cc.
References asList().
empty()
virtual bool Acl::Node::empty () const pure virtual
Implemented in ACLARP, Acl::ConnectionsEncrypted, Acl::ConnMark, ACLEui64, ACLExtUser, ACLHTTPStatus, Acl::InnerNode, ACLIP, ACLMaxConnection, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, Acl::ParameterizedNode< ACLTimeData >, ACLRandom, Acl::TransactionInitiator, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
FindByName()
Acl::Node * Acl::Node::FindByName (const SBuf & name) static
Definition at line 159 of file Acl.cc.
References assert, Config, debugs, and SquidConfig::namedAcls.
Referenced by aclIsProxyAuth(), Acl::InnerNode::lineParse(), parse_ftp_epsv(), and TestACLMaxUserIP::testParseLine().
Initialize()
void Acl::Node::Initialize () static
Definition at line 471 of file Acl.cc.
References Config, debugs, and SquidConfig::namedAcls.
Referenced by serverConnectionsOpen().
isProxyAuth()
bool Acl::Node::isProxyAuth () const virtual
Reimplemented in ACLProxyAuth, and ACLExternal.
Definition at line 354 of file Acl.cc.
lineOptions()
virtual const Acl::Options & Acl::Node::lineOptions () inline private virtual
Returns
(linked) "line" Options supported by this Acl::Node
See also
Acl::Node::options()
Reimplemented in ACLExtUser, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, Acl::ParameterizedNode< ACLTimeData >, and ACLProxyAuth.
Definition at line 102 of file Node.h.
References Acl::NoOptions().
match()
virtual int Acl::Node::match (ACLChecklist * checklist) private pure virtual
Implemented in Acl::AdaptationServiceCheck, Acl::AnnotateClientCheck, Acl::AnnotateTransactionCheck, Acl::AtStepCheck, Acl::ClientCertificateCheck, Acl::DestinationDomainCheck, Acl::HasComponentCheck, Acl::HierCodeCheck, Acl::HttpRepHeaderCheck, Acl::HttpReqHeaderCheck, Acl::LocalPortCheck, Acl::MethodCheck, Acl::MyPortNameCheck, Acl::NoteCheck, Acl::PeerNameCheck, Acl::ProtocolCheck, Acl::ReplyHeaderCheck< header >, Acl::RequestHeaderCheck< header >, Acl::ServerCertificateCheck, Acl::ServerNameCheck, Acl::SourceDomainCheck, Acl::SquidErrorCheck, Acl::CertificateErrorCheck, Acl::TagCheck, Acl::CurrentTimeCheck, Acl::UrlCheck, Acl::UrlLoginCheck, Acl::UrlPathCheck, Acl::UrlPortCheck, Acl::SnmpCommunityCheck, ACLARP, Acl::ConnectionsEncrypted, Acl::ConnMark, ACLDestinationIP, ACLEui64, ACLExtUser, ACLHTTPStatus, Acl::InnerNode, ACLLocalIP, ACLMaxConnection, ACLRandom, ACLSourceIP, Acl::TransactionInitiator, ACLProxyAuth, ACLExternal, ACLIP, ACLMaxUserIP, Acl::ReplyHeaderCheck< header >, and Acl::RequestHeaderCheck< header >.
matches()
bool Acl::Node::matches (ACLChecklist * checklist) const
Orchestrates matching checklist against the Acl::Node using match(), after checking preconditions and while providing debugging.
Returns
true if and only if there was a successful match. Updates the checklist state on match, async, and failure.
Definition at line 189 of file Acl.cc.
References ACLChecklist::asyncInProgress(), DBG_IMPORTANT, debugs, ACLChecklist::hasAle(), ACLChecklist::hasReply(), ACLChecklist::hasRequest(), ACLChecklist::setLastCheckedName(), and ACLChecklist::verifyAle().
Referenced by ACLChecklist::matchAndFinish().
matchForCache()
int Acl::Node::matchForCache (ACLChecklist * checklist) virtual
Reimplemented in ACLProxyAuth.
Definition at line 383 of file Acl.cc.
References fatal().
operator delete()
void Acl::Node::operator delete (void *)
Definition at line 153 of file Acl.cc.
References fatal().
operator new()
void * Acl::Node::operator new (size_t)
Definition at line 147 of file Acl.cc.
References fatal().
options()
virtual const Acl::Options & Acl::Node::options () inline private virtual
Returns
(linked) 'global' Options supported by this Acl::Node
Reimplemented in Acl::DestinationDomainCheck, ACLDestinationIP, Acl::AnnotationCheck, Acl::ServerNameCheck, and ACLMaxUserIP.
Definition at line 98 of file Node.h.
References Acl::NoOptions().
parse()
virtual void Acl::Node::parse () pure virtual
Implemented in Acl::AllOf, Acl::AnyOf, ACLARP, Acl::NotNode, Acl::AndNode, Acl::OrNode, Acl::ConnectionsEncrypted, Acl::ConnMark, ACLEui64, ACLExtUser, ACLHTTPStatus, ACLIP, ACLMaxConnection, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, Acl::ParameterizedNode< ACLTimeData >, ACLRandom, Acl::TransactionInitiator, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
parseFlags()
void Acl::Node::parseFlags ()
Definition at line 360 of file Acl.cc.
References Acl::ParseFlags().
ParseNamed()
void Acl::Node::ParseNamed (ConfigParser & parser, NamedAcls & namedAcls, const SBuf & name) static private
Definition at line 253 of file Acl.cc.
References Assure, SBuf::cmp(), config_input_line, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::destruct(), fatalf(), HttpPortList, Acl::Make(), and ConfigParser::NextToken().
ParseNamedAcl()
void Acl::Node::ParseNamedAcl (ConfigParser & parser, NamedAcls *& namedAcls) static
Definition at line 229 of file Acl.cc.
References CallParser(), DBG_CRITICAL, debugs, ConfigParser::destruct(), RefCount< C >::Make(), and ConfigParser::NextToken().
Referenced by parse_acl(), and TestACLMaxUserIP::testParseLine().
prepareForUse()
virtual void Acl::Node::prepareForUse () inline virtual
Reimplemented in Acl::InnerNode, ACLMaxConnection, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, and Acl::ParameterizedNode< ACLTimeData >.
Definition at line 69 of file Node.h.
requiresAle()
bool Acl::Node::requiresAle () const private virtual
Reimplemented in ACLExternal.
Definition at line 443 of file Acl.cc.
requiresReply()
bool Acl::Node::requiresReply () const private virtual
Reimplemented in Acl::HttpRepHeaderCheck, ACLHTTPStatus, and Acl::ReplyHeaderCheck< header >.
Definition at line 449 of file Acl.cc.
requiresRequest()
bool Acl::Node::requiresRequest () const private virtual
Reimplemented in Acl::DestinationDomainCheck, ACLExtUser, Acl::HierCodeCheck, Acl::HttpReqHeaderCheck, Acl::MethodCheck, Acl::NoteCheck, Acl::ProtocolCheck, Acl::RequestHeaderCheck< header >, Acl::ServerNameCheck, Acl::TransactionInitiator, Acl::UrlCheck, Acl::UrlLoginCheck, Acl::UrlPathCheck, Acl::UrlPortCheck, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
Definition at line 455 of file Acl.cc.
typeString()
virtual char const * Acl::Node::typeString () const pure virtual
Implemented in Acl::AllOf, Acl::AnyOf, ACLARP, Acl::NotNode, Acl::AndNode, Acl::OrNode, Acl::ConnectionsEncrypted, Acl::ConnMark, ACLDestinationIP, ACLEui64, ACLExtUser, ACLHTTPStatus, ACLLocalIP, ACLMaxConnection, ACLRandom, ACLSourceIP, Acl::TransactionInitiator, ACLMaxUserIP, ACLProxyAuth, ACLExternal, and ACLIP.
valid()
bool Acl::Node::valid () const virtual
Reimplemented in ACLMaxConnection, ACLRandom, Acl::ServerNameCheck, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
Definition at line 183 of file Acl.cc.
Member Data Documentation
cfgline
char* Acl::Node::cfgline = nullptr
Definition at line 83 of file Node.h.
name
SBuf Acl::Node::name
Either aclname parameter from the explicitly configured acl directive or a label generated for an internal ACL tree node. All Node objects corresponding to one Squid configuration have unique names. See also: context() and FindByName().
Definition at line 81 of file Node.h.
Referenced by Acl::NotNode::NotNode(), aclDestroyAccessList(), Acl::AnnotateClientCheck::match(), Acl::AnnotateTransactionCheck::match(), Acl::SourceDomainCheck::match(), ACLDestinationIP::match(), ACLRandom::match(), ACLExternal::parse(), and ACLMaxConnection::prepareForUse().
The documentation for this class was generated from the following files:
squid/src/acl/Node.h
squid/src/acl/Acl.cc