Squid Web Cache: ACLDomainData Class Reference
ACLDomainData Class Reference
#include <DomainData.h>
Public Member Functions
ACLDomainData ()=default
~ACLDomainData () override
bool match (char const *) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Public Attributes
Splay< char * > domains
Private Member Functions
MEMPROXY_CLASS (ACLDomainData)
Detailed Description
Definition at line 16 of file DomainData.h.
Constructor & Destructor Documentation
ACLDomainData()
ACLDomainData::ACLDomainData () default
~ACLDomainData()
ACLDomainData::~ACLDomainData () override
Definition at line 28 of file DomainData.cc.
References Splay< V >::destroy(), domains, and xRefFree().
Member Function Documentation
dump()
SBufList ACLDomainData::dump () const override virtual
Implements ACLData< char const * >.
Definition at line 84 of file DomainData.cc.
References AclDomainDataDumpVisitor::contents, domains, and Splay< V >::visit().
empty()
bool ACLDomainData::empty () const override virtual
Implements ACLData< char const * >.
Definition at line 165 of file DomainData.cc.
References domains, and Splay< V >::empty().
lineOptions()
virtual const Acl::Options & ACLData< char const * >::lineOptions () inline virtual inherited
Reimplemented in ACLRegexData, and ACLUserData.
Definition at line 26 of file Data.h.
match()
bool ACLDomainData::match (char const * host) override virtual
Implements ACLData< char const * >.
Reimplemented in ACLServerNameData.
Definition at line 61 of file DomainData.cc.
References aclHostDomainCompare(), debugs, domains, and Splay< V >::find().
MEMPROXY_CLASS()
ACLDomainData::MEMPROXY_CLASS (ACLDomainData) private
parse()
void ACLDomainData::parse () override virtual
Implements ACLData< char const * >.
Definition at line 156 of file DomainData.cc.
References domains, Acl::SplayInserter< DataValue >::Merge(), ConfigParser::strtokFile(), Tolower(), and xstrdup.
prepareForUse()
virtual void ACLData< char const * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
domains
Splay<char *> ACLDomainData::domains
Definition at line 28 of file DomainData.h.
Referenced by ~ACLDomainData(), dump(), empty(), match(), ACLServerNameData::match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/DomainData.h
squid/src/acl/DomainData.cc