Squid Web Cache: acl_ip_data Class Reference
acl_ip_data Class Reference
#include <Ip.h>
Public Member Functions
acl_ip_data ()
acl_ip_data (Ip::Address const &, Ip::Address const &, Ip::Address const &, acl_ip_data *)
void toStr (char *buf, int len) const
SBuf toSBuf () const
Ip::Address firstAddress () const
minimum (masked) address that matches this configured ACL value
Ip::Address lastAddress () const
maximum (masked) address that matches this configured ACL value
Static Public Member Functions
static acl_ip_data * FactoryParse (char const *)
Public Attributes
Ip::Address addr1
Ip::Address addr2
Ip::Address mask
acl_ip_data * next
Private Member Functions
MEMPROXY_CLASS (acl_ip_data)
bool containsVetted (const Ip::Address &needle) const
whether we have parsed and vetted an item with an addr1 field that matches the needle
Static Private Member Functions
static bool DecodeMask (const char *asc, Ip::Address &mask, int string_format_type)
Detailed Description
Definition at line 17 of file Ip.h.
Constructor & Destructor Documentation
acl_ip_data() [1/2]
acl_ip_data::acl_ip_data ()
Definition at line 567 of file Ip.cc.
Referenced by FactoryParse().
acl_ip_data() [2/2]
acl_ip_data::acl_ip_data (Ip::Address const & anAddress1, Ip::Address const & anAddress2, Ip::Address const & aMask, acl_ip_data * aNext)
Definition at line 569 of file Ip.cc.
Member Function Documentation
containsVetted()
bool acl_ip_data::containsVetted (const Ip::Address & needle) const private
Definition at line 219 of file Ip.cc.
Referenced by FactoryParse().
DecodeMask()
bool acl_ip_data::DecodeMask (const char * asc, Ip::Address & mask, int ctype) static private
Decode an ascii representation (asc) of a IP netmask address or CIDR, and place resulting information in mask. This function should NOT be called if 'asc' is a hostname!
Definition at line 176 of file Ip.cc.
References Ip::Address::applyMask(), Ip::Address::cidr(), DBG_CRITICAL, debugs, Ip::Address::isIPv4(), mask, and Ip::Address::setNoAddr().
Referenced by FactoryParse().
FactoryParse()
acl_ip_data * acl_ip_data::FactoryParse (char const * t) static
Definition at line 244 of file Ip.cc.
References acl_ip_data(), addr1, addr2, Ip::Address::applyMask(), Ip::Address::cidr(), containsVetted(), DBG_CRITICAL, DBG_IMPORTANT, debugs, DecodeMask(), LOCAL_ARRAY, mask, next, SCAN_ACL1_4, SCAN_ACL1_6, SCAN_ACL2_4, SCAN_ACL2_6, SCAN_ACL3_4, SCAN_ACL3_6, SCAN_ACL4_4, SCAN_ACL4_6, self_destruct(), Ip::Address::setAnyAddr(), and Ip::Address::setNoAddr().
Referenced by ACLIP::parse().
firstAddress()
Ip::Address acl_ip_data::firstAddress () const
Definition at line 84 of file Ip.cc.
References addr1, Ip::Address::applyMask(), Ip::Address::isNoAddr(), and mask.
lastAddress()
Ip::Address acl_ip_data::lastAddress () const
Definition at line 93 of file Ip.cc.
References addr1, addr2, Ip::Address::isAnyAddr(), Ip::Address::isNoAddr(), mask, and Ip::Address::turnMaskedBitsOn().
MEMPROXY_CLASS()
acl_ip_data::MEMPROXY_CLASS (acl_ip_data) private
toSBuf()
SBuf acl_ip_data::toSBuf () const
Definition at line 75 of file Ip.cc.
References MAX_IPSTRLEN, and toStr().
Referenced by IpAclDumpVisitor::operator()(), and operator<<().
toStr()
void acl_ip_data::toStr (char * buf, int len) const
print/format an acl_ip_data structure for debugging output.
Parameters
buf string buffer to write to
len size of the buffer available
Definition at line 44 of file Ip.cc.
References addr1, addr2, Ip::Address::cidr(), Ip::Address::isAnyAddr(), Ip::Address::isIPv4(), Ip::Address::isNoAddr(), mask, and Ip::Address::toStr().
Referenced by toSBuf().
Member Data Documentation
addr1
Ip::Address acl_ip_data::addr1
Definition at line 36 of file Ip.h.
Referenced by aclIpAddrNetworkCompare(), FactoryParse(), firstAddress(), lastAddress(), ACLIP::match(), and toStr().
addr2
Ip::Address acl_ip_data::addr2
Definition at line 38 of file Ip.h.
Referenced by aclIpAddrNetworkCompare(), FactoryParse(), lastAddress(), ACLIP::match(), and toStr().
mask
Ip::Address acl_ip_data::mask
Definition at line 40 of file Ip.h.
Referenced by aclIpAddrNetworkCompare(), DecodeMask(), FactoryParse(), firstAddress(), lastAddress(), ACLIP::match(), and toStr().
next
acl_ip_data* acl_ip_data::next
used for parsing, not for storing
Definition at line 42 of file Ip.h.
Referenced by FactoryParse(), and ACLIP::parse().
The documentation for this class was generated from the following files:
squid/src/acl/Ip.h
squid/src/acl/Ip.cc