Squid Web Cache: Ipc::Coordinator Class Reference
Ipc::Coordinator Class Reference abstract
Coordinates shared activities of Strands (Squid processes or threads)
#include <Coordinator.h>
Public Types
typedef CbcPointer< AsyncJob > Pointer
Public Member Functions
Coordinator ()
void broadcastSignal (int sig) const
send sig to registered strands
const StrandCoords & strands () const
currently registered strands
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static Coordinator * Instance ()
static String MakeAddr (const char *proccessLabel, int id)
calculates IPC message address for strand id of processLabel type
static String CoordinatorAddr ()
get the IPC message address for coordinator process
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
struct sockaddr_un address
UDS address from path; treat as read-only.
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void start () override
called by AsyncStart; do not call directly
void receive (const TypedMsgHdr &message) override
StrandCoord * findStrand (int kidId)
registered strand or NULL
void registerStrand (const StrandCoord &)
adds or updates existing
void handleRegistrationRequest (const StrandMessage &)
register,ACK
void notifySearcher (const StrandSearchRequest &request, const StrandCoord &)
answer the waiting search request
void handleSearchRequest (const StrandSearchRequest &request)
answers or queues the request if the answer is not yet known
void handleSharedListenRequest (const SharedListenRequest &request)
returns cached socket or calls openListenSocket()
void handleCacheMgrRequest (const Mgr::Request &request)
void handleCacheMgrResponse (const Mgr::Response &response)
void handleSnmpRequest (const Snmp::Request &request)
void handleSnmpResponse (const Snmp::Response &response)
Comm::ConnectionPointer openListenSocket (const SharedListenRequest &request, int &errNo)
calls comm_open_listener()
bool doneAll () const override
whether positive goal has been reached
void doListen ()
read the next incoming message
virtual void timedout ()
called after setTimeout() if timed out
Comm::ConnectionPointer & conn ()
creates if needed and returns raw UDS socket descriptor
void setTimeout (time_t seconds, const char *handlerName)
call timedout() if no UDS messages in a given number of seconds
void clearTimeout ()
remove previously set timeout, if any
void setOptions (int newOptions)
changes socket options
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual void swanSong ()
virtual const char * status () const
internal cleanup; do not call directly
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Types
typedef std::list< StrandSearchRequest > Searchers
search requests
typedef std::map< OpenListenerParams, Comm::ConnectionPointer > Listeners
params:connection map
Private Member Functions
CBDATA_CHILD (Coordinator)
Coordinator (const Coordinator &)
Coordinator & operator= (const Coordinator &)
void noteRead (const CommIoCbParams &params)
void receiveOrIgnore (const TypedMsgHdr &)
receive() but ignore any errors
void noteTimeout (const CommTimeoutCbParams &p)
Comm timeout callback; calls timedout()
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
StrandCoords strands_
registered processes and threads
Searchers searchers
yet unanswered search requests in arrival order
Listeners listeners
cached comm_open_listener() results
TypedMsgHdr buf
msghdr struct filled by Comm
int options
UDS options.
Comm::ConnectionPointer conn_
UDS descriptor.
Static Private Attributes
static Coordinator * TheInstance = nullptr
the only class instance in existence
Detailed Description
Definition at line 30 of file Coordinator.h.
Member Typedef Documentation
Listeners
typedef std::map<OpenListenerParams, Comm::ConnectionPointer> Ipc::Coordinator::Listeners private
Definition at line 74 of file Coordinator.h.
Pointer
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Searchers
typedef std::list<StrandSearchRequest> Ipc::Coordinator::Searchers private
Definition at line 71 of file Coordinator.h.
Constructor & Destructor Documentation
Coordinator() [1/2]
Ipc::Coordinator::Coordinator ()
Definition at line 39 of file Coordinator.cc.
Coordinator() [2/2]
Ipc::Coordinator::Coordinator (const Coordinator &) private
Member Function Documentation
broadcastSignal()
void Ipc::Coordinator::broadcastSignal (int sig) const
Definition at line 286 of file Coordinator.cc.
References debugs.
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
CBDATA_CHILD()
Ipc::Coordinator::CBDATA_CHILD (Coordinator) private
clearTimeout()
void Ipc::UdsOp::clearTimeout () protected inherited
Definition at line 63 of file UdsOp.cc.
References commUnsetConnTimeout().
conn()
Comm::ConnectionPointer & Ipc::UdsOp::conn () protected inherited
Definition at line 42 of file UdsOp.cc.
References COMM_DOBIND, comm_open_uds(), Comm::Connection::fd, Comm::IsConnOpen(), and Must.
CoordinatorAddr()
String Ipc::Port::CoordinatorAddr () static inherited
Definition at line 65 of file Port.cc.
References String::append(), channelPathPfx, coordinatorAddrLabel, Instance::NamePrefix(), and String::size().
Referenced by Ipc::StrandMessage::NotifyCoordinator(), IpcIoFile::open(), Mgr::Action::sendResponse(), Snmp::SendResponse(), SendSharedListenRequest(), and Ipc::Forwarder::start().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
doListen()
void Ipc::Port::doListen () protected inherited
Definition at line 38 of file Port.cc.
References comm_read(), debugs, JobCallback, MYNAME, and Ipc::Port::noteRead().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Ipc::Port::doneAll () const override protected virtual inherited
Reimplemented from AsyncJob.
Definition at line 48 of file Port.cc.
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
findStrand()
Ipc::StrandCoord * Ipc::Coordinator::findStrand (int kidId) protected
Definition at line 49 of file Coordinator.cc.
handleCacheMgrRequest()
void Ipc::Coordinator::handleCacheMgrRequest (const Mgr::Request & request) protected
Definition at line 172 of file Coordinator.cc.
References Mgr::ActionParams::actionName, Mgr::Request::conn, CacheManager::createRequestedAction(), DBG_IMPORTANT, debugs, Comm::Connection::fd, CacheManager::GetInstance(), MYNAME, Mgr::Response::pack(), Mgr::Request::params, Ipc::Request::requestId, Ipc::Request::requestorId, Ipc::SendMessage(), AsyncJob::Start(), Ipc::strandAddrLabel, and xclose().
handleCacheMgrResponse()
void Ipc::Coordinator::handleCacheMgrResponse (const Mgr::Response & response) protected
Definition at line 198 of file Coordinator.cc.
References Ipc::Inquirer::HandleRemoteAck().
handleRegistrationRequest()
void Ipc::Coordinator::handleRegistrationRequest (const StrandMessage & msg) protected
Definition at line 141 of file Coordinator.cc.
References Ipc::StrandCoord::kidId, Ipc::mtStrandRegistered, Ipc::StrandMessage::pack(), Ipc::SendMessage(), Ipc::StrandMessage::strand, and Ipc::strandAddrLabel.
handleSearchRequest()
void Ipc::Coordinator::handleSearchRequest (const StrandSearchRequest & request) protected
Definition at line 204 of file Coordinator.cc.
References debugs, Ipc::StrandSearchRequest::requestorId, and Ipc::StrandSearchRequest::tag.
handleSharedListenRequest()
void Ipc::Coordinator::handleSharedListenRequest (const SharedListenRequest & request) protected
Definition at line 152 of file Coordinator.cc.
References Ipc::OpenListenerParams::addr, debugs, Comm::Connection::fd, Ipc::SharedListenRequest::mapId, Ipc::SharedListenResponse::pack(), Ipc::SharedListenRequest::params, Ipc::SharedListenRequest::requestorId, Ipc::SendMessage(), and Ipc::strandAddrLabel.
handleSnmpRequest()
void Ipc::Coordinator::handleSnmpRequest (const Snmp::Request & request) protected
Definition at line 238 of file Coordinator.cc.
References debugs, MYNAME, Snmp::Response::pack(), Ipc::Request::requestId, Ipc::Request::requestorId, Ipc::SendMessage(), AsyncJob::Start(), and Ipc::strandAddrLabel.
handleSnmpResponse()
void Ipc::Coordinator::handleSnmpResponse (const Snmp::Response & response) protected
Definition at line 251 of file Coordinator.cc.
References debugs, Ipc::Inquirer::HandleRemoteAck(), and MYNAME.
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
Instance()
Ipc::Coordinator * Ipc::Coordinator::Instance () static
Definition at line 296 of file Coordinator.cc.
Referenced by SquidMain().
MakeAddr()
String Ipc::Port::MakeAddr (const char * proccessLabel, int id) static inherited
Definition at line 53 of file Port.cc.
References String::append(), assert, channelPathPfx, Instance::NamePrefix(), and xitoa().
Referenced by Ipc::Inquirer::inquire(), IpcIoFile::Notify(), and CollapsedForwarding::Notify().
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteRead()
void Ipc::Port::noteRead (const CommIoCbParams & params) private inherited
Definition at line 94 of file Port.cc.
References assert, CommIoCbParams::buf, CommCommonCbParams::conn, debugs, CommCommonCbParams::flag, and Comm::OK.
Referenced by Ipc::Port::doListen().
noteTimeout()
void Ipc::UdsOp::noteTimeout (const CommTimeoutCbParams & p) private inherited
Definition at line 68 of file UdsOp.cc.
Referenced by Ipc::UdsOp::setTimeout().
notifySearcher()
void Ipc::Coordinator::notifySearcher (const StrandSearchRequest & request, const StrandCoord & strand) protected
Definition at line 225 of file Coordinator.cc.
References debugs, Ipc::StrandCoord::kidId, Ipc::mtStrandReady, Ipc::StrandMessage::pack(), Ipc::StrandSearchRequest::qid, Ipc::StrandSearchRequest::requestorId, Ipc::SendMessage(), Ipc::strandAddrLabel, and Ipc::StrandSearchRequest::tag.
openListenSocket()
Comm::ConnectionPointer Ipc::Coordinator::openListenSocket (const SharedListenRequest & request, int & errNo) protected
Definition at line 259 of file Coordinator.cc.
References Ipc::OpenListenerParams::addr, comm_open_listener(), debugs, enter_suid(), Ipc::FdNote(), Ipc::OpenListenerParams::fdNote, Comm::Connection::flags, Ipc::OpenListenerParams::flags, Comm::IsConnOpen(), leave_suid(), Comm::Connection::local, Ipc::SharedListenRequest::params, Ipc::OpenListenerParams::proto, Ipc::SharedListenRequest::requestorId, and Ipc::OpenListenerParams::sock_type.
operator=()
Coordinator & Ipc::Coordinator::operator= (const Coordinator &) private
receive()
void Ipc::Coordinator::receive (const TypedMsgHdr & message) override protected virtual
handle IPC message just read kids must call parent method when they do not recognize the message type
Implements Ipc::Port.
Definition at line 84 of file Coordinator.cc.
References debugs, Ipc::Mine(), Ipc::mtCacheMgrRequest, Ipc::mtCacheMgrResponse, Ipc::mtFindStrand, Ipc::mtRegisterStrand, Ipc::mtSharedListenRequest, Ipc::mtSnmpRequest, Ipc::mtSnmpResponse, Ipc::TypedMsgHdr::rawType(), Ipc::Port::receive(), Ipc::StrandSearchRequest::requestorId, and Ipc::StrandSearchRequest::tag.
receiveOrIgnore()
void Ipc::Port::receiveOrIgnore (const TypedMsgHdr & message) private inherited
Definition at line 83 of file Port.cc.
References CurrentException(), DBG_IMPORTANT, debugs, Debug::Extra(), and Ipc::TypedMsgHdr::rawType().
registerStrand()
void Ipc::Coordinator::registerStrand (const StrandCoord & strand) protected
Definition at line 59 of file Coordinator.cc.
References debugs, Ipc::StrandCoord::kidId, String::size(), and Ipc::StrandCoord::tag.
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
setOptions()
void Ipc::UdsOp::setOptions (int newOptions) protected inherited
Definition at line 36 of file UdsOp.cc.
Referenced by Ipc::Port::Port().
setTimeout()
void Ipc::UdsOp::setTimeout (time_t seconds, const char * handlerName) protected inherited
Definition at line 55 of file UdsOp.cc.
References asyncCall(), commSetConnTimeout(), and Ipc::UdsOp::noteTimeout().
start()
void Ipc::Coordinator::start () override protected virtual
Implements Ipc::Port.
Definition at line 44 of file Coordinator.cc.
References Ipc::Port::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), handleCacheMgrRequest(), handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
status()
const char * AsyncJob::status () const protected virtual inherited
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), AsyncJob::stopReason, and MemBuf::terminate().
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
strands()
const Ipc::StrandCoords & Ipc::Coordinator::strands () const
Definition at line 307 of file Coordinator.cc.
swanSong()
virtual void AsyncJob::swanSong () inline protected virtual inherited
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::ModXactLauncher, Adaptation::Icap::OptXact, Adaptation::Icap::Xaction, Adaptation::Initiate, Adaptation::Iterator, ConnStateData, Client, Ftp::Relay, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, Ipc::Forwarder, Ipc::Inquirer, Ipc::UdsSender, Log::TcpLogger, Mgr::Filler, Mgr::Forwarder, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Server, and Snmp::Forwarder.
Definition at line 61 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), Client::swanSong(), Ftp::Relay::swanSong(), Http::Tunneler::swanSong(), Comm::ConnOpener::swanSong(), Comm::TcpAcceptor::swanSong(), Rock::HeaderUpdater::swanSong(), HappyConnOpener::swanSong(), Ipc::UdsSender::swanSong(), Log::TcpLogger::swanSong(), PeerPoolMgr::swanSong(), Security::PeerConnector::swanSong(), and Server::swanSong().
timedout()
virtual void Ipc::UdsOp::timedout () inline protected virtual inherited
Reimplemented in Ipc::Strand, and Ipc::UdsSender.
Definition at line 40 of file UdsOp.h.
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
Member Data Documentation
address
struct sockaddr_un Ipc::UdsOp::address inherited
Definition at line 37 of file UdsOp.h.
Referenced by Ipc::UdsSender::UdsSender().
buf
TypedMsgHdr Ipc::Port::buf private inherited
Definition at line 47 of file Port.h.
conn_
Comm::ConnectionPointer Ipc::UdsOp::conn_ private inherited
Definition at line 56 of file UdsOp.h.
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
listeners
Listeners Ipc::Coordinator::listeners private
Definition at line 75 of file Coordinator.h.
options
int Ipc::UdsOp::options private inherited
Definition at line 55 of file UdsOp.h.
searchers
Searchers Ipc::Coordinator::searchers private
Definition at line 72 of file Coordinator.h.
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
strands_
StrandCoords Ipc::Coordinator::strands_ private
Definition at line 69 of file Coordinator.h.
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
TheInstance
Ipc::Coordinator * Ipc::Coordinator::TheInstance = nullptr static private
Definition at line 77 of file Coordinator.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
The documentation for this class was generated from the following files:
squid/src/ipc/Coordinator.h
squid/src/ipc/Coordinator.cc