Squid Web Cache: Security::TLSPlaintext Class Reference
Security::TLSPlaintext Class Reference
TLS Record Layer's frame from RFC 5246 Section 6.2.1.
Public Member Functions
TLSPlaintext (Parser::BinaryTokenizer &tk)
Public Attributes
uint8_t type
see ContentType
AnyP::ProtocolVersion version
Record Layer, not necessarily the negotiated TLS version;.
SBuf fragment
possibly partial content
Detailed Description
Definition at line 38 of file Handshake.cc.
Constructor & Destructor Documentation
TLSPlaintext()
Security::TLSPlaintext::TLSPlaintext (Parser::BinaryTokenizer & tk) explicit
Definition at line 155 of file Handshake.cc.
References Security::ctApplicationData, Security::ctChangeCipherSpec, fragment, Must, Security::ParseProtocolVersion(), Parser::BinaryTokenizer::pstring16(), Parser::BinaryTokenizerContext::success(), type, Parser::BinaryTokenizer::uint8(), and version.
Member Data Documentation
fragment
SBuf Security::TLSPlaintext::fragment
Definition at line 45 of file Handshake.cc.
Referenced by TLSPlaintext(), and Security::HandshakeParser::parseModernRecord().
type
uint8_t Security::TLSPlaintext::type
Definition at line 43 of file Handshake.cc.
Referenced by TLSPlaintext(), and Security::HandshakeParser::parseModernRecord().
version
AnyP::ProtocolVersion Security::TLSPlaintext::version
Definition at line 44 of file Handshake.cc.
Referenced by TLSPlaintext(), and Security::HandshakeParser::parseModernRecord().
The documentation for this class was generated from the following file:
squid/src/security/Handshake.cc