Squid Web Cache: DiskDaemonDiskIOModule Class Reference
DiskDaemonDiskIOModule Class Reference
#include <DiskDaemonDiskIOModule.h>
Public Types
typedef std::vector< DiskIOModule * >::iterator iterator
typedef std::vector< DiskIOModule * >::const_iterator const_iterator
Public Member Functions
DiskDaemonDiskIOModule ()
void init () override
void gracefulShutdown () override
char const * type () const override
DiskIOStrategy * createStrategy () override
Static Public Member Functions
static DiskDaemonDiskIOModule & GetInstance ()
static void SetupAllModules ()
static void ModuleAdd (DiskIOModule &)
static void FreeAllModules ()
static DiskIOModule * Find (char const *type)
static DiskIOModule * FindDefault ()
static std::vector< DiskIOModule * > const & Modules ()
Static Protected Member Functions
static void RegisterAllModulesWithCacheManager (void)
Private Member Functions
void registerWithCacheManager (void)
Static Private Member Functions
static std::vector< DiskIOModule * > & GetModules ()
Private Attributes
bool initialised
Static Private Attributes
static DiskDaemonDiskIOModule Instance
static std::vector< DiskIOModule * > * _Modules = nullptr
Detailed Description
Definition at line 14 of file DiskDaemonDiskIOModule.h.
Member Typedef Documentation
const_iterator
typedef std::vector<DiskIOModule*>::const_iterator DiskIOModule::const_iterator inherited
Definition at line 37 of file DiskIOModule.h.
iterator
typedef std::vector<DiskIOModule*>::iterator DiskIOModule::iterator inherited
Definition at line 36 of file DiskIOModule.h.
Constructor & Destructor Documentation
DiskDaemonDiskIOModule()
DiskDaemonDiskIOModule::DiskDaemonDiskIOModule ()
Definition at line 16 of file DiskDaemonDiskIOModule.cc.
References DiskIOModule::ModuleAdd().
Member Function Documentation
createStrategy()
DiskIOStrategy * DiskDaemonDiskIOModule::createStrategy () override virtual
Implements DiskIOModule.
Definition at line 57 of file DiskDaemonDiskIOModule.cc.
Find()
DiskIOModule * DiskIOModule::Find (char const * type) static inherited
Definition at line 114 of file DiskIOModule.cc.
References DiskIOModule::GetModules(), and DiskIOModule::type().
Referenced by Fs::Ufs::UFSSwapDir::UFSSwapDir(), DiskIOModule::FindDefault(), Rock::SwapDir::init(), Rock::SwapDir::needsDiskStrand(), and TestUfs::testUfsSearch().
FindDefault()
DiskIOModule * DiskIOModule::FindDefault () static inherited
Find any usable disk module. This will look for the 'best' available module for this system.
Best IO options are in order:
Definition at line 124 of file DiskIOModule.cc.
References DiskIOModule::Find().
FreeAllModules()
void DiskIOModule::FreeAllModules () static inherited
Called when a graceful shutdown is to occur of each fs module.
Definition at line 104 of file DiskIOModule.cc.
References DiskIOModule::GetModules(), and DiskIOModule::gracefulShutdown().
Referenced by SquidShutdown().
GetInstance()
DiskDaemonDiskIOModule & DiskDaemonDiskIOModule::GetInstance () static
Definition at line 22 of file DiskDaemonDiskIOModule.cc.
References Instance.
Referenced by DiskIOModule::SetupAllModules().
GetModules()
std::vector< DiskIOModule * > & DiskIOModule::GetModules () static private inherited
Definition at line 91 of file DiskIOModule.cc.
References DiskIOModule::_Modules.
Referenced by DiskIOModule::Find(), DiskIOModule::FreeAllModules(), DiskIOModule::ModuleAdd(), DiskIOModule::Modules(), and DiskIOModule::SetupAllModules().
gracefulShutdown()
void DiskDaemonDiskIOModule::gracefulShutdown () override virtual
Implements DiskIOModule.
Definition at line 51 of file DiskDaemonDiskIOModule.cc.
References initialised.
init()
void DiskDaemonDiskIOModule::init () override virtual
Implements DiskIOModule.
Definition at line 28 of file DiskDaemonDiskIOModule.cc.
References assert, diskd_stats, initialised, and registerWithCacheManager().
ModuleAdd()
void DiskIOModule::ModuleAdd (DiskIOModule & instance) static inherited
Definition at line 72 of file DiskIOModule.cc.
References assert, DiskIOModule::GetModules(), and DiskIOModule::type().
Referenced by BlockingDiskIOModule::BlockingDiskIOModule(), DiskDaemonDiskIOModule(), DiskThreadsDiskIOModule::DiskThreadsDiskIOModule(), IpcIoDiskIOModule::IpcIoDiskIOModule(), and MmappedDiskIOModule::MmappedDiskIOModule().
Modules()
std::vector< DiskIOModule * > const & DiskIOModule::Modules () static inherited
Definition at line 85 of file DiskIOModule.cc.
References DiskIOModule::GetModules().
RegisterAllModulesWithCacheManager()
static void DiskIOModule::RegisterAllModulesWithCacheManager (void) static protected inherited
registerWithCacheManager()
void DiskDaemonDiskIOModule::registerWithCacheManager (void) private
Definition at line 45 of file DiskDaemonDiskIOModule.cc.
References DiskdAction::Create(), and Mgr::RegisterAction().
Referenced by init().
SetupAllModules()
void DiskIOModule::SetupAllModules () static inherited
Poke all compiled modules for self-setup
Definition at line 45 of file DiskIOModule.cc.
References BlockingDiskIOModule::GetInstance(), GetInstance(), DiskThreadsDiskIOModule::GetInstance(), IpcIoDiskIOModule::GetInstance(), MmappedDiskIOModule::GetInstance(), and DiskIOModule::GetModules().
Referenced by SquidMain().
type()
char const * DiskDaemonDiskIOModule::type () const override virtual
Implements DiskIOModule.
Definition at line 65 of file DiskDaemonDiskIOModule.cc.
Member Data Documentation
_Modules
std::vector< DiskIOModule * > * DiskIOModule::_Modules = nullptr static private inherited
Definition at line 57 of file DiskIOModule.h.
Referenced by DiskIOModule::GetModules().
initialised
bool DiskDaemonDiskIOModule::initialised private
Definition at line 27 of file DiskDaemonDiskIOModule.h.
Referenced by gracefulShutdown(), and init().
Instance
DiskDaemonDiskIOModule DiskDaemonDiskIOModule::Instance static private
Definition at line 26 of file DiskDaemonDiskIOModule.h.
Referenced by GetInstance().
The documentation for this class was generated from the following files:
squid/src/DiskIO/DiskDaemon/DiskDaemonDiskIOModule.h
squid/src/DiskIO/DiskDaemon/DiskDaemonDiskIOModule.cc