Squid Web Cache: BodyPipeCheckout Class Reference
BodyPipeCheckout Class Reference
#include <BodyPipe.h>
Public Member Functions
BodyPipeCheckout (BodyPipe &)
~BodyPipeCheckout ()
void checkIn ()
Public Attributes
BodyPipe & thePipe
MemBuf & buf
const uint64_t offset
Protected Attributes
const size_t checkedOutSize
bool checkedIn
Private Member Functions
BodyPipeCheckout (const BodyPipeCheckout &)
BodyPipeCheckout & operator= (const BodyPipeCheckout &)
Friends
class BodyPipe
Detailed Description
Makes raw buffer checkin/checkout interface efficient and exception-safe. Either append or consume operations can be performed on a checkedout buffer.
Definition at line 61 of file BodyPipe.h.
Constructor & Destructor Documentation
BodyPipeCheckout() [1/2]
BodyPipeCheckout::BodyPipeCheckout (BodyPipe & aPipe)
Definition at line 483 of file BodyPipe.cc.
~BodyPipeCheckout()
BodyPipeCheckout::~BodyPipeCheckout ()
Definition at line 489 of file BodyPipe.cc.
References checkedIn, BodyPipe::checkIn(), debugs, and thePipe.
BodyPipeCheckout() [2/2]
BodyPipeCheckout::BodyPipeCheckout (const BodyPipeCheckout & c) private
Definition at line 508 of file BodyPipe.cc.
References assert.
Member Function Documentation
checkIn()
void BodyPipeCheckout::checkIn ()
Definition at line 501 of file BodyPipe.cc.
References assert, checkedIn, BodyPipe::checkIn(), and thePipe.
Referenced by ConnStateData::handleChunkedRequestBody(), Client::handleMoreAdaptedBodyAvailable(), ClientHttpRequest::noteMoreBodyDataAvailable(), and Adaptation::Icap::ModXact::parseBody().
operator=()
BodyPipeCheckout & BodyPipeCheckout::operator= (const BodyPipeCheckout &) private
Definition at line 516 of file BodyPipe.cc.
References assert.
Friends And Related Symbol Documentation
BodyPipe
friend class BodyPipe friend
Definition at line 64 of file BodyPipe.h.
Member Data Documentation
buf
MemBuf& BodyPipeCheckout::buf
Definition at line 74 of file BodyPipe.h.
Referenced by ConnStateData::handleChunkedRequestBody(), Client::handleMoreAdaptedBodyAvailable(), ClientHttpRequest::noteMoreBodyDataAvailable(), and Adaptation::Icap::ModXact::parseBody().
checkedIn
bool BodyPipeCheckout::checkedIn protected
Definition at line 79 of file BodyPipe.h.
Referenced by ~BodyPipeCheckout(), and checkIn().
checkedOutSize
const size_t BodyPipeCheckout::checkedOutSize protected
Definition at line 78 of file BodyPipe.h.
Referenced by BodyPipe::checkIn(), and BodyPipe::undoCheckOut().
offset
const uint64_t BodyPipeCheckout::offset
Definition at line 75 of file BodyPipe.h.
thePipe
BodyPipe& BodyPipeCheckout::thePipe
Definition at line 73 of file BodyPipe.h.
Referenced by ~BodyPipeCheckout(), and checkIn().
The documentation for this class was generated from the following files:
squid/src/BodyPipe.h
squid/src/BodyPipe.cc