Squid Web Cache: UrnState Class Reference
UrnState Class Reference
Public Member Functions
CBDATA_DECL_ (UrnState, noexcept)
UrnState (const AccessLogEntry::Pointer &anAle)
void start (HttpRequest *, StoreEntry *)
void setUriResFromRequest (HttpRequest *)
~UrnState () override
Public Attributes
StoreEntry * entry = nullptr
store_client * sc = nullptr
StoreEntry * urlres_e = nullptr
HttpRequest::Pointer request
HttpRequest::Pointer urlres_r
AccessLogEntry::Pointer ale
details of the requesting transaction
Store::ParsingBuffer parsingBuffer
for receiving a URN resolver reply body from Store and interpreting it
Protected Member Functions
bool startCollapsingOn (const StoreEntry &, const bool doingRevalidation) const
bool mayInitiateCollapsing () const
whether Squid configuration allows us to become a CF initiator
bool onCollapsingPath () const
whether Squid configuration allows collapsing for this transaction
Protected Attributes
bool didCollapse = false
whether startCollapsingOn() was called and returned true
Private Member Functions
LogTags * loggingTags () const override
void fillChecklist (ACLFilledChecklist &) const override
configure the given checklist (to reflect the current transaction state)
Private Attributes
char * urlres = nullptr
Detailed Description
Definition at line 30 of file urn.cc.
Constructor & Destructor Documentation
UrnState()
UrnState::UrnState (const AccessLogEntry::Pointer & anAle) inline explicit
Definition at line 35 of file urn.cc.
~UrnState()
UrnState::~UrnState () override
Definition at line 76 of file urn.cc.
References entry, safe_free, sc, storeUnregister(), SWALLOW_EXCEPTIONS, StoreEntry::unlock(), urlres, and urlres_e.
Member Function Documentation
CBDATA_DECL_()
UrnState::CBDATA_DECL_ (UrnState , noexcept)
fillChecklist()
void UrnState::fillChecklist (ACLFilledChecklist &) const override private virtual
Implements Acl::ChecklistFiller.
Definition at line 199 of file urn.cc.
References ACLFilledChecklist::al, ale, RefCount< C >::getRaw(), request, and ACLFilledChecklist::setRequest().
loggingTags()
LogTags * UrnState::loggingTags () const inline override private virtual
Returns
LogTags (if the class logs transactions) or nil (otherwise)
Implements StoreClient.
Definition at line 54 of file urn.cc.
References ale, AccessLogEntry::cache, and AccessLogEntry::CacheDetails::code.
mayInitiateCollapsing()
bool StoreClient::mayInitiateCollapsing () const inline protected inherited
Definition at line 59 of file StoreClient.h.
References StoreClient::onCollapsingPath().
Referenced by clientReplyContext::createStoreEntry(), and clientReplyContext::processExpired().
onCollapsingPath()
bool StoreClient::onCollapsingPath () const protected inherited
Definition at line 52 of file store_client.cc.
References SquidConfig::accessList, Acl::Answer::allowed(), SquidConfig::collapsed_forwarding, SquidConfig::collapsedForwardingAccess, Config, ACLChecklist::fastCheck(), Acl::ChecklistFiller::fillChecklist(), and SquidConfig::onoff.
Referenced by StoreClient::mayInitiateCollapsing(), and StoreClient::startCollapsingOn().
setUriResFromRequest()
void UrnState::setUriResFromRequest (HttpRequest * r)
Definition at line 139 of file urn.cc.
References AnyP::Uri::absolute(), Http::ACCEPT, ale, debugs, entry, ERR_URN_RESOLVE, errorAppendEntry(), HttpRequest::FromUrlXXX(), Http::Message::header, AnyP::Uri::host(), LOCAL_ARRAY, HttpRequest::masterXaction, HttpHeader::putStr(), safe_free, Http::scNotFound, SQUIDSBUFPH, SQUIDSBUFPRINT, HttpRequest::url, urlres, urlres_r, and xstrdup.
Referenced by start().
start()
void UrnState::start (HttpRequest * r, StoreEntry * e)
Definition at line 162 of file urn.cc.
References ale, debugs, entry, RefCount< C >::getRaw(), StoreEntry::lock(), Store::ParsingBuffer::makeInitialSpace(), Http::METHOD_GET, parsingBuffer, request, sc, setUriResFromRequest(), FwdState::Start(), StoreClient::startCollapsingOn(), storeClientCopy(), storeClientListAdd(), storeCreateEntry(), storeGetPublic(), StoreEntry::url(), urlres, urlres_e, urlres_r, and urnHandleReply.
startCollapsingOn()
bool StoreClient::startCollapsingOn (const StoreEntry & e, const bool doingRevalidation) const protected inherited
Returns
whether the caller must collapse on the given entry Before returning true, updates common collapsing-related stats. See also: StoreEntry::hittingRequiresCollapsing().
Definition at line 66 of file store_client.cc.
References debugs, StoreClient::didCollapse, StoreEntry::hittingRequiresCollapsing(), StoreClient::loggingTags(), and StoreClient::onCollapsingPath().
Referenced by htcpSpecifier::checkHit(), ICPState::confirmAndPrepHit(), clientReplyContext::identifyFoundObject(), clientReplyContext::processExpired(), and start().
Member Data Documentation
ale
AccessLogEntry::Pointer UrnState::ale
Definition at line 47 of file urn.cc.
Referenced by fillChecklist(), loggingTags(), setUriResFromRequest(), start(), and urnHandleReply().
didCollapse
bool StoreClient::didCollapse = false mutable protected inherited
Definition at line 64 of file StoreClient.h.
Referenced by clientReplyContext::cacheHit(), htcpSpecifier::checkHit(), ICPState::confirmAndPrepHit(), and StoreClient::startCollapsingOn().
entry
StoreEntry* UrnState::entry = nullptr
Definition at line 42 of file urn.cc.
Referenced by ~UrnState(), setUriResFromRequest(), start(), and urnHandleReply().
parsingBuffer
Store::ParsingBuffer UrnState::parsingBuffer
Definition at line 50 of file urn.cc.
Referenced by start(), and urnHandleReply().
request
HttpRequest::Pointer UrnState::request
Definition at line 45 of file urn.cc.
Referenced by fillChecklist(), start(), and urnHandleReply().
sc
store_client* UrnState::sc = nullptr
Definition at line 43 of file urn.cc.
Referenced by ~UrnState(), start(), and urnHandleReply().
urlres
char* UrnState::urlres = nullptr private
Definition at line 57 of file urn.cc.
Referenced by ~UrnState(), setUriResFromRequest(), and start().
urlres_e
StoreEntry* UrnState::urlres_e = nullptr
Definition at line 44 of file urn.cc.
Referenced by ~UrnState(), start(), and urnHandleReply().
urlres_r
HttpRequest::Pointer UrnState::urlres_r
Definition at line 46 of file urn.cc.
Referenced by setUriResFromRequest(), and start().
The documentation for this class was generated from the following file:
squid/src/urn.cc