Squid Web Cache: WhoisState Class Reference
WhoisState Class Reference
Public Member Functions
void readReply (const Comm::ConnectionPointer &, char *aBuffer, size_t aBufferLength, Comm::Flag flag, int xerrno)
void setReplyToOK (StoreEntry *sentry)
Public Attributes
StoreEntry * entry
HttpRequest::Pointer request
FwdState::Pointer fwd
char buf [BUFSIZ+1]
bool dataWritten
Private Member Functions
CBDATA_CLASS (WhoisState)
Detailed Description
Definition at line 27 of file WhoisGateway.cc.
Member Function Documentation
CBDATA_CLASS()
WhoisState::CBDATA_CLASS (WhoisState) private
readReply()
void WhoisState::readReply (const Comm::ConnectionPointer & conn, char * aBuffer, size_t aBufferLength, Comm::Flag flag, int xerrno)
Definition at line 112 of file WhoisGateway.cc.
References FwdState::al, StatCounters::all, StoreEntry::append(), BUFSIZ, Comm::Connection::close(), comm_read(), commCbCall(), FwdState::complete(), dataWritten, debugs, entry, Comm::ERR_CLOSING, ERR_READ_ERROR, ERR_ZERO_SIZE_OBJECT, FwdState::fail(), StoreEntry::flush(), fwd, StatCounters::http, ignoreErrno(), StoreEntry::isAccepting(), StatCounters::kbytes_in, StoreEntry::makePrivate(), StoreEntry::makePublic(), FwdState::markStoredReplyAsWhole(), Comm::OK, FwdState::request, Http::scBadGateway, Http::scInternalServerError, StatCounters::server, setReplyToOK(), statCounter, StoreEntry::timestampsSet(), StoreEntry::url(), whoisReadReply, and xstrerr().
Referenced by whoisReadReply().
setReplyToOK()
void WhoisState::setReplyToOK (StoreEntry * sentry)
Definition at line 102 of file WhoisGateway.cc.
References StoreEntry::buffer(), StoreEntry::replaceHttpReply(), Http::scOkay, HttpReply::setHeaders(), Http::Message::sources, and Http::Message::srcWhois.
Referenced by readReply().
Member Data Documentation
buf
char WhoisState::buf[BUFSIZ+1]
Definition at line 37 of file WhoisGateway.cc.
Referenced by whoisStart().
dataWritten
bool WhoisState::dataWritten
Definition at line 38 of file WhoisGateway.cc.
Referenced by readReply(), and whoisStart().
entry
StoreEntry* WhoisState::entry
Definition at line 34 of file WhoisGateway.cc.
Referenced by readReply(), whoisClose(), whoisStart(), and whoisTimeout().
fwd
FwdState::Pointer WhoisState::fwd
Definition at line 36 of file WhoisGateway.cc.
Referenced by readReply(), and whoisStart().
request
HttpRequest::Pointer WhoisState::request
Definition at line 35 of file WhoisGateway.cc.
Referenced by whoisStart().
The documentation for this class was generated from the following file:
squid/src/clients/WhoisGateway.cc