Squid Web Cache: SBufStream Class Reference
SBufStream Class Reference
#include <Stream.h>
Public Member Functions
SBufStream (const SBuf &aBuf)
SBufStream ()
Create an empty SBufStream.
SBuf buf ()
bytes written so far
SBufStream & clearBuf ()
Clear the stream's backing store.
Private Attributes
SBuf sink_
buffer for (flushed) bytes written to the stream
AppendingStreamBuf< SBuf > streamBuffer_
writes raw (post-formatting) bytes to the sink_
Detailed Description
Stream interface to write to a SBuf.
Data is appended using standard operator << semantics, and extracted using the buf() method, in analogy with std::strstream .
Definition at line 20 of file Stream.h.
Constructor & Destructor Documentation
SBufStream() [1/2]
SBufStream::SBufStream (const SBuf & aBuf) inline
Create a SBufStream preinitialized with the contents of a SBuf
The supplied SBuf copied: in order to retrieve the written-to contents they must be later fetched using the buf() class method.
Definition at line 28 of file Stream.h.
References streamBuffer_.
SBufStream() [2/2]
SBufStream::SBufStream () inline
Definition at line 38 of file Stream.h.
Member Function Documentation
buf()
SBuf SBufStream::buf () inline
Definition at line 41 of file Stream.h.
References sink_.
Referenced by Format::Format::assemble(), Security::ErrorDetail::brief(), ConfigurationFailureMessage(), ACLAnnotationData::dump(), ACLRegexData::dump(), ErrorState::Dump(), dump_cache_log_message(), DumpDirective(), ProxyProtocol::Header::getValues(), Store::PackSwapMeta(), Rock::Rebuild::progressDescription(), Security::KeyLog::record(), HappyConnOpener::status(), TestSBuf::testSBufStream(), ProxyProtocol::Header::toMime(), ToSBuf(), and Security::ErrorDetail::verbose().
clearBuf()
SBufStream & SBufStream::clearBuf () inline
Definition at line 47 of file Stream.h.
References SBuf::clear(), and sink_.
Referenced by TestSBuf::testSBufStream().
Member Data Documentation
sink_
SBuf SBufStream::sink_ private
Definition at line 55 of file Stream.h.
Referenced by buf(), and clearBuf().
streamBuffer_
AppendingStreamBuf<SBuf> SBufStream::streamBuffer_ private
Definition at line 57 of file Stream.h.
Referenced by SBufStream().
The documentation for this class was generated from the following file:
squid/src/sbuf/Stream.h