Squid Web Cache: Adaptation::Icap::Xaction Class Reference
Adaptation::Icap::Xaction Class Reference abstract
#include <Xaction.h>
Public Types
typedef CbcPointer< AsyncJob > Pointer
Public Member Functions
Xaction (const char *aTypeName, ServiceRep::Pointer &aService)
~Xaction () override
void disableRetries ()
void disableRepeats (const char *reason)
bool retriable () const
bool repeatable () const
void noteCommConnected (const CommConnectCbParams &io)
called when the connection attempt to an ICAP service completes (successfully or not)
void noteCommWrote (const CommIoCbParams &io)
void noteCommRead (const CommIoCbParams &io)
void noteCommTimedout (const CommTimeoutCbParams &io)
void noteCommClosed (const CommCloseCbParams &io)
void callException (const std::exception &e) override
called when the job throws during an async call
void callEnd () override
called right after the called job method
virtual void clearError ()
clear stored error details, if any; used for retries/repeats
virtual AccessLogEntry::Pointer masterLogEntry ()
void dnsLookupDone (std::optional< Ip::Address >)
ServiceRep & service ()
void initiator (const CbcPointer< Initiator > &i)
sets initiator
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
HttpRequest * icapRequest
sent (or at least created) ICAP request
HttpReply::Pointer icapReply
received ICAP reply, if any
int attempts
the number of times we tried to get to the service, including this time
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void start () override
called by AsyncStart; do not call directly
void noteInitiatorAborted () override
virtual void startShoveling ()=0
starts sending/receiving ICAP messages
virtual void handleCommWrote (size_t sz)=0
virtual void handleCommRead (size_t sz)=0
void handleSecuredPeer (Security::EncryptorAnswer &answer)
virtual void detailError (const ErrorDetailPointer &)
record error detail if possible
void openConnection ()
void closeConnection ()
bool haveConnection () const
void scheduleRead ()
void scheduleWrite (MemBuf &buf)
void updateTimeout ()
void cancelRead ()
bool parseHttpMsg (Http::Message *msg)
bool mayReadMore () const
virtual bool doneReading () const
virtual bool doneWriting () const
bool doneWithIo () const
bool doneAll () const override
whether positive goal has been reached
void swanSong () override
const char * status () const override
internal cleanup; do not call directly
virtual void fillPendingStatus (MemBuf &buf) const
virtual void fillDoneStatus (MemBuf &buf) const
virtual bool fillVirginHttpHeader (MemBuf &) const
void setOutcome (const XactOutcome &xo)
virtual void finalizeLogInfo ()
void sendAnswer (const Answer &answer)
void tellQueryAborted (bool final)
void clearInitiator ()
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
Adaptation::Icap::ServiceRep::Pointer theService
SBuf readBuf
bool commEof
bool reuseConnection
bool isRetriable
can retry on persistent connection failures
bool isRepeatable
can repeat if no or unsatisfactory response
bool ignoreLastWrite
bool waitingForDns
expecting a ipcache_nbgethostbyname() callback
AsyncCall::Pointer reader
AsyncCall::Pointer writer
AccessLogEntry::Pointer alep
icap.log entry
AccessLogEntry & al
short for *alep
timeval icap_tr_start
timeval icap_tio_start
timeval icap_tio_finish
CbcPointer< Initiator > theInitiator
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
void useTransportConnection (const Comm::ConnectionPointer &)
void useIcapConnection (const Comm::ConnectionPointer &)
react to the availability of a fully-ready ICAP connection
void dieOnConnectionFailure ()
void tellQueryAborted ()
void maybeLog ()
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
JobWait< Comm::ConnOpener > transportWait
waits for a transport connection to the ICAP server to be established/opened
JobWait< Ssl::IcapPeerConnector > encryptionWait
waits for the established transport connection to be secured/encrypted
Comm::ConnectionPointer connection
open and, if necessary, secured connection to the ICAP server (or nil)
AsyncCall::Pointer closer
Detailed Description
Definition at line 43 of file Xaction.h.
Member Typedef Documentation
Pointer
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Constructor & Destructor Documentation
Xaction()
Adaptation::Icap::Xaction::Xaction (const char * aTypeName, ServiceRep::Pointer & aService)
Definition at line 69 of file Xaction.cc.
References current_time, debugs, HTTPMSGLOCK(), icap_tio_finish, icap_tio_start, icap_tr_start, icapRequest, and AsyncJob::typeName.
~Xaction()
Adaptation::Icap::Xaction::~Xaction () override
Definition at line 95 of file Xaction.cc.
References debugs, and HTTPMSGUNLOCK().
Member Function Documentation
callEnd()
void Adaptation::Icap::Xaction::callEnd () override virtual
called right after the called job method
Reimplemented from AsyncJob.
Definition at line 379 of file Xaction.cc.
References AsyncJob::callEnd(), and debugs.
callException()
void Adaptation::Icap::Xaction::callException (const std::exception & e) override virtual
Reimplemented from AsyncJob.
Definition at line 372 of file Xaction.cc.
References AsyncJob::callException(), and Adaptation::Icap::xoError.
Referenced by Adaptation::Icap::ModXact::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
cancelRead()
void Adaptation::Icap::Xaction::cancelRead () protected
Definition at line 487 of file Xaction.cc.
References Must, and Comm::ReadCancel().
clearError()
virtual void Adaptation::Icap::Xaction::clearError () inline virtual
Reimplemented in Adaptation::Icap::ModXact.
Definition at line 118 of file Xaction.h.
Referenced by Adaptation::Icap::Launcher::launchXaction().
clearInitiator()
void Adaptation::Initiate::clearInitiator () protected inherited
Definition at line 74 of file Initiate.cc.
closeConnection()
void Adaptation::Icap::Xaction::closeConnection () protected
Definition at line 218 of file Xaction.cc.
References comm_remove_close_handler(), commUnsetConnTimeout(), debugs, Adaptation::Icap::xoError, and Adaptation::Icap::xoGone.
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
detailError()
virtual void Adaptation::Icap::Xaction::detailError (const ErrorDetailPointer &) inline protected virtual
Reimplemented in Adaptation::Icap::ModXact.
Definition at line 82 of file Xaction.h.
dieOnConnectionFailure()
void Adaptation::Icap::Xaction::dieOnConnectionFailure () private
Definition at line 306 of file Xaction.cc.
References debugs, MakeNamedErrorDetail(), and TexcHere.
Referenced by dnsLookupDone().
disableRepeats()
void Adaptation::Icap::Xaction::disableRepeats (const char * reason)
Definition at line 123 of file Xaction.cc.
References debugs.
Referenced by Adaptation::Icap::Launcher::launchXaction().
disableRetries()
void Adaptation::Icap::Xaction::disableRetries ()
Definition at line 116 of file Xaction.cc.
References debugs.
Referenced by Adaptation::Icap::Launcher::launchXaction().
dnsLookupDone()
void Adaptation::Icap::Xaction::dnsLookupDone (std::optional< Ip::Address > addr)
Definition at line 187 of file Xaction.cc.
References assert, CallJobHere, Adaptation::Service::cfg(), Adaptation::Icap::Config::connect_timeout(), DBG_IMPORTANT, debugs, dieOnConnectionFailure(), getOutgoingAddress(), Adaptation::ServiceConfig::host, JobCallback, noteCommConnected(), Adaptation::ServiceConfig::port, Ip::Address::port(), Comm::Connection::remote, String::termedBuf(), and Adaptation::Icap::TheConfig.
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Adaptation::Icap::Xaction::doneAll () const override protected virtual
Reimplemented from AsyncJob.
Definition at line 388 of file Xaction.cc.
References AsyncJob::doneAll().
Referenced by Adaptation::Icap::ModXact::doneAll().
doneReading()
bool Adaptation::Icap::Xaction::doneReading () const protected virtual
Reimplemented in Adaptation::Icap::ModXact, and Adaptation::Icap::OptXact.
Definition at line 523 of file Xaction.cc.
doneWithIo()
bool Adaptation::Icap::Xaction::doneWithIo () const protected
Definition at line 533 of file Xaction.cc.
doneWriting()
bool Adaptation::Icap::Xaction::doneWriting () const protected virtual
Reimplemented in Adaptation::Icap::ModXact.
Definition at line 528 of file Xaction.cc.
fillDoneStatus()
void Adaptation::Icap::Xaction::fillDoneStatus (MemBuf & buf) const protected virtual
Reimplemented in Adaptation::Icap::ModXact.
Definition at line 667 of file Xaction.cc.
References MemBuf::append(), and Packable::appendf().
Referenced by Adaptation::Icap::ModXact::fillDoneStatus().
fillPendingStatus()
void Adaptation::Icap::Xaction::fillPendingStatus (MemBuf & buf) const protected virtual
Reimplemented in Adaptation::Icap::ModXact.
Definition at line 649 of file Xaction.cc.
References MemBuf::append(), and Packable::appendf().
Referenced by Adaptation::Icap::ModXact::fillPendingStatus().
fillVirginHttpHeader()
bool Adaptation::Icap::Xaction::fillVirginHttpHeader (MemBuf &) const protected virtual
Reimplemented in Adaptation::Icap::ModXact.
Definition at line 676 of file Xaction.cc.
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
finalizeLogInfo()
void Adaptation::Icap::Xaction::finalizeLogInfo () protected virtual
Reimplemented in Adaptation::Icap::ModXact, and Adaptation::Icap::OptXact.
Definition at line 612 of file Xaction.cc.
References Adaptation::Service::cfg(), current_time, Adaptation::ServiceConfig::host, HTTPMSGLOCK(), ICP_INVALID, Adaptation::ServiceConfig::key, String::termedBuf(), tvSub(), and Adaptation::ServiceConfig::uri.
Referenced by Adaptation::Icap::ModXact::finalizeLogInfo(), and Adaptation::Icap::OptXact::finalizeLogInfo().
handleCommRead()
virtual void Adaptation::Icap::Xaction::handleCommRead (size_t sz) protected pure virtual
Implemented in Adaptation::Icap::ModXact, and Adaptation::Icap::OptXact.
handleCommWrote()
virtual void Adaptation::Icap::Xaction::handleCommWrote (size_t sz) protected pure virtual
Implemented in Adaptation::Icap::ModXact, and Adaptation::Icap::OptXact.
handleSecuredPeer()
void Adaptation::Icap::Xaction::handleSecuredPeer (Security::EncryptorAnswer & answer) protected
Definition at line 717 of file Xaction.cc.
References assert, Security::EncryptorAnswer::conn, debugs, Security::EncryptorAnswer::error, Comm::Connection::fd, fd_table, CbcPointer< Cbc >::get(), Comm::Connection::isOpen(), MakeNamedErrorDetail(), Comm::Connection::noteClosure(), TexcHere, and Security::EncryptorAnswer::tunneled.
Referenced by useTransportConnection().
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
haveConnection()
bool Adaptation::Icap::Xaction::haveConnection () const protected
Definition at line 540 of file Xaction.cc.
initiator()
void Adaptation::Initiate::initiator (const CbcPointer< Initiator > & i) inherited
Definition at line 54 of file Initiate.cc.
References Must, and CbcPointer< Cbc >::valid().
Referenced by Adaptation::Initiator::initiateAdaptation().
masterLogEntry()
AccessLogEntry::Pointer Adaptation::Icap::Xaction::masterLogEntry () virtual
Reimplemented in Adaptation::Icap::ModXact.
Definition at line 103 of file Xaction.cc.
maybeLog()
void Adaptation::Icap::Xaction::maybeLog () private
Definition at line 604 of file Xaction.cc.
References IcapLogfileStatus, icapLogLog(), and LOG_ENABLE.
mayReadMore()
bool Adaptation::Icap::Xaction::mayReadMore () const protected
Definition at line 517 of file Xaction.cc.
References SQUID_TCP_SO_RCVBUF.
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteCommClosed()
void Adaptation::Icap::Xaction::noteCommClosed (const CommCloseCbParams & io)
Definition at line 359 of file Xaction.cc.
References MakeNamedErrorDetail().
Referenced by useIcapConnection().
noteCommConnected()
void Adaptation::Icap::Xaction::noteCommConnected (const CommConnectCbParams & io)
Definition at line 253 of file Xaction.cc.
References CommCommonCbParams::conn, CommCommonCbParams::flag, and Comm::OK.
Referenced by dnsLookupDone().
noteCommRead()
void Adaptation::Icap::Xaction::noteCommRead (const CommIoCbParams & io)
Definition at line 426 of file Xaction.cc.
References CommCommonCbParams::conn, debugs, Comm::ENDFILE, CommCommonCbParams::flag, Comm::INPROGRESS, Must, Comm::OK, Comm::ReadNow(), CommIoCbParams::size, SQUID_TCP_SO_RCVBUF, CommCommonCbParams::xerrno, Adaptation::Icap::xoRace, and xstrerr().
Referenced by scheduleRead().
noteCommTimedout()
void Adaptation::Icap::Xaction::noteCommTimedout (const CommTimeoutCbParams & io)
Definition at line 347 of file Xaction.cc.
References assert, debugs, and Here.
Referenced by updateTimeout().
noteCommWrote()
void Adaptation::Icap::Xaction::noteCommWrote (const CommIoCbParams & io)
Definition at line 329 of file Xaction.cc.
References debugs, CommCommonCbParams::flag, Must, Comm::OK, and CommIoCbParams::size.
Referenced by scheduleWrite().
noteInitiatorAborted()
void Adaptation::Icap::Xaction::noteInitiatorAborted () override protected virtual
Implements Adaptation::Initiate.
Definition at line 546 of file Xaction.cc.
References debugs, MakeNamedErrorDetail(), and Adaptation::Icap::xoGone.
openConnection()
void Adaptation::Icap::Xaction::openConnection () protected
Definition at line 161 of file Xaction.cc.
References assert, Adaptation::Service::cfg(), debugs, Adaptation::Icap::ServiceRep::getIdleConnection(), Adaptation::ServiceConfig::host, icapLookupDnsResults(), ipcache_nbgethostbyname(), Must, Adaptation::ServiceConfig::port, Adaptation::Icap::Config::reuse_connections, String::termedBuf(), and Adaptation::Icap::TheConfig.
parseHttpMsg()
bool Adaptation::Icap::Xaction::parseHttpMsg (Http::Message * msg) protected
Definition at line 497 of file Xaction.cc.
References debugs, error(), Http::Message::hdr_sz, Must, Http::Message::parse(), Http::Message::reset(), and Http::scNone.
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
repeatable()
bool Adaptation::Icap::Xaction::repeatable () const inline
Definition at line 53 of file Xaction.h.
References isRepeatable.
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
retriable()
bool Adaptation::Icap::Xaction::retriable () const inline
Definition at line 52 of file Xaction.h.
References isRetriable.
scheduleRead()
void Adaptation::Icap::Xaction::scheduleRead () protected
Definition at line 413 of file Xaction.cc.
References JobCallback, Must, noteCommRead(), Comm::Read(), and SQUID_TCP_SO_RCVBUF.
scheduleWrite()
void Adaptation::Icap::Xaction::scheduleWrite (MemBuf & buf) protected
Definition at line 316 of file Xaction.cc.
References JobCallback, Must, noteCommWrote(), and Comm::Write().
sendAnswer()
void Adaptation::Initiate::sendAnswer (const Answer & answer) protected inherited
Definition at line 79 of file Initiate.cc.
References Adaptation::Initiator::noteAdaptationAnswer(), and ScheduleCallHere.
service()
Adaptation::Icap::ServiceRep & Adaptation::Icap::Xaction::service ()
Definition at line 110 of file Xaction.cc.
References Must.
setOutcome()
void Adaptation::Icap::Xaction::setOutcome (const XactOutcome & xo) protected
Definition at line 560 of file Xaction.cc.
References debugs, and Adaptation::Icap::xoUnknown.
start()
void Adaptation::Icap::Xaction::start () override protected virtual
Reimplemented from AsyncJob.
Definition at line 130 of file Xaction.cc.
References AsyncJob::start().
Referenced by Adaptation::Icap::ModXact::start(), and Adaptation::Icap::OptXact::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
startShoveling()
virtual void Adaptation::Icap::Xaction::startShoveling () protected pure virtual
Implemented in Adaptation::Icap::ModXact, and Adaptation::Icap::OptXact.
status()
const char * Adaptation::Icap::Xaction::status () const override protected virtual
for debugging, starts with space
Reimplemented from AsyncJob.
Definition at line 635 of file Xaction.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), and MemBuf::terminate().
Referenced by Adaptation::Icap::ModXact::ModXact().
swanSong()
void Adaptation::Icap::Xaction::swanSong () override protected virtual
Reimplemented from AsyncJob.
Definition at line 573 of file Xaction.cc.
References Adaptation::Initiate::swanSong().
Referenced by Adaptation::Icap::ModXact::swanSong(), and Adaptation::Icap::OptXact::swanSong().
tellQueryAborted() [1/2]
void Adaptation::Icap::Xaction::tellQueryAborted () private
Definition at line 591 of file Xaction.cc.
References CallJobHere1.
tellQueryAborted() [2/2]
void Adaptation::Initiate::tellQueryAborted (bool final) protected inherited
Definition at line 87 of file Initiate.cc.
References Adaptation::Answer::Error().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
updateTimeout()
void Adaptation::Icap::Xaction::updateTimeout () protected
Definition at line 395 of file Xaction.cc.
References commSetConnTimeout(), commUnsetConnTimeout(), Adaptation::Icap::Config::io_timeout(), JobCallback, Must, noteCommTimedout(), and Adaptation::Icap::TheConfig.
useIcapConnection()
void Adaptation::Icap::Xaction::useIcapConnection (const Comm::ConnectionPointer & conn) private
Definition at line 290 of file Xaction.cc.
References assert, asyncCall(), comm_add_close_handler(), Comm::IsConnOpen(), and noteCommClosed().
useTransportConnection()
void Adaptation::Icap::Xaction::useTransportConnection (const Comm::ConnectionPointer & conn) private
React to the availability of a transport connection to the ICAP service. The given connection may (or may not) be secured already.
Definition at line 268 of file Xaction.cc.
References assert, asyncCallback, Adaptation::Icap::Config::connect_timeout(), Comm::Connection::fd, fd_table, handleSecuredPeer(), Comm::IsConnOpen(), and Adaptation::Icap::TheConfig.
Member Data Documentation
al
AccessLogEntry& Adaptation::Icap::Xaction::al protected
Definition at line 152 of file Xaction.h.
alep
AccessLogEntry::Pointer Adaptation::Icap::Xaction::alep protected
Definition at line 151 of file Xaction.h.
attempts
int Adaptation::Icap::Xaction::attempts
Definition at line 67 of file Xaction.h.
Referenced by Adaptation::Icap::Launcher::launchXaction().
closer
AsyncCall::Pointer Adaptation::Icap::Xaction::closer private
Definition at line 168 of file Xaction.h.
commEof
bool Adaptation::Icap::Xaction::commEof protected
Definition at line 141 of file Xaction.h.
Referenced by Adaptation::Icap::ModXact::doneReading(), and Adaptation::Icap::OptXact::doneReading().
connection
Comm::ConnectionPointer Adaptation::Icap::Xaction::connection private
Definition at line 166 of file Xaction.h.
encryptionWait
JobWait<Ssl::IcapPeerConnector> Adaptation::Icap::Xaction::encryptionWait private
Definition at line 163 of file Xaction.h.
icap_tio_finish
timeval Adaptation::Icap::Xaction::icap_tio_finish protected
Definition at line 156 of file Xaction.h.
Referenced by Xaction().
icap_tio_start
timeval Adaptation::Icap::Xaction::icap_tio_start protected
Definition at line 155 of file Xaction.h.
Referenced by Xaction().
icap_tr_start
timeval Adaptation::Icap::Xaction::icap_tr_start protected
Definition at line 154 of file Xaction.h.
Referenced by Xaction().
icapReply
HttpReply::Pointer Adaptation::Icap::Xaction::icapReply
Definition at line 64 of file Xaction.h.
Referenced by Adaptation::Icap::ModXact::ModXact().
icapRequest
HttpRequest* Adaptation::Icap::Xaction::icapRequest
Definition at line 63 of file Xaction.h.
Referenced by Xaction().
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
ignoreLastWrite
bool Adaptation::Icap::Xaction::ignoreLastWrite protected
Definition at line 145 of file Xaction.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
isRepeatable
bool Adaptation::Icap::Xaction::isRepeatable protected
Definition at line 144 of file Xaction.h.
Referenced by repeatable().
isRetriable
bool Adaptation::Icap::Xaction::isRetriable protected
Definition at line 143 of file Xaction.h.
Referenced by retriable().
readBuf
SBuf Adaptation::Icap::Xaction::readBuf protected
Definition at line 140 of file Xaction.h.
reader
AsyncCall::Pointer Adaptation::Icap::Xaction::reader protected
Definition at line 148 of file Xaction.h.
reuseConnection
bool Adaptation::Icap::Xaction::reuseConnection protected
Definition at line 142 of file Xaction.h.
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
theInitiator
CbcPointer<Initiator> Adaptation::Initiate::theInitiator protected inherited
Definition at line 51 of file Initiate.h.
theService
Adaptation::Icap::ServiceRep::Pointer Adaptation::Icap::Xaction::theService protected
Definition at line 138 of file Xaction.h.
transportWait
JobWait<Comm::ConnOpener> Adaptation::Icap::Xaction::transportWait private
Definition at line 160 of file Xaction.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
waitingForDns
bool Adaptation::Icap::Xaction::waitingForDns protected
Definition at line 146 of file Xaction.h.
writer
AsyncCall::Pointer Adaptation::Icap::Xaction::writer protected
Definition at line 149 of file Xaction.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/Xaction.h
squid/src/adaptation/icap/Xaction.cc