Squid Web Cache: Aggregate::AggregateId Class Reference
Aggregate::AggregateId Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Public Types
typedef RefCount< DelayIdComposite > Pointer
Public Member Functions
void * operator new (size_t byteCount)
void operator delete (void *address)
AggregateId (RefCount< Aggregate >)
int bytesWanted (int min, int max) const override
void bytesIn (int qty) override
void delayRead (const AsyncCallPointer &) override
Static Public Member Functions
static int UseCount ()
Static Private Member Functions
static Mem::AllocatorProxy & Pool ()
Private Attributes
RefCount< Aggregate > theAggregate
Detailed Description
Definition at line 65 of file delay_pools.cc.
Member Typedef Documentation
Pointer
typedef RefCount<DelayIdComposite> DelayIdComposite::Pointer inherited
Definition at line 23 of file DelayIdComposite.h.
Constructor & Destructor Documentation
AggregateId()
Aggregate::AggregateId::AggregateId (RefCount< Aggregate > anAggregate)
Definition at line 431 of file delay_pools.cc.
Member Function Documentation
bytesIn()
void Aggregate::AggregateId::bytesIn (int qty) override virtual
Implements DelayIdComposite.
Definition at line 441 of file delay_pools.cc.
bytesWanted()
int Aggregate::AggregateId::bytesWanted (int min, int max) const override virtual
Implements DelayIdComposite.
Definition at line 435 of file delay_pools.cc.
References max(), and min().
delayRead()
void Aggregate::AggregateId::delayRead (const AsyncCallPointer & aRead) override virtual
Reimplemented from DelayIdComposite.
Definition at line 242 of file delay_pools.cc.
References CompositePoolNode::delayRead(), and theAggregate.
operator delete()
void Aggregate::AggregateId::operator delete (void * address) inline
Definition at line 67 of file delay_pools.cc.
operator new()
void * Aggregate::AggregateId::operator new (size_t byteCount) inline
Definition at line 67 of file delay_pools.cc.
Pool()
static Mem::AllocatorProxy & Aggregate::AggregateId::Pool () inline static private
Definition at line 67 of file delay_pools.cc.
UseCount()
static int Aggregate::AggregateId::UseCount () inline static
Definition at line 67 of file delay_pools.cc.
Member Data Documentation
theAggregate
RefCount<Aggregate> Aggregate::AggregateId::theAggregate private
Definition at line 76 of file delay_pools.cc.
Referenced by delayRead().
The documentation for this class was generated from the following file:
squid/src/delay_pools.cc