Squid Web Cache: Ipc::Strand Class Reference
Ipc::Strand Class Reference abstract
Receives coordination messages on behalf of its process or thread.
#include <Strand.h>
Public Types
typedef CbcPointer< AsyncJob > Pointer
Public Member Functions
Strand ()
void start () override
called by AsyncStart; do not call directly
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static String MakeAddr (const char *proccessLabel, int id)
calculates IPC message address for strand id of processLabel type
static String CoordinatorAddr ()
get the IPC message address for coordinator process
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
struct sockaddr_un address
UDS address from path; treat as read-only.
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void timedout () override
called after setTimeout() if timed out
void receive (const TypedMsgHdr &message) override
bool doneAll () const override
whether positive goal has been reached
void doListen ()
read the next incoming message
Comm::ConnectionPointer & conn ()
creates if needed and returns raw UDS socket descriptor
void setTimeout (time_t seconds, const char *handlerName)
call timedout() if no UDS messages in a given number of seconds
void clearTimeout ()
remove previously set timeout, if any
void setOptions (int newOptions)
changes socket options
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual void swanSong ()
virtual const char * status () const
internal cleanup; do not call directly
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
CBDATA_CHILD (Strand)
void registerSelf ()
void handleRegistrationResponse (const StrandMessage &)
let Coordinator know this strand exists
void handleCacheMgrRequest (const Mgr::Request &request)
void handleCacheMgrResponse (const Mgr::Response &response)
void handleSnmpRequest (const Snmp::Request &request)
void handleSnmpResponse (const Snmp::Response &response)
Strand (const Strand &)
Strand & operator= (const Strand &)
void noteRead (const CommIoCbParams &params)
void receiveOrIgnore (const TypedMsgHdr &)
receive() but ignore any errors
void noteTimeout (const CommTimeoutCbParams &p)
Comm timeout callback; calls timedout()
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
bool isRegistered
whether Coordinator ACKed registration (unused)
TypedMsgHdr buf
msghdr struct filled by Comm
int options
UDS options.
Comm::ConnectionPointer conn_
UDS descriptor.
Detailed Description
Definition at line 27 of file Strand.h.
Member Typedef Documentation
Pointer
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Constructor & Destructor Documentation
Strand() [1/2]
Ipc::Strand::Strand ()
Definition at line 40 of file Strand.cc.
References Ipc::strandAddrLabel.
Strand() [2/2]
Ipc::Strand::Strand (const Strand &) private
Member Function Documentation
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
CBDATA_CHILD()
Ipc::Strand::CBDATA_CHILD (Strand) private
clearTimeout()
void Ipc::UdsOp::clearTimeout () protected inherited
Definition at line 63 of file UdsOp.cc.
References commUnsetConnTimeout().
conn()
Comm::ConnectionPointer & Ipc::UdsOp::conn () protected inherited
Definition at line 42 of file UdsOp.cc.
References COMM_DOBIND, comm_open_uds(), Comm::Connection::fd, Comm::IsConnOpen(), and Must.
CoordinatorAddr()
String Ipc::Port::CoordinatorAddr () static inherited
Definition at line 65 of file Port.cc.
References String::append(), channelPathPfx, coordinatorAddrLabel, Instance::NamePrefix(), and String::size().
Referenced by Ipc::StrandMessage::NotifyCoordinator(), IpcIoFile::open(), Mgr::Action::sendResponse(), Snmp::SendResponse(), SendSharedListenRequest(), and Ipc::Forwarder::start().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
doListen()
void Ipc::Port::doListen () protected inherited
Definition at line 38 of file Port.cc.
References comm_read(), debugs, JobCallback, MYNAME, and Ipc::Port::noteRead().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Ipc::Port::doneAll () const override protected virtual inherited
Reimplemented from AsyncJob.
Definition at line 48 of file Port.cc.
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
handleCacheMgrRequest()
void Ipc::Strand::handleCacheMgrRequest (const Mgr::Request & request) private
Definition at line 127 of file Strand.cc.
References CacheManager::createRequestedAction(), CacheManager::GetInstance(), and Mgr::Request::params.
handleCacheMgrResponse()
void Ipc::Strand::handleCacheMgrResponse (const Mgr::Response & response) private
Definition at line 134 of file Strand.cc.
References Ipc::Forwarder::HandleRemoteAck(), and Ipc::Response::requestId.
handleRegistrationResponse()
void Ipc::Strand::handleRegistrationResponse (const StrandMessage & msg) private
Definition at line 120 of file Strand.cc.
References Assure, debugs, Ipc::StrandCoord::kidId, KidIdentifier, and Ipc::StrandMessage::strand.
handleSnmpRequest()
void Ipc::Strand::handleSnmpRequest (const Snmp::Request & request) private
Definition at line 140 of file Strand.cc.
References debugs, MYNAME, Snmp::Request::pdu, Ipc::Request::requestId, and Snmp::SendResponse().
handleSnmpResponse()
void Ipc::Strand::handleSnmpResponse (const Snmp::Response & response) private
Definition at line 146 of file Strand.cc.
References debugs, Ipc::Forwarder::HandleRemoteAck(), MYNAME, and Ipc::Response::requestId.
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
MakeAddr()
String Ipc::Port::MakeAddr (const char * proccessLabel, int id) static inherited
Definition at line 53 of file Port.cc.
References String::append(), assert, channelPathPfx, Instance::NamePrefix(), and xitoa().
Referenced by Ipc::Inquirer::inquire(), IpcIoFile::Notify(), and CollapsedForwarding::Notify().
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteRead()
void Ipc::Port::noteRead (const CommIoCbParams & params) private inherited
Definition at line 94 of file Port.cc.
References assert, CommIoCbParams::buf, CommCommonCbParams::conn, debugs, CommCommonCbParams::flag, and Comm::OK.
Referenced by Ipc::Port::doListen().
noteTimeout()
void Ipc::UdsOp::noteTimeout (const CommTimeoutCbParams & p) private inherited
Definition at line 68 of file UdsOp.cc.
Referenced by Ipc::UdsOp::setTimeout().
operator=()
Strand & Ipc::Strand::operator= (const Strand &) private
receive()
void Ipc::Strand::receive (const TypedMsgHdr & message) override protected virtual
handle IPC message just read kids must call parent method when they do not recognize the message type
Implements Ipc::Port.
Definition at line 61 of file Strand.cc.
References CollapsedForwarding::HandleNotification(), IpcIoFile::HandleNotification(), IpcIoFile::HandleOpenResponse(), Ipc::Mine(), Ipc::mtCacheMgrRequest, Ipc::mtCacheMgrResponse, Ipc::mtCollapsedForwardingNotification, Ipc::mtIpcIoNotification, Ipc::mtSharedListenResponse, Ipc::mtSnmpRequest, Ipc::mtSnmpResponse, Ipc::mtStrandReady, Ipc::mtStrandRegistered, Ipc::TypedMsgHdr::rawType(), Ipc::Port::receive(), and Ipc::SharedListenJoined().
receiveOrIgnore()
void Ipc::Port::receiveOrIgnore (const TypedMsgHdr & message) private inherited
Definition at line 83 of file Port.cc.
References CurrentException(), DBG_IMPORTANT, debugs, Debug::Extra(), and Ipc::TypedMsgHdr::rawType().
registerSelf()
void Ipc::Strand::registerSelf () private
Definition at line 52 of file Strand.cc.
References debugs, Ipc::mtRegisterStrand, Must, MYNAME, and Ipc::StrandMessage::NotifyCoordinator().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
setOptions()
void Ipc::UdsOp::setOptions (int newOptions) protected inherited
Definition at line 36 of file UdsOp.cc.
Referenced by Ipc::Port::Port().
setTimeout()
void Ipc::UdsOp::setTimeout (time_t seconds, const char * handlerName) protected inherited
Definition at line 55 of file UdsOp.cc.
References asyncCall(), commSetConnTimeout(), and Ipc::UdsOp::noteTimeout().
start()
void Ipc::Strand::start () override virtual
Implements Ipc::Port.
Definition at line 46 of file Strand.cc.
References Ipc::Port::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
status()
const char * AsyncJob::status () const protected virtual inherited
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), AsyncJob::stopReason, and MemBuf::terminate().
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
swanSong()
virtual void AsyncJob::swanSong () inline protected virtual inherited
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::ModXactLauncher, Adaptation::Icap::OptXact, Adaptation::Icap::Xaction, Adaptation::Initiate, Adaptation::Iterator, ConnStateData, Client, Ftp::Relay, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, Ipc::Forwarder, Ipc::Inquirer, Ipc::UdsSender, Log::TcpLogger, Mgr::Filler, Mgr::Forwarder, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Server, and Snmp::Forwarder.
Definition at line 61 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), Client::swanSong(), Ftp::Relay::swanSong(), Http::Tunneler::swanSong(), Comm::ConnOpener::swanSong(), Comm::TcpAcceptor::swanSong(), Rock::HeaderUpdater::swanSong(), HappyConnOpener::swanSong(), Ipc::UdsSender::swanSong(), Log::TcpLogger::swanSong(), PeerPoolMgr::swanSong(), Security::PeerConnector::swanSong(), and Server::swanSong().
timedout()
void Ipc::Strand::timedout () override protected virtual
Reimplemented from Ipc::UdsOp.
Definition at line 153 of file Strand.cc.
References debugs, fatalf(), and KidIdentifier.
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
Member Data Documentation
address
struct sockaddr_un Ipc::UdsOp::address inherited
Definition at line 37 of file UdsOp.h.
Referenced by Ipc::UdsSender::UdsSender().
buf
TypedMsgHdr Ipc::Port::buf private inherited
Definition at line 47 of file Port.h.
conn_
Comm::ConnectionPointer Ipc::UdsOp::conn_ private inherited
Definition at line 56 of file UdsOp.h.
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
isRegistered
bool Ipc::Strand::isRegistered private
Definition at line 51 of file Strand.h.
options
int Ipc::UdsOp::options private inherited
Definition at line 55 of file UdsOp.h.
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
The documentation for this class was generated from the following files:
squid/src/ipc/Strand.h
squid/src/ipc/Strand.cc