Squid Web Cache: IORequestor Class Reference
IORequestor Class Reference abstract
#include <IORequestor.h>
Public Types
typedef RefCount< IORequestor > Pointer
Public Member Functions
virtual void ioCompletedNotification ()=0
virtual void closeCompleted ()=0
virtual void readCompleted (const char *buf, int len, int errflag, RefCount< ReadRequest >)=0
virtual void writeCompleted (int errflag, size_t len, RefCount< WriteRequest >)=0
Detailed Description
Definition at line 18 of file IORequestor.h.
Member Typedef Documentation
Pointer
typedef RefCount<IORequestor> IORequestor::Pointer
Definition at line 22 of file IORequestor.h.
Member Function Documentation
closeCompleted()
virtual void IORequestor::closeCompleted () pure virtual
Implemented in Rock::SwapDir, and Fs::Ufs::UFSStoreState.
Referenced by BlockingFile::close(), DiskThreadsDiskFile::close(), IpcIoFile::close(), MmappedFile::close(), and DiskdFile::closeDone().
ioCompletedNotification()
virtual void IORequestor::ioCompletedNotification () pure virtual
Implemented in Rock::SwapDir, and Fs::Ufs::UFSStoreState.
Referenced by DiskdFile::notifyClient(), DiskdFile::open(), IpcIoFile::open(), IpcIoFile::openCompleted(), and DiskThreadsDiskFile::openDone().
readCompleted()
virtual void IORequestor::readCompleted (const char * buf, int len, int errflag, RefCount< ReadRequest >) pure virtual
Implemented in Fs::Ufs::UFSStoreState.
Referenced by MmappedFile::read(), IpcIoFile::readCompleted(), DiskdFile::readDone(), BlockingFile::readDone(), and DiskThreadsDiskFile::readDone().
writeCompleted()
virtual void IORequestor::writeCompleted (int errflag, size_t len, RefCount< WriteRequest >) pure virtual
Implemented in Fs::Ufs::UFSStoreState.
Referenced by MmappedFile::write(), IpcIoFile::writeCompleted(), DiskdFile::writeDone(), BlockingFile::writeDone(), and DiskThreadsDiskFile::writeDone().
The documentation for this class was generated from the following file:
squid/src/DiskIO/IORequestor.h