Squid Web Cache: Security::Alert Class Reference
Security::Alert Class Reference
TLS Alert protocol frame from RFC 5246 Section 7.2.
Public Member Functions
Alert (Parser::BinaryTokenizer &tk)
bool fatal () const
Public Attributes
uint8_t level
warning or fatal
uint8_t description
close_notify, unexpected_message, etc.
Detailed Description
Definition at line 76 of file Handshake.cc.
Constructor & Destructor Documentation
Alert()
Security::Alert::Alert (Parser::BinaryTokenizer & tk) explicit
Definition at line 174 of file Handshake.cc.
References Parser::BinaryTokenizerContext::success(), and Parser::BinaryTokenizer::uint8().
Member Function Documentation
fatal()
bool Security::Alert::fatal () const inline
Definition at line 81 of file Handshake.cc.
References level.
Referenced by Security::HandshakeParser::parseAlertMessage().
Member Data Documentation
description
uint8_t Security::Alert::description
Definition at line 84 of file Handshake.cc.
Referenced by Security::HandshakeParser::parseAlertMessage().
level
uint8_t Security::Alert::level
Definition at line 83 of file Handshake.cc.
Referenced by fatal(), and Security::HandshakeParser::parseAlertMessage().
The documentation for this class was generated from the following file:
squid/src/security/Handshake.cc