Squid Web Cache: Ssl::CertValidationMsg Class Reference
Ssl::CertValidationMsg Class Reference
#include <cert_validate_message.h>
Classes
class CertItem
Public Types
enum ParseResult { OK , INCOMPLETE , ERROR }
Parse result codes.
enum MessageKind { REPLY , REQUEST }
typedef std::map< std::string, std::string > BodyParams
Public Member Functions
CertValidationMsg (MessageKind kind)
void composeRequest (CertValidationRequest const &vcert)
bool parseResponse (CertValidationResponse &resp)
Parse a response message and fill the resp object with parsed information.
X509 * getCertByName (std::vector< CertItem > const &, std::string const &name)
Search a CertItems list for the certificate with ID "name".
ParseResult parse (const char *buffer, size_t len)
std::string const & getBody () const
Current body. If parsing is not finished the method returns incompleted body.
std::string const & getCode () const
Current response/request code. If parsing is not finished the method may return incompleted code.
void setBody (std::string const &aBody)
Set new body to encode.
void setCode (std::string const &aCode)
Set new request/reply code to compose.
std::string compose () const
void clear ()
Reset the class.
void parseBody (BodyParams &map, std::string &other_part) const
void composeBody (BodyParams const &map, std::string const &other_part)
void parseRequest (CertificateProperties &)
orchestrates entire request parsing
void composeRequest (Ssl::CertificateProperties const &)
Static Public Attributes
static const std::string code_cert_validate
String code for "cert_validate" messages.
static const std::string param_domain
Parameter name for passing intended domain name.
static const std::string param_cert
Parameter name for passing SSL certificates.
static const std::string param_error_name
Parameter name for passing the major SSL error.
static const std::string param_error_reason
Parameter name for passing the error reason.
static const std::string param_error_cert
Parameter name for passing the error cert ID.
static const std::string param_error_depth
Parameter name for passing the error depth.
static const std::string param_proto_version
Parameter name for SSL version.
static const std::string param_cipher
Parameter name for SSL cipher.
static const std::string code_new_certificate
String code for "new_certificate" messages.
static const std::string param_host
Parameter name for passing hostname.
static const std::string param_SetValidAfter
Parameter name for passing SetValidAfter cert adaptation variable.
static const std::string param_SetValidBefore
Parameter name for passing SetValidBefore cert adaptation variable.
static const std::string param_SetCommonName
Parameter name for passing SetCommonName cert adaptation variable.
static const std::string param_Sign
Parameter name for passing signing algorithm.
static const std::string param_SignHash
The signing hash to use.
Protected Types
enum ParseState {
BEFORE_CODE , CODE , BEFORE_LENGTH , LENGTH ,
BEFORE_BODY , BODY , END
}
Protected Attributes
size_t body_size
The body size if exist or 0.
ParseState state
Parsing state.
std::string body
Current body.
std::string code
Current response/request code.
std::string current_block
Current block buffer.
Private Member Functions
void tryParsingResponse (CertValidationResponse &)
Detailed Description
This class is responsible for composing or parsing messages destined to or coming from a certificate validation helper. The messages format is:
   response/request-code SP body-length SP [key=value ...] EOL
Note
EOL for this interface is character 0x01
Definition at line 80 of file cert_validate_message.h.
Member Typedef Documentation
BodyParams
typedef std::map<std::string, std::string> Ssl::CrtdMessage::BodyParams inherited
Definition at line 27 of file crtd_message.h.
Member Enumeration Documentation
MessageKind
enum Ssl::CrtdMessage::MessageKind inherited
Enumerator
REPLY
REQUEST
Definition at line 34 of file crtd_message.h.
ParseResult
enum Ssl::CrtdMessage::ParseResult inherited
Enumerator
OK
INCOMPLETE
ERROR
Definition at line 29 of file crtd_message.h.
ParseState
enum Ssl::CrtdMessage::ParseState protected inherited
Enumerator
BEFORE_CODE
CODE
BEFORE_LENGTH
LENGTH
BEFORE_BODY
BODY
END
Definition at line 90 of file crtd_message.h.
Constructor & Destructor Documentation
CertValidationMsg()
Ssl::CertValidationMsg::CertValidationMsg (MessageKind kind) inline
Definition at line 96 of file cert_validate_message.h.
Member Function Documentation
clear()
void Ssl::CrtdMessage::clear () inherited
Definition at line 134 of file crtd_message.cc.
compose()
std::string Ssl::CrtdMessage::compose () const inherited
Compose current (request) code and body to string.
Definition at line 128 of file crtd_message.cc.
Referenced by ConnStateData::getSslContextStart(), processNewRequest(), Ssl::CertValidationHelper::Submit(), and Ssl::Helper::Submit().
composeBody()
void Ssl::CrtdMessage::composeBody (CrtdMessage::BodyParams const & map, std::string const & other_part) inherited
Compose parameters given by map with their values and the other part given by other_part to body data. The constructed body will have the form:
   param1=value1
   param2=value2
   The other multistring part of body.
Definition at line 166 of file crtd_message.cc.
composeRequest() [1/2]
void Ssl::CertValidationMsg::composeRequest (CertValidationRequest const & vcert)
Build a request message for the cert validation helper using information provided by vcert object
Definition at line 38 of file cert_validate_message.cc.
References Ssl::CrtdMessage::body, debugs, Ssl::CertValidationRequest::domainName, Ssl::CertValidationRequest::errors, Ssl::GetErrorName(), param_cert, param_cipher, param_error_cert, param_error_name, Ssl::CrtdMessage::param_host, param_proto_version, Ssl::CertValidationRequest::ssl, STACK_OF(), and xitoa().
Referenced by Ssl::CertValidationHelper::Submit().
composeRequest() [2/2]
void Ssl::CrtdMessage::composeRequest (Ssl::CertificateProperties const & certProperties) inherited
Definition at line 233 of file crtd_message.cc.
References Ssl::algSignEnd, Ssl::appendCertToMemory(), Ssl::certSignAlgorithm(), Ssl::CertificateProperties::commonName, Security::LockingPointer< T, UnLocker, Locker >::get(), Here, Ssl::CertificateProperties::mimicCert, Ssl::CrtdMessage::param_host, Ssl::CrtdMessage::param_SetCommonName, Ssl::CrtdMessage::param_SetValidAfter, Ssl::CrtdMessage::param_SetValidBefore, Ssl::CrtdMessage::param_Sign, Ssl::CrtdMessage::param_SignHash, Ssl::CertificateProperties::setCommonName, Ssl::CertificateProperties::setValidAfter, Ssl::CertificateProperties::setValidBefore, Ssl::CertificateProperties::signAlgorithm, Ssl::CertificateProperties::signHash, Ssl::CertificateProperties::signWithPkey, Ssl::CertificateProperties::signWithX509, and Ssl::writeCertAndPrivateKeyToMemory().
Referenced by ConnStateData::getSslContextStart().
getBody()
std::string const & Ssl::CrtdMessage::getBody () const inherited
Definition at line 120 of file crtd_message.cc.
Referenced by ConnStateData::sslCrtdHandleReply(), and sslCrtvdHandleReplyWrapper().
getCertByName()
X509 * Ssl::CertValidationMsg::getCertByName (std::vector< CertItem > const & certs, std::string const & name)
Definition at line 199 of file cert_validate_message.cc.
getCode()
std::string const & Ssl::CrtdMessage::getCode () const inherited
Definition at line 122 of file crtd_message.cc.
Referenced by main().
parse()
Ssl::CrtdMessage::ParseResult Ssl::CrtdMessage::parse (const char * buffer, size_t len) inherited
Parse buffer of length len
Return values
OK if parsing completes
INCOMPLETE if more data required
ERROR if there is an error.
Definition at line 23 of file crtd_message.cc.
References xisalnum, xisalpha, xisdigit, and xisspace.
Referenced by main(), ConnStateData::sslCrtdHandleReply(), and sslCrtvdHandleReplyWrapper().
parseBody()
void Ssl::CrtdMessage::parseBody (CrtdMessage::BodyParams & map, std::string & other_part) const inherited
Parse body data which has the form:
   param1=value1
   param2=value2
   The other multistring part of body.
The parameters of the body stored to map and the remaining part to other_part
Definition at line 143 of file crtd_message.cc.
parseRequest()
void Ssl::CrtdMessage::parseRequest (CertificateProperties & certProperties) inherited
Definition at line 179 of file crtd_message.cc.
References Ssl::algSignEnd, Ssl::algSignTrusted, Ssl::certSignAlgorithmId(), Ssl::CertificateProperties::commonName, Here, Ssl::CertificateProperties::mimicCert, Ssl::CrtdMessage::param_host, Ssl::CrtdMessage::param_SetCommonName, Ssl::CrtdMessage::param_SetValidAfter, Ssl::CrtdMessage::param_SetValidBefore, Ssl::CrtdMessage::param_Sign, Ssl::CrtdMessage::param_SignHash, Ssl::readCertAndPrivateKeyFromMemory(), Ssl::ReadCertificate(), Ssl::ReadOnlyBioTiedTo(), Ssl::CertificateProperties::setCommonName, Ssl::CertificateProperties::setValidAfter, Ssl::CertificateProperties::setValidBefore, Ssl::CertificateProperties::signAlgorithm, Ssl::CertificateProperties::signHash, Ssl::CertificateProperties::signWithPkey, Ssl::CertificateProperties::signWithX509, SQUID_SSL_SIGN_HASH_IF_NONE, and ToSBuf().
Referenced by processNewRequest().
parseResponse()
bool Ssl::CertValidationMsg::parseResponse (CertValidationResponse & resp)
Definition at line 93 of file cert_validate_message.cc.
References CurrentException(), DBG_IMPORTANT, debugs, and Debug::Extra().
Referenced by sslCrtvdHandleReplyWrapper().
setBody()
void Ssl::CrtdMessage::setBody (std::string const & aBody) inherited
Definition at line 124 of file crtd_message.cc.
Referenced by processNewRequest().
setCode()
void Ssl::CrtdMessage::setCode (std::string const & aCode) inherited
Definition at line 126 of file crtd_message.cc.
Referenced by ConnStateData::getSslContextStart(), processNewRequest(), and Ssl::CertValidationHelper::Submit().
tryParsingResponse()
void Ssl::CertValidationMsg::tryParsingResponse (CertValidationResponse & resp) private
implements primary parseResponse() functionality until that method callers are ready to handle exceptions
Definition at line 109 of file cert_validate_message.cc.
References debugs, Ssl::CertValidationResponse::RecvdError::error_depth, Ssl::CertValidationResponse::RecvdError::error_no, Ssl::CertValidationResponse::RecvdError::error_reason, Ssl::CertValidationResponse::errors, get_error_id(), Ssl::CertValidationResponse::getError(), Ssl::GetErrorCode(), Here, Ssl::CertValidationMsg::CertItem::name, Ssl::ReadCertificate(), Ssl::ReadOnlyBioTiedTo(), Ssl::CertValidationResponse::RecvdError::setCert(), Ssl::CertValidationMsg::CertItem::setCert(), Ssl::CertValidationResponse::ssl, STACK_OF(), ToSBuf(), and xisspace.
Member Data Documentation
body
std::string Ssl::CrtdMessage::body protected inherited
Definition at line 101 of file crtd_message.h.
Referenced by composeRequest().
body_size
size_t Ssl::CrtdMessage::body_size protected inherited
Definition at line 99 of file crtd_message.h.
code
std::string Ssl::CrtdMessage::code protected inherited
Definition at line 102 of file crtd_message.h.
code_cert_validate
const std::string Ssl::CertValidationMsg::code_cert_validate static
Definition at line 109 of file cert_validate_message.h.
Referenced by Ssl::CertValidationHelper::Submit().
code_new_certificate
const std::string Ssl::CrtdMessage::code_new_certificate static inherited
Definition at line 76 of file crtd_message.h.
Referenced by ConnStateData::getSslContextStart(), main(), and usage().
current_block
std::string Ssl::CrtdMessage::current_block protected inherited
Definition at line 103 of file crtd_message.h.
param_cert
const std::string Ssl::CertValidationMsg::param_cert static
Definition at line 113 of file cert_validate_message.h.
Referenced by composeRequest().
param_cipher
const std::string Ssl::CertValidationMsg::param_cipher static
Definition at line 125 of file cert_validate_message.h.
Referenced by composeRequest().
param_domain
const std::string Ssl::CertValidationMsg::param_domain static
Definition at line 111 of file cert_validate_message.h.
param_error_cert
const std::string Ssl::CertValidationMsg::param_error_cert static
Definition at line 119 of file cert_validate_message.h.
Referenced by composeRequest().
param_error_depth
const std::string Ssl::CertValidationMsg::param_error_depth static
Definition at line 121 of file cert_validate_message.h.
param_error_name
const std::string Ssl::CertValidationMsg::param_error_name static
Definition at line 115 of file cert_validate_message.h.
Referenced by composeRequest().
param_error_reason
const std::string Ssl::CertValidationMsg::param_error_reason static
Definition at line 117 of file cert_validate_message.h.
param_host
const std::string Ssl::CrtdMessage::param_host static inherited
Definition at line 78 of file crtd_message.h.
Referenced by composeRequest(), Ssl::CrtdMessage::composeRequest(), Ssl::CrtdMessage::parseRequest(), and usage().
param_proto_version
const std::string Ssl::CertValidationMsg::param_proto_version static
Definition at line 123 of file cert_validate_message.h.
Referenced by composeRequest().
param_SetCommonName
const std::string Ssl::CrtdMessage::param_SetCommonName static inherited
Definition at line 84 of file crtd_message.h.
Referenced by Ssl::CrtdMessage::composeRequest(), and Ssl::CrtdMessage::parseRequest().
param_SetValidAfter
const std::string Ssl::CrtdMessage::param_SetValidAfter static inherited
Definition at line 80 of file crtd_message.h.
Referenced by Ssl::CrtdMessage::composeRequest(), and Ssl::CrtdMessage::parseRequest().
param_SetValidBefore
const std::string Ssl::CrtdMessage::param_SetValidBefore static inherited
Definition at line 82 of file crtd_message.h.
Referenced by Ssl::CrtdMessage::composeRequest(), and Ssl::CrtdMessage::parseRequest().
param_Sign
const std::string Ssl::CrtdMessage::param_Sign static inherited
Definition at line 86 of file crtd_message.h.
Referenced by Ssl::CrtdMessage::composeRequest(), and Ssl::CrtdMessage::parseRequest().
param_SignHash
const std::string Ssl::CrtdMessage::param_SignHash static inherited
Definition at line 88 of file crtd_message.h.
Referenced by Ssl::CrtdMessage::composeRequest(), and Ssl::CrtdMessage::parseRequest().
state
ParseState Ssl::CrtdMessage::state protected inherited
Definition at line 100 of file crtd_message.h.
The documentation for this class was generated from the following files:
squid/src/ssl/cert_validate_message.h
squid/src/ssl/cert_validate_message.cc