Squid Web Cache: Adaptation::Icap::InOut Class Reference
Adaptation::Icap::InOut Class Reference
#include <InOut.h>
Public Types
typedef Http::Message Header
Public Member Functions
InOut ()
~InOut ()
void setCause (HttpRequest *r)
void setHeader (Header *h)
Public Attributes
Header * header
HttpRequest * cause
BodyPipe::Pointer body_pipe
Detailed Description
Definition at line 24 of file InOut.h.
Member Typedef Documentation
Header
typedef Http::Message Adaptation::Icap::InOut::Header
Definition at line 29 of file InOut.h.
Constructor & Destructor Documentation
InOut()
Adaptation::Icap::InOut::InOut () inline
Definition at line 31 of file InOut.h.
~InOut()
Adaptation::Icap::InOut::~InOut () inline
Definition at line 33 of file InOut.h.
References cause, header, and HTTPMSGUNLOCK().
Member Function Documentation
setCause()
void Adaptation::Icap::InOut::setCause (HttpRequest * r) inline
Definition at line 38 of file InOut.h.
References assert, cause, HTTPMSGLOCK(), and HTTPMSGUNLOCK().
Referenced by Adaptation::Icap::ModXact::ModXact(), and Adaptation::Icap::ModXactLauncher::ModXactLauncher().
setHeader()
void Adaptation::Icap::InOut::setHeader (Header * h) inline
Definition at line 48 of file InOut.h.
References body_pipe, Http::Message::body_pipe, header, HTTPMSGLOCK(), and HTTPMSGUNLOCK().
Referenced by Adaptation::Icap::ModXact::ModXact(), and Adaptation::Icap::ModXactLauncher::ModXactLauncher().
Member Data Documentation
body_pipe
BodyPipe::Pointer Adaptation::Icap::InOut::body_pipe
Definition at line 63 of file InOut.h.
Referenced by setHeader().
cause
HttpRequest* Adaptation::Icap::InOut::cause
Definition at line 60 of file InOut.h.
Referenced by ~InOut(), and setCause().
header
Header* Adaptation::Icap::InOut::header
Definition at line 57 of file InOut.h.
Referenced by ~InOut(), and setHeader().
The documentation for this class was generated from the following file:
squid/src/adaptation/icap/InOut.h