Squid Web Cache: Ipc::RequestId Class Reference
Ipc::RequestId Class Reference
#include <RequestId.h>
Public Types
typedef unsigned int Index
Public Member Functions
RequestId (Index)
RequestId ()=default
request recipient's constructor
void reset ()
void reset (const Index anIndex)
QuestionerId questioner () const
Index index () const
operator Index () const
RequestId & operator= (const Index anIndex)
Private Attributes
QuestionerId qid_
the sender of the request
Index index_ = 0
request ID; unique within pending same-qid_ questions of the same kind
Detailed Description
uniquely identifies an IPC request among same-type concurrent IPC requests submitted by a single Squid instance
Definition at line 22 of file RequestId.h.
Member Typedef Documentation
Index
typedef unsigned int Ipc::RequestId::Index
A simple ID for correlating IPC responses with pending requests. Value 0 has a special meaning of "unset/unknown", but otherwise opaque.
Definition at line 27 of file RequestId.h.
Constructor & Destructor Documentation
RequestId() [1/2]
Ipc::RequestId::RequestId (Index anIndex) explicit
Request sender's constructor. For performance and clarity sake, default constructor is preferred to 0 index.
Definition at line 16 of file RequestId.cc.
References Ipc::MyQuestionerId().
RequestId() [2/2]
Ipc::RequestId::RequestId () default
Referenced by reset().
Member Function Documentation
index()
Index Ipc::RequestId::index () const inline
Definition at line 45 of file RequestId.h.
References index_.
Referenced by Ipc::operator<<(), and Ipc::SharedListenJoined().
operator Index()
Ipc::RequestId::operator Index () const inline
Definition at line 48 of file RequestId.h.
References index_.
operator=()
RequestId & Ipc::RequestId::operator= (const Index anIndex) inline
Definition at line 49 of file RequestId.h.
References reset().
questioner()
QuestionerId Ipc::RequestId::questioner () const inline
Definition at line 44 of file RequestId.h.
References qid_.
Referenced by Ipc::Response::intendedRecepient(), Ipc::SharedListenResponse::intendedRecepient(), and Ipc::operator<<().
reset() [1/2]
void Ipc::RequestId::reset () inline
Make the ID unset/unknown. Optimization: leaves the questioner field alone.
Definition at line 38 of file RequestId.h.
References index_.
Referenced by operator=().
reset() [2/2]
void Ipc::RequestId::reset (const Index anIndex) inline
Make the ID set/known with the given (by the questioner) index. For performance and clarity sake, reset(void) is preferred to reset(0).
Definition at line 42 of file RequestId.h.
References RequestId().
Member Data Documentation
index_
Index Ipc::RequestId::index_ = 0 private
Definition at line 56 of file RequestId.h.
Referenced by index(), operator Index(), and reset().
qid_
QuestionerId Ipc::RequestId::qid_ private
Definition at line 53 of file RequestId.h.
Referenced by questioner().
The documentation for this class was generated from the following files:
squid/src/ipc/RequestId.h
squid/src/ipc/RequestId.cc