Squid Web Cache: MimeIcon Class Reference
MimeIcon Class Reference
Public Member Functions
MimeIcon (const char *aName)
~MimeIcon () override
void setName (char const *)
SBuf getName () const
void load ()
LogTags * loggingTags () const override
void fillChecklist (ACLFilledChecklist &) const override
configure the given checklist (to reflect the current transaction state)
Protected Member Functions
bool startCollapsingOn (const StoreEntry &, const bool doingRevalidation) const
bool mayInitiateCollapsing () const
whether Squid configuration allows us to become a CF initiator
bool onCollapsingPath () const
whether Squid configuration allows collapsing for this transaction
Protected Attributes
bool didCollapse = false
whether startCollapsingOn() was called and returned true
Private Member Functions
MEMPROXY_CLASS (MimeIcon)
Private Attributes
SBuf icon_
char * url_
Detailed Description
Definition at line 42 of file mime.cc.
Constructor & Destructor Documentation
MimeIcon()
MimeIcon::MimeIcon (const char * aName) explicit
Definition at line 125 of file mime.cc.
References setName().
~MimeIcon()
MimeIcon::~MimeIcon () override
Definition at line 131 of file mime.cc.
References url_, and xfree.
Member Function Documentation
fillChecklist()
void MimeIcon::fillChecklist (ACLFilledChecklist &) const override virtual
Implements Acl::ChecklistFiller.
Definition at line 446 of file mime.cc.
References assert.
getName()
SBuf MimeIcon::getName () const
Definition at line 145 of file mime.cc.
References icon_.
Referenced by mimeGetIcon().
load()
void MimeIcon::load ()
Definition at line 356 of file mime.cc.
References StoreEntry::append(), assert, StoreEntry::buffer(), SBuf::c_str(), Http::Message::cache_control, StoreEntry::complete(), Config, DBG_CRITICAL, debugs, SquidConfig::directory, EBIT_SET, ENTRY_SPECIAL, fatal(), fatalf(), FD_READ_METHOD(), file_close(), file_open(), StoreEntry::flags, StoreEntry::flush(), HttpRequest::FromUrlXXX(), RefCount< C >::getRaw(), Http::Message::header, icon_, SquidConfig::icons, StoreEntry::lock(), HttpHdrCc::maxAge(), MAXPATHLEN, StoreEntry::mem_obj, Http::METHOD_GET, mimeGetContentType(), O_BINARY, HttpHeader::putCc(), StoreEntry::replaceHttpReply(), MemObject::request, Http::scNoContent, Http::scOkay, HttpReply::setHeaders(), StoreEntry::setPublicKey(), SQUIDSBUFPH, SQUIDSBUFPRINT, storeCreatePureEntry(), storeGetPublic(), StoreEntry::timestampsSet(), url_, and xstrerr().
Referenced by mimeInit().
loggingTags()
LogTags * MimeIcon::loggingTags () const inline override virtual
Returns
LogTags (if the class logs transactions) or nil (otherwise)
Implements StoreClient.
Definition at line 54 of file mime.cc.
mayInitiateCollapsing()
bool StoreClient::mayInitiateCollapsing () const inline protected inherited
Definition at line 59 of file StoreClient.h.
References StoreClient::onCollapsingPath().
Referenced by clientReplyContext::createStoreEntry(), and clientReplyContext::processExpired().
MEMPROXY_CLASS()
MimeIcon::MEMPROXY_CLASS (MimeIcon) private
onCollapsingPath()
bool StoreClient::onCollapsingPath () const protected inherited
Definition at line 52 of file store_client.cc.
References SquidConfig::accessList, Acl::Answer::allowed(), SquidConfig::collapsed_forwarding, SquidConfig::collapsedForwardingAccess, Config, ACLChecklist::fastCheck(), Acl::ChecklistFiller::fillChecklist(), and SquidConfig::onoff.
Referenced by StoreClient::mayInitiateCollapsing(), and StoreClient::startCollapsingOn().
setName()
void MimeIcon::setName (char const * aString)
Definition at line 137 of file mime.cc.
References icon_, internalLocalUri(), url_, xfree, and xstrdup.
Referenced by MimeIcon().
startCollapsingOn()
bool StoreClient::startCollapsingOn (const StoreEntry & e, const bool doingRevalidation) const protected inherited
Returns
whether the caller must collapse on the given entry Before returning true, updates common collapsing-related stats. See also: StoreEntry::hittingRequiresCollapsing().
Definition at line 66 of file store_client.cc.
References debugs, StoreClient::didCollapse, StoreEntry::hittingRequiresCollapsing(), StoreClient::loggingTags(), and StoreClient::onCollapsingPath().
Referenced by htcpSpecifier::checkHit(), ICPState::confirmAndPrepHit(), clientReplyContext::identifyFoundObject(), clientReplyContext::processExpired(), and UrnState::start().
Member Data Documentation
didCollapse
bool StoreClient::didCollapse = false mutable protected inherited
Definition at line 64 of file StoreClient.h.
Referenced by clientReplyContext::cacheHit(), htcpSpecifier::checkHit(), ICPState::confirmAndPrepHit(), and StoreClient::startCollapsingOn().
icon_
SBuf MimeIcon::icon_ private
Definition at line 58 of file mime.cc.
Referenced by getName(), load(), and setName().
url_
char* MimeIcon::url_ private
Definition at line 59 of file mime.cc.
Referenced by ~MimeIcon(), load(), and setName().
The documentation for this class was generated from the following file:
squid/src/mime.cc