Squid Web Cache: DiskIOStrategy Class Reference
DiskIOStrategy Class Reference abstract
#include <DiskIOStrategy.h>
Public Member Functions
virtual ~DiskIOStrategy ()
virtual bool shedLoad ()=0
virtual int load ()=0
virtual RefCount< DiskFile > newFile (char const *path)=0
virtual void sync ()
virtual bool unlinkdUseful () const =0
virtual void unlinkFile (char const *)=0
virtual int callback ()
virtual void init ()
virtual void statfs (StoreEntry &) const
virtual ConfigOption * getOptionTree () const
Detailed Description
Definition at line 19 of file DiskIOStrategy.h.
Constructor & Destructor Documentation
~DiskIOStrategy()
virtual DiskIOStrategy::~DiskIOStrategy () inline virtual
Definition at line 23 of file DiskIOStrategy.h.
Member Function Documentation
callback()
virtual int DiskIOStrategy::callback () inline virtual
perform any pending callbacks
Reimplemented in DiskdIOStrategy, SingletonIOStrategy, and DiskThreadsIOStrategy.
Definition at line 44 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::callback().
getOptionTree()
virtual ConfigOption * DiskIOStrategy::getOptionTree () const inline virtual
module specific options
Reimplemented in DiskdIOStrategy, and SingletonIOStrategy.
Definition at line 53 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::getOptionTree().
init()
virtual void DiskIOStrategy::init (void) inline virtual
Init per-instance logic
Reimplemented in DiskdIOStrategy, SingletonIOStrategy, and DiskThreadsIOStrategy.
Definition at line 47 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::init().
load()
virtual int DiskIOStrategy::load () pure virtual
What is the current load? 999 = 99.9%
Implemented in BlockingIOStrategy, DiskdIOStrategy, SingletonIOStrategy, DiskThreadsIOStrategy, IpcIoIOStrategy, and MmappedIOStrategy.
Referenced by SingletonIOStrategy::load().
newFile()
virtual RefCount< DiskFile > DiskIOStrategy::newFile (char const * path) pure virtual
Return a handle for performing IO operations
Implemented in BlockingIOStrategy, DiskdIOStrategy, SingletonIOStrategy, DiskThreadsIOStrategy, IpcIoIOStrategy, and MmappedIOStrategy.
Referenced by SingletonIOStrategy::newFile().
shedLoad()
virtual bool DiskIOStrategy::shedLoad () pure virtual
Can the IO Strategy handle more requests ?
Implemented in BlockingIOStrategy, DiskdIOStrategy, SingletonIOStrategy, DiskThreadsIOStrategy, IpcIoIOStrategy, and MmappedIOStrategy.
Referenced by Fs::Ufs::UFSStrategy::shedLoad(), and SingletonIOStrategy::shedLoad().
statfs()
virtual void DiskIOStrategy::statfs (StoreEntry &) const inline virtual
cachemgr output on the IO instance stats
Reimplemented in DiskdIOStrategy, and SingletonIOStrategy.
Definition at line 50 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::statfs().
sync()
virtual void DiskIOStrategy::sync () inline virtual
flush all IO operations
Reimplemented in DiskdIOStrategy, SingletonIOStrategy, and DiskThreadsIOStrategy.
Definition at line 35 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::sync().
unlinkdUseful()
virtual bool DiskIOStrategy::unlinkdUseful () const pure virtual
whether the IO Strategy can use unlinkd
Implemented in BlockingIOStrategy, DiskdIOStrategy, SingletonIOStrategy, DiskThreadsIOStrategy, IpcIoIOStrategy, and MmappedIOStrategy.
Referenced by SingletonIOStrategy::unlinkdUseful().
unlinkFile()
virtual void DiskIOStrategy::unlinkFile (char const *) pure virtual
unlink a file by path
Implemented in BlockingIOStrategy, DiskdIOStrategy, DiskThreadsIOStrategy, IpcIoIOStrategy, MmappedIOStrategy, and SingletonIOStrategy.
Referenced by SingletonIOStrategy::unlinkFile().
The documentation for this class was generated from the following file:
squid/src/DiskIO/DiskIOStrategy.h