Squid Web Cache: TestRandomUuid Class Reference
TestRandomUuid Class Reference
Protected Member Functions
void testUniqueness ()
void testSerialization ()
void testTextRepresentation ()
void testInvalidIds ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestRandomUuid)
CPPUNIT_TEST (testUniqueness)
CPPUNIT_TEST (testSerialization)
CPPUNIT_TEST (testTextRepresentation)
CPPUNIT_TEST (testInvalidIds)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 19 of file testRandomUuid.cc.
Member Function Documentation
CPPUNIT_TEST() [1/4]
TestRandomUuid::CPPUNIT_TEST (testInvalidIds) private
CPPUNIT_TEST() [2/4]
TestRandomUuid::CPPUNIT_TEST (testSerialization) private
CPPUNIT_TEST() [3/4]
TestRandomUuid::CPPUNIT_TEST (testTextRepresentation) private
CPPUNIT_TEST() [4/4]
TestRandomUuid::CPPUNIT_TEST (testUniqueness) private
CPPUNIT_TEST_SUITE()
TestRandomUuid::CPPUNIT_TEST_SUITE (TestRandomUuid) private
CPPUNIT_TEST_SUITE_END()
TestRandomUuid::CPPUNIT_TEST_SUITE_END () private
testInvalidIds()
void TestRandomUuid::testInvalidIds () protected
Definition at line 78 of file testRandomUuid.cc.
References InvalidIds.
testSerialization()
void TestRandomUuid::testSerialization () protected
Definition at line 63 of file testRandomUuid.cc.
References RandomUuid::serialize().
testTextRepresentation()
void TestRandomUuid::testTextRepresentation () protected
Definition at line 70 of file testRandomUuid.cc.
References ExternalIds, and ToSBuf().
testUniqueness()
void TestRandomUuid::testUniqueness () protected
Definition at line 53 of file testRandomUuid.cc.
References ToSBuf().
The documentation for this class was generated from the following file:
squid/src/tests/testRandomUuid.cc