Squid Web Cache: ClassCBucket Class Reference
ClassCBucket Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Public Member Functions
bool individualUsed (unsigned int index) const
unsigned char findHostMapPosition (unsigned char const host) const
bool individualAllocated (unsigned char host) const
unsigned char hostPosition (DelaySpec &rate, unsigned char const host)
void initHostIndex (DelaySpec &rate, unsigned char index, unsigned char host)
void update (DelaySpec const &, int incr)
void stats (StoreEntry *) const
Public Attributes
DelayBucket net
VectorMap< unsigned char, DelayBucket > individuals
Detailed Description
Definition at line 173 of file delay_pools.cc.
Member Function Documentation
findHostMapPosition()
unsigned char ClassCBucket::findHostMapPosition (unsigned char const host) const
Definition at line 334 of file delay_pools.cc.
hostPosition()
unsigned char ClassCBucket::hostPosition (DelaySpec & rate, unsigned char const host)
Definition at line 352 of file delay_pools.cc.
References assert, and Aggregate::rate().
individualAllocated()
bool ClassCBucket::individualAllocated (unsigned char host) const
Definition at line 346 of file delay_pools.cc.
individualUsed()
bool ClassCBucket::individualUsed (unsigned int index) const
Definition at line 340 of file delay_pools.cc.
initHostIndex()
void ClassCBucket::initHostIndex (DelaySpec & rate, unsigned char index, unsigned char host)
Definition at line 367 of file delay_pools.cc.
References assert, and Aggregate::rate().
stats()
void ClassCBucket::stats (StoreEntry * sentry) const
Definition at line 324 of file delay_pools.cc.
References assert, and storeAppendPrintf().
update()
void ClassCBucket::update (DelaySpec const & rate, int incr)
Definition at line 314 of file delay_pools.cc.
References assert, Aggregate::rate(), and DelaySpec::restore_bps.
Member Data Documentation
individuals
VectorMap<unsigned char, DelayBucket> ClassCBucket::individuals
Definition at line 186 of file delay_pools.cc.
net
DelayBucket ClassCBucket::net
Definition at line 185 of file delay_pools.cc.
The documentation for this class was generated from the following file:
squid/src/delay_pools.cc