Squid Web Cache: Snmp::Response Class Reference
Snmp::Response Class Reference
#include <Response.h>
Public Types
typedef RefCount< Response > Pointer
Public Member Functions
Response (Ipc::RequestId)
sender's constructor
Response (const Ipc::TypedMsgHdr &msg)
from recvmsg()
void pack (Ipc::TypedMsgHdr &msg) const override
prepare for sendmsg()
Ipc::Response::Pointer clone () const override
returns a copy of this
QuestionerId intendedRecepient () const
for Mine() tests
Public Attributes
Pdu pdu
SNMP protocol data unit.
RequestId requestId
the ID of the request we are responding to
Detailed Description
Definition at line 23 of file Response.h.
Member Typedef Documentation
Pointer
typedef RefCount<Response> Ipc::Response::Pointer inherited
Definition at line 26 of file Response.h.
Constructor & Destructor Documentation
Response() [1/2]
Snmp::Response::Response (Ipc::RequestId aRequestId) explicit
Definition at line 18 of file Response.cc.
Response() [2/2]
Snmp::Response::Response (const Ipc::TypedMsgHdr & msg) explicit
Definition at line 23 of file Response.cc.
References Ipc::TypedMsgHdr::checkType(), Ipc::TypedMsgHdr::getPod(), and Ipc::mtSnmpResponse.
Member Function Documentation
clone()
Ipc::Response::Pointer Snmp::Response::clone () const override virtual
Implements Ipc::Response.
Definition at line 39 of file Response.cc.
intendedRecepient()
QuestionerId Ipc::Response::intendedRecepient () const inline inherited
Definition at line 33 of file Response.h.
References Ipc::RequestId::questioner(), and Ipc::Response::requestId.
pack()
void Snmp::Response::pack (Ipc::TypedMsgHdr & msg) const override virtual
Implements Ipc::Response.
Definition at line 31 of file Response.cc.
References Ipc::mtSnmpResponse, Ipc::TypedMsgHdr::putPod(), and Ipc::TypedMsgHdr::setType().
Referenced by Ipc::Coordinator::handleSnmpRequest(), and Snmp::SendResponse().
Member Data Documentation
pdu
Pdu Snmp::Response::pdu
Definition at line 33 of file Response.h.
Referenced by Snmp::Inquirer::aggregate(), and Snmp::SendResponse().
requestId
RequestId Ipc::Response::requestId inherited
Definition at line 36 of file Response.h.
Referenced by Ipc::Strand::handleCacheMgrResponse(), Ipc::Inquirer::HandleRemoteAck(), Ipc::Strand::handleSnmpResponse(), and Ipc::Response::intendedRecepient().
The documentation for this class was generated from the following files:
squid/src/snmp/Response.h
squid/src/snmp/Response.cc