Squid Web Cache: Error Class Reference
Error Class Reference
a transaction problem
#include <Error.h>
Public Member Functions
Error ()=default
Error (const err_type c)
support implicit conversions
Error (const err_type c, const ErrorDetailPointer &d)
operator bool () const
void update (const Error &)
if necessary, stores the given error information (if any)
void update (err_type, const ErrorDetailPointer &)
void update (err_type)
void update (const ErrorDetailPointer &detail)
void clear ()
switch to the default "no error information" state
Public Attributes
err_type category = ERR_NONE
primary error classification (or ERR_NONE)
ErrorDetails details
Detailed Description
Definition at line 27 of file Error.h.
Constructor & Destructor Documentation
Error() [1/3]
Error::Error () default
Referenced by clear().
Error() [2/3]
Error::Error (const err_type c) inline
Definition at line 30 of file Error.h.
Error() [3/3]
Error::Error (const err_type c, const ErrorDetailPointer & d) inline
Definition at line 31 of file Error.h.
References update().
Member Function Documentation
clear()
void Error::clear () inline
Definition at line 53 of file Error.h.
References Error().
Referenced by ConnStateData::add(), HttpRequest::clearError(), and HttpRequest::init().
operator bool()
Error::operator bool () const inline explicit
Definition at line 33 of file Error.h.
References category, and ERR_NONE.
update() [1/4]
void Error::update (const Error & recent)
Definition at line 51 of file Error.cc.
References category, details, and update().
Referenced by Error(), ErrorState::BuildHttpReply(), HttpRequest::detailError(), ConnStateData::serveDelayedError(), ConnStateData::terminateAll(), update(), update(), AccessLogEntry::updateError(), ConnStateData::updateError(), and ClientHttpRequest::updateError().
update() [2/4]
void Error::update (const ErrorDetailPointer & detail)
records an additional error detail (if any), leaving category unchanged more convenient and faster alternative to calling update(Error(ERR_NONE, d))
Parameters
detail either nil or a pointer to a new or an already known detail
Definition at line 35 of file Error.cc.
References debugs, details, and ErrorDetail::equals().
update() [3/4]
void Error::update (err_type recentCategory)
if necessary, stores the given error category (if any), leaving details unchanged; the first non-ERR_NONE category wins; more convenient alternative to calling update(Error(c))
Definition at line 17 of file Error.cc.
References category, debugs, ERR_NONE, and errorTypeName().
update() [4/4]
void Error::update (err_type recentCategory, const ErrorDetailPointer & recentDetail)
if necessary, stores the given error information (if any); more convenient and faster alternative to calling update(Error(c, d))
Definition at line 61 of file Error.cc.
References update().
Member Data Documentation
category
err_type Error::category = ERR_NONE
Definition at line 55 of file Error.h.
Referenced by ClientHttpRequest::~ClientHttpRequest(), operator bool(), update(), update(), and Ftp::Server::writeErrorReply().
details
ErrorDetails Error::details
Zero or more details of a single error, in temporal order of discovery without duplicates or nil pointers. The order/timing of update() calls is used to approximate detail discovery time.
Definition at line 60 of file Error.h.
Referenced by update(), update(), and Ftp::Server::writeErrorReply().
The documentation for this class was generated from the following files:
squid/src/error/Error.h
squid/src/error/Error.cc