Squid Web Cache: Ipc::SharedListenResponse Class Reference
Ipc::SharedListenResponse Class Reference
a response to SharedListenRequest
#include <SharedListen.h>
Public Member Functions
SharedListenResponse (int fd, int errNo, RequestId aMapId)
sender's constructor
SharedListenResponse (const TypedMsgHdr &hdrMsg)
from recvmsg()
void pack (TypedMsgHdr &hdrMsg) const
prepare for sendmsg()
QuestionerId intendedRecepient () const
for Mine() tests
Public Attributes
int fd
opened listening socket or -1
int errNo
errno value from comm_open_sharedListen() call
RequestId mapId
to map future response to the requestor's callback
Detailed Description
Definition at line 62 of file SharedListen.h.
Constructor & Destructor Documentation
SharedListenResponse() [1/2]
Ipc::SharedListenResponse::SharedListenResponse (int fd, int errNo, RequestId aMapId)
Definition at line 93 of file SharedListen.cc.
SharedListenResponse() [2/2]
Ipc::SharedListenResponse::SharedListenResponse (const TypedMsgHdr & hdrMsg) explicit
Definition at line 98 of file SharedListen.cc.
References Ipc::TypedMsgHdr::checkType(), fd, Ipc::TypedMsgHdr::getFd(), Ipc::TypedMsgHdr::getPod(), and Ipc::mtSharedListenResponse.
Member Function Documentation
intendedRecepient()
QuestionerId Ipc::SharedListenResponse::intendedRecepient () const inline
Definition at line 70 of file SharedListen.h.
References mapId, and Ipc::RequestId::questioner().
pack()
void Ipc::SharedListenResponse::pack (TypedMsgHdr & hdrMsg) const
Definition at line 108 of file SharedListen.cc.
References Ipc::mtSharedListenResponse, Ipc::TypedMsgHdr::putFd(), Ipc::TypedMsgHdr::putPod(), and Ipc::TypedMsgHdr::setType().
Referenced by Ipc::Coordinator::handleSharedListenRequest().
Member Data Documentation
errNo
int Ipc::SharedListenResponse::errNo
Definition at line 74 of file SharedListen.h.
Referenced by Ipc::SharedListenJoined().
fd
int Ipc::SharedListenResponse::fd
Definition at line 73 of file SharedListen.h.
Referenced by SharedListenResponse(), and Ipc::SharedListenJoined().
mapId
RequestId Ipc::SharedListenResponse::mapId
Definition at line 75 of file SharedListen.h.
Referenced by intendedRecepient(), and Ipc::SharedListenJoined().
The documentation for this class was generated from the following files:
squid/src/ipc/SharedListen.h
squid/src/ipc/SharedListen.cc