Squid Web Cache: DelayedAsyncCalls Class Reference
DelayedAsyncCalls Class Reference
#include <DelayedAsyncCalls.h>
Public Member Functions
~DelayedAsyncCalls ()
void delay (const AsyncCallPointer &)
stores the given call to schedule it at schedule() or destruction time
void schedule ()
schedules and forgets all async calls previously stored by delay()
Private Attributes
AsyncCallList deferredReads
delay()-ed calls waiting to be scheduled, in delay() call order
Detailed Description
a FIFO list of async calls, all to be scheduled in FIFO order (on demand via the schedule() method or automatically at object destruction time)
Definition at line 16 of file DelayedAsyncCalls.h.
Constructor & Destructor Documentation
~DelayedAsyncCalls()
DelayedAsyncCalls::~DelayedAsyncCalls () inline
Definition at line 19 of file DelayedAsyncCalls.h.
References schedule().
Member Function Documentation
delay()
void DelayedAsyncCalls::delay (const AsyncCallPointer & call)
Definition at line 15 of file DelayedAsyncCalls.cc.
References AsyncCallList::add(), debugs, deferredReads, and AsyncCallList::size().
Referenced by CompositePoolNode::delayRead(), and MemObject::delayRead().
schedule()
void DelayedAsyncCalls::schedule ()
Definition at line 22 of file DelayedAsyncCalls.cc.
References deferredReads, AsyncCallList::extract(), and ScheduleCallHere.
Referenced by ~DelayedAsyncCalls(), CompositePoolNode::kickReads(), and MemObject::kickReads().
Member Data Documentation
deferredReads
AsyncCallList DelayedAsyncCalls::deferredReads private
Definition at line 29 of file DelayedAsyncCalls.h.
Referenced by delay(), and schedule().
The documentation for this class was generated from the following files:
squid/src/base/DelayedAsyncCalls.h
squid/src/base/DelayedAsyncCalls.cc