Squid Web Cache: Ssl::GlobalContextStorage Class Reference
Ssl::GlobalContextStorage Class Reference
Class for storing/manipulating LocalContextStorage per local listening address/port.
#include <context_storage.h>
Public Member Functions
GlobalContextStorage ()
~GlobalContextStorage ()
void addLocalStorage (Ip::Address const &address, size_t size_of_store)
Create new SSL context storage for the local listening address/port.
LocalContextStorage * getLocalStorage (Ip::Address const &address)
Return the local storage for the given listening address/port.
void reconfigureStart ()
When reconfigring should be called this method.
Private Member Functions
void reconfigureFinish ()
Called by getLocalStorage method.
Private Attributes
bool reconfiguring
std::map< Ip::Address, size_t > configureStorage
Storage used on configure or reconfigure.
std::map< Ip::Address, LocalContextStorage * > storage
Map for storing all local ip address and their local storages.
Friends
class CertificateStorageAction
Detailed Description
Definition at line 54 of file context_storage.h.
Constructor & Destructor Documentation
GlobalContextStorage()
Ssl::GlobalContextStorage::GlobalContextStorage ()
Definition at line 61 of file context_storage.cc.
References Ssl::CertificateStorageAction::Create().
~GlobalContextStorage()
Ssl::GlobalContextStorage::~GlobalContextStorage ()
Definition at line 67 of file context_storage.cc.
Member Function Documentation
addLocalStorage()
void Ssl::GlobalContextStorage::addLocalStorage (Ip::Address const & address, size_t size_of_store)
Definition at line 74 of file context_storage.cc.
References assert, and reconfiguring.
Referenced by clientHttpConnectionsOpen().
getLocalStorage()
Ssl::LocalContextStorage * Ssl::GlobalContextStorage::getLocalStorage (Ip::Address const & address)
Definition at line 80 of file context_storage.cc.
Referenced by ConnStateData::getTlsContextFromCache(), and ConnStateData::storeTlsContextToCache().
reconfigureFinish()
void Ssl::GlobalContextStorage::reconfigureFinish () private
Definition at line 97 of file context_storage.cc.
References reconfiguring.
reconfigureStart()
void Ssl::GlobalContextStorage::reconfigureStart ()
Definition at line 91 of file context_storage.cc.
References reconfiguring.
Referenced by mainReconfigureStart().
Friends And Related Symbol Documentation
CertificateStorageAction
friend class CertificateStorageAction friend
Definition at line 56 of file context_storage.h.
Member Data Documentation
configureStorage
std::map<Ip::Address, size_t> Ssl::GlobalContextStorage::configureStorage private
Definition at line 71 of file context_storage.h.
reconfiguring
bool Ssl::GlobalContextStorage::reconfiguring private
True if system reconfiguring now.
Definition at line 69 of file context_storage.h.
storage
std::map<Ip::Address, LocalContextStorage *> Ssl::GlobalContextStorage::storage private
Definition at line 73 of file context_storage.h.
Referenced by Ssl::CertificateStorageAction::dump().
The documentation for this class was generated from the following files:
squid/src/ssl/context_storage.h
squid/src/ssl/context_storage.cc
squid/src/tests/stub_libsslsquid.cc