Squid Web Cache: SplayCheck Class Reference
SplayCheck Class Reference
Static Public Member Functions
static void BeginWalk ()
static void VisitVoid (void *const &)
static void VisitNode (intnode *const &)
static void VisitNodeRef (intnode const &)
static void CheckNode (intnode const &)
Static Public Attributes
static int LastValue
static bool ExpectedFail
Detailed Description
Definition at line 50 of file splay.cc.
Member Function Documentation
BeginWalk()
void SplayCheck::BeginWalk () static
Definition at line 67 of file splay.cc.
References LastValue.
Referenced by main().
CheckNode()
void SplayCheck::CheckNode (intnode const & A) static
Definition at line 80 of file splay.cc.
References ExpectedFail, intnode::i, and LastValue.
Referenced by VisitNode(), VisitNodeRef(), and VisitVoid().
VisitNode()
void SplayCheck::VisitNode (intnode *const & a) static
Definition at line 96 of file splay.cc.
References CheckNode().
Referenced by main().
VisitNodeRef()
void SplayCheck::VisitNodeRef (intnode const & a) static
Definition at line 102 of file splay.cc.
References CheckNode().
Referenced by main().
VisitVoid()
void SplayCheck::VisitVoid (void *const & node) static
Definition at line 73 of file splay.cc.
References CheckNode().
Referenced by main().
Member Data Documentation
ExpectedFail
bool SplayCheck::ExpectedFail static
Definition at line 56 of file splay.cc.
Referenced by CheckNode(), and main().
LastValue
int SplayCheck::LastValue static
Definition at line 55 of file splay.cc.
Referenced by BeginWalk(), and CheckNode().
The documentation for this class was generated from the following file:
squid/test-suite/splay.cc