Squid Web Cache: Adaptation::Ecap::XactionRep Class Reference
Adaptation::Ecap::XactionRep Class Reference abstract
#include <XactionRep.h>
Public Types
typedef libecap::shared_ptr< libecap::adapter::Xaction > AdapterXaction
typedef CbcPointer< AsyncJob > Pointer
typedef CbcPointer< BodyConsumer > Pointer
typedef CbcPointer< BodyProducer > Pointer
Public Member Functions
XactionRep (Http::Message *virginHeader, HttpRequest *virginCause, AccessLogEntry::Pointer &alp, const Adaptation::ServicePointer &service)
~XactionRep () override
void master (const AdapterXaction &aMaster)
const libecap::Area option (const libecap::Name &name) const override
void visitEachOption (libecap::NamedValueVisitor &visitor) const override
libecap::Message & virgin () override
const libecap::Message & cause () override
libecap::Message & adapted () override
void useVirgin () override
void useAdapted (const libecap::shared_ptr< libecap::Message > &msg) override
void blockVirgin () override
void adaptationDelayed (const libecap::Delay &) override
void adaptationAborted () override
void resume () override
void vbDiscard () override
void vbMake () override
void vbStopMaking () override
void vbMakeMore () override
libecap::Area vbContent (libecap::size_type offset, libecap::size_type size) override
void vbContentShift (libecap::size_type size) override
void noteAbContentDone (bool atEnd) override
void noteAbContentAvailable () override
void noteMoreBodySpaceAvailable (RefCount< BodyPipe > bp) override
void noteBodyConsumerAborted (RefCount< BodyPipe > bp) override
void noteMoreBodyDataAvailable (RefCount< BodyPipe > bp) override
void noteBodyProductionEnded (RefCount< BodyPipe > bp) override
void noteBodyProducerAborted (RefCount< BodyPipe > bp) override
void noteInitiatorAborted () override
void start () override
called by AsyncStart; do not call directly
bool doneAll () const override
whether positive goal has been reached
void swanSong () override
const char * status () const override
internal cleanup; do not call directly
void initiator (const CbcPointer< Initiator > &i)
sets initiator
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
Service & service ()
Adaptation::Message & answer ()
void sinkVb (const char *reason)
void preserveVb (const char *reason)
void forgetVb (const char *reason)
void moveAbContent ()
void updateHistory (Http::Message *adapted)
void terminateMaster ()
void scheduleStop (const char *reason)
void updateSources (Http::Message *adapted)
const libecap::Area clientIpValue () const
const libecap::Area usernameValue () const
const libecap::Area masterxSharedValue (const libecap::Name &name) const
const libecap::Area metaValue (const libecap::Name &name) const
Return the adaptation meta header value for the given header "name".
void visitEachMetaHeader (libecap::NamedValueVisitor &visitor) const
Return the adaptation meta headers and their values.
void doResume ()
void sendAnswer (const Answer &answer)
void tellQueryAborted (bool final)
void clearInitiator ()
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
void stopConsumingFrom (RefCount< BodyPipe > &)
void stopProducingFor (RefCount< BodyPipe > &, bool atEof)
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
CbcPointer< Initiator > theInitiator
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Types
enum OperationState { opUndecided , opOn , opComplete , opNever }
typedef libecap::shared_ptr< libecap::Message > MessagePtr
Private Member Functions
CBDATA_CHILD (XactionRep)
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
AdapterXaction theMaster
Adaptation::ServicePointer theService
xaction's adaptation service
MessageRep theVirginRep
MessageRep * theCauseRep
MessagePtr theAnswerRep
OperationState makingVb
OperationState proxyingAb
int adaptHistoryId
adaptation history slot reservation
bool vbProductionFinished
bool abProductionFinished
bool abProductionAtEnd
AccessLogEntry::Pointer al
Master transaction AccessLogEntry.
Detailed Description
Definition at line 35 of file XactionRep.h.
Member Typedef Documentation
AdapterXaction
typedef libecap::shared_ptr<libecap::adapter::Xaction> Adaptation::Ecap::XactionRep::AdapterXaction
Definition at line 44 of file XactionRep.h.
MessagePtr
typedef libecap::shared_ptr<libecap::Message> Adaptation::Ecap::XactionRep::MessagePtr private
Definition at line 119 of file XactionRep.h.
Pointer [1/3]
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Pointer [2/3]
typedef CbcPointer<BodyProducer> BodyProducer::Pointer inherited
Definition at line 25 of file BodyPipe.h.
Pointer [3/3]
typedef CbcPointer<BodyConsumer> BodyConsumer::Pointer inherited
Definition at line 45 of file BodyPipe.h.
Member Enumeration Documentation
OperationState
enum Adaptation::Ecap::XactionRep::OperationState private
Enumerator
opUndecided
opOn
opComplete
opNever
Definition at line 122 of file XactionRep.h.
Constructor & Destructor Documentation
XactionRep()
Adaptation::Ecap::XactionRep::XactionRep (Http::Message * virginHeader, HttpRequest * virginCause, AccessLogEntry::Pointer & alp, const Adaptation::ServicePointer & service)
Definition at line 55 of file XactionRep.cc.
References theCauseRep.
~XactionRep()
Adaptation::Ecap::XactionRep::~XactionRep () override
Definition at line 72 of file XactionRep.cc.
References assert.
Member Function Documentation
adaptationAborted()
void Adaptation::Ecap::XactionRep::adaptationAborted () override
Definition at line 627 of file XactionRep.cc.
adaptationDelayed()
void Adaptation::Ecap::XactionRep::adaptationDelayed (const libecap::Delay & d) override
Definition at line 619 of file XactionRep.cc.
References debugs.
adapted()
libecap::Message & Adaptation::Ecap::XactionRep::adapted () override
Definition at line 325 of file XactionRep.cc.
References Must.
answer()
Adaptation::Message & Adaptation::Ecap::XactionRep::answer () protected
Definition at line 332 of file XactionRep.cc.
References Must, and Adaptation::Ecap::MessageRep::raw().
blockVirgin()
void Adaptation::Ecap::XactionRep::blockVirgin () override
Definition at line 451 of file XactionRep.cc.
References Adaptation::Answer::Block(), debugs, Must, and StringToSBuf().
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
cause()
const libecap::Message & Adaptation::Ecap::XactionRep::cause () override
Definition at line 318 of file XactionRep.cc.
References Must.
CBDATA_CHILD()
Adaptation::Ecap::XactionRep::CBDATA_CHILD (XactionRep) private
clearInitiator()
void Adaptation::Initiate::clearInitiator () protected inherited
Definition at line 74 of file Initiate.cc.
clientIpValue()
const libecap::Area Adaptation::Ecap::XactionRep::clientIpValue () const protected
Definition at line 130 of file XactionRep.cc.
References HttpRequest::client_addr, HttpRequest::indirect_client_addr, Ip::Address::isAnyAddr(), Ip::Address::isNoAddr(), MAX_IPSTRLEN, Must, Adaptation::Config::send_client_ip, Adaptation::Ecap::TheConfig, Ip::Address::toStr(), and Adaptation::Config::use_indirect_client.
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Adaptation::Ecap::XactionRep::doneAll () const override virtual
Reimplemented from AsyncJob.
Definition at line 350 of file XactionRep.cc.
References AsyncJob::doneAll().
doResume()
void Adaptation::Ecap::XactionRep::doResume () protected
the guts of libecap::host::Xaction::resume() API implementation which just goes async in Adaptation::Ecap::XactionRep::resume().
Definition at line 305 of file XactionRep.cc.
References Must.
Referenced by resume().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
forgetVb()
void Adaptation::Ecap::XactionRep::forgetVb (const char * reason) protected
Definition at line 388 of file XactionRep.cc.
References debugs, and BodyPipe::stillConsuming().
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
initiator()
void Adaptation::Initiate::initiator (const CbcPointer< Initiator > & i) inherited
Definition at line 54 of file Initiate.cc.
References Must, and CbcPointer< Cbc >::valid().
Referenced by Adaptation::Initiator::initiateAdaptation().
master()
void Adaptation::Ecap::XactionRep::master (const AdapterXaction & aMaster)
Definition at line 80 of file XactionRep.cc.
References Must.
Referenced by Adaptation::Ecap::ServiceRep::makeXactLauncher().
masterxSharedValue()
const libecap::Area Adaptation::Ecap::XactionRep::masterxSharedValue (const libecap::Name & name) const protected
Definition at line 173 of file XactionRep.cc.
References HttpRequest::adaptHistory(), Adaptation::History::getXxRecord(), Must, String::rawBuf(), and String::size().
metaValue()
const libecap::Area Adaptation::Ecap::XactionRep::metaValue (const libecap::Name & name) const protected
Definition at line 190 of file XactionRep.cc.
References Adaptation::Config::metaHeaders(), Must, and SBuf::toStdString().
moveAbContent()
void Adaptation::Ecap::XactionRep::moveAbContent () protected
Definition at line 684 of file XactionRep.cc.
References debugs, and Must.
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteAbContentAvailable()
void Adaptation::Ecap::XactionRep::noteAbContentAvailable () override
Definition at line 601 of file XactionRep.cc.
References Must.
noteAbContentDone()
void Adaptation::Ecap::XactionRep::noteAbContentDone (bool atEnd) override
Definition at line 591 of file XactionRep.cc.
References debugs, and Must.
noteBodyConsumerAborted()
void Adaptation::Ecap::XactionRep::noteBodyConsumerAborted (RefCount< BodyPipe > bp) override virtual
Implements BodyProducer.
Definition at line 641 of file XactionRep.cc.
References Must.
noteBodyProducerAborted()
void Adaptation::Ecap::XactionRep::noteBodyProducerAborted (RefCount< BodyPipe > bp) override virtual
Implements BodyConsumer.
Definition at line 668 of file XactionRep.cc.
References Must.
noteBodyProductionEnded()
void Adaptation::Ecap::XactionRep::noteBodyProductionEnded (RefCount< BodyPipe > bp) override virtual
Implements BodyConsumer.
Definition at line 659 of file XactionRep.cc.
References Must.
noteInitiatorAborted()
void Adaptation::Ecap::XactionRep::noteInitiatorAborted () override virtual
Implements Adaptation::Initiate.
Definition at line 677 of file XactionRep.cc.
noteMoreBodyDataAvailable()
void Adaptation::Ecap::XactionRep::noteMoreBodyDataAvailable (RefCount< BodyPipe > bp) override virtual
Implements BodyConsumer.
Definition at line 651 of file XactionRep.cc.
References Must.
noteMoreBodySpaceAvailable()
void Adaptation::Ecap::XactionRep::noteMoreBodySpaceAvailable (RefCount< BodyPipe > bp) override virtual
Implements BodyProducer.
Definition at line 634 of file XactionRep.cc.
References Must.
option()
const libecap::Area Adaptation::Ecap::XactionRep::option (const libecap::Name & name) const override
Definition at line 95 of file XactionRep.cc.
References Adaptation::Config::masterx_shared_name.
preserveVb()
void Adaptation::Ecap::XactionRep::preserveVb (const char * reason) protected
Definition at line 372 of file XactionRep.cc.
References BodyPipe::consumedSize(), debugs, and Must.
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
resume()
void Adaptation::Ecap::XactionRep::resume () override
Definition at line 293 of file XactionRep.cc.
References asyncCall(), doResume(), and ScheduleCallHere.
scheduleStop()
void Adaptation::Ecap::XactionRep::scheduleStop (const char * reason) protected
sendAnswer()
void Adaptation::Initiate::sendAnswer (const Answer & answer) protected inherited
Definition at line 79 of file Initiate.cc.
References Adaptation::Initiator::noteAdaptationAnswer(), and ScheduleCallHere.
service()
Adaptation::Service & Adaptation::Ecap::XactionRep::service () protected
Definition at line 88 of file XactionRep.cc.
References Must.
sinkVb()
void Adaptation::Ecap::XactionRep::sinkVb (const char * reason) protected
Definition at line 358 of file XactionRep.cc.
References debugs, and BodyPipe::enableAutoConsumption().
start()
void Adaptation::Ecap::XactionRep::start () override virtual
Reimplemented from AsyncJob.
Definition at line 231 of file XactionRep.cc.
References HttpRequest::adaptLogHistory(), NotePairs::add(), current_time, NotePairs::hasPair(), Adaptation::Config::metaHeaders(), Adaptation::History::metaHeaders, Must, and Adaptation::History::recordXactStart().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
status()
const char * Adaptation::Ecap::XactionRep::status () const override virtual
for debugging, starts with space
Reimplemented from AsyncJob.
Definition at line 700 of file XactionRep.cc.
References MemBuf::append(), Packable::appendf(), Adaptation::Message::body_pipe, MemBuf::content(), Must, Adaptation::Ecap::MessageRep::raw(), MemBuf::reset(), BodyPipe::stillConsuming(), BodyPipe::stillProducing(), and MemBuf::terminate().
stopConsumingFrom()
void BodyConsumer::stopConsumingFrom (RefCount< BodyPipe > & p) protected inherited
Definition at line 118 of file BodyPipe.cc.
References assert, and debugs.
Referenced by ClientHttpRequest::~ClientHttpRequest(), Client::checkAdaptationWithBodyCompletion(), Client::cleanAdaptation(), Client::doneSendingRequestBody(), ClientHttpRequest::endRequestSatisfaction(), Client::handleRequestBodyProducerAborted(), BodySink::noteBodyProducerAborted(), ClientHttpRequest::noteBodyProducerAborted(), BodySink::noteBodyProductionEnded(), Client::serverComplete(), and Client::swanSong().
stopProducingFor()
void BodyProducer::stopProducingFor (RefCount< BodyPipe > & p, bool atEof) protected inherited
Definition at line 107 of file BodyPipe.cc.
References assert, and debugs.
Referenced by ConnStateData::~ConnStateData(), Client::cleanAdaptation(), ConnStateData::finishDechunkingRequest(), Client::noteBodyConsumerAborted(), and Client::serverComplete2().
swanSong()
void Adaptation::Ecap::XactionRep::swanSong () override virtual
Reimplemented from AsyncJob.
Definition at line 263 of file XactionRep.cc.
References HttpRequest::adaptLogHistory(), Must, Adaptation::History::recordXactFinish(), BodyPipe::stillConsuming(), BodyPipe::stillProducing(), and Adaptation::Initiate::swanSong().
tellQueryAborted()
void Adaptation::Initiate::tellQueryAborted (bool final) protected inherited
Definition at line 87 of file Initiate.cc.
References Adaptation::Answer::Error().
terminateMaster()
void Adaptation::Ecap::XactionRep::terminateMaster () protected
Definition at line 340 of file XactionRep.cc.
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
updateHistory()
void Adaptation::Ecap::XactionRep::updateHistory (Http::Message * adapted) protected
Called just before sendAnswer() to record adapter meta-information which may affect answer processing and may be needed for logging.
Definition at line 467 of file XactionRep.cc.
References HttpRequest::adaptHistory(), HttpRequest::adaptLogHistory(), hoReply, Adaptation::Config::masterx_shared_name, Must, Adaptation::History::recordMeta(), Adaptation::History::updateNextServices(), and Adaptation::History::updateXxRecord().
updateSources()
void Adaptation::Ecap::XactionRep::updateSources (Http::Message * adapted) protected
Definition at line 743 of file XactionRep.cc.
References HttpRequest::masterXaction, Must, Http::Message::sources, Http::Message::srcEcap, and Http::Message::srcEcaps.
useAdapted()
void Adaptation::Ecap::XactionRep::useAdapted (const libecap::shared_ptr< libecap::Message > & msg) override
Definition at line 421 of file XactionRep.cc.
References Http::Message::body_pipe, debugs, Adaptation::Answer::Forward(), Http::Message::header, Must, and Adaptation::Ecap::MessageRep::tieBody().
usernameValue()
const libecap::Area Adaptation::Ecap::XactionRep::usernameValue () const protected
Definition at line 155 of file XactionRep.cc.
References HttpRequest::auth_user_request, HttpRequest::extacl_user, Must, String::rawBuf(), String::size(), and Auth::UserRequest::username().
useVirgin()
void Adaptation::Ecap::XactionRep::useVirgin () override
Definition at line 403 of file XactionRep.cc.
References Http::Message::body_pipe, debugs, Adaptation::Answer::Forward(), Http::Message::header, and Must.
vbContent()
libecap::Area Adaptation::Ecap::XactionRep::vbContent (libecap::size_type offset, libecap::size_type size) override
Definition at line 553 of file XactionRep.cc.
References BodyPipe::buf(), MemBuf::content(), MemBuf::contentSize(), min(), Must, and size.
vbContentShift()
void Adaptation::Ecap::XactionRep::vbContentShift (libecap::size_type size) override
Definition at line 577 of file XactionRep.cc.
References BodyPipe::buf(), BodyPipe::consume(), MemBuf::contentSize(), min(), Must, and size.
vbDiscard()
void Adaptation::Ecap::XactionRep::vbDiscard () override
Definition at line 515 of file XactionRep.cc.
References Must.
vbMake()
void Adaptation::Ecap::XactionRep::vbMake () override
Definition at line 524 of file XactionRep.cc.
References Must, and BodyPipe::setConsumerIfNotLate().
vbMakeMore()
void Adaptation::Ecap::XactionRep::vbMakeMore () override
Definition at line 543 of file XactionRep.cc.
References BodyPipe::mayNeedMoreData(), Must, BodyPipe::productionEnded(), and BodyPipe::stillConsuming().
vbStopMaking()
void Adaptation::Ecap::XactionRep::vbStopMaking () override
Definition at line 534 of file XactionRep.cc.
References Must.
virgin()
libecap::Message & Adaptation::Ecap::XactionRep::virgin () override
Definition at line 312 of file XactionRep.cc.
visitEachMetaHeader()
void Adaptation::Ecap::XactionRep::visitEachMetaHeader (libecap::NamedValueVisitor & visitor) const protected
Definition at line 213 of file XactionRep.cc.
References Adaptation::Config::metaHeaders(), Must, and SBuf::toStdString().
visitEachOption()
void Adaptation::Ecap::XactionRep::visitEachOption (libecap::NamedValueVisitor & visitor) const override
Definition at line 111 of file XactionRep.cc.
References Adaptation::Config::masterx_shared_name.
Member Data Documentation
abProductionAtEnd
bool Adaptation::Ecap::XactionRep::abProductionAtEnd private
Definition at line 128 of file XactionRep.h.
abProductionFinished
bool Adaptation::Ecap::XactionRep::abProductionFinished private
Definition at line 127 of file XactionRep.h.
adaptHistoryId
int Adaptation::Ecap::XactionRep::adaptHistoryId private
Definition at line 125 of file XactionRep.h.
al
AccessLogEntry::Pointer Adaptation::Ecap::XactionRep::al private
Definition at line 129 of file XactionRep.h.
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
makingVb
OperationState Adaptation::Ecap::XactionRep::makingVb private
Definition at line 123 of file XactionRep.h.
proxyingAb
OperationState Adaptation::Ecap::XactionRep::proxyingAb private
Definition at line 124 of file XactionRep.h.
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
theAnswerRep
MessagePtr Adaptation::Ecap::XactionRep::theAnswerRep private
Definition at line 120 of file XactionRep.h.
theCauseRep
MessageRep* Adaptation::Ecap::XactionRep::theCauseRep private
Definition at line 117 of file XactionRep.h.
Referenced by XactionRep().
theInitiator
CbcPointer<Initiator> Adaptation::Initiate::theInitiator protected inherited
Definition at line 51 of file Initiate.h.
theMaster
AdapterXaction Adaptation::Ecap::XactionRep::theMaster private
Definition at line 113 of file XactionRep.h.
theService
Adaptation::ServicePointer Adaptation::Ecap::XactionRep::theService private
Definition at line 114 of file XactionRep.h.
theVirginRep
MessageRep Adaptation::Ecap::XactionRep::theVirginRep private
Definition at line 116 of file XactionRep.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
vbProductionFinished
bool Adaptation::Ecap::XactionRep::vbProductionFinished private
Definition at line 126 of file XactionRep.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/XactionRep.h
squid/src/adaptation/ecap/XactionRep.cc