Squid Web Cache: Ssl::CertValidationHelper Class Reference
Ssl::CertValidationHelper Class Reference
#include <helper.h>
Public Types
using Answer = CertValidationResponse::Pointer
using Callback = AsyncCallback< Answer >
typedef void CVHCB(void *, Ssl::CertValidationResponse const &)
typedef ClpMap< SBuf, CertValidationResponse::Pointer, CertValidationResponse::MemoryUsedByResponse > CacheType
Static Public Member Functions
static void Init ()
Init helper structure.
static void Shutdown ()
Shutdown helper structure.
static void Reconfigure ()
static void Submit (const Ssl::CertValidationRequest &, const Callback &)
Submit crtd request message to external crtd server.
Static Public Attributes
static CacheType * HelperCache = nullptr
cache for cert validation helper
Static Private Attributes
::Helper::ClientPointer ssl_crt_validator
helper for management of ssl_crtd.
Detailed Description
Definition at line 43 of file helper.h.
Member Typedef Documentation
Answer
using Ssl::CertValidationHelper::Answer = CertValidationResponse::Pointer
Definition at line 46 of file helper.h.
CacheType
typedef ClpMap<SBuf, CertValidationResponse::Pointer, CertValidationResponse::MemoryUsedByResponse> Ssl::CertValidationHelper::CacheType
Definition at line 58 of file helper.h.
Callback
using Ssl::CertValidationHelper::Callback = AsyncCallback<Answer>
Definition at line 47 of file helper.h.
CVHCB
typedef void Ssl::CertValidationHelper::CVHCB(void *, Ssl::CertValidationResponse const &)
Definition at line 49 of file helper.h.
Member Function Documentation
Init()
void Ssl::CertValidationHelper::Init () static
Definition at line 175 of file helper.cc.
References assert, Debug::Extra(), Here, HttpPortList, IPC_STREAM, Helper::Client::Make(), strwordtok(), Ssl::TheConfig, ToSBuf(), wordlistAdd(), xatoi(), xfree, and xstrdup.
Referenced by mainInitialize().
Reconfigure()
void Ssl::CertValidationHelper::Reconfigure () static
Reconfigure helper structure
Definition at line 252 of file helper.cc.
Referenced by mainReconfigureFinish().
Shutdown()
void Ssl::CertValidationHelper::Shutdown () static
Definition at line 236 of file helper.cc.
References helperShutdown(), and wordlistDestroy().
Referenced by SquidShutdown().
Submit()
void Ssl::CertValidationHelper::Submit (const Ssl::CertValidationRequest & request, const Callback & callback) static
Definition at line 303 of file helper.cc.
References AsyncCallback< Answer >::answer(), SBuf::append(), SBuf::assign(), Helper::BrokenHelper, SBuf::c_str(), submitData::callback, Ssl::CertValidationMsg::code_cert_validate, Ssl::CrtdMessage::compose(), Ssl::CertValidationMsg::composeRequest(), debugs, HelperCache, submitData::query, AsyncCallback< Answer >::release(), Ssl::CrtdMessage::REQUEST, ScheduleCallHere, Ssl::CrtdMessage::setCode(), Ssl::CertValidationRequest::ssl, submitData::ssl, and sslCrtvdHandleReplyWrapper().
Referenced by Security::PeerConnector::sslFinalized().
Member Data Documentation
HelperCache
Ssl::CertValidationHelper::CacheType * Ssl::CertValidationHelper::HelperCache = nullptr static
Definition at line 59 of file helper.h.
Referenced by sslCrtvdHandleReplyWrapper(), and Submit().
ssl_crt_validator
Helper::Client::Pointer Ssl::CertValidationHelper::ssl_crt_validator static private
Definition at line 56 of file helper.h.
The documentation for this class was generated from the following files:
squid/src/ssl/helper.h
squid/src/ssl/helper.cc