Squid Web Cache: Ssl::Bio Class Reference
Ssl::Bio Class Reference
BIO source and sink node, handling socket I/O and monitoring SSL state.
#include <bio.h>
Public Member Functions
Bio (const int anFd)
virtual ~Bio ()
virtual int write (const char *buf, int size, BIO *table)
Writes the given data to socket.
virtual int read (char *buf, int size, BIO *table)
Reads data from socket.
virtual void flush (BIO *)
int fd () const
The SSL socket descriptor.
virtual void stateChanged (const SSL *ssl, int where, int ret)
const SBuf & rBufData ()
The buffered input data.
Static Public Member Functions
static BIO * Create (const int fd, Security::Io::Type type)
static void Link (SSL *ssl, BIO *bio)
Tells ssl connection to use BIO and monitor state via stateChanged()
Protected Attributes
const int fd_
the SSL socket we are reading and writing
SBuf rbuf
Used to buffer input data.
Detailed Description
Definition at line 33 of file bio.h.
Constructor & Destructor Documentation
Bio()
Ssl::Bio::Bio (const int anFd) explicit
Definition at line 95 of file bio.cc.
References debugs, and fd_.
~Bio()
Ssl::Bio::~Bio () virtual
Definition at line 100 of file bio.cc.
References debugs.
Member Function Documentation
Create()
BIO * Ssl::Bio::Create (const int fd, Security::Io::Type type) static
Creates a low-level BIO table, creates a high-level Ssl::Bio object for a given socket, and then links the two together via BIO_C_SET_FD.
Definition at line 63 of file bio.cc.
References fd(), squid_bio_create(), squid_bio_ctrl(), squid_bio_destroy(), squid_bio_puts(), squid_bio_read(), squid_bio_write(), and SquidMethods.
Referenced by CreateSession().
fd()
int Ssl::Bio::fd () const inline
Definition at line 49 of file bio.h.
References fd_.
Referenced by Create(), Security::NegotiationHistory::retrieveNegotiatedInfo(), and squid_bio_ctrl().
flush()
virtual void Ssl::Bio::flush (BIO *) inline virtual
Flushes any buffered data to socket. The Ssl::Bio does not buffer any data, so this method has nothing to do
Reimplemented in Ssl::ServerBio.
Definition at line 47 of file bio.h.
Referenced by squid_bio_ctrl().
Link()
void Ssl::Bio::Link (SSL * ssl, BIO * bio) static
Definition at line 89 of file bio.cc.
References squid_ssl_info().
Referenced by CreateSession().
rBufData()
const SBuf & Ssl::Bio::rBufData () inline
Definition at line 61 of file bio.h.
References rbuf.
Referenced by Ssl::PeekingPeerConnector::initialize().
read()
int Ssl::Bio::read (char * buf, int size, BIO * table) virtual
Reimplemented in Ssl::ClientBio, and Ssl::ServerBio.
Definition at line 128 of file bio.cc.
References debugs, default_read_method(), ignoreErrno(), and size.
Referenced by Ssl::ClientBio::read(), Ssl::ServerBio::readAndBuffer(), Ssl::ServerBio::readAndGive(), and squid_bio_read().
stateChanged()
void Ssl::Bio::stateChanged (const SSL * ssl, int where, int ret) virtual
Called by linked SSL connection whenever state changes, an alert appears, or an error occurs. See SSL_set_info_callback().
Called whenever the SSL connection state changes, an alert appears, or an error occurs. See SSL_set_info_callback().
Reimplemented in Ssl::ClientBio, and Ssl::ServerBio.
Definition at line 153 of file bio.cc.
References asHex(), and debugs.
Referenced by Ssl::ClientBio::stateChanged(), and Ssl::ServerBio::stateChanged().
write()
int Ssl::Bio::write (const char * buf, int size, BIO * table) virtual
Reimplemented in Ssl::ClientBio, and Ssl::ServerBio.
Definition at line 105 of file bio.cc.
References debugs, default_write_method(), ignoreErrno(), and size.
Referenced by Ssl::ServerBio::flush(), squid_bio_write(), Ssl::ClientBio::write(), and Ssl::ServerBio::write().
Member Data Documentation
fd_
const int Ssl::Bio::fd_ protected
Definition at line 63 of file bio.h.
Referenced by Bio(), and fd().
rbuf
SBuf Ssl::Bio::rbuf protected
Definition at line 64 of file bio.h.
Referenced by rBufData(), and Ssl::ClientBio::setReadBufData().
The documentation for this class was generated from the following files:
squid/src/ssl/bio.h
squid/src/ssl/bio.cc