Squid Web Cache: Rock::LoadingEntry Class Reference
Rock::LoadingEntry Class Reference
smart StoreEntry-level info pointer (hides anti-padding LoadingParts arrays)
Public Types
enum State {
leEmpty = 0 , leLoading , leLoaded , leCorrupted ,
leIgnored
}
possible store entry states during index rebuild
Public Member Functions
LoadingEntry (const sfileno fileNo, LoadingParts &source)
State state () const
void state (State aState) const
bool anchored () const
void anchored (const bool beAnchored)
Public Attributes
uint64_t & size
payload seen so far
uint32_t & version
DbCellHeader::version to distinguish same-URL chains.
Private Attributes
LoadingFlags & flags
entry flags (see the above accessors) are ours
Detailed Description
Definition at line 111 of file RockRebuild.cc.
Member Enumeration Documentation
State
enum Rock::LoadingEntry::State
Enumerator
leEmpty
leLoading
leLoaded
leCorrupted
leIgnored
Definition at line 120 of file RockRebuild.cc.
Constructor & Destructor Documentation
LoadingEntry()
Rock::LoadingEntry::LoadingEntry (const sfileno fileNo, LoadingParts & source)
Definition at line 200 of file RockRebuild.cc.
Member Function Documentation
anchored() [1/2]
bool Rock::LoadingEntry::anchored () const inline
Definition at line 127 of file RockRebuild.cc.
References Rock::LoadingFlags::anchored, and flags.
Referenced by Rock::Rebuild::addSlotToEntry().
anchored() [2/2]
void Rock::LoadingEntry::anchored (const bool beAnchored) inline
Definition at line 128 of file RockRebuild.cc.
References Rock::LoadingFlags::anchored, and flags.
state() [1/2]
State Rock::LoadingEntry::state () const inline
Definition at line 123 of file RockRebuild.cc.
References flags, and Rock::LoadingFlags::state.
Referenced by Rock::Rebuild::finalizeOrThrow(), Rock::Rebuild::freeBadEntry(), Rock::Rebuild::primeNewEntry(), Rock::Rebuild::startNewEntry(), Rock::Rebuild::useNewSlot(), and Rock::Rebuild::validateOneEntry().
state() [2/2]
void Rock::LoadingEntry::state (State aState) const inline
Definition at line 124 of file RockRebuild.cc.
References flags, and Rock::LoadingFlags::state.
Member Data Documentation
flags
LoadingFlags& Rock::LoadingEntry::flags private
Definition at line 131 of file RockRebuild.cc.
Referenced by anchored(), anchored(), state(), and state().
size
uint64_t& Rock::LoadingEntry::size
Definition at line 116 of file RockRebuild.cc.
Referenced by Rock::Rebuild::addSlotToEntry(), Rock::Rebuild::finalizeOrThrow(), Rock::Rebuild::freeBadEntry(), and Rock::Rebuild::primeNewEntry().
version
uint32_t& Rock::LoadingEntry::version
Definition at line 117 of file RockRebuild.cc.
Referenced by Rock::Rebuild::primeNewEntry().
The documentation for this class was generated from the following file:
squid/src/fs/rock/RockRebuild.cc