Squid Web Cache: AsyncCallT< DialerClass > Class Template Reference
AsyncCallT< DialerClass > Class Template Reference
#include <AsyncCall.h>
Public Types
using Dialer = DialerClass
using Pointer = AsyncCallPointer
Public Member Functions
AsyncCallT (int aDebugSection, int aDebugLevel, const char *aName, const Dialer &aDialer)
AsyncCallT (const AsyncCallT< Dialer > &o)
~AsyncCallT () override
CallDialer * getDialer () override
void make ()
bool cancel (const char *reason)
bool canceled () const
void print (std::ostream &os)
void dequeue (AsyncCall::Pointer &head, AsyncCall::Pointer &prev)
remove us from the queue; we are head unless we are queued after prev
void setNext (AsyncCall::Pointer aNext)
AsyncCall::Pointer & Next ()
Public Attributes
Dialer dialer
const char *const name
CodeContext::Pointer codeContext
what the callee is expected to work on
const int debugSection
const int debugLevel
const InstanceId< AsyncCall > id
Protected Member Functions
bool canFire () override
void fire () override
Protected Attributes
AsyncCall::Pointer theNext
for AsyncCallList and similar lists
Private Member Functions
AsyncCallT & operator= (const AsyncCallT &)
Private Attributes
const char * isCanceled
Detailed Description
template<class DialerClass>
class AsyncCallT< DialerClass >
This template implements an AsyncCall using a specified Dialer class
Definition at line 124 of file AsyncCall.h.
Member Typedef Documentation
Dialer
template<class DialerClass > using AsyncCallT< DialerClass >::Dialer = DialerClass
Definition at line 127 of file AsyncCall.h.
Pointer
using AsyncCall::Pointer = AsyncCallPointer inherited
Definition at line 43 of file AsyncCall.h.
Constructor & Destructor Documentation
AsyncCallT() [1/2]
template<class DialerClass > AsyncCallT< DialerClass >::AsyncCallT (int aDebugSection, int aDebugLevel, const char * aName, const Dialer & aDialer) inline
Definition at line 129 of file AsyncCall.h.
AsyncCallT() [2/2]
template<class DialerClass > AsyncCallT< DialerClass >::AsyncCallT (const AsyncCallT< Dialer > & o) inline
Definition at line 133 of file AsyncCall.h.
~AsyncCallT()
template<class DialerClass > AsyncCallT< DialerClass >::~AsyncCallT () inline override
Definition at line 137 of file AsyncCall.h.
Member Function Documentation
cancel()
bool AsyncCall::cancel (const char * reason) inherited
Definition at line 56 of file AsyncCall.cc.
References AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncCall::isCanceled, and AsyncCall::name.
Referenced by AsyncJob::canBeCalled(), JobWaitBase::cancel(), JobDialer< Job >::canDial(), EventDialer::canDial(), BodyProducerDialer::canDial(), BodyConsumerDialer::canDial(), comm_remove_close_handler(), comm_remove_close_handler(), HappyOrderEnforcer::dequeue(), Comm::ReadCancel(), storeUnregister(), and StoreEntry::unregisterAbortCallback().
canceled()
bool AsyncCall::canceled () const inline inherited
Definition at line 53 of file AsyncCall.h.
References AsyncCall::isCanceled.
Referenced by commCallCloseHandlers().
canFire()
template<class DialerClass > bool AsyncCallT< DialerClass >::canFire () inline override protected virtual
Reimplemented from AsyncCall.
Definition at line 144 of file AsyncCall.h.
References AsyncCall::canFire(), and AsyncCallT< DialerClass >::dialer.
dequeue()
void AsyncCall::dequeue (AsyncCall::Pointer & head, AsyncCall::Pointer & prev) inherited
Definition at line 84 of file AsyncCall.cc.
References head, AsyncCall::Next(), and AsyncCall::setNext().
Referenced by comm_remove_close_handler(), and comm_remove_close_handler().
fire()
template<class DialerClass > void AsyncCallT< DialerClass >::fire () inline override protected virtual
Implements AsyncCall.
Definition at line 148 of file AsyncCall.h.
References AsyncCallT< DialerClass >::dialer.
Referenced by Adaptation::AnswerCall::fire().
getDialer()
template<class DialerClass > CallDialer * AsyncCallT< DialerClass >::getDialer () inline override virtual
Implements AsyncCall.
Definition at line 139 of file AsyncCall.h.
References AsyncCallT< DialerClass >::dialer.
make()
void AsyncCall::make () inherited
Definition at line 39 of file AsyncCall.cc.
References AsyncCall::canFire(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncCall::fire(), AsyncCall::isCanceled, and AsyncCall::name.
Next()
AsyncCall::Pointer & AsyncCall::Next () inline inherited
Definition at line 66 of file AsyncCall.h.
References AsyncCall::theNext.
Referenced by AsyncCallList::add(), comm_remove_close_handler(), comm_remove_close_handler(), commCallCloseHandlers(), AsyncCall::dequeue(), and AsyncCallList::extract().
operator=()
template<class DialerClass > AsyncCallT & AsyncCallT< DialerClass >::operator= (const AsyncCallT< DialerClass > &) private
print()
void AsyncCall::print (std::ostream & os) inherited
Definition at line 74 of file AsyncCall.cc.
References AsyncCall::getDialer(), and AsyncCall::name.
Referenced by operator<<().
setNext()
void AsyncCall::setNext (AsyncCall::Pointer aNext) inline inherited
Definition at line 62 of file AsyncCall.h.
References AsyncCall::theNext.
Referenced by AsyncCallList::add(), comm_add_close_handler(), commCallCloseHandlers(), AsyncCall::dequeue(), and AsyncCallList::extract().
Member Data Documentation
codeContext
CodeContext::Pointer AsyncCall::codeContext inherited
Definition at line 74 of file AsyncCall.h.
Referenced by CallSubscription< Call_ >::callback(), and ScheduleCall().
debugLevel
const int AsyncCall::debugLevel inherited
Definition at line 77 of file AsyncCall.h.
Referenced by AsyncCall::AsyncCall(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncCall::cancel(), JobWaitBase::cancel(), BodyProducerDialer::canDial(), BodyConsumerDialer::canDial(), AsyncCall::make(), and ScheduleCall().
debugSection
const int AsyncCall::debugSection inherited
Definition at line 76 of file AsyncCall.h.
Referenced by AsyncCall::AsyncCall(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncCall::cancel(), JobWaitBase::cancel(), BodyProducerDialer::canDial(), BodyConsumerDialer::canDial(), JobDialer< Job >::dial(), AsyncCall::make(), and ScheduleCall().
dialer
template<class DialerClass > Dialer AsyncCallT< DialerClass >::dialer
Definition at line 141 of file AsyncCall.h.
Referenced by AsyncCallT< DialerClass >::canFire(), AsyncCallT< DialerClass >::fire(), and AsyncCallT< DialerClass >::getDialer().
id
const InstanceId<AsyncCall> AsyncCall::id inherited
Definition at line 78 of file AsyncCall.h.
Referenced by JobWaitBase::print(), and ScheduleCall().
isCanceled
const char* AsyncCall::isCanceled private inherited
Definition at line 88 of file AsyncCall.h.
Referenced by AsyncCall::cancel(), AsyncCall::canceled(), AsyncCall::canFire(), and AsyncCall::make().
name
const char* const AsyncCall::name inherited
Definition at line 71 of file AsyncCall.h.
Referenced by AsyncCall::AsyncCall(), AsyncCall::cancel(), JobDialer< Job >::dial(), AsyncCall::make(), and AsyncCall::print().
theNext
AsyncCall::Pointer AsyncCall::theNext protected inherited
Definition at line 85 of file AsyncCall.h.
Referenced by AsyncCall::~AsyncCall(), AsyncCall::Next(), and AsyncCall::setNext().
The documentation for this class was generated from the following file:
squid/src/base/AsyncCall.h