Squid Web Cache: Adaptation::Icap::History Class Reference
Adaptation::Icap::History Class Reference
collects information about ICAP processing related to an HTTP transaction
#include <History.h>
Public Types
typedef RefCount< History > Pointer
Public Member Functions
History ()
void start (const char *context)
record the start of an ICAP processing interval
void stop (const char *context)
note the end of an ICAP processing interval
void processingTime (struct timeval &total) const
Public Attributes
String ssluser
the username from SSL
LogTags logType
the squid request status (TCP_MISS etc)
String log_uri
the request uri
size_t req_sz
the request size
Private Member Functions
void currentTime (struct timeval &) const
time since current start or zero
Private Attributes
timeval currentStart
when the current processing interval started
struct timeval pastTime
sum of closed processing interval durations
int concurrencyLevel
number of concurrent processing threads
Detailed Description
Definition at line 23 of file History.h.
Member Typedef Documentation
Pointer
typedef RefCount<History> Adaptation::Icap::History::Pointer
Definition at line 26 of file History.h.
Constructor & Destructor Documentation
History()
Adaptation::Icap::History::History ()
Definition at line 15 of file History.cc.
References currentStart, and pastTime.
Member Function Documentation
currentTime()
void Adaptation::Icap::History::currentTime (struct timeval & current) const private
Definition at line 57 of file History.cc.
References current_time, and tvSub().
processingTime()
void Adaptation::Icap::History::processingTime (struct timeval & total) const
the total time of all ICAP processing intervals
Parameters
[out] total time taken for all ICAP processing
Definition at line 49 of file History.cc.
References debugs, tvAssignAdd(), and tvToMsec().
start()
void Adaptation::Icap::History::start (const char * context)
Definition at line 23 of file History.cc.
References current_time, debugs, and tvToMsec().
Referenced by Adaptation::Icap::ModXactLauncher::updateHistory().
stop()
void Adaptation::Icap::History::stop (const char * context)
Definition at line 32 of file History.cc.
References DBG_IMPORTANT, debugs, tvAssignAdd(), and tvToMsec().
Referenced by Adaptation::Icap::ModXactLauncher::updateHistory().
Member Data Documentation
concurrencyLevel
int Adaptation::Icap::History::concurrencyLevel private
Definition at line 52 of file History.h.
currentStart
timeval Adaptation::Icap::History::currentStart private
Definition at line 50 of file History.h.
Referenced by History().
log_uri
String Adaptation::Icap::History::log_uri
Definition at line 44 of file History.h.
Referenced by Adaptation::Icap::ModXact::finalizeLogInfo().
logType
LogTags Adaptation::Icap::History::logType
Definition at line 42 of file History.h.
Referenced by Adaptation::Icap::ModXact::finalizeLogInfo().
pastTime
struct timeval Adaptation::Icap::History::pastTime private
Definition at line 51 of file History.h.
Referenced by History().
req_sz
size_t Adaptation::Icap::History::req_sz
Definition at line 45 of file History.h.
ssluser
String Adaptation::Icap::History::ssluser
Definition at line 40 of file History.h.
Referenced by Adaptation::Icap::ModXact::finalizeLogInfo().
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/History.h
squid/src/adaptation/icap/History.cc
squid/src/tests/stub_adaptation_History.cc