Squid Web Cache: Adaptation::Icap::Launcher Class Reference
Adaptation::Icap::Launcher Class Reference abstract
#include <Launcher.h>
Public Types
typedef CbcPointer< AsyncJob > Pointer
Public Member Functions
Launcher (const char *aTypeName, Adaptation::ServicePointer &aService)
~Launcher () override
void noteInitiatorAborted () override
void noteAdaptationAnswer (const Answer &answer) override
virtual void noteXactAbort (XactAbortInfo info)
void initiator (const CbcPointer< Initiator > &i)
sets initiator
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
virtual void noteAdaptationAclCheckDone (Adaptation::ServiceGroupPointer group)
Static Public Member Functions
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void start () override
called by AsyncStart; do not call directly
bool doneAll () const override
whether positive goal has been reached
void swanSong () override
virtual Xaction * createXaction ()=0
void launchXaction (const char *xkind)
void sendAnswer (const Answer &answer)
void tellQueryAborted (bool final)
void clearInitiator ()
const char * status () const override
internal cleanup; do not call directly
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
CbcPointer< Initiate > initiateAdaptation (Initiate *x)
< starts freshly created initiate and returns a safe pointer to it
void clearAdaptation (CbcPointer< Initiate > &x)
clears the pointer (does not call announceInitiatorAbort)
void announceInitiatorAbort (CbcPointer< Initiate > &x)
inform the transaction about abnormal termination and clear the pointer
bool initiated (const CbcPointer< AsyncJob > &job) const
Must(initiated(initiate)) instead of Must(initiate.set()), for clarity.
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
Adaptation::ServicePointer theService
ICAP service for all launches.
CbcPointer< Initiate > theXaction
current ICAP transaction
int theLaunches
CbcPointer< Initiator > theInitiator
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
bool canRetry (XactAbortInfo &info) const
bool canRepeat (XactAbortInfo &info) const
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Detailed Description
Definition at line 47 of file Launcher.h.
Member Typedef Documentation
Pointer
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Constructor & Destructor Documentation
Launcher()
Adaptation::Icap::Launcher::Launcher (const char * aTypeName, Adaptation::ServicePointer & aService)
Definition at line 22 of file Launcher.cc.
~Launcher()
Adaptation::Icap::Launcher::~Launcher () override
Definition at line 30 of file Launcher.cc.
References assert.
Member Function Documentation
announceInitiatorAbort()
void Adaptation::Initiator::announceInitiatorAbort (CbcPointer< Initiate > & x) protected inherited
Definition at line 38 of file Initiator.cc.
References CallJobHere.
Referenced by ClientHttpRequest::~ClientHttpRequest(), and Client::cleanAdaptation().
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
canRepeat()
bool Adaptation::Icap::Launcher::canRepeat (XactAbortInfo & info) const private
Definition at line 123 of file Launcher.cc.
References Acl::Answer::allowed(), debugs, ACLChecklist::fastCheck(), Adaptation::Icap::XactAbortInfo::icapReply, Adaptation::Icap::XactAbortInfo::icapRequest, Adaptation::Icap::XactAbortInfo::isRepeatable, Adaptation::Icap::Config::repeat, Adaptation::Icap::Config::repeat_limit, Http::scNone, shutting_down, HttpReply::sline, Http::StatusLine::status(), Adaptation::Icap::TheConfig, and ACLFilledChecklist::updateReply().
canRetry()
bool Adaptation::Icap::Launcher::canRetry (XactAbortInfo & info) const private
Definition at line 116 of file Launcher.cc.
References Adaptation::Icap::XactAbortInfo::isRetriable, and shutting_down.
clearAdaptation()
void Adaptation::Initiator::clearAdaptation (CbcPointer< Initiate > & x) protected inherited
Definition at line 32 of file Initiator.cc.
References CbcPointer< Cbc >::clear().
Referenced by ClientHttpRequest::handleAdaptedHeader(), ClientHttpRequest::noteAdaptationAnswer(), and Client::noteAdaptationAnswer().
clearInitiator()
void Adaptation::Initiate::clearInitiator () protected inherited
Definition at line 74 of file Initiate.cc.
createXaction()
virtual Xaction * Adaptation::Icap::Launcher::createXaction () protected pure virtual
Implemented in Adaptation::Icap::ModXactLauncher, and Adaptation::Icap::OptXactLauncher.
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Adaptation::Icap::Launcher::doneAll () const override protected virtual
Reimplemented from AsyncJob.
Definition at line 100 of file Launcher.cc.
References AsyncJob::doneAll().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
initiateAdaptation()
CbcPointer< Adaptation::Initiate > Adaptation::Initiator::initiateAdaptation (Initiate * x) protected inherited
Definition at line 23 of file Initiator.cc.
References Adaptation::Initiate::initiator().
Referenced by ClientHttpRequest::startAdaptation(), and Client::startAdaptation().
initiated()
bool Adaptation::Initiator::initiated (const CbcPointer< AsyncJob > & job) const inline protected inherited
Definition at line 52 of file Initiator.h.
References CbcPointer< Cbc >::set().
Referenced by ClientHttpRequest::startAdaptation(), and Client::startAdaptation().
initiator()
void Adaptation::Initiate::initiator (const CbcPointer< Initiator > & i) inherited
Definition at line 54 of file Initiate.cc.
References Must, and CbcPointer< Cbc >::valid().
Referenced by Adaptation::Initiator::initiateAdaptation().
launchXaction()
void Adaptation::Icap::Launcher::launchXaction (const char * xkind) protected
Definition at line 43 of file Launcher.cc.
References Adaptation::Icap::Xaction::attempts, Adaptation::Icap::Xaction::clearError(), debugs, Adaptation::Icap::Xaction::disableRepeats(), Adaptation::Icap::Xaction::disableRetries(), Must, Adaptation::Icap::Config::repeat_limit, and Adaptation::Icap::TheConfig.
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteAdaptationAclCheckDone()
void Adaptation::Initiator::noteAdaptationAclCheckDone (Adaptation::ServiceGroupPointer group) virtual inherited
AccessCheck calls this back with a possibly nil service group to signal whether adaptation is needed and where it should start.
Reimplemented in Client, and ClientHttpRequest.
Definition at line 17 of file Initiator.cc.
References Must.
noteAdaptationAnswer()
void Adaptation::Icap::Launcher::noteAdaptationAnswer (const Answer & answer) override virtual
called with the initial adaptation decision (adapt, block, error); virgin and/or adapted body transmission may continue after this
Implements Adaptation::Initiator.
Definition at line 60 of file Launcher.cc.
References Adaptation::Answer::akError, debugs, Adaptation::Answer::kind, and Must.
noteInitiatorAborted()
void Adaptation::Icap::Launcher::noteInitiatorAborted () override virtual
Implements Adaptation::Initiate.
Definition at line 72 of file Launcher.cc.
References Must.
noteXactAbort()
void Adaptation::Icap::Launcher::noteXactAbort (XactAbortInfo info) virtual
Definition at line 81 of file Launcher.cc.
References debugs, and Must.
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
sendAnswer()
void Adaptation::Initiate::sendAnswer (const Answer & answer) protected inherited
Definition at line 79 of file Initiate.cc.
References Adaptation::Initiator::noteAdaptationAnswer(), and ScheduleCallHere.
start()
void Adaptation::Icap::Launcher::start () override protected virtual
Reimplemented from AsyncJob.
Definition at line 35 of file Launcher.cc.
References Must, and AsyncJob::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
status()
const char * Adaptation::Initiate::status () const override protected virtual inherited
for debugging, starts with space
Reimplemented from AsyncJob.
Definition at line 92 of file Initiate.cc.
References AsyncJob::status().
swanSong()
void Adaptation::Icap::Launcher::swanSong () override protected virtual
Reimplemented from AsyncJob.
Reimplemented in Adaptation::Icap::ModXactLauncher.
Definition at line 105 of file Launcher.cc.
References Adaptation::Initiate::swanSong().
Referenced by Adaptation::Icap::ModXactLauncher::swanSong().
tellQueryAborted()
void Adaptation::Initiate::tellQueryAborted (bool final) protected inherited
Definition at line 87 of file Initiate.cc.
References Adaptation::Answer::Error().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
Member Data Documentation
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
theInitiator
CbcPointer<Initiator> Adaptation::Initiate::theInitiator protected inherited
Definition at line 51 of file Initiate.h.
theLaunches
int Adaptation::Icap::Launcher::theLaunches protected
Definition at line 77 of file Launcher.h.
theService
Adaptation::ServicePointer Adaptation::Icap::Launcher::theService protected
Definition at line 75 of file Launcher.h.
theXaction
CbcPointer<Initiate> Adaptation::Icap::Launcher::theXaction protected
Definition at line 76 of file Launcher.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/Launcher.h
squid/src/adaptation/icap/Launcher.cc