Squid Web Cache: Adaptation::Ecap::FirstLineRep Class Reference
Adaptation::Ecap::FirstLineRep Class Reference
#include <MessageRep.h>
Public Types
typedef libecap::Name Name
Public Member Functions
FirstLineRep (Http::Message &aMessage)
libecap::Version version () const
void version (const libecap::Version &aVersion)
Name protocol () const
void protocol (const Name &aProtocol)
Static Protected Member Functions
static AnyP::ProtocolType TranslateProtocolId (const Name &name)
Private Attributes
Http::Message & theMessage
Detailed Description
Definition at line 66 of file MessageRep.h.
Member Typedef Documentation
Name
typedef libecap::Name Adaptation::Ecap::FirstLineRep::Name
Definition at line 69 of file MessageRep.h.
Constructor & Destructor Documentation
FirstLineRep()
Adaptation::Ecap::FirstLineRep::FirstLineRep (Http::Message & aMessage)
Definition at line 119 of file MessageRep.cc.
Member Function Documentation
protocol() [1/2]
libecap::Name Adaptation::Ecap::FirstLineRep::protocol () const
Definition at line 138 of file MessageRep.cc.
References Must, AnyP::PROTO_AUTHORITY_FORM, AnyP::PROTO_COAP, AnyP::PROTO_COAPS, AnyP::PROTO_FTP, AnyP::PROTO_HTCP, AnyP::PROTO_HTTP, AnyP::PROTO_HTTPS, AnyP::PROTO_ICP, AnyP::PROTO_ICY, AnyP::PROTO_MAX, AnyP::PROTO_NONE, AnyP::PROTO_SSL, AnyP::PROTO_TLS, AnyP::PROTO_UNKNOWN, AnyP::PROTO_URN, AnyP::PROTO_WAIS, AnyP::PROTO_WHOIS, Adaptation::Ecap::protocolHtcp, Adaptation::Ecap::protocolIcp, Adaptation::Ecap::protocolIcy, and Adaptation::Ecap::protocolUnknown.
Referenced by Adaptation::Ecap::RequestLineRep::protocol(), Adaptation::Ecap::StatusLineRep::protocol(), Adaptation::Ecap::RequestLineRep::protocol(), and Adaptation::Ecap::StatusLineRep::protocol().
protocol() [2/2]
void Adaptation::Ecap::FirstLineRep::protocol (const Name & aProtocol)
Definition at line 182 of file MessageRep.cc.
TranslateProtocolId()
AnyP::ProtocolType Adaptation::Ecap::FirstLineRep::TranslateProtocolId (const Name & name) static protected
Definition at line 189 of file MessageRep.cc.
References AnyP::PROTO_UNKNOWN.
version() [1/2]
libecap::Version Adaptation::Ecap::FirstLineRep::version () const
Definition at line 124 of file MessageRep.cc.
Referenced by Adaptation::Ecap::RequestLineRep::version(), Adaptation::Ecap::StatusLineRep::version(), Adaptation::Ecap::RequestLineRep::version(), and Adaptation::Ecap::StatusLineRep::version().
version() [2/2]
void Adaptation::Ecap::FirstLineRep::version (const libecap::Version & aVersion)
Definition at line 131 of file MessageRep.cc.
Member Data Documentation
theMessage
Http::Message& Adaptation::Ecap::FirstLineRep::theMessage private
Definition at line 83 of file MessageRep.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/MessageRep.h
squid/src/adaptation/ecap/MessageRep.cc