Squid Web Cache: IpcIoRr Class Reference
IpcIoRr Class Reference
Public Types
typedef void(RegisteredRunner::* Method) ()
a pointer to one of the above notification methods
Public Member Functions
IpcIoRr ()
~IpcIoRr () override
void claimMemoryNeeds () override
void useConfig () override
virtual void bootstrapConfig ()
virtual void finalizeConfig ()
virtual void startReconfigure ()
virtual void syncConfig ()
virtual void startShutdown ()
virtual void endingShutdown ()
virtual void finishShutdown ()
Meant for cleanup of services needed by the already destroyed objects.
Protected Member Functions
void create () override
called when the runner should create a new memory segment
virtual void open ()
Private Attributes
Ipc::FewToFewBiQueue::Owner * owner
Detailed Description
reports our needs for shared memory pages to Ipc::Mem::Pages and initializes shared memory segments used by IpcIoFile
Definition at line 1013 of file IpcIoFile.cc.
Member Typedef Documentation
Method
typedef void(RegisteredRunner::* RegisteredRunner::Method) () inherited
Definition at line 94 of file RunnersRegistry.h.
Constructor & Destructor Documentation
IpcIoRr()
IpcIoRr::IpcIoRr () inline
Definition at line 1017 of file IpcIoFile.cc.
~IpcIoRr()
IpcIoRr::~IpcIoRr () override
Definition at line 1057 of file IpcIoFile.cc.
References owner.
Member Function Documentation
bootstrapConfig()
virtual void RegisteredRunner::bootstrapConfig () inline virtual inherited
Called right before parsing squid.conf. Meant for initializing/preparing configuration parsing facilities.
Reimplemented in NtlmAuthRr.
Definition at line 46 of file RunnersRegistry.h.
Referenced by SquidMain().
claimMemoryNeeds()
void IpcIoRr::claimMemoryNeeds () override virtual
Called after finalizeConfig(). Meant for announcing memory reservations before memory is allocated.
Reimplemented from RegisteredRunner.
Definition at line 1032 of file IpcIoFile.cc.
References Config, Ipc::Mem::PageId::ioPage, Ipc::FewToFewBiQueue::MaxItemsCount(), Ipc::Mem::NotePageNeed(), and QueueCapacity.
create()
void IpcIoRr::create () override protected virtual
Implements Ipc::Mem::RegisteredRunner.
Definition at line 1045 of file IpcIoFile.cc.
References SquidConfig::cacheSwap, Config, Ipc::FewToFewBiQueue::Init(), Must, Store::DiskConfig::n_strands, owner, QueueCapacity, ShmLabel, and SquidConfig::workers.
endingShutdown()
virtual void RegisteredRunner::endingShutdown () inline virtual inherited
Called after shutdown_lifetime grace period ends and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented in Auth::CredentialCacheRr, ConnStateData, Dns::ConfigRr, and IdleConnList.
Definition at line 84 of file RunnersRegistry.h.
Referenced by SignalEngine::FinalShutdownRunners().
finalizeConfig()
virtual void RegisteredRunner::finalizeConfig () inline virtual inherited
Called after parsing squid.conf. Meant for setting configuration options that depend on other configuration options and were not explicitly configured.
Reimplemented in sslBumpCfgRr, MemStoreRr, and SnmpRr.
Definition at line 51 of file RunnersRegistry.h.
Referenced by SquidMain().
finishShutdown()
virtual void RegisteredRunner::finishShutdown () inline virtual inherited
Definition at line 91 of file RunnersRegistry.h.
Referenced by RunRegistered(), SquidShutdown(), TestRock::tearDown(), and watch_child().
open()
virtual void Ipc::Mem::RegisteredRunner::open () inline protected virtual inherited
called when the runner should open a previously created segment, not needed if segments are opened in constructor or init methods
Reimplemented in CollapsedForwardingRr, and SharedMemPagesRr.
Definition at line 95 of file Segment.h.
startReconfigure()
virtual void RegisteredRunner::startReconfigure () inline virtual inherited
Called after receiving a reconfigure request and before parsing squid.conf. Meant for modules that need to prepare for their configuration being changed [outside their control]. The changes end with the syncConfig() event.
Reimplemented in Dns::ConfigRr, HtcpRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 67 of file RunnersRegistry.h.
Referenced by mainReconfigureStart().
startShutdown()
virtual void RegisteredRunner::startShutdown () inline virtual inherited
Called after receiving a shutdown request and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented in ConnStateData, Rock::Rebuild, HtcpRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 78 of file RunnersRegistry.h.
Referenced by SignalEngine::doShutdown().
syncConfig()
virtual void RegisteredRunner::syncConfig () inline virtual inherited
Called after parsing squid.conf during reconfiguration. Meant for adjusting the module state based on configuration changes.
Reimplemented in Auth::CredentialCacheRr, CarpRr, HtcpRr, PeerSourceHashRr, PeerUserHashRr, PeerPoolMgrsRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 71 of file RunnersRegistry.h.
Referenced by mainReconfigureFinish().
useConfig()
void RegisteredRunner::useConfig () override virtual inherited
Called after claimMemoryNeeds(). Meant for activating modules and features using a finalized configuration with known memory requirements.
Reimplemented from RegisteredRunner.
Reimplemented in SharedMemPagesRr, MemStoreRr, SharedSessionCacheRr, and TransientsRr.
Definition at line 375 of file Segment.cc.
References IamMasterProcess(), IamWorkerProcess(), and InDaemonMode().
Referenced by TestRock::setUp(), SharedMemPagesRr::useConfig(), MemStoreRr::useConfig(), SharedSessionCacheRr::useConfig(), and TransientsRr::useConfig().
Member Data Documentation
owner
Ipc::FewToFewBiQueue::Owner* IpcIoRr::owner private
Definition at line 1026 of file IpcIoFile.cc.
Referenced by ~IpcIoRr(), and create().
The documentation for this class was generated from the following file:
squid/src/DiskIO/IpcIo/IpcIoFile.cc