Squid Web Cache: AsyncCallQueue Class Reference
AsyncCallQueue Class Reference
#include <AsyncCallQueue.h>
Public Member Functions
void schedule (const AsyncCallPointer &call)
bool fire ()
Static Public Member Functions
static AsyncCallQueue & Instance ()
Private Member Functions
AsyncCallQueue ()=default
Private Attributes
AsyncCallList scheduled
calls waiting to be fire()d, in FIFO order
Static Private Attributes
static AsyncCallQueue * TheInstance = nullptr
Detailed Description
Definition at line 17 of file AsyncCallQueue.h.
Constructor & Destructor Documentation
AsyncCallQueue()
AsyncCallQueue::AsyncCallQueue () private default
Referenced by Instance().
Member Function Documentation
fire()
bool AsyncCallQueue::fire ()
Definition at line 21 of file AsyncCallQueue.cc.
References debugs, AsyncCallList::extract(), CodeContext::Reset(), scheduled, and AsyncCallList::size().
Referenced by EventLoop::dispatchCalls(), TestEvent::testCancel(), TestEvent::testCheckEvents(), and TestEvent::testDump().
Instance()
AsyncCallQueue & AsyncCallQueue::Instance () static
Definition at line 36 of file AsyncCallQueue.cc.
References AsyncCallQueue(), and TheInstance.
Referenced by EventLoop::dispatchCalls(), ScheduleCall(), TestEvent::testCancel(), TestEvent::testCheckEvents(), and TestEvent::testDump().
schedule()
void AsyncCallQueue::schedule (const AsyncCallPointer & call) inline
Definition at line 24 of file AsyncCallQueue.h.
References AsyncCallList::add(), and scheduled.
Referenced by ScheduleCall().
Member Data Documentation
scheduled
AsyncCallList AsyncCallQueue::scheduled private
Definition at line 32 of file AsyncCallQueue.h.
Referenced by fire(), and schedule().
TheInstance
AsyncCallQueue * AsyncCallQueue::TheInstance = nullptr static private
Definition at line 34 of file AsyncCallQueue.h.
Referenced by Instance().
The documentation for this class was generated from the following files:
squid/src/base/AsyncCallQueue.h
squid/src/base/AsyncCallQueue.cc