Squid Web Cache: NullDelayId Class Reference
NullDelayId Class Reference
#include <NullDelayId.h>
Public Types
typedef RefCount< DelayIdComposite > Pointer
Public Member Functions
void * operator new (size_t byteCount)
void operator delete (void *address)
int bytesWanted (int minimum, int maximum) const override
void bytesIn (int) override
virtual void delayRead (const AsyncCallPointer &)
Static Public Member Functions
static int UseCount ()
Static Private Member Functions
static Mem::AllocatorProxy & Pool ()
Detailed Description
Definition at line 18 of file NullDelayId.h.
Member Typedef Documentation
Pointer
typedef RefCount<DelayIdComposite> DelayIdComposite::Pointer inherited
Definition at line 23 of file DelayIdComposite.h.
Member Function Documentation
bytesIn()
void NullDelayId::bytesIn (int) inline override virtual
Implements DelayIdComposite.
Definition at line 25 of file NullDelayId.h.
bytesWanted()
int NullDelayId::bytesWanted (int minimum, int maximum) const inline override virtual
Implements DelayIdComposite.
Definition at line 23 of file NullDelayId.h.
References max().
delayRead()
virtual void DelayIdComposite::delayRead (const AsyncCallPointer &) inline virtual inherited
Reimplemented in Aggregate::AggregateId, DelayTagged::Id, and DelayVector::Id.
Definition at line 29 of file DelayIdComposite.h.
References fatal().
Referenced by DelayId::delayRead().
operator delete()
void NullDelayId::operator delete (void * address) inline
Definition at line 20 of file NullDelayId.h.
operator new()
void * NullDelayId::operator new (size_t byteCount) inline
Definition at line 20 of file NullDelayId.h.
Pool()
static Mem::AllocatorProxy & NullDelayId::Pool () inline static private
Definition at line 20 of file NullDelayId.h.
UseCount()
static int NullDelayId::UseCount () inline static
Definition at line 20 of file NullDelayId.h.
The documentation for this class was generated from the following file:
squid/src/NullDelayId.h