Squid Web Cache: Acl::ParsingContext Class Reference
Acl::ParsingContext Class Reference
CodeContext of the being-parsed acl directive.
Public Types
using Pointer = RefCount< ParsingContext >
Public Member Functions
ParsingContext (const SBuf &name)
ScopedId codeContextGist () const override
std::ostream & detailCodeContext (std::ostream &os) const override
appends human-friendly context description line(s) to a cache.log record
Static Public Member Functions
static const Pointer & Current ()
static void Reset ()
forgets the current context, setting it to nil/unknown
static void Reset (const Pointer)
changes the current context; nil argument sets it to nil/unknown
Public Attributes
Stopwatch busyTime
time spent in this context (see also: busy_time)
Static Private Member Functions
static void ForgetCurrent ()
static void Entering (const Pointer &codeCtx)
static void Leaving ()
Private Attributes
SBuf name_
the aclname parameter of the being-parsed acl directive
Detailed Description
Definition at line 74 of file Acl.cc.
Member Typedef Documentation
Pointer
using Acl::ParsingContext::Pointer = RefCount<ParsingContext>
Definition at line 77 of file Acl.cc.
Constructor & Destructor Documentation
ParsingContext()
Acl::ParsingContext::ParsingContext (const SBuf & name) inline explicit
Definition at line 79 of file Acl.cc.
Member Function Documentation
codeContextGist()
ScopedId Acl::ParsingContext::codeContextGist () const override virtual
Returns
a small, permanent ID of the current context gists persist forever and are suitable for passing to other SMP workers
Implements CodeContext.
Definition at line 133 of file Acl.cc.
Current()
const CodeContext::Pointer & CodeContext::Current () static inherited
Returns
the known global context or, to indicate unknown context, nil
Definition at line 33 of file CodeContext.cc.
Referenced by CallAndRestore_(), CallSubscription< Call_ >::callback(), CallContextCreator(), clientConnectionsClose(), clientHttpConnectionsOpen(), commStartHalfClosedMonitor(), CurrentCodeContextDetail(), HappyOrderEnforcer::enqueue(), CommQuotaQueue::enqueue(), StoreEntry::invokeHandlers(), neighborsUdpPing(), peerDnsRefreshStart(), Security::KeyLog::record(), CodeContext::Reset(), ScheduleCall(), Ftp::StartListening(), Ftp::StopListening(), tunnelDelayedClientRead(), and tunnelDelayedServerRead().
detailCodeContext()
std::ostream & Acl::ParsingContext::detailCodeContext (std::ostream & os) const override virtual
Implements CodeContext.
Definition at line 138 of file Acl.cc.
References ConfigParser::CurrentLocation(), and Debug::Extra().
Entering()
void CodeContext::Entering (const Pointer & codeCtx) static private inherited
Switches the current context to the given known context. Improves debugging output by replacing omni-directional "Reset" with directional "Entering".
Definition at line 55 of file CodeContext.cc.
References CodeContext::busyTime, CodeContext::codeContextGist(), debugs, CodeContext::ForgetCurrent(), and Stopwatch::resume().
Referenced by CodeContext::Reset().
ForgetCurrent()
void CodeContext::ForgetCurrent () static private inherited
Forgets the current known context, possibly triggering its destruction. Preserves the gist of the being-forgotten context during its destruction. Knows nothing about the next context – the caller must set it.
Definition at line 42 of file CodeContext.cc.
References assert.
Referenced by CodeContext::Entering(), and CodeContext::Leaving().
Leaving()
void CodeContext::Leaving () static private inherited
Forgets the current known context. Improves debugging output by replacing omni-directional "Reset" with directional "Leaving".
Definition at line 68 of file CodeContext.cc.
References debugs, and CodeContext::ForgetCurrent().
Referenced by CodeContext::Reset(), and CodeContext::Reset().
Reset() [1/2]
void CodeContext::Reset () static inherited
Definition at line 77 of file CodeContext.cc.
References CodeContext::Leaving().
Referenced by ClientHttpRequest::ClientHttpRequest(), CodeContextGuard::CodeContextGuard(), CodeContextGuard::~CodeContextGuard(), CallAndRestore_(), CallContextCreator(), checkTimeouts(), clientConnectionsClose(), clientHttpConnectionsOpen(), comm_close_complete(), Http::Stream::finished(), AsyncCallQueue::fire(), StoreEntry::invokeHandlers(), neighborsUdpPing(), peerCountMcastPeersCreateAndSend(), peerDnsRefreshStart(), ConnStateData::postHttpsAccept(), Ftp::StartListening(), Ftp::StopListening(), tunnelDelayedClientRead(), and tunnelDelayedServerRead().
Reset() [2/2]
void CodeContext::Reset (const Pointer codeCtx) static inherited
Definition at line 84 of file CodeContext.cc.
References CodeContext::Current(), CodeContext::Entering(), and CodeContext::Leaving().
Member Data Documentation
busyTime
Stopwatch CodeContext::busyTime inherited
Definition at line 76 of file CodeContext.h.
Referenced by Format::Format::assemble(), and CodeContext::Entering().
name_
SBuf Acl::ParsingContext::name_ private
Definition at line 86 of file Acl.cc.
The documentation for this class was generated from the following file:
squid/src/acl/Acl.cc