Squid Web Cache: Security::NegotiationHistory Class Reference
Security::NegotiationHistory Class Reference
#include <NegotiationHistory.h>
Public Member Functions
NegotiationHistory ()
void retrieveNegotiatedInfo (const Security::SessionPointer &)
Extract negotiation information from TLS object.
void retrieveParsedInfo (Security::TlsDetails::Pointer const &details)
Extract information from parser stored in TlsDetails object.
const char * cipherName () const
const char * negotiatedVersion () const
String representation of TLS negotiated version.
const char * helloVersion () const
String representation of the received TLS hello message version.
const char * supportedVersion () const
Private Member Functions
const char * printTlsVersion (AnyP::ProtocolVersion const &v) const
String representation of the TLS version 'v'.
Private Attributes
AnyP::ProtocolVersion helloVersion_
The TLS version of the hello message.
AnyP::ProtocolVersion supportedVersion_
The maximum supported TLS version.
AnyP::ProtocolVersion version_
The negotiated TLS version.
const SSL_CIPHER * cipher
The negotiated cipher.
Detailed Description
Definition at line 18 of file NegotiationHistory.h.
Constructor & Destructor Documentation
NegotiationHistory()
Security::NegotiationHistory::NegotiationHistory ()
Definition at line 18 of file NegotiationHistory.cc.
Member Function Documentation
cipherName()
const char * Security::NegotiationHistory::cipherName () const
The name of negotiated cipher
Definition at line 104 of file NegotiationHistory.cc.
Referenced by Format::Format::assemble().
helloVersion()
const char * Security::NegotiationHistory::helloVersion () const inline
Definition at line 33 of file NegotiationHistory.h.
References helloVersion_, and printTlsVersion().
Referenced by Format::Format::assemble().
negotiatedVersion()
const char * Security::NegotiationHistory::negotiatedVersion () const inline
Definition at line 31 of file NegotiationHistory.h.
References printTlsVersion(), and version_.
Referenced by Format::Format::assemble().
printTlsVersion()
const char * Security::NegotiationHistory::printTlsVersion (AnyP::ProtocolVersion const & v) const private
Definition at line 26 of file NegotiationHistory.cc.
References AnyP::ProtocolVersion::major, AnyP::ProtocolVersion::minor, AnyP::ProtocolVersion::protocol, AnyP::ProtocolType_str, and Security::TlsFamilyProtocol().
Referenced by helloVersion(), negotiatedVersion(), and supportedVersion().
retrieveNegotiatedInfo()
void Security::NegotiationHistory::retrieveNegotiatedInfo (const Security::SessionPointer & session)
Definition at line 72 of file NegotiationHistory.cc.
References BIO_get_data(), debugs, Debug::Enabled(), Ssl::Bio::fd(), and toProtocolVersion().
Referenced by clientNegotiateSSL().
retrieveParsedInfo()
void Security::NegotiationHistory::retrieveParsedInfo (Security::TlsDetails::Pointer const & details)
Definition at line 95 of file NegotiationHistory.cc.
References Security::TlsDetails::tlsSupportedVersion, and Security::TlsDetails::tlsVersion.
Referenced by ConnStateData::parseTlsHandshake().
supportedVersion()
const char * Security::NegotiationHistory::supportedVersion () const inline
String representation of the maximum supported TLS version by remote peer
Definition at line 36 of file NegotiationHistory.h.
References printTlsVersion(), and supportedVersion_.
Referenced by Format::Format::assemble().
Member Data Documentation
cipher
const SSL_CIPHER* Security::NegotiationHistory::cipher private
Definition at line 44 of file NegotiationHistory.h.
helloVersion_
AnyP::ProtocolVersion Security::NegotiationHistory::helloVersion_ private
Definition at line 40 of file NegotiationHistory.h.
Referenced by helloVersion().
supportedVersion_
AnyP::ProtocolVersion Security::NegotiationHistory::supportedVersion_ private
Definition at line 41 of file NegotiationHistory.h.
Referenced by supportedVersion().
version_
AnyP::ProtocolVersion Security::NegotiationHistory::version_ private
Definition at line 42 of file NegotiationHistory.h.
Referenced by negotiatedVersion().
The documentation for this class was generated from the following files:
squid/src/security/NegotiationHistory.h
squid/src/security/NegotiationHistory.cc