Squid Web Cache: Ipc::Mem::IdSetInnerNode Class Reference
Ipc::Mem::IdSetInnerNode Class Reference
a helper class to perform inner node manipulation for IdSet
Public Types
using size_type = IdSet::size_type
typedef uint64_t Packed
(atomically) stored serialized value
Public Member Functions
IdSetInnerNode ()=default
IdSetInnerNode (size_type left, size_type right)
Packed pack () const
returns a serializes value suitable for shared memory storage
Static Public Member Functions
static IdSetInnerNode Unpack (Packed packed)
de-serializes a given value
Public Attributes
size_type left = 0
the number of available IDs in the left subtree
size_type right = 0
the number of available IDs in the right subtree
Detailed Description
Definition at line 74 of file PageStack.cc.
Member Typedef Documentation
Packed
typedef uint64_t Ipc::Mem::IdSetInnerNode::Packed
Definition at line 78 of file PageStack.cc.
size_type
using Ipc::Mem::IdSetInnerNode::size_type = IdSet::size_type
Definition at line 77 of file PageStack.cc.
Constructor & Destructor Documentation
IdSetInnerNode() [1/2]
Ipc::Mem::IdSetInnerNode::IdSetInnerNode () default
IdSetInnerNode() [2/2]
Ipc::Mem::IdSetInnerNode::IdSetInnerNode (size_type left, size_type right)
Definition at line 137 of file PageStack.cc.
Member Function Documentation
pack()
Packed Ipc::Mem::IdSetInnerNode::pack () const inline
Definition at line 87 of file PageStack.cc.
References left, and right.
Referenced by Ipc::Mem::IdSet::fillAllNodes(), Ipc::Mem::IdSet::innerPop(), and Ipc::Mem::IdSet::innerPush().
Unpack()
Ipc::Mem::IdSetInnerNode Ipc::Mem::IdSetInnerNode::Unpack (Packed packed) static
Definition at line 144 of file PageStack.cc.
Referenced by Ipc::Mem::IdSet::innerPop(), and Ipc::Mem::IdSet::innerTruncate().
Member Data Documentation
left
size_type Ipc::Mem::IdSetInnerNode::left = 0
Definition at line 89 of file PageStack.cc.
Referenced by Ipc::Mem::IdSet::innerPop(), and pack().
right
size_type Ipc::Mem::IdSetInnerNode::right = 0
Definition at line 90 of file PageStack.cc.
Referenced by Ipc::Mem::IdSet::innerPop(), and pack().
The documentation for this class was generated from the following file:
squid/src/ipc/mem/PageStack.cc