Squid Web Cache: Ssl::ServerBump Class Reference
Ssl::ServerBump Class Reference
#include <ServerBump.h>
Public Member Functions
ServerBump (ClientHttpRequest *http, StoreEntry *e=nullptr, Ssl::BumpMode mode=Ssl::bumpServerFirst)
~ServerBump ()
void attachServerSession (const Security::SessionPointer &)
Sets the server TLS session object.
Security::CertErrors * sslErrors () const
SSL [certificate validation] errors.
bool connectedOk () const
whether there was a successful connection to (and peeking at) the origin server
bool at (const BumpStep stp) const
whether we are currently performing the given processing step
bool at (const BumpStep step1, const BumpStep step2) const
whether we are currently performing one of the given processing steps
Public Attributes
HttpRequest::Pointer request
faked, minimal request; required by Client API
StoreEntry * entry
Security::CertPointer serverCert
struct {
Ssl::BumpMode step1
The SSL bump mode at step1.
Ssl::BumpMode step2
The SSL bump mode at step2.
Ssl::BumpMode step3
The SSL bump mode at step3.
} act
bumping actions at various bumping steps
Ssl::BumpStep step
The SSL bumping step.
Private Member Functions
CBDATA_CLASS (ServerBump)
Private Attributes
Security::SessionPointer serverSession
The TLS session object on server side.
store_client * sc
dummy client to prevent entry trimming
Detailed Description
Maintains bump-server-first related information.
Definition at line 33 of file ServerBump.h.
Constructor & Destructor Documentation
ServerBump()
Ssl::ServerBump::ServerBump (ClientHttpRequest * http, StoreEntry * e = nullptr, Ssl::BumpMode mode = Ssl::bumpServerFirst) explicit
Definition at line 23 of file ServerBump.cc.
References act, assert, AnyP::Uri::authority(), Ssl::bumpNone, SBuf::c_str(), debugs, DelayId::DelayClient(), HttpRequest::effectiveRequestUri(), entry, HttpRequest::flags, StoreEntry::lock(), HttpRequest::method, ClientHttpRequest::request, request, sc, store_client::setDelayId(), storeClientListAdd(), storeCreateEntry(), and HttpRequest::url.
~ServerBump()
Ssl::ServerBump::~ServerBump ()
Definition at line 49 of file ServerBump.cc.
References debugs, and storeUnregister().
Member Function Documentation
at() [1/2]
bool Ssl::ServerBump::at (const BumpStep step1, const BumpStep step2) const inline
Definition at line 50 of file ServerBump.h.
References at(), step1, and step2.
Referenced by at().
at() [2/2]
bool Ssl::ServerBump::at (const BumpStep stp) const inline
Definition at line 47 of file ServerBump.h.
References step.
Referenced by TunnelStateData::clientExpectsConnectResponse(), and ConnStateData::startPeekAndSplice().
attachServerSession()
void Ssl::ServerBump::attachServerSession (const Security::SessionPointer & s)
Definition at line 60 of file ServerBump.cc.
CBDATA_CLASS()
Ssl::ServerBump::CBDATA_CLASS (ServerBump) private
connectedOk()
bool Ssl::ServerBump::connectedOk () const inline
Definition at line 44 of file ServerBump.h.
References entry, and StoreEntry::isEmpty().
Referenced by ConnStateData::buildSslCertGenerationParams().
sslErrors()
Security::CertErrors * Ssl::ServerBump::sslErrors () const
Definition at line 66 of file ServerBump.cc.
References ssl_ex_index_ssl_errors.
Referenced by ConnStateData::fillConnectionLevelDetails().
Member Data Documentation
[struct]
struct { ... } Ssl::ServerBump::act
Referenced by ServerBump(), ConnStateData::getSslContextStart(), httpsSslBumpStep2AccessCheckDone(), ConnStateData::parseTlsHandshake(), and ConnStateData::sslCrtdHandleReply().
entry
StoreEntry* Ssl::ServerBump::entry
for receiving Squid-generated error messages
Definition at line 54 of file ServerBump.h.
Referenced by ServerBump(), connectedOk(), ConnStateData::parseTlsHandshake(), ConnStateData::serveDelayedError(), and ConnStateData::startPeekAndSplice().
request
HttpRequest::Pointer Ssl::ServerBump::request
Definition at line 53 of file ServerBump.h.
Referenced by ServerBump(), ConnStateData::buildSslCertGenerationParams(), ConnStateData::httpsPeeked(), ConnStateData::parseTlsHandshake(), ConnStateData::serveDelayedError(), and ConnStateData::startPeekAndSplice().
sc
store_client* Ssl::ServerBump::sc private
Definition at line 67 of file ServerBump.h.
Referenced by ServerBump().
serverCert
Security::CertPointer Ssl::ServerBump::serverCert
HTTPS server certificate. Maybe it is different than the one it is stored in serverSession object (error SQUID_X509_V_ERR_CERT_CHANGE)
Definition at line 57 of file ServerBump.h.
Referenced by ConnStateData::buildSslCertGenerationParams(), and ConnStateData::serveDelayedError().
serverSession
Security::SessionPointer Ssl::ServerBump::serverSession private
Definition at line 66 of file ServerBump.h.
step
Ssl::BumpStep Ssl::ServerBump::step
Definition at line 63 of file ServerBump.h.
Referenced by at(), ConnStateData::parseTlsHandshake(), and ConnStateData::startPeekAndSplice().
step1
Ssl::BumpMode Ssl::ServerBump::step1
Definition at line 59 of file ServerBump.h.
Referenced by at(), ConnStateData::getSslContextStart(), ConnStateData::parseTlsHandshake(), and ConnStateData::sslCrtdHandleReply().
step2
Ssl::BumpMode Ssl::ServerBump::step2
Definition at line 60 of file ServerBump.h.
Referenced by at(), and httpsSslBumpStep2AccessCheckDone().
step3
Ssl::BumpMode Ssl::ServerBump::step3
Definition at line 61 of file ServerBump.h.
The documentation for this class was generated from the following files:
squid/src/ssl/ServerBump.h
squid/src/ssl/ServerBump.cc