Squid Web Cache: ACLAnnotationData Class Reference
ACLAnnotationData Class Reference
Squid Components » Access Controls
#include <AnnotationData.h>
Public Member Functions
ACLAnnotationData ()
bool match (NotePairs::Entry *) override
SBufList dump () const override
void parse () override
bool empty () const override
void annotate (NotePairs::Pointer pairs, const CharacterSet *delimiters, const AccessLogEntry::Pointer &al)
Stores annotations into pairs.
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Private Member Functions
MEMPROXY_CLASS (ACLAnnotationData)
Private Attributes
Notes::Pointer notes
Detailed Description
Definition at line 17 of file AnnotationData.h.
Constructor & Destructor Documentation
ACLAnnotationData()
ACLAnnotationData::ACLAnnotationData ()
Definition at line 20 of file AnnotationData.cc.
Member Function Documentation
annotate()
void ACLAnnotationData::annotate (NotePairs::Pointer pairs, const CharacterSet * delimiters, const AccessLogEntry::Pointer & al)
Definition at line 46 of file AnnotationData.cc.
References notes, and Notes::updateNotePairs().
dump()
SBufList ACLAnnotationData::dump () const override virtual
Implements ACLData< NotePairs::Entry * >.
Definition at line 24 of file AnnotationData.cc.
References SBufStream::buf(), Notes::empty(), notes, and Notes::printAsAnnotationAclParameters().
empty()
bool ACLAnnotationData::empty () const inline override virtual
Implements ACLData< NotePairs::Entry * >.
Definition at line 28 of file AnnotationData.h.
References Notes::empty(), and notes.
lineOptions()
virtual const Acl::Options & ACLData< NotePairs::Entry * >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLAnnotationData::match (NotePairs::Entry *) inline override virtual
Implements ACLData< NotePairs::Entry * >.
Definition at line 25 of file AnnotationData.h.
MEMPROXY_CLASS()
ACLAnnotationData::MEMPROXY_CLASS (ACLAnnotationData) private
parse()
void ACLAnnotationData::parse () override virtual
Implements ACLData< NotePairs::Entry * >.
Definition at line 35 of file AnnotationData.cc.
References DBG_CRITICAL, debugs, notes, Notes::parseKvPair(), ConfigParser::PeekAtToken(), and self_destruct().
prepareForUse()
virtual void ACLData< NotePairs::Entry * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
notes
Notes::Pointer ACLAnnotationData::notes private
Definition at line 34 of file AnnotationData.h.
Referenced by annotate(), dump(), empty(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/AnnotationData.h
squid/src/acl/AnnotationData.cc