Squid Web Cache: TestRfc1035 Class Reference
TestRfc1035 Class Reference
Protected Member Functions
void testHeaderUnpack ()
void testParseAPacket ()
void testBugPacketEndingOnCompressionPtr ()
void testBugPacketHeadersOnly ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestRfc1035)
CPPUNIT_TEST (testHeaderUnpack)
CPPUNIT_TEST (testParseAPacket)
CPPUNIT_TEST (testBugPacketHeadersOnly)
CPPUNIT_TEST (testBugPacketEndingOnCompressionPtr)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 20 of file testRFC1035.cc.
Member Function Documentation
CPPUNIT_TEST() [1/4]
TestRfc1035::CPPUNIT_TEST (testBugPacketEndingOnCompressionPtr) private
CPPUNIT_TEST() [2/4]
TestRfc1035::CPPUNIT_TEST (testBugPacketHeadersOnly) private
CPPUNIT_TEST() [3/4]
TestRfc1035::CPPUNIT_TEST (testHeaderUnpack) private
CPPUNIT_TEST() [4/4]
TestRfc1035::CPPUNIT_TEST (testParseAPacket) private
CPPUNIT_TEST_SUITE()
TestRfc1035::CPPUNIT_TEST_SUITE (TestRfc1035) private
CPPUNIT_TEST_SUITE_END()
TestRfc1035::CPPUNIT_TEST_SUITE_END () private
testBugPacketEndingOnCompressionPtr()
void TestRfc1035::testBugPacketEndingOnCompressionPtr () protected
Definition at line 97 of file testRFC1035.cc.
References _rfc1035_message::aa, _rfc1035_message::ancount, _rfc1035_message::arcount, _rfc1035_message::id, _rfc1035_message::nscount, off, _rfc1035_message::opcode, _rfc1035_message::qdcount, _rfc1035_message::qr, _rfc1035_message::ra, _rfc1035_message::rcode, _rfc1035_message::rd, rfc1035HeaderUnpack(), rfc1035MessageDestroy(), rfc1035MessageUnpack(), and _rfc1035_message::tc.
testBugPacketHeadersOnly()
void TestRfc1035::testBugPacketHeadersOnly () protected
Definition at line 140 of file testRFC1035.cc.
References off, rfc1035ErrorMessage(), rfc1035HeaderUnpack(), and rfc1035MessageUnpack().
testHeaderUnpack()
void TestRfc1035::testHeaderUnpack () protected
Definition at line 46 of file testRFC1035.cc.
References _rfc1035_message::aa, _rfc1035_message::ancount, _rfc1035_message::arcount, _rfc1035_message::id, _rfc1035_message::nscount, off, _rfc1035_message::opcode, _rfc1035_message::qdcount, _rfc1035_message::qr, _rfc1035_message::ra, _rfc1035_message::rcode, _rfc1035_message::rd, rfc1035HeaderUnpack(), and _rfc1035_message::tc.
testParseAPacket()
void TestRfc1035::testParseAPacket () protected
Definition at line 79 of file testRFC1035.cc.
References rfc1035MessageDestroy(), and rfc1035MessageUnpack().
The documentation for this class was generated from the following file:
squid/src/tests/testRFC1035.cc