Squid Web Cache: IndependentRunner Class Reference
IndependentRunner Class Reference
A RegisteredRunner with lifetime determined by forces outside the Registry.
#include <RunnersRegistry.h>
Public Types
typedef void(RegisteredRunner::* Method) ()
a pointer to one of the above notification methods
Public Member Functions
~IndependentRunner () override
virtual void bootstrapConfig ()
virtual void finalizeConfig ()
virtual void claimMemoryNeeds ()
virtual void useConfig ()
virtual void startReconfigure ()
virtual void syncConfig ()
virtual void startShutdown ()
virtual void endingShutdown ()
virtual void finishShutdown ()
Meant for cleanup of services needed by the already destroyed objects.
Protected Member Functions
void registerRunner ()
void unregisterRunner ()
unregisters self; safe to call multiple times
Detailed Description
Definition at line 106 of file RunnersRegistry.h.
Member Typedef Documentation
Method
typedef void(RegisteredRunner::* RegisteredRunner::Method) () inherited
Definition at line 94 of file RunnersRegistry.h.
Constructor & Destructor Documentation
~IndependentRunner()
IndependentRunner::~IndependentRunner () inline override
Definition at line 109 of file RunnersRegistry.h.
References unregisterRunner().
Member Function Documentation
bootstrapConfig()
virtual void RegisteredRunner::bootstrapConfig () inline virtual inherited
Called right before parsing squid.conf. Meant for initializing/preparing configuration parsing facilities.
Reimplemented in NtlmAuthRr.
Definition at line 46 of file RunnersRegistry.h.
Referenced by SquidMain().
claimMemoryNeeds()
virtual void RegisteredRunner::claimMemoryNeeds () inline virtual inherited
Called after finalizeConfig(). Meant for announcing memory reservations before memory is allocated.
Reimplemented in IpcIoRr, and MemStoreRr.
Definition at line 55 of file RunnersRegistry.h.
Referenced by RunConfigUsers().
endingShutdown()
virtual void RegisteredRunner::endingShutdown () inline virtual inherited
Called after shutdown_lifetime grace period ends and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented in Auth::CredentialCacheRr, ConnStateData, Dns::ConfigRr, and IdleConnList.
Definition at line 84 of file RunnersRegistry.h.
Referenced by SignalEngine::FinalShutdownRunners().
finalizeConfig()
virtual void RegisteredRunner::finalizeConfig () inline virtual inherited
Called after parsing squid.conf. Meant for setting configuration options that depend on other configuration options and were not explicitly configured.
Reimplemented in sslBumpCfgRr, MemStoreRr, and SnmpRr.
Definition at line 51 of file RunnersRegistry.h.
Referenced by SquidMain().
finishShutdown()
virtual void RegisteredRunner::finishShutdown () inline virtual inherited
Definition at line 91 of file RunnersRegistry.h.
Referenced by RunRegistered(), SquidShutdown(), TestRock::tearDown(), and watch_child().
registerRunner()
void IndependentRunner::registerRunner () protected
Definition at line 104 of file RunnersRegistry.cc.
References FindRunners(), and RegisterRunner_().
Referenced by ConnStateData::ConnStateData(), IdleConnList::IdleConnList(), and Rock::Rebuild::Rebuild().
startReconfigure()
virtual void RegisteredRunner::startReconfigure () inline virtual inherited
Called after receiving a reconfigure request and before parsing squid.conf. Meant for modules that need to prepare for their configuration being changed [outside their control]. The changes end with the syncConfig() event.
Reimplemented in Dns::ConfigRr, HtcpRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 67 of file RunnersRegistry.h.
Referenced by mainReconfigureStart().
startShutdown()
virtual void RegisteredRunner::startShutdown () inline virtual inherited
Called after receiving a shutdown request and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented in ConnStateData, Rock::Rebuild, HtcpRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 78 of file RunnersRegistry.h.
Referenced by SignalEngine::doShutdown().
syncConfig()
virtual void RegisteredRunner::syncConfig () inline virtual inherited
Called after parsing squid.conf during reconfiguration. Meant for adjusting the module state based on configuration changes.
Reimplemented in Auth::CredentialCacheRr, CarpRr, HtcpRr, PeerSourceHashRr, PeerUserHashRr, PeerPoolMgrsRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 71 of file RunnersRegistry.h.
Referenced by mainReconfigureFinish().
unregisterRunner()
void IndependentRunner::unregisterRunner () protected
Definition at line 96 of file RunnersRegistry.cc.
References FindRunners().
Referenced by ~IndependentRunner().
useConfig()
virtual void RegisteredRunner::useConfig () inline virtual inherited
Called after claimMemoryNeeds(). Meant for activating modules and features using a finalized configuration with known memory requirements.
Reimplemented in CarpRr, ClientDbRr, HtcpRr, SharedMemPagesRr, Ipc::Mem::RegisteredRunner, MemStoreRr, PeerSourceHashRr, PeerUserHashRr, PeerPoolMgrsRr, SharedSessionCacheRr, SnmpRr, TransientsRr, WccpRr, and Wccp2Rr.
Definition at line 60 of file RunnersRegistry.h.
Referenced by RunConfigUsers().
The documentation for this class was generated from the following files:
squid/src/base/RunnersRegistry.h
squid/src/base/RunnersRegistry.cc