Squid Web Cache: SBufStatsAction Class Reference
SBufStatsAction Class Reference
SBuf stats for cachemgr.
#include <SBufStatsAction.h>
Public Types
typedef RefCount< Action > Pointer
Public Member Functions
void run (StoreEntry *entry, bool writeHttpHeader)
collect + fillEntry: collect local information and fill the store entry
void fillEntry (StoreEntry *entry, bool writeHttpHeader)
prepare store entry, dump info, close store entry (if possible)
virtual void respond (const Request &request)
respond to Coordinator request; default is to collect and sendResponse
void sendResponse (Ipc::RequestId)
notify Coordinator that this action is done with local processing
virtual bool aggregatable () const
virtual Format format () const
action report syntax
bool atomic () const
dump() call writes everything before returning
const char * name () const
label as seen in the cache manager menu
const Command & command () const
the cause of this action
StoreEntry * createStoreEntry () const
creates store entry from params
const char * contentType () const
HTTP Content-Type header value for this Action report.
Static Public Member Functions
static Pointer Create (const Mgr::CommandPointer &cmd)
Mgr::ClassActionCreationHandler for Mgr::RegisterAction()
static void RegisterWithCacheManager (void)
Protected Member Functions
SBufStatsAction (const Mgr::CommandPointer &cmd)
void collect () override
calculate and keep local action-specific information
void dump (StoreEntry *entry) override
Private Member Functions
void add (const Mgr::Action &action) override
incrementally merge in remote information (of the same action type)
void pack (Ipc::TypedMsgHdr &msg) const override
pack collected action info into a message to be sent to Coordinator
void unpack (const Ipc::TypedMsgHdr &msg) override
unpack action info from the message received by Coordinator
Private Attributes
SBufStats sbdata
MemBlobStats mbdata
StatHist sbsizesatdestruct
StatHist mbsizesatdestruct
const CommandPointer cmd
the command that caused this action
Detailed Description
Definition at line 18 of file SBufStatsAction.h.
Member Typedef Documentation
Pointer
typedef RefCount<Action> Mgr::Action::Pointer inherited
Definition at line 28 of file Action.h.
Constructor & Destructor Documentation
SBufStatsAction()
SBufStatsAction::SBufStatsAction (const Mgr::CommandPointer & cmd) explicit protected
Definition at line 55 of file SBufStatsAction.cc.
Member Function Documentation
add()
void SBufStatsAction::add (const Mgr::Action & action) override private virtual
Reimplemented from Mgr::Action.
Definition at line 66 of file SBufStatsAction.cc.
References mbdata, mbsizesatdestruct, sbdata, and sbsizesatdestruct.
aggregatable()
virtual bool Mgr::Action::aggregatable () const inline virtual inherited
whether at least some local kid info can be combined and, hence, the combined data should be written at the end of the coordinated response
Reimplemented in Mgr::FunAction, and Ssl::CertificateStorageAction.
Definition at line 65 of file Action.h.
atomic()
bool Mgr::Action::atomic () const inherited
Definition at line 44 of file Action.cc.
collect()
void SBufStatsAction::collect () override protected virtual
Reimplemented from Mgr::Action.
Definition at line 75 of file SBufStatsAction.cc.
References collectMemBlobDestructTimeStats(), collectSBufDestructTimeStats(), MemBlob::GetStats(), SBuf::GetStats(), mbdata, mbsizesatdestruct, sbdata, and sbsizesatdestruct.
command()
const Mgr::Command & Mgr::Action::command () const inherited
Definition at line 37 of file Action.cc.
References Must.
contentType()
const char * Mgr::Action::contentType () const inherited
Definition at line 62 of file Action.cc.
References assert, Mgr::informal, and Mgr::yaml.
Create()
SBufStatsAction::Pointer SBufStatsAction::Create (const Mgr::CommandPointer & cmd) static
Definition at line 60 of file SBufStatsAction.cc.
References Mgr::Action::cmd.
Referenced by RegisterWithCacheManager().
createStoreEntry()
StoreEntry * Mgr::Action::createStoreEntry () const inherited
Definition at line 75 of file Action.cc.
References Mgr::ActionParams::httpFlags, Mgr::ActionParams::httpMethod, Mgr::ActionParams::httpUri, storeCreateEntry(), and String::termedBuf().
dump()
void SBufStatsAction::dump (StoreEntry *) override protected virtual
start writing action-specific info to Store entry; may collect info during dump, especially if collect() did nothing non-atomic() actions may continue writing asynchronously after returning
Reimplemented from Mgr::Action.
Definition at line 92 of file SBufStatsAction.cc.
References MemBlobStats::dump(), SBufStats::dump(), StatHist::dump(), mbdata, mbsizesatdestruct, sbdata, sbsizesatdestruct, and statHistSBufDumper().
fillEntry()
void Mgr::Action::fillEntry (StoreEntry * entry, bool writeHttpHeader) inherited
Definition at line 119 of file Action.cc.
References StoreEntry::buffer(), StoreEntry::complete(), debugs, StoreEntry::flush(), MYNAME, CacheManager::PutCommonResponseHeaders(), StoreEntry::replaceHttpReply(), Http::scOkay, HttpReply::setHeaders(), and squid_curtime.
format()
Mgr::Format Mgr::Action::format () const virtual inherited
Definition at line 50 of file Action.cc.
name()
const char * Mgr::Action::name () const inherited
Definition at line 56 of file Action.cc.
pack()
void SBufStatsAction::pack (Ipc::TypedMsgHdr &) const override private virtual
Reimplemented from Mgr::Action.
Definition at line 108 of file SBufStatsAction.cc.
References mbdata, Ipc::mtCacheMgrResponse, Ipc::TypedMsgHdr::putPod(), sbdata, and Ipc::TypedMsgHdr::setType().
RegisterWithCacheManager()
void SBufStatsAction::RegisterWithCacheManager (void) static
Definition at line 124 of file SBufStatsAction.cc.
References Create(), SBufStats::MemBlobSizeAtDestructRecorder, recordMemBlobSizeAtDestruct(), recordSBufSizeAtDestruct(), Mgr::RegisterAction(), and SBufStats::SBufSizeAtDestructRecorder.
Referenced by mainInitialize().
respond()
void Mgr::Action::respond (const Request & request) virtual inherited
Reimplemented in Mgr::FunAction, and Mgr::InfoAction.
Definition at line 88 of file Action.cc.
References Mgr::Request::conn, debugs, Comm::Connection::fd, MYNAME, Ipc::Request::requestId, and xclose().
run()
void Mgr::Action::run (StoreEntry * entry, bool writeHttpHeader) inherited
Definition at line 111 of file Action.cc.
References debugs, and MYNAME.
sendResponse()
void Mgr::Action::sendResponse (Ipc::RequestId requestId) inherited
Definition at line 102 of file Action.cc.
References Ipc::Port::CoordinatorAddr(), Mgr::Response::pack(), and Ipc::SendMessage().
unpack()
void SBufStatsAction::unpack (const Ipc::TypedMsgHdr &) override private virtual
Reimplemented from Mgr::Action.
Definition at line 116 of file SBufStatsAction.cc.
References Ipc::TypedMsgHdr::checkType(), Ipc::TypedMsgHdr::getPod(), mbdata, Ipc::mtCacheMgrResponse, and sbdata.
Member Data Documentation
cmd
const CommandPointer Mgr::Action::cmd private inherited
Definition at line 90 of file Action.h.
Referenced by Mgr::Action::Action(), Mgr::IndexAction::Create(), and Create().
mbdata
MemBlobStats SBufStatsAction::mbdata private
Definition at line 38 of file SBufStatsAction.h.
Referenced by add(), collect(), dump(), pack(), and unpack().
mbsizesatdestruct
StatHist SBufStatsAction::mbsizesatdestruct private
Definition at line 40 of file SBufStatsAction.h.
Referenced by add(), collect(), and dump().
sbdata
SBufStats SBufStatsAction::sbdata private
Definition at line 37 of file SBufStatsAction.h.
Referenced by add(), collect(), dump(), pack(), and unpack().
sbsizesatdestruct
StatHist SBufStatsAction::sbsizesatdestruct private
Definition at line 39 of file SBufStatsAction.h.
Referenced by add(), collect(), and dump().
The documentation for this class was generated from the following files:
squid/src/SBufStatsAction.h
squid/src/SBufStatsAction.cc