Squid Web Cache: LogTags Class Reference
LogTags Class Reference
#include <LogTags.h>
Public Member Functions
LogTags ()=default
LogTags (const LogTags_ot t)
void update (const LogTags_ot t)
const char * c_str () const
compute the status access.log field
bool isTcpHit () const
determine if the log tag code indicates a cache HIT
const char * cacheStatusSource () const
Public Attributes
LogTagsErrors err
various problems augmenting the primary log tag
LogTags_ot oldType = LOG_TAG_NONE
a set of client protocol, cache use, and other transaction outcome tags
CollapsingHistory collapsingHistory
controls CF tag presence
Static Private Attributes
static const char * Str_ []
list of string representations for LogTags_ot
Detailed Description
Definition at line 69 of file LogTags.h.
Constructor & Destructor Documentation
LogTags() [1/2]
LogTags::LogTags () default
LogTags() [2/2]
LogTags::LogTags (const LogTags_ot t) inline explicit
Definition at line 73 of file LogTags.h.
References update().
Member Function Documentation
c_str()
const char * LogTags::c_str () const
Definition at line 75 of file LogTags.cc.
References LogTagsErrors::aborted, assert, CollapsingHistory::collapsed(), collapsingHistory, err, LogTagsErrors::ignored, LOG_TYPE_MAX, oldType, Str_, and LogTagsErrors::timedout.
Referenced by Format::Format::assemble(), Log::Format::HttpdCombined(), Log::Format::HttpdCommon(), clientReplyContext::processMiss(), Log::Format::SquidNative(), and statClientRequests().
cacheStatusSource()
const char * LogTags::cacheStatusSource () const
Returns
Cache-Status "hit" or "fwd=..." parameter (or nil)
Definition at line 124 of file LogTags.cc.
References LOG_ICP_QUERY, LOG_TAG_NONE, LOG_TCP_CLIENT_REFRESH_MISS, LOG_TCP_DENIED, LOG_TCP_DENIED_REPLY, LOG_TCP_HIT, LOG_TCP_IMS_HIT, LOG_TCP_INM_HIT, LOG_TCP_MEM_HIT, LOG_TCP_MISS, LOG_TCP_NEGATIVE_HIT, LOG_TCP_OFFLINE_HIT, LOG_TCP_REDIRECT, LOG_TCP_REFRESH, LOG_TCP_REFRESH_FAIL_ERR, LOG_TCP_REFRESH_FAIL_OLD, LOG_TCP_REFRESH_MODIFIED, LOG_TCP_REFRESH_UNMODIFIED, LOG_TCP_SWAPFAIL_MISS, LOG_TCP_TUNNEL, LOG_TYPE_MAX, LOG_UDP_DENIED, LOG_UDP_HIT, LOG_UDP_INVALID, LOG_UDP_MISS, LOG_UDP_MISS_NOFETCH, and oldType.
Referenced by clientReplyContext::buildReplyHeader().
isTcpHit()
bool LogTags::isTcpHit () const
Definition at line 110 of file LogTags.cc.
References LOG_TCP_HIT, LOG_TCP_IMS_HIT, LOG_TCP_INM_HIT, LOG_TCP_MEM_HIT, LOG_TCP_NEGATIVE_HIT, LOG_TCP_OFFLINE_HIT, LOG_TCP_REFRESH_FAIL_OLD, LOG_TCP_REFRESH_UNMODIFIED, and oldType.
Referenced by clientReplyContext::buildReplyHeader(), clientdbUpdate(), clientUpdateStatCounters(), and clientReplyContext::sendMoreData().
update()
void LogTags::update (const LogTags_ot t)
Definition at line 63 of file LogTags.cc.
References assert, debugs, LOG_TYPE_MAX, oldType, and Str_.
Referenced by LogTags(), TunnelStateData::TunnelStateData(), htcpLogHtcp(), icpCreateAndSend(), icpLogIcp(), and ClientHttpRequest::updateLoggingTags().
Member Data Documentation
collapsingHistory
CollapsingHistory LogTags::collapsingHistory
Definition at line 98 of file LogTags.h.
Referenced by c_str().
err
LogTagsErrors LogTags::err
Definition at line 87 of file LogTags.h.
Referenced by c_str(), clientReplyContext::handleIMSReply(), and FwdState::updateAleWithFinalError().
oldType
LogTags_ot LogTags::oldType = LOG_TAG_NONE
Definition at line 96 of file LogTags.h.
Referenced by clientReplyContext::buildReplyHeader(), c_str(), clientReplyContext::cacheHit(), cacheStatusSource(), clientdbUpdate(), clientUpdateStatCounters(), clientUpdateStatHistCounters(), clientReplyContext::doGetMoreData(), isTcpHit(), clientReplyContext::processReplyAccess(), and update().
Str_
const char * LogTags::Str_ static private
Initial value:
= {
    "TAG_NONE",
    "TCP_HIT",
    "TCP_MISS",
    "TCP_REFRESH_UNMODIFIED",
    "TCP_REFRESH_FAIL_OLD",
    "TCP_REFRESH_FAIL_ERR",
    "TCP_REFRESH_MODIFIED",
    "TCP_REFRESH",
    "TCP_CLIENT_REFRESH_MISS",
    "TCP_IMS_HIT",
    "TCP_INM_HIT",
    "TCP_SWAPFAIL_MISS",
    "TCP_NEGATIVE_HIT",
    "TCP_MEM_HIT",
    "TCP_DENIED",
    "TCP_DENIED_REPLY",
    "TCP_OFFLINE_HIT",
    "TCP_REDIRECT",
    "TCP_TUNNEL",
    "UDP_HIT",
    "UDP_MISS",
    "UDP_DENIED",
    "UDP_INVALID",
    "UDP_MISS_NOFETCH",
    "ICP_QUERY",
    "TYPE_MAX"
}
Definition at line 33 of file LogTags.h.
Referenced by c_str(), and update().
The documentation for this class was generated from the following files:
squid/src/LogTags.h
squid/src/LogTags.cc