Squid Web Cache: Rock::Rebuild::Stats Class Reference
Rock::Rebuild::Stats Class Reference
cache_dir indexing statistics shared across same-kid process restarts
#include <RockRebuild.h>
Public Member Functions
size_t sharedMemorySize () const
bool completed (const SwapDir &) const
whether the rebuild is finished already
Static Public Member Functions
static SBuf Path (const char *dirPath)
static Ipc::Mem::Owner< Stats > * Init (const SwapDir &)
static size_t SharedMemorySize ()
Public Attributes
StoreRebuildData counts
Detailed Description
Definition at line 36 of file RockRebuild.h.
Member Function Documentation
completed()
bool Rock::Rebuild::Stats::completed (const SwapDir & dir) const
Definition at line 265 of file RockRebuild.cc.
References counts, Rock::DoneLoading(), Rock::DoneValidating(), Rock::SwapDir::entryLimitActual(), StoreRebuildData::scancount, Rock::SwapDir::slotLimitActual(), and StoreRebuildData::validations.
Init()
Ipc::Mem::Owner< Rock::Rebuild::Stats > * Rock::Rebuild::Stats::Init (const SwapDir & dir) static
Definition at line 259 of file RockRebuild.cc.
References Store::Disk::path, and shm_new.
Referenced by Rock::SwapDirRr::create().
Path()
SBuf Rock::Rebuild::Stats::Path (const char * dirPath) static
Definition at line 253 of file RockRebuild.cc.
References Ipc::Mem::Segment::Name().
SharedMemorySize()
static size_t Rock::Rebuild::Stats::SharedMemorySize () inline static
Definition at line 42 of file RockRebuild.h.
Referenced by sharedMemorySize().
sharedMemorySize()
size_t Rock::Rebuild::Stats::sharedMemorySize () const inline
Definition at line 43 of file RockRebuild.h.
References SharedMemorySize().
Member Data Documentation
counts
StoreRebuildData Rock::Rebuild::Stats::counts
Definition at line 48 of file RockRebuild.h.
The documentation for this class was generated from the following files:
squid/src/fs/rock/RockRebuild.h
squid/src/fs/rock/RockRebuild.cc