Squid Web Cache: ACLHasComponentData Class Reference
ACLHasComponentData Class Reference
Squid Components » Access Controls
#include <HasComponentData.h>
Public Member Functions
ACLHasComponentData ()
bool match (ACLChecklist *) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Private Types
enum ComponentKind { coRequest = 0 , coResponse , coAle , coEnd }
typedef bool(ACLChecklist::* ComponentCheck) () const
Private Member Functions
MEMPROXY_CLASS (ACLHasComponentData)
void parseComponent (const char *token)
Private Attributes
std::vector< ComponentCheck > componentMethods
component check callbacks, ordered by component kind ID
Static Private Attributes
static const SBuf RequestStr
static const SBuf ResponseStr
static const SBuf AleStr
Detailed Description
Definition at line 16 of file HasComponentData.h.
Member Typedef Documentation
ComponentCheck
typedef bool(ACLChecklist::* ACLHasComponentData::ComponentCheck) () const private
Definition at line 37 of file HasComponentData.h.
Member Enumeration Documentation
ComponentKind
enum ACLHasComponentData::ComponentKind private
Enumerator
coRequest
coResponse
coAle
coEnd
Definition at line 30 of file HasComponentData.h.
Constructor & Destructor Documentation
ACLHasComponentData()
ACLHasComponentData::ACLHasComponentData ()
Definition at line 19 of file HasComponentData.cc.
Member Function Documentation
dump()
SBufList ACLHasComponentData::dump () const override virtual
Implements ACLData< ACLChecklist * >.
Definition at line 52 of file HasComponentData.cc.
References AleStr, coAle, componentMethods, coRequest, coResponse, RequestStr, and ResponseStr.
empty()
bool ACLHasComponentData::empty () const inline override virtual
Implements ACLData< ACLChecklist * >.
Definition at line 27 of file HasComponentData.h.
lineOptions()
virtual const Acl::Options & ACLData< ACLChecklist * >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLHasComponentData::match (ACLChecklist * checklist) override virtual
Implements ACLData< ACLChecklist * >.
Definition at line 43 of file HasComponentData.cc.
References componentMethods.
MEMPROXY_CLASS()
ACLHasComponentData::MEMPROXY_CLASS (ACLHasComponentData) private
parse()
void ACLHasComponentData::parse () override virtual
Implements ACLData< ACLChecklist * >.
Definition at line 24 of file HasComponentData.cc.
References DBG_CRITICAL, debugs, parseComponent(), self_destruct(), and ConfigParser::strtokFile().
parseComponent()
void ACLHasComponentData::parseComponent (const char * token) private
Definition at line 65 of file HasComponentData.cc.
References AleStr, SBuf::cmp(), coAle, componentMethods, coRequest, coResponse, DBG_CRITICAL, debugs, ACLChecklist::hasAle(), ACLChecklist::hasReply(), ACLChecklist::hasRequest(), RequestStr, ResponseStr, and self_destruct().
Referenced by parse().
prepareForUse()
virtual void ACLData< ACLChecklist * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
AleStr
const SBuf ACLHasComponentData::AleStr static private
Definition at line 35 of file HasComponentData.h.
Referenced by dump(), and parseComponent().
componentMethods
std::vector<ComponentCheck> ACLHasComponentData::componentMethods private
Definition at line 39 of file HasComponentData.h.
Referenced by dump(), match(), and parseComponent().
RequestStr
const SBuf ACLHasComponentData::RequestStr static private
Definition at line 33 of file HasComponentData.h.
Referenced by dump(), and parseComponent().
ResponseStr
const SBuf ACLHasComponentData::ResponseStr static private
Definition at line 34 of file HasComponentData.h.
Referenced by dump(), and parseComponent().
The documentation for this class was generated from the following files:
squid/src/acl/HasComponentData.h
squid/src/acl/HasComponentData.cc