Squid Web Cache: Mgr::QueryParams Class Reference
Mgr::QueryParams Class Reference
#include <QueryParams.h>
Public Types
typedef std::pair< String, QueryParam::Pointer > Param
typedef std::vector< Param > Params
Public Member Functions
QueryParam::Pointer get (const String &name) const
returns query parameter by name
void pack (Ipc::TypedMsgHdr &msg) const
store params into msg
void unpack (const Ipc::TypedMsgHdr &msg)
Static Public Member Functions
static void Parse (Parser::Tokenizer &, QueryParams &)
parses the query string parameters
Private Member Functions
Params::const_iterator find (const String &name) const
find query parameter by name
Static Private Member Functions
static QueryParam::Pointer CreateParam (QueryParam::Type aType)
creates a parameter of the specified type
Private Attributes
Params params
Detailed Description
Definition at line 25 of file QueryParams.h.
Member Typedef Documentation
Param
typedef std::pair<String, QueryParam::Pointer> Mgr::QueryParams::Param
Definition at line 28 of file QueryParams.h.
Params
typedef std::vector<Param> Mgr::QueryParams::Params
Definition at line 29 of file QueryParams.h.
Member Function Documentation
CreateParam()
Mgr::QueryParam::Pointer Mgr::QueryParams::CreateParam (QueryParam::Type aType) static private
Definition at line 145 of file QueryParams.cc.
References Mgr::QueryParam::ptInt, Mgr::QueryParam::ptString, and TexcHere.
find()
Mgr::QueryParams::Params::const_iterator Mgr::QueryParams::find (const String & name) const private
Definition at line 61 of file QueryParams.cc.
References String::caseCmp(), Must, and String::size().
Referenced by get().
get()
Mgr::QueryParam::Pointer Mgr::QueryParams::get (const String & name) const
Definition at line 23 of file QueryParams.cc.
References find(), Must, params, and String::size().
Referenced by Mgr::Inquirer::applyQueryParams().
pack()
void Mgr::QueryParams::pack (Ipc::TypedMsgHdr & msg) const
Definition at line 31 of file QueryParams.cc.
References Must, Ipc::TypedMsgHdr::putInt(), and Ipc::TypedMsgHdr::putString().
Parse()
void Mgr::QueryParams::Parse (Parser::Tokenizer & tok, QueryParams & aParams) static
Syntax: query = [ param *('&' param) ] param = name '=' value name = [a-zA-Z0-9]+ value = *pchar | (1*DIGIT *(',' 1*DIGIT))
Definition at line 112 of file QueryParams.cc.
References CharacterSet::ALPHA, CharacterSet::complement(), CharacterSet::DIGIT, Here, params, ParseParamValue(), and SBufToString().
Referenced by CacheManager::ParseUrl().
unpack()
void Mgr::QueryParams::unpack (const Ipc::TypedMsgHdr & msg)
load params from msg
Definition at line 43 of file QueryParams.cc.
References Ipc::TypedMsgHdr::getInt(), Ipc::TypedMsgHdr::getPod(), Ipc::TypedMsgHdr::getString(), Must, and String::size().
Member Data Documentation
params
Params Mgr::QueryParams::params private
Definition at line 46 of file QueryParams.h.
Referenced by get(), and Parse().
The documentation for this class was generated from the following files:
squid/src/mgr/QueryParams.h
squid/src/mgr/QueryParams.cc