Squid Web Cache: ClientDelayPools Class Reference
ClientDelayPools Class Reference
#include <ClientDelayConfig.h>
Public Member Functions
ClientDelayPools (const ClientDelayPools &)=delete
ClientDelayPools & operator= (const ClientDelayPools &)=delete
Static Public Member Functions
static ClientDelayPools * Instance ()
Public Attributes
std::vector< ClientDelayPool::Pointer > pools
Private Member Functions
ClientDelayPools ()
~ClientDelayPools ()
Detailed Description
Definition at line 40 of file ClientDelayConfig.h.
Constructor & Destructor Documentation
ClientDelayPools() [1/2]
ClientDelayPools::ClientDelayPools (const ClientDelayPools &) delete
ClientDelayPools() [2/2]
ClientDelayPools::ClientDelayPools () inline private
Definition at line 49 of file ClientDelayConfig.h.
~ClientDelayPools()
ClientDelayPools::~ClientDelayPools () private
Definition at line 39 of file ClientDelayConfig.cc.
References pools.
Member Function Documentation
Instance()
ClientDelayPools * ClientDelayPools::Instance () static
Definition at line 33 of file ClientDelayConfig.cc.
References pools.
Referenced by ClientDelayConfig::dumpPoolCount(), ClientDelayConfig::pool(), ClientDelayConfig::pools(), and ConnStateData::whenClientIpKnown().
operator=()
ClientDelayPools & ClientDelayPools::operator= (const ClientDelayPools &) delete
Member Data Documentation
pools
std::vector<ClientDelayPool::Pointer> ClientDelayPools::pools
Definition at line 47 of file ClientDelayConfig.h.
Referenced by ~ClientDelayPools(), ClientDelayConfig::dumpPoolCount(), Instance(), ClientDelayConfig::pool(), ClientDelayConfig::pools(), and ConnStateData::whenClientIpKnown().
The documentation for this class was generated from the following files:
squid/src/ClientDelayConfig.h
squid/src/ClientDelayConfig.cc