Squid Web Cache: AsyncJob Class Reference
AsyncJob Class Reference abstract
Async-Jobs API
#include <AsyncJob.h>
Public Types
typedef CbcPointer< AsyncJob > Pointer
Public Member Functions
AsyncJob (const char *aTypeName)
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual void start ()
called by AsyncStart; do not call directly
virtual bool doneAll () const
whether positive goal has been reached
virtual void swanSong ()
virtual const char * status () const
internal cleanup; do not call directly
~AsyncJob () override
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Detailed Description
Base class for all asynchronous jobs
Definition at line 31 of file AsyncJob.h.
Member Typedef Documentation
Pointer
typedef CbcPointer<AsyncJob> AsyncJob::Pointer
Definition at line 34 of file AsyncJob.h.
Constructor & Destructor Documentation
AsyncJob()
AsyncJob::AsyncJob (const char * aTypeName)
Definition at line 43 of file AsyncJob.cc.
References AllJobs(), debugs, and typeName.
~AsyncJob()
AsyncJob::~AsyncJob () override protected
Definition at line 51 of file AsyncJob.cc.
References AllJobs(), assert, debugs, started_, swanSang_, and typeName.
Member Function Documentation
callEnd()
void AsyncJob::callEnd () virtual
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, done(), inCall, started_, status(), swanSang_, swanSong(), and typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call)
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, inCall, Must, status(), CbdataParent::toCbdata(), and typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and inCall.
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), callEnd(), debugs, deleteThis(), inCall, JobMemFun(), Must, stopReason, and typeName.
Referenced by ConnStateData::connStateClosed(), and deleteThis().
done()
bool AsyncJob::done () const protected
Definition at line 106 of file AsyncJob.cc.
References doneAll(), and stopReason.
Referenced by callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool AsyncJob::doneAll () const protected virtual
Reimplemented in Adaptation::AccessCheck, Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Iterator, BodySink, ConnStateData, ClientHttpRequest, Client, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, Ipc::Forwarder, Ipc::Inquirer, Ipc::Port, Ipc::UdsSender, Log::TcpLogger, Mgr::Inquirer, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Server, and Snmp::Inquirer.
Definition at line 112 of file AsyncJob.cc.
Referenced by done(), Adaptation::Ecap::XactionRep::doneAll(), Adaptation::Icap::Launcher::doneAll(), Adaptation::Icap::ServiceRep::doneAll(), Adaptation::Icap::Xaction::doneAll(), Adaptation::Iterator::doneAll(), BodySink::doneAll(), ConnStateData::doneAll(), ClientHttpRequest::doneAll(), Client::doneAll(), Comm::ConnOpener::doneAll(), Comm::TcpAcceptor::doneAll(), Downloader::doneAll(), Rock::HeaderUpdater::doneAll(), Rock::Rebuild::doneAll(), Ipc::UdsSender::doneAll(), Log::TcpLogger::doneAll(), PeerPoolMgr::doneAll(), Security::PeerConnector::doneAll(), and Server::doneAll().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
handleStopRequest()
void AsyncJob::handleStopRequest () inline
Definition at line 73 of file AsyncJob.h.
References mustStop().
mustStop()
void AsyncJob::mustStop (const char * aReason) protected
Definition at line 85 of file AsyncJob.cc.
References debugs, inCall, Must, stopReason, and typeName.
Referenced by HttpStateData::abortAll(), callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by RegisterWithCacheManager().
start()
void AsyncJob::start () protected virtual
Reimplemented in Adaptation::AccessCheck, Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::OptXact, Adaptation::Icap::Xaction, Adaptation::Iterator, ConnStateData, Ftp::Client, Ftp::Gateway, Ftp::Relay, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, HttpStateData, Ipc::Coordinator, Ipc::Forwarder, Ipc::Inquirer, Ipc::Strand, Ipc::UdsSender, Log::TcpLogger, Mgr::ActionWriter, Mgr::Filler, Mgr::Inquirer, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Ftp::Server, Http::One::Server, Server, Snmp::Inquirer, and Ipc::Port.
Definition at line 59 of file AsyncJob.cc.
Referenced by Adaptation::AccessCheck::start(), Adaptation::Icap::Launcher::start(), Adaptation::Icap::Xaction::start(), Adaptation::Iterator::start(), ConnStateData::start(), Http::Tunneler::start(), Ipc::UdsSender::start(), PeerPoolMgr::start(), Security::PeerConnector::start(), Ipc::Port::start(), and Start().
Start()
void AsyncJob::Start (const Pointer & job) static
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, start(), and started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
status()
const char * AsyncJob::status () const protected virtual
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), stopReason, and MemBuf::terminate().
Referenced by callEnd(), callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
swanSong()
virtual void AsyncJob::swanSong () inline protected virtual
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::ModXactLauncher, Adaptation::Icap::OptXact, Adaptation::Icap::Xaction, Adaptation::Initiate, Adaptation::Iterator, ConnStateData, Client, Ftp::Relay, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, Ipc::Forwarder, Ipc::Inquirer, Ipc::UdsSender, Log::TcpLogger, Mgr::Filler, Mgr::Forwarder, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Server, and Snmp::Forwarder.
Definition at line 61 of file AsyncJob.h.
Referenced by callEnd(), Client::swanSong(), Ftp::Relay::swanSong(), Http::Tunneler::swanSong(), Comm::ConnOpener::swanSong(), Comm::TcpAcceptor::swanSong(), Rock::HeaderUpdater::swanSong(), HappyConnOpener::swanSong(), Ipc::UdsSender::swanSong(), Log::TcpLogger::swanSong(), PeerPoolMgr::swanSong(), Security::PeerConnector::swanSong(), and Server::swanSong().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by callException(), and callStart().
Member Data Documentation
id
const InstanceId<AsyncJob> AsyncJob::id
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected
Definition at line 86 of file AsyncJob.h.
Referenced by callEnd(), callStart(), canBeCalled(), deleteThis(), and mustStop().
started_
bool AsyncJob::started_ = false protected
Definition at line 88 of file AsyncJob.h.
Referenced by ~AsyncJob(), callEnd(), and Start().
stopReason
const char* AsyncJob::stopReason protected
Definition at line 84 of file AsyncJob.h.
Referenced by deleteThis(), done(), mustStop(), status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected
Definition at line 89 of file AsyncJob.h.
Referenced by ~AsyncJob(), and callEnd().
typeName
const char* AsyncJob::typeName protected
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob(), Adaptation::Icap::Xaction::Xaction(), ~AsyncJob(), callEnd(), callStart(), deleteThis(), and mustStop().
The documentation for this class was generated from the following files:
squid/src/base/AsyncJob.h
squid/src/base/AsyncJob.cc