Squid Web Cache: Format::Format Class Reference
Format::Format Class Reference
#include <Format.h>
Public Member Functions
Format (const char *name)
virtual ~Format ()
bool parse (const char *def)
void assemble (MemBuf &mb, const AccessLogEntryPointer &al, int logSequenceNumber) const
assemble the state information into a formatted line.
void dump (StoreEntry *entry, const char *directiveName, bool eol=true) const
dump this whole list of formats into the provided StoreEntry
Public Attributes
char * name
Token * format
Format * next
Detailed Description
Definition at line 41 of file Format.h.
Constructor & Destructor Documentation
Format()
Format::Format::Format (const char * name)
Definition at line 42 of file Format.cc.
References xstrdup.
~Format()
Format::Format::~Format () virtual
Definition at line 49 of file Format.cc.
References next, and xfree.
Member Function Documentation
assemble()
void Format::Format::assemble (MemBuf & mb, const AccessLogEntryPointer & al, int logSequenceNumber) const
Definition at line 377 of file Format.cc.
References AnyP::Uri::absolutePath(), actualReplyHeader(), actualRequestHeader(), AccessLogEntry::adapt, AccessLogEntry::Headers::adapted_request, AccessLogEntry::adapted_request, HttpRequest::adaptHistory(), Adaptation::History::allLogString(), Adaptation::History::allMeta, MemBuf::append(), SBuf::append(), Packable::appendf(), SBuf::appendf(), assert, SBuf::assign(), HttpRequest::auth_user_request, base64_encode_final(), base64_encode_init(), base64_encode_len, base64_encode_update(), AccessLogEntry::IcapLogEntry::bodyBytesRead, HierarchyLogEntry::bodyBytesRead, SBufStream::buf(), AccessLogEntry::SslDetails::bumpMode, Ssl::bumpMode(), CodeContext::busyTime, AccessLogEntry::IcapLogEntry::bytesRead, AccessLogEntry::IcapLogEntry::bytesSent, SBuf::c_str(), LogTags::c_str(), AccessLogEntry::cache, Security::NegotiationHistory::cipherName(), SBuf::clear(), HttpRequest::client_addr, Server::clientConnection, HttpRequest::clientConnectionManager, AccessLogEntry::HttpDetails::clientReplySz, AccessLogEntry::HttpDetails::clientRequestSz, AccessLogEntry::HttpDetails::code, AccessLogEntry::CacheDetails::code, HierarchyLogEntry::code, MemBuf::content(), AccessLogEntry::HttpDetails::content_type, MemBuf::contentSize(), Auth::UserRequest::credentialsStr(), current_time, HttpRequest::dnsWait, HttpRequest::effectiveRequestUri(), AccessLogEntry::effectiveVirginUrl(), Eui::Eui48::encode(), Eui::Eui64::encode(), AccessLogEntry::error(), error(), errorPageName(), HttpRequest::extacl_log, HttpRequest::extacl_user, Comm::Connection::fd, fd_table, NotePairs::find(), FindListeningPortAddress(), FindListeningPortNumber(), CbcPointer< Cbc >::get(), HttpHeader::getByName(), HttpHeader::getByNameListMember(), HttpHeader::getEntry(), Ssl::GetErrorName(), AccessLogEntry::getExtUser(), AccessLogEntry::getLogClientFqdn(), AccessLogEntry::getLogClientIp(), AccessLogEntry::getLogMethod(), RefCount< C >::getRaw(), AnyP::Uri::getScheme(), Ssl::GetX509CAAttribute, Ssl::GetX509PEM, Ssl::GetX509UserAttribute, AccessLogEntry::hasLogMethod(), Comm::Connection::hasTlsNegotiations(), Http::Message::header, MessageSizes::header, AccessLogEntry::headers, Security::NegotiationHistory::helloVersion(), AccessLogEntry::hier, HttpRequest::hier, hier_code_str, AccessLogEntry::CacheDetails::highOffset, AnyP::Uri::host(), HierarchyLogEntry::host, AccessLogEntry::IcapLogEntry::hostAddr, AccessLogEntry::http, Http::Message::http_ver, HttpHeaderInitPos, AccessLogEntry::icap, Comm::Connection::id, MasterXaction::id, AnyP::UriScheme::image(), HttpRequestMethod::image(), MemBuf::init(), AccessLogEntry::IcapLogEntry::ioTime, Comm::IsConnOpen(), SBuf::isEmpty(), Ip::Address::isIPv4(), Security::IssuerName(), AccessLogEntry::AdaptationDetails::last_meta, AccessLogEntry::lastAclData, AccessLogEntry::lastAclName, Format::LFT_ADAPTATION_ALL_XACT_TIMES, Format::LFT_ADAPTATION_LAST_ALL_HEADERS, Format::LFT_ADAPTATION_LAST_HEADER, Format::LFT_ADAPTATION_LAST_HEADER_ELEM, Format::LFT_ADAPTATION_SUM_XACT_TIMES, Format::LFT_ADAPTED_REPLY_SIZE_HEADERS, Format::LFT_ADAPTED_REPLY_SIZE_TOTAL, Format::LFT_ADAPTED_REQUEST_ALL_HEADERS, Format::LFT_ADAPTED_REQUEST_HEADER, Format::LFT_ADAPTED_REQUEST_HEADER_ELEM, Format::LFT_BUSY_TIME, Format::LFT_BYTE, Format::LFT_CLIENT_EUI, Format::LFT_CLIENT_FQDN, Format::LFT_CLIENT_HANDSHAKE, Format::LFT_CLIENT_IO_SIZE_TOTAL, Format::LFT_CLIENT_IP_ADDRESS, Format::LFT_CLIENT_LOCAL_IP, Format::LFT_CLIENT_LOCAL_NFMARK, Format::LFT_CLIENT_LOCAL_PORT, Format::LFT_CLIENT_LOCAL_TOS, Format::LFT_CLIENT_PORT, Format::LFT_CLIENT_REQ_METHOD, Format::LFT_CLIENT_REQ_URI, Format::LFT_CLIENT_REQ_URLDOMAIN, Format::LFT_CLIENT_REQ_URLPATH, Format::LFT_CLIENT_REQ_URLPORT, Format::LFT_CLIENT_REQ_URLSCHEME, Format::LFT_CLIENT_REQ_VERSION, Format::LFT_CLIENT_REQUEST_SIZE_HEADERS, Format::LFT_CLIENT_REQUEST_SIZE_TOTAL, Format::LFT_CREDENTIALS, Format::LFT_DNS_WAIT_TIME, Format::LFT_EXT_ACL_CLIENT_EUI48, Format::LFT_EXT_ACL_CLIENT_EUI64, Format::LFT_EXT_ACL_DATA, Format::LFT_EXT_ACL_NAME, Format::LFT_EXT_ACL_USER_CA_CERT, Format::LFT_EXT_ACL_USER_CERT, Format::LFT_EXT_ACL_USER_CERT_RAW, Format::LFT_EXT_ACL_USER_CERTCHAIN_RAW, Format::LFT_EXT_LOG, Format::LFT_HTTP_BODY_BYTES_READ, Format::LFT_HTTP_RECEIVED_STATUS_CODE, Format::LFT_HTTP_SENT_STATUS_CODE, Format::LFT_HTTP_SENT_STATUS_CODE_OLD_30, Format::LFT_ICAP_ADDR, Format::LFT_ICAP_BODY_BYTES_READ, Format::LFT_ICAP_BYTES_READ, Format::LFT_ICAP_BYTES_SENT, Format::LFT_ICAP_IO_TIME, Format::LFT_ICAP_OUTCOME, Format::LFT_ICAP_REP_ALL_HEADERS, Format::LFT_ICAP_REP_HEADER, Format::LFT_ICAP_REP_HEADER_ELEM, Format::LFT_ICAP_REQ_ALL_HEADERS, Format::LFT_ICAP_REQ_HEADER, Format::LFT_ICAP_REQ_HEADER_ELEM, Format::LFT_ICAP_REQUEST_METHOD, Format::LFT_ICAP_REQUEST_URI, Format::LFT_ICAP_SERV_NAME, Format::LFT_ICAP_STATUS_CODE, Format::LFT_ICAP_TOTAL_TIME, Format::LFT_ICAP_TR_RESPONSE_TIME, Format::LFT_LOCAL_LISTENING_IP, Format::LFT_LOCAL_LISTENING_PORT, Format::LFT_MASTER_XACTION, Format::LFT_MIME_TYPE, Format::LFT_NONE, Format::LFT_NOTE, Format::LFT_PEER_RESPONSE_TIME, Format::LFT_PERCENT, Format::LFT_PROXY_PROTOCOL_RECEIVED_ALL_HEADERS, Format::LFT_PROXY_PROTOCOL_RECEIVED_HEADER, Format::LFT_PROXY_PROTOCOL_RECEIVED_HEADER_ELEM, Format::LFT_REPLY_ALL_HEADERS, Format::LFT_REPLY_HEADER, Format::LFT_REPLY_HEADER_ELEM, Format::LFT_REPLY_HIGHOFFSET, Format::LFT_REPLY_OBJECTSIZE, Format::LFT_REQUEST_ALL_HEADERS, Format::LFT_REQUEST_HEADER, Format::LFT_REQUEST_HEADER_ELEM, Format::LFT_REQUEST_METHOD, Format::LFT_REQUEST_URI, Format::LFT_REQUEST_URLGROUP_OLD_2X, Format::LFT_REQUEST_URLPATH_OLD_31, Format::LFT_REQUEST_VERSION, Format::LFT_REQUEST_VERSION_OLD_2X, Format::LFT_SEQUENCE_NUMBER, Format::LFT_SERVER_FQDN_OR_PEER_NAME, Format::LFT_SERVER_IP_ADDRESS, Format::LFT_SERVER_LOCAL_IP, Format::LFT_SERVER_LOCAL_IP_OLD_27, Format::LFT_SERVER_LOCAL_NFMARK, Format::LFT_SERVER_LOCAL_PORT, Format::LFT_SERVER_LOCAL_TOS, Format::LFT_SERVER_PORT, Format::LFT_SERVER_REQ_METHOD, Format::LFT_SERVER_REQ_URI, Format::LFT_SERVER_REQ_URLDOMAIN, Format::LFT_SERVER_REQ_URLPATH, Format::LFT_SERVER_REQ_URLPORT, Format::LFT_SERVER_REQ_URLSCHEME, Format::LFT_SERVER_REQ_VERSION, Format::LFT_SQUID_ERROR, Format::LFT_SQUID_ERROR_DETAIL, Format::LFT_SQUID_HIERARCHY, Format::LFT_SQUID_REQUEST_ATTEMPTS, Format::LFT_SQUID_STATUS, Format::LFT_SSL_BUMP_MODE, Format::LFT_SSL_CLIENT_SNI, Format::LFT_SSL_SERVER_CERT_ERRORS, Format::LFT_SSL_SERVER_CERT_ISSUER, Format::LFT_SSL_SERVER_CERT_SUBJECT, Format::LFT_SSL_SERVER_CERT_WHOLE, Format::LFT_SSL_USER_CERT_ISSUER, Format::LFT_SSL_USER_CERT_SUBJECT, Format::LFT_STRING, Format::LFT_TAG, Format::LFT_TIME_GMT, Format::LFT_TIME_LOCALTIME, Format::LFT_TIME_SECONDS_SINCE_EPOCH, Format::LFT_TIME_START, Format::LFT_TIME_SUBSECOND, Format::LFT_TIME_TO_HANDLE_REQUEST, Format::LFT_TLS_CLIENT_NEGOTIATED_CIPHER, Format::LFT_TLS_CLIENT_NEGOTIATED_VERSION, Format::LFT_TLS_CLIENT_RECEIVED_HELLO_VERSION, Format::LFT_TLS_CLIENT_SUPPORTED_VERSION, Format::LFT_TLS_SERVER_NEGOTIATED_CIPHER, Format::LFT_TLS_SERVER_NEGOTIATED_VERSION, Format::LFT_TLS_SERVER_RECEIVED_HELLO_VERSION, Format::LFT_TLS_SERVER_SUPPORTED_VERSION, Format::LFT_TOTAL_SERVER_SIDE_RESPONSE_TIME, Format::LFT_TRANSPORT_CLIENT_CONNECTION_ID, Format::LFT_USER_EXTERNAL, Format::LFT_USER_LOGIN, Format::LFT_USER_NAME, Comm::Connection::local, Format::LOG_QUOTE_MIMEBLOB, Format::LOG_QUOTE_NONE, Format::LOG_QUOTE_QUOTES, Format::LOG_QUOTE_RAW, Format::LOG_QUOTE_SHELL, Format::LOG_QUOTE_URL, log_quoted_string(), AnyP::ProtocolVersion::major, HttpRequest::masterXaction, MessageSizes::messageTotal(), Adaptation::History::metaHeaders, HttpRequest::method, Adaptation::methodReqmod, Adaptation::methodRespmod, AnyP::ProtocolVersion::minor, Security::NegotiationHistory::negotiatedVersion(), Format::Token::next, Comm::Connection::nfmark, AccessLogEntry::notes, AccessLogEntry::CacheDetails::objectSize, AccessLogEntry::IcapLogEntry::outcome, AccessLogEntry::packReplyHeaders(), HierarchyLogEntry::peer_reply_status, HierarchyLogEntry::peerResponseTime(), HierarchyLogEntry::ping, port, Ip::Address::port(), AnyP::Uri::port(), ConnStateData::preservedClientData, PRId64, NotePairs::print(), PRIu64, AccessLogEntry::IcapLogEntry::processingTime, AccessLogEntry::proxyProtocolHeader, Format::QuoteMimeBlob(), Stopwatch::ran(), SBuf::rawAppendFinish(), SBuf::rawAppendStart(), Comm::Connection::remote, Comm::Connection::remoteEui48, Comm::Connection::remoteEui64, AccessLogEntry::IcapLogEntry::reply, AccessLogEntry::IcapLogEntry::reqMethod, AccessLogEntry::Headers::request, AccessLogEntry::request, AccessLogEntry::IcapLogEntry::request, AccessLogEntry::requestAttempts, AccessLogEntry::IcapLogEntry::reqUri, AccessLogEntry::IcapLogEntry::resStatus, rfc1738_escape, rfc1738_escape_unescaped, safe_free, Http::scNone, ConnStateData::serverBump(), AccessLogEntry::IcapLogEntry::serviceName, String::size(), squid_curtime, AccessLogEntry::ssl, AccessLogEntry::CacheDetails::sslClientCert, sslGetCAAttribute(), sslGetUserAttribute(), sslGetUserCertificatePEM(), AccessLogEntry::CacheDetails::ssluser, AccessLogEntry::CacheDetails::start_time, MemBuf::stolen, StringToSBuf(), strOrNull, strwordquote(), Security::SubjectName(), Adaptation::History::sumLogString(), Security::NegotiationHistory::supportedVersion(), HttpRequest::tag, AccessLogEntry::tcpClient, HierarchyLogEntry::tcpServer, String::termedBuf(), ping_data::timedout, Comm::Connection::tos, ToSBuf(), Ip::Address::toStr(), Stopwatch::total(), HierarchyLogEntry::totalPeeringTime, AccessLogEntry::CacheDetails::trTime, AccessLogEntry::IcapLogEntry::trTime, tvToMsec(), AccessLogEntry::url, HttpRequest::url, Auth::UserRequest::username(), CbcPointer< Cbc >::valid(), InstanceId< Class, ValueType >::value, AccessLogEntry::HttpDetails::version, and xmalloc.
Referenced by Format::AssembleOne(), constructHelperQuery(), Auth::SchemeConfig::CreateAuthUser(), and ACLExternal::makeExternalAclKey().
dump()
void Format::Format::dump (StoreEntry * entry, const char * directiveName, bool eol = true) const
Definition at line 117 of file Format.cc.
References StoreEntry::append(), debugs, Format::LFT_ADAPTATION_LAST_ALL_HEADERS, Format::LFT_ADAPTATION_LAST_HEADER, Format::LFT_ADAPTATION_LAST_HEADER_ELEM, Format::LFT_ADAPTED_REQUEST_ALL_HEADERS, Format::LFT_ADAPTED_REQUEST_HEADER, Format::LFT_ADAPTED_REQUEST_HEADER_ELEM, Format::LFT_ICAP_REP_ALL_HEADERS, Format::LFT_ICAP_REP_HEADER, Format::LFT_ICAP_REP_HEADER_ELEM, Format::LFT_ICAP_REQ_ALL_HEADERS, Format::LFT_ICAP_REQ_HEADER, Format::LFT_ICAP_REQ_HEADER_ELEM, Format::LFT_REPLY_ALL_HEADERS, Format::LFT_REPLY_HEADER, Format::LFT_REPLY_HEADER_ELEM, Format::LFT_REQUEST_ALL_HEADERS, Format::LFT_REQUEST_HEADER, Format::LFT_REQUEST_HEADER_ELEM, Format::LFT_STRING, Format::LOG_QUOTE_MIMEBLOB, Format::LOG_QUOTE_NONE, Format::LOG_QUOTE_QUOTES, Format::LOG_QUOTE_RAW, Format::LOG_QUOTE_SHELL, Format::LOG_QUOTE_URL, MYNAME, and storeAppendPrintf().
Referenced by Log::LogConfig::dumpFormats().
parse()
bool Format::Format::parse (const char * def)
Definition at line 66 of file Format.cc.
References cur, DBG_IMPORTANT, debugs, Format::LOG_QUOTE_NONE, Format::Token::next, and Format::Token::parse().
Referenced by Note::Value::Value(), Auth::SchemeConfig::parse(), parse_HeaderWithAclList(), Log::LogConfig::parseFormats(), and redirectInit().
Member Data Documentation
format
Token* Format::Format::format
Definition at line 60 of file Format.h.
Referenced by Format::AssembleOne(), ACLExternal::makeExternalAclKey(), and parse_externalAclHelper().
name
char* Format::Format::name
Definition at line 59 of file Format.h.
Referenced by FormattedLog::dumpOptions().
next
Format* Format::Format::next
Definition at line 61 of file Format.h.
Referenced by ~Format(), and Log::LogConfig::parseFormats().
The documentation for this class was generated from the following files:
squid/src/format/Format.h
squid/src/format/Format.cc