Squid Web Cache: TestUfs Class Reference
TestUfs Class Reference
Protected Member Functions
void commonInit ()
void testUfsSearch ()
void testUfsDefaultEngine ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestUfs)
CPPUNIT_TEST (testUfsSearch)
CPPUNIT_TEST (testUfsDefaultEngine)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 33 of file testUfs.cc.
Member Function Documentation
commonInit()
void TestUfs::commonInit () protected
Definition at line 68 of file testUfs.cc.
References SquidConfig::avgObjectSize, comm_init(), Config, createRemovalPolicy_lru, YesNoNone::defaultTo(), httpHeaderInitModule(), fde::Init(), Mem::Init(), SquidConfig::maxObjectSize, SquidConfig::memShared, SquidConfig::objectsPerBucket, SquidConfig::replPolicy, SquidConfig::Store, SquidConfig::store_dir_select_algorithm, storeReplAdd(), RemovalPolicySettings::type, and xstrdup.
Referenced by testUfsDefaultEngine(), and testUfsSearch().
CPPUNIT_TEST() [1/2]
TestUfs::CPPUNIT_TEST (testUfsDefaultEngine) private
CPPUNIT_TEST() [2/2]
TestUfs::CPPUNIT_TEST (testUfsSearch) private
CPPUNIT_TEST_SUITE()
TestUfs::CPPUNIT_TEST_SUITE (TestUfs) private
CPPUNIT_TEST_SUITE_END()
TestUfs::CPPUNIT_TEST_SUITE_END () private
testUfsDefaultEngine()
void TestUfs::testUfsDefaultEngine () protected
Definition at line 229 of file testUfs.cc.
References addSwapDir(), SquidConfig::cacheSwap, commonInit(), Config, createRemovalPolicy(), free_cachedir(), Fs::Ufs::UFSStrategy::io, Fs::Ufs::UFSSwapDir::IO, mem_policy, Fs::Ufs::UFSSwapDir::parse(), SquidConfig::replPolicy, safe_free, ConfigParser::SetCfgLine(), TESTDIR, RemovalPolicySettings::type, and xstrdup.
testUfsSearch()
void TestUfs::testUfsSearch () protected
Definition at line 101 of file testUfs.cc.
References addSwapDir(), MemObject::adjustableBaseReply(), StoreEntry::buffer(), RequestFlags::cachable, SquidConfig::cacheSwap, cbcalled, commonInit(), StoreEntry::complete(), Config, Fs::Ufs::UFSSwapDir::create(), createRemovalPolicy(), StoreSearch::currentItem(), StoreSearch::error(), DiskIOModule::Find(), StoreEntry::flush(), free_cachedir(), MemObject::freshestReply(), Store::Controller::init(), Fs::Ufs::UFSSwapDir::IO, StoreSearch::isDone(), StoreEntry::mem(), mem_policy, Http::METHOD_GET, StoreSearch::next(), PACKAGE, HttpReply::packHeadersUsingSlowPacker(), Fs::Ufs::UFSSwapDir::parse(), SquidConfig::replPolicy, Store::Root(), EventLoop::runOnce(), safe_free, Http::scOkay, Store::Controller::search(), searchCallback(), ConfigParser::SetCfgLine(), HttpReply::setHeaders(), StoreEntry::setPublicKey(), squid_curtime, Store::Controller::store_dirs_rebuilding, store_maxobjsize, storeCreateEntry(), storeDirWriteCleanLogs(), SupportOrVeto::support(), StoreEntry::swap_dirn, StoreEntry::swap_filen, StoreEntry::swapOut(), TESTDIR, StoreEntry::timestampsSet(), RemovalPolicySettings::type, StoreEntry::unlock(), VERSION, visible_appname_string, and xstrdup.
The documentation for this class was generated from the following file:
squid/src/tests/testUfs.cc