Squid Web Cache: MemBlob Class Reference
MemBlob Class Reference
#include <MemBlob.h>
Public Types
typedef RefCount< MemBlob > Pointer
using value_type = char
using size_type = uint32_t
using const_pointer = const value_type *
Public Member Functions
MemBlob (const size_type reserveSize)
create a new MemBlob with at least reserveSize capacity
MemBlob (const_pointer, const size_type)
~MemBlob () override
size_type spaceSize () const
the number unused bytes at the end of the allocated blob
bool canAppend (const size_type off, const size_type n) const
void appended (const size_type n)
void append (const_pointer source, const size_type n)
void syncSize (const size_type n)
void consume (const size_type n)
std::ostream & dump (std::ostream &os) const
dump debugging information
void clear ()
Static Public Member Functions
static const MemBlobStats & GetStats ()
obtain a const view of class-wide statistics
Public Attributes
value_type * mem = nullptr
raw allocated memory block
size_type capacity = 0
size of the raw allocated memory block
size_type size = 0
maximum allocated memory in use by callers
const InstanceId< MemBlob > id
blob identifier
Private Member Functions
MEMPROXY_CLASS (MemBlob)
void memAlloc (const size_type memSize)
bool isAppendOffset (const size_type off) const
whether the offset points to the end of the used area
bool willFit (const size_type n) const
whether n more bytes can be appended
MemBlob (const MemBlob &)
MemBlob & operator= (const MemBlob &)
Detailed Description
Refcountable, fixed-size, content-agnostic memory buffer.
Allocated memory block is divided into two sequential areas: "used memory" and "available space". The used area can be filled during construction, grows via the append() call, and can be clear()ed.
MemBlob users can cooperate to safely share the used area. However, MemBlob provides weak use accounting and no sharing protections besides refcounting.
Definition at line 43 of file MemBlob.h.
Member Typedef Documentation
const_pointer
using MemBlob::const_pointer = const value_type *
Definition at line 53 of file MemBlob.h.
Pointer
typedef RefCount<MemBlob> MemBlob::Pointer
Definition at line 48 of file MemBlob.h.
size_type
using MemBlob::size_type = uint32_t
Definition at line 52 of file MemBlob.h.
value_type
using MemBlob::value_type = char
Definition at line 51 of file MemBlob.h.
Constructor & Destructor Documentation
MemBlob() [1/3]
MemBlob::MemBlob (const size_type reserveSize) explicit
Definition at line 60 of file MemBlob.cc.
References debugs, memAlloc(), and MEMBLOB_DEBUGSECTION.
MemBlob() [2/3]
MemBlob::MemBlob (const_pointer buffer, const size_type bufSize)
Definition at line 68 of file MemBlob.cc.
References append(), debugs, memAlloc(), and MEMBLOB_DEBUGSECTION.
~MemBlob()
MemBlob::~MemBlob () override
Definition at line 78 of file MemBlob.cc.
References capacity, debugs, mem, MEMBLOB_DEBUGSECTION, memFreeBuf(), SBufStats::RecordMemBlobSizeAtDestruct(), size, and WriteableStats().
MemBlob() [3/3]
MemBlob::MemBlob (const MemBlob &) private
Member Function Documentation
append()
void MemBlob::append (const_pointer source, const size_type n)
copies exactly n bytes from the source to the available space area, enlarging the used area by n bytes
Exceptions
TextException if there is not enough space in the blob
Parameters
source raw buffer to be copied
n the number of bytes to copy from the source buffer
Definition at line 125 of file MemBlob.cc.
References mem, Must, size, willFit(), and WriteableStats().
Referenced by MemBlob(), SBuf::lowAppend(), and SBuf::reAlloc().
appended()
void MemBlob::appended (const size_type n)
adjusts internal object state as if exactly n bytes were append()ed
Exceptions
TextException if there was not enough space in the blob
Parameters
n the number of bytes that were appended
Definition at line 117 of file MemBlob.cc.
References Must, size, willFit(), and WriteableStats().
canAppend()
bool MemBlob::canAppend (const size_type off, const size_type n) const inline
check whether the caller can successfully append() n bytes
Returns
true the caller may append() n bytes to this blob now
Parameters
off the end of the blob area currently used by the caller
n the total number of bytes the caller wants to append
Definition at line 74 of file MemBlob.h.
References isAppendOffset(), off, and willFit().
Referenced by SBuf::rawAppendFinish(), and SBuf::rawSpace().
clear()
void MemBlob::clear () inline
Definition at line 109 of file MemBlob.h.
References size.
Referenced by SBuf::clear().
consume()
void MemBlob::consume (const size_type n)
forget the first n bytes, moving the rest of data (if any) to the start forgets all data (i.e. empties the buffer) if n exceeds size
Definition at line 146 of file MemBlob.cc.
References mem, Must, and size.
Referenced by SBuf::cow().
dump()
std::ostream & MemBlob::dump (std::ostream & os) const
Definition at line 158 of file MemBlob.cc.
References capacity, mem, and size.
Referenced by SBuf::dump().
GetStats()
const MemBlobStats & MemBlob::GetStats () static
Definition at line 53 of file MemBlob.cc.
References WriteableStats().
Referenced by SBufStatsAction::collect(), SBufStats::dump(), and TestSBuf::testDumpStats().
isAppendOffset()
bool MemBlob::isAppendOffset (const size_type off) const inline private
Definition at line 122 of file MemBlob.h.
References off, and size.
Referenced by canAppend().
memAlloc()
void MemBlob::memAlloc (const size_type minSize) private
Allocate an available space area of at least minSize bytes in size. Must be called by constructors and only by constructors.
Definition at line 97 of file MemBlob.cc.
References capacity, debugs, mem, memAllocBuf(), MEMBLOB_DEBUGSECTION, Must, size, and WriteableStats().
Referenced by MemBlob(), and MemBlob().
MEMPROXY_CLASS()
MemBlob::MEMPROXY_CLASS (MemBlob) private
operator=()
MemBlob & MemBlob::operator= (const MemBlob &) private
spaceSize()
size_type MemBlob::spaceSize () const inline
Definition at line 66 of file MemBlob.h.
References capacity, and size.
Referenced by SBuf::spaceSize(), and willFit().
syncSize()
void MemBlob::syncSize (const size_type n)
keep the first n bytes and forget the rest of data cannot be used to increase our size; use append*() methods for that
Definition at line 137 of file MemBlob.cc.
References debugs, MEMBLOB_DEBUGSECTION, Must, and size.
Referenced by SBuf::cow().
willFit()
bool MemBlob::willFit (const size_type n) const inline private
Definition at line 125 of file MemBlob.h.
References spaceSize().
Referenced by append(), appended(), and canAppend().
Member Data Documentation
capacity
size_type MemBlob::capacity = 0
Definition at line 114 of file MemBlob.h.
Referenced by SBuf::Locker::Locker(), ~MemBlob(), dump(), memAlloc(), SBuf::rawAppendFinish(), SBuf::reAlloc(), SBuf::reserve(), and spaceSize().
id
const InstanceId<MemBlob> MemBlob::id
Definition at line 116 of file MemBlob.h.
mem
value_type* MemBlob::mem = nullptr
Definition at line 113 of file MemBlob.h.
Referenced by SBuf::Locker::Locker(), ~MemBlob(), append(), SBuf::buf(), SBuf::bufEnd(), consume(), dump(), memAlloc(), SBuf::operator[](), SBuf::setAt(), and Log::TcpLogger::writeIfPossible().
size
size_type MemBlob::size = 0
Definition at line 115 of file MemBlob.h.
Referenced by ~MemBlob(), append(), appended(), SBuf::c_str(), clear(), consume(), dump(), isAppendOffset(), memAlloc(), SBuf::rawAppendFinish(), spaceSize(), syncSize(), SBuf::vappendf(), Log::TcpLogger::writeDone(), and Log::TcpLogger::writeIfPossible().
The documentation for this class was generated from the following files:
squid/src/sbuf/MemBlob.h
squid/src/sbuf/MemBlob.cc