Squid Web Cache: TestSBufList Class Reference
TestSBufList Class Reference
Protected Member Functions
void testSBufListMembership ()
void testSBufListJoin ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestSBufList)
CPPUNIT_TEST (testSBufListMembership)
CPPUNIT_TEST (testSBufListJoin)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 15 of file testSBufList.cc.
Member Function Documentation
CPPUNIT_TEST() [1/2]
TestSBufList::CPPUNIT_TEST (testSBufListJoin) private
CPPUNIT_TEST() [2/2]
TestSBufList::CPPUNIT_TEST (testSBufListMembership) private
CPPUNIT_TEST_SUITE()
TestSBufList::CPPUNIT_TEST_SUITE (TestSBufList) private
CPPUNIT_TEST_SUITE_END()
TestSBufList::CPPUNIT_TEST_SUITE_END () private
testSBufListJoin()
void TestSBufList::testSBufListJoin () protected
Definition at line 48 of file testSBufList.cc.
References JoinContainerToSBuf(), literal, s1, sbuf_tokens_number, and tokens.
testSBufListMembership()
void TestSBufList::testSBufListMembership () protected
Definition at line 37 of file testSBufList.cc.
References caseInsensitive, IsMember(), SBuf::push_back(), sbuf_tokens_number, and tokens.
The documentation for this class was generated from the following file:
squid/src/tests/testSBufList.cc