Squid Web Cache: ClassCHostPool::Id Class Reference
ClassCHostPool::Id Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Public Types
typedef RefCount< DelayIdComposite > Pointer
Public Member Functions
void * operator new (size_t byteCount)
void operator delete (void *address)
Id (RefCount< ClassCHostPool >, unsigned char, unsigned char)
int bytesWanted (int min, int max) const override
void bytesIn (int qty) override
virtual void delayRead (const AsyncCallPointer &)
Static Public Member Functions
static int UseCount ()
Static Private Member Functions
static Mem::AllocatorProxy & Pool ()
Private Attributes
RefCount< ClassCHostPool > theClassCHost
unsigned char theNet
unsigned char theHost
Detailed Description
Definition at line 225 of file delay_pools.cc.
Member Typedef Documentation
Pointer
typedef RefCount<DelayIdComposite> DelayIdComposite::Pointer inherited
Definition at line 23 of file DelayIdComposite.h.
Constructor & Destructor Documentation
Id()
ClassCHostPool::Id::Id (RefCount< ClassCHostPool > aPool, unsigned char aNet, unsigned char aHost)
Definition at line 866 of file delay_pools.cc.
Member Function Documentation
bytesIn()
void ClassCHostPool::Id::bytesIn (int qty) override virtual
Implements DelayIdComposite.
Definition at line 876 of file delay_pools.cc.
bytesWanted()
int ClassCHostPool::Id::bytesWanted (int min, int max) const override virtual
Implements DelayIdComposite.
Definition at line 870 of file delay_pools.cc.
References max(), and min().
delayRead()
virtual void DelayIdComposite::delayRead (const AsyncCallPointer &) inline virtual inherited
Reimplemented in Aggregate::AggregateId, DelayTagged::Id, and DelayVector::Id.
Definition at line 29 of file DelayIdComposite.h.
References fatal().
Referenced by DelayId::delayRead().
operator delete()
void ClassCHostPool::Id::operator delete (void * address) inline
Definition at line 227 of file delay_pools.cc.
operator new()
void * ClassCHostPool::Id::operator new (size_t byteCount) inline
Definition at line 227 of file delay_pools.cc.
Pool()
static Mem::AllocatorProxy & ClassCHostPool::Id::Pool () inline static private
Definition at line 227 of file delay_pools.cc.
UseCount()
static int ClassCHostPool::Id::UseCount () inline static
Definition at line 227 of file delay_pools.cc.
Member Data Documentation
theClassCHost
RefCount<ClassCHostPool> ClassCHostPool::Id::theClassCHost private
Definition at line 235 of file delay_pools.cc.
theHost
unsigned char ClassCHostPool::Id::theHost private
Definition at line 237 of file delay_pools.cc.
theNet
unsigned char ClassCHostPool::Id::theNet private
Definition at line 236 of file delay_pools.cc.
The documentation for this class was generated from the following file:
squid/src/delay_pools.cc