Squid Web Cache: RefCount< C > Class Template Reference
RefCount< C > Class Template Reference
#include <RefCount.h>
Inherited by Ipc::Mem::Pointer< Ipc::FewToFewBiQueue::Metadata >, Ipc::Mem::Pointer< Ipc::OneToOneUniQueues >, Ipc::Mem::Pointer< Ipc::QueueReaders >, Ipc::Mem::Pointer< Ipc::Mem::PageStack >, Ipc::Mem::Pointer< Ipc::MemMap::Shared >, Ipc::Mem::Pointer< Ipc::MultiQueue::Metadata >, Ipc::Mem::Pointer< Ipc::StoreMapItems >, Ipc::Mem::Pointer< Ipc::StoreMapAnchors >, and Ipc::Mem::Pointer< Rock::Rebuild::Stats >.
Public Member Functions
RefCount ()
RefCount (C const *p)
~RefCount ()
RefCount (const RefCount &p)
RefCount (RefCount &&p)
template<class Other >
RefCount (const RefCount< Other > &p)
Base::Pointer = Derived::Pointer.
RefCount & operator= (const RefCount &p)
RefCount & operator= (RefCount &&p)
RefCount & operator= (std::nullptr_t)
operator bool () const
bool operator! () const
C * operator-> () const
C & operator* () const
C * getRaw () const
bool operator== (const RefCount &p) const
bool operator!= (const RefCount &p) const
template<class Other >
bool operator== (const Other *const p) const
template<class Other >
bool operator!= (const Other *const p) const
Static Public Member Functions
template<typename... Args>
static auto Make (Args &&... args)
Private Member Functions
void dereference (C const *newP=nullptr)
void reference (const RefCount &p)
Private Attributes
C const * p_
Detailed Description
template<class C>
class RefCount< C >
Template for Reference Counting pointers.
Objects of type 'C' must inherit from 'RefCountable' in base/Lock.h which provides the locking interface used by reference counting.
Definition at line 27 of file RefCount.h.
Constructor & Destructor Documentation
RefCount() [1/5]
template<class C > RefCount< C >::RefCount () inline
Definition at line 37 of file RefCount.h.
RefCount() [2/5]
template<class C > RefCount< C >::RefCount (C const * p) inline
Definition at line 39 of file RefCount.h.
References RefCount< C >::reference().
~RefCount()
template<class C > RefCount< C >::~RefCount () inline
Definition at line 41 of file RefCount.h.
References RefCount< C >::dereference().
RefCount() [3/5]
template<class C > RefCount< C >::RefCount (const RefCount< C > & p) inline
Definition at line 45 of file RefCount.h.
References RefCount< C >::reference().
RefCount() [4/5]
template<class C > RefCount< C >::RefCount (RefCount< C > && p) inline
Definition at line 49 of file RefCount.h.
RefCount() [5/5]
template<class C > template<class Other > RefCount< C >::RefCount (const RefCount< Other > & p) inline
Definition at line 55 of file RefCount.h.
References RefCount< C >::reference().
Member Function Documentation
dereference()
template<class C > void RefCount< C >::dereference (C const * newP = nullptr) inline private
Definition at line 112 of file RefCount.h.
References RefCount< C >::p_.
Referenced by RefCount< C >::~RefCount(), RefCount< C >::operator=(), RefCount< C >::operator=(), and RefCount< C >::operator=().
getRaw()
template<class C > C * RefCount< C >::getRaw () const inline
Definition at line 89 of file RefCount.h.
References RefCount< C >::p_.
Referenced by Snmp::Inquirer::Inquirer(), SBuf::Locker::Locker(), actualReplyHeader(), external_acl::add(), addSwapDir(), addSwapDir(), addSwapDir(), addSwapDir(), StoreEntry::adjustVary(), TunnelStateData::advanceDestination(), Mgr::Inquirer::applyQueryParams(), Format::Format::assemble(), AuthenticateAcl(), authenticateAuthenticateUser(), ErrorState::buildBody(), ConnStateData::buildFakeRequest(), ErrorState::BuildHttpReply(), Http::One::Server::buildHttpRequest(), Downloader::buildRequest(), HttpStateData::buildRequestPrefix(), ConnStateData::buildSslCertGenerationParams(), StoreEntry::calcPublicKey(), DiskdFile::canNotifyClient(), htcpSpecifier::checkHit(), clientGetMoreData(), clientProcessRequest(), clientReplyStatus(), clientStreamDetach(), clientStreamInsertHead(), clientStreamRead(), BlockingFile::close(), DiskdFile::close(), DiskThreadsDiskFile::close(), comm_read_cancel(), comm_remove_close_handler(), ErrorState::compileLegacyCode(), TunnelStateData::connectDone(), DiskdFile::create(), Fs::Ufs::UFSStrategy::create(), Ftp::Server::doProcessRequest(), HttpStateData::drop1xx(), ErrorState::Dump(), Adaptation::Icap::ModXact::encapsulateHead(), external_acl_cache_delete(), external_acl_cache_touch(), CommonPool::Factory(), htcpSpecifier::fillChecklist(), UrnState::fillChecklist(), Ssl::ErrorDetailsManager::findDetail(), findPreviouslyCachedEntry(), HttpStateData::forwardUpgrade(), ftpSendReply(), Client::handleAdaptationBlocked(), Client::handledEarlyAdaptationAbort(), Ftp::Server::handleFeatReply(), Http::Tunneler::handleResponse(), HttpStateData::haveParsedReplyHeaders(), htcpAccessAllowed(), htcpClrStore(), httpMaybeRemovePublic(), ConnStateData::httpsPeeked(), MimeIcon::load(), ClientHttpRequest::logRequest(), HappyConnOpener::makeError(), Acl::NoteCheck::match(), Client::maybePurgeOthers(), netdbExchangeStart(), ErrorState::NewForwarding(), ClientHttpRequest::noteAdaptationAnswer(), Client::noteAdaptationAnswer(), Adaptation::Icap::ServiceRep::noteAdaptationAnswer(), Adaptation::Iterator::noteAdaptationAnswer(), TunnelStateData::noteConnection(), TunnelStateData::noteDestinationsEnd(), TunnelStateData::noteSecurityPeerConnectorAnswer(), Mgr::Inquirer::noteWroteHeader(), MemObject::objectBytesOnDisk(), DiskdFile::open(), Fs::Ufs::UFSStrategy::open(), HappyConnOpener::openFreshConnection(), PeerPoolMgr::openNewConnection(), DelayTaggedUpdateVisitor::operator()(), DelayUserUpdateVisitor::operator()(), PeerConnectionPointer::operator->(), operator<<(), Adaptation::Icap::OptXact::parseResponse(), ConnStateData::parseTlsHandshake(), Adaptation::Icap::ModXact::prepEchoing(), Http::One::Server::proceedAfterBodyContinuation(), Http::One::Server::processParsedRequest(), BlockingFile::read(), DiskdFile::read(), DiskThreadsDiskFile::read(), Rock::SwapDir::readCompleted(), Fs::Ufs::UFSStoreState::readCompleted(), refreshCheckDigest(), Fs::Ufs::UFSSwapDir::replacementRemove(), TunnelStateData::retryOrBail(), BandwidthBucket::SelectBucket(), DiskdIOStrategy::send(), Client::sendBodyIsTooLargeError(), ConnStateData::sendControlMsg(), Http::One::Server::setReplyError(), UrnState::start(), ACLProxyAuth::StartLookup(), ConnStateData::startPeekAndSplice(), MemObject::stat(), Ftp::Server::stopWaitingForOrigin(), storeSwapInFileClosed(), StoreEntry::swapOutFileClose(), TestRefCount::testDoubleInheritToSingleInherit(), TestRefCount::testPointerConst(), TestRefCount::testPointerFromRefCounter(), TestRefCount::testRefCountFromConst(), TestStoreController::testSearch(), TestStoreHashIndex::testSearch(), TunnelStateData::tunnelEstablishmentDone(), urnHandleReply(), TunnelStateData::usePinned(), ACLFilledChecklist::verifyAle(), and Rock::SwapDir::writeCompleted().
Make()
template<class C > template<typename... Args> static auto RefCount< C >::Make (Args &&... args) inline static
creates a new C object using given C constructor arguments (if any)
Returns
a refcounting pointer to the created object
Definition at line 34 of file RefCount.h.
Referenced by Acl::Node::ParseNamedAcl().
operator bool()
template<class C > RefCount< C >::operator bool () const inline explicit
Definition at line 78 of file RefCount.h.
References RefCount< C >::p_.
operator!()
template<class C > bool RefCount< C >::operator! () const inline
Definition at line 80 of file RefCount.h.
References RefCount< C >::p_.
operator!=() [1/2]
template<class C > template<class Other > bool RefCount< C >::operator!= (const Other *const p) const inline
Definition at line 106 of file RefCount.h.
References RefCount< C >::p_.
operator!=() [2/2]
template<class C > bool RefCount< C >::operator!= (const RefCount< C > & p) const inline
Definition at line 95 of file RefCount.h.
References RefCount< C >::p_.
operator*()
template<class C > C & RefCount< C >::operator* () const inline
Definition at line 84 of file RefCount.h.
References assert, and RefCount< C >::p_.
operator->()
template<class C > C * RefCount< C >::operator-> () const inline
Definition at line 82 of file RefCount.h.
References RefCount< C >::p_.
operator=() [1/3]
template<class C > RefCount & RefCount< C >::operator= (const RefCount< C > & p) inline
Definition at line 59 of file RefCount.h.
References RefCount< C >::dereference(), RefCount< C >::p_, and RefCount< C >::reference().
operator=() [2/3]
template<class C > RefCount & RefCount< C >::operator= (RefCount< C > && p) inline
Definition at line 68 of file RefCount.h.
References RefCount< C >::dereference().
operator=() [3/3]
template<class C > RefCount & RefCount< C >::operator= (std::nullptr_t) inline
Definition at line 76 of file RefCount.h.
References RefCount< C >::dereference().
operator==() [1/2]
template<class C > template<class Other > bool RefCount< C >::operator== (const Other *const p) const inline
Definition at line 100 of file RefCount.h.
References RefCount< C >::p_.
operator==() [2/2]
template<class C > bool RefCount< C >::operator== (const RefCount< C > & p) const inline
Definition at line 91 of file RefCount.h.
References RefCount< C >::p_.
reference()
template<class C > void RefCount< C >::reference (const RefCount< C > & p) inline private
Definition at line 124 of file RefCount.h.
References RefCount< C >::p_.
Referenced by RefCount< C >::RefCount(), RefCount< C >::RefCount(), RefCount< C >::RefCount(), and RefCount< C >::operator=().
Member Data Documentation
p_
template<class C > C const* RefCount< C >::p_ private
Definition at line 129 of file RefCount.h.
Referenced by RefCount< C >::dereference(), RefCount< C >::getRaw(), RefCount< C >::operator bool(), RefCount< C >::operator!(), RefCount< C >::operator!=(), RefCount< C >::operator!=(), RefCount< C >::operator*(), RefCount< C >::operator->(), RefCount< C >::operator=(), RefCount< C >::operator==(), RefCount< C >::operator==(), and RefCount< C >::reference().
The documentation for this class was generated from the following files:
squid/src/adaptation/forward.h
squid/src/base/RefCount.h