Squid Web Cache: Helper::ReservationId Class Reference
Helper::ReservationId Class Reference
a (temporary) lock on a (stateful) helper channel
#include <ReservationId.h>
Public Member Functions
bool reserved () const
operator bool () const
bool operator! () const
bool operator== (const Helper::ReservationId &other) const
bool operator!= (const Helper::ReservationId &other) const
void clear ()
uint64_t value () const
std::ostream & print (std::ostream &os) const
dumps the reservation info for debugging
Static Public Member Functions
static ReservationId Next ()
Private Attributes
uint64_t id = 0
uniquely identifies this reservation
Detailed Description
Definition at line 17 of file ReservationId.h.
Member Function Documentation
clear()
void Helper::ReservationId::clear () inline
Definition at line 29 of file ReservationId.h.
Next()
Helper::ReservationId Helper::ReservationId::Next () static
Definition at line 13 of file ReservationId.cc.
References id.
Referenced by helper_stateful_server::reserve().
operator bool()
Helper::ReservationId::operator bool () const inline explicit
Definition at line 24 of file ReservationId.h.
References reserved().
operator!()
bool Helper::ReservationId::operator! () const inline
Definition at line 25 of file ReservationId.h.
References reserved().
operator!=()
bool Helper::ReservationId::operator!= (const Helper::ReservationId & other) const inline
Definition at line 27 of file ReservationId.h.
operator==()
bool Helper::ReservationId::operator== (const Helper::ReservationId & other) const inline
Definition at line 26 of file ReservationId.h.
References id.
print()
std::ostream & Helper::ReservationId::print (std::ostream & os) const
Definition at line 22 of file ReservationId.cc.
reserved()
bool Helper::ReservationId::reserved () const inline
Definition at line 22 of file ReservationId.h.
Referenced by operator bool(), operator!(), and helper_stateful_server::reserved().
value()
uint64_t Helper::ReservationId::value () const inline
Definition at line 30 of file ReservationId.h.
References id.
Member Data Documentation
id
uint64_t Helper::ReservationId::id = 0 private
Definition at line 36 of file ReservationId.h.
Referenced by Next(), operator==(), and value().
The documentation for this class was generated from the following files:
squid/src/helper/ReservationId.h
squid/src/helper/ReservationId.cc