Squid Web Cache: NullaryMemFunT< Job > Class Template Reference
NullaryMemFunT< Job > Class Template Reference
#include <AsyncJobCalls.h>
Public Types
typedef void(Job::* Method) ()
typedef Job DestClass
typedef CbcPointer< Job > JobPointer
Public Member Functions
NullaryMemFunT (const CbcPointer< Job > &aJob, Method aMethod)
void print (std::ostream &os) const override
virtual bool canDial (AsyncCall &call)
void dial (AsyncCall &call)
Public Attributes
Method method
JobPointer job
Protected Member Functions
void doDial () override
Detailed Description
template<class Job>
class NullaryMemFunT< Job >
Definition at line 91 of file AsyncJobCalls.h.
Member Typedef Documentation
DestClass
template<class Job > typedef Job JobDialer< Job >::DestClass inherited
Definition at line 29 of file AsyncJobCalls.h.
JobPointer
template<class Job > typedef CbcPointer<Job> JobDialer< Job >::JobPointer inherited
Definition at line 30 of file AsyncJobCalls.h.
Method
template<class Job > typedef void(Job::* NullaryMemFunT< Job >::Method) ()
Definition at line 94 of file AsyncJobCalls.h.
Constructor & Destructor Documentation
NullaryMemFunT()
template<class Job > NullaryMemFunT< Job >::NullaryMemFunT (const CbcPointer< Job > & aJob, Method aMethod) inline explicit
Definition at line 95 of file AsyncJobCalls.h.
Member Function Documentation
canDial()
template<class Job > bool JobDialer< Job >::canDial (AsyncCall & call) virtual inherited
Reimplemented in CommCbMemFunT< C, Params_ >, BodyProducerDialer, and BodyConsumerDialer.
Definition at line 161 of file AsyncJobCalls.h.
References AsyncCall::cancel().
Referenced by CommCbMemFunT< C, Params_ >::canDial(), BodyProducerDialer::canDial(), and BodyConsumerDialer::canDial().
dial()
template<class Job > void JobDialer< Job >::dial (AsyncCall & call) inherited
Definition at line 171 of file AsyncJobCalls.h.
References Critical, debugs, AsyncCall::debugSection, and AsyncCall::name.
doDial()
template<class Job > void NullaryMemFunT< Job >::doDial () inline override protected virtual
Implements JobDialer< Job >.
Definition at line 104 of file AsyncJobCalls.h.
References JobDialer< Job >::job, and NullaryMemFunT< Job >::method.
print()
template<class Job > void NullaryMemFunT< Job >::print (std::ostream & os) const inline override virtual
Implements CallDialer.
Definition at line 98 of file AsyncJobCalls.h.
Member Data Documentation
job
template<class Job > JobPointer JobDialer< Job >::job inherited
Definition at line 38 of file AsyncJobCalls.h.
Referenced by BodyProducerDialer::canDial(), BodyConsumerDialer::canDial(), NullaryMemFunT< Job >::doDial(), and UnaryMemFunT< Job, Data, Argument1 >::doDial().
method
template<class Job > Method NullaryMemFunT< Job >::method
Definition at line 101 of file AsyncJobCalls.h.
Referenced by NullaryMemFunT< Job >::doDial().
The documentation for this class was generated from the following file:
squid/src/base/AsyncJobCalls.h