Squid Web Cache: Adaptation::DynamicGroupCfg Class Reference
Adaptation::DynamicGroupCfg Class Reference
DynamicServiceGroup configuration to remember future dynamic chains.
#include <DynamicGroupCfg.h>
Public Types
typedef std::vector< String > Store
typedef String Id
Public Member Functions
bool empty () const
no services added
const String & serviceIds () const
configured service IDs in X-Next-Services value (comma-separated) format
void add (const String &item)
updates group id and services
void clear ()
makes the config empty
Public Attributes
Id id
group id
Store services
services in the group
Detailed Description
Definition at line 20 of file DynamicGroupCfg.h.
Member Typedef Documentation
Id
typedef String Adaptation::DynamicGroupCfg::Id
Definition at line 24 of file DynamicGroupCfg.h.
Store
typedef std::vector<String> Adaptation::DynamicGroupCfg::Store
Definition at line 23 of file DynamicGroupCfg.h.
Member Function Documentation
add()
void Adaptation::DynamicGroupCfg::add (const String & item)
Definition at line 14 of file DynamicGroupCfg.cc.
References String::append(), and services.
Referenced by Adaptation::DynamicServiceChain::Split().
clear()
void Adaptation::DynamicGroupCfg::clear ()
Definition at line 26 of file DynamicGroupCfg.cc.
empty()
bool Adaptation::DynamicGroupCfg::empty () const inline
Definition at line 29 of file DynamicGroupCfg.h.
References services.
Referenced by Adaptation::Iterator::updatePlan().
serviceIds()
const String & Adaptation::DynamicGroupCfg::serviceIds () const inline
Definition at line 32 of file DynamicGroupCfg.h.
References id.
Member Data Documentation
id
Id Adaptation::DynamicGroupCfg::id
Definition at line 26 of file DynamicGroupCfg.h.
Referenced by Adaptation::DynamicServiceChain::DynamicServiceChain(), Adaptation::operator<<(), and serviceIds().
services
Store Adaptation::DynamicGroupCfg::services
Definition at line 27 of file DynamicGroupCfg.h.
Referenced by Adaptation::DynamicServiceChain::DynamicServiceChain(), add(), and empty().
The documentation for this class was generated from the following files:
squid/src/adaptation/DynamicGroupCfg.h
squid/src/adaptation/DynamicGroupCfg.cc