Squid Web Cache: JobDialer< Job > Class Template Reference
JobDialer< Job > Class Template Reference abstract
Async-Jobs API
#include <AsyncJobCalls.h>
Public Types
typedef Job DestClass
typedef CbcPointer< Job > JobPointer
Public Member Functions
JobDialer (const JobPointer &aJob)
JobDialer (const JobDialer &d)
virtual bool canDial (AsyncCall &call)
void dial (AsyncCall &call)
virtual void print (std::ostream &os) const =0
Public Attributes
JobPointer job
Protected Member Functions
virtual void doDial ()=0
Private Member Functions
JobDialer & operator= (const JobDialer &)
Detailed Description
template<class Job>
class JobDialer< Job >
This is a base class for all job call dialers. It does all the job dialing logic (debugging, handling exceptions, etc.) except for calling the job method. The latter requires knowing the number and type of method parameters. Thus, we add a dial() virtual method that the MemFunT templates below implement for us, calling the job's method with the right params.
Definition at line 26 of file AsyncJobCalls.h.
Member Typedef Documentation
DestClass
template<class Job > typedef Job JobDialer< Job >::DestClass
Definition at line 29 of file AsyncJobCalls.h.
JobPointer
template<class Job > typedef CbcPointer<Job> JobDialer< Job >::JobPointer
Definition at line 30 of file AsyncJobCalls.h.
Constructor & Destructor Documentation
JobDialer() [1/2]
template<class Job > JobDialer< Job >::JobDialer (const JobPointer & aJob)
Definition at line 150 of file AsyncJobCalls.h.
JobDialer() [2/2]
template<class Job > JobDialer< Job >::JobDialer (const JobDialer< Job > & d)
Definition at line 155 of file AsyncJobCalls.h.
Member Function Documentation
canDial()
template<class Job > bool JobDialer< Job >::canDial (AsyncCall & call) virtual
Reimplemented in CommCbMemFunT< C, Params_ >, BodyProducerDialer, and BodyConsumerDialer.
Definition at line 161 of file AsyncJobCalls.h.
References AsyncCall::cancel().
Referenced by CommCbMemFunT< C, Params_ >::canDial(), BodyProducerDialer::canDial(), and BodyConsumerDialer::canDial().
dial()
template<class Job > void JobDialer< Job >::dial (AsyncCall & call)
Definition at line 171 of file AsyncJobCalls.h.
References Critical, debugs, AsyncCall::debugSection, and AsyncCall::name.
doDial()
template<class Job > virtual void JobDialer< Job >::doDial () protected pure virtual
Implemented in NullaryMemFunT< Job >, NullaryMemFunT< ModXact >, UnaryMemFunT< Job, Data, Argument1 >, UnaryMemFunT< BodyConsumer, BodyPipe::Pointer >, UnaryMemFunT< BodyProducer, BodyPipe::Pointer >, UnaryMemFunT< Job, Argument1, Argument1 & >, and CommCbMemFunT< C, Params_ >.
operator=()
template<class Job > JobDialer & JobDialer< Job >::operator= (const JobDialer< Job > &) private
print()
virtual void CallDialer::print (std::ostream & os) const pure virtual inherited
Implemented in UnaryFunCallbackDialer< Argument1 >, UnaryCbcCallbackDialer< Destination, Argument1 >, UnaryFunDialer< Argument1 >, UnaryCbdataDialer< Argument1 >, NullaryFunDialer, NullaryMemFunT< Job >, NullaryMemFunT< ModXact >, UnaryMemFunT< Job, Data, Argument1 >, UnaryMemFunT< BodyConsumer, BodyPipe::Pointer >, UnaryMemFunT< BodyProducer, BodyPipe::Pointer >, UnaryMemFunT< Job, Argument1, Argument1 & >, ListeningStartedDialer, CommCbMemFunT< C, Params_ >, CommAcceptCbPtrFun, CommConnectCbPtrFun, CommIoCbPtrFun, CommCloseCbPtrFun, CommTimeoutCbPtrFun, EventDialer, and StoreIOStateCb.
Member Data Documentation
job
template<class Job > JobPointer JobDialer< Job >::job
Definition at line 38 of file AsyncJobCalls.h.
Referenced by BodyProducerDialer::canDial(), BodyConsumerDialer::canDial(), NullaryMemFunT< Job >::doDial(), and UnaryMemFunT< Job, Data, Argument1 >::doDial().
The documentation for this class was generated from the following file:
squid/src/base/AsyncJobCalls.h