Squid Web Cache: ACLSslErrorData Class Reference
ACLSslErrorData Class Reference
#include <SslErrorData.h>
Public Member Functions
ACLSslErrorData ()=default
~ACLSslErrorData () override
bool match (const Security::CertErrors *) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Public Attributes
Security::Errors values
Private Member Functions
MEMPROXY_CLASS (ACLSslErrorData)
Detailed Description
Definition at line 16 of file SslErrorData.h.
Constructor & Destructor Documentation
ACLSslErrorData()
ACLSslErrorData::ACLSslErrorData () default
~ACLSslErrorData()
ACLSslErrorData::~ACLSslErrorData () inline override
Definition at line 22 of file SslErrorData.h.
Member Function Documentation
dump()
SBufList ACLSslErrorData::dump () const override virtual
Implements ACLData< const Security::CertErrors * >.
Definition at line 26 of file SslErrorData.cc.
References Ssl::GetErrorName(), and values.
empty()
bool ACLSslErrorData::empty () const inline override virtual
Implements ACLData< const Security::CertErrors * >.
Definition at line 26 of file SslErrorData.h.
References values.
lineOptions()
virtual const Acl::Options & ACLData< const Security::CertErrors * >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLSslErrorData::match (const Security::CertErrors * toFind) override virtual
Implements ACLData< const Security::CertErrors * >.
Definition at line 16 of file SslErrorData.cc.
References CbDataList< C >::next, and values.
MEMPROXY_CLASS()
ACLSslErrorData::MEMPROXY_CLASS (ACLSslErrorData) private
parse()
void ACLSslErrorData::parse () override virtual
Implements ACLData< const Security::CertErrors * >.
Definition at line 36 of file SslErrorData.cc.
References Ssl::ParseErrorString(), ConfigParser::strtokFile(), and values.
prepareForUse()
virtual void ACLData< const Security::CertErrors * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
values
Security::Errors ACLSslErrorData::values
Definition at line 28 of file SslErrorData.h.
Referenced by dump(), empty(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/SslErrorData.h
squid/src/acl/SslErrorData.cc