Squid Web Cache: ACLIntRange Class Reference
ACLIntRange Class Reference
#include <IntRange.h>
Public Member Functions
ACLIntRange ()
~ACLIntRange () override
bool match (int) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Private Types
typedef Range< int > RangeType
Private Attributes
std::list< RangeType > ranges
Detailed Description
Definition at line 17 of file IntRange.h.
Member Typedef Documentation
RangeType
typedef Range<int> ACLIntRange::RangeType private
Definition at line 30 of file IntRange.h.
Constructor & Destructor Documentation
ACLIntRange()
ACLIntRange::ACLIntRange () inline
Definition at line 21 of file IntRange.h.
~ACLIntRange()
ACLIntRange::~ACLIntRange () override
Definition at line 67 of file IntRange.cc.
Member Function Documentation
dump()
SBufList ACLIntRange::dump () const override virtual
Implements ACLData< int >.
Definition at line 71 of file IntRange.cc.
References SBuf::Printf(), SBuf::push_back(), and ranges.
empty()
bool ACLIntRange::empty () const override virtual
Implements ACLData< int >.
Definition at line 49 of file IntRange.cc.
References ranges.
lineOptions()
virtual const Acl::Options & ACLData< int >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLIntRange::match (int i) override virtual
Implements ACLData< int >.
Definition at line 55 of file IntRange.cc.
References Range< C, S >::intersection(), ranges, and Range< C, S >::size().
parse()
void ACLIntRange::parse () override virtual
Implements ACLData< int >.
Definition at line 20 of file IntRange.cc.
References DBG_CRITICAL, debugs, ranges, self_destruct(), ConfigParser::strtokFile(), and xatos().
prepareForUse()
virtual void ACLData< int >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
ranges
std::list<RangeType> ACLIntRange::ranges private
Definition at line 31 of file IntRange.h.
Referenced by dump(), empty(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/IntRange.h
squid/src/acl/IntRange.cc