Squid Web Cache: Security::Extension Class Reference
Security::Extension Class Reference
TLS Hello Extension from RFC 5246 Section 7.4.1.4.
Public Types
typedef uint16_t Type
Public Member Functions
Extension (Parser::BinaryTokenizer &tk)
bool supported () const
Public Attributes
Type type
SBuf data
Detailed Description
Definition at line 91 of file Handshake.cc.
Member Typedef Documentation
Type
typedef uint16_t Security::Extension::Type
Definition at line 94 of file Handshake.cc.
Constructor & Destructor Documentation
Extension()
Security::Extension::Extension (Parser::BinaryTokenizer & tk) explicit
Definition at line 182 of file Handshake.cc.
References Parser::BinaryTokenizer::pstring16(), Parser::BinaryTokenizerContext::success(), and Parser::BinaryTokenizer::uint16().
Member Function Documentation
supported()
bool Security::Extension::supported () const
whether this extension is supported by Squid and, hence, may be bumped after peeking or spliced after staring (subject to other restrictions)
Definition at line 191 of file Handshake.cc.
References Security::SupportedExtensions().
Referenced by Security::HandshakeParser::parseExtensions().
Member Data Documentation
data
SBuf Security::Extension::data
Definition at line 102 of file Handshake.cc.
Referenced by Security::HandshakeParser::parseExtensions().
type
Type Security::Extension::type
Definition at line 101 of file Handshake.cc.
Referenced by Security::HandshakeParser::parseExtensions().
The documentation for this class was generated from the following file:
squid/src/security/Handshake.cc