Squid Web Cache: Adaptation::Icap::ChunkExtensionValueParser Class Reference
Adaptation::Icap::ChunkExtensionValueParser Class Reference
handles ICAP-specific chunk extensions supported by Squid
#include <ModXact.h>
Public Types
typedef ::Parser::Tokenizer Tokenizer
Public Member Functions
void parse (Tokenizer &tok, const SBuf &extName) override
extracts and then interprets (or ignores) the extension value
bool sawUseOriginalBody () const
uint64_t useOriginalBody () const
Static Public Member Functions
static void Ignore (Tokenizer &tok, const SBuf &extName)
extracts and ignores the value of a named extension
Private Attributes
int64_t useOriginalBody_ = -1
the value of the parsed use-original-body chunk extension (or -1)
Static Private Attributes
static const SBuf UseOriginalBodyName
Detailed Description
Definition at line 125 of file ModXact.h.
Member Typedef Documentation
Tokenizer
typedef ::Parser::Tokenizer Http::One::ChunkExtensionValueParser::Tokenizer inherited
Definition at line 32 of file TeChunkedParser.h.
Member Function Documentation
Ignore()
void Http::One::ChunkExtensionValueParser::Ignore (Tokenizer & tok, const SBuf & extName) static inherited
Definition at line 164 of file TeChunkedParser.cc.
References debugs, and Http::One::tokenOrQuotedString().
Referenced by Http::One::TeChunkedParser::parseOneChunkExtension().
parse()
void Adaptation::Icap::ChunkExtensionValueParser::parse (Tokenizer & tok, const SBuf & extName) override virtual
Implements Http::One::ChunkExtensionValueParser.
Definition at line 2072 of file ModXact.cc.
References assert.
sawUseOriginalBody()
bool Adaptation::Icap::ChunkExtensionValueParser::sawUseOriginalBody () const inline
Definition at line 131 of file ModXact.h.
References useOriginalBody_.
Referenced by useOriginalBody().
useOriginalBody()
uint64_t Adaptation::Icap::ChunkExtensionValueParser::useOriginalBody () const inline
Definition at line 132 of file ModXact.h.
References assert, sawUseOriginalBody(), and useOriginalBody_.
Member Data Documentation
useOriginalBody_
int64_t Adaptation::Icap::ChunkExtensionValueParser::useOriginalBody_ = -1 private
Definition at line 138 of file ModXact.h.
Referenced by sawUseOriginalBody(), and useOriginalBody().
UseOriginalBodyName
const SBuf Adaptation::Icap::ChunkExtensionValueParser::UseOriginalBodyName static private
Definition at line 135 of file ModXact.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/ModXact.h
squid/src/adaptation/icap/ModXact.cc