Squid Web Cache: MessageDelayPools Class Reference
MessageDelayPools Class Reference
Squid Components » Delay Pools API
#include <MessageDelayPools.h>
Public Member Functions
MessageDelayPools (const MessageDelayPools &)=delete
MessageDelayPools & operator= (const MessageDelayPools &)=delete
MessageDelayPool::Pointer pool (const SBuf &name)
returns a MessageDelayPool with a given name or null otherwise
void add (MessageDelayPool *pool)
appends a single MessageDelayPool, created during configuration
void freePools ()
memory cleanup, performing during reconfiguration
Static Public Member Functions
static MessageDelayPools * Instance ()
Public Attributes
std::vector< MessageDelayPool::Pointer > pools
Private Member Functions
MessageDelayPools ()
~MessageDelayPools ()
void Stats ()
Detailed Description
represents all configured 'response' delay pools
Definition at line 73 of file MessageDelayPools.h.
Constructor & Destructor Documentation
MessageDelayPools() [1/2]
MessageDelayPools::MessageDelayPools (const MessageDelayPools &) delete
MessageDelayPools() [2/2]
MessageDelayPools::MessageDelayPools () inline private
Definition at line 91 of file MessageDelayPools.h.
~MessageDelayPools()
MessageDelayPools::~MessageDelayPools () private
Definition at line 25 of file MessageDelayPools.cc.
References freePools().
Member Function Documentation
add()
void MessageDelayPools::add (MessageDelayPool * pool)
Definition at line 46 of file MessageDelayPools.cc.
References DBG_CRITICAL, debugs, MessageDelayPool::poolName, and pools.
Referenced by MessageDelayConfig::parseResponseDelayPool().
freePools()
void MessageDelayPools::freePools ()
Definition at line 58 of file MessageDelayPools.cc.
References pools.
Referenced by ~MessageDelayPools(), and MessageDelayConfig::freePools().
Instance()
MessageDelayPools * MessageDelayPools::Instance () static
Definition at line 31 of file MessageDelayPools.cc.
References pools.
Referenced by MessageDelayConfig::dumpResponseDelayPoolParameters(), MessageDelayConfig::freePools(), MessageDelayConfig::parseResponseDelayPool(), MessageDelayConfig::parseResponseDelayPoolAccess(), and Http::Stream::sendStartOfMessage().
operator=()
MessageDelayPools & MessageDelayPools::operator= (const MessageDelayPools &) delete
pool()
MessageDelayPool::Pointer MessageDelayPools::pool (const SBuf & name)
Definition at line 38 of file MessageDelayPools.cc.
References pools.
Referenced by MessageDelayConfig::parseResponseDelayPoolAccess().
Stats()
void MessageDelayPools::Stats () inline private
Definition at line 93 of file MessageDelayPools.h.
Member Data Documentation
pools
std::vector<MessageDelayPool::Pointer> MessageDelayPools::pools
Definition at line 88 of file MessageDelayPools.h.
Referenced by add(), MessageDelayConfig::dumpResponseDelayPoolParameters(), freePools(), Instance(), pool(), and Http::Stream::sendStartOfMessage().
The documentation for this class was generated from the following files:
squid/src/MessageDelayPools.h
squid/src/MessageDelayPools.cc