Squid Web Cache: Fs::Ufs::UFSStrategy Class Reference
Fs::Ufs::UFSStrategy Class Reference
Storage Filesystems » UFS Storage Filesystem
#include <UFSStrategy.h>
Public Member Functions
UFSStrategy (DiskIOStrategy *)
virtual ~UFSStrategy ()
virtual bool shedLoad ()
virtual int load ()
StoreIOState::Pointer createState (SwapDir *SD, StoreEntry *e, StoreIOState::STIOCB *callback, void *callback_data) const
virtual RefCount< DiskFile > newFile (char const *path)
StoreIOState::Pointer open (SwapDir *, StoreEntry *, StoreIOState::STIOCB *, void *)
StoreIOState::Pointer create (SwapDir *, StoreEntry *, StoreIOState::STIOCB *, void *)
virtual void unlinkFile (char const *)
virtual void sync ()
virtual int callback ()
virtual void init ()
virtual void statfs (StoreEntry &sentry) const
Public Attributes
DiskIOStrategy * io
Private Member Functions
UFSStrategy ()
UFSStrategy (UFSStrategy const &)
UFSStrategy & operator= (UFSStrategy const &)
Friends
class UFSSwapDir
Detailed Description
Definition at line 24 of file UFSStrategy.h.
Constructor & Destructor Documentation
UFSStrategy() [1/3]
Fs::Ufs::UFSStrategy::UFSStrategy (DiskIOStrategy * anIO)
Definition at line 31 of file UFSStrategy.cc.
~UFSStrategy()
Fs::Ufs::UFSStrategy::~UFSStrategy () virtual
Definition at line 34 of file UFSStrategy.cc.
UFSStrategy() [2/3]
Fs::Ufs::UFSStrategy::UFSStrategy () private
UFSStrategy() [3/3]
Fs::Ufs::UFSStrategy::UFSStrategy (UFSStrategy const &) private
Member Function Documentation
callback()
int Fs::Ufs::UFSStrategy::callback () virtual
Definition at line 140 of file UFSStrategy.cc.
References StoreIOState::callback.
create()
StoreIOState::Pointer Fs::Ufs::UFSStrategy::create (SwapDir * SD, StoreEntry * e, StoreIOState::STIOCB * aCallback, void * callback_data)
Definition at line 93 of file UFSStrategy.cc.
References asHex(), assert, DiskFile::create(), Fs::Ufs::UFSStoreState::creating, debugs, DiskFile::error(), RefCount< C >::getRaw(), StoreIOState::mode, StoreIOState::swap_filen, and Fs::Ufs::UFSStoreState::theFile.
createState()
StoreIOState::Pointer Fs::Ufs::UFSStrategy::createState (SwapDir * SD, StoreEntry * e, StoreIOState::STIOCB * callback, void * callback_data) const
Definition at line 40 of file UFSStrategy.cc.
init()
void Fs::Ufs::UFSStrategy::init () virtual
Init per-instance logic
Definition at line 146 of file UFSStrategy.cc.
load()
int Fs::Ufs::UFSStrategy::load () virtual
Definition at line 26 of file UFSStrategy.cc.
Referenced by Fs::Ufs::UFSSwapDir::canStore().
newFile()
DiskFile::Pointer Fs::Ufs::UFSStrategy::newFile (char const * path) virtual
Definition at line 46 of file UFSStrategy.cc.
open()
StoreIOState::Pointer Fs::Ufs::UFSStrategy::open (SwapDir * SD, StoreEntry * e, StoreIOState::STIOCB * aCallback, void * callback_data)
Definition at line 58 of file UFSStrategy.cc.
References asHex(), assert, debugs, DiskFile::error(), RefCount< C >::getRaw(), StoreIOState::mode, DiskFile::open(), Fs::Ufs::UFSStoreState::opening, StoreEntry::swap_filen, and Fs::Ufs::UFSStoreState::theFile.
operator=()
UFSStrategy & Fs::Ufs::UFSStrategy::operator= (UFSStrategy const &) private
shedLoad()
bool Fs::Ufs::UFSStrategy::shedLoad () virtual
Definition at line 20 of file UFSStrategy.cc.
References io, and DiskIOStrategy::shedLoad().
Referenced by Fs::Ufs::UFSSwapDir::canStore().
statfs()
void Fs::Ufs::UFSStrategy::statfs (StoreEntry & sentry) const virtual
cachemgr output on the IO instance stats
Definition at line 158 of file UFSStrategy.cc.
sync()
void Fs::Ufs::UFSStrategy::sync () virtual
Definition at line 152 of file UFSStrategy.cc.
unlinkFile()
void Fs::Ufs::UFSStrategy::unlinkFile (char const * path) virtual
Definition at line 52 of file UFSStrategy.cc.
Friends And Related Symbol Documentation
UFSSwapDir
friend class UFSSwapDir friend
Definition at line 55 of file UFSStrategy.h.
Member Data Documentation
io
DiskIOStrategy* Fs::Ufs::UFSStrategy::io
The io strategy in use
Definition at line 51 of file UFSStrategy.h.
Referenced by shedLoad(), and TestUfs::testUfsDefaultEngine().
The documentation for this class was generated from the following files:
squid/src/fs/ufs/UFSStrategy.h
squid/src/fs/ufs/UFSStrategy.cc