Squid Web Cache: TestStatHist Class Reference
TestStatHist Class Reference
Protected Member Functions
void testStatHistBaseEquality ()
void testStatHistBaseAssignment ()
void testStatHistLog ()
void testStatHistSum ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestStatHist)
CPPUNIT_TEST (testStatHistBaseEquality)
CPPUNIT_TEST (testStatHistBaseAssignment)
CPPUNIT_TEST (testStatHistLog)
CPPUNIT_TEST (testStatHistSum)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 14 of file testStatHist.cc.
Member Function Documentation
CPPUNIT_TEST() [1/4]
TestStatHist::CPPUNIT_TEST (testStatHistBaseAssignment) private
CPPUNIT_TEST() [2/4]
TestStatHist::CPPUNIT_TEST (testStatHistBaseEquality) private
CPPUNIT_TEST() [3/4]
TestStatHist::CPPUNIT_TEST (testStatHistLog) private
CPPUNIT_TEST() [4/4]
TestStatHist::CPPUNIT_TEST (testStatHistSum) private
CPPUNIT_TEST_SUITE()
TestStatHist::CPPUNIT_TEST_SUITE (TestStatHist) private
CPPUNIT_TEST_SUITE_END()
TestStatHist::CPPUNIT_TEST_SUITE_END () private
testStatHistBaseAssignment()
void TestStatHist::testStatHistBaseAssignment () protected
Definition at line 71 of file testStatHist.cc.
References StatHist::count(), StatHist::enumInit(), FIVE, and ZERO.
testStatHistBaseEquality()
void TestStatHist::testStatHistBaseEquality () protected
Definition at line 60 of file testStatHist.cc.
References StatHist::count(), StatHist::enumInit(), FIVE, and ZERO.
testStatHistLog()
void TestStatHist::testStatHistLog () protected
Definition at line 83 of file testStatHist.cc.
References StatHist::count(), InspectingStatHist::counter(), StatHist::logInit(), max(), and min().
testStatHistSum()
void TestStatHist::testStatHistSum () protected
Definition at line 102 of file testStatHist.cc.
References StatHist::count(), StatHist::logInit(), and s1.
The documentation for this class was generated from the following file:
squid/src/tests/testStatHist.cc