Squid Web Cache: HttpHdrScTarget Class Reference
HttpHdrScTarget Class Reference
#include <HttpHdrScTarget.h>
Public Member Functions
HttpHdrScTarget (const char *aTarget)
HttpHdrScTarget (const String &aTarget)
HttpHdrScTarget (const HttpHdrScTarget &)=delete
HttpHdrScTarget & operator= (const HttpHdrScTarget &)=delete
bool hasNoStore () const
void noStore (bool v)
bool noStore () const
void clearNoStore ()
bool hasNoStoreRemote () const
void noStoreRemote (bool v)
bool noStoreRemote () const
void clearNoStoreRemote ()
bool hasMaxAge () const
void maxAge (int v)
int maxAge () const
void clearMaxAge ()
bool hasMaxStale () const
void maxStale (int v)
int maxStale () const
void clearMaxStale ()
bool hasContent () const
void Content (const String &v)
String content () const
void clearContent ()
bool hasTarget () const
String Target () const
void mergeWith (const HttpHdrScTarget *new_sc)
void packInto (Packable *p) const
XXX: this function should be in HttpHdrScTarget.cc.
void updateStats (StatHist *) const
Static Public Attributes
static const int MAX_AGE_UNSET =-1
static const int MAX_STALE_UNSET =0
Private Member Functions
bool isSet (http_hdr_sc_type id) const
void setMask (http_hdr_sc_type id, bool newval)
Private Attributes
int mask = 0
int max_age = MAX_AGE_UNSET
int max_stale = MAX_STALE_UNSET
String content_
String target
Friends
class HttpHdrSc
Detailed Description
Representation of HTTP Surogate-Control header field targeted directive
See also
HttpHdrSc
Definition at line 24 of file HttpHdrScTarget.h.
Constructor & Destructor Documentation
HttpHdrScTarget() [1/3]
HttpHdrScTarget::HttpHdrScTarget (const char * aTarget) inline explicit
Definition at line 32 of file HttpHdrScTarget.h.
HttpHdrScTarget() [2/3]
HttpHdrScTarget::HttpHdrScTarget (const String & aTarget) inline explicit
Definition at line 33 of file HttpHdrScTarget.h.
HttpHdrScTarget() [3/3]
HttpHdrScTarget::HttpHdrScTarget (const HttpHdrScTarget &) explicit delete
Member Function Documentation
clearContent()
void HttpHdrScTarget::clearContent () inline
Definition at line 72 of file HttpHdrScTarget.h.
References String::clean(), content_, SC_CONTENT, and setMask().
Referenced by HttpHdrSc::parse().
clearMaxAge()
void HttpHdrScTarget::clearMaxAge () inline
Definition at line 58 of file HttpHdrScTarget.h.
References max_age, MAX_AGE_UNSET, SC_MAX_AGE, and setMask().
Referenced by HttpHdrSc::parse().
clearMaxStale()
void HttpHdrScTarget::clearMaxStale () inline
Definition at line 64 of file HttpHdrScTarget.h.
References max_stale, and MAX_STALE_UNSET.
Referenced by HttpHdrSc::parse().
clearNoStore()
void HttpHdrScTarget::clearNoStore () inline
Definition at line 40 of file HttpHdrScTarget.h.
References SC_NO_STORE, and setMask().
clearNoStoreRemote()
void HttpHdrScTarget::clearNoStoreRemote () inline
Definition at line 45 of file HttpHdrScTarget.h.
References SC_NO_STORE_REMOTE, and setMask().
content()
String HttpHdrScTarget::content () const inline
Definition at line 71 of file HttpHdrScTarget.h.
References content_.
Referenced by mergeWith().
Content()
void HttpHdrScTarget::Content (const String & v) inline
Definition at line 67 of file HttpHdrScTarget.h.
References content_, SC_CONTENT, and setMask().
Referenced by mergeWith().
hasContent()
bool HttpHdrScTarget::hasContent () const inline
Definition at line 66 of file HttpHdrScTarget.h.
References isSet(), and SC_CONTENT.
Referenced by mergeWith().
hasMaxAge()
bool HttpHdrScTarget::hasMaxAge () const inline
Definition at line 47 of file HttpHdrScTarget.h.
References isSet(), and SC_MAX_AGE.
Referenced by mergeWith(), and HttpStateData::processSurrogateControl().
hasMaxStale()
bool HttpHdrScTarget::hasMaxStale () const inline
Definition at line 61 of file HttpHdrScTarget.h.
References max_stale, and MAX_STALE_UNSET.
hasNoStore()
bool HttpHdrScTarget::hasNoStore () const inline
Definition at line 37 of file HttpHdrScTarget.h.
References isSet(), and SC_NO_STORE.
Referenced by mergeWith(), and HttpStateData::processSurrogateControl().
hasNoStoreRemote()
bool HttpHdrScTarget::hasNoStoreRemote () const inline
Definition at line 42 of file HttpHdrScTarget.h.
References isSet(), and SC_NO_STORE_REMOTE.
Referenced by mergeWith().
hasTarget()
bool HttpHdrScTarget::hasTarget () const inline
Definition at line 74 of file HttpHdrScTarget.h.
References String::size(), and target.
Referenced by packInto().
isSet()
bool HttpHdrScTarget::isSet (http_hdr_sc_type id) const inline private
Definition at line 82 of file HttpHdrScTarget.h.
References assert, EBIT_TEST, mask, SC_ENUM_END, and SC_NO_STORE.
Referenced by hasContent(), hasMaxAge(), hasNoStore(), hasNoStoreRemote(), noStore(), noStoreRemote(), packInto(), HttpHdrSc::parse(), and updateStats().
maxAge() [1/2]
int HttpHdrScTarget::maxAge () const inline
Definition at line 57 of file HttpHdrScTarget.h.
References max_age.
Referenced by mergeWith().
maxAge() [2/2]
void HttpHdrScTarget::maxAge (int v) inline
Definition at line 48 of file HttpHdrScTarget.h.
References max_age, MAX_AGE_UNSET, SC_MAX_AGE, and setMask().
Referenced by mergeWith(), HttpHdrSc::parse(), HttpStateData::processSurrogateControl(), and HttpHdrSc::setMaxAge().
maxStale() [1/2]
int HttpHdrScTarget::maxStale () const inline
Definition at line 63 of file HttpHdrScTarget.h.
References max_stale.
Referenced by mergeWith().
maxStale() [2/2]
void HttpHdrScTarget::maxStale (int v) inline
Definition at line 62 of file HttpHdrScTarget.h.
References max_stale.
Referenced by mergeWith(), HttpHdrSc::parse(), and HttpStateData::processSurrogateControl().
mergeWith()
void HttpHdrScTarget::mergeWith (const HttpHdrScTarget * new_sc)
Definition at line 18 of file HttpHdrScTarget.cc.
References assert, content(), Content(), hasContent(), hasMaxAge(), hasNoStore(), hasNoStoreRemote(), maxAge(), maxAge(), maxStale(), maxStale(), noStore(), and noStoreRemote().
Referenced by HttpHdrSc::getMergedTarget().
noStore() [1/2]
bool HttpHdrScTarget::noStore () const inline
Definition at line 39 of file HttpHdrScTarget.h.
References isSet(), and SC_NO_STORE.
Referenced by mergeWith().
noStore() [2/2]
void HttpHdrScTarget::noStore (bool v) inline
Definition at line 38 of file HttpHdrScTarget.h.
References SC_NO_STORE, and setMask().
Referenced by HttpHdrSc::parse().
noStoreRemote() [1/2]
bool HttpHdrScTarget::noStoreRemote () const inline
Definition at line 44 of file HttpHdrScTarget.h.
References isSet(), and SC_NO_STORE_REMOTE.
Referenced by mergeWith().
noStoreRemote() [2/2]
void HttpHdrScTarget::noStoreRemote (bool v) inline
Definition at line 43 of file HttpHdrScTarget.h.
References SC_NO_STORE_REMOTE, and setMask().
Referenced by HttpHdrSc::parse(), and HttpStateData::processSurrogateControl().
operator=()
HttpHdrScTarget & HttpHdrScTarget::operator= (const HttpHdrScTarget &) delete
packInto()
void HttpHdrScTarget::packInto (Packable * p) const
Definition at line 194 of file HttpHdrSc.cc.
References Packable::appendf(), assert, content_, hasTarget(), isSet(), max_age, SC_CONTENT, SC_ENUM_END, SC_MAX_AGE, SC_NO_STORE, SC_OTHER, ScAttrs, SQUIDSTRINGPH, SQUIDSTRINGPRINT, and target.
setMask()
void HttpHdrScTarget::setMask (http_hdr_sc_type id, bool newval) inline private
Definition at line 87 of file HttpHdrScTarget.h.
References EBIT_CLR, EBIT_SET, and mask.
Referenced by clearContent(), clearMaxAge(), clearNoStore(), clearNoStoreRemote(), Content(), maxAge(), noStore(), noStoreRemote(), and HttpHdrSc::parse().
Target()
String HttpHdrScTarget::Target () const inline
Definition at line 75 of file HttpHdrScTarget.h.
References target.
updateStats()
void HttpHdrScTarget::updateStats (StatHist * hist) const
Definition at line 42 of file HttpHdrScTarget.cc.
References StatHist::count(), isSet(), SC_ENUM_END, and SC_NO_STORE.
Friends And Related Symbol Documentation
HttpHdrSc
friend class HttpHdrSc friend
Definition at line 27 of file HttpHdrScTarget.h.
Member Data Documentation
content_
String HttpHdrScTarget::content_ private
Definition at line 95 of file HttpHdrScTarget.h.
Referenced by clearContent(), content(), Content(), packInto(), and HttpHdrSc::parse().
mask
int HttpHdrScTarget::mask = 0 private
Definition at line 92 of file HttpHdrScTarget.h.
Referenced by isSet(), and setMask().
max_age
int HttpHdrScTarget::max_age = MAX_AGE_UNSET private
Definition at line 93 of file HttpHdrScTarget.h.
Referenced by clearMaxAge(), maxAge(), maxAge(), and packInto().
MAX_AGE_UNSET
const int HttpHdrScTarget::MAX_AGE_UNSET =-1 static
Definition at line 29 of file HttpHdrScTarget.h.
Referenced by clearMaxAge(), and maxAge().
max_stale
int HttpHdrScTarget::max_stale = MAX_STALE_UNSET private
Definition at line 94 of file HttpHdrScTarget.h.
Referenced by clearMaxStale(), hasMaxStale(), maxStale(), and maxStale().
MAX_STALE_UNSET
const int HttpHdrScTarget::MAX_STALE_UNSET =0 static
Definition at line 30 of file HttpHdrScTarget.h.
Referenced by clearMaxStale(), and hasMaxStale().
target
String HttpHdrScTarget::target private
Definition at line 96 of file HttpHdrScTarget.h.
Referenced by hasTarget(), packInto(), and Target().
The documentation for this class was generated from the following files:
squid/src/HttpHdrScTarget.h
squid/src/HttpHdrSc.cc
squid/src/HttpHdrScTarget.cc