Squid Web Cache: Ipc::MemMapSlot Class Reference
Ipc::MemMapSlot Class Reference
a MemMap basic element, holding basic shareable memory block info
#include <MemMap.h>
Public Member Functions
MemMapSlot ()
size_t size () const
size_t keySize () const
bool sameKey (const cache_key *const aKey) const
void set (const unsigned char *aKey, const void *block, size_t blockSize, time_t expire=0)
bool empty () const
bool reading () const
bool writing () const
Public Attributes
std::atomic< uint8_t > waitingToBeFreed
may be accessed w/o a lock
ReadWriteLock lock
protects slot data below
unsigned char key [MEMMAP_SLOT_KEY_SIZE]
The entry key.
unsigned char p [MEMMAP_SLOT_DATA_SIZE]
The memory block;.
size_t pSize
time_t expire
Detailed Description
Definition at line 33 of file MemMap.h.
Constructor & Destructor Documentation
MemMapSlot()
Ipc::MemMapSlot::MemMapSlot ()
Definition at line 291 of file MemMap.cc.
References key, and p.
Referenced by size().
Member Function Documentation
empty()
bool Ipc::MemMapSlot::empty () const
Definition at line 316 of file MemMap.cc.
Referenced by Ipc::MemMap::freeLocked(), Ipc::MemMap::openForReadingAt(), and Ipc::MemMap::openForWritingAt().
keySize()
size_t Ipc::MemMapSlot::keySize () const inline
Definition at line 38 of file MemMap.h.
References key.
reading()
bool Ipc::MemMapSlot::reading () const inline
Definition at line 42 of file MemMap.h.
References lock, and Ipc::ReadWriteLock::readers.
Referenced by Ipc::MemMap::closeForReading(), Ipc::MemMap::openForWritingAt(), and Ipc::MemMap::peekAtReader().
sameKey()
bool Ipc::MemMapSlot::sameKey (const cache_key *const aKey) const
Definition at line 310 of file MemMap.cc.
set()
void Ipc::MemMapSlot::set (const unsigned char * aKey, const void * block, size_t blockSize, time_t expire = 0)
Definition at line 300 of file MemMap.cc.
size()
size_t Ipc::MemMapSlot::size () const inline
Definition at line 37 of file MemMap.h.
References MemMapSlot().
writing()
bool Ipc::MemMapSlot::writing () const inline
Definition at line 43 of file MemMap.h.
References lock, and Ipc::ReadWriteLock::writing.
Referenced by Ipc::MemMap::abortWriting(), Ipc::MemMap::closeForWriting(), Ipc::MemMap::openForWritingAt(), Ipc::MemMap::peekAtReader(), and Ipc::MemMap::switchWritingToReading().
Member Data Documentation
expire
time_t Ipc::MemMapSlot::expire
Definition at line 50 of file MemMap.h.
key
unsigned char Ipc::MemMapSlot::key[MEMMAP_SLOT_KEY_SIZE]
Definition at line 47 of file MemMap.h.
Referenced by MemMapSlot(), Ipc::MemMap::freeLocked(), and keySize().
lock
ReadWriteLock Ipc::MemMapSlot::lock mutable
Definition at line 46 of file MemMap.h.
Referenced by Ipc::MemMap::closeForReading(), Ipc::MemMap::closeForWriting(), Ipc::MemMap::free(), Ipc::MemMap::freeLocked(), Ipc::MemMap::openForReadingAt(), Ipc::MemMap::openForWritingAt(), reading(), Ipc::MemMap::switchWritingToReading(), and writing().
p
unsigned char Ipc::MemMapSlot::p[MEMMAP_SLOT_DATA_SIZE]
Definition at line 48 of file MemMap.h.
Referenced by MemMapSlot().
pSize
size_t Ipc::MemMapSlot::pSize
Definition at line 49 of file MemMap.h.
waitingToBeFreed
std::atomic<uint8_t> Ipc::MemMapSlot::waitingToBeFreed
Definition at line 45 of file MemMap.h.
Referenced by Ipc::MemMap::free(), Ipc::MemMap::freeLocked(), Ipc::MemMap::openForReadingAt(), and Ipc::MemMap::openForWritingAt().
The documentation for this class was generated from the following files:
squid/src/ipc/MemMap.h
squid/src/ipc/MemMap.cc