Squid Web Cache: SwapChecksum24 Class Reference
SwapChecksum24 Class Reference
maintains a 24-bit checksum over integer fields
#include <StoreSwapLogData.h>
Public Member Functions
SwapChecksum24 ()
bool operator== (const SwapChecksum24 &o) const
bool operator!= (const SwapChecksum24 &o) const
void set (uint32_t f1, uint32_t f2, uint32_t f3)
compute and store checksum based on three 32bit integers
void set (int32_t f1, uint64_t f2)
compute and store checksum based on int32_t and uint64_t integers
std::ostream & print (std::ostream &os) const
Private Attributes
uint8_t raw [3]
Detailed Description
Definition at line 40 of file StoreSwapLogData.h.
Constructor & Destructor Documentation
SwapChecksum24()
SwapChecksum24::SwapChecksum24 () inline
Definition at line 43 of file StoreSwapLogData.h.
References raw.
Member Function Documentation
operator!=()
bool SwapChecksum24::operator!= (const SwapChecksum24 & o) const inline
Definition at line 49 of file StoreSwapLogData.h.
operator==()
bool SwapChecksum24::operator== (const SwapChecksum24 & o) const inline
Definition at line 45 of file StoreSwapLogData.h.
References raw.
print()
std::ostream & SwapChecksum24::print (std::ostream & os) const
Definition at line 47 of file StoreSwapLogData.cc.
References raw.
Referenced by operator<<().
set() [1/2]
void SwapChecksum24::set (int32_t f1, uint64_t f2)
Same as 3-argument SwapChecksum24::set() but for int32_t and uint64_t.
Definition at line 38 of file StoreSwapLogData.cc.
References set().
set() [2/2]
void SwapChecksum24::set (uint32_t f1, uint32_t f2, uint32_t f3)
Definition at line 20 of file StoreSwapLogData.cc.
References raw.
Referenced by StoreSwapLogHeader::StoreSwapLogHeader(), StoreSwapLogData::finalize(), StoreSwapLogData::sane(), StoreSwapLogHeader::sane(), and set().
Member Data Documentation
raw
uint8_t SwapChecksum24::raw[3] private
Definition at line 63 of file StoreSwapLogData.h.
Referenced by SwapChecksum24(), operator==(), print(), and set().
The documentation for this class was generated from the following files:
squid/src/StoreSwapLogData.h
squid/src/StoreSwapLogData.cc