Squid Web Cache: ClientDelayConfig Class Reference
ClientDelayConfig Class Reference
#include <ClientDelayConfig.h>
Public Member Functions
ClientDelayConfig ()
ClientDelayConfig (const ClientDelayConfig &)=delete
ClientDelayConfig & operator= (const ClientDelayConfig &)=delete
void freePools ()
void dumpPoolCount (StoreEntry *entry, const char *name) const
void parsePoolCount ()
void parsePoolRates ()
void parsePoolAccess (ConfigParser &parser)
void finalize ()
checks pools configuration
Public Attributes
unsigned short initial
Private Member Functions
unsigned short parsePoolId ()
std::vector< ClientDelayPool::Pointer > & pools ()
ClientDelayPool & pool (const int i)
Detailed Description
Definition at line 54 of file ClientDelayConfig.h.
Constructor & Destructor Documentation
ClientDelayConfig() [1/2]
ClientDelayConfig::ClientDelayConfig () inline
Definition at line 57 of file ClientDelayConfig.h.
ClientDelayConfig() [2/2]
ClientDelayConfig::ClientDelayConfig (const ClientDelayConfig &) delete
Member Function Documentation
dumpPoolCount()
void ClientDelayConfig::dumpPoolCount (StoreEntry * entry, const char * name) const
Definition at line 57 of file ClientDelayConfig.cc.
References ClientDelayPools::Instance(), ClientDelayPools::pools, and storeAppendPrintf().
Referenced by dump_client_delay_pool_count().
finalize()
void ClientDelayConfig::finalize ()
Definition at line 45 of file ClientDelayConfig.cc.
References ClientDelayPool::access, DBG_IMPORTANT, debugs, pool(), and pools().
Referenced by mainInitialize(), and mainReconfigureFinish().
freePools()
void ClientDelayConfig::freePools ()
Definition at line 68 of file ClientDelayConfig.cc.
References pools().
Referenced by free_client_delay_pool_count(), and parsePoolCount().
operator=()
ClientDelayConfig & ClientDelayConfig::operator= (const ClientDelayConfig &) delete
parsePoolAccess()
void ClientDelayConfig::parsePoolAccess (ConfigParser & parser)
Definition at line 95 of file ClientDelayConfig.cc.
References aclParseAccessLine(), parsePoolId(), and pool().
Referenced by parse_client_delay_pool_access().
parsePoolCount()
void ClientDelayConfig::parsePoolCount ()
Definition at line 73 of file ClientDelayConfig.cc.
References DBG_CRITICAL, debugs, freePools(), ConfigParser::ParseUShort(), pools(), and size.
Referenced by parse_client_delay_pool_count().
parsePoolId()
unsigned short ClientDelayConfig::parsePoolId () private
Definition at line 102 of file ClientDelayConfig.cc.
References DBG_CRITICAL, debugs, ConfigParser::ParseUShort(), pools(), and size.
Referenced by parsePoolAccess(), and parsePoolRates().
parsePoolRates()
void ClientDelayConfig::parsePoolRates ()
Definition at line 86 of file ClientDelayConfig.cc.
References GetInteger(), GetInteger64(), ClientDelayPool::highwatermark, parsePoolId(), pool(), and ClientDelayPool::rate.
Referenced by parse_client_delay_pool_rates().
pool()
ClientDelayPool & ClientDelayConfig::pool (const int i) inline private
Definition at line 79 of file ClientDelayConfig.h.
References ClientDelayPools::Instance(), and ClientDelayPools::pools.
Referenced by finalize(), parsePoolAccess(), and parsePoolRates().
pools()
std::vector< ClientDelayPool::Pointer > & ClientDelayConfig::pools () inline private
Definition at line 78 of file ClientDelayConfig.h.
References ClientDelayPools::Instance(), and ClientDelayPools::pools.
Referenced by finalize(), freePools(), parsePoolCount(), and parsePoolId().
Member Data Documentation
initial
unsigned short ClientDelayConfig::initial
Definition at line 74 of file ClientDelayConfig.h.
Referenced by ConnStateData::whenClientIpKnown().
The documentation for this class was generated from the following files:
squid/src/ClientDelayConfig.h
squid/src/ClientDelayConfig.cc