Squid Web Cache: Ftp::Server Class Reference
Ftp::Server Class Reference abstract
Manages a control connection from an FTP client.
#include <FtpServer.h>
Public Types
typedef CbcPointer< AsyncJob > Pointer
typedef CbcPointer< BodyProducer > Pointer
Public Member Functions
Server (const MasterXaction::Pointer &xact)
~Server () override
void callException (const std::exception &e) override
called when the job throws during an async call
void startWaitingForOrigin ()
void stopWaitingForOrigin (int status)
bool reading () const
whether Comm::Read() is scheduled
void receivedFirstByte () override
Update flags and timeout after the first byte received.
bool handleReadData () override
void afterClientRead () override
processing to be done after a Comm::Read()
void afterClientWrite (size_t) override
processing to sync state after a Comm::Write()
void sendControlMsg (HttpControlMsg) override
called to send the 1xx message and notify the Source
void doneWithControlMsg () override
void readNextRequest ()
Traffic parsing.
void kick ()
try to make progress on a transaction or read more I/O
bool isOpen () const
int64_t mayNeedToReadMoreBody () const
const Auth::UserRequest::Pointer & getAuth () const
void setAuth (const Auth::UserRequest::Pointer &aur, const char *cause)
bool transparent () const
const char * stoppedReceiving () const
true if we stopped receiving the request
const char * stoppedSending () const
true if we stopped sending the response
void stopReceiving (const char *error)
note request receiving error and close as soon as we write the response
void stopSending (const char *error)
note response sending error and close as soon as we read the request
void resetReadTimeout (time_t timeout)
(re)sets timeout for receiving more bytes from the client
void extendLifetime ()
(re)sets client_lifetime timeout
void expectNoForwarding ()
cleans up virgin request [body] forwarding state
BodyPipe::Pointer expectRequestBody (int64_t size)
bool handleRequestBodyData ()
void notePinnedConnectionBecameIdle (PinnedIdleContext pic)
Called when a pinned connection becomes available for forwarding the next request.
void pinBusyConnection (const Comm::ConnectionPointer &pinServerConn, const HttpRequest::Pointer &request)
void unpinConnection (const bool andClose)
Undo pinConnection() and, optionally, close the pinned connection.
CachePeer * pinnedPeer () const
bool pinnedAuth () const
virtual void noteTakeServerConnectionControl (ServerConnectionContext)
void clientReadFtpData (const CommIoCbParams &io)
void connStateClosed (const CommCloseCbParams &io)
void requestTimeout (const CommTimeoutCbParams &params)
void lifetimeTimeout (const CommTimeoutCbParams &params)
bool doneAll () const override
whether positive goal has been reached
void swanSong () override
void quitAfterError (HttpRequest *request)
void stopPinnedConnectionMonitoring ()
The caller assumes responsibility for connection closure detection.
Security::IoResult acceptTls ()
void postHttpsAccept ()
the second part of old httpsAccept, waiting for future HttpsServer home
void startPeekAndSplice ()
Initializes and starts a peek-and-splice negotiation with the SSL client.
void doPeekAndSpliceStep ()
void httpsPeeked (PinnedIdleContext pic)
called by FwdState when it is done bumping the server
bool splice ()
Splice a bumped client connection on peek-and-splice mode.
void getSslContextStart ()
Start to create dynamic Security::ContextPointer for host or uses static port SSL context.
void getSslContextDone (Security::ContextPointer &)
finish configuring the newly created SSL context"
void sslCrtdHandleReply (const Helper::Reply &reply)
Process response from ssl_crtd.
void switchToHttps (ClientHttpRequest *, Ssl::BumpMode bumpServerMode)
void parseTlsHandshake ()
bool switchedToHttps () const
Ssl::ServerBump * serverBump ()
void setServerBump (Ssl::ServerBump *srvBump)
const SBuf & sslCommonName () const
void resetSslCommonName (const char *name)
const SBuf & tlsClientSni () const
void buildSslCertGenerationParams (Ssl::CertificateProperties &certProperties)
bool serveDelayedError (Http::Stream *)
char * prepareTlsSwitchingURL (const Http1::RequestParserPointer &hp)
void add (const Http::StreamPointer &context)
registers a newly created stream
void consumeInput (const size_t byteCount)
remove no longer needed leading bytes from the input buffer
Http::Stream * abortRequestParsing (const char *const errUri)
stop parsing the request and create context for relaying error info
bool fakeAConnectRequest (const char *reason, const SBuf &payload)
bool initiateTunneledRequest (HttpRequest::Pointer const &cause, const char *reason, const SBuf &payload)
generates and sends to tunnel.cc a fake request with a given payload
bool shouldPreserveClientData () const
ClientHttpRequest * buildFakeRequest (SBuf &useHost, AnyP::KnownPort usePort, const SBuf &payload)
build a fake http request
void startShutdown () override
void endingShutdown () override
NotePairs::Pointer notes ()
bool hasNotes () const
const ProxyProtocol::HeaderPointer & proxyProtocolHeader () const
void updateError (const Error &)
if necessary, stores new error information (if any)
void updateError (const err_type c, const ErrorDetailPointer &d)
emplacement/convenience wrapper for updateError(const Error &)
void fillChecklist (ACLFilledChecklist &) const override
configure the given checklist (to reflect the current transaction state)
void fillConnectionLevelDetails (ACLFilledChecklist &) const
void readSomeData ()
maybe grow the inBuf and schedule Comm::Read()
void stopReading ()
cancels Comm::Read() if it is scheduled
virtual void writeSomeData ()
maybe find some data to send and schedule a Comm::Write()
void write (MemBuf *mb)
schedule some data for a Comm::Write()
void write (char *buf, int len)
schedule some data for a Comm::Write()
bool writing () const
whether Comm::Write() is scheduled
void maybeMakeSpaceAvailable ()
grows the available read buffer space (if possible)
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
void wroteControlMsg (const CommIoCbParams &)
callback to handle Comm::Write completion
Static Public Member Functions
static Comm::ConnectionPointer BorrowPinnedConnection (HttpRequest *, const AccessLogEntryPointer &)
static void sslCrtdHandleReplyWrapper (void *data, const Helper::Reply &reply)
Callback function. It is called when squid receive message from ssl_crtd.
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
MasterState::Pointer master
info shared among our FTP client and server jobs
Http1::TeChunkedParser * bodyParser = nullptr
parses HTTP/1.1 chunked request body
Ip::Address log_addr
struct {
bool readMore = true
needs comm_read (for this request or new requests)
bool swanSang = false
} flags
struct {
Comm::ConnectionPointer serverConnection
char * host = nullptr
host name of pinned connection
AnyP::Port port
destination port of the request that caused serverConnection
bool pinned = false
this connection was pinned
bool auth = false
pinned for www authentication
bool reading = false
we are monitoring for peer connection closure
bool zeroReply = false
server closed w/o response (ERR_ZERO_SIZE_OBJECT)
bool peerAccessDenied = false
cache_peer_access denied pinned connection reuse
AsyncCall::Pointer readHandler
detects serverConnection closure
AsyncCall::Pointer closeHandler
The close handler for pinned server side connection.
} pinning
Ssl::BumpMode sslBumpMode = Ssl::bumpEnd
ssl_bump decision (Ssl::bumpEnd if n/a).
Security::HandshakeParser tlsParser
SBuf preservedClientData
Error bareError
a problem that occurred without a request (e.g., while parsing headers)
Security::KeyLogger keyLogger
managers logging of the being-accepted TLS connection secrets
Comm::ConnectionPointer clientConnection
AnyP::ProtocolVersion transferProtocol
SBuf inBuf
read I/O buffer for the client connection
bool receivedFirstByte_
true if at least one byte received on this connection
Pipeline pipeline
set of requests waiting to be serviced
const InstanceId< AsyncJob > id
job identifier
AsyncCall::Pointer cbControlMsgSent
Call to schedule when the control msg has been sent.
Protected Types
enum class EarlyErrorKind {
HugeRequest , MissingLogin , MissingUsername , MissingHost ,
UnsupportedCommand , InvalidUri , MalformedCommand
}
typedef bool(Ftp::Server::* RequestHandler) (String &cmd, String &params)
a method handling an FTP command; selected by handleRequest()
typedef void(Ftp::Server::* ReplyHandler) (const HttpReply *reply, StoreIOBuffer data)
a method handling an FTP response; selected by handleReply()
Protected Member Functions
Http::Stream * parseOneRequest () override
void processParsedRequest (Http::StreamPointer &context) override
start processing a freshly parsed request
void notePeerConnection (Comm::ConnectionPointer conn) override
called just before a FwdState-dispatched job starts using connection
void clientPinnedConnectionClosed (const CommCloseCbParams &io) override
Our close handler called by Comm when the pinned connection is closed.
void handleReply (HttpReply *header, StoreIOBuffer receivedData) override
int pipelinePrefetchMax () const override
returning N allows a pipeline of 1+N requests (see pipeline_prefetch)
bool writeControlMsgAndCall (HttpReply *rep, AsyncCall::Pointer &call) override
handle a control message received by context from a peer and call back
time_t idleTimeout () const override
timeout to use when waiting for the next request
void noteMoreBodySpaceAvailable (BodyPipe::Pointer) override
void noteBodyConsumerAborted (BodyPipe::Pointer ptr) override
void start () override
called by AsyncStart; do not call directly
void acceptDataConnection (const CommAcceptCbParams &params)
void readUploadData (const CommIoCbParams &io)
imports more upload data from the data connection
void wroteEarlyReply (const CommIoCbParams &io)
void wroteReply (const CommIoCbParams &io)
void wroteReplyData (const CommIoCbParams &io)
called when we are done writing a chunk of the response data
void connectedForData (const CommConnectCbParams &params)
Done establishing a data connection to the user.
unsigned int listenForDataConnection ()
bool createDataConnection (Ip::Address cltAddr)
[Re]initializes dataConn for active data transfers. Does not connect.
void closeDataConnection ()
void userDataCompletionCheckpoint (int finalStatusCode)
void completeDataDownload ()
void calcUri (const SBuf *file)
computes uri member from host and, if tracked, working dir with file name
void changeState (const Ftp::ServerState newState, const char *reason)
Http::Stream * handleUserRequest (const SBuf &cmd, SBuf &params)
bool checkDataConnPost () const
Check that client data connection is ready for immediate I/O.
void replyDataWritingCheckpoint ()
ClientStream checks after (actual or skipped) reply data writing.
void maybeReadUploadData ()
schedules another data connection read if needed
void setReply (const int code, const char *msg)
void writeCustomReply (const int code, const char *msg, const HttpReply *reply=nullptr)
void writeEarlyReply (const int code, const char *msg)
void writeErrorReply (const HttpReply *reply, const int status)
writes FTP error response with given status and reply-derived error details
void writeForwardedForeign (const HttpReply *reply)
void writeForwardedReply (const HttpReply *reply)
void writeForwardedReplyAndCall (const HttpReply *reply, AsyncCall::Pointer &call)
void writeReply (MemBuf &mb)
Http::Stream * earlyError (const EarlyErrorKind eek)
creates a context filled with an error message for a given early error
bool handleRequest (HttpRequest *)
void setDataCommand ()
bool checkDataConnPre ()
bool handleFeatRequest (String &cmd, String &params)
bool handlePasvRequest (String &cmd, String &params)
bool handlePortRequest (String &cmd, String &params)
bool handleDataRequest (String &cmd, String &params)
bool handleUploadRequest (String &cmd, String &params)
bool handleEprtRequest (String &cmd, String &params)
bool handleEpsvRequest (String &cmd, String &params)
bool handleCwdRequest (String &cmd, String &params)
bool handlePassRequest (String &cmd, String &params)
bool handleCdupRequest (String &cmd, String &params)
void handleFeatReply (const HttpReply *header, StoreIOBuffer receivedData)
void handlePasvReply (const HttpReply *header, StoreIOBuffer receivedData)
void handlePortReply (const HttpReply *header, StoreIOBuffer receivedData)
void handleErrorReply (const HttpReply *header, StoreIOBuffer receivedData)
void handleDataReply (const HttpReply *header, StoreIOBuffer receivedData)
void handleUploadReply (const HttpReply *header, StoreIOBuffer receivedData)
void handleEprtReply (const HttpReply *header, StoreIOBuffer receivedData)
void handleEpsvReply (const HttpReply *header, StoreIOBuffer receivedData)
void startDechunkingRequest ()
initialize dechunking state
void finishDechunkingRequest (bool withSuccess)
put parsed content into input buffer and clean up
void abortChunkedRequestBody (const err_type error)
quit on errors related to chunked request body handling
err_type handleChunkedRequestBody ()
parses available chunked encoded body bytes, checks size, returns errors
Comm::ConnectionPointer borrowPinnedConnection (HttpRequest *, const AccessLogEntryPointer &)
ConnStateData-specific part of BorrowPinnedConnection()
void startPinnedConnectionMonitoring ()
void clientPinnedConnectionRead (const CommIoCbParams &io)
bool handleIdleClientPinnedTlsRead ()
Http::Stream * parseHttpRequest (const Http1::RequestParserPointer &)
void whenClientIpKnown ()
bool tunnelOnError (const err_type)
initiate tunneling if possible or return false otherwise
bool mayBufferMoreRequestBytes () const
whether client_request_buffer_max_size allows inBuf.length() increase
void doClientRead (const CommIoCbParams &io)
void clientWriteDone (const CommIoCbParams &io)
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual const char * status () const
internal cleanup; do not call directly
void stopProducingFor (RefCount< BodyPipe > &, bool atEof)
Static Protected Member Functions
static void AcceptCtrlConnection (const CommAcceptCbParams &params)
accept a new FTP control connection and hand it to a dedicated Server
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
BodyPipe::Pointer bodyPipe
set when we are reading request body
bool preservingClientData_ = false
whether preservedClientData is valid and should be kept up to date
AsyncCall::Pointer writer
set when we are writing
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Types
typedef void(RegisteredRunner::* Method) ()
a pointer to one of the above notification methods
Private Member Functions
CBDATA_CHILD (Server)
void doProcessRequest ()
react to the freshly parsed request
void shovelUploadData ()
shovel upload data from the internal buffer to the body pipe if possible
void resetLogin (const char *reason)
clear client and server login-related state after the old login is gone
void terminateAll (const Error &, const LogTagsErrors &) override
abort any pending transactions and prevent new ones (by closing)
bool shouldCloseOnEof () const override
whether to stop serving our client after reading EOF on its connection
void checkLogging ()
log the last (attempt at) transaction if nobody else did
void parseRequests ()
void clientAfterReadingRequests ()
bool concurrentRequestQueueFilled () const
void pinConnection (const Comm::ConnectionPointer &pinServerConn, const HttpRequest &request)
Forward future client requests using the given server connection.
bool proxyProtocolValidateClient ()
bool parseProxyProtocolHeader ()
bool proxyProtocolError (const char *reason)
Security::ContextPointer getTlsContextFromCache (const SBuf &cacheKey, const Ssl::CertificateProperties &certProperties)
void storeTlsContextToCache (const SBuf &cacheKey, Security::ContextPointer &ctx)
void handleSslBumpHandshakeError (const Security::IoResult &)
process a problematic Security::Accept() result on the SslBump code path
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
void registerRunner ()
void unregisterRunner ()
unregisters self; safe to call multiple times
virtual void bootstrapConfig ()
virtual void finalizeConfig ()
virtual void claimMemoryNeeds ()
virtual void useConfig ()
virtual void startReconfigure ()
virtual void syncConfig ()
virtual void finishShutdown ()
Meant for cleanup of services needed by the already destroyed objects.
Private Attributes
SBuf uri
a URI reconstructed from various FTP message details
SBuf host
intended dest. of a transparently intercepted FTP conn
bool gotEpsvAll
restrict data conn setup commands to just EPSV
AsyncCall::Pointer onDataAcceptCall
who to call upon data conn acceptance
Comm::ConnectionPointer dataListenConn
data connection listening socket
Comm::ConnectionPointer dataConn
data connection
char uploadBuf [CLIENT_REQ_BUF_SZ]
data connection input buffer
size_t uploadAvailSize
number of yet unused uploadBuf bytes
AsyncCall::Pointer listener
set when we are passively listening
JobWait< Comm::ConnOpener > dataConnWait
AsyncCall::Pointer reader
set when we are reading FTP data
bool waitingForOrigin
whether we wait for the origin data transfer to end
bool originDataDownloadAbortedOnError
whether the origin data transfer aborted
HttpReply::Pointer delayedReply
a response which writing was postponed until stopWaitingForOrigin()
bool needProxyProtocolHeader_ = false
whether PROXY protocol header is still expected
ProxyProtocol::HeaderPointer proxyProtocolHeader_
the parsed PROXY protocol header
Auth::UserRequest::Pointer auth_
some user details that can be used to perform authentication on this connection
bool switchedToHttps_ = false
bool parsingTlsHandshake = false
uint64_t parsedBumpedRequestCount = 0
The number of parsed HTTP requests headers on a bumped client connection.
SBuf tlsConnectHostOrIp
The TLS server host name appears in CONNECT request or the server ip address for the intercepted requests.
AnyP::Port tlsConnectPort
The TLS server port number as passed in the CONNECT request.
SBuf sslCommonName_
CN name for SSL certificate generation.
SBuf tlsClientSni_
TLS client delivered SNI value. Empty string if none has been received.
SBuf sslBumpCertKey
Key to use to store/retrieve generated certificate.
Ssl::ServerBump * sslServerBump = nullptr
HTTPS server cert. fetching state for bump-ssl-server-first.
Ssl::CertSignAlgorithm signAlgorithm = Ssl::algSignTrusted
The signing algorithm to use.
const char * stoppedSending_ = nullptr
the reason why we no longer write the response or nil
const char * stoppedReceiving_ = nullptr
the reason why we no longer read the request or nil
NotePairs::Pointer theNotes
Friends
void StartListening ()
accept connections on all configured ftp_ports
Detailed Description
Definition at line 58 of file FtpServer.h.
Member Typedef Documentation
Method
typedef void(RegisteredRunner::* RegisteredRunner::Method) () inherited
Definition at line 94 of file RunnersRegistry.h.
Pointer [1/2]
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Pointer [2/2]
typedef CbcPointer<BodyProducer> BodyProducer::Pointer inherited
Definition at line 25 of file BodyPipe.h.
ReplyHandler
typedef void(Ftp::Server::* Ftp::Server::ReplyHandler) (const HttpReply *reply, StoreIOBuffer data) protected
Definition at line 169 of file FtpServer.h.
RequestHandler
typedef bool(Ftp::Server::* Ftp::Server::RequestHandler) (String &cmd, String &params) protected
Definition at line 156 of file FtpServer.h.
Member Enumeration Documentation
EarlyErrorKind
enum class Ftp::Server::EarlyErrorKind strong protected
Enumerator
HugeRequest
MissingLogin
MissingUsername
MissingHost
UnsupportedCommand
InvalidUri
MalformedCommand
Definition at line 86 of file FtpServer.h.
Constructor & Destructor Documentation
Server()
Server::Server (const MasterXaction::Pointer & xact) explicit
Definition at line 53 of file FtpServer.cc.
References ConnStateData::flags, ConnStateData::readMore, and uploadBuf.
~Server()
Server::~Server () override
Definition at line 74 of file FtpServer.cc.
Member Function Documentation
abortChunkedRequestBody()
void ConnStateData::abortChunkedRequestBody (const err_type error) protected inherited
Definition at line 2034 of file client_side.cc.
References assert, Server::clientConnection, comm_reset_close(), debugs, ERR_TOO_BIG, error(), ConnStateData::finishDechunkingRequest(), ConnStateData::flags, Pipeline::front(), clientReplyContext::http, Server::inBuf, NULL, Server::pipeline, ClientHttpRequest::request, Http::scContentTooLarge, clientReplyContext::setReplyToError(), and ClientHttpRequest::uri.
Referenced by ConnStateData::handleRequestBodyData().
abortRequestParsing()
Http::Stream * ConnStateData::abortRequestParsing (const char *const errUri) inherited
Definition at line 998 of file client_side.cc.
References ClientHttpRequest::client_stream, Server::clientConnection, clientGetMoreData, clientReplyDetach, clientReplyStatus, clientSocketDetach, clientSocketRecipient, clientStreamInit(), StoreIOBuffer::data, HTTP_REQBUF_SZ, Server::inBuf, SBuf::length(), StoreIOBuffer::length, ClientHttpRequest::req_sz, and ClientHttpRequest::setErrorUri().
Referenced by ConnStateData::parseHttpRequest(), and prepareAcceleratedURL().
AcceptCtrlConnection()
void Server::AcceptCtrlConnection (const CommAcceptCbParams & params) static protected
Definition at line 242 of file FtpServer.cc.
References Assure, CommCommonCbParams::conn, debugs, Comm::Connection::fd, fd_note(), CommCommonCbParams::flag, MasterXaction::MakePortful(), Comm::OK, CommAcceptCbParams::port, AsyncJob::Start(), CommCommonCbParams::xerrno, and xstrerr().
Referenced by Ftp::StartListening().
acceptDataConnection()
void Server::acceptDataConnection (const CommAcceptCbParams & params) protected
Definition at line 401 of file FtpServer.cc.
References Packable::appendf(), Comm::Connection::close(), CommCommonCbParams::conn, debugs, Comm::Connection::fd, fd_note(), CommCommonCbParams::flag, Ftp::fssHandleDataRequest, Ftp::fssHandleUploadRequest, MemBuf::init(), Comm::Connection::leaveOrphanage(), Must, Comm::OK, Comm::Connection::remote, Comm::Write(), CommCommonCbParams::xerrno, and xstrerr().
Referenced by listenForDataConnection().
acceptTls()
Security::IoResult ConnStateData::acceptTls () inherited
Starts or resumes accepting a TLS connection. TODO: Make this helper method protected after converting clientNegotiateSSL() into a method.
Definition at line 2220 of file client_side.cc.
References Security::Accept(), assert, Security::KeyLogger::checkpoint(), Server::clientConnection, Comm::Connection::fd, fd_table, and ConnStateData::keyLogger.
Referenced by clientNegotiateSSL(), and ConnStateData::startPeekAndSplice().
add()
void ConnStateData::add (const Http::StreamPointer & context) inherited
Definition at line 1702 of file client_side.cc.
References Pipeline::add(), assert, ConnStateData::bareError, Error::clear(), Pipeline::count(), debugs, Pipeline::nrequests, and Server::pipeline.
afterClientRead()
void ConnStateData::afterClientRead () override virtual inherited
Implements Server.
Definition at line 1910 of file client_side.cc.
References ConnStateData::clientAfterReadingRequests(), Server::clientConnection, Pipeline::empty(), Comm::Connection::fd, fd_note(), ConnStateData::isOpen(), ConnStateData::parseRequests(), ConnStateData::parseTlsHandshake(), ConnStateData::parsingTlsHandshake, and Server::pipeline.
afterClientWrite()
void ConnStateData::afterClientWrite (size_t) override virtual inherited
Reimplemented from Server.
Definition at line 983 of file client_side.cc.
References StatCounters::client_http, Pipeline::empty(), Pipeline::front(), StatCounters::hit_kbytes_out, StatCounters::kbytes_out, Server::pipeline, size, and statCounter.
bootstrapConfig()
virtual void RegisteredRunner::bootstrapConfig () inline virtual inherited
Called right before parsing squid.conf. Meant for initializing/preparing configuration parsing facilities.
Reimplemented in NtlmAuthRr.
Definition at line 46 of file RunnersRegistry.h.
Referenced by SquidMain().
BorrowPinnedConnection()
Comm::ConnectionPointer ConnStateData::BorrowPinnedConnection (HttpRequest * request, const AccessLogEntryPointer & ale) static inherited
Returns
validated pinned to-server connection, stopping its monitoring
Exceptions
a newly allocated ErrorState if validation fails
Definition at line 3867 of file client_side.cc.
References ERR_CANNOT_FORWARD, ErrorState::NewForwarding(), and HttpRequest::pinnedConnection().
Referenced by FwdState::usePinned(), and TunnelStateData::usePinned().
borrowPinnedConnection()
Comm::ConnectionPointer ConnStateData::borrowPinnedConnection (HttpRequest * request, const AccessLogEntryPointer & ale) protected inherited
Definition at line 3836 of file client_side.cc.
References debugs, ERR_CANNOT_FORWARD, ERR_ZERO_SIZE_OBJECT, AnyP::Uri::host(), Comm::IsConnOpen(), Must, ErrorState::NewForwarding(), ConnStateData::pinning, AnyP::Uri::port(), ConnStateData::stopPinnedConnectionMonitoring(), ConnStateData::unpinConnection(), and HttpRequest::url.
buildFakeRequest()
ClientHttpRequest * ConnStateData::buildFakeRequest (SBuf & useHost, AnyP::KnownPort usePort, const SBuf & payload) inherited
Definition at line 3165 of file client_side.cc.
References ClientHttpRequest::al, HttpRequest::auth_user_request, SBuf::c_str(), ClientHttpRequest::client_stream, Server::clientConnection, clientGetMoreData, clientReplyDetach, clientReplyStatus, clientSocketDetach, clientSocketRecipient, clientStreamInit(), StoreIOBuffer::data, HttpRequest::effectiveRequestUri(), ConnStateData::extendLifetime(), ConnStateData::flags, Http::Stream::flags, ConnStateData::getAuth(), RefCount< C >::getRaw(), Http::Message::header, AnyP::Uri::host(), Http::HOST, HTTP_REQBUF_SZ, Server::inBuf, ClientHttpRequest::initRequest(), StoreIOBuffer::length, MasterXaction::MakePortful(), HttpRequest::manager(), Http::Stream::mayUseConnection(), HttpRequest::method, Http::METHOD_CONNECT, Http::Stream::parsed_ok, AnyP::Uri::port(), ConnStateData::port, AnyP::PROTO_AUTHORITY_FORM, AnyP::PROTO_HTTPS, HttpHeader::putStr(), Http::Stream::registerWithConn(), Http::Stream::reqbuf, SBufToCstring(), AnyP::Uri::setScheme(), Http::Message::sources, Http::Message::srcHttp, Http::Message::srcHttps, ConnStateData::switchedToHttps(), ClientHttpRequest::uri, and HttpRequest::url.
Referenced by ConnStateData::fakeAConnectRequest(), and ConnStateData::initiateTunneledRequest().
buildSslCertGenerationParams()
void ConnStateData::buildSslCertGenerationParams (Ssl::CertificateProperties & certProperties) inherited
Fill the certAdaptParams with the required data for certificate adaptation and create the key for storing/retrieve the certificate to/from the cache
Definition at line 2571 of file client_side.cc.
References Ssl::algSetCommonName, Ssl::algSetValidAfter, Ssl::algSetValidBefore, Ssl::algSignEnd, Ssl::algSignTrusted, Ssl::algSignUntrusted, Acl::Answer::allowed(), assert, SBuf::c_str(), SquidConfig::cert_adapt, SquidConfig::cert_sign, Ssl::CertAdaptAlgorithmStr, Ssl::CertificateProperties::commonName, Config, Ssl::ServerBump::connectedOk(), debugs, Ssl::DefaultSignHash, ACLChecklist::fastCheck(), ConnStateData::fillChecklist(), Security::LockingPointer< T, UnLocker, Locker >::get(), RefCount< C >::getRaw(), SBuf::isEmpty(), Ssl::CertificateProperties::mimicCert, ConnStateData::port, Ssl::ServerBump::request, Security::LockingPointer< T, UnLocker, Locker >::resetAndLock(), Ssl::ServerBump::serverCert, Ssl::CertificateProperties::setCommonName, Ssl::CertificateProperties::setValidAfter, Ssl::CertificateProperties::setValidBefore, ConnStateData::signAlgorithm, Ssl::CertificateProperties::signAlgorithm, Ssl::CertificateProperties::signHash, Ssl::CertificateProperties::signWithPkey, Ssl::CertificateProperties::signWithX509, SquidConfig::ssl_client, ConnStateData::sslCommonName_, ConnStateData::sslServerBump, and ConnStateData::tlsConnectHostOrIp.
Referenced by ConnStateData::getSslContextStart().
calcUri()
void Server::calcUri (const SBuf * file) protected
Definition at line 345 of file FtpServer.cc.
References port.
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void Server::callException (const std::exception & e) override virtual
Reimplemented from ConnStateData.
Definition at line 1750 of file FtpServer.cc.
References AsyncJob::callException(), debugs, and Comm::IsConnOpen().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
CBDATA_CHILD()
Ftp::Server::CBDATA_CHILD (Server) private
changeState()
void Server::changeState (const Ftp::ServerState newState, const char * reason) protected
Definition at line 529 of file FtpServer.cc.
References debugs.
checkDataConnPost()
bool Server::checkDataConnPost () const protected
Definition at line 1692 of file FtpServer.cc.
References debugs, and Comm::IsConnOpen().
checkDataConnPre()
bool Server::checkDataConnPre () protected
check that client data connection is ready for future I/O or at least has a chance of becoming ready soon.
Definition at line 1661 of file FtpServer.cc.
References Config, SquidConfig::connect, connectedForData(), debugs, Comm::IsConnOpen(), JobCallback, and SquidConfig::Timeout.
checkLogging()
void ConnStateData::checkLogging () private inherited
Definition at line 3950 of file client_side.cc.
References assert, ConnStateData::bareError, Pipeline::empty(), Server::inBuf, SBuf::isEmpty(), SBuf::length(), Pipeline::nrequests, Server::pipeline, ClientHttpRequest::req_sz, ClientHttpRequest::setErrorUri(), and ClientHttpRequest::updateError().
Referenced by ConnStateData::swanSong().
claimMemoryNeeds()
virtual void RegisteredRunner::claimMemoryNeeds () inline virtual inherited
Called after finalizeConfig(). Meant for announcing memory reservations before memory is allocated.
Reimplemented in IpcIoRr, and MemStoreRr.
Definition at line 55 of file RunnersRegistry.h.
Referenced by RunConfigUsers().
clientAfterReadingRequests()
void ConnStateData::clientAfterReadingRequests () private inherited
Definition at line 1417 of file client_side.cc.
References Server::clientConnection, Comm::Connection::close(), commIsHalfClosed(), debugs, Comm::Connection::fd, ConnStateData::flags, ConnStateData::mayNeedToReadMoreBody(), and Server::readSomeData().
Referenced by ConnStateData::afterClientRead().
clientPinnedConnectionClosed()
void Server::clientPinnedConnectionClosed (const CommCloseCbParams & io) override protected virtual
Reimplemented from ConnStateData.
Definition at line 316 of file FtpServer.cc.
References ConnStateData::clientPinnedConnectionClosed(), and Comm::IsConnOpen().
clientPinnedConnectionRead()
void ConnStateData::clientPinnedConnectionRead (const CommIoCbParams & io) protected inherited
Our read handler called by Comm when the server either closes an idle pinned connection or perhaps unexpectedly sends something on that idle (from Squid p.o.v.) connection.
Definition at line 3807 of file client_side.cc.
References Server::clientConnection, Comm::Connection::close(), CommCommonCbParams::conn, debugs, Pipeline::empty(), Comm::ERR_CLOSING, CommCommonCbParams::flag, ConnStateData::handleIdleClientPinnedTlsRead(), Must, ConnStateData::pinning, Server::pipeline, and CommIoCbParams::size.
Referenced by ConnStateData::startPinnedConnectionMonitoring().
clientReadFtpData()
void ConnStateData::clientReadFtpData (const CommIoCbParams & io) inherited
clientWriteDone()
void Server::clientWriteDone (const CommIoCbParams & io) protected inherited
callback handling the Comm::Write completion
Will call afterClientWrite(size_t) to sync the I/O state. Then writeSomeData() to initiate any followup writes that could be immediately done.
Definition at line 211 of file Server.cc.
References Server::afterClientWrite(), Server::clientConnection, CommCommonCbParams::conn, debugs, Comm::ERR_CLOSING, ERR_WRITE_ERROR, Comm::Connection::fd, CommCommonCbParams::flag, LogTagsErrors::FromErrno(), Comm::IsConnOpen(), Must, SysErrorDetail::NewIfAny(), CommIoCbParams::size, Server::terminateAll(), Server::writer, Server::writeSomeData(), CommCommonCbParams::xerrno, and xstrerr().
Referenced by Server::write(), and Server::write().
closeDataConnection()
void Server::closeDataConnection () protected
Definition at line 445 of file FtpServer.cc.
References debugs, Comm::IsConnOpen(), and Comm::ReadCancel().
completeDataDownload()
void Server::completeDataDownload () protected
Writes the data-transfer status reply to the FTP client and closes the data connection.
Definition at line 1834 of file FtpServer.cc.
concurrentRequestQueueFilled()
bool ConnStateData::concurrentRequestQueueFilled () const private inherited
Limit the number of concurrent requests.
Returns
true when there are available position(s) in the pipeline queue for another request.
false when the pipeline queue is full or disabled.
Definition at line 1730 of file client_side.cc.
References Ssl::bumpSplice, Server::clientConnection, Pipeline::count(), debugs, Server::pipeline, ConnStateData::pipelinePrefetchMax(), ConnStateData::sslBumpMode, and ConnStateData::transparent().
Referenced by ConnStateData::parseRequests().
connectedForData()
void Server::connectedForData (const CommConnectCbParams & params) protected
Definition at line 1703 of file FtpServer.cc.
References assert, CommCommonCbParams::conn, Comm::Connection::fd, fd_note(), CommCommonCbParams::flag, Comm::IsConnOpen(), Must, and Comm::OK.
Referenced by checkDataConnPre().
connStateClosed()
void ConnStateData::connStateClosed (const CommCloseCbParams & io) inherited
Definition at line 483 of file client_side.cc.
References Server::clientConnection, AsyncJob::deleteThis(), and Comm::Connection::noteClosure().
Referenced by ConnStateData::start().
consumeInput()
void ConnStateData::consumeInput (const size_t byteCount) inherited
Definition at line 1409 of file client_side.cc.
References assert, SBuf::consume(), debugs, Server::inBuf, and SBuf::length().
Referenced by ConnStateData::handleRequestBodyData(), and ConnStateData::parseHttpRequest().
createDataConnection()
bool Server::createDataConnection (Ip::Address cltAddr) protected
Definition at line 1432 of file FtpServer.cc.
References assert, COMM_DOBIND, COMM_INTERCEPTION, COMM_TRANSPARENT, debugs, Comm::Connection::flags, Ip::Address::isIPv4(), Comm::Connection::local, Ip::Address::port(), Comm::Connection::remote, Comm::Connection::setAddrs(), Ip::Address::setAnyAddr(), and Ip::Address::setIPv4().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
doClientRead()
void Server::doClientRead (const CommIoCbParams & io) protected inherited
Definition at line 115 of file Server.cc.
References LogTagsErrors::aborted, Server::afterClientRead(), assert, Assure, StatCounters::client_http, Server::clientConnection, commMarkHalfClosed(), Config, CommCommonCbParams::conn, debugs, Comm::ENDFILE, ERR_CLIENT_GONE, Comm::ERR_CLOSING, ERR_READ_ERROR, Comm::Connection::fd, fd_note(), fd_table, CommCommonCbParams::flag, LogTagsErrors::FromErrno(), Server::handleReadData(), Server::inBuf, Comm::INPROGRESS, Comm::IsConnOpen(), SBuf::isEmpty(), StatCounters::kbytes_in, SBuf::length(), SquidConfig::maxRequestBufferSize, Server::maybeMakeSpaceAvailable(), Server::mayBufferMoreRequestBytes(), Must, SysErrorDetail::NewIfAny(), Comm::OK, Server::reader, Server::reading(), Comm::ReadNow(), Server::readSomeData(), Server::receivedFirstByte(), Server::receivedFirstByte_, Server::shouldCloseOnEof(), CommIoCbParams::size, SBuf::spaceSize(), statCounter, Server::terminateAll(), CommCommonCbParams::xerrno, and xstrerr().
Referenced by Server::readSomeData().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool ConnStateData::doneAll () const inline override virtual inherited
Reimplemented from AsyncJob.
Definition at line 239 of file client_side.h.
References AsyncJob::doneAll().
doneWithControlMsg()
void ConnStateData::doneWithControlMsg () override virtual inherited
Reimplemented from HttpControlMsgSink.
Definition at line 3648 of file client_side.cc.
References Server::clientConnection, ClientSocketContextPushDeferredIfNeeded(), debugs, HttpControlMsgSink::doneWithControlMsg(), Pipeline::front(), and Server::pipeline.
Referenced by ConnStateData::sendControlMsg().
doPeekAndSpliceStep()
void ConnStateData::doPeekAndSpliceStep () inherited
Called when a peek-and-splice step finished. For example after server SSL certificates received and fake server SSL certificates generated
Definition at line 3056 of file client_side.cc.
References assert, BIO_get_data(), Server::clientConnection, clientNegotiateSSL(), COMM_SELECT_WRITE, debugs, Comm::Connection::fd, fd_table, Ssl::ClientBio::hold(), Comm::SetSelect(), and ConnStateData::switchedToHttps_.
Referenced by ConnStateData::getSslContextStart(), and ConnStateData::sslCrtdHandleReply().
doProcessRequest()
void Server::doProcessRequest () private
Definition at line 128 of file FtpServer.cc.
References assert, clientProcessRequest(), clientSetKeepaliveFlag(), debugs, RefCount< C >::getRaw(), Must, ClientHttpRequest::request, and ClientHttpRequest::storeEntry().
earlyError()
Http::Stream * Server::earlyError (const EarlyErrorKind eek) protected
Definition at line 570 of file FtpServer.cc.
References Http::Stream::getClientReplyContext(), Ftp::HttpReplyWrapper(), Must, Http::scBadRequest, and clientReplyContext::setReplyToReply().
endingShutdown()
void ConnStateData::endingShutdown () override virtual inherited
Called after shutdown_lifetime grace period ends and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented from RegisteredRunner.
Definition at line 1025 of file client_side.cc.
References Server::clientConnection, Comm::Connection::close(), and Comm::IsConnOpen().
Referenced by ConnStateData::startShutdown().
expectNoForwarding()
void ConnStateData::expectNoForwarding () inherited
Definition at line 3571 of file client_side.cc.
References ConnStateData::bodyPipe, debugs, BodyPipe::expectNoConsumption(), and BodyPipe::status().
Referenced by ClientHttpRequest::calloutsError().
expectRequestBody()
BodyPipe::Pointer ConnStateData::expectRequestBody (int64_t size) inherited
Definition at line 3522 of file client_side.cc.
References ConnStateData::bodyPipe, BodyPipe::setBodySize(), size, and ConnStateData::startDechunkingRequest().
Referenced by clientProcessRequest().
extendLifetime()
void ConnStateData::extendLifetime () inherited
Definition at line 582 of file client_side.cc.
References Server::clientConnection, commSetConnTimeout(), Config, JobCallback, SquidConfig::lifetime, ConnStateData::lifetimeTimeout(), and SquidConfig::Timeout.
Referenced by ConnStateData::buildFakeRequest(), and ConnStateData::parseRequests().
fakeAConnectRequest()
bool ConnStateData::fakeAConnectRequest (const char * reason, const SBuf & payload) inherited
generate a fake CONNECT request with the given payload at the beginning of the client I/O buffer
Definition at line 3136 of file client_side.cc.
References assert, SBuf::assign(), ConnStateData::buildFakeRequest(), ClientHttpRequest::calloutContext, Server::clientConnection, clientProcessRequestFinished(), debugs, ClientHttpRequest::doCallouts(), SBuf::isEmpty(), Comm::Connection::local, MAX_IPSTRLEN, Ip::Address::port(), ClientHttpRequest::request, ConnStateData::tlsClientSni_, Ip::Address::toHostStr(), and ConnStateData::transparent().
Referenced by httpsSslBumpAccessCheckDone(), and ConnStateData::splice().
fillChecklist()
void ConnStateData::fillChecklist (ACLFilledChecklist &) const override virtual inherited
Implements Acl::ChecklistFiller.
Definition at line 3482 of file client_side.cc.
References clientAclChecklistFill(), Pipeline::front(), Server::pipeline, and ACLFilledChecklist::setConn().
Referenced by ConnStateData::buildSslCertGenerationParams(), ConnStateData::postHttpsAccept(), ConnStateData::proxyProtocolValidateClient(), ConnStateData::startPeekAndSplice(), ConnStateData::tunnelOnError(), and ConnStateData::whenClientIpKnown().
fillConnectionLevelDetails()
void ConnStateData::fillConnectionLevelDetails (ACLFilledChecklist & checklist) const inherited
fillChecklist() obligations not fulfilled by the front request TODO: This is a temporary ACLFilledChecklist::setConn() callback to allow filling checklist using our non-public information sources. It should be removed as unnecessary by making ACLs extract the information they need from the ACLFilledChecklist::conn() without filling/copying.
Definition at line 3499 of file client_side.cc.
References assert, Server::clientConnection, ACLFilledChecklist::conn(), Comm::Connection::local, ACLFilledChecklist::my_addr, Comm::Connection::remote, ACLFilledChecklist::request, ACLFilledChecklist::src_addr, ACLFilledChecklist::sslErrors, Ssl::ServerBump::sslErrors(), and ConnStateData::sslServerBump.
Referenced by ACLFilledChecklist::setConn().
finalizeConfig()
virtual void RegisteredRunner::finalizeConfig () inline virtual inherited
Called after parsing squid.conf. Meant for setting configuration options that depend on other configuration options and were not explicitly configured.
Reimplemented in sslBumpCfgRr, MemStoreRr, and SnmpRr.
Definition at line 51 of file RunnersRegistry.h.
Referenced by SquidMain().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
finishDechunkingRequest()
void ConnStateData::finishDechunkingRequest (bool withSuccess) protected inherited
Definition at line 3591 of file client_side.cc.
References ConnStateData::bodyParser, ConnStateData::bodyPipe, BodyPipe::bodySize(), BodyPipe::bodySizeKnown(), debugs, Pipeline::front(), Must, Server::pipeline, BodyPipe::status(), and BodyProducer::stopProducingFor().
Referenced by ConnStateData::abortChunkedRequestBody(), and ConnStateData::handleChunkedRequestBody().
finishShutdown()
virtual void RegisteredRunner::finishShutdown () inline virtual inherited
Definition at line 91 of file RunnersRegistry.h.
Referenced by RunRegistered(), SquidShutdown(), TestRock::tearDown(), and watch_child().
getAuth()
const Auth::UserRequest::Pointer & ConnStateData::getAuth () const inline inherited
Fetch the user details for connection based authentication NOTE: this is ONLY connection based because NTLM and Negotiate is against HTTP spec.
Definition at line 123 of file client_side.h.
References ConnStateData::auth_.
Referenced by Auth::UserRequest::authenticate(), AuthenticateAcl(), authTryGetUser(), ConnStateData::buildFakeRequest(), ClientHttpRequest::calloutsError(), ClientRequestContext::clientAccessCheckDone(), clientProcessRequest(), constructHelperQuery(), and ClientRequestContext::hostHeaderVerifyFailed().
getSslContextDone()
void ConnStateData::getSslContextDone (Security::ContextPointer & ctx) inherited
Definition at line 2735 of file client_side.cc.
References BIO_get_data(), SBuf::clear(), Server::clientConnection, clientNegotiateSSL(), Comm::Connection::close(), Config, DBG_IMPORTANT, debugs, Comm::Connection::fd, fd_table, httpsCreate(), Server::inBuf, ConnStateData::port, Comm::Connection::remote, SquidConfig::request, ConnStateData::resetReadTimeout(), Ssl::ClientBio::setReadBufData(), ConnStateData::switchedToHttps_, SquidConfig::Timeout, and ConnStateData::tlsConnectHostOrIp.
Referenced by ConnStateData::getSslContextStart(), and ConnStateData::sslCrtdHandleReply().
getSslContextStart()
void ConnStateData::getSslContextStart () inherited
Definition at line 2675 of file client_side.cc.
References Ssl::ServerBump::act, Ssl::algSignTrusted, assert, ConnStateData::buildSslCertGenerationParams(), Ssl::bumpPeek, Ssl::bumpStare, SBuf::clear(), Server::clientConnection, Ssl::CrtdMessage::code_new_certificate, Ssl::CertificateProperties::commonName, Ssl::CrtdMessage::compose(), Ssl::CrtdMessage::composeRequest(), Ssl::configureSSL(), Ssl::configureUnconfiguredSslContext(), DBG_IMPORTANT, debugs, ConnStateData::doPeekAndSpliceStep(), Comm::Connection::fd, fd_table, Ssl::GenerateSslContext(), Security::GetFrom(), ConnStateData::getSslContextDone(), ConnStateData::getTlsContextFromCache(), Ssl::InRamCertificateDbKey(), SBuf::isEmpty(), ConnStateData::port, Ssl::CrtdMessage::REQUEST, Ssl::CrtdMessage::setCode(), ConnStateData::signAlgorithm, Ssl::CertificateProperties::signAlgorithm, ConnStateData::sslBumpCertKey, ConnStateData::sslCrtdHandleReplyWrapper(), ConnStateData::sslServerBump, Ssl::ServerBump::step1, ConnStateData::storeTlsContextToCache(), and Ssl::Helper::Submit().
Referenced by ConnStateData::httpsPeeked(), and ConnStateData::parseTlsHandshake().
getTlsContextFromCache()
Security::ContextPointer ConnStateData::getTlsContextFromCache (const SBuf & cacheKey, const Ssl::CertificateProperties & certProperties) private inherited
Returns
a pointer to the matching cached TLS context or nil
Definition at line 2647 of file client_side.cc.
References Ssl::CertificateProperties::commonName, debugs, Ssl::GlobalContextStorage::getLocalStorage(), ConnStateData::port, Ssl::TheGlobalContextStorage(), and Ssl::verifySslCertificate().
Referenced by ConnStateData::getSslContextStart().
handleCdupRequest()
bool Server::handleCdupRequest (String & cmd, String & params) protected
Definition at line 1635 of file FtpServer.cc.
References Ftp::fssHandleCdup.
Referenced by handleRequest().
handleChunkedRequestBody()
err_type ConnStateData::handleChunkedRequestBody () protected inherited
Definition at line 1993 of file client_side.cc.
References ConnStateData::bodyParser, ConnStateData::bodyPipe, BodyPipeCheckout::buf, BodyPipe::buf(), BodyPipeCheckout::checkIn(), Server::clientConnection, clientIsRequestBodyTooLargeForPolicy(), debugs, ERR_INVALID_REQ, ERR_NONE, ERR_TOO_BIG, ConnStateData::finishDechunkingRequest(), MemBuf::hasContent(), Server::inBuf, SBuf::isEmpty(), SBuf::length(), BodyPipe::mayNeedMoreData(), Must, Http::One::Parser::needsMoreData(), Http::One::TeChunkedParser::needsMoreSpace(), Http::One::TeChunkedParser::parse(), BodyPipe::producedSize(), Http::One::Parser::remaining(), Http::One::TeChunkedParser::setPayloadBuffer(), and BodyPipe::status().
Referenced by ConnStateData::handleRequestBodyData().
handleCwdRequest()
bool Server::handleCwdRequest (String & cmd, String & params) protected
Definition at line 1621 of file FtpServer.cc.
References Ftp::fssHandleCwd.
Referenced by handleRequest().
handleDataReply()
void Server::handleDataReply (const HttpReply * header, StoreIOBuffer receivedData) protected
Definition at line 943 of file FtpServer.cc.
References MemBuf::append(), StoreIOBuffer::data, debugs, MemBuf::init(), Comm::IsConnOpen(), JobCallback, StoreIOBuffer::length, Http::scOkay, HttpReply::sline, Http::StatusLine::status(), Comm::Write(), and wroteReplyData().
Referenced by handleReply().
handleDataRequest()
bool Server::handleDataRequest (String & cmd, String & params) protected
Definition at line 1520 of file FtpServer.cc.
References Ftp::fssHandleDataRequest.
Referenced by handleRequest().
handleEprtReply()
void Server::handleEprtReply (const HttpReply * header, StoreIOBuffer receivedData) protected
Definition at line 1059 of file FtpServer.cc.
Referenced by handleReply().
handleEprtRequest()
bool Server::handleEprtRequest (String & cmd, String & params) protected
Definition at line 1567 of file FtpServer.cc.
References debugs, Ftp::fssHandleEprt, Ftp::ParseProtoIpPort(), String::size(), and String::termedBuf().
Referenced by handleRequest().
handleEpsvReply()
void Server::handleEpsvReply (const HttpReply * header, StoreIOBuffer receivedData) protected
Definition at line 1072 of file FtpServer.cc.
References Packable::appendf(), MemBuf::buf, debugs, MemBuf::init(), and MemBuf::size.
Referenced by handleReply().
handleEpsvRequest()
bool Server::handleEpsvRequest (String & cmd, String & params) protected
Definition at line 1596 of file FtpServer.cc.
References String::caseCmp(), String::cmp(), debugs, Ftp::fssHandleEpsv, and String::size().
Referenced by handleRequest().
handleErrorReply()
void Server::handleErrorReply (const HttpReply * header, StoreIOBuffer receivedData) protected
Definition at line 934 of file FtpServer.cc.
Referenced by handleReply().
handleFeatReply()
void Server::handleFeatReply (const HttpReply * header, StoreIOBuffer receivedData) protected
Definition at line 812 of file FtpServer.cc.
References HttpHeader::addEntry(), Ftp::cmdEprt(), Ftp::cmdEpsv(), CharacterSet::complement(), Http::FTP_PRE, Http::FTP_STATUS, HttpHeader::getEntry(), HttpHeader::getInt(), RefCount< C >::getRaw(), Http::Message::header, HttpHeaderInitPos, Ftp::HttpReplyWrapper(), Must, HttpHeader::putStr(), HttpHeader::refreshMask(), Http::scNoContent, CharacterSet::SP, Ftp::SupportedCommand(), and SBuf::toUpper().
Referenced by handleReply().
handleFeatRequest()
bool Server::handleFeatRequest (String & cmd, String & params) protected
Definition at line 1406 of file FtpServer.cc.
References Ftp::fssHandleFeat.
Referenced by handleRequest().
handleIdleClientPinnedTlsRead()
bool ConnStateData::handleIdleClientPinnedTlsRead () protected inherited
Handles a ready-for-reading TLS squid-to-server connection that we thought was idle.
Returns
false if and only if the connection should be closed.
Definition at line 3765 of file client_side.cc.
References DBG_IMPORTANT, debugs, error(), fd_table, Must, ConnStateData::pinning, and ConnStateData::startPinnedConnectionMonitoring().
Referenced by ConnStateData::clientPinnedConnectionRead().
handlePassRequest()
bool Server::handlePassRequest (String & cmd, String & params) protected
Definition at line 1628 of file FtpServer.cc.
References Ftp::fssHandlePass.
Referenced by handleRequest().
handlePasvReply()
void Server::handlePasvReply (const HttpReply * header, StoreIOBuffer receivedData) protected
Definition at line 881 of file FtpServer.cc.
References Packable::appendf(), assert, MemBuf::buf, debugs, MemBuf::init(), MAX_IPSTRLEN, server, MemBuf::size, and Ip::Address::toStr().
Referenced by handleReply().
handlePasvRequest()
bool Server::handlePasvRequest (String & cmd, String & params) protected
Definition at line 1413 of file FtpServer.cc.
References Ftp::fssHandlePasv, and String::size().
Referenced by handleRequest().
handlePortReply()
void Server::handlePortReply (const HttpReply * header, StoreIOBuffer receivedData) protected
Definition at line 921 of file FtpServer.cc.
Referenced by handleReply().
handlePortRequest()
bool Server::handlePortRequest (String & cmd, String & params) protected
Definition at line 1491 of file FtpServer.cc.
References Ftp::fssHandlePort, Ftp::ParseIpPort(), String::size(), and String::termedBuf().
Referenced by handleRequest().
handleReadData()
bool ConnStateData::handleReadData () override virtual inherited
called when new request data has been read from the socket
Return values
false called comm_close or setReplyToError (the caller should bail)
true we did not call comm_close or setReplyToError
Implements Server.
Definition at line 1938 of file client_side.cc.
References ConnStateData::bodyPipe, and ConnStateData::handleRequestBodyData().
handleReply()
void Server::handleReply (HttpReply * header, StoreIOBuffer receivedData) override protected virtual
ClientStream calls this to supply response header (once) and data for the current Http::Stream.
Implements ConnStateData.
Definition at line 778 of file FtpServer.cc.
References assert, handleDataReply(), handleEprtReply(), handleEpsvReply(), handleErrorReply(), handleFeatReply(), handlePasvReply(), handlePortReply(), handleUploadReply(), server, and TexcHere.
handleRequest()
bool Server::handleRequest (HttpRequest * request) protected
Definition at line 1299 of file FtpServer.cc.
References MemBuf::buf, debugs, Debug::Enabled(), HttpHeader::findEntry(), Http::FTP_ARGUMENTS, Http::FTP_COMMAND, handleCdupRequest(), handleCwdRequest(), handleDataRequest(), handleEprtRequest(), handleEpsvRequest(), handleFeatRequest(), handlePassRequest(), handlePasvRequest(), handlePortRequest(), handleUploadRequest(), HttpHeader::has(), Http::Message::header, MemBuf::init(), HttpRequest::method, Http::METHOD_PUT, Must, HttpRequest::pack(), String::termedBuf(), and HttpHeaderEntry::value.
handleRequestBodyData()
bool ConnStateData::handleRequestBodyData () inherited
called when new request body data has been buffered in inBuf may close the connection if we were closing and piped everything out
Return values
false called comm_close or setReplyToError (the caller should bail)
true we did not call comm_close or setReplyToError
Definition at line 1954 of file client_side.cc.
References ConnStateData::abortChunkedRequestBody(), assert, ConnStateData::bodyParser, ConnStateData::bodyPipe, Server::clientConnection, Comm::Connection::close(), ConnStateData::consumeInput(), debugs, error(), ConnStateData::handleChunkedRequestBody(), Server::inBuf, SBuf::length(), BodyPipe::mayNeedMoreData(), BodyPipe::putMoreData(), SBuf::rawContent(), and ConnStateData::stoppedSending().
Referenced by clientProcessRequest(), and ConnStateData::handleReadData().
handleSslBumpHandshakeError()
void ConnStateData::handleSslBumpHandshakeError (const Security::IoResult & handshakeResult) private inherited
Definition at line 3020 of file client_side.cc.
References Security::IoResult::category, Server::clientConnection, Comm::Connection::close(), DBG_IMPORTANT, debugs, ERR_GATEWAY_FAILURE, ERR_NONE, ERR_SECURE_ACCEPT_FAIL, Security::IoResult::errorDetail, Debug::Extra(), Security::IoResult::important, Security::IoResult::ioError, Security::IoResult::ioSuccess, Security::IoResult::ioWantRead, Security::IoResult::ioWantWrite, MakeNamedErrorDetail(), ConnStateData::tunnelOnError(), and ConnStateData::updateError().
Referenced by ConnStateData::startPeekAndSplice().
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
handleUploadReply()
void Server::handleUploadReply (const HttpReply * header, StoreIOBuffer receivedData) protected
Definition at line 1029 of file FtpServer.cc.
Referenced by handleReply().
handleUploadRequest()
bool Server::handleUploadRequest (String & cmd, String & params) protected
Definition at line 1534 of file FtpServer.cc.
References SquidConfig::accessList, ACLFilledChecklist::al, ClientHttpRequest::al, Acl::Answer::allowed(), Config, ACLChecklist::fastCheck(), HttpRequest::forcedBodyContinuation, SquidConfig::forceRequestBodyContinuation, Ftp::fssHandleUploadRequest, JobCallback, ClientHttpRequest::log_uri, ClientHttpRequest::request, ACLFilledChecklist::syncAle(), and wroteEarlyReply().
Referenced by handleRequest().
handleUserRequest()
Http::Stream * Server::handleUserRequest (const SBuf & cmd, SBuf & params) protected
Called to parse USER command, which is required to create an HTTP request wrapper. W/o request, the errors are handled by returning earlyError().
Definition at line 1358 of file FtpServer.cc.
References SBuf::caseCmp(), SBuf::chop(), SBuf::clear(), debugs, Ip::Address::isAnyAddr(), SBuf::isEmpty(), SBuf::length(), MAX_IPSTRLEN, SBuf::npos, SBuf::rfind(), SBuf::substr(), and Ip::Address::toHostStr().
hasNotes()
bool ConnStateData::hasNotes () const inline inherited
Definition at line 358 of file client_side.h.
References NotePairs::empty(), and ConnStateData::theNotes.
httpsPeeked()
void ConnStateData::httpsPeeked (PinnedIdleContext pic) inherited
Definition at line 3071 of file client_side.cc.
References ConnStateData::PinnedIdleContext::connection, debugs, Pipeline::empty(), Pipeline::front(), RefCount< C >::getRaw(), ConnStateData::getSslContextStart(), Comm::IsConnOpen(), Must, ConnStateData::notePinnedConnectionBecameIdle(), Server::pipeline, ConnStateData::PinnedIdleContext::request, Ssl::ServerBump::request, ConnStateData::sslServerBump, and ConnStateData::tlsConnectHostOrIp.
Referenced by FwdState::completed(), and FwdState::dispatch().
idleTimeout()
time_t Server::idleTimeout () const override protected virtual
Implements ConnStateData.
Definition at line 86 of file FtpServer.cc.
References Config, SquidConfig::ftpClientIdle, and SquidConfig::Timeout.
initiateTunneledRequest()
bool ConnStateData::initiateTunneledRequest (HttpRequest::Pointer const & cause, const char * reason, const SBuf & payload) inherited
Definition at line 3089 of file client_side.cc.
References ConnStateData::buildFakeRequest(), Server::clientConnection, clientProcessRequestFinished(), debugs, ERR_INVALID_REQ, HttpRequest::flags, RequestFlags::forceTunnel, AnyP::Uri::hostOrIp(), SBuf::isEmpty(), Comm::Connection::local, MakeNamedErrorDetail(), MAX_IPSTRLEN, ConnStateData::pinning, Ip::Address::port(), AnyP::Uri::port(), ConnStateData::tlsConnectHostOrIp, ConnStateData::tlsConnectPort, Ip::Address::toStr(), ConnStateData::transparent(), ConnStateData::updateError(), and HttpRequest::url.
Referenced by ConnStateData::splice(), and ConnStateData::tunnelOnError().
isOpen()
bool ConnStateData::isOpen () const inherited
Definition at line 640 of file client_side.cc.
References cbdataReferenceValid(), Server::clientConnection, Comm::Connection::fd, fd_table, and Comm::IsConnOpen().
Referenced by ConnStateData::~ConnStateData(), ConnStateData::afterClientRead(), httpsSslBumpAccessCheckDone(), httpsSslBumpStep2AccessCheckDone(), ConnStateData::kick(), ClientHttpRequest::noteAdaptationAclCheckDone(), ConnStateData::parseRequests(), ConnStateData::sendControlMsg(), and ConnStateData::sslCrtdHandleReply().
kick()
void ConnStateData::kick () inherited
We are done with the response, and we are either still receiving request body (early response!) or have already stopped receiving anything.
If we are still receiving, then parseRequests() below will fail. (XXX: but then we will call readNextRequest() which may succeed and execute a smuggled request as we are not done with the current request).
If we stopped because we got everything, then try the next request.
If we stopped receiving because of an error, then close now to avoid getting stuck and to prevent accidental request smuggling.
Attempt to parse a request from the request buffer. If we've been fed a pipelined request it may already be in our read buffer.
At this point we either have a parsed request (which we've kicked off the processing for) or not. If we have a deferred request (parsed but deferred for pipeling processing reasons) then look at processing it. If not, simply kickstart another read.
Definition at line 894 of file client_side.cc.
References Server::clientConnection, ClientSocketContextPushDeferredIfNeeded(), Comm::Connection::close(), DBG_IMPORTANT, debugs, ConnStateData::flags, Pipeline::front(), Comm::IsConnOpen(), ConnStateData::isOpen(), MYNAME, ConnStateData::parseRequests(), ConnStateData::pinning, Server::pipeline, ConnStateData::readNextRequest(), and ConnStateData::stoppedReceiving().
Referenced by ConnStateData::notePinnedConnectionBecameIdle(), and Http::Stream::writeComplete().
lifetimeTimeout()
void ConnStateData::lifetimeTimeout (const CommTimeoutCbParams & params) inherited
Definition at line 2101 of file client_side.cc.
References CommCommonCbParams::conn, DBG_IMPORTANT, debugs, ERR_LIFETIME_EXP, Debug::Extra(), ConnStateData::terminateAll(), and LogTagsErrors::timedout.
Referenced by ConnStateData::extendLifetime().
listenForDataConnection()
unsigned int Server::listenForDataConnection () protected
Starts waiting for a data connection. Returns listening port. On errors, responds with an error and returns zero.
Definition at line 370 of file FtpServer.cc.
References acceptDataConnection(), comm_local_port(), COMM_NONBLOCKING, comm_open_listener(), DBG_CRITICAL, debugs, Comm::Connection::fd, Comm::Connection::flags, Comm::IsConnOpen(), JobCallback, Comm::Connection::local, port, Ip::Address::port(), and AsyncJob::Start().
maybeMakeSpaceAvailable()
void Server::maybeMakeSpaceAvailable () inherited
Prepare inBuf for I/O. This method balances several conflicting desires:
Do not read too few bytes at a time.
Do not waste too much buffer space.
Do not [re]allocate or memmove the buffer too much.
Obey Config.maxRequestBufferSize limit.
Definition at line 74 of file Server.cc.
References SBufReservationRequirements::allowShared, CLIENT_REQ_BUF_SZ, Config, debugs, SBufReservationRequirements::idealSpace, Server::inBuf, SBufReservationRequirements::maxCapacity, SquidConfig::maxRequestBufferSize, SBufReservationRequirements::minSpace, SBuf::reserve(), and SBuf::spaceSize().
Referenced by Server::doClientRead().
maybeReadUploadData()
void Server::maybeReadUploadData () protected
Definition at line 109 of file FtpServer.cc.
References comm_read(), debugs, JobCallback, and readUploadData().
mayBufferMoreRequestBytes()
bool Server::mayBufferMoreRequestBytes () const protected inherited
Definition at line 89 of file Server.cc.
References Config, debugs, Server::inBuf, SBuf::length(), and SquidConfig::maxRequestBufferSize.
Referenced by Server::doClientRead(), and Server::readSomeData().
mayNeedToReadMoreBody()
int64_t ConnStateData::mayNeedToReadMoreBody () const inherited
number of body bytes we need to comm_read for the "current" request
Return values
0 We do not need to read any [more] body bytes
negative May need more but do not know how many; could be zero!
positive Need to read exactly that many more body bytes
Definition at line 3533 of file client_side.cc.
References ConnStateData::bodyPipe, BodyPipe::bodySizeKnown(), Server::inBuf, SBuf::length(), and BodyPipe::unproducedSize().
Referenced by ConnStateData::clientAfterReadingRequests(), and ConnStateData::stopSending().
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteBodyConsumerAborted()
void Server::noteBodyConsumerAborted (BodyPipe::Pointer ptr) override protected virtual
Implements ConnStateData.
Definition at line 231 of file FtpServer.cc.
References isOpen(), and ConnStateData::noteBodyConsumerAborted().
noteMoreBodySpaceAvailable()
void Server::noteMoreBodySpaceAvailable (BodyPipe::Pointer) override protected virtual
Implements ConnStateData.
Definition at line 222 of file FtpServer.cc.
References isOpen().
notePeerConnection()
void Server::notePeerConnection (Comm::ConnectionPointer) override protected virtual
Reimplemented from ConnStateData.
Definition at line 302 of file FtpServer.cc.
References Must, and ClientHttpRequest::request.
notePinnedConnectionBecameIdle()
void ConnStateData::notePinnedConnectionBecameIdle (PinnedIdleContext pic) inherited
Definition at line 3684 of file client_side.cc.
References ConnStateData::PinnedIdleContext::connection, Pipeline::empty(), ConnStateData::kick(), Must, ConnStateData::pinConnection(), Server::pipeline, ConnStateData::PinnedIdleContext::request, and ConnStateData::startPinnedConnectionMonitoring().
Referenced by ConnStateData::httpsPeeked().
notes()
NotePairs::Pointer ConnStateData::notes () inherited
Returns
existing non-empty connection annotations, creates and returns empty annotations otherwise
Definition at line 4001 of file client_side.cc.
References ConnStateData::theNotes.
Referenced by UpdateRequestNotes().
noteTakeServerConnectionControl()
virtual void ConnStateData::noteTakeServerConnectionControl (ServerConnectionContext) inline virtual inherited
Gives us the control of the Squid-to-server connection. Used, for example, to initiate a TCP tunnel after protocol switching.
Reimplemented in Http::One::Server.
Definition at line 229 of file client_side.h.
Referenced by HttpStateData::proceedAfter1xx().
parseHttpRequest()
Http::Stream * ConnStateData::parseHttpRequest (const Http1::RequestParserPointer & hp) protected inherited
Parse an HTTP request
Note
Sets result->flags.parsed_ok to 0 if failed to parse the request, to 1 if the request was correctly parsed
Parameters
[in] hp an Http1::RequestParser
Returns
NULL on incomplete requests, a Http::Stream on success or failure. TODO: Move to HttpServer. Warning: Move requires large code nonchanges!
Definition at line 1255 of file client_side.cc.
References ConnStateData::abortRequestParsing(), ClientHttpRequest::Flags::accel, SquidConfig::appendDomainLen, ClientHttpRequest::client_stream, Server::clientConnection, clientGetMoreData, clientReplyDetach, clientReplyStatus, clientSocketDetach, clientSocketRecipient, clientStreamInit(), Config, ConnStateData::consumeInput(), StoreIOBuffer::data, DBG_IMPORTANT, debugs, ClientHttpRequest::flags, Http::Stream::flags, HTTP_REQBUF_SZ, Server::inBuf, internalCheck(), internalLocalUri(), SBuf::isEmpty(), SBuf::length(), StoreIOBuffer::length, Http::METHOD_CONNECT, Http::METHOD_NONE, Http::METHOD_PRI, Must, Http::Stream::parsed_ok, ConnStateData::port, prepareAcceleratedURL(), ConnStateData::prepareTlsSwitchingURL(), prepareTransparentURL(), ConnStateData::preservedClientData, ConnStateData::preservingClientData_, Http::ProtocolVersion(), ClientHttpRequest::req_sz, Http::Stream::reqbuf, SBufToCstring(), Http::scMethodNotAllowed, Http::scRequestHeaderFieldsTooLarge, Http::scUriTooLong, ConnStateData::switchedToHttps(), Server::transferProtocol, ConnStateData::transparent(), ClientHttpRequest::uri, xcalloc(), and xstrdup.
parseOneRequest()
Http::Stream * Server::parseOneRequest () override protected virtual
Parses a single FTP request on the control connection. Returns a new Http::Stream on valid requests and all errors. Returns NULL on incomplete requests that may still succeed given more data.
Implements ConnStateData.
Definition at line 640 of file FtpServer.cc.
References SBuf::c_str(), ClientHttpRequest::client_stream, clientGetMoreData, clientReplyDetach, clientReplyStatus, clientSocketDetach, clientSocketRecipient, clientStreamInit(), Ftp::cmdAppe(), Ftp::cmdStor(), Ftp::cmdStou(), Ftp::cmdUser(), Ftp::CommandHasPathParameter(), CharacterSet::complement(), Config, StoreIOBuffer::data, debugs, Http::EXPECT, Http::Stream::flags, HttpRequest::FromUrl(), Ftp::fssError, Http::FTP_ARGUMENTS, Http::FTP_COMMAND, HTTP_REQBUF_SZ, ClientHttpRequest::initRequest(), SBuf::isEmpty(), SBuf::length(), StoreIOBuffer::length, CharacterSet::LF, MasterXaction::MakePortful(), SquidConfig::maxRequestHeaderSize, Http::METHOD_GET, Http::METHOD_PUT, min(), Must, Http::Stream::parsed_ok, port, Ftp::ProtocolVersion(), Http::ProtocolVersion(), ClientHttpRequest::req_sz, Http::Stream::reqbuf, Ftp::SupportedCommand(), SBuf::toUpper(), Http::TRANSFER_ENCODING, SBuf::trim(), ClientHttpRequest::uri, and xstrdup.
parseProxyProtocolHeader()
bool ConnStateData::parseProxyProtocolHeader () private inherited
Attempts to extract a PROXY protocol header from the input buffer and, upon success, stores the parsed header in proxyProtocolHeader_.
Returns
true if the header was successfully parsed
false if more data is needed to parse the header or on error
Definition at line 1799 of file client_side.cc.
References assert, Server::clientConnection, COMM_TRANSPARENT, SBuf::consume(), debugs, Comm::Connection::flags, Server::inBuf, SBuf::length(), Comm::Connection::local, ConnStateData::needProxyProtocolHeader_, ProxyProtocol::Parse(), ConnStateData::proxyProtocolError(), ConnStateData::proxyProtocolHeader_, and Comm::Connection::remote.
Referenced by ConnStateData::parseRequests().
parseRequests()
void ConnStateData::parseRequests () private inherited
Attempt to parse one or more requests from the input buffer. May close the connection.
Definition at line 1836 of file client_side.cc.
References assert, ConnStateData::bodyPipe, Server::clientConnection, Comm::Connection::close(), commIsHalfClosed(), ConnStateData::concurrentRequestQueueFilled(), Config, debugs, Pipeline::empty(), ConnStateData::extendLifetime(), Comm::Connection::fd, ConnStateData::flags, Server::inBuf, SBuf::isEmpty(), ConnStateData::isOpen(), SBuf::length(), SquidConfig::maxRequestHeaderSize, Must, ConnStateData::needProxyProtocolHeader_, ConnStateData::parsedBumpedRequestCount, ConnStateData::parseOneRequest(), ConnStateData::parseProxyProtocolHeader(), ConnStateData::pinning, Server::pipeline, ConnStateData::preservingClientData_, ConnStateData::processParsedRequest(), ConnStateData::switchedToHttps(), and ConnStateData::whenClientIpKnown().
Referenced by ConnStateData::afterClientRead(), and ConnStateData::kick().
parseTlsHandshake()
void ConnStateData::parseTlsHandshake () inherited
Definition at line 2825 of file client_side.cc.
References Ssl::ServerBump::act, ClientHttpRequest::al, assert, Ssl::bumpClientFirst, Ssl::bumpPeek, Ssl::bumpServerFirst, Ssl::bumpStare, Server::clientConnection, Comm::Connection::close(), CurrentException(), debugs, Security::HandshakeParser::details, Ssl::ServerBump::entry, ERR_PROTOCOL_UNKNOWN, Comm::Connection::fd, fd_note(), Pipeline::front(), RefCount< C >::getRaw(), ConnStateData::getSslContextStart(), TextException::id(), Server::inBuf, SBuf::isEmpty(), MakeNamedErrorDetail(), Must, Security::HandshakeParser::parseHello(), ConnStateData::parsingTlsHandshake, Server::pipeline, ConnStateData::preservedClientData, Server::readSomeData(), ConnStateData::receivedFirstByte(), Ssl::ServerBump::request, Comm::ResetSelect(), ConnStateData::resetSslCommonName(), Security::NegotiationHistory::retrieveParsedInfo(), ConnStateData::sslServerBump, FwdState::Start(), ConnStateData::startPeekAndSplice(), Ssl::ServerBump::step, Ssl::ServerBump::step1, tlsBump3, ConnStateData::tlsClientSni_, Comm::Connection::tlsNegotiations(), ConnStateData::tlsParser, ConnStateData::tunnelOnError(), and ConnStateData::updateError().
Referenced by ConnStateData::afterClientRead().
pinBusyConnection()
void ConnStateData::pinBusyConnection (const Comm::ConnectionPointer & pinServerConn, const HttpRequest::Pointer & request) inherited
Forward future client requests using the given to-server connection. The connection is still being used by the current client request.
Definition at line 3678 of file client_side.cc.
References ConnStateData::pinConnection().
pinConnection()
void ConnStateData::pinConnection (const Comm::ConnectionPointer & pinServerConn, const HttpRequest & request) private inherited
Definition at line 3699 of file client_side.cc.
References Server::clientConnection, ConnStateData::clientPinnedConnectionClosed(), comm_add_close_handler(), RequestFlags::connectionAuth, debugs, Comm::Connection::fd, FD_DESC_SZ, fd_note(), HttpRequest::flags, AnyP::Uri::host(), Comm::IsConnOpen(), JobCallback, MAX_IPSTRLEN, Must, ConnStateData::pinning, AnyP::Uri::port(), Comm::Connection::remote, Ip::Address::toUrl(), ConnStateData::unpinConnection(), HttpRequest::url, and xstrdup.
Referenced by ConnStateData::notePinnedConnectionBecameIdle(), and ConnStateData::pinBusyConnection().
pinnedAuth()
bool ConnStateData::pinnedAuth () const inline inherited
Definition at line 204 of file client_side.h.
References ConnStateData::pinning.
pinnedPeer()
CachePeer * ConnStateData::pinnedPeer () const inline inherited
Returns
the pinned CachePeer if one exists, nil otherwise
Definition at line 203 of file client_side.h.
References ConnStateData::pinning.
Referenced by PeerSelector::selectPinned().
pipelinePrefetchMax()
int Server::pipelinePrefetchMax () const override protected virtual
Reimplemented from ConnStateData.
Definition at line 80 of file FtpServer.cc.
postHttpsAccept()
void ConnStateData::postHttpsAccept () inherited
Definition at line 2465 of file client_side.cc.
References ACCESS_DENIED, SquidConfig::accessList, assert, ConnStateData::bareError, AccessLogEntry::cache, Server::clientConnection, COMM_INTERCEPTION, COMM_TRANSPARENT, Config, current_time, debugs, fatal(), ConnStateData::fillChecklist(), Comm::Connection::flags, Pipeline::front(), AnyP::Uri::host(), HTTPMSGLOCK(), HTTPMSGUNLOCK(), httpsEstablish(), httpsSslBumpAccessCheckDone(), Comm::Connection::local, ConnStateData::log_addr, ClientHttpRequest::log_uri, ACLFilledChecklist::Make(), MasterXaction::MakePortful(), MAX_IPSTRLEN, HttpRequest::myportname, ACLFilledChecklist::NonBlockingCheck(), Server::pipeline, AnyP::Uri::port(), ConnStateData::port, Ip::Address::port(), ConnStateData::proxyProtocolHeader_, CodeContext::Reset(), SquidConfig::ssl_bump, AccessLogEntry::CacheDetails::start_time, Ip::Address::toStr(), and HttpRequest::url.
prepareTlsSwitchingURL()
char * ConnStateData::prepareTlsSwitchingURL (const Http1::RequestParserPointer & hp) inherited
Definition at line 1196 of file client_side.cc.
References buildUrlFromHost(), debugs, AnyP::UriScheme::image(), SBuf::isEmpty(), SBuf::length(), Must, AnyP::ProtocolVersion::protocol, SQUIDSBUFPH, SQUIDSBUFPRINT, ConnStateData::switchedToHttps(), ConnStateData::tlsClientSni(), ConnStateData::tlsConnectHostOrIp, ConnStateData::tlsConnectPort, Server::transferProtocol, and xcalloc().
Referenced by ConnStateData::parseHttpRequest().
processParsedRequest()
void Server::processParsedRequest (Http::StreamPointer &) override protected virtual
Implements ConnStateData.
Definition at line 156 of file FtpServer.cc.
References CallJobHere, and Must.
proxyProtocolError()
bool ConnStateData::proxyProtocolError (const char * msg) private inherited
Perform cleanup on PROXY protocol errors. If header parsing hits a fatal error terminate the connection, otherwise wait for more data.
Definition at line 1778 of file client_side.cc.
References Server::clientConnection, DBG_IMPORTANT, debugs, and AsyncJob::mustStop().
Referenced by ConnStateData::parseProxyProtocolHeader(), and ConnStateData::proxyProtocolValidateClient().
proxyProtocolHeader()
const ProxyProtocol::HeaderPointer & ConnStateData::proxyProtocolHeader () const inline inherited
Definition at line 360 of file client_side.h.
References ConnStateData::proxyProtocolHeader_.
Referenced by ClientHttpRequest::ClientHttpRequest().
proxyProtocolValidateClient()
bool ConnStateData::proxyProtocolValidateClient () private inherited
Perform proxy_protocol_access ACL tests on the client which connected to PROXY protocol port to see if we trust the sender enough to accept their PROXY header claim.
Definition at line 1759 of file client_side.cc.
References SquidConfig::accessList, Acl::Answer::allowed(), Config, ACLChecklist::fastCheck(), ConnStateData::fillChecklist(), SquidConfig::proxyProtocol, and ConnStateData::proxyProtocolError().
Referenced by ConnStateData::start().
quitAfterError()
void ConnStateData::quitAfterError (HttpRequest * request) inherited
Changes state so that we close the connection and quit after serving the client-side-detected error response instead of getting stuck.
Definition at line 1431 of file client_side.cc.
References Server::clientConnection, debugs, ConnStateData::flags, HttpRequest::flags, and RequestFlags::proxyKeepalive.
Referenced by clientProcessRequest(), and ConnStateData::serveDelayedError().
reading()
bool Server::reading () const inline inherited
Definition at line 60 of file Server.h.
References Server::reader.
Referenced by Server::doClientRead(), Server::readSomeData(), and Server::stopReading().
readNextRequest()
void ConnStateData::readNextRequest () inherited
Set the timeout BEFORE calling readSomeData().
Please don't do anything with the FD past here!
Definition at line 857 of file client_side.cc.
References Server::clientConnection, debugs, Comm::Connection::fd, fd_note(), ConnStateData::idleTimeout(), Server::readSomeData(), ConnStateData::resetReadTimeout(), and Comm::Connection::timeLeft().
Referenced by ConnStateData::kick().
readSomeData()
void Server::readSomeData () inherited
Definition at line 101 of file Server.cc.
References Server::clientConnection, Server::doClientRead(), JobCallback, Server::mayBufferMoreRequestBytes(), Comm::Read(), Server::reader, and Server::reading().
Referenced by ConnStateData::clientAfterReadingRequests(), clientNegotiateSSL(), Server::doClientRead(), ConnStateData::parseTlsHandshake(), ConnStateData::readNextRequest(), and ConnStateData::switchToHttps().
readUploadData()
void Server::readUploadData (const CommIoCbParams & io) protected
Definition at line 168 of file FtpServer.cc.
References assert, CommIoCbParams::buf, StatCounters::client_http, CommCommonCbParams::conn, debugs, Comm::Connection::fd, CommCommonCbParams::flag, Comm::IsConnOpen(), StatCounters::kbytes_in, Must, Comm::OK, CommIoCbParams::size, and statCounter.
Referenced by maybeReadUploadData().
receivedFirstByte()
void ConnStateData::receivedFirstByte () override virtual inherited
Implements Server.
Definition at line 1824 of file client_side.cc.
References Config, Server::receivedFirstByte_, SquidConfig::request, ConnStateData::resetReadTimeout(), and SquidConfig::Timeout.
Referenced by ConnStateData::parseTlsHandshake().
registerRunner()
void IndependentRunner::registerRunner () protected inherited
Definition at line 104 of file RunnersRegistry.cc.
References FindRunners(), and RegisterRunner_().
Referenced by ConnStateData::ConnStateData(), IdleConnList::IdleConnList(), and Rock::Rebuild::Rebuild().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
replyDataWritingCheckpoint()
void Server::replyDataWritingCheckpoint () protected
Definition at line 1004 of file FtpServer.cc.
References debugs, fatal(), STREAM_COMPLETE, STREAM_FAILED, STREAM_NONE, and STREAM_UNPLANNED_COMPLETE.
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
requestTimeout()
void ConnStateData::requestTimeout (const CommTimeoutCbParams & io) inherited
general lifetime handler for HTTP requests
Definition at line 2078 of file client_side.cc.
References Comm::Connection::close(), CommCommonCbParams::conn, debugs, ERR_REQUEST_PARSE_TIMEOUT, ERR_REQUEST_START_TIMEOUT, error(), CommCommonCbParams::fd, Comm::IsConnOpen(), Server::receivedFirstByte_, ConnStateData::tunnelOnError(), and ConnStateData::updateError().
Referenced by ConnStateData::resetReadTimeout().
resetLogin()
void Server::resetLogin (const char * reason) private
Definition at line 336 of file FtpServer.cc.
References debugs, and Ftp::fssBegin.
resetReadTimeout()
void ConnStateData::resetReadTimeout (time_t timeout) inherited
Definition at line 574 of file client_side.cc.
References Server::clientConnection, commSetConnTimeout(), JobCallback, and ConnStateData::requestTimeout().
Referenced by ConnStateData::getSslContextDone(), httpsEstablish(), ConnStateData::readNextRequest(), ConnStateData::receivedFirstByte(), and ConnStateData::switchToHttps().
resetSslCommonName()
void ConnStateData::resetSslCommonName (const char * name) inline inherited
Definition at line 293 of file client_side.h.
References ConnStateData::sslCommonName_.
Referenced by ConnStateData::parseTlsHandshake(), and ConnStateData::switchToHttps().
sendControlMsg()
void ConnStateData::sendControlMsg (HttpControlMsg msg) override virtual inherited
Implements HttpControlMsgSink.
Definition at line 3614 of file client_side.cc.
References HttpControlMsgSink::cbControlMsgSent, HttpControlMsg::cbSuccess, Server::clientConnection, Comm::Connection::close(), debugs, ConnStateData::doneWithControlMsg(), Pipeline::empty(), Pipeline::front(), RefCount< C >::getRaw(), ConnStateData::isOpen(), JobCallback, Must, Server::pipeline, HttpControlMsg::reply, ConnStateData::writeControlMsgAndCall(), and HttpControlMsgSink::wroteControlMsg().
Referenced by Ftp::Relay::forwardPreliminaryReply(), and HttpStateData::handle1xx().
serveDelayedError()
bool ConnStateData::serveDelayedError (Http::Stream * context) inherited
Called when the client sends the first request on a bumped connection. Returns false if no [delayed] error should be written to the client. Otherwise, writes the error to the client and returns true. Also checks for SQUID_X509_V_ERR_DOMAIN_MISMATCH on bumped requests.
Definition at line 1443 of file client_side.cc.
References ClientHttpRequest::al, Acl::Answer::allowed(), assert, SquidConfig::cert_error, clientAclChecklistFill(), Server::clientConnection, Config, debugs, Ssl::ServerBump::entry, ERR_SECURE_CONNECT_FAIL, HttpRequest::error, ACLChecklist::fastCheck(), Http::Stream::getClientReplyContext(), Ssl::HasSubjectName(), HttpRequest::hier, ConnStateData::host, Http::Stream::http, StoreEntry::isEmpty(), HttpRequest::method, ClientHttpRequest::Out::offset, ClientHttpRequest::out, AnyP::Uri::parsedHost(), Http::Stream::pullData(), ConnStateData::quitAfterError(), RawPointer(), Comm::Connection::remote, ClientHttpRequest::request, Ssl::ServerBump::request, Http::scServiceUnavailable, Ssl::ServerBump::serverCert, clientReplyContext::setReplyToError(), clientReplyContext::setReplyToStoreEntry(), SQUID_X509_V_ERR_DOMAIN_MISMATCH, SquidConfig::ssl_client, ACLFilledChecklist::sslErrors, ConnStateData::sslServerBump, Error::update(), ConnStateData::updateError(), ClientHttpRequest::uri, and HttpRequest::url.
Referenced by clientProcessRequest().
serverBump()
Ssl::ServerBump * ConnStateData::serverBump () inline inherited
Definition at line 285 of file client_side.h.
References ConnStateData::sslServerBump.
Referenced by Format::Format::assemble(), TunnelStateData::clientExpectsConnectResponse(), httpsSslBumpStep2AccessCheckDone(), and ClientRequestContext::sslBumpAccessCheck().
setAuth()
void ConnStateData::setAuth (const Auth::UserRequest::Pointer & aur, const char * cause) inherited
Set the user details for connection-based authentication to use from now until connection closure.
Any change to existing credentials shows that something invalid has happened. Such as:
NTLM/Negotiate auth was violated by the per-request headers missing a revalidation token
NTLM/Negotiate auth was violated by the per-request headers being for another user
SSL-Bump CONNECT tunnel with persistent credentials has ended
Definition at line 494 of file client_side.cc.
References ConnStateData::auth_, Server::clientConnection, comm_reset_close(), debugs, Auth::UserRequest::releaseAuthServer(), and ConnStateData::stopReceiving().
Referenced by Auth::UserRequest::authenticate(), ACLProxyAuth::LookupDone(), ClientHttpRequest::sslBumpEstablish(), and ConnStateData::swanSong().
setDataCommand()
void Server::setDataCommand () protected
Definition at line 1644 of file FtpServer.cc.
References assert, debugs, Http::FTP_ARGUMENTS, Http::FTP_COMMAND, Http::Message::header, ClientHttpRequest::request, and HttpHeader::updateOrAddStr().
setReply()
void Server::setReply (const int code, const char * msg) protected
Definition at line 1729 of file FtpServer.cc.
References assert, clientReplyContext::createStoreEntry(), RequestFlags::disableCacheUse(), Ftp::HttpReplyWrapper(), HttpRequest::method, StoreEntry::replaceHttpReply(), ClientHttpRequest::request, Http::scNoContent, and ClientHttpRequest::storeEntry().
setServerBump()
void ConnStateData::setServerBump (Ssl::ServerBump * srvBump) inline inherited
Definition at line 286 of file client_side.h.
References assert, and ConnStateData::sslServerBump.
Referenced by ClientHttpRequest::doCallouts().
shouldCloseOnEof()
bool ConnStateData::shouldCloseOnEof () const override private virtual inherited
Implements Server.
Definition at line 1389 of file client_side.cc.
References Config, debugs, Pipeline::empty(), SquidConfig::half_closed_clients, Server::inBuf, SBuf::isEmpty(), SquidConfig::onoff, and Server::pipeline.
shouldPreserveClientData()
bool ConnStateData::shouldPreserveClientData () const inherited
whether we should start saving inBuf client bytes in anticipation of tunneling them to the server later (on_unsupported_protocol)
Definition at line 3969 of file client_side.cc.
References SquidConfig::accessList, Config, ConnStateData::needProxyProtocolHeader_, Pipeline::nrequests, SquidConfig::on_unsupported_protocol, ConnStateData::parsedBumpedRequestCount, ConnStateData::parsingTlsHandshake, Server::pipeline, ConnStateData::port, AnyP::PROTO_FTP, ConnStateData::switchedToHttps(), and ConnStateData::transparent().
Referenced by ConnStateData::start(), and ConnStateData::switchToHttps().
shovelUploadData()
void Server::shovelUploadData () private
Definition at line 202 of file FtpServer.cc.
References assert, debugs, and Comm::IsConnOpen().
splice()
bool ConnStateData::splice () inherited
Definition at line 2930 of file client_side.cc.
References assert, Server::clientConnection, Pipeline::empty(), ConnStateData::fakeAConnectRequest(), Comm::Connection::fd, fd_table, Pipeline::front(), ConnStateData::initiateTunneledRequest(), Must, Server::pipeline, ConnStateData::preservedClientData, Http::ProtocolVersion(), ClientHttpRequest::request, Server::transferProtocol, and ConnStateData::transparent().
Referenced by httpsSslBumpStep2AccessCheckDone().
sslCommonName()
const SBuf & ConnStateData::sslCommonName () const inline inherited
Definition at line 292 of file client_side.h.
References ConnStateData::sslCommonName_.
sslCrtdHandleReply()
void ConnStateData::sslCrtdHandleReply (const Helper::Reply & reply) inherited
Definition at line 2528 of file client_side.cc.
References Ssl::ServerBump::act, Ssl::algSignTrusted, Helper::BrokenHelper, Ssl::bumpPeek, Ssl::bumpStare, Server::clientConnection, Ssl::configureSSLUsingPkeyAndCertFromMemory(), Ssl::configureUnconfiguredSslContext(), MemBuf::content(), MemBuf::contentSize(), DBG_IMPORTANT, debugs, ConnStateData::doPeekAndSpliceStep(), Comm::Connection::fd, fd_table, Ssl::GenerateSslContextUsingPkeyAndCertFromMemory(), Ssl::CrtdMessage::getBody(), Security::GetFrom(), ConnStateData::getSslContextDone(), MemBuf::hasContent(), SBuf::isEmpty(), ConnStateData::isOpen(), Ssl::CrtdMessage::OK, Helper::Okay, Helper::Reply::other(), Ssl::CrtdMessage::parse(), ConnStateData::port, Ssl::CrtdMessage::REPLY, Helper::Reply::result, ConnStateData::signAlgorithm, ConnStateData::sslBumpCertKey, ConnStateData::sslServerBump, Ssl::ServerBump::step1, ConnStateData::storeTlsContextToCache(), and ConnStateData::tlsConnectHostOrIp.
Referenced by ConnStateData::sslCrtdHandleReplyWrapper().
sslCrtdHandleReplyWrapper()
void ConnStateData::sslCrtdHandleReplyWrapper (void * data, const Helper::Reply & reply) static inherited
Definition at line 2521 of file client_side.cc.
References ConnStateData::sslCrtdHandleReply().
Referenced by ConnStateData::getSslContextStart().
start()
void Server::start () override protected virtual
Reimplemented from ConnStateData.
Definition at line 92 of file FtpServer.cc.
References debugs, MAX_IPSTRLEN, and ConnStateData::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
startDechunkingRequest()
void ConnStateData::startDechunkingRequest () protected inherited
Definition at line 3581 of file client_side.cc.
References assert, ConnStateData::bodyParser, ConnStateData::bodyPipe, debugs, Must, and BodyPipe::status().
Referenced by ConnStateData::expectRequestBody().
startPeekAndSplice()
void ConnStateData::startPeekAndSplice () inherited
Definition at line 2964 of file client_side.cc.
References ConnStateData::acceptTls(), ACCESS_ALLOWED, SquidConfig::accessList, ClientHttpRequest::al, assert, Ssl::ServerBump::at(), BIO_get_data(), Ssl::bumpClientFirst, Ssl::bumpNone, Ssl::bumpServerFirst, SBuf::clear(), Server::clientConnection, Config, Ssl::createSSLContext(), debugs, Ssl::ServerBump::entry, Comm::Connection::fd, fd_table, ConnStateData::fillChecklist(), Pipeline::front(), RefCount< C >::getRaw(), ConnStateData::handleSslBumpHandshakeError(), Ssl::ClientBio::hold(), httpsCreate(), httpsSslBumpStep2AccessCheckDone(), Server::inBuf, ACLFilledChecklist::Make(), ACLFilledChecklist::NonBlockingCheck(), Server::pipeline, ConnStateData::port, Ssl::ServerBump::request, Ssl::ClientBio::setReadBufData(), SquidConfig::ssl_bump, ConnStateData::sslServerBump, FwdState::Start(), Ssl::ServerBump::step, ConnStateData::switchedToHttps_, tlsBump1, tlsBump2, and tlsBump3.
Referenced by httpsSslBumpStep2AccessCheckDone(), and ConnStateData::parseTlsHandshake().
startPinnedConnectionMonitoring()
void ConnStateData::startPinnedConnectionMonitoring () protected inherited
[re]start monitoring pinned connection for peer closures so that we can propagate them to an idle client pinned to that peer
Definition at line 3743 of file client_side.cc.
References ConnStateData::clientPinnedConnectionRead(), JobCallback, ConnStateData::pinning, and Comm::Read().
Referenced by ConnStateData::handleIdleClientPinnedTlsRead(), and ConnStateData::notePinnedConnectionBecameIdle().
startReconfigure()
virtual void RegisteredRunner::startReconfigure () inline virtual inherited
Called after receiving a reconfigure request and before parsing squid.conf. Meant for modules that need to prepare for their configuration being changed [outside their control]. The changes end with the syncConfig() event.
Reimplemented in Dns::ConfigRr, HtcpRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 67 of file RunnersRegistry.h.
Referenced by mainReconfigureStart().
startShutdown()
void ConnStateData::startShutdown () override virtual inherited
Called after receiving a shutdown request and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented from RegisteredRunner.
Definition at line 1014 of file client_side.cc.
References Pipeline::empty(), ConnStateData::endingShutdown(), and Server::pipeline.
startWaitingForOrigin()
void Server::startWaitingForOrigin ()
Called by Ftp::Client class when it is start receiving or sending data.
Definition at line 1761 of file FtpServer.cc.
References debugs, and isOpen().
Referenced by Ftp::Relay::sendCommand().
status()
const char * AsyncJob::status () const protected virtual inherited
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), AsyncJob::stopReason, and MemBuf::terminate().
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
stoppedReceiving()
const char * ConnStateData::stoppedReceiving () const inline inherited
Definition at line 159 of file client_side.h.
References ConnStateData::stoppedReceiving_.
Referenced by ConnStateData::kick(), ConnStateData::stopReceiving(), and ConnStateData::stopSending().
stoppedSending()
const char * ConnStateData::stoppedSending () const inline inherited
Definition at line 161 of file client_side.h.
References ConnStateData::stoppedSending_.
Referenced by ConnStateData::handleRequestBodyData(), ConnStateData::stopReceiving(), and ConnStateData::stopSending().
stopPinnedConnectionMonitoring()
void ConnStateData::stopPinnedConnectionMonitoring () inherited
Definition at line 3755 of file client_side.cc.
References ConnStateData::pinning, and Comm::ReadCancel().
Referenced by ConnStateData::borrowPinnedConnection(), and ConnStateData::unpinConnection().
stopProducingFor()
void BodyProducer::stopProducingFor (RefCount< BodyPipe > & p, bool atEof) protected inherited
Definition at line 107 of file BodyPipe.cc.
References assert, and debugs.
Referenced by ConnStateData::~ConnStateData(), Client::cleanAdaptation(), ConnStateData::finishDechunkingRequest(), Client::noteBodyConsumerAborted(), and Client::serverComplete2().
stopReading()
void Server::stopReading () inherited
Definition at line 60 of file Server.cc.
References Server::clientConnection, Comm::Connection::fd, Comm::ReadCancel(), Server::reader, and Server::reading().
Referenced by ClientHttpRequest::processRequest().
stopReceiving()
void ConnStateData::stopReceiving (const char * error) inherited
Definition at line 3551 of file client_side.cc.
References Server::clientConnection, Comm::Connection::close(), debugs, error(), ConnStateData::stoppedReceiving(), ConnStateData::stoppedReceiving_, ConnStateData::stoppedSending(), and ConnStateData::stoppedSending_.
Referenced by ConnStateData::setAuth().
stopSending()
void ConnStateData::stopSending (const char * error) inherited
Definition at line 959 of file client_side.cc.
References Server::clientConnection, Comm::Connection::close(), debugs, error(), Server::inBuf, SBuf::length(), ConnStateData::mayNeedToReadMoreBody(), ConnStateData::stoppedReceiving(), ConnStateData::stoppedReceiving_, ConnStateData::stoppedSending(), and ConnStateData::stoppedSending_.
stopWaitingForOrigin()
void Server::stopWaitingForOrigin (int status)
Called by Ftp::Client class when it is done receiving or sending data. Waits for both agents to be done before responding to the FTP client and closing the data connection.
Definition at line 1771 of file FtpServer.cc.
References debugs, Ftp::fssHandleDataRequest, RefCount< C >::getRaw(), isOpen(), and Must.
Referenced by Ftp::Relay::stopOriginWait().
storeTlsContextToCache()
void ConnStateData::storeTlsContextToCache (const SBuf & cacheKey, Security::ContextPointer & ctx) private inherited
Attempts to add a given TLS context to the cache, replacing the old same-key context, if any
Definition at line 2665 of file client_side.cc.
References Server::clientConnection, Comm::Connection::fd, fd_table, Ssl::GlobalContextStorage::getLocalStorage(), ConnStateData::port, and Ssl::TheGlobalContextStorage().
Referenced by ConnStateData::getSslContextStart(), and ConnStateData::sslCrtdHandleReply().
swanSong()
void ConnStateData::swanSong () override virtual inherited
Reimplemented from AsyncJob.
Definition at line 591 of file client_side.cc.
References ConnStateData::checkLogging(), Server::clientConnection, clientdbEstablished(), debugs, ERR_NONE, ConnStateData::flags, Comm::Connection::remote, ConnStateData::setAuth(), Server::swanSong(), ConnStateData::terminateAll(), and ConnStateData::unpinConnection().
switchedToHttps()
bool ConnStateData::switchedToHttps () const inline inherited
Definition at line 284 of file client_side.h.
References ConnStateData::switchedToHttps_.
Referenced by ConnStateData::buildFakeRequest(), clientProcessRequest(), ConnStateData::parseHttpRequest(), ConnStateData::parseRequests(), ConnStateData::prepareTlsSwitchingURL(), ConnStateData::shouldPreserveClientData(), and ClientRequestContext::sslBumpAccessCheck().
switchToHttps()
void ConnStateData::switchToHttps (ClientHttpRequest * http, Ssl::BumpMode bumpServerMode) inherited
Definition at line 2772 of file client_side.cc.
References assert, Ssl::bumpPeek, Ssl::bumpServerFirst, Ssl::bumpStare, Server::clientConnection, Config, debugs, ConnStateData::flags, Must, ConnStateData::parsingTlsHandshake, ConnStateData::preservingClientData_, AnyP::PROTO_HTTPS, AnyP::ProtocolVersion::protocol, Server::readSomeData(), Server::receivedFirstByte_, ClientHttpRequest::request, SquidConfig::request_start_timeout, ConnStateData::resetReadTimeout(), ConnStateData::resetSslCommonName(), ConnStateData::shouldPreserveClientData(), ConnStateData::sslServerBump, ConnStateData::switchedToHttps_, SquidConfig::Timeout, ConnStateData::tlsConnectHostOrIp, ConnStateData::tlsConnectPort, and Server::transferProtocol.
Referenced by ClientHttpRequest::sslBumpEstablish().
syncConfig()
virtual void RegisteredRunner::syncConfig () inline virtual inherited
Called after parsing squid.conf during reconfiguration. Meant for adjusting the module state based on configuration changes.
Reimplemented in Auth::CredentialCacheRr, CarpRr, HtcpRr, PeerSourceHashRr, PeerUserHashRr, PeerPoolMgrsRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 71 of file RunnersRegistry.h.
Referenced by mainReconfigureFinish().
terminateAll()
void ConnStateData::terminateAll (const Error & , const LogTagsErrors &) override private virtual inherited
Implements Server.
Definition at line 3907 of file client_side.cc.
References assert, Pipeline::back(), ConnStateData::bareError, ConnStateData::bodyPipe, SBuf::clear(), Server::clientConnection, Comm::Connection::close(), Pipeline::count(), debugs, Pipeline::empty(), error(), Pipeline::front(), Server::inBuf, SBuf::isEmpty(), SBuf::length(), MakeNamedErrorDetail(), Pipeline::nrequests, ConnStateData::parsingTlsHandshake, Server::pipeline, and Error::update().
Referenced by ConnStateData::lifetimeTimeout(), and ConnStateData::swanSong().
tlsClientSni()
const SBuf & ConnStateData::tlsClientSni () const inline inherited
Definition at line 294 of file client_side.h.
References ConnStateData::tlsClientSni_.
Referenced by ConnStateData::prepareTlsSwitchingURL().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
transparent()
bool ConnStateData::transparent () const inherited
Definition at line 3516 of file client_side.cc.
References Server::clientConnection, COMM_INTERCEPTION, COMM_TRANSPARENT, and Comm::Connection::flags.
Referenced by ConnStateData::concurrentRequestQueueFilled(), ConnStateData::fakeAConnectRequest(), ConnStateData::initiateTunneledRequest(), ConnStateData::parseHttpRequest(), ConnStateData::shouldPreserveClientData(), ConnStateData::splice(), and ConnStateData::start().
tunnelOnError()
bool ConnStateData::tunnelOnError (const err_type requestError) protected inherited
Definition at line 1521 of file client_side.cc.
References SquidConfig::accessList, Server::clientConnection, COMM_SELECT_READ, Config, debugs, ACLChecklist::fastCheck(), Comm::Connection::fd, ConnStateData::fillChecklist(), Pipeline::front(), ConnStateData::initiateTunneledRequest(), SquidConfig::on_unsupported_protocol, Server::pipeline, ConnStateData::preservedClientData, ConnStateData::preservingClientData_, ACLFilledChecklist::requestErrorType, and Comm::SetSelect().
Referenced by ConnStateData::handleSslBumpHandshakeError(), ConnStateData::parseTlsHandshake(), and ConnStateData::requestTimeout().
unpinConnection()
void ConnStateData::unpinConnection (const bool andClose) inherited
Definition at line 3879 of file client_side.cc.
References comm_remove_close_handler(), debugs, Comm::IsConnOpen(), ConnStateData::pinning, safe_free, and ConnStateData::stopPinnedConnectionMonitoring().
Referenced by ConnStateData::borrowPinnedConnection(), ConnStateData::clientPinnedConnectionClosed(), ConnStateData::pinConnection(), and ConnStateData::swanSong().
unregisterRunner()
void IndependentRunner::unregisterRunner () protected inherited
Definition at line 96 of file RunnersRegistry.cc.
References FindRunners().
Referenced by IndependentRunner::~IndependentRunner().
updateError() [1/2]
void ConnStateData::updateError (const err_type c, const ErrorDetailPointer & d) inline inherited
Definition at line 366 of file client_side.h.
References ConnStateData::updateError().
Referenced by ConnStateData::updateError().
updateError() [2/2]
void ConnStateData::updateError (const Error & error) inherited
Definition at line 628 of file client_side.cc.
References assert, ConnStateData::bareError, error(), Pipeline::front(), Server::pipeline, and Error::update().
Referenced by ConnStateData::callException(), clientNegotiateSSL(), ConnStateData::handleSslBumpHandshakeError(), ConnStateData::initiateTunneledRequest(), ConnStateData::parseTlsHandshake(), ConnStateData::requestTimeout(), and ConnStateData::serveDelayedError().
useConfig()
virtual void RegisteredRunner::useConfig () inline virtual inherited
Called after claimMemoryNeeds(). Meant for activating modules and features using a finalized configuration with known memory requirements.
Reimplemented in CarpRr, ClientDbRr, HtcpRr, SharedMemPagesRr, Ipc::Mem::RegisteredRunner, MemStoreRr, PeerSourceHashRr, PeerUserHashRr, PeerPoolMgrsRr, SharedSessionCacheRr, SnmpRr, TransientsRr, WccpRr, and Wccp2Rr.
Definition at line 60 of file RunnersRegistry.h.
Referenced by RunConfigUsers().
userDataCompletionCheckpoint()
void Server::userDataCompletionCheckpoint (int finalStatusCode) protected
Called after data transfer on client-to-squid data connection is finished.
Definition at line 1809 of file FtpServer.cc.
References debugs, and Must.
whenClientIpKnown()
void ConnStateData::whenClientIpKnown () protected inherited
Perform client data lookups that depend on client src-IP. The PROXY protocol may require some data input first.
Definition at line 2167 of file client_side.cc.
References assert, ACLChecklist::changeAcl(), SquidConfig::client_db, Server::clientConnection, clientdbEstablished(), clientdbGetInfo(), SquidConfig::ClientDelay, Config, debugs, ACLChecklist::fastCheck(), Comm::Connection::fd, fd_table, ConnStateData::fillChecklist(), FQDN_LOOKUP_IF_MISS, fqdncache_gethostbyaddr(), ClientDelayConfig::initial, ClientDelayPools::Instance(), SquidConfig::onoff, ClientDelayPools::pools, Comm::Connection::remote, Dns::ResolveClientAddressesAsap, and ClientInfo::setWriteLimiter().
Referenced by ConnStateData::parseRequests(), and ConnStateData::start().
write() [1/2]
void Server::write (char * buf, int len) inline inherited
Definition at line 79 of file Server.h.
References Server::clientConnection, Server::clientWriteDone(), JobCallback, Comm::Write(), and Server::writer.
write() [2/2]
void Server::write (MemBuf * mb) inline inherited
Definition at line 72 of file Server.h.
References Server::clientConnection, Server::clientWriteDone(), JobCallback, Comm::Write(), and Server::writer.
writeControlMsgAndCall()
bool Server::writeControlMsgAndCall (HttpReply * rep, AsyncCall::Pointer & call) override protected virtual
Implements ConnStateData.
Definition at line 1152 of file FtpServer.cc.
writeCustomReply()
void Server::writeCustomReply (const int code, const char * msg, const HttpReply * reply = nullptr) protected
Definition at line 507 of file FtpServer.cc.
References Packable::appendf(), assert, debugs, Http::FTP_REASON, Http::FTP_STATUS, HttpHeader::has(), Http::Message::header, MemBuf::init(), and Ftp::PrintReply().
writeEarlyReply()
void Server::writeEarlyReply (const int code, const char * msg) protected
Writes FTP [error] response before we fully parsed the FTP request and created the corresponding HTTP request wrapper for that FTP request.
Definition at line 476 of file FtpServer.cc.
References Packable::appendf(), assert, debugs, MemBuf::init(), JobCallback, Comm::Write(), and wroteEarlyReply().
writeErrorReply()
void Server::writeErrorReply (const HttpReply * reply, const int status) protected
Definition at line 1095 of file FtpServer.cc.
References HttpRequest::adaptHistory(), Adaptation::History::allMeta, Packable::appendf(), assert, Error::category, Error::details, HttpRequest::error, errorPageName(), Http::FTP_REASON, HttpHeader::getByName(), HttpHeader::getStr(), HttpHeader::has(), Http::Message::header, MemBuf::init(), Http::StatusLine::reason(), String::size(), HttpReply::sline, SQUIDSBUFPH, SQUIDSBUFPRINT, and String::termedBuf().
writeForwardedForeign()
void Server::writeForwardedForeign (const HttpReply * reply) protected
writes FTP response based on HTTP reply that is not an FTP-response wrapper for example, internally-generated Squid "errorpages" end up here (for now)
Definition at line 1143 of file FtpServer.cc.
References Ftp::fssConnected.
writeForwardedReply()
void Server::writeForwardedReply (const HttpReply * reply) protected
Definition at line 1036 of file FtpServer.cc.
References Http::FTP_STATUS, HttpHeader::has(), Http::Message::header, JobCallback, Must, and wroteReply().
writeForwardedReplyAndCall()
void Server::writeForwardedReplyAndCall (const HttpReply * reply, AsyncCall::Pointer & call) protected
Definition at line 1161 of file FtpServer.cc.
References assert, MemBuf::buf, debugs, Ftp::fssHandleDataRequest, Ftp::fssHandleUploadRequest, Http::FTP_REASON, Http::FTP_STATUS, HttpHeader::getInt(), HttpHeader::has(), Http::Message::header, MemBuf::init(), Comm::IsConnOpen(), Must, Ftp::PrintReply(), and Comm::Write().
writeReply()
void Server::writeReply (MemBuf & mb) protected
Definition at line 495 of file FtpServer.cc.
References MemBuf::buf, debugs, JobCallback, Comm::Write(), and wroteReply().
writeSomeData()
virtual void Server::writeSomeData () inline virtual inherited
Definition at line 69 of file Server.h.
Referenced by Server::clientWriteDone().
writing()
bool Server::writing () const inline inherited
Definition at line 89 of file Server.h.
References Server::writer.
wroteControlMsg()
void HttpControlMsgSink::wroteControlMsg (const CommIoCbParams & params) inherited
called when we wrote the 1xx response
Definition at line 25 of file HttpControlMsg.cc.
References Comm::Connection::close(), CommCommonCbParams::conn, debugs, HttpControlMsgSink::doneWithControlMsg(), Comm::ERR_CLOSING, CommCommonCbParams::flag, Comm::OK, CommCommonCbParams::xerrno, and xstrerr().
Referenced by ConnStateData::sendControlMsg().
wroteEarlyReply()
void Server::wroteEarlyReply (const CommIoCbParams & io) protected
Definition at line 1234 of file FtpServer.cc.
References Comm::Connection::close(), CommCommonCbParams::conn, debugs, Comm::ERR_CLOSING, CommCommonCbParams::flag, Comm::OK, CommIoCbParams::size, CommCommonCbParams::xerrno, and xstrerr().
Referenced by handleUploadRequest(), and writeEarlyReply().
wroteReply()
void Server::wroteReply (const CommIoCbParams & io) protected
Definition at line 1256 of file FtpServer.cc.
References assert, Comm::Connection::close(), CommCommonCbParams::conn, debugs, Comm::ERR_CLOSING, CommCommonCbParams::flag, Ftp::fssConnected, Ftp::fssError, Comm::OK, CommIoCbParams::size, STREAM_COMPLETE, STREAM_FAILED, STREAM_NONE, STREAM_UNPLANNED_COMPLETE, CommCommonCbParams::xerrno, and xstrerr().
Referenced by writeForwardedReply(), and writeReply().
wroteReplyData()
void Server::wroteReplyData (const CommIoCbParams & io) protected
Definition at line 986 of file FtpServer.cc.
References assert, debugs, Comm::ERR_CLOSING, CommCommonCbParams::flag, Comm::OK, CommIoCbParams::size, CommCommonCbParams::xerrno, and xstrerr().
Referenced by handleDataReply().
Friends And Related Symbol Documentation
StartListening
void StartListening () friend
Member Data Documentation
auth
bool ConnStateData::auth = false inherited
Definition at line 147 of file client_side.h.
Referenced by clientCheckPinning().
auth_
Auth::UserRequest::Pointer ConnStateData::auth_ private inherited
Definition at line 474 of file client_side.h.
Referenced by ConnStateData::getAuth(), and ConnStateData::setAuth().
bareError
Error ConnStateData::bareError inherited
Definition at line 381 of file client_side.h.
Referenced by ClientHttpRequest::ClientHttpRequest(), ConnStateData::add(), ConnStateData::checkLogging(), ConnStateData::postHttpsAccept(), ConnStateData::terminateAll(), and ConnStateData::updateError().
bodyParser
Http1::TeChunkedParser* ConnStateData::bodyParser = nullptr inherited
Definition at line 108 of file client_side.h.
Referenced by ConnStateData::~ConnStateData(), ConnStateData::finishDechunkingRequest(), ConnStateData::handleChunkedRequestBody(), ConnStateData::handleRequestBodyData(), and ConnStateData::startDechunkingRequest().
bodyPipe
BodyPipe::Pointer ConnStateData::bodyPipe protected inherited
Definition at line 431 of file client_side.h.
Referenced by ConnStateData::~ConnStateData(), ConnStateData::expectNoForwarding(), ConnStateData::expectRequestBody(), ConnStateData::finishDechunkingRequest(), ConnStateData::handleChunkedRequestBody(), ConnStateData::handleReadData(), ConnStateData::handleRequestBodyData(), ConnStateData::mayNeedToReadMoreBody(), ConnStateData::noteBodyConsumerAborted(), ConnStateData::parseRequests(), ConnStateData::startDechunkingRequest(), and ConnStateData::terminateAll().
cbControlMsgSent
AsyncCall::Pointer HttpControlMsgSink::cbControlMsgSent inherited
Definition at line 42 of file HttpControlMsg.h.
Referenced by clientSocketRecipient(), HttpControlMsgSink::doneWithControlMsg(), and ConnStateData::sendControlMsg().
clientConnection
Comm::ConnectionPointer Server::clientConnection inherited
Definition at line 100 of file Server.h.
Referenced by ClientHttpRequest::ClientHttpRequest(), Server::Server(), TunnelStateData::TunnelStateData(), ConnStateData::~ConnStateData(), ConnStateData::abortChunkedRequestBody(), ConnStateData::abortRequestParsing(), ConnStateData::acceptTls(), ConnStateData::afterClientRead(), Format::Format::assemble(), Auth::UserRequest::authenticate(), ConnStateData::buildFakeRequest(), ConnStateData::clientAfterReadingRequests(), clientBuildError(), clientNegotiateSSL(), ConnStateData::clientPinnedConnectionClosed(), ConnStateData::clientPinnedConnectionRead(), clientProcessRequestFinished(), ClientRequestContext::clientRedirectDone(), ClientSocketContextPushDeferredIfNeeded(), clientSocketRecipient(), Server::clientWriteDone(), ConnStateData::concurrentRequestQueueFilled(), ConnStateData::connStateClosed(), Server::doClientRead(), Server::doneAll(), ConnStateData::doneWithControlMsg(), ConnStateData::doPeekAndSpliceStep(), ConnStateData::endingShutdown(), ConnStateData::extendLifetime(), ConnStateData::fakeAConnectRequest(), ConnStateData::fillConnectionLevelDetails(), ConnStateData::getSslContextDone(), ConnStateData::getSslContextStart(), ConnStateData::handleChunkedRequestBody(), ConnStateData::handleRequestBodyData(), ConnStateData::handleSslBumpHandshakeError(), ClientRequestContext::hostHeaderIpVerify(), ClientRequestContext::hostHeaderVerify(), ClientRequestContext::hostHeaderVerifyFailed(), httpsCreate(), httpsEstablish(), httpsSslBumpAccessCheckDone(), httpsSslBumpStep2AccessCheckDone(), ConnStateData::initiateTunneledRequest(), ConnStateData::isOpen(), ConnStateData::kick(), HttpRequest::manager(), ClientHttpRequest::noteBodyProducerAborted(), ConnStateData::parseHttpRequest(), ConnStateData::parseProxyProtocolHeader(), ConnStateData::parseRequests(), ConnStateData::parseTlsHandshake(), ConnStateData::pinConnection(), ConnStateData::postHttpsAccept(), prepareAcceleratedURL(), prepareTransparentURL(), clientReplyContext::processExpired(), clientReplyContext::processMiss(), ConnStateData::proxyProtocolError(), ConnStateData::quitAfterError(), ConnStateData::readNextRequest(), Server::readSomeData(), ConnStateData::resetReadTimeout(), PeerSelector::resolveSelected(), ConnStateData::sendControlMsg(), ConnStateData::serveDelayedError(), ConnStateData::setAuth(), ConnStateData::splice(), ClientRequestContext::sslBumpAccessCheckDone(), ClientHttpRequest::sslBumpEstablish(), ClientHttpRequest::sslBumpStart(), ConnStateData::sslCrtdHandleReply(), ConnStateData::start(), ConnStateData::startPeekAndSplice(), statClientRequests(), Server::stopReading(), ConnStateData::stopReceiving(), ConnStateData::stopSending(), ConnStateData::storeTlsContextToCache(), ConnStateData::swanSong(), Server::swanSong(), ConnStateData::switchToHttps(), ConnStateData::terminateAll(), ConnStateData::transparent(), ConnStateData::tunnelOnError(), tunnelStart(), ConnStateData::whenClientIpKnown(), Server::write(), and Server::write().
closeHandler
AsyncCall::Pointer ConnStateData::closeHandler inherited
Definition at line 153 of file client_side.h.
dataConn
Comm::ConnectionPointer Ftp::Server::dataConn private
Definition at line 189 of file FtpServer.h.
dataConnWait
JobWait<Comm::ConnOpener> Ftp::Server::dataConnWait private
Waits for an FTP data connection to the client to be established/opened. This wait only happens in FTP active mode (via PORT or EPRT).
Definition at line 197 of file FtpServer.h.
dataListenConn
Comm::ConnectionPointer Ftp::Server::dataListenConn private
Definition at line 188 of file FtpServer.h.
delayedReply
HttpReply::Pointer Ftp::Server::delayedReply private
Definition at line 207 of file FtpServer.h.
[struct]
struct { ... } ConnStateData::flags
Referenced by Server(), ConnStateData::~ConnStateData(), ConnStateData::abortChunkedRequestBody(), ConnStateData::buildFakeRequest(), ConnStateData::clientAfterReadingRequests(), clientProcessRequest(), clientProcessRequestFinished(), ClientHttpRequest::doCallouts(), ConnStateData::kick(), ConnStateData::parseRequests(), ConnStateData::quitAfterError(), ConnStateData::swanSong(), and ConnStateData::switchToHttps().
gotEpsvAll
bool Ftp::Server::gotEpsvAll private
Definition at line 186 of file FtpServer.h.
host
SBuf Ftp::Server::host private
Definition at line 185 of file FtpServer.h.
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inBuf
SBuf Server::inBuf inherited
Definition at line 113 of file Server.h.
Referenced by ConnStateData::abortChunkedRequestBody(), ConnStateData::abortRequestParsing(), ConnStateData::buildFakeRequest(), ConnStateData::checkLogging(), ConnStateData::consumeInput(), Server::doClientRead(), ConnStateData::getSslContextDone(), ConnStateData::handleChunkedRequestBody(), ConnStateData::handleRequestBodyData(), httpsSslBumpAccessCheckDone(), Server::maybeMakeSpaceAvailable(), Server::mayBufferMoreRequestBytes(), ConnStateData::mayNeedToReadMoreBody(), ConnStateData::parseHttpRequest(), ConnStateData::parseProxyProtocolHeader(), ConnStateData::parseRequests(), ConnStateData::parseTlsHandshake(), ConnStateData::shouldCloseOnEof(), ConnStateData::startPeekAndSplice(), statClientRequests(), ConnStateData::stopSending(), ConnStateData::terminateAll(), and tunnelStartShoveling().
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
keyLogger
Security::KeyLogger ConnStateData::keyLogger inherited
Definition at line 384 of file client_side.h.
Referenced by ConnStateData::acceptTls().
listener
AsyncCall::Pointer Ftp::Server::listener private
Definition at line 193 of file FtpServer.h.
log_addr
Ip::Address ConnStateData::log_addr inherited
Definition at line 136 of file client_side.h.
Referenced by ClientHttpRequest::ClientHttpRequest(), ConnStateData::ConnStateData(), and ConnStateData::postHttpsAccept().
master
MasterState::Pointer Ftp::Server::master
Definition at line 80 of file FtpServer.h.
needProxyProtocolHeader_
bool ConnStateData::needProxyProtocolHeader_ = false private inherited
Definition at line 467 of file client_side.h.
Referenced by ConnStateData::parseProxyProtocolHeader(), ConnStateData::parseRequests(), ConnStateData::shouldPreserveClientData(), and ConnStateData::start().
onDataAcceptCall
AsyncCall::Pointer Ftp::Server::onDataAcceptCall private
Definition at line 187 of file FtpServer.h.
originDataDownloadAbortedOnError
bool Ftp::Server::originDataDownloadAbortedOnError private
Definition at line 204 of file FtpServer.h.
parsedBumpedRequestCount
uint64_t ConnStateData::parsedBumpedRequestCount = 0 private inherited
Definition at line 481 of file client_side.h.
Referenced by ConnStateData::parseRequests(), and ConnStateData::shouldPreserveClientData().
parsingTlsHandshake
bool ConnStateData::parsingTlsHandshake = false private inherited
whether we are getting/parsing TLS Hello bytes
Definition at line 479 of file client_side.h.
Referenced by ConnStateData::afterClientRead(), ConnStateData::parseTlsHandshake(), ConnStateData::shouldPreserveClientData(), ConnStateData::switchToHttps(), and ConnStateData::terminateAll().
peerAccessDenied
bool ConnStateData::peerAccessDenied = false inherited
Definition at line 150 of file client_side.h.
Referenced by PeerSelector::selectPinned().
pinned
bool ConnStateData::pinned = false inherited
Definition at line 146 of file client_side.h.
Referenced by HttpRequest::pinnedConnection().
[struct]
struct { ... } ConnStateData::pinning
Referenced by ConnStateData::borrowPinnedConnection(), clientCheckPinning(), ConnStateData::clientPinnedConnectionClosed(), ConnStateData::clientPinnedConnectionRead(), ConnStateData::handleIdleClientPinnedTlsRead(), ConnStateData::initiateTunneledRequest(), ConnStateData::kick(), ConnStateData::parseRequests(), ConnStateData::pinConnection(), ConnStateData::pinnedAuth(), HttpRequest::pinnedConnection(), ConnStateData::pinnedPeer(), ConnStateData::pipelinePrefetchMax(), PeerSelector::selectPinned(), ConnStateData::startPinnedConnectionMonitoring(), ConnStateData::stopPinnedConnectionMonitoring(), and ConnStateData::unpinConnection().
pipeline
Pipeline Server::pipeline inherited
Definition at line 118 of file Server.h.
Referenced by ConnStateData::abortChunkedRequestBody(), ConnStateData::add(), ConnStateData::afterClientRead(), ConnStateData::afterClientWrite(), ConnStateData::checkLogging(), clientNegotiateSSL(), ConnStateData::clientPinnedConnectionRead(), clientSocketRecipient(), ConnStateData::concurrentRequestQueueFilled(), ConnStateData::doneWithControlMsg(), ConnStateData::fillChecklist(), ConnStateData::finishDechunkingRequest(), Http::Stream::finished(), ConnStateData::httpsPeeked(), httpsSslBumpStep2AccessCheckDone(), ConnStateData::kick(), ConnStateData::notePinnedConnectionBecameIdle(), ConnStateData::parseRequests(), ConnStateData::parseTlsHandshake(), ConnStateData::postHttpsAccept(), ConnStateData::sendControlMsg(), ConnStateData::shouldCloseOnEof(), ConnStateData::shouldPreserveClientData(), ConnStateData::splice(), ConnStateData::startPeekAndSplice(), ConnStateData::startShutdown(), statClientRequests(), ConnStateData::terminateAll(), ConnStateData::tunnelOnError(), and ConnStateData::updateError().
port
AnyP::Port ConnStateData::port inherited
Definition at line 145 of file client_side.h.
Referenced by ClientHttpRequest::ClientHttpRequest(), ConnStateData::buildFakeRequest(), clientReplyContext::buildReplyHeader(), ConnStateData::buildSslCertGenerationParams(), clientCheckPinning(), clientProcessRequest(), ConnStateData::getSslContextDone(), ConnStateData::getSslContextStart(), ConnStateData::getTlsContextFromCache(), httpsCreate(), HttpRequest::manager(), ConnStateData::parseHttpRequest(), ConnStateData::postHttpsAccept(), prepareAcceleratedURL(), ConnStateData::shouldPreserveClientData(), ClientRequestContext::sslBumpAccessCheck(), ConnStateData::sslCrtdHandleReply(), ConnStateData::start(), ConnStateData::startPeekAndSplice(), ConnStateData::storeTlsContextToCache(), and ACLFilledChecklist::verifyAle().
preservedClientData
SBuf ConnStateData::preservedClientData inherited
From-client handshake bytes (including bytes at the beginning of a CONNECT tunnel) which we may need to forward as-is if their syntax does not match the expected TLS or HTTP protocol (on_unsupported_protocol).
Definition at line 349 of file client_side.h.
Referenced by Format::Format::assemble(), ConnStateData::parseHttpRequest(), ConnStateData::parseTlsHandshake(), ConnStateData::splice(), and ConnStateData::tunnelOnError().
preservingClientData_
bool ConnStateData::preservingClientData_ = false protected inherited
Definition at line 434 of file client_side.h.
Referenced by ConnStateData::parseHttpRequest(), ConnStateData::parseRequests(), ConnStateData::start(), ConnStateData::switchToHttps(), and ConnStateData::tunnelOnError().
proxyProtocolHeader_
ProxyProtocol::HeaderPointer ConnStateData::proxyProtocolHeader_ private inherited
Definition at line 470 of file client_side.h.
Referenced by ConnStateData::parseProxyProtocolHeader(), ConnStateData::postHttpsAccept(), and ConnStateData::proxyProtocolHeader().
reader
AsyncCall::Pointer Ftp::Server::reader private
Definition at line 199 of file FtpServer.h.
readHandler
AsyncCall::Pointer ConnStateData::readHandler inherited
Definition at line 152 of file client_side.h.
reading
bool ConnStateData::reading = false inherited
Definition at line 148 of file client_side.h.
readMore
bool ConnStateData::readMore = true inherited
Definition at line 139 of file client_side.h.
Referenced by Server(), clientProcessRequest(), clientProcessRequestFinished(), and ClientHttpRequest::doCallouts().
receivedFirstByte_
bool Server::receivedFirstByte_ inherited
Definition at line 115 of file Server.h.
Referenced by Server::doClientRead(), ConnStateData::receivedFirstByte(), ConnStateData::requestTimeout(), and ConnStateData::switchToHttps().
serverConnection
Comm::ConnectionPointer ConnStateData::serverConnection inherited
Definition at line 143 of file client_side.h.
Referenced by clientCheckPinning().
signAlgorithm
Ssl::CertSignAlgorithm ConnStateData::signAlgorithm = Ssl::algSignTrusted private inherited
Definition at line 495 of file client_side.h.
Referenced by ConnStateData::buildSslCertGenerationParams(), ConnStateData::getSslContextStart(), and ConnStateData::sslCrtdHandleReply().
sslBumpCertKey
SBuf ConnStateData::sslBumpCertKey private inherited
Definition at line 491 of file client_side.h.
Referenced by ConnStateData::getSslContextStart(), and ConnStateData::sslCrtdHandleReply().
sslBumpMode
Ssl::BumpMode ConnStateData::sslBumpMode = Ssl::bumpEnd inherited
Definition at line 304 of file client_side.h.
Referenced by ConnStateData::concurrentRequestQueueFilled(), httpsSslBumpAccessCheckDone(), httpsSslBumpStep2AccessCheckDone(), ClientRequestContext::sslBumpAccessCheck(), and ClientHttpRequest::sslBumpStart().
sslCommonName_
SBuf ConnStateData::sslCommonName_ private inherited
Definition at line 487 of file client_side.h.
Referenced by ConnStateData::buildSslCertGenerationParams(), ConnStateData::resetSslCommonName(), and ConnStateData::sslCommonName().
sslServerBump
Ssl::ServerBump* ConnStateData::sslServerBump = nullptr private inherited
Definition at line 494 of file client_side.h.
Referenced by ConnStateData::~ConnStateData(), ConnStateData::buildSslCertGenerationParams(), ConnStateData::fillConnectionLevelDetails(), ConnStateData::getSslContextStart(), ConnStateData::httpsPeeked(), ConnStateData::parseTlsHandshake(), ConnStateData::serveDelayedError(), ConnStateData::serverBump(), ConnStateData::setServerBump(), ConnStateData::sslCrtdHandleReply(), ConnStateData::startPeekAndSplice(), and ConnStateData::switchToHttps().
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stoppedReceiving_
const char* ConnStateData::stoppedReceiving_ = nullptr private inherited
Definition at line 501 of file client_side.h.
Referenced by ConnStateData::stoppedReceiving(), ConnStateData::stopReceiving(), and ConnStateData::stopSending().
stoppedSending_
const char* ConnStateData::stoppedSending_ = nullptr private inherited
Definition at line 499 of file client_side.h.
Referenced by ConnStateData::stoppedSending(), ConnStateData::stopReceiving(), and ConnStateData::stopSending().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang
bool ConnStateData::swanSang = false inherited
Definition at line 140 of file client_side.h.
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
switchedToHttps_
bool ConnStateData::switchedToHttps_ = false private inherited
Definition at line 478 of file client_side.h.
Referenced by ConnStateData::doPeekAndSpliceStep(), ConnStateData::getSslContextDone(), ConnStateData::startPeekAndSplice(), ConnStateData::switchedToHttps(), and ConnStateData::switchToHttps().
theNotes
NotePairs::Pointer ConnStateData::theNotes private inherited
Connection annotations, clt_conn_tag and other tags are stored here. If set, are propagated to the current and all future master transactions on the connection.
Definition at line 505 of file client_side.h.
Referenced by ConnStateData::hasNotes(), and ConnStateData::notes().
tlsClientSni_
SBuf ConnStateData::tlsClientSni_ private inherited
Definition at line 490 of file client_side.h.
Referenced by ConnStateData::fakeAConnectRequest(), ConnStateData::parseTlsHandshake(), and ConnStateData::tlsClientSni().
tlsConnectHostOrIp
SBuf ConnStateData::tlsConnectHostOrIp private inherited
The TLS server host name as passed in the CONNECT request
Definition at line 485 of file client_side.h.
Referenced by ConnStateData::buildSslCertGenerationParams(), ConnStateData::getSslContextDone(), ConnStateData::httpsPeeked(), ConnStateData::initiateTunneledRequest(), ConnStateData::prepareTlsSwitchingURL(), ConnStateData::sslCrtdHandleReply(), and ConnStateData::switchToHttps().
tlsConnectPort
AnyP::Port ConnStateData::tlsConnectPort private inherited
Definition at line 486 of file client_side.h.
Referenced by ConnStateData::initiateTunneledRequest(), ConnStateData::prepareTlsSwitchingURL(), and ConnStateData::switchToHttps().
tlsParser
Security::HandshakeParser ConnStateData::tlsParser inherited
Tls parser to use for client HELLO messages parsing on bumped connections.
Definition at line 308 of file client_side.h.
Referenced by ConnStateData::parseTlsHandshake().
transferProtocol
AnyP::ProtocolVersion Server::transferProtocol inherited
The transfer protocol currently being spoken on this connection. HTTP/1.x CONNECT, HTTP/1.1 Upgrade and HTTP/2 SETTINGS offer the ability to change protocols on the fly.
Definition at line 107 of file Server.h.
Referenced by buildUrlFromHost(), ConnStateData::parseHttpRequest(), prepareAcceleratedURL(), ConnStateData::prepareTlsSwitchingURL(), prepareTransparentURL(), ConnStateData::splice(), and ConnStateData::switchToHttps().
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
uploadAvailSize
size_t Ftp::Server::uploadAvailSize private
Definition at line 191 of file FtpServer.h.
uploadBuf
char Ftp::Server::uploadBuf[CLIENT_REQ_BUF_SZ] private
Definition at line 190 of file FtpServer.h.
Referenced by Server().
uri
SBuf Ftp::Server::uri private
Definition at line 184 of file FtpServer.h.
waitingForOrigin
bool Ftp::Server::waitingForOrigin private
Definition at line 202 of file FtpServer.h.
writer
AsyncCall::Pointer Server::writer protected inherited
Definition at line 131 of file Server.h.
Referenced by Server::clientWriteDone(), Server::write(), Server::write(), and Server::writing().
zeroReply
bool ConnStateData::zeroReply = false inherited
Definition at line 149 of file client_side.h.
The documentation for this class was generated from the following files:
squid/src/servers/FtpServer.h
squid/src/servers/FtpServer.cc