Squid Web Cache: TestACLMaxUserIP Class Reference
TestACLMaxUserIP Class Reference
Protected Member Functions
void testDefaults ()
void testParseLine ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestACLMaxUserIP)
CPPUNIT_TEST (testDefaults)
CPPUNIT_TEST (testParseLine)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 28 of file testACLMaxUserIP.cc.
Member Function Documentation
CPPUNIT_TEST() [1/2]
TestACLMaxUserIP::CPPUNIT_TEST (testDefaults) private
CPPUNIT_TEST() [2/2]
TestACLMaxUserIP::CPPUNIT_TEST (testParseLine) private
CPPUNIT_TEST_SUITE()
TestACLMaxUserIP::CPPUNIT_TEST_SUITE (TestACLMaxUserIP) private
CPPUNIT_TEST_SUITE_END()
TestACLMaxUserIP::CPPUNIT_TEST_SUITE_END () private
testDefaults()
void TestACLMaxUserIP::testDefaults () protected
Definition at line 46 of file testACLMaxUserIP.cc.
References ACLMaxUserIP::beStrict, ACLMaxUserIP::getMaximum(), and ACLMaxUserIP::valid().
testParseLine()
void TestACLMaxUserIP::testParseLine () protected
Definition at line 72 of file testACLMaxUserIP.cc.
References ACLMaxUserIP::beStrict, Config, Acl::Node::FindByName(), Acl::FreeNamedAcls(), ACLMaxUserIP::getMaximum(), LegacyParser, SquidConfig::namedAcls, Acl::Node::ParseNamedAcl(), ConfigParser::SetCfgLine(), ACLMaxUserIP::valid(), xfree, and xstrdup.
The documentation for this class was generated from the following file:
squid/src/tests/testACLMaxUserIP.cc