Squid Web Cache: CommSelectEngine Class Reference
CommSelectEngine Class Reference
#include <comm.h>
Public Types
enum CheckError { EVENT_IDLE = -1 , EVENT_ERROR = -2 }
Public Member Functions
int checkEvents (int timeout) override
Detailed Description
Definition at line 108 of file comm.h.
Member Enumeration Documentation
CheckError
enum AsyncEngine::CheckError inherited
Enumerator
EVENT_IDLE
EVENT_ERROR
Definition at line 26 of file AsyncEngine.h.
Member Function Documentation
checkEvents()
int CommSelectEngine::checkEvents (int timeout) override virtual
Implements AsyncEngine.
Definition at line 1644 of file comm.cc.
References checkTimeouts(), Comm::COMM_ERROR, Comm::DoSelect(), AsyncEngine::EVENT_ERROR, AsyncEngine::EVENT_IDLE, fatal_dump(), Comm::IDLE, Comm::OK, Comm::SHUTDOWN, squid_curtime, and Comm::TIMEOUT.
The documentation for this class was generated from the following files:
squid/src/comm.h
squid/src/comm.cc