Squid Web Cache: DelayTagged::Id Class Reference
DelayTagged::Id Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Public Types
typedef RefCount< DelayIdComposite > Pointer
Public Member Functions
Id (const RefCount< DelayTagged > &, const SBuf &)
~Id () override
int bytesWanted (int min, int max) const override
void bytesIn (int qty) override
void delayRead (const AsyncCallPointer &) override
Private Member Functions
MEMPROXY_CLASS (DelayTagged::Id)
Private Attributes
RefCount< DelayTagged > theTagged
DelayTaggedBucket::Pointer theBucket
Detailed Description
Definition at line 60 of file DelayTagged.h.
Member Typedef Documentation
Pointer
typedef RefCount<DelayIdComposite> DelayIdComposite::Pointer inherited
Definition at line 23 of file DelayIdComposite.h.
Constructor & Destructor Documentation
Id()
DelayTagged::Id::Id (const RefCount< DelayTagged > & aDelayTagged, const SBuf & aTag)
Definition at line 136 of file DelayTagged.cc.
References DelayTagged::buckets, DelayTaggedCmp, DelayBucket::init(), DelayTagged::spec, DelayTaggedBucket::theBucket, theBucket, and theTagged.
~Id()
DelayTagged::Id::~Id () override
Definition at line 150 of file DelayTagged.cc.
References debugs.
Member Function Documentation
bytesIn()
void DelayTagged::Id::bytesIn (int qty) override virtual
Implements DelayIdComposite.
Definition at line 162 of file DelayTagged.cc.
bytesWanted()
int DelayTagged::Id::bytesWanted (int min, int max) const override virtual
Implements DelayIdComposite.
Definition at line 156 of file DelayTagged.cc.
References max(), and min().
delayRead()
void DelayTagged::Id::delayRead (const AsyncCallPointer & aRead) override virtual
Reimplemented from DelayIdComposite.
Definition at line 168 of file DelayTagged.cc.
MEMPROXY_CLASS()
DelayTagged::Id::MEMPROXY_CLASS (DelayTagged::Id) private
Member Data Documentation
theBucket
DelayTaggedBucket::Pointer DelayTagged::Id::theBucket private
Definition at line 73 of file DelayTagged.h.
Referenced by Id().
theTagged
RefCount<DelayTagged> DelayTagged::Id::theTagged private
Definition at line 72 of file DelayTagged.h.
Referenced by Id().
The documentation for this class was generated from the following files:
squid/src/DelayTagged.h
squid/src/DelayTagged.cc