Squid Web Cache: ACLExternal Class Reference
ACLExternal Class Reference
#include <ExternalACL.h>
Public Types
using Pointer = RefCount< Node >
Public Member Functions
ACLExternal (char const *)
~ACLExternal () override
char const * typeString () const override
void parse () override
parses node representation in squid.conf; dies on failures
int match (ACLChecklist *checklist) override
Matches the actual data in checklist against this Acl::Node.
bool requiresAle () const override
whether our (i.e. shallow) match() requires checklist to have a AccessLogEntry
bool requiresRequest () const override
whether our (i.e. shallow) match() requires checklist to have a request
bool isProxyAuth () const override
SBufList dump () const override
bool valid () const override
bool empty () const override
void * operator new (size_t)
void operator delete (void *)
void context (const SBuf &aName, const char *configuration)
sets user-specified ACL name and squid.conf context
bool matches (ACLChecklist *checklist) const
void parseFlags ()
configures Acl::Node options, throwing on configuration errors
int cacheMatchAcl (dlink_list *cache, ACLChecklist *)
virtual int matchForCache (ACLChecklist *checklist)
virtual void prepareForUse ()
void dumpWhole (const char *directiveName, std::ostream &)
Static Public Member Functions
static void ParseNamedAcl (ConfigParser &, NamedAcls *&)
parses acl directive parts that follow directive name (i.e. "acl")
static void Initialize ()
static Acl::Node * FindByName (const SBuf &)
A configured ACL with a given name or nil.
Public Attributes
SBuf name
char * cfgline = nullptr
Private Member Functions
MEMPROXY_CLASS (ACLExternal)
void startLookup (ACLFilledChecklist *, external_acl_data *, bool inBackground) const
Acl::Answer aclMatchExternal (external_acl_data *, ACLFilledChecklist *) const
char * makeExternalAclKey (ACLFilledChecklist *, external_acl_data *) const
virtual bool requiresReply () const
whether our (i.e. shallow) match() requires checklist to have a reply
virtual const Acl::Options & options ()
virtual const Acl::Options & lineOptions ()
Static Private Member Functions
static void StartLookup (ACLFilledChecklist &, const Acl::Node &)
static void LookupDone (void *data, const ExternalACLEntryPointer &)
Called when an async lookup returns.
static void ParseNamed (ConfigParser &, NamedAcls &, const SBuf &name)
parses acl directive parts that follow aclname
Private Attributes
external_acl_data * data
char const * class_
Detailed Description
Definition at line 20 of file ExternalACL.h.
Member Typedef Documentation
Pointer
using Acl::Node::Pointer = RefCount<Node> inherited
Definition at line 29 of file Node.h.
Constructor & Destructor Documentation
ACLExternal()
ACLExternal::ACLExternal (char const * theClass)
Definition at line 1146 of file external_acl.cc.
~ACLExternal()
ACLExternal::~ACLExternal () override
Definition at line 559 of file external_acl.cc.
References class_, data, and xfree.
Member Function Documentation
aclMatchExternal()
Acl::Answer ACLExternal::aclMatchExternal (external_acl_data * acl, ACLFilledChecklist * ch) const private
Definition at line 592 of file external_acl.cc.
References ACCESS_DUNNO, AuthenticateAcl(), external_acl::cache, cbdataReferenceValid(), copyResultsFromEntry(), ExternalACLEntry::date, DBG_IMPORTANT, debugs, external_acl_data::def, ExternalACLEntry::def, ACLFilledChecklist::extacl_entry, external_acl_cache_touch(), external_acl_entry_expired(), external_acl_grace_expired(), external_acl_message, ACLChecklist::goAsync(), hash_lookup(), hash_link::key, ExternalACLEntry::log, makeExternalAclKey(), ExternalACLEntry::message, external_acl::name, ACLFilledChecklist::request, external_acl::require_auth, ExternalACLEntry::result, StartLookup(), startLookup(), ExternalACLEntry::tag, String::termedBuf(), external_acl::theHelper, and ExternalACLEntry::user.
Referenced by match().
cacheMatchAcl()
int Acl::Node::cacheMatchAcl (dlink_list * cache, ACLChecklist * checklist) inherited
Definition at line 401 of file Acl.cc.
References acl_proxy_auth_match_cache::acl_data, dlink_node::data, debugs, dlinkAddTail(), dlink_list::head, acl_proxy_auth_match_cache::link, acl_proxy_auth_match_cache::matchrv, and dlink_node::next.
Referenced by ACLProxyAuth::matchProxyAuth().
context()
void Acl::Node::context (const SBuf & aName, const char * configuration) inherited
Definition at line 220 of file Acl.cc.
References safe_free, and xstrdup.
Referenced by aclParseAccessLine(), aclParseAclList(), Acl::AllOf::parse(), and ParseAclWithAction().
dump()
SBufList ACLExternal::dump () const override virtual
Implements Acl::Node.
Definition at line 732 of file external_acl.cc.
References external_acl_data::arguments, data, external_acl_data::def, external_acl::name, SBuf::Printf(), and SBuf::push_back().
dumpWhole()
void Acl::Node::dumpWhole (const char * directiveName, std::ostream & os) inherited
Prints aggregated "acl" (or similar) directive configuration, including the given directive name, ACL name, ACL type, and ACL parameters. The printed parameters are collected from all same-name "acl" directives.
Definition at line 371 of file Acl.cc.
References asList().
empty()
bool ACLExternal::empty () const override virtual
Implements Acl::Node.
Definition at line 554 of file external_acl.cc.
FindByName()
Acl::Node * Acl::Node::FindByName (const SBuf & name) static inherited
Definition at line 159 of file Acl.cc.
References assert, Config, debugs, and SquidConfig::namedAcls.
Referenced by aclIsProxyAuth(), Acl::InnerNode::lineParse(), parse_ftp_epsv(), and TestACLMaxUserIP::testParseLine().
Initialize()
void Acl::Node::Initialize () static inherited
Definition at line 471 of file Acl.cc.
References Config, debugs, and SquidConfig::namedAcls.
Referenced by serverConnectionsOpen().
isProxyAuth()
bool ACLExternal::isProxyAuth () const override virtual
Reimplemented from Acl::Node.
Definition at line 1156 of file external_acl.cc.
References data, external_acl_data::def, and external_acl::require_auth.
lineOptions()
virtual const Acl::Options & Acl::Node::lineOptions () inline private virtual inherited
Returns
(linked) "line" Options supported by this Acl::Node
See also
Acl::Node::options()
Reimplemented in ACLExtUser, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, Acl::ParameterizedNode< ACLTimeData >, and ACLProxyAuth.
Definition at line 102 of file Node.h.
References Acl::NoOptions().
LookupDone()
void ACLExternal::LookupDone (void * data, const ExternalACLEntryPointer & result) static private
Definition at line 1139 of file external_acl.cc.
References data, ACLFilledChecklist::extacl_entry, Filled(), and ACLChecklist::resumeNonBlockingCheck().
Referenced by startLookup().
makeExternalAclKey()
char * ACLExternal::makeExternalAclKey (ACLFilledChecklist * ch, external_acl_data * acl_data) const private
Definition at line 764 of file external_acl.cc.
References ACLFilledChecklist::al, SBuf::append(), external_acl_data::arguments, Format::Format::assemble(), MemBuf::buf, MemBuf::clean(), external_acl_data::def, external_acl::format, Format::Format::format, MemBuf::init(), AccessLogEntry::lastAclData, AccessLogEntry::lastAclName, SBuf::length(), Format::LFT_EXT_ACL_DATA, Format::LFT_EXT_ACL_NAME, Format::LOG_QUOTE_URL, external_acl_data::name, external_acl::quote, MemBuf::reset(), rfc1738_escape, MemBuf::size, and strwordquote().
Referenced by aclMatchExternal(), and startLookup().
match()
int ACLExternal::match (ACLChecklist * checklist) override virtual
Implements Acl::Node.
Definition at line 708 of file external_acl.cc.
References ACCESS_ALLOWED, ACCESS_AUTH_REQUIRED, ACCESS_DENIED, ACCESS_DUNNO, aclMatchExternal(), data, Filled(), ACLChecklist::keepMatching(), and ACLChecklist::markFinished().
matches()
bool Acl::Node::matches (ACLChecklist * checklist) const inherited
Orchestrates matching checklist against the Acl::Node using match(), after checking preconditions and while providing debugging.
Returns
true if and only if there was a successful match. Updates the checklist state on match, async, and failure.
Definition at line 189 of file Acl.cc.
References ACLChecklist::asyncInProgress(), DBG_IMPORTANT, debugs, ACLChecklist::hasAle(), ACLChecklist::hasReply(), ACLChecklist::hasRequest(), ACLChecklist::setLastCheckedName(), and ACLChecklist::verifyAle().
Referenced by ACLChecklist::matchAndFinish().
matchForCache()
int Acl::Node::matchForCache (ACLChecklist * checklist) virtual inherited
Reimplemented in ACLProxyAuth.
Definition at line 383 of file Acl.cc.
References fatal().
MEMPROXY_CLASS()
ACLExternal::MEMPROXY_CLASS (ACLExternal) private
operator delete()
void Acl::Node::operator delete (void *) inherited
Definition at line 153 of file Acl.cc.
References fatal().
operator new()
void * Acl::Node::operator new (size_t) inherited
Definition at line 147 of file Acl.cc.
References fatal().
options()
virtual const Acl::Options & Acl::Node::options () inline private virtual inherited
Returns
(linked) 'global' Options supported by this Acl::Node
Reimplemented in Acl::DestinationDomainCheck, ACLDestinationIP, Acl::AnnotationCheck, Acl::ServerNameCheck, and ACLMaxUserIP.
Definition at line 98 of file Node.h.
References Acl::NoOptions().
parse()
void ACLExternal::parse () override virtual
Implements Acl::Node.
Definition at line 502 of file external_acl.cc.
References external_acl_data::arguments, data, external_acl_data::def, find_externalAclHelper(), Acl::Node::name, external_acl_data::name, self_destruct(), ConfigParser::strtokFile(), and wordlistAdd().
parseFlags()
void Acl::Node::parseFlags () inherited
Definition at line 360 of file Acl.cc.
References Acl::ParseFlags().
ParseNamed()
void Acl::Node::ParseNamed (ConfigParser & parser, NamedAcls & namedAcls, const SBuf & name) static private inherited
Definition at line 253 of file Acl.cc.
References Assure, SBuf::cmp(), config_input_line, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::destruct(), fatalf(), HttpPortList, Acl::Make(), and ConfigParser::NextToken().
ParseNamedAcl()
void Acl::Node::ParseNamedAcl (ConfigParser & parser, NamedAcls *& namedAcls) static inherited
Definition at line 229 of file Acl.cc.
References CallParser(), DBG_CRITICAL, debugs, ConfigParser::destruct(), RefCount< C >::Make(), and ConfigParser::NextToken().
Referenced by parse_acl(), and TestACLMaxUserIP::testParseLine().
prepareForUse()
virtual void Acl::Node::prepareForUse () inline virtual inherited
Reimplemented in Acl::InnerNode, ACLMaxConnection, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, and Acl::ParameterizedNode< ACLTimeData >.
Definition at line 69 of file Node.h.
requiresAle()
bool ACLExternal::requiresAle () const inline override virtual
Reimplemented from Acl::Node.
Definition at line 32 of file ExternalACL.h.
requiresReply()
bool Acl::Node::requiresReply () const private virtual inherited
Reimplemented in Acl::HttpRepHeaderCheck, ACLHTTPStatus, and Acl::ReplyHeaderCheck< header >.
Definition at line 449 of file Acl.cc.
requiresRequest()
bool ACLExternal::requiresRequest () const inline override virtual
Reimplemented from Acl::Node.
Definition at line 33 of file ExternalACL.h.
StartLookup()
void ACLExternal::StartLookup (ACLFilledChecklist & checklist, const Acl::Node & acl) static private
Asks the helper (if needed) or returns the [cached] result (otherwise). Does not support "background" lookups. See also: ACLExternal::Start().
Definition at line 1008 of file external_acl.cc.
References startLookup().
Referenced by aclMatchExternal().
startLookup()
void ACLExternal::startLookup (ACLFilledChecklist * ch, external_acl_data * acl, bool inBackground) const private
Definition at line 1017 of file external_acl.cc.
References Packable::appendf(), assert, MemBuf::buf, external_acl::cache_size, externalAclState::callback, externalAclState::callback_data, cbdataReference, MemBuf::clean(), debugs, external_acl_data::def, dlinkAdd(), externalAclHandleReply(), dlink_list::head, MemBuf::init(), externalAclState::key, externalAclState::list, LookupDone(), makeExternalAclKey(), external_acl::name, node::next, external_acl::queue, externalAclState::queue, and external_acl::theHelper.
Referenced by aclMatchExternal(), and StartLookup().
typeString()
char const * ACLExternal::typeString () const override virtual
Implements Acl::Node.
Definition at line 1150 of file external_acl.cc.
References class_.
valid()
bool ACLExternal::valid () const override virtual
Reimplemented from Acl::Node.
Definition at line 534 of file external_acl.cc.
References authenticateActiveSchemeCount(), authenticateSchemeCount(), data, DBG_CRITICAL, debugs, external_acl_data::def, and external_acl::require_auth.
Member Data Documentation
cfgline
char* Acl::Node::cfgline = nullptr inherited
Definition at line 83 of file Node.h.
class_
char const* ACLExternal::class_ private
Definition at line 50 of file ExternalACL.h.
Referenced by ~ACLExternal(), and typeString().
data
external_acl_data* ACLExternal::data private
Definition at line 49 of file ExternalACL.h.
Referenced by ~ACLExternal(), dump(), isProxyAuth(), LookupDone(), match(), parse(), and valid().
name
SBuf Acl::Node::name inherited
Either aclname parameter from the explicitly configured acl directive or a label generated for an internal ACL tree node. All Node objects corresponding to one Squid configuration have unique names. See also: context() and FindByName().
Definition at line 81 of file Node.h.
Referenced by Acl::NotNode::NotNode(), aclDestroyAccessList(), Acl::AnnotateClientCheck::match(), Acl::AnnotateTransactionCheck::match(), Acl::SourceDomainCheck::match(), ACLDestinationIP::match(), ACLRandom::match(), parse(), and ACLMaxConnection::prepareForUse().
The documentation for this class was generated from the following files:
squid/src/ExternalACL.h
squid/src/external_acl.cc