Squid Web Cache: Adaptation::Ecap::RequestLineRep Class Reference
Adaptation::Ecap::RequestLineRep Class Reference
#include <MessageRep.h>
Public Types
typedef libecap::Area Area
typedef libecap::Name Name
Public Member Functions
RequestLineRep (HttpRequest &aMessage)
void uri (const Area &aUri) override
Area uri () const override
void method (const Name &aMethod) override
Name method () const override
libecap::Version version () const override
void version (const libecap::Version &aVersion) override
Name protocol () const override
void protocol (const Name &aProtocol) override
Static Protected Member Functions
static AnyP::ProtocolType TranslateProtocolId (const Name &name)
Private Attributes
HttpRequest & theMessage
Detailed Description
Definition at line 87 of file MessageRep.h.
Member Typedef Documentation
Area
typedef libecap::Area Adaptation::Ecap::RequestLineRep::Area
Definition at line 91 of file MessageRep.h.
Name
typedef libecap::Name Adaptation::Ecap::FirstLineRep::Name inherited
Definition at line 69 of file MessageRep.h.
Constructor & Destructor Documentation
RequestLineRep()
Adaptation::Ecap::RequestLineRep::RequestLineRep (HttpRequest & aMessage)
Definition at line 198 of file MessageRep.cc.
Member Function Documentation
method() [1/2]
Adaptation::Ecap::RequestLineRep::Name Adaptation::Ecap::RequestLineRep::method () const override
Definition at line 237 of file MessageRep.cc.
References Http::METHOD_CONNECT, Http::METHOD_DELETE, Http::METHOD_GET, Http::METHOD_HEAD, Http::METHOD_POST, Http::METHOD_PUT, and Http::METHOD_TRACE.
method() [2/2]
void Adaptation::Ecap::RequestLineRep::method (const Name & aMethod) override
Definition at line 223 of file MessageRep.cc.
References Http::METHOD_ENUM_END, Http::METHOD_NONE, Http::METHOD_OTHER, and Must.
protocol() [1/2]
libecap::Name Adaptation::Ecap::RequestLineRep::protocol () const override
Definition at line 272 of file MessageRep.cc.
References Adaptation::Ecap::FirstLineRep::protocol().
protocol() [2/2]
void Adaptation::Ecap::RequestLineRep::protocol (const Name & aProtocol) override
Definition at line 278 of file MessageRep.cc.
References Adaptation::Ecap::FirstLineRep::protocol().
TranslateProtocolId()
AnyP::ProtocolType Adaptation::Ecap::FirstLineRep::TranslateProtocolId (const Name & name) static protected inherited
Definition at line 189 of file MessageRep.cc.
References AnyP::PROTO_UNKNOWN.
uri() [1/2]
Adaptation::Ecap::RequestLineRep::Area Adaptation::Ecap::RequestLineRep::uri () const override
Definition at line 213 of file MessageRep.cc.
References SBuf::isEmpty(), SBuf::length(), Must, and SBuf::rawContent().
uri() [2/2]
void Adaptation::Ecap::RequestLineRep::uri (const Area & aUri) override
Definition at line 204 of file MessageRep.cc.
References Must.
version() [1/2]
libecap::Version Adaptation::Ecap::RequestLineRep::version () const override
Definition at line 260 of file MessageRep.cc.
References Adaptation::Ecap::FirstLineRep::version().
version() [2/2]
void Adaptation::Ecap::RequestLineRep::version (const libecap::Version & aVersion) override
Definition at line 266 of file MessageRep.cc.
References Adaptation::Ecap::FirstLineRep::version().
Member Data Documentation
theMessage
HttpRequest& Adaptation::Ecap::RequestLineRep::theMessage private
Definition at line 107 of file MessageRep.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/MessageRep.h
squid/src/adaptation/ecap/MessageRep.cc