Squid Web Cache: TestRock Class Reference
TestRock Class Reference
Public Types
typedef RefCount< Rock::SwapDir > SwapDirPointer
Public Member Functions
TestRock ()
void setUp () override
void tearDown () override
Protected Member Functions
void commonInit ()
void storeInit ()
StoreEntry * createEntry (const int i)
StoreEntry * addEntry (const int i)
StoreEntry * getEntry (const int i)
void testRockCreate ()
void testRockSwapOut ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestRock)
CPPUNIT_TEST (testRockCreate)
CPPUNIT_TEST (testRockSwapOut)
CPPUNIT_TEST_SUITE_END ()
Private Attributes
SwapDirPointer store
Rock::SwapDirRr * rr
Detailed Description
Definition at line 43 of file testRock.cc.
Member Typedef Documentation
SwapDirPointer
typedef RefCount<Rock::SwapDir> TestRock::SwapDirPointer
Definition at line 55 of file testRock.cc.
Constructor & Destructor Documentation
TestRock()
TestRock::TestRock () inline
Definition at line 51 of file testRock.cc.
Member Function Documentation
addEntry()
StoreEntry * TestRock::addEntry (const int i) protected
Definition at line 179 of file testRock.cc.
References StoreEntry::buffer(), StoreEntry::complete(), createEntry(), StoreEntry::flush(), MemObject::freshestReply(), StoreEntry::mem(), HttpReply::packHeadersUsingSlowPacker(), StoreEntry::swapOut(), and StoreEntry::timestampsSet().
Referenced by testRockSwapOut().
commonInit()
void TestRock::commonInit () protected
CPPUNIT_TEST() [1/2]
TestRock::CPPUNIT_TEST (testRockCreate) private
CPPUNIT_TEST() [2/2]
TestRock::CPPUNIT_TEST (testRockSwapOut) private
CPPUNIT_TEST_SUITE()
TestRock::CPPUNIT_TEST_SUITE (TestRock) private
CPPUNIT_TEST_SUITE_END()
TestRock::CPPUNIT_TEST_SUITE_END () private
createEntry()
StoreEntry * TestRock::createEntry (const int i) protected
Definition at line 164 of file testRock.cc.
References MemObject::adjustableBaseReply(), RequestFlags::cachable, StoreEntry::mem(), Http::METHOD_GET, Http::scOkay, HttpReply::setHeaders(), StoreEntry::setPublicKey(), squid_curtime, storeCreateEntry(), storeId(), and SupportOrVeto::support().
Referenced by addEntry().
getEntry()
StoreEntry * TestRock::getEntry (const int i) protected
Definition at line 194 of file testRock.cc.
References Http::METHOD_GET, storeGetPublic(), and storeId().
Referenced by testRockSwapOut().
setUp()
void TestRock::setUp () override
Definition at line 81 of file testRock.cc.
References addSwapDir(), Rock::SwapDir::create(), Rock::SwapDir::parse(), rr, safe_free, ConfigParser::SetCfgLine(), store, store_maxobjsize, TESTDIR, Ipc::Mem::RegisteredRunner::useConfig(), and xstrdup.
storeInit()
void TestRock::storeInit () protected
Definition at line 133 of file testRock.cc.
References Store::Controller::init(), Store::Root(), EventLoop::run(), and Store::Controller::store_dirs_rebuilding.
Referenced by testRockSwapOut().
tearDown()
void TestRock::tearDown () override
Definition at line 113 of file testRock.cc.
References SquidConfig::cacheSwap, Config, RegisteredRunner::finishShutdown(), free_cachedir(), rr, store, and TESTDIR.
testRockCreate()
void TestRock::testRockCreate () protected
Definition at line 200 of file testRock.cc.
References TESTDIR.
testRockSwapOut()
void TestRock::testRockSwapOut () protected
Definition at line 212 of file testRock.cc.
References addEntry(), Rock::SwapDir::currentCount(), MemObject::SwapOut::decision, getEntry(), StoreEntry::mem_obj, StoreEntry::release(), EventLoop::run(), store, storeInit(), StoreEntry::swap_dirn, StoreEntry::swap_filen, StoreEntry::swap_status, MemObject::swapout, SWAPOUT_DONE, SWAPOUT_NONE, SWAPOUT_WRITING, MemObject::SwapOut::swImpossible, and StoreEntry::unlock().
Member Data Documentation
rr
Rock::SwapDirRr* TestRock::rr private
Definition at line 68 of file testRock.cc.
Referenced by setUp(), and tearDown().
store
SwapDirPointer TestRock::store private
Definition at line 67 of file testRock.cc.
Referenced by setUp(), tearDown(), and testRockSwapOut().
The documentation for this class was generated from the following file:
squid/src/tests/testRock.cc