Squid Web Cache: Http::One::ResponseParser Class Reference
Http::One::ResponseParser Class Reference
#include <ResponseParser.h>
Public Types
typedef SBuf::size_type size_type
typedef ::Parser::Tokenizer Tokenizer
Public Member Functions
ResponseParser ()=default
ResponseParser (const ResponseParser &)=default
ResponseParser & operator= (const ResponseParser &)=default
ResponseParser (ResponseParser &&)=default
ResponseParser & operator= (ResponseParser &&)=default
~ResponseParser () override
void clear () override
Http1::Parser::size_type firstLineSize () const override
size in bytes of the first line including CRLF terminator
bool parse (const SBuf &aBuf) override
Http::StatusCode messageStatus () const
SBuf reasonPhrase () const
bool needsMoreData () const
size_type headerBlockSize () const
size_type messageHeaderSize () const
SBuf mimeHeader () const
buffer containing HTTP mime headers, excluding message first-line.
const AnyP::ProtocolVersion & messageProtocol () const
the protocol label for this message
char * getHostHeaderField ()
const SBuf & remaining () const
the remaining unprocessed section of buffer
Static Public Member Functions
static void ParseResponseStatus (Tokenizer &, StatusCode &code)
static const CharacterSet & WhitespaceCharacters ()
static const CharacterSet & DelimiterCharacters ()
Public Attributes
Http::StatusCode parseStatusCode = Http::scNone
Protected Member Functions
void skipLineTerminator (Tokenizer &) const
bool grabMimeBlock (const char *which, const size_t limit)
Protected Attributes
SBuf buf_
bytes remaining to be parsed
ParseState parsingStage_ = HTTP_PARSE_NONE
what stage the parser is currently up to
AnyP::ProtocolVersion msgProtocol_
what protocol label has been found in the first line (if any)
SBuf mimeHeaderBlock_
buffer holding the mime headers (if any)
bool hackExpectsMime_ = false
Whether the invalid HTTP as HTTP/0.9 hack expects a mime header block.
Static Protected Attributes
static const SBuf Http1magic
RFC 7230 section 2.6 - 7 magic octets.
Private Member Functions
int parseResponseFirstLine ()
int parseResponseStatusAndReason (Tokenizer &)
void cleanMimePrefix ()
void unfoldMime ()
Private Attributes
bool completedStatus_ = false
Http::StatusCode statusCode_ = Http::scNone
HTTP/1 status-line status code.
SBuf reasonPhrase_
HTTP/1 status-line reason phrase.
Static Private Attributes
static const SBuf IcyMagic
magic prefix for identifying ICY response messages
Detailed Description
HTTP/1.x protocol response parser
Also capable of parsing unexpected ICY responses and upgrading HTTP/0.9 syntax responses to HTTP/1.1
Works on a raw character I/O buffer and tokenizes the content into the major CRLF delimited segments of an HTTP/1 response message:
status-line (version SP status SP reason-phrase)
mime-header (set of RFC2616 syntax header fields)
Definition at line 29 of file ResponseParser.h.
Member Typedef Documentation
size_type
typedef SBuf::size_type Http::One::Parser::size_type inherited
Definition at line 43 of file Parser.h.
Tokenizer
typedef ::Parser::Tokenizer Http::One::Parser::Tokenizer inherited
Definition at line 44 of file Parser.h.
Constructor & Destructor Documentation
ResponseParser() [1/3]
Http::One::ResponseParser::ResponseParser () default
Referenced by clear().
ResponseParser() [2/3]
Http::One::ResponseParser::ResponseParser (const ResponseParser &) default
ResponseParser() [3/3]
Http::One::ResponseParser::ResponseParser (ResponseParser &&) default
~ResponseParser()
Http::One::ResponseParser::~ResponseParser () inline override
Definition at line 37 of file ResponseParser.h.
Member Function Documentation
cleanMimePrefix()
void Http::One::Parser::cleanMimePrefix () private inherited
Remove invalid lines (if any) from the mime prefix
RFC 7230 section 3: "A recipient that receives whitespace between the start-line and the first header field MUST ... consume each whitespace-preceded line without further processing of it."
We need to always use the relaxed delimiters here to prevent line smuggling through strict parsers.
Note that 'whitespace' in RFC 7230 includes CR. So that means sequences of CRLF will be pruned, but not sequences of bare-LF.
Definition at line 97 of file Parser.cc.
References Http::One::CrLf(), CharacterSet::LF, LineCharacters(), and RelaxedDelimiterCharacters().
clear()
void Http::One::ResponseParser::clear () inline override virtual
Set this parser back to a default state. Will DROP any reference to a buffer (does not free).
Implements Http::One::Parser.
Definition at line 40 of file ResponseParser.h.
References ResponseParser().
DelimiterCharacters()
const CharacterSet & Http::One::Parser::DelimiterCharacters () static inherited
Whitespace between protocol elements in restricted contexts like request line, status line, asctime-date, and credentials Seen in RFCs as SP but may be "relaxed" by us. See also: WhitespaceCharacters(). XXX: Misnamed and overused.
Definition at line 59 of file Parser.cc.
References Config, SquidConfig::onoff, SquidConfig::relaxed_header_parser, RelaxedDelimiterCharacters(), and CharacterSet::SP.
Referenced by Http::ContentLengthInterpreter::goodSuffix(), and ParseResponseStatus().
firstLineSize()
Http1::Parser::size_type Http::One::ResponseParser::firstLineSize () const override virtual
Implements Http::One::Parser.
Definition at line 21 of file ResponseParser.cc.
References Http::One::Parser::Http1magic, IcyMagic, SBuf::length(), AnyP::ProtocolVersion::minor, Http::One::Parser::msgProtocol_, AnyP::PROTO_HTTP, AnyP::PROTO_ICY, AnyP::ProtocolVersion::protocol, and reasonPhrase_.
getHostHeaderField()
char * Http::One::Parser::getHostHeaderField () inherited
Scan the mime header block (badly) for a Host header.
BUG: omits lines when searching for headers with obs-fold or multiple entries.
BUG: limits output to just 1KB when Squid accepts up to 64KB line length.
Returns
A pointer to a field-value of the first matching field-name, or NULL.
Definition at line 213 of file Parser.cc.
References CharacterSet::ALPHA, SBuf::caseCmp(), SBuf::chop(), SBuf::consume(), Http::One::CrLf(), debugs, CharacterSet::DIGIT, SBuf::findFirstNotOf(), GET_HDR_SZ, CharacterSet::LF, LineCharacters(), LOCAL_ARRAY, SBuf::npos, SBufToCstring(), SBuf::substr(), SBuf::trim(), and CharacterSet::WSP.
grabMimeBlock()
bool Http::One::Parser::grabMimeBlock (const char * which, const size_t limit) protected inherited
Scan to find the mime headers block for current message.
Return values
true If mime block (or a blocks non-existence) has been identified accurately within limit characters. mimeHeaderBlock_ has been updated and buf_ consumed.
false An error occurred, or no mime terminator found within limit.
Definition at line 157 of file Parser.cc.
References debugs, headersEnd(), Http::One::HTTP_PARSE_DONE, AnyP::PROTO_HTTP, AnyP::PROTO_ICY, and Http::scHeaderTooLarge.
headerBlockSize()
size_type Http::One::Parser::headerBlockSize () const inline inherited
size in bytes of the message headers including CRLF terminator(s) but excluding first-line bytes
Definition at line 73 of file Parser.h.
References SBuf::length(), and Http::One::Parser::mimeHeaderBlock_.
Referenced by Http::One::Parser::messageHeaderSize(), and Http::Message::parseHeader().
messageHeaderSize()
size_type Http::One::Parser::messageHeaderSize () const inline inherited
size in bytes of HTTP message block, includes first-line and mime headers excludes any body/entity/payload bytes excludes any garbage prefix before the first-line
Definition at line 78 of file Parser.h.
References Http::One::Parser::firstLineSize(), and Http::One::Parser::headerBlockSize().
Referenced by Http::Message::parseHeader().
messageProtocol()
const AnyP::ProtocolVersion & Http::One::Parser::messageProtocol () const inline inherited
Definition at line 84 of file Parser.h.
References Http::One::Parser::msgProtocol_.
messageStatus()
Http::StatusCode Http::One::ResponseParser::messageStatus () const inline
Definition at line 45 of file ResponseParser.h.
References statusCode_.
mimeHeader()
SBuf Http::One::Parser::mimeHeader () const inline inherited
Definition at line 81 of file Parser.h.
References Http::One::Parser::mimeHeaderBlock_.
Referenced by Http::Message::parseHeader().
needsMoreData()
bool Http::One::Parser::needsMoreData () const inline inherited
Whether the parser is waiting on more data to complete parsing a message. Use to distinguish between incomplete data and error results when parse() returns false.
Definition at line 66 of file Parser.h.
References Http::One::HTTP_PARSE_DONE, and Http::One::Parser::parsingStage_.
Referenced by ConnStateData::handleChunkedRequestBody(), TestHttp1Parser::testDripFeed(), TestHttp1Parser::testParserConstruct(), and testResults().
operator=() [1/2]
ResponseParser & Http::One::ResponseParser::operator= (const ResponseParser &) default
operator=() [2/2]
ResponseParser & Http::One::ResponseParser::operator= (ResponseParser &&) default
parse()
bool Http::One::ResponseParser::parse (const SBuf & aBuf) override virtual
attempt to parse a message from the buffer
Return values
true if a full message was found and parsed
false if incomplete, invalid or no message was found
Implements Http::One::Parser.
Definition at line 198 of file ResponseParser.cc.
References Config, DBG_DATA, debugs, Http::One::HTTP_PARSE_DONE, Http::One::HTTP_PARSE_FIRST, Http::One::HTTP_PARSE_MIME, Http::One::HTTP_PARSE_NONE, SBuf::length(), SquidConfig::maxReplyHeaderSize, and Http::scInvalidHeader.
Referenced by Http::Tunneler::handleResponse().
parseResponseFirstLine()
int Http::One::ResponseParser::parseResponseFirstLine () private
Attempt to parse the method field out of an HTTP message status-line.
Governed by: RFC 1945 section 6.1 RFC 7230 section 2.6, 3.1 and 3.5
Parsing state is stored between calls. The current implementation uses checkpoints after each successful status-line field. The return value tells you whether the parsing is completed or not.
Return values
-1 an error occurred.
1 successful parse. statusCode_ and maybe reasonPhrase_ are filled and buffer consumed including first delimiter.
0 more data is needed to complete the parse
Definition at line 125 of file ResponseParser.cc.
References assert, DBG_DATA, debugs, Http::One::HTTP_PARSE_DONE, AnyP::PROTO_HTTP, AnyP::PROTO_ICY, AnyP::PROTO_NONE, Http::ProtocolVersion(), and Http::scOkay.
ParseResponseStatus()
void Http::One::ResponseParser::ParseResponseStatus (Tokenizer & tok, StatusCode & code) static
extracts response status-code and the following delimiter; validates status-code
Parameters
[out] code syntactically valid status-code (unchanged on syntax errors)
Exceptions
InsuffientInput and other exceptions on syntax and validation errors
Definition at line 86 of file ResponseParser.cc.
References debugs, Http::One::Parser::DelimiterCharacters(), Here, and ToSBuf().
Referenced by Http::StatusLine::parse().
parseResponseStatusAndReason()
int Http::One::ResponseParser::parseResponseStatusAndReason (Tokenizer & tok) private
Definition at line 51 of file ResponseParser.cc.
References DBG_DATA, debugs, CharacterSet::OBSTEXT, CharacterSet::VCHAR, and CharacterSet::WSP.
reasonPhrase()
SBuf Http::One::ResponseParser::reasonPhrase () const inline
Definition at line 46 of file ResponseParser.h.
References reasonPhrase_.
remaining()
const SBuf & Http::One::Parser::remaining () const inline inherited
Definition at line 98 of file Parser.h.
References Http::One::Parser::buf_.
Referenced by HttpStateData::decodeAndWriteReplyBody(), ConnStateData::handleChunkedRequestBody(), and TestHttp1Parser::testDripFeed().
skipLineTerminator()
void Http::One::Parser::skipLineTerminator (Tokenizer & tok) const protected inherited
detect and skip the CRLF or (if tolerant) LF line terminator consume from the tokenizer.
Exceptions
exception on bad or InsufficientInput
Definition at line 66 of file Parser.cc.
References Config, Http::One::CrLf(), CharacterSet::LF, SquidConfig::onoff, and SquidConfig::relaxed_header_parser.
unfoldMime()
void Http::One::Parser::unfoldMime () private inherited
Replace obs-fold with a single SP,
RFC 7230 section 3.2.4 "A server that receives an obs-fold in a request message that is not within a message/http container MUST ... replace each received obs-fold with one or more SP octets prior to interpreting the field value or forwarding the message downstream."
"A proxy or gateway that receives an obs-fold in a response message that is not within a message/http container MUST ... replace each received obs-fold with one or more SP octets prior to interpreting the field value or forwarding the message downstream."
Definition at line 132 of file Parser.cc.
References CharacterSet::CR, CharacterSet::LF, CharacterSet::rename(), SBuf::substr(), and CharacterSet::WSP.
WhitespaceCharacters()
const CharacterSet & Http::One::Parser::WhitespaceCharacters () static inherited
Whitespace between regular protocol elements. Seen in RFCs as OWS, RWS, BWS, SP/HTAB but may be "relaxed" by us. See also: DelimiterCharacters().
Definition at line 52 of file Parser.cc.
References Config, SquidConfig::onoff, SquidConfig::relaxed_header_parser, RelaxedDelimiterCharacters(), and CharacterSet::WSP.
Referenced by Http::ContentLengthInterpreter::findDigits(), and Http::One::ParseBws().
Member Data Documentation
buf_
SBuf Http::One::Parser::buf_ protected inherited
Definition at line 146 of file Parser.h.
Referenced by Http::One::Parser::clear(), Http::One::Parser::remaining(), TestHttp1Parser::testParserConstruct(), and testResults().
completedStatus_
bool Http::One::ResponseParser::completedStatus_ = false private
Whether we found the status code yet. We cannot rely on status value because server may send "000".
Definition at line 62 of file ResponseParser.h.
hackExpectsMime_
bool Http::One::Parser::hackExpectsMime_ = false protected inherited
Definition at line 158 of file Parser.h.
Http1magic
const SBuf Http::One::Parser::Http1magic static protected inherited
Definition at line 143 of file Parser.h.
Referenced by firstLineSize().
IcyMagic
const SBuf Http::One::ResponseParser::IcyMagic static private
Definition at line 58 of file ResponseParser.h.
Referenced by firstLineSize().
mimeHeaderBlock_
SBuf Http::One::Parser::mimeHeaderBlock_ protected inherited
Definition at line 155 of file Parser.h.
Referenced by Http::One::Parser::clear(), Http::One::Parser::headerBlockSize(), and Http::One::Parser::mimeHeader().
msgProtocol_
AnyP::ProtocolVersion Http::One::Parser::msgProtocol_ protected inherited
Definition at line 152 of file Parser.h.
Referenced by Http::One::Parser::clear(), firstLineSize(), Http::One::RequestParser::http0(), Http::One::Parser::messageProtocol(), TestHttp1Parser::testParserConstruct(), and testResults().
parseStatusCode
Http::StatusCode Http::One::Parser::parseStatusCode = Http::scNone inherited
HTTP status code resulting from the parse process. to be used on the invalid message handling.
Http::scNone indicates incomplete parse, Http::scOkay indicates no error, other codes represent a parse error.
Definition at line 108 of file Parser.h.
Referenced by TestHttp1Parser::testParserConstruct(), and testResults().
parsingStage_
ParseState Http::One::Parser::parsingStage_ = HTTP_PARSE_NONE protected inherited
Definition at line 149 of file Parser.h.
Referenced by Http::One::Parser::clear(), Http::One::Parser::needsMoreData(), TestHttp1Parser::testParserConstruct(), and testResults().
reasonPhrase_
SBuf Http::One::ResponseParser::reasonPhrase_ private
Definition at line 68 of file ResponseParser.h.
Referenced by firstLineSize(), and reasonPhrase().
statusCode_
Http::StatusCode Http::One::ResponseParser::statusCode_ = Http::scNone private
Definition at line 65 of file ResponseParser.h.
Referenced by messageStatus().
The documentation for this class was generated from the following files:
squid/src/http/one/ResponseParser.h
squid/src/http/one/ResponseParser.cc