Squid Web Cache: Acl::ServerNameMatcher Class Reference
Acl::ServerNameMatcher Class Reference
GeneralNameMatcher for matching configured ACL parameters.
Public Member Functions
ServerNameMatcher (ServerNameCheck::Parameters &p)
bool match (const Ssl::GeneralName &) const
whether the given name satisfies algorithm conditions
Protected Member Functions
bool matchDomainName (const Dns::DomainName &) const override
bool matchIp (const Ip::Address &) const override
Private Attributes
ServerNameCheck::Parameters & parameters
configured ACL parameters
Detailed Description
Definition at line 53 of file ServerName.cc.
Constructor & Destructor Documentation
ServerNameMatcher()
Acl::ServerNameMatcher::ServerNameMatcher (ServerNameCheck::Parameters & p) inline explicit
Definition at line 56 of file ServerName.cc.
Member Function Documentation
match()
bool Ssl::GeneralNameMatcher::match (const Ssl::GeneralName & name) const inherited
Definition at line 84 of file support.cc.
References Assure, AnyP::Host::domainName(), AnyP::Host::ip(), Ssl::GeneralNameMatcher::matchDomainName(), and Ssl::GeneralNameMatcher::matchIp().
Referenced by Ssl::HasMatchingSubjectName().
matchDomainName()
bool Acl::ServerNameMatcher::matchDomainName (const Dns::DomainName & domain) const override protected virtual
Implements Ssl::GeneralNameMatcher.
Definition at line 71 of file ServerName.cc.
References ACLData< M >::match(), and parameters.
matchIp()
bool Acl::ServerNameMatcher::matchIp (const Ip::Address & ip) const override protected virtual
Implements Ssl::GeneralNameMatcher.
Definition at line 77 of file ServerName.cc.
References MAX_IPSTRLEN, and Ip::Address::toStr().
Member Data Documentation
parameters
ServerNameCheck::Parameters& Acl::ServerNameMatcher::parameters private
Definition at line 65 of file ServerName.cc.
Referenced by matchDomainName().
The documentation for this class was generated from the following file:
squid/src/acl/ServerName.cc