Squid Web Cache: TestRefCount Class Reference
TestRefCount Class Reference
Protected Member Functions
void testCountability ()
void testObjectToRefCounted ()
void testStandalonePointer ()
void testCheckPointers ()
void testPointerConst ()
void testRefCountFromConst ()
void testPointerFromRefCounter ()
void testDoubleInheritToSingleInherit ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestRefCount)
CPPUNIT_TEST (testCountability)
CPPUNIT_TEST (testObjectToRefCounted)
CPPUNIT_TEST (testStandalonePointer)
CPPUNIT_TEST (testCheckPointers)
CPPUNIT_TEST (testPointerConst)
CPPUNIT_TEST (testRefCountFromConst)
CPPUNIT_TEST (testPointerFromRefCounter)
CPPUNIT_TEST (testDoubleInheritToSingleInherit)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 16 of file testRefCount.cc.
Member Function Documentation
CPPUNIT_TEST() [1/8]
TestRefCount::CPPUNIT_TEST (testCheckPointers) private
CPPUNIT_TEST() [2/8]
TestRefCount::CPPUNIT_TEST (testCountability) private
CPPUNIT_TEST() [3/8]
TestRefCount::CPPUNIT_TEST (testDoubleInheritToSingleInherit) private
CPPUNIT_TEST() [4/8]
TestRefCount::CPPUNIT_TEST (testObjectToRefCounted) private
CPPUNIT_TEST() [5/8]
TestRefCount::CPPUNIT_TEST (testPointerConst) private
CPPUNIT_TEST() [6/8]
TestRefCount::CPPUNIT_TEST (testPointerFromRefCounter) private
CPPUNIT_TEST() [7/8]
TestRefCount::CPPUNIT_TEST (testRefCountFromConst) private
CPPUNIT_TEST() [8/8]
TestRefCount::CPPUNIT_TEST (testStandalonePointer) private
CPPUNIT_TEST_SUITE()
TestRefCount::CPPUNIT_TEST_SUITE (TestRefCount) private
CPPUNIT_TEST_SUITE_END()
TestRefCount::CPPUNIT_TEST_SUITE_END () private
testCheckPointers()
void TestRefCount::testCheckPointers () protected
Definition at line 128 of file testRefCount.cc.
References _ToRefCount::Instances.
testCountability()
void TestRefCount::testCountability () protected
Definition at line 75 of file testRefCount.cc.
References _ToRefCount::Instances.
testDoubleInheritToSingleInherit()
void TestRefCount::testDoubleInheritToSingleInherit () protected
Definition at line 181 of file testRefCount.cc.
References RefCount< C >::getRaw(), and _ToRefCount::Instances.
testObjectToRefCounted()
void TestRefCount::testObjectToRefCounted () protected
Definition at line 107 of file testRefCount.cc.
References _ToRefCount::Instances, and _ToRefCount::someMethod().
testPointerConst()
void TestRefCount::testPointerConst () protected
Definition at line 145 of file testRefCount.cc.
References RefCount< C >::getRaw(), and _ToRefCount::Instances.
testPointerFromRefCounter()
void TestRefCount::testPointerFromRefCounter () protected
Definition at line 169 of file testRefCount.cc.
References RefCount< C >::getRaw(), and _ToRefCount::Instances.
testRefCountFromConst()
void TestRefCount::testRefCountFromConst () protected
Definition at line 157 of file testRefCount.cc.
References RefCount< C >::getRaw(), and _ToRefCount::Instances.
testStandalonePointer()
void TestRefCount::testStandalonePointer () protected
Definition at line 120 of file testRefCount.cc.
References _ToRefCount::Instances.
The documentation for this class was generated from the following file:
squid/src/tests/testRefCount.cc