Squid Web Cache: TestTokenizer Class Reference
TestTokenizer Class Reference
Protected Member Functions
void testTokenizerPrefix ()
void testTokenizerSuffix ()
void testTokenizerSkip ()
void testTokenizerToken ()
void testTokenizerInt64 ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestTokenizer)
CPPUNIT_TEST (testTokenizerPrefix)
CPPUNIT_TEST (testTokenizerSuffix)
CPPUNIT_TEST (testTokenizerSkip)
CPPUNIT_TEST (testTokenizerToken)
CPPUNIT_TEST (testTokenizerInt64)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 15 of file testTokenizer.cc.
Member Function Documentation
CPPUNIT_TEST() [1/5]
TestTokenizer::CPPUNIT_TEST (testTokenizerInt64) private
CPPUNIT_TEST() [2/5]
TestTokenizer::CPPUNIT_TEST (testTokenizerPrefix) private
CPPUNIT_TEST() [3/5]
TestTokenizer::CPPUNIT_TEST (testTokenizerSkip) private
CPPUNIT_TEST() [4/5]
TestTokenizer::CPPUNIT_TEST (testTokenizerSuffix) private
CPPUNIT_TEST() [5/5]
TestTokenizer::CPPUNIT_TEST (testTokenizerToken) private
CPPUNIT_TEST_SUITE()
TestTokenizer::CPPUNIT_TEST_SUITE (TestTokenizer) private
CPPUNIT_TEST_SUITE_END()
TestTokenizer::CPPUNIT_TEST_SUITE_END () private
testTokenizerInt64()
void TestTokenizer::testTokenizerInt64 () protected
Definition at line 209 of file testTokenizer.cc.
References Parser::Tokenizer::buf(), Parser::Tokenizer::int64(), SBuf::isEmpty(), SBuf::length(), and SBuf::substr().
testTokenizerPrefix()
void TestTokenizer::testTokenizerPrefix () protected
Definition at line 45 of file testTokenizer.cc.
References CharacterSet::add(), alpha, crlf, numbers, Parser::Tokenizer::prefix(), Parser::Tokenizer::remaining(), tab, text, and whitespace.
testTokenizerSkip()
void TestTokenizer::testTokenizerSkip () protected
Definition at line 97 of file testTokenizer.cc.
References alpha, Parser::Tokenizer::prefix(), Parser::Tokenizer::remaining(), Parser::Tokenizer::skip(), Parser::Tokenizer::skipAll(), Parser::Tokenizer::skipOne(), SBuf::startsWith(), text, and whitespace.
testTokenizerSuffix()
void TestTokenizer::testTokenizerSuffix () protected
Definition at line 149 of file testTokenizer.cc.
References CharacterSet::add(), alpha, crlf, SBuf::findLastOf(), SBuf::length(), SBuf::npos, numbers, Parser::Tokenizer::remaining(), Parser::Tokenizer::skipOneTrailing(), Parser::Tokenizer::skipSuffix(), Parser::Tokenizer::suffix(), text, and whitespace.
testTokenizerToken()
void TestTokenizer::testTokenizerToken () protected
Definition at line 131 of file testTokenizer.cc.
References text, Parser::Tokenizer::token(), and whitespace.
The documentation for this class was generated from the following file:
squid/src/tests/testTokenizer.cc