Squid Web Cache: Adaptation::Service Class Reference
Adaptation::Service Class Reference abstract
#include <Service.h>
Public Types
typedef RefCount< Service > Pointer
typedef String Id
Public Member Functions
Service (const ServiceConfigPointer &aConfig)
~Service () override
virtual bool probed () const =0
virtual bool broken () const
virtual bool up () const =0
virtual Initiate * makeXactLauncher (Http::Message *virginHeader, HttpRequest *virginCause, AccessLogEntry::Pointer &alp)=0
bool wants (const ServiceFilter &filter) const
virtual bool wantsUrl (const SBuf &urlPath) const =0
virtual void noteFailure ()=0
const ServiceConfig & cfg () const
virtual void finalize ()
virtual void detach ()=0
virtual bool detached () const =0
whether detached() was called
Protected Member Functions
ServiceConfig & writeableCfg ()
Private Attributes
ServiceConfigPointer theConfig
Detailed Description
Definition at line 27 of file Service.h.
Member Typedef Documentation
Id
typedef String Adaptation::Service::Id
Definition at line 31 of file Service.h.
Pointer
typedef RefCount<Service> Adaptation::Service::Pointer
Definition at line 30 of file Service.h.
Constructor & Destructor Documentation
Service()
Adaptation::Service::Service (const ServiceConfigPointer & aConfig) explicit
Definition at line 16 of file Service.cc.
References cfg(), debugs, Must, and theConfig.
~Service()
Adaptation::Service::~Service () override
Definition at line 22 of file Service.cc.
Member Function Documentation
broken()
bool Adaptation::Service::broken () const virtual
Definition at line 30 of file Service.cc.
cfg()
const ServiceConfig & Adaptation::Service::cfg () const inline
Definition at line 51 of file Service.h.
References theConfig.
Referenced by Service(), Adaptation::ServiceGroup::checkUniqueness(), Adaptation::Icap::Xaction::dnsLookupDone(), Adaptation::ServiceGroup::finalize(), Adaptation::Icap::Xaction::finalizeLogInfo(), Adaptation::Icap::ModXact::finalizeLogInfo(), Adaptation::ServiceGroup::findService(), Adaptation::Icap::OptXact::makeRequest(), Adaptation::Icap::Xaction::openConnection(), Adaptation::DynamicServiceChain::Split(), and Adaptation::Iterator::step().
detach()
virtual void Adaptation::Service::detach () pure virtual
called when removed from the config; the service will be auto-destroyed when the last refcounting user leaves
Implemented in Adaptation::Ecap::ServiceRep, and Adaptation::Icap::ServiceRep.
Referenced by Adaptation::DetachServices().
detached()
virtual bool Adaptation::Service::detached () const pure virtual
Implemented in Adaptation::Ecap::ServiceRep, and Adaptation::Icap::ServiceRep.
finalize()
void Adaptation::Service::finalize () virtual
Reimplemented in Adaptation::Ecap::ServiceRep, and Adaptation::Icap::ServiceRep.
Definition at line 26 of file Service.cc.
Referenced by Adaptation::Ecap::ServiceRep::finalize(), and Adaptation::Icap::ServiceRep::finalize().
makeXactLauncher()
virtual Initiate * Adaptation::Service::makeXactLauncher (Http::Message * virginHeader, HttpRequest * virginCause, AccessLogEntry::Pointer & alp) pure virtual
Implemented in Adaptation::Ecap::ServiceRep, and Adaptation::Icap::ServiceRep.
Referenced by Adaptation::Iterator::step().
noteFailure()
virtual void Adaptation::Service::noteFailure () pure virtual
Implemented in Adaptation::Ecap::ServiceRep, and Adaptation::Icap::ServiceRep.
probed()
virtual bool Adaptation::Service::probed () const pure virtual
Implemented in Adaptation::Ecap::ServiceRep, and Adaptation::Icap::ServiceRep.
Referenced by Adaptation::ServiceGroup::findService().
up()
virtual bool Adaptation::Service::up () const pure virtual
Implemented in Adaptation::Ecap::ServiceRep, and Adaptation::Icap::ServiceRep.
Referenced by Adaptation::ServiceGroup::findService().
wants()
bool Adaptation::Service::wants (const ServiceFilter & filter) const
Definition at line 36 of file Service.cc.
References AnyP::Uri::absolutePath(), Adaptation::ServiceFilter::method, Adaptation::ServiceFilter::point, Adaptation::ServiceFilter::request, and HttpRequest::url.
Referenced by Adaptation::ServiceGroup::findService().
wantsUrl()
virtual bool Adaptation::Service::wantsUrl (const SBuf & urlPath) const pure virtual
Implemented in Adaptation::Ecap::ServiceRep, and Adaptation::Icap::ServiceRep.
writeableCfg()
ServiceConfig & Adaptation::Service::writeableCfg () inline protected
Definition at line 62 of file Service.h.
References theConfig.
Member Data Documentation
theConfig
ServiceConfigPointer Adaptation::Service::theConfig private
Definition at line 65 of file Service.h.
Referenced by Service(), cfg(), and writeableCfg().
The documentation for this class was generated from the following files:
squid/src/adaptation/Service.h
squid/src/adaptation/Service.cc