Squid Web Cache: Debug Class Reference
Debug Class Reference
#include <Stream.h>
Classes
class Context
meta-information for debugs() or a similar debugging call
Static Public Member Functions
static bool Enabled (const int section, const int level)
whether debugging the given section and the given level produces output
static void NameThisHelper (const char *name)
static void NameThisKid (int kidIdentifier)
static void parseOptions (char const *)
static int Level ()
minimum level required by the current debugs() call
static int SectionLevel ()
maximum level currently allowed
static std::ostringstream & Start (const int section, const int level)
opens debugging context and returns output buffer
static void Finish ()
logs output buffer created in Start() and closes debugging context
static void ForceAlert ()
configures the active debugging context to write syslog ALERT
static std::ostream & Extra (std::ostream &)
static void ForgetSaved ()
silently erases saved early debugs() messages (if any)
static void PrepareToDie ()
static void LogWaitingForIdle ()
Logs messages of Finish()ed debugs() calls that were queued earlier.
static void BanCacheLogUse ()
static void UseCacheLog ()
static void StopCacheLogUse ()
static void EnsureDefaultStderrLevel (int maxDefault)
static void ResetStderrLevel (int maxLevel)
static void SettleStderr ()
static bool StderrEnabled ()
static void ConfigureSyslog (const char *facility)
enables logging to syslog (using the specified facility, when not nil)
static void SettleSyslog ()
Static Public Attributes
static char * debugOptions = nullptr
static char * cache_log = nullptr
static int rotateNumber = -1
static int Levels [MAX_DEBUG_SECTIONS]
static int override_X = 0
static bool log_syslog = false
Static Private Member Functions
static void FormatStream (std::ostream &)
configures default formatting for the debugging stream
static void LogMessage (const Context &)
broadcasts debugs() message to the logging channels
Static Private Attributes
static Context * Current = nullptr
deepest active context; nil outside debugs()
Detailed Description
Definition at line 46 of file Stream.h.
Member Function Documentation
BanCacheLogUse()
void Debug::BanCacheLogUse () static
Starts using stderr as a cache_log file replacement. Also applies configured debug_options (if any). Call this or UseCacheLog() to stop early message accumulation.
Definition at line 1118 of file debug.cc.
References DebugModule::banCacheLogUse(), debugOptions, Module(), and parseOptions().
Referenced by ConfigureDebugging(), mainHandleCommandLineOption(), NameThisHelper(), and IcmpPinger::Open().
ConfigureSyslog()
void Debug::ConfigureSyslog (const char * facility) static
Definition at line 1083 of file debug.cc.
References fatalf().
Referenced by mainHandleCommandLineOption().
Enabled()
static bool Debug::Enabled (const int section, const int level) inline static
Definition at line 75 of file Stream.h.
References Levels.
Referenced by clientNegotiateSSL(), Ftp::Server::handleRequest(), Adaptation::Ecap::Host::openDebug(), DebugChannel::Logger::operator=(), Security::NegotiationHistory::retrieveNegotiatedInfo(), and Security::PeerConnector::sslCrtvdHandleReply().
EnsureDefaultStderrLevel()
void Debug::EnsureDefaultStderrLevel (int maxDefault) static
In the absence of ResetStderrLevel() calls, future debugs() with the given (or lower) level will be written to stderr (at least). If called many times, the highest parameter wins. ResetStderrLevel() overwrites this default-setting method, regardless of the calls order.
Definition at line 693 of file debug.cc.
References DefaultStderrLevel.
Referenced by mainHandleCommandLineOption(), and NameThisHelper().
Extra()
std::ostream & Debug::Extra (std::ostream & os) static
Prefixes each grouped debugs() line after the first one in the group. Resets debugging stream format to the initial/default one.
Definition at line 1316 of file debug.cc.
References FormatStream().
Referenced by PeerPoolMgr::PeerPoolMgr(), RegexPattern::RegexPattern(), Store::SwapMetaUnpacker::SwapMetaUnpacker(), Comm::TcpAcceptor::acceptInto(), Comm::TcpAcceptor::acceptOne(), Helper::Reply::CheckReceivedKey(), Store::CheckSwapMetaUrl(), clientFollowXForwardedForCheck(), clientHttpConnectionsOpen(), clientListenerConnectionOpened(), clientNegotiateSSL(), ConfigurationFailureMessage(), CurrentExceptionExtra(), debugOpenLog(), AccessLogEntry::detailCodeContext(), Acl::ParsingContext::detailCodeContext(), AnyP::PortCfg::detailCodeContext(), PrecomputedCodeContext::detailCodeContext(), Comm::Connection::detailCodeContext(), htcpSpecifier::detailCodeContext(), Rock::Rebuild::failure(), MemStore::get(), Helper::Client::handleFewerServers(), Security::PeerConnector::handleNegotiationResult(), ConnStateData::handleSslBumpHandshakeError(), idnsSendQueryVC(), Ssl::CertValidationHelper::Init(), ipcCreate(), Security::IssuedBy(), ConnStateData::lifetimeTimeout(), Security::KeyData::loadCertificates(), Acl::SplayInserter< DataValue >::Merge(), neighborIgnoreNonPeer(), neighbors_init(), operator<<(), operator<<(), ACLRegexData::parse(), store_client::parseHttpHeadersFromDisk(), parseOneConfigFile(), FormattedLog::parseOptions(), Ssl::CertValidationMsg::parseResponse(), HttpReply::parseTerminatedPrefix(), TextException::print(), Security::IoResult::printWithExtras(), processNewRequest(), Rock::Rebuild::progressDescription(), Ssl::readCertAndPrivateKeyFromMemory(), Ipc::Port::receiveOrIgnore(), Ipc::QuestionerId::rejectAnswerIfStale(), Ssl::ReportAndForgetErrors(), Acl::SetKey(), setTraceability(), storeCleanup(), and storeRebuildComplete().
Finish()
void Debug::Finish () static
Definition at line 1366 of file debug.cc.
References Debug::Context::buf, Current, CurrentCodeContextDetail(), DBG_IMPORTANT, Debug::Context::forceAlert, last, Debug::Context::level, LogMessage(), Debug::Context::upper, WaitingForIdle, and Debug::Context::waitingForIdle.
Referenced by Adaptation::Ecap::Host::closeDebug().
ForceAlert()
void Debug::ForceAlert () static
Definition at line 1403 of file debug.cc.
References Current, and Debug::Context::forceAlert.
Referenced by ForceAlert().
ForgetSaved()
void Debug::ForgetSaved () static
Definition at line 554 of file debug.cc.
Referenced by GoIntoBackground().
FormatStream()
void Debug::FormatStream (std::ostream & buf) static private
Definition at line 1305 of file debug.cc.
Referenced by Debug::Context::Context(), Extra(), and Debug::Context::rewind().
Level()
static int Debug::Level () inline static
Definition at line 100 of file Stream.h.
References Current, and Debug::Context::level.
Referenced by debugLogTime().
LogMessage()
void Debug::LogMessage (const Context & context) static private
Definition at line 781 of file debug.cc.
References Debug::Context::buf, dbg_mutex, DebugFile::file(), DebugModule::log(), Module(), TheLog, and xcalloc().
Referenced by Finish(), and LogWaitingForIdle().
LogWaitingForIdle()
void Debug::LogWaitingForIdle () static
Definition at line 1327 of file debug.cc.
References assert, LogMessage(), Debug::Context::upper, and WaitingForIdle.
Referenced by LoggingSectionGuard::~LoggingSectionGuard(), and DebugModule::prepareToDie().
NameThisHelper()
void Debug::NameThisHelper (const char * name) static
Use the given name for debugs() messages from this helper process. Side effect: Commits to using helper-appropriate debug levels/channels.
See also
NameThisKid()
Definition at line 384 of file debug.cc.
References assert, BanCacheLogUse(), DBG_DATA, debugOptions, debugs, EnsureDefaultStderrLevel(), LabelThisProcess(), SettleStderr(), SettleSyslog(), and xstrdup.
Referenced by main(), main(), and main().
NameThisKid()
void Debug::NameThisKid (int kidIdentifier) static
Use the given ID for debugs() messages from this SMP kid process.
See also
NameThisHelper()
Definition at line 407 of file debug.cc.
References LabelThisProcess(), and ProcessLabel.
Referenced by ConfigureCurrentKid().
parseOptions()
void Debug::parseOptions (char const * options) static
Definition at line 1095 of file debug.cc.
References debugArg(), debugs, override_X, ResetSections(), w_space, xfree, and xstrdup.
Referenced by BanCacheLogUse(), main(), mainHandleCommandLineOption(), sigusr2_handle(), and UseCacheLog().
PrepareToDie()
void Debug::PrepareToDie () static
Reacts to ongoing program termination (e.g., flushes buffered messages). Call this before logging the termination reason to maximize the chances of that valuable debugs() getting through to the admin.
Definition at line 563 of file debug.cc.
References Module(), and DebugModule::prepareToDie().
Referenced by DebugModule::DebugModule(), death(), fatal_dump(), OnTerminate(), OnTerminate(), and xassert().
ResetStderrLevel()
void Debug::ResetStderrLevel (int maxLevel) static
Future debugs() messages with the given (or lower) level will be written to stderr (at least). If called many times, the last call wins.
Definition at line 701 of file debug.cc.
References ExplicitStderrLevel.
Referenced by mainHandleCommandLineOption().
SectionLevel()
static int Debug::SectionLevel () inline static
Definition at line 102 of file Stream.h.
References Current, and Debug::Context::sectionLevel.
Referenced by Raw::print().
SettleStderr()
void Debug::SettleStderr () static
Finalizes stderr configuration when no (more) ResetStderrLevel() and EnsureDefaultStderrLevel() calls are expected.
Definition at line 707 of file debug.cc.
References DBG_CRITICAL, DBG_DATA, debugs, ExplicitStderrLevel, Module(), override_X, DebugModule::stderrChannel, and DebugChannel::stopEarlyMessageCollection().
Referenced by NameThisHelper(), and SquidMain().
SettleSyslog()
void Debug::SettleSyslog () static
Finalizes syslog configuration when no (more) ConfigureSyslog() calls are expected.
Definition at line 1145 of file debug.cc.
References APP_SHORTNAME, log_syslog, SyslogChannel::markOpened(), Module(), DebugChannel::stopEarlyMessageCollection(), and DebugModule::syslogChannel.
Referenced by Module(), NameThisHelper(), and SquidMain().
Start()
std::ostringstream & Debug::Start (const int section, const int level) static
Definition at line 1342 of file debug.cc.
References Debug::Context::buf, LoggingSectionGuard::Busy(), Current, Debug::Context::rewind(), and Debug::Context::waitingForIdle.
Referenced by Adaptation::Ecap::Host::openDebug().
StderrEnabled()
bool Debug::StderrEnabled () static
Whether at least some debugs() messages may be written to stderr. The answer may be affected by BanCacheLogUse() and SettleStderr().
Definition at line 727 of file debug.cc.
References DBG_CRITICAL, StderrChannel::enabled(), Module(), and DebugModule::stderrChannel.
Referenced by watch_child().
StopCacheLogUse()
void Debug::StopCacheLogUse () static
Closes and stops using cache_log (if it was open). Starts using stderr as a cache_log file replacement.
Definition at line 1132 of file debug.cc.
References DebugModule::banCacheLogUse(), DebugModule::cacheLogChannel, DebugFile::clear(), DebugFile::file(), Module(), DebugChannel::stopEarlyMessageCollection(), and TheLog.
Referenced by RemoveInstance().
UseCacheLog()
void Debug::UseCacheLog () static
Opens and starts using the configured cache_log file. Also applies configured debug_options (if any). Call this or BanCacheLogUse() to stop early message accumulation.
Definition at line 1125 of file debug.cc.
References cache_log, debugOpenLog(), debugOptions, and parseOptions().
Referenced by ConfigureDebugging(), and mainReconfigureFinish().
Member Data Documentation
cache_log
char * Debug::cache_log = nullptr static
Definition at line 81 of file Stream.h.
Referenced by _db_rotate_log(), DebugFile::reset(), and UseCacheLog().
Current
Debug::Context * Debug::Current = nullptr static private
Definition at line 176 of file Stream.h.
Referenced by Finish(), ForceAlert(), Level(), Debug::Context::rewind(), SectionLevel(), and Start().
debugOptions
char * Debug::debugOptions = nullptr static
Definition at line 80 of file Stream.h.
Referenced by BanCacheLogUse(), NameThisHelper(), IcmpPinger::Open(), PutEnvironment(), PutEnvironment(), sigusr2_handle(), snmp_confFn(), and UseCacheLog().
Levels
int Debug::Levels static
Definition at line 83 of file Stream.h.
Referenced by TestAuthConfig::create(), debugArg(), Enabled(), ResetSections(), Debug::Context::rewind(), TestProgram::run(), and TestAuthUserRequest::scheme().
log_syslog
bool Debug::log_syslog = false static
Definition at line 85 of file Stream.h.
Referenced by SettleSyslog(), and SyslogChannel::shouldWrite().
override_X
int Debug::override_X = 0 static
Definition at line 84 of file Stream.h.
Referenced by mainHandleCommandLineOption(), parseOptions(), and SettleStderr().
rotateNumber
int Debug::rotateNumber = -1 static
Definition at line 82 of file Stream.h.
Referenced by _db_rotate_log(), configDoConfigure(), and debugArg().
The documentation for this class was generated from the following files:
squid/src/debug/Stream.h
squid/src/debug/debug.cc
squid/src/tests/stub_debug.cc