Squid Web Cache: DelayVector Class Reference
DelayVector Class Reference
Squid Components » Delay Pools API
#include <DelayVector.h>
Classes
class Id
Public Types
typedef RefCount< DelayVector > Pointer
Public Member Functions
DelayVector ()
~DelayVector () override
void stats (StoreEntry *sentry) override
void dump (StoreEntry *entry) const override
void update (int incr) override
void parse () override
DelayIdComposite::Pointer id (CompositeSelectionDetails &) override
void push_back (CompositePoolNode::Pointer)
void delayRead (const AsyncCallPointer &)
Protected Member Functions
void kickReads ()
Protected Attributes
DelayedAsyncCalls deferredReads
Private Types
typedef std::vector< CompositePoolNode::Pointer >::iterator iterator
typedef std::vector< CompositePoolNode::Pointer >::const_iterator const_iterator
Private Member Functions
MEMPROXY_CLASS (DelayVector)
Private Attributes
std::vector< CompositePoolNode::Pointer > pools
Friends
class Id
Detailed Description
Definition at line 18 of file DelayVector.h.
Member Typedef Documentation
const_iterator
typedef std::vector<CompositePoolNode::Pointer>::const_iterator DelayVector::const_iterator private
Definition at line 59 of file DelayVector.h.
iterator
typedef std::vector<CompositePoolNode::Pointer>::iterator DelayVector::iterator private
Definition at line 58 of file DelayVector.h.
Pointer
typedef RefCount<DelayVector> DelayVector::Pointer
Definition at line 23 of file DelayVector.h.
Constructor & Destructor Documentation
DelayVector()
DelayVector::DelayVector ()
Definition at line 19 of file DelayVector.cc.
References DelayPools::registerForUpdates().
~DelayVector()
DelayVector::~DelayVector () override
Definition at line 24 of file DelayVector.cc.
References DelayPools::deregisterForUpdates().
Member Function Documentation
delayRead()
void CompositePoolNode::delayRead (const AsyncCallPointer & aRead) inherited
Definition at line 80 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::delay().
Referenced by Aggregate::AggregateId::delayRead().
dump()
void DelayVector::dump (StoreEntry * entry) const override virtual
Implements CompositePoolNode.
Definition at line 41 of file DelayVector.cc.
References pools.
id()
DelayIdComposite::Pointer DelayVector::id (CompositeSelectionDetails & details) override virtual
Implements CompositePoolNode.
Definition at line 74 of file DelayVector.cc.
kickReads()
void CompositePoolNode::kickReads () protected inherited
Definition at line 88 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::schedule().
Referenced by Aggregate::update(), DelayTagged::update(), and update().
MEMPROXY_CLASS()
DelayVector::MEMPROXY_CLASS (DelayVector) private
parse()
void DelayVector::parse () override virtual
Implements CompositePoolNode.
Definition at line 63 of file DelayVector.cc.
References pools.
push_back()
void DelayVector::push_back (CompositePoolNode::Pointer aNode)
Definition at line 80 of file DelayVector.cc.
References pools.
Referenced by CommonPool::Factory().
stats()
void DelayVector::stats (StoreEntry * sentry) override virtual
Implements CompositePoolNode.
Definition at line 30 of file DelayVector.cc.
References pools.
update()
void DelayVector::update (int incr) override virtual
Implements CompositePoolNode.
Definition at line 52 of file DelayVector.cc.
References CompositePoolNode::kickReads().
Friends And Related Symbol Documentation
Id
friend class Id friend
Definition at line 55 of file DelayVector.h.
Member Data Documentation
deferredReads
DelayedAsyncCalls CompositePoolNode::deferredReads protected inherited
Definition at line 60 of file CompositePoolNode.h.
Referenced by CompositePoolNode::delayRead(), and CompositePoolNode::kickReads().
pools
std::vector<CompositePoolNode::Pointer> DelayVector::pools private
Definition at line 57 of file DelayVector.h.
Referenced by DelayVector::Id::Id(), dump(), parse(), push_back(), and stats().
The documentation for this class was generated from the following files:
squid/src/DelayVector.h
squid/src/DelayVector.cc