Squid Web Cache: ACLHTTPHeaderData Class Reference
ACLHTTPHeaderData Class Reference
#include <HttpHeaderData.h>
Public Member Functions
ACLHTTPHeaderData ()
~ACLHTTPHeaderData () override
bool match (const HttpHeader &) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual void prepareForUse ()
Private Member Functions
MEMPROXY_CLASS (ACLHTTPHeaderData)
const Acl::Options & lineOptions () override
supported ACL "line" options (e.g., "-i")
Private Attributes
Http::HdrType hdrId
SBuf hdrName
ACLData< char const * > * regex_rule
Detailed Description
Definition at line 17 of file HttpHeaderData.h.
Constructor & Destructor Documentation
ACLHTTPHeaderData()
ACLHTTPHeaderData::ACLHTTPHeaderData ()
Definition at line 29 of file HttpHeaderData.cc.
~ACLHTTPHeaderData()
ACLHTTPHeaderData::~ACLHTTPHeaderData () override
Definition at line 32 of file HttpHeaderData.cc.
References regex_rule.
Member Function Documentation
dump()
SBufList ACLHTTPHeaderData::dump () const override virtual
Implements ACLData< const HttpHeader & >.
Definition at line 57 of file HttpHeaderData.cc.
References ACLData< M >::dump(), hdrName, and regex_rule.
empty()
bool ACLHTTPHeaderData::empty () const override virtual
Implements ACLData< const HttpHeader & >.
Definition at line 80 of file HttpHeaderData.cc.
References Http::BAD_HDR, ACLData< M >::empty(), hdrId, hdrName, SBuf::isEmpty(), and regex_rule.
lineOptions()
const Acl::Options & ACLHTTPHeaderData::lineOptions () override private virtual
Reimplemented from ACLData< const HttpHeader & >.
Definition at line 66 of file HttpHeaderData.cc.
References ACLData< M >::lineOptions(), and regex_rule.
match()
bool ACLHTTPHeaderData::match (const HttpHeader & hdr) override virtual
Implements ACLData< const HttpHeader & >.
Definition at line 38 of file HttpHeaderData.cc.
References Http::BAD_HDR, debugs, HttpHeader::getStrOrList(), HttpHeader::has(), HttpHeader::hasNamed(), hdrId, hdrName, ACLData< M >::match(), regex_rule, and StringToSBuf().
MEMPROXY_CLASS()
ACLHTTPHeaderData::MEMPROXY_CLASS (ACLHTTPHeaderData) private
parse()
void ACLHTTPHeaderData::parse () override virtual
Implements ACLData< const HttpHeader & >.
Definition at line 72 of file HttpHeaderData.cc.
References hdrId, hdrName, Http::HeaderLookupTable, Http::HeaderTableRecord::id, Http::HeaderLookupTable_t::lookup(), ACLData< M >::parse(), regex_rule, Acl::SetKey(), and ConfigParser::strtokFile().
prepareForUse()
virtual void ACLData< const HttpHeader & >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
hdrId
Http::HdrType ACLHTTPHeaderData::hdrId private
set if header is known
Definition at line 33 of file HttpHeaderData.h.
Referenced by empty(), match(), and parse().
hdrName
SBuf ACLHTTPHeaderData::hdrName private
always set
Definition at line 34 of file HttpHeaderData.h.
Referenced by dump(), empty(), match(), and parse().
regex_rule
ACLData<char const *>* ACLHTTPHeaderData::regex_rule private
Definition at line 35 of file HttpHeaderData.h.
Referenced by ~ACLHTTPHeaderData(), dump(), empty(), lineOptions(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/HttpHeaderData.h
squid/src/acl/HttpHeaderData.cc