Squid Web Cache: Acl::MyPortNameCheck Class Reference
Acl::MyPortNameCheck Class Reference abstract
a "myportname" ACL
#include <MyPortName.h>
Public Types
using Parameters = ACLData< const char * >
using Pointer = RefCount< Node >
Public Member Functions
int match (ACLChecklist *) override
Matches the actual data in checklist against this Acl::Node.
void * operator new (size_t)
void operator delete (void *)
void context (const SBuf &aName, const char *configuration)
sets user-specified ACL name and squid.conf context
bool matches (ACLChecklist *checklist) const
void parseFlags ()
configures Acl::Node options, throwing on configuration errors
virtual char const * typeString () const =0
virtual bool isProxyAuth () const
virtual bool valid () const
int cacheMatchAcl (dlink_list *cache, ACLChecklist *)
virtual int matchForCache (ACLChecklist *checklist)
void dumpWhole (const char *directiveName, std::ostream &)
Static Public Member Functions
static void ParseNamedAcl (ConfigParser &, NamedAcls *&)
parses acl directive parts that follow directive name (i.e. "acl")
static void Initialize ()
static Acl::Node * FindByName (const SBuf &)
A configured ACL with a given name or nil.
Public Attributes
SBuf name
char * cfgline = nullptr
Protected Member Functions
void parse () override
parses node representation in squid.conf; dies on failures
void prepareForUse () override
SBufList dump () const override
bool empty () const override
const Acl::Options & lineOptions () override
Protected Attributes
std::unique_ptr< Parameters > data
Private Member Functions
virtual bool requiresAle () const
whether our (i.e. shallow) match() requires checklist to have a AccessLogEntry
virtual bool requiresRequest () const
whether our (i.e. shallow) match() requires checklist to have a request
virtual bool requiresReply () const
whether our (i.e. shallow) match() requires checklist to have a reply
virtual const Acl::Options & options ()
Static Private Member Functions
static void ParseNamed (ConfigParser &, NamedAcls &, const SBuf &name)
parses acl directive parts that follow aclname
Detailed Description
Definition at line 19 of file MyPortName.h.
Member Typedef Documentation
Parameters
using Acl::ParameterizedNode< ACLData< const char * > >::Parameters = ACLData< const char * > inherited
Definition at line 26 of file ParameterizedNode.h.
Pointer
using Acl::Node::Pointer = RefCount<Node> inherited
Definition at line 29 of file Node.h.
Member Function Documentation
cacheMatchAcl()
int Acl::Node::cacheMatchAcl (dlink_list * cache, ACLChecklist * checklist) inherited
Definition at line 401 of file Acl.cc.
References acl_proxy_auth_match_cache::acl_data, dlink_node::data, debugs, dlinkAddTail(), dlink_list::head, acl_proxy_auth_match_cache::link, acl_proxy_auth_match_cache::matchrv, and dlink_node::next.
Referenced by ACLProxyAuth::matchProxyAuth().
context()
void Acl::Node::context (const SBuf & aName, const char * configuration) inherited
Definition at line 220 of file Acl.cc.
References safe_free, and xstrdup.
Referenced by aclParseAccessLine(), aclParseAclList(), Acl::AllOf::parse(), and ParseAclWithAction().
dump()
SBufList Acl::ParameterizedNode< ACLData< const char * > >::dump () const inline override protected virtual inherited
Implements Acl::Node.
Definition at line 37 of file ParameterizedNode.h.
dumpWhole()
void Acl::Node::dumpWhole (const char * directiveName, std::ostream & os) inherited
Prints aggregated "acl" (or similar) directive configuration, including the given directive name, ACL name, ACL type, and ACL parameters. The printed parameters are collected from all same-name "acl" directives.
Definition at line 371 of file Acl.cc.
References asList().
empty()
bool Acl::ParameterizedNode< ACLData< const char * > >::empty () const inline override protected virtual inherited
Implements Acl::Node.
Definition at line 38 of file ParameterizedNode.h.
FindByName()
Acl::Node * Acl::Node::FindByName (const SBuf & name) static inherited
Definition at line 159 of file Acl.cc.
References assert, Config, debugs, and SquidConfig::namedAcls.
Referenced by aclIsProxyAuth(), Acl::InnerNode::lineParse(), parse_ftp_epsv(), and TestACLMaxUserIP::testParseLine().
Initialize()
void Acl::Node::Initialize () static inherited
Definition at line 471 of file Acl.cc.
References Config, debugs, and SquidConfig::namedAcls.
Referenced by serverConnectionsOpen().
isProxyAuth()
bool Acl::Node::isProxyAuth () const virtual inherited
Reimplemented in ACLProxyAuth, and ACLExternal.
Definition at line 354 of file Acl.cc.
lineOptions()
const Acl::Options & Acl::ParameterizedNode< ACLData< const char * > >::lineOptions () inline override protected virtual inherited
Returns
(linked) "line" Options supported by this Acl::Node
See also
Acl::Node::options()
Reimplemented from Acl::Node.
Definition at line 39 of file ParameterizedNode.h.
match()
int Acl::MyPortNameCheck::match (ACLChecklist * checklist) override virtual
Implements Acl::Node.
Definition at line 18 of file MyPortName.cc.
References Acl::ParameterizedNode< ACLData< const char * > >::data, and Filled().
matches()
bool Acl::Node::matches (ACLChecklist * checklist) const inherited
Orchestrates matching checklist against the Acl::Node using match(), after checking preconditions and while providing debugging.
Returns
true if and only if there was a successful match. Updates the checklist state on match, async, and failure.
Definition at line 189 of file Acl.cc.
References ACLChecklist::asyncInProgress(), DBG_IMPORTANT, debugs, ACLChecklist::hasAle(), ACLChecklist::hasReply(), ACLChecklist::hasRequest(), ACLChecklist::setLastCheckedName(), and ACLChecklist::verifyAle().
Referenced by ACLChecklist::matchAndFinish().
matchForCache()
int Acl::Node::matchForCache (ACLChecklist * checklist) virtual inherited
Reimplemented in ACLProxyAuth.
Definition at line 383 of file Acl.cc.
References fatal().
operator delete()
void Acl::Node::operator delete (void *) inherited
Definition at line 153 of file Acl.cc.
References fatal().
operator new()
void * Acl::Node::operator new (size_t) inherited
Definition at line 147 of file Acl.cc.
References fatal().
options()
virtual const Acl::Options & Acl::Node::options () inline private virtual inherited
Returns
(linked) 'global' Options supported by this Acl::Node
Reimplemented in Acl::DestinationDomainCheck, ACLDestinationIP, Acl::AnnotationCheck, Acl::ServerNameCheck, and ACLMaxUserIP.
Definition at line 98 of file Node.h.
References Acl::NoOptions().
parse()
void Acl::ParameterizedNode< ACLData< const char * > >::parse () inline override protected virtual inherited
Implements Acl::Node.
Definition at line 35 of file ParameterizedNode.h.
parseFlags()
void Acl::Node::parseFlags () inherited
Definition at line 360 of file Acl.cc.
References Acl::ParseFlags().
ParseNamed()
void Acl::Node::ParseNamed (ConfigParser & parser, NamedAcls & namedAcls, const SBuf & name) static private inherited
Definition at line 253 of file Acl.cc.
References Assure, SBuf::cmp(), config_input_line, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::destruct(), fatalf(), HttpPortList, Acl::Make(), and ConfigParser::NextToken().
ParseNamedAcl()
void Acl::Node::ParseNamedAcl (ConfigParser & parser, NamedAcls *& namedAcls) static inherited
Definition at line 229 of file Acl.cc.
References CallParser(), DBG_CRITICAL, debugs, ConfigParser::destruct(), RefCount< C >::Make(), and ConfigParser::NextToken().
Referenced by parse_acl(), and TestACLMaxUserIP::testParseLine().
prepareForUse()
void Acl::ParameterizedNode< ACLData< const char * > >::prepareForUse () inline override protected virtual inherited
Reimplemented from Acl::Node.
Definition at line 36 of file ParameterizedNode.h.
requiresAle()
bool Acl::Node::requiresAle () const private virtual inherited
Reimplemented in ACLExternal.
Definition at line 443 of file Acl.cc.
requiresReply()
bool Acl::Node::requiresReply () const private virtual inherited
Reimplemented in Acl::HttpRepHeaderCheck, ACLHTTPStatus, and Acl::ReplyHeaderCheck< header >.
Definition at line 449 of file Acl.cc.
requiresRequest()
bool Acl::Node::requiresRequest () const private virtual inherited
Reimplemented in Acl::DestinationDomainCheck, ACLExtUser, Acl::HierCodeCheck, Acl::HttpReqHeaderCheck, Acl::MethodCheck, Acl::NoteCheck, Acl::ProtocolCheck, Acl::RequestHeaderCheck< header >, Acl::ServerNameCheck, Acl::TransactionInitiator, Acl::UrlCheck, Acl::UrlLoginCheck, Acl::UrlPathCheck, Acl::UrlPortCheck, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
Definition at line 455 of file Acl.cc.
typeString()
virtual char const * Acl::Node::typeString () const pure virtual inherited
Implemented in Acl::AllOf, Acl::AnyOf, ACLARP, Acl::NotNode, Acl::AndNode, Acl::OrNode, Acl::ConnectionsEncrypted, Acl::ConnMark, ACLDestinationIP, ACLEui64, ACLExtUser, ACLHTTPStatus, ACLLocalIP, ACLMaxConnection, ACLRandom, ACLSourceIP, Acl::TransactionInitiator, ACLMaxUserIP, ACLProxyAuth, ACLExternal, and ACLIP.
valid()
bool Acl::Node::valid () const virtual inherited
Reimplemented in ACLMaxConnection, ACLRandom, Acl::ServerNameCheck, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
Definition at line 183 of file Acl.cc.
Member Data Documentation
cfgline
char* Acl::Node::cfgline = nullptr inherited
Definition at line 83 of file Node.h.
data
std::unique_ptr<Parameters> Acl::ParameterizedNode< ACLData< const char * > >::data protected inherited
Points to items this ACL is configured to match. A derived class ensures that this pointer is never nil after object construction ends.
Definition at line 43 of file ParameterizedNode.h.
name
SBuf Acl::Node::name inherited
Either aclname parameter from the explicitly configured acl directive or a label generated for an internal ACL tree node. All Node objects corresponding to one Squid configuration have unique names. See also: context() and FindByName().
Definition at line 81 of file Node.h.
Referenced by Acl::NotNode::NotNode(), aclDestroyAccessList(), Acl::AnnotateClientCheck::match(), Acl::AnnotateTransactionCheck::match(), Acl::SourceDomainCheck::match(), ACLDestinationIP::match(), ACLRandom::match(), ACLExternal::parse(), and ACLMaxConnection::prepareForUse().
The documentation for this class was generated from the following files:
squid/src/acl/MyPortName.h
squid/src/acl/MyPortName.cc