Squid Web Cache: ErrorDetail Class Reference
ErrorDetail Class Reference abstract
interface for supplying additional information about a transaction failure
#include <Detail.h>
Public Types
using Pointer = ErrorDetailPointer
Public Member Functions
~ErrorDetail () override
virtual SBuf brief () const =0
virtual SBuf verbose (const HttpRequestPointer &) const =0
bool equals (const ErrorDetail &other) const
Detailed Description
Definition at line 20 of file Detail.h.
Member Typedef Documentation
Pointer
using ErrorDetail::Pointer = ErrorDetailPointer
Definition at line 23 of file Detail.h.
Constructor & Destructor Documentation
~ErrorDetail()
ErrorDetail::~ErrorDetail () inline override
Definition at line 25 of file Detail.h.
Member Function Documentation
brief()
virtual SBuf ErrorDetail::brief () const pure virtual
Returns
a single "token" summarizing available details suitable as an access.log field and similar output processed by programs
Implemented in Ftp::ErrorDetail, NamedErrorDetail, ExceptionErrorDetail, SysErrorDetail, and Security::ErrorDetail.
Referenced by ErrorState::compileLegacyCode(), and operator<<().
equals()
bool ErrorDetail::equals (const ErrorDetail & other) const inline
Definition at line 44 of file Detail.h.
Referenced by Error::update().
verbose()
virtual SBuf ErrorDetail::verbose (const HttpRequestPointer &) const pure virtual
Returns
all available details; may be customized for the given request suitable for error pages and other output meant for human consumption
Implemented in Ftp::ErrorDetail, NamedErrorDetail, ExceptionErrorDetail, SysErrorDetail, and Security::ErrorDetail.
Referenced by ErrorState::compileLegacyCode().
The documentation for this class was generated from the following file:
squid/src/error/Detail.h