Squid Web Cache: Range< C, S > Class Template Reference
Range< C, S > Class Template Reference
#include <Range.h>
Public Member Functions
Range ()
Range (C start_, C end_)
Range intersection (Range const &) const
bool contains (C const &) const
S size () const
Public Attributes
C start
C end
Detailed Description
template<class C, class S = size_t>
class Range< C, S >
Definition at line 18 of file Range.h.
Constructor & Destructor Documentation
Range() [1/2]
template<class C , class S > Range< C, S >::Range ()
Definition at line 39 of file Range.h.
Range() [2/2]
template<class C , class S > Range< C, S >::Range (C start_, C end_)
Definition at line 42 of file Range.h.
Member Function Documentation
contains()
template<class C , class S > bool Range< C, S >::contains (C const & value) const
Definition at line 54 of file Range.h.
References assert.
intersection()
template<class C , class S > Range< C, S > Range< C, S >::intersection (Range< C, S > const & rhs) const
Definition at line 46 of file Range.h.
References Range< C, S >::end, max(), min(), and Range< C, S >::start.
Referenced by HttpHdrRangeSpec::canonize(), and ACLIntRange::match().
size()
template<class C , class S > S Range< C, S >::size () const
Definition at line 61 of file Range.h.
Referenced by HttpHdrRangeSpec::canonize(), mem_hdr::hasContigousContentRange(), Http::Stream::lengthToSend(), ACLIntRange::match(), Http::Stream::packRange(), HttpHdrRangeSpec::parseInit(), Snmp::Var::setName(), and Snmp::Pdu::setSystemOid().
Member Data Documentation
end
template<class C , class S = size_t> C Range< C, S >::end
Definition at line 25 of file Range.h.
Referenced by StoreEntry::bytesWanted(), mem_hdr::hasContigousContentRange(), Range< C, S >::intersection(), operator<<(), Snmp::Var::setName(), and Snmp::Pdu::setSystemOid().
start
template<class C , class S = size_t> C Range< C, S >::start
Definition at line 24 of file Range.h.
Referenced by mem_hdr::hasContigousContentRange(), Range< C, S >::intersection(), Http::Stream::lengthToSend(), operator<<(), Http::Stream::packRange(), Snmp::Var::setName(), and Snmp::Pdu::setSystemOid().
The documentation for this class was generated from the following file:
squid/src/base/Range.h