Squid Web Cache: TestProgram Class Reference
TestProgram Class Reference
implements test program's main() function while enabling customization
#include <unitTestMain.h>
Public Member Functions
virtual ~TestProgram ()=default
virtual void startup ()
int run (int argc, char *argv[])
Private Member Functions
bool runTests ()
Detailed Description
Definition at line 25 of file unitTestMain.h.
Constructor & Destructor Documentation
~TestProgram()
virtual TestProgram::~TestProgram () virtual default
Member Function Documentation
run()
int TestProgram::run (int argc, char * argv[])
Implements main(), combining all the steps. Must be called from main().
Returns
desired main() result.
Definition at line 44 of file unitTestMain.h.
References Debug::Levels, runTests(), and startup().
Referenced by main().
runTests()
bool TestProgram::runTests () private
runs all tests registered with CPPUNIT_TEST_SUITE_REGISTRATION() calls
Returns
whether all tests were successful
Definition at line 58 of file unitTestMain.h.
Referenced by run().
startup()
virtual void TestProgram::startup () inline virtual
Runs before all tests. Does nothing by default.
Reimplemented in MyTestProgram, MyTestProgram, MyTestProgram, MyTestProgram, MyTestProgram, MyTestProgram, MyTestProgram, MyTestProgram, MyTestProgram, MyTestProgram, and MyTestProgram.
Definition at line 32 of file unitTestMain.h.
Referenced by run().
The documentation for this class was generated from the following file:
squid/include/unitTestMain.h