Squid Web Cache: SignalEngine Class Reference
SignalEngine Class Reference
Public Types
enum CheckError { EVENT_IDLE = -1 , EVENT_ERROR = -2 }
Public Member Functions
int checkEvents (int timeout) override
Private Member Functions
void doShutdown (time_t wait)
void handleStoppedChild ()
Static Private Member Functions
static void StopEventLoop (void *)
static void FinalShutdownRunners (void *)
Detailed Description
Definition at line 187 of file main.cc.
Member Enumeration Documentation
CheckError
enum AsyncEngine::CheckError inherited
Enumerator
EVENT_IDLE
EVENT_ERROR
Definition at line 26 of file AsyncEngine.h.
Member Function Documentation
checkEvents()
int SignalEngine::checkEvents (int timeout) override virtual
Implements AsyncEngine.
Definition at line 216 of file main.cc.
References Config, do_handle_stopped_child, do_reconfigure, do_rotate, do_shutdown, doShutdown(), AsyncEngine::EVENT_IDLE, handleStoppedChild(), mainReconfigureStart(), mainRotate(), and SquidConfig::shutdownLifetime.
doShutdown()
void SignalEngine::doShutdown (time_t wait) private
Definition at line 261 of file main.cc.
References AvoidSignalAction(), StatCounters::client_http, debugs, do_shutdown, eventAdd(), FinalShutdownRunners(), Important, StatCounters::requests, RunRegisteredHere, serverConnectionsClose(), shutting_down, RegisteredRunner::startShutdown(), statCounter, and WIN32_svcstatusupdate().
Referenced by checkEvents().
FinalShutdownRunners()
static void SignalEngine::FinalShutdownRunners (void *) inline static private
Definition at line 199 of file main.cc.
References RegisteredRunner::endingShutdown(), eventAdd(), Auth::Scheme::FreeAll(), RunRegisteredHere, and StopEventLoop().
Referenced by doShutdown().
handleStoppedChild()
void SignalEngine::handleStoppedChild () private
Definition at line 290 of file main.cc.
References do_handle_stopped_child, pid, and WaitForAnyPid().
Referenced by checkEvents().
StopEventLoop()
static void SignalEngine::StopEventLoop (void *) inline static private
Definition at line 194 of file main.cc.
References EventLoop::Running, and EventLoop::stop().
Referenced by FinalShutdownRunners().
The documentation for this class was generated from the following file:
squid/src/main.cc