Squid Web Cache: DebugFile Class Reference
DebugFile Class Reference
a named FILE with very-early/late usage safety mechanisms
Public Member Functions
DebugFile ()
~DebugFile ()
DebugFile (DebugFile &&)=delete
void reset (FILE *newFile, const char *newName)
switches to the new pair, absorbing FILE and duping the name
void clear ()
go back to the initial state
FILE * file ()
an opened cache_log stream or nil
Public Attributes
char * name = nullptr
Private Attributes
FILE * file_ = nullptr
opened "real" file or nil; never stderr
Friends
void ResyncDebugLog (FILE *newFile)
a hack for low-level file descriptor manipulations in ipcCreate()
Detailed Description
Definition at line 83 of file debug.cc.
Constructor & Destructor Documentation
DebugFile() [1/2]
DebugFile::DebugFile () inline
Definition at line 86 of file debug.cc.
~DebugFile()
DebugFile::~DebugFile () inline
Definition at line 87 of file debug.cc.
References clear().
DebugFile() [2/2]
DebugFile::DebugFile (DebugFile &&) delete
Member Function Documentation
clear()
void DebugFile::clear () inline
Definition at line 94 of file debug.cc.
References reset().
Referenced by ~DebugFile(), _db_rotate_log(), debugOpenLog(), and Debug::StopCacheLogUse().
file()
FILE * DebugFile::file () inline
Definition at line 97 of file debug.cc.
References file_.
Referenced by DebugModule::banCacheLogUse(), DebugStream(), Debug::LogMessage(), DebugModule::prepareToDie(), CacheLogChannel::shouldWrite(), Debug::StopCacheLogUse(), DebugModule::useCacheLog(), and CacheLogChannel::write().
reset()
void DebugFile::reset (FILE * newFile, const char * newName)
Definition at line 755 of file debug.cc.
References assert, Debug::cache_log, commSetCloseOnExec(), fd_close(), FD_LOG, fd_open(), file_, name, xfree, and xstrdup.
Referenced by clear(), and debugOpenLog().
Friends And Related Symbol Documentation
ResyncDebugLog
void ResyncDebugLog (FILE * newFile) friend
Definition at line 515 of file debug.cc.
Member Data Documentation
file_
FILE* DebugFile::file_ = nullptr private
Definition at line 104 of file debug.cc.
Referenced by file(), and reset().
name
char* DebugFile::name = nullptr
Definition at line 99 of file debug.cc.
Referenced by _db_rotate_log(), and reset().
The documentation for this class was generated from the following file:
squid/src/debug/debug.cc