Squid Web Cache: Mgr::ActionParams Class Reference
Mgr::ActionParams Class Reference
Cache Manager Action parameters extracted from the user request.
#include <ActionParams.h>
Public Member Functions
ActionParams ()
ActionParams (const Ipc::TypedMsgHdr &msg)
load from msg
void pack (Ipc::TypedMsgHdr &msg) const
store into msg
Public Attributes
String httpUri
HTTP request URI.
HttpRequestMethod httpMethod
HTTP request method.
RequestFlags httpFlags
HTTP request flags.
String httpOrigin
HTTP Origin: header (if any)
String actionName
action name (and credentials realm)
String userName
user login name; currently only used for logging
String password
user password; used for acceptance check and cleared
QueryParams queryParams
Detailed Description
Definition at line 23 of file ActionParams.h.
Constructor & Destructor Documentation
ActionParams() [1/2]
Mgr::ActionParams::ActionParams ()
Definition at line 17 of file ActionParams.cc.
ActionParams() [2/2]
Mgr::ActionParams::ActionParams (const Ipc::TypedMsgHdr & msg) explicit
Definition at line 21 of file ActionParams.cc.
References Ipc::TypedMsgHdr::getPod(), Ipc::TypedMsgHdr::getString(), and String::termedBuf().
Member Function Documentation
pack()
void Mgr::ActionParams::pack (Ipc::TypedMsgHdr & msg) const
Definition at line 39 of file ActionParams.cc.
References Ipc::TypedMsgHdr::putPod(), Ipc::TypedMsgHdr::putString(), and SBufToString().
Member Data Documentation
actionName
String Mgr::ActionParams::actionName
Definition at line 39 of file ActionParams.h.
Referenced by CacheManager::createRequestedAction(), and Ipc::Coordinator::handleCacheMgrRequest().
httpFlags
RequestFlags Mgr::ActionParams::httpFlags
Definition at line 35 of file ActionParams.h.
Referenced by Mgr::Action::createStoreEntry(), and CacheManager::ParseHeaders().
httpMethod
HttpRequestMethod Mgr::ActionParams::httpMethod
Definition at line 34 of file ActionParams.h.
Referenced by Mgr::Action::createStoreEntry(), and CacheManager::ParseHeaders().
httpOrigin
String Mgr::ActionParams::httpOrigin
Definition at line 36 of file ActionParams.h.
httpUri
String Mgr::ActionParams::httpUri
Definition at line 33 of file ActionParams.h.
Referenced by Mgr::Action::createStoreEntry().
password
String Mgr::ActionParams::password
Definition at line 41 of file ActionParams.h.
Referenced by CacheManager::CheckPassword(), and CacheManager::ParseHeaders().
queryParams
QueryParams Mgr::ActionParams::queryParams
Definition at line 42 of file ActionParams.h.
userName
String Mgr::ActionParams::userName
Definition at line 40 of file ActionParams.h.
Referenced by CacheManager::ParseHeaders().
The documentation for this class was generated from the following files:
squid/src/mgr/ActionParams.h
squid/src/mgr/ActionParams.cc