Squid Web Cache: TestAuthConfig Class Reference
TestAuthConfig Class Reference
#include <testAuth.h>
Protected Member Functions
void create ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestAuthConfig)
CPPUNIT_TEST (create)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 32 of file testAuth.h.
Member Function Documentation
CPPUNIT_TEST()
TestAuthConfig::CPPUNIT_TEST (create) private
CPPUNIT_TEST_SUITE()
TestAuthConfig::CPPUNIT_TEST_SUITE (TestAuthConfig) private
CPPUNIT_TEST_SUITE_END()
TestAuthConfig::CPPUNIT_TEST_SUITE_END () private
create()
void TestAuthConfig::create () protected
Definition at line 163 of file testAuth.cc.
References fake_auth_setup(), find_proxy_auth(), Auth::Scheme::GetSchemes(), Debug::Levels, and NULL.
The documentation for this class was generated from the following files:
squid/src/tests/testAuth.h
squid/src/tests/testAuth.cc