Squid Web Cache: DiskFile Class Reference
DiskFile Class Reference abstract
#include <DiskFile.h>
Classes
class Config
generally useful configuration options supported by some children
Public Types
typedef RefCount< DiskFile > Pointer
Public Member Functions
virtual void configure (const Config &)
notes supported configuration options; kids must call this first
virtual void open (int flags, mode_t mode, RefCount< IORequestor > callback)=0
virtual void create (int flags, mode_t mode, RefCount< IORequestor > callback)=0
virtual void read (ReadRequest *)=0
virtual void write (WriteRequest *)=0
virtual void close ()=0
virtual bool canRead () const =0
virtual bool canWrite () const
virtual int getFD () const
virtual bool error () const =0
virtual bool ioInProgress () const =0
Detailed Description
Definition at line 21 of file DiskFile.h.
Member Typedef Documentation
Pointer
typedef RefCount<DiskFile> DiskFile::Pointer
Definition at line 39 of file DiskFile.h.
Member Function Documentation
canRead()
virtual bool DiskFile::canRead () const pure virtual
Implemented in BlockingFile, DiskdFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
canWrite()
virtual bool DiskFile::canWrite () const inline virtual
Reimplemented in DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
Definition at line 50 of file DiskFile.h.
close()
virtual void DiskFile::close () pure virtual
Implemented in BlockingFile, DiskdFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
configure()
virtual void DiskFile::configure (const Config &) inline virtual
Reimplemented in IpcIoFile.
Definition at line 42 of file DiskFile.h.
Referenced by IpcIoFile::configure().
create()
virtual void DiskFile::create (int flags, mode_t mode, RefCount< IORequestor > callback) pure virtual
Implemented in DiskdFile, BlockingFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
Referenced by Fs::Ufs::UFSStrategy::create().
error()
virtual bool DiskFile::error () const pure virtual
Implemented in BlockingFile, DiskdFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
Referenced by Fs::Ufs::UFSStrategy::create(), Fs::Ufs::UFSStoreState::ioCompletedNotification(), and Fs::Ufs::UFSStrategy::open().
getFD()
virtual int DiskFile::getFD () const inline virtual
During migration only
Reimplemented in BlockingFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
Definition at line 53 of file DiskFile.h.
ioInProgress()
virtual bool DiskFile::ioInProgress () const pure virtual
Inform callers if there is IO in progress
Implemented in BlockingFile, DiskdFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
open()
virtual void DiskFile::open (int flags, mode_t mode, RefCount< IORequestor > callback) pure virtual
Implemented in DiskdFile, BlockingFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
Referenced by Fs::Ufs::UFSStrategy::open().
read()
virtual void DiskFile::read (ReadRequest *) pure virtual
Implemented in BlockingFile, DiskdFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
write()
virtual void DiskFile::write (WriteRequest *) pure virtual
Implemented in BlockingFile, DiskdFile, DiskThreadsDiskFile, IpcIoFile, and MmappedFile.
The documentation for this class was generated from the following file:
squid/src/DiskIO/DiskFile.h