Squid Web Cache: Ipc::MultiQueue Class Reference
Ipc::MultiQueue Class Reference
#include <Queue.h>
Classes
struct Metadata
Shared metadata for MultiQueue.
class Owner
Public Types
typedef OneToOneUniQueue::Full Full
typedef OneToOneUniQueue::ItemTooLarge ItemTooLarge
Public Member Functions
MultiQueue (const String &id, const int localProcessId)
void clearReaderSignal (const int remoteProcessId)
clears the reader notification received by the local process from the remote process
void clearAllReaderSignals ()
clears all reader notifications received by the local process
template<class Value >
bool pop (int &remoteProcessId, Value &value)
picks a process and calls OneToOneUniQueue::pop() using its queue
template<class Value >
bool push (const int remoteProcessId, const Value &value)
calls OneToOneUniQueue::push() using the given process queue
template<class Value >
bool peek (int &remoteProcessId, Value &value) const
peeks at the item likely to be pop()ed next
template<class Value >
void stat (std::ostream &) const
prints current state; suitable for cache manager reports
QueueReader::Balance & localBalance ()
returns local reader's balance
const QueueReader::Balance & balance (const int remoteProcessId) const
returns reader's balance for a given remote process
QueueReader::Rate & localRateLimit ()
returns local reader's rate limit
const QueueReader::Rate & rateLimit (const int remoteProcessId) const
returns reader's rate limit for a given remote process
int inSize (const int remoteProcessId) const
number of items in incoming queue from a given remote process
int outSize (const int remoteProcessId) const
number of items in outgoing queue to a given remote process
Static Public Member Functions
static Owner * Init (const String &id, const int processCount, const int processIdOffset, const unsigned int maxItemSize, const int capacity)
Protected Member Functions
const OneToOneUniQueue & inQueue (const int remoteProcessId) const override
incoming queue from a given remote process
const OneToOneUniQueue & outQueue (const int remoteProcessId) const override
outgoing queue to a given remote process
const QueueReader & localReader () const override
const QueueReader & remoteReader (const int remoteProcessId) const override
int remotesCount () const override
int remotesIdOffset () const override
OneToOneUniQueue & inQueue (const int remoteProcessId)
OneToOneUniQueue & outQueue (const int remoteProcessId)
QueueReader & localReader ()
QueueReader & remoteReader (const int remoteProcessId)
Protected Attributes
const int theLocalProcessId
process ID of this queue
Private Member Functions
bool validProcessId (const int processId) const
const OneToOneUniQueue & oneToOneQueue (const int fromProcessId, const int toProcessId) const
const QueueReader & reader (const int processId) const
Private Attributes
const Mem::Pointer< Metadata > metadata
shared metadata
const Mem::Pointer< OneToOneUniQueues > queues
unidirection one-to-one queues
const Mem::Pointer< QueueReaders > readers
readers array
int theLastPopProcessId
the ID of the last process we tried to pop() from
Detailed Description
Lockless fixed-capacity bidirectional queue for a limited number processes. Any process may send data to and receive from any other process (including itself). Each process has a unique integer ID in [processIdOffset, processIdOffset + processCount) range.
Definition at line 316 of file Queue.h.
Member Typedef Documentation
Full
typedef OneToOneUniQueue::Full Ipc::MultiQueue::Full
Definition at line 319 of file Queue.h.
ItemTooLarge
typedef OneToOneUniQueue::ItemTooLarge Ipc::MultiQueue::ItemTooLarge
Definition at line 320 of file Queue.h.
Constructor & Destructor Documentation
MultiQueue()
Ipc::MultiQueue::MultiQueue (const String & id, const int localProcessId)
Definition at line 373 of file Queue.cc.
References debugs, localReader(), metadata, Must, queues, and readers.
Member Function Documentation
balance()
const Ipc::QueueReader::Balance & Ipc::BaseMultiQueue::balance (const int remoteProcessId) const inherited
Definition at line 180 of file Queue.cc.
References Ipc::QueueReader::balance.
clearAllReaderSignals()
void Ipc::BaseMultiQueue::clearAllReaderSignals () inherited
Definition at line 172 of file Queue.cc.
References Ipc::QueueReader::clearSignal(), debugs, and Ipc::QueueReader::id.
clearReaderSignal()
void Ipc::BaseMultiQueue::clearReaderSignal (const int remoteProcessId) inherited
Definition at line 159 of file Queue.cc.
Init()
Ipc::MultiQueue::Owner * Ipc::MultiQueue::Init (const String & id, const int processCount, const int processIdOffset, const unsigned int maxItemSize, const int capacity) static
Definition at line 368 of file Queue.cc.
Referenced by CollapsedForwardingRr::create().
inQueue() [1/2]
Ipc::OneToOneUniQueue & Ipc::BaseMultiQueue::inQueue (const int remoteProcessId) protected inherited
Definition at line 194 of file Queue.cc.
inQueue() [2/2]
const Ipc::OneToOneUniQueue & Ipc::MultiQueue::inQueue (const int remoteProcessId) const override protected virtual
Implements Ipc::BaseMultiQueue.
Definition at line 412 of file Queue.cc.
inSize()
int Ipc::BaseMultiQueue::inSize (const int remoteProcessId) const inline inherited
Definition at line 204 of file Queue.h.
References Ipc::BaseMultiQueue::inQueue(), and Ipc::OneToOneUniQueue::size().
localBalance()
QueueReader::Balance & Ipc::BaseMultiQueue::localBalance () inline inherited
Definition at line 192 of file Queue.h.
References Ipc::QueueReader::balance, and Ipc::BaseMultiQueue::localReader().
localRateLimit()
QueueReader::Rate & Ipc::BaseMultiQueue::localRateLimit () inline inherited
Definition at line 198 of file Queue.h.
References Ipc::BaseMultiQueue::localReader(), and Ipc::QueueReader::rateLimit.
localReader() [1/2]
Ipc::QueueReader & Ipc::BaseMultiQueue::localReader () protected inherited
Definition at line 210 of file Queue.cc.
localReader() [2/2]
const Ipc::QueueReader & Ipc::MultiQueue::localReader () const override protected virtual
Implements Ipc::BaseMultiQueue.
Definition at line 424 of file Queue.cc.
Referenced by MultiQueue().
oneToOneQueue()
const Ipc::OneToOneUniQueue & Ipc::MultiQueue::oneToOneQueue (const int fromProcessId, const int toProcessId) const private
Definition at line 393 of file Queue.cc.
References assert.
outQueue() [1/2]
Ipc::OneToOneUniQueue & Ipc::BaseMultiQueue::outQueue (const int remoteProcessId) protected inherited
Definition at line 202 of file Queue.cc.
outQueue() [2/2]
const Ipc::OneToOneUniQueue & Ipc::MultiQueue::outQueue (const int remoteProcessId) const override protected virtual
Implements Ipc::BaseMultiQueue.
Definition at line 418 of file Queue.cc.
outSize()
int Ipc::BaseMultiQueue::outSize (const int remoteProcessId) const inline inherited
Definition at line 207 of file Queue.h.
References Ipc::BaseMultiQueue::outQueue(), and Ipc::OneToOneUniQueue::size().
peek()
template<class Value > bool Ipc::BaseMultiQueue::peek (int & remoteProcessId, Value & value) const inherited
Definition at line 568 of file Queue.h.
References Ipc::BaseMultiQueue::inQueue(), Ipc::OneToOneUniQueue::peek(), Ipc::BaseMultiQueue::remotesCount(), Ipc::BaseMultiQueue::remotesIdOffset(), and Ipc::BaseMultiQueue::theLastPopProcessId.
pop()
template<class Value > bool Ipc::BaseMultiQueue::pop (int & remoteProcessId, Value & value) inherited
Definition at line 540 of file Queue.h.
References debugs, Ipc::BaseMultiQueue::inQueue(), Ipc::BaseMultiQueue::localReader(), Ipc::OneToOneUniQueue::pop(), Ipc::BaseMultiQueue::remotesCount(), Ipc::BaseMultiQueue::remotesIdOffset(), Ipc::OneToOneUniQueue::size(), Ipc::BaseMultiQueue::theLastPopProcessId, and Ipc::BaseMultiQueue::theLocalProcessId.
push()
template<class Value > bool Ipc::BaseMultiQueue::push (const int remoteProcessId, const Value & value) inherited
Definition at line 558 of file Queue.h.
References debugs, Ipc::BaseMultiQueue::outQueue(), Ipc::OneToOneUniQueue::push(), Ipc::BaseMultiQueue::remoteReader(), Ipc::OneToOneUniQueue::size(), and Ipc::BaseMultiQueue::theLocalProcessId.
rateLimit()
const Ipc::QueueReader::Rate & Ipc::BaseMultiQueue::rateLimit (const int remoteProcessId) const inherited
Definition at line 187 of file Queue.cc.
References Ipc::QueueReader::rateLimit.
reader()
const Ipc::QueueReader & Ipc::MultiQueue::reader (const int processId) const private
Definition at line 404 of file Queue.cc.
References assert.
remoteReader() [1/2]
Ipc::QueueReader & Ipc::BaseMultiQueue::remoteReader (const int remoteProcessId) protected inherited
Definition at line 218 of file Queue.cc.
remoteReader() [2/2]
const Ipc::QueueReader & Ipc::MultiQueue::remoteReader (const int remoteProcessId) const override protected virtual
Implements Ipc::BaseMultiQueue.
Definition at line 430 of file Queue.cc.
remotesCount()
int Ipc::MultiQueue::remotesCount () const override protected virtual
Implements Ipc::BaseMultiQueue.
Definition at line 436 of file Queue.cc.
remotesIdOffset()
int Ipc::MultiQueue::remotesIdOffset () const override protected virtual
Implements Ipc::BaseMultiQueue.
Definition at line 442 of file Queue.cc.
stat()
template<class Value > void Ipc::BaseMultiQueue::stat (std::ostream & os) const inherited
Definition at line 586 of file Queue.h.
References Ipc::BaseMultiQueue::inQueue(), Ipc::BaseMultiQueue::localReader(), Ipc::BaseMultiQueue::outQueue(), Ipc::BaseMultiQueue::remotesCount(), Ipc::BaseMultiQueue::remotesIdOffset(), and Ipc::BaseMultiQueue::theLocalProcessId.
validProcessId()
bool Ipc::MultiQueue::validProcessId (const int processId) const private
Definition at line 386 of file Queue.cc.
Member Data Documentation
metadata
const Mem::Pointer<Metadata> Ipc::MultiQueue::metadata private
Definition at line 364 of file Queue.h.
Referenced by MultiQueue().
queues
const Mem::Pointer<OneToOneUniQueues> Ipc::MultiQueue::queues private
Definition at line 365 of file Queue.h.
Referenced by MultiQueue().
readers
const Mem::Pointer<QueueReaders> Ipc::MultiQueue::readers private
Definition at line 366 of file Queue.h.
Referenced by MultiQueue().
theLastPopProcessId
int Ipc::BaseMultiQueue::theLastPopProcessId private inherited
Definition at line 231 of file Queue.h.
Referenced by Ipc::BaseMultiQueue::peek(), and Ipc::BaseMultiQueue::pop().
theLocalProcessId
const int Ipc::BaseMultiQueue::theLocalProcessId protected inherited
Definition at line 228 of file Queue.h.
Referenced by Ipc::FewToFewBiQueue::findOldest(), Ipc::BaseMultiQueue::pop(), Ipc::BaseMultiQueue::push(), and Ipc::BaseMultiQueue::stat().
The documentation for this class was generated from the following files:
squid/src/ipc/Queue.h
squid/src/ipc/Queue.cc