Squid Web Cache: Ipc::StrandSearchRequest Class Reference
Ipc::StrandSearchRequest Class Reference
asynchronous strand search request
#include <StrandSearch.h>
Public Member Functions
StrandSearchRequest (const String &aTag)
sender's constructor
StrandSearchRequest (const TypedMsgHdr &hdrMsg)
from recvmsg()
void pack (TypedMsgHdr &hdrMsg) const
prepare for sendmsg()
Public Attributes
int requestorId
sender-provided return address
String tag
set when looking for a matching StrandCoord::tag
QuestionerId qid
the sender of the request
Detailed Description
Definition at line 21 of file StrandSearch.h.
Constructor & Destructor Documentation
StrandSearchRequest() [1/2]
Ipc::StrandSearchRequest::StrandSearchRequest (const String & aTag) explicit
Definition at line 17 of file StrandSearch.cc.
References Ipc::MyQuestionerId().
StrandSearchRequest() [2/2]
Ipc::StrandSearchRequest::StrandSearchRequest (const TypedMsgHdr & hdrMsg) explicit
Definition at line 24 of file StrandSearch.cc.
References Ipc::TypedMsgHdr::checkType(), Ipc::TypedMsgHdr::getPod(), Ipc::TypedMsgHdr::getString(), Ipc::mtFindStrand, qid, requestorId, tag, and Ipc::QuestionerId::unpack().
Member Function Documentation
pack()
void Ipc::StrandSearchRequest::pack (TypedMsgHdr & hdrMsg) const
Definition at line 33 of file StrandSearch.cc.
References Ipc::mtFindStrand, Ipc::TypedMsgHdr::putPod(), Ipc::TypedMsgHdr::putString(), and Ipc::TypedMsgHdr::setType().
Referenced by IpcIoFile::open().
Member Data Documentation
qid
QuestionerId Ipc::StrandSearchRequest::qid
Definition at line 31 of file StrandSearch.h.
Referenced by StrandSearchRequest(), and Ipc::Coordinator::notifySearcher().
requestorId
int Ipc::StrandSearchRequest::requestorId
Definition at line 29 of file StrandSearch.h.
Referenced by StrandSearchRequest(), Ipc::Coordinator::handleSearchRequest(), Ipc::Coordinator::notifySearcher(), and Ipc::Coordinator::receive().
tag
String Ipc::StrandSearchRequest::tag
Definition at line 30 of file StrandSearch.h.
Referenced by StrandSearchRequest(), Ipc::Coordinator::handleSearchRequest(), Ipc::Coordinator::notifySearcher(), and Ipc::Coordinator::receive().
The documentation for this class was generated from the following files:
squid/src/ipc/StrandSearch.h
squid/src/ipc/StrandSearch.cc