Squid Web Cache: SnmpRr Class Reference
SnmpRr Class Reference
Public Types
typedef void(RegisteredRunner::* Method) ()
a pointer to one of the above notification methods
Public Member Functions
void finalizeConfig () override
void useConfig () override
void startReconfigure () override
void syncConfig () override
void startShutdown () override
virtual void bootstrapConfig ()
virtual void claimMemoryNeeds ()
virtual void endingShutdown ()
virtual void finishShutdown ()
Meant for cleanup of services needed by the already destroyed objects.
Detailed Description
Definition at line 339 of file snmp_core.cc.
Member Typedef Documentation
Method
typedef void(RegisteredRunner::* RegisteredRunner::Method) () inherited
Definition at line 94 of file RunnersRegistry.h.
Member Function Documentation
bootstrapConfig()
virtual void RegisteredRunner::bootstrapConfig () inline virtual inherited
Called right before parsing squid.conf. Meant for initializing/preparing configuration parsing facilities.
Reimplemented in NtlmAuthRr.
Definition at line 46 of file RunnersRegistry.h.
Referenced by SquidMain().
claimMemoryNeeds()
virtual void RegisteredRunner::claimMemoryNeeds () inline virtual inherited
Called after finalizeConfig(). Meant for announcing memory reservations before memory is allocated.
Reimplemented in IpcIoRr, and MemStoreRr.
Definition at line 55 of file RunnersRegistry.h.
Referenced by RunConfigUsers().
endingShutdown()
virtual void RegisteredRunner::endingShutdown () inline virtual inherited
Called after shutdown_lifetime grace period ends and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented in Auth::CredentialCacheRr, ConnStateData, Dns::ConfigRr, and IdleConnList.
Definition at line 84 of file RunnersRegistry.h.
Referenced by SignalEngine::FinalShutdownRunners().
finalizeConfig()
void SnmpRr::finalizeConfig () inline override virtual
Called after parsing squid.conf. Meant for setting configuration options that depend on other configuration options and were not explicitly configured.
Reimplemented from RegisteredRunner.
Definition at line 342 of file snmp_core.cc.
References snmpInit().
finishShutdown()
virtual void RegisteredRunner::finishShutdown () inline virtual inherited
Definition at line 91 of file RunnersRegistry.h.
Referenced by RunRegistered(), SquidShutdown(), TestRock::tearDown(), and watch_child().
startReconfigure()
void SnmpRr::startReconfigure () inline override virtual
Called after receiving a reconfigure request and before parsing squid.conf. Meant for modules that need to prepare for their configuration being changed [outside their control]. The changes end with the syncConfig() event.
Reimplemented from RegisteredRunner.
Definition at line 344 of file snmp_core.cc.
References snmpClosePorts().
startShutdown()
void SnmpRr::startShutdown () inline override virtual
Called after receiving a shutdown request and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented from RegisteredRunner.
Definition at line 346 of file snmp_core.cc.
References snmpClosePorts().
syncConfig()
void SnmpRr::syncConfig () inline override virtual
Called after parsing squid.conf during reconfiguration. Meant for adjusting the module state based on configuration changes.
Reimplemented from RegisteredRunner.
Definition at line 345 of file snmp_core.cc.
References snmpOpenPorts().
useConfig()
void SnmpRr::useConfig () inline override virtual
Called after claimMemoryNeeds(). Meant for activating modules and features using a finalized configuration with known memory requirements.
Reimplemented from RegisteredRunner.
Definition at line 343 of file snmp_core.cc.
References snmpOpenPorts().
The documentation for this class was generated from the following file:
squid/src/snmp_core.cc