Squid Web Cache: CommonNamesPrinter Class Reference
CommonNamesPrinter Class Reference
prints X.509 names extracted using Ssl::HasMatchingSubjectName()
Public Member Functions
CommonNamesPrinter (std::ostream &os)
bool match (const Ssl::GeneralName &) const
whether the given name satisfies algorithm conditions
Public Attributes
size_t printed = 0
the number of names printed so far
Protected Member Functions
bool matchDomainName (const Dns::DomainName &) const override
bool matchIp (const Ip::Address &) const override
Private Member Functions
std::ostream & itemStream () const
Private Attributes
std::ostream & os_
destination for printed names
Detailed Description
Definition at line 582 of file ErrorDetail.cc.
Constructor & Destructor Documentation
CommonNamesPrinter()
CommonNamesPrinter::CommonNamesPrinter (std::ostream & os) inline explicit
Definition at line 585 of file ErrorDetail.cc.
Member Function Documentation
itemStream()
std::ostream & CommonNamesPrinter::itemStream () const private
prints a comma in front of each item except for the very first one
Returns
a stream for printing the name
Definition at line 621 of file ErrorDetail.cc.
match()
bool Ssl::GeneralNameMatcher::match (const Ssl::GeneralName & name) const inherited
Definition at line 84 of file support.cc.
References Assure, AnyP::Host::domainName(), AnyP::Host::ip(), Ssl::GeneralNameMatcher::matchDomainName(), and Ssl::GeneralNameMatcher::matchIp().
Referenced by Ssl::HasMatchingSubjectName().
matchDomainName()
bool CommonNamesPrinter::matchDomainName (const Dns::DomainName & domain) const override protected virtual
Implements Ssl::GeneralNameMatcher.
Definition at line 602 of file ErrorDetail.cc.
References html_quote().
matchIp()
bool CommonNamesPrinter::matchIp (const Ip::Address & ip) const override protected virtual
Implements Ssl::GeneralNameMatcher.
Definition at line 610 of file ErrorDetail.cc.
References MAX_IPSTRLEN, and Ip::Address::toStr().
Member Data Documentation
os_
std::ostream& CommonNamesPrinter::os_ private
Definition at line 598 of file ErrorDetail.cc.
printed
size_t CommonNamesPrinter::printed = 0 mutable
Definition at line 588 of file ErrorDetail.cc.
Referenced by Security::ErrorDetail::printCommonName().
The documentation for this class was generated from the following file:
squid/src/security/ErrorDetail.cc