Squid Web Cache: ConfigParser::CfgFile Class Reference
ConfigParser::CfgFile Class Reference
#include <ConfigParser.h>
Public Member Functions
CfgFile ()
~CfgFile ()
bool isOpen ()
True if the configuration file is open.
bool startParse (char *path)
char * parse (TokenType &type)
Public Attributes
std::string filePath
The file path.
std::string currentLine
The current line to parse.
int lineNo
Current line number.
Private Member Functions
bool getFileLine ()
Read the next line from the file.
char * nextElement (TokenType &type)
Private Attributes
FILE * wordFile
Pointer to the file.
char parseBuffer [CONFIG_LINE_LIMIT]
Temporary buffer to store data to parse.
const char * parsePos
The next element position in parseBuffer string.
Detailed Description
Class used to store required information for the current configuration file.
Definition at line 167 of file ConfigParser.h.
Constructor & Destructor Documentation
CfgFile()
ConfigParser::CfgFile::CfgFile () inline
Definition at line 170 of file ConfigParser.h.
References parseBuffer.
~CfgFile()
ConfigParser::CfgFile::~CfgFile ()
Definition at line 679 of file ConfigParser.cc.
Member Function Documentation
getFileLine()
bool ConfigParser::CfgFile::getFileLine () private
Definition at line 635 of file ConfigParser.cc.
References CONFIG_LINE_LIMIT.
Referenced by startParse().
isOpen()
bool ConfigParser::CfgFile::isOpen () inline
Definition at line 173 of file ConfigParser.h.
References wordFile.
Referenced by ConfigParser::NextToken().
nextElement()
char * ConfigParser::CfgFile::nextElement (ConfigParser::TokenType & type) private
Return the body of the next element. If the wasQuoted is given set to true if the element was quoted.
Definition at line 669 of file ConfigParser.cc.
References ConfigParser::FunctionParameters, ConfigParser::PreviewMode_, ConfigParser::token(), and ConfigParser::TokenParse().
parse()
char * ConfigParser::CfgFile::parse (ConfigParser::TokenType & type)
Do the next parsing step: reads the next line from file if required.
Returns
the body of next element or a NULL pointer if there are no more token elements in the file.
Parameters
type will be filled with the ConfigParse::TokenType for any element found, or left unchanged if NULL is returned.
Definition at line 652 of file ConfigParser.cc.
References ConfigParser::token().
Referenced by ConfigParser::NextToken().
startParse()
bool ConfigParser::CfgFile::startParse (char * path)
Open the file given by 'path' and initializes the CfgFile object to start parsing
Definition at line 617 of file ConfigParser.cc.
References assert, DBG_CRITICAL, debugs, filePath, getFileLine(), O_TEXT, and wordFile.
Referenced by ConfigParser::NextToken().
Member Data Documentation
currentLine
std::string ConfigParser::CfgFile::currentLine
Definition at line 201 of file ConfigParser.h.
Referenced by ConfigParser::destruct().
filePath
std::string ConfigParser::CfgFile::filePath
Definition at line 200 of file ConfigParser.h.
Referenced by ConfigParser::destruct(), ConfigParser::NextToken(), and startParse().
lineNo
int ConfigParser::CfgFile::lineNo
Definition at line 202 of file ConfigParser.h.
Referenced by ConfigParser::destruct().
parseBuffer
char ConfigParser::CfgFile::parseBuffer[CONFIG_LINE_LIMIT] private
Definition at line 197 of file ConfigParser.h.
Referenced by CfgFile().
parsePos
const char* ConfigParser::CfgFile::parsePos private
Definition at line 198 of file ConfigParser.h.
wordFile
FILE* ConfigParser::CfgFile::wordFile private
Definition at line 196 of file ConfigParser.h.
Referenced by isOpen(), and startParse().
The documentation for this class was generated from the following files:
squid/src/ConfigParser.h
squid/src/ConfigParser.cc