Squid Web Cache: statefulhelper Class Reference
statefulhelper Class Reference
#include <helper.h>
Public Types
using Pointer = RefCount< statefulhelper >
typedef std::unordered_map< Helper::ReservationId, helper_stateful_server * > Reservations
Public Member Functions
~statefulhelper () override=default
void reserveServer (helper_stateful_server *srv)
reserve the given server
void cancelReservation (const Helper::ReservationId reservation)
undo reserveServer(), clear the reservation and kick the queue
void openSessions () override
Xaction * nextRequest ()
bool trySubmit (const char *buf, HLPCB *callback, void *data)
If possible, submit request. Otherwise, either kill Squid or return false.
void submitRequest (Xaction *)
void packStatsInto (Packable *p, const char *label=nullptr) const
Dump some stats about the helper state to a Packable object.
bool willOverload () const
void handleKilledServer (SessionBase *)
void handleFewerServers (bool madeProgress)
void dropQueued ()
void callBack (Xaction &)
sends transaction response to the transaction initiator
Static Public Member Functions
static Pointer Make (const char *name)
Public Attributes
wordlist * cmdline = nullptr
dlink_list servers
std::queue< Xaction * > queue
const char * id_name = nullptr
ChildConfig childs
Configuration settings for number running.
int ipc_type = 0
Ip::Address addr
unsigned int droppedRequests = 0
requests not sent during helper overload
time_t overloadStart = 0
when the helper became overloaded (zero if it is not)
time_t last_queue_warn = 0
time_t last_restart = 0
time_t timeout = 0
Requests timeout.
bool retryTimedOut = false
Whether the timed-out requests must retried.
bool retryBrokenHelper = false
Whether the requests must retried on BH replies.
SBuf onTimedOutResponse
The response to use when helper response timedout.
char eom = '\n'
The char which marks the end of (response) message, normally '
'.
struct Helper::Client::_stats stats
Protected Member Functions
bool queueFull () const
whether queuing an additional request would overload the helper
bool overloaded () const
void syncQueueStats ()
synchronizes queue-dependent measurements with the current queue state
bool prepSubmit ()
void submit (const char *buf, HLPCB *callback, void *data)
dispatches or enqueues a helper requests; does not enforce queue limits
Private Member Functions
statefulhelper (const char *const name)
helper_stateful_server * findServer (const Helper::ReservationId &reservation)
void submit (const char *buf, HLPCB *callback, void *data, const Helper::ReservationId &reservation)
bool trySubmit (const char *buf, HLPCB *callback, void *data, const Helper::ReservationId &reservation)
reserved servers indexed by reservation IDs
Private Attributes
Reservations reservations
Friends
void helperStatefulSubmit (const statefulhelper::Pointer &, const char *buf, HLPCB *, void *cbData, const Helper::ReservationId &)
Detailed Description
Definition at line 154 of file helper.h.
Member Typedef Documentation
Pointer
using statefulhelper::Pointer = RefCount<statefulhelper>
Definition at line 157 of file helper.h.
Reservations
typedef std::unordered_map<Helper::ReservationId, helper_stateful_server *> statefulhelper::Reservations
Definition at line 158 of file helper.h.
Constructor & Destructor Documentation
~statefulhelper()
statefulhelper::~statefulhelper () override default
statefulhelper()
statefulhelper::statefulhelper (const char *const name) inline explicit private
Definition at line 176 of file helper.h.
Member Function Documentation
callBack()
void Client::callBack (Xaction & r) inherited
Definition at line 573 of file helper.cc.
References Assure, Helper::Request::callback, cbdataReferenceValidDone, Helper::Request::data, Helper::Xaction::reply, and Helper::Xaction::request.
Referenced by helperReturnBuffer().
cancelReservation()
void statefulhelper::cancelReservation (const Helper::ReservationId reservation)
Definition at line 618 of file helper.cc.
References asyncCall(), cbdataDialer(), helper_stateful_server::clearReservation(), helperStatefulServerDone(), and ScheduleCallHere.
dropQueued()
void Client::dropQueued () inherited
satisfies all queued requests with a Helper::Unknown answer \prec no existing servers will be able to process queued requests
See also
SessionBase::dropQueued()
Definition at line 888 of file helper.cc.
References Assure, DBG_CRITICAL, debugs, GetFirstAvailable(), and Helper::Unknown.
Referenced by helperKickQueue(), helperShutdown(), and helperStatefulKickQueue().
findServer()
helper_stateful_server * statefulhelper::findServer (const Helper::ReservationId & reservation) private
Returns
the previously reserved server (if the reservation is still valid) or nil
Definition at line 634 of file helper.cc.
handleFewerServers()
void Client::handleFewerServers (bool madeProgress) inherited
Reacts to unexpected helper process death(s), including a failure to start helper(s) and an unexpected exit of a previously started helper.
See also
handleKilledServer()
Parameters
madeProgress whether the died helper(s) responded to any requests
Definition at line 909 of file helper.cc.
References DBG_CRITICAL, DBG_IMPORTANT, debugs, Debug::Extra(), fatalf(), and squid_curtime.
handleKilledServer()
void Client::handleKilledServer (SessionBase * srv) inherited
Updates internal statistics and starts new helper processes after an unexpected server exit
Definition at line 868 of file helper.cc.
References assert, DBG_CRITICAL, debugs, Helper::SessionBase::flags, Helper::SessionBase::index, Helper::SessionBase::replies, Helper::SessionBase::_helper_flags::shutdown, and Helper::SessionBase::stats.
Referenced by Helper::SessionBase::HelperServerClosed().
Make()
statefulhelper::Pointer statefulhelper::Make (const char * name) static
Definition at line 764 of file helper.cc.
nextRequest()
Helper::Xaction * Client::nextRequest () inherited
Returns
next request in the queue, or nil.
Definition at line 1303 of file helper.cc.
Referenced by helperKickQueue(), and helperStatefulKickQueue().
openSessions()
void statefulhelper::openSessions () override virtual
Starts required helper process(es). The caller is responsible for checking that new processes are needed.
Reimplemented from Helper::Client.
Definition at line 328 of file helper.cc.
References Helper::SessionBase::addr, assert, asyncCall(), cbdataDialer(), comm_add_close_handler(), comm_read(), commCbCall(), commSetNonBlocking(), DBG_CRITICAL, DBG_IMPORTANT, debugs, dlinkAddTail(), Comm::Connection::fd, FD_DESC_SZ, fd_note(), getCurrentTime(), HELPER_MAX_ARGS, Helper::SessionBase::HelperServerClosed(), helperStatefulHandleRead, helperStatefulKickQueue(), Helper::SessionBase::hIpc, hIpc, Helper::SessionBase::initStats(), ipcCreate(), Helper::SessionBase::link, memAllocBuf(), wordlist::next, helper_stateful_server::parent, Helper::SessionBase::pid, pid, progname, Helper::SessionBase::rbuf, Helper::SessionBase::rbuf_sz, ReadBufSize(), Helper::SessionBase::readPipe, helper_stateful_server::reservationStart, Helper::SessionBase::roffset, safe_free, squid_curtime, Helper::SessionBase::writePipe, xmalloc, and xstrdup.
Referenced by StatefulEnqueue().
overloaded()
bool Client::overloaded () const protected inherited
Definition at line 494 of file helper.cc.
packStatsInto()
void Client::packStatsInto (Packable * p, const char * label = nullptr) const inherited
Definition at line 695 of file helper.cc.
References Packable::append(), Packable::appendf(), assert, current_time, int, PRIu64, Format::QuoteMimeBlob(), and tvSubMsec().
Referenced by authenticateNegotiateStats(), and authenticateNTLMStats().
prepSubmit()
bool Client::prepSubmit () protected inherited
prepares the helper for request submission returns true if and only if the submission should proceed may kill Squid if the helper remains overloaded for too long
Definition at line 527 of file helper.cc.
References Helper::ChildConfig::actDie, DBG_IMPORTANT, debugs, fatalf(), and squid_curtime.
queueFull()
bool Client::queueFull () const protected inherited
Definition at line 489 of file helper.cc.
reserveServer()
void statefulhelper::reserveServer (helper_stateful_server * srv)
Definition at line 605 of file helper.cc.
References helper_stateful_server::clearReservation(), helper_stateful_server::reservationId, helper_stateful_server::reserve(), and helper_stateful_server::reserved().
Referenced by helperStatefulKickQueue().
submit() [1/2]
void Client::submit (const char * buf, HLPCB * callback, void * data) protected inherited
Definition at line 565 of file helper.cc.
References DBG_DATA, and debugs.
submit() [2/2]
void statefulhelper::submit (const char * buf, HLPCB * callback, void * data, const Helper::ReservationId & reservation) private
Definition at line 665 of file helper.cc.
References DBG_CRITICAL, debugs, helperStatefulDispatch(), Helper::Xaction::reply, Helper::Reply::result, StatefulEnqueue(), StatefulGetFirstAvailable(), and Helper::TimedOut.
submitRequest()
void Client::submitRequest (Xaction * r) inherited
Submits a request to the helper or add it to the queue if none of the servers is available.
Definition at line 456 of file helper.cc.
References Enqueue(), GetFirstAvailable(), and helperDispatch().
Referenced by helperReturnBuffer().
syncQueueStats()
void Client::syncQueueStats () protected inherited
Definition at line 500 of file helper.cc.
References DBG_IMPORTANT, debugs, and squid_curtime.
trySubmit() [1/2]
bool Client::trySubmit (const char * buf, HLPCB * callback, void * data) inherited
Definition at line 554 of file helper.cc.
Referenced by helperSubmit().
trySubmit() [2/2]
bool statefulhelper::trySubmit (const char * buf, HLPCB * callback, void * data, const Helper::ReservationId & reservation) private
If possible, submit request. Otherwise, either kill Squid or return false.
Definition at line 595 of file helper.cc.
willOverload()
bool Client::willOverload () const inherited
whether the helper will be in "overloaded" state after one more request already overloaded helpers return true
Definition at line 753 of file helper.cc.
References GetFirstAvailable().
Friends And Related Symbol Documentation
helperStatefulSubmit
void helperStatefulSubmit (const statefulhelper::Pointer & hlp, const char * buf, HLPCB * callback, void * cbData, const Helper::ReservationId & reservation) friend
Submit request or callback the caller with a Helper::Error error. If the reservation is not set then reserves a new helper.
Definition at line 587 of file helper.cc.
Member Data Documentation
addr
Ip::Address Helper::Client::addr inherited
Definition at line 121 of file helper.h.
childs
ChildConfig Helper::Client::childs inherited
Definition at line 119 of file helper.h.
Referenced by Enqueue(), GetFirstAvailable(), helperKickQueue(), helperReturnBuffer(), helperShutdown(), helperStatefulKickQueue(), helperStatefulShutdown(), StatefulEnqueue(), and StatefulGetFirstAvailable().
cmdline
wordlist* Helper::Client::cmdline = nullptr inherited
Definition at line 115 of file helper.h.
droppedRequests
unsigned int Helper::Client::droppedRequests = 0 inherited
Definition at line 122 of file helper.h.
eom
char Helper::Client::eom = '\n' inherited
Definition at line 130 of file helper.h.
id_name
const char* Helper::Client::id_name = nullptr inherited
Definition at line 118 of file helper.h.
Referenced by Enqueue(), helperReturnBuffer(), helperShutdown(), helperStatefulShutdown(), and StatefulEnqueue().
ipc_type
int Helper::Client::ipc_type = 0 inherited
Definition at line 120 of file helper.h.
last_queue_warn
time_t Helper::Client::last_queue_warn = 0 inherited
Definition at line 124 of file helper.h.
Referenced by Enqueue(), and StatefulEnqueue().
last_restart
time_t Helper::Client::last_restart = 0 inherited
Definition at line 125 of file helper.h.
onTimedOutResponse
SBuf Helper::Client::onTimedOutResponse inherited
Definition at line 129 of file helper.h.
overloadStart
time_t Helper::Client::overloadStart = 0 inherited
Definition at line 123 of file helper.h.
queue
std::queue<Xaction *> Helper::Client::queue inherited
Definition at line 117 of file helper.h.
Referenced by Enqueue(), and StatefulEnqueue().
reservations
Reservations statefulhelper::reservations private
Definition at line 185 of file helper.h.
retryBrokenHelper
bool Helper::Client::retryBrokenHelper = false inherited
Definition at line 128 of file helper.h.
retryTimedOut
bool Helper::Client::retryTimedOut = false inherited
Definition at line 127 of file helper.h.
Referenced by helperReturnBuffer().
servers
dlink_list Helper::Client::servers inherited
Definition at line 116 of file helper.h.
Referenced by GetFirstAvailable(), helperShutdown(), helperStatefulShutdown(), and StatefulGetFirstAvailable().
stats
struct Helper::Client::_stats Helper::Client::stats inherited
Referenced by Enqueue(), helperReturnBuffer(), and StatefulEnqueue().
timeout
time_t Helper::Client::timeout = 0 inherited
Definition at line 126 of file helper.h.
Referenced by helperReturnBuffer().
The documentation for this class was generated from the following files:
squid/src/helper.h
squid/src/helper.cc