Squid Web Cache: Adaptation::Ecap::HeaderRep Class Reference
Adaptation::Ecap::HeaderRep Class Reference
#include <MessageRep.h>
Public Types
typedef libecap::Name Name
typedef libecap::Area Area
Public Member Functions
HeaderRep (Http::Message &aMessage)
bool hasAny (const Name &name) const override
Value value (const Name &name) const override
void add (const Name &name, const Value &value) override
void removeAny (const Name &name) override
void visitEach (libecap::NamedValueVisitor &visitor) const override
Area image () const override
void parse (const Area &buf) override
Static Protected Member Functions
static Http::HdrType TranslateHeaderId (const Name &name)
Private Attributes
HttpHeader & theHeader
Http::Message & theMessage
Detailed Description
Definition at line 39 of file MessageRep.h.
Member Typedef Documentation
Area
typedef libecap::Area Adaptation::Ecap::HeaderRep::Area
Definition at line 43 of file MessageRep.h.
Name
typedef libecap::Name Adaptation::Ecap::HeaderRep::Name
Definition at line 42 of file MessageRep.h.
Constructor & Destructor Documentation
HeaderRep()
Adaptation::Ecap::HeaderRep::HeaderRep (Http::Message & aMessage)
Definition at line 31 of file MessageRep.cc.
Member Function Documentation
add()
void Adaptation::Ecap::HeaderRep::add (const Name & name, const Value & value) override
Definition at line 57 of file MessageRep.cc.
References SBuf::c_str(), and Http::CONTENT_LENGTH.
hasAny()
bool Adaptation::Ecap::HeaderRep::hasAny (const Name & name) const override
Definition at line 37 of file MessageRep.cc.
References Http::OTHER.
image()
libecap::Area Adaptation::Ecap::HeaderRep::image () const override
Definition at line 93 of file MessageRep.cc.
References MemBuf::content(), MemBuf::contentSize(), and MemBuf::init().
parse()
void Adaptation::Ecap::HeaderRep::parse (const Area & buf) override
Definition at line 103 of file MessageRep.cc.
References error(), and Must.
removeAny()
void Adaptation::Ecap::HeaderRep::removeAny (const Name & name) override
Definition at line 69 of file MessageRep.cc.
References Http::CONTENT_LENGTH, and Http::OTHER.
TranslateHeaderId()
Http::HdrType Adaptation::Ecap::HeaderRep::TranslateHeaderId (const Name & name) static protected
Definition at line 110 of file MessageRep.cc.
References Http::OTHER.
value()
Adaptation::Ecap::HeaderRep::Value Adaptation::Ecap::HeaderRep::value (const Name & name) const override
Definition at line 46 of file MessageRep.cc.
References Http::OTHER, String::size(), and String::termedBuf().
visitEach()
void Adaptation::Ecap::HeaderRep::visitEach (libecap::NamedValueVisitor & visitor) const override
Definition at line 82 of file MessageRep.cc.
References HttpHeaderInitPos.
Member Data Documentation
theHeader
HttpHeader& Adaptation::Ecap::HeaderRep::theHeader private
Definition at line 61 of file MessageRep.h.
theMessage
Http::Message& Adaptation::Ecap::HeaderRep::theMessage private
Definition at line 62 of file MessageRep.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/ecap/MessageRep.h
squid/src/adaptation/ecap/MessageRep.cc