Squid Web Cache: Adaptation::DynamicServiceChain Class Reference
Adaptation::DynamicServiceChain Class Reference
a temporary service chain built upon another service request
#include <ServiceGroups.h>
Public Types
typedef RefCount< ServiceGroup > Pointer
typedef std::vector< String > Store
typedef String Id
typedef unsigned int Pos
Public Member Functions
DynamicServiceChain (const DynamicGroupCfg &cfg, const ServiceFilter &f)
virtual void parse ()
virtual void finalize ()
bool wants (const ServiceFilter &filter) const
Static Public Member Functions
static void Split (const ServiceFilter &filter, const String &ids, DynamicGroupCfg &current, DynamicGroupCfg &future)
separates dynamic services matching current location from future ones
Public Attributes
String kind
Id id
Store services
Store removedServices
the disabled services in the case ecap or icap is disabled
Method method
VectPoint point
based on the first added service
const bool allServicesSame
based on the first added service
Protected Member Functions
virtual bool replace (Pos &) const
virtual bool advance (Pos &pos) const
bool has (const Pos pos) const
< whether this group has a service at the specified pos
bool findReplacement (const ServiceFilter &filter, Pos &pos) const
these methods control group iteration; used by ServicePlan
bool findLink (const ServiceFilter &filter, Pos &pos) const
find next to link after success, starting with pos
Private Member Functions
ServicePointer at (const Pos pos) const
bool findService (const ServiceFilter &filter, Pos &pos) const
void checkUniqueness (const Pos checkedPos) const
checks that the service name or URI is not repeated later in the group
void finalizeMsg (const char *msg, const String &culprit, bool error) const
emits a formatted warning or error message at the appropriate dbg level
Detailed Description
Definition at line 110 of file ServiceGroups.h.
Member Typedef Documentation
Id
typedef String Adaptation::ServiceGroup::Id inherited
Definition at line 30 of file ServiceGroups.h.
Pointer
typedef RefCount<ServiceGroup> Adaptation::ServiceGroup::Pointer inherited
Definition at line 27 of file ServiceGroups.h.
Pos
typedef unsigned int Adaptation::ServiceGroup::Pos inherited
Definition at line 31 of file ServiceGroups.h.
Store
typedef std::vector<String> Adaptation::ServiceGroup::Store inherited
Definition at line 29 of file ServiceGroups.h.
Constructor & Destructor Documentation
DynamicServiceChain()
Adaptation::DynamicServiceChain::DynamicServiceChain (const DynamicGroupCfg & cfg, const ServiceFilter & f)
Definition at line 228 of file ServiceGroups.cc.
References Adaptation::DynamicGroupCfg::id, Adaptation::ServiceFilter::method, Adaptation::ServiceFilter::point, and Adaptation::DynamicGroupCfg::services.
Member Function Documentation
advance()
virtual bool Adaptation::ServiceChain::advance (Pos & pos) const inline protected virtual inherited
Definition at line 106 of file ServiceGroups.h.
References Adaptation::ServiceGroup::has().
at()
Adaptation::ServicePointer Adaptation::ServiceGroup::at (const Pos pos) const private inherited
Definition at line 127 of file ServiceGroups.cc.
References Adaptation::FindService().
checkUniqueness()
void Adaptation::ServiceGroup::checkUniqueness (const Pos checkedPos) const private inherited
Definition at line 101 of file ServiceGroups.cc.
References Adaptation::Service::cfg(), Adaptation::ServiceConfig::key, and Adaptation::ServiceConfig::uri.
finalize()
void Adaptation::ServiceGroup::finalize () virtual inherited
Definition at line 45 of file ServiceGroups.cc.
References String::append(), Adaptation::ServiceConfig::bypass, Adaptation::Service::cfg(), String::cut(), DBG_CRITICAL, DBG_IMPORTANT, debugs, Adaptation::ServiceConfig::key, Adaptation::ServiceConfig::method, Adaptation::methodNone, Adaptation::ServiceConfig::point, and String::size().
Referenced by Adaptation::AccessRule::finalize().
finalizeMsg()
void Adaptation::ServiceGroup::finalizeMsg (const char * msg, const String & culprit, bool error) const private inherited
Definition at line 118 of file ServiceGroups.cc.
References DBG_CRITICAL, DBG_IMPORTANT, debugs, and error().
findLink()
bool Adaptation::ServiceGroup::findLink (const ServiceFilter & filter, Pos & pos) const protected inherited
Definition at line 200 of file ServiceGroups.cc.
findReplacement()
bool Adaptation::ServiceGroup::findReplacement (const ServiceFilter & filter, Pos & pos) const protected inherited
find next to try after failure, starting with pos
Definition at line 194 of file ServiceGroups.cc.
findService()
bool Adaptation::ServiceGroup::findService (const ServiceFilter & filter, Pos & pos) const private inherited
Definition at line 141 of file ServiceGroups.cc.
References Adaptation::ServiceConfig::bypass, Adaptation::Service::cfg(), debugs, Adaptation::ServiceFilter::method, Adaptation::ServiceFilter::point, Adaptation::Service::probed(), Adaptation::Service::up(), and Adaptation::Service::wants().
has()
bool Adaptation::ServiceGroup::has (const Pos pos) const inline protected inherited
Definition at line 45 of file ServiceGroups.h.
References Adaptation::ServiceGroup::services.
Referenced by Adaptation::ServiceChain::advance(), and Adaptation::ServiceSet::replace().
parse()
void Adaptation::ServiceGroup::parse () virtual inherited
Definition at line 32 of file ServiceGroups.cc.
References wordlist::next, ConfigParser::NextToken(), ConfigParser::ParseWordList(), and wordlistDestroy().
Referenced by Adaptation::Config::ParseServiceGroup().
replace()
virtual bool Adaptation::ServiceChain::replace (Pos &) const inline protected virtual inherited
Definition at line 105 of file ServiceGroups.h.
Split()
void Adaptation::DynamicServiceChain::Split (const ServiceFilter & filter, const String & ids, DynamicGroupCfg & current, DynamicGroupCfg & future) static
Definition at line 243 of file ServiceGroups.cc.
References Adaptation::DynamicGroupCfg::add(), String::assign(), Adaptation::Service::cfg(), Adaptation::FindService(), Adaptation::ServiceConfig::method, Adaptation::ServiceFilter::method, Adaptation::ServiceConfig::point, Adaptation::ServiceFilter::point, and strListGetItem().
Referenced by Adaptation::History::extractCurrentServices(), and Adaptation::Iterator::updatePlan().
wants()
bool Adaptation::ServiceGroup::wants (const ServiceFilter & filter) const inherited
Definition at line 134 of file ServiceGroups.cc.
Referenced by Adaptation::AccessCheck::isCandidate().
Member Data Documentation
allServicesSame
const bool Adaptation::ServiceGroup::allServicesSame inherited
Definition at line 73 of file ServiceGroups.h.
id
Id Adaptation::ServiceGroup::id inherited
Definition at line 66 of file ServiceGroups.h.
Referenced by Adaptation::Config::removeService().
kind
String Adaptation::ServiceGroup::kind inherited
Definition at line 65 of file ServiceGroups.h.
method
Method Adaptation::ServiceGroup::method inherited
Definition at line 70 of file ServiceGroups.h.
point
VectPoint Adaptation::ServiceGroup::point inherited
Definition at line 71 of file ServiceGroups.h.
removedServices
Store Adaptation::ServiceGroup::removedServices inherited
Definition at line 68 of file ServiceGroups.h.
Referenced by Adaptation::Config::removeService().
services
Store Adaptation::ServiceGroup::services inherited
Definition at line 67 of file ServiceGroups.h.
Referenced by Adaptation::SingleService::SingleService(), Adaptation::ServiceGroup::has(), and Adaptation::Config::removeService().
The documentation for this class was generated from the following files:
squid/src/adaptation/ServiceGroups.h
squid/src/adaptation/ServiceGroups.cc