Squid Web Cache: TestRfc1738 Class Reference
TestRfc1738 Class Reference
Protected Member Functions
void testUrlDecode ()
void testUrlEncode ()
void PercentZeroNullDecoding ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestRfc1738)
CPPUNIT_TEST (testUrlDecode)
CPPUNIT_TEST (testUrlEncode)
CPPUNIT_TEST (PercentZeroNullDecoding)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Test the URL coder RFC 1738 Engine
Definition at line 21 of file testRFC1738.cc.
Member Function Documentation
CPPUNIT_TEST() [1/3]
TestRfc1738::CPPUNIT_TEST (PercentZeroNullDecoding) private
CPPUNIT_TEST() [2/3]
TestRfc1738::CPPUNIT_TEST (testUrlDecode) private
CPPUNIT_TEST() [3/3]
TestRfc1738::CPPUNIT_TEST (testUrlEncode) private
CPPUNIT_TEST_SUITE()
TestRfc1738::CPPUNIT_TEST_SUITE (TestRfc1738) private
CPPUNIT_TEST_SUITE_END()
TestRfc1738::CPPUNIT_TEST_SUITE_END () private
PercentZeroNullDecoding()
void TestRfc1738::PercentZeroNullDecoding () protected
SECURITY BUG TESTS: avoid null truncation attacks by skipping %00 bytes
Definition at line 147 of file testRFC1738.cc.
References rfc1738_unescape(), xfree, and xstrdup.
testUrlDecode()
void TestRfc1738::testUrlDecode () protected
Definition at line 41 of file testRFC1738.cc.
References rfc1738_unescape(), xfree, and xstrdup.
testUrlEncode()
void TestRfc1738::testUrlEncode () protected
Public API is formed of a triplet of encode functions mapping to the rfc1738_do_encode() engine.
Flags: rfc1738_escape == 0 rfc1738_escape_unescaped == -1 rfc1738_escape_part == 1
Definition at line 110 of file testRFC1738.cc.
References rfc1738_do_escape(), RFC1738_ESCAPE_RESERVED, RFC1738_ESCAPE_UNESCAPED, and RFC1738_ESCAPE_UNSAFE.
The documentation for this class was generated from the following file:
squid/lib/tests/testRFC1738.cc