Squid Web Cache: DelayUser::Id Class Reference
DelayUser::Id Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Public Types
typedef RefCount< DelayIdComposite > Pointer
Public Member Functions
Id (const DelayUser::Pointer &, const Auth::User::Pointer &)
~Id () override
int bytesWanted (int min, int max) const override
void bytesIn (int qty) override
virtual void delayRead (const AsyncCallPointer &)
Private Member Functions
MEMPROXY_CLASS (DelayUser::Id)
Private Attributes
RefCount< DelayUser > theUser
DelayUserBucket::Pointer theBucket
Detailed Description
Definition at line 58 of file DelayUser.h.
Member Typedef Documentation
Pointer
typedef RefCount<DelayIdComposite> DelayIdComposite::Pointer inherited
Definition at line 23 of file DelayIdComposite.h.
Constructor & Destructor Documentation
Id()
DelayUser::Id::Id (const DelayUser::Pointer & aDelayUser, const Auth::User::Pointer & aUser)
Definition at line 142 of file DelayUser.cc.
References DelayUser::buckets, DelayUserCmp, DelayBucket::init(), DelayUser::spec, DelayUserBucket::theBucket, theBucket, and theUser.
~Id()
DelayUser::Id::~Id () override
Definition at line 156 of file DelayUser.cc.
References debugs.
Member Function Documentation
bytesIn()
void DelayUser::Id::bytesIn (int qty) override virtual
Implements DelayIdComposite.
Definition at line 168 of file DelayUser.cc.
bytesWanted()
int DelayUser::Id::bytesWanted (int min, int max) const override virtual
Implements DelayIdComposite.
Definition at line 162 of file DelayUser.cc.
References max(), and min().
delayRead()
virtual void DelayIdComposite::delayRead (const AsyncCallPointer &) inline virtual inherited
Reimplemented in Aggregate::AggregateId, DelayTagged::Id, and DelayVector::Id.
Definition at line 29 of file DelayIdComposite.h.
References fatal().
Referenced by DelayId::delayRead().
MEMPROXY_CLASS()
DelayUser::Id::MEMPROXY_CLASS (DelayUser::Id) private
Member Data Documentation
theBucket
DelayUserBucket::Pointer DelayUser::Id::theBucket private
Definition at line 70 of file DelayUser.h.
Referenced by Id().
theUser
RefCount<DelayUser> DelayUser::Id::theUser private
Definition at line 69 of file DelayUser.h.
Referenced by Id().
The documentation for this class was generated from the following files:
squid/src/DelayUser.h
squid/src/DelayUser.cc