Squid Web Cache: CompositePoolNode Class Reference
CompositePoolNode Class Reference abstract
Squid Components » Delay Pools API
#include <CompositePoolNode.h>
Classes
class CompositeSelectionDetails
Public Types
typedef RefCount< CompositePoolNode > Pointer
Public Member Functions
~CompositePoolNode () override
virtual void stats (StoreEntry *sentry)=0
virtual void dump (StoreEntry *entry) const =0
void update (int incr) override=0
virtual void parse ()=0
virtual DelayIdComposite::Pointer id (CompositeSelectionDetails &)=0
void delayRead (const AsyncCallPointer &)
Protected Member Functions
void kickReads ()
Protected Attributes
DelayedAsyncCalls deferredReads
Private Member Functions
MEMPROXY_CLASS (CompositePoolNode)
Detailed Description
Definition at line 25 of file CompositePoolNode.h.
Member Typedef Documentation
Pointer
typedef RefCount<CompositePoolNode> CompositePoolNode::Pointer
Definition at line 30 of file CompositePoolNode.h.
Constructor & Destructor Documentation
~CompositePoolNode()
CompositePoolNode::~CompositePoolNode () inline override
Definition at line 31 of file CompositePoolNode.h.
Member Function Documentation
delayRead()
void CompositePoolNode::delayRead (const AsyncCallPointer & aRead)
Definition at line 80 of file DelayPool.cc.
References deferredReads, and DelayedAsyncCalls::delay().
Referenced by Aggregate::AggregateId::delayRead().
dump()
virtual void CompositePoolNode::dump (StoreEntry * entry) const pure virtual
Implemented in Aggregate, VectorPool, ClassCHostPool, DelayTagged, DelayUser, and DelayVector.
Referenced by DelayPool::dump().
id()
virtual DelayIdComposite::Pointer CompositePoolNode::id (CompositeSelectionDetails &) pure virtual
Implemented in Aggregate, VectorPool, ClassCHostPool, DelayTagged, DelayUser, and DelayVector.
kickReads()
void CompositePoolNode::kickReads () protected
Definition at line 88 of file DelayPool.cc.
References deferredReads, and DelayedAsyncCalls::schedule().
Referenced by Aggregate::update(), DelayTagged::update(), and DelayVector::update().
MEMPROXY_CLASS()
CompositePoolNode::MEMPROXY_CLASS (CompositePoolNode) private
parse()
virtual void CompositePoolNode::parse () pure virtual
Implemented in Aggregate, VectorPool, ClassCHostPool, DelayTagged, DelayUser, and DelayVector.
Referenced by DelayPool::parse().
stats()
virtual void CompositePoolNode::stats (StoreEntry * sentry) pure virtual
Implemented in Aggregate, VectorPool, ClassCHostPool, DelayTagged, DelayUser, and DelayVector.
Referenced by DelayPools::Stats().
update()
void CompositePoolNode::update (int incr) override pure virtual
Implements Updateable.
Implemented in Aggregate, VectorPool, ClassCHostPool, DelayTagged, DelayUser, and DelayVector.
Member Data Documentation
deferredReads
DelayedAsyncCalls CompositePoolNode::deferredReads protected
Definition at line 60 of file CompositePoolNode.h.
Referenced by delayRead(), and kickReads().
The documentation for this class was generated from the following files:
squid/src/CompositePoolNode.h
squid/src/DelayPool.cc