Squid Web Cache: PeerPoolMgr Class Reference
PeerPoolMgr Class Reference abstract
Maintains an fixed-size "standby" PconnPool for a single CachePeer.
#include <PeerPoolMgr.h>
Public Types
typedef CbcPointer< PeerPoolMgr > Pointer
Public Member Functions
PeerPoolMgr (CachePeer *aPeer)
~PeerPoolMgr () override
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void Checkpoint (const Pointer &mgr, const char *reason)
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
PrecomputedCodeContextPointer codeContext
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void start () override
called by AsyncStart; do not call directly
void swanSong () override
bool doneAll () const override
whether positive goal has been reached
bool validPeer () const
whether the peer is still out there and in a valid state we can safely use
void checkpoint (const char *reason)
void openNewConnection ()
starts the process of opening a new standby connection (if possible)
void closeOldConnections (const int howMany)
closes 'howMany' standby connections
void handleOpenedConnection (const CommConnectCbParams &params)
Comm::ConnOpener calls this when done opening a connection for us.
void handleSecuredPeer (Security::EncryptorAnswer &answer)
Security::PeerConnector callback.
void pushNewConnection (const Comm::ConnectionPointer &conn)
the final step in connection opening (and, optionally, securing) sequence
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual const char * status () const
internal cleanup; do not call directly
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
CBDATA_CHILD (PeerPoolMgr)
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
CachePeer * peer
the owner of the pool we manage
RefCount< HttpRequest > request
fake HTTP request for conn opening code
JobWait< Comm::ConnOpener > transportWait
waits for a transport connection to the peer to be established/opened
JobWait< Security::BlindPeerConnector > encryptionWait
waits for the established transport connection to be secured/encrypted
unsigned int addrUsed
counter for cycling through peer addresses
Detailed Description
Definition at line 23 of file PeerPoolMgr.h.
Member Typedef Documentation
Pointer
typedef CbcPointer<PeerPoolMgr> PeerPoolMgr::Pointer
Definition at line 28 of file PeerPoolMgr.h.
Constructor & Destructor Documentation
PeerPoolMgr()
PeerPoolMgr::PeerPoolMgr (CachePeer * aPeer) explicit
Definition at line 33 of file PeerPoolMgr.cc.
References codeContext, Debug::Extra(), AnyP::Uri::host(), CachePeer::host, CachePeer::id, Http::METHOD_OPTIONS, peer, AnyP::PROTO_HTTP, request, ToSBuf(), and HttpRequest::url.
~PeerPoolMgr()
PeerPoolMgr::~PeerPoolMgr () override
Definition at line 50 of file PeerPoolMgr.cc.
References cbdataReferenceDone, and peer.
Member Function Documentation
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
CBDATA_CHILD()
PeerPoolMgr::CBDATA_CHILD (PeerPoolMgr) private
checkpoint()
void PeerPoolMgr::checkpoint (const char * reason) protected
Starts new connection, or closes the excess connections according pool configuration
Definition at line 214 of file PeerPoolMgr.cc.
References closeOldConnections(), PconnPool::count(), debugs, CachePeer::limit, openNewConnection(), peer, CachePeer::pool, CachePeer::standby, and validPeer().
Referenced by handleOpenedConnection(), handleSecuredPeer(), and start().
Checkpoint()
void PeerPoolMgr::Checkpoint (const Pointer & mgr, const char * reason) static
Definition at line 232 of file PeerPoolMgr.cc.
References CallService(), codeContext, debugs, and CbcPointer< Cbc >::valid().
Referenced by CachePeer::~CachePeer(), PconnPool::notifyManager(), peerAlive(), peerConnClosed(), and peerDNSConfigure().
closeOldConnections()
void PeerPoolMgr::closeOldConnections (const int howMany) protected
Definition at line 207 of file PeerPoolMgr.cc.
References PconnPool::closeN(), debugs, peer, CachePeer::pool, and CachePeer::standby.
Referenced by checkpoint().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool PeerPoolMgr::doneAll () const override protected virtual
Reimplemented from AsyncJob.
Definition at line 75 of file PeerPoolMgr.cc.
References AsyncJob::doneAll(), CachePeer::limit, peer, CachePeer::standby, and validPeer().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
handleOpenedConnection()
void PeerPoolMgr::handleOpenedConnection (const CommConnectCbParams & params) protected
Definition at line 81 of file PeerPoolMgr.cc.
References asyncCallback, checkpoint(), Comm::Connection::close(), CommCommonCbParams::conn, CachePeer::connectTimeout(), debugs, encryptionWait, Security::PeerOptions::encryptTransport, JobWaitBase::finish(), CommCommonCbParams::flag, handleSecuredPeer(), Must, NoteOutgoingConnectionFailure(), Comm::OK, peer, positiveTimeout(), pushNewConnection(), request, CachePeer::secure, squid_curtime, JobWait< Job >::start(), Comm::Connection::startTime(), transportWait, and validPeer().
Referenced by openNewConnection().
handleSecuredPeer()
void PeerPoolMgr::handleSecuredPeer (Security::EncryptorAnswer & answer) protected
Definition at line 127 of file PeerPoolMgr.cc.
References assert, checkpoint(), Comm::Connection::close(), Security::EncryptorAnswer::conn, debugs, encryptionWait, Security::EncryptorAnswer::error, Comm::Connection::fd, fd_table, JobWaitBase::finish(), CbcPointer< Cbc >::get(), Comm::Connection::isOpen(), Comm::Connection::noteClosure(), pushNewConnection(), Security::EncryptorAnswer::tunneled, and validPeer().
Referenced by handleOpenedConnection().
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
openNewConnection()
void PeerPoolMgr::openNewConnection () protected
Definition at line 160 of file PeerPoolMgr.cc.
References CachePeer::addresses, addrUsed, CachePeer::connectTimeout(), debugs, encryptionWait, fdUsageHigh(), GetMarkingsToServer(), getOutgoingAddress(), RefCount< C >::getRaw(), handleOpenedConnection(), CachePeer::http_port, JobCallback, Must, CachePeer::n_addresses, neighborUp(), peer, peerCanOpenMore(), Comm::Connection::peerType, Ip::Address::port(), Comm::Connection::remote, request, Comm::Connection::setPeer(), shutting_down, CachePeer::standby, STANDBY_POOL, JobWait< Job >::start(), transportWait, and CachePeer::waitingForClose.
Referenced by checkpoint().
pushNewConnection()
void PeerPoolMgr::pushNewConnection (const Comm::ConnectionPointer & conn) protected
Definition at line 118 of file PeerPoolMgr.cc.
References Comm::IsConnOpen(), Must, peer, CachePeer::pool, PconnPool::push(), CachePeer::standby, and validPeer().
Referenced by handleOpenedConnection(), and handleSecuredPeer().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
start()
void PeerPoolMgr::start () override protected virtual
Reimplemented from AsyncJob.
Definition at line 56 of file PeerPoolMgr.cc.
References checkpoint(), and AsyncJob::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
status()
const char * AsyncJob::status () const protected virtual inherited
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), AsyncJob::stopReason, and MemBuf::terminate().
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
swanSong()
void PeerPoolMgr::swanSong () override protected virtual
Reimplemented from AsyncJob.
Definition at line 63 of file PeerPoolMgr.cc.
References AsyncJob::swanSong().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
validPeer()
bool PeerPoolMgr::validPeer () const protected
Definition at line 69 of file PeerPoolMgr.cc.
References cbdataReferenceValid(), peer, CachePeer::pool, and CachePeer::standby.
Referenced by checkpoint(), doneAll(), handleOpenedConnection(), handleSecuredPeer(), and pushNewConnection().
Member Data Documentation
addrUsed
unsigned int PeerPoolMgr::addrUsed private
Definition at line 74 of file PeerPoolMgr.h.
Referenced by openNewConnection().
codeContext
PrecomputedCodeContextPointer PeerPoolMgr::codeContext
Definition at line 36 of file PeerPoolMgr.h.
Referenced by PeerPoolMgr(), and Checkpoint().
encryptionWait
JobWait<Security::BlindPeerConnector> PeerPoolMgr::encryptionWait private
Definition at line 72 of file PeerPoolMgr.h.
Referenced by handleOpenedConnection(), handleSecuredPeer(), and openNewConnection().
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
peer
CachePeer* PeerPoolMgr::peer private
Definition at line 65 of file PeerPoolMgr.h.
Referenced by PeerPoolMgr(), ~PeerPoolMgr(), checkpoint(), closeOldConnections(), doneAll(), handleOpenedConnection(), openNewConnection(), pushNewConnection(), and validPeer().
request
RefCount<HttpRequest> PeerPoolMgr::request private
Definition at line 66 of file PeerPoolMgr.h.
Referenced by PeerPoolMgr(), handleOpenedConnection(), and openNewConnection().
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
transportWait
JobWait<Comm::ConnOpener> PeerPoolMgr::transportWait private
Definition at line 69 of file PeerPoolMgr.h.
Referenced by handleOpenedConnection(), and openNewConnection().
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
The documentation for this class was generated from the following files:
squid/src/PeerPoolMgr.h
squid/src/PeerPoolMgr.cc