Squid Web Cache: TestSBuf Class Reference
TestSBuf Class Reference
Protected Member Functions
void commonInit ()
void testSBufConstructDestruct ()
void testSBufConstructDestructAfterMemInit ()
void testEqualityTest ()
void testAppendSBuf ()
void testAppendCString ()
void testAppendStdString ()
void testAppendf ()
void testPrintf ()
void testSubscriptOp ()
void testSubscriptOpFail ()
void testDumpStats ()
void testComparisons ()
void testConsume ()
void testRawContent ()
void testRawSpace ()
void testChop ()
void testChomp ()
void testSubstr ()
void testTailCopy ()
void testSBufLength ()
void testFindChar ()
void testFindSBuf ()
void testRFindChar ()
void testRFindSBuf ()
void testSearchFail ()
void testCopy ()
void testStringOps ()
void testGrow ()
void testReserve ()
void testStartsWith ()
void testSBufStream ()
void testFindFirstOf ()
void testFindFirstNotOf ()
void testAutoFind ()
void testStdStringOps ()
void testIterators ()
void testSBufHash ()
void testStdAlgorithm ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestSBuf)
CPPUNIT_TEST (testSBufConstructDestruct)
CPPUNIT_TEST (testSBufConstructDestructAfterMemInit)
CPPUNIT_TEST (testSBufLength)
CPPUNIT_TEST (testEqualityTest)
CPPUNIT_TEST (testStartsWith)
CPPUNIT_TEST (testAppendSBuf)
CPPUNIT_TEST (testAppendCString)
CPPUNIT_TEST (testAppendStdString)
CPPUNIT_TEST (testAppendf)
CPPUNIT_TEST (testSubscriptOp)
CPPUNIT_TEST_EXCEPTION (testSubscriptOpFail, TextException)
CPPUNIT_TEST (testComparisons)
CPPUNIT_TEST (testConsume)
CPPUNIT_TEST (testRawContent)
CPPUNIT_TEST (testRawSpace)
CPPUNIT_TEST (testChop)
CPPUNIT_TEST (testChomp)
CPPUNIT_TEST (testSubstr)
CPPUNIT_TEST (testFindChar)
CPPUNIT_TEST (testFindSBuf)
CPPUNIT_TEST (testRFindChar)
CPPUNIT_TEST (testRFindSBuf)
CPPUNIT_TEST (testFindFirstOf)
CPPUNIT_TEST (testFindFirstNotOf)
CPPUNIT_TEST (testPrintf)
CPPUNIT_TEST (testCopy)
CPPUNIT_TEST (testStringOps)
CPPUNIT_TEST (testGrow)
CPPUNIT_TEST (testReserve)
CPPUNIT_TEST (testSBufStream)
CPPUNIT_TEST (testAutoFind)
CPPUNIT_TEST (testStdStringOps)
CPPUNIT_TEST (testIterators)
CPPUNIT_TEST (testSBufHash)
CPPUNIT_TEST (testStdAlgorithm)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 31 of file testSBuf.cc.
Member Function Documentation
commonInit()
void TestSBuf::commonInit () protected
CPPUNIT_TEST() [1/34]
TestSBuf::CPPUNIT_TEST (testAppendCString) private
CPPUNIT_TEST() [2/34]
TestSBuf::CPPUNIT_TEST (testAppendf) private
CPPUNIT_TEST() [3/34]
TestSBuf::CPPUNIT_TEST (testAppendSBuf) private
CPPUNIT_TEST() [4/34]
TestSBuf::CPPUNIT_TEST (testAppendStdString) private
CPPUNIT_TEST() [5/34]
TestSBuf::CPPUNIT_TEST (testAutoFind) private
CPPUNIT_TEST() [6/34]
TestSBuf::CPPUNIT_TEST (testChomp) private
CPPUNIT_TEST() [7/34]
TestSBuf::CPPUNIT_TEST (testChop) private
CPPUNIT_TEST() [8/34]
TestSBuf::CPPUNIT_TEST (testComparisons) private
CPPUNIT_TEST() [9/34]
TestSBuf::CPPUNIT_TEST (testConsume) private
CPPUNIT_TEST() [10/34]
TestSBuf::CPPUNIT_TEST (testCopy) private
CPPUNIT_TEST() [11/34]
TestSBuf::CPPUNIT_TEST (testEqualityTest) private
CPPUNIT_TEST() [12/34]
TestSBuf::CPPUNIT_TEST (testFindChar) private
CPPUNIT_TEST() [13/34]
TestSBuf::CPPUNIT_TEST (testFindFirstNotOf) private
CPPUNIT_TEST() [14/34]
TestSBuf::CPPUNIT_TEST (testFindFirstOf) private
CPPUNIT_TEST() [15/34]
TestSBuf::CPPUNIT_TEST (testFindSBuf) private
CPPUNIT_TEST() [16/34]
TestSBuf::CPPUNIT_TEST (testGrow) private
CPPUNIT_TEST() [17/34]
TestSBuf::CPPUNIT_TEST (testIterators) private
CPPUNIT_TEST() [18/34]
TestSBuf::CPPUNIT_TEST (testPrintf) private
CPPUNIT_TEST() [19/34]
TestSBuf::CPPUNIT_TEST (testRawContent) private
CPPUNIT_TEST() [20/34]
TestSBuf::CPPUNIT_TEST (testRawSpace) private
CPPUNIT_TEST() [21/34]
TestSBuf::CPPUNIT_TEST (testReserve) private
CPPUNIT_TEST() [22/34]
TestSBuf::CPPUNIT_TEST (testRFindChar) private
CPPUNIT_TEST() [23/34]
TestSBuf::CPPUNIT_TEST (testRFindSBuf) private
CPPUNIT_TEST() [24/34]
TestSBuf::CPPUNIT_TEST (testSBufConstructDestruct) private
CPPUNIT_TEST() [25/34]
TestSBuf::CPPUNIT_TEST (testSBufConstructDestructAfterMemInit) private
CPPUNIT_TEST() [26/34]
TestSBuf::CPPUNIT_TEST (testSBufHash) private
CPPUNIT_TEST() [27/34]
TestSBuf::CPPUNIT_TEST (testSBufLength) private
CPPUNIT_TEST() [28/34]
TestSBuf::CPPUNIT_TEST (testSBufStream) private
CPPUNIT_TEST() [29/34]
TestSBuf::CPPUNIT_TEST (testStartsWith) private
CPPUNIT_TEST() [30/34]
TestSBuf::CPPUNIT_TEST (testStdAlgorithm) private
CPPUNIT_TEST() [31/34]
TestSBuf::CPPUNIT_TEST (testStdStringOps) private
CPPUNIT_TEST() [32/34]
TestSBuf::CPPUNIT_TEST (testStringOps) private
CPPUNIT_TEST() [33/34]
TestSBuf::CPPUNIT_TEST (testSubscriptOp) private
CPPUNIT_TEST() [34/34]
TestSBuf::CPPUNIT_TEST (testSubstr) private
CPPUNIT_TEST_EXCEPTION()
TestSBuf::CPPUNIT_TEST_EXCEPTION (testSubscriptOpFail , TextException) private
CPPUNIT_TEST_SUITE()
TestSBuf::CPPUNIT_TEST_SUITE (TestSBuf) private
CPPUNIT_TEST_SUITE_END()
TestSBuf::CPPUNIT_TEST_SUITE_END () private
testAppendCString()
void TestSBuf::testAppendCString () protected
Definition at line 271 of file testSBuf.cc.
References fox1, fox2, literal, and s1.
testAppendf()
void TestSBuf::testAppendf () protected
Definition at line 304 of file testSBuf.cc.
References SBuf::appendf(), SBuf::assign(), fox, and s1.
testAppendSBuf()
void TestSBuf::testAppendSBuf () protected
Definition at line 241 of file testSBuf.cc.
References SBuf::append(), fox1, SBuf::rawContent(), and s1.
testAppendStdString()
void TestSBuf::testAppendStdString () protected
Definition at line 279 of file testSBuf.cc.
References alpha, SBuf::append(), control, SBuf::npos, and SBuf::rawContent().
testAutoFind()
void TestSBuf::testAutoFind () protected
Definition at line 1116 of file testSBuf.cc.
References SBufFindTest::run().
testChomp()
void TestSBuf::testChomp () protected
Definition at line 581 of file testSBuf.cc.
References SBuf::assign(), s1, and SBuf::trim().
testChop()
void TestSBuf::testChop () protected
Definition at line 517 of file testSBuf.cc.
References SBuf::assign(), SBuf::chop(), SBuf::clear(), SBuf::length(), literal, SBuf::npos, and s1.
testComparisons()
void TestSBuf::testComparisons () protected
Definition at line 409 of file testSBuf.cc.
References SBuf::assign(), SBuf::c_str(), SBuf::caseCmp(), SBuf::cmp(), SBuf::length(), min(), SBuf::rawContent(), s1, SBuf::setAt(), sign(), testComparisonStd(), testComparisonStdOneWay(), xfree, and xstrdup.
testConsume()
void TestSBuf::testConsume () protected
Definition at line 480 of file testSBuf.cc.
References SBuf::assign(), SBuf::consume(), literal, and s1.
testCopy()
void TestSBuf::testCopy () protected
Definition at line 858 of file testSBuf.cc.
References SBuf::assign(), SBuf::chop(), fox1, and literal.
testDumpStats()
void TestSBuf::testDumpStats () protected
Definition at line 313 of file testSBuf.cc.
References MemBlobStats::dump(), SBufStats::dump(), MemBlob::GetStats(), and SBuf::GetStats().
testEqualityTest()
void TestSBuf::testEqualityTest () protected
Definition at line 223 of file testSBuf.cc.
References SBuf::assign(), SBuf::clear(), fox, and s1.
testFindChar()
void TestSBuf::testFindChar () protected
Definition at line 630 of file testSBuf.cc.
References SBuf::npos, and s1.
testFindFirstNotOf()
void TestSBuf::testFindFirstNotOf () protected
Definition at line 1093 of file testSBuf.cc.
References SBuf::c_str(), SBuf::findFirstNotOf(), SBuf::length(), literal, SBuf::npos, and SBuf::substr().
testFindFirstOf()
void TestSBuf::testFindFirstOf () protected
Definition at line 1070 of file testSBuf.cc.
References SBuf::findFirstOf(), SBuf::length(), literal, and SBuf::npos.
testFindSBuf()
void TestSBuf::testFindSBuf () protected
Definition at line 687 of file testSBuf.cc.
References SBuf::append(), SBuf::find(), SBuf::npos, and SBuf::rfind().
testGrow()
void TestSBuf::testGrow () protected
Definition at line 886 of file testSBuf.cc.
References SBuf::append(), SBuf::assign(), literal, SBuf::rawContent(), and SBuf::reserveCapacity().
testIterators()
void TestSBuf::testIterators () protected
Definition at line 1132 of file testSBuf.cc.
References SBuf::begin(), SBuf::end(), SBuf::rbegin(), SBuf::rend(), and text.
testPrintf()
void TestSBuf::testPrintf () protected
Definition at line 262 of file testSBuf.cc.
References SBuf::assign(), SBuf::Printf(), and s1.
testRawContent()
void TestSBuf::testRawContent () protected
Definition at line 493 of file testSBuf.cc.
References SBuf::append(), fox, literal, SBuf::rawContent(), and s1.
testRawSpace()
void TestSBuf::testRawSpace () protected
Definition at line 506 of file testSBuf.cc.
References fox1, fox2, literal, SBuf::rawAppendFinish(), SBuf::rawAppendStart(), and s1.
testReserve()
void TestSBuf::testReserve () protected
Definition at line 901 of file testSBuf.cc.
References SBufReservationRequirements::allowShared, SBuf::append(), SBuf::c_str(), SBuf::consume(), fox, SBuf::GetStats(), SBufReservationRequirements::idealSpace, SBuf::length(), SBufReservationRequirements::maxCapacity, min(), SBufReservationRequirements::minSpace, SBuf::rawContent(), SBuf::reserve(), SBuf::reserveCapacity(), SBuf::reserveSpace(), and SBuf::spaceSize().
testRFindChar()
void TestSBuf::testRFindChar () protected
Definition at line 796 of file testSBuf.cc.
References literal, and s1.
testRFindSBuf()
void TestSBuf::testRFindSBuf () protected
Definition at line 806 of file testSBuf.cc.
References literal, SBuf::npos, and SBuf::rfind().
testSBufConstructDestruct()
void TestSBuf::testSBufConstructDestruct () protected
Definition at line 136 of file testSBuf.cc.
References empty_sbuf, fox, literal, SBuf::rawContent(), s1, and SBuf::substr().
Referenced by testSBufConstructDestructAfterMemInit().
testSBufConstructDestructAfterMemInit()
void TestSBuf::testSBufConstructDestructAfterMemInit () protected
Definition at line 216 of file testSBuf.cc.
References Mem::Init(), and testSBufConstructDestruct().
testSBufHash()
void TestSBuf::testSBufHash () protected
Definition at line 1169 of file testSBuf.cc.
References fox, fox1, and literal.
testSBufLength()
void TestSBuf::testSBufLength () protected
Definition at line 851 of file testSBuf.cc.
References fox, and SBuf::length().
testSBufStream()
void TestSBuf::testSBufStream () protected
Definition at line 1052 of file testSBuf.cc.
References SBufStream::buf(), SBufStream::clearBuf(), fox1, fox2, and literal.
testSearchFail()
void TestSBuf::testSearchFail () protected
testStartsWith()
void TestSBuf::testStartsWith () protected
Definition at line 1035 of file testSBuf.cc.
References caseInsensitive, fox1, fox2, literal, SBuf::startsWith(), and ToUpper().
testStdAlgorithm()
void TestSBuf::testStdAlgorithm () protected
Definition at line 1197 of file testSBuf.cc.
References fox.
testStdStringOps()
void TestSBuf::testStdStringOps () protected
Definition at line 1123 of file testSBuf.cc.
References SBuf::toStdString().
testStringOps()
void TestSBuf::testStringOps () protected
Definition at line 872 of file testSBuf.cc.
References caseInsensitive, SBuf::compare(), literal, and ToLower().
testSubscriptOp()
void TestSBuf::testSubscriptOp () protected
Definition at line 322 of file testSBuf.cc.
References literal, and SBuf::setAt().
testSubscriptOpFail()
void TestSBuf::testSubscriptOpFail () protected
Definition at line 334 of file testSBuf.cc.
References SBuf::at(), SBuf::length(), and literal.
testSubstr()
void TestSBuf::testSubstr () protected
Definition at line 618 of file testSBuf.cc.
References SBuf::assign(), literal, s1, and SBuf::substr().
testTailCopy()
void TestSBuf::testTailCopy () protected
The documentation for this class was generated from the following file:
squid/src/tests/testSBuf.cc