Squid Web Cache: Security::ServerOptions Class Reference
Security::ServerOptions Class Reference
TLS squid.conf settings for a listening port.
#include <ServerOptions.h>
Public Types
typedef std::unique_ptr< STACK_OF(X509_NAME), Security::ServerOptions::sk_X509_NAME_free_wrapper > X509_NAME_STACK_Pointer
Public Member Functions
sk_dtor_wrapper (sk_X509_NAME, STACK_OF(X509_NAME) *, X509_NAME_free)
ServerOptions ()
ServerOptions (const ServerOptions &o)
ServerOptions & operator= (const ServerOptions &)
ServerOptions (ServerOptions &&o)
ServerOptions & operator= (ServerOptions &&o)
~ServerOptions () override=default
void parse (const char *) override
parse a TLS squid.conf option
void clear () override
reset the configuration details to default
Security::ContextPointer createBlankContext () const override
generate an unset security context object
void dumpCfg (std::ostream &, const char *pfx) const override
output squid.conf syntax with 'pfx' prefix on parameters for the stored settings
void initServerContexts (AnyP::PortCfg &)
bool updateContextConfig (Security::ContextPointer &)
update the given TLS security context using squid.conf settings
void updateContextEecdh (Security::ContextPointer &)
update the context with DH, EDH, EECDH settings
void updateContextClientCa (Security::ContextPointer &)
update the context with CA details used to verify client certificates
void updateContextSessionId (Security::ContextPointer &)
update the context with a configured session ID (if any)
void syncCaFiles ()
sync the various sources of CA files to be loaded
void parseOptions ()
parse and verify the [tls-]options= string in sslOptions
Security::ContextPointer createClientContext (bool setOptions)
generate a security client-context from these configured options
void updateTlsVersionLimits ()
sync the context options with tls-min-version=N configuration
void updateContextOptions (Security::ContextPointer &)
Setup the library specific 'options=' parameters for the given context.
void updateContextNpn (Security::ContextPointer &)
setup the NPN extension details for the given context
void updateContextCa (Security::ContextPointer &)
setup the CA details for the given context
void updateContextCrl (Security::ContextPointer &)
setup the CRL details for the given context
void updateContextTrust (Security::ContextPointer &)
decide which CAs to trust
void updateSessionOptions (Security::SessionPointer &)
setup any library-specific options that can be set for the given session
Public Attributes
Security::ContextPointer staticContext
TLS context to use for HTTPS accelerator or static SSL-Bump.
SBuf staticContextSessionId
"session id context" for staticContext
bool generateHostCertificates = true
dynamically make host cert
Security::KeyData signingCa
x509 certificate and key for signing generated certificates
Security::KeyData untrustedSigningCa
x509 certificate and key for signing untrusted generated certificates
size_t dynamicCertMemCacheSize = 4*1024*1024
max size of generated certificates memory cache (4 MB default)
SBuf sslOptions
library-specific options string
SBuf caDir
path of directory containing a set of trusted Certificate Authorities
SBuf crlFile
path of file containing Certificate Revoke List
SBuf sslCipher
SBuf sslFlags
flags defining what TLS operations Squid performs
SBuf sslDomain
SBuf tlsMinVersion
version label for minimum TLS version to permit
ParsedPortFlags parsedFlags = 0
parsed value of sslFlags
std::list< Security::KeyData > certs
details from the cert= and file= config parameters
std::list< SBuf > caFiles
paths of files containing trusted Certificate Authority
Security::CertRevokeList parsedCrl
CRL to use when verifying the remote end certificate.
bool encryptTransport = false
whether transport encryption (TLS/SSL) is to be used on connections to the peer
Protected Member Functions
template<typename T >
Security::ContextPointer convertContextFromRawPtr (T ctx) const
Protected Attributes
int sslVersion = 0
struct Security::PeerOptions::flags_ flags
Private Member Functions
bool loadClientCaFile ()
void loadDhParams ()
bool createStaticServerContext (AnyP::PortCfg &)
void createSigningContexts (const AnyP::PortCfg &)
ParsedPortFlags parseFlags ()
void loadCrlFile ()
void loadKeysFile ()
Private Attributes
SBuf clientCaFile
name of file to load client CAs from
X509_NAME_STACK_Pointer clientCaStack
CA certificate(s) to use when verifying client certificates.
SBuf dh
Diffi-Helman cipher config.
SBuf dhParamsFile
Diffi-Helman ciphers parameter file.
SBuf eecdhCurve
Elliptic curve for ephemeral EC-based DH key exchanges.
Security::DhePointer parsedDhParams
DH parameters for temporary/ephemeral DH key exchanges.
SBuf tlsMinOptions
Security::ParsedOptions parsedOptions
bool optsReparse = true
whether parsedOptions content needs to be regenerated
Detailed Description
Definition at line 25 of file ServerOptions.h.
Member Typedef Documentation
X509_NAME_STACK_Pointer
typedef std::unique_ptr<STACK_OF(X509_NAME), Security::ServerOptions::sk_X509_NAME_free_wrapper> Security::ServerOptions::X509_NAME_STACK_Pointer
Definition at line 30 of file ServerOptions.h.
Constructor & Destructor Documentation
ServerOptions() [1/3]
Security::ServerOptions::ServerOptions () inline
Definition at line 33 of file ServerOptions.h.
References YesNoNone::defaultTo(), Security::PeerOptions::flags, and Security::PeerOptions::flags_::tlsDefaultCa.
Referenced by clear().
ServerOptions() [2/3]
Security::ServerOptions::ServerOptions (const ServerOptions & o) inline
Definition at line 38 of file ServerOptions.h.
ServerOptions() [3/3]
Security::ServerOptions::ServerOptions (ServerOptions && o) inline
Definition at line 40 of file ServerOptions.h.
References operator=().
~ServerOptions()
Security::ServerOptions::~ServerOptions () override default
Member Function Documentation
clear()
void Security::ServerOptions::clear () inline override virtual
Reimplemented from Security::PeerOptions.
Definition at line 46 of file ServerOptions.h.
References ServerOptions().
convertContextFromRawPtr()
template<typename T > Security::ContextPointer Security::PeerOptions::convertContextFromRawPtr (T ctx) const inline protected inherited
Definition at line 111 of file PeerOptions.h.
References assert, and debugs.
createBlankContext()
Security::ContextPointer Security::ServerOptions::createBlankContext () const override virtual
Reimplemented from Security::PeerOptions.
Definition at line 163 of file ServerOptions.cc.
References DBG_CRITICAL, debugs, Security::ErrorString(), Ssl::Initialize(), and TLS_server_method.
Referenced by Ssl::createSSLContext().
createClientContext()
Security::ContextPointer Security::PeerOptions::createClientContext (bool setOptions) inherited
Definition at line 276 of file PeerOptions.cc.
References Ssl::InitClientContext().
Referenced by configDoConfigure().
createSigningContexts()
void Security::ServerOptions::createSigningContexts (const AnyP::PortCfg & port) private
initialize contexts for signing dynamic TLS certificates (if needed) the resulting keys are stored in signingCa and untrustedSigningCa
Definition at line 285 of file ServerOptions.cc.
References DBG_CRITICAL, DBG_IMPORTANT, debugs, fatalf(), Ssl::generateUntrustedCert(), port, and AnyP::ProtocolType_str.
createStaticServerContext()
bool Security::ServerOptions::createStaticServerContext (AnyP::PortCfg &) private
generate a security server-context from these configured options the resulting context is stored in staticContext
Returns
true if a context could be created
Definition at line 214 of file ServerOptions.cc.
References SBuf::append(), SBuf::appendf(), DBG_CRITICAL, DBG_IMPORTANT, debugs, error(), Security::ErrorString(), and keys.
dumpCfg()
void Security::ServerOptions::dumpCfg (std::ostream & os, const char * pfx) const override virtual
Reimplemented from Security::PeerOptions.
Definition at line 140 of file ServerOptions.cc.
References Security::PeerOptions::dumpCfg().
initServerContexts()
void Security::ServerOptions::initServerContexts (AnyP::PortCfg & port)
initialize all server contexts as-needed and load PEM files. if none can be created this may do nothing.
Definition at line 193 of file ServerOptions.cc.
References fatalf(), port, and AnyP::ProtocolType_str.
loadClientCaFile()
bool Security::ServerOptions::loadClientCaFile () private
load clientca= file (if any) into memory.
Return values
true clientca is not set, or loaded successfully
false unable to load the file, or not using OpenSSL
Definition at line 338 of file ServerOptions.cc.
References DBG_CRITICAL, and debugs.
loadCrlFile()
void Security::PeerOptions::loadCrlFile () private inherited
Load a CRLs list stored in the file whose /path/name is in crlFile replaces any CRL loaded previously
Definition at line 618 of file PeerOptions.cc.
References debugs.
loadDhParams()
void Security::ServerOptions::loadDhParams () private
Interprets DHE parameters stored in a previously configured dhParamsFile. These DHE parameters are orthogonal to ECDHE curve name that may also be configured when naming that DHE parameters configuration file. When both are configured, the server selects either FFDHE or ECDHE key exchange mechanism (and its cipher suites) depending on client-supported cipher suites.
See also
Security::ServerOptions::updateContextEecdh() and RFC 7919 Section 1.2
Definition at line 361 of file ServerOptions.cc.
References asHex(), assert, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, Ssl::ForgetErrors(), Security::LockingPointer< T, UnLocker, Locker >::get(), and Ssl::ReportAndForgetErrors().
loadKeysFile()
void Security::PeerOptions::loadKeysFile () private inherited
operator=() [1/2]
Security::ServerOptions & Security::ServerOptions::operator= (const ServerOptions & old)
Definition at line 35 of file ServerOptions.cc.
References clientCaFile, clientCaStack, dh, dhParamsFile, dynamicCertMemCacheSize, eecdhCurve, generateHostCertificates, Security::PeerOptions::operator=(), parsedDhParams, signingCa, staticContextSessionId, and untrustedSigningCa.
Referenced by ServerOptions(), and operator=().
operator=() [2/2]
ServerOptions & Security::ServerOptions::operator= (ServerOptions && o) inline
Definition at line 41 of file ServerOptions.h.
References operator=().
parse()
void Security::ServerOptions::parse (const char * token) override virtual
Reimplemented from Security::PeerOptions.
Definition at line 60 of file ServerOptions.cc.
References DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, SBuf::npos, Security::PeerOptions::parse(), parseBytesOptionValue(), and self_destruct().
parseFlags()
Security::ParsedPortFlags Security::PeerOptions::parseFlags () private inherited
Parses the TLS flags squid.conf parameter
Definition at line 554 of file PeerOptions.cc.
References DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, fatal(), fatalf(), Here, SQUIDSBUFPH, SQUIDSBUFPRINT, SSL_FLAG_CONDITIONAL_AUTH, SSL_FLAG_DELAYED_AUTH, SSL_FLAG_DONT_VERIFY_DOMAIN, SSL_FLAG_DONT_VERIFY_PEER, SSL_FLAG_NO_DEFAULT_CA, SSL_FLAG_NO_SESSION_REUSE, SSL_FLAG_VERIFY_CRL, and SSL_FLAG_VERIFY_CRL_ALL.
parseOptions()
void Security::PeerOptions::parseOptions () inherited
Pre-parse TLS options= parameter to be applied when the TLS objects created. Options must not used in the case of peek or stare bump mode.
Definition at line 447 of file PeerOptions.cc.
References CharacterSet::ALPHA, SBuf::append(), Parser::Tokenizer::atEnd(), SBuf::c_str(), SBuf::cmp(), DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, CharacterSet::DIGIT, Security::ErrorString(), fatalf(), Parser::Tokenizer::int64(), SBuf::isEmpty(), ssl_option::name, SQUIDSBUFPH, SQUIDSBUFPRINT, and ssl_options.
Referenced by Security::PeerOptions::PeerOptions(), and parse_securePeerOptions().
sk_dtor_wrapper()
Security::ServerOptions::sk_dtor_wrapper (sk_X509_NAME , STACK_OF(X509_NAME) * , X509_NAME_free)
syncCaFiles()
void Security::ServerOptions::syncCaFiles ()
Definition at line 323 of file ServerOptions.cc.
updateContextCa()
void Security::PeerOptions::updateContextCa (Security::ContextPointer & ctx) inherited
Definition at line 696 of file PeerOptions.cc.
References DBG_IMPORTANT, debugs, Security::ErrorString(), and loadSystemTrustedCa().
updateContextClientCa()
void Security::ServerOptions::updateContextClientCa (Security::ContextPointer & ctx)
Definition at line 499 of file ServerOptions.cc.
References Ssl::ConfigurePeerVerification(), DBG_CRITICAL, debugs, Ssl::DisablePeerVerification(), Security::ErrorString(), and STACK_OF().
updateContextConfig()
bool Security::ServerOptions::updateContextConfig (Security::ContextPointer & ctx)
Definition at line 457 of file ServerOptions.cc.
References Config, DBG_CRITICAL, debugs, Security::ErrorString(), Ssl::MaybeSetupRsaCallback(), Security::SetSessionCacheCallbacks(), SquidConfig::SSL, ssl_ctx_ex_index_dont_verify_domain, SSL_FLAG_DONT_VERIFY_DOMAIN, SSL_FLAG_NO_SESSION_REUSE, and SquidConfig::unclean_shutdown.
Referenced by Ssl::createSSLContext().
updateContextCrl()
void Security::PeerOptions::updateContextCrl (Security::ContextPointer & ctx) inherited
Definition at line 732 of file PeerOptions.cc.
References debugs, SSL_FLAG_VERIFY_CRL, and SSL_FLAG_VERIFY_CRL_ALL.
updateContextEecdh()
void Security::ServerOptions::updateContextEecdh (Security::ContextPointer & ctx)
Definition at line 526 of file ServerOptions.cc.
References DBG_CRITICAL, DBG_IMPORTANT, debugs, Security::ErrorString(), Ssl::ForgetErrors(), and Ssl::ReportAndForgetErrors().
updateContextNpn()
void Security::PeerOptions::updateContextNpn (Security::ContextPointer & ctx) inherited
Definition at line 664 of file PeerOptions.cc.
updateContextOptions()
void Security::PeerOptions::updateContextOptions (Security::ContextPointer & ctx) inherited
Definition at line 639 of file PeerOptions.cc.
updateContextSessionId()
void Security::ServerOptions::updateContextSessionId (Security::ContextPointer & ctx)
Definition at line 593 of file ServerOptions.cc.
updateContextTrust()
void Security::PeerOptions::updateContextTrust (Security::ContextPointer & ctx) inherited
Definition at line 759 of file PeerOptions.cc.
References assert, DBG_IMPORTANT, debugs, and Security::ErrorString().
updateSessionOptions()
void Security::PeerOptions::updateSessionOptions (Security::SessionPointer & s) inherited
Definition at line 779 of file PeerOptions.cc.
References DBG_IMPORTANT, debugs, and Security::ErrorString().
Referenced by CreateSession().
updateTlsVersionLimits()
void Security::PeerOptions::updateTlsVersionLimits () inherited
Definition at line 158 of file PeerOptions.cc.
References SBuf::append(), SBuf::chop(), DBG_PARSE_NOTE, and debugs.
Member Data Documentation
caDir
SBuf Security::PeerOptions::caDir inherited
Definition at line 81 of file PeerOptions.h.
caFiles
std::list<SBuf> Security::PeerOptions::caFiles inherited
Definition at line 106 of file PeerOptions.h.
certs
std::list<Security::KeyData> Security::PeerOptions::certs inherited
Definition at line 105 of file PeerOptions.h.
Referenced by Ssl::InitClientContext().
clientCaFile
SBuf Security::ServerOptions::clientCaFile private
Definition at line 107 of file ServerOptions.h.
Referenced by operator=().
clientCaStack
X509_NAME_STACK_Pointer Security::ServerOptions::clientCaStack private
Definition at line 110 of file ServerOptions.h.
Referenced by operator=().
crlFile
SBuf Security::PeerOptions::crlFile inherited
Definition at line 82 of file PeerOptions.h.
dh
SBuf Security::ServerOptions::dh private
Definition at line 115 of file ServerOptions.h.
Referenced by operator=().
dhParamsFile
SBuf Security::ServerOptions::dhParamsFile private
Definition at line 116 of file ServerOptions.h.
Referenced by operator=().
dynamicCertMemCacheSize
size_t Security::ServerOptions::dynamicCertMemCacheSize = 4*1024*1024
Definition at line 91 of file ServerOptions.h.
Referenced by operator=().
eecdhCurve
SBuf Security::ServerOptions::eecdhCurve private
Definition at line 117 of file ServerOptions.h.
Referenced by operator=().
encryptTransport
bool Security::PeerOptions::encryptTransport = false inherited
Definition at line 147 of file PeerOptions.h.
Referenced by Adaptation::Config::dumpService(), PeerPoolMgr::handleOpenedConnection(), Security::BlindPeerConnector::initialize(), netdbExchangeStart(), FwdState::secureConnectionToPeerIfNeeded(), and CachePeer::securityContext().
flags
struct Security::PeerOptions::flags_ Security::PeerOptions::flags protected inherited
Referenced by ServerOptions().
generateHostCertificates
bool Security::ServerOptions::generateHostCertificates = true
Definition at line 75 of file ServerOptions.h.
Referenced by operator=().
optsReparse
bool Security::PeerOptions::optsReparse = true private inherited
Definition at line 100 of file PeerOptions.h.
parsedCrl
Security::CertRevokeList Security::PeerOptions::parsedCrl inherited
Definition at line 107 of file PeerOptions.h.
parsedDhParams
Security::DhePointer Security::ServerOptions::parsedDhParams private
Definition at line 119 of file ServerOptions.h.
Referenced by operator=().
parsedFlags
ParsedPortFlags Security::PeerOptions::parsedFlags = 0 inherited
Definition at line 103 of file PeerOptions.h.
parsedOptions
Security::ParsedOptions Security::PeerOptions::parsedOptions private inherited
Parsed value of sslOptions + tlsMinOptions settings. Set optsReparse=true to have this re-parsed before next use.
Definition at line 97 of file PeerOptions.h.
signingCa
Security::KeyData Security::ServerOptions::signingCa
Definition at line 87 of file ServerOptions.h.
Referenced by Ssl::chainCertificatesToSSLContext(), and operator=().
sslCipher
SBuf Security::PeerOptions::sslCipher inherited
Definition at line 84 of file PeerOptions.h.
Referenced by Ssl::InitClientContext().
sslDomain
SBuf Security::PeerOptions::sslDomain inherited
Definition at line 86 of file PeerOptions.h.
Referenced by Security::BlindPeerConnector::initialize().
sslFlags
SBuf Security::PeerOptions::sslFlags inherited
Definition at line 85 of file PeerOptions.h.
sslOptions
SBuf Security::PeerOptions::sslOptions inherited
Definition at line 80 of file PeerOptions.h.
sslVersion
int Security::PeerOptions::sslVersion = 0 protected inherited
Definition at line 130 of file PeerOptions.h.
staticContext
Security::ContextPointer Security::ServerOptions::staticContext
Definition at line 71 of file ServerOptions.h.
staticContextSessionId
SBuf Security::ServerOptions::staticContextSessionId
Definition at line 72 of file ServerOptions.h.
Referenced by operator=().
tlsMinOptions
SBuf Security::PeerOptions::tlsMinOptions private inherited
Library-specific options string generated from tlsMinVersion. Call updateTlsVersionLimits() to regenerate this string.
Definition at line 93 of file PeerOptions.h.
tlsMinVersion
SBuf Security::PeerOptions::tlsMinVersion inherited
Definition at line 88 of file PeerOptions.h.
untrustedSigningCa
Security::KeyData Security::ServerOptions::untrustedSigningCa
Definition at line 88 of file ServerOptions.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
squid/src/security/ServerOptions.h
squid/src/security/ServerOptions.cc