Squid Web Cache: HeaderManglers Class Reference
HeaderManglers Class Reference
A collection of headerMangler objects for a given message kind.
#include <HeaderMangling.h>
Classes
class NoCaseLessThan
Public Member Functions
HeaderManglers ()
~HeaderManglers ()
const headerMangler * find (const HttpHeaderEntry &e) const
returns a header mangler for field e or nil if none was specified
headerMangler * track (const char *name)
returns a mangler for the named header (known or custom)
void setReplacement (const char *name, const char *replacementValue)
updates mangler for the named header with a replacement value
void dumpAccess (StoreEntry *entry, const char *optionName) const
report the *_header_access part of the configuration
void dumpReplacement (StoreEntry *entry, const char *optionName) const
report the *_header_replace part of the configuration
Private Types
typedef std::map< std::string, headerMangler, NoCaseLessThan > ManglersByName
a name:mangler map; optimize: use unordered map or some such
Private Member Functions
HeaderManglers (const HeaderManglers &)
HeaderManglers & operator= (const HeaderManglers &)
Private Attributes
headerMangler known [static_cast< int >(Http::HdrType::enumEnd_)]
one mangler for each known header
ManglersByName custom
one mangler for each custom header
headerMangler all
configured if some mangling ACL applies to all header names
Detailed Description
Definition at line 46 of file HeaderMangling.h.
Member Typedef Documentation
ManglersByName
typedef std::map<std::string, headerMangler, NoCaseLessThan> HeaderManglers::ManglersByName private
Definition at line 78 of file HeaderMangling.h.
Constructor & Destructor Documentation
HeaderManglers() [1/2]
HeaderManglers::HeaderManglers ()
Definition at line 143 of file HeaderMangling.cc.
References all, and known.
~HeaderManglers()
HeaderManglers::~HeaderManglers ()
Definition at line 149 of file HeaderMangling.cc.
References all, custom, header_mangler_clean(), and known.
HeaderManglers() [2/2]
HeaderManglers::HeaderManglers (const HeaderManglers &) private
Member Function Documentation
dumpAccess()
void HeaderManglers::dumpAccess (StoreEntry * entry, const char * optionName) const
Definition at line 161 of file HeaderMangling.cc.
References all, custom, header_mangler_dump_access(), Http::HeaderLookupTable, and known.
Referenced by dump_http_header_access().
dumpReplacement()
void HeaderManglers::dumpReplacement (StoreEntry * entry, const char * optionName) const
Definition at line 173 of file HeaderMangling.cc.
References all, custom, header_mangler_dump_replacement(), Http::HeaderLookupTable, and known.
Referenced by dump_http_header_replace().
find()
const headerMangler * HeaderManglers::find (const HttpHeaderEntry & e) const
Definition at line 215 of file HeaderMangling.cc.
References headerMangler::access_list, all, Http::any_HdrType_enum_value(), SBuf::c_str(), custom, HttpHeaderEntry::id, known, HttpHeaderEntry::name, and Http::OTHER.
Referenced by httpHdrMangle().
operator=()
HeaderManglers & HeaderManglers::operator= (const HeaderManglers &) private
setReplacement()
void HeaderManglers::setReplacement (const char * name, const char * replacementValue)
Definition at line 204 of file HeaderMangling.cc.
References headerMangler::replacement, safe_free, track(), and xstrdup.
Referenced by parse_http_header_replace().
track()
headerMangler * HeaderManglers::track (const char * name)
Definition at line 187 of file HeaderMangling.cc.
References all, Http::BAD_HDR, custom, Http::HeaderLookupTable, Http::HeaderTableRecord::id, known, Http::HeaderLookupTable_t::lookup(), and Http::OTHER.
Referenced by parse_http_header_access(), and setReplacement().
Member Data Documentation
all
headerMangler HeaderManglers::all private
Definition at line 87 of file HeaderMangling.h.
Referenced by HeaderManglers(), ~HeaderManglers(), dumpAccess(), dumpReplacement(), find(), and track().
custom
ManglersByName HeaderManglers::custom private
Definition at line 84 of file HeaderMangling.h.
Referenced by ~HeaderManglers(), dumpAccess(), dumpReplacement(), find(), and track().
known
headerMangler HeaderManglers::known[static_cast< int >(Http::HdrType::enumEnd_)] private
Definition at line 81 of file HeaderMangling.h.
Referenced by HeaderManglers(), ~HeaderManglers(), dumpAccess(), dumpReplacement(), find(), and track().
The documentation for this class was generated from the following files:
squid/src/HeaderMangling.h
squid/src/HeaderMangling.cc