Squid Web Cache: Dns::IpsSelector< Iterator > Class Template Reference
Dns::IpsSelector< Iterator > Class Template Reference
#include <ipcache.h>
Public Member Functions
IpsSelector (const CachedIps &ips)
Iterator cbegin () const noexcept
Iterator cend () const noexcept
Iterator begin () const noexcept
Iterator end () const noexcept
Private Attributes
const CachedIps & ips_
master IP storage we are wrapping
Detailed Description
template<class Iterator>
class Dns::IpsSelector< Iterator >
Makes "which IPs to iterate" decision explicit in range-based for loops. Supported Iterator types are IpsIterator and GoodIpsIterator.
Definition at line 179 of file ipcache.h.
Constructor & Destructor Documentation
IpsSelector()
template<class Iterator > Dns::IpsSelector< Iterator >::IpsSelector (const CachedIps & ips) inline explicit
Definition at line 182 of file ipcache.h.
Member Function Documentation
begin()
template<class Iterator > Iterator Dns::IpsSelector< Iterator >::begin () const inline noexcept
Definition at line 186 of file ipcache.h.
References Dns::IpsSelector< Iterator >::cbegin().
cbegin()
template<class Iterator > Iterator Dns::IpsSelector< Iterator >::cbegin () const inline noexcept
Definition at line 184 of file ipcache.h.
References Dns::CachedIps::goodPosition, Dns::IpsSelector< Iterator >::ips_, and Dns::CachedIps::raw().
Referenced by Dns::IpsSelector< Iterator >::begin().
cend()
template<class Iterator > Iterator Dns::IpsSelector< Iterator >::cend () const inline noexcept
Definition at line 185 of file ipcache.h.
References Dns::IpsSelector< Iterator >::ips_, and Dns::CachedIps::raw().
Referenced by Dns::IpsSelector< Iterator >::end().
end()
template<class Iterator > Iterator Dns::IpsSelector< Iterator >::end () const inline noexcept
Definition at line 187 of file ipcache.h.
References Dns::IpsSelector< Iterator >::cend().
Member Data Documentation
ips_
template<class Iterator > const CachedIps& Dns::IpsSelector< Iterator >::ips_ private
Definition at line 190 of file ipcache.h.
Referenced by Dns::IpsSelector< Iterator >::cbegin(), and Dns::IpsSelector< Iterator >::cend().
The documentation for this class was generated from the following file:
squid/src/ipcache.h