Squid Web Cache: SyslogChannel Class Reference
SyslogChannel Class Reference
syslog DebugChannel
Public Types
using EarlyMessages = std::unique_ptr< CompiledDebugMessages >
Public Member Functions
SyslogChannel ()
void markOpened ()
bool collectingEarlyMessages () const
whether we are still expecting (and buffering) early messages
void stopEarlyMessageCollection ()
end early message buffering, logging any saved messages
EarlyMessages releaseEarlyMessages ()
void log (const DebugMessageHeader &, const CompiledDebugMessageBody &)
Protected Member Functions
bool shouldWrite (const DebugMessageHeader &) const final
void write (const DebugMessageHeader &, const CompiledDebugMessageBody &) final
write the corresponding debugs() message into the channel
void saveMessage (const DebugMessageHeader &, const CompiledDebugMessageBody &)
stores the given early message (if possible) or forgets it (otherwise)
void writeToStream (FILE &, const DebugMessageHeader &, const CompiledDebugMessageBody &)
Formats a validated debugs() record and writes it to the given FILE.
void noteWritten (const DebugMessageHeader &)
reacts to a written a debugs() message
Static Protected Member Functions
static void StopSavingAndLog (DebugChannel &, DebugChannel *=nullptr)
stop saving and log() any "early" messages, in recordNumber order
Protected Attributes
const char *const name = nullptr
unique channel label for debugging
DebugRecordCount written = 0
the number of messages sent to the underlying channel so far
DebugRecordCount lastWrittenRecordNumber = 0
DebugMessageHeader::recordNumber of the last message we wrote.
EarlyMessages earlyMessages
Private Attributes
bool opened = false
whether openlog() was called
Detailed Description
Definition at line 276 of file debug.cc.
Member Typedef Documentation
EarlyMessages
using DebugChannel::EarlyMessages = std::unique_ptr<CompiledDebugMessages> inherited
Definition at line 151 of file debug.cc.
Constructor & Destructor Documentation
SyslogChannel()
SyslogChannel::SyslogChannel () inline
Definition at line 279 of file debug.cc.
Member Function Documentation
collectingEarlyMessages()
bool DebugChannel::collectingEarlyMessages () const inline inherited
Definition at line 160 of file debug.cc.
References DebugChannel::earlyMessages.
Referenced by DebugModule::prepareToDie().
log()
void DebugChannel::log (const DebugMessageHeader & header, const CompiledDebugMessageBody & body) inherited
Write the message to the channel if the channel accepts (such) messages. This writing may be delayed until the channel configuration is settled.
Definition at line 537 of file debug.cc.
References DebugChannel::lastWrittenRecordNumber, DebugMessageHeader::recordNumber, DebugChannel::saveMessage(), DebugChannel::shouldWrite(), DebugChannel::stopEarlyMessageCollection(), and DebugChannel::write().
Referenced by DebugModule::log().
markOpened()
void SyslogChannel::markOpened () inline
Definition at line 281 of file debug.cc.
References opened.
Referenced by Debug::SettleSyslog().
noteWritten()
void DebugChannel::noteWritten (const DebugMessageHeader & header) protected inherited
Definition at line 623 of file debug.cc.
References DebugChannel::lastWrittenRecordNumber, DebugMessageHeader::recordNumber, and DebugChannel::written.
Referenced by DebugChannel::writeToStream().
releaseEarlyMessages()
EarlyMessages DebugChannel::releaseEarlyMessages () inline inherited
end early message buffering, without logging any saved messages
Returns
(a possibly empty container with) saved messages or nil
Definition at line 167 of file debug.cc.
References DebugChannel::earlyMessages.
Referenced by DebugChannel::StopSavingAndLog().
saveMessage()
void DebugChannel::saveMessage (const DebugMessageHeader & header, const CompiledDebugMessageBody & body) protected inherited
Definition at line 594 of file debug.cc.
References assert, DebugChannel::earlyMessages, EarlyMessagesLevel, and DebugMessageHeader::level.
Referenced by DebugChannel::log().
shouldWrite()
bool SyslogChannel::shouldWrite (const DebugMessageHeader &) const final protected virtual
whether we should write() the corresponding debugs() message now (assumes some higher-level code applied cache.log section/level filter)
Implements DebugChannel.
Definition at line 1073 of file debug.cc.
References assert, DBG_IMPORTANT, DebugMessageHeader::forceAlert, DebugMessageHeader::level, Debug::log_syslog, and opened.
stopEarlyMessageCollection()
void DebugChannel::stopEarlyMessageCollection () inherited
Definition at line 529 of file debug.cc.
References DebugChannel::earlyMessages, and DebugChannel::StopSavingAndLog().
Referenced by DebugChannel::log(), DebugModule::prepareToDie(), Debug::SettleStderr(), Debug::SettleSyslog(), Debug::StopCacheLogUse(), and DebugModule::useCacheLog().
StopSavingAndLog()
void DebugChannel::StopSavingAndLog (DebugChannel & channelA, DebugChannel * channelBOrNil = nullptr) static protected inherited
Definition at line 569 of file debug.cc.
References assert, debugs, CompiledDebugMessage::header, DebugChannel::name, DebugMessageHeader::recordNumber, DebugChannel::releaseEarlyMessages(), and DebugChannel::written.
Referenced by DebugChannel::stopEarlyMessageCollection(), and StderrChannel::takeOver().
write()
void SyslogChannel::write (const DebugMessageHeader & , const CompiledDebugMessageBody &) final protected virtual
Implements DebugChannel.
Definition at line 1065 of file debug.cc.
References assert.
writeToStream()
void DebugChannel::writeToStream (FILE & destination, const DebugMessageHeader & header, const CompiledDebugMessageBody & body) protected inherited
Definition at line 613 of file debug.cc.
References debugLogTime(), DebugChannel::noteWritten(), ProcessLabel, and DebugMessageHeader::timestamp.
Referenced by CacheLogChannel::write(), and StderrChannel::write().
Member Data Documentation
earlyMessages
EarlyMessages DebugChannel::earlyMessages protected inherited
debugs() messages waiting for the channel configuration to settle (and the channel to open) so that their eligibility for logging can be determined (and the messages can be actually written somewhere)
Definition at line 235 of file debug.cc.
Referenced by DebugChannel::collectingEarlyMessages(), DebugChannel::releaseEarlyMessages(), DebugChannel::saveMessage(), and DebugChannel::stopEarlyMessageCollection().
lastWrittenRecordNumber
DebugRecordCount DebugChannel::lastWrittenRecordNumber = 0 protected inherited
Definition at line 230 of file debug.cc.
Referenced by DebugChannel::log(), and DebugChannel::noteWritten().
name
const char* const DebugChannel::name = nullptr protected inherited
Definition at line 224 of file debug.cc.
Referenced by DebugChannel::StopSavingAndLog().
opened
bool SyslogChannel::opened = false private
Definition at line 289 of file debug.cc.
Referenced by markOpened(), and shouldWrite().
written
DebugRecordCount DebugChannel::written = 0 protected inherited
Definition at line 227 of file debug.cc.
Referenced by DebugChannel::noteWritten(), and DebugChannel::StopSavingAndLog().
The documentation for this class was generated from the following file:
squid/src/debug/debug.cc