Squid Web Cache: ACLAtStepData Class Reference
ACLAtStepData Class Reference
#include <AtStepData.h>
Public Member Functions
ACLAtStepData ()
~ACLAtStepData () override
bool match (XactionStep) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Public Attributes
std::list< XactionStep > values
Private Member Functions
MEMPROXY_CLASS (ACLAtStepData)
Detailed Description
Definition at line 17 of file AtStepData.h.
Constructor & Destructor Documentation
ACLAtStepData()
ACLAtStepData::ACLAtStepData ()
Definition at line 52 of file AtStepData.cc.
~ACLAtStepData()
ACLAtStepData::~ACLAtStepData () override
Definition at line 55 of file AtStepData.cc.
Member Function Documentation
dump()
SBufList ACLAtStepData::dump () const override virtual
Implements ACLData< XactionStep >.
Definition at line 67 of file AtStepData.cc.
References StepName(), and values.
empty()
bool ACLAtStepData::empty () const override virtual
Implements ACLData< XactionStep >.
Definition at line 87 of file AtStepData.cc.
References values.
lineOptions()
virtual const Acl::Options & ACLData< XactionStep >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLAtStepData::match (XactionStep toFind) override virtual
Implements ACLData< XactionStep >.
Definition at line 60 of file AtStepData.cc.
References values.
MEMPROXY_CLASS()
ACLAtStepData::MEMPROXY_CLASS (ACLAtStepData) private
parse()
void ACLAtStepData::parse () override virtual
Implements ACLData< XactionStep >.
Definition at line 76 of file AtStepData.cc.
References Here, StepValue(), ConfigParser::strtokFile(), ToSBuf(), unknown, and values.
prepareForUse()
virtual void ACLData< XactionStep >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
values
std::list<XactionStep> ACLAtStepData::values
Definition at line 29 of file AtStepData.h.
Referenced by dump(), empty(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/AtStepData.h
squid/src/acl/AtStepData.cc