Squid Web Cache: Ssl::Helper Class Reference
Ssl::Helper Class Reference
#include <helper.h>
Static Public Member Functions
static void Init ()
Init helper structure.
static void Shutdown ()
Shutdown helper structure.
static void Reconfigure ()
static void Submit (CrtdMessage const &message, HLPCB *callback, void *data)
Submit crtd message to external crtd server.
Static Private Attributes
::Helper::ClientPointer ssl_crtd
helper for management of ssl_crtd.
Detailed Description
Set of thread for ssl_crtd. This class is singleton. This class use helper structure for threads management.
Definition at line 28 of file helper.h.
Member Function Documentation
Init()
void Ssl::Helper::Init () static
Definition at line 81 of file helper.cc.
References assert, HttpPortList, IPC_STREAM, Helper::Client::Make(), safe_free, ssl_crtd, strwordtok(), Ssl::TheConfig, wordlistAdd(), and xstrdup.
Referenced by mainInitialize().
Reconfigure()
void Ssl::Helper::Reconfigure () static
Reconfigure helper structure.
Definition at line 122 of file helper.cc.
Referenced by mainReconfigureFinish().
Shutdown()
void Ssl::Helper::Shutdown () static
Definition at line 112 of file helper.cc.
References helperShutdown(), and wordlistDestroy().
Referenced by SquidShutdown().
Submit()
void Ssl::Helper::Submit (CrtdMessage const & message, HLPCB * callback, void * data) static
Definition at line 128 of file helper.cc.
References NotePairs::add(), SBuf::append(), Helper::BrokenHelper, SBuf::c_str(), Ssl::CrtdMessage::compose(), debugs, Ssl::GeneratorRequest::emplace(), SBuf::find(), Ssl::HandleGeneratorReply(), Helper::Reply::notes, Ssl::GeneratorRequest::query, and Ssl::TheGeneratorRequests().
Referenced by ConnStateData::getSslContextStart().
Member Data Documentation
ssl_crtd
Helper::Client::Pointer Ssl::Helper::ssl_crtd static private
Definition at line 37 of file helper.h.
Referenced by Init().
The documentation for this class was generated from the following files:
squid/src/ssl/helper.h
squid/src/ssl/helper.cc