Squid Web Cache: CollapsedForwarding Class Reference
CollapsedForwarding Class Reference
Sends and handles collapsed forwarding notifications.
#include <CollapsedForwarding.h>
Static Public Member Functions
static void Init ()
open shared memory segment
static void Broadcast (const StoreEntry &e, const bool includingThisWorker=false)
notify other workers about changes in entry state (e.g., new data)
static void Broadcast (const sfileno index, const bool includingThisWorker)
static void Notify (const int workerId)
kick worker with empty IPC queue
static void HandleNewData (const char *const when)
handle new data messages in IPC queue
static void HandleNotification (const Ipc::TypedMsgHdr &msg)
handle queue push notifications from worker or disker
static void StatQueue (std::ostream &)
prints IPC message queue state; suitable for cache manager reports
Private Types
typedef Ipc::MultiQueue Queue
Static Private Member Functions
static void HandleNewDataAtStart ()
Static Private Attributes
static std::unique_ptr< Queue > queue
IPC queue.
Detailed Description
Definition at line 23 of file CollapsedForwarding.h.
Member Typedef Documentation
Queue
typedef Ipc::MultiQueue CollapsedForwarding::Queue private
Definition at line 51 of file CollapsedForwarding.h.
Member Function Documentation
Broadcast() [1/2]
void CollapsedForwarding::Broadcast (const sfileno index, const bool includingThisWorker) static
notify other workers about state changes in Transient entry at the given xitTable.index use Broadcast(StoreEntry) variant if you have a StoreEntry object
Definition at line 83 of file CollapsedForwarding.cc.
References Config, DBG_IMPORTANT, debugs, KidIdentifier, Notify(), queue, CollapsedForwardingMsg::sender, SquidConfig::workers, and CollapsedForwardingMsg::xitIndex.
Broadcast() [2/2]
void CollapsedForwarding::Broadcast (const StoreEntry & e, const bool includingThisWorker = false) static
Definition at line 70 of file CollapsedForwarding.cc.
References Broadcast(), debugs, StoreEntry::hasTransients(), MemObject::XitTable::index, StoreEntry::mem_obj, Store::Root(), Store::Controller::transientReaders(), and MemObject::xitTable.
Referenced by Broadcast(), Transients::completeWriting(), MemStore::completeWriting(), Transients::disconnect(), MemStore::disconnect(), Rock::SwapDir::disconnect(), Rock::SwapDir::evictCached(), MemStore::evictCached(), Transients::evictCached(), Transients::evictIfFound(), Rock::IoState::finishedWriting(), MemStore::write(), Rock::SwapDir::writeCompleted(), and Rock::SwapDir::writeError().
HandleNewData()
void CollapsedForwarding::HandleNewData (const char *const when) static
Definition at line 121 of file CollapsedForwarding.cc.
References assert, DBG_IMPORTANT, debugs, queue, Store::Root(), CollapsedForwardingMsg::sender, SQUID_MAXFD, Store::Controller::syncCollapsed(), and CollapsedForwardingMsg::xitIndex.
Referenced by HandleNewDataAtStart(), and HandleNotification().
HandleNewDataAtStart()
void CollapsedForwarding::HandleNewDataAtStart () static private
Handle queued IPC messages for the first time in this process lifetime, when the queue may be reflecting the state of our killed predecessor.
See also
IpcIoFile::HandleMessagesAtStart() – duplicates this logic
Definition at line 157 of file CollapsedForwarding.cc.
References HandleNewData(), and queue.
Referenced by Init().
HandleNotification()
void CollapsedForwarding::HandleNotification (const Ipc::TypedMsgHdr & msg) static
Definition at line 145 of file CollapsedForwarding.cc.
References assert, debugs, Ipc::TypedMsgHdr::getInt(), HandleNewData(), and queue.
Referenced by Ipc::Strand::receive().
Init()
void CollapsedForwarding::Init () static
Definition at line 58 of file CollapsedForwarding.cc.
References asyncCall(), HandleNewDataAtStart(), IamWorkerProcess(), KidIdentifier, Must, queue, ScheduleCallHere, ShmLabel, and UsingSmp().
Referenced by CollapsedForwardingRr::open().
Notify()
void CollapsedForwarding::Notify (const int workerId) static
Definition at line 109 of file CollapsedForwarding.cc.
References debugs, KidIdentifier, Ipc::Port::MakeAddr(), Ipc::mtCollapsedForwardingNotification, Ipc::TypedMsgHdr::putInt(), Ipc::SendMessage(), Ipc::TypedMsgHdr::setType(), and Ipc::strandAddrLabel.
Referenced by Broadcast().
StatQueue()
void CollapsedForwarding::StatQueue (std::ostream & os) static
Definition at line 165 of file CollapsedForwarding.cc.
References queue.
Referenced by StatQueues().
Member Data Documentation
queue
std::unique_ptr< CollapsedForwarding::Queue > CollapsedForwarding::queue static private
Definition at line 52 of file CollapsedForwarding.h.
Referenced by Broadcast(), HandleNewData(), HandleNewDataAtStart(), HandleNotification(), Init(), and StatQueue().
The documentation for this class was generated from the following files:
squid/src/CollapsedForwarding.h
squid/src/CollapsedForwarding.cc