Squid Web Cache: ICPState Class Reference
ICPState Class Reference
#include <ICP.h>
Public Member Functions
ICPState (icp_common_t &aHeader, HttpRequest *aRequest)
~ICPState () override
bool isHit () const
whether the cache contains the requested entry
Public Attributes
icp_common_t header
HttpRequest * request
int fd
Ip::Address from
char * url
AccessLogEntryPointer al
Protected Member Functions
LogTags * loggingTags () const override
void fillChecklist (ACLFilledChecklist &) const override
configure the given checklist (to reflect the current transaction state)
bool confirmAndPrepHit (const StoreEntry &) const
either confirms and starts processing a cache hit or returns false
bool startCollapsingOn (const StoreEntry &, const bool doingRevalidation) const
bool mayInitiateCollapsing () const
whether Squid configuration allows us to become a CF initiator
bool onCollapsingPath () const
whether Squid configuration allows collapsing for this transaction
Protected Attributes
bool didCollapse = false
whether startCollapsingOn() was called and returned true
Detailed Description
Definition at line 61 of file ICP.h.
Constructor & Destructor Documentation
ICPState()
ICPState::ICPState (icp_common_t & aHeader, HttpRequest * aRequest)
Definition at line 139 of file icp_v2.cc.
References HTTPMSGLOCK(), and request.
~ICPState()
ICPState::~ICPState () override
Definition at line 148 of file icp_v2.cc.
References HTTPMSGUNLOCK(), request, safe_free, and url.
Member Function Documentation
confirmAndPrepHit()
bool ICPState::confirmAndPrepHit (const StoreEntry & e) const protected
Definition at line 168 of file icp_v2.cc.
References Config, StoreClient::didCollapse, StoreEntry::hittingRequiresCollapsing(), SquidConfig::icp_hit_stale, SquidConfig::onoff, refreshCheckICP(), request, StoreClient::startCollapsingOn(), and StoreEntry::validToSend().
Referenced by isHit().
fillChecklist()
void ICPState::fillChecklist (ACLFilledChecklist &) const override protected virtual
Implements Acl::ChecklistFiller.
Definition at line 192 of file icp_v2.cc.
References ACLFilledChecklist::al, al, from, icpSyncAle(), request, ACLFilledChecklist::setRequest(), and url.
isHit()
bool ICPState::isHit () const
Definition at line 155 of file icp_v2.cc.
References confirmAndPrepHit(), Http::METHOD_GET, storeGetPublic(), and url.
Referenced by doV2Query(), and doV3Query().
loggingTags()
LogTags * ICPState::loggingTags () const override protected virtual
Returns
LogTags (if the class logs transactions) or nil (otherwise)
Implements StoreClient.
Definition at line 183 of file icp_v2.cc.
References al, AccessLogEntry::cache, and AccessLogEntry::CacheDetails::code.
mayInitiateCollapsing()
bool StoreClient::mayInitiateCollapsing () const inline protected inherited
Definition at line 59 of file StoreClient.h.
References StoreClient::onCollapsingPath().
Referenced by clientReplyContext::createStoreEntry(), and clientReplyContext::processExpired().
onCollapsingPath()
bool StoreClient::onCollapsingPath () const protected inherited
Definition at line 52 of file store_client.cc.
References SquidConfig::accessList, Acl::Answer::allowed(), SquidConfig::collapsed_forwarding, SquidConfig::collapsedForwardingAccess, Config, ACLChecklist::fastCheck(), Acl::ChecklistFiller::fillChecklist(), and SquidConfig::onoff.
Referenced by StoreClient::mayInitiateCollapsing(), and StoreClient::startCollapsingOn().
startCollapsingOn()
bool StoreClient::startCollapsingOn (const StoreEntry & e, const bool doingRevalidation) const protected inherited
Returns
whether the caller must collapse on the given entry Before returning true, updates common collapsing-related stats. See also: StoreEntry::hittingRequiresCollapsing().
Definition at line 66 of file store_client.cc.
References debugs, StoreClient::didCollapse, StoreEntry::hittingRequiresCollapsing(), StoreClient::loggingTags(), and StoreClient::onCollapsingPath().
Referenced by htcpSpecifier::checkHit(), confirmAndPrepHit(), clientReplyContext::identifyFoundObject(), clientReplyContext::processExpired(), and UrnState::start().
Member Data Documentation
al
AccessLogEntryPointer ICPState::al mutable
Definition at line 77 of file ICP.h.
Referenced by doV2Query(), doV3Query(), fillChecklist(), and loggingTags().
didCollapse
bool StoreClient::didCollapse = false mutable protected inherited
Definition at line 64 of file StoreClient.h.
Referenced by clientReplyContext::cacheHit(), htcpSpecifier::checkHit(), confirmAndPrepHit(), and StoreClient::startCollapsingOn().
fd
int ICPState::fd
Definition at line 73 of file ICP.h.
Referenced by doV2Query(), and doV3Query().
from
Ip::Address ICPState::from
Definition at line 75 of file ICP.h.
Referenced by doV2Query(), doV3Query(), and fillChecklist().
header
icp_common_t ICPState::header
Definition at line 71 of file ICP.h.
request
HttpRequest* ICPState::request
Definition at line 72 of file ICP.h.
Referenced by ICPState(), ~ICPState(), confirmAndPrepHit(), doV2Query(), and fillChecklist().
url
char* ICPState::url
Definition at line 76 of file ICP.h.
Referenced by ~ICPState(), doV2Query(), doV3Query(), fillChecklist(), and isHit().
The documentation for this class was generated from the following files:
squid/src/ICP.h
squid/src/icp_v2.cc