Squid Web Cache: Ipc::Mem::Owner< Class > Class Template Reference
Ipc::Mem::Owner< Class > Class Template Reference
#include <Pointer.h>
Public Member Functions
~Owner ()
Class * object ()
Raw access; handy to finalize initiatization, but avoid if possible.
template<class P1 >
Owner< Class > * New (const char *const id, const P1 &p1)
template<class P1 , class P2 >
Owner< Class > * New (const char *const id, const P1 &p1, const P2 &p2)
template<class P1 , class P2 , class P3 >
Owner< Class > * New (const char *const id, const P1 &p1, const P2 &p2, const P3 &p3)
template<class P1 , class P2 , class P3 , class P4 >
Owner< Class > * New (const char *const id, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4)
Static Public Member Functions
static Owner * New (const char *const id)
template<class P1 >
static Owner * New (const char *const id, const P1 &p1)
template<class P1 , class P2 >
static Owner * New (const char *const id, const P1 &p1, const P2 &p2)
template<class P1 , class P2 , class P3 >
static Owner * New (const char *const id, const P1 &p1, const P2 &p2, const P3 &p3)
template<class P1 , class P2 , class P3 , class P4 >
static Owner * New (const char *const id, const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4)
static Owner * Old (const char *const id)
attaches to the existing shared memory segment, becoming its owner
Private Member Functions
Owner (const char *const id)
Owner (const char *const id, const off_t sharedSize)
Owner (const Owner &)
Owner & operator= (const Owner &)
Private Attributes
Segment theSegment
shared memory segment that holds the object
Class * theObject
shared object
Detailed Description
template<class Class>
class Ipc::Mem::Owner< Class >
allocates/deallocates shared memory; creates and later destroys a Class object using that memory
Definition at line 25 of file Pointer.h.
Constructor & Destructor Documentation
~Owner()
template<class Class > Ipc::Mem::Owner< Class >::~Owner ()
Definition at line 115 of file Pointer.h.
Owner() [1/3]
template<class Class > Ipc::Mem::Owner< Class >::Owner (const char *const id) explicit private
Definition at line 107 of file Pointer.h.
References Ipc::Mem::Segment::mem(), Must, Ipc::Mem::Segment::open(), and Ipc::Mem::Owner< Class >::theSegment.
Owner() [2/3]
template<class Class > Ipc::Mem::Owner< Class >::Owner (const char *const id, const off_t sharedSize) private
Definition at line 99 of file Pointer.h.
References Ipc::Mem::Segment::create(), Ipc::Mem::Segment::mem(), Must, and Ipc::Mem::Owner< Class >::theSegment.
Owner() [3/3]
template<class Class > Ipc::Mem::Owner< Class >::Owner (const Owner< Class > &) private
Member Function Documentation
New() [1/9]
template<class Class > Owner< Class > * Ipc::Mem::Owner< Class >::New (const char *const id) static
Definition at line 133 of file Pointer.h.
References Ipc::Mem::Segment::reserve(), Ipc::Mem::Owner< Class >::theObject, and Ipc::Mem::Owner< Class >::theSegment.
New() [2/9]
template<class Class > template<class P1 > static Owner * Ipc::Mem::Owner< Class >::New (const char *const id, const P1 & p1) static
New() [3/9]
template<class Class > template<class P1 > Owner< Class > * Ipc::Mem::Owner< Class >::New (const char *const id, const P1 & p1)
Definition at line 143 of file Pointer.h.
References Ipc::Mem::Segment::reserve(), Ipc::Mem::Owner< Class >::theObject, and Ipc::Mem::Owner< Class >::theSegment.
New() [4/9]
template<class Class > template<class P1 , class P2 > static Owner * Ipc::Mem::Owner< Class >::New (const char *const id, const P1 & p1, const P2 & p2) static
New() [5/9]
template<class Class > template<class P1 , class P2 > Owner< Class > * Ipc::Mem::Owner< Class >::New (const char *const id, const P1 & p1, const P2 & p2)
Definition at line 153 of file Pointer.h.
References Ipc::Mem::Segment::reserve(), Ipc::Mem::Owner< Class >::theObject, and Ipc::Mem::Owner< Class >::theSegment.
New() [6/9]
template<class Class > template<class P1 , class P2 , class P3 > static Owner * Ipc::Mem::Owner< Class >::New (const char *const id, const P1 & p1, const P2 & p2, const P3 & p3) static
New() [7/9]
template<class Class > template<class P1 , class P2 , class P3 > Owner< Class > * Ipc::Mem::Owner< Class >::New (const char *const id, const P1 & p1, const P2 & p2, const P3 & p3)
Definition at line 163 of file Pointer.h.
References Ipc::Mem::Segment::reserve(), Ipc::Mem::Owner< Class >::theObject, and Ipc::Mem::Owner< Class >::theSegment.
New() [8/9]
template<class Class > template<class P1 , class P2 , class P3 , class P4 > static Owner * Ipc::Mem::Owner< Class >::New (const char *const id, const P1 & p1, const P2 & p2, const P3 & p3, const P4 & p4) static
New() [9/9]
template<class Class > template<class P1 , class P2 , class P3 , class P4 > Owner< Class > * Ipc::Mem::Owner< Class >::New (const char *const id, const P1 & p1, const P2 & p2, const P3 & p3, const P4 & p4)
Definition at line 173 of file Pointer.h.
References Ipc::Mem::Segment::reserve(), Ipc::Mem::Owner< Class >::theObject, and Ipc::Mem::Owner< Class >::theSegment.
object()
template<class Class > Class * Ipc::Mem::Owner< Class >::object () inline
Definition at line 43 of file Pointer.h.
References Ipc::Mem::Owner< Class >::theObject.
Referenced by Rock::LoadingParts::flags(), Rock::LoadingParts::mores(), Rock::LoadingParts::sizes(), and Rock::LoadingParts::versions().
Old()
template<class Class > Owner< Class > * Ipc::Mem::Owner< Class >::Old (const char *const id) static
Definition at line 123 of file Pointer.h.
References Must.
Referenced by createOwner().
operator=()
template<class Class > Owner & Ipc::Mem::Owner< Class >::operator= (const Owner< Class > &) private
Member Data Documentation
theObject
template<class Class > Class* Ipc::Mem::Owner< Class >::theObject private
Definition at line 54 of file Pointer.h.
Referenced by Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), and Ipc::Mem::Owner< Class >::object().
theSegment
template<class Class > Segment Ipc::Mem::Owner< Class >::theSegment private
Definition at line 53 of file Pointer.h.
Referenced by Ipc::Mem::Owner< Class >::Owner(), Ipc::Mem::Owner< Class >::Owner(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), and Ipc::Mem::Owner< Class >::New().
The documentation for this class was generated from the following file:
squid/src/ipc/mem/Pointer.h