Squid Web Cache: Configuration::Component< T > Class Template Reference
Configuration::Component< T > Class Template Reference
#include <ConfigOption.h>
Public Member Functions
Security::KeyLog * Parse (ConfigParser &parser)
void Print (std::ostream &os, Security::KeyLog *const &keyLog)
void Free (Security::KeyLog *const keyLog)
Static Public Member Functions
static T Parse (ConfigParser &)
creates a new T instance using the given parser; never returns nil
static void Print (std::ostream &, const T &)
reports the current T instance configuration in squid.conf format
static void Free (T)
destroys Parse() result
Detailed Description
template<class T>
class Configuration::Component< T >
Interface for basic/low-level manipulation of a squid.conf directive value. Hides T's declarations from squid.conf parsing/reconfiguring/reporting code.
Implementations/specializations must not modify the current configuration (i.e. the Config objects and similar/related global state). To facilitate reuse, implementations/specializations should also be independent from any specific configuration directive name and its squid.conf location.
TODO: Support multi-directive components of various kinds.
Definition at line 30 of file ConfigOption.h.
Member Function Documentation
Free() [1/2]
void Configuration::Component< Security::KeyLog * >::Free (Security::KeyLog *const keyLog)
Definition at line 114 of file KeyLog.cc.
Free() [2/2]
template<class T > static void Configuration::Component< T >::Free (T) static
Referenced by FreeDirective().
Parse() [1/2]
template<class T > static T Configuration::Component< T >::Parse (ConfigParser &) static
Referenced by ParseDirective().
Parse() [2/2]
Security::KeyLog * Configuration::Component< Security::KeyLog * >::Parse (ConfigParser & parser)
Definition at line 99 of file KeyLog.cc.
Print() [1/2]
template<class T > static void Configuration::Component< T >::Print (std::ostream & , const T &) static
Referenced by DumpDirective().
Print() [2/2]
void Configuration::Component< Security::KeyLog * >::Print (std::ostream & os, Security::KeyLog *const & keyLog)
Definition at line 106 of file KeyLog.cc.
References assert, and Security::KeyLog::dump().
The documentation for this class was generated from the following file:
squid/src/ConfigOption.h