Squid Web Cache: TestEventLoop Class Reference
TestEventLoop Class Reference
Protected Member Functions
void testCreate ()
void testRunOnce ()
void testEngineTimeout ()
void testEngineErrors ()
void testSetTimeService ()
void testSetPrimaryEngine ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestEventLoop)
CPPUNIT_TEST (testCreate)
CPPUNIT_TEST (testRunOnce)
CPPUNIT_TEST (testEngineTimeout)
CPPUNIT_TEST (testEngineErrors)
CPPUNIT_TEST (testSetTimeService)
CPPUNIT_TEST (testSetPrimaryEngine)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 22 of file testEventLoop.cc.
Member Function Documentation
CPPUNIT_TEST() [1/6]
TestEventLoop::CPPUNIT_TEST (testCreate) private
CPPUNIT_TEST() [2/6]
TestEventLoop::CPPUNIT_TEST (testEngineErrors) private
CPPUNIT_TEST() [3/6]
TestEventLoop::CPPUNIT_TEST (testEngineTimeout) private
CPPUNIT_TEST() [4/6]
TestEventLoop::CPPUNIT_TEST (testRunOnce) private
CPPUNIT_TEST() [5/6]
TestEventLoop::CPPUNIT_TEST (testSetPrimaryEngine) private
CPPUNIT_TEST() [6/6]
TestEventLoop::CPPUNIT_TEST (testSetTimeService) private
CPPUNIT_TEST_SUITE()
TestEventLoop::CPPUNIT_TEST_SUITE (TestEventLoop) private
CPPUNIT_TEST_SUITE_END()
TestEventLoop::CPPUNIT_TEST_SUITE_END () private
testCreate()
void TestEventLoop::testCreate () protected
Definition at line 49 of file testEventLoop.cc.
testEngineErrors()
void TestEventLoop::testEngineErrors () protected
Definition at line 139 of file testEventLoop.cc.
References RecordingEngine::calls, EventLoop::errcount, AsyncEngine::EVENT_ERROR, EventLoop::registerEngine(), EventLoop::run(), and EventLoop::runOnce().
testEngineTimeout()
void TestEventLoop::testEngineTimeout () protected
Definition at line 120 of file testEventLoop.cc.
References RecordingEngine::calls, RecordingEngine::lasttimeout, EventLoop::registerEngine(), and EventLoop::runOnce().
testRunOnce()
void TestEventLoop::testRunOnce () protected
Definition at line 74 of file testEventLoop.cc.
References RecordingEngine::calls, AsyncEngine::EVENT_IDLE, EVENT_LOOP_TIMEOUT, RecordingEngine::lasttimeout, EventLoop::registerEngine(), EventLoop::run(), and EventLoop::runOnce().
testSetPrimaryEngine()
void TestEventLoop::testSetPrimaryEngine () protected
Definition at line 188 of file testEventLoop.cc.
References EVENT_LOOP_TIMEOUT, RecordingEngine::lasttimeout, EventLoop::registerEngine(), EventLoop::runOnce(), and EventLoop::setPrimaryEngine().
testSetTimeService()
void TestEventLoop::testSetTimeService () protected
Definition at line 168 of file testEventLoop.cc.
References StubTime::calls, EventLoop::runOnce(), and EventLoop::setTimeService().
The documentation for this class was generated from the following file:
squid/src/tests/testEventLoop.cc