Squid Web Cache: Fs::Ufs::UFSSwapLogParser Class Reference
Fs::Ufs::UFSSwapLogParser Class Reference abstract
Storage Filesystems » UFS Storage Filesystem
#include <UFSSwapLogParser.h>
Public Member Functions
UFSSwapLogParser (FILE *fp)
virtual ~UFSSwapLogParser ()
virtual bool ReadRecord (StoreSwapLogData &swapData)=0
int SwapLogEntries ()
void Close ()
Static Public Member Functions
static UFSSwapLogParser * GetUFSSwapLogParser (FILE *fp)
Public Attributes
FILE * log
int log_entries
int record_size
Detailed Description
Definition at line 19 of file UFSSwapLogParser.h.
Constructor & Destructor Documentation
UFSSwapLogParser()
Fs::Ufs::UFSSwapLogParser::UFSSwapLogParser (FILE * fp) inline
Definition at line 26 of file UFSSwapLogParser.h.
~UFSSwapLogParser()
virtual Fs::Ufs::UFSSwapLogParser::~UFSSwapLogParser () inline virtual
Definition at line 28 of file UFSSwapLogParser.h.
Member Function Documentation
Close()
void Fs::Ufs::UFSSwapLogParser::Close () inline
Definition at line 34 of file UFSSwapLogParser.h.
References log.
GetUFSSwapLogParser()
Fs::Ufs::UFSSwapLogParser * Fs::Ufs::UFSSwapLogParser::GetUFSSwapLogParser (FILE * fp) static
Definition at line 81 of file UFSSwapLogParser.cc.
References assert, DBG_IMPORTANT, debugs, StoreSwapLogHeader::op, StoreSwapLogHeader::record_size, StoreSwapLogHeader::sane(), SWAP_LOG_VERSION, and StoreSwapLogHeader::version.
Referenced by Fs::Ufs::RebuildState::RebuildState().
ReadRecord()
virtual bool Fs::Ufs::UFSSwapLogParser::ReadRecord (StoreSwapLogData & swapData) pure virtual
Implemented in UFSSwapLogParser_v1_32bs, and UFSSwapLogParser_v2.
SwapLogEntries()
int Fs::Ufs::UFSSwapLogParser::SwapLogEntries ()
Definition at line 129 of file UFSSwapLogParser.cc.
References log().
Member Data Documentation
log
FILE* Fs::Ufs::UFSSwapLogParser::log
Definition at line 22 of file UFSSwapLogParser.h.
Referenced by Close(), UFSSwapLogParser_v1_32bs::ReadRecord(), and UFSSwapLogParser_v2::ReadRecord().
log_entries
int Fs::Ufs::UFSSwapLogParser::log_entries
Definition at line 23 of file UFSSwapLogParser.h.
record_size
int Fs::Ufs::UFSSwapLogParser::record_size
Definition at line 24 of file UFSSwapLogParser.h.
Referenced by UFSSwapLogParser_v1_32bs::UFSSwapLogParser_v1_32bs(), and UFSSwapLogParser_v2::UFSSwapLogParser_v2().
The documentation for this class was generated from the following files:
squid/src/fs/ufs/UFSSwapLogParser.h
squid/src/fs/ufs/UFSSwapLogParser.cc