Squid Web Cache: MessageDelayConfig Class Reference
MessageDelayConfig Class Reference
represents configuration for response delay pools
#include <MessageDelayPools.h>
Public Member Functions
void parseResponseDelayPool ()
void dumpResponseDelayPoolParameters (StoreEntry *)
void parseResponseDelayPoolAccess ()
void freePools ()
Detailed Description
Definition at line 97 of file MessageDelayPools.h.
Member Function Documentation
dumpResponseDelayPoolParameters()
void MessageDelayConfig::dumpResponseDelayPoolParameters (StoreEntry * entry)
Definition at line 197 of file MessageDelayPools.cc.
References MessageDelayPools::Instance(), and MessageDelayPools::pools.
Referenced by dump_response_delay_pool_parameters().
freePools()
void MessageDelayConfig::freePools ()
Definition at line 191 of file MessageDelayPools.cc.
References MessageDelayPools::freePools(), and MessageDelayPools::Instance().
Referenced by free_response_delay_pool_parameters().
parseResponseDelayPool()
void MessageDelayConfig::parseResponseDelayPool ()
Definition at line 116 of file MessageDelayPools.cc.
References MessageDelayPools::add(), DBG_CRITICAL, debugs, MessageDelayPools::Instance(), SBuf::isEmpty(), ConfigParser::NextKvPair(), ConfigParser::NextToken(), self_destruct(), xatoll(), and xatos().
Referenced by parse_response_delay_pool_parameters().
parseResponseDelayPoolAccess()
void MessageDelayConfig::parseResponseDelayPoolAccess ()
Definition at line 178 of file MessageDelayPools.cc.
References MessageDelayPool::access, aclParseAccessLine(), DBG_CRITICAL, debugs, MessageDelayPools::Instance(), ConfigParser::NextToken(), and MessageDelayPools::pool().
Referenced by parse_response_delay_pool_access().
The documentation for this class was generated from the following files:
squid/src/MessageDelayPools.h
squid/src/MessageDelayPools.cc