Squid Web Cache: BodyConsumerDialer Class Reference
BodyConsumerDialer Class Reference
Public Types
typedef UnaryMemFunT< BodyConsumer, BodyPipe::Pointer > Parent
typedef void(Job::* Method) (BodyPipe::Pointer)
typedef Job DestClass
typedef CbcPointer< Job > JobPointer
Public Member Functions
BodyConsumerDialer (const BodyConsumer::Pointer &aConsumer, Parent::Method aHandler, BodyPipe::Pointer bp)
bool canDial (AsyncCall &call) override
void print (std::ostream &os) const override
void dial (AsyncCall &call)
Public Attributes
Method method
BodyPipe::Pointer arg1
JobPointer job
Protected Member Functions
void doDial () override
Detailed Description
Definition at line 60 of file BodyPipe.cc.
Member Typedef Documentation
DestClass
template<class Job > typedef Job JobDialer< Job >::DestClass inherited
Definition at line 29 of file AsyncJobCalls.h.
JobPointer
template<class Job > typedef CbcPointer<Job> JobDialer< Job >::JobPointer inherited
Definition at line 30 of file AsyncJobCalls.h.
Method
typedef void(Job::* UnaryMemFunT< BodyConsumer , BodyPipe::Pointer , BodyPipe::Pointer >::Method) (BodyPipe::Pointer) inherited
Definition at line 111 of file AsyncJobCalls.h.
Parent
typedef UnaryMemFunT<BodyConsumer, BodyPipe::Pointer> BodyConsumerDialer::Parent
Definition at line 63 of file BodyPipe.cc.
Constructor & Destructor Documentation
BodyConsumerDialer()
BodyConsumerDialer::BodyConsumerDialer (const BodyConsumer::Pointer & aConsumer, Parent::Method aHandler, BodyPipe::Pointer bp) inline
Definition at line 65 of file BodyPipe.cc.
Member Function Documentation
canDial()
bool BodyConsumerDialer::canDial (AsyncCall & call) override virtual
Reimplemented from JobDialer< Job >.
Definition at line 89 of file BodyPipe.cc.
References UnaryMemFunT< BodyConsumer, BodyPipe::Pointer >::arg1, AsyncCall::cancel(), JobDialer< Job >::canDial(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, JobDialer< Job >::job, BodyPipe::status(), and BodyPipe::stillConsuming().
dial()
template<class Job > void JobDialer< Job >::dial (AsyncCall & call) inherited
Definition at line 171 of file AsyncJobCalls.h.
References Critical, debugs, AsyncCall::debugSection, and AsyncCall::name.
doDial()
void UnaryMemFunT< BodyConsumer , BodyPipe::Pointer , BodyPipe::Pointer >::doDial () inline override protected virtual inherited
Implements JobDialer< Job >.
Definition at line 123 of file AsyncJobCalls.h.
print()
void UnaryMemFunT< BodyConsumer , BodyPipe::Pointer , BodyPipe::Pointer >::print (std::ostream & os) const inline override virtual inherited
Implements CallDialer.
Definition at line 116 of file AsyncJobCalls.h.
Member Data Documentation
arg1
BodyPipe::Pointer UnaryMemFunT< BodyConsumer , BodyPipe::Pointer , BodyPipe::Pointer >::arg1 inherited
Definition at line 120 of file AsyncJobCalls.h.
job
template<class Job > JobPointer JobDialer< Job >::job inherited
Definition at line 38 of file AsyncJobCalls.h.
Referenced by BodyProducerDialer::canDial(), canDial(), NullaryMemFunT< Job >::doDial(), and UnaryMemFunT< Job, Data, Argument1 >::doDial().
method
Method UnaryMemFunT< BodyConsumer , BodyPipe::Pointer , BodyPipe::Pointer >::method inherited
Definition at line 119 of file AsyncJobCalls.h.
The documentation for this class was generated from the following file:
squid/src/BodyPipe.cc