Squid Web Cache: DelayTaggedBucket Class Reference
DelayTaggedBucket Class Reference
Squid Components » Delay Pools API
#include <DelayTagged.h>
Public Types
typedef RefCount< DelayTaggedBucket > Pointer
Public Member Functions
void stats (StoreEntry *) const
DelayTaggedBucket (const SBuf &aTag)
~DelayTaggedBucket () override
Public Attributes
DelayBucket theBucket
const SBuf tag
Private Member Functions
MEMPROXY_CLASS (DelayTaggedBucket)
Detailed Description
Definition at line 26 of file DelayTagged.h.
Member Typedef Documentation
Pointer
typedef RefCount<DelayTaggedBucket> DelayTaggedBucket::Pointer
Definition at line 31 of file DelayTagged.h.
Constructor & Destructor Documentation
DelayTaggedBucket()
DelayTaggedBucket::DelayTaggedBucket (const SBuf & aTag) explicit
Definition at line 119 of file DelayTagged.cc.
References debugs.
~DelayTaggedBucket()
DelayTaggedBucket::~DelayTaggedBucket () override
Definition at line 124 of file DelayTagged.cc.
References debugs.
Member Function Documentation
MEMPROXY_CLASS()
DelayTaggedBucket::MEMPROXY_CLASS (DelayTaggedBucket) private
stats()
void DelayTaggedBucket::stats (StoreEntry * entry) const
Definition at line 130 of file DelayTagged.cc.
References SQUIDSBUFPH, SQUIDSBUFPRINT, DelayBucket::stats(), storeAppendPrintf(), tag, and theBucket.
Referenced by DelayTaggedStatsVisitor::operator()().
Member Data Documentation
tag
const SBuf DelayTaggedBucket::tag
Definition at line 37 of file DelayTagged.h.
Referenced by DelayTaggedCmp(), and stats().
theBucket
DelayBucket DelayTaggedBucket::theBucket
Definition at line 36 of file DelayTagged.h.
Referenced by DelayTagged::Id::Id(), and stats().
The documentation for this class was generated from the following files:
squid/src/DelayTagged.h
squid/src/DelayTagged.cc