Squid Web Cache: TestHttpRequest Class Reference
TestHttpRequest Class Reference
Protected Member Functions
void testCreateFromUrl ()
void testIPv6HostColonBug ()
void testSanityCheckStartLine ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestHttpRequest)
CPPUNIT_TEST (testCreateFromUrl)
CPPUNIT_TEST (testIPv6HostColonBug)
CPPUNIT_TEST (testSanityCheckStartLine)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 19 of file testHttpRequest.cc.
Member Function Documentation
CPPUNIT_TEST() [1/3]
TestHttpRequest::CPPUNIT_TEST (testCreateFromUrl) private
CPPUNIT_TEST() [2/3]
TestHttpRequest::CPPUNIT_TEST (testIPv6HostColonBug) private
CPPUNIT_TEST() [3/3]
TestHttpRequest::CPPUNIT_TEST (testSanityCheckStartLine) private
CPPUNIT_TEST_SUITE()
TestHttpRequest::CPPUNIT_TEST_SUITE (TestHttpRequest) private
CPPUNIT_TEST_SUITE_END()
TestHttpRequest::CPPUNIT_TEST_SUITE_END () private
testCreateFromUrl()
void TestHttpRequest::testCreateFromUrl () protected
Definition at line 63 of file testHttpRequest.cc.
References HttpRequest::FromUrl(), AnyP::Uri::getScheme(), AnyP::Uri::host(), HttpRequest::method, Http::METHOD_CONNECT, Http::METHOD_GET, Http::METHOD_PUT, AnyP::Uri::path(), AnyP::Uri::port(), AnyP::PROTO_HTTP, AnyP::PROTO_NONE, and HttpRequest::url.
testIPv6HostColonBug()
void TestHttpRequest::testIPv6HostColonBug () protected
Definition at line 123 of file testHttpRequest.cc.
References HttpRequest::FromUrl(), AnyP::Uri::getScheme(), AnyP::Uri::host(), HttpRequest::method, Http::METHOD_GET, AnyP::Uri::path(), AnyP::Uri::port(), AnyP::PROTO_HTTP, and HttpRequest::url.
testSanityCheckStartLine()
void TestHttpRequest::testSanityCheckStartLine () protected
Definition at line 160 of file testHttpRequest.cc.
References MemBuf::append(), MemBuf::content(), MemBuf::contentSize(), PrivateHttpRequest::doSanityCheckStartLine(), error(), headersEnd(), MemBuf::init(), MemBuf::reset(), Http::scInvalidHeader, and Http::scNone.
The documentation for this class was generated from the following file:
squid/src/tests/testHttpRequest.cc