Squid Web Cache: Ssl::ErrorDetailFile Class Reference
Ssl::ErrorDetailFile Class Reference
manages error detail templates
Public Member Functions
ErrorDetailFile (ErrorDetailsList::Pointer const details)
bool loaded () const
return true if the data loaded from disk without any problem
void loadDefault ()
bool loadFor (const HttpRequest *request)
bool loadFromFile (const char *path)
const char * language ()
The language used for the template.
Public Attributes
SBuf filename
where the template was loaded from
bool silent
Whether to print error messages on cache.log file or not. It is user defined.
Protected Member Functions
virtual void setDefault ()
recover from loadDefault() failure to load or parse() a template
bool tryLoadTemplate (const char *lang)
Protected Attributes
SBuf template_
raw template contents
bool wasLoaded
True if the template data read from disk without any problem.
String errLanguage
The error language of the template.
String templateName
The name of the template.
err_type templateCode
The internal code for this template.
Private Member Functions
bool parse () override
post-process the loaded template
Private Attributes
ErrorDetailsList::Pointer theDetails
Detailed Description
Definition at line 52 of file ErrorDetailManager.cc.
Constructor & Destructor Documentation
ErrorDetailFile()
Ssl::ErrorDetailFile::ErrorDetailFile (ErrorDetailsList::Pointer const details) inline explicit
Definition at line 55 of file ErrorDetailManager.cc.
References theDetails.
Member Function Documentation
language()
const char * TemplateFile::language () inline inherited
Definition at line 312 of file errorpage.h.
References TemplateFile::errLanguage, and String::termedBuf().
Referenced by ErrorState::buildBody(), and Ssl::ErrorDetailsManager::findDetail().
loadDefault()
void TemplateFile::loadDefault () inherited
Load the page_name template from a file which probably exist at: (a) admin specified custom directory (error_directory) (b) default language translation directory (error_default_language) (c) English sub-directory where errors should ALWAYS exist If all of the above fail, setDefault() is called.
test error_directory configured location
test error_default_language location
Definition at line 363 of file errorpage.cc.
References Config, DBG_CRITICAL, debugs, SquidConfig::errorDefaultLanguage, SquidConfig::errorDirectory, TemplateFile::loaded(), TemplateFile::loadFromFile(), MAXPATHLEN, TemplateFile::setDefault(), TCP_RESET, TemplateFile::templateCode, TemplateFile::templateName, String::termedBuf(), TemplateFile::tryLoadTemplate(), and TemplateFile::wasLoaded.
Referenced by Ssl::ErrorDetailsManager::ErrorDetailsManager(), and errorInitialize().
loaded()
bool TemplateFile::loaded () const inline inherited
Definition at line 286 of file errorpage.h.
References TemplateFile::wasLoaded.
Referenced by TemplateFile::loadDefault(), TemplateFile::loadFor(), and TemplateFile::loadFromFile().
loadFor()
bool TemplateFile::loadFor (const HttpRequest * request) inherited
Load an error template for a given HTTP request. This function examines the Accept-Language header and select the first available template. If the default template selected (eg because of a "Accept-Language: *"), or not available template found this function return false.
Definition at line 526 of file errorpage.cc.
References Http::ACCEPT_LANGUAGE, Config, DBG_IMPORTANT, debugs, TemplateFile::errLanguage, SquidConfig::errorLogMissingLanguages, HttpHeader::getList(), Http::Message::header, TemplateFile::loaded(), strHdrAcptLangGetItem(), and TemplateFile::tryLoadTemplate().
Referenced by ErrorState::buildBody(), and Ssl::ErrorDetailsManager::findDetail().
loadFromFile()
bool TemplateFile::loadFromFile (const char * path) inherited
Load the file given by "path". It uses the "parse()" method. On success return true and sets the "defined" member
Definition at line 424 of file errorpage.cc.
References DBG_CRITICAL, debugs, FD_READ_METHOD(), file_close(), file_open(), TemplateFile::filename, TemplateFile::loaded(), MYNAME, O_TEXT, TemplateFile::parse(), TemplateFile::silent, TCP_RESET, TemplateFile::templateCode, TemplateFile::wasLoaded, and xstrerr().
Referenced by errorInitialize(), TemplateFile::loadDefault(), and TemplateFile::tryLoadTemplate().
parse()
bool Ssl::ErrorDetailFile::parse () override private virtual
Reimplemented from TemplateFile.
Definition at line 174 of file ErrorDetailManager.cc.
References CurrentException(), DBG_IMPORTANT, debugs, detailEntryEnd(), Ssl::ErrorIsOptional(), HttpHeader::getByName(), Ssl::GetErrorCode(), HttpHeader::parse(), size, String::size(), StringToSBuf(), and String::termedBuf().
setDefault()
virtual void TemplateFile::setDefault () inline protected virtual inherited
Reimplemented in ErrorPageFile.
Definition at line 323 of file errorpage.h.
Referenced by TemplateFile::loadDefault().
tryLoadTemplate()
bool TemplateFile::tryLoadTemplate (const char * lang) protected inherited
Try to load the "page_name" template for a given language "lang" from squid errors directory
Returns
true on success false otherwise
Definition at line 399 of file errorpage.cc.
References assert, debugs, DEFAULT_SQUID_ERROR_DIR, TemplateFile::loadFromFile(), MAXPATHLEN, TemplateFile::templateName, and String::termedBuf().
Referenced by TemplateFile::loadDefault(), and TemplateFile::loadFor().
Member Data Documentation
errLanguage
String TemplateFile::errLanguage protected inherited
Definition at line 334 of file errorpage.h.
Referenced by TemplateFile::language(), and TemplateFile::loadFor().
filename
SBuf TemplateFile::filename inherited
Definition at line 314 of file errorpage.h.
Referenced by ErrorState::buildBody(), errorInitialize(), and TemplateFile::loadFromFile().
silent
bool TemplateFile::silent inherited
Definition at line 316 of file errorpage.h.
Referenced by TemplateFile::loadFromFile().
template_
SBuf TemplateFile::template_ protected inherited
Definition at line 332 of file errorpage.h.
Referenced by ErrorPageFile::setDefault().
templateCode
err_type TemplateFile::templateCode protected inherited
Definition at line 336 of file errorpage.h.
Referenced by TemplateFile::loadDefault(), and TemplateFile::loadFromFile().
templateName
String TemplateFile::templateName protected inherited
Definition at line 335 of file errorpage.h.
Referenced by TemplateFile::loadDefault(), ErrorPageFile::setDefault(), and TemplateFile::tryLoadTemplate().
theDetails
ErrorDetailsList::Pointer Ssl::ErrorDetailFile::theDetails private
Definition at line 60 of file ErrorDetailManager.cc.
Referenced by ErrorDetailFile().
wasLoaded
bool TemplateFile::wasLoaded protected inherited
Definition at line 333 of file errorpage.h.
Referenced by TemplateFile::loadDefault(), TemplateFile::loaded(), and TemplateFile::loadFromFile().
The documentation for this class was generated from the following file:
squid/src/ssl/ErrorDetailManager.cc