Squid Web Cache: TextException Class Reference
TextException Class Reference
an std::runtime_error with thrower location info
#include <TextException.h>
Public Member Functions
TextException (const char *message, const SourceLocation &location)
TextException (SBuf message, const SourceLocation &location)
TextException (const TextException &)=default
TextException (TextException &&)=default
TextException & operator= (const TextException &)=default
~TextException () override throw ()
const char * what () const override throw ()
SourceLocationId id () const
same-location exceptions have the same ID
std::ostream & print (std::ostream &) const
dumps the exception text into the stream
Public Attributes
SourceLocation where
code location related to the exception; usually the thrower location
Detailed Description
Definition at line 20 of file TextException.h.
Constructor & Destructor Documentation
TextException() [1/4]
TextException::TextException (const char * message, const SourceLocation & location) inline
Definition at line 24 of file TextException.h.
TextException() [2/4]
TextException::TextException (SBuf message, const SourceLocation & location)
Definition at line 26 of file TextException.cc.
TextException() [3/4]
TextException::TextException (const TextException &) default
TextException() [4/4]
TextException::TextException (TextException &&) default
~TextException()
TextException::~TextException () throw () override
Definition at line 30 of file TextException.cc.
References WhatStrings_.
Member Function Documentation
id()
SourceLocationId TextException::id () const inline
Definition at line 40 of file TextException.h.
References SourceLocation::id(), and where.
Referenced by Adaptation::Icap::ModXact::callException(), and ConnStateData::parseTlsHandshake().
operator=()
TextException & TextException::operator= (const TextException &) default
print()
std::ostream & TextException::print (std::ostream & os) const
Definition at line 37 of file TextException.cc.
References Debug::Extra(), and where.
Referenced by operator<<(), and what().
what()
const char * TextException::what () const throw () override
Definition at line 46 of file TextException.cc.
References print(), and WhatStrings_.
Referenced by CurrentException_(), and IpcIoFile::push().
Member Data Documentation
where
SourceLocation TextException::where
Definition at line 46 of file TextException.h.
Referenced by id(), and print().
The documentation for this class was generated from the following files:
squid/src/base/TextException.h
squid/src/base/TextException.cc