Squid Web Cache: DelayConfig Class Reference
DelayConfig Class Reference
Squid Components » Delay Pools API
#include <DelayConfig.h>
Public Member Functions
void freePoolCount ()
void dumpPoolCount (StoreEntry *entry, const char *name) const
void parsePoolCount ()
void parsePoolClass ()
void parsePoolRates ()
void parsePoolAccess (ConfigParser &parser)
Public Attributes
unsigned short initial
Detailed Description
Definition at line 18 of file DelayConfig.h.
Member Function Documentation
dumpPoolCount()
void DelayConfig::dumpPoolCount (StoreEntry * entry, const char * name) const
Definition at line 100 of file DelayConfig.cc.
References DelayPools::delay_data, DelayPools::pools(), and storeAppendPrintf().
Referenced by dump_delay_pool_count().
freePoolCount()
void DelayConfig::freePoolCount ()
Definition at line 93 of file DelayConfig.cc.
References DelayPools::FreePools(), and initial.
Referenced by free_delay_pool_count().
parsePoolAccess()
void DelayConfig::parsePoolAccess (ConfigParser & parser)
Definition at line 77 of file DelayConfig.cc.
References aclParseAccessLine(), DBG_CRITICAL, debugs, DelayPools::delay_data, ConfigParser::ParseUShort(), and DelayPools::pools().
Referenced by parse_delay_pool_access().
parsePoolClass()
void DelayConfig::parsePoolClass ()
Definition at line 31 of file DelayConfig.cc.
References DelayPool::createPool(), DBG_CRITICAL, debugs, DelayPools::delay_data, ConfigParser::ParseUShort(), and DelayPools::pools().
Referenced by parse_delay_pool_class().
parsePoolCount()
void DelayConfig::parsePoolCount ()
Definition at line 23 of file DelayConfig.cc.
References ConfigParser::ParseUShort(), and DelayPools::pools().
Referenced by parse_delay_pool_count().
parsePoolRates()
void DelayConfig::parsePoolRates ()
Definition at line 56 of file DelayConfig.cc.
References DBG_CRITICAL, debugs, DelayPools::delay_data, DelayPool::parse(), ConfigParser::ParseUShort(), and DelayPools::pools().
Referenced by parse_delay_pool_rates().
Member Data Documentation
initial
unsigned short DelayConfig::initial
Definition at line 28 of file DelayConfig.h.
Referenced by freePoolCount(), and DelayBucket::init().
The documentation for this class was generated from the following files:
squid/src/DelayConfig.h
squid/src/DelayConfig.cc