Squid Web Cache: TestString Class Reference
TestString Class Reference
Protected Member Functions
void testCmpDefault ()
void testCmpEmptyString ()
void testCmpNotEmptyDefault ()
void testSubstr ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestString)
CPPUNIT_TEST (testCmpDefault)
CPPUNIT_TEST (testCmpEmptyString)
CPPUNIT_TEST (testCmpNotEmptyDefault)
CPPUNIT_TEST (testSubstr)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 19 of file testString.cc.
Member Function Documentation
CPPUNIT_TEST() [1/4]
TestString::CPPUNIT_TEST (testCmpDefault) private
CPPUNIT_TEST() [2/4]
TestString::CPPUNIT_TEST (testCmpEmptyString) private
CPPUNIT_TEST() [3/4]
TestString::CPPUNIT_TEST (testCmpNotEmptyDefault) private
CPPUNIT_TEST() [4/4]
TestString::CPPUNIT_TEST (testSubstr) private
CPPUNIT_TEST_SUITE()
TestString::CPPUNIT_TEST_SUITE (TestString) private
CPPUNIT_TEST_SUITE_END()
TestString::CPPUNIT_TEST_SUITE_END () private
testCmpDefault()
void TestString::testCmpDefault () protected
Definition at line 38 of file testString.cc.
References String::cmp().
testCmpEmptyString()
void TestString::testCmpEmptyString () protected
Definition at line 48 of file testString.cc.
References String::cmp().
testCmpNotEmptyDefault()
void TestString::testCmpNotEmptyDefault () protected
Definition at line 63 of file testString.cc.
References String::cmp().
testSubstr()
void TestString::testSubstr () protected
Definition at line 77 of file testString.cc.
References String::substr().
The documentation for this class was generated from the following file:
squid/src/tests/testString.cc