Squid Web Cache: ACLProxyAuth Class Reference
ACLProxyAuth Class Reference
#include <AclProxyAuth.h>
Public Types
using Pointer = RefCount< Node >
Public Member Functions
~ACLProxyAuth () override
ACLProxyAuth (ACLData< char const * > *, char const *)
char const * typeString () const override
void parse () override
parses node representation in squid.conf; dies on failures
bool isProxyAuth () const override
int match (ACLChecklist *checklist) override
Matches the actual data in checklist against this Acl::Node.
SBufList dump () const override
bool valid () const override
bool empty () const override
bool requiresRequest () const override
whether our (i.e. shallow) match() requires checklist to have a request
int matchForCache (ACLChecklist *checklist) override
void * operator new (size_t)
void operator delete (void *)
void context (const SBuf &aName, const char *configuration)
sets user-specified ACL name and squid.conf context
bool matches (ACLChecklist *checklist) const
void parseFlags ()
configures Acl::Node options, throwing on configuration errors
int cacheMatchAcl (dlink_list *cache, ACLChecklist *)
virtual void prepareForUse ()
void dumpWhole (const char *directiveName, std::ostream &)
Static Public Member Functions
static void StartLookup (ACLFilledChecklist &, const Acl::Node &)
static void ParseNamedAcl (ConfigParser &, NamedAcls *&)
parses acl directive parts that follow directive name (i.e. "acl")
static void Initialize ()
static Acl::Node * FindByName (const SBuf &)
A configured ACL with a given name or nil.
Public Attributes
SBuf name
char * cfgline = nullptr
Private Member Functions
MEMPROXY_CLASS (ACLProxyAuth)
const Acl::Options & lineOptions () override
int matchProxyAuth (ACLChecklist *)
virtual bool requiresAle () const
whether our (i.e. shallow) match() requires checklist to have a AccessLogEntry
virtual bool requiresReply () const
whether our (i.e. shallow) match() requires checklist to have a reply
virtual const Acl::Options & options ()
Static Private Member Functions
static void LookupDone (void *data)
static void ParseNamed (ConfigParser &, NamedAcls &, const SBuf &name)
parses acl directive parts that follow aclname
Private Attributes
ACLData< char const * > * data
char const * type_
Detailed Description
Definition at line 18 of file AclProxyAuth.h.
Member Typedef Documentation
Pointer
using Acl::Node::Pointer = RefCount<Node> inherited
Definition at line 29 of file Node.h.
Constructor & Destructor Documentation
~ACLProxyAuth()
ACLProxyAuth::~ACLProxyAuth () override
Definition at line 24 of file AclProxyAuth.cc.
References data.
ACLProxyAuth()
ACLProxyAuth::ACLProxyAuth (ACLData< char const * > * newData, char const * theType)
Definition at line 29 of file AclProxyAuth.cc.
Member Function Documentation
cacheMatchAcl()
int Acl::Node::cacheMatchAcl (dlink_list * cache, ACLChecklist * checklist) inherited
Definition at line 401 of file Acl.cc.
References acl_proxy_auth_match_cache::acl_data, dlink_node::data, debugs, dlinkAddTail(), dlink_list::head, acl_proxy_auth_match_cache::link, acl_proxy_auth_match_cache::matchrv, and dlink_node::next.
Referenced by matchProxyAuth().
context()
void Acl::Node::context (const SBuf & aName, const char * configuration) inherited
Definition at line 220 of file Acl.cc.
References safe_free, and xstrdup.
Referenced by aclParseAccessLine(), aclParseAclList(), Acl::AllOf::parse(), and ParseAclWithAction().
dump()
SBufList ACLProxyAuth::dump () const override virtual
Implements Acl::Node.
Definition at line 78 of file AclProxyAuth.cc.
References data, and ACLData< M >::dump().
dumpWhole()
void Acl::Node::dumpWhole (const char * directiveName, std::ostream & os) inherited
Prints aggregated "acl" (or similar) directive configuration, including the given directive name, ACL name, ACL type, and ACL parameters. The printed parameters are collected from all same-name "acl" directives.
Definition at line 371 of file Acl.cc.
References asList().
empty()
bool ACLProxyAuth::empty () const override virtual
Implements Acl::Node.
Definition at line 84 of file AclProxyAuth.cc.
References data, and ACLData< M >::empty().
FindByName()
Acl::Node * Acl::Node::FindByName (const SBuf & name) static inherited
Definition at line 159 of file Acl.cc.
References assert, Config, debugs, and SquidConfig::namedAcls.
Referenced by aclIsProxyAuth(), Acl::InnerNode::lineParse(), parse_ftp_epsv(), and TestACLMaxUserIP::testParseLine().
Initialize()
void Acl::Node::Initialize () static inherited
Definition at line 471 of file Acl.cc.
References Config, debugs, and SquidConfig::namedAcls.
Referenced by serverConnectionsOpen().
isProxyAuth()
bool ACLProxyAuth::isProxyAuth () const inline override virtual
Reimplemented from Acl::Node.
Definition at line 31 of file AclProxyAuth.h.
lineOptions()
const Acl::Options & ACLProxyAuth::lineOptions () override private virtual
Returns
(linked) "line" Options supported by this Acl::Node
See also
Acl::Node::options()
Reimplemented from Acl::Node.
Definition at line 41 of file AclProxyAuth.cc.
References data, and ACLData< M >::lineOptions().
LookupDone()
void ACLProxyAuth::LookupDone (void * data) static private
Definition at line 117 of file AclProxyAuth.cc.
References ACLFilledChecklist::auth_user_request, ACLFilledChecklist::conn(), data, Filled(), ACLChecklist::resumeNonBlockingCheck(), ConnStateData::setAuth(), and Auth::UserRequest::valid().
Referenced by StartLookup().
match()
int ACLProxyAuth::match (ACLChecklist * checklist) override virtual
Implements Acl::Node.
Definition at line 53 of file AclProxyAuth.cc.
References ACCESS_ALLOWED, ACCESS_AUTH_REQUIRED, ACCESS_DENIED, ACCESS_DUNNO, AuthenticateAcl(), ACLChecklist::keepMatching(), ACLChecklist::markFinished(), and matchProxyAuth().
matches()
bool Acl::Node::matches (ACLChecklist * checklist) const inherited
Orchestrates matching checklist against the Acl::Node using match(), after checking preconditions and while providing debugging.
Returns
true if and only if there was a successful match. Updates the checklist state on match, async, and failure.
Definition at line 189 of file Acl.cc.
References ACLChecklist::asyncInProgress(), DBG_IMPORTANT, debugs, ACLChecklist::hasAle(), ACLChecklist::hasReply(), ACLChecklist::hasRequest(), ACLChecklist::setLastCheckedName(), and ACLChecklist::verifyAle().
Referenced by ACLChecklist::matchAndFinish().
matchForCache()
int ACLProxyAuth::matchForCache (ACLChecklist * checklist) override virtual
Reimplemented from Acl::Node.
Definition at line 136 of file AclProxyAuth.cc.
References assert, ACLFilledChecklist::auth_user_request, data, Filled(), ACLData< M >::match(), and Auth::UserRequest::username().
matchProxyAuth()
int ACLProxyAuth::matchProxyAuth (ACLChecklist * cl) private
Definition at line 148 of file AclProxyAuth.cc.
References ACLFilledChecklist::auth_user_request, authenticateUserAuthenticated(), Acl::Node::cacheMatchAcl(), Filled(), HttpRequest::flags, ACLFilledChecklist::request, RequestFlags::sslBumped, and Auth::UserRequest::user().
Referenced by match().
MEMPROXY_CLASS()
ACLProxyAuth::MEMPROXY_CLASS (ACLProxyAuth) private
operator delete()
void Acl::Node::operator delete (void *) inherited
Definition at line 153 of file Acl.cc.
References fatal().
operator new()
void * Acl::Node::operator new (size_t) inherited
Definition at line 147 of file Acl.cc.
References fatal().
options()
virtual const Acl::Options & Acl::Node::options () inline private virtual inherited
Returns
(linked) 'global' Options supported by this Acl::Node
Reimplemented in Acl::DestinationDomainCheck, ACLDestinationIP, Acl::AnnotationCheck, Acl::ServerNameCheck, and ACLMaxUserIP.
Definition at line 98 of file Node.h.
References Acl::NoOptions().
parse()
void ACLProxyAuth::parse () override virtual
Implements Acl::Node.
Definition at line 47 of file AclProxyAuth.cc.
References data, and ACLData< M >::parse().
parseFlags()
void Acl::Node::parseFlags () inherited
Definition at line 360 of file Acl.cc.
References Acl::ParseFlags().
ParseNamed()
void Acl::Node::ParseNamed (ConfigParser & parser, NamedAcls & namedAcls, const SBuf & name) static private inherited
Definition at line 253 of file Acl.cc.
References Assure, SBuf::cmp(), config_input_line, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::destruct(), fatalf(), HttpPortList, Acl::Make(), and ConfigParser::NextToken().
ParseNamedAcl()
void Acl::Node::ParseNamedAcl (ConfigParser & parser, NamedAcls *& namedAcls) static inherited
Definition at line 229 of file Acl.cc.
References CallParser(), DBG_CRITICAL, debugs, ConfigParser::destruct(), RefCount< C >::Make(), and ConfigParser::NextToken().
Referenced by parse_acl(), and TestACLMaxUserIP::testParseLine().
prepareForUse()
virtual void Acl::Node::prepareForUse () inline virtual inherited
Reimplemented in Acl::InnerNode, ACLMaxConnection, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, and Acl::ParameterizedNode< ACLTimeData >.
Definition at line 69 of file Node.h.
requiresAle()
bool Acl::Node::requiresAle () const private virtual inherited
Reimplemented in ACLExternal.
Definition at line 443 of file Acl.cc.
requiresReply()
bool Acl::Node::requiresReply () const private virtual inherited
Reimplemented in Acl::HttpRepHeaderCheck, ACLHTTPStatus, and Acl::ReplyHeaderCheck< header >.
Definition at line 449 of file Acl.cc.
requiresRequest()
bool ACLProxyAuth::requiresRequest () const inline override virtual
Reimplemented from Acl::Node.
Definition at line 36 of file AclProxyAuth.h.
StartLookup()
void ACLProxyAuth::StartLookup (ACLFilledChecklist & cl, const Acl::Node &) static
Definition at line 106 of file AclProxyAuth.cc.
References ACLFilledChecklist::al, assert, ACLFilledChecklist::auth_user_request, debugs, RefCount< C >::getRaw(), LookupDone(), ACLFilledChecklist::request, Auth::UserRequest::start(), and Auth::UserRequest::valid().
Referenced by AuthenticateAcl().
typeString()
char const * ACLProxyAuth::typeString () const override virtual
Implements Acl::Node.
Definition at line 35 of file AclProxyAuth.cc.
References type_.
valid()
bool ACLProxyAuth::valid () const override virtual
Reimplemented from Acl::Node.
Definition at line 90 of file AclProxyAuth.cc.
References authenticateActiveSchemeCount(), authenticateSchemeCount(), DBG_CRITICAL, and debugs.
Member Data Documentation
cfgline
char* Acl::Node::cfgline = nullptr inherited
Definition at line 83 of file Node.h.
data
ACLData<char const *>* ACLProxyAuth::data private
Definition at line 46 of file AclProxyAuth.h.
Referenced by ~ACLProxyAuth(), dump(), empty(), lineOptions(), LookupDone(), matchForCache(), and parse().
name
SBuf Acl::Node::name inherited
Either aclname parameter from the explicitly configured acl directive or a label generated for an internal ACL tree node. All Node objects corresponding to one Squid configuration have unique names. See also: context() and FindByName().
Definition at line 81 of file Node.h.
Referenced by Acl::NotNode::NotNode(), aclDestroyAccessList(), Acl::AnnotateClientCheck::match(), Acl::AnnotateTransactionCheck::match(), Acl::SourceDomainCheck::match(), ACLDestinationIP::match(), ACLRandom::match(), ACLExternal::parse(), and ACLMaxConnection::prepareForUse().
type_
char const* ACLProxyAuth::type_ private
Definition at line 47 of file AclProxyAuth.h.
Referenced by typeString().
The documentation for this class was generated from the following files:
squid/src/auth/AclProxyAuth.h
squid/src/auth/AclProxyAuth.cc