Squid Web Cache: Comm::ConnOpener Class Reference
Comm::ConnOpener Class Reference abstract
#include <ConnOpener.h>
Classes
struct Calls
handles to calls which we may need to cancel.
Public Types
typedef CbcPointer< ConnOpener > Pointer
Public Member Functions
bool doneAll () const override
whether positive goal has been reached
ConnOpener (const Comm::ConnectionPointer &, const AsyncCall::Pointer &handler, time_t connect_timeout)
~ConnOpener () override
void setHost (const char *)
set the hostname note for this connection
const char * getHost () const
get the hostname noted for this connection
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void start () override
called by AsyncStart; do not call directly
void swanSong () override
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual const char * status () const
internal cleanup; do not call directly
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
CBDATA_CHILD (ConnOpener)
ConnOpener (const ConnOpener &)
ConnOpener & operator= (const ConnOpener &c)
void earlyAbort (const CommCloseCbParams &)
void timeout (const CommTimeoutCbParams &)
void sendAnswer (Comm::Flag errFlag, int xerrno, const char *why)
void doConnect ()
Make an FD connection attempt.
void connected ()
void lookupLocalAddress ()
void retrySleep ()
Close and wait a little before trying to open and connect again.
void restart ()
called at the end of Comm::ConnOpener::DelayedConnectRetry event
bool createFd ()
void closeFd ()
cleans I/O state and ends I/O for temporaryFd_
void keepFd ()
cleans I/O state and moves temporaryFd_ to the conn_ for long-term use
void cleanFd ()
void cancelSleep ()
cleans up this job sleep state
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Static Private Member Functions
static void InProgressConnectRetry (int fd, void *data)
static void DelayedConnectRetry (void *data)
Private Attributes
char * host_
domain name we are trying to connect to.
int temporaryFd_
the FD being opened. Do NOT set conn_->fd until it is fully open.
Comm::ConnectionPointer conn_
single connection currently to be opened.
AsyncCall::Pointer callback_
handler to be called on connection completion.
int totalTries_
total number of connection attempts over all destinations so far.
int failRetries_
number of retries current destination has been tried.
time_t deadline_
if we are not done by then, we will call back with Comm::TIMEOUT
struct Comm::ConnOpener::Calls calls_
Detailed Description
Asynchronously opens a TCP connection. Returns CommConnectCbParams: either Comm::OK with an open connection or another Comm::Flag with a closed one.
Definition at line 24 of file ConnOpener.h.
Member Typedef Documentation
Pointer
typedef CbcPointer<ConnOpener> Comm::ConnOpener::Pointer
Definition at line 29 of file ConnOpener.h.
Constructor & Destructor Documentation
ConnOpener() [1/2]
Comm::ConnOpener::ConnOpener (const Comm::ConnectionPointer & c, const AsyncCall::Pointer & handler, time_t connect_timeout)
Definition at line 33 of file ConnOpener.cc.
References assert, conn_, debugs, and Comm::Connection::isOpen().
~ConnOpener()
Comm::ConnOpener::~ConnOpener () override
Definition at line 54 of file ConnOpener.cc.
References safe_free.
ConnOpener() [2/2]
Comm::ConnOpener::ConnOpener (const ConnOpener &) private
Member Function Documentation
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
cancelSleep()
void Comm::ConnOpener::cancelSleep () private
Definition at line 410 of file ConnOpener.cc.
References debugs.
CBDATA_CHILD()
Comm::ConnOpener::CBDATA_CHILD (ConnOpener) private
cleanFd()
void Comm::ConnOpener::cleanFd () private
cleans up this job I/O state without closing temporaryFd required before closing temporaryFd or keeping it in conn_ leaves FD bare so must only be called via closeFd() or keepFd()
Definition at line 174 of file ConnOpener.cc.
References comm_remove_close_handler(), COMM_SELECT_WRITE, debugs, fd_table, Must, Comm::SetSelect(), fde::timeout, fde::timeoutHandler, fde::write_data, and fde::write_handler.
closeFd()
void Comm::ConnOpener::closeFd () private
Definition at line 220 of file ConnOpener.cc.
References comm_close.
connected()
void Comm::ConnOpener::connected () private
Definition at line 328 of file ConnOpener.cc.
References fd_table, Must, and Comm::OK.
createFd()
bool Comm::ConnOpener::createFd () private
Create a socket for the future connection or return false. If false is returned, done() is guaranteed to return true and end the job.
Definition at line 279 of file ConnOpener.cc.
References assert, comm_add_close_handler(), comm_open(), debugs, earlyAbort(), Comm::ERR_CONNECT, fd_table, JobCallback, Must, Ip::Qos::setSockNfmark(), Ip::Qos::setSockTos(), squid_curtime, Squid_MaxFD, and timeout().
DelayedConnectRetry()
void Comm::ConnOpener::DelayedConnectRetry (void * data) static private
Definition at line 491 of file ConnOpener.cc.
References assert, JobCallback, restart(), ScheduleCallHere, and CbcPointer< Cbc >::valid().
Referenced by retrySleep().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
doConnect()
void Comm::ConnOpener::doConnect () private
Definition at line 357 of file ConnOpener.cc.
References comm_connect_addr(), COMM_SELECT_WRITE, Config, SquidConfig::connect_retries, debugs, Comm::ERR_CONNECT, Comm::INPROGRESS, InProgressConnectRetry(), Must, Comm::OK, Comm::SetSelect(), and xstrerr().
Referenced by InProgressConnectRetry().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Comm::ConnOpener::doneAll () const override virtual
Reimplemented from AsyncJob.
Definition at line 60 of file ConnOpener.cc.
References AsyncJob::doneAll(), and Must.
earlyAbort()
void Comm::ConnOpener::earlyAbort (const CommCloseCbParams & io) private
Abort connection attempt. Handles the case(s) when a partially setup connection gets closed early.
Definition at line 449 of file ConnOpener.cc.
References CommCommonCbParams::conn, debugs, Comm::ERR_CLOSING, and CommCommonCbParams::xerrno.
Referenced by createFd().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
getHost()
const char * Comm::ConnOpener::getHost () const
Definition at line 113 of file ConnOpener.cc.
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
InProgressConnectRetry()
void Comm::ConnOpener::InProgressConnectRetry (int fd, void * data) static private
Definition at line 473 of file ConnOpener.cc.
References assert, doConnect(), JobCallback, ScheduleCallHere, and CbcPointer< Cbc >::valid().
Referenced by doConnect().
keepFd()
void Comm::ConnOpener::keepFd () private
Definition at line 239 of file ConnOpener.cc.
References Must.
lookupLocalAddress()
void Comm::ConnOpener::lookupLocalAddress () private
Lookup local-end address and port of the TCP link just opened. This ensure the connection local details are set correctly
Definition at line 431 of file ConnOpener.cc.
References DBG_IMPORTANT, debugs, xgetsockname(), and xstrerr().
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
operator=()
ConnOpener & Comm::ConnOpener::operator= (const ConnOpener & c) private
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
restart()
void Comm::ConnOpener::restart () private
Definition at line 267 of file ConnOpener.cc.
References debugs.
Referenced by DelayedConnectRetry().
retrySleep()
void Comm::ConnOpener::retrySleep () private
Definition at line 398 of file ConnOpener.cc.
References DelayedConnectRetry(), eventAdd(), and Must.
sendAnswer()
void Comm::ConnOpener::sendAnswer (Comm::Flag errFlag, int xerrno, const char * why) private
Connection attempt are completed. One way or the other. Pass the results back to the external handler.
Definition at line 123 of file ConnOpener.cc.
References assert, Config, debugs, ipcacheMarkBadAddr(), ipcacheMarkGoodAddr(), netdbDeleteAddrNetwork(), Comm::OK, SquidConfig::onoff, ScheduleCallHere, and SquidConfig::test_reachability.
setHost()
void Comm::ConnOpener::setHost (const char * new_host)
Definition at line 101 of file ConnOpener.cc.
References safe_free, and xstrdup.
Referenced by idnsInitVC(), and peerProbeConnect().
start()
void Comm::ConnOpener::start () override protected virtual
Reimplemented from AsyncJob.
Definition at line 251 of file ConnOpener.cc.
References IPV6_SPECIAL_V4MAPPING, and Must.
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
status()
const char * AsyncJob::status () const protected virtual inherited
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), AsyncJob::stopReason, and MemBuf::terminate().
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
swanSong()
void Comm::ConnOpener::swanSong () override protected virtual
Reimplemented from AsyncJob.
Definition at line 78 of file ConnOpener.cc.
References Comm::ERR_CONNECT, and AsyncJob::swanSong().
timeout()
void Comm::ConnOpener::timeout (const CommTimeoutCbParams &) private
Handles the case(s) when a partially setup connection gets timed out. NP: When commSetConnTimeout accepts generic CommCommonCbParams this can die.
Definition at line 462 of file ConnOpener.cc.
References debugs, and Comm::TIMEOUT.
Referenced by createFd().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
Member Data Documentation
callback_
AsyncCall::Pointer Comm::ConnOpener::callback_ private
Definition at line 71 of file ConnOpener.h.
calls_
struct Comm::ConnOpener::Calls Comm::ConnOpener::calls_ private
conn_
Comm::ConnectionPointer Comm::ConnOpener::conn_ private
Definition at line 70 of file ConnOpener.h.
Referenced by ConnOpener().
deadline_
time_t Comm::ConnOpener::deadline_ private
Definition at line 77 of file ConnOpener.h.
failRetries_
int Comm::ConnOpener::failRetries_ private
Definition at line 74 of file ConnOpener.h.
host_
char* Comm::ConnOpener::host_ private
Definition at line 68 of file ConnOpener.h.
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
temporaryFd_
int Comm::ConnOpener::temporaryFd_ private
Definition at line 69 of file ConnOpener.h.
totalTries_
int Comm::ConnOpener::totalTries_ private
Definition at line 73 of file ConnOpener.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
The documentation for this class was generated from the following files:
squid/src/comm/ConnOpener.h
squid/src/comm/ConnOpener.cc
squid/src/tests/stub_libcomm.cc