Squid Web Cache: Snmp::Inquirer Class Reference
Snmp::Inquirer Class Reference abstract
#include <Inquirer.h>
Public Types
typedef CbcPointer< AsyncJob > Pointer
Public Member Functions
Inquirer (const Request &aRequest, const Ipc::StrandCoords &coords)
void callException (const std::exception &e) override
called when the job throws during an async call
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void HandleRemoteAck (const Response &response)
finds and calls the right Inquirer upon strand's response
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
CodeContextPointer codeContext
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
void start () override
called by AsyncStart; do not call directly
bool doneAll () const override
whether positive goal has been reached
void cleanup () override
closes our copy of the client connection socket
void handleException (const std::exception &e) override
do specific exception handling
void sendResponse () override
send response to client
bool aggregate (Ipc::Response::Pointer aResponse) override
perform aggregating of responses and returns true if need to continue
void swanSong () override
const char * status () const override
internal cleanup; do not call directly
virtual void inquire ()
inquire the next strand
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
Request::Pointer request
cache manager request received from client
Ipc::StrandCoords strands
all strands we want to query, in order
Ipc::StrandCoords::const_iterator pos
strand we should query now
const double timeout
number of seconds to wait for strand response
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Static Protected Attributes
static RequestId::Index LastRequestId = 0
last requestId used
Private Member Functions
CBDATA_CHILD (Inquirer)
void noteCommClosed (const CommCloseCbParams &params)
called when the some external force closed our socket
CBDATA_INTERMEDIATE ()
void handleRemoteAck (Response::Pointer response)
called when a strand is done writing its output
void requestTimedOut ()
called when the strand failed to respond (or finish responding) in time
void removeTimeoutEvent ()
called when we are no longer waiting for the strand to respond
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Static Private Member Functions
static void RequestTimedOut (void *param)
Ipc::Inquirer::requestTimedOut wrapper.
Private Attributes
Pdu aggrPdu
aggregated pdu
Comm::ConnectionPointer conn
client connection descriptor
AsyncCall::Pointer writer
comm_write callback
AsyncCall::Pointer closer
comm_close handler
Detailed Description
Coordinator's job that sends a PDU request to each strand, aggregates strand responses and send back the result to client
Definition at line 26 of file Inquirer.h.
Member Typedef Documentation
Pointer
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Constructor & Destructor Documentation
Inquirer()
Snmp::Inquirer::Inquirer (const Request & aRequest, const Ipc::StrandCoords & coords)
Definition at line 24 of file Inquirer.cc.
References asyncCall(), closer, comm_add_close_handler(), conn, debugs, Comm::Connection::fd, Snmp::Request::fd, Ipc::fdnInSnmpSocket, RefCount< C >::getRaw(), MYNAME, noteCommClosed(), and Ipc::Inquirer::request.
Member Function Documentation
aggregate()
bool Snmp::Inquirer::aggregate (Ipc::Response::Pointer aResponse) override protected virtual
Implements Ipc::Inquirer.
Definition at line 73 of file Inquirer.cc.
References Snmp::Pdu::aggregate(), error(), snmp_pdu::errstat, Snmp::Response::pdu, and SNMP_ERR_NOERROR.
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void Ipc::Inquirer::callException (const std::exception & e) override virtual inherited
Reimplemented from AsyncJob.
Definition at line 159 of file Inquirer.cc.
References AsyncJob::callException(), DBG_CRITICAL, debugs, and MYNAME.
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
CBDATA_CHILD()
Snmp::Inquirer::CBDATA_CHILD (Inquirer) private
CBDATA_INTERMEDIATE()
Ipc::Inquirer::CBDATA_INTERMEDIATE () private inherited
cleanup()
void Snmp::Inquirer::cleanup () override protected virtual
Reimplemented from Ipc::Inquirer.
Definition at line 44 of file Inquirer.cc.
References comm_remove_close_handler(), and Comm::IsConnOpen().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Snmp::Inquirer::doneAll () const override protected virtual
Reimplemented from Ipc::Inquirer.
Definition at line 100 of file Inquirer.cc.
References Ipc::Inquirer::doneAll().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
handleException()
void Snmp::Inquirer::handleException (const std::exception & e) override protected virtual
Reimplemented from Ipc::Inquirer.
Definition at line 66 of file Inquirer.cc.
References Ipc::Inquirer::handleException(), and SNMP_ERR_GENERR.
HandleRemoteAck()
void Ipc::Inquirer::HandleRemoteAck (const Response & response) static inherited
Definition at line 171 of file Inquirer.cc.
References CallService(), Ipc::DequeueRequest(), Must, and Ipc::Response::requestId.
Referenced by Ipc::Coordinator::handleCacheMgrResponse(), and Ipc::Coordinator::handleSnmpResponse().
handleRemoteAck()
void Ipc::Inquirer::handleRemoteAck (Response::Pointer response) private inherited
Definition at line 118 of file Inquirer.cc.
References debugs, and Must.
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
inquire()
void Ipc::Inquirer::inquire () protected virtual inherited
Definition at line 95 of file Inquirer.cc.
References debugs, eventAdd(), Ipc::Port::MakeAddr(), Must, Ipc::Inquirer::RequestTimedOut(), Ipc::SendMessage(), Ipc::strandAddrLabel, and Ipc::TheWaitingInquirers.
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteCommClosed()
void Snmp::Inquirer::noteCommClosed (const CommCloseCbParams & params) private
Definition at line 87 of file Inquirer.cc.
References CommCommonCbParams::conn, debugs, Comm::Connection::fd, Comm::IsConnOpen(), Must, and MYNAME.
Referenced by Inquirer().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
removeTimeoutEvent()
void Ipc::Inquirer::removeTimeoutEvent () private inherited
Definition at line 186 of file Inquirer.cc.
References eventDelete(), eventFind(), and Ipc::Inquirer::RequestTimedOut().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
requestTimedOut()
void Ipc::Inquirer::requestTimedOut () private inherited
Definition at line 207 of file Inquirer.cc.
References debugs, Ipc::DequeueRequest(), Must, and MYNAME.
RequestTimedOut()
void Ipc::Inquirer::RequestTimedOut (void * param) static private inherited
Definition at line 194 of file Inquirer.cc.
References CallBack(), Ipc::Inquirer::codeContext, debugs, Must, and MYNAME.
Referenced by Ipc::Inquirer::inquire(), and Ipc::Inquirer::removeTimeoutEvent().
sendResponse()
void Snmp::Inquirer::sendResponse () override protected virtual
Implements Ipc::Inquirer.
Definition at line 106 of file Inquirer.cc.
References Snmp::Request::address, comm_udp_sendto(), DBG_IMPORTANT, debugs, Comm::IsConnOpen(), MYNAME, Snmp::Request::session, snmp_build(), SNMP_PDU_RESPONSE, and SNMP_REQUEST_SIZE.
start()
void Snmp::Inquirer::start () override protected virtual
Reimplemented from Ipc::Inquirer.
Definition at line 57 of file Inquirer.cc.
References debugs, Comm::IsConnOpen(), Must, MYNAME, and Ipc::Inquirer::start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
status()
const char * Ipc::Inquirer::status () const override protected virtual inherited
for debugging, starts with space
Reimplemented from AsyncJob.
Definition at line 220 of file Inquirer.cc.
References Packable::appendf(), MemBuf::content(), MemBuf::reset(), and MemBuf::terminate().
swanSong()
void Ipc::Inquirer::swanSong () override protected virtual inherited
Reimplemented from AsyncJob.
Definition at line 133 of file Inquirer.cc.
References debugs, Ipc::DequeueRequest(), and MYNAME.
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
Member Data Documentation
aggrPdu
Pdu Snmp::Inquirer::aggrPdu private
Definition at line 48 of file Inquirer.h.
closer
AsyncCall::Pointer Snmp::Inquirer::closer private
Definition at line 52 of file Inquirer.h.
Referenced by Inquirer().
codeContext
CodeContextPointer Ipc::Inquirer::codeContext inherited
Definition at line 41 of file Inquirer.h.
Referenced by Ipc::Inquirer::RequestTimedOut().
conn
Comm::ConnectionPointer Snmp::Inquirer::conn private
Definition at line 49 of file Inquirer.h.
Referenced by Inquirer().
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
LastRequestId
Ipc::RequestId::Index Ipc::Inquirer::LastRequestId = 0 static protected inherited
Definition at line 76 of file Inquirer.h.
pos
Ipc::StrandCoords::const_iterator Ipc::Inquirer::pos protected inherited
Definition at line 72 of file Inquirer.h.
request
Request::Pointer Ipc::Inquirer::request protected inherited
Definition at line 69 of file Inquirer.h.
Referenced by Inquirer().
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
strands
Ipc::StrandCoords Ipc::Inquirer::strands protected inherited
Definition at line 71 of file Inquirer.h.
Referenced by Ipc::Inquirer::Inquirer().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
timeout
const double Ipc::Inquirer::timeout protected inherited
Definition at line 74 of file Inquirer.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
writer
AsyncCall::Pointer Snmp::Inquirer::writer private
Definition at line 51 of file Inquirer.h.
The documentation for this class was generated from the following files:
squid/src/snmp/Inquirer.h
squid/src/snmp/Inquirer.cc