Squid Web Cache: Adaptation::AccessCheck Class Reference
Adaptation::AccessCheck Class Reference abstract
#include <AccessCheck.h>
Public Types
typedef void AccessCheckCallback(ServiceGroupPointer group, void *data)
typedef CbcPointer< AsyncJob > Pointer
Public Member Functions
void checkCandidates ()
void noteAnswer (Acl::Answer answer)
process the results of the ACL check
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static bool Start (Method method, VectPoint vp, HttpRequest *req, HttpReply *, const AccessLogEntryPointer &, Adaptation::Initiator *)
static void AccessCheckCallbackWrapper (Acl::Answer, void *)
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
AccessCheck (const ServiceFilter &aFilter, Adaptation::Initiator *)
~AccessCheck () override
void start () override
called by AsyncStart; do not call directly
bool doneAll () const override
whether positive goal has been reached
bool usedDynamicRules ()
not done until mustStop
void check ()
Walk the access rules list to find rules with applicable service groups.
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual void swanSong ()
virtual const char * status () const
internal cleanup; do not call directly
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Types
typedef int Candidate
typedef std::vector< Candidate > Candidates
Private Member Functions
CBDATA_CHILD (AccessCheck)
Candidate topCandidate () const
ServiceGroupPointer topGroup () const
void callBack (const ServiceGroupPointer &g)
bool isCandidate (AccessRule &r)
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
const ServiceFilter filter
CbcPointer< Adaptation::Initiator > theInitiator
the job which ordered this access check
Candidates candidates
Detailed Description
Definition at line 30 of file AccessCheck.h.
Member Typedef Documentation
AccessCheckCallback
typedef void Adaptation::AccessCheck::AccessCheckCallback(ServiceGroupPointer group, void *data)
Definition at line 35 of file AccessCheck.h.
Candidate
typedef int Adaptation::AccessCheck::Candidate private
Definition at line 50 of file AccessCheck.h.
Candidates
typedef std::vector<Candidate> Adaptation::AccessCheck::Candidates private
Definition at line 51 of file AccessCheck.h.
Pointer
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Constructor & Destructor Documentation
AccessCheck()
Adaptation::AccessCheck::AccessCheck (const ServiceFilter & aFilter, Adaptation::Initiator * initiator) protected
Definition at line 46 of file AccessCheck.cc.
References debugs, filter, HttpRequest::icapHistory(), and Adaptation::ServiceFilter::request.
~AccessCheck()
Adaptation::AccessCheck::~AccessCheck () override protected
Definition at line 60 of file AccessCheck.cc.
Member Function Documentation
AccessCheckCallbackWrapper()
void Adaptation::AccessCheck::AccessCheckCallbackWrapper (Acl::Answer answer, void * data) static
Definition at line 148 of file AccessCheck.cc.
References asyncCall(), debugs, noteAnswer(), and ScheduleCallHere.
callBack()
void Adaptation::AccessCheck::callBack (const ServiceGroupPointer & g) private
call back with a possibly nil group; the job ends here because all failures at this point are fatal to the access check process
Definition at line 191 of file AccessCheck.cc.
References CallJobHere1, and debugs.
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
CBDATA_CHILD()
Adaptation::AccessCheck::CBDATA_CHILD (AccessCheck) private
check()
void Adaptation::AccessCheck::check () protected
Definition at line 102 of file AccessCheck.cc.
References Adaptation::AllRules(), debugs, and Adaptation::AccessRule::id.
checkCandidates()
void Adaptation::AccessCheck::checkCandidates ()
Definition at line 124 of file AccessCheck.cc.
References debugs, Adaptation::FindRule(), ACLFilledChecklist::Make(), Must, and ACLFilledChecklist::NonBlockingCheck().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Adaptation::AccessCheck::doneAll () const inline override protected virtual
Reimplemented from AsyncJob.
Definition at line 67 of file AccessCheck.h.
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
isCandidate()
bool Adaptation::AccessCheck::isCandidate (AccessRule & r) private
Returns true iff the rule's service group will be used after ACL matches. Used to detect rules worth ACl-checking.
Definition at line 220 of file AccessCheck.cc.
References debugs, Adaptation::FindGroup(), Adaptation::AccessRule::groupId, Adaptation::AccessRule::id, and Adaptation::ServiceGroup::wants().
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteAnswer()
void Adaptation::AccessCheck::noteAnswer (Acl::Answer answer)
Definition at line 169 of file AccessCheck.cc.
References Acl::Answer::allowed(), debugs, and Must.
Referenced by AccessCheckCallbackWrapper().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
start()
void Adaptation::AccessCheck::start () override protected virtual
Reimplemented from AsyncJob.
Definition at line 70 of file AccessCheck.cc.
References AsyncJob::start().
Start() [1/2]
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
Start() [2/2]
bool Adaptation::AccessCheck::Start (Method method, VectPoint vp, HttpRequest * req, HttpReply * rep, const AccessLogEntryPointer & al, Adaptation::Initiator * initiator) static
Definition at line 30 of file AccessCheck.cc.
References debugs, Adaptation::Config::Enabled, and AsyncJob::Start().
Referenced by Client::adaptOrFinalizeReply(), and ClientHttpRequest::doCallouts().
status()
const char * AsyncJob::status () const protected virtual inherited
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), AsyncJob::stopReason, and MemBuf::terminate().
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
swanSong()
virtual void AsyncJob::swanSong () inline protected virtual inherited
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::ModXactLauncher, Adaptation::Icap::OptXact, Adaptation::Icap::Xaction, Adaptation::Initiate, Adaptation::Iterator, ConnStateData, Client, Ftp::Relay, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, Ipc::Forwarder, Ipc::Inquirer, Ipc::UdsSender, Log::TcpLogger, Mgr::Filler, Mgr::Forwarder, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Server, and Snmp::Forwarder.
Definition at line 61 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), Client::swanSong(), Ftp::Relay::swanSong(), Http::Tunneler::swanSong(), Comm::ConnOpener::swanSong(), Comm::TcpAcceptor::swanSong(), Rock::HeaderUpdater::swanSong(), HappyConnOpener::swanSong(), Ipc::UdsSender::swanSong(), Log::TcpLogger::swanSong(), PeerPoolMgr::swanSong(), Security::PeerConnector::swanSong(), and Server::swanSong().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
topCandidate()
Candidate Adaptation::AccessCheck::topCandidate () const inline private
Definition at line 53 of file AccessCheck.h.
References candidates.
topGroup()
Adaptation::ServiceGroupPointer Adaptation::AccessCheck::topGroup () const private
Definition at line 200 of file AccessCheck.cc.
References debugs, Adaptation::FindGroup(), and Adaptation::FindRule().
usedDynamicRules()
bool Adaptation::AccessCheck::usedDynamicRules () protected
returns true if previous services configured dynamic chaining "rules"
Definition at line 80 of file AccessCheck.cc.
References debugs, Adaptation::History::extractCurrentServices(), and Must.
Member Data Documentation
candidates
Candidates Adaptation::AccessCheck::candidates private
Definition at line 52 of file AccessCheck.h.
Referenced by topCandidate().
filter
const ServiceFilter Adaptation::AccessCheck::filter private
Definition at line 47 of file AccessCheck.h.
Referenced by AccessCheck().
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
theInitiator
CbcPointer<Adaptation::Initiator> Adaptation::AccessCheck::theInitiator private
Definition at line 48 of file AccessCheck.h.
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
The documentation for this class was generated from the following files:
squid/src/adaptation/AccessCheck.h
squid/src/adaptation/AccessCheck.cc