Squid Web Cache: ACLTimeData Class Reference
ACLTimeData Class Reference
#include <TimeData.h>
Public Member Functions
ACLTimeData ()
~ACLTimeData () override
bool match (time_t) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Private Member Functions
MEMPROXY_CLASS (ACLTimeData)
Private Attributes
int weekbits
int start
int stop
ACLTimeData * next
Detailed Description
Definition at line 15 of file TimeData.h.
Constructor & Destructor Documentation
ACLTimeData()
ACLTimeData::ACLTimeData ()
Definition at line 30 of file TimeData.cc.
Referenced by parse().
~ACLTimeData()
ACLTimeData::~ACLTimeData () override
Definition at line 32 of file TimeData.cc.
References next.
Member Function Documentation
dump()
SBufList ACLTimeData::dump () const override virtual
Implements ACLData< time_t >.
Definition at line 69 of file TimeData.cc.
References ACL_FRIDAY, ACL_MONDAY, ACL_SATURDAY, ACL_SUNDAY, ACL_THURSDAY, ACL_TUESDAY, ACL_WEDNESDAY, next, SBuf::Printf(), SBuf::push_back(), start, stop, and weekbits.
empty()
bool ACLTimeData::empty () const override virtual
Implements ACLData< time_t >.
Definition at line 215 of file TimeData.cc.
lineOptions()
virtual const Acl::Options & ACLData< time_t >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLTimeData::match (time_t when) override virtual
Implements ACLData< time_t >.
Definition at line 39 of file TimeData.cc.
References asHex(), debugs, next, start, stop, and weekbits.
MEMPROXY_CLASS()
ACLTimeData::MEMPROXY_CLASS (ACLTimeData) private
parse()
void ACLTimeData::parse () override virtual
Implements ACLData< time_t >.
Definition at line 93 of file TimeData.cc.
References ACLTimeData(), ACL_ALLWEEK, ACL_FRIDAY, ACL_MONDAY, ACL_SATURDAY, ACL_SUNDAY, ACL_THURSDAY, ACL_TUESDAY, ACL_WEDNESDAY, ACL_WEEKDAYS, cfg_filename, config_input_line, config_lineno, DBG_CRITICAL, debugs, next, self_destruct(), start, stop, ConfigParser::strtokFile(), and weekbits.
prepareForUse()
virtual void ACLData< time_t >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
next
ACLTimeData* ACLTimeData::next private
Definition at line 31 of file TimeData.h.
Referenced by ~ACLTimeData(), dump(), match(), and parse().
start
int ACLTimeData::start private
Definition at line 29 of file TimeData.h.
Referenced by dump(), match(), and parse().
stop
int ACLTimeData::stop private
Definition at line 30 of file TimeData.h.
Referenced by dump(), match(), and parse().
weekbits
int ACLTimeData::weekbits private
Definition at line 28 of file TimeData.h.
Referenced by dump(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/TimeData.h
squid/src/acl/TimeData.cc