Squid Web Cache: TestHttp1Parser Class Reference
TestHttp1Parser Class Reference
Protected Member Functions
void globalSetup ()
void testParserConstruct ()
void testParseRequestLineTerminators ()
void testParseRequestLineMethods ()
void testParseRequestLineProtocols ()
void testParseRequestLineStrange ()
void testParseRequestLineInvalid ()
void testDripFeed ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestHttp1Parser)
CPPUNIT_TEST (testParserConstruct)
CPPUNIT_TEST (testDripFeed)
CPPUNIT_TEST (testParseRequestLineMethods)
CPPUNIT_TEST (testParseRequestLineProtocols)
CPPUNIT_TEST (testParseRequestLineTerminators)
CPPUNIT_TEST (testParseRequestLineStrange)
CPPUNIT_TEST (testParseRequestLineInvalid)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file testHttp1Parser.cc.
Member Function Documentation
CPPUNIT_TEST() [1/7]
TestHttp1Parser::CPPUNIT_TEST (testDripFeed) private
CPPUNIT_TEST() [2/7]
TestHttp1Parser::CPPUNIT_TEST (testParserConstruct) private
CPPUNIT_TEST() [3/7]
TestHttp1Parser::CPPUNIT_TEST (testParseRequestLineInvalid) private
CPPUNIT_TEST() [4/7]
TestHttp1Parser::CPPUNIT_TEST (testParseRequestLineMethods) private
CPPUNIT_TEST() [5/7]
TestHttp1Parser::CPPUNIT_TEST (testParseRequestLineProtocols) private
CPPUNIT_TEST() [6/7]
TestHttp1Parser::CPPUNIT_TEST (testParseRequestLineStrange) private
CPPUNIT_TEST() [7/7]
TestHttp1Parser::CPPUNIT_TEST (testParseRequestLineTerminators) private
CPPUNIT_TEST_SUITE()
TestHttp1Parser::CPPUNIT_TEST_SUITE (TestHttp1Parser) private
CPPUNIT_TEST_SUITE_END()
TestHttp1Parser::CPPUNIT_TEST_SUITE_END () private
globalSetup()
void TestHttp1Parser::globalSetup () protected
Definition at line 55 of file testHttp1Parser.cc.
References Config, Mem::Init(), SquidConfig::maxRequestHeaderSize, SquidConfig::onoff, and SquidConfig::relaxed_header_parser.
Referenced by testParseRequestLineInvalid(), testParseRequestLineMethods(), testParseRequestLineProtocols(), testParseRequestLineStrange(), and testParseRequestLineTerminators().
testDripFeed()
void TestHttp1Parser::testDripFeed () protected
Definition at line 1101 of file testHttp1Parser.cc.
References SBuf::append(), SBuf::clear(), Http::One::RequestParser::clear(), Config, Http::One::HTTP_PARSE_FIRST, Http::One::HTTP_PARSE_MIME, Http::One::HTTP_PARSE_NONE, SBuf::length(), SquidConfig::maxRequestHeaderSize, resultSet::method, Http::METHOD_GET, resultSet::needsMore, Http::One::Parser::needsMoreData(), SquidConfig::onoff, resultSet::parsed, resultSet::parserState, AnyP::PROTO_HTTP, SquidConfig::relaxed_header_parser, Http::One::Parser::remaining(), Http::scNone, Http::scOkay, resultSet::status, SBuf::substr(), resultSet::suffixSz, testResults(), resultSet::uri, and resultSet::version.
testParserConstruct()
void TestHttp1Parser::testParserConstruct () protected
Definition at line 152 of file testHttp1Parser.cc.
References Http::One::Parser::buf_, Http::One::HTTP_PARSE_NONE, SBuf::isEmpty(), Http::One::RequestParser::method_, Http::METHOD_NONE, Http::One::Parser::msgProtocol_, Http::One::Parser::needsMoreData(), Http::One::Parser::parseStatusCode, Http::One::Parser::parsingStage_, Http::scNone, and Http::One::RequestParser::uri_.
testParseRequestLineInvalid()
void TestHttp1Parser::testParseRequestLineInvalid () protected
Definition at line 911 of file testHttp1Parser.cc.
References SBuf::append(), SBuf::clear(), Http::One::RequestParser::clear(), Config, globalSetup(), Http::One::HTTP_PARSE_DONE, SBuf::length(), SquidConfig::onoff, resultSet::parsed, SquidConfig::relaxed_header_parser, Http::scBadRequest, and testResults().
testParseRequestLineMethods()
void TestHttp1Parser::testParseRequestLineMethods () protected
Definition at line 657 of file testHttp1Parser.cc.
References SBuf::append(), SBuf::clear(), Http::One::RequestParser::clear(), Config, globalSetup(), Http::One::HTTP_PARSE_DONE, Http::One::HTTP_PARSE_MIME, SBuf::length(), Http::METHOD_GET, Http::METHOD_OPTIONS, SquidConfig::onoff, resultSet::parsed, AnyP::PROTO_HTTP, SquidConfig::relaxed_header_parser, Http::scBadRequest, Http::scOkay, and testResults().
testParseRequestLineProtocols()
void TestHttp1Parser::testParseRequestLineProtocols () protected
Definition at line 181 of file testHttp1Parser.cc.
References SBuf::append(), SBuf::clear(), Http::One::RequestParser::clear(), globalSetup(), Http::One::HTTP_PARSE_DONE, Http::One::HTTP_PARSE_MIME, SBuf::length(), Http::METHOD_GET, Http::METHOD_POST, resultSet::parsed, AnyP::PROTO_HTTP, Http::scBadRequest, Http::scOkay, and testResults().
testParseRequestLineStrange()
void TestHttp1Parser::testParseRequestLineStrange () protected
Definition at line 463 of file testHttp1Parser.cc.
References SBuf::append(), SBuf::clear(), Http::One::RequestParser::clear(), Config, globalSetup(), Http::One::HTTP_PARSE_DONE, Http::One::HTTP_PARSE_MIME, SBuf::length(), Http::METHOD_GET, SquidConfig::onoff, resultSet::parsed, AnyP::PROTO_HTTP, SquidConfig::relaxed_header_parser, Http::scBadRequest, Http::scOkay, and testResults().
testParseRequestLineTerminators()
void TestHttp1Parser::testParseRequestLineTerminators () protected
Definition at line 559 of file testHttp1Parser.cc.
References SBuf::append(), SBuf::clear(), Http::One::RequestParser::clear(), Config, globalSetup(), Http::One::HTTP_PARSE_DONE, Http::One::HTTP_PARSE_MIME, SBuf::length(), Http::METHOD_GET, SquidConfig::onoff, resultSet::parsed, AnyP::PROTO_HTTP, SquidConfig::relaxed_header_parser, Http::scBadRequest, Http::scOkay, and testResults().
The documentation for this class was generated from the following file:
squid/src/tests/testHttp1Parser.cc