Squid Web Cache: ErrorPage::BuildErrorPrinter Class Reference
ErrorPage::BuildErrorPrinter Class Reference
pretty-prints error page/deny_info building error
Public Member Functions
BuildErrorPrinter (const SBuf &anInputLocation, int aPage, const char *aMsg, const char *anErrorLocation)
std::ostream & print (std::ostream &) const
reports error details (for admin-visible exceptions and debugging)
std::ostream & printLocation (std::ostream &os) const
print() helper to report where the error was found
Public Attributes
const SBuf & inputLocation
const int page_id
const char * msg
const char * errorLocation
Detailed Description
Definition at line 116 of file errorpage.cc.
Constructor & Destructor Documentation
BuildErrorPrinter()
ErrorPage::BuildErrorPrinter::BuildErrorPrinter (const SBuf & anInputLocation, int aPage, const char * aMsg, const char * anErrorLocation) inline
Definition at line 119 of file errorpage.cc.
Member Function Documentation
print()
std::ostream & ErrorPage::BuildErrorPrinter::print (std::ostream & os) const
Definition at line 1514 of file errorpage.cc.
References CurrentException().
Referenced by ErrorPage::operator<<().
printLocation()
std::ostream & ErrorPage::BuildErrorPrinter::printLocation (std::ostream & os) const
Definition at line 1500 of file errorpage.cc.
References SBuf::at(), ERR_MAX, err_type_str, error_page_count, ErrorDynamicPages, inputLocation, SBuf::isEmpty(), and page_id.
Member Data Documentation
errorLocation
const char* ErrorPage::BuildErrorPrinter::errorLocation
Definition at line 136 of file errorpage.cc.
inputLocation
const SBuf& ErrorPage::BuildErrorPrinter::inputLocation
Definition at line 133 of file errorpage.cc.
Referenced by printLocation().
msg
const char* ErrorPage::BuildErrorPrinter::msg
Definition at line 135 of file errorpage.cc.
page_id
const int ErrorPage::BuildErrorPrinter::page_id
Definition at line 134 of file errorpage.cc.
Referenced by printLocation().
The documentation for this class was generated from the following file:
squid/src/errorpage.cc