Squid Web Cache: RemovalPolicy Class Reference
RemovalPolicy Class Reference
#include <RemovalPolicy.h>
Public Member Functions
CBDATA_DECL_ (RemovalPolicy, noexcept)
Public Attributes
const char * _type
void * _data
void(* Free)(RemovalPolicy *policy)
void(* Add)(RemovalPolicy *policy, StoreEntry *entry, RemovalPolicyNode *node)
void(* Remove)(RemovalPolicy *policy, StoreEntry *entry, RemovalPolicyNode *node)
void(* Referenced)(RemovalPolicy *policy, const StoreEntry *entry, RemovalPolicyNode *node)
void(* Dereferenced)(RemovalPolicy *policy, const StoreEntry *entry, RemovalPolicyNode *node)
RemovalPolicyWalker *(* WalkInit)(RemovalPolicy *policy)
RemovalPurgeWalker *(* PurgeInit)(RemovalPolicy *policy, int max_scan)
void(* Stats)(RemovalPolicy *policy, StoreEntry *entry)
Detailed Description
Definition at line 38 of file RemovalPolicy.h.
Member Function Documentation
CBDATA_DECL_()
RemovalPolicy::CBDATA_DECL_ (RemovalPolicy , noexcept)
Member Data Documentation
_data
void* RemovalPolicy::_data
Definition at line 44 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), createRemovalPolicy_lru(), heap_add(), heap_free(), heap_purgeDone(), heap_purgeInit(), heap_purgeNext(), heap_referenced(), heap_remove(), heap_walkDone(), heap_walkInit(), heap_walkNext(), lru_add(), lru_free(), lru_purgeDone(), lru_purgeInit(), lru_purgeNext(), lru_referenced(), lru_remove(), lru_stats(), lru_walkDone(), and lru_walkInit().
_type
const char* RemovalPolicy::_type
Definition at line 43 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), createRemovalPolicy_lru(), heap_free(), heap_purgeDone(), heap_walkDone(), lru_free(), lru_purgeDone(), and lru_walkDone().
Add
void(* RemovalPolicy::Add) (RemovalPolicy *policy, StoreEntry *entry, RemovalPolicyNode *node)
Definition at line 46 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), createRemovalPolicy_lru(), and StoreEntry::setMemStatus().
Dereferenced
void(* RemovalPolicy::Dereferenced) (RemovalPolicy *policy, const StoreEntry *entry, RemovalPolicyNode *node)
Definition at line 49 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), createRemovalPolicy_lru(), and Store::Controller::dereferenceIdle().
Free
void(* RemovalPolicy::Free) (RemovalPolicy *policy)
Definition at line 45 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), and createRemovalPolicy_lru().
PurgeInit
RemovalPurgeWalker *(* RemovalPolicy::PurgeInit) (RemovalPolicy *policy, int max_scan)
Definition at line 51 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), createRemovalPolicy_lru(), and Store::Controller::freeMemorySpace().
Referenced
void(* RemovalPolicy::Referenced) (RemovalPolicy *policy, const StoreEntry *entry, RemovalPolicyNode *node)
Definition at line 48 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), createRemovalPolicy_lru(), and Store::Controller::referenceBusy().
Remove
void(* RemovalPolicy::Remove) (RemovalPolicy *policy, StoreEntry *entry, RemovalPolicyNode *node)
Definition at line 47 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), createRemovalPolicy_lru(), and StoreEntry::setMemStatus().
Stats
void(* RemovalPolicy::Stats) (RemovalPolicy *policy, StoreEntry *entry)
Definition at line 52 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_lru().
WalkInit
RemovalPolicyWalker *(* RemovalPolicy::WalkInit) (RemovalPolicy *policy)
Definition at line 50 of file RemovalPolicy.h.
Referenced by createRemovalPolicy_heap(), and createRemovalPolicy_lru().
The documentation for this class was generated from the following file:
squid/src/RemovalPolicy.h