Squid Web Cache: ACLNoteData Class Reference
ACLNoteData Class Reference
Squid Components » Access Controls
#include <NoteData.h>
Public Member Functions
ACLNoteData ()
~ACLNoteData () override
bool match (NotePairs::Entry *) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Private Member Functions
MEMPROXY_CLASS (ACLNoteData)
Private Attributes
SBuf name
Note name to check. It is always set.
ACLStringData * values
if set, at least one value must match
Detailed Description
Definition at line 19 of file NoteData.h.
Constructor & Destructor Documentation
ACLNoteData()
ACLNoteData::ACLNoteData ()
Definition at line 19 of file NoteData.cc.
~ACLNoteData()
ACLNoteData::~ACLNoteData () override
Definition at line 22 of file NoteData.cc.
References values.
Member Function Documentation
dump()
SBufList ACLNoteData::dump () const override virtual
Implements ACLData< NotePairs::Entry * >.
Definition at line 39 of file NoteData.cc.
References ACLStringData::dump(), name, and values.
empty()
bool ACLNoteData::empty () const override virtual
Implements ACLData< NotePairs::Entry * >.
Definition at line 55 of file NoteData.cc.
References SBuf::isEmpty(), and name.
lineOptions()
virtual const Acl::Options & ACLData< NotePairs::Entry * >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLNoteData::match (NotePairs::Entry * entry) override virtual
Implements ACLData< NotePairs::Entry * >.
Definition at line 28 of file NoteData.cc.
References SBuf::cmp(), ACLStringData::empty(), ACLStringData::match(), name, NotePairs::Entry::name(), NotePairs::Entry::value(), and values.
MEMPROXY_CLASS()
ACLNoteData::MEMPROXY_CLASS (ACLNoteData) private
parse()
void ACLNoteData::parse () override virtual
Implements ACLData< NotePairs::Entry * >.
Definition at line 48 of file NoteData.cc.
References name, ACLStringData::parse(), Acl::SetKey(), ConfigParser::strtokFile(), and values.
prepareForUse()
virtual void ACLData< NotePairs::Entry * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
name
SBuf ACLNoteData::name private
Definition at line 32 of file NoteData.h.
Referenced by dump(), empty(), match(), and parse().
values
ACLStringData* ACLNoteData::values private
Definition at line 33 of file NoteData.h.
Referenced by ~ACLNoteData(), dump(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/NoteData.h
squid/src/acl/NoteData.cc