Squid Web Cache: XactionInitiator Class Reference
XactionInitiator Class Reference
identifies a protocol agent or Squid feature initiating transactions
#include <XactionInitiator.h>
Public Types
enum Initiator {
initUnknown = 0 , initClient = 1 << 0 , initPeerPool = 1 << 1 , initCertFetcher = 1 << 2 ,
initCacheDigest = 1 << 4 , initHtcp = 1<< 5 , initIcp = 1 << 6 , initIcmp = 1 << 7 ,
initIpc = 1 << 9 , initAdaptation = 1 << 10 , initIcon = 1 << 11 , initPeerMcast = 1 << 12 ,
initServer = 1 << 13 , initAdaptationOrphan_ = 1 << 31
}
transaction triggers
typedef uint32_t Initiators
Initiator set.
Public Member Functions
XactionInitiator (Initiator i)
bool in (Initiators setOfInitiators) const
whether this initiator belongs to the given set
bool internalClient () const
whether the transaction was initiated by an internal subsystem
Static Public Member Functions
static Initiators InternalInitiators ()
internally generated requests
static Initiators AllInitiators ()
all initiators
static Initiators ParseInitiators (const char *name)
Private Member Functions
XactionInitiator ()
Private Attributes
Initiator initiator
Detailed Description
Definition at line 13 of file XactionInitiator.h.
Member Typedef Documentation
Initiators
typedef uint32_t XactionInitiator::Initiators
Definition at line 34 of file XactionInitiator.h.
Member Enumeration Documentation
Initiator
enum XactionInitiator::Initiator
Enumerator
initUnknown
initClient
HTTP or FTP client.
initPeerPool
PeerPool manager.
initCertFetcher
Missing intermediate certificates fetching code.
initCacheDigest
Cache Digest fetching code.
initHtcp
HTCP client.
initIcp
the ICP/neighbors subsystem
initIcmp
the ICMP RTT database (NetDB) neighbors exchange subsystem
initIpc
the IPC subsystem
initAdaptation
ICAP/ECAP requests generated by Squid.
initIcon
internal icons
initPeerMcast
neighbor multicast
initServer
HTTP/2 push request (not yet supported by Squid)
initAdaptationOrphan_
eCAP-created HTTP message w/o an associated HTTP transaction (not ACL-detectable)
Definition at line 16 of file XactionInitiator.h.
Constructor & Destructor Documentation
XactionInitiator() [1/2]
XactionInitiator::XactionInitiator (Initiator i) inline
Definition at line 37 of file XactionInitiator.h.
XactionInitiator() [2/2]
XactionInitiator::XactionInitiator () inline private
Definition at line 60 of file XactionInitiator.h.
Member Function Documentation
AllInitiators()
static Initiators XactionInitiator::AllInitiators () inline static
Definition at line 53 of file XactionInitiator.h.
Referenced by ParseInitiators().
in()
bool XactionInitiator::in (Initiators setOfInitiators) const inline
Definition at line 40 of file XactionInitiator.h.
References initiator.
Referenced by Acl::TransactionInitiator::match().
internalClient()
bool XactionInitiator::internalClient () const inline
Definition at line 43 of file XactionInitiator.h.
References initiator, and InternalInitiators().
InternalInitiators()
static Initiators XactionInitiator::InternalInitiators () inline static
Definition at line 48 of file XactionInitiator.h.
References initAdaptation, initCacheDigest, initCertFetcher, initIcmp, initIcon, initIcp, initIpc, initPeerMcast, and initPeerPool.
Referenced by internalClient(), and ParseInitiators().
ParseInitiators()
XactionInitiator::Initiators XactionInitiator::ParseInitiators (const char * name) static
Definition at line 18 of file XactionInitiator.cc.
References AllInitiators(), DBG_CRITICAL, debugs, initAdaptation, initCacheDigest, initCertFetcher, initClient, initHtcp, initIcmp, initIcon, initIcp, initIpc, initPeerMcast, initPeerPool, initServer, InternalInitiators(), and self_destruct().
Referenced by Acl::TransactionInitiator::parse().
Member Data Documentation
initiator
Initiator XactionInitiator::initiator private
Definition at line 62 of file XactionInitiator.h.
Referenced by in(), and internalClient().
The documentation for this class was generated from the following files:
squid/src/XactionInitiator.h
squid/src/XactionInitiator.cc