Squid Web Cache: AsyncCallList Class Reference
AsyncCallList Class Reference
#include <AsyncCallList.h>
Public Member Functions
AsyncCallList ()=default
AsyncCallList (const AsyncCallList &)=delete
AsyncCallList & operator= (const AsyncCallList &)=delete
void add (const AsyncCallPointer &)
stores the given async call
AsyncCallPointer extract ()
size_t size () const
the number of currently stored calls
Private Attributes
AsyncCallPointer head
the earliest still-stored call (or nil)
AsyncCallPointer tail
the latest still-stored call (or nil)
size_t length = 0
Detailed Description
An efficient (but intrusive) AsyncCall storage preserving FIFO order. A given AsyncCall object may reside in at most one such storage.
Definition at line 17 of file AsyncCallList.h.
Constructor & Destructor Documentation
AsyncCallList() [1/2]
AsyncCallList::AsyncCallList () default
AsyncCallList() [2/2]
AsyncCallList::AsyncCallList (const AsyncCallList &) delete
Member Function Documentation
add()
void AsyncCallList::add (const AsyncCallPointer & call)
Definition at line 15 of file AsyncCallList.cc.
References Assure, head, length, AsyncCall::Next(), AsyncCall::setNext(), and tail.
Referenced by DelayedAsyncCalls::delay(), and AsyncCallQueue::schedule().
extract()
AsyncCall::Pointer AsyncCallList::extract ()
removes the earliest add()-ed call that is still stored (if any)
Returns
the removed call (or nil)
Return values
nil means the list stored no calls at extract() time
Definition at line 33 of file AsyncCallList.cc.
References Assure, head, length, AsyncCall::Next(), AsyncCall::setNext(), and tail.
Referenced by AsyncCallQueue::fire(), and DelayedAsyncCalls::schedule().
operator=()
AsyncCallList & AsyncCallList::operator= (const AsyncCallList &) delete
size()
size_t AsyncCallList::size () const inline
Definition at line 34 of file AsyncCallList.h.
References length.
Referenced by DelayedAsyncCalls::delay(), and AsyncCallQueue::fire().
Member Data Documentation
head
AsyncCallPointer AsyncCallList::head private
Definition at line 37 of file AsyncCallList.h.
Referenced by add(), and extract().
length
size_t AsyncCallList::length = 0 private
maximum number of elements in array
Definition at line 39 of file AsyncCallList.h.
Referenced by add(), extract(), and size().
tail
AsyncCallPointer AsyncCallList::tail private
Definition at line 38 of file AsyncCallList.h.
Referenced by add(), and extract().
The documentation for this class was generated from the following files:
squid/src/base/AsyncCallList.h
squid/src/base/AsyncCallList.cc