Squid Web Cache: TestStoreHashIndex Class Reference
TestStoreHashIndex Class Reference
Protected Member Functions
void testStats ()
void testMaxSize ()
void testSearch ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestStoreHashIndex)
CPPUNIT_TEST (testStats)
CPPUNIT_TEST (testMaxSize)
CPPUNIT_TEST (testSearch)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 22 of file testStoreHashIndex.cc.
Member Function Documentation
CPPUNIT_TEST() [1/3]
TestStoreHashIndex::CPPUNIT_TEST (testMaxSize) private
CPPUNIT_TEST() [2/3]
TestStoreHashIndex::CPPUNIT_TEST (testSearch) private
CPPUNIT_TEST() [3/3]
TestStoreHashIndex::CPPUNIT_TEST (testStats) private
CPPUNIT_TEST_SUITE()
TestStoreHashIndex::CPPUNIT_TEST_SUITE (TestStoreHashIndex) private
CPPUNIT_TEST_SUITE_END()
TestStoreHashIndex::CPPUNIT_TEST_SUITE_END () private
testMaxSize()
void TestStoreHashIndex::testMaxSize () protected
Definition at line 65 of file testStoreHashIndex.cc.
References addSwapDir(), SquidConfig::cacheSwap, Config, StoreEntry::createMemObject(), free_cachedir(), Store::Root(), STORE_PENDING, and StoreEntry::store_status.
testSearch()
void TestStoreHashIndex::testSearch () protected
Definition at line 143 of file testStoreHashIndex.cc.
References addedEntry(), addSwapDir(), cbcalled, commonInit(), StoreSearch::currentItem(), StoreSearch::error(), RefCount< C >::getRaw(), Store::Controller::init(), StoreSearch::isDone(), StoreSearch::next(), Store::Root(), Store::Controller::search(), and searchCallback().
testStats()
void TestStoreHashIndex::testStats () protected
Definition at line 47 of file testStoreHashIndex.cc.
References addSwapDir(), SquidConfig::cacheSwap, Config, StoreEntry::createMemObject(), free_cachedir(), Store::Stats(), STORE_PENDING, and StoreEntry::store_status.
The documentation for this class was generated from the following file:
squid/src/tests/testStoreHashIndex.cc