Squid Web Cache: Mgr::IntervalAction Class Reference
Mgr::IntervalAction Class Reference
implement aggregated interval actions
#include <IntervalAction.h>
Public Types
typedef RefCount< Action > Pointer
Public Member Functions
void add (const Action &action) override
incrementally merge in remote information (of the same action type)
void pack (Ipc::TypedMsgHdr &msg) const override
pack collected action info into a message to be sent to Coordinator
void unpack (const Ipc::TypedMsgHdr &msg) override
unpack action info from the message received by Coordinator
void run (StoreEntry *entry, bool writeHttpHeader)
collect + fillEntry: collect local information and fill the store entry
void fillEntry (StoreEntry *entry, bool writeHttpHeader)
prepare store entry, dump info, close store entry (if possible)
virtual void respond (const Request &request)
respond to Coordinator request; default is to collect and sendResponse
void sendResponse (Ipc::RequestId)
notify Coordinator that this action is done with local processing
virtual bool aggregatable () const
virtual Format format () const
action report syntax
bool atomic () const
dump() call writes everything before returning
const char * name () const
label as seen in the cache manager menu
const Command & command () const
the cause of this action
StoreEntry * createStoreEntry () const
creates store entry from params
const char * contentType () const
HTTP Content-Type header value for this Action report.
Static Public Member Functions
static Pointer Create5min (const CommandPointer &cmd)
static Pointer Create60min (const CommandPointer &cmd)
Protected Member Functions
IntervalAction (const CommandPointer &cmd, int aMinutes, int aHours)
void collect () override
calculate and keep local action-specific information
void dump (StoreEntry *entry) override
Private Attributes
int minutes
int hours
IntervalActionData data
const CommandPointer cmd
the command that caused this action
Detailed Description
Definition at line 110 of file IntervalAction.h.
Member Typedef Documentation
Pointer
typedef RefCount<Action> Mgr::Action::Pointer inherited
Definition at line 28 of file Action.h.
Constructor & Destructor Documentation
IntervalAction()
Mgr::IntervalAction::IntervalAction (const CommandPointer & cmd, int aMinutes, int aHours) protected
Definition at line 128 of file IntervalAction.cc.
References debugs, and MYNAME.
Member Function Documentation
add()
void Mgr::IntervalAction::add (const Action & action) override virtual
Reimplemented from Mgr::Action.
Definition at line 135 of file IntervalAction.cc.
References debugs, and MYNAME.
aggregatable()
virtual bool Mgr::Action::aggregatable () const inline virtual inherited
whether at least some local kid info can be combined and, hence, the combined data should be written at the end of the coordinated response
Reimplemented in Mgr::FunAction, and Ssl::CertificateStorageAction.
Definition at line 65 of file Action.h.
atomic()
bool Mgr::Action::atomic () const inherited
Definition at line 44 of file Action.cc.
collect()
void Mgr::IntervalAction::collect () override protected virtual
Reimplemented from Mgr::Action.
Definition at line 142 of file IntervalAction.cc.
References GetAvgStat().
command()
const Mgr::Command & Mgr::Action::command () const inherited
Definition at line 37 of file Action.cc.
References Must.
contentType()
const char * Mgr::Action::contentType () const inherited
Definition at line 62 of file Action.cc.
References assert, Mgr::informal, and Mgr::yaml.
Create5min()
Mgr::IntervalAction::Pointer Mgr::IntervalAction::Create5min (const CommandPointer & cmd) static
Definition at line 117 of file IntervalAction.cc.
Referenced by statRegisterWithCacheManager().
Create60min()
Mgr::IntervalAction::Pointer Mgr::IntervalAction::Create60min (const CommandPointer & cmd) static
Definition at line 123 of file IntervalAction.cc.
Referenced by statRegisterWithCacheManager().
createStoreEntry()
StoreEntry * Mgr::Action::createStoreEntry () const inherited
Definition at line 75 of file Action.cc.
References Mgr::ActionParams::httpFlags, Mgr::ActionParams::httpMethod, Mgr::ActionParams::httpUri, storeCreateEntry(), and String::termedBuf().
dump()
void Mgr::IntervalAction::dump (StoreEntry *) override protected virtual
start writing action-specific info to Store entry; may collect info during dump, especially if collect() did nothing non-atomic() actions may continue writing asynchronously after returning
Reimplemented from Mgr::Action.
Definition at line 148 of file IntervalAction.cc.
References debugs, DumpAvgStat(), Must, and MYNAME.
fillEntry()
void Mgr::Action::fillEntry (StoreEntry * entry, bool writeHttpHeader) inherited
Definition at line 119 of file Action.cc.
References StoreEntry::buffer(), StoreEntry::complete(), debugs, StoreEntry::flush(), MYNAME, CacheManager::PutCommonResponseHeaders(), StoreEntry::replaceHttpReply(), Http::scOkay, HttpReply::setHeaders(), and squid_curtime.
format()
Mgr::Format Mgr::Action::format () const virtual inherited
Definition at line 50 of file Action.cc.
name()
const char * Mgr::Action::name () const inherited
Definition at line 56 of file Action.cc.
pack()
void Mgr::IntervalAction::pack (Ipc::TypedMsgHdr &) const override virtual
Reimplemented from Mgr::Action.
Definition at line 156 of file IntervalAction.cc.
References Ipc::mtCacheMgrResponse, Ipc::TypedMsgHdr::putPod(), and Ipc::TypedMsgHdr::setType().
respond()
void Mgr::Action::respond (const Request & request) virtual inherited
Reimplemented in Mgr::FunAction, and Mgr::InfoAction.
Definition at line 88 of file Action.cc.
References Mgr::Request::conn, debugs, Comm::Connection::fd, MYNAME, Ipc::Request::requestId, and xclose().
run()
void Mgr::Action::run (StoreEntry * entry, bool writeHttpHeader) inherited
Definition at line 111 of file Action.cc.
References debugs, and MYNAME.
sendResponse()
void Mgr::Action::sendResponse (Ipc::RequestId requestId) inherited
Definition at line 102 of file Action.cc.
References Ipc::Port::CoordinatorAddr(), Mgr::Response::pack(), and Ipc::SendMessage().
unpack()
void Mgr::IntervalAction::unpack (const Ipc::TypedMsgHdr &) override virtual
Reimplemented from Mgr::Action.
Definition at line 163 of file IntervalAction.cc.
References Ipc::TypedMsgHdr::checkType(), Ipc::TypedMsgHdr::getPod(), and Ipc::mtCacheMgrResponse.
Member Data Documentation
cmd
const CommandPointer Mgr::Action::cmd private inherited
Definition at line 90 of file Action.h.
Referenced by Mgr::Action::Action(), Mgr::IndexAction::Create(), and SBufStatsAction::Create().
data
IntervalActionData Mgr::IntervalAction::data private
Definition at line 131 of file IntervalAction.h.
hours
int Mgr::IntervalAction::hours private
Definition at line 130 of file IntervalAction.h.
minutes
int Mgr::IntervalAction::minutes private
Definition at line 129 of file IntervalAction.h.
The documentation for this class was generated from the following files:
squid/src/mgr/IntervalAction.h
squid/src/mgr/IntervalAction.cc