Squid Web Cache: DelayPool Class Reference
DelayPool Class Reference
Squid Components » Delay Pools API
#include <DelayPool.h>
Public Member Functions
DelayPool ()
~DelayPool ()
void freeData ()
void createPool (u_char delay_class)
void parse ()
void dump (StoreEntry *, unsigned int poolNumberMinusOne) const
CompositePoolNode::Pointer theComposite ()
CompositePoolNode::Pointer const theComposite () const
Public Attributes
CommonPool * pool
acl_access * access
Private Attributes
CompositePoolNode::Pointer theComposite_
Detailed Description
Definition at line 23 of file DelayPool.h.
Constructor & Destructor Documentation
DelayPool()
DelayPool::DelayPool ()
Definition at line 20 of file DelayPool.cc.
References CommonPool::Factory(), pool, and theComposite_.
~DelayPool()
DelayPool::~DelayPool ()
Definition at line 25 of file DelayPool.cc.
References access, aclDestroyAccessList(), freeData(), and pool.
Member Function Documentation
createPool()
void DelayPool::createPool (u_char delay_class)
Definition at line 63 of file DelayPool.cc.
References CommonPool::Factory(), freeData(), pool, and theComposite_.
Referenced by DelayConfig::parsePoolClass().
dump()
void DelayPool::dump (StoreEntry * entry, unsigned int poolNumberMinusOne) const
Definition at line 42 of file DelayPool.cc.
References access, CommonPool::classTypeLabel(), CompositePoolNode::dump(), dump_acl_access(), LOCAL_ARRAY, pool, SQUIDSBUFPH, SQUIDSBUFPRINT, storeAppendPrintf(), and theComposite().
freeData()
void DelayPool::freeData ()
Definition at line 72 of file DelayPool.cc.
References pool.
Referenced by ~DelayPool(), and createPool().
parse()
void DelayPool::parse ()
Definition at line 35 of file DelayPool.cc.
References assert, CompositePoolNode::parse(), and theComposite().
Referenced by DelayConfig::parsePoolRates().
theComposite() [1/2]
CompositePoolNode::Pointer DelayPool::theComposite () inline
Definition at line 34 of file DelayPool.h.
References theComposite_.
Referenced by dump(), parse(), and DelayPools::Stats().
theComposite() [2/2]
CompositePoolNode::Pointer const DelayPool::theComposite () const inline
Definition at line 36 of file DelayPool.h.
References theComposite_.
Member Data Documentation
access
acl_access* DelayPool::access
Definition at line 38 of file DelayPool.h.
Referenced by ~DelayPool(), and dump().
pool
CommonPool* DelayPool::pool
Definition at line 33 of file DelayPool.h.
Referenced by DelayPool(), ~DelayPool(), createPool(), dump(), and freeData().
theComposite_
CompositePoolNode::Pointer DelayPool::theComposite_ private
Definition at line 41 of file DelayPool.h.
Referenced by DelayPool(), createPool(), theComposite(), and theComposite().
The documentation for this class was generated from the following files:
squid/src/DelayPool.h
squid/src/DelayPool.cc