Squid Web Cache: IcmpConfig Class Reference
IcmpConfig Class Reference
#include <IcmpConfig.h>
Public Member Functions
IcmpConfig ()
~IcmpConfig ()
void clear ()
void parse ()
Public Attributes
SBuf program
int enable
Detailed Description
Squid pinger Configuration settings
Definition at line 22 of file IcmpConfig.h.
Constructor & Destructor Documentation
IcmpConfig()
IcmpConfig::IcmpConfig () inline
Definition at line 25 of file IcmpConfig.h.
~IcmpConfig()
IcmpConfig::~IcmpConfig () inline
Definition at line 26 of file IcmpConfig.h.
Member Function Documentation
clear()
void IcmpConfig::clear () inline
Definition at line 28 of file IcmpConfig.h.
References SBuf::clear(), enable, and program.
parse()
void IcmpConfig::parse ()
Definition at line 20 of file IcmpConfig.cc.
References SBuf::append(), SBuf::clear(), ConfigParser::NextQuotedOrToEol(), program, and self_destruct().
Member Data Documentation
enable
int IcmpConfig::enable
Whether the pinger helper is enabled for use or not
Definition at line 35 of file IcmpConfig.h.
Referenced by clear(), and IcmpSquid::Open().
program
SBuf IcmpConfig::program
pinger helper application path
Definition at line 32 of file IcmpConfig.h.
Referenced by clear(), IcmpSquid::Open(), and parse().
The documentation for this class was generated from the following files:
squid/src/icmp/IcmpConfig.h
squid/src/icmp/IcmpConfig.cc