Squid Web Cache: ACLUserData Class Reference
ACLUserData Class Reference
#include <UserData.h>
Public Member Functions
~ACLUserData () override
ACLUserData ()
bool match (char const *user) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual void prepareForUse ()
Private Types
typedef std::set< SBuf, bool(*)(const SBuf &, const SBuf &)> UserDataNames_t
Private Member Functions
MEMPROXY_CLASS (ACLUserData)
const Acl::Options & lineOptions () override
supported ACL "line" options (e.g., "-i")
Private Attributes
UserDataNames_t userDataNames
struct {
bool case_insensitive
bool required
} flags
Static Private Attributes
static Acl::BooleanOptionValue CaseInsensitive_
whether parse() is called in a case insensitive context
Detailed Description
Definition at line 18 of file UserData.h.
Member Typedef Documentation
UserDataNames_t
typedef std::set<SBuf,bool(*)(const SBuf&, const SBuf&)> ACLUserData::UserDataNames_t private
Definition at line 37 of file UserData.h.
Constructor & Destructor Documentation
~ACLUserData()
ACLUserData::~ACLUserData () inline override
Definition at line 23 of file UserData.h.
ACLUserData()
ACLUserData::ACLUserData ()
Definition at line 74 of file UserData.cc.
References flags.
Member Function Documentation
dump()
SBufList ACLUserData::dump () const override virtual
Implements ACLData< char const * >.
Definition at line 42 of file UserData.cc.
References debugs, flags, JoinContainerToSBuf(), and userDataNames.
empty()
bool ACLUserData::empty () const override virtual
Implements ACLData< char const * >.
Definition at line 146 of file UserData.cc.
References debugs, flags, and userDataNames.
lineOptions()
const Acl::Options & ACLUserData::lineOptions () override private virtual
Reimplemented from ACLData< char const * >.
Definition at line 82 of file UserData.cc.
References CaseInsensitive_, and Acl::CaseSensitivityOption().
match()
bool ACLUserData::match (char const * user) override virtual
Implements ACLData< char const * >.
Definition at line 24 of file UserData.cc.
References debugs, flags, and userDataNames.
MEMPROXY_CLASS()
ACLUserData::MEMPROXY_CLASS (ACLUserData) private
parse()
void ACLUserData::parse () override virtual
Implements ACLData< char const * >.
Definition at line 91 of file UserData.cc.
References CaseInsensitive_, CaseInsensitveSBufCompare(), SBuf::cmp(), DBG_PARSE_NOTE, debugs, flags, ConfigParser::strtokFile(), SBuf::toLower(), and userDataNames.
prepareForUse()
virtual void ACLData< char const * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
case_insensitive
bool ACLUserData::case_insensitive
Definition at line 41 of file UserData.h.
CaseInsensitive_
Acl::BooleanOptionValue ACLUserData::CaseInsensitive_ static private
Definition at line 32 of file UserData.h.
Referenced by lineOptions(), and parse().
[struct]
struct { ... } ACLUserData::flags
Referenced by ACLUserData(), dump(), empty(), match(), and parse().
required
bool ACLUserData::required
Definition at line 42 of file UserData.h.
userDataNames
UserDataNames_t ACLUserData::userDataNames private
Definition at line 38 of file UserData.h.
Referenced by dump(), empty(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/UserData.h
squid/src/acl/UserData.cc