Squid Web Cache: TestHttpReply Class Reference
TestHttpReply Class Reference
Protected Member Functions
void testSanityCheckFirstLine ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestHttpReply)
CPPUNIT_TEST (testSanityCheckFirstLine)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 19 of file testHttpReply.cc.
Member Function Documentation
CPPUNIT_TEST()
TestHttpReply::CPPUNIT_TEST (testSanityCheckFirstLine) private
CPPUNIT_TEST_SUITE()
TestHttpReply::CPPUNIT_TEST_SUITE (TestHttpReply) private
CPPUNIT_TEST_SUITE_END()
TestHttpReply::CPPUNIT_TEST_SUITE_END () private
testSanityCheckFirstLine()
void TestHttpReply::testSanityCheckFirstLine () protected
Definition at line 60 of file testHttpReply.cc.
References MemBuf::append(), MemBuf::content(), MemBuf::contentSize(), error(), headersEnd(), MemBuf::init(), HttpReply::protoPrefix, MemBuf::reset(), HttpReply::reset(), HttpReply::sanityCheckStartLine(), Http::scInvalidHeader, and Http::scNone.
The documentation for this class was generated from the following file:
squid/src/tests/testHttpReply.cc