Squid Web Cache: TestHttpRange Class Reference
TestHttpRange Class Reference
Protected Member Functions
void testRangeParser ()
void testRangeParsing (char const *rangestring)
void testRangeIter ()
void testRangeCanonization ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestHttpRange)
CPPUNIT_TEST (testRangeParser)
CPPUNIT_TEST (testRangeIter)
CPPUNIT_TEST (testRangeCanonization)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 15 of file testHttpRange.cc.
Member Function Documentation
CPPUNIT_TEST() [1/3]
TestHttpRange::CPPUNIT_TEST (testRangeCanonization) private
CPPUNIT_TEST() [2/3]
TestHttpRange::CPPUNIT_TEST (testRangeIter) private
CPPUNIT_TEST() [3/3]
TestHttpRange::CPPUNIT_TEST (testRangeParser) private
CPPUNIT_TEST_SUITE()
TestHttpRange::CPPUNIT_TEST_SUITE (TestHttpRange) private
CPPUNIT_TEST_SUITE_END()
TestHttpRange::CPPUNIT_TEST_SUITE_END () private
testRangeCanonization()
void TestHttpRange::testRangeCanonization () protected
Definition at line 94 of file testHttpRange.cc.
References HttpHdrRange::canonize(), rangeFromString(), and HttpHdrRange::specs.
testRangeIter()
void TestHttpRange::testRangeIter () protected
Definition at line 73 of file testHttpRange.cc.
References HttpHdrRange::begin(), HttpHdrRange::end(), rangeFromString(), and HttpHdrRange::specs.
testRangeParser()
void TestHttpRange::testRangeParser () protected
Definition at line 32 of file testHttpRange.cc.
References testRangeParsing().
testRangeParsing()
void TestHttpRange::testRangeParsing (char const * rangestring) protected
Definition at line 41 of file testHttpRange.cc.
References HttpHdrRange::begin(), HttpHdrRange::ParseCreate(), and HttpHdrRange::specs.
Referenced by testRangeParser().
The documentation for this class was generated from the following file:
squid/src/tests/testHttpRange.cc