Squid Web Cache: TestStoreController Class Reference
TestStoreController Class Reference
Protected Member Functions
void testStats ()
void testMaxSize ()
void testSearch ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestStoreController)
CPPUNIT_TEST (testStats)
CPPUNIT_TEST (testMaxSize)
CPPUNIT_TEST (testSearch)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 22 of file testStoreController.cc.
Member Function Documentation
CPPUNIT_TEST() [1/3]
TestStoreController::CPPUNIT_TEST (testMaxSize) private
CPPUNIT_TEST() [2/3]
TestStoreController::CPPUNIT_TEST (testSearch) private
CPPUNIT_TEST() [3/3]
TestStoreController::CPPUNIT_TEST (testStats) private
CPPUNIT_TEST_SUITE()
TestStoreController::CPPUNIT_TEST_SUITE (TestStoreController) private
CPPUNIT_TEST_SUITE_END()
TestStoreController::CPPUNIT_TEST_SUITE_END () private
testMaxSize()
void TestStoreController::testMaxSize () protected
Definition at line 86 of file testStoreController.cc.
References addSwapDir(), SquidConfig::cacheSwap, commonInit(), Config, StoreEntry::createMemObject(), free_cachedir(), Store::Root(), STORE_PENDING, and StoreEntry::store_status.
testSearch()
void TestStoreController::testSearch () protected
Definition at line 143 of file testStoreController.cc.
References addedEntry(), addSwapDir(), cbcalled, commonInit(), StoreSearch::currentItem(), StoreSearch::error(), RefCount< C >::getRaw(), Store::Controller::init(), StoreSearch::isDone(), StoreSearch::next(), Store::Root(), Store::Controller::search(), and searchCallback().
testStats()
void TestStoreController::testStats () protected
Definition at line 47 of file testStoreController.cc.
References addSwapDir(), SquidConfig::cacheSwap, Config, StoreEntry::createMemObject(), free_cachedir(), Store::Stats(), STORE_PENDING, and StoreEntry::store_status.
The documentation for this class was generated from the following file:
squid/src/tests/testStoreController.cc