Squid Web Cache: Adaptation::Icap::Options Class Reference
Adaptation::Icap::Options Class Reference
#include <Options.h>
Classes
class TransferList
struct Transfers
Public Types
enum TransferKind { xferNone , xferPreview , xferIgnore , xferComplete }
typedef void GetCallback(void *data, Options *options)
Public Member Functions
Options ()
~Options ()
void configure (const HttpReply *reply)
bool valid () const
bool fresh () const
int ttl () const
time_t expire () const
time_t timestamp () const
TransferKind transferKind (const SBuf &urlPath) const
Static Public Member Functions
static void Get (ServiceRep::Pointer &service, GetCallback *cb, void *data)
Public Attributes
const char * error
std::vector< ICAP::Method > methods
String istag
String service
String serviceId
int max_connections
bool allow204
bool allow206
int preview
Protected Attributes
struct Adaptation::Icap::Options::Transfers theTransfers
int theTTL
time_t theTimestamp
Private Member Functions
void cfgMethod (ICAP::Method m)
void cfgIntHeader (const HttpHeader *h, const char *fname, int &value)
void cfgTransferList (const HttpHeader *h, TransferList &l)
Detailed Description
Definition at line 25 of file Options.h.
Member Typedef Documentation
GetCallback
typedef void Adaptation::Icap::Options::GetCallback(void *data, Options *options)
Definition at line 29 of file Options.h.
Member Enumeration Documentation
TransferKind
enum Adaptation::Icap::Options::TransferKind
Enumerator
xferNone
xferPreview
xferIgnore
xferComplete
Definition at line 44 of file Options.h.
Constructor & Destructor Documentation
Options()
Adaptation::Icap::Options::Options ()
Definition at line 17 of file Options.cc.
References Adaptation::Icap::Options::Transfers::byDefault, Adaptation::Icap::Options::Transfers::complete, Adaptation::Icap::Options::Transfers::ignore, Adaptation::Icap::Options::TransferList::kind, Adaptation::Icap::Options::TransferList::name, Adaptation::Icap::Options::Transfers::preview, theTransfers, xferComplete, xferIgnore, and xferPreview.
~Options()
Adaptation::Icap::Options::~Options ()
Definition at line 38 of file Options.cc.
Member Function Documentation
cfgIntHeader()
void Adaptation::Icap::Options::cfgIntHeader (const HttpHeader * h, const char * fname, int & value) private
Definition at line 144 of file Options.cc.
References debugs, HttpHeader::getByName(), String::size(), String::termedBuf(), and xisdigit.
cfgMethod()
void Adaptation::Icap::Options::cfgMethod (ICAP::Method m) private
Definition at line 137 of file Options.cc.
References Must.
cfgTransferList()
void Adaptation::Icap::Options::cfgTransferList (const HttpHeader * h, TransferList & l) private
Definition at line 156 of file Options.cc.
References debugs, HttpHeader::getByName(), Adaptation::Icap::Options::TransferList::name, Adaptation::Icap::Options::TransferList::parse(), and Adaptation::Icap::Options::TransferList::report().
configure()
void Adaptation::Icap::Options::configure (const HttpReply * reply)
Definition at line 84 of file Options.cc.
References Http::ALLOW, Http::DATE, DBG_IMPORTANT, debugs, error(), HttpHeader::getByName(), HttpHeader::getTime(), HttpHeader::hasByNameListMember(), HttpHeader::hasListMember(), Http::Message::header, Http::scOkay, String::size(), HttpReply::sline, squid_curtime, and Http::StatusLine::status().
Referenced by Adaptation::Icap::ServiceRep::noteAdaptationAnswer().
expire()
time_t Adaptation::Icap::Options::expire () const
Definition at line 78 of file Options.cc.
References Must.
fresh()
bool Adaptation::Icap::Options::fresh () const
Definition at line 67 of file Options.cc.
References squid_curtime.
Get()
static void Adaptation::Icap::Options::Get (ServiceRep::Pointer & service, GetCallback * cb, void * data) static
timestamp()
time_t Adaptation::Icap::Options::timestamp () const inline
Definition at line 42 of file Options.h.
References theTimestamp.
transferKind()
Adaptation::Icap::Options::TransferKind Adaptation::Icap::Options::transferKind (const SBuf & urlPath) const
Definition at line 46 of file Options.cc.
References debugs.
ttl()
int Adaptation::Icap::Options::ttl () const
Definition at line 72 of file Options.cc.
References Adaptation::Icap::Config::default_options_ttl, Must, and Adaptation::Icap::TheConfig.
valid()
bool Adaptation::Icap::Options::valid () const
Definition at line 62 of file Options.cc.
References error().
Member Data Documentation
allow204
bool Adaptation::Icap::Options::allow204
Definition at line 58 of file Options.h.
allow206
bool Adaptation::Icap::Options::allow206
Definition at line 59 of file Options.h.
error
const char* Adaptation::Icap::Options::error
Definition at line 48 of file Options.h.
istag
String Adaptation::Icap::Options::istag
Definition at line 52 of file Options.h.
max_connections
int Adaptation::Icap::Options::max_connections
Definition at line 57 of file Options.h.
methods
std::vector<ICAP::Method> Adaptation::Icap::Options::methods
Definition at line 51 of file Options.h.
preview
int Adaptation::Icap::Options::preview
Definition at line 60 of file Options.h.
service
String Adaptation::Icap::Options::service
Definition at line 55 of file Options.h.
serviceId
String Adaptation::Icap::Options::serviceId
Definition at line 56 of file Options.h.
theTimestamp
time_t Adaptation::Icap::Options::theTimestamp protected
Definition at line 92 of file Options.h.
Referenced by timestamp().
theTransfers
struct Adaptation::Icap::Options::Transfers Adaptation::Icap::Options::theTransfers protected
Referenced by Options().
theTTL
int Adaptation::Icap::Options::theTTL protected
Definition at line 91 of file Options.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/Options.h
squid/src/adaptation/icap/Options.cc