Squid Web Cache: BlockingIOStrategy Class Reference
BlockingIOStrategy Class Reference
#include <BlockingIOStrategy.h>
Public Member Functions
bool shedLoad () override
int load () override
RefCount< DiskFile > newFile (char const *path) override
bool unlinkdUseful () const override
void unlinkFile (char const *) override
virtual void sync ()
virtual int callback ()
virtual void init ()
virtual void statfs (StoreEntry &) const
virtual ConfigOption * getOptionTree () const
Detailed Description
Definition at line 15 of file BlockingIOStrategy.h.
Member Function Documentation
callback()
virtual int DiskIOStrategy::callback () inline virtual inherited
perform any pending callbacks
Reimplemented in DiskdIOStrategy, SingletonIOStrategy, and DiskThreadsIOStrategy.
Definition at line 44 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::callback().
getOptionTree()
virtual ConfigOption * DiskIOStrategy::getOptionTree () const inline virtual inherited
module specific options
Reimplemented in DiskdIOStrategy, and SingletonIOStrategy.
Definition at line 53 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::getOptionTree().
init()
virtual void DiskIOStrategy::init (void) inline virtual inherited
Init per-instance logic
Reimplemented in DiskdIOStrategy, SingletonIOStrategy, and DiskThreadsIOStrategy.
Definition at line 47 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::init().
load()
int BlockingIOStrategy::load () override virtual
What is the current load? 999 = 99.9%
Implements DiskIOStrategy.
Definition at line 23 of file BlockingIOStrategy.cc.
newFile()
DiskFile::Pointer BlockingIOStrategy::newFile (char const * path) override virtual
Return a handle for performing IO operations
Implements DiskIOStrategy.
Definition at line 30 of file BlockingIOStrategy.cc.
shedLoad()
bool BlockingIOStrategy::shedLoad () override virtual
Can the IO Strategy handle more requests ?
Implements DiskIOStrategy.
Definition at line 17 of file BlockingIOStrategy.cc.
statfs()
virtual void DiskIOStrategy::statfs (StoreEntry &) const inline virtual inherited
cachemgr output on the IO instance stats
Reimplemented in DiskdIOStrategy, and SingletonIOStrategy.
Definition at line 50 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::statfs().
sync()
virtual void DiskIOStrategy::sync () inline virtual inherited
flush all IO operations
Reimplemented in DiskdIOStrategy, SingletonIOStrategy, and DiskThreadsIOStrategy.
Definition at line 35 of file DiskIOStrategy.h.
Referenced by SingletonIOStrategy::sync().
unlinkdUseful()
bool BlockingIOStrategy::unlinkdUseful () const override virtual
whether the IO Strategy can use unlinkd
Implements DiskIOStrategy.
Definition at line 36 of file BlockingIOStrategy.cc.
unlinkFile()
void BlockingIOStrategy::unlinkFile (char const *) override virtual
unlink a file by path
Implements DiskIOStrategy.
Definition at line 42 of file BlockingIOStrategy.cc.
References unlinkdUnlink().
The documentation for this class was generated from the following files:
squid/src/DiskIO/Blocking/BlockingIOStrategy.h
squid/src/DiskIO/Blocking/BlockingIOStrategy.cc