Squid Web Cache: PeerSelectionInitiator Class Reference
PeerSelectionInitiator Class Reference abstract
Interface for those who need a list of peers to forward a request to.
#include <PeerSelectState.h>
Public Member Functions
~PeerSelectionInitiator () override=default
virtual void noteDestination (Comm::ConnectionPointer path)=0
called when a new unique destination has been found
virtual void noteDestinationsEnd (ErrorState *error)=0
void startSelectingDestinations (HttpRequest *request, const AccessLogEntry::Pointer &ale, StoreEntry *entry)
virtual void * toCbdata ()=0
Public Attributes
bool subscribed = false
whether noteDestination() and noteDestinationsEnd() calls are allowed
Private Member Functions
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Detailed Description
Definition at line 32 of file PeerSelectState.h.
Constructor & Destructor Documentation
~PeerSelectionInitiator()
PeerSelectionInitiator::~PeerSelectionInitiator () override default
Member Function Documentation
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
noteDestination()
virtual void PeerSelectionInitiator::noteDestination (Comm::ConnectionPointer path) pure virtual
Implemented in FwdState, and TunnelStateData.
noteDestinationsEnd()
virtual void PeerSelectionInitiator::noteDestinationsEnd (ErrorState * error) pure virtual
called when there will be no more noteDestination() calls
Parameters
error is a possible reason why no destinations were found; it is guaranteed to be nil if there was at least one noteDestination() call
Implemented in FwdState, and TunnelStateData.
startSelectingDestinations()
void PeerSelectionInitiator::startSelectingDestinations (HttpRequest * request, const AccessLogEntry::Pointer & ale, StoreEntry * entry)
Initiates asynchronous peer selection that eventually results in zero or more noteDestination() calls and exactly one noteDestinationsEnd() call.
Definition at line 330 of file peer_select.cc.
References peerSelect(), and subscribed.
Referenced by FwdState::start(), and tunnelStart().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
Member Data Documentation
subscribed
bool PeerSelectionInitiator::subscribed = false
Definition at line 46 of file PeerSelectState.h.
Referenced by TunnelStateData::commitToServer(), FwdState::noteDestinationsEnd(), TunnelStateData::noteDestinationsEnd(), FwdState::reforward(), TunnelStateData::retryOrBail(), TunnelStateData::sendError(), startSelectingDestinations(), FwdState::stopAndDestroy(), and FwdState::useDestinations().
The documentation for this class was generated from the following files:
squid/src/PeerSelectState.h
squid/src/peer_select.cc