Squid Web Cache: ClassCNetPool Class Reference
ClassCNetPool Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Public Types
typedef RefCount< VectorPool > Pointer
Public Member Functions
void * operator new (size_t byteCount)
void operator delete (void *address)
void dump (StoreEntry *entry) const override
void parse () override
void update (int incr) override
void stats (StoreEntry *sentry) override
DelayIdComposite::Pointer id (CompositeSelectionDetails &) override
void delayRead (const AsyncCallPointer &)
Static Public Member Functions
static int UseCount ()
Public Attributes
VectorMap< unsigned char, DelayBucket > buckets
Protected Member Functions
char const * label () const override
unsigned int makeKey (Ip::Address &src_addr) const override
bool keyAllocated (unsigned char const key) const
virtual DelaySpec * rate ()
virtual DelaySpec const * rate () const
void kickReads ()
Protected Attributes
DelaySpec spec
DelayedAsyncCalls deferredReads
Private Member Functions
MEMPROXY_CLASS (CompositePoolNode)
Static Private Member Functions
static Mem::AllocatorProxy & Pool ()
Detailed Description
Definition at line 162 of file delay_pools.cc.
Member Typedef Documentation
Pointer
typedef RefCount<VectorPool> VectorPool::Pointer inherited
Definition at line 112 of file delay_pools.cc.
Member Function Documentation
delayRead()
void CompositePoolNode::delayRead (const AsyncCallPointer & aRead) inherited
Definition at line 80 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::delay().
Referenced by Aggregate::AggregateId::delayRead().
dump()
void VectorPool::dump (StoreEntry * entry) const override virtual inherited
Implements CompositePoolNode.
Definition at line 642 of file delay_pools.cc.
References DelaySpec::dump(), and VectorPool::rate().
id()
DelayIdComposite::Pointer VectorPool::id (CompositeSelectionDetails & details) override virtual inherited
Implements CompositePoolNode.
Definition at line 693 of file delay_pools.cc.
References VectorPool::buckets, VectorMap< Key, Value >::findKeyIndex(), DelayBucket::init(), VectorMap< Key, Value >::insert(), Ip::Address::isIPv4(), VectorPool::keyAllocated(), VectorPool::makeKey(), VectorPool::rate(), CompositePoolNode::CompositeSelectionDetails::src_addr, and VectorMap< Key, Value >::values.
keyAllocated()
bool VectorPool::keyAllocated (unsigned char const key) const protected inherited
Definition at line 664 of file delay_pools.cc.
References VectorPool::buckets, VectorMap< Key, Value >::findKeyIndex(), and VectorMap< Key, Value >::indexUsed().
Referenced by VectorPool::id(), and ClassCHostPool::id().
kickReads()
void CompositePoolNode::kickReads () protected inherited
Definition at line 88 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::schedule().
Referenced by Aggregate::update(), DelayTagged::update(), and DelayVector::update().
label()
char const * ClassCNetPool::label () const inline override protected virtual
Implements VectorPool.
Definition at line 167 of file delay_pools.cc.
makeKey()
unsigned int ClassCNetPool::makeKey (Ip::Address & src_addr) const override protected virtual
Implements VectorPool.
Definition at line 742 of file delay_pools.cc.
References Ip::Address::getInAddr(), and Ip::Address::isIPv4().
MEMPROXY_CLASS()
CompositePoolNode::MEMPROXY_CLASS (CompositePoolNode) private inherited
operator delete()
void ClassCNetPool::operator delete (void * address) inline
Definition at line 164 of file delay_pools.cc.
operator new()
void * ClassCNetPool::operator new (size_t byteCount) inline
Definition at line 164 of file delay_pools.cc.
parse()
void VectorPool::parse () override virtual inherited
Implements CompositePoolNode.
Definition at line 658 of file delay_pools.cc.
References DelaySpec::parse(), and VectorPool::rate().
Pool()
static Mem::AllocatorProxy & ClassCNetPool::Pool () inline static private
Definition at line 164 of file delay_pools.cc.
rate() [1/2]
virtual DelaySpec * VectorPool::rate () inline protected virtual inherited
Definition at line 125 of file delay_pools.cc.
References VectorPool::spec.
Referenced by VectorPool::dump(), ClassCHostPool::dump(), VectorPool::id(), ClassCHostPool::id(), VectorPool::parse(), ClassCHostPool::parse(), VectorPool::stats(), ClassCHostPool::stats(), VectorPool::update(), and ClassCHostPool::update().
rate() [2/2]
virtual DelaySpec const * VectorPool::rate () const inline protected virtual inherited
Definition at line 127 of file delay_pools.cc.
References VectorPool::spec.
stats()
void VectorPool::stats (StoreEntry * sentry) override virtual inherited
Implements CompositePoolNode.
Definition at line 619 of file delay_pools.cc.
References VectorPool::buckets, VectorMap< Key, Value >::key_map, VectorPool::label(), VectorPool::rate(), VectorMap< Key, Value >::size(), DelayBucket::stats(), DelaySpec::stats(), storeAppendPrintf(), and VectorMap< Key, Value >::values.
update()
void VectorPool::update (int incr) override virtual inherited
Implements CompositePoolNode.
Definition at line 648 of file delay_pools.cc.
References VectorPool::buckets, VectorPool::rate(), VectorMap< Key, Value >::size(), DelayBucket::update(), and VectorMap< Key, Value >::values.
UseCount()
static int ClassCNetPool::UseCount () inline static
Definition at line 164 of file delay_pools.cc.
Member Data Documentation
buckets
VectorMap<unsigned char, DelayBucket> VectorPool::buckets inherited
Definition at line 119 of file delay_pools.cc.
Referenced by VectorPool::id(), ClassCHostPool::id(), VectorPool::keyAllocated(), ClassCHostPool::keyAllocated(), VectorPool::stats(), ClassCHostPool::stats(), VectorPool::update(), and ClassCHostPool::update().
deferredReads
DelayedAsyncCalls CompositePoolNode::deferredReads protected inherited
Definition at line 60 of file CompositePoolNode.h.
Referenced by CompositePoolNode::delayRead(), and CompositePoolNode::kickReads().
spec
DelaySpec VectorPool::spec protected inherited
Definition at line 133 of file delay_pools.cc.
Referenced by VectorPool::rate(), and VectorPool::rate().
The documentation for this class was generated from the following file:
squid/src/delay_pools.cc