Squid Web Cache: ClassCHostPool Class Reference
ClassCHostPool Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Classes
class Id
Public Types
typedef RefCount< ClassCHostPool > Pointer
Public Member Functions
void * operator new (size_t byteCount)
void operator delete (void *address)
void dump (StoreEntry *entry) const override
void parse () override
void update (int incr) override
void stats (StoreEntry *sentry) override
DelayIdComposite::Pointer id (CompositeSelectionDetails &) override
ClassCHostPool ()
~ClassCHostPool () override
void delayRead (const AsyncCallPointer &)
Static Public Member Functions
static int UseCount ()
Protected Member Functions
bool keyAllocated (unsigned char const key) const
virtual DelaySpec * rate ()
virtual DelaySpec const * rate () const
virtual char const * label () const
virtual unsigned int makeKey (Ip::Address &src_addr) const
unsigned char makeHostKey (Ip::Address &src_addr) const
void kickReads ()
Protected Attributes
DelaySpec spec
VectorMap< unsigned char, ClassCBucket > buckets
DelayedAsyncCalls deferredReads
Private Member Functions
MEMPROXY_CLASS (CompositePoolNode)
Static Private Member Functions
static Mem::AllocatorProxy & Pool ()
Friends
class ClassCHostPool::Id
Detailed Description
Definition at line 190 of file delay_pools.cc.
Member Typedef Documentation
Pointer
typedef RefCount<ClassCHostPool> ClassCHostPool::Pointer
Definition at line 195 of file delay_pools.cc.
Constructor & Destructor Documentation
ClassCHostPool()
ClassCHostPool::ClassCHostPool ()
Definition at line 753 of file delay_pools.cc.
References DelayPools::registerForUpdates().
~ClassCHostPool()
ClassCHostPool::~ClassCHostPool () override
Definition at line 758 of file delay_pools.cc.
References DelayPools::deregisterForUpdates().
Member Function Documentation
delayRead()
void CompositePoolNode::delayRead (const AsyncCallPointer & aRead) inherited
Definition at line 80 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::delay().
Referenced by Aggregate::AggregateId::delayRead().
dump()
void ClassCHostPool::dump (StoreEntry * entry) const override virtual
Implements CompositePoolNode.
Definition at line 786 of file delay_pools.cc.
References DelaySpec::dump(), and VectorPool::rate().
id()
DelayIdComposite::Pointer ClassCHostPool::id (CompositeSelectionDetails & details) override virtual
Implements CompositePoolNode.
Definition at line 839 of file delay_pools.cc.
References VectorPool::buckets, VectorMap< Key, Value >::findKeyIndex(), VectorMap< Key, Value >::insert(), Ip::Address::isIPv4(), VectorPool::keyAllocated(), VectorPool::makeKey(), VectorPool::rate(), CompositePoolNode::CompositeSelectionDetails::src_addr, and VectorMap< Key, Value >::values.
keyAllocated()
bool ClassCHostPool::keyAllocated (unsigned char const key) const protected
Definition at line 808 of file delay_pools.cc.
References VectorPool::buckets, VectorMap< Key, Value >::findKeyIndex(), and VectorMap< Key, Value >::indexUsed().
kickReads()
void CompositePoolNode::kickReads () protected inherited
Definition at line 88 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::schedule().
Referenced by Aggregate::update(), DelayTagged::update(), and DelayVector::update().
label()
virtual char const * ClassCHostPool::label () const inline protected virtual
Definition at line 211 of file delay_pools.cc.
makeHostKey()
unsigned char ClassCHostPool::makeHostKey (Ip::Address & src_addr) const protected
Definition at line 814 of file delay_pools.cc.
References Ip::Address::getInAddr(), and Ip::Address::isIPv4().
makeKey()
unsigned int ClassCHostPool::makeKey (Ip::Address & src_addr) const protected virtual
Definition at line 827 of file delay_pools.cc.
References Ip::Address::getInAddr(), and Ip::Address::isIPv4().
MEMPROXY_CLASS()
CompositePoolNode::MEMPROXY_CLASS (CompositePoolNode) private inherited
operator delete()
void ClassCHostPool::operator delete (void * address) inline
Definition at line 192 of file delay_pools.cc.
operator new()
void * ClassCHostPool::operator new (size_t byteCount) inline
Definition at line 192 of file delay_pools.cc.
parse()
void ClassCHostPool::parse () override virtual
Implements CompositePoolNode.
Definition at line 802 of file delay_pools.cc.
References DelaySpec::parse(), and VectorPool::rate().
Pool()
static Mem::AllocatorProxy & ClassCHostPool::Pool () inline static private
Definition at line 192 of file delay_pools.cc.
rate() [1/2]
virtual DelaySpec * ClassCHostPool::rate () inline protected virtual
Definition at line 207 of file delay_pools.cc.
References spec.
rate() [2/2]
virtual DelaySpec const * ClassCHostPool::rate () const inline protected virtual
Definition at line 209 of file delay_pools.cc.
References spec.
stats()
void ClassCHostPool::stats (StoreEntry * sentry) override virtual
Implements CompositePoolNode.
Definition at line 764 of file delay_pools.cc.
References VectorPool::buckets, VectorMap< Key, Value >::key_map, VectorPool::label(), VectorPool::rate(), VectorMap< Key, Value >::size(), DelayBucket::stats(), DelaySpec::stats(), storeAppendPrintf(), and VectorMap< Key, Value >::values.
update()
void ClassCHostPool::update (int incr) override virtual
Implements CompositePoolNode.
Definition at line 792 of file delay_pools.cc.
References VectorPool::buckets, VectorPool::rate(), VectorMap< Key, Value >::size(), DelayBucket::update(), and VectorMap< Key, Value >::values.
UseCount()
static int ClassCHostPool::UseCount () inline static
Definition at line 192 of file delay_pools.cc.
Friends And Related Symbol Documentation
ClassCHostPool::Id
friend class ClassCHostPool::Id friend
Definition at line 222 of file delay_pools.cc.
Member Data Documentation
buckets
VectorMap<unsigned char, ClassCBucket> ClassCHostPool::buckets protected
Definition at line 218 of file delay_pools.cc.
deferredReads
DelayedAsyncCalls CompositePoolNode::deferredReads protected inherited
Definition at line 60 of file CompositePoolNode.h.
Referenced by CompositePoolNode::delayRead(), and CompositePoolNode::kickReads().
spec
DelaySpec ClassCHostPool::spec protected
Definition at line 217 of file delay_pools.cc.
Referenced by rate(), and rate().
The documentation for this class was generated from the following file:
squid/src/delay_pools.cc