Squid Web Cache: HasExplicit Class Reference
HasExplicit Class Reference
Public Member Functions
HasExplicit ()
~HasExplicit ()
HasExplicit (HasExplicit const &)
HasExplicit & operator= (HasExplicit const &)
Static Public Member Functions
static int const & Instances ()
static int const & Assignments ()
static void Assignments (int const &)
Static Private Member Functions
static void AddInstance ()
static void RemoveInstance ()
static void Assignment ()
Static Private Attributes
static int Instances_
static int Assignments_
Detailed Description
Definition at line 15 of file syntheticoperators.cc.
Constructor & Destructor Documentation
HasExplicit() [1/2]
HasExplicit::HasExplicit ()
Definition at line 36 of file syntheticoperators.cc.
References AddInstance().
~HasExplicit()
HasExplicit::~HasExplicit ()
Definition at line 41 of file syntheticoperators.cc.
References RemoveInstance().
HasExplicit() [2/2]
HasExplicit::HasExplicit (HasExplicit const &)
Definition at line 46 of file syntheticoperators.cc.
References AddInstance().
Member Function Documentation
AddInstance()
void HasExplicit::AddInstance () static private
Definition at line 59 of file syntheticoperators.cc.
References Instances_.
Referenced by HasExplicit(), and HasExplicit().
Assignment()
void HasExplicit::Assignment () static private
Definition at line 71 of file syntheticoperators.cc.
References Assignments_.
Referenced by operator=().
Assignments() [1/2]
int const & HasExplicit::Assignments () static
Definition at line 83 of file syntheticoperators.cc.
References Assignments_.
Referenced by CheckHasExplicitWorks(), and CheckSyntheticWorks().
Assignments() [2/2]
void HasExplicit::Assignments (int const & newValue) static
Definition at line 89 of file syntheticoperators.cc.
References Assignments_.
Instances()
int const & HasExplicit::Instances () static
Definition at line 77 of file syntheticoperators.cc.
References Instances_.
Referenced by CheckHasExplicitWorks(), and CheckSyntheticWorks().
operator=()
HasExplicit & HasExplicit::operator= (HasExplicit const &)
Definition at line 52 of file syntheticoperators.cc.
References Assignment().
RemoveInstance()
void HasExplicit::RemoveInstance () static private
Definition at line 65 of file syntheticoperators.cc.
References Instances_.
Referenced by ~HasExplicit().
Member Data Documentation
Assignments_
int HasExplicit::Assignments_ static private
Definition at line 30 of file syntheticoperators.cc.
Referenced by Assignment(), Assignments(), and Assignments().
Instances_
int HasExplicit::Instances_ static private
Definition at line 29 of file syntheticoperators.cc.
Referenced by AddInstance(), Instances(), and RemoveInstance().
The documentation for this class was generated from the following file:
squid/test-suite/syntheticoperators.cc