Squid Web Cache: StoreFileSystem Class Reference
StoreFileSystem Class Reference abstract
Storage Filesystems
#include <StoreFileSystem.h>
Public Types
typedef std::vector< StoreFileSystem * >::iterator iterator
typedef std::vector< StoreFileSystem * >::const_iterator const_iterator
Public Member Functions
StoreFileSystem ()=default
StoreFileSystem (StoreFileSystem &&)=delete
virtual char const * type () const =0
virtual SwapDir * createSwapDir ()=0
Static Public Member Functions
static void FsAdd (StoreFileSystem &)
static StoreFileSystem * FindByType (const char *type)
static std::vector< StoreFileSystem * > const & FileSystems ()
Static Private Member Functions
static std::vector< StoreFileSystem * > & GetFileSystems ()
Static Private Attributes
static std::vector< StoreFileSystem * > * _FileSystems = nullptr
Detailed Description
The core API for storage modules this class provides all the hooks squid uses to interact with a filesystem IO module.
Definition at line 90 of file StoreFileSystem.h.
Member Typedef Documentation
const_iterator
typedef std::vector<StoreFileSystem*>::const_iterator StoreFileSystem::const_iterator
Definition at line 98 of file StoreFileSystem.h.
iterator
typedef std::vector<StoreFileSystem*>::iterator StoreFileSystem::iterator
Definition at line 97 of file StoreFileSystem.h.
Constructor & Destructor Documentation
StoreFileSystem() [1/2]
StoreFileSystem::StoreFileSystem () default
StoreFileSystem() [2/2]
StoreFileSystem::StoreFileSystem (StoreFileSystem &&) delete
Member Function Documentation
createSwapDir()
virtual SwapDir * StoreFileSystem::createSwapDir () pure virtual
Implemented in Rock::StoreFileSystem, and Fs::Ufs::StoreFSufs< TheSwapDir >.
FileSystems()
std::vector< StoreFileSystem * > const & StoreFileSystem::FileSystems () static
Definition at line 30 of file StoreFileSystem.cc.
References GetFileSystems().
Referenced by FindByType().
FindByType()
StoreFileSystem * StoreFileSystem::FindByType (const char * type) static
Definition at line 45 of file StoreFileSystem.cc.
References FileSystems(), and type().
Referenced by Store::Disks::Parse().
FsAdd()
void StoreFileSystem::FsAdd (StoreFileSystem & instance) static
Definition at line 17 of file StoreFileSystem.cc.
References assert, GetFileSystems(), and type().
Referenced by Rock::StoreFileSystem::StoreFileSystem(), and Fs::Ufs::StoreFSufs< TheSwapDir >::StoreFSufs().
GetFileSystems()
std::vector< StoreFileSystem * > & StoreFileSystem::GetFileSystems () static private
Definition at line 36 of file StoreFileSystem.cc.
References _FileSystems.
Referenced by FileSystems(), and FsAdd().
type()
virtual char const * StoreFileSystem::type () const pure virtual
Implemented in Rock::StoreFileSystem, and Fs::Ufs::StoreFSufs< TheSwapDir >.
Referenced by FindByType(), and FsAdd().
Member Data Documentation
_FileSystems
std::vector< StoreFileSystem * > * StoreFileSystem::_FileSystems = nullptr static private
Definition at line 108 of file StoreFileSystem.h.
Referenced by GetFileSystems().
The documentation for this class was generated from the following files:
squid/src/StoreFileSystem.h
squid/src/StoreFileSystem.cc