Squid Web Cache: Http::One::TeChunkedParser Class Reference
Http::One::TeChunkedParser Class Reference
#include <TeChunkedParser.h>
Public Types
typedef SBuf::size_type size_type
typedef ::Parser::Tokenizer Tokenizer
Public Member Functions
TeChunkedParser ()
~TeChunkedParser () override
void setPayloadBuffer (MemBuf *parsedContent)
set the buffer to be used to store decoded chunk data
void parseExtensionValuesWith (ChunkExtensionValueParser *parser)
bool needsMoreSpace () const
void clear () override
bool parse (const SBuf &) override
Parser::size_type firstLineSize () const override
size in bytes of the first line including CRLF terminator
bool needsMoreData () const
size_type headerBlockSize () const
size_type messageHeaderSize () const
SBuf mimeHeader () const
buffer containing HTTP mime headers, excluding message first-line.
const AnyP::ProtocolVersion & messageProtocol () const
the protocol label for this message
char * getHostHeaderField ()
const SBuf & remaining () const
the remaining unprocessed section of buffer
Static Public Member Functions
static const CharacterSet & WhitespaceCharacters ()
static const CharacterSet & DelimiterCharacters ()
Public Attributes
Http::StatusCode parseStatusCode = Http::scNone
Protected Member Functions
void skipLineTerminator (Tokenizer &) const
bool grabMimeBlock (const char *which, const size_t limit)
Protected Attributes
SBuf buf_
bytes remaining to be parsed
ParseState parsingStage_ = HTTP_PARSE_NONE
what stage the parser is currently up to
AnyP::ProtocolVersion msgProtocol_
what protocol label has been found in the first line (if any)
SBuf mimeHeaderBlock_
buffer holding the mime headers (if any)
bool hackExpectsMime_ = false
Whether the invalid HTTP as HTTP/0.9 hack expects a mime header block.
Static Protected Attributes
static const SBuf Http1magic
RFC 7230 section 2.6 - 7 magic octets.
Private Member Functions
bool parseChunkSize (Tokenizer &tok)
RFC 7230 section 4.1 chunk-size.
bool parseChunkMetadataSuffix (Tokenizer &)
void parseChunkExtensions (Tokenizer &)
void parseOneChunkExtension (Tokenizer &)
bool parseChunkBody (Tokenizer &tok)
bool parseChunkEnd (Tokenizer &tok)
void cleanMimePrefix ()
void unfoldMime ()
Private Attributes
MemBuf * theOut
uint64_t theChunkSize
uint64_t theLeftBodySize
ChunkExtensionValueParser * customExtensionValueParser
Detailed Description
An incremental parser for chunked transfer coding defined in RFC 7230 section 4.1. http://tools.ietf.org/html/rfc7230#section-4.1
The parser shovels content bytes from the raw input buffer into the content output buffer, both caller-supplied. Chunk extensions like use-original-body are handled via parseExtensionValuesWith(). Trailers are available via mimeHeader() if wanted.
Definition at line 51 of file TeChunkedParser.h.
Member Typedef Documentation
size_type
typedef SBuf::size_type Http::One::Parser::size_type inherited
Definition at line 43 of file Parser.h.
Tokenizer
typedef ::Parser::Tokenizer Http::One::Parser::Tokenizer inherited
Definition at line 44 of file Parser.h.
Constructor & Destructor Documentation
TeChunkedParser()
Http::One::TeChunkedParser::TeChunkedParser ()
Definition at line 21 of file TeChunkedParser.cc.
References clear(), and Http::ProtocolVersion().
~TeChunkedParser()
Http::One::TeChunkedParser::~TeChunkedParser () inline override
Definition at line 55 of file TeChunkedParser.h.
References theOut.
Member Function Documentation
cleanMimePrefix()
void Http::One::Parser::cleanMimePrefix () private inherited
Remove invalid lines (if any) from the mime prefix
RFC 7230 section 3: "A recipient that receives whitespace between the start-line and the first header field MUST ... consume each whitespace-preceded line without further processing of it."
We need to always use the relaxed delimiters here to prevent line smuggling through strict parsers.
Note that 'whitespace' in RFC 7230 includes CR. So that means sequences of CRLF will be pruned, but not sequences of bare-LF.
Definition at line 97 of file Parser.cc.
References Http::One::CrLf(), CharacterSet::LF, LineCharacters(), and RelaxedDelimiterCharacters().
clear()
void Http::One::TeChunkedParser::clear () override virtual
Set this parser back to a default state. Will DROP any reference to a buffer (does not free).
Implements Http::One::Parser.
Definition at line 31 of file TeChunkedParser.cc.
References Http::One::HTTP_PARSE_NONE.
Referenced by TeChunkedParser().
DelimiterCharacters()
const CharacterSet & Http::One::Parser::DelimiterCharacters () static inherited
Whitespace between protocol elements in restricted contexts like request line, status line, asctime-date, and credentials Seen in RFCs as SP but may be "relaxed" by us. See also: WhitespaceCharacters(). XXX: Misnamed and overused.
Definition at line 59 of file Parser.cc.
References Config, SquidConfig::onoff, SquidConfig::relaxed_header_parser, RelaxedDelimiterCharacters(), and CharacterSet::SP.
Referenced by Http::ContentLengthInterpreter::goodSuffix(), and Http::One::ResponseParser::ParseResponseStatus().
firstLineSize()
Parser::size_type Http::One::TeChunkedParser::firstLineSize () const inline override virtual
Implements Http::One::Parser.
Definition at line 69 of file TeChunkedParser.h.
getHostHeaderField()
char * Http::One::Parser::getHostHeaderField () inherited
Scan the mime header block (badly) for a Host header.
BUG: omits lines when searching for headers with obs-fold or multiple entries.
BUG: limits output to just 1KB when Squid accepts up to 64KB line length.
Returns
A pointer to a field-value of the first matching field-name, or NULL.
Definition at line 213 of file Parser.cc.
References CharacterSet::ALPHA, SBuf::caseCmp(), SBuf::chop(), SBuf::consume(), Http::One::CrLf(), debugs, CharacterSet::DIGIT, SBuf::findFirstNotOf(), GET_HDR_SZ, CharacterSet::LF, LineCharacters(), LOCAL_ARRAY, SBuf::npos, SBufToCstring(), SBuf::substr(), SBuf::trim(), and CharacterSet::WSP.
grabMimeBlock()
bool Http::One::Parser::grabMimeBlock (const char * which, const size_t limit) protected inherited
Scan to find the mime headers block for current message.
Return values
true If mime block (or a blocks non-existence) has been identified accurately within limit characters. mimeHeaderBlock_ has been updated and buf_ consumed.
false An error occurred, or no mime terminator found within limit.
Definition at line 157 of file Parser.cc.
References debugs, headersEnd(), Http::One::HTTP_PARSE_DONE, AnyP::PROTO_HTTP, AnyP::PROTO_ICY, and Http::scHeaderTooLarge.
headerBlockSize()
size_type Http::One::Parser::headerBlockSize () const inline inherited
size in bytes of the message headers including CRLF terminator(s) but excluding first-line bytes
Definition at line 73 of file Parser.h.
References SBuf::length(), and Http::One::Parser::mimeHeaderBlock_.
Referenced by Http::One::Parser::messageHeaderSize(), and Http::Message::parseHeader().
messageHeaderSize()
size_type Http::One::Parser::messageHeaderSize () const inline inherited
size in bytes of HTTP message block, includes first-line and mime headers excludes any body/entity/payload bytes excludes any garbage prefix before the first-line
Definition at line 78 of file Parser.h.
References Http::One::Parser::firstLineSize(), and Http::One::Parser::headerBlockSize().
Referenced by Http::Message::parseHeader().
messageProtocol()
const AnyP::ProtocolVersion & Http::One::Parser::messageProtocol () const inline inherited
Definition at line 84 of file Parser.h.
References Http::One::Parser::msgProtocol_.
mimeHeader()
SBuf Http::One::Parser::mimeHeader () const inline inherited
Definition at line 81 of file Parser.h.
References Http::One::Parser::mimeHeaderBlock_.
Referenced by Http::Message::parseHeader().
needsMoreData()
bool Http::One::Parser::needsMoreData () const inline inherited
Whether the parser is waiting on more data to complete parsing a message. Use to distinguish between incomplete data and error results when parse() returns false.
Definition at line 66 of file Parser.h.
References Http::One::HTTP_PARSE_DONE, and Http::One::Parser::parsingStage_.
Referenced by ConnStateData::handleChunkedRequestBody(), TestHttp1Parser::testDripFeed(), TestHttp1Parser::testParserConstruct(), and testResults().
needsMoreSpace()
bool Http::One::TeChunkedParser::needsMoreSpace () const
Definition at line 82 of file TeChunkedParser.cc.
References assert, and Http::One::HTTP_PARSE_CHUNK.
Referenced by ConnStateData::handleChunkedRequestBody().
parse()
bool Http::One::TeChunkedParser::parse (const SBuf & aBuf) override virtual
attempt to parse a message from the buffer
Return values
true if a full message was found and parsed
false if incomplete, invalid or no message was found
Implements Http::One::Parser.
Definition at line 45 of file TeChunkedParser.cc.
References DBG_DATA, debugs, Http::One::HTTP_PARSE_CHUNK, Http::One::HTTP_PARSE_CHUNK_EXT, Http::One::HTTP_PARSE_CHUNK_SZ, Http::One::HTTP_PARSE_MIME, Http::One::HTTP_PARSE_NONE, SBuf::length(), and Must.
Referenced by HttpStateData::decodeAndWriteReplyBody(), and ConnStateData::handleChunkedRequestBody().
parseChunkBody()
bool Http::One::TeChunkedParser::parseChunkBody (Tokenizer & tok) private
Definition at line 199 of file TeChunkedParser.cc.
References min(), and Must.
parseChunkEnd()
bool Http::One::TeChunkedParser::parseChunkEnd (Tokenizer & tok) private
Definition at line 224 of file TeChunkedParser.cc.
References Http::One::CrLf(), Http::One::HTTP_PARSE_CHUNK_SZ, and Must.
parseChunkExtensions()
void Http::One::TeChunkedParser::parseChunkExtensions (Tokenizer & callerTok) private
Parses the chunk-ext list (RFC 9112 section 7.1.1: chunk-ext = *(BWS ";" BWS chunk-ext-name [ BWS "=" BWS chunk-ext-val ])
Definition at line 147 of file TeChunkedParser.cc.
References Http::One::ParseBws().
parseChunkMetadataSuffix()
bool Http::One::TeChunkedParser::parseChunkMetadataSuffix (Tokenizer & tok) private
Parses "[chunk-ext] CRLF" from RFC 7230 section 4.1.1: chunk = chunk-size [ chunk-ext ] CRLF chunk-data CRLF last-chunk = 1*"0" [ chunk-ext ] CRLF
Definition at line 123 of file TeChunkedParser.cc.
References Http::One::CrLf(), Http::One::HTTP_PARSE_CHUNK, Http::One::HTTP_PARSE_MIME, and Http::One::ParseStrictBws().
parseChunkSize()
bool Http::One::TeChunkedParser::parseChunkSize (Tokenizer & tok) private
Definition at line 90 of file TeChunkedParser.cc.
References debugs, Here, Http::One::HTTP_PARSE_CHUNK_EXT, Must, size, and TexcHere.
parseExtensionValuesWith()
void Http::One::TeChunkedParser::parseExtensionValuesWith (ChunkExtensionValueParser * parser) inline
Instead of ignoring all chunk extension values, give the supplied parser a chance to handle them. Only applied to last-chunk (for now).
Definition at line 62 of file TeChunkedParser.h.
References customExtensionValueParser.
Referenced by Adaptation::Icap::ModXact::decideOnParsingBody().
parseOneChunkExtension()
void Http::One::TeChunkedParser::parseOneChunkExtension (Tokenizer & callerTok) private
Parses a single chunk-ext list element: chunk-ext = *(BWS ";" BWS chunk-ext-name [ BWS "=" BWS chunk-ext-val ])
Definition at line 173 of file TeChunkedParser.cc.
References Http::One::ChunkExtensionValueParser::Ignore(), Http::One::ParseBws(), and CharacterSet::TCHAR.
remaining()
const SBuf & Http::One::Parser::remaining () const inline inherited
Definition at line 98 of file Parser.h.
References Http::One::Parser::buf_.
Referenced by HttpStateData::decodeAndWriteReplyBody(), ConnStateData::handleChunkedRequestBody(), and TestHttp1Parser::testDripFeed().
setPayloadBuffer()
void Http::One::TeChunkedParser::setPayloadBuffer (MemBuf * parsedContent) inline
Definition at line 58 of file TeChunkedParser.h.
References theOut.
Referenced by HttpStateData::decodeAndWriteReplyBody(), and ConnStateData::handleChunkedRequestBody().
skipLineTerminator()
void Http::One::Parser::skipLineTerminator (Tokenizer & tok) const protected inherited
detect and skip the CRLF or (if tolerant) LF line terminator consume from the tokenizer.
Exceptions
exception on bad or InsufficientInput
Definition at line 66 of file Parser.cc.
References Config, Http::One::CrLf(), CharacterSet::LF, SquidConfig::onoff, and SquidConfig::relaxed_header_parser.
unfoldMime()
void Http::One::Parser::unfoldMime () private inherited
Replace obs-fold with a single SP,
RFC 7230 section 3.2.4 "A server that receives an obs-fold in a request message that is not within a message/http container MUST ... replace each received obs-fold with one or more SP octets prior to interpreting the field value or forwarding the message downstream."
"A proxy or gateway that receives an obs-fold in a response message that is not within a message/http container MUST ... replace each received obs-fold with one or more SP octets prior to interpreting the field value or forwarding the message downstream."
Definition at line 132 of file Parser.cc.
References CharacterSet::CR, CharacterSet::LF, CharacterSet::rename(), SBuf::substr(), and CharacterSet::WSP.
WhitespaceCharacters()
const CharacterSet & Http::One::Parser::WhitespaceCharacters () static inherited
Whitespace between regular protocol elements. Seen in RFCs as OWS, RWS, BWS, SP/HTAB but may be "relaxed" by us. See also: DelimiterCharacters().
Definition at line 52 of file Parser.cc.
References Config, SquidConfig::onoff, SquidConfig::relaxed_header_parser, RelaxedDelimiterCharacters(), and CharacterSet::WSP.
Referenced by Http::ContentLengthInterpreter::findDigits(), and Http::One::ParseBws().
Member Data Documentation
buf_
SBuf Http::One::Parser::buf_ protected inherited
Definition at line 146 of file Parser.h.
Referenced by Http::One::Parser::clear(), Http::One::Parser::remaining(), TestHttp1Parser::testParserConstruct(), and testResults().
customExtensionValueParser
ChunkExtensionValueParser* Http::One::TeChunkedParser::customExtensionValueParser private
An optional plugin for parsing and interpreting custom chunk-ext-val. This "visitor" object is owned by our creator.
Definition at line 85 of file TeChunkedParser.h.
Referenced by parseExtensionValuesWith().
hackExpectsMime_
bool Http::One::Parser::hackExpectsMime_ = false protected inherited
Definition at line 158 of file Parser.h.
Http1magic
const SBuf Http::One::Parser::Http1magic static protected inherited
Definition at line 143 of file Parser.h.
Referenced by Http::One::ResponseParser::firstLineSize().
mimeHeaderBlock_
SBuf Http::One::Parser::mimeHeaderBlock_ protected inherited
Definition at line 155 of file Parser.h.
Referenced by Http::One::Parser::clear(), Http::One::Parser::headerBlockSize(), and Http::One::Parser::mimeHeader().
msgProtocol_
AnyP::ProtocolVersion Http::One::Parser::msgProtocol_ protected inherited
Definition at line 152 of file Parser.h.
Referenced by Http::One::Parser::clear(), Http::One::ResponseParser::firstLineSize(), Http::One::RequestParser::http0(), Http::One::Parser::messageProtocol(), TestHttp1Parser::testParserConstruct(), and testResults().
parseStatusCode
Http::StatusCode Http::One::Parser::parseStatusCode = Http::scNone inherited
HTTP status code resulting from the parse process. to be used on the invalid message handling.
Http::scNone indicates incomplete parse, Http::scOkay indicates no error, other codes represent a parse error.
Definition at line 108 of file Parser.h.
Referenced by TestHttp1Parser::testParserConstruct(), and testResults().
parsingStage_
ParseState Http::One::Parser::parsingStage_ = HTTP_PARSE_NONE protected inherited
Definition at line 149 of file Parser.h.
Referenced by Http::One::Parser::clear(), Http::One::Parser::needsMoreData(), TestHttp1Parser::testParserConstruct(), and testResults().
theChunkSize
uint64_t Http::One::TeChunkedParser::theChunkSize private
Definition at line 80 of file TeChunkedParser.h.
theLeftBodySize
uint64_t Http::One::TeChunkedParser::theLeftBodySize private
Definition at line 81 of file TeChunkedParser.h.
theOut
MemBuf* Http::One::TeChunkedParser::theOut private
Definition at line 79 of file TeChunkedParser.h.
Referenced by ~TeChunkedParser(), and setPayloadBuffer().
The documentation for this class was generated from the following files:
squid/src/http/one/TeChunkedParser.h
squid/src/http/one/TeChunkedParser.cc