Squid Web Cache: ACLStringData Class Reference
ACLStringData Class Reference
#include <StringData.h>
Public Member Functions
ACLStringData ()
~ACLStringData () override
bool match (char const *) override
bool match (const SBuf &)
SBufList dump () const override
void parse () override
bool empty () const override
void insert (const char *)
Insert a string data value.
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Private Types
typedef std::set< SBuf > StringValues_t
Private Member Functions
MEMPROXY_CLASS (ACLStringData)
Private Attributes
StringValues_t stringValues
Detailed Description
Definition at line 18 of file StringData.h.
Member Typedef Documentation
StringValues_t
typedef std::set<SBuf> ACLStringData::StringValues_t private
Definition at line 36 of file StringData.h.
Constructor & Destructor Documentation
ACLStringData()
ACLStringData::ACLStringData () inline
Definition at line 23 of file StringData.h.
~ACLStringData()
ACLStringData::~ACLStringData () inline override
Definition at line 24 of file StringData.h.
Member Function Documentation
dump()
SBufList ACLStringData::dump () const override virtual
Implements ACLData< char const * >.
Definition at line 50 of file StringData.cc.
References stringValues.
Referenced by ACLCertificateData::dump(), and ACLNoteData::dump().
empty()
bool ACLStringData::empty () const override virtual
Implements ACLData< char const * >.
Definition at line 65 of file StringData.cc.
References stringValues.
Referenced by ACLCertificateData::empty(), and ACLNoteData::match().
insert()
void ACLStringData::insert (const char * value)
Definition at line 18 of file StringData.cc.
References stringValues.
Referenced by ACLAdaptationServiceData::parse(), and ACLCertificateData::parse().
lineOptions()
virtual const Acl::Options & ACLData< char const * >::lineOptions () inline virtual inherited
Reimplemented in ACLRegexData, and ACLUserData.
Definition at line 26 of file Data.h.
match() [1/2]
bool ACLStringData::match (char const * toFind) override virtual
Deprecated:
use match(SBuf&) instead.
Implements ACLData< char const * >.
Definition at line 39 of file StringData.cc.
References debugs, and match().
Referenced by match(), ACLNoteData::match(), and ACLCertificateData::match().
match() [2/2]
bool ACLStringData::match (const SBuf & tf)
Definition at line 24 of file StringData.cc.
References debugs, and stringValues.
MEMPROXY_CLASS()
ACLStringData::MEMPROXY_CLASS (ACLStringData) private
parse()
void ACLStringData::parse () override virtual
Implements ACLData< char const * >.
Definition at line 58 of file StringData.cc.
References stringValues, and ConfigParser::strtokFile().
Referenced by ACLCertificateData::parse(), and ACLNoteData::parse().
prepareForUse()
virtual void ACLData< char const * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
stringValues
StringValues_t ACLStringData::stringValues private
Definition at line 37 of file StringData.h.
Referenced by dump(), empty(), insert(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/StringData.h
squid/src/acl/StringData.cc