Squid Web Cache: Parser::BinaryTokenizerContext Class Reference
Parser::BinaryTokenizerContext Class Reference
enables efficient debugging with concise field names: Hello.version.major
#include <BinaryTokenizer.h>
Public Member Functions
BinaryTokenizerContext (BinaryTokenizer &tk, const char *aName)
starts parsing named object
~BinaryTokenizerContext ()
void close ()
ends parsing named object; repeated calls OK
void success ()
reports successful parsing of a named object and calls close()
Public Attributes
BinaryTokenizer & tokenizer
tokenizer being used for parsing
const BinaryTokenizerContext *const parent
enclosing context or nullptr
const char *const name
this context description or nullptr
uint64_t start
context parsing begins at this tokenizer position
Detailed Description
Definition at line 22 of file BinaryTokenizer.h.
Constructor & Destructor Documentation
BinaryTokenizerContext()
Parser::BinaryTokenizerContext::BinaryTokenizerContext (BinaryTokenizer & tk, const char * aName) inline explicit
Definition at line 136 of file BinaryTokenizer.h.
References Parser::BinaryTokenizer::context.
~BinaryTokenizerContext()
Parser::BinaryTokenizerContext::~BinaryTokenizerContext () inline
Definition at line 27 of file BinaryTokenizer.h.
References close().
Member Function Documentation
close()
void Parser::BinaryTokenizerContext::close () inline
Definition at line 147 of file BinaryTokenizer.h.
References Parser::BinaryTokenizer::context, parent, and tokenizer.
Referenced by ~BinaryTokenizerContext(), and success().
success()
void Parser::BinaryTokenizerContext::success () inline
Definition at line 153 of file BinaryTokenizer.h.
References close(), Parser::BinaryTokenizer::got(), Parser::BinaryTokenizer::parsed(), start, and tokenizer.
Referenced by Security::Alert::Alert(), Security::Extension::Extension(), Security::Handshake::Handshake(), Security::Sslv2Record::Sslv2Record(), Security::TLSPlaintext::TLSPlaintext(), Security::HandshakeParser::parseClientHelloHandshakeMessage(), Security::HandshakeParser::parseServerHelloHandshakeMessage(), Security::HandshakeParser::parseSniExtension(), and Security::HandshakeParser::parseVersion2HandshakeMessage().
Member Data Documentation
name
const char* const Parser::BinaryTokenizerContext::name
Definition at line 37 of file BinaryTokenizer.h.
Referenced by operator<<().
parent
const BinaryTokenizerContext* const Parser::BinaryTokenizerContext::parent
Definition at line 36 of file BinaryTokenizer.h.
Referenced by close(), and operator<<().
start
uint64_t Parser::BinaryTokenizerContext::start
Definition at line 38 of file BinaryTokenizer.h.
Referenced by success().
tokenizer
BinaryTokenizer& Parser::BinaryTokenizerContext::tokenizer
Definition at line 35 of file BinaryTokenizer.h.
Referenced by close(), and success().
The documentation for this class was generated from the following file:
squid/src/parser/BinaryTokenizer.h