Squid Web Cache: Ipc::Mem::Object< Class > Class Template Reference
Ipc::Mem::Object< Class > Class Template Reference
attaches to a shared memory segment with Class object owned by Owner
#include <Pointer.h>
Static Public Member Functions
static Pointer< Class > Old (const char *const id)
Private Member Functions
Object (const char *const id)
Object (const Object &)
Object & operator= (const Object &)
Private Attributes
Segment theSegment
shared memory segment that holds the object
Class * theObject
shared object
Friends
class Pointer< Class >
Detailed Description
template<class Class>
class Ipc::Mem::Object< Class >
Definition at line 61 of file Pointer.h.
Constructor & Destructor Documentation
Object() [1/2]
template<class Class > Ipc::Mem::Object< Class >::Object (const char *const id) explicit private
Definition at line 184 of file Pointer.h.
References Ipc::Mem::Segment::mem(), Must, Ipc::Mem::Segment::open(), Ipc::Mem::Segment::size(), Ipc::Mem::Object< Class >::theObject, and Ipc::Mem::Object< Class >::theSegment.
Object() [2/2]
template<class Class > Ipc::Mem::Object< Class >::Object (const Object< Class > &) private
Member Function Documentation
Old()
template<class Class > Pointer< Class > Ipc::Mem::Object< Class >::Old (const char *const id) static
Definition at line 194 of file Pointer.h.
operator=()
template<class Class > Object & Ipc::Mem::Object< Class >::operator= (const Object< Class > &) private
Friends And Related Symbol Documentation
Pointer< Class >
template<class Class > friend class Pointer< Class > friend
Definition at line 74 of file Pointer.h.
Member Data Documentation
theObject
template<class Class > Class* Ipc::Mem::Object< Class >::theObject private
Definition at line 74 of file Pointer.h.
Referenced by Ipc::Mem::Object< Class >::Object().
theSegment
template<class Class > Segment Ipc::Mem::Object< Class >::theSegment private
Definition at line 73 of file Pointer.h.
Referenced by Ipc::Mem::Object< Class >::Object().
The documentation for this class was generated from the following file:
squid/src/ipc/mem/Pointer.h