Squid Web Cache: DelayBucket Class Reference
DelayBucket Class Reference
Squid Components » Delay Pools API
#include <DelayBucket.h>
Public Member Functions
DelayBucket ()
int const & level () const
int & level ()
void stats (StoreEntry *) const
void update (DelaySpec const &, int incr)
int bytesWanted (int min, int max) const
void bytesIn (int qty)
void init (DelaySpec const &)
Private Attributes
int level_
Detailed Description
Definition at line 18 of file DelayBucket.h.
Constructor & Destructor Documentation
DelayBucket()
DelayBucket::DelayBucket () inline
Definition at line 22 of file DelayBucket.h.
Member Function Documentation
bytesIn()
void DelayBucket::bytesIn (int qty)
Definition at line 41 of file DelayBucket.cc.
References level().
Referenced by MessageDelayPool::bytesIn().
bytesWanted()
int DelayBucket::bytesWanted (int min, int max) const
Definition at line 34 of file DelayBucket.cc.
References level(), max(), and min().
init()
void DelayBucket::init (DelaySpec const & rate)
Definition at line 47 of file DelayBucket.cc.
References Config, SquidConfig::Delay, DelayConfig::initial, int, level(), and DelaySpec::max_bytes.
Referenced by Aggregate::Aggregate(), DelayUser::Id::Id(), DelayTagged::Id::Id(), and VectorPool::id().
level() [1/2]
int & DelayBucket::level () inline
Definition at line 26 of file DelayBucket.h.
References level_.
level() [2/2]
int const & DelayBucket::level () const inline
Definition at line 24 of file DelayBucket.h.
References level_.
Referenced by MessageDelayPool::MessageDelayPool(), bytesIn(), bytesWanted(), init(), MessageDelayPool::level(), stats(), and update().
stats()
void DelayBucket::stats (StoreEntry * entry) const
Definition at line 20 of file DelayBucket.cc.
References level(), and storeAppendPrintf().
Referenced by DelayTaggedBucket::stats(), DelayUserBucket::stats(), Aggregate::stats(), VectorPool::stats(), and ClassCHostPool::stats().
update()
void DelayBucket::update (DelaySpec const & rate, int incr)
Definition at line 26 of file DelayBucket.cc.
References level(), DelaySpec::max_bytes, and DelaySpec::restore_bps.
Referenced by MessageDelayPool::refillBucket(), Aggregate::update(), VectorPool::update(), and ClassCHostPool::update().
Member Data Documentation
level_
int DelayBucket::level_ private
Definition at line 35 of file DelayBucket.h.
Referenced by level(), and level().
The documentation for this class was generated from the following files:
squid/src/DelayBucket.h
squid/src/DelayBucket.cc