Squid Web Cache: Fs::Ufs::RebuildState Class Reference
Fs::Ufs::RebuildState Class Reference
#include <RebuildState.h>
Classes
struct Flags
Public Member Functions
RebuildState (const RefCount< UFSSwapDir > &sd)
virtual ~RebuildState ()
virtual bool error () const
virtual bool isDone () const
Public Attributes
RefCount< UFSSwapDir > sd
int n_read
Fs::Ufs::UFSSwapLogParser * LogParser
int curlvl1
int curlvl2
struct Fs::Ufs::RebuildState::Flags flags
int in_dir
int done
int fn
dirent_t * entry
DIR * td
SBuf fullpath
SBuf fullfilename
StoreRebuildData counts
Static Public Attributes
static EVH RebuildStep
Private Member Functions
CBDATA_CLASS (RebuildState)
void rebuildFromDirectory ()
process one cache file
void rebuildFromSwapLog ()
process one swap log entry
void rebuildStep ()
load entries from swap.state or files until we run out of entries or time
void addIfFresh (const cache_key *key, sfileno file_number, uint64_t swap_file_sz, time_t expires, time_t timestamp, time_t lastref, time_t lastmod, uint32_t refcount, uint16_t flags)
if the loaded entry metadata is still relevant, indexes the entry
bool evictStaleAndContinue (const cache_key *candidateKey, const time_t maxRef, int &staleCount)
int getNextFile (sfileno *, int *size)
void() callback (void *cbdata)
Private Attributes
bool fromLog
bool _done
void * cbdata
Detailed Description
Definition at line 24 of file RebuildState.h.
Constructor & Destructor Documentation
RebuildState()
Fs::Ufs::RebuildState::RebuildState (const RefCount< UFSSwapDir > & sd)
Definition at line 32 of file RebuildState.cc.
References Fs::Ufs::RebuildState::Flags::clean, counts, current_time, DBG_IMPORTANT, debugs, flags, fromLog, Fs::Ufs::UFSSwapLogParser::GetUFSSwapLogParser(), LogParser, Fs::Ufs::RebuildState::Flags::need_to_validate, sd, and StoreRebuildData::updateStartTime().
~RebuildState()
Fs::Ufs::RebuildState::~RebuildState () virtual
Definition at line 81 of file RebuildState.cc.
Member Function Documentation
addIfFresh()
void Fs::Ufs::RebuildState::addIfFresh (const cache_key * key, sfileno file_number, uint64_t swap_file_sz, time_t expires, time_t timestamp, time_t lastref, time_t lastmod, uint32_t refcount, uint16_t flags) private
Definition at line 220 of file RebuildState.cc.
References addedEntry(), counts, StoreRebuildData::dupcount, StoreRebuildData::objcount, storeDirSwapLog(), and SWAP_LOG_ADD.
callback()
void() Fs::Ufs::RebuildState::callback (void * cbdata) private
CBDATA_CLASS()
Fs::Ufs::RebuildState::CBDATA_CLASS (RebuildState) private
error()
bool Fs::Ufs::RebuildState::error () const virtual
Definition at line 464 of file RebuildState.cc.
evictStaleAndContinue()
bool Fs::Ufs::RebuildState::evictStaleAndContinue (const cache_key * candidateKey, const time_t maxRef, int & staleCount) private
Evicts a matching entry if it was last touched before caller's maxRef.
Returns
false only if the matching entry was touched at or after maxRef, indicating that the caller has supplied outdated maxRef.
Definition at line 251 of file RebuildState.cc.
References StoreRebuildData::clashcount, counts, and Store::Root().
getNextFile()
int Fs::Ufs::RebuildState::getNextFile (sfileno * filn_p, int * size) private
Definition at line 354 of file RebuildState.cc.
References asHex(), assert, SquidConfig::cacheSwap, Config, DBG_IMPORTANT, debugs, file_open(), Fs::Ufs::UFSSwapDir::FilenoBelongsHere(), MYNAME, Store::DiskConfig::n_configured, O_BINARY, SQUIDSBUFPH, SQUIDSBUFPRINT, store_open_disk_fd, and xstrerr().
isDone()
bool Fs::Ufs::RebuildState::isDone () const virtual
Definition at line 470 of file RebuildState.cc.
rebuildFromDirectory()
void Fs::Ufs::RebuildState::rebuildFromDirectory () private
Definition at line 142 of file RebuildState.cc.
References assert, counts, DBG_IMPORTANT, debugs, StoreEntry::expires, file_close(), StoreEntry::flags, MemBuf::init(), StoreEntry::lastModified(), StoreEntry::lastref, MYNAME, StoreEntry::refcount, size, SM_PAGE_SIZE, SQUID_MD5_DIGEST_LENGTH, store_open_disk_fd, storeRebuildLoadEntry(), storeRebuildParseEntry(), StoreEntry::swap_file_sz, StoreEntry::timestamp, and xstrerr().
rebuildFromSwapLog()
void Fs::Ufs::RebuildState::rebuildFromSwapLog () private
Definition at line 270 of file RebuildState.cc.
References asHex(), StoreRebuildData::bad_log_op, StoreRebuildData::badflags, StoreRebuildData::cancelcount, StoreRebuildData::clashcount, counts, DBG_IMPORTANT, debugs, EBIT_TEST, StoreSwapLogData::expires, StoreSwapLogData::flags, StoreRebuildData::invalid, StoreSwapLogData::key, KEY_PRIVATE, StoreSwapLogData::lastmod, StoreSwapLogData::lastref, log(), StoreSwapLogData::op, StoreSwapLogData::refcount, StoreSwapLogData::sane(), StoreRebuildData::scancount, storeKeyText(), StoreSwapLogData::swap_file_sz, StoreSwapLogData::swap_filen, SWAP_LOG_ADD, SWAP_LOG_DEL, swap_log_op_str, and StoreSwapLogData::timestamp.
rebuildStep()
void Fs::Ufs::RebuildState::rebuildStep () private
Definition at line 107 of file RebuildState.cc.
References current_time, debugs, getCurrentTime(), opt_foreground_rebuild, storeRebuildProgress(), and tvSubMsec().
Member Data Documentation
_done
bool Fs::Ufs::RebuildState::_done private
Definition at line 77 of file RebuildState.h.
cbdata
void* Fs::Ufs::RebuildState::cbdata private
Definition at line 80 of file RebuildState.h.
counts
StoreRebuildData Fs::Ufs::RebuildState::counts
Definition at line 59 of file RebuildState.h.
Referenced by RebuildState().
curlvl1
int Fs::Ufs::RebuildState::curlvl1
Definition at line 41 of file RebuildState.h.
curlvl2
int Fs::Ufs::RebuildState::curlvl2
Definition at line 42 of file RebuildState.h.
done
int Fs::Ufs::RebuildState::done
Definition at line 51 of file RebuildState.h.
entry
dirent_t* Fs::Ufs::RebuildState::entry
Definition at line 54 of file RebuildState.h.
flags
struct Fs::Ufs::RebuildState::Flags Fs::Ufs::RebuildState::flags
Referenced by RebuildState().
fn
int Fs::Ufs::RebuildState::fn
Definition at line 52 of file RebuildState.h.
fromLog
bool Fs::Ufs::RebuildState::fromLog private
Definition at line 76 of file RebuildState.h.
Referenced by RebuildState().
fullfilename
SBuf Fs::Ufs::RebuildState::fullfilename
Definition at line 57 of file RebuildState.h.
fullpath
SBuf Fs::Ufs::RebuildState::fullpath
Definition at line 56 of file RebuildState.h.
in_dir
int Fs::Ufs::RebuildState::in_dir
Definition at line 50 of file RebuildState.h.
LogParser
Fs::Ufs::UFSSwapLogParser* Fs::Ufs::RebuildState::LogParser
Definition at line 40 of file RebuildState.h.
Referenced by RebuildState().
n_read
int Fs::Ufs::RebuildState::n_read
Definition at line 38 of file RebuildState.h.
RebuildStep
void Fs::Ufs::RebuildState::RebuildStep static
Definition at line 29 of file RebuildState.h.
Referenced by Fs::Ufs::UFSSwapDir::rebuild().
sd
RefCount<UFSSwapDir> Fs::Ufs::RebuildState::sd
Definition at line 37 of file RebuildState.h.
Referenced by RebuildState().
td
DIR* Fs::Ufs::RebuildState::td
Definition at line 55 of file RebuildState.h.
The documentation for this class was generated from the following files:
squid/src/fs/ufs/RebuildState.h
squid/src/fs/ufs/RebuildState.cc