Squid Web Cache: RemovalPolicyWalker Class Reference
RemovalPolicyWalker Class Reference
#include <RemovalPolicy.h>
Public Member Functions
CBDATA_DECL_ (RemovalPolicyWalker, noexcept)
Public Attributes
RemovalPolicy * _policy
void * _data
const StoreEntry *(* Next)(RemovalPolicyWalker *walker)
void(* Done)(RemovalPolicyWalker *walker)
Detailed Description
Definition at line 55 of file RemovalPolicy.h.
Member Function Documentation
CBDATA_DECL_()
RemovalPolicyWalker::CBDATA_DECL_ (RemovalPolicyWalker , noexcept)
Member Data Documentation
_data
void* RemovalPolicyWalker::_data
Definition at line 61 of file RemovalPolicy.h.
Referenced by heap_walkDone(), heap_walkInit(), heap_walkNext(), lru_walkDone(), lru_walkInit(), and lru_walkNext().
_policy
RemovalPolicy* RemovalPolicyWalker::_policy
Definition at line 60 of file RemovalPolicy.h.
Referenced by heap_walkDone(), heap_walkInit(), heap_walkNext(), lru_walkDone(), and lru_walkInit().
Done
void(* RemovalPolicyWalker::Done) (RemovalPolicyWalker *walker)
Definition at line 63 of file RemovalPolicy.h.
Referenced by heap_walkInit(), lru_walkInit(), and Fs::Ufs::UFSSwapDir::writeCleanDone().
Next
const StoreEntry *(* RemovalPolicyWalker::Next) (RemovalPolicyWalker *walker)
Definition at line 62 of file RemovalPolicy.h.
Referenced by heap_walkInit(), lru_walkInit(), and UFSCleanLog::nextEntry().
The documentation for this class was generated from the following file:
squid/src/RemovalPolicy.h