Squid Web Cache: Ipc::Mem::Segment Class Reference
Ipc::Mem::Segment Class Reference
POSIX shared memory segment.
#include <Segment.h>
Public Member Functions
Segment (const char *const id)
Create a shared memory segment.
~Segment ()
void create (const off_t aSize)
Create a new shared memory segment. Unlinks the segment on destruction.
void open (const bool unlinkWhenDone)
const String & name ()
shared memory segment name
off_t size ()
shared memory segment size
void * mem ()
pointer to the next chunk
void * reserve (size_t chunkSize)
reserve and return the next chunk
Static Public Member Functions
static bool Enabled ()
Whether shared memory support is available.
static SBuf Name (const SBuf &prefix, const char *suffix)
concatenates parts of a name to form a complete name (or its prefix)
Static Public Attributes
static const char * BasePath = DEFAULT_STATEDIR
common path of all segment names in path-based environments
Private Member Functions
Segment (const Segment &)
Segment & operator= (const Segment &)
void checkSupport (const char *const context)
Private Attributes
const String theName
shared memory segment file name
void * theMem
pointer to mmapped shared memory segment
off_t theSize
shared memory segment size
off_t theReserved
the total number of reserve()d bytes
bool doUnlink
whether the segment should be unlinked on destruction
Detailed Description
Definition at line 23 of file Segment.h.
Constructor & Destructor Documentation
Segment() [1/2]
Ipc::Mem::Segment::Segment (const char *const id)
Definition at line 304 of file Segment.cc.
~Segment()
Ipc::Mem::Segment::~Segment ()
Definition at line 309 of file Segment.cc.
References debugs, and Segments.
Segment() [2/2]
Ipc::Mem::Segment::Segment (const Segment &) private
Member Function Documentation
checkSupport()
void Ipc::Mem::Segment::checkSupport (const char *const context) private
Definition at line 361 of file Segment.cc.
References debugs, and fatalf().
create()
void Ipc::Mem::Segment::create (const off_t aSize)
Definition at line 326 of file Segment.cc.
References assert, debugs, fatalf(), and Segments.
Referenced by Ipc::Mem::Owner< Class >::Owner().
Enabled()
bool Ipc::Mem::Segment::Enabled () static
Definition at line 320 of file Segment.cc.
References IamWorkerProcess(), and UsingSmp().
Referenced by MemStoreRr::finalizeConfig().
mem()
void * Ipc::Mem::Segment::mem () inline
Definition at line 41 of file Segment.h.
References reserve().
Referenced by Ipc::Mem::Object< Class >::Object(), Ipc::Mem::Owner< Class >::Owner(), and Ipc::Mem::Owner< Class >::Owner().
name()
const String & Ipc::Mem::Segment::name () inline
Definition at line 39 of file Segment.h.
References theName.
Name()
SBuf Ipc::Mem::Segment::Name (const SBuf & prefix, const char * suffix) static
Definition at line 51 of file Segment.cc.
References SBuf::append().
Referenced by createOwner(), Rock::SwapDir::inodeMapPath(), Rock::Rebuild::Stats::Path(), StoreMapAnchorsId(), StoreMapFileNosId(), and StoreMapSlicesId().
open()
void Ipc::Mem::Segment::open (const bool unlinkWhenDone)
opens an existing shared memory segment
Parameters
unlinkWhenDone whether to delete the segment on destruction
Definition at line 344 of file Segment.cc.
References assert, debugs, fatalf(), Segments, theMem, and theSize.
Referenced by Ipc::Mem::Object< Class >::Object(), and Ipc::Mem::Owner< Class >::Owner().
operator=()
Segment & Ipc::Mem::Segment::operator= (const Segment &) private
reserve()
void * Ipc::Mem::Segment::reserve (size_t chunkSize)
Definition at line 37 of file Segment.cc.
References assert, Must, theMem, theReserved, and theSize.
Referenced by mem(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), Ipc::Mem::Owner< Class >::New(), and Ipc::Mem::Owner< Class >::New().
size()
off_t Ipc::Mem::Segment::size () inline
Definition at line 40 of file Segment.h.
References theSize.
Referenced by Ipc::Mem::Object< Class >::Object().
Member Data Documentation
BasePath
const char * Ipc::Mem::Segment::BasePath = DEFAULT_STATEDIR static
Definition at line 45 of file Segment.h.
doUnlink
bool Ipc::Mem::Segment::doUnlink private
Definition at line 79 of file Segment.h.
theMem
void* Ipc::Mem::Segment::theMem private
Definition at line 76 of file Segment.h.
Referenced by open(), and reserve().
theName
const String Ipc::Mem::Segment::theName private
Definition at line 75 of file Segment.h.
Referenced by name().
theReserved
off_t Ipc::Mem::Segment::theReserved private
Definition at line 78 of file Segment.h.
Referenced by reserve().
theSize
off_t Ipc::Mem::Segment::theSize private
Definition at line 77 of file Segment.h.
Referenced by open(), reserve(), and size().
The documentation for this class was generated from the following files:
squid/src/ipc/mem/Segment.h
squid/src/ipc/mem/Segment.cc