Squid Web Cache: Acl::AndNode Class Reference
Acl::AndNode Class Reference
#include <BoolOps.h>
Public Types
using Pointer = RefCount< Node >
Public Member Functions
char const * typeString () const override
void parse () override
parses node representation in squid.conf; dies on failures
bool resumeMatchingAt (ACLChecklist *checklist, Acl::Nodes::const_iterator pos) const
Resumes matching (suspended by an async call) at the given position.
Nodes::size_type childrenCount () const
the number of children nodes
void prepareForUse () override
bool empty () const override
SBufList dump () const override
size_t lineParse ()
void add (Acl::Node *node)
appends the node to the collection and takes control over it
void * operator new (size_t)
void operator delete (void *)
void context (const SBuf &aName, const char *configuration)
sets user-specified ACL name and squid.conf context
bool matches (ACLChecklist *checklist) const
void parseFlags ()
configures Acl::Node options, throwing on configuration errors
virtual bool isProxyAuth () const
virtual bool valid () const
int cacheMatchAcl (dlink_list *cache, ACLChecklist *)
virtual int matchForCache (ACLChecklist *checklist)
void dumpWhole (const char *directiveName, std::ostream &)
Static Public Member Functions
static void ParseNamedAcl (ConfigParser &, NamedAcls *&)
parses acl directive parts that follow directive name (i.e. "acl")
static void Initialize ()
static Acl::Node * FindByName (const SBuf &)
A configured ACL with a given name or nil.
Public Attributes
SBuf name
char * cfgline = nullptr
Protected Member Functions
int match (ACLChecklist *checklist) override
Matches the actual data in checklist against this Acl::Node.
Protected Attributes
Nodes nodes
children of this intermediate node
Private Member Functions
MEMPROXY_CLASS (AndNode)
int doMatch (ACLChecklist *checklist, Nodes::const_iterator start) const override
virtual bool requiresAle () const
whether our (i.e. shallow) match() requires checklist to have a AccessLogEntry
virtual bool requiresRequest () const
whether our (i.e. shallow) match() requires checklist to have a request
virtual bool requiresReply () const
whether our (i.e. shallow) match() requires checklist to have a reply
virtual const Acl::Options & options ()
virtual const Acl::Options & lineOptions ()
Static Private Member Functions
static void ParseNamed (ConfigParser &, NamedAcls &, const SBuf &name)
parses acl directive parts that follow aclname
Detailed Description
An inner ACL expression tree node representing a boolean conjunction (AND) operator applied to a list of child tree nodes. For example, conditions expressed on a single http_access line are ANDed.
Definition at line 42 of file BoolOps.h.
Member Typedef Documentation
Pointer
using Acl::Node::Pointer = RefCount<Node> inherited
Definition at line 29 of file Node.h.
Member Function Documentation
add()
void Acl::InnerNode::add (Acl::Node * node) inherited
Definition at line 36 of file InnerNode.cc.
References assert.
Referenced by Acl::NotNode::NotNode(), Acl::Tree::add(), Acl::Tree::add(), Acl::AllOf::parse(), and ParseAclWithAction().
cacheMatchAcl()
int Acl::Node::cacheMatchAcl (dlink_list * cache, ACLChecklist * checklist) inherited
Definition at line 401 of file Acl.cc.
References acl_proxy_auth_match_cache::acl_data, dlink_node::data, debugs, dlinkAddTail(), dlink_list::head, acl_proxy_auth_match_cache::link, acl_proxy_auth_match_cache::matchrv, and dlink_node::next.
Referenced by ACLProxyAuth::matchProxyAuth().
childrenCount()
Nodes::size_type Acl::InnerNode::childrenCount () const inline inherited
Definition at line 29 of file InnerNode.h.
References Acl::InnerNode::nodes.
Referenced by aclParseAccessLine(), and Acl::AllOf::parse().
context()
void Acl::Node::context (const SBuf & aName, const char * configuration) inherited
Definition at line 220 of file Acl.cc.
References safe_free, and xstrdup.
Referenced by aclParseAccessLine(), aclParseAclList(), Acl::AllOf::parse(), and ParseAclWithAction().
doMatch()
int Acl::AndNode::doMatch (ACLChecklist * checklist, Nodes::const_iterator start) const override private virtual
checks whether the nodes match, starting with the given one kids determine what a match means for their type of intermediate nodes
Implements Acl::InnerNode.
Definition at line 71 of file BoolOps.cc.
References ACLChecklist::keepMatching(), and ACLChecklist::matchChild().
dump()
SBufList Acl::InnerNode::dump () const override virtual inherited
Implements Acl::Node.
Reimplemented in Acl::NotNode.
Definition at line 81 of file InnerNode.cc.
dumpWhole()
void Acl::Node::dumpWhole (const char * directiveName, std::ostream & os) inherited
Prints aggregated "acl" (or similar) directive configuration, including the given directive name, ACL name, ACL type, and ACL parameters. The printed parameters are collected from all same-name "acl" directives.
Definition at line 371 of file Acl.cc.
References asList().
empty()
bool Acl::InnerNode::empty () const override virtual inherited
Implements Acl::Node.
Definition at line 30 of file InnerNode.cc.
Referenced by aclParseAccessLine().
FindByName()
Acl::Node * Acl::Node::FindByName (const SBuf & name) static inherited
Definition at line 159 of file Acl.cc.
References assert, Config, debugs, and SquidConfig::namedAcls.
Referenced by aclIsProxyAuth(), Acl::InnerNode::lineParse(), parse_ftp_epsv(), and TestACLMaxUserIP::testParseLine().
Initialize()
void Acl::Node::Initialize () static inherited
Definition at line 471 of file Acl.cc.
References Config, debugs, and SquidConfig::namedAcls.
Referenced by serverConnectionsOpen().
isProxyAuth()
bool Acl::Node::isProxyAuth () const virtual inherited
Reimplemented in ACLProxyAuth, and ACLExternal.
Definition at line 354 of file Acl.cc.
lineOptions()
virtual const Acl::Options & Acl::Node::lineOptions () inline private virtual inherited
Returns
(linked) "line" Options supported by this Acl::Node
See also
Acl::Node::options()
Reimplemented in ACLExtUser, Acl::ParameterizedNode< P >, Acl::ParameterizedNode< ACLData< ACLChecklist * > >, Acl::ParameterizedNode< ACLData< AnyP::ProtocolType > >, Acl::ParameterizedNode< ACLData< const char * > >, Acl::ParameterizedNode< ACLData< const HttpHeader & > >, Acl::ParameterizedNode< ACLData< const Security::CertErrors * > >, Acl::ParameterizedNode< ACLData< err_type > >, Acl::ParameterizedNode< ACLData< hier_code > >, Acl::ParameterizedNode< ACLData< HttpRequestMethod > >, Acl::ParameterizedNode< ACLData< int > >, Acl::ParameterizedNode< ACLData< NotePairs::Entry * > >, Acl::ParameterizedNode< ACLData< X509 * > >, Acl::ParameterizedNode< ACLData< XactionStep > >, Acl::ParameterizedNode< ACLTimeData >, and ACLProxyAuth.
Definition at line 102 of file Node.h.
References Acl::NoOptions().
lineParse()
size_t Acl::InnerNode::lineParse () inherited
parses a [ [!]acl1 [!]acl2... ] sequence, appending to nodes
Returns
the number of parsed ACL names
Definition at line 44 of file InnerNode.cc.
References config_input_line, DBG_CRITICAL, debugs, Acl::Node::FindByName(), self_destruct(), ConfigParser::strtokFile(), and xstrdup.
Referenced by aclParseAccessLine(), aclParseAclList(), Acl::AllOf::parse(), and ParseAclWithAction().
match()
int Acl::InnerNode::match (ACLChecklist * checklist) override protected virtual inherited
Implements Acl::Node.
Definition at line 90 of file InnerNode.cc.
matches()
bool Acl::Node::matches (ACLChecklist * checklist) const inherited
Orchestrates matching checklist against the Acl::Node using match(), after checking preconditions and while providing debugging.
Returns
true if and only if there was a successful match. Updates the checklist state on match, async, and failure.
Definition at line 189 of file Acl.cc.
References ACLChecklist::asyncInProgress(), DBG_IMPORTANT, debugs, ACLChecklist::hasAle(), ACLChecklist::hasReply(), ACLChecklist::hasRequest(), ACLChecklist::setLastCheckedName(), and ACLChecklist::verifyAle().
Referenced by ACLChecklist::matchAndFinish().
matchForCache()
int Acl::Node::matchForCache (ACLChecklist * checklist) virtual inherited
Reimplemented in ACLProxyAuth.
Definition at line 383 of file Acl.cc.
References fatal().
MEMPROXY_CLASS()
Acl::AndNode::MEMPROXY_CLASS (AndNode) private
operator delete()
void Acl::Node::operator delete (void *) inherited
Definition at line 153 of file Acl.cc.
References fatal().
operator new()
void * Acl::Node::operator new (size_t) inherited
Definition at line 147 of file Acl.cc.
References fatal().
options()
virtual const Acl::Options & Acl::Node::options () inline private virtual inherited
Returns
(linked) 'global' Options supported by this Acl::Node
Reimplemented in Acl::DestinationDomainCheck, ACLDestinationIP, Acl::AnnotationCheck, Acl::ServerNameCheck, and ACLMaxUserIP.
Definition at line 98 of file Node.h.
References Acl::NoOptions().
parse()
void Acl::AndNode::parse () override virtual
Implements Acl::Node.
Definition at line 84 of file BoolOps.cc.
References assert.
parseFlags()
void Acl::Node::parseFlags () inherited
Definition at line 360 of file Acl.cc.
References Acl::ParseFlags().
ParseNamed()
void Acl::Node::ParseNamed (ConfigParser & parser, NamedAcls & namedAcls, const SBuf & name) static private inherited
Definition at line 253 of file Acl.cc.
References Assure, SBuf::cmp(), config_input_line, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::destruct(), fatalf(), HttpPortList, Acl::Make(), and ConfigParser::NextToken().
ParseNamedAcl()
void Acl::Node::ParseNamedAcl (ConfigParser & parser, NamedAcls *& namedAcls) static inherited
Definition at line 229 of file Acl.cc.
References CallParser(), DBG_CRITICAL, debugs, ConfigParser::destruct(), RefCount< C >::Make(), and ConfigParser::NextToken().
Referenced by parse_acl(), and TestACLMaxUserIP::testParseLine().
prepareForUse()
void Acl::InnerNode::prepareForUse () override virtual inherited
Reimplemented from Acl::Node.
Definition at line 23 of file InnerNode.cc.
References Acl::InnerNode::nodes.
requiresAle()
bool Acl::Node::requiresAle () const private virtual inherited
Reimplemented in ACLExternal.
Definition at line 443 of file Acl.cc.
requiresReply()
bool Acl::Node::requiresReply () const private virtual inherited
Reimplemented in Acl::HttpRepHeaderCheck, ACLHTTPStatus, and Acl::ReplyHeaderCheck< header >.
Definition at line 449 of file Acl.cc.
requiresRequest()
bool Acl::Node::requiresRequest () const private virtual inherited
Reimplemented in Acl::DestinationDomainCheck, ACLExtUser, Acl::HierCodeCheck, Acl::HttpReqHeaderCheck, Acl::MethodCheck, Acl::NoteCheck, Acl::ProtocolCheck, Acl::RequestHeaderCheck< header >, Acl::ServerNameCheck, Acl::TransactionInitiator, Acl::UrlCheck, Acl::UrlLoginCheck, Acl::UrlPathCheck, Acl::UrlPortCheck, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
Definition at line 455 of file Acl.cc.
resumeMatchingAt()
bool Acl::InnerNode::resumeMatchingAt (ACLChecklist * checklist, Acl::Nodes::const_iterator pos) const inherited
Definition at line 96 of file InnerNode.cc.
References ACLChecklist::asyncInProgress(), and debugs.
Referenced by ACLChecklist::matchAndFinish(), and ACLChecklist::matchChild().
typeString()
char const * Acl::AndNode::typeString () const override virtual
Implements Acl::Node.
Definition at line 65 of file BoolOps.cc.
valid()
bool Acl::Node::valid () const virtual inherited
Reimplemented in ACLMaxConnection, ACLRandom, Acl::ServerNameCheck, ACLMaxUserIP, ACLProxyAuth, and ACLExternal.
Definition at line 183 of file Acl.cc.
Member Data Documentation
cfgline
char* Acl::Node::cfgline = nullptr inherited
Definition at line 83 of file Node.h.
name
SBuf Acl::Node::name inherited
Either aclname parameter from the explicitly configured acl directive or a label generated for an internal ACL tree node. All Node objects corresponding to one Squid configuration have unique names. See also: context() and FindByName().
Definition at line 81 of file Node.h.
Referenced by Acl::NotNode::NotNode(), aclDestroyAccessList(), Acl::AnnotateClientCheck::match(), Acl::AnnotateTransactionCheck::match(), Acl::SourceDomainCheck::match(), ACLDestinationIP::match(), ACLRandom::match(), ACLExternal::parse(), and ACLMaxConnection::prepareForUse().
nodes
Nodes Acl::InnerNode::nodes protected inherited
Definition at line 51 of file InnerNode.h.
Referenced by Acl::InnerNode::childrenCount(), Acl::InnerNode::prepareForUse(), Acl::Tree::treeDump(), and Acl::Tree::winningAction().
The documentation for this class was generated from the following files:
squid/src/acl/BoolOps.h
squid/src/acl/BoolOps.cc