Squid Web Cache: VectorPool::Id Class Reference
VectorPool::Id Class Reference
Squid Components » Delay Pools API » Delay Pools Internal
Public Types
typedef RefCount< DelayIdComposite > Pointer
Public Member Functions
void * operator new (size_t byteCount)
void operator delete (void *address)
Id (RefCount< VectorPool >, int)
int bytesWanted (int min, int max) const override
void bytesIn (int qty) override
virtual void delayRead (const AsyncCallPointer &)
Static Public Member Functions
static int UseCount ()
Static Private Member Functions
static Mem::AllocatorProxy & Pool ()
Private Attributes
RefCount< VectorPool > theVector
int theIndex
Detailed Description
Definition at line 136 of file delay_pools.cc.
Member Typedef Documentation
Pointer
typedef RefCount<DelayIdComposite> DelayIdComposite::Pointer inherited
Definition at line 23 of file DelayIdComposite.h.
Constructor & Destructor Documentation
Id()
VectorPool::Id::Id (RefCount< VectorPool > aPool, int anIndex)
Definition at line 714 of file delay_pools.cc.
Member Function Documentation
bytesIn()
void VectorPool::Id::bytesIn (int qty) override virtual
Implements DelayIdComposite.
Definition at line 724 of file delay_pools.cc.
bytesWanted()
int VectorPool::Id::bytesWanted (int min, int max) const override virtual
Implements DelayIdComposite.
Definition at line 718 of file delay_pools.cc.
References max(), and min().
delayRead()
virtual void DelayIdComposite::delayRead (const AsyncCallPointer &) inline virtual inherited
Reimplemented in Aggregate::AggregateId, DelayTagged::Id, and DelayVector::Id.
Definition at line 29 of file DelayIdComposite.h.
References fatal().
Referenced by DelayId::delayRead().
operator delete()
void VectorPool::Id::operator delete (void * address) inline
Definition at line 138 of file delay_pools.cc.
operator new()
void * VectorPool::Id::operator new (size_t byteCount) inline
Definition at line 138 of file delay_pools.cc.
Pool()
static Mem::AllocatorProxy & VectorPool::Id::Pool () inline static private
Definition at line 138 of file delay_pools.cc.
UseCount()
static int VectorPool::Id::UseCount () inline static
Definition at line 138 of file delay_pools.cc.
Member Data Documentation
theIndex
int VectorPool::Id::theIndex private
Definition at line 147 of file delay_pools.cc.
theVector
RefCount<VectorPool> VectorPool::Id::theVector private
Definition at line 146 of file delay_pools.cc.
The documentation for this class was generated from the following file:
squid/src/delay_pools.cc