Squid Web Cache: Rock::StoreFileSystem Class Reference
Rock::StoreFileSystem Class Reference
Storage Filesystems
,
#include <RockStoreFileSystem.h>
Public Types
typedef std::vector< StoreFileSystem * >::iterator iterator
typedef std::vector< StoreFileSystem * >::const_iterator const_iterator
Public Member Functions
StoreFileSystem ()
~StoreFileSystem () override
char const * type () const override
SwapDir * createSwapDir () override
Static Public Member Functions
static void Stats (StoreEntry *sentry)
static void FsAdd (StoreFileSystem &)
static StoreFileSystem * FindByType (const char *type)
static std::vector< StoreFileSystem * > const & FileSystems ()
Private Member Functions
StoreFileSystem (const StoreFileSystem &)
StoreFileSystem & operator= (const StoreFileSystem &)
Static Private Member Functions
static std::vector< StoreFileSystem * > & GetFileSystems ()
Static Private Attributes
static std::vector< StoreFileSystem * > * _FileSystems = nullptr
Detailed Description
Definition at line 19 of file RockStoreFileSystem.h.
Member Typedef Documentation
const_iterator
typedef std::vector<StoreFileSystem*>::const_iterator StoreFileSystem::const_iterator inherited
Definition at line 98 of file StoreFileSystem.h.
iterator
typedef std::vector<StoreFileSystem*>::iterator StoreFileSystem::iterator inherited
Definition at line 97 of file StoreFileSystem.h.
Constructor & Destructor Documentation
StoreFileSystem() [1/2]
StoreFileSystem::StoreFileSystem ()
Definition at line 15 of file RockStoreFileSystem.cc.
References StoreFileSystem::FsAdd().
~StoreFileSystem()
StoreFileSystem::~StoreFileSystem () override
Definition at line 20 of file RockStoreFileSystem.cc.
StoreFileSystem() [2/2]
Rock::StoreFileSystem::StoreFileSystem (const StoreFileSystem &) private
Member Function Documentation
createSwapDir()
SwapDir * StoreFileSystem::createSwapDir () override virtual
Implements StoreFileSystem.
Definition at line 31 of file RockStoreFileSystem.cc.
FileSystems()
std::vector< StoreFileSystem * > const & StoreFileSystem::FileSystems () static inherited
Definition at line 30 of file StoreFileSystem.cc.
References StoreFileSystem::GetFileSystems().
Referenced by StoreFileSystem::FindByType().
FindByType()
StoreFileSystem * StoreFileSystem::FindByType (const char * type) static inherited
Definition at line 45 of file StoreFileSystem.cc.
References StoreFileSystem::FileSystems(), and StoreFileSystem::type().
Referenced by Store::Disks::Parse().
FsAdd()
void StoreFileSystem::FsAdd (StoreFileSystem & instance) static inherited
Definition at line 17 of file StoreFileSystem.cc.
References assert, StoreFileSystem::GetFileSystems(), and StoreFileSystem::type().
Referenced by StoreFileSystem(), and Fs::Ufs::StoreFSufs< TheSwapDir >::StoreFSufs().
GetFileSystems()
std::vector< StoreFileSystem * > & StoreFileSystem::GetFileSystems () static private inherited
Definition at line 36 of file StoreFileSystem.cc.
References StoreFileSystem::_FileSystems.
Referenced by StoreFileSystem::FileSystems(), and StoreFileSystem::FsAdd().
operator=()
StoreFileSystem & Rock::StoreFileSystem::operator= (const StoreFileSystem &) private
Stats()
static void Rock::StoreFileSystem::Stats (StoreEntry * sentry) static
type()
char const * StoreFileSystem::type () const override virtual
Implements StoreFileSystem.
Definition at line 25 of file RockStoreFileSystem.cc.
Member Data Documentation
_FileSystems
std::vector< StoreFileSystem * > * StoreFileSystem::_FileSystems = nullptr static private inherited
Definition at line 108 of file StoreFileSystem.h.
Referenced by StoreFileSystem::GetFileSystems().
The documentation for this class was generated from the following files:
squid/src/fs/rock/RockStoreFileSystem.h
squid/src/fs/rock/RockStoreFileSystem.cc