Squid Web Cache: Acl::OptionsParser Class Reference
Acl::OptionsParser Class Reference
parses/validates/stores ACL options; skips/preserves parameter flags
Public Member Functions
OptionsParser (const Options &options)
void parse ()
Private Types
using SupportedOption = std::pair< const Option *, bool >
Private Member Functions
SupportedOption supportedOption (const SBuf &name) const
Private Attributes
const Options & options_
caller-supported, linked options
Detailed Description
Definition at line 47 of file Options.cc.
Member Typedef Documentation
SupportedOption
using Acl::OptionsParser::SupportedOption = std::pair<const Option *, bool > private
Definition at line 56 of file Options.cc.
Constructor & Destructor Documentation
OptionsParser()
Acl::OptionsParser::OptionsParser (const Options & options) explicit
Definition at line 169 of file Options.cc.
Member Function Documentation
parse()
void Acl::OptionsParser::parse ()
Definition at line 189 of file Options.cc.
References debugs, Acl::OptionExtractor::extractOne(), Acl::OptionExtractor::hasValue, Acl::OptionExtractor::name, TexcHere, ToSBuf(), Acl::OptionExtractor::value(), Acl::Option::valueNone, Acl::Option::valueOptional, and Acl::Option::valueRequired.
Referenced by Acl::ParseFlags().
supportedOption()
Acl::OptionsParser::SupportedOption Acl::OptionsParser::supportedOption (const SBuf & name) const private
Returns
named supported option paired with a name-based enable/disable flag
Definition at line 176 of file Options.cc.
References SBuf::cmp(), TexcHere, and ToSBuf().
Member Data Documentation
options_
const Options& Acl::OptionsParser::options_ private
Definition at line 59 of file Options.cc.
The documentation for this class was generated from the following file:
squid/src/acl/Options.cc