Squid Web Cache: PconnModule Class Reference
PconnModule Class Reference
Persistent Connection API
#include <pconn.h>
Public Member Functions
PconnModule ()
void registerWithCacheManager (void)
void add (PconnPool *)
void remove (PconnPool *)
unregister and forget about this pool object
void dump (std::ostream &yaml)
Static Public Member Functions
static PconnModule * GetInstance ()
static void DumpWrapper (StoreEntry *e)
Private Types
typedef std::set< PconnPool * > Pools
unordered PconnPool collection
Private Attributes
Pools pools
all live pools
Static Private Attributes
static PconnModule * instance = nullptr
Detailed Description
The global registry of persistent connection pools.
Definition at line 172 of file pconn.h.
Member Typedef Documentation
Pools
typedef std::set<PconnPool*> PconnModule::Pools private
Definition at line 192 of file pconn.h.
Constructor & Destructor Documentation
PconnModule()
PconnModule::PconnModule ()
Definition at line 573 of file pconn.cc.
References registerWithCacheManager().
Referenced by GetInstance().
Member Function Documentation
add()
void PconnModule::add (PconnPool * aPool)
Definition at line 597 of file pconn.cc.
References pools.
Referenced by PconnPool::PconnPool().
dump()
void PconnModule::dump (std::ostream & yaml)
Definition at line 609 of file pconn.cc.
References pools.
Referenced by DumpWrapper().
DumpWrapper()
void PconnModule::DumpWrapper (StoreEntry * e) static
A thunk to the still C like CacheManager callback api.
Definition at line 616 of file pconn.cc.
References dump(), and GetInstance().
Referenced by registerWithCacheManager().
GetInstance()
PconnModule * PconnModule::GetInstance () static
the module is a singleton until we have instance based cachemanager management
Definition at line 579 of file pconn.cc.
References PconnModule(), and instance.
Referenced by PconnPool::PconnPool(), PconnPool::~PconnPool(), and DumpWrapper().
registerWithCacheManager()
void PconnModule::registerWithCacheManager (void)
Definition at line 588 of file pconn.cc.
References DumpWrapper(), Mgr::no, Mgr::RegisterAction(), Mgr::yaml, and Mgr::yes.
Referenced by PconnModule().
remove()
void PconnModule::remove (PconnPool * aPool)
Definition at line 603 of file pconn.cc.
References pools.
Referenced by PconnPool::~PconnPool().
Member Data Documentation
instance
PconnModule * PconnModule::instance = nullptr static private
Definition at line 195 of file pconn.h.
Referenced by GetInstance().
pools
Pools PconnModule::pools private
Definition at line 193 of file pconn.h.
Referenced by add(), dump(), and remove().
The documentation for this class was generated from the following files:
squid/src/pconn.h
squid/src/pconn.cc