Squid Web Cache: AppendingStreamBuf< Buffer > Class Template Reference
AppendingStreamBuf< Buffer > Class Template Reference
write-only std::streambuf that append()s all writes to a given Buffer
#include <PackableStream.h>
Public Member Functions
AppendingStreamBuf (Buffer &p)
~AppendingStreamBuf () override=default
Protected Member Functions
int_type overflow (int_type aChar=traits_type::eof()) override
int sync () override
std::streamsize xsputn (const char *chars, std::streamsize number) override
Private Member Functions
void postInit ()
for specializations that must customize the last construction step
void postSync ()
for specializations that must customize the last sync() step
void lowAppend (const char *s, const std::streamsize n)
Private Attributes
Buffer & buf_
the associated character sequence (a.k.a. the sink)
Detailed Description
template<class Buffer>
class AppendingStreamBuf< Buffer >
Definition at line 19 of file PackableStream.h.
Constructor & Destructor Documentation
AppendingStreamBuf()
template<class Buffer > AppendingStreamBuf< Buffer >::AppendingStreamBuf (Buffer & p) inline explicit
Definition at line 22 of file PackableStream.h.
References AppendingStreamBuf< Buffer >::postInit().
~AppendingStreamBuf()
template<class Buffer > AppendingStreamBuf< Buffer >::~AppendingStreamBuf () override default
Member Function Documentation
lowAppend()
template<class Buffer > void AppendingStreamBuf< Buffer >::lowAppend (const char * s, const std::streamsize n) inline private
Definition at line 62 of file PackableStream.h.
References AppendingStreamBuf< Buffer >::buf_.
Referenced by AppendingStreamBuf< Buffer >::overflow(), AppendingStreamBuf< Buffer >::sync(), and AppendingStreamBuf< Buffer >::xsputn().
overflow()
template<class Buffer > int_type AppendingStreamBuf< Buffer >::overflow (int_type aChar = traits_type::eof()) inline override protected
Definition at line 28 of file PackableStream.h.
References AppendingStreamBuf< Buffer >::lowAppend(), and AppendingStreamBuf< Buffer >::sync().
postInit()
template<class Buffer > void AppendingStreamBuf< Buffer >::postInit () inline private
Definition at line 57 of file PackableStream.h.
Referenced by AppendingStreamBuf< Buffer >::AppendingStreamBuf().
postSync()
template<class Buffer > void AppendingStreamBuf< Buffer >::postSync () inline private
Definition at line 60 of file PackableStream.h.
Referenced by AppendingStreamBuf< Buffer >::sync().
sync()
template<class Buffer > int AppendingStreamBuf< Buffer >::sync () inline override protected
Definition at line 43 of file PackableStream.h.
References AppendingStreamBuf< Buffer >::lowAppend(), and AppendingStreamBuf< Buffer >::postSync().
Referenced by AppendingStreamBuf< Buffer >::overflow().
xsputn()
template<class Buffer > std::streamsize AppendingStreamBuf< Buffer >::xsputn (const char * chars, std::streamsize number) inline override protected
Definition at line 50 of file PackableStream.h.
References AppendingStreamBuf< Buffer >::lowAppend().
Member Data Documentation
buf_
template<class Buffer > Buffer& AppendingStreamBuf< Buffer >::buf_ private
Definition at line 64 of file PackableStream.h.
Referenced by AppendingStreamBuf< Buffer >::lowAppend().
The documentation for this class was generated from the following file:
squid/src/base/PackableStream.h