Squid Web Cache: Ssl::CertificateDb::Row Class Reference
Ssl::CertificateDb::Row Class Reference
A wrapper for OpenSSL database row of TXT_DB database.
#include <certificate_db.h>
Public Member Functions
Row ()
Create row wrapper.
Row (char **row, size_t width)
Create row wrapper for row with width items.
~Row ()
Delete all row.
void setValue (size_t number, char const *value)
Set cell's value in row.
char ** getRow ()
Raw row.
void reset ()
Abandon row and don't free memory.
Private Attributes
char ** row
Raw row.
size_t width
Number of cells in the row.
Detailed Description
Definition at line 77 of file certificate_db.h.
Constructor & Destructor Documentation
Row() [1/2]
Ssl::CertificateDb::Row::Row ()
Definition at line 117 of file certificate_db.cc.
References row, and width.
Row() [2/2]
Ssl::CertificateDb::Row::Row (char ** row, size_t width)
Definition at line 124 of file certificate_db.cc.
References row.
~Row()
Ssl::CertificateDb::Row::~Row ()
Definition at line 129 of file certificate_db.cc.
References max().
Member Function Documentation
getRow()
char ** Ssl::CertificateDb::Row::getRow ()
Definition at line 171 of file certificate_db.cc.
Referenced by Ssl::CertificateDb::addCertAndPrivateKey(), and Ssl::CertificateDb::pure_find().
reset()
void Ssl::CertificateDb::Row::reset ()
Definition at line 153 of file certificate_db.cc.
Referenced by Ssl::CertificateDb::addCertAndPrivateKey().
setValue()
void Ssl::CertificateDb::Row::setValue (size_t number, char const * value)
Definition at line 158 of file certificate_db.cc.
References assert.
Referenced by Ssl::CertificateDb::addCertAndPrivateKey(), and Ssl::CertificateDb::pure_find().
Member Data Documentation
row
char** Ssl::CertificateDb::Row::row private
Definition at line 90 of file certificate_db.h.
Referenced by Row(), and Row().
width
size_t Ssl::CertificateDb::Row::width private
Definition at line 91 of file certificate_db.h.
Referenced by Row().
The documentation for this class was generated from the following files:
squid/src/security/cert_generators/file/certificate_db.h
squid/src/security/cert_generators/file/certificate_db.cc