Squid Web Cache: DelayIdComposite Class Reference
DelayIdComposite Class Reference abstract
#include <DelayIdComposite.h>
Public Types
typedef RefCount< DelayIdComposite > Pointer
Public Member Functions
~DelayIdComposite () override
virtual int bytesWanted (int min, int max) const =0
virtual void bytesIn (int qty)=0
virtual void delayRead (const AsyncCallPointer &)
Detailed Description
Definition at line 19 of file DelayIdComposite.h.
Member Typedef Documentation
Pointer
typedef RefCount<DelayIdComposite> DelayIdComposite::Pointer
Definition at line 23 of file DelayIdComposite.h.
Constructor & Destructor Documentation
~DelayIdComposite()
DelayIdComposite::~DelayIdComposite () inline override
Definition at line 24 of file DelayIdComposite.h.
Member Function Documentation
bytesIn()
virtual void DelayIdComposite::bytesIn (int qty) pure virtual
Implemented in Aggregate::AggregateId, VectorPool::Id, ClassCHostPool::Id, DelayTagged::Id, DelayUser::Id, DelayVector::Id, and NullDelayId.
Referenced by DelayId::bytesIn().
bytesWanted()
virtual int DelayIdComposite::bytesWanted (int min, int max) const pure virtual
Implemented in Aggregate::AggregateId, VectorPool::Id, ClassCHostPool::Id, DelayTagged::Id, DelayUser::Id, DelayVector::Id, and NullDelayId.
Referenced by DelayId::bytesWanted().
delayRead()
virtual void DelayIdComposite::delayRead (const AsyncCallPointer &) inline virtual
Reimplemented in Aggregate::AggregateId, DelayTagged::Id, and DelayVector::Id.
Definition at line 29 of file DelayIdComposite.h.
References fatal().
Referenced by DelayId::delayRead().
The documentation for this class was generated from the following file:
squid/src/DelayIdComposite.h