Squid Web Cache: Mgr::Response Class Reference
Mgr::Response Class Reference
#include <Response.h>
Public Types
typedef RefCount< Response > Pointer
Public Member Functions
Response (Ipc::RequestId, Action::Pointer anAction=nullptr)
sender's constructor
Response (const Ipc::TypedMsgHdr &msg)
from recvmsg()
void pack (Ipc::TypedMsgHdr &msg) const override
prepare for sendmsg()
Ipc::Response::Pointer clone () const override
returns a copy of this
bool hasAction () const
whether response contain action object
const Action & getAction () const
returns action object
QuestionerId intendedRecepient () const
for Mine() tests
Public Attributes
Action::Pointer action
action relating to response
RequestId requestId
the ID of the request we are responding to
Detailed Description
A response to Mgr::Request. May carry strand action data to be aggregated with data from other strands.
Definition at line 23 of file Response.h.
Member Typedef Documentation
Pointer
typedef RefCount<Response> Ipc::Response::Pointer inherited
Definition at line 26 of file Response.h.
Constructor & Destructor Documentation
Response() [1/2]
Mgr::Response::Response (Ipc::RequestId aRequestId, Action::Pointer anAction = nullptr)
Definition at line 21 of file Response.cc.
References action, and Must.
Response() [2/2]
Mgr::Response::Response (const Ipc::TypedMsgHdr & msg) explicit
Definition at line 27 of file Response.cc.
References Ipc::TypedMsgHdr::checkType(), CacheManager::createNamedAction(), CacheManager::GetInstance(), Ipc::TypedMsgHdr::getPod(), Ipc::TypedMsgHdr::getString(), Ipc::TypedMsgHdr::hasMoreData(), Ipc::mtCacheMgrResponse, Must, and String::termedBuf().
Member Function Documentation
clone()
Ipc::Response::Pointer Mgr::Response::clone () const override virtual
Implements Ipc::Response.
Definition at line 55 of file Response.cc.
getAction()
const Mgr::Action & Mgr::Response::getAction () const
Definition at line 67 of file Response.cc.
References Must.
Referenced by Mgr::Inquirer::aggregate().
hasAction()
bool Mgr::Response::hasAction () const
Definition at line 61 of file Response.cc.
Referenced by Mgr::Inquirer::aggregate().
intendedRecepient()
QuestionerId Ipc::Response::intendedRecepient () const inline inherited
Definition at line 33 of file Response.h.
References Ipc::RequestId::questioner(), and Ipc::Response::requestId.
pack()
void Mgr::Response::pack (Ipc::TypedMsgHdr & msg) const override virtual
Implements Ipc::Response.
Definition at line 43 of file Response.cc.
References Ipc::mtCacheMgrResponse, Must, Ipc::TypedMsgHdr::putPod(), Ipc::TypedMsgHdr::putString(), and Ipc::TypedMsgHdr::setType().
Referenced by Ipc::Coordinator::handleCacheMgrRequest(), and Mgr::Action::sendResponse().
Member Data Documentation
action
Action::Pointer Mgr::Response::action
Definition at line 39 of file Response.h.
Referenced by Response().
requestId
RequestId Ipc::Response::requestId inherited
Definition at line 36 of file Response.h.
Referenced by Ipc::Strand::handleCacheMgrResponse(), Ipc::Inquirer::HandleRemoteAck(), Ipc::Strand::handleSnmpResponse(), and Ipc::Response::intendedRecepient().
The documentation for this class was generated from the following files:
squid/src/mgr/Response.h
squid/src/mgr/Response.cc