Squid Web Cache: Ssl::GeneralNameMatcher Class Reference
Ssl::GeneralNameMatcher Class Reference abstract
an algorithm for checking/testing/comparing X.509 certificate names
#include <support.h>
Public Member Functions
bool match (const Ssl::GeneralName &) const
whether the given name satisfies algorithm conditions
Protected Member Functions
virtual bool matchDomainName (const Dns::DomainName &) const =0
virtual bool matchIp (const Ip::Address &) const =0
Detailed Description
Definition at line 298 of file support.h.
Member Function Documentation
match()
bool Ssl::GeneralNameMatcher::match (const Ssl::GeneralName & name) const
Definition at line 84 of file support.cc.
References Assure, AnyP::Host::domainName(), AnyP::Host::ip(), matchDomainName(), and matchIp().
Referenced by Ssl::HasMatchingSubjectName().
matchDomainName()
virtual bool Ssl::GeneralNameMatcher::matchDomainName (const Dns::DomainName &) const protected pure virtual
Implemented in Acl::ServerNameMatcher, CommonNamesPrinter, and Ssl::OneNameMatcher.
Referenced by match().
matchIp()
virtual bool Ssl::GeneralNameMatcher::matchIp (const Ip::Address &) const protected pure virtual
Implemented in Acl::ServerNameMatcher, CommonNamesPrinter, and Ssl::OneNameMatcher.
Referenced by match().
The documentation for this class was generated from the following files:
squid/src/ssl/support.h
squid/src/ssl/support.cc