Squid Web Cache: Fs::Ufs::UFSSwapDir Class Reference
Fs::Ufs::UFSSwapDir Class Reference
Storage Filesystems » UFS Storage Filesystem
#include <UFSSwapDir.h>
Public Types
typedef RefCount< Disk > Pointer
Public Member Functions
UFSSwapDir (char const *aType, const char *aModuleType)
~UFSSwapDir () override
void create () override
create system resources needed for this store to operate in the future
void init () override
void dump (StoreEntry &) const override
bool doubleCheck (StoreEntry &) override
bool unlinkdUseful () const override
whether SwapDir may benefit from unlinkd
void statfs (StoreEntry &) const override
void maintain () override
perform regular periodic maintenance; TODO: move to UFSSwapDir::Maintain
void evictCached (StoreEntry &) override
void evictIfFound (const cache_key *) override
bool canStore (const StoreEntry &e, int64_t diskSpaceNeeded, int &load) const override
check whether we can store the entry; if we can, report current load
void reference (StoreEntry &) override
somebody needs this entry (many cache replacement policies need to know)
bool dereference (StoreEntry &) override
StoreIOState::Pointer createStoreIO (StoreEntry &, StoreIOState::STIOCB *, void *) override
StoreIOState::Pointer openStoreIO (StoreEntry &, StoreIOState::STIOCB *, void *) override
void openLog () override
void closeLog () override
int writeCleanStart () override
void writeCleanDone () override
void logEntry (const StoreEntry &e, int op) const override
void parse (int index, char *path) override
void reconfigure () override
int callback () override
called once every main loop iteration; TODO: Move to UFS code.
void sync () override
prepare for shutdown
void finalizeSwapoutSuccess (const StoreEntry &) override
finalize the successful swapout that has been already noticed by Store
void finalizeSwapoutFailure (StoreEntry &) override
abort the failed swapout that has been already noticed by Store
uint64_t currentSize () const override
current size
uint64_t currentCount () const override
the total number of objects stored right now
ConfigOption * getOptionTree () const override
bool smpAware () const override
whether this disk storage is capable of serving multiple workers
bool hasReadableEntry (const StoreEntry &) const override
void unlinkFile (sfileno f)
char * fullPath (sfileno, char *) const
void closeTmpSwapLog ()
FILE * openTmpSwapLog (int *clean_flag, int *zero_flag)
char * swapSubDir (int subdirn) const
int mapBitTest (sfileno filn)
void mapBitReset (sfileno filn)
void mapBitSet (sfileno filn)
StoreEntry * addDiskRestore (const cache_key *key, sfileno file_number, uint64_t swap_file_sz, time_t expires, time_t timestamp, time_t lastref, time_t lastmod, uint32_t refcount, uint16_t flags, int clean)
int validFileno (sfileno filn, int flag) const
int mapBitAllocate ()
bool validL2 (int) const
bool validL1 (int) const
void replacementAdd (StoreEntry *e)
void replacementRemove (StoreEntry *e)
char const * type () const
virtual bool needsDiskStrand () const
needs a dedicated kid process
virtual bool active () const
virtual bool doReportStat () const
whether stat should be reported by this SwapDir
virtual void diskFull ()
StoreEntry * get (const cache_key *) override
uint64_t maxSize () const override
uint64_t minSize () const override
the minimum size the store will shrink to via normal housekeeping
int64_t maxObjectSize () const override
the maximum size of a storable object; -1 if unlimited
void maxObjectSize (int64_t newMax)
void getStats (StoreInfoStats &stats) const override
collect statistics
void stat (StoreEntry &) const override
int64_t minObjectSize () const
the size of the smallest entry this cache_dir can store
bool objectSizeIsAcceptable (int64_t objSize) const
virtual void disconnect (StoreEntry &)
called when the entry is about to forget its association with cache_dir
bool canLog (StoreEntry const &e) const
virtual void updateHeaders (StoreEntry *)
make stored metadata and HTTP headers the same as in the given entry
virtual bool anchorToCache (StoreEntry &)
virtual bool updateAnchored (StoreEntry &)
Static Public Member Functions
static bool IsUFSDir (SwapDir *sd)
static int DirClean (int swap_index)
static bool FilenoBelongsHere (int fn, int cachedir, int level1dir, int level2dir)
Public Attributes
Fs::Ufs::UFSStrategy * IO
void * fsdata
char * path
int index
int disker
disker kid id dedicated to this SwapDir or -1
RemovalPolicy * repl
int removals
int scanned
struct Store::Disk::Flags flags
CleanLog * cleanLog
struct {
int blksize
} fs
Protected Member Functions
void parseOptions (int reconfiguring)
void dumpOptions (StoreEntry *e) const
virtual bool allowOptionReconfigure (const char *const) const
int64_t sizeInBlocks (const int64_t size) const
Protected Attributes
FileMap * map
int suggest
int l1
int l2
uint64_t max_size
maximum allocatable size of the storage area
int64_t min_objsize
minimum size of any object stored here (-1 for no limit)
int64_t max_objsize
maximum size of any object stored here (-1 for no limit)
Private Member Functions
void parseSizeL1L2 ()
bool pathIsDirectory (const char *path) const
bool verifyCacheDirs ()
void rebuild ()
int createDirectory (const char *path, int)
void createSwapSubDirs ()
void dumpEntry (StoreEntry &) const
SBuf logFile (char const *ext=nullptr) const
void changeIO (DiskIOModule *)
bool optionIOParse (char const *option, const char *value, int reconfiguring)
void optionIODump (StoreEntry *e) const
bool optionReadOnlyParse (char const *option, const char *value, int reconfiguring)
void optionReadOnlyDump (StoreEntry *e) const
bool optionObjectSizeParse (char const *option, const char *value, int reconfiguring)
void optionObjectSizeDump (StoreEntry *e) const
Static Private Member Functions
static int HandleCleanEvent ()
safely cleans a few unused files if possible
Private Attributes
int swaplog_fd
ConfigOptionVector * currentIOOptions
char const * ioType
uint64_t cur_size
currently used space in the storage area
uint64_t n_disk_objects
total number of objects stored
bool rebuilding_
whether RebuildState is writing the new swap.state
char const * theType
Static Private Attributes
static size_t NumberOfUFSDirs = 0
static int * UFSDirToGlobalDirMapping = nullptr
static EVH CleanEvent
Detailed Description
Definition at line 30 of file UFSSwapDir.h.
Member Typedef Documentation
Pointer
typedef RefCount<Disk> Store::Disk::Pointer inherited
Definition at line 25 of file Disk.h.
Constructor & Destructor Documentation
UFSSwapDir()
Fs::Ufs::UFSSwapDir::UFSSwapDir (char const * aType, const char * aModuleType)
Definition at line 307 of file UFSSwapDir.cc.
References DiskIOModule::Find(), and IO.
~UFSSwapDir()
Fs::Ufs::UFSSwapDir::~UFSSwapDir () override
Definition at line 328 of file UFSSwapDir.cc.
References file_close(), and xfree.
Member Function Documentation
active()
bool Store::Disk::active () const virtual inherited
may be used in this strand
Definition at line 236 of file Disk.cc.
References IamWorkerProcess(), and KidIdentifier.
Referenced by Store::Disks::anchorToCache(), and Store::Disk::doReportStat().
addDiskRestore()
StoreEntry * Fs::Ufs::UFSSwapDir::addDiskRestore (const cache_key * key, sfileno file_number, uint64_t swap_file_sz, time_t expires, time_t timestamp, time_t lastref, time_t lastmod, uint32_t refcount, uint16_t flags, int clean)
Add a new object to the cache with empty memory copy and pointer to disk
This method is used to rebuild a store from disk
Definition at line 788 of file UFSSwapDir.cc.
References asHex(), StoreEntry::attachToDisk(), debugs, EBIT_CLR, ENTRY_VALIDATED, StoreEntry::expires, StoreEntry::flags, StoreEntry::hashInsert(), StoreEntry::lastModified(), StoreEntry::lastref, n_disk_objects, NOT_IN_MEMORY, PING_NONE, StoreEntry::ping_status, StoreEntry::refcount, StoreEntry::setMemStatus(), STORE_OK, StoreEntry::store_status, storeKeyText(), StoreEntry::swap_file_sz, StoreEntry::swap_filen, SWAPOUT_DONE, and StoreEntry::timestamp.
allowOptionReconfigure()
virtual bool Store::Disk::allowOptionReconfigure (const char * const) const inline protected virtual inherited
Reimplemented in Rock::SwapDir.
Definition at line 85 of file Disk.h.
Referenced by Rock::SwapDir::allowOptionReconfigure().
anchorToCache()
virtual bool Store::Controlled::anchorToCache (StoreEntry &) inline virtual inherited
tie StoreEntry to this storage if this storage has a matching entry
Return values
true if this storage has a matching entry
Reimplemented in Rock::SwapDir, MemStore, and Store::Disks.
Definition at line 39 of file Controlled.h.
Referenced by Store::Disks::anchorToCache().
callback()
int Fs::Ufs::UFSSwapDir::callback () override virtual
Reimplemented from Store::Storage.
Definition at line 1256 of file UFSSwapDir.cc.
canLog()
bool Store::Disk::canLog (StoreEntry const & e) const inherited
Definition at line 188 of file Disk.cc.
References EBIT_TEST, ENTRY_SPECIAL, StoreEntry::flags, StoreEntry::hasDisk(), KEY_PRIVATE, RELEASE_REQUEST, StoreEntry::swap_file_sz, and StoreEntry::swappedOut().
canStore()
bool Fs::Ufs::UFSSwapDir::canStore (const StoreEntry & e, int64_t diskSpaceNeeded, int & load) const override virtual
Implements Store::Disk.
Definition at line 115 of file UFSSwapDir.cc.
References Store::Disk::canStore(), IO, Fs::Ufs::UFSStrategy::load(), and Fs::Ufs::UFSStrategy::shedLoad().
changeIO()
void Fs::Ufs::UFSSwapDir::changeIO (DiskIOModule * module) private
Definition at line 194 of file UFSSwapDir.cc.
References safe_free, DiskIOModule::type(), and xstrdup.
closeLog()
void Fs::Ufs::UFSSwapDir::closeLog () override virtual
Reimplemented from Store::Disk.
Definition at line 755 of file UFSSwapDir.cc.
References assert, debugs, file_close(), and safe_free.
closeTmpSwapLog()
void Fs::Ufs::UFSSwapDir::closeTmpSwapLog ()
Definition at line 831 of file UFSSwapDir.cc.
References assert, SBuf::c_str(), DBG_IMPORTANT, debugs, fatalf(), file_close(), file_open(), FileRename(), O_BINARY, SQUIDSBUFPH, SQUIDSBUFPRINT, and xstrerr().
create()
void Fs::Ufs::UFSSwapDir::create () override virtual
Implements Store::Storage.
Definition at line 300 of file UFSSwapDir.cc.
References debugs.
Referenced by TestUfs::testUfsSearch().
createDirectory()
int Fs::Ufs::UFSSwapDir::createDirectory (const char * path, int should_exist) private
Definition at line 604 of file UFSSwapDir.cc.
References DBG_IMPORTANT, debugs, fatalf(), getCurrentTime(), and xstrerr().
createStoreIO()
StoreIOState::Pointer Fs::Ufs::UFSSwapDir::createStoreIO (StoreEntry & e, StoreIOState::STIOCB * aCallback, void * callback_data) override virtual
Implements Store::Disk.
Definition at line 546 of file UFSSwapDir.cc.
createSwapSubDirs()
void Fs::Ufs::UFSSwapDir::createSwapSubDirs () private
Definition at line 665 of file UFSSwapDir.cc.
References DBG_IMPORTANT, debugs, LOCAL_ARRAY, and MAXPATHLEN.
currentCount()
uint64_t Fs::Ufs::UFSSwapDir::currentCount () const inline override virtual
Implements Store::Storage.
Definition at line 73 of file UFSSwapDir.h.
References n_disk_objects.
currentSize()
uint64_t Fs::Ufs::UFSSwapDir::currentSize () const inline override virtual
Implements Store::Storage.
Definition at line 72 of file UFSSwapDir.h.
References cur_size.
dereference()
bool Fs::Ufs::UFSSwapDir::dereference (StoreEntry & e) override virtual
somebody no longer needs this entry (usually after calling reference()) return false iff the idle entry should be destroyed
Implements Store::Controlled.
Definition at line 534 of file UFSSwapDir.cc.
References debugs, StoreEntry::repl, StoreEntry::swap_dirn, and StoreEntry::swap_filen.
DirClean()
int Fs::Ufs::UFSSwapDir::DirClean (int swap_index) static
Definition at line 1312 of file UFSSwapDir.cc.
References SBuf::appendf(), asHex(), assert, SBuf::c_str(), DBG_CRITICAL, debugs, FilenoBelongsHere(), StatCounters::files_cleaned, INDEXSD, l1, l2, mapBitTest(), MYNAME, Store::Disk::path, rev_int_sort(), safeunlink(), statCounter, StatCounters::swap, validFileno(), and xstrerr().
disconnect()
virtual void Store::Disk::disconnect (StoreEntry &) inline virtual inherited
Reimplemented in Rock::SwapDir.
Definition at line 71 of file Disk.h.
Referenced by storeGetPublic().
diskFull()
void Store::Disk::diskFull () virtual inherited
Notify this disk that it is full. XXX move into a protected api call between store files and their stores, rather than a top level api call
Reimplemented in Rock::SwapDir.
Definition at line 145 of file Disk.cc.
References DBG_IMPORTANT, and debugs.
Referenced by storeSwapOutFileClosed().
doReportStat()
virtual bool Store::Disk::doReportStat () const inline virtual inherited
Reimplemented in Rock::SwapDir.
Definition at line 35 of file Disk.h.
References Store::Disk::active().
doubleCheck()
bool Fs::Ufs::UFSSwapDir::doubleCheck (StoreEntry & e) override virtual
Reimplemented from Store::Disk.
Definition at line 349 of file UFSSwapDir.cc.
References DBG_CRITICAL, debugs, StoreEntry::swap_file_sz, and StoreEntry::swap_filen.
dump()
void Fs::Ufs::UFSSwapDir::dump (StoreEntry & entry) const override virtual
Reimplemented from Store::Disk.
Definition at line 1228 of file UFSSwapDir.cc.
References PRIu64, and storeAppendPrintf().
dumpEntry()
void Fs::Ufs::UFSSwapDir::dumpEntry (StoreEntry & e) const private
Definition at line 341 of file UFSSwapDir.cc.
References asHex(), DBG_CRITICAL, debugs, StoreEntry::dump(), and StoreEntry::swap_filen.
dumpOptions()
void Store::Disk::dumpOptions (StoreEntry * e) const protected inherited
Definition at line 307 of file Disk.cc.
References ConfigOption::dump().
evictCached()
void Fs::Ufs::UFSSwapDir::evictCached (StoreEntry & e) override virtual
Prevent new get() calls from returning the matching entry. If the matching entry is unused, it may be removed from the store now. The store entry is matched using either e attachment info or e.key.
Implements Store::Storage.
Definition at line 1178 of file UFSSwapDir.cc.
References debugs, StoreEntry::detachFromDisk(), StoreEntry::hasDisk(), StoreEntry::locked(), n_disk_objects, StoreEntry::swap_file_sz, StoreEntry::swap_filen, StoreEntry::swappedOut(), and unlinkFile().
evictIfFound()
void Fs::Ufs::UFSSwapDir::evictIfFound (const cache_key *) override virtual
An evictCached() equivalent for callers that did not get() a StoreEntry. Callers with StoreEntry objects must use evictCached() instead.
Implements Store::Storage.
Definition at line 1200 of file UFSSwapDir.cc.
FilenoBelongsHere()
bool Fs::Ufs::UFSSwapDir::FilenoBelongsHere (int fn, int cachedir, int level1dir, int level2dir) static
check whether swapfile belongs to the specified cachedir/l1dir/l2dir
Parameters
cachedir the number of the cachedir which is being tested
level1dir level-1 dir in the cachedir
level2dir level-2 dir
Definition at line 1114 of file UFSSwapDir.cc.
References assert, SquidConfig::cacheSwap, Config, F1, F2, INDEXSD, IsUFSDir(), l1, l2, and Store::DiskConfig::n_configured.
Referenced by DirClean(), and Fs::Ufs::RebuildState::getNextFile().
finalizeSwapoutFailure()
void Fs::Ufs::UFSSwapDir::finalizeSwapoutFailure (StoreEntry &) override virtual
Implements Store::Disk.
Definition at line 1275 of file UFSSwapDir.cc.
References debugs.
finalizeSwapoutSuccess()
void Fs::Ufs::UFSSwapDir::finalizeSwapoutSuccess (const StoreEntry &) override virtual
Implements Store::Disk.
Definition at line 1268 of file UFSSwapDir.cc.
References n_disk_objects, and StoreEntry::swap_file_sz.
fullPath()
char * Fs::Ufs::UFSSwapDir::fullPath (sfileno filn, char * fullpath) const
Definition at line 1235 of file UFSSwapDir.cc.
References LOCAL_ARRAY, and MAXPATHLEN.
get()
StoreEntry * Store::Disk::get (const cache_key *) override virtual inherited
Returns
a possibly unlocked/unregistered stored entry with key (or nil) The returned entry might not match the caller's Store ID or method. The caller must abandon()/release() the entry or register it with Root(). This method must not trigger slow I/O operations (e.g., disk swap in).
Implements Store::Controlled.
Definition at line 393 of file Disk.cc.
getOptionTree()
ConfigOption * Fs::Ufs::UFSSwapDir::getOptionTree () const override virtual
Reimplemented from Store::Disk.
Definition at line 250 of file UFSSwapDir.cc.
References Store::Disk::getOptionTree(), optionIODump(), and optionIOParse().
getStats()
void Store::Disk::getStats (StoreInfoStats & stats) const override virtual inherited
Implements Store::Storage.
Definition at line 52 of file Disk.cc.
References StoreInfoStats::Part::capacity, StoreInfoStats::Part::count, StoreInfoStats::Part::size, and StoreInfoStats::swap.
HandleCleanEvent()
int Fs::Ufs::UFSSwapDir::HandleCleanEvent () static private
Definition at line 1039 of file UFSSwapDir.cc.
References assert, SquidConfig::cacheSwap, Config, INDEXSD, IsUFSDir(), l1, l2, Store::DiskConfig::n_configured, RandomSeed32(), Store::Controller::store_dirs_rebuilding, and xcalloc().
hasReadableEntry()
bool Fs::Ufs::UFSSwapDir::hasReadableEntry (const StoreEntry &) const inline override virtual
as long as ufs relies on the global store_table to index entries, it is wrong to ask individual ufs cache_dirs whether they have an entry
Implements Store::Disk.
Definition at line 78 of file UFSSwapDir.h.
init()
void Fs::Ufs::UFSSwapDir::init () override virtual
Start preparing the store for use. To check readiness, callers should use readable() and writable() methods.
Implements Store::Storage.
Definition at line 272 of file UFSSwapDir.cc.
References debugs, eventAdd(), fatal(), and fsBlockSize().
IsUFSDir()
bool Fs::Ufs::UFSSwapDir::IsUFSDir (SwapDir * sd) static
Definition at line 1102 of file UFSSwapDir.cc.
Referenced by FilenoBelongsHere(), and HandleCleanEvent().
logEntry()
void Fs::Ufs::UFSSwapDir::logEntry (const StoreEntry & e, int op) const override virtual
Reimplemented from Store::Disk.
Definition at line 1283 of file UFSSwapDir.cc.
References debugs, StoreEntry::expires, StoreSwapLogData::expires, file_write(), StoreSwapLogData::finalize(), StoreEntry::flags, StoreSwapLogData::flags, FreeObject(), hash_link::key, StoreSwapLogData::key, StoreSwapLogData::lastmod, StoreEntry::lastModified(), StoreEntry::lastref, StoreSwapLogData::lastref, StoreSwapLogData::op, StoreEntry::refcount, StoreSwapLogData::refcount, SQUID_MD5_DIGEST_LENGTH, StoreEntry::swap_file_sz, StoreSwapLogData::swap_file_sz, StoreEntry::swap_filen, StoreSwapLogData::swap_filen, StoreEntry::timestamp, and StoreSwapLogData::timestamp.
logFile()
SBuf Fs::Ufs::UFSSwapDir::logFile (char const * ext = nullptr) const private
Definition at line 689 of file UFSSwapDir.cc.
References SBuf::append(), SBuf::appendf(), SBuf::cmp(), Config, SquidConfig::Log, MAXPATHLEN, SquidConfig::swap, and xstrncpy().
maintain()
void Fs::Ufs::UFSSwapDir::maintain () override virtual
Implements Store::Storage.
Definition at line 414 of file UFSSwapDir.cc.
References Config, DBG_IMPORTANT, debugs, RemovalPurgeWalker::Done, double, SquidConfig::highWaterMark, int, RemovalPurgeWalker::Next, StoreEntry::release(), squid_curtime, Store::Controller::store_dirs_rebuilding, and SquidConfig::Swap.
mapBitAllocate()
int Fs::Ufs::UFSSwapDir::mapBitAllocate ()
Definition at line 585 of file UFSSwapDir.cc.
mapBitReset()
void Fs::Ufs::UFSSwapDir::mapBitReset (sfileno filn)
Definition at line 570 of file UFSSwapDir.cc.
mapBitSet()
void Fs::Ufs::UFSSwapDir::mapBitSet (sfileno filn)
Definition at line 564 of file UFSSwapDir.cc.
mapBitTest()
int Fs::Ufs::UFSSwapDir::mapBitTest (sfileno filn)
Definition at line 558 of file UFSSwapDir.cc.
Referenced by DirClean().
maxObjectSize() [1/2]
int64_t Store::Disk::maxObjectSize () const override virtual inherited
Implements Store::Storage.
Definition at line 103 of file Disk.cc.
References Config, SquidConfig::maxObjectSize, min(), and SquidConfig::Store.
Referenced by Fs::Ufs::UFSStoreState::write().
maxObjectSize() [2/2]
void Store::Disk::maxObjectSize (int64_t newMax) inherited
configure the maximum object size for this storage area. May be any size up to the total storage area.
Definition at line 115 of file Disk.cc.
References DBG_PARSE_NOTE, and debugs.
maxSize()
uint64_t Store::Disk::maxSize () const inline override virtual inherited
The maximum size the store will support in normal use. Inaccuracy is permitted, but may throw estimates for memory etc out of whack.
Implements Store::Storage.
Reimplemented in TestSwapDir.
Definition at line 48 of file Disk.h.
References Store::Disk::max_size.
minObjectSize()
int64_t Store::Disk::minObjectSize () const inherited
Definition at line 96 of file Disk.cc.
References Config, SquidConfig::minObjectSize, and SquidConfig::Store.
minSize()
uint64_t Store::Disk::minSize () const override virtual inherited
Implements Store::Storage.
Definition at line 89 of file Disk.cc.
References Config, SquidConfig::lowWaterMark, and SquidConfig::Swap.
needsDiskStrand()
bool Store::Disk::needsDiskStrand () const virtual inherited
Reimplemented in Rock::SwapDir.
Definition at line 249 of file Disk.cc.
objectSizeIsAcceptable()
bool Store::Disk::objectSizeIsAcceptable (int64_t objSize) const inherited
whether we can store an object of the given size negative objSize means the object size is currently unknown
Definition at line 156 of file Disk.cc.
References assert.
openLog()
void Fs::Ufs::UFSSwapDir::openLog () override virtual
Reimplemented from Store::Disk.
Definition at line 728 of file UFSSwapDir.cc.
References assert, SBuf::c_str(), SquidConfig::cacheSwap, Config, DBG_IMPORTANT, debugs, fatal(), file_open(), IamWorkerProcess(), Store::DiskConfig::n_configured, O_BINARY, and xstrerr().
openStoreIO()
StoreIOState::Pointer Fs::Ufs::UFSSwapDir::openStoreIO (StoreEntry & e, StoreIOState::STIOCB * aCallback, void * callback_data) override virtual
Implements Store::Disk.
Definition at line 552 of file UFSSwapDir.cc.
openTmpSwapLog()
FILE * Fs::Ufs::UFSSwapDir::openTmpSwapLog (int * clean_flag, int * zero_flag)
Definition at line 858 of file UFSSwapDir.cc.
References MemBuf::append(), MemBuf::appended(), assert, SBuf::c_str(), MemBuf::content(), MemBuf::contentSize(), DBG_CRITICAL, DBG_IMPORTANT, debugs, fatalf(), file_close(), file_open(), file_write(), MemBuf::freeFunc(), StoreSwapLogHeader::gapSize(), MemBuf::init(), O_BINARY, StoreSwapLogHeader::record_size, safeunlink(), MemBuf::space(), SQUIDSBUFPH, SQUIDSBUFPRINT, and xstrerr().
optionIODump()
void Fs::Ufs::UFSSwapDir::optionIODump (StoreEntry * e) const private
Definition at line 244 of file UFSSwapDir.cc.
References storeAppendPrintf().
Referenced by getOptionTree().
optionIOParse()
bool Fs::Ufs::UFSSwapDir::optionIOParse (char const * option, const char * value, int reconfiguring) private
Definition at line 217 of file UFSSwapDir.cc.
References self_destruct().
Referenced by getOptionTree().
optionObjectSizeDump()
void Store::Disk::optionObjectSizeDump (StoreEntry * e) const private inherited
Definition at line 382 of file Disk.cc.
References PRId64, and storeAppendPrintf().
Referenced by Store::Disk::getOptionTree().
optionObjectSizeParse()
bool Store::Disk::optionObjectSizeParse (char const * option, const char * value, int reconfiguring) private inherited
Definition at line 347 of file Disk.cc.
References DBG_IMPORTANT, debugs, self_destruct(), size, and strtoll().
Referenced by Store::Disk::getOptionTree().
optionReadOnlyDump()
void Store::Disk::optionReadOnlyDump (StoreEntry * e) const private inherited
Definition at line 340 of file Disk.cc.
References storeAppendPrintf().
Referenced by Store::Disk::getOptionTree().
optionReadOnlyParse()
bool Store::Disk::optionReadOnlyParse (char const * option, const char * value, int reconfiguring) private inherited
Definition at line 318 of file Disk.cc.
References DBG_PARSE_NOTE, debugs, and xatoi().
Referenced by Store::Disk::getOptionTree().
parse()
void Fs::Ufs::UFSSwapDir::parse (int index, char * path) override virtual
Implements Store::Disk.
Definition at line 180 of file UFSSwapDir.cc.
References Config, createRemovalPolicy(), SquidConfig::replPolicy, and xstrdup.
Referenced by TestUfs::testUfsDefaultEngine(), and TestUfs::testUfsSearch().
parseOptions()
void Store::Disk::parseOptions (int reconfiguring) protected inherited
Definition at line 267 of file Disk.cc.
References DBG_IMPORTANT, debugs, ConfigParser::NextToken(), ConfigOption::parse(), and self_destruct().
parseSizeL1L2()
void Fs::Ufs::UFSSwapDir::parseSizeL1L2 () private
Definition at line 143 of file UFSSwapDir.cc.
References DBG_IMPORTANT, debugs, fatal(), GetInteger(), reconfiguring, and size.
pathIsDirectory()
bool Fs::Ufs::UFSSwapDir::pathIsDirectory (const char * path) const private
Definition at line 629 of file UFSSwapDir.cc.
References DBG_CRITICAL, debugs, and xstrerr().
rebuild()
void Fs::Ufs::UFSSwapDir::rebuild () private
Definition at line 825 of file UFSSwapDir.cc.
References eventAdd(), and Fs::Ufs::RebuildState::RebuildStep.
reconfigure()
void Fs::Ufs::UFSSwapDir::reconfigure () override virtual
Implements Store::Disk.
Definition at line 173 of file UFSSwapDir.cc.
reference()
void Fs::Ufs::UFSSwapDir::reference (StoreEntry & e) override virtual
Implements Store::Controlled.
Definition at line 524 of file UFSSwapDir.cc.
References debugs, StoreEntry::repl, StoreEntry::swap_dirn, and StoreEntry::swap_filen.
replacementAdd()
void Fs::Ufs::UFSSwapDir::replacementAdd (StoreEntry * e)
Add and remove the given StoreEntry from the replacement policy in use
Definition at line 1207 of file UFSSwapDir.cc.
References debugs, and StoreEntry::repl.
replacementRemove()
void Fs::Ufs::UFSSwapDir::replacementRemove (StoreEntry * e)
Definition at line 1214 of file UFSSwapDir.cc.
References assert, debugs, RefCount< C >::getRaw(), StoreEntry::hasDisk(), INDEXSD, StoreEntry::repl, and StoreEntry::swap_dirn.
sizeInBlocks()
int64_t Store::Disk::sizeInBlocks (const int64_t size) const inline protected inherited
Definition at line 87 of file Disk.h.
References Store::Disk::fs, and size.
smpAware()
bool Fs::Ufs::UFSSwapDir::smpAware () const inline override virtual
Implements Store::Disk.
Definition at line 75 of file UFSSwapDir.h.
stat()
void Store::Disk::stat (StoreEntry & e) const override virtual inherited
Output stats to the provided store entry. TODO: make these calls asynchronous
Implements Store::Storage.
Reimplemented in TestSwapDir.
Definition at line 63 of file Disk.cc.
References storeAppendPrintf().
statfs()
void Fs::Ufs::UFSSwapDir::statfs (StoreEntry & sentry) const override virtual
Reimplemented from Store::Disk.
Definition at line 371 of file UFSSwapDir.cc.
References Math::doublePercent(), fsStats(), Math::intPercent(), PRIu64, and storeAppendPrintf().
swapSubDir()
char * Fs::Ufs::UFSSwapDir::swapSubDir (int subdirn) const
Definition at line 595 of file UFSSwapDir.cc.
References assert, LOCAL_ARRAY, and MAXPATHLEN.
sync()
void Fs::Ufs::UFSSwapDir::sync (void) override virtual
Reimplemented from Store::Storage.
Definition at line 1262 of file UFSSwapDir.cc.
type()
char const * Store::Disk::type () const inherited
Definition at line 230 of file Disk.cc.
unlinkdUseful()
bool Fs::Ufs::UFSSwapDir::unlinkdUseful () const override virtual
Implements Store::Disk.
Definition at line 1171 of file UFSSwapDir.cc.
References IamWorkerProcess().
unlinkFile()
void Fs::Ufs::UFSSwapDir::unlinkFile (sfileno f)
Definition at line 1162 of file UFSSwapDir.cc.
References asHex(), and debugs.
Referenced by evictCached().
updateAnchored()
virtual bool Store::Controlled::updateAnchored (StoreEntry &) inline virtual inherited
Update a local Transients entry with fresh info from this cache (if any). Return true iff the cache supports Transients entries and the given local Transients entry is now in sync with this storage.
Reimplemented in Rock::SwapDir, MemStore, and Store::Disks.
Definition at line 44 of file Controlled.h.
Referenced by Store::Disks::updateAnchored().
updateHeaders()
virtual void Store::Controlled::updateHeaders (StoreEntry *) inline virtual inherited
Reimplemented in Store::Disks, Rock::SwapDir, and MemStore.
Definition at line 35 of file Controlled.h.
Referenced by Store::Disks::updateHeaders().
validFileno()
int Fs::Ufs::UFSSwapDir::validFileno (sfileno filn, int flag) const
Definition at line 1145 of file UFSSwapDir.cc.
Referenced by DirClean().
validL1()
bool Fs::Ufs::UFSSwapDir::validL1 (int anInt) const
Definition at line 776 of file UFSSwapDir.cc.
validL2()
bool Fs::Ufs::UFSSwapDir::validL2 (int anInt) const
Definition at line 782 of file UFSSwapDir.cc.
verifyCacheDirs()
bool Fs::Ufs::UFSSwapDir::verifyCacheDirs () private
Verify that the the CacheDir exists
If this returns < 0, then Squid exits, complains about swap directories not existing, and instructs the admin to run 'squid -z' Called by UFSSwapDir::init
Definition at line 649 of file UFSSwapDir.cc.
writeCleanDone()
void Fs::Ufs::UFSSwapDir::writeCleanDone () override virtual
Reimplemented from Store::Disk.
Definition at line 976 of file UFSSwapDir.cc.
References SBuf::c_str(), UFSCleanLog::cln, UFSCleanLog::cur, DBG_CRITICAL, debugs, RemovalPolicyWalker::Done, UFSCleanLog::fd, FD_WRITE_METHOD(), file_close(), file_open(), FileRename(), MYNAME, UFSCleanLog::newLog, O_BINARY, UFSCleanLog::outbuf, UFSCleanLog::outbuf_offset, safe_free, Store::Controller::store_dirs_rebuilding, UFSCleanLog::walker, and xstrerr().
writeCleanStart()
int Fs::Ufs::UFSSwapDir::writeCleanStart () override virtual
Reimplemented from Store::Disk.
Definition at line 932 of file UFSSwapDir.cc.
References SBuf::append(), SBuf::c_str(), CLEAN_BUF_SZ, UFSCleanLog::cln, UFSCleanLog::cur, debugs, UFSCleanLog::fd, file_open(), StoreSwapLogHeader::gapSize(), UFSCleanLog::newLog, O_BINARY, UFSCleanLog::outbuf, UFSCleanLog::outbuf_offset, StoreSwapLogHeader::record_size, UFSCleanLog::walker, and xcalloc().
Member Data Documentation
blksize
int Store::Disk::blksize inherited
Definition at line 146 of file Disk.h.
CleanEvent
void Fs::Ufs::UFSSwapDir::CleanEvent static private
Definition at line 130 of file UFSSwapDir.h.
cleanLog
CleanLog* Store::Disk::cleanLog inherited
Definition at line 140 of file Disk.h.
Referenced by UFSCleanLog::write().
cur_size
uint64_t Fs::Ufs::UFSSwapDir::cur_size private
Definition at line 149 of file UFSSwapDir.h.
Referenced by currentSize().
currentIOOptions
ConfigOptionVector* Fs::Ufs::UFSSwapDir::currentIOOptions mutable private
Definition at line 147 of file UFSSwapDir.h.
disker
int Store::Disk::disker inherited
Definition at line 104 of file Disk.h.
flags
struct Store::Disk::Flags Store::Disk::flags inherited
Referenced by storeDirSelectSwapDirLeastLoad().
[struct]
struct { ... } Store::Disk::fs
Referenced by Store::Disk::Disk(), and Store::Disk::sizeInBlocks().
fsdata
void* Fs::Ufs::UFSSwapDir::fsdata
Definition at line 109 of file UFSSwapDir.h.
index
int Store::Disk::index inherited
Definition at line 103 of file Disk.h.
Referenced by Fs::Ufs::UFSStoreState::UFSStoreState(), and Rock::Rebuild::Start().
IO
Fs::Ufs::UFSStrategy* Fs::Ufs::UFSSwapDir::IO
Definition at line 83 of file UFSSwapDir.h.
Referenced by UFSSwapDir(), canStore(), TestUfs::testUfsDefaultEngine(), and TestUfs::testUfsSearch().
ioType
char const* Fs::Ufs::UFSSwapDir::ioType private
Definition at line 148 of file UFSSwapDir.h.
l1
int Fs::Ufs::UFSSwapDir::l1 protected
Definition at line 121 of file UFSSwapDir.h.
Referenced by DirClean(), FilenoBelongsHere(), and HandleCleanEvent().
l2
int Fs::Ufs::UFSSwapDir::l2 protected
Definition at line 122 of file UFSSwapDir.h.
Referenced by DirClean(), FilenoBelongsHere(), and HandleCleanEvent().
map
FileMap* Fs::Ufs::UFSSwapDir::map protected
Definition at line 119 of file UFSSwapDir.h.
max_objsize
int64_t Store::Disk::max_objsize protected inherited
Definition at line 99 of file Disk.h.
max_size
uint64_t Store::Disk::max_size protected inherited
Definition at line 97 of file Disk.h.
Referenced by Store::Disk::maxSize().
min_objsize
int64_t Store::Disk::min_objsize protected inherited
Definition at line 98 of file Disk.h.
n_disk_objects
uint64_t Fs::Ufs::UFSSwapDir::n_disk_objects private
Definition at line 150 of file UFSSwapDir.h.
Referenced by currentCount().
NumberOfUFSDirs
size_t Fs::Ufs::UFSSwapDir::NumberOfUFSDirs = 0 static private
Definition at line 126 of file UFSSwapDir.h.
path
char* Store::Disk::path inherited
Definition at line 102 of file Disk.h.
Referenced by DirClean(), Rock::Rebuild::Stats::Init(), and Rock::Rebuild::Start().
rebuilding_
bool Fs::Ufs::UFSSwapDir::rebuilding_ private
Definition at line 151 of file UFSSwapDir.h.
removals
int Store::Disk::removals inherited
Definition at line 106 of file Disk.h.
repl
RemovalPolicy* Store::Disk::repl inherited
Definition at line 105 of file Disk.h.
scanned
int Store::Disk::scanned inherited
Definition at line 107 of file Disk.h.
suggest
int Fs::Ufs::UFSSwapDir::suggest protected
Definition at line 120 of file UFSSwapDir.h.
swaplog_fd
int Fs::Ufs::UFSSwapDir::swaplog_fd private
Definition at line 129 of file UFSSwapDir.h.
theType
char const* Store::Disk::theType private inherited
Definition at line 94 of file Disk.h.
UFSDirToGlobalDirMapping
int * Fs::Ufs::UFSSwapDir::UFSDirToGlobalDirMapping = nullptr static private
Definition at line 127 of file UFSSwapDir.h.
The documentation for this class was generated from the following files:
squid/src/fs/ufs/UFSSwapDir.h
squid/src/fs/ufs/UFSSwapDir.cc