Squid Web Cache: Rock::LoadingSlot Class Reference
Rock::LoadingSlot Class Reference
smart db slot-level info pointer (hides anti-padding LoadingParts arrays)
Public Member Functions
LoadingSlot (const SlotId slotId, LoadingParts &source)
bool mapped () const
void mapped (const bool beMapped)
bool finalized () const
void finalized (const bool beFinalized)
bool freed () const
void freed (const bool beFreed)
bool used () const
Public Attributes
Ipc::StoreMapSliceId & more
another slot in some chain belonging to the same entry (unordered!)
Private Attributes
LoadingFlags & flags
slot flags (see the above accessors) are ours
Detailed Description
Definition at line 135 of file RockRebuild.cc.
Constructor & Destructor Documentation
LoadingSlot()
Rock::LoadingSlot::LoadingSlot (const SlotId slotId, LoadingParts & source)
Definition at line 209 of file RockRebuild.cc.
Member Function Documentation
finalized() [1/2]
bool Rock::LoadingSlot::finalized () const inline
Definition at line 148 of file RockRebuild.cc.
References Rock::LoadingFlags::finalized, and flags.
Referenced by Rock::Rebuild::finalizeOrThrow(), and Rock::Rebuild::validateOneSlot().
finalized() [2/2]
void Rock::LoadingSlot::finalized (const bool beFinalized) inline
Definition at line 149 of file RockRebuild.cc.
References Rock::LoadingFlags::finalized, and flags.
freed() [1/2]
bool Rock::LoadingSlot::freed () const inline
Definition at line 152 of file RockRebuild.cc.
References flags, and Rock::LoadingFlags::freed.
Referenced by Rock::Rebuild::finalizeOrThrow(), Rock::Rebuild::freeSlot(), Rock::Rebuild::mapSlot(), used(), and Rock::Rebuild::validateOneSlot().
freed() [2/2]
void Rock::LoadingSlot::freed (const bool beFreed) inline
Definition at line 153 of file RockRebuild.cc.
References flags, and Rock::LoadingFlags::freed.
mapped() [1/2]
bool Rock::LoadingSlot::mapped () const inline
Definition at line 144 of file RockRebuild.cc.
References flags, and Rock::LoadingFlags::mapped.
Referenced by Rock::Rebuild::finalizeOrThrow(), Rock::Rebuild::freeUnusedSlot(), Rock::Rebuild::mapSlot(), used(), and Rock::Rebuild::validateOneSlot().
mapped() [2/2]
void Rock::LoadingSlot::mapped (const bool beMapped) inline
Definition at line 145 of file RockRebuild.cc.
References flags, and Rock::LoadingFlags::mapped.
used()
bool Rock::LoadingSlot::used () const inline
Definition at line 155 of file RockRebuild.cc.
References freed(), mapped(), and more.
Member Data Documentation
flags
LoadingFlags& Rock::LoadingSlot::flags private
Definition at line 158 of file RockRebuild.cc.
Referenced by finalized(), finalized(), freed(), freed(), mapped(), and mapped().
more
Ipc::StoreMapSliceId& Rock::LoadingSlot::more
Definition at line 141 of file RockRebuild.cc.
Referenced by Rock::Rebuild::addSlotToEntry(), Rock::Rebuild::chainSlots(), and used().
The documentation for this class was generated from the following file:
squid/src/fs/rock/RockRebuild.cc