Squid Web Cache: DelaySpec Class Reference
DelaySpec Class Reference
#include <DelaySpec.h>
Public Member Functions
DelaySpec ()
void stats (StoreEntry *sentry, char const *) const
void dump (StoreEntry *) const
void parse ()
Public Attributes
int restore_bps
int64_t max_bytes
Detailed Description
Definition at line 15 of file DelaySpec.h.
Constructor & Destructor Documentation
DelaySpec()
DelaySpec::DelaySpec ()
Definition at line 19 of file DelaySpec.cc.
Member Function Documentation
dump()
void DelaySpec::dump (StoreEntry * entry) const
Definition at line 36 of file DelaySpec.cc.
References max_bytes, PRId64, restore_bps, and storeAppendPrintf().
Referenced by Aggregate::dump(), VectorPool::dump(), ClassCHostPool::dump(), DelayTagged::dump(), and DelayUser::dump().
parse()
void DelaySpec::parse ()
Definition at line 42 of file DelaySpec.cc.
References DBG_CRITICAL, debugs, max_bytes, ConfigParser::NextToken(), restore_bps, self_destruct(), StringToInt(), and StringToInt64().
Referenced by Aggregate::parse(), VectorPool::parse(), ClassCHostPool::parse(), DelayTagged::parse(), and DelayUser::parse().
stats()
void DelaySpec::stats (StoreEntry * sentry, char const * label) const
Definition at line 23 of file DelaySpec.cc.
References max_bytes, PRId64, restore_bps, and storeAppendPrintf().
Referenced by Aggregate::stats(), VectorPool::stats(), ClassCHostPool::stats(), DelayTagged::stats(), and DelayUser::stats().
Member Data Documentation
max_bytes
int64_t DelaySpec::max_bytes
Definition at line 24 of file DelaySpec.h.
Referenced by dump(), DelayBucket::init(), parse(), MessageDelayPool::refillBucket(), stats(), and DelayBucket::update().
restore_bps
int DelaySpec::restore_bps
Definition at line 23 of file DelaySpec.h.
Referenced by dump(), parse(), MessageDelayPool::refillBucket(), DelayTagged::stats(), DelayUser::stats(), stats(), ClassCBucket::update(), and DelayBucket::update().
The documentation for this class was generated from the following files:
squid/src/DelaySpec.h
squid/src/DelaySpec.cc