Squid Web Cache: DebugMessage Class Reference
DebugMessage Class Reference
manages configurable aspects of a debugs() message
#include <Messages.h>
Public Member Functions
bool configured () const
whether the logging of this message has been customized
bool levelled () const
whether the default logging level of this message has been altered
bool limited () const
whether the number of logging attempts have been limited
int currentLevel (const int defaultLevel) const
Public Attributes
DebugMessageId id = 0
message identifier or, if the message has not been configured, zero
int level = -1
debugging level (i.e., the second debugs() parameter) or -1
uint64_t limit = std::numeric_limits<uint64_t>::max()
logging attempts beyond this limit are logged at the DBG_DATA level
Private Attributes
uint64_t count_ = 0
the total number of attempts to log this message if it was configured()
Detailed Description
Definition at line 25 of file Messages.h.
Member Function Documentation
configured()
bool DebugMessage::configured () const inline
Definition at line 29 of file Messages.h.
Referenced by currentLevel().
currentLevel()
int DebugMessage::currentLevel (const int defaultLevel) const inline
Returns
appropriate debugging level for the message
Definition at line 38 of file Messages.h.
References configured(), count_, DBG_IMPORTANT, level, and limit.
levelled()
bool DebugMessage::levelled () const inline
Definition at line 32 of file Messages.h.
References level.
Referenced by parse_cache_log_message().
limited()
bool DebugMessage::limited () const inline
Definition at line 35 of file Messages.h.
References limit, and max().
Referenced by parse_cache_log_message().
Member Data Documentation
count_
uint64_t DebugMessage::count_ = 0 mutable private
Definition at line 60 of file Messages.h.
Referenced by currentLevel().
id
DebugMessageId DebugMessage::id = 0
Definition at line 48 of file Messages.h.
Referenced by parse_cache_log_message().
level
int DebugMessage::level = -1
Definition at line 53 of file Messages.h.
Referenced by currentLevel(), levelled(), and parse_cache_log_message().
limit
uint64_t DebugMessage::limit = std::numeric_limits<uint64_t>::max()
Definition at line 56 of file Messages.h.
Referenced by currentLevel(), limited(), and parse_cache_log_message().
The documentation for this class was generated from the following file:
squid/src/debug/Messages.h