Squid Web Cache: store_client Class Reference
store_client Class Reference
#include <StoreClient.h>
Classes
struct Callback
Public Member Functions
CBDATA_DECL_ (store_client, noexcept)
store_client (StoreEntry *)
~store_client ()
auto discardableHttpEnd () const
the client will not use HTTP response bytes with lower offsets (if any)
int getType () const
void noteSwapInDone (bool error)
void doCopy (StoreEntry *e)
void readHeader (const char *buf, ssize_t len)
void readBody (const char *buf, ssize_t len)
void copy (StoreEntry *, StoreIOBuffer, STCB *, void *)
void dumpStats (MemBuf *output, int clientNumber) const
bool atEof () const
int bytesWanted () const
void setDelayId (DelayId delay_id)
Public Attributes
StoreEntry * entry
StoreIOState::Pointer swapin_sio
struct {
bool disk_io_pending
bool store_copying
} flags
DelayId delayId
dlink_node node
struct store_client::Callback _callback
Private Member Functions
bool moreToRead () const
Whether Store has (or possibly will have) more entry data for us.
bool canReadFromMemory () const
whether at least one byte wanted by the client is in memory
bool answeredOnce () const
bool sendingHttpHeaders () const
int64_t nextHttpReadOffset () const
The offset of the next stored HTTP response byte wanted by the client.
void fileRead ()
void scheduleDiskRead ()
void readFromMemory ()
void scheduleRead ()
bool startSwapin ()
opens the swapin "file" if possible; otherwise, fail()s and returns false
void handleBodyFromDisk ()
de-serializes HTTP response (partially) read from disk storage
void maybeWriteFromDiskToMemory (const StoreIOBuffer &)
bool parseHttpHeadersFromDisk ()
bool tryParsingHttpHeaders ()
void skipHttpHeadersFromDisk ()
skips HTTP header bytes previously loaded from disk
void fail ()
void callback (ssize_t)
void noteCopiedBytes (size_t)
void noteNews ()
if necessary and possible, informs the Store reader about copy() result
void finishCallback ()
finishes a copy()-STCB sequence by synchronously calling STCB
Static Private Member Functions
static void FinishCallback (store_client *)
finishCallback() wrapper; TODO: Add NullaryMemFunT for non-jobs.
Private Attributes
int type
bool object_ok
bool atEof_
StoreIOBuffer copyInto
int64_t discardableHttpEnd_ = 0
the client will not use HTTP response bytes with lower offsets (if any)
uint64_t answers
the total number of finishCallback() calls
std::optional< Store::ParsingBuffer > parsingBuffer
StoreIOBuffer lastDiskRead
buffer used for the last storeRead() call
Detailed Description
Definition at line 73 of file StoreClient.h.
Constructor & Destructor Documentation
store_client()
store_client::store_client (StoreEntry * e) explicit
Definition at line 192 of file store_client.cc.
References assert, Assure, entry, flags, getType(), StoreEntry::hasDisk(), StoreEntry::lock(), StoreEntry::refcount, STORE_DISK_CLIENT, and StoreEntry::swapoutFailed().
~store_client()
store_client::~store_client ()
Definition at line 216 of file store_client.cc.
References assert, entry, and StoreEntry::unlock().
Member Function Documentation
answeredOnce()
bool store_client::answeredOnce () const inline private
Definition at line 144 of file StoreClient.h.
References answers.
Referenced by copy(), handleBodyFromDisk(), readBody(), and sendingHttpHeaders().
atEof()
bool store_client::atEof () const inline
Whether the last successful storeClientCopy() answer was known to contain the last body bytes of the HTTP response
Return values
true requesting bytes at higher offsets is futile
See also
STCB
Definition at line 106 of file StoreClient.h.
References atEof_.
Referenced by netdbExchangeHandleReply(), peerDigestHandleReply(), and urnHandleReply().
bytesWanted()
int store_client::bytesWanted () const
The maximum number of bytes the Store client can read/copy next without overflowing its buffer and without violating delay pool limits. Store I/O is not rate-limited, but we assume that the same number of bytes may be read from the Squid-to-server connection that may be rate-limited.
Definition at line 1092 of file store_client.cc.
References DelayId::bytesWanted(), copyInto, delayId, and StoreIOBuffer::length.
Referenced by MemObject::mostBytesAllowed().
callback()
void store_client::callback (ssize_t) private
canReadFromMemory()
bool store_client::canReadFromMemory () const private
Definition at line 497 of file store_client.cc.
References MemObject::endOffset(), entry, MemObject::inmem_lo, StoreEntry::mem(), nextHttpReadOffset(), and parsingBuffer.
Referenced by doCopy(), and moreToRead().
CBDATA_DECL_()
store_client::CBDATA_DECL_ (store_client , noexcept)
copy()
void store_client::copy (StoreEntry * anEntry, StoreIOBuffer copyRequest, STCB * callback_fn, void * data)
Request StoreIOBuffer-described response data via an asynchronous STCB callback. At most one outstanding request is allowed per store_client.
Definition at line 235 of file store_client.cc.
References _callback, answeredOnce(), assert, Assure, copyInto, StoreIOBuffer::data, debugs, discardableHttpEnd_, EBIT_TEST, entry, ENTRY_ABORTED, StoreEntry::flags, StoreEntry::getMD5Text(), StoreEntry::kickProducer(), MemObject::kickReads(), StoreIOBuffer::length, StoreEntry::lock(), StoreEntry::mem_obj, nextHttpReadOffset(), StoreIOBuffer::offset, parsingBuffer, store_client::Callback::pending(), storeClientCopy2(), and StoreEntry::unlock().
Referenced by storeClientCopy().
discardableHttpEnd()
auto store_client::discardableHttpEnd () const inline
Definition at line 82 of file StoreClient.h.
References discardableHttpEnd_.
Referenced by LowestMemReader::operator()().
doCopy()
void store_client::doCopy (StoreEntry * e)
Definition at line 365 of file store_client.cc.
References _callback, answers, assert, Assure, MemObject::baseReply(), canReadFromMemory(), copyInto, debugs, MemObject::endOffset(), entry, flags, getType(), Http::Message::hdr_sz, StoreEntry::mem_obj, moreToRead(), nextHttpReadOffset(), noteNews(), StoreEntry::objectLen(), store_client::Callback::pending(), readFromMemory(), scheduleDiskRead(), sendingHttpHeaders(), startSwapin(), STORE_DISK_CLIENT, STORE_PENDING, StoreEntry::store_status, and swapin_sio.
Referenced by storeClientCopy2().
dumpStats()
void store_client::dumpStats (MemBuf * output, int clientNumber) const
Definition at line 1055 of file store_client.cc.
References _callback, MemBuf::append(), Packable::appendf(), copyInto, flags, StoreIOBuffer::length, store_client::Callback::notifier, StoreIOBuffer::offset, store_client::Callback::pending(), and PRId64.
Referenced by StoreClientStats::operator()().
fail()
void store_client::fail () private
Definition at line 674 of file store_client.cc.
References debugs, noteNews(), and object_ok.
Referenced by noteSwapInDone(), parseHttpHeadersFromDisk(), readBody(), readHeader(), and startSwapin().
fileRead()
void store_client::fileRead () private
Definition at line 537 of file store_client.cc.
References _callback, assert, Assure, copyInto, StoreIOBuffer::data, debugs, entry, flags, lastDiskRead, StoreIOBuffer::length, StoreEntry::mem_obj, nextHttpReadOffset(), StoreIOBuffer::offset, StoreIOState::offset(), parsingBuffer, store_client::Callback::pending(), StoreIOBuffer::positionAt(), MemObject::SwapOut::sio, SM_PAGE_SIZE, storeClientReadBody, storeClientReadHeader, storeRead(), MemObject::swap_hdr_sz, swapin_sio, MemObject::swapout, and StoreEntry::swappingOut().
Referenced by scheduleDiskRead().
finishCallback()
void store_client::finishCallback () private
Definition at line 154 of file store_client.cc.
References _callback, answers, Assure, atEof_, MemObject::baseReply(), store_client::Callback::callback_handler, store_client::Callback::cbData, copyInto, StoreIOBuffer::data, debugs, discardableHttpEnd_, MemObject::endOffset(), entry, Http::Message::hdr_sz, StoreIOBuffer::length, StoreEntry::mem(), store_client::Callback::notifier, object_ok, StoreIOBuffer::offset, parsingBuffer, sendingHttpHeaders(), and CallbackData::validDone().
Referenced by FinishCallback().
FinishCallback()
void store_client::FinishCallback (store_client * sc) static private
Definition at line 147 of file store_client.cc.
References finishCallback().
Referenced by noteNews().
getType()
int store_client::getType () const
Definition at line 91 of file store_client.cc.
References type.
Referenced by store_client(), doCopy(), LowestMemReader::operator()(), and scheduleDiskRead().
handleBodyFromDisk()
void store_client::handleBodyFromDisk () private
Definition at line 627 of file store_client.cc.
References answeredOnce(), Assure, entry, StoreEntry::hasParsedReplyHeader(), StoreEntry::mem_obj, noteNews(), parseHttpHeadersFromDisk(), skipHttpHeadersFromDisk(), and MemObject::swap_hdr_sz.
Referenced by readBody(), and readHeader().
maybeWriteFromDiskToMemory()
void store_client::maybeWriteFromDiskToMemory (const StoreIOBuffer & httpResponsePart) private
Adds HTTP response data loaded from disk to the memory cache (if needed/possible). The given part may contain portions of HTTP response headers and/or HTTP response body.
Definition at line 650 of file store_client.cc.
References Config, MemObject::endOffset(), entry, MemObject::inmem_lo, StoreIOBuffer::length, SquidConfig::maxInMemObjSize, StoreEntry::mem_obj, SquidConfig::memory_cache_disk, StoreEntry::objectLen(), StoreIOBuffer::offset, SquidConfig::onoff, SquidConfig::Store, storeGetMemSpace(), and MemObject::write().
Referenced by readBody(), and readHeader().
moreToRead()
bool store_client::moreToRead () const private
Definition at line 308 of file store_client.cc.
References canReadFromMemory(), StoreEntry::contentLen(), copyInto, entry, StoreEntry::hasDisk(), StoreIOBuffer::length, StoreEntry::objectLen(), StoreIOBuffer::offset, STORE_PENDING, and StoreEntry::store_status.
Referenced by doCopy().
nextHttpReadOffset()
int64_t store_client::nextHttpReadOffset () const private
Definition at line 508 of file store_client.cc.
References Assure, MemObject::baseReply(), copyInto, entry, Http::Message::hdr_sz, StoreEntry::mem(), StoreIOBuffer::offset, and parsingBuffer.
Referenced by canReadFromMemory(), copy(), doCopy(), fileRead(), and readFromMemory().
noteCopiedBytes()
void store_client::noteCopiedBytes (size_t) private
noteNews()
void store_client::noteNews () private
Definition at line 687 of file store_client.cc.
References _callback, Assure, asyncCall(), store_client::Callback::callback_handler, cbdataDialer(), debugs, FinishCallback(), store_client::Callback::notifier, store_client::Callback::pending(), and ScheduleCallHere.
Referenced by doCopy(), fail(), handleBodyFromDisk(), noteSwapInDone(), and readBody().
noteSwapInDone()
void store_client::noteSwapInDone (bool error)
React to the end of reading the response from disk. There will be no more readHeader() and readBody() callbacks for the current storeRead() swapin after this notification.
Definition at line 464 of file store_client.cc.
References _callback, Assure, error(), fail(), noteNews(), and store_client::Callback::pending().
Referenced by storeSwapInFileClosed().
parseHttpHeadersFromDisk()
bool store_client::parseHttpHeadersFromDisk () private
parses HTTP header bytes loaded from disk
Returns
false if fail() or scheduleDiskRead() has been called and, hence, the caller should just quit without any further action
Definition at line 1001 of file store_client.cc.
References CurrentException(), DBG_CRITICAL, debugs, Debug::Extra(), fail(), parsingBuffer, and tryParsingHttpHeaders().
Referenced by handleBodyFromDisk().
readBody()
void store_client::readBody (const char * buf, ssize_t len)
Definition at line 586 of file store_client.cc.
References _callback, answeredOnce(), assert, Assure, StoreIOBuffer::data, DBG_CRITICAL, debugs, entry, fail(), flags, handleBodyFromDisk(), lastDiskRead, StoreIOBuffer::length, Less(), maybeWriteFromDiskToMemory(), StoreEntry::mem(), noteNews(), StoreIOBuffer::offset, parsingBuffer, store_client::Callback::pending(), StoreIOBuffer::positionAt(), and MemObject::swap_hdr_sz.
Referenced by storeClientReadBody().
readFromMemory()
void store_client::readFromMemory () private
Copies at least some of the requested body bytes from MemObject memory, satisfying the copy() request.
Precondition
canReadFromMemory() is true
Definition at line 525 of file store_client.cc.
References Assure, mem_hdr::copy(), MemObject::data_hdr, debugs, entry, StoreEntry::mem_obj, nextHttpReadOffset(), and parsingBuffer.
Referenced by doCopy().
readHeader()
void store_client::readHeader (const char * buf, ssize_t len)
Definition at line 727 of file store_client.cc.
References _callback, assert, Assure, CurrentException(), DBG_IMPORTANT, debugs, entry, fail(), flags, handleBodyFromDisk(), maybeWriteFromDiskToMemory(), StoreEntry::mem_obj, object_ok, parsingBuffer, store_client::Callback::pending(), MemObject::swap_hdr_sz, and Store::UnpackHitSwapMeta().
Referenced by storeClientReadHeader().
scheduleDiskRead()
void store_client::scheduleDiskRead () private
Definition at line 474 of file store_client.cc.
References assert, debugs, entry, fileRead(), flags, getType(), startSwapin(), STORE_DISK_CLIENT, and swapin_sio.
Referenced by doCopy(), and tryParsingHttpHeaders().
scheduleRead()
void store_client::scheduleRead () private
sendingHttpHeaders()
bool store_client::sendingHttpHeaders () const private
Whether our answer, if sent right now, will announce the availability of HTTP response headers (to the STCB callback) for the first time.
Definition at line 359 of file store_client.cc.
References answeredOnce(), MemObject::baseReply(), entry, Http::Message::hdr_sz, and StoreEntry::mem().
Referenced by doCopy(), and finishCallback().
setDelayId()
void store_client::setDelayId (DelayId delay_id)
Definition at line 1099 of file store_client.cc.
References delayId.
Referenced by Ssl::ServerBump::ServerBump(), clientReplyContext::createStoreEntry(), clientReplyContext::doGetMoreData(), clientReplyContext::processExpired(), clientReplyContext::sendMoreData(), and clientReplyContext::setReplyToStoreEntry().
skipHttpHeadersFromDisk()
void store_client::skipHttpHeadersFromDisk () private
Definition at line 1039 of file store_client.cc.
References Assure, MemObject::baseReply(), copyInto, debugs, entry, Http::Message::hdr_sz, StoreIOBuffer::length, Less(), StoreEntry::mem_obj, and parsingBuffer.
Referenced by handleBodyFromDisk().
startSwapin()
bool store_client::startSwapin () private
Definition at line 435 of file store_client.cc.
References DBG_IMPORTANT, debugs, fail(), flags, storeSwapInStart(), storeTooManyDiskFilesOpen(), and swapin_sio.
Referenced by doCopy(), and scheduleDiskRead().
tryParsingHttpHeaders()
bool store_client::tryParsingHttpHeaders () private
parseHttpHeadersFromDisk() helper
Definition at line 1021 of file store_client.cc.
References MemObject::adjustableBaseReply(), Assure, copyInto, entry, StoreEntry::mem(), StoreIOBuffer::offset, parsingBuffer, and scheduleDiskRead().
Referenced by parseHttpHeadersFromDisk().
Member Data Documentation
_callback
struct store_client::Callback store_client::_callback
Referenced by copy(), doCopy(), dumpStats(), fileRead(), finishCallback(), StoreEntry::invokeHandlers(), noteNews(), noteSwapInDone(), readBody(), readHeader(), storeClientCopy2(), storeSwapInFileClosed(), and storeUnregister().
answers
uint64_t store_client::answers private
Definition at line 186 of file StoreClient.h.
Referenced by answeredOnce(), doCopy(), and finishCallback().
atEof_
bool store_client::atEof_ private
Whether the last successful storeClientCopy() answer was known to contain the last body bytes of the HTTP response
Return values
true requesting bytes at higher offsets is futile
See also
STCB
Definition at line 171 of file StoreClient.h.
Referenced by atEof(), and finishCallback().
copyInto
StoreIOBuffer store_client::copyInto private
Storage and metadata associated with the current copy() request. Ought to be ignored when not answering a copy() request.
copyInto.offset is the requested HTTP response body offset;
copyInto.data is the client-owned, client-provided result buffer;
copyInto.length is the size of the .data result buffer;
copyInto.flags are unused by this class.
Definition at line 179 of file StoreClient.h.
Referenced by bytesWanted(), copy(), doCopy(), dumpStats(), fileRead(), finishCallback(), moreToRead(), nextHttpReadOffset(), skipHttpHeadersFromDisk(), and tryParsingHttpHeaders().
delayId
DelayId store_client::delayId
Definition at line 128 of file StoreClient.h.
Referenced by bytesWanted(), MemObject::mostBytesAllowed(), setDelayId(), and MemObject::setNoDelay().
discardableHttpEnd_
int64_t store_client::discardableHttpEnd_ = 0 private
Definition at line 183 of file StoreClient.h.
Referenced by copy(), discardableHttpEnd(), and finishCallback().
disk_io_pending
bool store_client::disk_io_pending
whether we are expecting a response to be swapped in from disk (i.e. whether async storeRead() is currently in progress)
Definition at line 120 of file StoreClient.h.
Referenced by StoreEntry::invokeHandlers().
entry
StoreEntry* store_client::entry
Definition at line 113 of file StoreClient.h.
Referenced by store_client(), ~store_client(), canReadFromMemory(), copy(), doCopy(), fileRead(), finishCallback(), handleBodyFromDisk(), maybeWriteFromDiskToMemory(), moreToRead(), nextHttpReadOffset(), readBody(), readFromMemory(), readHeader(), scheduleDiskRead(), sendingHttpHeaders(), skipHttpHeadersFromDisk(), storeSwapInStart(), and tryParsingHttpHeaders().
[struct]
struct { ... } store_client::flags
Referenced by store_client(), doCopy(), dumpStats(), fileRead(), StoreEntry::invokeHandlers(), readBody(), readHeader(), scheduleDiskRead(), startSwapin(), and storeClientCopy2().
lastDiskRead
StoreIOBuffer store_client::lastDiskRead private
Definition at line 194 of file StoreClient.h.
Referenced by fileRead(), and readBody().
node
dlink_node store_client::node
Definition at line 139 of file StoreClient.h.
Referenced by MemObject::addClient(), and storeUnregister().
object_ok
bool store_client::object_ok private
Definition at line 168 of file StoreClient.h.
Referenced by fail(), finishCallback(), and readHeader().
parsingBuffer
std::optional<Store::ParsingBuffer> store_client::parsingBuffer private
Accumulates raw bytes read from Store while answering the current copy() request. Buffer contents depends on the source and parsing stage; it may hold (parts of) swap metadata, HTTP response headers, and/or HTTP response body bytes.
Definition at line 192 of file StoreClient.h.
Referenced by canReadFromMemory(), copy(), fileRead(), finishCallback(), nextHttpReadOffset(), parseHttpHeadersFromDisk(), readBody(), readFromMemory(), readHeader(), skipHttpHeadersFromDisk(), and tryParsingHttpHeaders().
store_copying
bool store_client::store_copying
whether the store_client::doCopy()-initiated STCB sequence is currently in progress
Definition at line 124 of file StoreClient.h.
Referenced by StoreEntry::invokeHandlers(), and storeClientCopy2().
swapin_sio
StoreIOState::Pointer store_client::swapin_sio
Definition at line 114 of file StoreClient.h.
Referenced by doCopy(), fileRead(), scheduleDiskRead(), startSwapin(), storeSwapInFileClosed(), storeSwapInStart(), and storeUnregister().
type
int store_client::type private
Definition at line 167 of file StoreClient.h.
Referenced by getType().
The documentation for this class was generated from the following files:
squid/src/StoreClient.h
squid/src/store_client.cc