Squid Web Cache: Client Class Reference
Client Class Reference abstract
#include <Client.h>
Public Types
typedef CbcPointer< AsyncJob > Pointer
typedef CbcPointer< BodyProducer > Pointer
typedef CbcPointer< BodyConsumer > Pointer
Public Member Functions
Client (FwdState *)
~Client () override
virtual const Comm::ConnectionPointer & dataConnection () const =0
void noteMoreBodyDataAvailable (BodyPipe::Pointer) override
void noteBodyProductionEnded (BodyPipe::Pointer) override
void noteBodyProducerAborted (BodyPipe::Pointer) override
virtual void maybeReadVirginBody ()=0
read response data from the network
virtual void abortAll (const char *reason)=0
abnormal transaction termination; reason is for debugging only
virtual bool abortOnData (const char *reason)
virtual HttpRequestPointer originalRequest ()
a hack to reach HttpStateData::orignal_request
void noteAdaptationAnswer (const Adaptation::Answer &answer) override
void noteAdaptationAclCheckDone (Adaptation::ServiceGroupPointer group) override
void noteMoreBodySpaceAvailable (BodyPipe::Pointer) override
void noteBodyConsumerAborted (BodyPipe::Pointer) override
virtual bool getMoreRequestBody (MemBuf &buf)
either fill buf with available [encoded] request body bytes or return false
virtual void processReplyBody ()=0
void swanSong () override
bool doneAll () const override
whether positive goal has been reached
void serverComplete ()
void markParsedVirginReplyAsWhole (const char *reasonWeAreSure)
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
virtual void callException (const std::exception &e)
called when the job throws during an async call
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
StoreEntry * entry = nullptr
FwdState::Pointer fwd
HttpRequestPointer request
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
virtual void haveParsedReplyHeaders ()
called when we have final (possibly adapted) reply headers; kids extend
virtual void completeForwarding ()
bool startRequestBodyFlow ()
void handleMoreRequestBodyAvailable ()
void handleRequestBodyProductionEnded ()
virtual void handleRequestBodyProducerAborted ()=0
void sendMoreRequestBody ()
virtual void sentRequestBody (const CommIoCbParams &io)=0
virtual void doneSendingRequestBody ()=0
virtual void closeServer ()=0
virtual bool doneWithServer () const =0
virtual bool mayReadVirginReplyBody () const =0
whether we may receive more virgin response body bytes
virtual void noteDelayAwareReadChance ()=0
bool abortOnBadEntry (const char *abortReason)
Entry-dependent callbacks use this check to quit if the entry went bad.
bool blockCaching ()
whether to prevent caching of an otherwise cachable response
void startAdaptation (const Adaptation::ServiceGroupPointer &group, HttpRequest *cause)
Initiate an asynchronous adaptation transaction which will call us back.
void adaptVirginReplyBody (const char *buf, ssize_t len)
void cleanAdaptation ()
virtual bool doneWithAdaptation () const
void handleMoreAdaptedBodyAvailable ()
void handleAdaptedBodyProductionEnded ()
void handleAdaptedBodyProducerAborted ()
void handleAdaptedHeader (Http::Message *msg)
void handleAdaptationCompleted ()
void handleAdaptationBlocked (const Adaptation::Answer &answer)
void handleAdaptationAborted (bool bypassable=false)
bool handledEarlyAdaptationAbort ()
void resumeBodyStorage ()
called by StoreEntry when it has more buffer space available
void checkAdaptationWithBodyCompletion ()
const HttpReply * virginReply () const
HttpReply * virginReply ()
HttpReply * setVirginReply (HttpReply *r)
HttpReply * finalReply ()
HttpReply * setFinalReply (HttpReply *r)
void adaptOrFinalizeReply ()
void addVirginReplyBody (const char *buf, ssize_t len)
void storeReplyBody (const char *buf, ssize_t len)
size_t calcBufferSpaceToReserve (const size_t space, const size_t wantSpace) const
determine how much space the buffer needs to reserve
void adjustBodyBytesRead (const int64_t delta)
initializes bodyBytesRead stats if needed and applies delta
void delayRead ()
CbcPointer< Initiate > initiateAdaptation (Initiate *x)
< starts freshly created initiate and returns a safe pointer to it
void clearAdaptation (CbcPointer< Initiate > &x)
clears the pointer (does not call announceInitiatorAbort)
void announceInitiatorAbort (CbcPointer< Initiate > &x)
inform the transaction about abnormal termination and clear the pointer
bool initiated (const CbcPointer< AsyncJob > &job) const
Must(initiated(initiate)) instead of Must(initiate.set()), for clarity.
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual void start ()
called by AsyncStart; do not call directly
virtual const char * status () const
internal cleanup; do not call directly
void stopProducingFor (RefCount< BodyPipe > &, bool atEof)
void stopConsumingFrom (RefCount< BodyPipe > &)
Static Protected Member Functions
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
int64_t currentOffset = 0
MemBuf * responseBodyBuffer = nullptr
BodyPipe::Pointer requestBodySource
AsyncCall::Pointer requestSender
BodyPipe::Pointer virginBodyDestination
CbcPointer< Adaptation::Initiate > adaptedHeadSource
BodyPipe::Pointer adaptedBodySource
bool adaptationAccessCheckPending = false
bool startedAdaptation = false
bool receivedWholeAdaptedReply = false
bool adaptedReplyAborted = false
handleAdaptedBodyProducerAborted() has been called
bool receivedWholeRequestBody = false
handleRequestBodyProductionEnded called
bool waitingForDelayAwareReadChance = false
whether we are waiting for MemObject::delayRead() to call us back
const char * markedParsedVirginReplyAsWhole = nullptr
const char * doneWithFwd = nullptr
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Member Functions
void serverComplete2 ()
void sendBodyIsTooLargeError ()
void maybePurgeOthers ()
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
Private Attributes
bool completed = false
HttpReply * theVirginReply = nullptr
HttpReply * theFinalReply = nullptr
Detailed Description
Client is a common base for classes such as HttpStateData and FtpStateData. All such classes must be able to consume request bodies from a BodyPipe or ICAP producer, adapt virgin responses using ICAP, and provide a consumer with responses.
Definition at line 29 of file Client.h.
Member Typedef Documentation
Pointer [1/3]
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Pointer [2/3]
typedef CbcPointer<BodyProducer> BodyProducer::Pointer inherited
Definition at line 25 of file BodyPipe.h.
Pointer [3/3]
typedef CbcPointer<BodyConsumer> BodyConsumer::Pointer inherited
Definition at line 45 of file BodyPipe.h.
Constructor & Destructor Documentation
Client()
Client::Client (FwdState * theFwdState)
Definition at line 38 of file Client.cc.
References entry, FwdState::entry, fwd, and StoreEntry::lock().
~Client()
Client::~Client () override
Definition at line 47 of file Client.cc.
References adaptedBodySource, assert, entry, HTTPMSGUNLOCK(), requestBodySource, responseBodyBuffer, theFinalReply, theVirginReply, StoreEntry::unlock(), and virginBodyDestination.
Member Function Documentation
abortAll()
virtual void Client::abortAll (const char * reason) pure virtual
Implemented in Ftp::Client, and HttpStateData.
Referenced by abortOnData(), handleAdaptationAborted(), handleAdaptationBlocked(), and handledEarlyAdaptationAbort().
abortOnBadEntry()
bool Client::abortOnBadEntry (const char * abortReason) protected
Definition at line 262 of file Client.cc.
References abortOnData(), debugs, entry, and StoreEntry::isAccepting().
Referenced by handleAdaptationAborted(), handleAdaptationBlocked(), handleAdaptedBodyProducerAborted(), handleAdaptedBodyProductionEnded(), handleAdaptedHeader(), handleMoreAdaptedBodyAvailable(), noteAdaptationAclCheckDone(), and resumeBodyStorage().
abortOnData()
bool Client::abortOnData (const char * reason) virtual
abnormal data transfer termination
Return values
true the transaction will be terminated (abortAll called)
false the transaction will survive
Reimplemented in Ftp::Relay.
Definition at line 315 of file Client.cc.
References abortAll().
Referenced by abortOnBadEntry(), handleAdaptationBlocked(), sendBodyIsTooLargeError(), and sentRequestBody().
adaptOrFinalizeReply()
void Client::adaptOrFinalizeReply () protected
Definition at line 1009 of file Client.cc.
References adaptationAccessCheckPending, FwdState::al, debugs, fwd, Adaptation::methodRespmod, originalRequest(), Adaptation::pointPreCache, setFinalReply(), Adaptation::AccessCheck::Start(), and virginReply().
Referenced by HttpStateData::processReply().
adaptVirginReplyBody()
void Client::adaptVirginReplyBody (const char * buf, ssize_t len) protected
Definition at line 632 of file Client.cc.
References MemBuf::append(), assert, MemBuf::consume(), MemBuf::content(), MemBuf::contentSize(), debugs, MemBuf::init(), BodyPipe::putMoreData(), responseBodyBuffer, SQUID_TCP_SO_RCVBUF, startedAdaptation, and virginBodyDestination.
Referenced by addVirginReplyBody().
addVirginReplyBody()
void Client::addVirginReplyBody (const char * buf, ssize_t len) protected
Definition at line 1054 of file Client.cc.
References adaptationAccessCheckPending, adaptVirginReplyBody(), adjustBodyBytesRead(), assert, startedAdaptation, and storeReplyBody().
Referenced by HttpStateData::decodeAndWriteReplyBody(), noteMoreBodySpaceAvailable(), and HttpStateData::writeReplyBody().
adjustBodyBytesRead()
void Client::adjustBodyBytesRead (const int64_t delta) protected
Definition at line 1027 of file Client.cc.
References HierarchyLogEntry::bodyBytesRead, HttpRequest::hier, Must, and originalRequest().
Referenced by addVirginReplyBody().
announceInitiatorAbort()
void Adaptation::Initiator::announceInitiatorAbort (CbcPointer< Initiate > & x) protected inherited
Definition at line 38 of file Initiator.cc.
References CallJobHere.
Referenced by ClientHttpRequest::~ClientHttpRequest(), and cleanAdaptation().
blockCaching()
bool Client::blockCaching () protected
Definition at line 556 of file Client.cc.
References SquidConfig::accessList, FwdState::al, Acl::Answer::allowed(), Config, debugs, entry, ACLChecklist::fastCheck(), MemObject::freshestReply(), fwd, StoreEntry::mem(), originalRequest(), SquidConfig::storeMiss, ACLFilledChecklist::updateAle(), and ACLFilledChecklist::updateReply().
Referenced by setFinalReply().
calcBufferSpaceToReserve()
size_t Client::calcBufferSpaceToReserve (const size_t space, const size_t wantSpace) const protected
Definition at line 1079 of file Client.cc.
References BodyPipe::buf(), debugs, SBuf::maxSize, min(), MemBuf::potentialSpaceSize(), responseBodyBuffer, and virginBodyDestination.
Referenced by HttpStateData::maybeMakeSpaceAvailable().
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void AsyncJob::callException (const std::exception & e) virtual inherited
Reimplemented in ConnStateData, ClientHttpRequest, Rock::Rebuild, Adaptation::Icap::ModXact, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Ipc::Forwarder, Ipc::Inquirer, and Ftp::Server.
Definition at line 143 of file AsyncJob.cc.
References cbdataReferenceValid(), debugs, Must, AsyncJob::mustStop(), and CbdataParent::toCbdata().
Referenced by ConnStateData::callException(), Adaptation::Icap::Xaction::callException(), Ipc::Forwarder::callException(), Ipc::Inquirer::callException(), and Ftp::Server::callException().
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
checkAdaptationWithBodyCompletion()
void Client::checkAdaptationWithBodyCompletion () protected
Reacts to adaptedBodySource-related changes. May end adapted body consumption, adaptation as a whole, or forwarding. Safe to call multiple times, including calls made after the end of adaptation.
Definition at line 831 of file Client.cc.
References adaptedBodySource, adaptedReplyAborted, debugs, doneWithAdaptation(), BodyPipe::exhausted(), handleAdaptationCompleted(), receivedWholeAdaptedReply, startedAdaptation, BodyPipe::status(), and BodyConsumer::stopConsumingFrom().
Referenced by handleAdaptedBodyProducerAborted(), handleAdaptedBodyProductionEnded(), handleAdaptedHeader(), and resumeBodyStorage().
cleanAdaptation()
void Client::cleanAdaptation () protected
Definition at line 607 of file Client.cc.
References adaptationAccessCheckPending, adaptedBodySource, adaptedHeadSource, Adaptation::Initiator::announceInitiatorAbort(), assert, debugs, doneWithAdaptation(), BodyConsumer::stopConsumingFrom(), BodyProducer::stopProducingFor(), and virginBodyDestination.
Referenced by handleAdaptationCompleted(), and swanSong().
clearAdaptation()
void Adaptation::Initiator::clearAdaptation (CbcPointer< Initiate > & x) protected inherited
Definition at line 32 of file Initiator.cc.
References CbcPointer< Cbc >::clear().
Referenced by ClientHttpRequest::handleAdaptedHeader(), ClientHttpRequest::noteAdaptationAnswer(), and noteAdaptationAnswer().
closeServer()
virtual void Client::closeServer () protected pure virtual
Use this to end communication with the server. The call cancels our closure handler and tells FwdState to forget about the connection.
Implemented in Ftp::Client, and HttpStateData.
Referenced by handleAdaptationCompleted(), serverComplete(), and swanSong().
completeForwarding()
void Client::completeForwarding () protected virtual
default calls fwd->complete()
Reimplemented in Ftp::Gateway, and Ftp::Relay.
Definition at line 216 of file Client.cc.
References assert, Assure, FwdState::complete(), debugs, doneWithAdaptation(), doneWithFwd, fwd, markedParsedVirginReplyAsWhole, FwdState::markStoredReplyAsWhole(), receivedWholeAdaptedReply, and startedAdaptation.
Referenced by Ftp::Gateway::completeForwarding(), Ftp::Relay::completeForwarding(), handleAdaptationCompleted(), and serverComplete2().
dataConnection()
virtual const Comm::ConnectionPointer & Client::dataConnection () const pure virtual
Returns
primary or "request data connection"
Implemented in Ftp::Client, and HttpStateData.
Referenced by sendMoreRequestBody().
delayRead()
void Client::delayRead () protected
Defer reading until it is likely to become possible. Eventually, noteDelayAwareReadChance() will be called.
Definition at line 1042 of file Client.cc.
References Assure, asyncCall(), MemObject::delayRead(), entry, StoreEntry::mem(), noteDelayAwareReadChance(), and waitingForDelayAwareReadChance.
Referenced by HttpStateData::readReply().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Client::doneAll () const override virtual
Reimplemented from AsyncJob.
Definition at line 203 of file Client.cc.
References AsyncJob::doneAll(), doneWithAdaptation(), and doneWithServer().
doneSendingRequestBody()
void Client::doneSendingRequestBody () protected pure virtual
Implemented in Ftp::Client, and HttpStateData.
Definition at line 344 of file Client.cc.
References assert, debugs, requestBodySource, and BodyConsumer::stopConsumingFrom().
Referenced by HttpStateData::doneSendingRequestBody(), handleRequestBodyProductionEnded(), and sentRequestBody().
doneWithAdaptation()
bool Client::doneWithAdaptation () const protected virtual
did we end ICAP communication?
Definition at line 624 of file Client.cc.
References adaptationAccessCheckPending, adaptedBodySource, adaptedHeadSource, and virginBodyDestination.
Referenced by checkAdaptationWithBodyCompletion(), cleanAdaptation(), completeForwarding(), doneAll(), handleAdaptedHeader(), noteBodyConsumerAborted(), and serverComplete2().
doneWithServer()
virtual bool Client::doneWithServer () const protected pure virtual
did we end communication?
Implemented in Ftp::Client, and HttpStateData.
Referenced by doneAll(), serverComplete(), and swanSong().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
finalReply()
HttpReply * Client::finalReply () protected
Definition at line 129 of file Client.cc.
References assert, and theFinalReply.
Referenced by HttpStateData::haveParsedReplyHeaders(), and HttpStateData::reusableReply().
getMoreRequestBody()
bool Client::getMoreRequestBody (MemBuf & buf) virtual
Reimplemented in HttpStateData.
Definition at line 442 of file Client.cc.
References BodyPipe::getMoreData(), Must, and requestBodySource.
Referenced by HttpStateData::getMoreRequestBody(), and sendMoreRequestBody().
handleAdaptationAborted()
void Client::handleAdaptationAborted (bool bypassable = false) protected
Definition at line 897 of file Client.cc.
References abortAll(), abortOnBadEntry(), debugs, entry, handledEarlyAdaptationAbort(), and StoreEntry::isEmpty().
Referenced by noteAdaptationAnswer().
handleAdaptationBlocked()
void Client::handleAdaptationBlocked (const Adaptation::Answer & answer) protected
Definition at line 936 of file Client.cc.
References abortAll(), abortOnBadEntry(), abortOnData(), FwdState::al, Adaptation::Answer::blockedToChecklistAnswer(), debugs, HttpRequest::detailError(), FwdState::dontRetry(), entry, ERR_ACCESS_DENIED, ERR_ICAP_FAILURE, ERR_NONE, FwdState::fail(), FindDenyInfoPage(), fwd, RefCount< C >::getRaw(), StoreEntry::isEmpty(), MakeNamedErrorDetail(), request, and Http::scForbidden.
Referenced by noteAdaptationAnswer().
handleAdaptationCompleted()
void Client::handleAdaptationCompleted () protected
Definition at line 878 of file Client.cc.
References cleanAdaptation(), closeServer(), completeForwarding(), debugs, and mayReadVirginReplyBody().
Referenced by checkAdaptationWithBodyCompletion(), handleAdaptedHeader(), and noteBodyConsumerAborted().
handleAdaptedBodyProducerAborted()
void Client::handleAdaptedBodyProducerAborted () protected
Definition at line 857 of file Client.cc.
References abortOnBadEntry(), adaptedBodySource, adaptedReplyAborted, Assure, checkAdaptationWithBodyCompletion(), debugs, BodyPipe::exhausted(), handledEarlyAdaptationAbort(), Must, and receivedWholeAdaptedReply.
Referenced by noteBodyProducerAborted().
handleAdaptedBodyProductionEnded()
void Client::handleAdaptedBodyProductionEnded () protected
Definition at line 819 of file Client.cc.
References abortOnBadEntry(), adaptedReplyAborted, Assure, checkAdaptationWithBodyCompletion(), and receivedWholeAdaptedReply.
Referenced by noteBodyProductionEnded().
handleAdaptedHeader()
void Client::handleAdaptedHeader (Http::Message * msg) protected
Definition at line 720 of file Client.cc.
References abortOnBadEntry(), adaptedBodySource, adaptedReplyAborted, assert, Assure, Http::Message::body_pipe, checkAdaptationWithBodyCompletion(), debugs, doneWithAdaptation(), BodyPipe::expectNoConsumption(), handleAdaptationCompleted(), receivedWholeAdaptedReply, BodyPipe::setConsumerIfNotLate(), and setFinalReply().
Referenced by noteAdaptationAnswer().
handledEarlyAdaptationAbort()
bool Client::handledEarlyAdaptationAbort () protected
If the store entry is still empty, fully handles adaptation abort, returning true. Otherwise just updates the request error detail and returns false.
Definition at line 913 of file Client.cc.
References abortAll(), FwdState::al, debugs, HttpRequest::detailError(), FwdState::dontRetry(), entry, ERR_ICAP_FAILURE, FwdState::fail(), fwd, RefCount< C >::getRaw(), StoreEntry::isEmpty(), MakeNamedErrorDetail(), request, and Http::scInternalServerError.
Referenced by handleAdaptationAborted(), and handleAdaptedBodyProducerAborted().
handleMoreAdaptedBodyAvailable()
void Client::handleMoreAdaptedBodyAvailable () protected
Definition at line 772 of file Client.cc.
References abortOnBadEntry(), adaptedBodySource, assert, asyncCall(), BodyPipeCheckout::buf, BodyPipe::buf(), StoreEntry::bytesWanted(), BodyPipeCheckout::checkIn(), MemBuf::consume(), BodyPipe::consumedSize(), MemBuf::contentSize(), currentOffset, debugs, StoreEntry::deferProducer(), entry, StoreIOBuffer::length, resumeBodyStorage(), and StoreEntry::write().
Referenced by noteMoreBodyDataAvailable(), and resumeBodyStorage().
handleMoreRequestBodyAvailable()
void Client::handleMoreRequestBodyAvailable () protected
Definition at line 323 of file Client.cc.
References debugs, requestSender, and sendMoreRequestBody().
Referenced by noteMoreBodyDataAvailable().
handleRequestBodyProducerAborted()
void Client::handleRequestBodyProducerAborted () protected pure virtual
Implemented in Ftp::Gateway, Ftp::Relay, and HttpStateData.
Definition at line 355 of file Client.cc.
References debugs, FwdState::dontRetry(), fwd, requestBodySource, requestSender, and BodyConsumer::stopConsumingFrom().
Referenced by Ftp::Gateway::handleRequestBodyProducerAborted(), Ftp::Relay::handleRequestBodyProducerAborted(), HttpStateData::handleRequestBodyProducerAborted(), and noteBodyProducerAborted().
handleRequestBodyProductionEnded()
void Client::handleRequestBodyProductionEnded () protected
Definition at line 333 of file Client.cc.
References debugs, doneSendingRequestBody(), receivedWholeRequestBody, and requestSender.
Referenced by noteBodyProductionEnded().
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
haveParsedReplyHeaders()
void Client::haveParsedReplyHeaders () protected virtual
called when got final headers
Reimplemented in Ftp::Gateway, and HttpStateData.
Definition at line 541 of file Client.cc.
References HttpReply::contentRange(), currentOffset, maybePurgeOthers(), Must, theFinalReply, and HttpHdrRangeSpec::UnknownPosition.
Referenced by Ftp::Gateway::haveParsedReplyHeaders(), HttpStateData::haveParsedReplyHeaders(), and setFinalReply().
initiateAdaptation()
CbcPointer< Adaptation::Initiate > Adaptation::Initiator::initiateAdaptation (Initiate * x) protected inherited
Definition at line 23 of file Initiator.cc.
References Adaptation::Initiate::initiator().
Referenced by ClientHttpRequest::startAdaptation(), and startAdaptation().
initiated()
bool Adaptation::Initiator::initiated (const CbcPointer< AsyncJob > & job) const inline protected inherited
Definition at line 52 of file Initiator.h.
References CbcPointer< Cbc >::set().
Referenced by ClientHttpRequest::startAdaptation(), and startAdaptation().
markParsedVirginReplyAsWhole()
void Client::markParsedVirginReplyAsWhole (const char * reasonWeAreSure)
remember that the received virgin reply was parsed in its entirety, including its body (if any)
Definition at line 158 of file Client.cc.
References assert, debugs, and markedParsedVirginReplyAsWhole.
Referenced by HttpStateData::decodeAndWriteReplyBody(), ftpReadTransferDone(), ftpWriteTransferDone(), and HttpStateData::writeReplyBody().
maybePurgeOthers()
void Client::maybePurgeOthers () private
Definition at line 520 of file Client.cc.
References SBuf::c_str(), Http::CONTENT_LOCATION, debugs, HttpRequest::effectiveRequestUri(), RefCount< C >::getRaw(), Http::LOCATION, HttpRequest::method, purgeEntriesByHeader(), purgeEntriesByUrl(), HttpRequestMethod::purgesOthers(), request, HttpReply::sline, Http::StatusLine::status(), and theFinalReply.
Referenced by haveParsedReplyHeaders().
maybeReadVirginBody()
virtual void Client::maybeReadVirginBody () pure virtual
Implemented in Ftp::Client, and HttpStateData.
Referenced by noteMoreBodySpaceAvailable().
mayReadVirginReplyBody()
virtual bool Client::mayReadVirginReplyBody () const protected pure virtual
Implemented in Ftp::Gateway, Ftp::Relay, and HttpStateData.
Referenced by handleAdaptationCompleted().
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
noteAdaptationAclCheckDone()
void Client::noteAdaptationAclCheckDone (Adaptation::ServiceGroupPointer group) override virtual
AccessCheck calls this back with a possibly nil service group to signal whether adaptation is needed and where it should start.
Reimplemented from Adaptation::Initiator.
Definition at line 970 of file Client.cc.
References abortOnBadEntry(), adaptationAccessCheckPending, debugs, originalRequest(), processReplyBody(), request, sendBodyIsTooLargeError(), setFinalReply(), startAdaptation(), and virginReply().
noteAdaptationAnswer()
void Client::noteAdaptationAnswer (const Adaptation::Answer & answer) override virtual
called with the initial adaptation decision (adapt, block, error); virgin and/or adapted body transmission may continue after this
Implements Adaptation::Initiator.
Definition at line 700 of file Client.cc.
References adaptedHeadSource, Adaptation::Answer::akBlock, Adaptation::Answer::akError, Adaptation::Answer::akForward, Adaptation::Initiator::clearAdaptation(), Adaptation::Answer::final, RefCount< C >::getRaw(), handleAdaptationAborted(), handleAdaptationBlocked(), handleAdaptedHeader(), Adaptation::Answer::kind, and Adaptation::Answer::message.
noteBodyConsumerAborted()
void Client::noteBodyConsumerAborted (BodyPipe::Pointer) override virtual
Implements BodyProducer.
Definition at line 688 of file Client.cc.
References doneWithAdaptation(), handleAdaptationCompleted(), BodyProducer::stopProducingFor(), and virginBodyDestination.
noteBodyProducerAborted()
void Client::noteBodyProducerAborted (BodyPipe::Pointer bp) override virtual
Implements BodyConsumer.
Definition at line 302 of file Client.cc.
References adaptedBodySource, handleAdaptedBodyProducerAborted(), handleRequestBodyProducerAborted(), and requestBodySource.
noteBodyProductionEnded()
void Client::noteBodyProductionEnded (BodyPipe::Pointer bp) override virtual
Implements BodyConsumer.
Definition at line 288 of file Client.cc.
References adaptedBodySource, handleAdaptedBodyProductionEnded(), handleRequestBodyProductionEnded(), and requestBodySource.
noteDelayAwareReadChance()
virtual void Client::noteDelayAwareReadChance () protected pure virtual
Called when a previously delayed dataConnection() read may be possible.
See also
delayRead()
Implemented in Ftp::Client, and HttpStateData.
Referenced by delayRead().
noteMoreBodyDataAvailable()
void Client::noteMoreBodyDataAvailable (BodyPipe::Pointer bp) override virtual
Implements BodyConsumer.
Definition at line 274 of file Client.cc.
References adaptedBodySource, handleMoreAdaptedBodyAvailable(), handleMoreRequestBodyAvailable(), and requestBodySource.
noteMoreBodySpaceAvailable()
void Client::noteMoreBodySpaceAvailable (BodyPipe::Pointer) override virtual
Implements BodyProducer.
Definition at line 674 of file Client.cc.
References addVirginReplyBody(), completed, maybeReadVirginBody(), responseBodyBuffer, and serverComplete2().
originalRequest()
HttpRequestPointer Client::originalRequest () virtual
Definition at line 573 of file Client.cc.
References request.
Referenced by adaptOrFinalizeReply(), adjustBodyBytesRead(), blockCaching(), HttpStateData::finishingBrokenPost(), HttpStateData::handle1xx(), noteAdaptationAclCheckDone(), and startRequestBodyFlow().
processReplyBody()
virtual void Client::processReplyBody () pure virtual
Implemented in Ftp::Gateway, Ftp::Relay, and HttpStateData.
Referenced by noteAdaptationAclCheckDone().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
resumeBodyStorage()
void Client::resumeBodyStorage () protected
Definition at line 757 of file Client.cc.
References abortOnBadEntry(), adaptedBodySource, checkAdaptationWithBodyCompletion(), and handleMoreAdaptedBodyAvailable().
Referenced by handleMoreAdaptedBodyAvailable().
sendBodyIsTooLargeError()
void Client::sendBodyIsTooLargeError () private
Definition at line 998 of file Client.cc.
References abortOnData(), FwdState::al, FwdState::dontRetry(), ERR_TOO_BIG, FwdState::fail(), fwd, RefCount< C >::getRaw(), request, and Http::scForbidden.
Referenced by noteAdaptationAclCheckDone().
sendMoreRequestBody()
void Client::sendMoreRequestBody () protected
Definition at line 416 of file Client.cc.
References assert, MemBuf::contentSize(), dataConnection(), debugs, getMoreRequestBody(), Comm::IsConnOpen(), JobCallback, requestBodySource, requestSender, sentRequestBody(), and Comm::Write().
Referenced by handleMoreRequestBodyAvailable(), and sentRequestBody().
sentRequestBody()
void Client::sentRequestBody (const CommIoCbParams & io) protected pure virtual
Implemented in Ftp::Client, and HttpStateData.
Definition at line 368 of file Client.cc.
References abortOnData(), FwdState::al, StatCounters::all, DBG_IMPORTANT, debugs, doneSendingRequestBody(), EBIT_TEST, entry, ENTRY_ABORTED, Comm::ERR_CLOSING, ERR_WRITE_ERROR, BodyPipe::exhausted(), FwdState::fail(), CommCommonCbParams::fd, fd_bytes(), CommCommonCbParams::flag, StoreEntry::flags, fwd, HttpRequest::hier, StatCounters::kbytes_out, HierarchyLogEntry::notePeerWrite(), receivedWholeRequestBody, request, FwdState::request, requestBodySource, requestSender, Http::scBadGateway, sendMoreRequestBody(), StatCounters::server, CommIoCbParams::size, statCounter, Write, CommCommonCbParams::xerrno, ErrorState::xerrno, and xstrerr().
Referenced by sendMoreRequestBody(), and HttpStateData::sentRequestBody().
serverComplete()
void Client::serverComplete ()
call when no server communication is expected
Definition at line 167 of file Client.cc.
References assert, closeServer(), completed, debugs, doneWithServer(), requestBodySource, responseBodyBuffer, serverComplete2(), and BodyConsumer::stopConsumingFrom().
Referenced by ftpReadQuit(), HttpStateData::processReplyBody(), and Ftp::Relay::serverComplete().
serverComplete2()
void Client::serverComplete2 () private
Continuation of serverComplete
Definition at line 188 of file Client.cc.
References completeForwarding(), debugs, doneWithAdaptation(), BodyProducer::stopProducingFor(), and virginBodyDestination.
Referenced by noteMoreBodySpaceAvailable(), and serverComplete().
setFinalReply()
HttpReply * Client::setFinalReply (HttpReply * r) protected
Definition at line 136 of file Client.cc.
References FwdState::al, assert, blockCaching(), debugs, EBIT_TEST, entry, StoreEntry::flags, fwd, haveParsedReplyHeaders(), HTTPMSGLOCK(), StoreEntry::release(), RELEASE_REQUEST, StoreEntry::replaceHttpReply(), AccessLogEntry::reply, StoreEntry::startWriting(), and theFinalReply.
Referenced by adaptOrFinalizeReply(), handleAdaptedHeader(), and noteAdaptationAclCheckDone().
setVirginReply()
HttpReply * Client::setVirginReply (HttpReply * r) protected
Definition at line 116 of file Client.cc.
References FwdState::al, assert, debugs, fwd, HTTPMSGLOCK(), AccessLogEntry::reply, and theVirginReply.
Referenced by HttpStateData::processReplyHeader().
start()
void AsyncJob::start () protected virtual inherited
Reimplemented in Adaptation::AccessCheck, Adaptation::Ecap::XactionRep, Adaptation::Icap::Launcher, Adaptation::Icap::ModXact, Adaptation::Icap::OptXact, Adaptation::Icap::Xaction, Adaptation::Iterator, ConnStateData, Ftp::Client, Ftp::Gateway, Ftp::Relay, Http::Tunneler, Comm::ConnOpener, Comm::TcpAcceptor, Downloader, Rock::HeaderUpdater, Rock::Rebuild, HappyConnOpener, HttpStateData, Ipc::Coordinator, Ipc::Forwarder, Ipc::Inquirer, Ipc::Strand, Ipc::UdsSender, Log::TcpLogger, Mgr::ActionWriter, Mgr::Filler, Mgr::Inquirer, Mgr::StoreToCommWriter, PeerPoolMgr, Security::PeerConnector, Ftp::Server, Http::One::Server, Server, Snmp::Inquirer, and Ipc::Port.
Definition at line 59 of file AsyncJob.cc.
Referenced by Adaptation::AccessCheck::start(), Adaptation::Icap::Launcher::start(), Adaptation::Icap::Xaction::start(), Adaptation::Iterator::start(), ConnStateData::start(), Http::Tunneler::start(), Ipc::UdsSender::start(), PeerPoolMgr::start(), Security::PeerConnector::start(), Ipc::Port::start(), and AsyncJob::Start().
Start()
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Rock::Rebuild::Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
startAdaptation()
void Client::startAdaptation (const Adaptation::ServiceGroupPointer & group, HttpRequest * cause) protected
Definition at line 581 of file Client.cc.
References adaptedHeadSource, FwdState::al, assert, Http::Message::body_pipe, debugs, HttpReply::expectingBody(), fwd, Adaptation::Initiator::initiateAdaptation(), Adaptation::Initiator::initiated(), HttpRequest::method, Must, BodyPipe::setBodySize(), size, startedAdaptation, virginBodyDestination, and virginReply().
Referenced by noteAdaptationAclCheckDone().
startRequestBodyFlow()
bool Client::startRequestBodyFlow () protected
Definition at line 243 of file Client.cc.
References assert, Http::Message::body_pipe, debugs, originalRequest(), requestBodySource, BodyPipe::setConsumerIfNotLate(), and BodyPipe::status().
Referenced by HttpStateData::sendRequest().
status()
const char * AsyncJob::status () const protected virtual inherited
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), AsyncJob::stopReason, and MemBuf::terminate().
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
stopConsumingFrom()
void BodyConsumer::stopConsumingFrom (RefCount< BodyPipe > & p) protected inherited
Definition at line 118 of file BodyPipe.cc.
References assert, and debugs.
Referenced by ClientHttpRequest::~ClientHttpRequest(), checkAdaptationWithBodyCompletion(), cleanAdaptation(), doneSendingRequestBody(), ClientHttpRequest::endRequestSatisfaction(), handleRequestBodyProducerAborted(), BodySink::noteBodyProducerAborted(), ClientHttpRequest::noteBodyProducerAborted(), BodySink::noteBodyProductionEnded(), serverComplete(), and swanSong().
stopProducingFor()
void BodyProducer::stopProducingFor (RefCount< BodyPipe > & p, bool atEof) protected inherited
Definition at line 107 of file BodyPipe.cc.
References assert, and debugs.
Referenced by ConnStateData::~ConnStateData(), cleanAdaptation(), ConnStateData::finishDechunkingRequest(), noteBodyConsumerAborted(), and serverComplete2().
storeReplyBody()
void Client::storeReplyBody (const char * buf, ssize_t len) protected
Definition at line 1070 of file Client.cc.
References currentOffset, entry, and StoreEntry::write().
Referenced by addVirginReplyBody().
swanSong()
void Client::swanSong () override virtual
Reimplemented from AsyncJob.
Reimplemented in Ftp::Relay.
Definition at line 68 of file Client.cc.
References adaptedBodySource, assert, cleanAdaptation(), closeServer(), doneWithFwd, doneWithServer(), fwd, FwdState::handleUnregisteredServerEnd(), requestBodySource, BodyConsumer::stopConsumingFrom(), AsyncJob::swanSong(), and virginBodyDestination.
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
virginReply() [1/2]
HttpReply * Client::virginReply () protected
Definition at line 102 of file Client.cc.
References assert, and theVirginReply.
virginReply() [2/2]
const HttpReply * Client::virginReply () const protected
Definition at line 109 of file Client.cc.
References assert, and theVirginReply.
Referenced by adaptOrFinalizeReply(), HttpStateData::continueAfterParsingHeader(), noteAdaptationAclCheckDone(), HttpStateData::persistentConnStatus(), startAdaptation(), HttpStateData::statusIfComplete(), HttpStateData::truncateVirginBody(), and HttpStateData::writeReplyBody().
Member Data Documentation
adaptationAccessCheckPending
bool Client::adaptationAccessCheckPending = false protected
Definition at line 190 of file Client.h.
Referenced by adaptOrFinalizeReply(), addVirginReplyBody(), cleanAdaptation(), doneWithAdaptation(), noteAdaptationAclCheckDone(), and HttpStateData::processReplyBody().
adaptedBodySource
BodyPipe::Pointer Client::adaptedBodySource protected
to consume adated response body
Definition at line 188 of file Client.h.
Referenced by ~Client(), checkAdaptationWithBodyCompletion(), cleanAdaptation(), doneWithAdaptation(), handleAdaptedBodyProducerAborted(), handleAdaptedHeader(), handleMoreAdaptedBodyAvailable(), noteBodyProducerAborted(), noteBodyProductionEnded(), noteMoreBodyDataAvailable(), resumeBodyStorage(), and swanSong().
adaptedHeadSource
CbcPointer<Adaptation::Initiate> Client::adaptedHeadSource protected
to get adapted response headers
Definition at line 187 of file Client.h.
Referenced by cleanAdaptation(), doneWithAdaptation(), noteAdaptationAnswer(), and startAdaptation().
adaptedReplyAborted
bool Client::adaptedReplyAborted = false protected
Definition at line 198 of file Client.h.
Referenced by checkAdaptationWithBodyCompletion(), handleAdaptedBodyProducerAborted(), handleAdaptedBodyProductionEnded(), and handleAdaptedHeader().
completed
bool Client::completed = false private
serverComplete() has been called
Definition at line 90 of file Client.h.
Referenced by noteMoreBodySpaceAvailable(), and serverComplete().
currentOffset
int64_t Client::currentOffset = 0 protected
Our current offset in the StoreEntry
Definition at line 173 of file Client.h.
Referenced by Ftp::Gateway::getCurrentOffset(), handleMoreAdaptedBodyAvailable(), haveParsedReplyHeaders(), Ftp::Gateway::setCurrentOffset(), and storeReplyBody().
doneWithFwd
const char* Client::doneWithFwd = nullptr protected
whether we should not be talking to FwdState; XXX: clear fwd instead points to a string literal which is used only for debugging
Definition at line 211 of file Client.h.
Referenced by completeForwarding(), HttpStateData::httpStateConnClosed(), HttpStateData::proceedAfter1xx(), and swanSong().
entry
StoreEntry* Client::entry = nullptr
Definition at line 177 of file Client.h.
Referenced by Client(), Ftp::Gateway::Gateway(), HttpStateData::HttpStateData(), Ftp::Relay::Relay(), ~Client(), abortOnBadEntry(), blockCaching(), HttpStateData::buildRequestPrefix(), HttpStateData::continueAfterParsingHeader(), delayRead(), ftpFail(), ftpSendReply(), ftpWriteTransferDone(), handleAdaptationAborted(), handleAdaptationBlocked(), handledEarlyAdaptationAbort(), handleMoreAdaptedBodyAvailable(), HttpStateData::handleRequestBodyProducerAborted(), HttpStateData::haveParsedReplyHeaders(), HttpStateData::httpBuildRequestHeader(), HttpStateData::httpTimeout(), HttpStateData::keepaliveAccounting(), HttpStateData::peerSupportsConnectionPinning(), HttpStateData::processReply(), HttpStateData::processReplyBody(), HttpStateData::processReplyHeader(), HttpStateData::processSurrogateControl(), HttpStateData::readReply(), HttpStateData::reusableReply(), sentRequestBody(), setFinalReply(), HttpStateData::statusIfComplete(), storeReplyBody(), and HttpStateData::wroteLast().
fwd
FwdState::Pointer Client::fwd
Definition at line 178 of file Client.h.
Referenced by Client(), HttpStateData::HttpStateData(), adaptOrFinalizeReply(), blockCaching(), HttpStateData::buildRequestPrefix(), HttpStateData::closeServer(), completeForwarding(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), HttpStateData::finishingBrokenPost(), HttpStateData::forwardUpgrade(), ftpFail(), ftpSendReply(), HttpStateData::handle1xx(), handleAdaptationBlocked(), handledEarlyAdaptationAbort(), HttpStateData::handleRequestBodyProducerAborted(), handleRequestBodyProducerAborted(), HttpStateData::httpTimeout(), HttpStateData::markPrematureReplyBodyEofFailure(), HttpStateData::proceedAfter1xx(), HttpStateData::processReplyBody(), HttpStateData::readReply(), sendBodyIsTooLargeError(), sentRequestBody(), setFinalReply(), setVirginReply(), startAdaptation(), swanSong(), and HttpStateData::wroteLast().
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
markedParsedVirginReplyAsWhole
const char* Client::markedParsedVirginReplyAsWhole = nullptr protected
markParsedVirginReplyAsWhole() parameter (if that method was called) or nil; points to a string literal which is used only for debugging
Definition at line 207 of file Client.h.
Referenced by completeForwarding(), and markParsedVirginReplyAsWhole().
receivedWholeAdaptedReply
bool Client::receivedWholeAdaptedReply = false protected
Whether the entire adapted response (including bodyless responses) has been successfully produced. A successful end of body production does not imply that we have consumed all of the produced body bytes.
Definition at line 196 of file Client.h.
Referenced by checkAdaptationWithBodyCompletion(), completeForwarding(), handleAdaptedBodyProducerAborted(), handleAdaptedBodyProductionEnded(), and handleAdaptedHeader().
receivedWholeRequestBody
bool Client::receivedWholeRequestBody = false protected
Definition at line 200 of file Client.h.
Referenced by HttpStateData::finishingChunkedRequest(), HttpStateData::getMoreRequestBody(), handleRequestBodyProductionEnded(), and sentRequestBody().
request
HttpRequestPointer Client::request
Definition at line 179 of file Client.h.
Referenced by Ftp::Gateway::Gateway(), HttpStateData::HttpStateData(), HttpStateData::buildRequestPrefix(), HttpStateData::checkDateSkew(), HttpStateData::continueAfterParsingHeader(), HttpStateData::decideIfWeDoRanges(), HttpStateData::drop1xx(), HttpStateData::forwardUpgrade(), ftpFail(), ftpReadType(), ftpSendPassive(), ftpSendReply(), ftpSendStor(), ftpSendType(), ftpSendUser(), HttpStateData::handle1xx(), handleAdaptationBlocked(), handledEarlyAdaptationAbort(), HttpStateData::haveParsedReplyHeaders(), HttpStateData::httpBuildRequestHeader(), HttpStateData::keepaliveAccounting(), maybePurgeOthers(), noteAdaptationAclCheckDone(), originalRequest(), HttpStateData::peerSupportsConnectionPinning(), HttpStateData::persistentConnStatus(), HttpStateData::proceedAfter1xx(), HttpStateData::processReplyBody(), HttpStateData::processReplyHeader(), HttpStateData::processSurrogateControl(), HttpStateData::readReply(), HttpStateData::reusableReply(), sendBodyIsTooLargeError(), HttpStateData::sendRequest(), sentRequestBody(), HttpStateData::statusIfComplete(), HttpStateData::truncateVirginBody(), HttpStateData::writeReplyBody(), and HttpStateData::wroteLast().
requestBodySource
BodyPipe::Pointer Client::requestBodySource protected
to consume request body
Definition at line 182 of file Client.h.
Referenced by ~Client(), doneSendingRequestBody(), getMoreRequestBody(), HttpStateData::getMoreRequestBody(), handleRequestBodyProducerAborted(), noteBodyProducerAborted(), noteBodyProductionEnded(), noteMoreBodyDataAvailable(), sendMoreRequestBody(), HttpStateData::sendRequest(), sentRequestBody(), serverComplete(), startRequestBodyFlow(), and swanSong().
requestSender
AsyncCall::Pointer Client::requestSender protected
set if we are expecting Comm::Write to call us back
Definition at line 183 of file Client.h.
Referenced by HttpStateData::finishingBrokenPost(), HttpStateData::finishingChunkedRequest(), handleMoreRequestBodyAvailable(), handleRequestBodyProducerAborted(), handleRequestBodyProductionEnded(), sendMoreRequestBody(), HttpStateData::sendRequest(), and sentRequestBody().
responseBodyBuffer
MemBuf* Client::responseBodyBuffer = nullptr protected
Data temporarily buffered for ICAP
Definition at line 174 of file Client.h.
Referenced by ~Client(), adaptVirginReplyBody(), calcBufferSpaceToReserve(), HttpStateData::canBufferMoreReplyBytes(), noteMoreBodySpaceAvailable(), HttpStateData::readReply(), and serverComplete().
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
startedAdaptation
bool Client::startedAdaptation = false protected
Definition at line 191 of file Client.h.
Referenced by adaptVirginReplyBody(), addVirginReplyBody(), checkAdaptationWithBodyCompletion(), completeForwarding(), and startAdaptation().
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
theFinalReply
HttpReply* Client::theFinalReply = nullptr private
adapted reply from ICAP or virgin reply
Definition at line 218 of file Client.h.
Referenced by ~Client(), finalReply(), haveParsedReplyHeaders(), maybePurgeOthers(), and setFinalReply().
theVirginReply
HttpReply* Client::theVirginReply = nullptr private
reply received from the origin server
Definition at line 217 of file Client.h.
Referenced by ~Client(), setVirginReply(), virginReply(), and virginReply().
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
virginBodyDestination
BodyPipe::Pointer Client::virginBodyDestination protected
to provide virgin response body
Definition at line 186 of file Client.h.
Referenced by ~Client(), adaptVirginReplyBody(), calcBufferSpaceToReserve(), cleanAdaptation(), doneWithAdaptation(), noteBodyConsumerAborted(), HttpStateData::readReply(), serverComplete2(), startAdaptation(), and swanSong().
waitingForDelayAwareReadChance
bool Client::waitingForDelayAwareReadChance = false protected
Definition at line 203 of file Client.h.
Referenced by delayRead(), HttpStateData::maybeReadVirginBody(), and HttpStateData::noteDelayAwareReadChance().
The documentation for this class was generated from the following files:
squid/src/clients/Client.h
squid/src/clients/Client.cc