Squid Web Cache: Ipc::StrandMessage Class Reference
Ipc::StrandMessage Class Reference
an IPC message carrying StrandCoord
#include <StrandCoord.h>
Public Member Functions
StrandMessage (const StrandCoord &, QuestionerId)
StrandMessage (const TypedMsgHdr &)
void pack (MessageType, TypedMsgHdr &) const
QuestionerId intendedRecepient () const
for Mine() tests
Static Public Member Functions
static void NotifyCoordinator (MessageType, const char *tag)
creates and sends StrandMessage to Coordinator
Public Attributes
StrandCoord strand
messageType-specific coordinates (e.g., sender)
QuestionerId qid
Detailed Description
Definition at line 38 of file StrandCoord.h.
Constructor & Destructor Documentation
StrandMessage() [1/2]
Ipc::StrandMessage::StrandMessage (const StrandCoord & aStrand, QuestionerId aQid) explicit
Definition at line 41 of file StrandCoord.cc.
StrandMessage() [2/2]
Ipc::StrandMessage::StrandMessage (const TypedMsgHdr & hdrMsg) explicit
Definition at line 47 of file StrandCoord.cc.
Member Function Documentation
intendedRecepient()
QuestionerId Ipc::StrandMessage::intendedRecepient () const inline
Definition at line 49 of file StrandCoord.h.
References qid.
NotifyCoordinator()
void Ipc::StrandMessage::NotifyCoordinator (MessageType msgType, const char * tag) static
Definition at line 62 of file StrandCoord.cc.
References Ipc::Port::CoordinatorAddr(), KidIdentifier, Ipc::MyQuestionerId(), pack(), pid, Ipc::SendMessage(), strand, and Ipc::StrandCoord::tag.
Referenced by IpcIoFile::open(), and Ipc::Strand::registerSelf().
pack()
void Ipc::StrandMessage::pack (MessageType messageType, TypedMsgHdr & hdrMsg) const
Definition at line 54 of file StrandCoord.cc.
References Ipc::TypedMsgHdr::setType().
Referenced by Ipc::Coordinator::handleRegistrationRequest(), NotifyCoordinator(), and Ipc::Coordinator::notifySearcher().
Member Data Documentation
qid
QuestionerId Ipc::StrandMessage::qid
For IPC requests/questions: The sender of this request. For IPC responses/answers: The sender of the corresponding request.
Definition at line 56 of file StrandCoord.h.
Referenced by intendedRecepient().
strand
StrandCoord Ipc::StrandMessage::strand
Definition at line 52 of file StrandCoord.h.
Referenced by IpcIoFile::HandleOpenResponse(), Ipc::Coordinator::handleRegistrationRequest(), Ipc::Strand::handleRegistrationResponse(), NotifyCoordinator(), and IpcIoFile::openCompleted().
The documentation for this class was generated from the following files:
squid/src/ipc/StrandCoord.h
squid/src/ipc/StrandCoord.cc