Squid Web Cache: CpuAffinityMap Class Reference
CpuAffinityMap Class Reference
stores cpu_affinity_map configuration
#include <CpuAffinityMap.h>
Public Member Functions
bool add (const std::vector< int > &aProcesses, const std::vector< int > &aCores)
append cpu_affinity_map option
CpuAffinitySet * calculateSet (const int targetProcess) const
calculate CPU set for this process
const std::vector< int > & processes () const
returns list of process numbers
const std::vector< int > & cores () const
returns list of cores
Private Attributes
std::vector< int > theProcesses
list of process numbers
std::vector< int > theCores
list of cores
Detailed Description
Definition at line 17 of file CpuAffinityMap.h.
Member Function Documentation
add()
bool CpuAffinityMap::add (const std::vector< int > & aProcesses, const std::vector< int > & aCores)
Definition at line 18 of file CpuAffinityMap.cc.
References theCores, and theProcesses.
calculateSet()
CpuAffinitySet * CpuAffinityMap::calculateSet (const int targetProcess) const
Definition at line 36 of file CpuAffinityMap.cc.
References CPU_SET, CPU_ZERO, DBG_CRITICAL, debugs, Must, CpuAffinitySet::set(), theCores, and theProcesses.
Referenced by CpuAffinityInit().
cores()
const std::vector< int > & CpuAffinityMap::cores () const inline
Definition at line 30 of file CpuAffinityMap.h.
References theCores.
Referenced by dump_CpuAffinityMap().
processes()
const std::vector< int > & CpuAffinityMap::processes () const inline
Definition at line 27 of file CpuAffinityMap.h.
References theProcesses.
Referenced by CpuAffinityCheck(), and dump_CpuAffinityMap().
Member Data Documentation
theCores
std::vector<int> CpuAffinityMap::theCores private
Definition at line 34 of file CpuAffinityMap.h.
Referenced by add(), calculateSet(), and cores().
theProcesses
std::vector<int> CpuAffinityMap::theProcesses private
Definition at line 33 of file CpuAffinityMap.h.
Referenced by add(), calculateSet(), and processes().
The documentation for this class was generated from the following files:
squid/src/CpuAffinityMap.h
squid/src/CpuAffinityMap.cc