Squid Web Cache: Rock::Rebuild Class Reference
Rock::Rebuild Class Reference abstract
#include <RockRebuild.h>
Classes
class Stats
cache_dir indexing statistics shared across same-kid process restarts
Public Types
typedef CbcPointer< AsyncJob > Pointer
Public Member Functions
virtual void callException (const std::exception &) override
called when the job throws during an async call
bool canBeCalled (AsyncCall &call) const
whether we can be called
void callStart (AsyncCall &call)
virtual void callEnd ()
called right after the called job method
void handleStopRequest ()
process external request to terminate now (i.e. during this async call)
virtual void * toCbdata ()=0
Static Public Member Functions
static bool Start (SwapDir &dir)
static void Start (const Pointer &job)
static void RegisterWithCacheManager ()
Public Attributes
const InstanceId< AsyncJob > id
job identifier
Protected Member Functions
Rebuild (SwapDir *dir, const Ipc::Mem::Pointer< Stats > &)
~Rebuild () override
void startShutdown () override
void start () override
prepares and initiates entry loading sequence
bool doneAll () const override
whether positive goal has been reached
void swanSong () override
bool doneLoading () const
bool doneValidating () const
void deleteThis (const char *aReason)
void mustStop (const char *aReason)
bool done () const
the job is destroyed in callEnd() when done()
virtual const char * status () const
internal cleanup; do not call directly
Static Protected Member Functions
static bool IsResponsible (const SwapDir &)
whether the current kid is responsible for rebuilding the given cache_dir
static void ReportAllJobs (StoreEntry *)
writes a cache manager report about all jobs existing in this worker
Protected Attributes
const char * stopReason
reason for forcing done() to be true
const char * typeName
kid (leaf) class name, for debugging
AsyncCall::Pointer inCall
the asynchronous call being handled, if any
bool started_ = false
Start() has finished successfully.
bool swanSang_ = false
swanSong() was called
Private Types
typedef void(RegisteredRunner::* Method) ()
a pointer to one of the above notification methods
Private Member Functions
CBDATA_CHILD (Rebuild)
void checkpoint ()
continues after a pause if not done
void steps ()
void loadingSteps ()
void validationSteps ()
void loadOneSlot ()
void validateOneEntry (const sfileno fileNo)
void validateOneSlot (const SlotId slotId)
bool importEntry (Ipc::StoreMapAnchor &anchor, const sfileno slotId, const DbCellHeader &header)
parse StoreEntry basics and add them to the map, returning true on success
void freeBadEntry (const sfileno fileno, const char *eDescription)
void failure (const char *msg, int errNo=0)
a helper to handle rebuild-killing I/O errors
LoadingEntry loadingEntry (const sfileno fileNo)
void startNewEntry (const sfileno fileno, const SlotId slotId, const DbCellHeader &header)
handle a slot from an entry that we have not seen before
void primeNewEntry (Ipc::StoreMapAnchor &anchor, const sfileno fileno, const DbCellHeader &header)
initialize housekeeping information for a newly accepted entry
void finalizeOrFree (const sfileno fileNo, LoadingEntry &le)
void finalizeOrThrow (const sfileno fileNo, LoadingEntry &le)
void addSlotToEntry (const sfileno fileno, const SlotId slotId, const DbCellHeader &header)
void useNewSlot (const SlotId slotId, const DbCellHeader &header)
handle freshly loaded (and validated) db slot header
LoadingSlot loadingSlot (const SlotId slotId)
void mapSlot (const SlotId slotId, const DbCellHeader &header)
adds slot to the entry chain in the map
void freeUnusedSlot (const SlotId slotId, const bool invalid)
freeSlot() for never-been-mapped slots
void freeSlot (const SlotId slotId, const bool invalid)
adds slot to the free slot index
template<class SlotIdType >
void chainSlots (SlotIdType &from, const SlotId to)
bool sameEntry (const sfileno fileno, const DbCellHeader &header) const
does the header belong to the fileno entry being loaded?
SBuf progressDescription () const
virtual void finalizedInCbdataChild ()=0
hack: ensure CBDATA_CHILD() after a toCbdata()-defining CBDATA_INTERMEDIATE()
void registerRunner ()
void unregisterRunner ()
unregisters self; safe to call multiple times
virtual void bootstrapConfig ()
virtual void finalizeConfig ()
virtual void claimMemoryNeeds ()
virtual void useConfig ()
virtual void startReconfigure ()
virtual void syncConfig ()
virtual void endingShutdown ()
virtual void finishShutdown ()
Meant for cleanup of services needed by the already destroyed objects.
Static Private Member Functions
static void Steps (void *data)
Private Attributes
SwapDir * sd
LoadingParts * parts
parts of store entries being loaded from disk
Ipc::Mem::Pointer< Stats > stats
indexing statistics in shared memory
int64_t dbSize
int dbSlotSize
the size of a db cell, including the cell header
int64_t dbSlotLimit
total number of db cells
int64_t dbEntryLimit
maximum number of entries that can be stored in db
int fd
int64_t dbOffset
int64_t loadingPos
index of the db slot being loaded from disk now
int64_t validationPos
index of the loaded db slot being validated now
MemBuf buf
space to load current db slot (and entry metadata) into
StoreRebuildData & counts
a reference to the shared memory counters
const bool resuming
Detailed Description
manages store rebuild process: loading meta information from db on disk
Definition at line 30 of file RockRebuild.h.
Member Typedef Documentation
Method
typedef void(RegisteredRunner::* RegisteredRunner::Method) () inherited
Definition at line 94 of file RunnersRegistry.h.
Pointer
typedef CbcPointer<AsyncJob> AsyncJob::Pointer inherited
Definition at line 34 of file AsyncJob.h.
Constructor & Destructor Documentation
Rebuild()
Rock::Rebuild::Rebuild (SwapDir * dir, const Ipc::Mem::Pointer< Stats > & s) protected
Definition at line 300 of file RockRebuild.cc.
References assert, dbEntryLimit, dbSize, dbSlotLimit, dbSlotSize, Rock::SwapDir::diskOffsetLimit(), Rock::SwapDir::entryLimitActual(), IndependentRunner::registerRunner(), sd, Rock::SwapDir::slotLimitActual(), and Rock::SwapDir::slotSize.
~Rebuild()
Rock::Rebuild::~Rebuild () override protected
Definition at line 324 of file RockRebuild.cc.
References file_close().
Member Function Documentation
addSlotToEntry()
void Rock::Rebuild::addSlotToEntry (const sfileno fileno, const SlotId slotId, const DbCellHeader & header) private
adds slot to an existing entry chain; caller must check that the slot belongs to the chain it is being added to
Definition at line 783 of file RockRebuild.cc.
References Rock::LoadingEntry::anchored(), assert, Ipc::StoreMapAnchor::basics, StoreRebuildData::clashcount, counts, debugs, Rock::DbCellHeader::entrySize, Rock::DbCellHeader::firstSlot, Rock::LoadingSlot::more, Rock::DbCellHeader::payloadSize, Rock::LoadingEntry::size, Ipc::StoreMapAnchor::start, and Ipc::StoreMapAnchor::Basics::swap_file_sz.
bootstrapConfig()
virtual void RegisteredRunner::bootstrapConfig () inline virtual inherited
Called right before parsing squid.conf. Meant for initializing/preparing configuration parsing facilities.
Reimplemented in NtlmAuthRr.
Definition at line 46 of file RunnersRegistry.h.
Referenced by SquidMain().
callEnd()
void AsyncJob::callEnd () virtual inherited
called right after the called job method
Reimplemented in Adaptation::Icap::Xaction.
Definition at line 152 of file AsyncJob.cc.
References assert, AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::done(), AsyncJob::inCall, AsyncJob::started_, AsyncJob::status(), AsyncJob::swanSang_, AsyncJob::swanSong(), and AsyncJob::typeName.
Referenced by Adaptation::Icap::Xaction::callEnd(), and AsyncJob::deleteThis().
callException()
void Rock::Rebuild::callException (const std::exception & e) override virtual
Reimplemented from AsyncJob.
Definition at line 700 of file RockRebuild.cc.
callStart()
void AsyncJob::callStart (AsyncCall & call) inherited
called just before the called method
Definition at line 130 of file AsyncJob.cc.
References cbdataReferenceValid(), AsyncCall::debugLevel, debugs, AsyncCall::debugSection, AsyncJob::inCall, Must, AsyncJob::status(), CbdataParent::toCbdata(), and AsyncJob::typeName.
canBeCalled()
bool AsyncJob::canBeCalled (AsyncCall & call) const inherited
Definition at line 117 of file AsyncJob.cc.
References AsyncCall::cancel(), debugs, and AsyncJob::inCall.
CBDATA_CHILD()
Rock::Rebuild::CBDATA_CHILD (Rebuild) private
chainSlots()
template<class SlotIdType > void Rock::Rebuild::chainSlots (SlotIdType & from, const SlotId to) private
Definition at line 772 of file RockRebuild.cc.
References assert, and Rock::LoadingSlot::more.
checkpoint()
void Rock::Rebuild::checkpoint () private
Definition at line 377 of file RockRebuild.cc.
References eventAdd(), and Steps().
claimMemoryNeeds()
virtual void RegisteredRunner::claimMemoryNeeds () inline virtual inherited
Called after finalizeConfig(). Meant for announcing memory reservations before memory is allocated.
Reimplemented in IpcIoRr, and MemStoreRr.
Definition at line 55 of file RunnersRegistry.h.
Referenced by RunConfigUsers().
deleteThis()
void AsyncJob::deleteThis (const char * aReason) protected inherited
Definition at line 65 of file AsyncJob.cc.
References asyncCall(), AsyncJob::callEnd(), debugs, AsyncJob::deleteThis(), AsyncJob::inCall, JobMemFun(), Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by ConnStateData::connStateClosed(), and AsyncJob::deleteThis().
done()
bool AsyncJob::done () const protected inherited
Definition at line 106 of file AsyncJob.cc.
References AsyncJob::doneAll(), and AsyncJob::stopReason.
Referenced by AsyncJob::callEnd(), HappyConnOpener::checkForNewConnection(), Downloader::downloadFinished(), and HappyConnOpener::maybeOpenPrimeConnection().
doneAll()
bool Rock::Rebuild::doneAll () const override protected virtual
Reimplemented from AsyncJob.
Definition at line 396 of file RockRebuild.cc.
References AsyncJob::doneAll().
doneLoading()
bool Rock::Rebuild::doneLoading () const protected
Definition at line 384 of file RockRebuild.cc.
References Rock::DoneLoading().
doneValidating()
bool Rock::Rebuild::doneValidating () const protected
Definition at line 390 of file RockRebuild.cc.
References Rock::DoneValidating().
endingShutdown()
virtual void RegisteredRunner::endingShutdown () inline virtual inherited
Called after shutdown_lifetime grace period ends and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented in Auth::CredentialCacheRr, ConnStateData, Dns::ConfigRr, and IdleConnList.
Definition at line 84 of file RunnersRegistry.h.
Referenced by SignalEngine::FinalShutdownRunners().
failure()
void Rock::Rebuild::failure (const char * msg, int errNo = 0) private
Definition at line 709 of file RockRebuild.cc.
References assert, debugs, error(), Debug::Extra(), Here, Math::int64Percent(), and xstrerr().
finalizeConfig()
virtual void RegisteredRunner::finalizeConfig () inline virtual inherited
Called after parsing squid.conf. Meant for setting configuration options that depend on other configuration options and were not explicitly configured.
Reimplemented in sslBumpCfgRr, MemStoreRr, and SnmpRr.
Definition at line 51 of file RunnersRegistry.h.
Referenced by SquidMain().
finalizedInCbdataChild()
virtual void CbdataParent::finalizedInCbdataChild () private pure virtual inherited
finalizeOrFree()
void Rock::Rebuild::finalizeOrFree (const sfileno fileNo, LoadingEntry & le) private
Either make the entry accessible to all or free it. This method must only be called when no more entry slots are expected.
Definition at line 634 of file RockRebuild.cc.
finalizeOrThrow()
void Rock::Rebuild::finalizeOrThrow (const sfileno fileNo, LoadingEntry & le) private
Either make the entry accessible to all or throw. This method assumes it is called only when no more entry slots are expected.
Definition at line 600 of file RockRebuild.cc.
References Ipc::StoreMapAnchor::basics, counts, EBIT_SET, ENTRY_VALIDATED, Rock::LoadingSlot::finalized(), Ipc::StoreMapAnchor::Basics::flags, Rock::LoadingSlot::freed(), Rock::LoadingEntry::leLoaded, Rock::LoadingSlot::mapped(), Must, Ipc::StoreMapSlice::next, StoreRebuildData::objcount, Rock::LoadingEntry::size, Ipc::StoreMapSlice::size, Ipc::StoreMapAnchor::start, Rock::LoadingEntry::state(), and Ipc::StoreMapAnchor::Basics::swap_file_sz.
finishShutdown()
virtual void RegisteredRunner::finishShutdown () inline virtual inherited
Definition at line 91 of file RunnersRegistry.h.
Referenced by RunRegistered(), SquidShutdown(), TestRock::tearDown(), and watch_child().
freeBadEntry()
void Rock::Rebuild::freeBadEntry (const sfileno fileno, const char * eDescription) private
Marks remaining bad entry slots as free and unlocks the entry. The map cannot do this because Loading entries may have holes in the slots chain.
Definition at line 672 of file RockRebuild.cc.
References assert, debugs, Rock::LoadingEntry::leCorrupted, Rock::LoadingEntry::size, Ipc::StoreMapAnchor::start, and Rock::LoadingEntry::state().
freeSlot()
void Rock::Rebuild::freeSlot (const SlotId slotId, const bool invalid) private
Definition at line 727 of file RockRebuild.cc.
References assert, counts, debugs, Rock::LoadingSlot::freed(), Ipc::Mem::PageStack::IdForSwapDirSpace(), StoreRebuildData::invalid, Ipc::Mem::PageId::number, and Ipc::Mem::PageId::pool.
freeUnusedSlot()
void Rock::Rebuild::freeUnusedSlot (const SlotId slotId, const bool invalid) private
Definition at line 747 of file RockRebuild.cc.
References assert, and Rock::LoadingSlot::mapped().
handleStopRequest()
void AsyncJob::handleStopRequest () inline inherited
Definition at line 73 of file AsyncJob.h.
References AsyncJob::mustStop().
importEntry()
bool Rock::Rebuild::importEntry (Ipc::StoreMapAnchor & anchor, const sfileno slotId, const DbCellHeader & header) private
Definition at line 532 of file RockRebuild.cc.
References Ipc::StoreMapAnchor::basics, counts, debugs, EBIT_CLR, ENTRY_VALIDATED, Rock::DbCellHeader::entrySize, Ipc::StoreMapAnchor::Basics::flags, Ipc::StoreMapAnchor::set(), SQUID_MD5_DIGEST_LENGTH, storeRebuildParseEntry(), Ipc::StoreMapAnchor::Basics::swap_file_sz, StoreEntry::swap_file_sz, and ZeroedSlot().
IsResponsible()
bool Rock::Rebuild::IsResponsible (const SwapDir &) static protected
Definition at line 274 of file RockRebuild.cc.
References IamDiskProcess(), and UsingSmp().
loadingEntry()
Rock::LoadingEntry Rock::Rebuild::loadingEntry (const sfileno fileNo) private
Definition at line 455 of file RockRebuild.cc.
References Must.
loadingSlot()
Rock::LoadingSlot Rock::Rebuild::loadingSlot (const SlotId slotId) private
Definition at line 462 of file RockRebuild.cc.
References Must.
loadingSteps()
void Rock::Rebuild::loadingSteps () private
Definition at line 420 of file RockRebuild.cc.
References counts, current_time, debugs, getCurrentTime(), opt_foreground_rebuild, StoreRebuildData::scancount, storeRebuildProgress(), and tvSubMsec().
loadOneSlot()
void Rock::Rebuild::loadOneSlot () private
Definition at line 470 of file RockRebuild.cc.
References counts, DBG_IMPORTANT, debugs, Rock::DbCellHeader::empty(), Rock::DbCellHeader::sane(), StoreRebuildData::scancount, and storeRebuildLoadEntry().
mapSlot()
void Rock::Rebuild::mapSlot (const SlotId slotId, const DbCellHeader & header) private
Definition at line 757 of file RockRebuild.cc.
References assert, Rock::LoadingSlot::freed(), Rock::LoadingSlot::mapped(), Ipc::StoreMapSlice::next, Rock::DbCellHeader::nextSlot, Rock::DbCellHeader::payloadSize, and Ipc::StoreMapSlice::size.
mustStop()
void AsyncJob::mustStop (const char * aReason) protected inherited
Definition at line 85 of file AsyncJob.cc.
References debugs, AsyncJob::inCall, Must, AsyncJob::stopReason, and AsyncJob::typeName.
Referenced by HttpStateData::abortAll(), AsyncJob::callException(), HttpStateData::continueAfterParsingHeader(), HttpStateData::drop1xx(), AsyncJob::handleStopRequest(), HttpStateData::httpStateConnClosed(), HttpStateData::httpTimeout(), HttpStateData::proceedAfter1xx(), ConnStateData::proxyProtocolError(), HttpStateData::readReply(), HttpStateData::start(), and HttpStateData::wroteLast().
primeNewEntry()
void Rock::Rebuild::primeNewEntry (Ipc::StoreMapAnchor & anchor, const sfileno fileno, const DbCellHeader & header) private
Definition at line 843 of file RockRebuild.cc.
References assert, Ipc::StoreMapAnchor::basics, Rock::DbCellHeader::firstSlot, Rock::DbCellHeader::key, Rock::LoadingEntry::leLoading, Ipc::StoreMapAnchor::setKey(), Rock::LoadingEntry::size, Ipc::StoreMapAnchor::start, Rock::LoadingEntry::state(), Ipc::StoreMapAnchor::Basics::swap_file_sz, Rock::DbCellHeader::version, and Rock::LoadingEntry::version.
progressDescription()
SBuf Rock::Rebuild::progressDescription () const private
Definition at line 945 of file RockRebuild.cc.
References SBufStream::buf(), Debug::Extra(), and opt_store_doublecheck.
registerRunner()
void IndependentRunner::registerRunner () protected inherited
Definition at line 104 of file RunnersRegistry.cc.
References FindRunners(), and RegisterRunner_().
Referenced by ConnStateData::ConnStateData(), IdleConnList::IdleConnList(), and Rebuild().
RegisterWithCacheManager()
void AsyncJob::RegisterWithCacheManager () static inherited
Definition at line 215 of file AsyncJob.cc.
References Mgr::RegisterAction(), and AsyncJob::ReportAllJobs().
Referenced by mainInitialize().
ReportAllJobs()
void AsyncJob::ReportAllJobs (StoreEntry * e) static protected inherited
Definition at line 198 of file AsyncJob.cc.
References AllJobs().
Referenced by AsyncJob::RegisterWithCacheManager().
sameEntry()
bool Rock::Rebuild::sameEntry (const sfileno fileno, const DbCellHeader & header) const private
Definition at line 879 of file RockRebuild.cc.
References Rock::DbCellHeader::key, and Ipc::StoreMapAnchor::sameKey().
start()
void Rock::Rebuild::start () override protected virtual
Reimplemented from AsyncJob.
Definition at line 341 of file RockRebuild.cc.
References assert, counts, current_time, debugs, file_open(), Important, O_BINARY, SM_PAGE_SIZE, StoreRebuildData::updateStartTime(), and xread().
Start() [1/2]
void AsyncJob::Start (const Pointer & job) static inherited
Promises to start the configured job (eventually). The job is deemed to be running asynchronously beyond this point, so the caller should only access the job object via AsyncCalls rather than directly.
swanSong() is only called for jobs for which this method has returned successfully (i.e. without throwing).
Definition at line 37 of file AsyncJob.cc.
References CallJobHere, AsyncJob::start(), and AsyncJob::started_.
Referenced by Ftp::Server::AcceptCtrlConnection(), clientListenerConnectionOpened(), Ipc::Coordinator::handleCacheMgrRequest(), Ipc::Coordinator::handleSnmpRequest(), httpAccept(), httpsAccept(), httpStart(), idnsInitVC(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Log::TcpLogger::Open(), peerProbeConnect(), Mgr::FunAction::respond(), Mgr::InfoAction::respond(), Ipc::SendMessage(), Mgr::Inquirer::sendResponse(), snmpConstructReponse(), SquidMain(), CacheManager::start(), Adaptation::AccessCheck::Start(), Start(), JobWaitBase::start_(), BodyPipe::startAutoConsumptionIfNeeded(), Ftp::StartGateway(), Ftp::StartRelay(), and Rock::SwapDir::updateHeaders().
Start() [2/2]
bool Rock::Rebuild::Start (SwapDir & dir) static
starts indexing the given cache_dir if that indexing is necessary
Returns
whether the indexing was necessary (and, hence, started)
Definition at line 281 of file RockRebuild.cc.
References debugs, Rock::SwapDir::filePath, Store::Disk::index, Store::Disk::path, shm_old, and AsyncJob::Start().
Referenced by Rock::SwapDir::ioCompletedNotification().
startNewEntry()
void Rock::Rebuild::startNewEntry (const sfileno fileno, const SlotId slotId, const DbCellHeader & header) private
Definition at line 859 of file RockRebuild.cc.
References assert, Rock::LoadingEntry::leIgnored, and Rock::LoadingEntry::state().
startReconfigure()
virtual void RegisteredRunner::startReconfigure () inline virtual inherited
Called after receiving a reconfigure request and before parsing squid.conf. Meant for modules that need to prepare for their configuration being changed [outside their control]. The changes end with the syncConfig() event.
Reimplemented in Dns::ConfigRr, HtcpRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 67 of file RunnersRegistry.h.
Referenced by mainReconfigureStart().
startShutdown()
void Rock::Rebuild::startShutdown () override protected virtual
Called after receiving a shutdown request and before stopping the main loop. At least one main loop iteration is guaranteed after this call. Meant for cleanup and state saving that may require other modules.
Reimplemented from RegisteredRunner.
Definition at line 334 of file RockRebuild.cc.
status()
const char * AsyncJob::status () const protected virtual inherited
for debugging, starts with space
Reimplemented in Adaptation::Ecap::XactionRep, Adaptation::Icap::ServiceRep, Adaptation::Icap::Xaction, Adaptation::Initiate, Http::Tunneler, Comm::TcpAcceptor, HappyConnOpener, Ipc::Inquirer, and Security::PeerConnector.
Definition at line 182 of file AsyncJob.cc.
References MemBuf::append(), Packable::appendf(), MemBuf::content(), MemBuf::reset(), AsyncJob::stopReason, and MemBuf::terminate().
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), Adaptation::Initiate::status(), and Comm::TcpAcceptor::status().
steps()
void Rock::Rebuild::steps () private
Definition at line 409 of file RockRebuild.cc.
Steps()
void Rock::Rebuild::Steps (void * data) static private
Definition at line 402 of file RockRebuild.cc.
References CallJobHere.
Referenced by checkpoint().
swanSong()
void Rock::Rebuild::swanSong () override protected virtual
Reimplemented from AsyncJob.
Definition at line 692 of file RockRebuild.cc.
References counts, debugs, Store::Controller::store_dirs_rebuilding, and storeRebuildComplete().
syncConfig()
virtual void RegisteredRunner::syncConfig () inline virtual inherited
Called after parsing squid.conf during reconfiguration. Meant for adjusting the module state based on configuration changes.
Reimplemented in Auth::CredentialCacheRr, CarpRr, HtcpRr, PeerSourceHashRr, PeerUserHashRr, PeerPoolMgrsRr, SnmpRr, WccpRr, and Wccp2Rr.
Definition at line 71 of file RunnersRegistry.h.
Referenced by mainReconfigureFinish().
toCbdata()
virtual void * CbdataParent::toCbdata () pure virtual inherited
Referenced by AsyncJob::callException(), and AsyncJob::callStart().
unregisterRunner()
void IndependentRunner::unregisterRunner () protected inherited
Definition at line 96 of file RunnersRegistry.cc.
References FindRunners().
Referenced by IndependentRunner::~IndependentRunner().
useConfig()
virtual void RegisteredRunner::useConfig () inline virtual inherited
Called after claimMemoryNeeds(). Meant for activating modules and features using a finalized configuration with known memory requirements.
Reimplemented in CarpRr, ClientDbRr, HtcpRr, SharedMemPagesRr, Ipc::Mem::RegisteredRunner, MemStoreRr, PeerSourceHashRr, PeerUserHashRr, PeerPoolMgrsRr, SharedSessionCacheRr, SnmpRr, TransientsRr, WccpRr, and Wccp2Rr.
Definition at line 60 of file RunnersRegistry.h.
Referenced by RunConfigUsers().
useNewSlot()
void Rock::Rebuild::useNewSlot (const SlotId slotId, const DbCellHeader & header) private
Definition at line 889 of file RockRebuild.cc.
References assert, counts, debugs, StoreRebuildData::dupcount, Rock::DbCellHeader::firstSlot, Rock::DbCellHeader::key, Rock::LoadingEntry::leCorrupted, Rock::LoadingEntry::leEmpty, Rock::LoadingEntry::leIgnored, Rock::LoadingEntry::leLoaded, Rock::LoadingEntry::leLoading, Rock::DbCellHeader::payloadSize, and Rock::LoadingEntry::state().
validateOneEntry()
void Rock::Rebuild::validateOneEntry (const sfileno fileNo) private
Definition at line 644 of file RockRebuild.cc.
References Rock::LoadingEntry::leCorrupted, Rock::LoadingEntry::leEmpty, Rock::LoadingEntry::leIgnored, Rock::LoadingEntry::leLoaded, Rock::LoadingEntry::leLoading, and Rock::LoadingEntry::state().
validateOneSlot()
void Rock::Rebuild::validateOneSlot (const SlotId slotId) private
Definition at line 662 of file RockRebuild.cc.
References Rock::LoadingSlot::finalized(), Rock::LoadingSlot::freed(), Rock::LoadingSlot::mapped(), and Must.
validationSteps()
void Rock::Rebuild::validationSteps () private
Definition at line 561 of file RockRebuild.cc.
References counts, current_time, debugs, getCurrentTime(), opt_foreground_rebuild, tvSubMsec(), and StoreRebuildData::validations.
Member Data Documentation
buf
MemBuf Rock::Rebuild::buf private
Definition at line 123 of file RockRebuild.h.
counts
StoreRebuildData& Rock::Rebuild::counts private
Definition at line 125 of file RockRebuild.h.
dbEntryLimit
int64_t Rock::Rebuild::dbEntryLimit private
Definition at line 117 of file RockRebuild.h.
Referenced by Rebuild().
dbOffset
int64_t Rock::Rebuild::dbOffset private
Definition at line 120 of file RockRebuild.h.
dbSize
int64_t Rock::Rebuild::dbSize private
Definition at line 114 of file RockRebuild.h.
Referenced by Rebuild().
dbSlotLimit
int64_t Rock::Rebuild::dbSlotLimit private
Definition at line 116 of file RockRebuild.h.
Referenced by Rebuild().
dbSlotSize
int Rock::Rebuild::dbSlotSize private
Definition at line 115 of file RockRebuild.h.
Referenced by Rebuild().
fd
int Rock::Rebuild::fd private
Definition at line 119 of file RockRebuild.h.
id
const InstanceId<AsyncJob> AsyncJob::id inherited
Definition at line 75 of file AsyncJob.h.
inCall
AsyncCall::Pointer AsyncJob::inCall protected inherited
Definition at line 86 of file AsyncJob.h.
Referenced by AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::canBeCalled(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
loadingPos
int64_t Rock::Rebuild::loadingPos private
Definition at line 121 of file RockRebuild.h.
parts
LoadingParts* Rock::Rebuild::parts private
Definition at line 110 of file RockRebuild.h.
resuming
const bool Rock::Rebuild::resuming private
whether we have started indexing this cache_dir before, presumably in the previous process performing the same-kid role
Definition at line 129 of file RockRebuild.h.
sd
SwapDir* Rock::Rebuild::sd private
Definition at line 109 of file RockRebuild.h.
Referenced by Rebuild().
started_
bool AsyncJob::started_ = false protected inherited
Definition at line 88 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), AsyncJob::callEnd(), and AsyncJob::Start().
stats
Ipc::Mem::Pointer<Stats> Rock::Rebuild::stats private
Definition at line 112 of file RockRebuild.h.
stopReason
const char* AsyncJob::stopReason protected inherited
Definition at line 84 of file AsyncJob.h.
Referenced by AsyncJob::deleteThis(), AsyncJob::done(), AsyncJob::mustStop(), AsyncJob::status(), and HappyConnOpener::status().
swanSang_
bool AsyncJob::swanSang_ = false protected inherited
Definition at line 89 of file AsyncJob.h.
Referenced by AsyncJob::~AsyncJob(), and AsyncJob::callEnd().
typeName
const char* AsyncJob::typeName protected inherited
Definition at line 85 of file AsyncJob.h.
Referenced by AsyncJob::AsyncJob(), Adaptation::Icap::Xaction::Xaction(), AsyncJob::~AsyncJob(), AsyncJob::callEnd(), AsyncJob::callStart(), AsyncJob::deleteThis(), and AsyncJob::mustStop().
validationPos
int64_t Rock::Rebuild::validationPos private
Definition at line 122 of file RockRebuild.h.
The documentation for this class was generated from the following files:
squid/src/fs/rock/RockRebuild.h
squid/src/fs/rock/RockRebuild.cc