Squid Web Cache: TestMath Class Reference
TestMath Class Reference
Protected Member Functions
void testNaturalSum ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestMath)
CPPUNIT_TEST (testNaturalSum)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 14 of file testMath.cc.
Member Function Documentation
CPPUNIT_TEST()
TestMath::CPPUNIT_TEST (testNaturalSum) private
CPPUNIT_TEST_SUITE()
TestMath::CPPUNIT_TEST_SUITE (TestMath) private
CPPUNIT_TEST_SUITE_END()
TestMath::CPPUNIT_TEST_SUITE_END () private
testNaturalSum()
void TestMath::testNaturalSum () protected
Definition at line 196 of file testMath.cc.
References GoodSum(), max64s, max64u, max8s, max8u, min64s, min8s, one64s, one64u, one8s, one8u, SetToNaturalSumOrMax(), TestOverflowForEitherSummationType(), TestSuccessForFirstSummationType(), zero64s, zero64u, zero8s, and zero8u.
The documentation for this class was generated from the following file:
squid/src/tests/testMath.cc