Squid Web Cache: DelayUser Class Reference
DelayUser Class Reference
Squid Components » Delay Pools API
#include <DelayUser.h>
Classes
class Id
Public Types
typedef RefCount< DelayUser > Pointer
Public Member Functions
DelayUser ()
~DelayUser () override
void stats (StoreEntry *sentry) override
void dump (StoreEntry *entry) const override
void update (int incr) override
void parse () override
DelayIdComposite::Pointer id (CompositeSelectionDetails &) override
void delayRead (const AsyncCallPointer &)
Protected Member Functions
void kickReads ()
Protected Attributes
DelayedAsyncCalls deferredReads
Private Member Functions
MEMPROXY_CLASS (DelayUser)
Private Attributes
DelaySpec spec
Splay< DelayUserBucket::Pointer > buckets
Friends
class Id
Detailed Description
Definition at line 40 of file DelayUser.h.
Member Typedef Documentation
Pointer
typedef RefCount<DelayUser> DelayUser::Pointer
Definition at line 45 of file DelayUser.h.
Constructor & Destructor Documentation
DelayUser()
DelayUser::DelayUser ()
Definition at line 21 of file DelayUser.cc.
References DelayPools::registerForUpdates().
~DelayUser()
DelayUser::~DelayUser () override
Definition at line 28 of file DelayUser.cc.
References buckets, DelayUserFree, and DelayPools::deregisterForUpdates().
Member Function Documentation
delayRead()
void CompositePoolNode::delayRead (const AsyncCallPointer & aRead) inherited
Definition at line 80 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::delay().
Referenced by Aggregate::AggregateId::delayRead().
dump()
void DelayUser::dump (StoreEntry * entry) const override virtual
Implements CompositePoolNode.
Definition at line 80 of file DelayUser.cc.
References DelaySpec::dump(), and spec.
id()
DelayIdComposite::Pointer DelayUser::id (CompositePoolNode::CompositeSelectionDetails & details) override virtual
Implements CompositePoolNode.
Definition at line 115 of file DelayUser.cc.
References debugs, Auth::UserRequest::user(), and CompositePoolNode::CompositeSelectionDetails::user.
kickReads()
void CompositePoolNode::kickReads () protected inherited
Definition at line 88 of file DelayPool.cc.
References CompositePoolNode::deferredReads, and DelayedAsyncCalls::schedule().
Referenced by Aggregate::update(), DelayTagged::update(), and DelayVector::update().
MEMPROXY_CLASS()
DelayUser::MEMPROXY_CLASS (DelayUser) private
parse()
void DelayUser::parse () override virtual
Implements CompositePoolNode.
Definition at line 109 of file DelayUser.cc.
References DelaySpec::parse(), and spec.
stats()
void DelayUser::stats (StoreEntry * sentry) override virtual
Implements CompositePoolNode.
Definition at line 60 of file DelayUser.cc.
References buckets, DelaySpec::restore_bps, spec, DelaySpec::stats(), and storeAppendPrintf().
update()
void DelayUser::update (int incr) override virtual
Implements CompositePoolNode.
Definition at line 101 of file DelayUser.cc.
References buckets, and spec.
Friends And Related Symbol Documentation
Id
friend class Id friend
Definition at line 73 of file DelayUser.h.
Member Data Documentation
buckets
Splay<DelayUserBucket::Pointer> DelayUser::buckets private
Definition at line 76 of file DelayUser.h.
Referenced by DelayUser::Id::Id(), ~DelayUser(), stats(), and update().
deferredReads
DelayedAsyncCalls CompositePoolNode::deferredReads protected inherited
Definition at line 60 of file CompositePoolNode.h.
Referenced by CompositePoolNode::delayRead(), and CompositePoolNode::kickReads().
spec
DelaySpec DelayUser::spec private
Definition at line 75 of file DelayUser.h.
Referenced by DelayUser::Id::Id(), dump(), parse(), stats(), and update().
The documentation for this class was generated from the following files:
squid/src/DelayUser.h
squid/src/DelayUser.cc