Squid Web Cache: MyTestProgram Class Reference
MyTestProgram Class Reference
customizes our test setup
Public Member Functions
void startup () override
void startup () override
void startup () override
void startup () override
void startup () override
void startup () override
void startup () override
void startup () override
void startup () override
void startup () override
void startup () override
int run (int argc, char *argv[])
Private Member Functions
bool runTests ()
Detailed Description
Definition at line 58 of file testACLMaxUserIP.cc.
Member Function Documentation
run()
int TestProgram::run (int argc, char * argv[]) inherited
Implements main(), combining all the steps. Must be called from main().
Returns
desired main() result.
Definition at line 44 of file unitTestMain.h.
References Debug::Levels, TestProgram::runTests(), and TestProgram::startup().
Referenced by main().
runTests()
bool TestProgram::runTests () private inherited
runs all tests registered with CPPUNIT_TEST_SUITE_REGISTRATION() calls
Returns
whether all tests were successful
Definition at line 58 of file unitTestMain.h.
Referenced by TestProgram::run().
startup() [1/11]
void MyTestProgram::startup () override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
Definition at line 66 of file testACLMaxUserIP.cc.
References Acl::RegisterMaker().
startup() [2/11]
void MyTestProgram::startup () override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
startup() [3/11]
void MyTestProgram::startup () inline override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
Definition at line 386 of file testClpMap.cc.
References squid_curtime.
startup() [4/11]
void MyTestProgram::startup () override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
startup() [5/11]
void MyTestProgram::startup () inline override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
Definition at line 177 of file testEvent.cc.
References Mem::Init().
startup() [6/11]
void MyTestProgram::startup () override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
startup() [7/11]
void MyTestProgram::startup () override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
startup() [8/11]
void MyTestProgram::startup () override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
startup() [9/11]
void MyTestProgram::startup () inline override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
Definition at line 101 of file testStore.cc.
References Mem::Init().
startup() [10/11]
void MyTestProgram::startup () inline override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
Definition at line 90 of file testString.cc.
References Mem::Init().
startup() [11/11]
void MyTestProgram::startup () override virtual
Runs before all tests. Does nothing by default.
Reimplemented from TestProgram.
The documentation for this class was generated from the following files:
squid/src/tests/testACLMaxUserIP.cc
squid/src/tests/testCacheManager.cc
squid/src/tests/testClpMap.cc
squid/src/tests/testDiskIO.cc
squid/src/tests/testEvent.cc
squid/src/tests/testHttpReply.cc
squid/src/tests/testHttpRequest.cc
squid/src/tests/testRock.cc
squid/src/tests/testStore.cc
squid/src/tests/testString.cc
squid/src/tests/testURL.cc