Squid Web Cache: ErrorState Class Reference
ErrorState Class Reference
Squid Components » Error Pages API
#include <errorpage.h>
Public Member Functions
CBDATA_DECL_ (ErrorState, noexcept)
ErrorState (err_type type, Http::StatusCode, HttpRequest *request, const AccessLogEntryPointer &al)
creates an error of type other than ERR_RELAY_REMOTE
ErrorState ()=delete
ErrorState (HttpRequest *request, HttpReply *, const AccessLogEntryPointer &)
creates an ERR_RELAY_REMOTE error
~ErrorState ()
HttpReply * BuildHttpReply (void)
void detailError (const ErrorDetail::Pointer &dCode)
set error type-specific detail code
void validate ()
ensures that a future BuildHttpReply() is likely to succeed
Static Public Member Functions
static ErrorState * NewForwarding (err_type, HttpRequestPointer &, const AccessLogEntryPointer &)
Creates a general request forwarding error with the right http_status.
Public Attributes
SBuf inputLocation
the source of the error template (for reporting purposes)
err_type type = ERR_NONE
int page_id = ERR_NONE
char * err_language = nullptr
Http::StatusCode httpStatus = Http::scNone
Auth::UserRequest::Pointer auth_user_request
HttpRequestPointer request
char * url = nullptr
int xerrno = 0
std::optional< SBuf > dnsError
DNS lookup error message.
time_t ttl = 0
Ip::Address src_addr
char * redirect_url = nullptr
ERCB * callback
void * callback_data = nullptr
struct {
wordlist * server_msg = nullptr
char * request = nullptr
char * reply = nullptr
char * cwd_msg = nullptr
MemBuf * listing = nullptr
} ftp
char * err_msg = nullptr
AccessLogEntryPointer ale
transaction details (or nil)
ErrorDetail::Pointer detail
HttpReplyPointer response_
Private Types
typedef ErrorPage::Build Build
Private Member Functions
ErrorState (err_type, const AccessLogEntryPointer &)
initializations shared by public constructors
SBuf buildBody ()
locates the right error page template for this error and compiles it
SBuf compileBody (const char *text, bool allowRecursion)
void compileLegacyCode (Build &build)
compile a single-letter code like D
void compileLogformatCode (Build &build)
compile @Squid{code} sequence containing a single logformat code
SBuf compile (const char *input, bool building_deny_info_url, bool allowRecursion)
void noteBuildError (const char *const msg, const char *const errorLocation)
void bypassBuildErrorXXX (const char *const msg, const char *const errorLocation)
int Dump (MemBuf *mb)
void noteBuildError_ (const char *msg, const char *errorLocation, bool forceBypass)
Static Private Attributes
static const SBuf LogformatMagic
marks each embedded logformat entry
Detailed Description
Definition at line 88 of file errorpage.h.
Member Typedef Documentation
Build
typedef ErrorPage::Build ErrorState::Build private
Definition at line 120 of file errorpage.h.
Constructor & Destructor Documentation
ErrorState() [1/4]
ErrorState::ErrorState (err_type type, Http::StatusCode status, HttpRequest * request, const AccessLogEntryPointer & al)
Definition at line 706 of file errorpage.cc.
References HttpRequest::client_addr, debugs, ERR_MAX, ErrorDynamicPages, httpStatus, page_id, request, Http::scNone, and src_addr.
ErrorState() [2/4]
ErrorState::ErrorState () delete
Referenced by NewForwarding().
ErrorState() [3/4]
ErrorState::ErrorState (HttpRequest * request, HttpReply * errorReply, const AccessLogEntryPointer & anAle)
Definition at line 722 of file errorpage.cc.
References HttpRequest::client_addr, debugs, httpStatus, Must, request, response_, HttpReply::sline, src_addr, and Http::StatusLine::status().
~ErrorState()
ErrorState::~ErrorState ()
Definition at line 834 of file errorpage.cc.
References Config, debugs, err_language, err_msg, SquidConfig::errorDefaultLanguage, ftp, redirect_url, safe_free, url, and wordlistDestroy().
ErrorState() [4/4]
ErrorState::ErrorState (err_type t, const AccessLogEntryPointer & anAle) private
Definition at line 698 of file errorpage.cc.
Member Function Documentation
buildBody()
SBuf ErrorState::buildBody () private
error_directory option in squid.conf overrides translations. Custom errors are always found either in error_directory or the templates directory. Otherwise locate the Accept-Language header
If client-specific error templates are not enabled or available. fall back to the old style squid.conf settings.
Definition at line 1392 of file errorpage.cc.
References assert, compileBody(), Config, debugs, err_language, ERR_MAX, ERR_NONE, err_type_str, error_page_count, error_text, SquidConfig::errorDefaultLanguage, SquidConfig::errorDirectory, TemplateFile::filename, RefCount< C >::getRaw(), inputLocation, TemplateFile::language(), TemplateFile::loadFor(), page_id, request, safe_free, ErrorPageFile::text(), and xstrdup.
Referenced by BuildHttpReply(), and compileLegacyCode().
BuildHttpReply()
HttpReply * ErrorState::BuildHttpReply (void)
Allocates and initializes an error response
Definition at line 1307 of file errorpage.cc.
References ale, HttpReply::body, buildBody(), compile(), Config, Http::CONTENT_LANGUAGE, detail, err_language, HttpRequest::error, SquidConfig::errorDirectory, errorPageName(), RefCount< C >::getRaw(), Http::Message::header, Http::Message::http_ver, httpHeaderPutStrf(), httpStatus, ErrorPage::IsDenyInfoUri(), Http::LOCATION, HttpRequest::method, Http::METHOD_GET, Http::METHOD_HEAD, SysErrorDetail::NewIfAny(), page_id, Http::ProtocolVersion(), HttpHeader::putStr(), request, response_, Http::scFound, Http::scTemporaryRedirect, HttpBody::set(), HttpReply::setHeaders(), type, Error::update(), AccessLogEntry::updateError(), HttpHeader::updateOrAddStr(), Http::VARY, Http::X_SQUID_ERROR, and xerrno.
Referenced by Ftp::Gateway::completedListing(), errorAppendEntry(), errorSend(), Ftp::Gateway::ftpAuthRequired(), ftpSendReply(), Ftp::Gateway::loginFailed(), Mgr::Inquirer::start(), and CacheManager::start().
bypassBuildErrorXXX()
void ErrorState::bypassBuildErrorXXX (const char *const msg, const char *const errorLocation) inline private
Note a compile() error but do not throw for backwards compatibility with older configurations that may have such errors. Should eventually be replaced with noteBuildError().
Parameters
msg description of what went wrong
errorLocation approximate start of the problematic input
Definition at line 158 of file errorpage.h.
References noteBuildError_().
Referenced by compileLegacyCode().
CBDATA_DECL_()
ErrorState::CBDATA_DECL_ (ErrorState , noexcept)
compile()
SBuf ErrorState::compile (const char * input, bool building_deny_info_url, bool allowRecursion) private
replaces all legacy and logformat codes in the given input
Parameters
input the template text to be converted
building_deny_info_url whether input is a deny_info URL parameter
allowRecursion whether to compile codes which produce codes
Returns
the given input with all codes substituted
Definition at line 1434 of file errorpage.cc.
References ErrorPage::Build::allowRecursion, SBuf::append(), assert, ErrorPage::Build::building_deny_info_url, SBuf::cmp(), compileLegacyCode(), compileLogformatCode(), ErrorPage::Build::input, SBuf::length(), LogformatMagic, and ErrorPage::Build::output.
Referenced by BuildHttpReply(), compileBody(), and validate().
compileBody()
SBuf ErrorState::compileBody (const char * text, bool allowRecursion) private
compiles error page or error detail template (i.e. anything but deny_url)
Parameters
input the template text to be compiled
allowRecursion whether to compile codes which produce codes
Definition at line 1428 of file errorpage.cc.
References compile().
Referenced by buildBody(), compileLegacyCode(), and validate().
compileLegacyCode()
void ErrorState::compileLegacyCode (Build & build) private
Definition at line 949 of file errorpage.cc.
References AnyP::Uri::absolutePath(), SquidConfig::adminEmail, ErrorPage::Build::allowRecursion, MemBuf::append(), SBuf::append(), Packable::appendf(), assert, auth_user_request, HttpRequest::auth_user_request, ErrorDetail::brief(), MemBuf::buf, buildBody(), ErrorPage::Build::building_deny_info_url, bypassBuildErrorXXX(), compileBody(), Config, MemBuf::content(), MemBuf::contentSize(), DBG_CRITICAL, debugs, Auth::UserRequest::denyMessage(), detail, dnsError, Dump(), HttpRequest::effectiveRequestUri(), SquidConfig::emailErrData, err_msg, ERR_SQUID_SIGNATURE, SquidConfig::errHtmlText, error_stylesheet, errorPageName(), HttpRequest::extacl_message, external_acl_message, FindListeningPortAddress(), Time::FormatHttpd(), Time::FormatRfc1123(), ftp, getMyHostname(), getMyPort(), RefCount< C >::getRaw(), AnyP::Uri::getScheme(), HttpRequest::hier, AnyP::Uri::host(), HierarchyLogEntry::host, html_quote(), AnyP::UriScheme::image(), HttpRequestMethod::image(), ErrorPage::Build::input, SBuf::length(), MAX_IPSTRLEN, HttpRequest::method, SquidConfig::onoff, ErrorPage::Build::output, HttpRequest::pack(), page_id, AnyP::Uri::port(), SBuf::rawContent(), Comm::Connection::remote, request, MemBuf::reset(), rfc1738_escape_part, squid_curtime, src_addr, strerror(), HierarchyLogEntry::tcpServer, String::termedBuf(), Ip::Address::toStr(), type, url, HttpRequest::url, urlCanonicalFakeHttps(), Ftp::UrlWith2f(), Auth::UserRequest::username(), ErrorDetail::verbose(), visible_appname_string, wordlistCat(), and xerrno.
Referenced by compile().
compileLogformatCode()
void ErrorState::compileLogformatCode (Build & build) private
Definition at line 913 of file errorpage.cc.
References ale, SBuf::append(), Format::AssembleOne(), assert, SBuf::cmp(), MemBuf::content(), MemBuf::contentSize(), ErrorPage::Build::input, SBuf::length(), LogformatMagic, noteBuildError(), ErrorPage::Build::output, MemBuf::reset(), and TexcHere.
Referenced by compile().
detailError()
void ErrorState::detailError (const ErrorDetail::Pointer & dCode) inline
Definition at line 111 of file errorpage.h.
References detail.
Referenced by ClientHttpRequest::calloutsError(), ftpSendReply(), Security::PeerConnector::sslCrtvdHandleReply(), and FwdState::updateAleWithFinalError().
Dump()
int ErrorState::Dump (MemBuf * mb) private
CacheManager / Debug dump of the ErrorState object. Writes output into the given MemBuf.
Return values
0 successful completion.
Definition at line 852 of file errorpage.cc.
References auth_user_request, SBufStream::buf(), MemBuf::content(), AsList< Container >::delimitedBy(), Auth::UserRequest::denyMessage(), dnsError, AnyP::Uri::Encode(), errorPageName(), Time::FormatRfc1123(), ftp, getMyHostname(), RefCount< C >::getRaw(), HttpRequest::hier, HierarchyLogEntry::host, MemBuf::init(), HttpRequest::pack(), request, CharacterSet::RFC3986_UNRESERVED(), squid_curtime, src_addr, strerror(), type, and xerrno.
Referenced by compileLegacyCode().
NewForwarding()
ErrorState * ErrorState::NewForwarding (err_type type, HttpRequestPointer & request, const AccessLogEntryPointer & ale) static
Definition at line 691 of file errorpage.cc.
References ErrorState(), ale, HttpRequest::flags, RefCount< C >::getRaw(), RequestFlags::needValidation, request, Http::scGatewayTimeout, Http::scServiceUnavailable, and type.
Referenced by ConnStateData::BorrowPinnedConnection(), ConnStateData::borrowPinnedConnection(), and Security::PeerConnector::noteNegotiationError().
noteBuildError()
void ErrorState::noteBuildError (const char *const msg, const char *const errorLocation) inline private
React to a compile() error, throwing if buildContext allows.
Parameters
msg description of what went wrong
errorLocation approximate start of the problematic input
Definition at line 149 of file errorpage.h.
References noteBuildError_().
Referenced by compileLogformatCode().
noteBuildError_()
void ErrorState::noteBuildError_ (const char * msg, const char * errorLocation, bool forceBypass) private
react to a compile() error
Parameters
msg description of what went wrong
errorLocation approximate start of the problematic input
forceBypass whether detection of this error was introduced late, after old configurations containing this error could have been successfully validated and deployed (i.e. the admin may not be able to fix this newly detected but old problem quickly)
Definition at line 1470 of file errorpage.cc.
References DBG_CRITICAL, DBG_DATA, debugs, inputLocation, page_id, reconfiguring, starting_up, TexcHere, and ToSBuf().
Referenced by bypassBuildErrorXXX(), and noteBuildError().
validate()
void ErrorState::validate ()
Definition at line 1295 of file errorpage.cc.
References assert, compile(), compileBody(), ERR_NONE, error_page_count, error_text, ErrorPage::IsDenyInfoUri(), and page_id.
Referenced by ErrorPage::ValidateStaticError().
Member Data Documentation
ale
AccessLogEntryPointer ErrorState::ale
Definition at line 198 of file errorpage.h.
Referenced by BuildHttpReply(), compileLogformatCode(), and NewForwarding().
auth_user_request
Auth::UserRequest::Pointer ErrorState::auth_user_request
Definition at line 175 of file errorpage.h.
Referenced by ClientHttpRequest::calloutsError(), ClientRequestContext::clientAccessCheckDone(), compileLegacyCode(), and Dump().
callback
ERCB* ErrorState::callback
Definition at line 185 of file errorpage.h.
Referenced by errorSendComplete(), and TunnelStateData::sendError().
callback_data
void* ErrorState::callback_data = nullptr
Definition at line 186 of file errorpage.h.
Referenced by errorSendComplete(), TunnelStateData::sendError(), and clientReplyContext::setReplyToError().
cwd_msg
char* ErrorState::cwd_msg = nullptr
Definition at line 192 of file errorpage.h.
Referenced by Ftp::Gateway::completedListing().
detail
ErrorDetail::Pointer ErrorState::detail
type-specific detail about the transaction error; overwrites xerrno;
Definition at line 204 of file errorpage.h.
Referenced by BuildHttpReply(), compileLegacyCode(), detailError(), and FwdState::updateAleWithFinalError().
dnsError
std::optional<SBuf> ErrorState::dnsError
Definition at line 180 of file errorpage.h.
Referenced by compileLegacyCode(), Dump(), and PeerSelector::noteIps().
err_language
char* ErrorState::err_language = nullptr
Definition at line 172 of file errorpage.h.
Referenced by ~ErrorState(), buildBody(), and BuildHttpReply().
err_msg
char* ErrorState::err_msg = nullptr
Definition at line 196 of file errorpage.h.
Referenced by ~ErrorState(), and compileLegacyCode().
[struct]
struct { ... } ErrorState::ftp
Referenced by ~ErrorState(), compileLegacyCode(), Ftp::Gateway::completedListing(), Dump(), Ftp::Client::failed(), and ftpSendReply().
httpStatus
Http::StatusCode ErrorState::httpStatus = Http::scNone
Definition at line 173 of file errorpage.h.
Referenced by ErrorState(), ErrorState(), BuildHttpReply(), Ftp::Client::failed(), operator<<(), TunnelStateData::retryOrBail(), TunnelStateData::sendError(), clientReplyContext::setReplyToError(), and ClientRequestContext::sslBumpAccessCheck().
inputLocation
SBuf ErrorState::inputLocation
Definition at line 117 of file errorpage.h.
Referenced by buildBody(), noteBuildError_(), and ErrorPage::ValidateStaticError().
listing
MemBuf* ErrorState::listing = nullptr
Definition at line 193 of file errorpage.h.
Referenced by Ftp::Gateway::completedListing().
LogformatMagic
const SBuf ErrorState::LogformatMagic static private
Definition at line 211 of file errorpage.h.
Referenced by compile(), and compileLogformatCode().
page_id
int ErrorState::page_id = ERR_NONE
Definition at line 171 of file errorpage.h.
Referenced by ErrorState(), buildBody(), BuildHttpReply(), compileLegacyCode(), errorAppendEntry(), noteBuildError_(), Http::operator<<(), and validate().
redirect_url
char* ErrorState::redirect_url = nullptr
Definition at line 184 of file errorpage.h.
Referenced by ~ErrorState().
reply
char* ErrorState::reply = nullptr
Definition at line 191 of file errorpage.h.
Referenced by Ftp::Client::failed(), and ftpSendReply().
request [1/2]
HttpRequestPointer ErrorState::request
Definition at line 177 of file errorpage.h.
Referenced by ErrorState(), ErrorState(), buildBody(), BuildHttpReply(), compileLegacyCode(), Dump(), errorAppendEntry(), FwdState::fail(), Ftp::Client::failed(), ftpSendReply(), and NewForwarding().
request [2/2]
char* ErrorState::request = nullptr
Definition at line 190 of file errorpage.h.
response_
HttpReplyPointer ErrorState::response_
Definition at line 206 of file errorpage.h.
Referenced by ErrorState(), and BuildHttpReply().
server_msg
wordlist* ErrorState::server_msg = nullptr
Definition at line 189 of file errorpage.h.
Referenced by Ftp::Gateway::completedListing(), and Ftp::Client::failed().
src_addr
Ip::Address ErrorState::src_addr
Definition at line 183 of file errorpage.h.
Referenced by ErrorState(), ErrorState(), compileLegacyCode(), and Dump().
ttl
time_t ErrorState::ttl = 0
Definition at line 181 of file errorpage.h.
type
err_type ErrorState::type = ERR_NONE
Definition at line 170 of file errorpage.h.
Referenced by BuildHttpReply(), compileLegacyCode(), Dump(), FwdState::fail(), Ftp::Client::failed(), NewForwarding(), operator<<(), FwdState::reactToZeroSizeObject(), ClientRequestContext::sslBumpAccessCheck(), and FwdState::updateAleWithFinalError().
url
char* ErrorState::url = nullptr
Definition at line 178 of file errorpage.h.
Referenced by ~ErrorState(), compileLegacyCode(), CacheManager::start(), and urnHandleReply().
xerrno
int ErrorState::xerrno = 0
Definition at line 179 of file errorpage.h.
Referenced by BuildHttpReply(), compileLegacyCode(), Dump(), Ftp::Client::failed(), HappyConnOpener::handleConnOpenerAnswer(), Client::sentRequestBody(), and FwdState::updateAleWithFinalError().
The documentation for this class was generated from the following files:
squid/src/errorpage.h
squid/src/errorpage.cc