Squid Web Cache: StoreSearch Class Reference
StoreSearch Class Reference abstract
#include <StoreSearch.h>
Public Member Functions
StoreSearch ()
StoreSearch (StoreSearch const &)
~StoreSearch () override
virtual void next (void(callback)(void *cbdata), void *cbdata)=0
virtual bool next ()=0
virtual bool error () const =0
virtual bool isDone () const =0
virtual StoreEntry * currentItem ()=0
Detailed Description
Definition at line 15 of file StoreSearch.h.
Constructor & Destructor Documentation
StoreSearch() [1/2]
StoreSearch::StoreSearch () inline
Definition at line 19 of file StoreSearch.h.
StoreSearch() [2/2]
StoreSearch::StoreSearch (StoreSearch const &)
~StoreSearch()
StoreSearch::~StoreSearch () inline override
Definition at line 22 of file StoreSearch.h.
Member Function Documentation
currentItem()
virtual StoreEntry * StoreSearch::currentItem () pure virtual
Implemented in Store::LocalSearch.
Referenced by statObjects(), storeCleanup(), storeDigestRebuildStep(), TestStoreController::testSearch(), TestStoreHashIndex::testSearch(), and TestUfs::testUfsSearch().
error()
virtual bool StoreSearch::error () const pure virtual
Implemented in Store::LocalSearch.
Referenced by TestStoreController::testSearch(), TestStoreHashIndex::testSearch(), and TestUfs::testUfsSearch().
isDone()
virtual bool StoreSearch::isDone () const pure virtual
Implemented in Store::LocalSearch.
Referenced by statObjects(), storeCleanup(), storeDigestRebuildStep(), TestStoreController::testSearch(), TestStoreHashIndex::testSearch(), and TestUfs::testUfsSearch().
next() [1/2]
virtual bool StoreSearch::next () pure virtual
Implemented in Store::LocalSearch.
next() [2/2]
virtual void StoreSearch::next (void(callback)(void *cbdata) , void * cbdata) pure virtual
Implemented in Store::LocalSearch.
Referenced by storeCleanup(), storeDigestRebuildStep(), TestStoreController::testSearch(), TestStoreHashIndex::testSearch(), and TestUfs::testUfsSearch().
The documentation for this class was generated from the following file:
squid/src/StoreSearch.h