Squid Web Cache: TestEnumIterator Class Reference
TestEnumIterator Class Reference
Protected Member Functions
void testForwardIter ()
void testReverseIter ()
void testBidirectionalIter ()
void testRangeFor ()
void testRangeForRange ()
void testUnsignedEnum ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestEnumIterator)
CPPUNIT_TEST (testForwardIter)
CPPUNIT_TEST (testReverseIter)
CPPUNIT_TEST (testBidirectionalIter)
CPPUNIT_TEST (testRangeFor)
CPPUNIT_TEST (testRangeForRange)
CPPUNIT_TEST (testUnsignedEnum)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 16 of file testEnumIterator.cc.
Member Function Documentation
CPPUNIT_TEST() [1/6]
TestEnumIterator::CPPUNIT_TEST (testBidirectionalIter) private
CPPUNIT_TEST() [2/6]
TestEnumIterator::CPPUNIT_TEST (testForwardIter) private
CPPUNIT_TEST() [3/6]
TestEnumIterator::CPPUNIT_TEST (testRangeFor) private
CPPUNIT_TEST() [4/6]
TestEnumIterator::CPPUNIT_TEST (testRangeForRange) private
CPPUNIT_TEST() [5/6]
TestEnumIterator::CPPUNIT_TEST (testReverseIter) private
CPPUNIT_TEST() [6/6]
TestEnumIterator::CPPUNIT_TEST (testUnsignedEnum) private
CPPUNIT_TEST_SUITE()
TestEnumIterator::CPPUNIT_TEST_SUITE (TestEnumIterator) private
CPPUNIT_TEST_SUITE_END()
TestEnumIterator::CPPUNIT_TEST_SUITE_END () private
testBidirectionalIter()
void TestEnumIterator::testBidirectionalIter () protected
Definition at line 93 of file testEnumIterator.cc.
References EnumRangeT< EnumType >::begin(), EnumRangeT< EnumType >::end(), one, and zero.
testForwardIter()
void TestEnumIterator::testForwardIter () protected
Definition at line 59 of file testEnumIterator.cc.
References EnumRangeT< EnumType >::begin(), four, one, three, two, and zero.
testRangeFor()
void TestEnumIterator::testRangeFor () protected
Definition at line 126 of file testEnumIterator.cc.
testRangeForRange()
void TestEnumIterator::testRangeForRange () protected
Definition at line 139 of file testEnumIterator.cc.
References EnumRange(), four, and two.
testReverseIter()
void TestEnumIterator::testReverseIter () protected
Definition at line 76 of file testEnumIterator.cc.
References four, one, EnumRangeT< EnumType >::rbegin(), three, two, and zero.
testUnsignedEnum()
void TestEnumIterator::testUnsignedEnum () protected
Definition at line 153 of file testEnumIterator.cc.
References EnumRangeT< EnumType >::rend().
The documentation for this class was generated from the following file:
squid/src/tests/testEnumIterator.cc