Squid Web Cache: Fs::Ufs::StoreFSufs< TheSwapDir > Class Template Reference
Fs::Ufs::StoreFSufs< TheSwapDir > Class Template Reference
Storage Filesystems » UFS Storage Filesystem | Storage Filesystems
#include <StoreFSufs.h>
Public Types
typedef std::vector< StoreFileSystem * >::iterator iterator
typedef std::vector< StoreFileSystem * >::const_iterator const_iterator
Public Member Functions
StoreFSufs (char const *DefaultModuleType, char const *label)
~StoreFSufs () override
const char * type () const override
SwapDir * createSwapDir () override
Static Public Member Functions
static StoreFileSystem & GetInstance ()
static void FsAdd (StoreFileSystem &)
static StoreFileSystem * FindByType (const char *type)
static std::vector< StoreFileSystem * > const & FileSystems ()
Protected Attributes
DiskIOModule * IO
char const * moduleName
char const * label
Static Private Member Functions
static std::vector< StoreFileSystem * > & GetFileSystems ()
Static Private Attributes
static std::vector< StoreFileSystem * > * _FileSystems = nullptr
Detailed Description
template<class TheSwapDir>
class Fs::Ufs::StoreFSufs< TheSwapDir >
,
Core UFS class. This template provides compile time aliases for ufs/aufs/diskd to ease configuration conversion - each becomes a StoreFS module whose createSwapDir method parameterises the common UFSSwapDir with an IO module instance.
Definition at line 34 of file StoreFSufs.h.
Member Typedef Documentation
const_iterator
typedef std::vector<StoreFileSystem*>::const_iterator StoreFileSystem::const_iterator inherited
Definition at line 98 of file StoreFileSystem.h.
iterator
typedef std::vector<StoreFileSystem*>::iterator StoreFileSystem::iterator inherited
Definition at line 97 of file StoreFileSystem.h.
Constructor & Destructor Documentation
StoreFSufs()
template<class C > Fs::Ufs::StoreFSufs< C >::StoreFSufs (char const * DefaultModuleType, char const * label)
Definition at line 52 of file StoreFSufs.h.
References StoreFileSystem::FsAdd().
~StoreFSufs()
template<class TheSwapDir > Fs::Ufs::StoreFSufs< TheSwapDir >::~StoreFSufs () inline override
Definition at line 39 of file StoreFSufs.h.
Member Function Documentation
createSwapDir()
template<class C > SwapDir * Fs::Ufs::StoreFSufs< C >::createSwapDir () override virtual
Implements StoreFileSystem.
Definition at line 66 of file StoreFSufs.h.
FileSystems()
std::vector< StoreFileSystem * > const & StoreFileSystem::FileSystems () static inherited
Definition at line 30 of file StoreFileSystem.cc.
References StoreFileSystem::GetFileSystems().
Referenced by StoreFileSystem::FindByType().
FindByType()
StoreFileSystem * StoreFileSystem::FindByType (const char * type) static inherited
Definition at line 45 of file StoreFileSystem.cc.
References StoreFileSystem::FileSystems(), and StoreFileSystem::type().
Referenced by Store::Disks::Parse().
FsAdd()
void StoreFileSystem::FsAdd (StoreFileSystem & instance) static inherited
Definition at line 17 of file StoreFileSystem.cc.
References assert, StoreFileSystem::GetFileSystems(), and StoreFileSystem::type().
Referenced by Rock::StoreFileSystem::StoreFileSystem(), and Fs::Ufs::StoreFSufs< TheSwapDir >::StoreFSufs().
GetFileSystems()
std::vector< StoreFileSystem * > & StoreFileSystem::GetFileSystems () static private inherited
Definition at line 36 of file StoreFileSystem.cc.
References StoreFileSystem::_FileSystems.
Referenced by StoreFileSystem::FileSystems(), and StoreFileSystem::FsAdd().
GetInstance()
template<class TheSwapDir > static StoreFileSystem & Fs::Ufs::StoreFSufs< TheSwapDir >::GetInstance () static
type()
template<class C > char const * Fs::Ufs::StoreFSufs< C >::type () const override virtual
Implements StoreFileSystem.
Definition at line 59 of file StoreFSufs.h.
Member Data Documentation
_FileSystems
std::vector< StoreFileSystem * > * StoreFileSystem::_FileSystems = nullptr static private inherited
Definition at line 108 of file StoreFileSystem.h.
Referenced by StoreFileSystem::GetFileSystems().
IO
template<class TheSwapDir > DiskIOModule* Fs::Ufs::StoreFSufs< TheSwapDir >::IO protected
Definition at line 46 of file StoreFSufs.h.
label
template<class TheSwapDir > char const* Fs::Ufs::StoreFSufs< TheSwapDir >::label protected
Definition at line 48 of file StoreFSufs.h.
moduleName
template<class TheSwapDir > char const* Fs::Ufs::StoreFSufs< TheSwapDir >::moduleName protected
Definition at line 47 of file StoreFSufs.h.
The documentation for this class was generated from the following file:
squid/src/fs/ufs/StoreFSufs.h