Squid Web Cache: ACLSquidErrorData Class Reference
ACLSquidErrorData Class Reference
Squid Components » Access Controls
#include <SquidErrorData.h>
Public Member Functions
ACLSquidErrorData ()
~ACLSquidErrorData () override
bool match (err_type err) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual const Acl::Options & lineOptions ()
supported ACL "line" options (e.g., "-i")
virtual void prepareForUse ()
Private Attributes
CbDataListContainer< err_type > errors
Detailed Description
Definition at line 17 of file SquidErrorData.h.
Constructor & Destructor Documentation
ACLSquidErrorData()
ACLSquidErrorData::ACLSquidErrorData () inline
Definition at line 21 of file SquidErrorData.h.
~ACLSquidErrorData()
ACLSquidErrorData::~ACLSquidErrorData () inline override
Definition at line 23 of file SquidErrorData.h.
Member Function Documentation
dump()
SBufList ACLSquidErrorData::dump () const override virtual
Implements ACLData< err_type >.
Definition at line 34 of file SquidErrorData.cc.
References CbDataListIterator< C >::end(), errors, errorTypeName(), and CbDataListIterator< C >::next().
empty()
bool ACLSquidErrorData::empty () const override virtual
Implements ACLData< err_type >.
Definition at line 64 of file SquidErrorData.cc.
References CbDataListContainer< C >::empty(), and errors.
lineOptions()
virtual const Acl::Options & ACLData< err_type >::lineOptions () inline virtual inherited
Definition at line 26 of file Data.h.
match()
bool ACLSquidErrorData::match (err_type err) override virtual
Implements ACLData< err_type >.
Definition at line 20 of file SquidErrorData.cc.
References debugs, CbDataListIterator< C >::end(), errors, errorTypeName(), and CbDataListIterator< C >::next().
parse()
void ACLSquidErrorData::parse () override virtual
Implements ACLData< err_type >.
Definition at line 48 of file SquidErrorData.cc.
References DBG_CRITICAL, debugs, ERR_MAX, errors, errorTypeByName(), opt_parse_cfg_only, CbDataListContainer< C >::push_back(), self_destruct(), and ConfigParser::strtokFile().
prepareForUse()
virtual void ACLData< err_type >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
errors
CbDataListContainer<err_type> ACLSquidErrorData::errors private
Definition at line 30 of file SquidErrorData.h.
Referenced by dump(), empty(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/SquidErrorData.h
squid/src/acl/SquidErrorData.cc