Squid Web Cache: AnyP::Uri Class Reference
AnyP::Uri Class Reference
#include <Uri.h>
Public Member Functions
Uri ()
Uri (AnyP::UriScheme const &aScheme)
Uri (const Uri &)=default
Uri (Uri &&)=default
Uri & operator= (const Uri &)=default
Uri & operator= (Uri &&)=default
void clear ()
void touch ()
clear the cached URI display forms
bool parse (const HttpRequestMethod &, const SBuf &url)
AnyP::UriScheme const & getScheme () const
void setScheme (const AnyP::ProtocolType &p, const char *str)
convert the URL scheme to that given
void setScheme (const AnyP::UriScheme &s)
void userInfo (const SBuf &s)
const SBuf & userInfo () const
void host (const char *src)
const char * host (void) const
int hostIsNumeric (void) const
Ip::Address const & hostIP (void) const
std::optional< Host > parsedHost () const
SBuf hostOrIp () const
void port (const Port p)
reset authority port subcomponent
Port port () const
authority port subcomponent
void defaultPort ()
reset the port to the default port number for the current scheme
void path (const char *p)
void path (const SBuf &p)
const SBuf & path () const
void addRelativePath (const char *relUrl)
SBuf & authority (bool requirePort=false) const
SBuf & absolute () const
SBuf & absolutePath () const
RFC 3986 section 4.2 relative reference called 'absolute-path'.
SBuf & originForm () const
The RFC 7230 origin-form URI for currently stored values.
Static Public Member Functions
static char * cleanup (const char *uri)
static const SBuf & SlashPath ()
the static '/' default URL-path
static const SBuf & Asterisk ()
the static '*' pseudo-URI
static SBuf Encode (const SBuf &, const CharacterSet &expected)
static std::optional< SBuf > Decode (const SBuf &)
static SBuf DecodeOrDupe (const SBuf &input)
Private Member Functions
MEMPROXY_CLASS (Uri)
void parseUrn (Parser::Tokenizer &)
SBuf parseHost (Parser::Tokenizer &) const
int parsePort (Parser::Tokenizer &) const
Private Attributes
AnyP::UriScheme scheme_
SBuf userInfo_
char host_ [SQUIDHOSTNAMELEN]
string representation of the URI authority name or IP
bool hostIsNumeric_
whether the authority 'host' is a raw-IP
Ip::Address hostAddr_
binary representation of the URI authority if it is a raw-IP
Port port_
authority port subcomponent
SBuf path_
URI path segment.
SBuf authorityHttp_
RFC 7230 section 5.3.3 authority, maybe without default-port.
SBuf authorityWithPort_
RFC 7230 section 5.3.3 authority with explicit port.
SBuf absolute_
RFC 7230 section 5.3.2 absolute-URI.
SBuf absolutePath_
RFC 3986 section 4.2 absolute-path.
Detailed Description
Represents a Uniform Resource Identifier. Can store both URL or URN representations.
Governed by RFC 3986
Definition at line 31 of file Uri.h.
Constructor & Destructor Documentation
Uri() [1/4]
AnyP::Uri::Uri () inline
Definition at line 36 of file Uri.h.
References host_.
Uri() [2/4]
AnyP::Uri::Uri (AnyP::UriScheme const & aScheme)
Definition at line 1067 of file Uri.cc.
References host_.
Uri() [3/4]
AnyP::Uri::Uri (const Uri &) default
Uri() [4/4]
AnyP::Uri::Uri (Uri &&) default
Member Function Documentation
absolute()
SBuf & AnyP::Uri::absolute () const
The absolute-form URI for currently stored values.
As defined by RFC 7230 section 5.3.3 this form omits the userinfo@ field from RFC 3986 defined authority segments when the protocol scheme is http: or https:.
Definition at line 743 of file Uri.cc.
References MAX_URL, AnyP::PROTO_FTP, AnyP::PROTO_UNKNOWN, AnyP::PROTO_URN, CharacterSet::remove(), CharacterSet::rename(), SBuf::reserveCapacity(), and UserInfoChars().
Referenced by HttpRequest::effectiveRequestUri(), CacheManager::ParseUrl(), purgeEntriesByHeader(), UrnState::setUriResFromRequest(), and urnParseReply().
absolutePath()
SBuf & AnyP::Uri::absolutePath () const
Definition at line 775 of file Uri.cc.
References PathChars().
Referenced by Format::Format::assemble(), carpSelectParent(), ErrorState::compileLegacyCode(), internalStart(), AnyP::operator<<(), originForm(), Adaptation::Service::wants(), and whoisStart().
addRelativePath()
void AnyP::Uri::addRelativePath (const char * relUrl)
Merge a relative-path URL into the existing URI details. Implements RFC 3986 section 5.2.3
The caller must ensure relUrl is a valid relative-path.
Definition at line 879 of file Uri.cc.
References SBuf::npos, and AnyP::PROTO_URN.
Referenced by purgeEntriesByHeader().
Asterisk()
const SBuf & AnyP::Uri::Asterisk () static
Definition at line 140 of file Uri.cc.
Referenced by urlCheckRequest().
authority()
SBuf & AnyP::Uri::authority (bool requirePort = false) const
The authority-form URI for currently stored values.
As defined by RFC 7230 section 5.3.3 this form omits the userinfo@ field from RFC 3986 defined authority segment.
Parameters
requirePort when true the port will be included, otherwise port will be elided when it is the default for the current scheme.
Definition at line 721 of file Uri.cc.
References SBuf::append(), SBuf::appendf(), and port.
Referenced by Ssl::ServerBump::ServerBump(), Http::Tunneler::Tunneler(), Http::One::Server::buildHttpRequest(), ClientHttpRequest::checkForInternalAccess(), copyOneHeaderFromClientsideRequestToUpstreamRequest(), HttpRequest::effectiveRequestUri(), HttpStateData::httpBuildRequestHeader(), internalRemoteUri(), AnyP::operator<<(), and peerAllowedToUse().
cleanup()
char * AnyP::Uri::cleanup (const char * uri) static
Returns
a new URI that honors uri_whitespace
Definition at line 1076 of file Uri.cc.
References assert, Config, MAX_URL, rfc1738_do_escape(), RFC1738_ESCAPE_NOSPACE, RFC1738_ESCAPE_UNESCAPED, rfc1738_escape_unescaped, SquidConfig::uri_whitespace, URI_WHITESPACE_ALLOW, URI_WHITESPACE_CHOP, URI_WHITESPACE_DENY, URI_WHITESPACE_ENCODE, URI_WHITESPACE_STRIP, w_space, xfree, xisspace, xmalloc, and xstrndup().
Referenced by ClientHttpRequest::setLogUriToRawUri().
clear()
void AnyP::Uri::clear () inline
Definition at line 43 of file Uri.h.
References host_, hostAddr_, hostIsNumeric_, port_, AnyP::PROTO_NONE, scheme_, Ip::Address::setEmpty(), and touch().
Referenced by HttpRequest::clean(), and HttpRequest::init().
Decode()
std::optional< SBuf > AnyP::Uri::Decode (const SBuf & buf) static
%-decode the given buffer
Return values
std::nullopt on decoding failures
See also
DecodeOrDupe()
Definition at line 105 of file Uri.cc.
References SBuf::append(), CharacterSet::complement(), and debugs.
Referenced by Ftp::Gateway::decodedRequestUriPath(), and TestUri::testEncoding().
DecodeOrDupe()
SBuf AnyP::Uri::DecodeOrDupe (const SBuf & input) static
%-decode the given buffer
Return values
decoded input if input obeys RFC 3986 Percent-Encoding rules
an input copy if input violates RFC 3986 Percent-Encoding rules
See also
Decode()
Definition at line 132 of file Uri.cc.
Referenced by Acl::UrlCheck::match(), Acl::UrlLoginCheck::match(), and TestUri::testEncoding().
defaultPort()
void AnyP::Uri::defaultPort () inline
Definition at line 94 of file Uri.h.
References defaultPort(), getScheme(), and port().
Referenced by defaultPort().
Encode()
SBuf AnyP::Uri::Encode (const SBuf & buf, const CharacterSet & ignore) static
%-encode characters in a buffer which do not conform to the provided set of expected characters.
Governed by RFC 3986 section 2.1
Definition at line 76 of file Uri.cc.
References SBuf::append(), SBuf::appendf(), Parser::Tokenizer::atEnd(), SBuf::isEmpty(), SBuf::length(), Parser::Tokenizer::prefix(), Parser::Tokenizer::remaining(), SBuf::reserveSpace(), and Parser::Tokenizer::skip().
Referenced by ErrorState::Dump(), and TestUri::testEncoding().
getScheme()
AnyP::UriScheme const & AnyP::Uri::getScheme () const inline
Definition at line 58 of file Uri.h.
References scheme_.
Referenced by Format::Format::assemble(), clientReplyContext::cacheHit(), HttpRequest::canonicalCleanUrl(), carpSelectParent(), ClientHttpRequest::checkForInternalAccess(), clientHierarchical(), ErrorState::compileLegacyCode(), defaultPort(), FwdState::dispatch(), HttpRequest::effectiveRequestUri(), ClientRequestContext::hostHeaderVerify(), HttpStateData::httpBuildRequestHeader(), HttpRequest::maybeCacheable(), AnyP::operator<<(), HttpStateData::processReplyHeader(), purgeEntriesByHeader(), FwdState::secureConnectionToPeerIfNeeded(), PeerSelector::selectSomeDirect(), FwdState::Start(), TestUri::testConstructScheme(), TestHttpRequest::testCreateFromUrl(), TestUri::testDefaultConstructor(), TestHttpRequest::testIPv6HostColonBug(), urlCheckRequest(), and Ftp::UrlWith2f().
host() [1/2]
void AnyP::Uri::host (const char * src)
Definition at line 154 of file Uri.cc.
References debugs, and xstrncpy().
Referenced by PeerPoolMgr::PeerPoolMgr(), Format::Format::assemble(), ConnStateData::borrowPinnedConnection(), ConnStateData::buildFakeRequest(), carpSelectParent(), HttpStateData::checkDateSkew(), ClientHttpRequest::checkForInternalAccess(), PeerSelector::checkNetdbDirect(), ErrorState::compileLegacyCode(), TunnelStateData::connectDone(), FwdState::connectStart(), FwdState::dispatch(), doV2Query(), ftpSendUser(), TunnelStateData::getHost(), ClientRequestContext::hostHeaderVerify(), htcpTstReply(), clientReplyContext::identifyFoundObject(), internalRemoteUri(), ACLDestinationIP::match(), neighborType(), netdbClosestParent(), netdbUpdatePeer(), FwdState::noteConnection(), TunnelStateData::noteConnection(), PeerSelector::noteIps(), operator<<(), CacheManager::ParseUrl(), ConnStateData::pinConnection(), ConnStateData::postHttpsAccept(), HttpStateData::processReplyBody(), clientReplyContext::purgeRequest(), PeerSelector::resolveSelected(), PeerSelector::selectMore(), PeerSelector::selectSomeParent(), UrnState::setUriResFromRequest(), TunnelStateData::startConnecting(), ACLDestinationIP::StartLookup(), FwdState::successfullyConnectedToPeer(), TestHttpRequest::testCreateFromUrl(), TestHttpRequest::testIPv6HostColonBug(), TestCacheManager::testParseUrl(), urlCanonicalFakeHttps(), urnParseReply(), FwdState::usePinned(), and TunnelStateData::usePinned().
host() [2/2]
const char * AnyP::Uri::host (void) const inline
Definition at line 76 of file Uri.h.
References host_.
hostIP()
Ip::Address const & AnyP::Uri::hostIP (void) const inline
Definition at line 78 of file Uri.h.
References hostAddr_.
Referenced by ACLDestinationIP::match().
hostIsNumeric()
int AnyP::Uri::hostIsNumeric (void) const inline
Definition at line 77 of file Uri.h.
References hostIsNumeric_.
Referenced by ACLDestinationIP::match().
hostOrIp()
SBuf AnyP::Uri::hostOrIp () const
Returns
the host subcomponent of the authority component If the host is an IPv6 address, returns that IP address with [brackets]. See RFC 3986 Section 3.2.2.
Definition at line 170 of file Uri.cc.
References MAX_IPSTRLEN.
Referenced by ConnStateData::initiateTunneledRequest().
MEMPROXY_CLASS()
AnyP::Uri::MEMPROXY_CLASS (Uri) private
operator=() [1/2]
Uri & AnyP::Uri::operator= (const Uri &) default
operator=() [2/2]
Uri & AnyP::Uri::operator= (Uri &&) default
originForm()
SBuf & AnyP::Uri::originForm () const inline
Definition at line 154 of file Uri.h.
References absolutePath().
Referenced by HttpStateData::buildRequestPrefix(), HttpRequest::packFirstLineInto(), and HttpRequest::prefixLen().
parse()
bool AnyP::Uri::parse (const HttpRequestMethod & method, const SBuf & url)
Definition at line 326 of file Uri.cc.
References SquidConfig::allow_underscore, SquidConfig::appendDomainLen, Assure, SquidConfig::check_hostnames, Config, CurrentException(), DBG_IMPORTANT, debugs, AnyP::UriScheme::defaultPort(), Here, AnyP::UriScheme::image(), SBuf::length(), LOCAL_ARRAY, MAX_URL, Http::METHOD_CONNECT, Http::METHOD_OPTIONS, Http::METHOD_TRACE, MYNAME, SquidConfig::onoff, port, AnyP::PROTO_HTTP, AnyP::PROTO_NONE, AnyP::PROTO_URN, SBuf::rawContent(), rfc1738_escape_unescaped, rfc1738_unescape(), SBufToCstring(), stringHasWhitespace(), SquidConfig::uri_whitespace, URI_WHITESPACE_ALLOW, URI_WHITESPACE_CHOP, URI_WHITESPACE_DENY, URI_WHITESPACE_ENCODE, URI_WHITESPACE_STRIP, uriParseScheme(), urlAppendDomain(), valid_hostname_chars, valid_hostname_chars_u, w_space, xisspace, xstrncpy(), and xtolower.
Referenced by ClientRequestContext::clientRedirectDone(), HttpRequest::parseFirstLine(), and urnParseReply().
parsedHost()
std::optional< AnyP::Host > AnyP::Uri::parsedHost () const
Successfully interpreted non-empty host subcomponent of the authority component (if any). XXX: Remove hostOrIp() and print Host instead.
Definition at line 181 of file Uri.cc.
References debugs, SBuf::find(), SBuf::npos, AnyP::Host::ParseIp(), and AnyP::Host::ParseSimpleDomainName().
Referenced by ConnStateData::serveDelayedError().
parseHost()
SBuf AnyP::Uri::parseHost (Parser::Tokenizer & tok) const private
Extracts and returns a (suspected but only partially validated) uri-host IPv6address, IPv4address, or reg-name component. This function uses (and quotes) RFC 3986, Section 3.2.2 syntax rules.
Definition at line 632 of file Uri.cc.
References SBuf::c_str(), SBuf::find(), Ip::Address::fromHost(), Here, CharacterSet::HEXDIG, SBuf::npos, and CharacterSet::TCHAR.
parsePort()
int AnyP::Uri::parsePort (Parser::Tokenizer & tok) const private
Extracts and returns an RFC 3986 URI authority port value (with additional restrictions). The RFC defines port as a possibly empty sequence of decimal digits. We reject certain ports (that are syntactically valid from the RFC point of view) because we are worried that Squid and other traffic handlers may dangerously mishandle unusual (and virtually always bogus) port numbers. Rejected ports cannot be successfully used by Squid itself.
Definition at line 690 of file Uri.cc.
References Assure, Here, and Less().
parseUrn()
void AnyP::Uri::parseUrn (Parser::Tokenizer & tok) private
Governed by RFC 8141 section 2:
assigned-name = "urn" ":" NID ":" NSS NID = (alphanum) 0*30(ldh) (alphanum) ldh = alphanum / "-" NSS = pchar *(pchar / "/")
RFC 3986 Appendix D.2 defines (as deprecated):
alphanum = ALPHA / DIGIT
Notice that NID is exactly 2-32 characters in length.
Definition at line 601 of file Uri.cc.
References CharacterSet::ALPHA, SBuf::begin(), SBuf::c_str(), debugs, CharacterSet::DIGIT, Here, SBuf::length(), AnyP::PROTO_URN, and SBuf::rbegin().
path() [1/3]
const SBuf & AnyP::Uri::path () const
Definition at line 200 of file Uri.cc.
References AnyP::PROTO_HTTP, and AnyP::PROTO_HTTPS.
path() [2/3]
void AnyP::Uri::path (const char * p) inline
Definition at line 96 of file Uri.h.
References path_, and touch().
Referenced by ClientHttpRequest::checkForInternalAccess(), ftpFail(), ftpReadType(), ftpSendType(), HttpRequest::initHTTP(), CacheManager::ParseUrl(), purgeEntriesByHeader(), TestHttpRequest::testCreateFromUrl(), TestHttpRequest::testIPv6HostColonBug(), TestCacheManager::testParseUrl(), urlCheckRequest(), and Ftp::UrlWith2f().
path() [3/3]
void AnyP::Uri::path (const SBuf & p) inline
Definition at line 97 of file Uri.h.
References path_, and touch().
port() [1/2]
Port AnyP::Uri::port () const inline
Definition at line 92 of file Uri.h.
References port_.
Referenced by defaultPort().
port() [2/2]
void AnyP::Uri::port (const Port p) inline
Definition at line 90 of file Uri.h.
References port_, and touch().
Referenced by Format::Format::assemble(), ConnStateData::borrowPinnedConnection(), ConnStateData::buildFakeRequest(), carpSelectParent(), ClientHttpRequest::checkForInternalAccess(), ErrorState::compileLegacyCode(), ClientRequestContext::hostHeaderVerify(), ConnStateData::initiateTunneledRequest(), internalRemoteUri(), PeerSelector::noteIp(), peerAllowedToUse(), ConnStateData::pinConnection(), ConnStateData::postHttpsAccept(), TestHttpRequest::testCreateFromUrl(), TestHttpRequest::testIPv6HostColonBug(), TestCacheManager::testParseUrl(), and urlCanonicalFakeHttps().
setScheme() [1/2]
void AnyP::Uri::setScheme (const AnyP::ProtocolType & p, const char * str) inline
Definition at line 61 of file Uri.h.
References scheme_, and touch().
Referenced by ConnStateData::buildFakeRequest(), ClientHttpRequest::checkForInternalAccess(), HttpRequest::initHTTP(), and TestCacheManager::testParseUrl().
setScheme() [2/2]
void AnyP::Uri::setScheme (const AnyP::UriScheme & s) inline
Definition at line 65 of file Uri.h.
References scheme_, and touch().
SlashPath()
const SBuf & AnyP::Uri::SlashPath () static
Definition at line 147 of file Uri.cc.
Referenced by Ftp::UrlWith2f().
touch()
void AnyP::Uri::touch ()
Definition at line 712 of file Uri.cc.
Referenced by clear(), path(), path(), port(), setScheme(), setScheme(), and userInfo().
userInfo() [1/2]
const SBuf & AnyP::Uri::userInfo () const inline
Returns
raw userinfo subcomponent (or an empty string) the caller is responsible for caller-specific encoding
Definition at line 73 of file Uri.h.
References userInfo_.
userInfo() [2/2]
void AnyP::Uri::userInfo (const SBuf & s) inline
Definition at line 70 of file Uri.h.
References touch(), and userInfo_.
Referenced by clientInterpretRequestHeaders(), HttpStateData::httpBuildRequestHeader(), netdbExchangeStart(), and peerDigestRequest().
Member Data Documentation
absolute_
SBuf AnyP::Uri::absolute_ mutable private
Definition at line 200 of file Uri.h.
absolutePath_
SBuf AnyP::Uri::absolutePath_ mutable private
Definition at line 201 of file Uri.h.
authorityHttp_
SBuf AnyP::Uri::authorityHttp_ mutable private
Definition at line 198 of file Uri.h.
authorityWithPort_
SBuf AnyP::Uri::authorityWithPort_ mutable private
Definition at line 199 of file Uri.h.
host_
char AnyP::Uri::host_[SQUIDHOSTNAMELEN] private
Definition at line 188 of file Uri.h.
Referenced by Uri(), Uri(), clear(), and host().
hostAddr_
Ip::Address AnyP::Uri::hostAddr_ private
Definition at line 190 of file Uri.h.
Referenced by clear(), and hostIP().
hostIsNumeric_
bool AnyP::Uri::hostIsNumeric_ private
Definition at line 189 of file Uri.h.
Referenced by clear(), and hostIsNumeric().
path_
SBuf AnyP::Uri::path_ private
Definition at line 195 of file Uri.h.
Referenced by path(), and path().
port_
Port AnyP::Uri::port_ private
Definition at line 192 of file Uri.h.
Referenced by clear(), port(), and port().
scheme_
AnyP::UriScheme AnyP::Uri::scheme_ private
The scheme of this URL. This has the 'type code' smell about it. In future we may want to make the methods that dispatch based on the scheme virtual and have a class per protocol.
On the other hand, having Protocol as an explicit concept is useful, see for instance the ACLProtocol acl type. One way to represent this is to have one prototype URL with no host etc for each scheme, another is to have an explicit scheme class, and then each URL class could be a subclass of the scheme. Another way is one instance of a AnyP::UriScheme class instance for each URL scheme we support, and one class for each manner of treating the scheme : a Hierarchical URL, a non-hierarchical URL etc.
Deferring the decision, its a type code for now. RBC 20060507.
In order to make taking any of these routes easy, scheme is private, only settable at construction time, or with explicit setter
Definition at line 182 of file Uri.h.
Referenced by clear(), getScheme(), setScheme(), and setScheme().
userInfo_
SBuf AnyP::Uri::userInfo_ private
Definition at line 184 of file Uri.h.
Referenced by userInfo(), and userInfo().
The documentation for this class was generated from the following files:
squid/src/anyp/Uri.h
squid/src/anyp/Uri.cc
squid/src/tests/stub_libanyp.cc