Squid Web Cache: Adaptation::AccessRule Class Reference
Adaptation::AccessRule Class Reference
#include <AccessRule.h>
Public Types
typedef int Id
Public Member Functions
AccessRule (const String &groupId)
~AccessRule ()
void parse (ConfigParser &parser)
void finalize ()
ServiceGroupPointer group ()
Public Attributes
const Id id
String groupId
acl_access * acl
Static Private Attributes
static Id LastId = 0
Detailed Description
Definition at line 25 of file AccessRule.h.
Member Typedef Documentation
Id
typedef int Adaptation::AccessRule::Id
Definition at line 38 of file AccessRule.h.
Constructor & Destructor Documentation
AccessRule()
Adaptation::AccessRule::AccessRule (const String & groupId)
Definition at line 20 of file AccessRule.cc.
~AccessRule()
Adaptation::AccessRule::~AccessRule ()
Definition at line 24 of file AccessRule.cc.
Member Function Documentation
finalize()
void Adaptation::AccessRule::finalize ()
Definition at line 36 of file AccessRule.cc.
References Adaptation::AllGroups(), DBG_CRITICAL, debugs, Adaptation::ServiceGroup::finalize(), and Adaptation::FindService().
group()
Adaptation::ServiceGroupPointer Adaptation::AccessRule::group ()
Definition at line 55 of file AccessRule.cc.
References Adaptation::FindGroup().
parse()
void Adaptation::AccessRule::parse (ConfigParser & parser)
Definition at line 30 of file AccessRule.cc.
References aclParseAccessLine().
Referenced by Adaptation::Config::ParseAccess().
Member Data Documentation
acl
acl_access* Adaptation::AccessRule::acl
Definition at line 41 of file AccessRule.h.
groupId
String Adaptation::AccessRule::groupId
Definition at line 40 of file AccessRule.h.
Referenced by Adaptation::AccessCheck::isCandidate(), and Adaptation::Config::removeRule().
id
const Id Adaptation::AccessRule::id
Definition at line 39 of file AccessRule.h.
Referenced by Adaptation::AccessCheck::check(), and Adaptation::AccessCheck::isCandidate().
LastId
int Adaptation::AccessRule::LastId = 0 static private
Definition at line 44 of file AccessRule.h.
The documentation for this class was generated from the following files:
squid/src/adaptation/AccessRule.h
squid/src/adaptation/AccessRule.cc