Squid Web Cache: Adaptation::Icap::Options::TransferList Class Reference
Adaptation::Icap::Options::TransferList Class Reference
#include <Options.h>
Public Member Functions
TransferList ()
~TransferList ()
bool matches (const SBuf &urlPath) const
void parse (const String &buf, bool &foundStar)
void add (const char *extension)
void report (int level, const char *prefix) const
Public Attributes
wordlist * extensions
const char * name
TransferKind kind
Detailed Description
Definition at line 65 of file Options.h.
Constructor & Destructor Documentation
TransferList()
Adaptation::Icap::Options::TransferList::TransferList ()
Definition at line 172 of file Options.cc.
~TransferList()
Adaptation::Icap::Options::TransferList::~TransferList ()
Definition at line 177 of file Options.cc.
References wordlistDestroy().
Member Function Documentation
add()
void Adaptation::Icap::Options::TransferList::add (const char * extension)
Definition at line 182 of file Options.cc.
References wordlistAdd().
matches()
bool Adaptation::Icap::Options::TransferList::matches (const SBuf & urlPath) const
Definition at line 187 of file Options.cc.
References SBuf::cmp(), debugs, SBuf::length(), wordlist::next, and SBuf::substr().
parse()
void Adaptation::Icap::Options::TransferList::parse (const String & buf, bool & foundStar)
Definition at line 208 of file Options.cc.
References strListGetItem(), xfree, and xstrndup().
Referenced by Adaptation::Icap::Options::cfgTransferList().
report()
void Adaptation::Icap::Options::TransferList::report (int level, const char * prefix) const
Definition at line 226 of file Options.cc.
References debugs, and wordlist::next.
Referenced by Adaptation::Icap::Options::cfgTransferList().
Member Data Documentation
extensions
wordlist* Adaptation::Icap::Options::TransferList::extensions
Definition at line 78 of file Options.h.
kind
TransferKind Adaptation::Icap::Options::TransferList::kind
Definition at line 80 of file Options.h.
Referenced by Adaptation::Icap::Options::Options().
name
const char* Adaptation::Icap::Options::TransferList::name
Definition at line 79 of file Options.h.
Referenced by Adaptation::Icap::Options::Options(), and Adaptation::Icap::Options::cfgTransferList().
The documentation for this class was generated from the following files:
squid/src/adaptation/icap/Options.h
squid/src/adaptation/icap/Options.cc