Squid Web Cache: CommonPool Class Reference
CommonPool Class Reference
#include <CommonPool.h>
Public Member Functions
const SBuf & classTypeLabel () const
Static Public Member Functions
static CommonPool * Factory (unsigned char _class, CompositePoolNode::Pointer &)
Protected Member Functions
CommonPool ()
Protected Attributes
SBuf typeLabel
Private Member Functions
MEMPROXY_CLASS (CommonPool)
Detailed Description
Definition at line 25 of file CommonPool.h.
Constructor & Destructor Documentation
CommonPool()
CommonPool::CommonPool () protected
Definition at line 310 of file delay_pools.cc.
Member Function Documentation
classTypeLabel()
const SBuf & CommonPool::classTypeLabel () const inline
Definition at line 31 of file CommonPool.h.
References typeLabel.
Referenced by DelayPool::dump().
Factory()
CommonPool * CommonPool::Factory (unsigned char _class, CompositePoolNode::Pointer & compositeCopy) static
Definition at line 248 of file delay_pools.cc.
References Aggregate::Aggregate(), fatal(), RefCount< C >::getRaw(), DelayVector::push_back(), and typeLabel.
Referenced by DelayPool::DelayPool(), and DelayPool::createPool().
MEMPROXY_CLASS()
CommonPool::MEMPROXY_CLASS (CommonPool) private
Member Data Documentation
typeLabel
SBuf CommonPool::typeLabel protected
Definition at line 35 of file CommonPool.h.
Referenced by classTypeLabel(), and Factory().
The documentation for this class was generated from the following files:
squid/src/CommonPool.h
squid/src/delay_pools.cc