Squid Web Cache: Ipc::StoreMapItems< C > Class Template Reference
Ipc::StoreMapItems< C > Class Template Reference
#include <StoreMap.h>
Public Types
typedef C Item
typedef Ipc::Mem::Owner< StoreMapItems< Item > > Owner
Public Member Functions
StoreMapItems (const int aCapacity)
size_t sharedMemorySize () const
Item & at (const int index)
const Item & at (const int index) const
void fill (const Item &value)
reset all items to the same value
Static Public Member Functions
static size_t SharedMemorySize (const int aCapacity)
Public Attributes
const int capacity
total number of items
Ipc::Mem::FlexibleArray< Item > items
storage
Detailed Description
template<class C>
class Ipc::StoreMapItems< C >
an array of shareable Items must be the last data member or, if used as a parent class, the last parent
Definition at line 121 of file StoreMap.h.
Member Typedef Documentation
Item
template<class C > typedef C Ipc::StoreMapItems< C >::Item
Definition at line 124 of file StoreMap.h.
Owner
template<class C > typedef Ipc::Mem::Owner< StoreMapItems<Item> > Ipc::StoreMapItems< C >::Owner
Definition at line 125 of file StoreMap.h.
Constructor & Destructor Documentation
StoreMapItems()
template<class C > Ipc::StoreMapItems< C >::StoreMapItems (const int aCapacity) inline explicit
Definition at line 127 of file StoreMap.h.
Member Function Documentation
at() [1/2]
template<class C > Item & Ipc::StoreMapItems< C >::at (const int index) inline
Definition at line 132 of file StoreMap.h.
References assert, Ipc::StoreMapItems< C >::capacity, and Ipc::StoreMapItems< C >::items.
Referenced by Ipc::StoreMapItems< C >::at().
at() [2/2]
template<class C > const Item & Ipc::StoreMapItems< C >::at (const int index) const inline
Definition at line 139 of file StoreMap.h.
References Ipc::StoreMapItems< C >::at().
fill()
template<class C > void Ipc::StoreMapItems< C >::fill (const Item & value) inline
Definition at line 145 of file StoreMap.h.
References Ipc::StoreMapItems< C >::capacity, and Ipc::StoreMapItems< C >::items.
Referenced by Rock::LoadingParts::LoadingParts().
sharedMemorySize()
template<class C > size_t Ipc::StoreMapItems< C >::sharedMemorySize () const inline
Definition at line 129 of file StoreMap.h.
References Ipc::StoreMapItems< C >::capacity, and Ipc::StoreMapItems< C >::SharedMemorySize().
SharedMemorySize()
template<class C > static size_t Ipc::StoreMapItems< C >::SharedMemorySize (const int aCapacity) inline static
Definition at line 130 of file StoreMap.h.
Referenced by Ipc::StoreMapItems< C >::sharedMemorySize().
Member Data Documentation
capacity
template<class C > const int Ipc::StoreMapItems< C >::capacity
Definition at line 151 of file StoreMap.h.
Referenced by Ipc::StoreMapItems< C >::at(), Ipc::StoreMapItems< C >::fill(), and Ipc::StoreMapItems< C >::sharedMemorySize().
items
template<class C > Ipc::Mem::FlexibleArray<Item> Ipc::StoreMapItems< C >::items
Definition at line 152 of file StoreMap.h.
Referenced by Ipc::StoreMapItems< C >::at(), and Ipc::StoreMapItems< C >::fill().
The documentation for this class was generated from the following file:
squid/src/ipc/StoreMap.h