Squid Web Cache: ACLRegexData Class Reference
ACLRegexData Class Reference
#include <RegexData.h>
Public Member Functions
~ACLRegexData () override
bool match (char const *user) override
SBufList dump () const override
void parse () override
bool empty () const override
virtual void prepareForUse ()
Private Member Functions
MEMPROXY_CLASS (ACLRegexData)
const Acl::Options & lineOptions () override
supported ACL "line" options (e.g., "-i")
Private Attributes
std::list< RegexPattern > data
Static Private Attributes
static Acl::BooleanOptionValue CaseInsensitive_
whether parse() is called in a case insensitive context
Detailed Description
Definition at line 18 of file RegexData.h.
Constructor & Destructor Documentation
~ACLRegexData()
ACLRegexData::~ACLRegexData () override
Definition at line 31 of file RegexData.cc.
Member Function Documentation
dump()
SBufList ACLRegexData::dump () const override virtual
Implements ACLData< char const * >.
Definition at line 66 of file RegexData.cc.
References SBufStream::buf(), data, and RegexPattern::print().
empty()
bool ACLRegexData::empty () const override virtual
Implements ACLData< char const * >.
Definition at line 253 of file RegexData.cc.
References data.
lineOptions()
const Acl::Options & ACLRegexData::lineOptions () override private virtual
Reimplemented from ACLData< char const * >.
Definition at line 36 of file RegexData.cc.
References CaseInsensitive_, and Acl::CaseSensitivityOption().
match()
bool ACLRegexData::match (char const * user) override virtual
Implements ACLData< char const * >.
Definition at line 45 of file RegexData.cc.
References data, and debugs.
MEMPROXY_CLASS()
ACLRegexData::MEMPROXY_CLASS (ACLRegexData) private
parse()
void ACLRegexData::parse () override virtual
Implements ACLData< char const * >.
Definition at line 221 of file RegexData.cc.
References CaseInsensitive_, cfg_filename, compileOptimisedREs(), compileUnoptimisedREs(), config_input_line, config_lineno, CurrentException(), data, DBG_IMPORTANT, debugs, Debug::Extra(), ConfigParser::RegexStrtokFile(), and removeUnnecessaryWildcards().
prepareForUse()
virtual void ACLData< char const * >::prepareForUse () inline virtual inherited
Definition at line 31 of file Data.h.
Member Data Documentation
CaseInsensitive_
Acl::BooleanOptionValue ACLRegexData::CaseInsensitive_ static private
Definition at line 31 of file RegexData.h.
Referenced by lineOptions(), and parse().
data
std::list<RegexPattern> ACLRegexData::data private
Definition at line 36 of file RegexData.h.
Referenced by dump(), empty(), match(), and parse().
The documentation for this class was generated from the following files:
squid/src/acl/RegexData.h
squid/src/acl/RegexData.cc