Squid Web Cache: TestCacheManager Class Reference
TestCacheManager Class Reference
Protected Member Functions
void testCreate ()
void testRegister ()
void testParseUrl ()
Private Member Functions
CPPUNIT_TEST_SUITE (TestCacheManager)
CPPUNIT_TEST (testCreate)
CPPUNIT_TEST (testRegister)
CPPUNIT_TEST (testParseUrl)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 23 of file testCacheManager.cc.
Member Function Documentation
CPPUNIT_TEST() [1/3]
TestCacheManager::CPPUNIT_TEST (testCreate) private
CPPUNIT_TEST() [2/3]
TestCacheManager::CPPUNIT_TEST (testParseUrl) private
CPPUNIT_TEST() [3/3]
TestCacheManager::CPPUNIT_TEST (testRegister) private
CPPUNIT_TEST_SUITE()
TestCacheManager::CPPUNIT_TEST_SUITE (TestCacheManager) private
CPPUNIT_TEST_SUITE_END()
TestCacheManager::CPPUNIT_TEST_SUITE_END () private
testCreate()
void TestCacheManager::testCreate () protected
Definition at line 82 of file testCacheManager.cc.
References CacheManager::GetInstance().
testParseUrl()
void TestCacheManager::testParseUrl () protected
Definition at line 124 of file testCacheManager.cc.
References SBuf::append(), assert, CacheManager::GetInstance(), AnyP::Uri::host(), AnyP::Uri::path(), AnyP::Uri::port(), AnyP::PROTO_FTP, AnyP::PROTO_HTTP, AnyP::PROTO_HTTPS, AnyP::Uri::setScheme(), and CacheManager::WellKnownUrlPathPrefix().
testRegister()
void TestCacheManager::testRegister () protected
Definition at line 98 of file testCacheManager.cc.
References StoreEntry::createMemObject(), CacheManager::createNamedAction(), dummy_action(), StoreEntry::flags, CacheManager::GetInstance(), Mgr::informal, Mgr::no, and Mgr::RegisterAction().
The documentation for this class was generated from the following file:
squid/src/tests/testCacheManager.cc