Squid Web Cache: DelayId Class Reference
DelayId Class Reference
Squid Components » Delay Pools API
#include <DelayId.h>
Public Member Functions
DelayId ()
DelayId (unsigned short, const DelayIdComposite::Pointer &)
~DelayId ()
unsigned short pool () const
bool operator== (DelayId const &rhs) const
operator bool () const
int bytesWanted (int min, int max) const
void bytesIn (int qty)
void setNoDelay (bool const)
void delayRead (const AsyncCallPointer &)
Static Public Member Functions
static DelayId DelayClient (ClientHttpRequest *, HttpReply *reply=nullptr)
Private Attributes
unsigned short pool_
DelayIdComposite::Pointer compositeId
bool markedAsNoDelay
Detailed Description
Definition at line 21 of file DelayId.h.
Constructor & Destructor Documentation
DelayId() [1/2]
DelayId::DelayId ()
Definition at line 28 of file DelayId.cc.
Referenced by DelayClient().
DelayId() [2/2]
DelayId::DelayId (unsigned short aPool, const DelayIdComposite::Pointer & aCompositeId)
Definition at line 31 of file DelayId.cc.
References assert, compositeId, debugs, and pool_.
~DelayId()
DelayId::~DelayId ()
Definition at line 39 of file DelayId.cc.
Member Function Documentation
bytesIn()
void DelayId::bytesIn (int qty)
Definition at line 135 of file DelayId.cc.
References DelayIdComposite::bytesIn(), and compositeId.
Referenced by Ftp::Client::dataRead(), and HttpStateData::readReply().
bytesWanted()
int DelayId::bytesWanted (int min, int max) const
Definition at line 119 of file DelayId.cc.
References DelayIdComposite::bytesWanted(), compositeId, and max().
Referenced by store_client::bytesWanted(), and MemObject::mostBytesWanted().
DelayClient()
DelayId DelayId::DelayClient (ClientHttpRequest * http, HttpReply * reply = nullptr) static
Definition at line 64 of file DelayId.cc.
References DelayId(), Acl::Answer::allowed(), assert, HttpRequest::auth_user_request, HttpRequest::client_addr, clientAclChecklistFill(), Config, DBG_IMPORTANT, debugs, DelayPools::delay_data, SquidConfig::delay_pool_uses_indirect_client, ACLChecklist::fastCheck(), HttpRequest::indirect_client_addr, Ip::Address::isNoAddr(), SquidConfig::onoff, pool(), DelayPools::pools(), ClientHttpRequest::request, ACLFilledChecklist::src_addr, StringToSBuf(), HttpRequest::tag, ACLFilledChecklist::updateReply(), and CompositePoolNode::CompositeSelectionDetails::user.
Referenced by Ssl::ServerBump::ServerBump(), clientReplyContext::createStoreEntry(), clientReplyContext::doGetMoreData(), clientReplyContext::processExpired(), clientReplyContext::sendMoreData(), clientReplyContext::setReplyToStoreEntry(), statClientRequests(), switchToTunnel(), and tunnelStart().
delayRead()
void DelayId::delayRead (const AsyncCallPointer & aRead)
Definition at line 144 of file DelayId.cc.
References assert, compositeId, and DelayIdComposite::delayRead().
operator bool()
DelayId::operator bool () const
Whether we may delay reading. This operator is meant to be used as an optimization that helps avoid more expensive bytesWanted() computations.
Return values
false if bytesWanted() called with a positive maximum limit parameter will never return zero
Definition at line 57 of file DelayId.cc.
operator==()
bool DelayId::operator== (DelayId const & rhs) const
Definition at line 49 of file DelayId.cc.
References compositeId, and pool_.
pool()
unsigned short DelayId::pool () const
Definition at line 43 of file DelayId.cc.
References pool_.
Referenced by DelayClient().
setNoDelay()
void DelayId::setNoDelay (bool const newValue)
Definition at line 109 of file DelayId.cc.
References markedAsNoDelay.
Referenced by MemObject::setNoDelay().
Member Data Documentation
compositeId
DelayIdComposite::Pointer DelayId::compositeId private
Definition at line 45 of file DelayId.h.
Referenced by DelayId(), bytesIn(), bytesWanted(), delayRead(), and operator==().
markedAsNoDelay
bool DelayId::markedAsNoDelay private
Definition at line 46 of file DelayId.h.
Referenced by setNoDelay().
pool_
unsigned short DelayId::pool_ private
Definition at line 44 of file DelayId.h.
Referenced by DelayId(), operator==(), and pool().
The documentation for this class was generated from the following files:
squid/src/DelayId.h
squid/src/DelayId.cc
squid/src/tests/stub_DelayId.cc