Squid Web Cache: LoadableModule Class Reference
LoadableModule Class Reference
#include <LoadableModule.h>
Public Member Functions
LoadableModule (const SBuf &aName)
~LoadableModule ()
bool loaded () const
const auto & name () const
const auto & error () const
void load ()
void unload ()
Protected Attributes
SBuf theName
SBuf theError
void * theHandle = nullptr
Private Member Functions
void * openModule ()
bool closeModule ()
const char * errorMsg ()
Detailed Description
Definition at line 15 of file LoadableModule.h.
Constructor & Destructor Documentation
LoadableModule()
LoadableModule::LoadableModule (const SBuf & aName) explicit
Definition at line 17 of file LoadableModule.cc.
References TexcHere.
~LoadableModule()
LoadableModule::~LoadableModule ()
Definition at line 26 of file LoadableModule.cc.
References assert, loaded(), and unload().
Member Function Documentation
closeModule()
bool LoadableModule::closeModule () private
Definition at line 70 of file LoadableModule.cc.
References theHandle.
Referenced by unload().
error()
const auto & LoadableModule::error () const inline
Definition at line 23 of file LoadableModule.h.
References theError.
errorMsg()
const char * LoadableModule::errorMsg () private
Definition at line 77 of file LoadableModule.cc.
Referenced by load(), and unload().
load()
void LoadableModule::load ()
Definition at line 40 of file LoadableModule.cc.
References errorMsg(), loaded(), openModule(), TexcHere, and theHandle.
loaded()
bool LoadableModule::loaded () const
Definition at line 34 of file LoadableModule.cc.
References theHandle.
Referenced by ~LoadableModule(), load(), and unload().
name()
const auto & LoadableModule::name () const inline
Definition at line 22 of file LoadableModule.h.
References theName.
openModule()
void * LoadableModule::openModule () private
Definition at line 64 of file LoadableModule.cc.
References SBuf::c_str(), and theName.
Referenced by load().
unload()
void LoadableModule::unload ()
Definition at line 52 of file LoadableModule.cc.
References closeModule(), errorMsg(), loaded(), TexcHere, and theHandle.
Referenced by ~LoadableModule().
Member Data Documentation
theError
SBuf LoadableModule::theError protected
Definition at line 30 of file LoadableModule.h.
Referenced by error().
theHandle
void* LoadableModule::theHandle = nullptr protected
Definition at line 31 of file LoadableModule.h.
Referenced by closeModule(), load(), loaded(), and unload().
theName
SBuf LoadableModule::theName protected
Definition at line 29 of file LoadableModule.h.
Referenced by name(), and openModule().
The documentation for this class was generated from the following files:
squid/src/LoadableModule.h
squid/src/LoadableModule.cc