Squid Web Cache: squid/src/clients/Client.cc File Reference
Client.cc File Reference
#include "squid.h"
#include "acl/FilledChecklist.h"
#include "acl/Gadgets.h"
#include "base/TextException.h"
#include "clients/Client.h"
#include "comm/Connection.h"
#include "comm/forward.h"
#include "comm/Write.h"
#include "error/Detail.h"
#include "errorpage.h"
#include "fd.h"
#include "HttpHdrContRange.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "SquidConfig.h"
#include "StatCounters.h"
#include "Store.h"
#include "tools.h"
#include "adaptation/AccessCheck.h"
#include "adaptation/Answer.h"
#include "adaptation/Iterator.h"
#include "base/AsyncCall.h"
Functions
void purgeEntriesByUrl (HttpRequest *req, const char *url)
static bool sameUrlHosts (const char *url1, const char *url2)
static void purgeEntriesByHeader (HttpRequest *req, const char *reqUrl, Http::Message *rep, Http::HdrType hdr)
Function Documentation
purgeEntriesByHeader()
static void purgeEntriesByHeader (HttpRequest * req, const char * reqUrl, Http::Message * rep, Http::HdrType hdr) static
Definition at line 480 of file Client.cc.
References AnyP::Uri::absolute(), AnyP::Uri::addRelativePath(), SBuf::c_str(), AnyP::Uri::getScheme(), HttpHeader::getStr(), Http::Message::header, HttpRequestMethod::id(), HttpRequest::method, Http::METHOD_CONNECT, AnyP::Uri::path(), AnyP::PROTO_URN, purgeEntriesByUrl(), sameUrlHosts(), HttpRequest::url, and urlIsRelative().
Referenced by Client::maybePurgeOthers().
purgeEntriesByUrl()
void purgeEntriesByUrl (HttpRequest * req, const char * url)
Definition at line 869 of file client_side_reply.cc.
References debugs, Store::Controller::evictIfFound(), HTCP_CLR_INVALIDATION, Http::METHOD_ENUM_END, Http::METHOD_NONE, neighborsHtcpClear(), Store::Root(), storeKeyPublic(), and storeKeyText().
Referenced by Client::maybePurgeOthers(), and purgeEntriesByHeader().
sameUrlHosts()
static bool sameUrlHosts (const char * url1, const char * url2) static
Definition at line 451 of file Client.cc.
Referenced by purgeEntriesByHeader().