Squid Web Cache: squid/src/client_side.cc File Reference
client_side.cc File Reference
#include "squid.h"
#include "acl/FilledChecklist.h"
#include "anyp/Host.h"
#include "anyp/PortCfg.h"
#include "base/AsyncCallbacks.h"
#include "base/Subscription.h"
#include "base/TextException.h"
#include "CachePeer.h"
#include "client_db.h"
#include "client_side.h"
#include "client_side_reply.h"
#include "client_side_request.h"
#include "ClientRequestContext.h"
#include "clientStream.h"
#include "comm.h"
#include "comm/Connection.h"
#include "comm/Loops.h"
#include "comm/Read.h"
#include "comm/TcpAcceptor.h"
#include "comm/Write.h"
#include "CommCalls.h"
#include "compat/socket.h"
#include "debug/Messages.h"
#include "error/ExceptionErrorDetail.h"
#include "errorpage.h"
#include "fd.h"
#include "fde.h"
#include "fqdncache.h"
#include "FwdState.h"
#include "globals.h"
#include "helper.h"
#include "helper/Reply.h"
#include "http.h"
#include "http/one/RequestParser.h"
#include "http/one/TeChunkedParser.h"
#include "http/Stream.h"
#include "HttpHdrContRange.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "internal.h"
#include "ipc/FdNotes.h"
#include "ipc/StartListening.h"
#include "log/access_log.h"
#include "MemBuf.h"
#include "MemObject.h"
#include "mime_header.h"
#include "parser/Tokenizer.h"
#include "proxyp/Header.h"
#include "proxyp/Parser.h"
#include "sbuf/Stream.h"
#include "security/Certificate.h"
#include "security/CommunicationSecrets.h"
#include "security/Io.h"
#include "security/KeyLog.h"
#include "security/NegotiationHistory.h"
#include "servers/forward.h"
#include "SquidConfig.h"
#include "StatCounters.h"
#include "StatHist.h"
#include "Store.h"
#include "TimeOrTag.h"
#include "tools.h"
#include "auth/UserRequest.h"
#include "ClientInfo.h"
#include "MessageDelayPools.h"
#include "ssl/bio.h"
#include "ssl/context_storage.h"
#include "ssl/gadgets.h"
#include "ssl/helper.h"
#include "ssl/ProxyCerts.h"
#include "ssl/ServerBump.h"
#include "ssl/support.h"
#include <climits>
#include <cmath>
#include <limits>
Classes
class ListeningStartedDialer
dials clientListenerConnectionOpened call
Functions
static void clientListenerConnectionOpened (AnyP::PortCfgPointer &s, const Ipc::FdNoteId portTypeNote, const Subscription::Pointer &sub)
process clientHttpConnectionsOpen result
static int clientIsRequestBodyTooLargeForPolicy (int64_t bodyLength)
static void clientUpdateStatHistCounters (const LogTags &logType, int svc_time)
static void clientUpdateStatCounters (const LogTags &logType)
static void clientUpdateHierCounters (HierarchyLogEntry *)
static bool clientPingHasFinished (ping_data const *aPing)
void prepareLogWithRequestDetails (HttpRequest *, const AccessLogEntryPointer &)
static void ClientSocketContextPushDeferredIfNeeded (Http::StreamPointer deferredRequest, ConnStateData *conn)
char * skipLeadingSpace (char *aString)
void httpRequestFree (void *data)
void clientSetKeepaliveFlag (ClientHttpRequest *http)
decide whether to expect multiple requests on the corresponding connection
void clientPackTermBound (String boundary, MemBuf *mb)
put terminating boundary for multiparts to the buffer
void clientPackRangeHdr (const HttpReplyPointer &rep, const HttpHdrRangeSpec *spec, String boundary, MemBuf *mb)
append a "part" HTTP header (as in a multi-part/range reply) to the buffer
void clientSocketRecipient (clientStreamNode *node, ClientHttpRequest *http, HttpReply *rep, StoreIOBuffer receivedData)
void clientSocketDetach (clientStreamNode *node, ClientHttpRequest *http)
const char * findTrailingHTTPVersion (const char *uriAndHTTPVersion, const char *end)
static char * prepareAcceleratedURL (ConnStateData *conn, const Http1::RequestParserPointer &hp)
static char * buildUrlFromHost (ConnStateData *conn, const Http1::RequestParserPointer &hp)
static char * prepareTransparentURL (ConnStateData *conn, const Http1::RequestParserPointer &hp)
void clientProcessRequestFinished (ConnStateData *conn, const HttpRequest::Pointer &request)
void clientProcessRequest (ConnStateData *conn, const Http1::RequestParserPointer &hp, Http::Stream *context)
void httpAccept (const CommAcceptCbParams &params)
static bool httpsCreate (const ConnStateData *connState, const Security::ContextPointer &ctx)
Create TLS connection structure and update fd_table.
static void clientNegotiateSSL (int fd, void *data)
static void httpsEstablish (ConnStateData *connState, const Security::ContextPointer &ctx)
static void httpsSslBumpAccessCheckDone (Acl::Answer answer, void *data)
static void httpsAccept (const CommAcceptCbParams &params)
static void httpsSslBumpStep2AccessCheckDone (Acl::Answer answer, void *data)
static bool OpenedHttpSocket (const Comm::ConnectionPointer &c, const Ipc::FdNoteId portType)
check FD after clientHttp[s]ConnectionOpened, adjust HttpSockets as needed
static bool AddOpenedHttpSocket (const Comm::ConnectionPointer &conn)
find any unused HttpSockets[] slot and store fd there or return false
static void clientHttpConnectionsOpen (void)
void clientStartListeningOn (AnyP::PortCfgPointer &port, const RefCount< CommCbFunPtrCallT< CommAcceptCbPtrFun > > &subCall, const Ipc::FdNoteId fdNote)
accept requests to a given port and inform subCall about them
void clientOpenListenSockets (void)
void clientConnectionsClose ()
int varyEvaluateMatch (StoreEntry *entry, HttpRequest *request)
ACLFilledChecklist::MakingPointer clientAclChecklistCreate (const acl_access *acl, ClientHttpRequest *http)
void clientAclChecklistFill (ACLFilledChecklist &checklist, ClientHttpRequest *http)
std::ostream & operator<< (std::ostream &os, const ConnStateData::PinnedIdleContext &pic)
std::ostream & operator<< (std::ostream &os, const ConnStateData::ServerConnectionContext &scc)
Variables
static IOACB httpAccept
Function Documentation
AddOpenedHttpSocket()
static bool AddOpenedHttpSocket (const Comm::ConnectionPointer & conn) static
Definition at line 3234 of file client_side.cc.
References Comm::Connection::fd, HttpSockets, and NHttpSockets.
Referenced by clientListenerConnectionOpened().
buildUrlFromHost()
static char * buildUrlFromHost (ConnStateData * conn, const Http1::RequestParserPointer & hp) static
Definition at line 1179 of file client_side.cc.
References AnyP::UriScheme::image(), SBuf::length(), AnyP::ProtocolVersion::protocol, SQUIDSBUFPH, SQUIDSBUFPRINT, Server::transferProtocol, and xcalloc().
Referenced by ConnStateData::prepareTlsSwitchingURL(), and prepareTransparentURL().
clientAclChecklistCreate()
ACLFilledChecklist::MakingPointer clientAclChecklistCreate (const acl_access * acl, ClientHttpRequest * http)
Definition at line 3458 of file client_side.cc.
References clientAclChecklistFill(), and ACLFilledChecklist::Make().
Referenced by ClientRequestContext::checkNoCache(), ClientRequestContext::clientAccessCheck(), ClientRequestContext::clientAccessCheck2(), clientFollowXForwardedForCheck(), ClientRequestContext::clientRedirectStart(), ClientRequestContext::clientStoreIdStart(), clientReplyContext::processReplyAccess(), and ClientRequestContext::sslBumpAccessCheck().
clientAclChecklistFill()
void clientAclChecklistFill (ACLFilledChecklist & checklist, ClientHttpRequest * http)
Definition at line 3466 of file client_side.cc.
References ACLFilledChecklist::al, ClientHttpRequest::al, assert, ClientHttpRequest::getConn(), ClientHttpRequest::log_uri, ACLFilledChecklist::request, ClientHttpRequest::request, ACLFilledChecklist::setConn(), ACLFilledChecklist::setRequest(), ACLFilledChecklist::syncAle(), and ACLFilledChecklist::updateAle().
Referenced by clientReplyContext::blockedHit(), clientAclChecklistCreate(), DelayId::DelayClient(), ConnStateData::fillChecklist(), clientReplyContext::fillChecklist(), Http::Stream::sendStartOfMessage(), and ConnStateData::serveDelayedError().
clientConnectionsClose()
void clientConnectionsClose (void)
Definition at line 3370 of file client_side.cc.
References CodeContext::Current(), debugs, HttpPortList, HttpSockets, Important, NHttpSockets, CodeContext::Reset(), and Ftp::StopListening().
Referenced by releaseServerSockets(), and serverConnectionsClose().
clientHttpConnectionsOpen()
static void clientHttpConnectionsOpen (void) static
Definition at line 3245 of file client_side.cc.
References SquidConfig::accessList, Ssl::GlobalContextStorage::addLocalStorage(), assert, clientStartListeningOn(), commCbCall(), Config, CodeContext::Current(), DBG_CRITICAL, DBG_IMPORTANT, debugs, Debug::Extra(), Ipc::fdnHttpSocket, Ipc::fdnHttpsSocket, httpAccept, HttpPortList, httpsAccept(), AnyP::UriScheme::image(), MAXTCPLISTENPORTS, NHttpSockets, AnyP::PROTO_HTTP, AnyP::PROTO_HTTPS, CodeContext::Reset(), SquidConfig::ssl_bump, and Ssl::TheGlobalContextStorage().
Referenced by clientOpenListenSockets().
clientIsRequestBodyTooLargeForPolicy()
int clientIsRequestBodyTooLargeForPolicy (int64_t bodyLength) static
Definition at line 686 of file client_side.cc.
References Config, and SquidConfig::maxRequestBodySize.
Referenced by clientProcessRequest(), and ConnStateData::handleChunkedRequestBody().
clientListenerConnectionOpened()
static void clientListenerConnectionOpened (AnyP::PortCfgPointer & s, const Ipc::FdNoteId portTypeNote, const Subscription::Pointer & sub) static
Definition at line 3322 of file client_side.cc.
References AddOpenedHttpSocket(), DBG_IMPORTANT, debugs, Debug::Extra(), Important, Comm::IsConnOpen(), Must, OpenedHttpSocket(), opt_foreground, opt_no_daemon, AsyncJob::Start(), and xstrerr().
Referenced by clientStartListeningOn().
clientNegotiateSSL()
static void clientNegotiateSSL (int fd, void * data) static
negotiate an SSL connection
Definition at line 2279 of file client_side.cc.
References ConnStateData::acceptTls(), Server::clientConnection, clientNegotiateSSL(), Comm::Connection::close(), COMM_SELECT_READ, COMM_SELECT_WRITE, debugs, DebugStream(), Pipeline::empty(), Debug::Enabled(), ERR_SECURE_ACCEPT_FAIL, Debug::Extra(), Comm::Connection::fd, fd_table, Pipeline::front(), Important, Security::IoResult::ioError, Security::IoResult::ioSuccess, Security::IoResult::ioWantRead, Security::IoResult::ioWantWrite, Security::IssuerName(), Http::METHOD_CONNECT, Must, Server::pipeline, Server::readSomeData(), Security::NegotiationHistory::retrieveNegotiatedInfo(), Security::SessionIsResumed(), Comm::SetSelect(), Security::SubjectName(), Comm::Connection::tlsNegotiations(), and ConnStateData::updateError().
Referenced by clientNegotiateSSL(), ConnStateData::doPeekAndSpliceStep(), ConnStateData::getSslContextDone(), and httpsEstablish().
clientOpenListenSockets()
void clientOpenListenSockets (void)
Definition at line 3360 of file client_side.cc.
References clientHttpConnectionsOpen(), fatal(), NHttpSockets, and Ftp::StartListening().
Referenced by serverConnectionsOpen().
clientPackRangeHdr()
void clientPackRangeHdr (const HttpReplyPointer & rep, const HttpHdrRangeSpec * spec, String boundary, MemBuf * mb)
Definition at line 709 of file client_side.cc.
References MemBuf::append(), Packable::appendf(), assert, HttpHeader::clean(), Http::Message::content_length, Http::CONTENT_TYPE, debugs, HttpHeader::getStr(), HttpHeader::has(), Http::Message::header, hoReply, httpHeaderAddContRange(), HttpHeader::packInto(), HttpHeader::putStr(), SQUIDSTRINGPH, and SQUIDSTRINGPRINT.
Referenced by ClientHttpRequest::mRangeCLen(), and Http::Stream::packRange().
clientPackTermBound()
void clientPackTermBound (String boundary, MemBuf * mb)
Definition at line 702 of file client_side.cc.
References Packable::appendf(), debugs, MemBuf::size, SQUIDSTRINGPH, and SQUIDSTRINGPRINT.
Referenced by ClientHttpRequest::mRangeCLen(), and Http::Stream::packRange().
clientPingHasFinished()
bool clientPingHasFinished (ping_data const * aPing) static
Definition at line 254 of file client_side.cc.
References ping_data::start, and ping_data::stop.
Referenced by clientUpdateHierCounters().
clientProcessRequest()
void clientProcessRequest (ConnStateData * conn, const Http1::RequestParserPointer & hp, Http::Stream * context)
Definition at line 1569 of file client_side.cc.
References ClientHttpRequest::Flags::accel, RequestFlags::accelerated, ClientHttpRequest::al, assert, HttpRequest::auth_user_request, Http::Message::body_pipe, ClientHttpRequest::calloutContext, HttpRequest::checkEntityFraming(), ClientHttpRequest::checkForInternalAccess(), HttpHeader::chunked(), clientIsRequestBodyTooLargeForPolicy(), clientProcessRequestFinished(), clientSetKeepaliveFlag(), Http::Message::content_length, debugs, ClientHttpRequest::doCallouts(), ERR_INVALID_REQ, ERR_TOO_BIG, ERR_UNSUP_REQ, ConnStateData::expectRequestBody(), ConnStateData::flags, ClientHttpRequest::flags, HttpRequest::flags, ConnStateData::getAuth(), Http::Stream::getClientReplyContext(), HttpHeader::getInt64(), RefCount< C >::getRaw(), ConnStateData::handleRequestBodyData(), Http::Message::header, Http::Stream::http, Http::Message::http_ver, AnyP::ProtocolVersion::major, HttpRequest::manager(), Http::MAX_FORWARDS, Http::Stream::mayUseConnection(), HttpRequest::method, Http::METHOD_CONNECT, Http::METHOD_OPTIONS, AnyP::ProtocolVersion::minor, RequestFlags::noDirect, ClientHttpRequest::Out::offset, ClientHttpRequest::out, ConnStateData::port, BodyPipe::productionEnded(), AnyP::PROTO_HTTPS, AnyP::ProtocolVersion::protocol, Http::Stream::pullData(), ConnStateData::quitAfterError(), ConnStateData::readMore, ClientHttpRequest::request, Http::scContentTooLarge, Http::scNone, Http::scNotImplemented, ConnStateData::serveDelayedError(), clientReplyContext::setReplyToError(), Http::Message::sources, Http::Message::srcFtp, Http::Message::srcHttp, Http::Message::srcHttps, RequestFlags::sslBumped, ConnStateData::switchedToHttps(), and urlCheckRequest().
Referenced by Ftp::Server::doProcessRequest(), Http::One::Server::proceedAfterBodyContinuation(), and Http::One::Server::processParsedRequest().
clientProcessRequestFinished()
void clientProcessRequestFinished (ConnStateData * conn, const HttpRequest::Pointer & request)
Definition at line 1553 of file client_side.cc.
References Server::clientConnection, comm_reset_close(), debugs, ConnStateData::flags, HttpRequest::flags, Comm::IsConnOpen(), ConnStateData::readMore, and RequestFlags::resetTcp.
Referenced by Http::One::Server::buildHttpRequest(), clientProcessRequest(), ConnStateData::fakeAConnectRequest(), ConnStateData::initiateTunneledRequest(), and Http::One::Server::processParsedRequest().
clientSetKeepaliveFlag()
void clientSetKeepaliveFlag (ClientHttpRequest * http)
clientSetKeepaliveFlag() sets request->flags.proxyKeepalive. This is the client-side persistent connection flag. We need to set this relatively early in the request processing to handle hacks for broken servers and clients.
Definition at line 674 of file client_side.cc.
References debugs, HttpRequest::flags, Http::Message::http_ver, HttpRequest::method, Http::Message::persistent(), RequestFlags::proxyKeepalive, and ClientHttpRequest::request.
Referenced by clientProcessRequest(), and Ftp::Server::doProcessRequest().
ClientSocketContextPushDeferredIfNeeded()
static void ClientSocketContextPushDeferredIfNeeded (Http::StreamPointer deferredRequest, ConnStateData * conn) static
If the client stream is waiting on a socket write to occur, then
NO data is allowed to have been sent.
defer now.
otherwise, the request is still active in a callbacksomewhere, and we are done
Definition at line 872 of file client_side.cc.
References assert, Server::clientConnection, clientSocketRecipient, and debugs.
Referenced by ConnStateData::doneWithControlMsg(), and ConnStateData::kick().
clientSocketDetach()
void clientSocketDetach (clientStreamNode * node, ClientHttpRequest * http)
Called when a downstream node is no longer interested in our data. As we are a terminal node, this means on aborts only
Definition at line 836 of file client_side.cc.
References assert, cbdataReferenceValid(), clientStreamDetach(), and node::next.
clientSocketRecipient()
void clientSocketRecipient (clientStreamNode * node, ClientHttpRequest * http, HttpReply * rep, StoreIOBuffer receivedData)
Write a chunk of data to a client socket. If the reply is present, send the reply headers down the wire too, and clean them up when finished. Pre-condition: The request is one backed by a connection, not an internal request. data context is not NULL There are no more entries in the stream chain.
Definition at line 800 of file client_side.cc.
References assert, HttpControlMsgSink::cbControlMsgSent, cbdataReferenceValid(), Server::clientConnection, Pipeline::front(), ClientHttpRequest::getConn(), ConnStateData::handleReply(), Comm::IsConnOpen(), node::next, and Server::pipeline.
clientStartListeningOn()
void clientStartListeningOn (AnyP::PortCfgPointer & port, const RefCount< CommCbFunPtrCallT< CommAcceptCbPtrFun > > & subCall, const Ipc::FdNoteId fdNote)
Definition at line 3294 of file client_side.cc.
References assert, asyncCall(), clientListenerConnectionOpened(), COMM_INTERCEPTION, COMM_NONBLOCKING, COMM_REUSEPORT, COMM_TRANSPARENT, HttpSockets, Comm::Connection::local, MAXTCPLISTENPORTS, NHttpSockets, port, and Ipc::StartListening().
Referenced by clientHttpConnectionsOpen(), and Ftp::StartListening().
clientUpdateHierCounters()
void clientUpdateHierCounters (HierarchyLogEntry * someEntry) static
Definition at line 263 of file client_side.cc.
References StatCounters::cd, CD_PARENT_HIT, CD_SIBLING_HIT, clientPingHasFinished(), CLOSEST_DIRECT, CLOSEST_PARENT, CLOSEST_PARENT_MISS, HierarchyLogEntry::code, StatHist::count(), FIRST_PARENT_MISS, StatCounters::icp, StatCounters::netdb, PARENT_HIT, HierarchyLogEntry::ping, StatCounters::query_timeouts, StatCounters::querySvcTime, SIBLING_HIT, ping_data::start, statCounter, ping_data::stop, ping_data::timeout, StatCounters::times_used, and tvSubUsec().
Referenced by ClientHttpRequest::updateCounters().
clientUpdateStatCounters()
void clientUpdateStatCounters (const LogTags & logType) static
Definition at line 198 of file client_side.cc.
References StatCounters::client_http, StatCounters::disk_hits, StatCounters::hits, LogTags::isTcpHit(), LOG_TCP_HIT, LOG_TCP_MEM_HIT, StatCounters::mem_hits, LogTags::oldType, StatCounters::requests, and statCounter.
Referenced by ClientHttpRequest::updateCounters().
clientUpdateStatHistCounters()
void clientUpdateStatHistCounters (const LogTags & logType, int svc_time) static
The idea here is not to be complete, but to get service times for only well-defined types. For example, we don't include LOG_TCP_REFRESH_FAIL because its not really a cache hit (we tried to validate it, but failed).
Definition at line 212 of file client_side.cc.
References StatCounters::allSvcTime, StatCounters::client_http, StatHist::count(), LogTags::oldType, and statCounter.
Referenced by ClientHttpRequest::updateCounters().
findTrailingHTTPVersion()
const char * findTrailingHTTPVersion (const char * uriAndHTTPVersion, const char * end)
'end' defaults to NULL for backwards compatibility remove default value if we ever get rid of NULL-terminated request buffers.
Definition at line 1052 of file client_side.cc.
References assert, and xisspace.
Referenced by HttpRequest::parseFirstLine().
httpAccept()
void httpAccept (const CommAcceptCbParams & params)
Handle a new connection on an HTTP socket.
Definition at line 2239 of file client_side.cc.
References Assure, CommCommonCbParams::conn, debugs, Comm::Connection::fd, fd_note(), CommCommonCbParams::flag, MasterXaction::MakePortful(), Http::NewServer(), Comm::OK, CommAcceptCbParams::port, AsyncJob::Start(), CommCommonCbParams::xerrno, and xstrerr().
httpRequestFree()
void httpRequestFree (void * data)
Definition at line 475 of file client_side.cc.
References assert.
Referenced by Http::Stream::~Stream().
httpsAccept()
static void httpsAccept (const CommAcceptCbParams & params) static
handle a new HTTPS connection
Definition at line 2441 of file client_side.cc.
References Assure, CommCommonCbParams::conn, debugs, Comm::Connection::fd, fd_note(), CommCommonCbParams::flag, MasterXaction::MakePortful(), Https::NewServer(), Comm::OK, CommAcceptCbParams::port, AsyncJob::Start(), CommCommonCbParams::xerrno, and xstrerr().
Referenced by clientHttpConnectionsOpen().
httpsCreate()
static bool httpsCreate (const ConnStateData * connState, const Security::ContextPointer & ctx) static
Definition at line 2264 of file client_side.cc.
References Server::clientConnection, Security::CreateServerSession(), DBG_IMPORTANT, debugs, and ConnStateData::port.
Referenced by ConnStateData::getSslContextDone(), httpsEstablish(), and ConnStateData::startPeekAndSplice().
httpsEstablish()
static void httpsEstablish (ConnStateData * connState, const Security::ContextPointer & ctx) static
If Security::ContextPointer is given, starts reading the TLS handshake. Otherwise, calls switchToHttps to generate a dynamic Security::ContextPointer.
Definition at line 2395 of file client_side.cc.
References assert, Server::clientConnection, clientNegotiateSSL(), COMM_SELECT_READ, Config, Comm::Connection::fd, httpsCreate(), SquidConfig::request, ConnStateData::resetReadTimeout(), Comm::SetSelect(), and SquidConfig::Timeout.
Referenced by ConnStateData::postHttpsAccept().
httpsSslBumpAccessCheckDone()
static void httpsSslBumpAccessCheckDone (Acl::Answer answer, void * data) static
A callback function to use with the ACLFilledChecklist callback.
Definition at line 2413 of file client_side.cc.
References Acl::Answer::allowed(), Ssl::bumpMode(), Ssl::bumpSplice, Ssl::bumpTerminate, Server::clientConnection, Comm::Connection::close(), debugs, ConnStateData::fakeAConnectRequest(), Server::inBuf, ConnStateData::isOpen(), Acl::Answer::kind, and ConnStateData::sslBumpMode.
Referenced by ConnStateData::postHttpsAccept().
httpsSslBumpStep2AccessCheckDone()
static void httpsSslBumpStep2AccessCheckDone (Acl::Answer answer, void * data) static
Definition at line 2900 of file client_side.cc.
References Ssl::ServerBump::act, Acl::Answer::allowed(), assert, Ssl::bumpSplice, Ssl::bumpTerminate, Server::clientConnection, Comm::Connection::close(), debugs, Pipeline::front(), ConnStateData::isOpen(), Acl::Answer::kind, Server::pipeline, ConnStateData::serverBump(), ConnStateData::splice(), ConnStateData::sslBumpMode, ConnStateData::startPeekAndSplice(), and Ssl::ServerBump::step2.
Referenced by ConnStateData::startPeekAndSplice().
OpenedHttpSocket()
static bool OpenedHttpSocket (const Comm::ConnectionPointer & c, const Ipc::FdNoteId portType) static
Definition at line 3217 of file client_side.cc.
References fatalf(), HttpSockets, Comm::IsConnOpen(), Must, and NHttpSockets.
Referenced by clientListenerConnectionOpened().
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const ConnStateData::PinnedIdleContext & pic)
Definition at line 4009 of file client_side.cc.
References ConnStateData::PinnedIdleContext::connection, and ConnStateData::PinnedIdleContext::request.
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const ConnStateData::ServerConnectionContext & scc)
Definition at line 4015 of file client_side.cc.
prepareAcceleratedURL()
static char * prepareAcceleratedURL (ConnStateData * conn, const Http1::RequestParserPointer & hp) static
Definition at line 1075 of file client_side.cc.
References ConnStateData::abortRequestParsing(), CharacterSet::ALPHA, SBuf::append(), SBuf::appendf(), SBuf::chop(), Server::clientConnection, debugs, CharacterSet::DIGIT, CharacterSet::HEXDIG, AnyP::UriScheme::image(), SBuf::isEmpty(), SBuf::length(), Comm::Connection::local, MAX_IPSTRLEN, SBuf::npos, ConnStateData::port, Ip::Address::port(), AnyP::ProtocolVersion::protocol, SBuf::rbegin(), SBuf::rfind(), Http::scBadRequest, SQUIDSBUFPH, SQUIDSBUFPRINT, Ip::Address::toHostStr(), Server::transferProtocol, and xcalloc().
Referenced by ConnStateData::parseHttpRequest().
prepareLogWithRequestDetails()
void prepareLogWithRequestDetails (HttpRequest * request, const AccessLogEntryPointer & aLogEntry)
Definition at line 322 of file client_side.cc.
References AccessLogEntry::adapt, AccessLogEntry::Headers::adapted_request, HttpRequest::adaptLogHistory(), assert, MemBuf::buf, AccessLogEntry::cache, MemBuf::clean(), Config, HttpRequest::dnsWait, HttpRequest::error, HttpRequest::extacl_user, AccessLogEntry::CacheDetails::extuser, Http::Message::header, AccessLogEntry::headers, AccessLogEntry::hier, HttpRequest::hier, AccessLogEntry::http, Http::Message::http_ver, AccessLogEntry::icap, HttpRequest::icapHistory(), MemBuf::init(), AccessLogEntry::AdaptationDetails::last_meta, Adaptation::History::lastMeta, SquidConfig::log_mime_hdrs, AccessLogEntry::HttpDetails::method, HttpRequest::method, SquidConfig::onoff, HttpHeader::packInto(), AccessLogEntry::IcapLogEntry::processingTime, AccessLogEntry::Headers::request, AccessLogEntry::request, MemBuf::reset(), String::termedBuf(), AccessLogEntry::HttpDetails::version, and xstrdup.
Referenced by Adaptation::Icap::ModXact::finalizeLogInfo(), and ClientHttpRequest::logRequest().
prepareTransparentURL()
static char * prepareTransparentURL (ConnStateData * conn, const Http1::RequestParserPointer & hp) static
Definition at line 1230 of file client_side.cc.
References buildUrlFromHost(), Server::clientConnection, debugs, AnyP::UriScheme::image(), Comm::Connection::local, MAX_IPSTRLEN, Ip::Address::port(), AnyP::ProtocolVersion::protocol, SQUIDSBUFPH, SQUIDSBUFPRINT, Ip::Address::toHostStr(), Server::transferProtocol, and xcalloc().
Referenced by ConnStateData::parseHttpRequest().
skipLeadingSpace()
char * skipLeadingSpace (char * aString)
Definition at line 1036 of file client_side.cc.
References xisspace.
varyEvaluateMatch()
int varyEvaluateMatch (StoreEntry * entry, HttpRequest * request)
Definition at line 3394 of file client_side.cc.
References SBuf::clear(), SBuf::cmp(), DBG_IMPORTANT, debugs, MemObject::freshestReply(), HttpHeader::has(), Http::HDR_X_ACCELERATOR_VARY, Http::Message::header, httpMakeVaryMark(), SBuf::isEmpty(), StoreEntry::mem(), StoreEntry::mem_obj, MemObject::urlXXX(), Http::VARY, VARY_CANCEL, HttpRequest::vary_headers, MemObject::vary_headers, VARY_MATCH, VARY_NONE, and VARY_OTHER.
Referenced by clientReplyContext::cacheHit().
Variable Documentation
httpAccept
IOACB httpAccept static
Definition at line 185 of file client_side.cc.
Referenced by clientHttpConnectionsOpen().