Squid Web Cache: squid/src/client_side_request.h File Reference
client_side_request.h File Reference
#include "AccessLogEntry.h"
#include "acl/FilledChecklist.h"
#include "client_side.h"
#include "http/forward.h"
#include "HttpHeaderRange.h"
#include "log/forward.h"
#include "LogTags.h"
#include "Store.h"
#include "adaptation/forward.h"
#include "adaptation/Initiator.h"
Classes
class ClientHttpRequest
struct ClientHttpRequest::Out
struct ClientHttpRequest::Flags
struct ClientHttpRequest::Redirect
Functions
char * clientConstructTraceEcho (ClientHttpRequest *)
ACLFilledChecklist::MakingPointer clientAclChecklistCreate (const acl_access *, ClientHttpRequest *)
void clientAclChecklistFill (ACLFilledChecklist &, ClientHttpRequest *)
void clientAccessCheck (ClientHttpRequest *)
void tunnelStart (ClientHttpRequest *)
Function Documentation
clientAccessCheck()
void clientAccessCheck (ClientHttpRequest *)
clientAclChecklistCreate()
ACLFilledChecklist::MakingPointer clientAclChecklistCreate (const acl_access * acl, ClientHttpRequest * http)
Definition at line 3457 of file client_side.cc.
References clientAclChecklistFill(), and ACLFilledChecklist::Make().
Referenced by ClientRequestContext::checkNoCache(), ClientRequestContext::clientAccessCheck(), ClientRequestContext::clientAccessCheck2(), clientFollowXForwardedForCheck(), ClientRequestContext::clientRedirectStart(), ClientRequestContext::clientStoreIdStart(), clientReplyContext::processReplyAccess(), and ClientRequestContext::sslBumpAccessCheck().
clientAclChecklistFill()
void clientAclChecklistFill (ACLFilledChecklist & checklist, ClientHttpRequest * http)
Definition at line 3465 of file client_side.cc.
References ACLFilledChecklist::al, ClientHttpRequest::al, assert, ClientHttpRequest::getConn(), ClientHttpRequest::log_uri, ACLFilledChecklist::request, ClientHttpRequest::request, ACLFilledChecklist::setConn(), ACLFilledChecklist::setRequest(), ACLFilledChecklist::syncAle(), and ACLFilledChecklist::updateAle().
Referenced by clientReplyContext::blockedHit(), clientAclChecklistCreate(), DelayId::DelayClient(), ConnStateData::fillChecklist(), clientReplyContext::fillChecklist(), Http::Stream::sendStartOfMessage(), and ConnStateData::serveDelayedError().
clientConstructTraceEcho()
char * clientConstructTraceEcho (ClientHttpRequest *)
tunnelStart()
void tunnelStart (ClientHttpRequest * http)
Definition at line 1259 of file tunnel.cc.
References SquidConfig::accessList, ACLFilledChecklist::al, ClientHttpRequest::al, StatCounters::all, HttpRequest::client_addr, Server::clientConnection, AccessLogEntry::HttpDetails::code, Config, debugs, DelayId::DelayClient(), Acl::Answer::denied(), ERR_FORWARDING_DENIED, errorSend(), ACLChecklist::fastCheck(), ClientHttpRequest::getConn(), AccessLogEntry::http, TunnelStateData::http, Http::Message::http_ver, Ip::Address::isNoAddr(), LOG_TCP_TUNNEL, ClientHttpRequest::log_uri, HttpRequest::method, SquidConfig::miss, ACLFilledChecklist::my_addr, HttpRequest::my_addr, MYNAME, StatCounters::other, ClientHttpRequest::request, TunnelStateData::request, StatCounters::requests, Http::scForbidden, StatCounters::server, TunnelStateData::server, TunnelStateData::Connection::setDelayId(), ACLFilledChecklist::src_addr, PeerSelectionInitiator::startSelectingDestinations(), statCounter, ACLFilledChecklist::syncAle(), ClientHttpRequest::updateLoggingTags(), ClientHttpRequest::uri, and TunnelStateData::url.
Referenced by ClientHttpRequest::processRequest().