Squid Web Cache: squid/lib/snmplib/coexistance.c File Reference
coexistance.c File Reference
#include "squid.h"
#include "asn1.h"
#include "snmp.h"
#include "snmp_api_error.h"
#include "snmp_error.h"
#include "snmp_pdu.h"
#include "snmp_vars.h"
#include "util.h"
Functions
int snmp_coexist_V2toV1 (struct snmp_pdu *PDU)
Function Documentation
snmp_coexist_V2toV1()
int snmp_coexist_V2toV1 (struct snmp_pdu * PDU)
Definition at line 108 of file coexistance.c.
References snmp_pdu::command, snmp_pdu::max_repetitions, snmp_pdu::non_repeaters, SNMP_PDU_GET, SNMP_PDU_GETBULK, SNMP_PDU_GETNEXT, snmp_set_api_error(), SNMPERR_PDU_TRANSLATION, and snmplib_debug().
Referenced by snmpDecodePacket().