Squid Web Cache: squid/src/security/CommunicationSecrets.cc File Reference
CommunicationSecrets.cc File Reference
#include "squid.h"
#include "base/CharacterSet.h"
#include "base/IoManip.h"
#include "security/CommunicationSecrets.h"
#include "security/Session.h"
#include <ostream>
Functions
static void PrintSecret (std::ostream &os, const SBuf &secret)
writes the given secret (in hex) or, if there is no secret, a placeholder
static void IgnorePlaceholder (SBuf &secret)
Function Documentation
IgnorePlaceholder()
static void IgnorePlaceholder (SBuf & secret) static
Clears the given secret if it is likely to contain no secret information. When asked for a secret too early, OpenSSL (successfully!) returns a copy of the secret storage (filled with zeros) rather than an actual secret.
Definition at line 104 of file CommunicationSecrets.cc.
References CharacterSet::add(), SBuf::clear(), SBuf::findFirstNotOf(), and SBuf::npos.
Referenced by Security::CommunicationSecrets::getClientRandom(), Security::CommunicationSecrets::getMasterKey(), and Security::CommunicationSecrets::getSessionId().
PrintSecret()
static void PrintSecret (std::ostream & os, const SBuf & secret) static
Definition at line 66 of file CommunicationSecrets.cc.
References SBuf::isEmpty(), SBuf::length(), PrintHex(), and SBuf::rawContent().
Referenced by Security::CommunicationSecrets::record().