Squid Web Cache: squid/src/comm/minimal.cc File Reference
minimal.cc File Reference
#include "squid.h"
#include "comm.h"
#include "debug/Stream.h"
#include "fd.h"
Functions
void fd_open (const int fd, unsigned int, const char *description)
void fd_close (const int fd)
void commSetCloseOnExec (int)
Function Documentation
commSetCloseOnExec()
void commSetCloseOnExec (int fd)
On platforms where FD_CLOEXEC is defined, close the given descriptor during a function call from the exec(3) family. Otherwise, do nothing; the platform itself may close-on-exec by default (e.g., MS Win32 is said to do that at https://devblogs.microsoft.com/oldnewthing/20111216-00/?p=8873); other platforms are unsupported. Callers that want close-on-exec behavior must call this function on all platforms and are not responsible for the outcome on platforms without FD_CLOEXEC.
Definition at line 27 of file minimal.cc.
References assert.
fd_close()
void fd_close (const int fd)
Definition at line 21 of file minimal.cc.
References debugs.
Referenced by comm_close_complete(), DiskThreadsDiskFile::doClose(), file_close(), CommIO::NotifyIOClose(), and DebugFile::reset().
fd_open()
void fd_open (const int fd, unsigned int type, const char * description)
Definition at line 15 of file minimal.cc.
References debugs.
Referenced by Comm::TcpAcceptor::acceptInto(), comm_init_opened(), comm_open_uds(), ConfigureDebugging(), file_open(), CommIO::Initialize(), ipc_thread_1(), ipcCreate(), DiskThreadsDiskFile::openDone(), DebugFile::reset(), and Comm::SelectLoopInit().