Squid Web Cache: squid/src/comm.h File Reference
comm.h File Reference
#include "comm/IoCallback.h"
#include "CommCalls.h"
#include "StoreIOBuffer.h"
Classes
class CommSelectEngine
Namespaces
namespace Ip
Macros
#define comm_close(x) (_comm_close((x), __FILE__, __LINE__))
Functions
bool comm_iocallbackpending (void)
int commSetNonBlocking (int fd)
int commUnsetNonBlocking (int fd)
void commSetCloseOnExec (int fd)
void _comm_close (int fd, char const *file, int line)
void old_comm_reset_close (int fd)
void comm_reset_close (const Comm::ConnectionPointer &conn)
int comm_connect_addr (int sock, const Ip::Address &addr)
void comm_init (void)
void comm_exit (void)
int comm_open (int, int, Ip::Address &, int, const char *note)
int comm_open_uds (int sock_type, int proto, struct sockaddr_un *addr, int flags)
Create a unix-domain socket (UDS) that only supports FD_MSGHDR I/O.
void comm_import_opened (const Comm::ConnectionPointer &, const char *note, struct addrinfo *AI)
update Comm state after getting a comm_open() FD from another process
int comm_open_listener (int sock_type, int proto, Ip::Address &addr, int flags, const char *note)
void comm_open_listener (int sock_type, int proto, Comm::ConnectionPointer &conn, const char *note)
unsigned short comm_local_port (int fd)
int comm_udp_sendto (int sock, const Ip::Address &to, const void *buf, int buflen)
void commCallCloseHandlers (int fd)
void commUnsetFdTimeout (int fd)
clear a timeout handler by FD number
void commSetConnTimeout (const Comm::ConnectionPointer &, time_t seconds, AsyncCall::Pointer &)
void commUnsetConnTimeout (const Comm::ConnectionPointer &)
int ignoreErrno (int)
void commCloseAllSockets (void)
void checkTimeouts (void)
AsyncCall::Pointer comm_add_close_handler (int fd, CLCB *, void *)
void comm_add_close_handler (int fd, AsyncCall::Pointer &)
void comm_remove_close_handler (int fd, CLCB *, void *)
void comm_remove_close_handler (int fd, AsyncCall::Pointer &)
int comm_udp_recvfrom (int fd, void *buf, size_t len, int flags, Ip::Address &from)
int comm_udp_recv (int fd, void *buf, size_t len, int flags)
ssize_t comm_udp_send (int s, const void *buf, size_t len, int flags)
bool comm_has_incomplete_write (int)
void commStartHalfClosedMonitor (int fd)
Start waiting for a possibly half-closed connection to close.
bool commHasHalfClosedMonitor (int fd)
checks whether we are waiting for possibly half-closed connection to close
void commMarkHalfClosed (int fd)
bool commIsHalfClosed (int fd)
Macro Definition Documentation
comm_close
#define comm_close (x) (_comm_close((x), __FILE__, __LINE__))
Definition at line 36 of file comm.h.
Function Documentation
_comm_close()
void _comm_close (int fd, char const * file, int line)
Definition at line 839 of file comm.cc.
References assert, asyncCall(), callDialer(), fde::_fde_flags::close_request, fde::closing(), comm_close_complete(), comm_empty_os_read_buffers(), COMM_SELECT_READ, COMM_SELECT_WRITE, commCallCloseHandlers(), commHasHalfClosedMonitor(), COMMIO_FD_READCB, COMMIO_FD_WRITECB, commStartTlsClose(), commStopHalfClosedMonitor(), commUnsetFdTimeout(), DBG_IMPORTANT, debugs, Comm::ERR_CLOSING, FD_FILE, fd_table, fde::flags, fde::_fde_flags::harshClosureRequested, isOpen(), fde::_fde_flags::open, reconfiguring, ScheduleCallHere, BandwidthBucket::SelectBucket(), Comm::SetSelect(), shutting_down, Squid_MaxFD, fde::ssl, and fde::type.
checkTimeouts()
void checkTimeouts (void)
Definition at line 1494 of file comm.cc.
References AlreadyTimedOut(), Biggest_FD, fde::closing(), fde::codeContext, comm_close, Comm::COMM_ERROR, COMM_SELECT_WRITE, COMMIO_FD_WRITECB, debugs, fd_table, Comm::HandleWrite, MessageBucket::quota(), CodeContext::Reset(), ScheduleCallHere, BandwidthBucket::selectWaiting, Comm::SetSelect(), fde::timeoutHandler, fde::writeQuotaHandler, and writeTimedOut().
Referenced by CommSelectEngine::checkEvents().
comm_add_close_handler() [1/2]
void comm_add_close_handler (int fd, AsyncCall::Pointer & call)
Definition at line 954 of file comm.cc.
References debugs, fd_table, and AsyncCall::setNext().
comm_add_close_handler() [2/2]
AsyncCall::Pointer comm_add_close_handler (int fd, CLCB * handler, void * data)
Definition at line 942 of file comm.cc.
References comm_add_close_handler(), commCbCall(), and debugs.
Referenced by Mgr::Forwarder::Forwarder(), Snmp::Forwarder::Forwarder(), HttpStateData::HttpStateData(), Mgr::Inquirer::Inquirer(), Snmp::Inquirer::Inquirer(), Security::PeerConnector::PeerConnector(), Mgr::StoreToCommWriter::StoreToCommWriter(), comm_add_close_handler(), Log::TcpLogger::connectDone(), Comm::ConnOpener::createFd(), idnsInitVCConnected(), TunnelStateData::Connection::initConnection(), Ftp::Channel::opened(), Helper::Client::openSessions(), statefulhelper::openSessions(), ConnStateData::pinConnection(), Comm::TcpAcceptor::setListen(), ConnStateData::start(), FwdState::syncWithServerConn(), Adaptation::Icap::Xaction::useIcapConnection(), Http::Tunneler::watchForClosures(), and whoisStart().
comm_connect_addr()
int comm_connect_addr (int sock, const Ip::Address & address)
Connect socket FD to given remote address. If return value is an error flag (COMM_ERROR, ERR_CONNECT, ERR_PROTOCOL, etc.), then error code will also be returned in errno.
Definition at line 631 of file comm.cc.
References assert, fde::_fde_flags::called_connect, Comm::COMM_ERROR, StatCounters::connects, DBG_DATA, debugs, Comm::ERR_PROTOCOL, fd_table, fde::flags, Ip::Address::FreeAddr(), Ip::Address::getAddrInfo(), ignoreErrno(), Comm::INPROGRESS, fde::ipaddr, Ip::Address::isIPv4(), fde::local_addr, MAX_IPSTRLEN, Comm::OK, Ip::Address::port(), fde::remote_port, StatCounters::sock, fde::sock_family, statCounter, StatCounters::syscalls, Ip::Address::toStr(), xconnect(), xgetsockopt(), and xstrerr().
Referenced by Comm::ConnOpener::doConnect(), ipc_thread_1(), ipcCreate(), and logfile_mod_udp_open().
comm_exit()
void comm_exit (void)
Definition at line 1158 of file comm.cc.
References TheHalfClosed.
Referenced by SquidShutdown().
comm_has_incomplete_write()
bool comm_has_incomplete_write (int fd)
Definition at line 154 of file comm.cc.
References assert, COMMIO_FD_WRITECB, and isOpen().
Referenced by PconnPool::push().
comm_import_opened()
void comm_import_opened (const Comm::ConnectionPointer & conn, const char * note, struct addrinfo * AI)
Definition at line 551 of file comm.cc.
References assert, comm_init_opened(), COMM_NONBLOCKING, COMM_TRANSPARENT, debugs, Comm::Connection::fd, fd_table, Comm::Connection::flags, and Comm::IsConnOpen().
Referenced by Ipc::ImportFdIntoComm(), and Ipc::SharedListenJoined().
comm_init()
void comm_init (void)
Definition at line 1141 of file comm.cc.
References assert, fd_table, min(), RESERVED_FD, Comm::SelectLoopInit(), Squid_MaxFD, and TheHalfClosed.
Referenced by TestUfs::commonInit(), and SquidMain().
comm_iocallbackpending()
bool comm_iocallbackpending (void)
comm_local_port()
unsigned short comm_local_port (int fd)
Queue a write. handler/handler_data are called when the write fully completes, on error, or on file descriptor close.
Definition at line 167 of file comm.cc.
References DBG_IMPORTANT, debugs, fd_table, fde::flags, Ip::Address::FreeAddr(), Ip::Address::InitAddr(), Ip::Address::isAnyAddr(), fde::local_addr, MYNAME, fde::_fde_flags::open, Ip::Address::port(), Ip::Address::setIPv4(), fde::sock_family, xgetsockname(), and xstrerr().
Referenced by comm_udp_sendto(), Dns::Init(), Ftp::Server::listenForDataConnection(), and Ftp::Client::sendEprt().
comm_open()
int comm_open (int sock_type, int proto, Ip::Address & addr, int flags, const char * note)
Create a socket. Default is blocking, stream (TCP) socket. IO_TYPE is OR of flags specified in comm.h. Defaults TOS
Definition at line 245 of file comm.cc.
References COMM_DOBIND, COMM_DOBIND_PORT_LATER, comm_openex(), Ip::Address::isAnyAddr(), and Ip::Address::port().
Referenced by Comm::ConnOpener::createFd(), ipc_thread_1(), ipcCreate(), and logfile_mod_udp_open().
comm_open_listener() [1/2]
void comm_open_listener (int sock_type, int proto, Comm::ConnectionPointer & conn, const char * note)
Definition at line 259 of file comm.cc.
References COMM_DOBIND, comm_openex(), Comm::Connection::fd, Comm::Connection::flags, and Comm::Connection::local.
Referenced by htcpOpenPorts(), icpOpenPorts(), Dns::Init(), ipcCreate(), Ftp::Gateway::listenForDataChannel(), Ftp::Server::listenForDataConnection(), Ipc::Coordinator::openListenSocket(), Ipc::StartListening(), wccp2ConnectionOpen(), and wccpConnectionOpen().
comm_open_listener() [2/2]
int comm_open_listener (int sock_type, int proto, Ip::Address & addr, int flags, const char * note)
Open a port specially bound for listening or sending through a specific port. Please use for all listening sockets and bind() outbound sockets.
It will open a socket bound for:
IPv4 if IPv6 is disabled or address is IPv4-native.
IPv6 if address is IPv6-native
IPv6 dual-stack mode if able to open [::]
When an open performs failover it update the given address to feedback the new IPv4-only status of the socket. Further displays of the IP (in debugs or cachemgr) will occur in Native IPv4 format. A reconfigure is needed to reset the stored IP in most cases and attempt a port re-open.
Definition at line 272 of file comm.cc.
References COMM_DOBIND, and comm_openex().
comm_open_uds()
int comm_open_uds (int sock_type, int proto, struct sockaddr_un * addr, int flags)
Definition at line 1677 of file comm.cc.
References assert, comm_close, COMM_DOBIND, COMM_NOCLOEXEC, COMM_NONBLOCKING, COMM_REUSEADDR, commBind(), commSetCloseOnExec(), commSetNonBlocking(), commSetReuseAddr(), commSetTcpRcvbuf(), Config, DBG_CRITICAL, DBG_IMPORTANT, debugs, FD_MSGHDR, fd_open(), fd_table, fdAdjustReserved(), isOpen(), limitError(), MYNAME, Comm::OK, StatCounters::sock, StatCounters::sockets, statCounter, SUN_LEN, sockaddr_un::sun_path, StatCounters::syscalls, SquidConfig::tcpRcvBufsz, xsocket(), and xstrerr().
Referenced by Ipc::UdsOp::conn().
comm_remove_close_handler() [1/2]
void comm_remove_close_handler (int fd, AsyncCall::Pointer & call)
Definition at line 1000 of file comm.cc.
References assert, AsyncCall::cancel(), debugs, AsyncCall::dequeue(), fd_table, isOpen(), and AsyncCall::Next().
comm_remove_close_handler() [2/2]
void comm_remove_close_handler (int fd, CLCB * handler, void * data)
Definition at line 971 of file comm.cc.
References assert, AsyncCall::cancel(), debugs, AsyncCall::dequeue(), fd_table, RefCount< C >::getRaw(), isOpen(), and AsyncCall::Next().
Referenced by Comm::ConnOpener::cleanFd(), Snmp::Inquirer::cleanup(), Ftp::Channel::close(), Mgr::StoreToCommWriter::close(), Adaptation::Icap::Xaction::closeConnection(), HttpStateData::closeServer(), FwdState::closeServerConnection(), Http::Tunneler::disconnect(), Log::TcpLogger::disconnect(), Security::PeerConnector::disconnect(), Ftp::Channel::forget(), HttpStateData::proceedAfter1xx(), HttpStateData::processReplyBody(), Mgr::Inquirer::removeCloseHandler(), Comm::TcpAcceptor::swanSong(), Mgr::Forwarder::swanSong(), Snmp::Forwarder::swanSong(), ConnStateData::unpinConnection(), and FwdState::unregister().
comm_reset_close()
void comm_reset_close (const Comm::ConnectionPointer & conn)
enable linger with time of 0 so that when the socket is closed, TCP generates a RESET
Definition at line 787 of file comm.cc.
References Comm::Connection::close(), commConfigureLinger(), debugs, Comm::Connection::fd, Comm::Connection::id, Comm::IsConnOpen(), and on.
Referenced by ConnStateData::abortChunkedRequestBody(), clientProcessRequestFinished(), Adaptation::Icap::ServiceRep::putConnection(), and ConnStateData::setAuth().
comm_udp_recv()
int comm_udp_recv (int fd, void * buf, size_t len, int flags)
Definition at line 141 of file comm.cc.
References comm_udp_recvfrom().
Referenced by ipcCreate(), and IcmpSquid::Recv().
comm_udp_recvfrom()
int comm_udp_recvfrom (int fd, void * buf, size_t len, int flags, Ip::Address & from)
synchronous wrapper around udp socket functions
Definition at line 128 of file comm.cc.
References debugs, Ip::Address::FreeAddr(), Ip::Address::InitAddr(), StatCounters::recvfroms, StatCounters::sock, statCounter, StatCounters::syscalls, and xrecvfrom().
Referenced by comm_udp_recv(), htcpRecv(), icpHandleUdp(), idnsRead(), snmpHandleUdp(), wccp2HandleUdp(), and wccpHandleUdp().
comm_udp_send()
ssize_t comm_udp_send (int s, const void * buf, size_t len, int flags)
Definition at line 148 of file comm.cc.
References xsend().
Referenced by ipcCreate(), IcmpSquid::SendEcho(), wccpAssignBuckets(), and wccpHereIam().
comm_udp_sendto()
int comm_udp_sendto (int sock, const Ip::Address & to, const void * buf, int buflen)
Definition at line 911 of file comm.cc.
References Comm::COMM_ERROR, comm_local_port(), DBG_IMPORTANT, debugs, fd_table, Ip::Address::FreeAddr(), Ip::Address::getAddrInfo(), MYNAME, StatCounters::sendtos, StatCounters::sock, statCounter, StatCounters::syscalls, xsendto(), and xstrerr().
Referenced by htcpSend(), icpUdpSend(), idnsSendQuery(), Snmp::Forwarder::sendError(), Snmp::Inquirer::sendResponse(), snmpConstructReponse(), wccp2AssignBuckets(), and wccp2HereIam().
commCallCloseHandlers()
void commCallCloseHandlers (int fd)
Definition at line 744 of file comm.cc.
References AsyncCall::canceled(), fde::closeHandler, debugs, fd_table, AsyncCall::Next(), ScheduleCallHere, and AsyncCall::setNext().
Referenced by _comm_close(), and examine_select().
commCloseAllSockets()
void commCloseAllSockets (void)
Definition at line 1437 of file comm.cc.
References Biggest_FD, debugs, FD_SOCKET, fd_table, fde::flags, fde::_fde_flags::ipc, old_comm_reset_close(), fde::_fde_flags::open, ScheduleCallHere, fde::timeoutHandler, and fde::type.
Referenced by SquidShutdown().
commHasHalfClosedMonitor()
bool commHasHalfClosedMonitor (int fd)
Definition at line 1597 of file comm.cc.
References DescriptorSet::has(), and TheHalfClosed.
Referenced by _comm_close(), commHalfClosedReader(), commIsHalfClosed(), and commStartHalfClosedMonitor().
commIsHalfClosed()
bool commIsHalfClosed (int fd) inline
Definition at line 104 of file comm.h.
References commHasHalfClosedMonitor().
Referenced by ConnStateData::clientAfterReadingRequests(), and ConnStateData::parseRequests().
commMarkHalfClosed()
void commMarkHalfClosed (int fd) inline
Definition at line 103 of file comm.h.
References commStartHalfClosedMonitor().
Referenced by Server::doClientRead().
commSetCloseOnExec()
void commSetCloseOnExec (int fd)
On platforms where FD_CLOEXEC is defined, close the given descriptor during a function call from the exec(3) family. Otherwise, do nothing; the platform itself may close-on-exec by default (e.g., MS Win32 is said to do that at https://devblogs.microsoft.com/oldnewthing/20111216-00/?p=8873); other platforms are unsupported. Callers that want close-on-exec behavior must call this function on all platforms and are not responsible for the outcome on platforms without FD_CLOEXEC.
Definition at line 1105 of file comm.cc.
References assert, DBG_CRITICAL, debugs, dummy, MYNAME, and xstrerr().
Referenced by Comm::TcpAcceptor::acceptInto(), comm_apply_flags(), comm_open_uds(), file_open(), ipcCreate(), DiskThreadsDiskFile::openDone(), and DebugFile::reset().
commSetConnTimeout()
void commSetConnTimeout (const Comm::ConnectionPointer & conn, time_t seconds, AsyncCall::Pointer & callback)
Set or clear the timeout for some action on an active connection. API to replace commSetTimeout() when a Comm::ConnectionPointer is available.
Definition at line 594 of file comm.cc.
References assert, debugs, Comm::Connection::fd, fd_table, fde::flags, Comm::IsConnOpen(), fde::_fde_flags::open, squid_curtime, Squid_MaxFD, fde::timeout, and fde::timeoutHandler.
Referenced by TunnelStateData::TunnelStateData(), commUnsetConnTimeout(), ConnStateData::extendLifetime(), idnsDoSendQueryVC(), TunnelStateData::keepGoingAfterRead(), Ftp::Client::maybeReadVirginBody(), Security::PeerConnector::noteWantRead(), Helper::Client::openSessions(), HttpStateData::processReplyBody(), IdleConnList::push(), Http::Tunneler::readMore(), Helper::Session::requestTimeout(), ConnStateData::resetReadTimeout(), Ftp::Client::scheduleReadControlReply(), HttpStateData::sendComplete(), HttpStateData::sendRequest(), Ipc::UdsOp::setTimeout(), Http::One::Server::start(), Ftp::Client::switchTimeoutToDataChannel(), tunnelStartShoveling(), Adaptation::Icap::Xaction::updateTimeout(), and whoisStart().
commSetNonBlocking()
int commSetNonBlocking (int fd)
Definition at line 1044 of file comm.cc.
References Comm::COMM_ERROR, DBG_CRITICAL, debugs, dummy, fd_table, MYNAME, SQUID_NONBLOCK, TRUE, and xstrerr().
Referenced by Comm::TcpAcceptor::acceptInto(), comm_apply_flags(), comm_open_uds(), DiskdIOStrategy::init(), CommIO::Initialize(), ipcCreate(), logfile_mod_daemon_flush(), Helper::Client::openSessions(), and statefulhelper::openSessions().
commStartHalfClosedMonitor()
void commStartHalfClosedMonitor (int fd)
The read channel has closed and the caller does not expect more data but needs to detect connection aborts. The current detection method uses 0-length reads: We read until the error occurs or the writer closes the connection. If there is a read error, we close the connection.
Definition at line 1547 of file comm.cc.
References DescriptorSet::add(), assert, commHasHalfClosedMonitor(), commPlanHalfClosedCheck(), CodeContext::Current(), debugs, fd_table, isOpen(), and TheHalfClosed.
Referenced by commMarkHalfClosed().
commUnsetConnTimeout()
void commUnsetConnTimeout (const Comm::ConnectionPointer & conn)
Definition at line 618 of file comm.cc.
References commSetConnTimeout(), and debugs.
Referenced by IdleConnList::clearHandlers(), Ipc::UdsOp::clearTimeout(), Adaptation::Icap::Xaction::closeConnection(), Http::Tunneler::disconnect(), Security::PeerConnector::disconnect(), Ftp::Channel::forget(), HttpStateData::processReplyBody(), Ftp::Client::readControlReply(), Ftp::Client::scheduleReadControlReply(), Ftp::Client::switchTimeoutToDataChannel(), and Adaptation::Icap::Xaction::updateTimeout().
commUnsetFdTimeout()
void commUnsetFdTimeout (int fd)
Definition at line 581 of file comm.cc.
References assert, debugs, fd_table, fde::flags, fde::_fde_flags::open, Squid_MaxFD, fde::timeout, and fde::timeoutHandler.
Referenced by _comm_close(), DiskdIOStrategy::init(), ipcCreate(), IcmpSquid::Open(), and unlinkdInit().
commUnsetNonBlocking()
int commUnsetNonBlocking (int fd)
Definition at line 1077 of file comm.cc.
References Comm::COMM_ERROR, DBG_CRITICAL, debugs, dummy, FALSE, fd_table, MYNAME, SQUID_NONBLOCK, and xstrerr().
Referenced by ipc_thread_1(), logfile_mod_daemon_flush(), and unlinkdInit().
ignoreErrno()
int ignoreErrno (int ierrno)
Definition at line 1407 of file comm.cc.
Referenced by Comm::TcpAcceptor::acceptInto(), comm_connect_addr(), Ftp::Client::dataRead(), TunnelStateData::Connection::debugLevelForError(), diskHandleRead(), diskHandleWrite(), Comm::DoSelect(), TunnelStateData::Connection::error(), icpHandleUdp(), idnsRead(), logfileHandleWrite(), Ssl::Bio::read(), Ftp::Client::readControlReply(), Comm::ReadNow(), WhoisState::readReply(), and Ssl::Bio::write().
old_comm_reset_close()
void old_comm_reset_close (int fd)
Definition at line 798 of file comm.cc.
References comm_close, commConfigureLinger(), and on.
Referenced by commCloseAllSockets().