Squid Web Cache: squid/src/CommCalls.h File Reference
CommCalls.h File Reference
#include "base/AsyncCall.h"
#include "base/AsyncJobCalls.h"
#include "comm/Flag.h"
#include "comm/forward.h"
#include "MasterXaction.h"
Classes
class CommCommonCbParams
class CommAcceptCbParams
class CommConnectCbParams
class CommIoCbParams
class CommCloseCbParams
class CommTimeoutCbParams
class CommDialerParamsT< Params_ >
class CommCbMemFunT< C, Params_ >
class CommAcceptCbPtrFun
class CommConnectCbPtrFun
class CommIoCbPtrFun
class CommCloseCbPtrFun
class CommTimeoutCbPtrFun
class CommCbFunPtrCallT< Dialer >
Typedefs
typedef void IOACB(const CommAcceptCbParams &params)
typedef void CNCB(const Comm::ConnectionPointer &conn, Comm::Flag status, int xerrno, void *data)
typedef void IOCB(const Comm::ConnectionPointer &conn, char *, size_t size, Comm::Flag flag, int xerrno, void *data)
typedef void CTCB(const CommTimeoutCbParams &params)
typedef void CLCB(const CommCloseCbParams &params)
Functions
template<class Params >
Params & GetCommParams (AsyncCall::Pointer &call)
template<class Dialer >
CommCbFunPtrCallT< Dialer > * commCbCall (int debugSection, int debugLevel, const char *callName, const Dialer &dialer)
Typedef Documentation
CLCB
typedef void CLCB(const CommCloseCbParams &params)
Definition at line 40 of file CommCalls.h.
CNCB
typedef void CNCB(const Comm::ConnectionPointer &conn, Comm::Flag status, int xerrno, void *data)
Definition at line 33 of file CommCalls.h.
CTCB
typedef void CTCB(const CommTimeoutCbParams &params)
Definition at line 37 of file CommCalls.h.
IOACB
typedef void IOACB(const CommAcceptCbParams &params)
Definition at line 31 of file CommCalls.h.
IOCB
typedef void IOCB(const Comm::ConnectionPointer &conn, char *, size_t size, Comm::Flag flag, int xerrno, void *data)
Definition at line 34 of file CommCalls.h.
Function Documentation
commCbCall()
template<class Dialer > CommCbFunPtrCallT< Dialer > * commCbCall (int debugSection, int debugLevel, const char * callName, const Dialer & dialer) inline
Definition at line 312 of file CommCalls.h.
Referenced by TunnelStateData::TunnelStateData(), clientHttpConnectionsOpen(), comm_add_close_handler(), TunnelStateData::copy(), TunnelStateData::copyRead(), errorSend(), helperDispatch(), helperDispatchWriteDone(), helperHandleRead(), helperStatefulDispatch(), helperStatefulHandleRead(), idnsDoSendQueryVC(), idnsInitVC(), idnsInitVCConnected(), idnsReadVC(), idnsReadVCHeader(), TunnelStateData::Connection::initConnection(), TunnelStateData::keepGoingAfterRead(), TunnelStateData::notePeerReadyToShovel(), Helper::Client::openSessions(), statefulhelper::openSessions(), peerProbeConnect(), IdleConnList::push(), WhoisState::readReply(), Helper::Session::requestTimeout(), ClientHttpRequest::sslBumpStart(), Ftp::StartListening(), tunnelStartShoveling(), and whoisStart().
GetCommParams()
template<class Params > Params & GetCommParams (AsyncCall::Pointer & call)
Definition at line 154 of file CommCalls.h.
References assert, and AsyncCall::getDialer().