Squid Web Cache: squid/src/comm/comm_internal.h File Reference
comm_internal.h File Reference
Functions
bool isOpen (const int fd)
void commStopHalfClosedMonitor (int fd)
stop waiting for possibly half-closed connection to close
Function Documentation
commStopHalfClosedMonitor()
void commStopHalfClosedMonitor (int fd)
Definition at line 1604 of file comm.cc.
References debugs, DescriptorSet::del(), fd_table, Comm::ReadCancel(), and TheHalfClosed.
Referenced by _comm_close(), and comm_read_base().
isOpen()
bool isOpen (const int fd)
Definition at line 91 of file comm.cc.
References fd_table.
Referenced by _comm_close(), Comm::Connection::close(), comm_has_incomplete_write(), comm_init_opened(), comm_open_uds(), comm_read_cancel(), comm_remove_close_handler(), comm_remove_close_handler(), commStartHalfClosedMonitor(), Comm::TcpAcceptor::doAccept(), Comm::MonitorsRead(), Ftp::Server::noteBodyConsumerAborted(), Comm::Connection::noteClosure(), Ftp::Server::noteMoreBodySpaceAvailable(), Http::One::Server::noteMoreBodySpaceAvailable(), Comm::ReadCancel(), Ftp::Server::startWaitingForOrigin(), and Ftp::Server::stopWaitingForOrigin().