Squid Web Cache: squid/compat/compat_shared.h File Reference
compat_shared.h File Reference
#include <csignal>
#include "compat/xalloc.h"
#include "compat/xis.h"
#include "compat/xstrerror.h"
#include "compat/xstring.h"
#include "compat/xstrto.h"
#include "compat/strtoll.h"
#include "compat/memrchr.h"
Classes
struct rusage
Macros
#define SQUID_MAXFD_LIMIT ((signed int)FD_SETSIZE)
#define w_space " \t\n\r"
#define SQUID_NONBLOCK O_NDELAY
#define SA_RESTART 0
#define SA_NODEFER 0
#define SA_RESETHAND 0
#define PRINTF_FORMAT_ARG1
#define PRINTF_FORMAT_ARG2
#define PRINTF_FORMAT_ARG3
Functions
template<class A >
A const & min (A const &lhs, A const &rhs)
template<class A >
A const & max (A const &lhs, A const &rhs)
Variables
void(* failure_notify)(const char *)
Macro Definition Documentation
PRINTF_FORMAT_ARG1
#define PRINTF_FORMAT_ARG1
com_err.h is a C header and needs explicit shielding, but not all other system headers including this care to do so.
Definition at line 241 of file compat_shared.h.
PRINTF_FORMAT_ARG2
#define PRINTF_FORMAT_ARG2
Definition at line 242 of file compat_shared.h.
PRINTF_FORMAT_ARG3
#define PRINTF_FORMAT_ARG3
Definition at line 243 of file compat_shared.h.
SA_NODEFER
#define SA_NODEFER 0
Definition at line 175 of file compat_shared.h.
SA_RESETHAND
#define SA_RESETHAND 0
Definition at line 178 of file compat_shared.h.
SA_RESTART
#define SA_RESTART 0
Signalling flags are apparently not always provided. TODO find out if these can be moved into specific OS portability files.
Definition at line 172 of file compat_shared.h.
SQUID_MAXFD_LIMIT
#define SQUID_MAXFD_LIMIT ((signed int)FD_SETSIZE)
Definition at line 66 of file compat_shared.h.
SQUID_NONBLOCK
#define SQUID_NONBLOCK O_NDELAY
O_NDELAY is our fallback.
Definition at line 156 of file compat_shared.h.
w_space
#define w_space " \t\n\r"
Common shared definition of what whitespace consists of for string tests
Definition at line 139 of file compat_shared.h.
Function Documentation
max()
template<class A > A const & max (A const & lhs, A const & rhs) inline
max() comparison may not always be provided. Squid bundles this template for when its needed. May be used on any type which provides operator '>'
Definition at line 124 of file compat_shared.h.
Referenced by Ssl::CertificateDb::Row::~Row(), Auth::User::absorb(), Adaptation::Icap::ServiceRep::availableConnections(), DelayBucket::bytesWanted(), DelayId::bytesWanted(), Aggregate::AggregateId::bytesWanted(), VectorPool::Id::bytesWanted(), ClassCHostPool::Id::bytesWanted(), DelayTagged::Id::bytesWanted(), DelayUser::Id::bytesWanted(), DelayVector::Id::bytesWanted(), NullDelayId::bytesWanted(), IpcIoFile::canWait(), Math::doubleAverage(), Adaptation::Icap::ModXact::finalizeLogInfo(), icpHandleUdp(), idnsRead(), Math::intAverage(), Range< C, S >::intersection(), Store::Controller::keepForLocalMemoryCache(), DebugMessage::limited(), StatHist::logInit(), main(), MemObject::mostBytesWanted(), Mgr::InfoActionData::operator+=(), parse_refreshpattern(), positiveTimeout(), Helper::Session::requestTimeout(), MemStore::shouldCache(), Rock::SwapDir::slotLimitActual(), TestStatHist::testStatHistLog(), EventScheduler::timeRemaining(), Rock::SwapDir::validateOptions(), xstrtoui(), and xstrtoul().
min()
template<class A > A const & min (A const & lhs, A const & rhs) inline
min() comparison may not always be provided. Squid bundles this template for when its needed. May be used on any type which provides operator '<'
Definition at line 103 of file compat_shared.h.
Referenced by Log::TcpLogger::appendRecord(), BandwidthBucket::applyQuota(), DelayBucket::bytesWanted(), Aggregate::AggregateId::bytesWanted(), VectorPool::Id::bytesWanted(), ClassCHostPool::Id::bytesWanted(), DelayTagged::Id::bytesWanted(), DelayUser::Id::bytesWanted(), DelayVector::Id::bytesWanted(), Client::calcBufferSpaceToReserve(), comm_init(), SBuf::compare(), SBuf::compare(), Store::Controller::configure(), Comm::Connection::connectTimeout(), SBuf::consume(), SBuf::copy(), mem_hdr::copyAvailable(), Adaptation::Icap::ModXact::decideOnPreview(), diskerRead(), diskerWriteAttempts(), Ipc::StoreMap::entryLimit(), Rock::SwapDir::entryLimitActual(), fdAdjustReserved(), BodyPipe::getMoreData(), Adaptation::Icap::ServiceRep::handleNewOptions(), hashPrime(), idnsGrokReply(), idnsTickleQueue(), Ipc::StoreMap::Init(), Range< C, S >::intersection(), Store::Controller::keepForLocalMemoryCache(), Http::Stream::lengthToSend(), logfile_mod_daemon_append(), StatHist::logInit(), MemStore::maxObjectSize(), Store::Disk::maxObjectSize(), Comm::MortalReadTimeout(), ACLRandom::parse(), HttpHeaderEntry::parse(), parse_refreshpattern(), Http::One::TeChunkedParser::parseChunkBody(), Ftp::Server::parseOneRequest(), BodyPipe::putMoreData(), MessageBucket::quota(), SBuf::rawAppendFinish(), Rock::IoState::read_(), refreshCheck(), refreshStaleness(), rfc2671RROptPack(), Ftp::Client::scheduleReadControlReply(), Rock::SwapDir::slotLimitActual(), TestSBuf::testComparisons(), testComparisonStdOneWay(), TestSBuf::testReserve(), TestStatHist::testStatHistLog(), Comm::Connection::timeLeft(), Ip::Address::toStr(), Adaptation::Ecap::XactionRep::vbContent(), Adaptation::Ecap::XactionRep::vbContentShift(), Adaptation::Icap::ModXact::virginConsume(), Ipc::StoreMap::visitVictims(), IpcIoFile::WaitBeforePop(), mem_hdr::writeAvailable(), Adaptation::Icap::ModXact::writePreviewBody(), Adaptation::Icap::ModXact::writeSomeBody(), Rock::IoState::writeToBuffer(), xstrtoui(), and xstrtoul().
Variable Documentation
failure_notify
void(* failure_notify) (const char *) (const char *) extern
Definition at line 12 of file compat.cc.
Referenced by fatal_dump(), SquidMain(), xcalloc(), xmalloc(), xrealloc(), xstrdup(), and xstrndup().