Squid Web Cache: squid/compat/compat.cc File Reference
compat.cc File Reference
#include "squid.h"
#include "compat.h"
Variables
void(* failure_notify)(const char *) = nullptr
Variable Documentation
failure_notify
void(* failure_notify) (const char *) (const char *) = nullptr
Definition at line 12 of file compat.cc.
Referenced by fatal_dump(), SquidMain(), xcalloc(), xmalloc(), xrealloc(), xstrdup(), and xstrndup().