Squid Web Cache: squid/src/mgr/CountersAction.cc File Reference
CountersAction.cc File Reference
#include "squid.h"
#include "base/TextException.h"
#include "ipc/Messages.h"
#include "ipc/TypedMsgHdr.h"
#include "mgr/CountersAction.h"
#include "Store.h"
#include "tools.h"
Functions
void GetCountersStats (Mgr::CountersActionData &stats)
void DumpCountersStats (Mgr::CountersActionData &stats, StoreEntry *sentry)
Function Documentation
DumpCountersStats()
void DumpCountersStats (Mgr::CountersActionData & stats, StoreEntry * sentry)
Definition at line 1440 of file stat.cc.
References Mgr::CountersActionData::aborted_requests, Mgr::CountersActionData::cd_kbytes_recv, Mgr::CountersActionData::cd_kbytes_sent, Mgr::CountersActionData::cd_local_memory, Mgr::CountersActionData::cd_memory, Mgr::CountersActionData::cd_msgs_recv, Mgr::CountersActionData::cd_msgs_sent, Mgr::CountersActionData::cd_times_used, Mgr::CountersActionData::client_http_errors, Mgr::CountersActionData::client_http_hit_kbytes_out, Mgr::CountersActionData::client_http_hits, Mgr::CountersActionData::client_http_kbytes_in, Mgr::CountersActionData::client_http_kbytes_out, Mgr::CountersActionData::client_http_requests, Mgr::CountersActionData::cpu_time, Time::FormatRfc1123(), Mgr::CountersActionData::hitValidationAttempts, Mgr::CountersActionData::hitValidationFailures, Mgr::CountersActionData::hitValidationRefusalsDueToLocking, Mgr::CountersActionData::hitValidationRefusalsDueToTimeLimit, Mgr::CountersActionData::hitValidationRefusalsDueToZeroSize, Mgr::CountersActionData::icp_kbytes_recv, Mgr::CountersActionData::icp_kbytes_sent, Mgr::CountersActionData::icp_pkts_recv, Mgr::CountersActionData::icp_pkts_sent, Mgr::CountersActionData::icp_q_kbytes_recv, Mgr::CountersActionData::icp_q_kbytes_sent, Mgr::CountersActionData::icp_queries_recv, Mgr::CountersActionData::icp_queries_sent, Mgr::CountersActionData::icp_query_timeouts, Mgr::CountersActionData::icp_r_kbytes_recv, Mgr::CountersActionData::icp_r_kbytes_sent, Mgr::CountersActionData::icp_replies_queued, Mgr::CountersActionData::icp_replies_recv, Mgr::CountersActionData::icp_replies_sent, Mgr::CountersActionData::icp_times_used, Mgr::CountersActionData::page_faults, Mgr::CountersActionData::sample_time, Mgr::CountersActionData::select_loops, Mgr::CountersActionData::server_all_errors, Mgr::CountersActionData::server_all_kbytes_in, Mgr::CountersActionData::server_all_kbytes_out, Mgr::CountersActionData::server_all_requests, Mgr::CountersActionData::server_ftp_errors, Mgr::CountersActionData::server_ftp_kbytes_in, Mgr::CountersActionData::server_ftp_kbytes_out, Mgr::CountersActionData::server_ftp_requests, Mgr::CountersActionData::server_http_errors, Mgr::CountersActionData::server_http_kbytes_in, Mgr::CountersActionData::server_http_kbytes_out, Mgr::CountersActionData::server_http_requests, Mgr::CountersActionData::server_other_errors, Mgr::CountersActionData::server_other_kbytes_in, Mgr::CountersActionData::server_other_kbytes_out, Mgr::CountersActionData::server_other_requests, storeAppendPrintf(), Mgr::CountersActionData::swap_files_cleaned, Mgr::CountersActionData::swap_ins, Mgr::CountersActionData::swap_outs, Mgr::CountersActionData::unlink_requests, and Mgr::CountersActionData::wall_time.
Referenced by Mgr::CountersAction::dump(), and statCountersDump().
GetCountersStats()
void GetCountersStats (Mgr::CountersActionData & stats)
Definition at line 1358 of file stat.cc.
References Mgr::CountersActionData::aborted_requests, StatCounters::aborted_requests, StatCounters::all, StatCounters::attempts, StatCounters::cd, Mgr::CountersActionData::cd_kbytes_recv, Mgr::CountersActionData::cd_kbytes_sent, Mgr::CountersActionData::cd_local_memory, Mgr::CountersActionData::cd_memory, Mgr::CountersActionData::cd_msgs_recv, Mgr::CountersActionData::cd_msgs_sent, Mgr::CountersActionData::cd_times_used, StatCounters::client_http, Mgr::CountersActionData::client_http_errors, Mgr::CountersActionData::client_http_hit_kbytes_out, Mgr::CountersActionData::client_http_hits, Mgr::CountersActionData::client_http_kbytes_in, Mgr::CountersActionData::client_http_kbytes_out, Mgr::CountersActionData::client_http_requests, Mgr::CountersActionData::cpu_time, StatCounters::cputime, current_time, StatCounters::errors, StatCounters::failures, StatCounters::files_cleaned, StatCounters::ftp, StatCounters::hit_kbytes_out, StatCounters::hits, StatCounters::hitValidation, Mgr::CountersActionData::hitValidationAttempts, Mgr::CountersActionData::hitValidationFailures, Mgr::CountersActionData::hitValidationRefusalsDueToLocking, Mgr::CountersActionData::hitValidationRefusalsDueToTimeLimit, Mgr::CountersActionData::hitValidationRefusalsDueToZeroSize, StatCounters::http, StatCounters::icp, Mgr::CountersActionData::icp_kbytes_recv, Mgr::CountersActionData::icp_kbytes_sent, Mgr::CountersActionData::icp_pkts_recv, Mgr::CountersActionData::icp_pkts_sent, Mgr::CountersActionData::icp_q_kbytes_recv, Mgr::CountersActionData::icp_q_kbytes_sent, Mgr::CountersActionData::icp_queries_recv, Mgr::CountersActionData::icp_queries_sent, Mgr::CountersActionData::icp_query_timeouts, Mgr::CountersActionData::icp_r_kbytes_recv, Mgr::CountersActionData::icp_r_kbytes_sent, Mgr::CountersActionData::icp_replies_queued, Mgr::CountersActionData::icp_replies_recv, Mgr::CountersActionData::icp_replies_sent, Mgr::CountersActionData::icp_times_used, StatCounters::ins, ByteCounter::kb, StatCounters::kbytes_in, StatCounters::kbytes_out, StatCounters::kbytes_recv, StatCounters::kbytes_sent, CacheDigest::mask_size, StatCounters::memory, StatCounters::msgs_recv, StatCounters::msgs_sent, StatCounters::other, StatCounters::outs, Mgr::CountersActionData::page_faults, StatCounters::page_faults, StatCounters::pkts_recv, StatCounters::pkts_sent, StatCounters::q_kbytes_recv, StatCounters::q_kbytes_sent, StatCounters::queries_recv, StatCounters::queries_sent, StatCounters::query_timeouts, StatCounters::r_kbytes_recv, StatCounters::r_kbytes_sent, StatCounters::refusalsDueToLocking, StatCounters::refusalsDueToTimeLimit, StatCounters::refusalsDueToZeroSize, StatCounters::replies_queued, StatCounters::replies_recv, StatCounters::replies_sent, StatCounters::requests, rusage_cputime(), rusage_pagefaults(), Mgr::CountersActionData::sample_time, Mgr::CountersActionData::select_loops, StatCounters::select_loops, StatCounters::server, Mgr::CountersActionData::server_all_errors, Mgr::CountersActionData::server_all_kbytes_in, Mgr::CountersActionData::server_all_kbytes_out, Mgr::CountersActionData::server_all_requests, Mgr::CountersActionData::server_ftp_errors, Mgr::CountersActionData::server_ftp_kbytes_in, Mgr::CountersActionData::server_ftp_kbytes_out, Mgr::CountersActionData::server_ftp_requests, Mgr::CountersActionData::server_http_errors, Mgr::CountersActionData::server_http_kbytes_in, Mgr::CountersActionData::server_http_kbytes_out, Mgr::CountersActionData::server_http_requests, Mgr::CountersActionData::server_other_errors, Mgr::CountersActionData::server_other_kbytes_in, Mgr::CountersActionData::server_other_kbytes_out, Mgr::CountersActionData::server_other_requests, squid_getrusage(), statCounter, store_digest, StatCounters::swap, Mgr::CountersActionData::swap_files_cleaned, Mgr::CountersActionData::swap_ins, Mgr::CountersActionData::swap_outs, StatCounters::times_used, StatCounters::timestamp, tvSubDsec(), StatCounters::unlink, Mgr::CountersActionData::unlink_requests, and Mgr::CountersActionData::wall_time.
Referenced by Mgr::CountersAction::collect(), and statCountersDump().