Squid Web Cache: squid/compat/cpu.h File Reference
cpu.h File Reference
#include <cerrno>
Classes
struct cpu_set_t
Macros
#define CPU_SETSIZE 0
#define CPU_ZERO(set) (void)0
#define CPU_SET(cpunum, cpuset) CpuSet(cpunum, cpuset)
#define CPU_CLR(cpu, set) (void)0
#define CPU_ISSET(cpunum, cpuset) CpuIsSet(cpunum, cpuset)
#define CPU_COUNT(set) CpuCount(set)
#define CPU_AND(destset, srcset1, srcset2) CpuAnd((destset), (srcset1), (srcset2))
Functions
int sched_setaffinity (int, size_t, cpu_set_t *)
int sched_getaffinity (int, size_t, cpu_set_t *)
void CpuSet (int, const cpu_set_t *)
bool CpuIsSet (int, const cpu_set_t *)
int CpuCount (const cpu_set_t *set)
CPU_COUNT replacement.
void CpuAnd (cpu_set_t *destset, const cpu_set_t *srcset1, const cpu_set_t *srcset2)
CPU_AND replacement.
Macro Definition Documentation
CPU_AND
#define CPU_AND (destset, srcset1, srcset2) CpuAnd((destset), (srcset1), (srcset2))
Definition at line 69 of file cpu.h.
CPU_CLR
#define CPU_CLR (cpu, set) (void)0
Definition at line 43 of file cpu.h.
CPU_COUNT
#define CPU_COUNT (set) CpuCount(set)
Definition at line 53 of file cpu.h.
CPU_ISSET
#define CPU_ISSET (cpunum, cpuset) CpuIsSet(cpunum, cpuset)
Definition at line 47 of file cpu.h.
CPU_SET
#define CPU_SET (cpunum, cpuset) CpuSet(cpunum, cpuset)
Definition at line 38 of file cpu.h.
CPU_SETSIZE
#define CPU_SETSIZE 0
Definition at line 30 of file cpu.h.
CPU_ZERO
#define CPU_ZERO (set) (void)0
Definition at line 34 of file cpu.h.
Function Documentation
CpuAnd()
void CpuAnd (cpu_set_t * destset, const cpu_set_t * srcset1, const cpu_set_t * srcset2) inline
Definition at line 72 of file cpu.h.
References CPU_CLR, CPU_ISSET, CPU_SET, and CPU_SETSIZE.
CpuCount()
int CpuCount (const cpu_set_t * set) inline
Definition at line 56 of file cpu.h.
References CPU_ISSET, and CPU_SETSIZE.
CpuIsSet()
bool CpuIsSet (int , const cpu_set_t *) inline
Definition at line 48 of file cpu.h.
CpuSet()
void CpuSet (int , const cpu_set_t *) inline
Definition at line 39 of file cpu.h.
sched_getaffinity()
int sched_getaffinity (int , size_t , cpu_set_t *) inline
Definition at line 26 of file cpu.h.
Referenced by CpuAffinitySet::apply().
sched_setaffinity()
int sched_setaffinity (int , size_t , cpu_set_t *) inline
Definition at line 25 of file cpu.h.
Referenced by CpuAffinitySet::apply(), and CpuAffinitySet::undo().