Squid Web Cache: squid/src/debug/Stream.h File Reference
Stream.h File Reference
#include "base/Here.h"
#include "mem/AllocatorProxy.h"
#include <iostream>
#include <sstream>
#include <iomanip>
Classes
class Debug
class Debug::Context
meta-information for debugs() or a similar debugging call
Macros
#define assert(EX) ((EX)?((void)0):xassert(# EX , __FILE__, __LINE__))
#define MAX_DEBUG_SECTIONS 100
#define DBG_CRITICAL 0
#define DBG_IMPORTANT 1
#define DBG_DATA 9
#define DBG_PARSE_NOTE(x) (opt_parse_cfg_only?0:(x))
#define debugs(SECTION, LEVEL, CONTENT)
#define MYNAME __func__ << " "
Functions
FILE * DebugStream ()
void ResyncDebugLog (FILE *newDestination)
a hack for low-level file descriptor manipulations in ipcCreate()
std::ostream & ForceAlert (std::ostream &s)
std::ostream & operator<< (std::ostream &os, const uint8_t d)
void _db_rotate_log (void)
Macro Definition Documentation
assert
#define assert (EX) ((EX)?((void)0):xassert(# EX , __FILE__, __LINE__))
Definition at line 30 of file Stream.h.
DBG_CRITICAL
#define DBG_CRITICAL 0
critical messages always shown when they occur
Definition at line 37 of file Stream.h.
DBG_DATA
#define DBG_DATA 9
output is a large data dump only necessary for advanced debugging
Definition at line 40 of file Stream.h.
DBG_IMPORTANT
#define DBG_IMPORTANT 1
important messages always shown when their section is being checked
Definition at line 38 of file Stream.h.
DBG_PARSE_NOTE
#define DBG_PARSE_NOTE (x) (opt_parse_cfg_only?0:(x))
output is always to be displayed on '-k parse' but at level-x normally.
Definition at line 42 of file Stream.h.
debugs
#define debugs (SECTION, LEVEL, CONTENT)
Value:
   do { \
        const int _dbg_level = (LEVEL); \
        if (Debug::Enabled((SECTION), _dbg_level)) { \
            std::ostream &_dbo = Debug::Start((SECTION), _dbg_level); \
            if (_dbg_level > DBG_IMPORTANT) { \
                _dbo << (SECTION) << ',' << _dbg_level << "| " \
                     << Here() << ": "; \
            } \
            _dbo << CONTENT; \
            Debug::Finish(); \
        } \
   } while (/*CONSTCOND*/ 0)
Definition at line 192 of file Stream.h.
MAX_DEBUG_SECTIONS
#define MAX_DEBUG_SECTIONS 100
Definition at line 34 of file Stream.h.
MYNAME
#define MYNAME __func__ << " "
Definition at line 219 of file Stream.h.
Function Documentation
_db_rotate_log()
void _db_rotate_log (void)
Definition at line 1160 of file debug.cc.
References Debug::cache_log, DebugFile::clear(), DBG_IMPORTANT, debugOpenLog(), debugs, MAXPATHLEN, DebugFile::name, Debug::rotateNumber, TheLog, and xstrerr().
Referenced by mainRotate().
DebugStream()
FILE * DebugStream ()
cache.log FILE or, as the last resort, stderr stream; may be nil during static initialization and destruction!
Definition at line 355 of file debug.cc.
References DebugFile::file(), and TheLog.
Referenced by clientNegotiateSSL(), death(), dumpMallocStats(), fdDumpOpen(), ipc_thread_1(), ipcCreate(), logsFlush(), and PrintRusage().
ForceAlert()
std::ostream & ForceAlert (std::ostream & s)
Does not change the stream being manipulated. Exists for its side effect: In a debugs() context, forces the message to become a syslog ALERT. Outside of debugs() context, has no effect and should not be used.
Definition at line 1411 of file debug.cc.
References Debug::ForceAlert().
Referenced by death(), and fatal_common().
operator<<()
std::ostream & operator<< (std::ostream & os, const uint8_t d) inline
Definition at line 223 of file Stream.h.
ResyncDebugLog()
void ResyncDebugLog (FILE * newDestination)
Definition at line 102 of file debug.cc.
Referenced by ipcCreate().