Squid Web Cache: squid/compat/debug.h File Reference
debug.h File Reference
Functions
void debug (const char *format,...)
Variables
int debug_enabled
Function Documentation
debug()
void debug (const char * format, ...)
Definition at line 19 of file debug.cc.
References debug_enabled.
Referenced by build_groups_DN_array(), checkLDAP(), Adaptation::Ecap::Host::closeDebug(), dict_lookup(), Get_primaryGroup(), GetDomainName(), getpassword(), ldapconnect(), load_dict(), local_printfx(), main(), main(), main(), MainSafe(), manage_request(), match_group(), My_NameTranslate(), ntlm_fetch_string(), ntlm_unpack_auth(), ntlm_validate_packet(), password_conversation(), Recursive_Memberof(), result_recv(), SearchIPLDAP(), searchLDAP(), searchLDAPGroup(), SigTrap(), Valid_Global_Groups(), Valid_Local_Groups(), Valid_User(), wcstrcmparray(), and wStrIsInArray().
Variable Documentation
debug_enabled
int debug_enabled extern
Definition at line 13 of file debug.cc.