Squid Web Cache: squid/src/acl/DestinationDomain.cc File Reference
DestinationDomain.cc File Reference
#include "squid.h"
#include "acl/DestinationDomain.h"
#include "acl/DomainData.h"
#include "acl/FilledChecklist.h"
#include "acl/RegexData.h"
#include "fqdncache.h"
#include "HttpRequest.h"
Functions
static void LookupDone (const char *, const Dns::LookupDetails &, void *data)
static void StartLookup (ACLFilledChecklist &cl, const Acl::Node &)
Function Documentation
LookupDone()
static void LookupDone (const char * , const Dns::LookupDetails & details, void * data) static
Definition at line 28 of file DestinationDomain.cc.
References Filled(), ACLFilledChecklist::markDestinationDomainChecked(), HttpRequest::recordLookup(), ACLFilledChecklist::request, and ACLChecklist::resumeNonBlockingCheck().
Referenced by StartLookup().
StartLookup()
static void StartLookup (ACLFilledChecklist & cl, const Acl::Node &) static
Definition at line 22 of file DestinationDomain.cc.
References ACLFilledChecklist::dst_addr, fqdncache_nbgethostbyaddr(), and LookupDone().
Referenced by Acl::DestinationDomainCheck::match(), and Acl::SourceDomainCheck::match().