Squid Web Cache: squid/src/error/Detail.cc File Reference
Detail.cc File Reference
#include "squid.h"
#include "error/Detail.h"
#include "HttpRequest.h"
#include "sbuf/SBuf.h"
#include "sbuf/Stream.h"
Classes
class NamedErrorDetail
details an error by tying it to a uniquely named circumstance
Functions
std::ostream & operator<< (std::ostream &os, const ErrorDetail &detail)
dump the given ErrorDetail (for debugging)
std::ostream & operator<< (std::ostream &os, const ErrorDetail::Pointer &detail)
dump the given ErrorDetail via a possibly nil pointer (for debugging)
ErrorDetail::Pointer MakeNamedErrorDetail (const char *name)
Function Documentation
MakeNamedErrorDetail()
ErrorDetail::Pointer MakeNamedErrorDetail (const char * name)
creates a new NamedErrorDetail object with a unique name
See also
NamedErrorDetail::Name for naming restrictions
Definition at line 54 of file Detail.cc.
Referenced by ClientRequestContext::clientRedirectDone(), Security::PeerConnector::commCloseHandler(), Security::PeerConnector::commTimeoutHandler(), Adaptation::Icap::Xaction::dieOnConnectionFailure(), ClientHttpRequest::handleAdaptationBlock(), Client::handleAdaptationBlocked(), Client::handledEarlyAdaptationAbort(), HttpStateData::handleRequestBodyProducerAborted(), Adaptation::Icap::Xaction::handleSecuredPeer(), ConnStateData::handleSslBumpHandshakeError(), ConnStateData::initiateTunneledRequest(), HttpStateData::markPrematureReplyBodyEofFailure(), ClientHttpRequest::noteAdaptationAnswer(), Adaptation::Icap::ModXact::noteBodyConsumerAborted(), ClientHttpRequest::noteBodyProducerAborted(), Adaptation::Icap::Xaction::noteCommClosed(), FwdState::noteDestinationsEnd(), TunnelStateData::noteDestinationsEnd(), Adaptation::Icap::Xaction::noteInitiatorAborted(), ConnStateData::parseTlsHandshake(), Adaptation::Icap::ModXact::swanSong(), ConnStateData::terminateAll(), and FwdState::updateAleWithFinalError().
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const ErrorDetail & detail)
Definition at line 34 of file Detail.cc.
References ErrorDetail::brief().
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const ErrorDetail::Pointer & detail)
Definition at line 41 of file Detail.cc.