Squid Web Cache: squid/src/DiskIO/DiskDaemon/diskd.cc File Reference
diskd.cc File Reference
#include "squid.h"
#include "compat/socket.h"
#include "compat/unistd.h"
#include "DiskIO/DiskDaemon/diomsg.h"
#include "hash.h"
#include <cerrno>
#include <iostream>
Classes
struct _file_state
Macros
#define DEBUG(LEVEL) if ((LEVEL) <= DebugLevel)
Typedefs
typedef struct _file_state file_state
Functions
void xassert (const char *msg, const char *file, int line)
static int do_open (diomsg *r, int, const char *buf)
static int do_close (diomsg *r, int)
static int do_read (diomsg *r, int, char *buf)
static int do_write (diomsg *r, int, const char *buf)
static int do_unlink (diomsg *r, int, const char *buf)
static void msg_handle (diomsg *r, int rl, diomsg *s)
static int fsCmp (const void *a, const void *b)
static unsigned int fsHash (const void *key, unsigned int n)
static void alarm_handler (int)
int main (int argc, char *argv[])
Variables
static hash_table * hash = nullptr
static pid_t mypid
static char * shmbuf
static int DebugLevel = 0
Macro Definition Documentation
DEBUG
#define DEBUG (LEVEL) if ((LEVEL) <= DebugLevel)
Definition at line 38 of file diskd.cc.
Typedef Documentation
file_state
typedef struct _file_state file_state
Definition at line 40 of file diskd.cc.
Function Documentation
alarm_handler()
static void alarm_handler (int) static
Definition at line 298 of file diskd.cc.
Referenced by main().
do_close()
static int do_close (diomsg * r, int) static
Definition at line 89 of file diskd.cc.
References DEBUG, _file_state::fd, hash, hash_lookup(), hash_remove_link(), diomsg::id, mypid, xclose(), and xfree.
Referenced by diskHandleWrite(), and msg_handle().
do_open()
static int do_open (diomsg * r, int , const char * buf) static
Definition at line 56 of file diskd.cc.
References DEBUG, _file_state::fd, hash, hash_join(), diomsg::id, _file_state::id, _file_state::key, mypid, diomsg::offset, xcalloc(), and xopen().
Referenced by msg_handle().
do_read()
static int do_read (diomsg * r, int , char * buf) static
Definition at line 119 of file diskd.cc.
References DEBUG, _file_state::fd, hash, hash_lookup(), diomsg::id, mypid, diomsg::offset, _file_state::offset, PRId64, diomsg::size, and xread().
Referenced by msg_handle().
do_unlink()
static int do_unlink (diomsg * r, int , const char * buf) static
Definition at line 213 of file diskd.cc.
References DEBUG, diomsg::id, and mypid.
Referenced by msg_handle().
do_write()
static int do_write (diomsg * r, int , const char * buf) static
Definition at line 168 of file diskd.cc.
References DEBUG, _file_state::fd, hash, hash_lookup(), diomsg::id, mypid, diomsg::offset, _file_state::offset, PRId64, diomsg::size, and xwrite().
Referenced by msg_handle().
fsCmp()
static int fsCmp (const void * a, const void * b) static
Definition at line 282 of file diskd.cc.
Referenced by main().
fsHash()
static unsigned int fsHash (const void * key, unsigned int n) static
Definition at line 290 of file diskd.cc.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 302 of file diskd.cc.
References alarm_handler(), assert, DEBUG, fsCmp(), fsHash(), hash, hash_create(), msg_handle(), diomsg::msg_snd_rcv_sz, mypid, SA_RESTART, shmbuf, SQUID_NONBLOCK, xread(), and xstrerr().
msg_handle()
static void msg_handle (diomsg * r, int rl, diomsg * s) static
Definition at line 231 of file diskd.cc.
References _MQD_CLOSE, _MQD_CREATE, _MQD_OPEN, _MQD_READ, _MQD_UNLINK, _MQD_WRITE, assert, diomsg::callback_data, do_close(), do_open(), do_read(), do_unlink(), do_write(), diomsg::id, diomsg::mtype, mypid, diomsg::newstyle, diomsg::offset, diomsg::requestor, diomsg::seq_no, diomsg::shm_offset, shmbuf, diomsg::size, and diomsg::status.
Referenced by main().
xassert()
void xassert (const char * msg, const char * file, int line)
Definition at line 30 of file diskd.cc.
Variable Documentation
DebugLevel
int DebugLevel = 0 static
Definition at line 53 of file diskd.cc.
hash
hash_table* hash = nullptr static
Definition at line 50 of file diskd.cc.
Referenced by do_close(), do_open(), do_read(), do_write(), and main().
mypid
pid_t mypid static
Definition at line 51 of file diskd.cc.
Referenced by do_close(), do_open(), do_read(), do_unlink(), do_write(), main(), and msg_handle().
shmbuf
char* shmbuf static
Definition at line 52 of file diskd.cc.
Referenced by main(), and msg_handle().