Squid Web Cache: squid/src/store/Disks.h File Reference
Disks.h File Reference
#include "store/Controlled.h"
#include "store/forward.h"
Classes
class Store::Disks
summary view of all disk caches (cache_dirs) combined
Namespaces
namespace Store
Functions
void storeDirOpenSwapLogs (void)
int storeDirWriteCleanLogs (int reopen)
void storeDirCloseSwapLogs (void)
void allocate_new_swapdir (Store::DiskConfig &swap)
void free_cachedir (Store::DiskConfig *swap)
void storeDirSwapLog (const StoreEntry *e, int op)
Function Documentation
allocate_new_swapdir()
void allocate_new_swapdir (Store::DiskConfig & swap)
Definition at line 781 of file Disks.cc.
References Store::DiskConfig::n_allocated, Store::DiskConfig::n_configured, and Store::DiskConfig::swapDirs.
Referenced by addSwapDir(), addSwapDir(), addSwapDir(), addSwapDir(), and Store::Disks::Parse().
free_cachedir()
void free_cachedir (Store::DiskConfig * swap)
Definition at line 800 of file Disks.cc.
References Store::DiskConfig::n_allocated, Store::DiskConfig::n_configured, reconfiguring, and Store::DiskConfig::swapDirs.
Referenced by TestRock::tearDown(), TestStoreController::testMaxSize(), TestStoreHashIndex::testMaxSize(), TestStoreController::testStats(), TestStoreHashIndex::testStats(), TestUfs::testUfsDefaultEngine(), and TestUfs::testUfsSearch().
storeDirCloseSwapLogs()
void storeDirCloseSwapLogs (void)
Definition at line 679 of file Disks.cc.
References SquidConfig::cacheSwap, Store::Disk::closeLog(), Config, Store::DiskConfig::n_configured, and SwapDirByIndex().
Referenced by mainReconfigureStart().
storeDirOpenSwapLogs()
void storeDirOpenSwapLogs (void)
Definition at line 672 of file Disks.cc.
References SquidConfig::cacheSwap, Config, Store::DiskConfig::n_configured, Store::Disk::openLog(), and SwapDirByIndex().
Referenced by mainReconfigureFinish(), and storeDirWriteCleanLogs().
storeDirSwapLog()
void storeDirSwapLog (const StoreEntry * e, int op)
An entry written to the swap log MUST have the following properties.
It MUST be a public key. It does no good to log a public ADD, change the key, then log a private DEL. So we need to log a DEL before we change a key from public to private.
It MUST have a valid (> -1) swap_filen.
Definition at line 833 of file Disks.cc.
References asHex(), assert, debugs, StoreEntry::disk(), EBIT_TEST, ENTRY_SPECIAL, StoreEntry::flags, StoreEntry::getMD5Text(), StoreEntry::hasDisk(), KEY_PRIVATE, Store::Disk::logEntry(), Store::NewLocalSearch(), STUB_RETVAL, StoreEntry::swap_dirn, StoreEntry::swap_filen, SWAP_LOG_MAX, SWAP_LOG_NOP, and swap_log_op_str.
Referenced by Fs::Ufs::RebuildState::addIfFresh(), Store::Disks::evictCached(), StoreEntry::forcePublicKey(), and storeSwapOutFileClosed().
storeDirWriteCleanLogs()
int storeDirWriteCleanLogs (int reopen)
storeDirWriteCleanLogs
Writes a "clean" swap log file from in-memory metadata. This is a rewrite of the original function to troll each StoreDir and write the logs, and flush at the end of the run. Thanks goes to Eric Stern, since this solution came out of his COSS code.
Definition at line 695 of file Disks.cc.
References SquidConfig::cacheSwap, Config, current_time, DBG_IMPORTANT, debugs, getCurrentTime(), Important, Store::DiskConfig::n_configured, Store::Controller::store_dirs_rebuilding, storeDirOpenSwapLogs(), SwapDirByIndex(), tvSubDsec(), StoreEntry::write(), and Store::Disk::writeCleanDone().
Referenced by death(), fatal(), fatal_dump(), mainRotate(), SquidShutdown(), and TestUfs::testUfsSearch().