Squid Web Cache: squid/src/dlink.cc File Reference
dlink.cc File Reference
#include "squid.h"
#include "dlink.h"
Functions
void dlinkAdd (void *data, dlink_node *m, dlink_list *list)
void dlinkAddAfter (void *data, dlink_node *m, dlink_node *n, dlink_list *list)
void dlinkAddTail (void *data, dlink_node *m, dlink_list *list)
void dlinkDelete (dlink_node *m, dlink_list *list)
Variables
dlink_list ClientActiveRequests
Function Documentation
dlinkAdd()
void dlinkAdd (void * data, dlink_node * m, dlink_list * list)
Definition at line 15 of file dlink.cc.
References dlink_node::data, dlink_list::head, dlink_node::next, dlink_node::prev, and dlink_list::tail.
Referenced by ClientHttpRequest::ClientHttpRequest(), external_acl::add(), MemObject::addClient(), aioClose(), aioOpen(), aioRead(), aioStat(), aioUnlink(), aioWrite(), clientStreamInit(), external_acl_cache_touch(), fqdncacheAddEntry(), fqdncacheLockEntry(), idnsCheckQueue(), idnsSendQuery(), ipcacheAddEntry(), ipcacheLockEntry(), clientReplyContext::makeThisHead(), and ACLExternal::startLookup().
dlinkAddAfter()
void dlinkAddAfter (void * data, dlink_node * m, dlink_node * n, dlink_list * list)
Definition at line 31 of file dlink.cc.
References assert, dlink_node::data, dlink_node::next, dlink_node::prev, and dlink_list::tail.
Referenced by clientStreamInsertHead().
dlinkAddTail()
void dlinkAddTail (void * data, dlink_node * m, dlink_list * list)
Definition at line 48 of file dlink.cc.
References dlink_node::data, dlink_list::head, dlink_node::next, dlink_node::prev, and dlink_list::tail.
Referenced by Auth::User::absorb(), Auth::User::addIp(), authDigestUserLinkNonce(), Acl::Node::cacheMatchAcl(), logfileNewBuffer(), lru_add(), lru_purgeNext(), lru_referenced(), Helper::Client::openSessions(), and statefulhelper::openSessions().
dlinkDelete()
void dlinkDelete (dlink_node * m, dlink_list * list)
Definition at line 64 of file dlink.cc.
References dlink_list::head, dlink_node::next, dlink_node::prev, and dlink_list::tail.
Referenced by ClientHttpRequest::~ClientHttpRequest(), helper_stateful_server::~helper_stateful_server(), Helper::Session::~Session(), Auth::User::absorb(), aclCacheMatchFlush(), Auth::User::addIp(), aioCancel(), authDigestNonceUserUnlink(), DiskThreadsIOStrategy::callback(), Auth::User::clearIp(), external_acl_cache_delete(), external_acl_cache_touch(), externalAclHandleReply(), fqdncacheLockEntry(), fqdncacheRelease(), idnsCheckQueue(), idnsGrokReply(), ipcacheLockEntry(), ipcacheRelease(), logfileFreeBuffer(), lru_purgeNext(), lru_referenced(), lru_remove(), clientReplyContext::makeThisHead(), clientStreamNode::removeFromStream(), Auth::User::removeIp(), and storeUnregister().
Variable Documentation
ClientActiveRequests
dlink_list ClientActiveRequests
Definition at line 12 of file dlink.cc.
Referenced by ClientHttpRequest::ClientHttpRequest(), ClientHttpRequest::~ClientHttpRequest(), clientReplyContext::makeThisHead(), statClientRequests(), and statInit().