Squid Web Cache: squid/src/dns/forward.h File Reference
forward.h File Reference
#include "ip/forward.h"
#include "sbuf/forward.h"
Namespaces
namespace Dns
generic DNS API
Typedefs
typedef void IDNSCB(void *cbdata, const rfc1035_rr *answer, const int recordsInAnswer, const char *error, bool lastAnswer)
using Dns::DomainName = SBuf
Functions
void Dns::Init (void)
void idnsALookup (const char *, IDNSCB *, void *)
void idnsPTRLookup (const Ip::Address &, IDNSCB *, void *)
Typedef Documentation
IDNSCB
typedef void IDNSCB(void *cbdata, const rfc1035_rr *answer, const int recordsInAnswer, const char *error, bool lastAnswer)
Definition at line 17 of file forward.h.
Function Documentation
idnsALookup()
void idnsALookup (const char * name, IDNSCB * callback, void * data)
Definition at line 1753 of file dns_internal.cc.
References asHex(), idns_query::buf, Config, DBG_IMPORTANT, debugs, idns_query::do_searchpath, idns_query::domain, _sp::domain, idnsCachedLookup(), idnsCallbackOnEarlyError(), idnsCheckMDNS(), idnsQueryID(), idnsSendSlaveAAAAQuery(), idnsStartQuery(), idns_query::name, ndots, npc, NS_MAXDNAME, SquidConfig::onoff, idns_query::orig, idns_query::query, idns_query::query_id, SquidConfig::res_defnames, rfc3596BuildAQuery(), searchpath, and idns_query::sz.
Referenced by ipcache_nbgethostbyname_().
idnsPTRLookup()
void idnsPTRLookup (const Ip::Address & addr, IDNSCB * callback, void * data)
Definition at line 1811 of file dns_internal.cc.
References asHex(), idns_query::buf, Config, debugs, SquidConfig::dns_mdns, Ip::Address::getInAddr(), idnsCachedLookup(), idnsCallbackOnEarlyError(), idnsQueryID(), idnsStartQuery(), Ip::Address::isIPv6(), MAX_IPSTRLEN, _rfc1035_query::name, SquidConfig::onoff, idns_query::permit_mdns, idns_query::query, idns_query::query_id, rfc3596BuildPTRQuery4(), rfc3596BuildPTRQuery6(), idns_query::sz, and Ip::Address::toStr().
Referenced by fqdncache_nbgethostbyaddr().