Squid Web Cache: squid/src/dns_internal.cc File Reference
dns_internal.cc File Reference
#include "squid.h"
#include "base/CodeContext.h"
#include "base/InstanceId.h"
#include "base/IoManip.h"
#include "base/Random.h"
#include "base/RunnersRegistry.h"
#include "comm.h"
#include "comm/Connection.h"
#include "comm/ConnOpener.h"
#include "comm/Loops.h"
#include "comm/Read.h"
#include "comm/Write.h"
#include "debug/Messages.h"
#include "dlink.h"
#include "dns/forward.h"
#include "dns/rfc3596.h"
#include "event.h"
#include "fd.h"
#include "fde.h"
#include "ip/tools.h"
#include "MemBuf.h"
#include "mgr/Registration.h"
#include "snmp_agent.h"
#include "SquidConfig.h"
#include "Store.h"
#include "tools.h"
#include "util.h"
#include "wordlist.h"
#include "snmp_core.h"
#include <cerrno>
Classes
class idns_query
class nsvc
class ns
class Dns::ConfigRr
manage DNS internal component
struct _sp
Namespaces
namespace Dns
generic DNS API
Macros
#define _PATH_RESCONF "/etc/resolv.conf"
#define NS_DEFAULTPORT 53
#define NS_MAXDNAME 1025
#define MAXDNSRCH 6
#define RESOLV_BUFSZ NS_MAXDNAME * MAXDNSRCH + sizeof("search ") + 1
#define IDNS_MAX_TRIES 20
#define MAX_RCODE 17
#define MAX_ATTEMPT 3
Typedefs
typedef struct _sp sp
Functions
InstanceIdDefinitions (idns_query, "dns")
DefineRunnerRegistratorIn (Dns, ConfigRr)
static void idnsAddNameserver (const char *buf)
static void idnsAddMDNSNameservers ()
static void idnsAddPathComponent (const char *buf)
static void idnsFreeSearchpath (void)
static bool idnsParseNameservers (void)
static bool idnsParseResolvConf (void)
static void idnsStartQuery (idns_query *q, IDNSCB *callback, void *data)
static void idnsSendQuery (idns_query *q)
static void idnsDoSendQueryVC (nsvc *vc)
static int idnsFromKnownNameserver (Ip::Address const &from)
static idns_query * idnsFindQuery (unsigned short id)
static void idnsGrokReply (const char *buf, size_t sz, int from_ns)
static void idnsTickleQueue (void)
static void idnsRcodeCount (int, int)
static unsigned short idnsQueryID (void)
static void idnsSendSlaveAAAAQuery (idns_query *q)
static void idnsCallbackOnEarlyError (IDNSCB *callback, void *cbdata, const char *error)
static void idnsCheckMDNS (idns_query *q)
static void idnsStats (StoreEntry *sentry)
static void idnsSentQueryVC (const Comm::ConnectionPointer &conn, char *, size_t size, Comm::Flag flag, int, void *data)
static void idnsInitVCConnected (const Comm::ConnectionPointer &conn, Comm::Flag status, int, void *data)
static void idnsVCClosed (const CommCloseCbParams &params)
static void idnsInitVC (size_t nsv)
static void idnsSendQueryVC (idns_query *q, size_t nsn)
static bool idnsStillPending (const idns_query *master)
static std::ostream & operator<< (std::ostream &os, const idns_query &answered)
static bool idnsCallbackOneWithAnswer (IDNSCB *callback, void *cbdata, const idns_query &answered, const bool lastAnswer)
safely sends one set of DNS records (or an error) to the caller
static void idnsCallbackNewCallerWithOldAnswers (IDNSCB *callback, void *cbdata, const idns_query *const master)
static void idnsCallbackAllCallersWithNewAnswer (const idns_query *const answered, const bool lastAnswer)
static void idnsCallback (idns_query *q, const char *error)
static void idnsRead (int fd, void *)
static void idnsCheckQueue (void *)
static void idnsReadVC (const Comm::ConnectionPointer &conn, char *buf, size_t len, Comm::Flag flag, int, void *data)
static void idnsReadVCHeader (const Comm::ConnectionPointer &conn, char *buf, size_t len, Comm::Flag flag, int, void *data)
static void idnsShutdownAndFreeState (const char *reason)
static int idnsCachedLookup (const char *key, IDNSCB *callback, void *data)
void idnsALookup (const char *name, IDNSCB *callback, void *data)
void idnsPTRLookup (const Ip::Address &addr, IDNSCB *callback, void *data)
variable_list * snmp_netDnsFn (variable_list *Var, snint *ErrP)
Variables
static int RcodeMatrix [MAX_RCODE][MAX_ATTEMPT]
static const char * Rcodes []
static std::vector< ns > nameservers
static sp * searchpath = nullptr
static int nns_mdns_count = 0
static int npc = 0
static int npc_alloc = 0
static int ndots = 1
static dlink_list lru_list
static int event_queued = 0
static hash_table * idns_lookup_hash = nullptr
static OBJH idnsStats
static IOCB idnsReadVCHeader
static CNCB idnsInitVCConnected
static IOCB idnsReadVC
static IOCB idnsSentQueryVC
static PF idnsRead
static EVH idnsCheckQueue
static CLCB idnsVCClosed
Macro Definition Documentation
_PATH_RESCONF
#define _PATH_RESCONF "/etc/resolv.conf"
Definition at line 58 of file dns_internal.cc.
IDNS_MAX_TRIES
#define IDNS_MAX_TRIES 20
Definition at line 77 of file dns_internal.cc.
MAX_ATTEMPT
#define MAX_ATTEMPT 3
Definition at line 79 of file dns_internal.cc.
MAX_RCODE
#define MAX_RCODE 17
Definition at line 78 of file dns_internal.cc.
MAXDNSRCH
#define MAXDNSRCH 6
Definition at line 69 of file dns_internal.cc.
NS_DEFAULTPORT
#define NS_DEFAULTPORT 53
Definition at line 61 of file dns_internal.cc.
NS_MAXDNAME
#define NS_MAXDNAME 1025
Definition at line 65 of file dns_internal.cc.
RESOLV_BUFSZ
#define RESOLV_BUFSZ NS_MAXDNAME * MAXDNSRCH + sizeof("search ") + 1
Definition at line 74 of file dns_internal.cc.
Typedef Documentation
sp
typedef struct _sp sp
Definition at line 102 of file dns_internal.cc.
Function Documentation
DefineRunnerRegistratorIn()
DefineRunnerRegistratorIn (Dns , ConfigRr)
idnsAddMDNSNameservers()
static void idnsAddMDNSNameservers () static
Definition at line 298 of file dns_internal.cc.
References Config, SquidConfig::dns_mdns, idnsAddNameserver(), nameservers, nns_mdns_count, and SquidConfig::onoff.
Referenced by Dns::Init().
idnsAddNameserver()
static void idnsAddNameserver (const char * buf) static
Definition at line 322 of file dns_internal.cc.
References DBG_CRITICAL, DBG_IMPORTANT, debugs, Ip::Address::isAnyAddr(), nameservers, NS_DEFAULTPORT, Ip::Address::port(), RFC1035_DEFAULT_PACKET_SZ, Ip::Address::setIPv4(), and Ip::Address::setLocalhost().
Referenced by idnsAddMDNSNameservers(), idnsParseNameservers(), idnsParseResolvConf(), and Dns::Init().
idnsAddPathComponent()
static void idnsAddPathComponent (const char * buf) static
Definition at line 353 of file dns_internal.cc.
References assert, debugs, _sp::domain, npc, npc_alloc, safe_free, searchpath, Tolower(), and xcalloc().
Referenced by idnsParseResolvConf().
idnsALookup()
void idnsALookup (const char * name, IDNSCB * callback, void * data)
Definition at line 1753 of file dns_internal.cc.
References asHex(), idns_query::buf, Config, DBG_IMPORTANT, debugs, idns_query::do_searchpath, idns_query::domain, _sp::domain, idnsCachedLookup(), idnsCallbackOnEarlyError(), idnsCheckMDNS(), idnsQueryID(), idnsSendSlaveAAAAQuery(), idnsStartQuery(), idns_query::name, ndots, npc, NS_MAXDNAME, SquidConfig::onoff, idns_query::orig, idns_query::query, idns_query::query_id, SquidConfig::res_defnames, rfc3596BuildAQuery(), searchpath, and idns_query::sz.
Referenced by ipcache_nbgethostbyname_().
idnsCachedLookup()
static int idnsCachedLookup (const char * key, IDNSCB * callback, void * data) static
Definition at line 1685 of file dns_internal.cc.
References idns_query::callback, idns_query::callback_data, cbdataReference, hash_lookup(), idns_lookup_hash, idnsCallbackNewCallerWithOldAnswers(), idnsStillPending(), and idns_query::queue.
Referenced by idnsALookup(), and idnsPTRLookup().
idnsCallback()
static void idnsCallback (idns_query * q, const char * error) static
Definition at line 1149 of file dns_internal.cc.
References error(), idns_query::error, hash_table::hash, hash_remove_link(), idns_lookup_hash, idnsCallbackAllCallersWithNewAnswer(), idnsStillPending(), and idns_query::master.
Referenced by idnsCheckQueue(), and idnsGrokReply().
idnsCallbackAllCallersWithNewAnswer()
static void idnsCallbackAllCallersWithNewAnswer (const idns_query *const answered, const bool lastAnswer) static
Definition at line 1135 of file dns_internal.cc.
References CallBack(), debugs, and idns_query::master.
Referenced by idnsCallback().
idnsCallbackNewCallerWithOldAnswers()
static void idnsCallbackNewCallerWithOldAnswers (IDNSCB * callback, void * cbdata, const idns_query *const master) static
Definition at line 1121 of file dns_internal.cc.
References idnsCallbackOneWithAnswer(), and idns_query::slave.
Referenced by idnsCachedLookup().
idnsCallbackOnEarlyError()
static void idnsCallbackOnEarlyError (IDNSCB * callback, void * cbdata, const char * error) static
Definition at line 1100 of file dns_internal.cc.
References debugs, and error().
Referenced by idnsALookup(), and idnsPTRLookup().
idnsCallbackOneWithAnswer()
static bool idnsCallbackOneWithAnswer (IDNSCB * callback, void * cbdata, const idns_query & answered, const bool lastAnswer) static
Definition at line 1110 of file dns_internal.cc.
References idns_query::ancount, _rfc1035_message::answer, cbdataReferenceValid(), debugs, idns_query::error, and idns_query::message.
Referenced by idnsCallbackNewCallerWithOldAnswers().
idnsCheckMDNS()
static void idnsCheckMDNS (idns_query * q) static
Definition at line 286 of file dns_internal.cc.
References Config, SquidConfig::dns_mdns, idns_query::name, SquidConfig::onoff, and idns_query::permit_mdns.
Referenced by idnsALookup(), idnsGrokReply(), and idnsSendSlaveAAAAQuery().
idnsCheckQueue()
static void idnsCheckQueue (void *) static
Definition at line 1405 of file dns_internal.cc.
References asHex(), Config, current_time, dlink_node::data, debugs, dlinkAdd(), dlinkDelete(), event_queued, SquidConfig::idns_query, SquidConfig::idns_retransmit, idnsCallback(), idnsSendQuery(), idnsTickleQueue(), idns_query::lru, lru_list, nameservers, idns_query::nsends, idns_query::pending, dlink_node::prev, idns_query::query_id, idns_query::queue_t, idns_query::rcode, rfc1035ErrorMessage(), idns_query::sent_t, idns_query::start_t, dlink_list::tail, SquidConfig::Timeout, tvSubDsec(), tvSubMsec(), and idns_query::xact_id.
idnsDoSendQueryVC()
static void idnsDoSendQueryVC (nsvc * vc) static
Definition at line 811 of file dns_internal.cc.
References nsvc::busy, commCbCall(), commSetConnTimeout(), Config, nsvc::conn, MemBuf::contentSize(), Comm::Connection::fd, fd_table, SquidConfig::idns_query, idnsSentQueryVC, nsvc::queue, SquidConfig::Timeout, and Comm::Write().
Referenced by idnsInitVCConnected(), idnsSendQueryVC(), and idnsSentQueryVC().
idnsFindQuery()
static idns_query * idnsFindQuery (unsigned short id) static
Definition at line 1041 of file dns_internal.cc.
References dlink_node::data, lru_list, dlink_node::prev, idns_query::query_id, and dlink_list::tail.
Referenced by idnsGrokReply(), and idnsQueryID().
idnsFreeSearchpath()
static void idnsFreeSearchpath (void) static
Definition at line 382 of file dns_internal.cc.
References npc, npc_alloc, safe_free, and searchpath.
Referenced by idnsParseResolvConf(), and idnsShutdownAndFreeState().
idnsFromKnownNameserver()
static int idnsFromKnownNameserver (Ip::Address const & from) static
Definition at line 1025 of file dns_internal.cc.
References nameservers, and Ip::Address::port().
Referenced by idnsRead().
idnsGrokReply()
static void idnsGrokReply (const char * buf, size_t sz, int from_ns) static
Definition at line 1171 of file dns_internal.cc.
References idns_query::ancount, _rfc1035_message::answer, asHex(), assert, idns_query::attempt, idns_query::buf, DBG_IMPORTANT, debugs, dlinkDelete(), idns_query::do_searchpath, idns_query::domain, _sp::domain, _rfc1035_message::id, idnsCallback(), idnsCheckMDNS(), idnsFindQuery(), idnsQueryID(), idnsRcodeCount(), idnsSendQuery(), idnsSendSlaveAAAAQuery(), idns_query::lru, lru_list, idns_query::master, MAX_ATTEMPT, idns_query::message, min(), idns_query::name, _rfc1035_query::name, nameservers, idns_query::need_vc, npc, idns_query::nsends, idns_query::orig, idns_query::pending, _rfc1035_message::query, idns_query::query, idns_query::query_id, idns_query::rcode, RFC1035_DEFAULT_PACKET_SZ, rfc1035ErrorMessage(), rfc1035MessageDestroy(), rfc1035MessageUnpack(), rfc1035QueryCompare(), rfc3596BuildAQuery(), searchpath, server, idns_query::slave, idns_query::sz, and _rfc1035_message::tc.
Referenced by idnsRead(), and idnsReadVC().
idnsInitVC()
static void idnsInitVC (size_t nsv) static
Definition at line 889 of file dns_internal.cc.
References SquidConfig::Addrs, assert, commCbCall(), Config, nsvc::conn, SquidConfig::connect, idnsInitVCConnected, Ip::Address::isIPv4(), Ip::Address::isNoAddr(), Comm::Connection::local, nameservers, Comm::Connection::remote, Comm::Connection::setAddrs(), Comm::ConnOpener::setHost(), Ip::Address::setIPv4(), AsyncJob::Start(), SquidConfig::Timeout, SquidConfig::udp_incoming, and SquidConfig::udp_outgoing.
Referenced by idnsSendQueryVC().
idnsInitVCConnected()
static void idnsInitVCConnected (const Comm::ConnectionPointer & conn, Comm::Flag status, int , void * data) static
Definition at line 844 of file dns_internal.cc.
References nsvc::busy, comm_add_close_handler(), comm_read(), commCbCall(), nsvc::conn, DBG_IMPORTANT, debugs, Comm::Connection::fd, idnsDoSendQueryVC(), idnsReadVCHeader, idnsVCClosed, MAX_IPSTRLEN, nsvc::msglen, nameservers, nsvc::ns, and Comm::OK.
idnsParseNameservers()
static bool idnsParseNameservers (void) static
Definition at line 389 of file dns_internal.cc.
References Config, debugs, SquidConfig::dns, idnsAddNameserver(), Important, and SquidConfig::nameservers.
Referenced by Dns::Init().
idnsParseResolvConf()
static bool idnsParseResolvConf (void) static
Definition at line 401 of file dns_internal.cc.
References _PATH_RESCONF, DBG_IMPORTANT, debugs, getMyHostname(), idnsAddNameserver(), idnsAddPathComponent(), idnsFreeSearchpath(), ndots, npc, RESOLV_BUFSZ, w_space, and xstrerr().
Referenced by Dns::Init().
idnsPTRLookup()
void idnsPTRLookup (const Ip::Address & addr, IDNSCB * callback, void * data)
Definition at line 1811 of file dns_internal.cc.
References asHex(), idns_query::buf, Config, debugs, SquidConfig::dns_mdns, Ip::Address::getInAddr(), idnsCachedLookup(), idnsCallbackOnEarlyError(), idnsQueryID(), idnsStartQuery(), Ip::Address::isIPv6(), MAX_IPSTRLEN, _rfc1035_query::name, SquidConfig::onoff, idns_query::permit_mdns, idns_query::query, idns_query::query_id, rfc3596BuildPTRQuery4(), rfc3596BuildPTRQuery6(), idns_query::sz, and Ip::Address::toStr().
Referenced by fqdncache_nbgethostbyaddr().
idnsQueryID()
static unsigned short idnsQueryID (void) static
Definition at line 1057 of file dns_internal.cc.
References DBG_IMPORTANT, debugs, idnsFindQuery(), and RandomSeed32().
Referenced by idnsALookup(), idnsGrokReply(), idnsPTRLookup(), and idnsSendSlaveAAAAQuery().
idnsRcodeCount()
static void idnsRcodeCount (int rcode, int attempt) static
Definition at line 1536 of file dns_internal.cc.
References MAX_ATTEMPT, MAX_RCODE, and RcodeMatrix.
Referenced by idnsGrokReply().
idnsRead()
static void idnsRead (int fd, void *) static
Definition at line 1320 of file dns_internal.cc.
References assert, COMM_SELECT_READ, comm_udp_recvfrom(), Config, DBG_IMPORTANT, debugs, fd_bytes(), dlink_list::head, idnsFromKnownNameserver(), idnsGrokReply(), idnsRead, SquidConfig::ignore_unknown_nameservers, ignoreErrno(), INCOMING_DNS_MAX, incoming_sockets_accepted, lru_list, max(), MYNAME, nameservers, SquidConfig::onoff, Read, Comm::SetSelect(), squid_curtime, SQUID_UDP_SO_RCVBUF, and xstrerr().
idnsReadVC()
static void idnsReadVC (const Comm::ConnectionPointer & conn, char * buf, size_t len, Comm::Flag flag, int , void * data) static
Definition at line 1459 of file dns_internal.cc.
References assert, MemBuf::buf, MemBuf::clean(), Comm::Connection::close(), comm_read(), commCbCall(), MemBuf::contentSize(), debugs, Comm::ERR_CLOSING, idnsGrokReply(), idnsReadVC, idnsReadVCHeader, Comm::IsConnOpen(), nsvc::msg, nsvc::msglen, nameservers, nsvc::ns, Comm::OK, and MemBuf::size.
idnsReadVCHeader()
static void idnsReadVCHeader (const Comm::ConnectionPointer & conn, char * buf, size_t len, Comm::Flag flag, int , void * data) static
Definition at line 1492 of file dns_internal.cc.
References assert, MemBuf::buf, Comm::Connection::close(), comm_read(), commCbCall(), Comm::ERR_CLOSING, idnsReadVC, idnsReadVCHeader, MemBuf::init(), Comm::IsConnOpen(), nsvc::msg, nsvc::msglen, Comm::OK, and nsvc::read_msglen.
idnsSendQuery()
static void idnsSendQuery (idns_query * q) static
Definition at line 954 of file dns_internal.cc.
References assert, idns_query::buf, comm_udp_sendto(), current_time, DBG_IMPORTANT, debugs, dlinkAdd(), DnsSocketA, DnsSocketB, fd_bytes(), idnsSendQueryVC(), idnsTickleQueue(), idns_query::lru, lru_list, MYNAME, nameservers, idns_query::need_vc, dlink_node::next, nns_mdns_count, idns_query::nsends, idns_query::pending, idns_query::permit_mdns, dlink_node::prev, idns_query::queue_t, idns_query::sent_t, idns_query::sz, Write, and xstrerr().
Referenced by idnsCheckQueue(), idnsGrokReply(), idnsSendSlaveAAAAQuery(), and idnsStartQuery().
idnsSendQueryVC()
static void idnsSendQueryVC (idns_query * q, size_t nsn) static
Definition at line 914 of file dns_internal.cc.
References MemBuf::append(), assert, idns_query::buf, MemBuf::contentSize(), DBG_IMPORTANT, debugs, Debug::Extra(), head, idnsDoSendQueryVC(), idnsInitVC(), MemBuf::init(), MemBuf::isNull(), MAX_IPSTRLEN, idns_query::name, nameservers, MemBuf::potentialSpaceSize(), nsvc::queue, and idns_query::sz.
Referenced by idnsSendQuery().
idnsSendSlaveAAAAQuery()
static void idnsSendSlaveAAAAQuery (idns_query * q) static
Definition at line 1728 of file dns_internal.cc.
References asHex(), idns_query::buf, debugs, idnsCheckMDNS(), idnsQueryID(), idnsSendQuery(), idns_query::master, idns_query::name, idns_query::orig, idns_query::query, idns_query::query_id, rfc3596BuildAAAAQuery(), idns_query::slave, idns_query::start_t, and idns_query::sz.
Referenced by idnsALookup(), and idnsGrokReply().
idnsSentQueryVC()
static void idnsSentQueryVC (const Comm::ConnectionPointer & conn, char * , size_t size, Comm::Flag flag, int , void * data) static
Definition at line 790 of file dns_internal.cc.
References nsvc::busy, Comm::Connection::close(), Comm::ERR_CLOSING, Comm::Connection::fd, fd_table, idnsDoSendQueryVC(), Comm::IsConnOpen(), Comm::OK, and size.
idnsShutdownAndFreeState()
static void idnsShutdownAndFreeState (const char * reason) static
Definition at line 1643 of file dns_internal.cc.
References comm_close, debugs, DnsSocketA, DnsSocketB, idnsFreeSearchpath(), Comm::IsConnOpen(), nameservers, and server.
Referenced by Dns::ConfigRr::endingShutdown(), and Dns::ConfigRr::startReconfigure().
idnsStartQuery()
static void idnsStartQuery (idns_query * q, IDNSCB * callback, void * data) static
Definition at line 1715 of file dns_internal.cc.
References idns_query::callback, idns_query::callback_data, cbdataReference, current_time, idns_query::hash, hash_join(), idns_lookup_hash, idnsSendQuery(), hash_link::key, idns_query::orig, and idns_query::start_t.
Referenced by idnsALookup(), and idnsPTRLookup().
idnsStats()
static void idnsStats (StoreEntry * sentry) static
Definition at line 703 of file dns_internal.cc.
References Config, current_time, dlink_node::data, SquidConfig::dns, dlink_list::head, lru_list, MAX_ATTEMPT, MAX_IPSTRLEN, MAX_RCODE, idns_query::name, nameservers, dlink_node::next, npc, idns_query::nsends, SquidConfig::packet_max, idns_query::permit_mdns, idns_query::query_id, RcodeMatrix, Rcodes, searchpath, idns_query::sent_t, server, idns_query::start_t, storeAppendPrintf(), idns_query::sz, and tvSubDsec().
idnsStillPending()
static bool idnsStillPending (const idns_query * master) static
Returns
whether master or associated queries are still waiting for replies
Definition at line 1079 of file dns_internal.cc.
References assert, idns_query::master, and idns_query::slave.
Referenced by idnsCachedLookup(), and idnsCallback().
idnsTickleQueue()
static void idnsTickleQueue (void) static
Definition at line 774 of file dns_internal.cc.
References Config, event_queued, eventAdd(), SquidConfig::idns_query, SquidConfig::idns_retransmit, idnsCheckQueue, lru_list, min(), dlink_list::tail, and SquidConfig::Timeout.
Referenced by idnsCheckQueue(), and idnsSendQuery().
idnsVCClosed()
static void idnsVCClosed (const CommCloseCbParams & params) static
Definition at line 868 of file dns_internal.cc.
References nsvc::conn, CommCommonCbParams::data, and Comm::Connection::noteClosure().
InstanceIdDefinitions()
InstanceIdDefinitions (idns_query , "dns")
operator<<()
static std::ostream & operator<< (std::ostream & os, const idns_query & answered) static
Definition at line 1089 of file dns_internal.cc.
References idns_query::ancount, and idns_query::error.
snmp_netDnsFn()
variable_list * snmp_netDnsFn (variable_list * Var, snint * ErrP)
Definition at line 1854 of file dns_internal.cc.
References debugs, DNS_REP, DNS_REQ, DNS_SERVERS, LEN_SQ_NET, variable_list::name, variable_list::name_length, nameservers, server, SMI_COUNTER32, SNMP_ERR_NOERROR, SNMP_ERR_NOSUCHNAME, snmp_var_new_integer(), and snmpDebugOid().
Referenced by snmpInit().
Variable Documentation
event_queued
int event_queued = 0 static
Definition at line 230 of file dns_internal.cc.
Referenced by idnsCheckQueue(), and idnsTickleQueue().
idns_lookup_hash
hash_table* idns_lookup_hash = nullptr static
Definition at line 231 of file dns_internal.cc.
Referenced by idnsCachedLookup(), idnsCallback(), idnsStartQuery(), and Dns::Init().
idnsCheckQueue
EVH idnsCheckQueue static
Definition at line 277 of file dns_internal.cc.
Referenced by idnsTickleQueue().
idnsInitVCConnected
CNCB idnsInitVCConnected static
Definition at line 269 of file dns_internal.cc.
Referenced by idnsInitVC().
idnsRead
PF idnsRead static
Definition at line 276 of file dns_internal.cc.
Referenced by idnsRead(), and Dns::Init().
idnsReadVC
IOCB idnsReadVC static
Definition at line 270 of file dns_internal.cc.
Referenced by idnsReadVC(), and idnsReadVCHeader().
idnsReadVCHeader
IOCB idnsReadVCHeader static
Definition at line 267 of file dns_internal.cc.
Referenced by idnsInitVCConnected(), idnsReadVC(), and idnsReadVCHeader().
idnsSentQueryVC
IOCB idnsSentQueryVC static
Definition at line 271 of file dns_internal.cc.
Referenced by idnsDoSendQueryVC().
idnsStats
OBJH idnsStats static
Definition at line 254 of file dns_internal.cc.
Referenced by Dns::Init().
idnsVCClosed
CLCB idnsVCClosed static
Definition at line 280 of file dns_internal.cc.
Referenced by idnsInitVCConnected().
lru_list
dlink_list lru_list static
Definition at line 229 of file dns_internal.cc.
Referenced by idnsCheckQueue(), idnsFindQuery(), idnsGrokReply(), idnsRead(), idnsSendQuery(), idnsStats(), and idnsTickleQueue().
nameservers
std::vector<ns> nameservers static
Definition at line 223 of file dns_internal.cc.
Referenced by nsvc::~nsvc(), idnsAddMDNSNameservers(), idnsAddNameserver(), idnsCheckQueue(), idnsFromKnownNameserver(), idnsGrokReply(), idnsInitVC(), idnsInitVCConnected(), idnsRead(), idnsReadVC(), idnsSendQuery(), idnsSendQueryVC(), idnsShutdownAndFreeState(), idnsStats(), Dns::Init(), and snmp_netDnsFn().
ndots
int ndots = 1 static
Definition at line 228 of file dns_internal.cc.
Referenced by idnsALookup(), and idnsParseResolvConf().
nns_mdns_count
int nns_mdns_count = 0 static
Definition at line 225 of file dns_internal.cc.
Referenced by idnsAddMDNSNameservers(), and idnsSendQuery().
npc
int npc = 0 static
Definition at line 226 of file dns_internal.cc.
Referenced by idnsAddPathComponent(), idnsALookup(), idnsFreeSearchpath(), idnsGrokReply(), idnsParseResolvConf(), and idnsStats().
npc_alloc
int npc_alloc = 0 static
Definition at line 227 of file dns_internal.cc.
Referenced by idnsAddPathComponent(), and idnsFreeSearchpath().
RcodeMatrix
int RcodeMatrix[MAX_RCODE][MAX_ATTEMPT] static
Definition at line 80 of file dns_internal.cc.
Referenced by idnsRcodeCount(), idnsStats(), and Dns::Init().
Rcodes
const char* Rcodes[] static
Initial value:
= {
    "Success",
    "Packet Format Error",
    "DNS Server Failure",
    "Non-Existent Domain",
    "Not Implemented",
    "Query Refused",
    "Name Exists when it should not",
    "RR Set Exists when it should not",
    "RR Set that should exist does not",
    "Server Not Authoritative for zone",
    "Name not contained in zone",
    "","","","","",
    "Bad OPT Version or TSIG Signature Failure"
}
Definition at line 82 of file dns_internal.cc.
Referenced by idnsStats().
searchpath
sp* searchpath = nullptr static
Definition at line 224 of file dns_internal.cc.
Referenced by idnsAddPathComponent(), idnsALookup(), idnsFreeSearchpath(), idnsGrokReply(), and idnsStats().