Squid Web Cache: squid/src/acl/DomainData.cc File Reference
DomainData.cc File Reference
#include "squid.h"
#include "acl/Checklist.h"
#include "acl/DomainData.h"
#include "acl/SplayInserter.h"
#include "anyp/Uri.h"
#include "cache_cf.h"
#include "ConfigParser.h"
#include "debug/Stream.h"
#include "util.h"
Classes
struct AclDomainDataDumpVisitor
Functions
template<class T >
void xRefFree (T &thing)
template<class T >
int splaystrcasecmp (T &l, T &r)
template<class T >
int splaystrcmp (T &l, T &r)
static int aclHostDomainCompare (char *const &a, char *const &b)
Function Documentation
aclHostDomainCompare()
static int aclHostDomainCompare (char *const & a, char *const & b) static
Definition at line 53 of file DomainData.cc.
References matchDomainName().
Referenced by ACLDomainData::match(), and ACLServerNameData::match().
splaystrcasecmp()
template<class T > int splaystrcasecmp (T & l, T & r) inline
Definition at line 35 of file DomainData.cc.
splaystrcmp()
template<class T > int splaystrcmp (T & l, T & r) inline
Definition at line 42 of file DomainData.cc.
xRefFree()
template<class T > void xRefFree (T & thing) inline
Definition at line 23 of file DomainData.cc.
References xfree.