Squid Web Cache: squid/src/Downloader.cc File Reference
Downloader.cc File Reference
#include "squid.h"
#include "base/Raw.h"
#include "client_side.h"
#include "client_side_reply.h"
#include "client_side_request.h"
#include "ClientRequestContext.h"
#include "clientStream.h"
#include "Downloader.h"
#include "fatal.h"
#include "http/one/RequestParser.h"
#include "http/Stream.h"
Classes
class DownloaderContext
Functions
std::ostream & operator<< (std::ostream &os, const DownloaderAnswer &answer)
static void downloaderRecipient (clientStreamNode *node, ClientHttpRequest *http, HttpReply *rep, StoreIOBuffer receivedData)
static void downloaderDetach (clientStreamNode *node, ClientHttpRequest *http)
Function Documentation
downloaderDetach()
static void downloaderDetach (clientStreamNode * node, ClientHttpRequest * http) static
Definition at line 128 of file Downloader.cc.
References clientStreamDetach(), debugs, and MYNAME.
Referenced by Downloader::buildRequest().
downloaderRecipient()
static void downloaderRecipient (clientStreamNode * node, ClientHttpRequest * http, HttpReply * rep, StoreIOBuffer receivedData) static
Definition at line 106 of file Downloader.cc.
References assert, cbdataReferenceValid(), debugs, DownloaderContext::downloader, Downloader::handleReply(), MYNAME, node::next, and CbcPointer< Cbc >::valid().
Referenced by Downloader::buildRequest().
operator<<()
std::ostream & operator<< (std::ostream & os, const DownloaderAnswer & answer)
Definition at line 62 of file Downloader.cc.
References SBuf::length(), DownloaderAnswer::outcome, DownloaderAnswer::resource, and Http::scOkay.