Squid Web Cache: squid/src/error/Error.h File Reference
Error.h File Reference
#include "error/Detail.h"
#include "error/forward.h"
#include "mem/PoolingAllocator.h"
#include <iosfwd>
#include <vector>
Classes
class Error
a transaction problem
Typedefs
using ErrorDetails = std::vector< ErrorDetailPointer, PoolingAllocator< ErrorDetailPointer > >
zero or more details of a single error
Functions
std::ostream & operator<< (std::ostream &, const ErrorDetails &)
err_type errorTypeByName (const char *name)
const char * errorTypeName (err_type err)
std::ostream & operator<< (std::ostream &os, const Error &error)
Variables
const char * err_type_str []
Typedef Documentation
ErrorDetails
using ErrorDetails = std::vector<ErrorDetailPointer, PoolingAllocator<ErrorDetailPointer> >
Definition at line 20 of file Error.h.
Function Documentation
errorTypeByName()
err_type errorTypeByName (const char * name) inline
Definition at line 67 of file Error.h.
References ERR_MAX, and err_type_str.
Referenced by ACLSquidErrorData::parse().
errorTypeName()
const char * errorTypeName (err_type err) inline
Definition at line 77 of file Error.h.
References ERR_MAX, and err_type_str.
Referenced by ACLSquidErrorData::dump(), ACLSquidErrorData::match(), operator<<(), ClientRequestContext::sslBumpAccessCheck(), and Error::update().
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const ErrorDetails & details)
prints all given details separated by '+'; if no details were given, prints nothing
Definition at line 69 of file Error.cc.
References AsList< Container >::delimitedBy().
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const Error & error)
Definition at line 76 of file Error.cc.
References error(), errorTypeName(), and AsList< Container >::prefixedBy().
Variable Documentation
err_type_str
const char* err_type_str[] extern
Definition at line 16 of file stub_liberror.cc.
Referenced by ErrorState::buildBody(), errorInitialize(), errorPageId(), errorPageName(), errorTypeByName(), errorTypeName(), and ErrorPage::BuildErrorPrinter::printLocation().