Squid Web Cache: squid/src/error/Error.cc File Reference
Error.cc File Reference
#include "squid.h"
#include "base/IoManip.h"
#include "debug/Stream.h"
#include "error/Error.h"
Functions
std::ostream & operator<< (std::ostream &os, const ErrorDetails &details)
std::ostream & operator<< (std::ostream &os, const Error &error)
Function Documentation
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const Error & error)
Definition at line 76 of file Error.cc.
References error(), errorTypeName(), and AsList< Container >::prefixedBy().
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const ErrorDetails & details)
prints all given details separated by '+'; if no details were given, prints nothing
Definition at line 69 of file Error.cc.
References AsList< Container >::delimitedBy().