Squid Web Cache: squid/src/ssl/ErrorDetailManager.cc File Reference
ErrorDetailManager.cc File Reference
#include "squid.h"
#include "base/Raw.h"
#include "ErrorDetail.h"
#include "ErrorDetailManager.h"
#include "errorpage.h"
#include "http/ContentLengthInterpreter.h"
#include "mime_header.h"
#include "sbuf/Stream.h"
#include "sbuf/StringConvert.h"
Classes
class Ssl::ErrorDetailFile
manages error detail templates
class DetailEntryParser
Namespaces
namespace Ssl
Functions
static SBuf SlowlyParseQuotedField (const char *const description, const HttpHeader &parser, const char *const fieldName)
ErrorDetailEntry constructor helper that extracts a quoted HTTP field value.
size_t detailEntryEnd (const char *s, size_t len)
Function Documentation
detailEntryEnd()
size_t detailEntryEnd (const char * s, size_t len) inline
Definition at line 171 of file ErrorDetailManager.cc.
References headersEnd().
Referenced by Ssl::ErrorDetailFile::parse().
SlowlyParseQuotedField()
static SBuf SlowlyParseQuotedField (const char *const description, const HttpHeader & parser, const char *const fieldName) static
Definition at line 31 of file ErrorDetailManager.cc.
References HttpHeader::hasNamed(), Here, String::size(), Http::SlowlyParseQuotedString(), String::termedBuf(), and ToSBuf().