Squid Web Cache: squid/src/ETag.h File Reference
ETag.h File Reference
Classes
class ETag
Functions
int etagParseInit (ETag *etag, const char *str)
bool etagIsStrongEqual (const ETag &tag1, const ETag &tag2)
whether etags are strong-equal
bool etagIsWeakEqual (const ETag &tag1, const ETag &tag2)
whether etags are weak-equal
Function Documentation
etagIsStrongEqual()
bool etagIsStrongEqual (const ETag & tag1, const ETag & tag2)
Definition at line 49 of file ETag.cc.
References etagStringsMatch(), and ETag::weak.
Referenced by clientIfRangeMatch(), and StoreEntry::hasOneOfEtags().
etagIsWeakEqual()
bool etagIsWeakEqual (const ETag & tag1, const ETag & tag2)
Definition at line 55 of file ETag.cc.
References etagStringsMatch().
Referenced by StoreEntry::hasOneOfEtags().
etagParseInit()
int etagParseInit (ETag * etag, const char * str)
Definition at line 29 of file ETag.cc.
References assert, ETag::str, and ETag::weak.
Referenced by HttpHeader::getETag(), HttpHeader::getTimeOrTag(), and StoreEntry::hasOneOfEtags().