Squid Web Cache: squid/src/event.cc File Reference
event.cc File Reference
#include "squid.h"
#include "base/Random.h"
#include "event.h"
#include "mgr/Registration.h"
#include "Store.h"
#include "tools.h"
#include <cmath>
Classes
class EventDialer
Functions
void eventAdd (const char *name, EVH *func, void *arg, double when, int weight, bool cbdata)
void eventAddIsh (const char *name, EVH *func, void *arg, double delta_ish, int weight)
void eventDelete (EVH *func, void *arg)
void eventInit (void)
static void eventDump (StoreEntry *sentry)
int eventFind (EVH *func, void *arg)
Variables
static OBJH eventDump
static const char * last_event_ran = nullptr
Function Documentation
eventAdd()
void eventAdd (const char * name, EVH * func, void * arg, double when, int weight, bool cbdata)
Definition at line 107 of file event.cc.
References EventScheduler::GetInstance(), and EventScheduler::schedule().
Referenced by authenticateDigestNonceCacheCleanup(), authenticateDigestNonceSetup(), Rock::Rebuild::checkpoint(), Mem::CleanIdlePools(), clientdbAdd(), clientdbGC(), commPlanHalfClosedCheck(), Log::TcpLogger::connectDone(), TunnelStateData::copyRead(), IpcIoFile::DiskerHandleRequests(), SignalEngine::doShutdown(), eventAddIsh(), SignalEngine::FinalShutdownRunners(), fqdncache_purgelru(), idnsTickleQueue(), Fs::Ufs::UFSSwapDir::init(), DelayPools::InitDelayData(), Ipc::Inquirer::inquire(), ipcache_purgelru(), ClientInfo::kickQuotaQueue(), logfile_mod_daemon_open(), logfileFlushEvent(), mainInitialize(), mainReconfigureStart(), Store::Maintain(), IpcIoFile::open(), peerClearRRLoop(), peerCountMcastPeersCreateAndSend(), peerCountMcastPeersSchedule(), peerDigestSetCheck(), Fs::Ufs::UFSSwapDir::rebuild(), Comm::ConnOpener::retrySleep(), Auth::CredentialsCache::scheduleCleanup(), IpcIoFile::scheduleTimeoutCheck(), Adaptation::Icap::ServiceRep::scheduleUpdate(), Ipc::Forwarder::start(), HappyOrderEnforcer::startedWaiting(), Ipc::UdsSender::startSleep(), PeerSelectorPingMonitor::startWaiting(), statAvgTick(), statInit(), statObjects(), statObjectsStart(), storeCleanup(), storeDigestRebuildFinish(), storeDigestRebuildResume(), storeDigestRebuildStep(), storeDigestRewriteFinish(), storeDigestRewriteResume(), storeDigestSwapOutStep(), storeInit(), storeLateRelease(), storeRebuildComplete(), DelayPools::Update(), IpcIoFile::WaitBeforePop(), wccp2HandleUdp(), wccp2HereIam(), wccp2Init(), wccpHereIam(), and wccpInit().
eventAddIsh()
void eventAddIsh (const char * name, EVH * func, void * arg, double delta_ish, int weight)
Definition at line 114 of file event.cc.
References eventAdd(), and RandomSeed32().
Referenced by netdbInit(), netdbSaveState(), peerDNSConfigure(), and peerScheduleDnsRefreshCheck().
eventDelete()
void eventDelete (EVH * func, void * arg)
Definition at line 127 of file event.cc.
References EventScheduler::cancel(), and EventScheduler::GetInstance().
Referenced by TunnelStateData::Connection::~Connection(), PeerDigest::~PeerDigest(), PeerSelectorPingMonitor::abortWaiting(), logfile_mod_daemon_close(), peerScheduleDnsRefreshCheck(), Ipc::Forwarder::removeTimeoutEvent(), Ipc::Inquirer::removeTimeoutEvent(), Adaptation::Icap::ServiceRep::scheduleUpdate(), wccp2ConnectionClose(), and wccp2HandleUdp().
eventDump()
static void eventDump (StoreEntry * sentry) static
Definition at line 139 of file event.cc.
References EventScheduler::dump(), and EventScheduler::GetInstance().
eventFind()
int eventFind (EVH * func, void * arg)
Definition at line 145 of file event.cc.
References EventScheduler::find(), and EventScheduler::GetInstance().
Referenced by PeerDigest::~PeerDigest(), peerScheduleDnsRefreshCheck(), Ipc::Forwarder::removeTimeoutEvent(), Ipc::Inquirer::removeTimeoutEvent(), Adaptation::Icap::ServiceRep::scheduleUpdate(), wccp2Init(), wccpHereIam(), and wccpInit().
eventInit()
void eventInit (void)
Definition at line 133 of file event.cc.
References eventDump, and Mgr::RegisterAction().
Referenced by mainInitialize().
Variable Documentation
eventDump
OBJH eventDump static
Definition at line 22 of file event.cc.
Referenced by eventInit().
last_event_ran
const char* last_event_ran = nullptr static
Definition at line 23 of file event.cc.
Referenced by EventScheduler::checkEvents(), and EventScheduler::dump().