Squid Web Cache: squid/src/acl/external/AD_group/ext_ad_group_acl.cc File Reference
ext_ad_group_acl.cc File Reference
#include "squid.h"
#include "helper/protocol_defines.h"
#include "include/util.h"
#include "rfc1738.h"
#include <cassert>
#include <cctype>
#include <cstring>
Enumerations
enum ADSI_PATH { LDAP_MODE , GC_MODE }
Functions
static wchar_t * My_NameTranslate (wchar_t *, int, int)
static char * Get_WIN32_ErrorMessage (HRESULT)
static void CloseCOM (void)
static HRESULT GetLPBYTEtoOctetString (VARIANT *pVar, LPBYTE *ppByte)
static wchar_t * Get_primaryGroup (IADs *pUser)
static wchar_t * GetLDAPPath (wchar_t *Base_DN, int query_mode)
static char * GetDomainName (void)
static int add_User_Group (wchar_t *Group)
static bool wStrIsInArray (const wchar_t *str, wchar_t **array)
static int wcstrcmparray (const wchar_t *str, const char **array)
static HRESULT Recursive_Memberof (IADs *pObj)
static wchar_t ** build_groups_DN_array (const char **array, char *userdomain)
static int Valid_Local_Groups (char *UserName, const char **Groups)
static int Valid_Global_Groups (char *UserName, const char **Groups)
static void usage (const char *program)
static void process_options (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
enum ADSI_PATH ADSI_Path
int use_global = 0
char * program_name
pid_t mypid
char * machinedomain
int use_case_insensitive_compare = 0
char * DefaultDomain = nullptr
const char NTV_VALID_DOMAIN_SEPARATOR [] = "\\/"
int numberofgroups = 0
int WIN32_COM_initialized = 0
char * WIN32_ErrorMessage = nullptr
wchar_t ** User_Groups
int User_Groups_Count = 0
Enumeration Type Documentation
ADSI_PATH
enum ADSI_PATH
Enumerator
LDAP_MODE
GC_MODE
Definition at line 114 of file ext_ad_group_acl.cc.
Function Documentation
add_User_Group()
static int add_User_Group (wchar_t * Group) static
Definition at line 371 of file ext_ad_group_acl.cc.
References User_Groups, User_Groups_Count, xmalloc, and xrealloc().
Referenced by Recursive_Memberof(), and Valid_Global_Groups().
build_groups_DN_array()
static wchar_t ** build_groups_DN_array (const char ** array, char * userdomain) static
Definition at line 514 of file ext_ad_group_acl.cc.
References debug(), My_NameTranslate(), numberofgroups, safe_free, xmalloc, and xstrncpy().
Referenced by Valid_Global_Groups().
CloseCOM()
static void CloseCOM (void) static
Definition at line 136 of file ext_ad_group_acl.cc.
References WIN32_COM_initialized.
Referenced by main().
Get_primaryGroup()
static wchar_t * Get_primaryGroup (IADs * pUser) static
Definition at line 173 of file ext_ad_group_acl.cc.
References debug(), Get_WIN32_ErrorMessage(), GetLPBYTEtoOctetString(), My_NameTranslate(), safe_free, and xmalloc.
Referenced by Valid_Global_Groups().
Get_WIN32_ErrorMessage()
static char * Get_WIN32_ErrorMessage (HRESULT hr) static
Definition at line 234 of file ext_ad_group_acl.cc.
References WIN32_ErrorMessage.
Referenced by Get_primaryGroup(), GetDomainName(), My_NameTranslate(), Recursive_Memberof(), Valid_Global_Groups(), and Valid_Local_Groups().
GetDomainName()
static char * GetDomainName (void) static
Definition at line 320 of file ext_ad_group_acl.cc.
References debug(), Get_WIN32_ErrorMessage(), safe_free, and xmalloc.
Referenced by main().
GetLDAPPath()
static wchar_t * GetLDAPPath (wchar_t * Base_DN, int query_mode) static
Definition at line 304 of file ext_ad_group_acl.cc.
References LDAP_MODE, and xmalloc.
Referenced by Recursive_Memberof(), and Valid_Global_Groups().
GetLPBYTEtoOctetString()
static HRESULT GetLPBYTEtoOctetString (VARIANT * pVar, LPBYTE * ppByte) static
Definition at line 143 of file ext_ad_group_acl.cc.
Referenced by Get_primaryGroup().
main()
int main (int argc, char * argv[])
Definition at line 806 of file ext_ad_group_acl.cc.
References assert, CloseCOM(), debug(), DefaultDomain, GetDomainName(), HELPER_INPUT_BUFFER, HLP_MSG, machinedomain, mypid, numberofgroups, process_options(), program_name, rfc1738_unescape(), SEND_BH, SEND_ERR, SEND_OK, SQUID_BUILD_INFO, use_case_insensitive_compare, use_global, Valid_Global_Groups(), Valid_Local_Groups(), VERSION, and xstrdup.
My_NameTranslate()
static wchar_t * My_NameTranslate (wchar_t * name, int in_format, int out_format) static
Definition at line 248 of file ext_ad_group_acl.cc.
References debug(), Get_WIN32_ErrorMessage(), WIN32_COM_initialized, and xmalloc.
Referenced by build_groups_DN_array(), Get_primaryGroup(), and Valid_Global_Groups().
process_options()
static void process_options (int argc, char * argv[]) static
Definition at line 770 of file ext_ad_group_acl.cc.
References debug_enabled, DefaultDomain, getopt(), optarg, opterr, optopt, program_name, usage(), use_case_insensitive_compare, use_global, and xstrndup().
Referenced by main().
Recursive_Memberof()
static HRESULT Recursive_Memberof (IADs * pObj) static
Definition at line 429 of file ext_ad_group_acl.cc.
References add_User_Group(), debug(), GC_MODE, Get_WIN32_ErrorMessage(), GetLDAPPath(), LDAP_MODE, Recursive_Memberof(), and safe_free.
Referenced by Recursive_Memberof(), and Valid_Global_Groups().
usage()
static void usage (const char * program) static
Definition at line 758 of file ext_ad_group_acl.cc.
Valid_Global_Groups()
static int Valid_Global_Groups (char * UserName, const char ** Groups) static
Definition at line 634 of file ext_ad_group_acl.cc.
References add_User_Group(), build_groups_DN_array(), debug(), DefaultDomain, GC_MODE, Get_primaryGroup(), Get_WIN32_ErrorMessage(), GetLDAPPath(), LDAP_MODE, My_NameTranslate(), NTV_VALID_DOMAIN_SEPARATOR, Recursive_Memberof(), safe_free, User_Groups, User_Groups_Count, wStrIsInArray(), and xstrncpy().
Referenced by main().
Valid_Local_Groups()
static int Valid_Local_Groups (char * UserName, const char ** Groups) static
Definition at line 557 of file ext_ad_group_acl.cc.
References debug(), Get_WIN32_ErrorMessage(), and wcstrcmparray().
Referenced by main().
wcstrcmparray()
static int wcstrcmparray (const wchar_t * str, const char ** array) static
Definition at line 413 of file ext_ad_group_acl.cc.
References debug(), and use_case_insensitive_compare.
Referenced by Valid_Local_Groups().
wStrIsInArray()
static bool wStrIsInArray (const wchar_t * str, wchar_t ** array) static
Definition at line 398 of file ext_ad_group_acl.cc.
References debug().
Referenced by Valid_Global_Groups().
Variable Documentation
ADSI_Path
enum ADSI_PATH ADSI_Path
DefaultDomain
char* DefaultDomain = nullptr
Definition at line 124 of file ext_ad_group_acl.cc.
Referenced by main(), process_options(), and Valid_Global_Groups().
machinedomain
char* machinedomain
Definition at line 122 of file ext_ad_group_acl.cc.
Referenced by main().
mypid
pid_t mypid
Definition at line 121 of file ext_ad_group_acl.cc.
Referenced by main().
NTV_VALID_DOMAIN_SEPARATOR
const char NTV_VALID_DOMAIN_SEPARATOR[] = "\\/"
Definition at line 125 of file ext_ad_group_acl.cc.
Referenced by Valid_Global_Groups().
numberofgroups
int numberofgroups = 0
Definition at line 126 of file ext_ad_group_acl.cc.
Referenced by build_groups_DN_array(), and main().
program_name
char* program_name
Definition at line 120 of file ext_ad_group_acl.cc.
Referenced by main(), process_options(), usage(), and usage().
use_case_insensitive_compare
int use_case_insensitive_compare = 0
Definition at line 123 of file ext_ad_group_acl.cc.
Referenced by main(), process_options(), and wcstrcmparray().
use_global
int use_global = 0
Definition at line 119 of file ext_ad_group_acl.cc.
Referenced by main(), and process_options().
User_Groups
wchar_t** User_Groups
Definition at line 129 of file ext_ad_group_acl.cc.
Referenced by add_User_Group(), and Valid_Global_Groups().
User_Groups_Count
int User_Groups_Count = 0
Definition at line 130 of file ext_ad_group_acl.cc.
Referenced by add_User_Group(), and Valid_Global_Groups().
WIN32_COM_initialized
int WIN32_COM_initialized = 0
Definition at line 127 of file ext_ad_group_acl.cc.
Referenced by CloseCOM(), and My_NameTranslate().
WIN32_ErrorMessage
char* WIN32_ErrorMessage = nullptr
Definition at line 128 of file ext_ad_group_acl.cc.
Referenced by Get_WIN32_ErrorMessage().