Squid Web Cache: squid/src/ExternalACL.h File Reference
ExternalACL.h File Reference
#include "acl/Acl.h"
#include "acl/Checklist.h"
#include "base/RefCount.h"
Classes
class ACLExternal
Typedefs
typedef void EAH(void *data, const ExternalACLEntryPointer &result)
Functions
void parse_externalAclHelper (external_acl **)
void dump_externalAclHelper (StoreEntry *sentry, const char *name, const external_acl *)
void free_externalAclHelper (external_acl **)
void externalAclLookup (ACLChecklist *ch, void *acl_data, EAH *handler, void *data)
void externalAclInit (void)
void externalAclShutdown (void)
Typedef Documentation
EAH
typedef void EAH(void *data, const ExternalACLEntryPointer &result)
Definition at line 56 of file ExternalACL.h.
Function Documentation
dump_externalAclHelper()
void dump_externalAclHelper (StoreEntry * sentry, const char * name, const external_acl * list)
Definition at line 369 of file external_acl.cc.
References DEFAULT_EXTERNAL_ACL_CHILDREN, DEFAULT_EXTERNAL_ACL_TTL, wordlist::key, Format::LOG_QUOTE_SHELL, node::next, wordlist::next, and storeAppendPrintf().
externalAclInit()
void externalAclInit (void)
Definition at line 1104 of file external_acl.cc.
References Config, SquidConfig::externalAclHelperList, externalAclRegisterWithCacheManager(), hash4, hash_create(), hashPrime(), IPC_TCP_SOCKET, and Helper::Client::Make().
Referenced by mainInitialize(), mainReconfigureFinish(), and mainRotate().
externalAclLookup()
void externalAclLookup (ACLChecklist * ch, void * acl_data, EAH * handler, void * data)
externalAclShutdown()
void externalAclShutdown (void)
Definition at line 1128 of file external_acl.cc.
References Config, SquidConfig::externalAclHelperList, helperShutdown(), external_acl::next, and external_acl::theHelper.
Referenced by mainReconfigureStart(), mainRotate(), and SquidShutdown().
free_externalAclHelper()
void free_externalAclHelper (external_acl ** list)
Definition at line 419 of file external_acl.cc.
parse_externalAclHelper()
void parse_externalAclHelper (external_acl ** list)
Definition at line 174 of file external_acl.cc.
References SBuf::append(), assert, SBuf::c_str(), external_acl::cache_size, external_acl::children, external_acl::cmdline, Helper::ChildConfig::concurrency, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, Helper::ChildConfig::defaultQueueSize, ConfigParser::DisableMacros(), ConfigParser::EnableMacros(), external_acl::format, Format::Format::format, external_acl::grace, SBuf::length(), Format::LFT_ADAPTED_REQUEST_HEADER, Format::LFT_ADAPTED_REQUEST_HEADER_ELEM, Format::LFT_EXT_ACL_DATA, Format::LFT_EXT_ACL_USER_CA_CERT, Format::LFT_EXT_ACL_USER_CERT, Format::LFT_REPLY_HEADER, Format::LFT_REPLY_HEADER_ELEM, Format::LFT_USER_LOGIN, external_acl::local_addr, Format::LOG_QUOTE_NONE, Format::LOG_QUOTE_SHELL, Format::LOG_QUOTE_URL, Helper::ChildConfig::n_idle, Helper::ChildConfig::n_max, Helper::ChildConfig::n_startup, external_acl::name, external_acl::negative_ttl, external_acl::next, ConfigParser::NextToken(), parse_wordlist(), Helper::ChildConfig::queue_size, external_acl::quote, external_acl::require_auth, self_destruct(), Ip::Address::setIPv4(), Format::Token::space, external_acl::ttl, Format::Token::type, wordlistAdd(), and xstrdup.