Squid Web Cache: squid/src/external_acl.cc File Reference
external_acl.cc File Reference
#include "squid.h"
#include "acl/Acl.h"
#include "acl/FilledChecklist.h"
#include "cache_cf.h"
#include "client_side.h"
#include "client_side_request.h"
#include "comm/Connection.h"
#include "ConfigParser.h"
#include "ExternalACL.h"
#include "ExternalACLEntry.h"
#include "fde.h"
#include "format/Token.h"
#include "helper.h"
#include "helper/Reply.h"
#include "http/Stream.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "ip/tools.h"
#include "MemBuf.h"
#include "mgr/Registration.h"
#include "rfc1738.h"
#include "SquidConfig.h"
#include "SquidString.h"
#include "Store.h"
#include "tools.h"
#include "wordlist.h"
#include "ssl/ServerBump.h"
#include "ssl/support.h"
#include "auth/Acl.h"
#include "auth/Gadgets.h"
#include "auth/UserRequest.h"
Classes
class external_acl
class external_acl_data
class externalAclState
Macros
#define DEFAULT_EXTERNAL_ACL_TTL 1 * 60 * 60
#define DEFAULT_EXTERNAL_ACL_CHILDREN 5
Functions
static void external_acl_cache_delete (external_acl *def, const ExternalACLEntryPointer &entry)
static int external_acl_entry_expired (external_acl *def, const ExternalACLEntryPointer &entry)
static int external_acl_grace_expired (external_acl *def, const ExternalACLEntryPointer &entry)
static void external_acl_cache_touch (external_acl *def, const ExternalACLEntryPointer &entry)
static ExternalACLEntryPointer external_acl_cache_add (external_acl *def, const char *key, ExternalACLEntryData const &data)
void parse_externalAclHelper (external_acl **list)
void dump_externalAclHelper (StoreEntry *sentry, const char *name, const external_acl *list)
void free_externalAclHelper (external_acl **list)
static external_acl * find_externalAclHelper (const char *name)
static void copyResultsFromEntry (const HttpRequest::Pointer &req, const ExternalACLEntryPointer &entry)
static void externalAclHandleReply (void *data, const Helper::Reply &reply)
static void externalAclStats (StoreEntry *sentry)
static void externalAclRegisterWithCacheManager (void)
void externalAclInit (void)
void externalAclShutdown (void)
Macro Definition Documentation
DEFAULT_EXTERNAL_ACL_CHILDREN
#define DEFAULT_EXTERNAL_ACL_CHILDREN 5
Definition at line 51 of file external_acl.cc.
DEFAULT_EXTERNAL_ACL_TTL
#define DEFAULT_EXTERNAL_ACL_TTL 1 * 60 * 60
Definition at line 48 of file external_acl.cc.
Function Documentation
copyResultsFromEntry()
static void copyResultsFromEntry (const HttpRequest::Pointer & req, const ExternalACLEntryPointer & entry) static
Definition at line 566 of file external_acl.cc.
References HttpRequest::clientConnectionManager, HttpRequest::extacl_log, HttpRequest::extacl_message, HttpRequest::extacl_passwd, HttpRequest::extacl_user, CbcPointer< Cbc >::get(), ExternalACLEntry::log, ExternalACLEntry::message, ExternalACLEntry::notes, ExternalACLEntry::password, String::size(), ExternalACLEntry::tag, HttpRequest::tag, UpdateRequestNotes(), and ExternalACLEntry::user.
Referenced by ACLExternal::aclMatchExternal().
dump_externalAclHelper()
void dump_externalAclHelper (StoreEntry * sentry, const char * name, const external_acl * list)
Definition at line 369 of file external_acl.cc.
References DEFAULT_EXTERNAL_ACL_CHILDREN, DEFAULT_EXTERNAL_ACL_TTL, wordlist::key, Format::LOG_QUOTE_SHELL, node::next, wordlist::next, and storeAppendPrintf().
external_acl_cache_add()
static ExternalACLEntryPointer external_acl_cache_add (external_acl * def, const char * key, ExternalACLEntryData const & data) static
Definition at line 835 of file external_acl.cc.
References ACCESS_DUNNO, external_acl::add(), external_acl::cache, debugs, ExternalACLEntry::def, external_acl_cache_delete(), external_acl_cache_touch(), hash_lookup(), hash_link::key, external_acl::maybeCacheable(), MYNAME, ExternalACLEntryData::result, ExternalACLEntry::update(), and xstrdup.
Referenced by externalAclHandleReply().
external_acl_cache_delete()
static void external_acl_cache_delete (external_acl * def, const ExternalACLEntryPointer & entry) static
Definition at line 873 of file external_acl.cc.
References assert, external_acl::cache, external_acl::cache_entries, external_acl::cache_size, ExternalACLEntry::def, dlinkDelete(), RefCount< C >::getRaw(), hash_remove_link(), ExternalACLEntry::lru, and external_acl::lru_list.
Referenced by external_acl::~external_acl(), external_acl_cache_add(), and external_acl::trimCache().
external_acl_cache_touch()
static void external_acl_cache_touch (external_acl * def, const ExternalACLEntryPointer & entry) static
Definition at line 752 of file external_acl.cc.
References dlinkAdd(), dlinkDelete(), RefCount< C >::getRaw(), ExternalACLEntry::lru, external_acl::lru_list, external_acl::maybeCacheable(), and ExternalACLEntry::result.
Referenced by ACLExternal::aclMatchExternal(), and external_acl_cache_add().
external_acl_entry_expired()
static int external_acl_entry_expired (external_acl * def, const ExternalACLEntryPointer & entry) static
Definition at line 807 of file external_acl.cc.
References ACCESS_DUNNO, Acl::Answer::allowed(), external_acl::cache_size, ExternalACLEntry::date, external_acl::negative_ttl, ExternalACLEntry::result, squid_curtime, and external_acl::ttl.
Referenced by ACLExternal::aclMatchExternal().
external_acl_grace_expired()
static int external_acl_grace_expired (external_acl * def, const ExternalACLEntryPointer & entry) static
Definition at line 819 of file external_acl.cc.
References ACCESS_DUNNO, Acl::Answer::allowed(), external_acl::cache_size, ExternalACLEntry::date, external_acl::grace, external_acl::negative_ttl, ExternalACLEntry::result, squid_curtime, and external_acl::ttl.
Referenced by ACLExternal::aclMatchExternal().
externalAclHandleReply()
static void externalAclHandleReply (void * data, const Helper::Reply & reply) static
Definition at line 942 of file external_acl.cc.
References ACCESS_ALLOWED, ACCESS_DENIED, ACCESS_DUNNO, NotePairs::append(), externalAclState::callback, externalAclState::callback_data, cbdataReferenceValid(), cbdataReferenceValidDone, debugs, externalAclState::def, dlinkDelete(), Helper::Error, external_acl_cache_add(), NotePairs::findFirst(), externalAclState::key, externalAclState::list, ExternalACLEntryData::log, ExternalACLEntryData::message, ExternalACLEntryData::notes, Helper::Reply::notes, Helper::Okay, ExternalACLEntryData::password, external_acl::queue, externalAclState::queue, ExternalACLEntryData::result, Helper::Reply::result, ExternalACLEntryData::tag, and ExternalACLEntryData::user.
Referenced by ACLExternal::startLookup().
externalAclInit()
void externalAclInit (void)
Definition at line 1104 of file external_acl.cc.
References Config, SquidConfig::externalAclHelperList, externalAclRegisterWithCacheManager(), hash4, hash_create(), hashPrime(), IPC_TCP_SOCKET, and Helper::Client::Make().
Referenced by mainInitialize(), mainReconfigureFinish(), and mainRotate().
externalAclRegisterWithCacheManager()
static void externalAclRegisterWithCacheManager (void) static
Definition at line 1096 of file external_acl.cc.
References externalAclStats(), and Mgr::RegisterAction().
Referenced by externalAclInit().
externalAclShutdown()
void externalAclShutdown (void)
Definition at line 1128 of file external_acl.cc.
References Config, SquidConfig::externalAclHelperList, helperShutdown(), external_acl::next, and external_acl::theHelper.
Referenced by mainReconfigureStart(), mainRotate(), and SquidShutdown().
externalAclStats()
static void externalAclStats (StoreEntry * sentry) static
Definition at line 1084 of file external_acl.cc.
References assert, Config, SquidConfig::externalAclHelperList, and storeAppendPrintf().
Referenced by externalAclRegisterWithCacheManager().
find_externalAclHelper()
static external_acl * find_externalAclHelper (const char * name) static
Definition at line 426 of file external_acl.cc.
References Config, SquidConfig::externalAclHelperList, and node::next.
Referenced by ACLExternal::parse().
free_externalAclHelper()
void free_externalAclHelper (external_acl ** list)
Definition at line 419 of file external_acl.cc.
parse_externalAclHelper()
void parse_externalAclHelper (external_acl ** list)
Definition at line 174 of file external_acl.cc.
References SBuf::append(), assert, SBuf::c_str(), external_acl::cache_size, external_acl::children, external_acl::cmdline, Helper::ChildConfig::concurrency, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, Helper::ChildConfig::defaultQueueSize, ConfigParser::DisableMacros(), ConfigParser::EnableMacros(), external_acl::format, Format::Format::format, external_acl::grace, SBuf::length(), Format::LFT_ADAPTED_REQUEST_HEADER, Format::LFT_ADAPTED_REQUEST_HEADER_ELEM, Format::LFT_EXT_ACL_DATA, Format::LFT_EXT_ACL_USER_CA_CERT, Format::LFT_EXT_ACL_USER_CERT, Format::LFT_REPLY_HEADER, Format::LFT_REPLY_HEADER_ELEM, Format::LFT_USER_LOGIN, external_acl::local_addr, Format::LOG_QUOTE_NONE, Format::LOG_QUOTE_SHELL, Format::LOG_QUOTE_URL, Helper::ChildConfig::n_idle, Helper::ChildConfig::n_max, Helper::ChildConfig::n_startup, external_acl::name, external_acl::negative_ttl, external_acl::next, ConfigParser::NextToken(), parse_wordlist(), Helper::ChildConfig::queue_size, external_acl::quote, external_acl::require_auth, self_destruct(), Ip::Address::setIPv4(), Format::Token::space, external_acl::ttl, Format::Token::type, wordlistAdd(), and xstrdup.