Squid Web Cache: squid/src/fd.cc File Reference
fd.cc File Reference
#include "squid.h"
#include "comm/Loops.h"
#include "compat/socket.h"
#include "compat/unistd.h"
#include "debug/Messages.h"
#include "debug/Stream.h"
#include "fatal.h"
#include "fd.h"
#include "fde.h"
#include "globals.h"
Functions
int default_read_method (int, char *, int)
int default_write_method (int, const char *, int)
int msghdr_read_method (int, char *, int)
int msghdr_write_method (int, const char *, int)
static void fdUpdateBiggest (int fd, int)
void fd_close (int fd)
void fd_open (int fd, unsigned int type, const char *desc)
void fd_note (int fd, const char *s)
void fd_bytes (const int fd, const int len, const IoDirection direction)
void fdDumpOpen (void)
int fdNFree (void)
int fdUsageHigh (void)
void fdAdjustReserved (void)
Variables
const char * fdTypeStr []
Function Documentation
default_read_method()
int default_read_method (int fd, char * buf, int len)
Definition at line 124 of file fd.cc.
References xread().
Referenced by fd_open(), Ssl::Bio::read(), and fde::useDefaultIo().
default_write_method()
int default_write_method (int fd, const char * buf, int len)
Definition at line 130 of file fd.cc.
References xwrite().
Referenced by fd_open(), fde::useDefaultIo(), and Ssl::Bio::write().
fd_bytes()
void fd_bytes (const int fd, const int len, const IoDirection direction)
Definition at line 221 of file fd.cc.
References fde::bytes_read, fde::bytes_written, fd_table, Read, and Write.
Referenced by diskerRead(), diskerWriteAttempts(), diskHandleRead(), diskHandleWrite(), idnsRead(), idnsSendQuery(), logfile_mod_udp_write(), logfileWriteWrapper(), Ftp::Client::readControlReply(), Comm::ReadNow(), Client::sentRequestBody(), Ftp::Client::writeCommandCallback(), and HttpStateData::wroteLast().
fd_close()
void fd_close (int fd)
Definition at line 76 of file fd.cc.
References assert, fde::clear(), debugs, fde::desc, FD_FILE, fd_table, fdUpdateBiggest(), fde::flags, Number_FD, fde::_fde_flags::open, fde::read_handler, Comm::ResetSelect(), fde::type, and fde::write_handler.
Referenced by fd_open().
fd_note()
void fd_note (int fd, const char * s)
Definition at line 211 of file fd.cc.
References fde::desc, FD_DESC_SZ, fd_table, and xstrncpy().
Referenced by Ftp::Server::AcceptCtrlConnection(), Ftp::Server::acceptDataConnection(), ConnStateData::afterClientRead(), ClientRequestContext::clientRedirectDone(), Ftp::Server::connectedForData(), CreateSession(), FwdState::dispatch(), Server::doClientRead(), fd_open(), httpAccept(), httpsAccept(), icpIncomingConnectionOpened(), icpOpenPorts(), DiskdIOStrategy::init(), ipc_thread_1(), IcmpSquid::Open(), Helper::Client::openSessions(), statefulhelper::openSessions(), ConnStateData::parseTlsHandshake(), ConnStateData::pinConnection(), PconnPool::push(), ConnStateData::readNextRequest(), unlinkdInit(), and Http::Tunneler::writeRequest().
fd_open()
void fd_open (int fd, unsigned int type, const char * desc)
Definition at line 151 of file fd.cc.
References assert, DBG_IMPORTANT, debugs, default_read_method(), default_write_method(), fde::epoll_state, fatalf(), fd_close(), FD_FILE, FD_LOG, FD_MSGHDR, fd_note(), FD_PIPE, FD_SOCKET, fd_table, fdUpdateBiggest(), fde::flags, msghdr_read_method(), msghdr_write_method(), Number_FD, fde::_fde_flags::open, fde::setIo(), and fde::type.
fdAdjustReserved()
void fdAdjustReserved (void)
Definition at line 283 of file fd.cc.
References DBG_CRITICAL, debugs, fatalf(), last, min(), Number_FD, RESERVED_FD, squid_curtime, and Squid_MaxFD.
Referenced by comm_open_uds(), and comm_openex().
fdDumpOpen()
void fdDumpOpen (void)
Definition at line 239 of file fd.cc.
References fde::bytes_read, fde::bytes_written, debugs, DebugStream(), fde::desc, fd_table, fde::flags, Important, fde::_fde_flags::open, and Squid_MaxFD.
Referenced by SquidShutdown().
fdNFree()
int fdNFree (void)
Definition at line 262 of file fd.cc.
References Number_FD, Opening_FD, and Squid_MaxFD.
Referenced by StoreEntry::checkCachable(), fdUsageHigh(), GetInfo(), and Comm::TcpAcceptor::okToAccept().
fdUpdateBiggest()
static void fdUpdateBiggest (int fd, int opening) static
Definition at line 47 of file fd.cc.
References assert, Biggest_FD, fd_table, and Squid_MaxFD.
Referenced by fd_close(), and fd_open().
fdUsageHigh()
int fdUsageHigh (void)
Definition at line 268 of file fd.cc.
References fdNFree(), Number_FD, and RESERVED_FD.
Referenced by clientReplyContext::buildReplyHeader(), PeerPoolMgr::openNewConnection(), and PconnPool::push().
msghdr_read_method()
int msghdr_read_method (int fd, char * buf, int)
Definition at line 136 of file fd.cc.
Referenced by fd_open().
msghdr_write_method()
int msghdr_write_method (int fd, const char * buf, int len)
Definition at line 142 of file fd.cc.
References MSG_NOSIGNAL.
Referenced by fd_open().
Variable Documentation
fdTypeStr
const char* fdTypeStr[]
Initial value:
= {
    "None",
    "Log",
    "File",
    "Socket",
    "Pipe",
    "MsgHdr",
    "Unknown"
}
Definition at line 34 of file fd.cc.
Referenced by fde::dumpStats(), and examine_select().