Squid Web Cache: squid/src/fd.h File Reference
fd.h File Reference
Enumerations
enum class IoDirection { Read , Write }
distinguishes reading/importing I/O operations from their writing/exporting counterparts
Functions
void fd_close (int fd)
void fd_open (int fd, unsigned int type, const char *)
void fd_note (int fd, const char *)
void fd_bytes (int fd, int len, IoDirection)
void fdDumpOpen (void)
int fdUsageHigh (void)
void fdAdjustReserved (void)
int default_read_method (int, char *, int)
int default_write_method (int, const char *, int)
Enumeration Type Documentation
IoDirection
enum class IoDirection strong
Enumerator
Read
Write
Definition at line 15 of file fd.h.
Function Documentation
default_read_method()
int default_read_method (int fd, char * buf, int len)
Definition at line 124 of file fd.cc.
References xread().
Referenced by fd_open(), Ssl::Bio::read(), and fde::useDefaultIo().
default_write_method()
int default_write_method (int fd, const char * buf, int len)
Definition at line 130 of file fd.cc.
References xwrite().
Referenced by fd_open(), fde::useDefaultIo(), and Ssl::Bio::write().
fd_bytes()
void fd_bytes (int fd, int len, IoDirection direction)
Definition at line 221 of file fd.cc.
References fde::bytes_read, fde::bytes_written, fd_table, Read, and Write.
Referenced by diskerRead(), diskerWriteAttempts(), diskHandleRead(), diskHandleWrite(), idnsRead(), idnsSendQuery(), logfile_mod_udp_write(), logfileWriteWrapper(), Ftp::Client::readControlReply(), Comm::ReadNow(), Client::sentRequestBody(), Ftp::Client::writeCommandCallback(), and HttpStateData::wroteLast().
fd_close()
void fd_close (int fd)
Definition at line 21 of file minimal.cc.
References assert, fde::clear(), debugs, fde::desc, FD_FILE, fd_table, fdUpdateBiggest(), fde::flags, Number_FD, fde::_fde_flags::open, fde::read_handler, Comm::ResetSelect(), fde::type, and fde::write_handler.
Referenced by comm_close_complete(), DiskThreadsDiskFile::doClose(), fd_open(), file_close(), CommIO::NotifyIOClose(), and DebugFile::reset().
fd_note()
void fd_note (int fd, const char * s)
Definition at line 211 of file fd.cc.
References fde::desc, FD_DESC_SZ, fd_table, and xstrncpy().
Referenced by Ftp::Server::AcceptCtrlConnection(), Ftp::Server::acceptDataConnection(), ConnStateData::afterClientRead(), ClientRequestContext::clientRedirectDone(), Ftp::Server::connectedForData(), CreateSession(), FwdState::dispatch(), Server::doClientRead(), fd_open(), httpAccept(), httpsAccept(), icpIncomingConnectionOpened(), icpOpenPorts(), DiskdIOStrategy::init(), ipc_thread_1(), IcmpSquid::Open(), Helper::Client::openSessions(), statefulhelper::openSessions(), ConnStateData::parseTlsHandshake(), ConnStateData::pinConnection(), PconnPool::push(), ConnStateData::readNextRequest(), unlinkdInit(), and Http::Tunneler::writeRequest().
fd_open()
void fd_open (int fd, unsigned int type, const char * description)
Definition at line 15 of file minimal.cc.
References assert, DBG_IMPORTANT, debugs, default_read_method(), default_write_method(), fde::epoll_state, fatalf(), fd_close(), FD_FILE, FD_LOG, FD_MSGHDR, fd_note(), FD_PIPE, FD_SOCKET, fd_table, fdUpdateBiggest(), fde::flags, msghdr_read_method(), msghdr_write_method(), Number_FD, fde::_fde_flags::open, fde::setIo(), and fde::type.
Referenced by Comm::TcpAcceptor::acceptInto(), comm_init_opened(), comm_open_uds(), ConfigureDebugging(), file_open(), CommIO::Initialize(), ipc_thread_1(), ipcCreate(), DiskThreadsDiskFile::openDone(), DebugFile::reset(), and Comm::SelectLoopInit().
fdAdjustReserved()
void fdAdjustReserved (void)
Definition at line 283 of file fd.cc.
References DBG_CRITICAL, debugs, fatalf(), last, min(), Number_FD, RESERVED_FD, squid_curtime, and Squid_MaxFD.
Referenced by comm_open_uds(), and comm_openex().
fdDumpOpen()
void fdDumpOpen (void)
Definition at line 239 of file fd.cc.
References fde::bytes_read, fde::bytes_written, debugs, DebugStream(), fde::desc, fd_table, fde::flags, Important, fde::_fde_flags::open, and Squid_MaxFD.
Referenced by SquidShutdown().
fdUsageHigh()
int fdUsageHigh (void)
Definition at line 268 of file fd.cc.
References fdNFree(), Number_FD, and RESERVED_FD.
Referenced by clientReplyContext::buildReplyHeader(), PeerPoolMgr::openNewConnection(), and PconnPool::push().