Squid Web Cache: squid/src/fde.h File Reference
fde.h File Reference
#include "base/CodeContext.h"
#include "base/forward.h"
#include "comm.h"
#include "defines.h"
#include "ip/Address.h"
#include "ip/forward.h"
#include "security/forward.h"
#include "typedefs.h"
#include "MessageBucket.h"
Classes
class _fde_disk
class fde
struct fde::_fde_flags
Macros
#define fd_table fde::Table
Typedefs
typedef int READ_HANDLER(int, char *, int)
typedef int WRITE_HANDLER(int, const char *, int)
Functions
int FD_READ_METHOD (int fd, char *buf, int len)
int FD_WRITE_METHOD (int fd, const char *buf, int len)
Macro Definition Documentation
fd_table
#define fd_table fde::Table
Definition at line 189 of file fde.h.
Typedef Documentation
READ_HANDLER
typedef int READ_HANDLER(int, char *, int)
READ_HANDLER functions return < 0 if, and only if, they fail with an error. On error, they must pass back an error code in 'errno'.
Definition at line 31 of file fde.h.
WRITE_HANDLER
typedef int WRITE_HANDLER(int, const char *, int)
WRITE_HANDLER functions return < 0 if, and only if, they fail with an error. On error, they must pass back an error code in 'errno'.
Definition at line 37 of file fde.h.
Function Documentation
FD_READ_METHOD()
int FD_READ_METHOD (int fd, char * buf, int len) inline
Definition at line 192 of file fde.h.
References fd_table.
Referenced by comm_empty_os_read_buffers(), diskHandleRead(), CommIO::FlushPipe(), MimeIcon::load(), TemplateFile::loadFromFile(), netdbReloadState(), Comm::ReadNow(), and storeRebuildLoadEntry().
FD_WRITE_METHOD()
int FD_WRITE_METHOD (int fd, const char * buf, int len) inline
Definition at line 198 of file fde.h.
References fd_table.
Referenced by diskHandleWrite(), logfileHandleWrite(), logfileWriteWrapper(), CommIO::NotifyIOCompleted(), UFSCleanLog::write(), and Fs::Ufs::UFSSwapDir::writeCleanDone().