Squid Web Cache: squid/src/acl/FilledChecklist.h File Reference
FilledChecklist.h File Reference
#include "AccessLogEntry.h"
#include "acl/Acl.h"
#include "acl/Checklist.h"
#include "acl/forward.h"
#include "base/CbcPointer.h"
#include "error/forward.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "ip/Address.h"
#include "auth/UserRequest.h"
#include "security/CertError.h"
Classes
class ACLFilledChecklist
Functions
ACLFilledChecklist * Filled (ACLChecklist *checklist)
convenience and safety wrapper for dynamic_cast<ACLFilledChecklist*>
Function Documentation
Filled()
ACLFilledChecklist * Filled (ACLChecklist * checklist) inline
Definition at line 146 of file FilledChecklist.h.
Referenced by AuthenticateAcl(), ACLChecklist::goAsync(), LookupDone(), LookupDone(), ACLDestinationIP::LookupDone(), ACLProxyAuth::LookupDone(), ACLExternal::LookupDone(), Acl::AdaptationServiceCheck::match(), Acl::AnnotateClientCheck::match(), Acl::AnnotateTransactionCheck::match(), Acl::AtStepCheck::match(), Acl::ClientCertificateCheck::match(), Acl::DestinationDomainCheck::match(), Acl::HierCodeCheck::match(), Acl::HttpRepHeaderCheck::match(), Acl::HttpReqHeaderCheck::match(), Acl::LocalPortCheck::match(), Acl::MethodCheck::match(), Acl::MyPortNameCheck::match(), Acl::NoteCheck::match(), Acl::PeerNameCheck::match(), Acl::ProtocolCheck::match(), Acl::ReplyHeaderCheck< header >::match(), Acl::RequestHeaderCheck< header >::match(), Acl::ServerCertificateCheck::match(), Acl::ServerNameCheck::match(), Acl::SourceDomainCheck::match(), Acl::SquidErrorCheck::match(), Acl::CertificateErrorCheck::match(), Acl::TagCheck::match(), Acl::UrlCheck::match(), Acl::UrlLoginCheck::match(), Acl::UrlPathCheck::match(), Acl::UrlPortCheck::match(), Acl::SnmpCommunityCheck::match(), ACLARP::match(), Acl::ConnectionsEncrypted::match(), Acl::ConnMark::match(), ACLDestinationIP::match(), ACLEui64::match(), ACLExtUser::match(), ACLHTTPStatus::match(), ACLLocalIP::match(), ACLMaxConnection::match(), ACLSourceIP::match(), Acl::TransactionInitiator::match(), ACLExternal::match(), ACLMaxUserIP::match(), Acl::ReplyHeaderCheck< header >::match(), Acl::RequestHeaderCheck< header >::match(), ACLProxyAuth::matchForCache(), ACLProxyAuth::matchProxyAuth(), and ssl_verify_cb().