Squid Web Cache: squid/src/format/Format.cc File Reference
Format.cc File Reference
#include "squid.h"
#include "AccessLogEntry.h"
#include "base64.h"
#include "client_side.h"
#include "comm/Connection.h"
#include "error/Detail.h"
#include "errorpage.h"
#include "fde.h"
#include "format/Format.h"
#include "format/Quoting.h"
#include "format/Token.h"
#include "http/Stream.h"
#include "HttpRequest.h"
#include "MemBuf.h"
#include "proxyp/Header.h"
#include "rfc1738.h"
#include "sbuf/Stream.h"
#include "sbuf/StringConvert.h"
#include "security/CertError.h"
#include "security/Certificate.h"
#include "security/NegotiationHistory.h"
#include "Store.h"
#include "tools.h"
#include "ssl/ErrorDetail.h"
#include "ssl/ServerBump.h"
Macros
#define strOrNull(s) ((s)==NULL||(s)[0]=='\0'?NULL:(s))
Convert a string to NULL pointer if it is "".
Functions
static void log_quoted_string (const char *str, char *out)
static const Http::Message * actualReplyHeader (const AccessLogEntry::Pointer &al)
static const Http::Message * actualRequestHeader (const AccessLogEntry::Pointer &al)
Macro Definition Documentation
strOrNull
#define strOrNull (s) ((s)==NULL||(s)[0]=='\0'?NULL:(s))
Definition at line 38 of file Format.cc.
Function Documentation
actualReplyHeader()
static const Http::Message * actualReplyHeader (const AccessLogEntry::Pointer & al) static
XXX: Misnamed. TODO: Split <h (and this function) to distinguish received headers from sent headers rather than failing to distinguish requests from responses.
Return values
HttpReply sent to the HTTP client (access.log and default context).
HttpReply received (encapsulated) from the ICAP server (icap.log context).
HttpRequest received (encapsulated) from the ICAP server (icap.log context).
Definition at line 350 of file Format.cc.
References AccessLogEntry::adapted_request, RefCount< C >::getRaw(), AccessLogEntry::icap, Adaptation::methodReqmod, AccessLogEntry::reply, and AccessLogEntry::IcapLogEntry::reqMethod.
Referenced by Format::Format::assemble().
actualRequestHeader()
static const Http::Message * actualRequestHeader (const AccessLogEntry::Pointer & al) static
XXX: Misnamed. See actualReplyHeader().
Returns
HttpRequest or HttpReply for http::>h.
Definition at line 364 of file Format.cc.
References AccessLogEntry::icap, Adaptation::methodRespmod, AccessLogEntry::IcapLogEntry::reqMethod, and AccessLogEntry::request.
Referenced by Format::Format::assemble().
log_quoted_string()
static void log_quoted_string (const char * str, char * out) static
Definition at line 292 of file Format.cc.
Referenced by Format::Format::assemble().