Squid Web Cache: squid/src/fqdncache.h File Reference
fqdncache.h File Reference
#include "dns/forward.h"
#include "ip/forward.h"
#include "sbuf/forward.h"
#include "store/forward.h"
Namespaces
namespace Dns
generic DNS API
Typedefs
using FQDNH = void(const char *, const Dns::LookupDetails &, void *)
Functions
void fqdncache_init ()
void fqdnStats (StoreEntry *)
void fqdncache_restart ()
void fqdncache_purgelru (void *)
void fqdncacheAddEntryFromHosts (char *addr, SBufList &hostnames)
const char * fqdncache_gethostbyaddr (const Ip::Address &, int flags)
void fqdncache_nbgethostbyaddr (const Ip::Address &, FQDNH *, void *)
Variables
bool Dns::ResolveClientAddressesAsap = false
whether to do reverse DNS lookups for source IPs of accepted connections
Typedef Documentation
FQDNH
using FQDNH = void (const char *, const Dns::LookupDetails &, void *)
Definition at line 25 of file fqdncache.h.
Function Documentation
fqdncacheAddEntryFromHosts()
void fqdncacheAddEntryFromHosts (char * addr, SBufList & hostnames)
Adds a "static" entry from /etc/hosts.
Parameters
addr FQDN name to be added.
hostnames list of hostnames for the addr
Definition at line 636 of file fqdncache.cc.
References DBG_IMPORTANT, debugs, fqdncache_entry::flags, FQDN_MAX_NAMES, fqdncache_get(), fqdncacheAddEntry(), fqdncacheLockEntry(), fqdncacheRelease(), fqdncacheUnlockEntry(), fqdncache_entry::Flags::fromhosts, fqdncache_entry::locks, fqdncache_entry::name_count, fqdncache_entry::names, Tolower(), and xstrdup.
Referenced by parseEtcHosts().