Squid Web Cache: squid/src/fs_io.h File Reference
fs_io.h File Reference
#include "mem/forward.h"
#include "sbuf/forward.h"
#include "typedefs.h"
Classes
class dread_ctrl
class dwrite_q
Functions
int file_open (const char *path, int mode)
void file_close (int fd)
void file_write (int, off_t, void const *, int len, DWCB *, void *, FREE *)
void file_read (int, char *, int, off_t, DRCB *, void *)
void safeunlink (const char *path, int quiet)
bool FileRename (const SBuf &from, const SBuf &to)
int fsBlockSize (const char *path, int *blksize)
int fsStats (const char *, int *, int *, int *, int *)
Function Documentation
file_close()
void file_close (int fd)
Definition at line 92 of file fs_io.cc.
References assert, fde::_fde_flags::close_request, StatCounters::closes, debugs, StatCounters::disk, diskHandleWrite, fd_close(), fd_table, fde::flags, fde::_fde_flags::open, fde::read_data, fde::read_handler, statCounter, StatCounters::syscalls, fde::_fde_flags::write_daemon, fde::write_handler, and xclose().
Referenced by Rock::Rebuild::~Rebuild(), Fs::Ufs::UFSSwapDir::~UFSSwapDir(), Fs::Ufs::UFSSwapDir::closeLog(), Fs::Ufs::UFSSwapDir::closeTmpSwapLog(), DiskerClose(), diskHandleWrite(), BlockingFile::doClose(), DiskThreadsDiskFile::doClose(), MmappedFile::doClose(), MimeIcon::load(), TemplateFile::loadFromFile(), logfile_mod_stdio_close(), logfile_mod_stdio_rotate(), logfile_mod_udp_close(), netdbReloadState(), Fs::Ufs::UFSSwapDir::openTmpSwapLog(), Fs::Ufs::RebuildState::rebuildFromDirectory(), UFSCleanLog::write(), and Fs::Ufs::UFSSwapDir::writeCleanDone().
file_open()
int file_open (const char * path, int mode)
Definition at line 66 of file fs_io.cc.
References commSetCloseOnExec(), debugs, StatCounters::disk, DISK_ERROR, FD_FILE, fd_open(), FILE_MODE, StatCounters::opens, statCounter, StatCounters::syscalls, xopen(), and xstrerr().
Referenced by Fs::Ufs::UFSSwapDir::closeTmpSwapLog(), DiskThreadsDiskFile::create(), DiskerOpen(), Fs::Ufs::RebuildState::getNextFile(), MimeIcon::load(), TemplateFile::loadFromFile(), logfile_mod_stdio_open(), logfile_mod_stdio_rotate(), netdbReloadState(), BlockingFile::open(), DiskThreadsDiskFile::open(), MmappedFile::open(), Fs::Ufs::UFSSwapDir::openLog(), Fs::Ufs::UFSSwapDir::openTmpSwapLog(), Rock::Rebuild::start(), Fs::Ufs::UFSSwapDir::writeCleanDone(), and Fs::Ufs::UFSSwapDir::writeCleanStart().
file_read()
void file_read (int fd, char * buf, int req_len, off_t offset, DRCB * handler, void * client_data)
Definition at line 424 of file fs_io.cc.
References assert, cbdataReference, and diskHandleRead.
Referenced by BlockingFile::read(), and DiskThreadsDiskFile::read().
file_write()
void file_write (int fd, off_t file_offset, void const * ptr_to_buf, int len, DWCB * handle, void * handle_data, FREE * free_func)
Definition at line 313 of file fs_io.cc.
References assert, cbdataReference, fde::disk, diskHandleWrite, fd_table, fde::flags, dwrite_q::next, fde::_fde_flags::open, fde::_fde_flags::write_daemon, _fde_disk::write_q, _fde_disk::write_q_tail, _fde_disk::wrt_handle, and _fde_disk::wrt_handle_data.
Referenced by Fs::Ufs::UFSSwapDir::logEntry(), Fs::Ufs::UFSSwapDir::openTmpSwapLog(), BlockingFile::write(), and DiskThreadsDiskFile::write().
FileRename()
bool FileRename (const SBuf & from, const SBuf & to)
Definition at line 443 of file fs_io.cc.
References SBuf::c_str(), DBG_IMPORTANT, debugs, SBuf::length(), SBuf::rawContent(), and xstrerr().
Referenced by Fs::Ufs::UFSSwapDir::closeTmpSwapLog(), logfile_mod_stdio_rotate(), and Fs::Ufs::UFSSwapDir::writeCleanDone().
fsBlockSize()
int fsBlockSize (const char * path, int * blksize)
Definition at line 466 of file fs_io.cc.
References DBG_IMPORTANT, debugs, statvfs::f_frsize, int, xstatvfs(), and xstrerr().
Referenced by Fs::Ufs::UFSSwapDir::init().
fsStats()
int fsStats (const char * path, int * totl_kb, int * free_kb, int * totl_in, int * free_in)
Definition at line 490 of file fs_io.cc.
References DBG_IMPORTANT, debugs, statvfs::f_bfree, statvfs::f_blocks, statvfs::f_ffree, statvfs::f_files, statvfs::f_frsize, fsbtoblk, int, xstatvfs(), and xstrerr().
Referenced by Fs::Ufs::UFSSwapDir::statfs().
safeunlink()
void safeunlink (const char * path, int quiet)
Definition at line 432 of file fs_io.cc.
References DBG_IMPORTANT, debugs, StatCounters::disk, statCounter, StatCounters::syscalls, StatCounters::unlinks, and xstrerr().
Referenced by Fs::Ufs::UFSSwapDir::DirClean(), Fs::Ufs::UFSSwapDir::openTmpSwapLog(), RemoveInstance(), and unlinkdUnlink().