Squid Web Cache: squid/src/clients/FtpGateway.cc File Reference
FtpGateway.cc File Reference
#include "squid.h"
#include "acl/FilledChecklist.h"
#include "base/PackableStream.h"
#include "clients/forward.h"
#include "clients/FtpClient.h"
#include "comm.h"
#include "comm/ConnOpener.h"
#include "comm/Read.h"
#include "comm/TcpAcceptor.h"
#include "CommCalls.h"
#include "compat/socket.h"
#include "compat/strtoll.h"
#include "errorpage.h"
#include "fd.h"
#include "fde.h"
#include "FwdState.h"
#include "html/Quoting.h"
#include "HttpHdrContRange.h"
#include "HttpHeader.h"
#include "HttpHeaderRange.h"
#include "HttpReply.h"
#include "ip/tools.h"
#include "MemBuf.h"
#include "mime.h"
#include "rfc1738.h"
#include "SquidConfig.h"
#include "SquidString.h"
#include "StatCounters.h"
#include "Store.h"
#include "tools.h"
#include "util.h"
#include "wordlist.h"
#include "DelayPools.h"
#include "MemObject.h"
#include <cerrno>
Classes
struct Ftp::GatewayFlags
class Ftp::Gateway
struct ftpListParts
Namespaces
namespace Ftp
Macros
#define CTRL_BUFLEN 16*1024
#define MAX_TOKENS 64
Typedefs
typedef void() Ftp::StateMethod(Ftp::Gateway *)
typedef Ftp::StateMethod FTPSM
Functions
CBDATA_NAMESPACED_CLASS_INIT (Ftp, Gateway)
static int is_month (const char *buf)
static void ftpListPartsFree (ftpListParts **parts)
static ftpListParts * ftpListParseParts (const char *buf, struct Ftp::GatewayFlags flags)
static void ftpReadWelcome (Ftp::Gateway *ftpState)
static void ftpSendUser (Ftp::Gateway *ftpState)
static void ftpReadUser (Ftp::Gateway *ftpState)
static void ftpSendPass (Ftp::Gateway *ftpState)
static void ftpReadPass (Ftp::Gateway *ftpState)
static void ftpSendType (Ftp::Gateway *ftpState)
static void ftpReadType (Ftp::Gateway *ftpState)
static void ftpTraverseDirectory (Ftp::Gateway *ftpState)
static void ftpSendCwd (Ftp::Gateway *ftpState)
static void ftpReadCwd (Ftp::Gateway *ftpState)
static void ftpSendMkdir (Ftp::Gateway *ftpState)
static void ftpReadMkdir (Ftp::Gateway *ftpState)
static void ftpGetFile (Ftp::Gateway *ftpState)
static void ftpListDir (Ftp::Gateway *ftpState)
static void ftpSendMdtm (Ftp::Gateway *ftpState)
static void ftpReadMdtm (Ftp::Gateway *ftpState)
static void ftpSendSize (Ftp::Gateway *ftpState)
static void ftpReadSize (Ftp::Gateway *ftpState)
static void ftpReadEPSV (Ftp::Gateway *ftpState)
static void ftpSendPassive (Ftp::Gateway *ftpState)
static void ftpReadPasv (Ftp::Gateway *ftpState)
static void ftpOpenListenSocket (Ftp::Gateway *ftpState, int fallback)
static void ftpSendPORT (Ftp::Gateway *ftpState)
static void ftpReadPORT (Ftp::Gateway *ftpState)
static void ftpReadEPRT (Ftp::Gateway *ftpState)
static void ftpRestOrList (Ftp::Gateway *ftpState)
static void ftpSendStor (Ftp::Gateway *ftpState)
static void ftpReadStor (Ftp::Gateway *ftpState)
static void ftpSendRest (Ftp::Gateway *ftpState)
static void ftpReadRest (Ftp::Gateway *ftpState)
static void ftpSendList (Ftp::Gateway *ftpState)
static void ftpSendNlst (Ftp::Gateway *ftpState)
static void ftpReadList (Ftp::Gateway *ftpState)
static void ftpSendRetr (Ftp::Gateway *ftpState)
static void ftpReadRetr (Ftp::Gateway *ftpState)
static void ftpReadTransferDone (Ftp::Gateway *ftpState)
static void ftpWriteTransferDone (Ftp::Gateway *ftpState)
static void ftpSendQuit (Ftp::Gateway *ftpState)
static void ftpReadQuit (Ftp::Gateway *ftpState)
static void ftpTrySlashHack (Ftp::Gateway *ftpState)
static void ftpFail (Ftp::Gateway *ftpState)
static void ftpSendReply (Ftp::Gateway *ftpState)
Variables
static char cbuf [CTRL_BUFLEN]
static FTPSM ftpReadWelcome
static FTPSM ftpSendUser
static FTPSM ftpReadUser
static FTPSM ftpSendPass
static FTPSM ftpReadPass
static FTPSM ftpSendType
static FTPSM ftpReadType
static FTPSM ftpSendMdtm
static FTPSM ftpReadMdtm
static FTPSM ftpSendSize
static FTPSM ftpReadSize
static FTPSM ftpReadEPRT
static FTPSM ftpSendPORT
static FTPSM ftpReadPORT
static FTPSM ftpSendPassive
static FTPSM ftpReadEPSV
static FTPSM ftpReadPasv
static FTPSM ftpTraverseDirectory
static FTPSM ftpListDir
static FTPSM ftpGetFile
static FTPSM ftpSendCwd
static FTPSM ftpReadCwd
static FTPSM ftpRestOrList
static FTPSM ftpSendList
static FTPSM ftpSendNlst
static FTPSM ftpReadList
static FTPSM ftpSendRest
static FTPSM ftpReadRest
static FTPSM ftpSendRetr
static FTPSM ftpReadRetr
static FTPSM ftpReadTransferDone
static FTPSM ftpSendStor
static FTPSM ftpReadStor
static FTPSM ftpWriteTransferDone
static FTPSM ftpSendReply
static FTPSM ftpSendMkdir
static FTPSM ftpReadMkdir
static FTPSM ftpFail
static FTPSM ftpSendQuit
static FTPSM ftpReadQuit
FTPSM * FTP_SM_FUNCS []
static const char * Month []
Macro Definition Documentation
CTRL_BUFLEN
#define CTRL_BUFLEN 16*1024
Definition at line 194 of file FtpGateway.cc.
MAX_TOKENS
#define MAX_TOKENS 64
Definition at line 531 of file FtpGateway.cc.
Typedef Documentation
FTPSM
typedef Ftp::StateMethod FTPSM
Definition at line 181 of file FtpGateway.cc.
Function Documentation
CBDATA_NAMESPACED_CLASS_INIT()
CBDATA_NAMESPACED_CLASS_INIT (Ftp , Gateway)
ftpFail()
static void ftpFail (Ftp::Gateway * ftpState) static
Definition at line 2375 of file FtpGateway.cc.
References FwdState::al, Ftp::Client::ctrl, debugs, Ftp::Gateway::decodedRequestUriPath(), Client::entry, ERR_NONE, Ftp::Client::failed(), Ftp::Gateway::failedHttpStatus(), Ftp::Gateway::flags, ftpSendQuit, ftpTrySlashHack(), Client::fwd, Ftp::Gateway::hackShortcut(), Ftp::GatewayFlags::isdir, Ftp::Gateway::mdtm, AnyP::Uri::path(), StoreEntry::replaceHttpReply(), Ftp::CtrlChannel::replycode, Client::request, FwdState::request, Ftp::Client::SENT_CWD, Ftp::Client::SENT_RETR, Ftp::Client::state, Ftp::Gateway::theSize, Ftp::GatewayFlags::try_slash_hack, and HttpRequest::url.
ftpGetFile()
static void ftpGetFile (Ftp::Gateway * ftpState) static
Definition at line 1557 of file FtpGateway.cc.
References assert, Ftp::Gateway::filepath, Ftp::Gateway::flags, ftpSendMdtm, and Ftp::GatewayFlags::isdir.
ftpListDir()
static void ftpListDir (Ftp::Gateway * ftpState) static
Definition at line 1565 of file FtpGateway.cc.
References String::append(), debugs, Ftp::GatewayFlags::dir_slash, Ftp::Gateway::flags, ftpSendPassive, Ftp::GatewayFlags::isdir, and Ftp::Gateway::title_url.
ftpListParseParts()
static ftpListParts * ftpListParseParts (const char * buf, struct Ftp::GatewayFlags flags) static
< token image copied from the received line
< token offset on the received line
Definition at line 534 of file FtpGateway.cc.
References assert, ftpListParts::date, ftpListPartsFree(), is_month(), ftpListParts::link, MAX_TOKENS, ftpListParts::name, safe_free, ftpListParts::size, size, Ftp::GatewayFlags::skip_whitespace, strtoll(), tok::token, tokens, Ftp::GatewayFlags::tried_nlst, ftpListParts::type, w_space, xcalloc(), xfree, xstrdup, and xstrndup().
Referenced by Ftp::Gateway::htmlifyListEntry().
ftpListPartsFree()
static void ftpListPartsFree (ftpListParts ** parts) static
Definition at line 522 of file FtpGateway.cc.
References safe_free.
Referenced by ftpListParseParts(), and Ftp::Gateway::htmlifyListEntry().
ftpOpenListenSocket()
static void ftpOpenListenSocket (Ftp::Gateway * ftpState, int fallback) static
Close old data channels, if any. We may open a new one below.
Definition at line 1755 of file FtpGateway.cc.
References Ftp::Channel::clear(), Ftp::Channel::close(), COMM_REUSEADDR, Ftp::Channel::conn, Ftp::Client::ctrl, Ftp::Client::data, debugs, Comm::Connection::fd, Comm::Connection::flags, Ftp::DataChannel::host, Comm::IsConnOpen(), Ftp::Gateway::listenForDataChannel(), Comm::Connection::local, on, Ip::Address::port(), safe_free, xsetsockopt(), and xstrerr().
Referenced by ftpReadPORT(), and ftpSendPORT().
ftpReadCwd()
static void ftpReadCwd (Ftp::Gateway * ftpState) static
Definition at line 1490 of file FtpGateway.cc.
References String::append(), Ftp::Client::ctrl, Ftp::Gateway::cwd_message, debugs, Ftp::Gateway::flags, ftpFail, ftpSendMkdir, ftpTraverseDirectory, Ftp::CtrlChannel::message, MYNAME, Ftp::GatewayFlags::put, Ftp::CtrlChannel::replycode, String::reset(), and Ftp::Gateway::unhack().
ftpReadEPRT()
static void ftpReadEPRT (Ftp::Gateway * ftpState) static
Definition at line 1864 of file FtpGateway.cc.
References Ftp::Client::ctrl, debugs, ftpRestOrList, ftpSendPORT, MYNAME, and Ftp::CtrlChannel::replycode.
ftpReadEPSV()
static void ftpReadEPSV (Ftp::Gateway * ftpState) static
Definition at line 1652 of file FtpGateway.cc.
References Ftp::Client::connectDataChannel(), Ftp::Client::ctrl, Ftp::Client::handleEpsvReply(), and Ftp::CtrlChannel::message.
ftpReadList()
static void ftpReadList (Ftp::Gateway * ftpState) static
Definition at line 2151 of file FtpGateway.cc.
References Ftp::Channel::conn, Ftp::Client::ctrl, Ftp::Client::data, debugs, Ftp::Gateway::flags, ftpFail, ftpSendNlst, Comm::IsConnOpen(), Ftp::Gateway::listenForDataChannel(), Comm::Connection::local, Ftp::Client::maybeReadVirginBody(), MYNAME, Ftp::Client::READING_DATA, Comm::Connection::remote, Ftp::CtrlChannel::replycode, Ftp::Client::state, Ftp::Client::switchTimeoutToDataChannel(), and Ftp::GatewayFlags::tried_nlst.
ftpReadMdtm()
static void ftpReadMdtm (Ftp::Gateway * ftpState) static
Definition at line 1590 of file FtpGateway.cc.
References Ftp::Client::ctrl, debugs, ftpFail, ftpSendSize, Ftp::CtrlChannel::last_reply, Ftp::Gateway::mdtm, MYNAME, Time::ParseIso3307(), Ftp::CtrlChannel::replycode, and Ftp::Gateway::unhack().
ftpReadMkdir()
static void ftpReadMkdir (Ftp::Gateway * ftpState) static
Definition at line 1536 of file FtpGateway.cc.
References Ftp::Client::ctrl, debugs, Ftp::Gateway::filepath, Ftp::Gateway::flags, ftpSendCwd, ftpSendReply, Ftp::GatewayFlags::put_mkdir, and Ftp::CtrlChannel::replycode.
ftpReadPass()
static void ftpReadPass (Ftp::Gateway * ftpState) static
Definition at line 1332 of file FtpGateway.cc.
References Ftp::Client::ctrl, debugs, ftpSendType, Ftp::Gateway::loginFailed(), and Ftp::CtrlChannel::replycode.
ftpReadPasv()
static void ftpReadPasv (Ftp::Gateway * ftpState) static
Definition at line 1719 of file FtpGateway.cc.
References Ftp::Client::connectDataChannel(), ftpFail, and Ftp::Client::handlePasvReply().
ftpReadPORT()
static void ftpReadPORT (Ftp::Gateway * ftpState) static
Definition at line 1849 of file FtpGateway.cc.
References Ftp::Client::ctrl, debugs, ftpOpenListenSocket(), ftpRestOrList, MYNAME, and Ftp::CtrlChannel::replycode.
ftpReadQuit()
static void ftpReadQuit (Ftp::Gateway * ftpState) static
Completes a client FTP operation with success or other page generated and stored in the entry field by the code issuing QUIT.
Definition at line 2302 of file FtpGateway.cc.
References Client::serverComplete().
ftpReadRest()
static void ftpReadRest (Ftp::Gateway * ftpState) static
Definition at line 2092 of file FtpGateway.cc.
References assert, Ftp::Client::ctrl, debugs, Ftp::Gateway::flags, ftpFail, ftpSendRetr, MYNAME, Ftp::CtrlChannel::replycode, Ftp::GatewayFlags::rest_supported, Ftp::Gateway::restart_offset, and Ftp::Gateway::setCurrentOffset().
ftpReadRetr()
static void ftpReadRetr (Ftp::Gateway * ftpState) static
Definition at line 2192 of file FtpGateway.cc.
References Ftp::Channel::conn, Ftp::Client::ctrl, Ftp::Client::data, debugs, Ftp::Gateway::flags, ftpFail, ftpSendCwd, Ftp::Gateway::hackShortcut(), Comm::IsConnOpen(), Ftp::Gateway::listenForDataChannel(), Comm::Connection::local, Ftp::Client::maybeReadVirginBody(), MYNAME, Ftp::Client::READING_DATA, Comm::Connection::remote, Ftp::CtrlChannel::replycode, Ftp::Client::state, Ftp::Client::switchTimeoutToDataChannel(), and Ftp::GatewayFlags::try_slash_hack.
ftpReadSize()
static void ftpReadSize (Ftp::Gateway * ftpState) static
Definition at line 1628 of file FtpGateway.cc.
References Ftp::Client::ctrl, debugs, ftpFail, ftpSendPassive, Ftp::CtrlChannel::last_reply, MYNAME, Ftp::CtrlChannel::replycode, strtoll(), Ftp::Gateway::theSize, Ftp::Gateway::title_url, and Ftp::Gateway::unhack().
ftpReadStor()
static void ftpReadStor (Ftp::Gateway * ftpState) static
Deprecated:
use ftpState->readStor() instead.
Definition at line 2010 of file FtpGateway.cc.
References Ftp::Gateway::readStor().
ftpReadTransferDone()
static void ftpReadTransferDone (Ftp::Gateway * ftpState) static
Definition at line 2239 of file FtpGateway.cc.
References Ftp::Gateway::completedListing(), Ftp::Client::ctrl, DBG_IMPORTANT, debugs, ERR_FTP_FAILURE, Ftp::Client::failed(), Ftp::Gateway::flags, ftpSendQuit, Ftp::GatewayFlags::listing, Client::markParsedVirginReplyAsWhole(), MYNAME, and Ftp::CtrlChannel::replycode.
ftpReadType()
static void ftpReadType (Ftp::Gateway * ftpState) static
Definition at line 1394 of file FtpGateway.cc.
References Ftp::Client::ctrl, debugs, ftpFail, ftpListDir, ftpTraverseDirectory, AnyP::Uri::path(), Ftp::Gateway::pathcomps, Ftp::CtrlChannel::replycode, Client::request, rfc1738_unescape(), SBufToCstring(), HttpRequest::url, wordlistAdd(), and xfree.
ftpReadUser()
static void ftpReadUser (Ftp::Gateway * ftpState) static
Definition at line 1305 of file FtpGateway.cc.
References Ftp::Client::ctrl, debugs, ftpReadPass, ftpSendPass, Ftp::Gateway::loginFailed(), MYNAME, and Ftp::CtrlChannel::replycode.
ftpReadWelcome()
static void ftpReadWelcome (Ftp::Gateway * ftpState) static
Definition at line 1195 of file FtpGateway.cc.
References Ftp::Client::ctrl, DBG_IMPORTANT, debugs, Ftp::Gateway::flags, ftpFail, ftpSendUser, wordlist::key, Ftp::Gateway::login_att, Ftp::CtrlChannel::message, MYNAME, Ftp::GatewayFlags::pasv_only, Ftp::CtrlChannel::replycode, and Ftp::GatewayFlags::skip_whitespace.
ftpRestOrList()
static void ftpRestOrList (Ftp::Gateway * ftpState) static
Definition at line 1961 of file FtpGateway.cc.
References debugs, Ftp::Gateway::flags, ftpSendList, ftpSendMkdir, ftpSendNlst, ftpSendRest, ftpSendRetr, ftpSendStor, Ftp::GatewayFlags::isdir, MYNAME, Ftp::GatewayFlags::put, Ftp::Gateway::restartable(), and Ftp::Gateway::typecode.
ftpSendCwd()
static void ftpSendCwd (Ftp::Gateway * ftpState) static
Definition at line 1464 of file FtpGateway.cc.
References cbuf, CTRL_BUFLEN, debugs, Ftp::Gateway::filepath, Ftp::Gateway::flags, Ftp::Gateway::haveControlChannel(), MYNAME, Ftp::GatewayFlags::no_dotdot, Ftp::Client::SENT_CWD, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendList()
static void ftpSendList (Ftp::Gateway * ftpState) static
Definition at line 2111 of file FtpGateway.cc.
References cbuf, CTRL_BUFLEN, debugs, Ftp::Gateway::filepath, Ftp::Gateway::haveControlChannel(), MYNAME, Ftp::Client::SENT_LIST, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendMdtm()
static void ftpSendMdtm (Ftp::Gateway * ftpState) static
Definition at line 1577 of file FtpGateway.cc.
References assert, cbuf, CTRL_BUFLEN, Ftp::Gateway::filepath, Ftp::Gateway::haveControlChannel(), Ftp::Client::SENT_MDTM, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendMkdir()
static void ftpSendMkdir (Ftp::Gateway * ftpState) static
Definition at line 1520 of file FtpGateway.cc.
References cbuf, CTRL_BUFLEN, debugs, Ftp::Gateway::filepath, Ftp::Gateway::haveControlChannel(), Ftp::Client::SENT_MKDIR, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendNlst()
static void ftpSendNlst (Ftp::Gateway * ftpState) static
Definition at line 2130 of file FtpGateway.cc.
References cbuf, CTRL_BUFLEN, debugs, Ftp::Gateway::filepath, Ftp::Gateway::flags, Ftp::Gateway::haveControlChannel(), MYNAME, Ftp::Client::SENT_NLST, Ftp::Client::state, Ftp::GatewayFlags::tried_nlst, and Ftp::Client::writeCommand().
ftpSendPass()
static void ftpSendPass (Ftp::Gateway * ftpState) static
Definition at line 1320 of file FtpGateway.cc.
References cbuf, CTRL_BUFLEN, Ftp::Gateway::haveControlChannel(), Ftp::Gateway::password, Ftp::Client::SENT_PASS, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendPassive()
static void ftpSendPassive (Ftp::Gateway * ftpState) static
Send Passive connection request. Default method is to use modern EPSV request. The failover mechanism should check for previous state and re-call with alternates on failure.
Checks the server control channel is still available before running.
Checks for 'HEAD' method request and passes off for special handling by Ftp::Gateway::processHeadResponse().
Definition at line 1668 of file FtpGateway.cc.
References debugs, Ftp::GatewayFlags::epsv_all_sent, Ftp::Gateway::flags, Ftp::Gateway::haveControlChannel(), Ftp::GatewayFlags::isdir, HttpRequest::method, Http::METHOD_HEAD, MYNAME, Ftp::Gateway::processHeadResponse(), Client::request, Ftp::Client::sendPassive(), Ftp::Client::SENT_EPSV_ALL, Ftp::Client::state, and Ftp::Gateway::theSize.
ftpSendPORT()
static void ftpSendPORT (Ftp::Gateway * ftpState) static
Definition at line 1803 of file FtpGateway.cc.
References cbuf, Config, CTRL_BUFLEN, Ftp::Client::data, DBG_IMPORTANT, debugs, SquidConfig::epsv_all, Ftp::GatewayFlags::epsv_all_sent, Ftp::Gateway::flags, Ip::Address::FreeAddr(), SquidConfig::Ftp, ftpFail, ftpOpenListenSocket(), ftpReadPORT, Ip::Address::getAddrInfo(), Ftp::Gateway::haveControlChannel(), Comm::IsConnOpen(), Ip::Address::isIPv4(), Ftp::Channel::listenConn, Comm::Connection::local, MYNAME, Ftp::GatewayFlags::pasv_supported, Ftp::Client::SENT_PORT, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendQuit()
static void ftpSendQuit (Ftp::Gateway * ftpState) static
Definition at line 2287 of file FtpGateway.cc.
References cbuf, CTRL_BUFLEN, Ftp::Gateway::haveControlChannel(), Ftp::Client::SENT_QUIT, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendReply()
static void ftpSendReply (Ftp::Gateway * ftpState) static
Definition at line 2456 of file FtpGateway.cc.
References FwdState::al, ErrorState::BuildHttpReply(), cbdataReferenceValid(), Ftp::Client::ctrl, debugs, ErrorState::detailError(), Client::entry, ERR_FTP_PUT_CREATED, ERR_FTP_PUT_ERROR, ERR_FTP_PUT_MODIFIED, ERR_NONE, ErrorState::ftp, ftpSendQuit, Client::fwd, RefCount< C >::getRaw(), Ftp::CtrlChannel::last_command, Ftp::CtrlChannel::last_reply, Ftp::Gateway::mdtm, Ftp::Client::old_reply, Ftp::Client::old_request, StoreEntry::replaceHttpReply(), ErrorState::reply, Ftp::CtrlChannel::replycode, Client::request, ErrorState::request, Http::scAccepted, Http::scCreated, Http::scInternalServerError, StoreEntry::url(), and xstrdup.
ftpSendRest()
static void ftpSendRest (Ftp::Gateway * ftpState) static
Definition at line 2051 of file FtpGateway.cc.
References cbuf, CTRL_BUFLEN, debugs, Ftp::Gateway::haveControlChannel(), MYNAME, PRId64, Ftp::Gateway::restart_offset, Ftp::Client::SENT_REST, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendRetr()
static void ftpSendRetr (Ftp::Gateway * ftpState) static
Definition at line 2177 of file FtpGateway.cc.
References assert, cbuf, CTRL_BUFLEN, debugs, Ftp::Gateway::filepath, Ftp::Gateway::haveControlChannel(), MYNAME, Ftp::Client::SENT_RETR, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendSize()
static void ftpSendSize (Ftp::Gateway * ftpState) static
Definition at line 1607 of file FtpGateway.cc.
References assert, Ftp::GatewayFlags::binary, cbuf, CTRL_BUFLEN, Ftp::Gateway::filepath, Ftp::Gateway::flags, ftpSendPassive, Ftp::Gateway::haveControlChannel(), Ftp::Client::SENT_SIZE, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendStor()
static void ftpSendStor (Ftp::Gateway * ftpState) static
Definition at line 1984 of file FtpGateway.cc.
References cbuf, Http::CONTENT_LENGTH, CTRL_BUFLEN, debugs, Ftp::Gateway::filepath, ftpSendReply, HttpHeader::getInt64(), Ftp::Gateway::haveControlChannel(), Http::Message::header, MYNAME, Client::request, Ftp::Client::SENT_STOR, Ftp::Client::state, and Ftp::Client::writeCommand().
ftpSendType()
static void ftpSendType (Ftp::Gateway * ftpState) static
Definition at line 1345 of file FtpGateway.cc.
References Ftp::GatewayFlags::binary, SBuf::c_str(), cbuf, CTRL_BUFLEN, Ftp::Gateway::flags, Ftp::Gateway::haveControlChannel(), Ftp::GatewayFlags::isdir, mimeGetTransferMode(), SBuf::npos, AnyP::Uri::path(), Client::request, Ftp::Client::SENT_TYPE, Ftp::Client::state, Ftp::Gateway::typecode, HttpRequest::url, and Ftp::Client::writeCommand().
ftpSendUser()
static void ftpSendUser (Ftp::Gateway * ftpState) static
Definition at line 1288 of file FtpGateway.cc.
References cbuf, CTRL_BUFLEN, Ftp::Gateway::haveControlChannel(), AnyP::Uri::host(), Ftp::Gateway::proxy_host, Client::request, Ftp::Client::SENT_USER, Ftp::Client::state, HttpRequest::url, Ftp::Gateway::user, and Ftp::Client::writeCommand().
ftpTraverseDirectory()
static void ftpTraverseDirectory (Ftp::Gateway * ftpState) static
Definition at line 1434 of file FtpGateway.cc.
References debugs, Ftp::Gateway::dirpath, Ftp::Gateway::filepath, Ftp::Gateway::flags, ftpGetFile, ftpListDir, ftpSendCwd, Ftp::GatewayFlags::isdir, Ftp::Gateway::pathcomps, safe_free, and wordlistChopHead().
ftpTrySlashHack()
static void ftpTrySlashHack (Ftp::Gateway * ftpState) static
\prec !ftpState->flags.try_slash_hack \prec ftpState->decodedRequestUriPath()
Definition at line 2317 of file FtpGateway.cc.
References debugs, Ftp::Gateway::decodedRequestUriPath(), Ftp::Gateway::filepath, Ftp::Gateway::flags, ftpGetFile, MYNAME, Ftp::Gateway::pathcomps, safe_free, SBufToCstring(), Ftp::GatewayFlags::try_slash_hack, and wordlistDestroy().
Referenced by ftpFail().
ftpWriteTransferDone()
static void ftpWriteTransferDone (Ftp::Gateway * ftpState) static
Definition at line 2270 of file FtpGateway.cc.
References Ftp::Client::ctrl, DBG_IMPORTANT, debugs, Client::entry, ERR_FTP_PUT_ERROR, Ftp::Client::failed(), ftpSendReply, Client::markParsedVirginReplyAsWhole(), MYNAME, Ftp::CtrlChannel::replycode, and StoreEntry::timestampsSet().
is_month()
static int is_month (const char * buf) static
Definition at line 510 of file FtpGateway.cc.
References Month.
Referenced by ftpListParseParts().
Variable Documentation
cbuf
char cbuf[CTRL_BUFLEN] static
Definition at line 195 of file FtpGateway.cc.
Referenced by ftpSendCwd(), ftpSendList(), ftpSendMdtm(), ftpSendMkdir(), ftpSendNlst(), ftpSendPass(), ftpSendPORT(), ftpSendQuit(), ftpSendRest(), ftpSendRetr(), ftpSendSize(), ftpSendStor(), ftpSendType(), and ftpSendUser().
FTP_SM_FUNCS
FTPSM* FTP_SM_FUNCS[]
Initial value:
= {
    ftpReadWelcome,
    ftpReadUser,
    ftpReadPass,
    ftpReadType,
    ftpReadMdtm,
    ftpReadSize,
    ftpReadEPRT,
    ftpReadPORT,
    ftpReadEPSV,
    ftpReadEPSV,
    ftpReadEPSV,
    ftpReadPasv,
    ftpReadCwd,
    ftpReadList,
    ftpReadList,
    ftpReadRest,
    ftpReadRetr,
    ftpReadStor,
    ftpReadQuit,
    ftpReadTransferDone,
    ftpWriteTransferDone,
    ftpReadMkdir,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr
}
Definition at line 286 of file FtpGateway.cc.
Referenced by Ftp::Gateway::handleControlReply().
ftpFail
FTPSM ftpFail static
Definition at line 240 of file FtpGateway.cc.
Referenced by Ftp::Gateway::ftpAcceptDataConnection(), ftpReadCwd(), ftpReadList(), ftpReadMdtm(), ftpReadPasv(), ftpReadRest(), ftpReadRetr(), ftpReadSize(), ftpReadType(), ftpReadWelcome(), ftpSendPORT(), Ftp::Gateway::loginFailed(), and Ftp::Gateway::readStor().
ftpGetFile
FTPSM ftpGetFile static
Definition at line 222 of file FtpGateway.cc.
Referenced by ftpTraverseDirectory(), and ftpTrySlashHack().
ftpListDir
FTPSM ftpListDir static
Definition at line 221 of file FtpGateway.cc.
Referenced by ftpReadType(), and ftpTraverseDirectory().
ftpReadCwd
FTPSM ftpReadCwd static
Definition at line 224 of file FtpGateway.cc.
ftpReadEPRT
FTPSM ftpReadEPRT static
Definition at line 214 of file FtpGateway.cc.
ftpReadEPSV
FTPSM ftpReadEPSV static
Definition at line 218 of file FtpGateway.cc.
ftpReadList
FTPSM ftpReadList static
Definition at line 228 of file FtpGateway.cc.
ftpReadMdtm
FTPSM ftpReadMdtm static
Definition at line 211 of file FtpGateway.cc.
ftpReadMkdir
FTPSM ftpReadMkdir static
Definition at line 239 of file FtpGateway.cc.
ftpReadPass
FTPSM ftpReadPass static
Definition at line 207 of file FtpGateway.cc.
Referenced by ftpReadUser().
ftpReadPasv
FTPSM ftpReadPasv static
Definition at line 219 of file FtpGateway.cc.
ftpReadPORT
FTPSM ftpReadPORT static
Definition at line 216 of file FtpGateway.cc.
Referenced by ftpSendPORT().
ftpReadQuit
FTPSM ftpReadQuit static
Definition at line 242 of file FtpGateway.cc.
ftpReadRest
FTPSM ftpReadRest static
Definition at line 230 of file FtpGateway.cc.
ftpReadRetr
FTPSM ftpReadRetr static
Definition at line 232 of file FtpGateway.cc.
ftpReadSize
FTPSM ftpReadSize static
Definition at line 213 of file FtpGateway.cc.
ftpReadStor
FTPSM ftpReadStor static
Definition at line 235 of file FtpGateway.cc.
ftpReadTransferDone
FTPSM ftpReadTransferDone static
Definition at line 233 of file FtpGateway.cc.
ftpReadType
FTPSM ftpReadType static
Definition at line 209 of file FtpGateway.cc.
ftpReadUser
FTPSM ftpReadUser static
Definition at line 205 of file FtpGateway.cc.
ftpReadWelcome
FTPSM ftpReadWelcome static
Definition at line 203 of file FtpGateway.cc.
ftpRestOrList
FTPSM ftpRestOrList static
Definition at line 225 of file FtpGateway.cc.
Referenced by Ftp::Gateway::dataChannelConnected(), ftpReadEPRT(), and ftpReadPORT().
ftpSendCwd
FTPSM ftpSendCwd static
Definition at line 223 of file FtpGateway.cc.
Referenced by ftpReadMkdir(), ftpReadRetr(), and ftpTraverseDirectory().
ftpSendList
FTPSM ftpSendList static
Definition at line 226 of file FtpGateway.cc.
Referenced by ftpRestOrList().
ftpSendMdtm
FTPSM ftpSendMdtm static
Definition at line 210 of file FtpGateway.cc.
Referenced by ftpGetFile().
ftpSendMkdir
FTPSM ftpSendMkdir static
Definition at line 238 of file FtpGateway.cc.
Referenced by ftpReadCwd(), and ftpRestOrList().
ftpSendNlst
FTPSM ftpSendNlst static
Definition at line 227 of file FtpGateway.cc.
Referenced by ftpReadList(), and ftpRestOrList().
ftpSendPass
FTPSM ftpSendPass static
Definition at line 206 of file FtpGateway.cc.
Referenced by ftpReadUser().
ftpSendPassive
FTPSM ftpSendPassive static
Definition at line 217 of file FtpGateway.cc.
Referenced by Ftp::Gateway::dataChannelConnected(), ftpListDir(), ftpReadSize(), and ftpSendSize().
ftpSendPORT
FTPSM ftpSendPORT static
Definition at line 215 of file FtpGateway.cc.
Referenced by ftpReadEPRT().
ftpSendQuit
FTPSM ftpSendQuit static
Definition at line 241 of file FtpGateway.cc.
Referenced by ftpFail(), ftpReadTransferDone(), ftpSendReply(), and Ftp::Gateway::processHeadResponse().
ftpSendReply
FTPSM ftpSendReply static
Definition at line 237 of file FtpGateway.cc.
Referenced by ftpReadMkdir(), ftpSendStor(), and ftpWriteTransferDone().
ftpSendRest
FTPSM ftpSendRest static
Definition at line 229 of file FtpGateway.cc.
Referenced by ftpRestOrList().
ftpSendRetr
FTPSM ftpSendRetr static
Definition at line 231 of file FtpGateway.cc.
Referenced by ftpReadRest(), and ftpRestOrList().
ftpSendSize
FTPSM ftpSendSize static
Definition at line 212 of file FtpGateway.cc.
Referenced by ftpReadMdtm().
ftpSendStor
FTPSM ftpSendStor static
Definition at line 234 of file FtpGateway.cc.
Referenced by ftpRestOrList().
ftpSendType
FTPSM ftpSendType static
Definition at line 208 of file FtpGateway.cc.
Referenced by ftpReadPass().
ftpSendUser
FTPSM ftpSendUser static
Definition at line 204 of file FtpGateway.cc.
Referenced by ftpReadWelcome().
ftpTraverseDirectory
FTPSM ftpTraverseDirectory static
Definition at line 220 of file FtpGateway.cc.
Referenced by ftpReadCwd(), and ftpReadType().
ftpWriteTransferDone
FTPSM ftpWriteTransferDone static
Definition at line 236 of file FtpGateway.cc.
Month
const char* Month[] static
Initial value:
= {
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
}
Definition at line 504 of file FtpGateway.cc.
Referenced by is_month().