Squid Web Cache: Access Controls
Access Controls
Squid Components
Namespaces
namespace Acl
Classes
class acl_proxy_auth_match_cache
class ACLAdaptationServiceData
class ACLAnnotationData
class ACLARP
class ACLCertificateData
class ACLChecklist
class ACLFilledChecklist
class ACLHasComponentData
struct acl_httpstatus_data
class ACLHTTPStatus
class ACLLocalIP
class ACLMaxConnection
class Acl::Node
class ACLNoteData
class ACLSquidErrorData
Enumerations
enum aclMatchCode { ACCESS_DENIED , ACCESS_ALLOWED , ACCESS_DUNNO , ACCESS_AUTH_REQUIRED }
Functions
void aclDestroyAccessList (acl_access **list)
void aclDestroyAclList (ACLList **)
template<class Any >
size_t aclParseAclList (ConfigParser &parser, ACLList **const tree, const Any any)
Template to convert various context labels to strings.
void aclParseDenyInfoLine (AclDenyInfoList **)
void aclDestroyDenyInfoList (AclDenyInfoList **)
wordlist * aclDumpGeneric (const Acl::Node *)
void aclCacheMatchFlush (dlink_list *cache)
void dump_acl_access (StoreEntry *entry, const char *name, acl_access *head)
void dump_acl_list (StoreEntry *entry, ACLList *head)
Detailed Description
These functions are responsible for allowing or denying a request, based on a number of different parameters. These parameters include the client's IP address, the hostname of the requested resource, the request method, etc. Some of the necessary information may not be immediately available, for example the origin server's IP address. In these cases, the ACL routines initiate lookups for the necessary information and continues the access control checks when the information is available.
Enumeration Type Documentation
aclMatchCode
enum aclMatchCode
Enumerator
ACCESS_DENIED
ACCESS_ALLOWED
ACCESS_DUNNO
ACCESS_AUTH_REQUIRED
Definition at line 39 of file Acl.h.
Function Documentation
aclCacheMatchFlush()
void aclCacheMatchFlush (dlink_list * cache)
Definition at line 425 of file Acl.cc.
References dlink_node::data, debugs, dlinkDelete(), dlink_list::head, and dlink_node::next.
Referenced by Auth::User::~User(), and Auth::CredentialsCache::doConfigChangeCleanup().
aclDestroyAccessList()
void aclDestroyAccessList (acl_access ** list)
Definition at line 223 of file Gadgets.cc.
References assert, debugs, and Acl::Node::name.
Referenced by CachePeer::~CachePeer(), ClientDelayPool::~ClientDelayPool(), DelayPool::~DelayPool(), HttpUpgradeProtocolAccess::~HttpUpgradeProtocolAccess(), MessageDelayPool::~MessageDelayPool(), HttpUpgradeProtocolAccess::NamedGuard::~NamedGuard(), free_acl_access(), and header_mangler_clean().
aclDestroyAclList()
void aclDestroyAclList (ACLList ** list)
Definition at line 214 of file Gadgets.cc.
References assert, and debugs.
Referenced by acl_nfmark::~acl_nfmark(), acl_tos::~acl_tos(), AclSizeLimit::~AclSizeLimit(), Acl::Address::~Address(), FormattedLog::~FormattedLog(), sslproxy_cert_adapt::~sslproxy_cert_adapt(), sslproxy_cert_sign::~sslproxy_cert_sign(), Note::Value::~Value(), and free_HeaderWithAclList().
aclDestroyDenyInfoList()
void aclDestroyDenyInfoList (AclDenyInfoList ** list)
Definition at line 236 of file Gadgets.cc.
References debugs, and AclDenyInfoList::next.
aclDumpGeneric()
wordlist * aclDumpGeneric (const Acl::Node *)
aclParseAclList()
template<class Any > size_t aclParseAclList (ConfigParser & parser, ACLList **const tree, const Any any) inline
Definition at line 40 of file Gadgets.h.
References aclParseAclList().
aclParseDenyInfoLine()
void aclParseDenyInfoLine (AclDenyInfoList ** head)
Definition at line 88 of file Gadgets.cc.
References cfg_filename, config_input_line, config_lineno, ConfigParser::CurrentLocation(), DBG_CRITICAL, debugs, head, AclDenyInfoList::next, and ConfigParser::NextToken().
Referenced by parse_denyinfo().
dump_acl_access()
void dump_acl_access (StoreEntry * entry, const char * name, acl_access * head)
Definition at line 1499 of file cache_cf.cc.
References Acl::AllowOrDeny(), dump_SBufList(), and head.
Referenced by DelayPool::dump(), MessageDelayPool::dump(), ClientDelayPool::dump(), dump_peer(), Adaptation::Config::DumpAccess(), and header_mangler_dump_access().
dump_acl_list()
void dump_acl_list (StoreEntry * entry, ACLList * head)
Definition at line 1491 of file cache_cf.cc.
References dump_SBufList(), and head.
Referenced by dump_access_log(), dump_acl_address(), dump_acl_b_size_t(), dump_acl_tos(), dump_HeaderWithAclList(), dump_sslproxy_cert_adapt(), and dump_sslproxy_cert_sign().