Squid Web Cache: ICPv3 Internals
ICPv3 Internals
Squid Components » Server-Side Protocols » ICP
Classes
class ICP3State
Functions
static void doV3Query (int fd, Ip::Address &from, const char *const buf, icp_common_t header)
void icpHandleIcpV3 (int fd, Ip::Address &from, char *buf, int len)
Detailed Description
Function Documentation
doV3Query()
static void doV3Query (int fd, Ip::Address & from, const char *const buf, icp_common_t header) static
Definition at line 35 of file icp_v3.cc.
References ICPState::al, ICPState::fd, ICPState::from, ICP_ERR, ICP_HIT, ICP_MISS, icpAccessAllowed(), icpCreateAndSend(), icpDenyAccess(), icpGetCommonOpcode(), icpGetRequest(), icpGetUrl(), ICPState::isHit(), icp_common_t::reqnum, ICPState::url, and xstrdup.
Referenced by icpHandleIcpV3().
icpHandleIcpV3()
void icpHandleIcpV3 (int fd, Ip::Address & from, char * buf, int len)
Definition at line 75 of file icp_v3.cc.
References DBG_CRITICAL, debugs, doV3Query(), icp_common_t::getOpCode(), icp_common_t::handleReply(), ICP_DECHO, ICP_DENIED, ICP_ERR, ICP_HIT, ICP_INVALID, ICP_MISS, ICP_MISS_NOFETCH, icp_opcode_str, ICP_QUERY, icp_common_t::length, and icp_common_t::opcode.
Referenced by icpHandleUdp().