Squid Web Cache: Server-Side WHOIS API
Server-Side WHOIS API
Squid Components » Server-Side Protocols
Functions
void whoisStart (FwdState *)
Detailed Description
Function Documentation
whoisStart()
void whoisStart (FwdState * fwd)
Definition at line 56 of file WhoisGateway.cc.
References AnyP::Uri::absolutePath(), WhoisState::buf, BUFSIZ, comm_add_close_handler(), comm_read(), commCbCall(), commSetConnTimeout(), Config, WhoisState::dataWritten, WhoisState::entry, FwdState::entry, Comm::Connection::fd, WhoisState::fwd, SBuf::length(), StoreEntry::lock(), SquidConfig::read, WhoisState::request, FwdState::request, FwdState::serverConnection(), SQUIDSBUFPH, SQUIDSBUFPRINT, SBuf::substr(), SquidConfig::Timeout, HttpRequest::url, whoisClose, whoisReadReply, whoisTimeout, whoisWriteComplete(), Comm::Write(), and xmalloc.
Referenced by FwdState::dispatch().