Squid Web Cache: ICPv2 Internals
ICPv2 Internals
Squid Components » Server-Side Protocols » ICP
Classes
class ICP2State
Functions
static void icpLogIcp (const Ip::Address &caddr, const LogTags_ot logcode, const int len, const char *url, int delay, AccessLogEntry::Pointer &al)
updates ALE (if any) and logs the transaction (if needed)
static void icpHandleIcpV2 (int, Ip::Address &, char *, int)
static void icpCount (void *, int, size_t, int)
static void icpUdpSendQueue (int fd, void *)
Variables
static DelayedUdpSend * IcpQueueHead = nullptr
static DelayedUdpSend * IcpQueueTail = nullptr
Comm::ConnectionPointer icpIncomingConn = nullptr
Comm::ConnectionPointer icpOutgoingConn = nullptr
Detailed Description
Function Documentation
icpCount()
static void icpCount (void * buf, int which, size_t len, int delay) static
Definition at line 796 of file icp_v2.cc.
References StatHist::count(), StatCounters::hits_recv, StatCounters::hits_sent, StatCounters::icp, ICP_HIT, ICP_QUERY, StatCounters::kbytes_recv, StatCounters::kbytes_sent, icp_common_t::opcode, StatCounters::pkts_recv, StatCounters::pkts_sent, StatCounters::q_kbytes_recv, StatCounters::q_kbytes_sent, StatCounters::queries_recv, StatCounters::queries_sent, StatCounters::r_kbytes_recv, StatCounters::r_kbytes_sent, RECV, StatCounters::replies_recv, StatCounters::replies_sent, StatCounters::replySvcTime, SENT, and statCounter.
Referenced by icpHandleUdp(), and icpUdpSend().
icpHandleIcpV2()
static void icpHandleIcpV2 (int fd, Ip::Address & from, char * buf, int len) static
Definition at line 561 of file icp_v2.cc.
References DBG_CRITICAL, debugs, doV2Query(), icp_common_t::getOpCode(), icp_common_t::handleReply(), ICP_DECHO, ICP_DENIED, ICP_ERR, ICP_HIT, ICP_INVALID, ICP_MISS, ICP_MISS_NOFETCH, icp_opcode_str, ICP_QUERY, icp_common_t::length, and icp_common_t::opcode.
Referenced by icpHandleUdp().
icpLogIcp()
static void icpLogIcp (const Ip::Address & caddr, const LogTags_ot logcode, int len, const char * url, const int delay, AccessLogEntryPointer & al) static
Definition at line 225 of file icp_v2.cc.
References accessLogLog(), assert, AccessLogEntry::cache, clientdbUpdate(), AccessLogEntry::CacheDetails::code, Config, icpSyncAle(), LOG_ICP_QUERY, LOG_TAG_NONE, SquidConfig::log_udp, SquidConfig::onoff, AnyP::PROTO_ICP, and LogTags::update().
Referenced by icpUdpSend().
icpUdpSendQueue()
static void icpUdpSendQueue (int fd, void *) static
Definition at line 254 of file icp_v2.cc.
References DelayedUdpSend::address, DelayedUdpSend::ale, current_time, IcpQueueHead, icpUdpSend(), DelayedUdpSend::msg, DelayedUdpSend::next, DelayedUdpSend::queue_time, and tvSubUsec().
Referenced by icpUdpSend().
Variable Documentation
icpIncomingConn
Comm::ConnectionPointer icpIncomingConn = nullptr
Definition at line 99 of file icp_v2.cc.
Referenced by comm_poll_udp_incoming(), comm_select_udp_incoming(), fdIsUdpListen(), fdIsUdpListener(), icpConnectionShutdown(), icpOpenPorts(), mcastJoinGroups(), and neighbors_init().
icpOutgoingConn
Comm::ConnectionPointer icpOutgoingConn = nullptr
Definition at line 101 of file icp_v2.cc.
Referenced by icpClosePorts(), icpConnectionShutdown(), icpHandleUdp(), icpIncomingConnectionOpened(), and icpOpenPorts().
IcpQueueHead
DelayedUdpSend* IcpQueueHead = nullptr static
IcpQueueHead is global so comm_incoming() knows whether or not to call icpUdpSendQueue.
Definition at line 94 of file icp_v2.cc.
Referenced by icpUdpSend(), and icpUdpSendQueue().
IcpQueueTail
DelayedUdpSend* IcpQueueTail = nullptr static
Definition at line 96 of file icp_v2.cc.
Referenced by icpUdpSend().