Squid Web Cache: Server-Side SSL Internals
Server-Side SSL Internals
Squid Components » Server-Side Protocols » Server-Side SSL API
Functions
static bool setSerialNumber (ASN1_INTEGER *ai, BIGNUM const *serial)
static void ssl_ask_password (SSL_CTX *context, const char *prompt)
static void ssl_free_CertChain (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
static const char * ssl_get_attribute (X509_NAME *name, const char *attribute_name)
Detailed Description
Function Documentation
setSerialNumber()
static bool setSerialNumber (ASN1_INTEGER * ai, BIGNUM const * serial) static
Set serial random serial number or set random serial number.
Definition at line 125 of file gadgets.cc.
Referenced by generateFakeSslCertificate().
ssl_ask_password()
static void ssl_ask_password (SSL_CTX * context, const char * prompt) static
Definition at line 156 of file support.cc.
References Ssl::AskPasswordCb(), Config, SquidConfig::Program, and SquidConfig::ssl_password.
Referenced by Ssl::InitClientContext().
ssl_free_CertChain()
static void ssl_free_CertChain (void * , void * ptr, CRYPTO_EX_DATA * , int , long , void *) static
Callback handler function to release STACK_OF(X509) "ex" data stored in an SSL object.
Definition at line 713 of file support.cc.
References STACK_OF().
Referenced by Ssl::Initialize().
ssl_get_attribute()
static const char * ssl_get_attribute (X509_NAME * name, const char * attribute_name) static
Definition at line 864 of file support.cc.
References DBG_IMPORTANT, and debugs.