Squid Web Cache: squid/src/HeaderMangling.h File Reference
HeaderMangling.h File Reference
#include "acl/forward.h"
#include "format/Format.h"
#include "http/RegisteredHeaders.h"
#include <functional>
#include <list>
#include <map>
#include <string>
Classes
class headerMangler
class HeaderManglers
A collection of headerMangler objects for a given message kind.
class HeaderManglers::NoCaseLessThan
class HeaderWithAcl
Typedefs
typedef std::list< HeaderWithAcl > HeaderWithAclList
Enumerations
enum req_or_rep_t { ROR_REQUEST , ROR_REPLY }
Functions
void httpHdrMangleList (HttpHeader *, HttpRequest *, const AccessLogEntryPointer &al, req_or_rep_t req_or_rep)
Typedef Documentation
HeaderWithAclList
typedef std::list<HeaderWithAcl> HeaderWithAclList
Definition at line 29 of file HeaderMangling.h.
Enumeration Type Documentation
req_or_rep_t
enum req_or_rep_t
Enumerator
ROR_REQUEST
ROR_REPLY
Definition at line 32 of file HeaderMangling.h.
Function Documentation
httpHdrMangleList()
void httpHdrMangleList (HttpHeader * l, HttpRequest * request, const AccessLogEntryPointer & al, req_or_rep_t req_or_rep)
Mangles headers for a list of headers.
Definition at line 82 of file HeaderMangling.cc.
References Config, HttpHeader::delAt(), HttpHeader::getEntry(), httpHdrAdd(), httpHdrMangle(), HttpHeaderInitPos, HttpHeader::refreshMask(), SquidConfig::reply_header_access, SquidConfig::reply_header_add, SquidConfig::request_header_access, SquidConfig::request_header_add, ROR_REPLY, and ROR_REQUEST.
Referenced by clientReplyContext::buildReplyHeader(), HttpStateData::httpBuildRequestHeader(), and Http::One::Server::writeControlMsgAndCall().