Squid Web Cache: squid/src/helper.h File Reference
helper.h File Reference
#include "base/AsyncCall.h"
#include "base/InstanceId.h"
#include "base/RefCount.h"
#include "cbdata.h"
#include "comm/forward.h"
#include "dlink.h"
#include "helper/ChildConfig.h"
#include "helper/forward.h"
#include "helper/Reply.h"
#include "helper/Request.h"
#include "helper/ReservationId.h"
#include "ip/Address.h"
#include "sbuf/SBuf.h"
#include <list>
#include <map>
#include <queue>
#include <unordered_map>
Classes
class Helper::Xaction
Holds the required data to serve a helper request.
class Helper::Client
struct Helper::Client::_stats
class statefulhelper
class Helper::SessionBase
represents a single helper process
struct Helper::SessionBase::_helper_flags
class Helper::Session
class helper_stateful_server
Namespaces
namespace Helper
helper protocol primitives
Functions
void helperSubmit (const Helper::Client::Pointer &, const char *buf, HLPCB *, void *cbData)
void helperStatefulSubmit (const statefulhelper::Pointer &, const char *buf, HLPCB *, void *cbData, uint64_t reservation)
void helperShutdown (const Helper::Client::Pointer &)
void helperStatefulShutdown (const statefulhelper::Pointer &)
Function Documentation
helperShutdown()
void helperShutdown (const Helper::Client::Pointer & hlp)
Definition at line 770 of file helper.cc.
References assert, Assure, Helper::Client::childs, dlink_node::data, debugs, Helper::Client::dropQueued(), dlink_list::head, Helper::Client::id_name, Helper::ChildConfig::n_active, dlink_node::next, and Helper::Client::servers.
Referenced by external_acl::~external_acl(), externalAclShutdown(), redirectShutdown(), Ssl::Helper::Shutdown(), and Ssl::CertValidationHelper::Shutdown().
helperStatefulShutdown()
void helperStatefulShutdown (const statefulhelper::Pointer & hlp)
Definition at line 809 of file helper.cc.
References assert, Helper::Client::childs, Helper::SessionBase::closePipesSafely(), Helper::SessionBase::_helper_flags::closing, dlink_node::data, debugs, Helper::SessionBase::flags, dlink_list::head, Helper::Client::id_name, Helper::SessionBase::index, Helper::ChildConfig::n_active, dlink_node::next, Helper::SessionBase::pending, helper_stateful_server::reserved(), Helper::Client::servers, Helper::SessionBase::_helper_flags::shutdown, shutting_down, and Helper::SessionBase::stats.
helperStatefulSubmit()
void helperStatefulSubmit (const statefulhelper::Pointer & , const char * buf, HLPCB * , void * cbData, uint64_t reservation)
helperSubmit()
void helperSubmit (const Helper::Client::Pointer & hlp, const char * buf, HLPCB * callback, void * cbData)
Definition at line 481 of file helper.cc.
References SubmissionFailure(), and Helper::Client::trySubmit().
Referenced by constructHelperQuery().