Squid Web Cache: squid/src/htcp.cc File Reference
htcp.cc File Reference
#include "squid.h"
#include "AccessLogEntry.h"
#include "acl/Acl.h"
#include "acl/FilledChecklist.h"
#include "base/AsyncCallbacks.h"
#include "base/RunnersRegistry.h"
#include "CachePeer.h"
#include "CachePeers.h"
#include "comm.h"
#include "comm/Connection.h"
#include "comm/Loops.h"
#include "compat/xalloc.h"
#include "debug/Messages.h"
#include "globals.h"
#include "htcp.h"
#include "http.h"
#include "http/ContentLengthInterpreter.h"
#include "HttpRequest.h"
#include "icmp/net_db.h"
#include "ip/tools.h"
#include "ipc/StartListening.h"
#include "md5.h"
#include "mem/forward.h"
#include "MemBuf.h"
#include "refresh.h"
#include "SquidConfig.h"
#include "StatCounters.h"
#include "Store.h"
#include "store_key_md5.h"
#include "StoreClient.h"
#include "tools.h"
#include <memory>
Classes
struct _Countstr
struct _htcpHeader
struct _htcpDataHeaderSquid
struct _htcpDataHeader
struct _htcpAuthHeader
class htcpSpecifier
class htcpDetail
class htcpStuff
class HtcpRr
Macros
#define N_QUERIED_KEYS 8192
Typedefs
typedef struct _Countstr Countstr
typedef struct _htcpHeader htcpHeader
typedef struct _htcpDataHeader htcpDataHeader
typedef struct _htcpDataHeaderSquid htcpDataHeaderSquid
typedef struct _htcpAuthHeader htcpAuthHeader
Enumerations
enum {
HTCP_NOP , HTCP_TST , HTCP_MON , HTCP_SET ,
HTCP_CLR , HTCP_END
}
enum {
AUTH_REQUIRED , AUTH_FAILURE , OPCODE_UNIMPLEMENTED , MAJOR_VERSION_UNSUPPORTED ,
MINOR_VERSION_UNSUPPORTED , INVALID_OPCODE
}
enum { RR_REQUEST , RR_RESPONSE }
Functions
static void htcpIncomingConnectionOpened (Ipc::StartListeningAnswer &)
static ssize_t htcpBuildPacket (char *buf, size_t buflen, htcpStuff *stuff)
static htcpDetail * htcpUnpackDetail (char *buf, int sz)
static ssize_t htcpBuildAuth (char *buf, size_t buflen)
static ssize_t htcpBuildCountstr (char *buf, size_t buflen, const char *s, size_t len)
static ssize_t htcpBuildData (char *buf, size_t buflen, htcpStuff *stuff)
static ssize_t htcpBuildDetail (char *buf, size_t buflen, htcpStuff *stuff)
static ssize_t htcpBuildOpData (char *buf, size_t buflen, htcpStuff *stuff)
static ssize_t htcpBuildSpecifier (char *buf, size_t buflen, htcpStuff *stuff)
static ssize_t htcpBuildTstOpData (char *buf, size_t buflen, htcpStuff *stuff)
static void htcpHandleMsg (char *buf, int sz, Ip::Address &from)
static void htcpLogHtcp (Ip::Address &, const int, const LogTags_ot, const char *, AccessLogEntryPointer)
static void htcpHandleTst (htcpDataHeader *, char *buf, int sz, Ip::Address &from)
static void htcpRecv (int fd, void *data)
static void htcpSend (const char *buf, int len, Ip::Address &to)
static void htcpTstReply (htcpDataHeader *, StoreEntry *, htcpSpecifier *, Ip::Address &)
static void htcpHandleTstRequest (htcpDataHeader *, char *buf, int sz, Ip::Address &from)
static void htcpHandleTstResponse (htcpDataHeader *, char *, int, Ip::Address &)
static void htcpSyncAle (AccessLogEntryPointer &al, const Ip::Address &caddr, const int opcode, const char *url)
static void htcpHexdump (const char *tag, const char *s, int sz)
static bool parseUint16 (const char *const buf, const int sz, uint16_t &out, const char *const field)
static ssize_t htcpBuildClrOpData (char *buf, size_t buflen, htcpStuff *stuff)
static htcpSpecifier::Pointer htcpUnpackSpecifier (char *buf, int sz)
static bool htcpAccessAllowed (acl_access *acl, const htcpSpecifier::Pointer &s, Ip::Address &from)
static void htcpClrReply (htcpDataHeader *dhdr, int purgeSucceeded, Ip::Address &from)
static void htcpClrStoreEntry (StoreEntry *e)
static int htcpClrStore (const htcpSpecifier::Pointer &s)
static void htcpHandleClr (htcpDataHeader *const hdr, char *const buf, const int sz, Ip::Address &from)
static void htcpOpenPorts ()
int htcpQuery (StoreEntry *e, HttpRequest *req, CachePeer *p)
void htcpClear (StoreEntry *e, HttpRequest *req, const HttpRequestMethod &, CachePeer *p, htcp_clr_reason reason)
static void htcpSocketShutdown ()
static void htcpClosePorts ()
DefineRunnerRegistrator (HtcpRr)
Variables
static const char *const htcpOpcodeStr []
static uint32_t msg_id_counter = 0
static Comm::ConnectionPointer htcpOutgoingConn = nullptr
static Comm::ConnectionPointer htcpIncomingConn = nullptr
static uint32_t queried_id [N_QUERIED_KEYS]
static cache_key queried_keys [N_QUERIED_KEYS][SQUID_MD5_DIGEST_LENGTH]
static Ip::Address queried_addr [N_QUERIED_KEYS]
static int old_squid_format = 0
Macro Definition Documentation
N_QUERIED_KEYS
#define N_QUERIED_KEYS 8192
Definition at line 244 of file htcp.cc.
Typedef Documentation
Countstr
typedef struct _Countstr Countstr
Definition at line 44 of file htcp.cc.
htcpAuthHeader
typedef struct _htcpAuthHeader htcpAuthHeader
Definition at line 52 of file htcp.cc.
htcpDataHeader
typedef struct _htcpDataHeader htcpDataHeader
Definition at line 48 of file htcp.cc.
htcpDataHeaderSquid
typedef struct _htcpDataHeaderSquid htcpDataHeaderSquid
Definition at line 50 of file htcp.cc.
htcpHeader
typedef struct _htcpHeader htcpHeader
Definition at line 46 of file htcp.cc.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HTCP_NOP
HTCP_TST
HTCP_MON
HTCP_SET
HTCP_CLR
HTCP_END
Definition at line 201 of file htcp.cc.
anonymous enum
anonymous enum
Enumerator
AUTH_REQUIRED
AUTH_FAILURE
OPCODE_UNIMPLEMENTED
MAJOR_VERSION_UNSUPPORTED
MINOR_VERSION_UNSUPPORTED
INVALID_OPCODE
Definition at line 222 of file htcp.cc.
anonymous enum
anonymous enum
Enumerator
RR_REQUEST
RR_RESPONSE
Definition at line 234 of file htcp.cc.
Function Documentation
DefineRunnerRegistrator()
DefineRunnerRegistrator (HtcpRr)
htcpAccessAllowed()
static bool htcpAccessAllowed (acl_access * acl, const htcpSpecifier::Pointer & s, Ip::Address & from) static
Definition at line 832 of file htcp.cc.
References Acl::Answer::allowed(), ACLChecklist::fastCheck(), RefCount< C >::getRaw(), ACLFilledChecklist::my_addr, Ip::Address::setNoAddr(), and ACLFilledChecklist::src_addr.
Referenced by htcpHandleClr(), and htcpHandleTstRequest().
htcpBuildAuth()
static ssize_t htcpBuildAuth (char * buf, size_t buflen) static
Definition at line 336 of file htcp.cc.
References assert, and _htcpAuthHeader::length.
Referenced by htcpBuildPacket().
htcpBuildClrOpData()
static ssize_t htcpBuildClrOpData (char * buf, size_t buflen, htcpStuff * stuff) static
Definition at line 471 of file htcp.cc.
References debugs, fatal_dump(), htcpBuildSpecifier(), htcpStuff::reason, htcpStuff::rr, RR_REQUEST, and RR_RESPONSE.
Referenced by htcpBuildOpData().
htcpBuildCountstr()
static ssize_t htcpBuildCountstr (char * buf, size_t buflen, const char * s, size_t len) static
Definition at line 350 of file htcp.cc.
References debugs, and off.
Referenced by htcpBuildDetail(), and htcpBuildSpecifier().
htcpBuildData()
static ssize_t htcpBuildData (char * buf, size_t buflen, htcpStuff * stuff) static
Definition at line 522 of file htcp.cc.
References debugs, _htcpDataHeaderSquid::F1, _htcpDataHeader::F1, htcpStuff::f1, htcpBuildOpData(), _htcpDataHeaderSquid::length, _htcpDataHeader::length, _htcpDataHeader::msg_id, htcpStuff::msg_id, off, old_squid_format, htcpStuff::op, _htcpDataHeaderSquid::opcode, _htcpDataHeader::opcode, _htcpDataHeaderSquid::response, _htcpDataHeader::response, htcpStuff::response, _htcpDataHeaderSquid::RR, _htcpDataHeader::RR, and htcpStuff::rr.
Referenced by htcpBuildPacket().
htcpBuildDetail()
static ssize_t htcpBuildDetail (char * buf, size_t buflen, htcpStuff * stuff) static
Definition at line 417 of file htcp.cc.
References htcpDetail::cache_hdrs, htcpDetail::cacheHdrsSz, htcpStuff::D, htcpDetail::entity_hdrs, htcpDetail::entityHdrsSz, htcpBuildCountstr(), off, htcpDetail::resp_hdrs, and htcpDetail::respHdrsSz.
Referenced by htcpBuildTstOpData().
htcpBuildOpData()
static ssize_t htcpBuildOpData (char * buf, size_t buflen, htcpStuff * stuff) static
Definition at line 498 of file htcp.cc.
References assert, debugs, HTCP_CLR, HTCP_TST, htcpBuildClrOpData(), htcpBuildTstOpData(), htcpOpcodeStr, off, and htcpStuff::op.
Referenced by htcpBuildData().
htcpBuildPacket()
static ssize_t htcpBuildPacket (char * buf, size_t buflen, htcpStuff * stuff) static
Definition at line 574 of file htcp.cc.
References debugs, htcpBuildAuth(), htcpBuildData(), _htcpHeader::length, _htcpHeader::major, _htcpHeader::minor, off, and old_squid_format.
Referenced by htcpClear(), htcpClrReply(), htcpQuery(), and htcpTstReply().
htcpBuildSpecifier()
static ssize_t htcpBuildSpecifier (char * buf, size_t buflen, htcpStuff * stuff) static
Definition at line 379 of file htcp.cc.
References debugs, htcpBuildCountstr(), htcpSpecifier::method, off, htcpSpecifier::req_hdrs, htcpSpecifier::reqHdrsSz, htcpStuff::S, htcpSpecifier::uri, and htcpSpecifier::version.
Referenced by htcpBuildClrOpData(), and htcpBuildTstOpData().
htcpBuildTstOpData()
static ssize_t htcpBuildTstOpData (char * buf, size_t buflen, htcpStuff * stuff) static
Definition at line 446 of file htcp.cc.
References debugs, htcpStuff::f1, fatal_dump(), htcpBuildDetail(), htcpBuildSpecifier(), htcpStuff::rr, RR_REQUEST, and RR_RESPONSE.
Referenced by htcpBuildOpData().
htcpClear()
void htcpClear (StoreEntry * e, HttpRequest * req, const HttpRequestMethod & method, CachePeer * p, htcp_clr_reason reason)
Definition at line 1607 of file htcp.cc.
References MemBuf::buf, SBuf::c_str(), HttpHeader::clean(), MemBuf::clean(), debugs, HttpRequest::effectiveRequestUri(), hoRequest, HTCP_CLR, HTCP_CLR_INVALIDATION, CachePeer::htcp_oldsquid, htcpBuildPacket(), htcpIncomingConn, htcpSend(), Http::Message::http_ver, HttpStateData::httpBuildRequestHeader(), HttpRequestMethod::image(), CachePeer::in_addr, MemBuf::init(), Comm::IsConnOpen(), AnyP::ProtocolVersion::major, htcpSpecifier::method, HttpRequest::method, AnyP::ProtocolVersion::minor, msg_id_counter, old_squid_format, CachePeer::options, HttpHeader::packInto(), htcpStuff::reason, htcpSpecifier::req_hdrs, htcpSpecifier::request, RR_REQUEST, htcpStuff::S, htcpSpecifier::uri, and htcpSpecifier::version.
Referenced by neighborsHtcpClear().
htcpClosePorts()
static void htcpClosePorts () static
Definition at line 1688 of file htcp.cc.
References DBG_IMPORTANT, debugs, htcpOutgoingConn, htcpSocketShutdown(), IamWorkerProcess(), and Comm::Connection::local.
Referenced by HtcpRr::startReconfigure(), and HtcpRr::startShutdown().
htcpClrReply()
static void htcpClrReply (htcpDataHeader * dhdr, int purgeSucceeded, Ip::Address & from) static
Definition at line 934 of file htcp.cc.
References debugs, _htcpDataHeader::F1, HTCP_CLR, htcpBuildPacket(), htcpSend(), _htcpDataHeader::msg_id, htcpStuff::response, and RR_RESPONSE.
Referenced by htcpHandleClr().
htcpClrStore()
static int htcpClrStore (const htcpSpecifier::Pointer & s) static
Definition at line 1058 of file htcp.cc.
References debugs, RefCount< C >::getRaw(), htcpClrStoreEntry(), HttpRequest::parseHeader(), and storeGetPublicByRequest().
Referenced by htcpHandleClr().
htcpClrStoreEntry()
static void htcpClrStoreEntry (StoreEntry * e) static
Definition at line 1051 of file htcp.cc.
References debugs, StoreEntry::releaseRequest(), and StoreEntry::url().
Referenced by htcpClrStore().
htcpHandleClr()
static void htcpHandleClr (htcpDataHeader *const hdr, char *const buf, const int sz, Ip::Address & from) static
Definition at line 1239 of file htcp.cc.
References SquidConfig::accessList, Config, CurrentCachePeers(), dash_str, debugs, SquidConfig::htcp_clr, htcpAccessAllowed(), htcpClrReply(), htcpClrStore(), htcpLogHtcp(), htcpSend(), htcpUnpackSpecifier(), LOG_UDP_DENIED, LOG_UDP_HIT, LOG_UDP_INVALID, LOG_UDP_MISS, and _htcpDataHeader::opcode.
Referenced by htcpHandleMsg().
htcpHandleMsg()
static void htcpHandleMsg (char * buf, int sz, Ip::Address & from) static
Definition at line 1329 of file htcp.cc.
References debugs, _htcpDataHeaderSquid::F1, _htcpDataHeader::F1, HTCP_CLR, HTCP_END, HTCP_MON, HTCP_NOP, HTCP_SET, HTCP_TST, htcpHandleClr(), htcpHandleTst(), htcpHexdump(), htcpOpcodeStr, int, _htcpHeader::length, _htcpDataHeaderSquid::length, _htcpDataHeader::length, _htcpHeader::major, _htcpHeader::minor, _htcpDataHeaderSquid::msg_id, _htcpDataHeader::msg_id, old_squid_format, _htcpDataHeaderSquid::opcode, _htcpDataHeader::opcode, _htcpDataHeader::reserved, _htcpDataHeaderSquid::response, _htcpDataHeader::response, _htcpDataHeaderSquid::RR, and _htcpDataHeader::RR.
Referenced by htcpRecv().
htcpHandleTst()
static void htcpHandleTst (htcpDataHeader * hdr, char * buf, int sz, Ip::Address & from) static
Definition at line 1091 of file htcp.cc.
References debugs, htcpHandleTstRequest(), htcpHandleTstResponse(), _htcpDataHeader::RR, and RR_REQUEST.
Referenced by htcpHandleMsg().
htcpHandleTstRequest()
static void htcpHandleTstRequest (htcpDataHeader * dhdr, char * buf, int sz, Ip::Address & from) static
Definition at line 1187 of file htcp.cc.
References SquidConfig::accessList, Config, dash_str, debugs, _htcpDataHeader::F1, SquidConfig::htcp, htcpAccessAllowed(), htcpLogHtcp(), htcpUnpackSpecifier(), LOG_UDP_DENIED, LOG_UDP_INVALID, and _htcpDataHeader::opcode.
Referenced by htcpHandleTst().
htcpHandleTstResponse()
static void htcpHandleTstResponse (htcpDataHeader * hdr, char * buf, int sz, Ip::Address & from) static
Definition at line 1117 of file htcp.cc.
References htcpDetail::cache_hdrs, htcpDetail::cacheHdrsSz, HttpHeader::clean(), debugs, htcpDetail::entity_hdrs, htcpDetail::entityHdrsSz, _htcpDataHeader::F1, HtcpReplyData::hdr, HtcpReplyData::hit, htcpUnpackDetail(), _htcpDataHeader::msg_id, HtcpReplyData::msg_id, N_QUERIED_KEYS, neighborsHtcpReply(), HtcpReplyData::parseHeader(), Ip::Address::port(), queried_addr, queried_id, queried_keys, htcpDetail::resp_hdrs, htcpDetail::respHdrsSz, _htcpDataHeader::response, and storeKeyText().
Referenced by htcpHandleTst().
htcpHexdump()
static void htcpHexdump (const char * tag, const char * s, int sz) static
Definition at line 293 of file htcp.cc.
References debugs.
Referenced by htcpHandleMsg(), and htcpSend().
htcpIncomingConnectionOpened()
static void htcpIncomingConnectionOpened (Ipc::StartListeningAnswer & answer) static
Definition at line 1540 of file htcp.cc.
References SquidConfig::Addrs, COMM_SELECT_READ, Config, Ipc::StartListeningAnswer::conn, DBG_CRITICAL, DBG_IMPORTANT, debugs, fatal(), htcpOutgoingConn, htcpRecv(), Comm::IsConnOpen(), Ip::Address::isNoAddr(), Comm::Connection::local, Comm::SetSelect(), and SquidConfig::udp_outgoing.
Referenced by htcpOpenPorts().
htcpLogHtcp()
static void htcpLogHtcp (Ip::Address & caddr, const int opcode, const LogTags_ot logcode, const char * url, AccessLogEntryPointer al) static
Definition at line 1712 of file htcp.cc.
References accessLogLog(), assert, AccessLogEntry::cache, AccessLogEntry::CacheDetails::code, Config, htcpSyncAle(), LOG_TAG_NONE, SquidConfig::log_udp, SquidConfig::onoff, and LogTags::update().
Referenced by htcpSpecifier::checkedHit(), htcpHandleClr(), and htcpHandleTstRequest().
htcpOpenPorts()
static void htcpOpenPorts () static
Definition at line 1482 of file htcp.cc.
References SquidConfig::Addrs, asyncCallbackFun, comm_open_listener(), COMM_SELECT_READ, Config, DBG_CRITICAL, DBG_IMPORTANT, debugs, enter_suid(), fatal(), Comm::Connection::fd, Ipc::fdnInHtcpSocket, SquidConfig::htcp, htcpIncomingConn, htcpIncomingConnectionOpened(), htcpOutgoingConn, htcpRecv(), IamWorkerProcess(), Important, IPV6_SPECIAL_SPLITSTACK, Ip::Address::isAnyAddr(), Comm::IsConnOpen(), Ip::Address::isNoAddr(), leave_suid(), Comm::Connection::local, Ip::Address::port(), SquidConfig::Port, Ip::Address::setIPv4(), Comm::SetSelect(), Ipc::StartListening(), SquidConfig::udp_incoming, and SquidConfig::udp_outgoing.
Referenced by HtcpRr::syncConfig(), and HtcpRr::useConfig().
htcpQuery()
int htcpQuery (StoreEntry * e, HttpRequest * req, CachePeer * p)
Generate and Send an HTCP query to the specified peer.
Parameters
e
req
p
Return values
1 Successfully sent request.
0 Unable to send request at this time. HTCP may be shutting down or starting up. Don't wait for a reply or count in stats as sent.
-1 Error sending request.
Definition at line 1558 of file htcp.cc.
References MemBuf::buf, SBuf::c_str(), HttpHeader::clean(), MemBuf::clean(), debugs, hoRequest, CachePeer::htcp_oldsquid, HTCP_TST, htcpBuildPacket(), htcpIncomingConn, htcpSend(), Http::Message::http_ver, HttpStateData::httpBuildRequestHeader(), HttpRequestMethod::image(), CachePeer::in_addr, MemBuf::init(), Comm::IsConnOpen(), hash_link::key, AnyP::ProtocolVersion::major, htcpSpecifier::method, HttpRequest::method, AnyP::ProtocolVersion::minor, htcpStuff::msg_id, msg_id_counter, N_QUERIED_KEYS, old_squid_format, CachePeer::options, HttpHeader::packInto(), queried_addr, queried_id, queried_keys, htcpSpecifier::req_hdrs, RR_REQUEST, htcpStuff::S, storeKeyCopy(), storeKeyText(), htcpSpecifier::uri, StoreEntry::url(), and htcpSpecifier::version.
Referenced by neighborsUdpPing().
htcpRecv()
static void htcpRecv (int fd, void * data) static
Definition at line 1461 of file htcp.cc.
References COMM_SELECT_READ, comm_udp_recvfrom(), debugs, StatCounters::htcp, htcpHandleMsg(), htcpRecv(), StatCounters::pkts_recv, Comm::SetSelect(), and statCounter.
Referenced by htcpIncomingConnectionOpened(), htcpOpenPorts(), and htcpRecv().
htcpSend()
static void htcpSend (const char * buf, int len, Ip::Address & to) static
Definition at line 617 of file htcp.cc.
References comm_udp_sendto(), debugs, Comm::Connection::fd, StatCounters::htcp, htcpHexdump(), htcpOutgoingConn, StatCounters::pkts_sent, statCounter, and xstrerr().
Referenced by htcpClear(), htcpClrReply(), htcpHandleClr(), htcpQuery(), and htcpTstReply().
htcpSocketShutdown()
static void htcpSocketShutdown () static
Definition at line 1659 of file htcp.cc.
References assert, COMM_SELECT_READ, DBG_IMPORTANT, debugs, Comm::Connection::fd, htcpIncomingConn, htcpOutgoingConn, Comm::IsConnOpen(), Comm::Connection::local, and Comm::SetSelect().
Referenced by htcpClosePorts().
htcpSyncAle()
static void htcpSyncAle (AccessLogEntryPointer & al, const Ip::Address & caddr, const int opcode, const char * url) static
Definition at line 278 of file htcp.cc.
References AccessLogEntry::cache, AccessLogEntry::CacheDetails::caddr, current_time, AccessLogEntry::htcp, htcpOpcodeStr, AccessLogEntry::HtcpDetails::opcode, AccessLogEntry::setVirginUrlForMissingRequest(), AccessLogEntry::CacheDetails::start_time, AccessLogEntry::CacheDetails::trTime, and AccessLogEntry::url.
Referenced by htcpSpecifier::fillChecklist(), and htcpLogHtcp().
htcpTstReply()
static void htcpTstReply (htcpDataHeader * dhdr, StoreEntry * e, htcpSpecifier * spec, Ip::Address & from) static
Definition at line 845 of file htcp.cc.
References Http::AGE, MemBuf::buf, htcpDetail::cache_hdrs, htcpDetail::cacheHdrsSz, HttpHeader::clean(), MemBuf::clean(), MemBuf::contentSize(), htcpStuff::D, debugs, htcpDetail::entity_hdrs, htcpDetail::entityHdrsSz, Http::EXPIRES, StoreEntry::expires, hoHtcpReply, AnyP::Uri::host(), HTCP_TST, htcpBuildPacket(), htcpSend(), MemBuf::init(), Http::LAST_MODIFIED, StoreEntry::lastModified(), htcpSpecifier::method, _htcpDataHeader::msg_id, netdbHostData(), HttpHeader::packInto(), HttpHeader::putExt(), HttpHeader::putInt(), HttpHeader::putTime(), htcpSpecifier::req_hdrs, htcpSpecifier::reqHdrsSz, htcpSpecifier::request, MemBuf::reset(), htcpDetail::resp_hdrs, htcpDetail::respHdrsSz, htcpStuff::response, RR_RESPONSE, htcpStuff::S, safe_free, squid_curtime, SQUIDHOSTNAMELEN, StoreEntry::timestamp, htcpSpecifier::uri, HttpRequest::url, htcpSpecifier::version, and xstrdup.
Referenced by htcpSpecifier::checkedHit().
htcpUnpackDetail()
static htcpDetail * htcpUnpackDetail (char * buf, int sz) static
Definition at line 752 of file htcp.cc.
References debugs, and parseUint16().
Referenced by htcpHandleTstResponse().
htcpUnpackSpecifier()
static htcpSpecifier::Pointer htcpUnpackSpecifier (char * buf, int sz) static
Definition at line 636 of file htcp.cc.
References debugs, HttpRequest::FromUrlXXX(), HttpRequestMethod::HttpRequestMethodXXX(), Http::METHOD_GET, Http::METHOD_NONE, and parseUint16().
Referenced by htcpHandleClr(), and htcpHandleTstRequest().
parseUint16()
static bool parseUint16 (const char *const buf, const int sz, uint16_t & out, const char *const field) static
Definition at line 319 of file htcp.cc.
References debugs.
Referenced by htcpUnpackDetail(), and htcpUnpackSpecifier().
Variable Documentation
htcpIncomingConn
Comm::ConnectionPointer htcpIncomingConn = nullptr static
Definition at line 243 of file htcp.cc.
Referenced by htcpClear(), htcpOpenPorts(), htcpQuery(), and htcpSocketShutdown().
htcpOpcodeStr
const char* const htcpOpcodeStr[] static
Initial value:
= {
    "HTCP_NOP",
    "HTCP_TST",
    "HTCP_MON",
    "HTCP_SET",
    "HTCP_CLR",
    "HTCP_END"
}
Definition at line 210 of file htcp.cc.
Referenced by htcpBuildOpData(), htcpHandleMsg(), and htcpSyncAle().
htcpOutgoingConn
Comm::ConnectionPointer htcpOutgoingConn = nullptr static
Definition at line 242 of file htcp.cc.
Referenced by htcpClosePorts(), htcpIncomingConnectionOpened(), htcpOpenPorts(), htcpSend(), and htcpSocketShutdown().
msg_id_counter
uint32_t msg_id_counter = 0 static
Definition at line 240 of file htcp.cc.
Referenced by htcpClear(), and htcpQuery().
old_squid_format
int old_squid_format = 0 static
Definition at line 250 of file htcp.cc.
Referenced by htcpBuildData(), htcpBuildPacket(), htcpClear(), htcpHandleMsg(), and htcpQuery().
queried_addr
Ip::Address queried_addr[N_QUERIED_KEYS] static
Definition at line 248 of file htcp.cc.
Referenced by htcpHandleTstResponse(), and htcpQuery().
queried_id
uint32_t queried_id[N_QUERIED_KEYS] static
Definition at line 245 of file htcp.cc.
Referenced by htcpHandleTstResponse(), and htcpQuery().
queried_keys
cache_key queried_keys[N_QUERIED_KEYS][SQUID_MD5_DIGEST_LENGTH] static
Definition at line 246 of file htcp.cc.
Referenced by htcpHandleTstResponse(), and htcpQuery().