Squid Web Cache: squid/src/http/url_rewriters/fake/fake.cc File Reference
fake.cc File Reference
#include "squid.h"
#include "helper/protocol_defines.h"
#include <cstring>
Functions
static void usage (void)
static void process_options (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
char * my_program_name = nullptr
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 95 of file fake.cc.
References debug(), HELPER_INPUT_BUFFER, my_program_name, PRId64, process_options(), SQUID_BUILD_INFO, strtoll(), and VERSION.
process_options()
static void process_options (int argc, char * argv[]) static
Definition at line 68 of file fake.cc.
References debug_enabled, getopt(), opterr, optopt, and usage().
usage()
static void usage (void) static
Definition at line 58 of file fake.cc.
References my_program_name.
Variable Documentation
my_program_name
char* my_program_name = nullptr
options: -d enable debugging. -h interface help.
Definition at line 55 of file fake.cc.
Referenced by main(), and usage().