Squid Web Cache: squid/src/HttpHdrSc.cc File Reference
HttpHdrSc.cc File Reference
#include "squid.h"
#include "base/LookupTable.h"
#include "HttpHdrScTarget.h"
#include "HttpHeader.h"
#include "HttpHeaderFieldStat.h"
#include "HttpHeaderStat.h"
#include "HttpHeaderTools.h"
#include "Store.h"
#include "StrList.h"
#include "util.h"
#include <map>
#include <vector>
Functions
http_hdr_sc_type & operator++ (http_hdr_sc_type &aHeader)
void httpHdrScInitModule (void)
HttpHdrSc * httpHdrScParseCreate (const String &str)
void httpHdrScTargetStatDumper (StoreEntry *sentry, int, double val, double, int count)
void httpHdrScStatDumper (StoreEntry *sentry, int, double val, double, int count)
Variables
static const LookupTable< http_hdr_sc_type >::Record ScAttrs []
LookupTable< http_hdr_sc_type > scLookupTable (SC_ENUM_END, ScAttrs)
Function Documentation
httpHdrScInitModule()
void httpHdrScInitModule (void)
Definition at line 48 of file HttpHdrSc.cc.
References assert, and ScAttrs.
Referenced by httpHeaderInitModule().
httpHdrScParseCreate()
HttpHdrSc * httpHdrScParseCreate (const String & str)
Definition at line 59 of file HttpHdrSc.cc.
References HttpHdrSc::parse().
Referenced by HttpHeader::getSc().
httpHdrScStatDumper()
void httpHdrScStatDumper (StoreEntry * sentry, int idx, double val, double size, int count)
Definition at line 266 of file HttpHdrSc.cc.
References dump_stat, int, SC_ENUM_END, ScAttrs, HttpHeaderStat::scParsedCount, storeAppendPrintf(), and xdiv().
Referenced by httpHeaderStatDump().
httpHdrScTargetStatDumper()
void httpHdrScTargetStatDumper (StoreEntry * sentry, int idx, double val, double size, int count)
Definition at line 253 of file HttpHdrSc.cc.
References dump_stat, int, SC_ENUM_END, ScAttrs, HttpHeaderStat::scParsedCount, storeAppendPrintf(), and xdiv().
operator++()
http_hdr_sc_type & operator++ (http_hdr_sc_type & aHeader)
Definition at line 40 of file HttpHdrSc.cc.
Variable Documentation
ScAttrs
const LookupTable<http_hdr_sc_type>::Record ScAttrs[] static
Initial value:
{
    {"no-store", SC_NO_STORE},
    {"no-store-remote", SC_NO_STORE_REMOTE},
    {"max-age", SC_MAX_AGE},
    {"content", SC_CONTENT},
    {"Other,", SC_OTHER},
    {nullptr, SC_ENUM_END}
}
Definition at line 29 of file HttpHdrSc.cc.
Referenced by httpHdrScInitModule(), httpHdrScStatDumper(), httpHdrScTargetStatDumper(), and HttpHdrScTarget::packInto().
scLookupTable
LookupTable< http_hdr_sc_type > scLookupTable(SC_ENUM_END, ScAttrs) (SC_ENUM_END , ScAttrs)
Referenced by HttpHdrSc::parse().