Squid Web Cache: squid/src/acl/HttpStatus.cc File Reference
HttpStatus.cc File Reference
#include "squid.h"
#include "acl/FilledChecklist.h"
#include "acl/HttpStatus.h"
#include "acl/SplayInserter.h"
#include "debug/Stream.h"
#include "HttpReply.h"
#include <algorithm>
#include <climits>
Classes
struct HttpStatusAclDumpVisitor
Functions
static void aclParseHTTPStatusList (Splay< acl_httpstatus_data * > **curlist)
static int aclHTTPStatusCompare (acl_httpstatus_data *const &a, acl_httpstatus_data *const &b)
static int aclMatchHTTPStatus (Splay< acl_httpstatus_data * > **dataptr, Http::StatusCode status)
static std::ostream & operator<< (std::ostream &os, const acl_httpstatus_data *status)
reports acl_httpstatus_data using squid.conf http_status ACL value format
static acl_httpstatus_data * aclParseHTTPStatusData (const char *t)
Function Documentation
aclHTTPStatusCompare()
static int aclHTTPStatusCompare (acl_httpstatus_data *const & a, acl_httpstatus_data *const & b) static
Definition at line 148 of file HttpStatus.cc.
References acl_httpstatus_data::status1, and acl_httpstatus_data::status2.
Referenced by aclMatchHTTPStatus(), and Acl::SplayInserter< DataValue >::Compare().
aclMatchHTTPStatus()
int aclMatchHTTPStatus (Splay< acl_httpstatus_data * > ** dataptr, Http::StatusCode status) static
Definition at line 138 of file HttpStatus.cc.
References aclHTTPStatusCompare(), and debugs.
Referenced by ACLHTTPStatus::match().
aclParseHTTPStatusData()
static acl_httpstatus_data * aclParseHTTPStatusData (const char * t) static
Definition at line 98 of file HttpStatus.cc.
References INT_MAX.
Referenced by aclParseHTTPStatusList().
aclParseHTTPStatusList()
void aclParseHTTPStatusList (Splay< acl_httpstatus_data * > ** curlist) static
Definition at line 123 of file HttpStatus.cc.
References aclParseHTTPStatusData(), Acl::SplayInserter< DataValue >::Merge(), and ConfigParser::strtokFile().
Referenced by ACLHTTPStatus::parse().
operator<<()
static std::ostream & operator<< (std::ostream & os, const acl_httpstatus_data * status) static
Definition at line 66 of file HttpStatus.cc.
References acl_httpstatus_data::toStr().