Squid Web Cache: squid/src/HttpHdrSc.h File Reference
HttpHdrSc.h File Reference
#include "http/forward.h"
#include "HttpHdrScTarget.h"
#include "mem/PoolingAllocator.h"
#include "SquidString.h"
#include <list>
Classes
class HttpHdrSc
Functions
void httpHdrScStatDumper (StoreEntry *sentry, int idx, double val, double size, int count)
void httpHdrScInitModule (void)
HttpHdrSc * httpHdrScParseCreate (String const &)
void httpHdrScSetMaxAge (HttpHdrSc *, char const *, int)
http_hdr_sc_type & operator++ (http_hdr_sc_type &)
Function Documentation
httpHdrScInitModule()
void httpHdrScInitModule (void)
Definition at line 48 of file HttpHdrSc.cc.
References assert, and ScAttrs.
Referenced by httpHeaderInitModule().
httpHdrScParseCreate()
HttpHdrSc * httpHdrScParseCreate (String const & str)
Definition at line 59 of file HttpHdrSc.cc.
References HttpHdrSc::parse().
Referenced by HttpHeader::getSc().
httpHdrScSetMaxAge()
void httpHdrScSetMaxAge (HttpHdrSc * , char const * , int)
httpHdrScStatDumper()
void httpHdrScStatDumper (StoreEntry * sentry, int idx, double val, double size, int count)
Definition at line 266 of file HttpHdrSc.cc.
References dump_stat, int, SC_ENUM_END, ScAttrs, HttpHeaderStat::scParsedCount, storeAppendPrintf(), and xdiv().
Referenced by httpHeaderStatDump().
operator++()
http_hdr_sc_type & operator++ (http_hdr_sc_type & aHeader)
Definition at line 40 of file HttpHdrSc.cc.