Squid Web Cache: squid/src/HttpRequest.cc File Reference
HttpRequest.cc File Reference
#include "squid.h"
#include "AccessLogEntry.h"
#include "acl/AclSizeLimit.h"
#include "acl/FilledChecklist.h"
#include "CachePeer.h"
#include "client_side.h"
#include "client_side_request.h"
#include "dns/LookupDetails.h"
#include "Downloader.h"
#include "error/Detail.h"
#include "globals.h"
#include "http.h"
#include "http/ContentLengthInterpreter.h"
#include "http/one/RequestParser.h"
#include "http/Stream.h"
#include "HttpHdrCc.h"
#include "HttpHeaderRange.h"
#include "HttpRequest.h"
#include "log/Config.h"
#include "MemBuf.h"
#include "sbuf/StringConvert.h"
#include "SquidConfig.h"
#include "Store.h"
#include "auth/UserRequest.h"
#include "adaptation/icap/icap_log.h"
Functions
void httpRequestPack (void *obj, Packable *p)
void UpdateRequestNotes (ConnStateData *csd, HttpRequest &request, NotePairs const &helperNotes)
template<typename Filter >
static const Ip::Address * FindGoodListeningPortAddressInPort (const AnyP::PortCfgPointer &port, const Filter isGood)
a helper for handling PortCfg cases of FindListeningPortAddress()
template<typename Filter >
static const Ip::Address * FindGoodListeningPortAddressInConn (const Comm::ConnectionPointer &conn, const Filter isGood)
a helper for handling Connection cases of FindListeningPortAddress()
template<typename Filter >
const Ip::Address * FindGoodListeningPortAddress (const HttpRequest *callerRequest, const AccessLogEntry *ale, const Filter filter)
const Ip::Address * FindListeningPortAddress (const HttpRequest *callerRequest, const AccessLogEntry *ale)
AnyP::Port FindListeningPortNumber (const HttpRequest *callerRequest, const AccessLogEntry *ale)
Function Documentation
FindGoodListeningPortAddress()
template<typename Filter > const Ip::Address * FindGoodListeningPortAddress (const HttpRequest * callerRequest, const AccessLogEntry * ale, const Filter filter)
Definition at line 833 of file HttpRequest.cc.
References AccessLogEntry::cache, FindGoodListeningPortAddressInConn(), FindGoodListeningPortAddressInPort(), HttpRequest::flags, RequestFlags::intercepted, RequestFlags::interceptTproxy, HttpRequest::masterXaction, AccessLogEntry::CacheDetails::port, AccessLogEntry::request, MasterXaction::squidPort, AccessLogEntry::tcpClient, and MasterXaction::tcpClient.
Referenced by FindListeningPortAddress(), and FindListeningPortNumber().
FindGoodListeningPortAddressInConn()
template<typename Filter > static const Ip::Address * FindGoodListeningPortAddressInConn (const Comm::ConnectionPointer & conn, const Filter isGood) static
Definition at line 826 of file HttpRequest.cc.
References Comm::Connection::local.
Referenced by FindGoodListeningPortAddress().
FindGoodListeningPortAddressInPort()
template<typename Filter > static const Ip::Address * FindGoodListeningPortAddressInPort (const AnyP::PortCfgPointer & port, const Filter isGood) static
Definition at line 818 of file HttpRequest.cc.
References port.
Referenced by FindGoodListeningPortAddress().
FindListeningPortAddress()
const Ip::Address * FindListeningPortAddress (const HttpRequest * callerRequest, const AccessLogEntry * ale)
Returns
listening/*_port address used by the client connection (or nil) nil parameter(s) indicate missing caller information and are handled safely
Definition at line 860 of file HttpRequest.cc.
References FindGoodListeningPortAddress(), and Ip::Address::isAnyAddr().
Referenced by Format::Format::assemble(), and ErrorState::compileLegacyCode().
FindListeningPortNumber()
AnyP::Port FindListeningPortNumber (const HttpRequest * callerRequest, const AccessLogEntry * ale)
Returns
listening/*_port port number used by the client connection (or nothing) nil parameter(s) indicate missing caller information and are handled safely
Definition at line 869 of file HttpRequest.cc.
References Assure, FindGoodListeningPortAddress(), and Ip::Address::port().
Referenced by Format::Format::assemble().
httpRequestPack()
void httpRequestPack (void * obj, Packable * p)
Definition at line 358 of file HttpRequest.cc.
References HttpRequest::pack().
Referenced by clientInterpretRequestHeaders(), and internalStart().
UpdateRequestNotes()
void UpdateRequestNotes (ConnStateData * csd, HttpRequest & request, NotePairs const & notes)
Updates ConnStateData ids and HttpRequest notes from helpers received notes.
Definition at line 757 of file HttpRequest.cc.
References NotePairs::add(), NotePairs::findFirst(), ConnStateData::notes(), HttpRequest::notes(), NotePairs::remove(), and NotePairs::replaceOrAdd().
Referenced by authTryGetUser(), ClientRequestContext::clientRedirectDone(), ClientRequestContext::clientStoreIdDone(), and copyResultsFromEntry().