Squid Web Cache: squid/src/http/one/Tokenizer.cc File Reference
Tokenizer.cc File Reference
#include "squid.h"
#include "debug/Stream.h"
#include "http/one/Parser.h"
#include "http/one/Tokenizer.h"
#include "parser/Tokenizer.h"
#include "sbuf/Stream.h"
Functions
static SBuf parseQuotedStringSuffix (Parser::Tokenizer &tok, const bool http1p0)
Function Documentation
parseQuotedStringSuffix()
static SBuf parseQuotedStringSuffix (Parser::Tokenizer & tok, const bool http1p0) static
Extracts quoted-string after the caller removes the initial '"'.
Parameters
http1p0 whether to prohibit -escaped characters in quoted strings
Exceptions
InsufficientInput when input can be a token prefix
Returns
extracted quoted string (without quotes and with chars unescaped)
Definition at line 21 of file Tokenizer.cc.
References SBuf::append(), CharacterSet::CR, CharacterSet::HTAB, CharacterSet::LF, CharacterSet::name, CharacterSet::OBSTEXT, CharacterSet::SP, TexcHere, ToSBuf(), and CharacterSet::VCHAR.
Referenced by Http::One::tokenOrQuotedString().