Squid Web Cache: squid/src/http.h File Reference
http.h File Reference
#include "clients/Client.h"
#include "comm.h"
#include "http/forward.h"
#include "http/StateFlags.h"
#include "sbuf/SBuf.h"
#include <optional>
Classes
class HttpStateData
class HttpStateData::ReuseDecision
assists in making and relaying entry caching/sharing decision
Functions
std::ostream & operator<< (std::ostream &os, const HttpStateData::ReuseDecision &d)
int httpCachable (const HttpRequestMethod &)
void httpStart (FwdState *)
SBuf httpMakeVaryMark (HttpRequest *request, HttpReply const *reply)
Function Documentation
httpCachable()
int httpCachable (const HttpRequestMethod &)
httpMakeVaryMark()
SBuf httpMakeVaryMark (HttpRequest * request, HttpReply const * reply)
Definition at line 590 of file http.cc.
References assembleVaryKey(), String::clean(), debugs, HttpHeader::getList(), Http::HDR_X_ACCELERATOR_VARY, Http::Message::header, and Http::VARY.
Referenced by StoreEntry::adjustVary(), HttpStateData::haveParsedReplyHeaders(), and varyEvaluateMatch().
httpStart()
void httpStart (FwdState * fwd)
Definition at line 2531 of file http.cc.
References debugs, FwdState::entry, HttpRequest::method, FwdState::request, AsyncJob::Start(), and StoreEntry::url().
Referenced by FwdState::dispatch().
operator<<()
std::ostream & operator<< (std::ostream & os, const HttpStateData::ReuseDecision & d)
Definition at line 2673 of file http.cc.
References HttpStateData::ReuseDecision::answer, assert, HttpStateData::ReuseDecision::doNotCacheButShare, HttpStateData::ReuseDecision::entry, HttpStateData::ReuseDecision::reason, HttpStateData::ReuseDecision::reuseNot, and HttpStateData::ReuseDecision::statusCode.