Squid Web Cache: squid/src/HttpRequest.h File Reference
HttpRequest.h File Reference
#include "anyp/Uri.h"
#include "base/CbcPointer.h"
#include "dns/forward.h"
#include "error/Error.h"
#include "HierarchyLogEntry.h"
#include "http/Message.h"
#include "http/RequestMethod.h"
#include "MasterXaction.h"
#include "Notes.h"
#include "RequestFlags.h"
#include "auth/UserRequest.h"
#include "adaptation/History.h"
#include "adaptation/icap/History.h"
#include "eui/Eui48.h"
#include "eui/Eui64.h"
Classes
class HttpRequest
Typedefs
typedef RefCount< AccessLogEntry > AccessLogEntryPointer
Functions
void httpRequestPack (void *obj, Packable *p)
void UpdateRequestNotes (ConnStateData *csd, HttpRequest &request, NotePairs const &notes)
const Ip::Address * FindListeningPortAddress (const HttpRequest *, const AccessLogEntry *)
AnyP::Port FindListeningPortNumber (const HttpRequest *, const AccessLogEntry *)
Typedef Documentation
AccessLogEntryPointer
typedef RefCount<AccessLogEntry> AccessLogEntryPointer
Definition at line 38 of file HttpRequest.h.
Function Documentation
FindListeningPortAddress()
const Ip::Address * FindListeningPortAddress (const HttpRequest * callerRequest, const AccessLogEntry * ale)
Returns
listening/*_port address used by the client connection (or nil) nil parameter(s) indicate missing caller information and are handled safely
Definition at line 860 of file HttpRequest.cc.
References FindGoodListeningPortAddress(), and Ip::Address::isAnyAddr().
Referenced by Format::Format::assemble(), and ErrorState::compileLegacyCode().
FindListeningPortNumber()
AnyP::Port FindListeningPortNumber (const HttpRequest * callerRequest, const AccessLogEntry * ale)
Returns
listening/*_port port number used by the client connection (or nothing) nil parameter(s) indicate missing caller information and are handled safely
Definition at line 869 of file HttpRequest.cc.
References Assure, FindGoodListeningPortAddress(), and Ip::Address::port().
Referenced by Format::Format::assemble().
httpRequestPack()
void httpRequestPack (void * obj, Packable * p)
Definition at line 358 of file HttpRequest.cc.
References HttpRequest::pack().
Referenced by clientInterpretRequestHeaders(), and internalStart().
UpdateRequestNotes()
void UpdateRequestNotes (ConnStateData * csd, HttpRequest & request, NotePairs const & notes)
Updates ConnStateData ids and HttpRequest notes from helpers received notes.
Definition at line 757 of file HttpRequest.cc.
References NotePairs::add(), NotePairs::findFirst(), ConnStateData::notes(), HttpRequest::notes(), NotePairs::remove(), and NotePairs::replaceOrAdd().
Referenced by authTryGetUser(), ClientRequestContext::clientRedirectDone(), ClientRequestContext::clientStoreIdDone(), and copyResultsFromEntry().