Squid Web Cache: squid/src/HttpHdrCc.h File Reference
HttpHdrCc.h File Reference
#include "defines.h"
#include "dlink.h"
#include "mem/forward.h"
#include "SquidString.h"
#include <iosfwd>
Classes
class HttpHdrCc
Enumerations
enum HttpHdrCcType : unsigned char {
CC_PUBLIC = 0 , CC_PRIVATE , CC_NO_CACHE , CC_NO_STORE ,
CC_NO_TRANSFORM , CC_MUST_REVALIDATE , CC_PROXY_REVALIDATE , CC_MAX_AGE ,
CC_S_MAXAGE , CC_MAX_STALE , CC_MIN_FRESH , CC_ONLY_IF_CACHED ,
CC_STALE_IF_ERROR , CC_IMMUTABLE , CC_OTHER , CC_ENUM_END
}
Functions
void httpHdrCcUpdateStats (const HttpHdrCc *cc, StatHist *hist)
void httpHdrCcStatDumper (StoreEntry *sentry, int idx, double val, double size, int count)
std::ostream & operator<< (std::ostream &, HttpHdrCcType)
Enumeration Type Documentation
HttpHdrCcType
enum HttpHdrCcType : unsigned char
Enumerator
CC_PUBLIC
CC_PRIVATE
CC_NO_CACHE
CC_NO_STORE
CC_NO_TRANSFORM
CC_MUST_REVALIDATE
CC_PROXY_REVALIDATE
CC_MAX_AGE
CC_S_MAXAGE
CC_MAX_STALE
CC_MIN_FRESH
CC_ONLY_IF_CACHED
CC_STALE_IF_ERROR
CC_IMMUTABLE
CC_OTHER
CC_ENUM_END
Definition at line 20 of file HttpHdrCc.h.
Function Documentation
httpHdrCcStatDumper()
void httpHdrCcStatDumper (StoreEntry * sentry, int idx, double val, double size, int count)
Definition at line 352 of file HttpHdrCc.cc.
References ccNameByType(), HttpHeaderStat::ccParsedCount, dump_stat, storeAppendPrintf(), and xdiv().
Referenced by httpHeaderStatDump().
httpHdrCcUpdateStats()
void httpHdrCcUpdateStats (const HttpHdrCc * cc, StatHist * hist)
Definition at line 342 of file HttpHdrCc.cc.
References assert, CC_ENUM_END, CC_PUBLIC, StatHist::count(), and HttpHdrCc::isSet().
Referenced by HttpHeader::getCc().
operator<<()
std::ostream & operator<< (std::ostream & s, HttpHdrCcType c)
Definition at line 362 of file HttpHdrCc.cc.
References ccNameByType().