Squid Web Cache: squid/src/servers/Http1Server.cc File Reference
Http1Server.cc File Reference
#include "squid.h"
#include "acl/FilledChecklist.h"
#include "client_side.h"
#include "client_side_reply.h"
#include "client_side_request.h"
#include "clientStream.h"
#include "comm/Write.h"
#include "HeaderMangling.h"
#include "http/one/RequestParser.h"
#include "http/Stream.h"
#include "servers/Http1Server.h"
#include "SquidConfig.h"
#include "Store.h"
#include "tunnel.h"
Functions
CBDATA_NAMESPACED_CLASS_INIT (Http1, Server)
void clientProcessRequestFinished (ConnStateData *conn, const HttpRequest::Pointer &request)
Function Documentation
CBDATA_NAMESPACED_CLASS_INIT()
CBDATA_NAMESPACED_CLASS_INIT (Http1 , Server)
clientProcessRequestFinished()
void clientProcessRequestFinished (ConnStateData * conn, const HttpRequest::Pointer & request)
Definition at line 1552 of file client_side.cc.
References Server::clientConnection, comm_reset_close(), debugs, ConnStateData::flags, HttpRequest::flags, Comm::IsConnOpen(), ConnStateData::readMore, and RequestFlags::resetTcp.
Referenced by Http::One::Server::buildHttpRequest(), clientProcessRequest(), and Http::One::Server::processParsedRequest().