Squid Web Cache: squid/src/http/one/Parser.cc File Reference
Parser.cc File Reference
#include "squid.h"
#include "base/CharacterSet.h"
#include "debug/Stream.h"
#include "http/one/Parser.h"
#include "mime_header.h"
#include "parser/Tokenizer.h"
#include "SquidConfig.h"
Namespaces
namespace Http
namespace Http::One
common part of ParseBws() and ParseStrctBws()
Macros
#define GET_HDR_SZ 1024
Functions
static const CharacterSet & RelaxedDelimiterCharacters ()
characters HTTP permits tolerant parsers to accept as delimiters
static const CharacterSet & LineCharacters ()
all characters except the LF line terminator
static void Http::One::ParseBws_ (Parser::Tokenizer &tok, const CharacterSet &bwsChars)
Macro Definition Documentation
GET_HDR_SZ
#define GET_HDR_SZ 1024
Definition at line 208 of file Parser.cc.
Function Documentation
LineCharacters()
static const CharacterSet & LineCharacters () static
Definition at line 76 of file Parser.cc.
References CharacterSet::complement(), and CharacterSet::LF.
Referenced by Http::One::Parser::cleanMimePrefix(), and Http::One::Parser::getHostHeaderField().
RelaxedDelimiterCharacters()
static const CharacterSet & RelaxedDelimiterCharacters () static
Definition at line 37 of file Parser.cc.
References CharacterSet::CR, CharacterSet::HTAB, and CharacterSet::SP.
Referenced by Http::One::Parser::cleanMimePrefix(), Http::One::Parser::DelimiterCharacters(), and Http::One::Parser::WhitespaceCharacters().