Squid Web Cache: squid/src/HttpHeader.h File Reference
HttpHeader.h File Reference
#include "anyp/ProtocolVersion.h"
#include "base/LookupTable.h"
#include "http/RegisteredHeaders.h"
#include "HttpHeaderMask.h"
#include "mem/PoolingAllocator.h"
#include "sbuf/forward.h"
#include "SquidString.h"
#include <vector>
Classes
class HttpHeaderEntry
class HttpHeader
Namespaces
namespace Http
Macros
#define HttpHeaderInitPos (-1)
Typedefs
typedef ssize_t HttpHeaderPos
Enumerations
enum http_hdr_owner_type {
hoNone =0 , hoHtcpReply , hoRequest , hoReply ,
hoErrorDetail , hoEnd
}
Functions
int httpHeaderParseQuotedString (const char *start, const int len, String *val)
SBuf Http::SlowlyParseQuotedString (const char *description, const char *start, size_t length)
SBuf httpHeaderQuoteString (const char *raw)
quotes string using RFC 7230 quoted-string rules
void httpHeaderCalcMask (HttpHeaderMask *mask, Http::HdrType http_hdr_type_enums[], size_t count)
void httpHeaderInitModule (void)
Macro Definition Documentation
HttpHeaderInitPos
#define HttpHeaderInitPos (-1)
Definition at line 48 of file HttpHeader.h.
Typedef Documentation
HttpHeaderPos
typedef ssize_t HttpHeaderPos
Iteration for headers; use HttpHeaderPos as opaque type, do not interpret
Definition at line 45 of file HttpHeader.h.
Enumeration Type Documentation
http_hdr_owner_type
enum http_hdr_owner_type
Possible owners of http header
Enumerator
hoNone
hoHtcpReply
hoRequest
hoReply
hoErrorDetail
hoEnd
Definition at line 31 of file HttpHeader.h.
Function Documentation
httpHeaderCalcMask()
void httpHeaderCalcMask (HttpHeaderMask * mask, Http::HdrType http_hdr_type_enums[], size_t count)
httpHeaderInitModule()
void httpHeaderInitModule (void)
Definition at line 138 of file HttpHeader.cc.
References assert, CBIT_SET, Http::enumEnd_, Http::HeaderLookupTable, hoEnd, httpHdrScInitModule(), httpHeaderRegisterWithCacheManager(), HttpHeaderStats, ReplyHeadersMask, and RequestHeadersMask.
Referenced by TestUfs::commonInit(), and mainInitialize().
httpHeaderParseQuotedString()
int httpHeaderParseQuotedString (const char * start, const int len, String * val)
Parses a quoted-string field (RFC 2616 section 2.2), complains if something went wrong, returns non-zero on success. Un-escapes quoted-pair characters found within the string. start should point at the first double-quote.
Definition at line 167 of file HttpHeader.cc.
References String::append(), String::assign(), String::clean(), debugs, and String::termedBuf().
Referenced by HttpHdrCc::parse(), HttpHdrSc::parse(), Ftp::PrintReply(), and Http::SlowlyParseQuotedString().
httpHeaderQuoteString()
SBuf httpHeaderQuoteString (const char * raw)
Definition at line 237 of file HttpHeader.cc.
References SBuf::append(), and assert.
Referenced by Ftp::Relay::createHttpReply().