Squid Web Cache: squid/src/http/Message.h File Reference
Message.h File Reference
#include "base/Lock.h"
#include "BodyPipe.h"
#include "enums.h"
#include "http/forward.h"
#include "http/ProtocolVersion.h"
#include "http/StatusCode.h"
#include "HttpHeader.h"
#include <type_traits>
Classes
class Http::Message
common parts of HttpRequest and HttpReply
Namespaces
namespace Http
Functions
template<class M >
void HTTPMSGUNLOCK (M *&a)
void HTTPMSGLOCK (Http::Message *a)
Function Documentation
HTTPMSGLOCK()
void HTTPMSGLOCK (Http::Message * a) inline
Definition at line 161 of file Message.h.
Referenced by DigestFetchState::DigestFetchState(), Mgr::Forwarder::Forwarder(), FwdState::FwdState(), ICPState::ICPState(), Adaptation::Iterator::Iterator(), Adaptation::ServiceFilter::ServiceFilter(), Adaptation::ServiceFilter::ServiceFilter(), Adaptation::Icap::XactAbortInfo::XactAbortInfo(), Adaptation::Icap::XactAbortInfo::XactAbortInfo(), Adaptation::Icap::Xaction::Xaction(), ClientHttpRequest::assignRequest(), clientReplyContext::cloneReply(), clientReplyContext::createStoreEntry(), Adaptation::Icap::Xaction::finalizeLogInfo(), Adaptation::Icap::ModXact::finalizeLogInfo(), Adaptation::Iterator::handleAdaptedHeader(), ClientHttpRequest::initRequest(), ClientHttpRequest::logRequest(), Adaptation::ServiceFilter::operator=(), peerCountMcastPeersCreateAndSend(), peerSelect(), ConnStateData::postHttpsAccept(), Adaptation::Message::set(), Adaptation::Icap::InOut::setCause(), Client::setFinalReply(), Adaptation::Icap::InOut::setHeader(), Client::setVirginReply(), ACLFilledChecklist::syncAle(), and ACLFilledChecklist::verifyAle().
HTTPMSGUNLOCK()
template<class M > void HTTPMSGUNLOCK (M *& a) inline
Definition at line 150 of file Message.h.
Referenced by AccessLogEntry::~AccessLogEntry(), Client::~Client(), clientReplyContext::~clientReplyContext(), DigestFetchState::~DigestFetchState(), Mgr::Forwarder::~Forwarder(), FwdState::~FwdState(), ICPState::~ICPState(), Adaptation::Icap::InOut::~InOut(), Adaptation::Iterator::~Iterator(), PeerSelector::~PeerSelector(), Adaptation::ServiceFilter::~ServiceFilter(), Adaptation::Icap::XactAbortInfo::~XactAbortInfo(), Adaptation::Icap::Xaction::~Xaction(), Adaptation::Message::clear(), ClientHttpRequest::clearRequest(), Adaptation::Iterator::handleAdaptedHeader(), ClientHttpRequest::logRequest(), Adaptation::ServiceFilter::operator=(), ConnStateData::postHttpsAccept(), clientReplyContext::processReplyAccessResult(), clientReplyContext::sendBodyTooLargeError(), clientReplyContext::sendPreconditionFailedError(), Adaptation::Icap::InOut::setCause(), and Adaptation::Icap::InOut::setHeader().