Squid Web Cache: squid/src/HttpHdrContRange.h File Reference
HttpHdrContRange.h File Reference
#include "HttpHeaderRange.h"
Classes
class HttpHdrContRange
Functions
HttpHdrContRange * httpHdrContRangeCreate (void)
HttpHdrContRange * httpHdrContRangeParseCreate (const char *crange_spec)
int httpHdrContRangeParseInit (HttpHdrContRange *crange, const char *crange_spec)
HttpHdrContRange * httpHdrContRangeDup (const HttpHdrContRange *crange)
void httpHdrContRangePackInto (const HttpHdrContRange *crange, Packable *p)
void httpHdrContRangeSet (HttpHdrContRange *, HttpHdrRangeSpec, int64_t)
void httpHeaderAddContRange (HttpHeader *, HttpHdrRangeSpec, int64_t)
Function Documentation
httpHdrContRangeCreate()
HttpHdrContRange * httpHdrContRangeCreate (void)
Definition at line 118 of file HttpHdrContRange.cc.
References HttpHdrContRange::elength, HttpHdrRangeSpec::length, HttpHdrRangeSpec::offset, range_spec_unknown, and HttpHdrContRange::spec.
Referenced by httpHdrContRangeDup(), httpHdrContRangeParseCreate(), and httpHeaderAddContRange().
httpHdrContRangeDup()
HttpHdrContRange * httpHdrContRangeDup (const HttpHdrContRange * crange)
Definition at line 196 of file HttpHdrContRange.cc.
References assert, and httpHdrContRangeCreate().
httpHdrContRangePackInto()
void httpHdrContRangePackInto (const HttpHdrContRange * crange, Packable * p)
Definition at line 206 of file HttpHdrContRange.cc.
References Packable::append(), Packable::appendf(), assert, HttpHdrContRange::elength, httpHdrRangeRespSpecPackInto(), known_spec, PRId64, and HttpHdrContRange::spec.
Referenced by HttpHeader::putContRange().
httpHdrContRangeParseCreate()
HttpHdrContRange * httpHdrContRangeParseCreate (const char * crange_spec)
Definition at line 127 of file HttpHdrContRange.cc.
References httpHdrContRangeCreate(), and httpHdrContRangeParseInit().
Referenced by HttpHeader::getContRange().
httpHdrContRangeParseInit()
int httpHdrContRangeParseInit (HttpHdrContRange * crange, const char * crange_spec)
returns true if range is valid; inits HttpHdrContRange
Definition at line 141 of file HttpHdrContRange.cc.
References assert, debugs, HttpHdrContRange::elength, httpHdrRangeRespSpecParseInit(), httpHeaderParseOffset(), known_spec, HttpHdrRangeSpec::length, HttpHdrRangeSpec::offset, range_spec_unknown, and HttpHdrContRange::spec.
Referenced by httpHdrContRangeParseCreate().
httpHdrContRangeSet()
void httpHdrContRangeSet (HttpHdrContRange * cr, HttpHdrRangeSpec spec, int64_t ent_len)
inits with given spec
Definition at line 220 of file HttpHdrContRange.cc.
References assert, HttpHdrContRange::elength, and HttpHdrContRange::spec.
Referenced by httpHeaderAddContRange().
httpHeaderAddContRange()
void httpHeaderAddContRange (HttpHeader * hdr, HttpHdrRangeSpec spec, int64_t ent_len)
wrapper arrounf PutContRange
Definition at line 47 of file HttpHeaderTools.cc.
References assert, httpHdrContRangeCreate(), httpHdrContRangeSet(), and HttpHeader::putContRange().
Referenced by Ftp::Gateway::appendSuccessHeader(), Http::Stream::buildRangeHeader(), and clientPackRangeHdr().