Squid Web Cache: squid/src/adaptation/icap/icap_log.h File Reference
icap_log.h File Reference
#include "AccessLogEntry.h"
#include "base/RefCount.h"
Typedefs
typedef RefCount< AccessLogEntry > AccessLogEntryPointer
Functions
void icapLogClose ()
void icapLogOpen ()
void icapLogRotate ()
void icapLogLog (AccessLogEntryPointer &al)
Variables
int IcapLogfileStatus
Typedef Documentation
AccessLogEntryPointer
typedef RefCount<AccessLogEntry> AccessLogEntryPointer
Definition at line 15 of file icap_log.h.
Function Documentation
icapLogClose()
void icapLogClose ()
Definition at line 38 of file icap_log.cc.
References Config, SquidConfig::icaplogs, log(), SquidConfig::Log, and logfileClose().
Referenced by mainReconfigureStart().
icapLogLog()
void icapLogLog (AccessLogEntryPointer & al)
Definition at line 60 of file icap_log.cc.
References accessLogLogTo(), AccessLogEntry::adapted_request, Config, IcapLogfileStatus, SquidConfig::icaplogs, SquidConfig::Log, LOG_ENABLE, and ACLFilledChecklist::updateAle().
Referenced by Adaptation::Icap::Xaction::maybeLog().
icapLogOpen()
void icapLogOpen ()
Definition at line 23 of file icap_log.cc.
References Log::Format::CLF_NONE, Config, IcapLogfileStatus, SquidConfig::icaplogs, log(), SquidConfig::Log, LOG_ENABLE, FormattedLog::logfile, and logfileOpen().
Referenced by mainInitialize(), and mainReconfigureFinish().
icapLogRotate()
void icapLogRotate ()
Definition at line 51 of file icap_log.cc.
References Config, SquidConfig::icaplogs, log(), SquidConfig::Log, logfileRotate(), and SquidConfig::rotateNumber.
Referenced by mainRotate().
Variable Documentation
IcapLogfileStatus
int IcapLogfileStatus extern
Definition at line 20 of file icap_log.cc.
Referenced by HttpRequest::icapHistory(), icapLogLog(), icapLogOpen(), and Adaptation::Icap::Xaction::maybeLog().