Squid Web Cache: squid/src/ICP.h File Reference
ICP.h File Reference
#include "base/RefCount.h"
#include "comm/forward.h"
#include "icp_opcode.h"
#include "ip/Address.h"
#include "LogTags.h"
#include "store_key_md5.h"
#include "StoreClient.h"
Classes
class icp_common_t
class ICPState
Typedefs
typedef RefCount< AccessLogEntry > AccessLogEntryPointer
Functions
const char * icpGetUrl (const Ip::Address &from, const char *, const icp_common_t &)
HttpRequest * icpGetRequest (const char *url, int reqnum, int fd, const Ip::Address &from)
bool icpAccessAllowed (Ip::Address &from, HttpRequest *icp_request)
void icpCreateAndSend (icp_opcode, int flags, char const *url, int reqnum, int pad, int fd, const Ip::Address &from, AccessLogEntryPointer)
icp_opcode icpGetCommonOpcode ()
void icpDenyAccess (const Ip::Address &from, const char *url, int reqnum, int fd)
void icpHandleIcpV3 (int, Ip::Address &, char *, int)
void icpOpenPorts (void)
void icpConnectionShutdown (void)
void icpClosePorts (void)
int icpSetCacheKey (const cache_key *key)
const cache_key * icpGetCacheKey (const char *url, int reqnum)
Variables
Comm::ConnectionPointer icpIncomingConn
Comm::ConnectionPointer icpOutgoingConn
Ip::Address theIcpPublicHostID
PF icpHandleUdp
Typedef Documentation
AccessLogEntryPointer
typedef RefCount<AccessLogEntry> AccessLogEntryPointer
Definition at line 28 of file ICP.h.
Function Documentation
icpGetUrl()
const char * icpGetUrl (const Ip::Address & from, const char * buf, const icp_common_t & header)
A URI extracted from the given raw packet buffer. On errors, details the problem and returns nil.
Definition at line 461 of file icp_v2.cc.
References debugs, ICP_QUERY, icp_common_t::length, and icp_common_t::opcode.
Referenced by doV2Query(), doV3Query(), and icp_common_t::handleReply().
Variable Documentation
theIcpPublicHostID
Ip::Address theIcpPublicHostID extern
Definition at line 30 of file stub_icp.cc.