Squid Web Cache: squid/src/mgr/InfoAction.cc File Reference
InfoAction.cc File Reference
#include "squid.h"
#include "base/TextException.h"
#include "comm/Connection.h"
#include "globals.h"
#include "HttpReply.h"
#include "ipc/Messages.h"
#include "ipc/RequestId.h"
#include "ipc/TypedMsgHdr.h"
#include "ipc/UdsOp.h"
#include "mgr/Filler.h"
#include "mgr/InfoAction.h"
#include "mgr/Request.h"
#include "mgr/Response.h"
#include "Store.h"
#include "tools.h"
Functions
void GetInfo (Mgr::InfoActionData &stats)
void DumpInfo (Mgr::InfoActionData &stats, StoreEntry *sentry)
void DumpMallocStatistics (StoreEntry *sentry)
Function Documentation
DumpInfo()
void DumpInfo (Mgr::InfoActionData & stats, StoreEntry * sentry)
Definition at line 554 of file stat.cc.
References APP_SHORTNAME, StoreEntry::append(), StoreInfoStats::Part::available(), Mgr::InfoActionData::avg_client_http_requests, Mgr::InfoActionData::avg_icp_messages, Mgr::InfoActionData::avg_loop_time, Mgr::InfoActionData::biggest_fd, Mgr::InfoActionData::byte_hit_ratio5, Mgr::InfoActionData::byte_hit_ratio60, Mgr::InfoActionData::cache_hits5, Mgr::InfoActionData::cache_hits60, Mgr::InfoActionData::cache_misses5, Mgr::InfoActionData::cache_misses60, StoreInfoStats::Part::capacity, SquidConfig::client_db, Mgr::InfoActionData::client_http_clients, Mgr::InfoActionData::client_http_requests, Config, Mgr::InfoActionData::count, StoreInfoStats::Part::count, Mgr::InfoActionData::cpu_time, Mgr::InfoActionData::cpu_usage, Mgr::InfoActionData::cpu_usage5, Mgr::InfoActionData::cpu_usage60, Mgr::InfoActionData::current_time, Mgr::InfoActionData::dns_lookups5, Mgr::InfoActionData::dns_lookups60, Math::doublePercent(), Time::FormatRfc1123(), Mgr::InfoActionData::gb_freed_count, Mgr::InfoActionData::gb_saved_count, Mem::GlobalStats(), Mgr::InfoActionData::htcp_pkts_recv, Mgr::InfoActionData::htcp_pkts_sent, Mgr::InfoActionData::http_requests5, Mgr::InfoActionData::http_requests60, Mgr::InfoActionData::icp_pkts_recv, Mgr::InfoActionData::icp_pkts_sent, Mgr::InfoActionData::icp_queries5, Mgr::InfoActionData::icp_queries60, Mgr::InfoActionData::icp_replies_queued, Mgr::InfoActionData::max_fd, Mgr::InfoActionData::maxrss, StoreInfoStats::Part::meanObjectSize(), StoreInfoStats::mem, StoreInfoStats::mem_object_count, Mgr::InfoActionData::near_hits5, Mgr::InfoActionData::near_hits60, Mgr::InfoActionData::not_modified_replies5, Mgr::InfoActionData::not_modified_replies60, Mgr::InfoActionData::num_fd_free, Mgr::InfoActionData::number_fd, SquidConfig::onoff, StoreInfoStats::Swap::open_disk_fd, Mgr::InfoActionData::opening_fd, Mgr::InfoActionData::page_faults, Mgr::InfoActionData::request_failure_ratio, Mgr::InfoActionData::request_hit_disk_ratio5, Mgr::InfoActionData::request_hit_disk_ratio60, Mgr::InfoActionData::request_hit_mem_ratio5, Mgr::InfoActionData::request_hit_mem_ratio60, Mgr::InfoActionData::request_hit_ratio5, Mgr::InfoActionData::request_hit_ratio60, Mgr::InfoActionData::reserved_fd, Mgr::InfoActionData::select_loops, service_name, StoreInfoStats::Part::size, SQUID_BUILD_INFO, Mgr::InfoActionData::squid_start, SQUIDSBUFPH, SQUIDSBUFPRINT, Mgr::InfoActionData::store, StoreInfoStats::store_entry_count, storeAppendPrintf(), StoreInfoStats::swap, Mgr::InfoActionData::total_accounted, Mgr::InfoActionData::unlink_requests, Mgr::InfoActionData::up_time, and version_string.
Referenced by Mgr::InfoAction::dump().
DumpMallocStatistics()
void DumpMallocStatistics (StoreEntry * sentry)
Definition at line 764 of file stat.cc.
References current_dtime, storeAppendPrintf(), xm_deltat, and xm_time.
Referenced by Mgr::InfoAction::dump().
GetInfo()
void GetInfo (Mgr::InfoActionData & stats)
Definition at line 431 of file stat.cc.
References Mem::PoolMeter::alloc, Mgr::InfoActionData::avg_client_http_requests, Mgr::InfoActionData::avg_icp_messages, Mgr::InfoActionData::avg_loop_time, Biggest_FD, Mgr::InfoActionData::biggest_fd, Mgr::InfoActionData::byte_hit_ratio5, Mgr::InfoActionData::byte_hit_ratio60, Mgr::InfoActionData::cache_hits5, Mgr::InfoActionData::cache_hits60, Mgr::InfoActionData::cache_misses5, Mgr::InfoActionData::cache_misses60, StatCounters::client_http, Mgr::InfoActionData::client_http_clients, Mgr::InfoActionData::client_http_requests, StatCounters::clients, Mem::PoolMeter::mgb_t::count, Mgr::InfoActionData::cpu_time, Mgr::InfoActionData::cpu_usage, Mgr::InfoActionData::cpu_usage5, Mgr::InfoActionData::cpu_usage60, Mgr::InfoActionData::current_time, current_time, Mem::Meter::currentLevel(), Mgr::InfoActionData::dns_lookups5, Mgr::InfoActionData::dns_lookups60, Math::doublePercent(), fdNFree(), Mem::PoolMeter::gb_freed, Mgr::InfoActionData::gb_freed_count, Mem::PoolMeter::gb_saved, Mgr::InfoActionData::gb_saved_count, Store::Controller::getStats(), Mem::GlobalStats(), StatCounters::htcp, Mgr::InfoActionData::htcp_pkts_recv, Mgr::InfoActionData::htcp_pkts_sent, Mgr::InfoActionData::http_requests5, Mgr::InfoActionData::http_requests60, StatCounters::icp, Mgr::InfoActionData::icp_pkts_recv, Mgr::InfoActionData::icp_pkts_sent, Mgr::InfoActionData::icp_queries5, Mgr::InfoActionData::icp_queries60, Mgr::InfoActionData::icp_replies_queued, Mgr::InfoActionData::max_fd, Mgr::InfoActionData::maxrss, Mem::PoolStats::meter, Mgr::InfoActionData::near_hits5, Mgr::InfoActionData::near_hits60, Mgr::InfoActionData::not_modified_replies5, Mgr::InfoActionData::not_modified_replies60, Mgr::InfoActionData::num_fd_free, Number_FD, Mgr::InfoActionData::number_fd, Opening_FD, Mgr::InfoActionData::opening_fd, Mgr::InfoActionData::page_faults, PCTILE_DNS, PCTILE_HIT, PCTILE_HTTP, PCTILE_ICP_QUERY, PCTILE_MISS, PCTILE_NH, PCTILE_NM, StatCounters::pkts_recv, StatCounters::pkts_sent, StatCounters::replies_queued, request_failure_ratio, Mgr::InfoActionData::request_failure_ratio, Mgr::InfoActionData::request_hit_disk_ratio5, Mgr::InfoActionData::request_hit_disk_ratio60, Mgr::InfoActionData::request_hit_mem_ratio5, Mgr::InfoActionData::request_hit_mem_ratio60, Mgr::InfoActionData::request_hit_ratio5, Mgr::InfoActionData::request_hit_ratio60, StatCounters::requests, RESERVED_FD, Mgr::InfoActionData::reserved_fd, Store::Root(), rusage_cputime(), rusage_maxrss(), rusage_pagefaults(), Mgr::InfoActionData::select_loops, StatCounters::select_loops, squid_getrusage(), Squid_MaxFD, squid_start, Mgr::InfoActionData::squid_start, statByteHitRatio(), statCounter, statCPUUsage(), statPctileSvc(), statRequestHitDiskRatio(), statRequestHitMemoryRatio(), statRequestHitRatio(), Mgr::InfoActionData::store, Mgr::InfoActionData::total_accounted, tvSubDsec(), StatCounters::unlink, Mgr::InfoActionData::unlink_requests, and Mgr::InfoActionData::up_time.
Referenced by Mgr::InfoAction::collect().