Squid Web Cache: squid/src/mgr/IntervalAction.cc File Reference
IntervalAction.cc File Reference
#include "squid.h"
#include "base/TextException.h"
#include "ipc/Messages.h"
#include "ipc/TypedMsgHdr.h"
#include "mgr/IntervalAction.h"
#include "SquidMath.h"
#include "Store.h"
#include "tools.h"
Functions
void GetAvgStat (Mgr::IntervalActionData &stats, int minutes, int hours)
void DumpAvgStat (Mgr::IntervalActionData &stats, StoreEntry *sentry)
Function Documentation
DumpAvgStat()
void DumpAvgStat (Mgr::IntervalActionData & stats, StoreEntry * sentry)
Definition at line 1000 of file stat.cc.
References Mgr::IntervalActionData::aborted_requests, Mgr::IntervalActionData::average_select_fd_period, Mgr::IntervalActionData::client_http_all_median_svc_time, Mgr::IntervalActionData::client_http_errors, Mgr::IntervalActionData::client_http_hit_median_svc_time, Mgr::IntervalActionData::client_http_hits, Mgr::IntervalActionData::client_http_kbytes_in, Mgr::IntervalActionData::client_http_kbytes_out, Mgr::IntervalActionData::client_http_miss_median_svc_time, Mgr::IntervalActionData::client_http_nh_median_svc_time, Mgr::IntervalActionData::client_http_nm_median_svc_time, Mgr::IntervalActionData::client_http_requests, Mgr::IntervalActionData::count, Mgr::IntervalActionData::cpu_time, Mgr::IntervalActionData::dns_median_svc_time, Math::doublePercent(), Time::FormatRfc1123(), Mgr::IntervalActionData::hitValidationAttempts, Mgr::IntervalActionData::hitValidationFailures, Mgr::IntervalActionData::hitValidationRefusalsDueToLocking, Mgr::IntervalActionData::hitValidationRefusalsDueToTimeLimit, Mgr::IntervalActionData::hitValidationRefusalsDueToZeroSize, Mgr::IntervalActionData::icp_kbytes_recv, Mgr::IntervalActionData::icp_kbytes_sent, Mgr::IntervalActionData::icp_pkts_recv, Mgr::IntervalActionData::icp_pkts_sent, Mgr::IntervalActionData::icp_q_kbytes_recv, Mgr::IntervalActionData::icp_q_kbytes_sent, Mgr::IntervalActionData::icp_queries_recv, Mgr::IntervalActionData::icp_queries_sent, Mgr::IntervalActionData::icp_query_median_svc_time, Mgr::IntervalActionData::icp_query_timeouts, Mgr::IntervalActionData::icp_r_kbytes_recv, Mgr::IntervalActionData::icp_r_kbytes_sent, Mgr::IntervalActionData::icp_replies_queued, Mgr::IntervalActionData::icp_replies_recv, Mgr::IntervalActionData::icp_replies_sent, Mgr::IntervalActionData::icp_reply_median_svc_time, Mgr::IntervalActionData::median_select_fds, Mgr::IntervalActionData::page_faults, Mgr::IntervalActionData::sample_end_time, Mgr::IntervalActionData::sample_start_time, Mgr::IntervalActionData::select_fds, Mgr::IntervalActionData::select_loops, Mgr::IntervalActionData::server_all_errors, Mgr::IntervalActionData::server_all_kbytes_in, Mgr::IntervalActionData::server_all_kbytes_out, Mgr::IntervalActionData::server_all_requests, Mgr::IntervalActionData::server_ftp_errors, Mgr::IntervalActionData::server_ftp_kbytes_in, Mgr::IntervalActionData::server_ftp_kbytes_out, Mgr::IntervalActionData::server_ftp_requests, Mgr::IntervalActionData::server_http_errors, Mgr::IntervalActionData::server_http_kbytes_in, Mgr::IntervalActionData::server_http_kbytes_out, Mgr::IntervalActionData::server_http_requests, Mgr::IntervalActionData::server_other_errors, Mgr::IntervalActionData::server_other_kbytes_in, Mgr::IntervalActionData::server_other_kbytes_out, Mgr::IntervalActionData::server_other_requests, storeAppendPrintf(), Mgr::IntervalActionData::swap_files_cleaned, Mgr::IntervalActionData::swap_ins, Mgr::IntervalActionData::swap_outs, Mgr::IntervalActionData::syscalls_disk_closes, Mgr::IntervalActionData::syscalls_disk_opens, Mgr::IntervalActionData::syscalls_disk_reads, Mgr::IntervalActionData::syscalls_disk_seeks, Mgr::IntervalActionData::syscalls_disk_unlinks, Mgr::IntervalActionData::syscalls_disk_writes, Mgr::IntervalActionData::syscalls_selects, Mgr::IntervalActionData::syscalls_sock_accepts, Mgr::IntervalActionData::syscalls_sock_binds, Mgr::IntervalActionData::syscalls_sock_closes, Mgr::IntervalActionData::syscalls_sock_connects, Mgr::IntervalActionData::syscalls_sock_reads, Mgr::IntervalActionData::syscalls_sock_recvfroms, Mgr::IntervalActionData::syscalls_sock_sendtos, Mgr::IntervalActionData::syscalls_sock_sockets, Mgr::IntervalActionData::syscalls_sock_writes, Mgr::IntervalActionData::unlink_requests, and Mgr::IntervalActionData::wall_time.
Referenced by Mgr::IntervalAction::dump(), and statAvgDump().
GetAvgStat()
void GetAvgStat (Mgr::IntervalActionData & stats, int minutes, int hours)
Definition at line 864 of file stat.cc.
References Mgr::IntervalActionData::aborted_requests, StatCounters::allSvcTime, assert, Mgr::IntervalActionData::average_select_fd_period, StatCounters::client_http, Mgr::IntervalActionData::client_http_all_median_svc_time, Mgr::IntervalActionData::client_http_errors, Mgr::IntervalActionData::client_http_hit_median_svc_time, Mgr::IntervalActionData::client_http_hits, Mgr::IntervalActionData::client_http_kbytes_in, Mgr::IntervalActionData::client_http_kbytes_out, Mgr::IntervalActionData::client_http_miss_median_svc_time, Mgr::IntervalActionData::client_http_nh_median_svc_time, Mgr::IntervalActionData::client_http_nm_median_svc_time, Mgr::IntervalActionData::client_http_requests, CountHist, CountHourHist, Mgr::IntervalActionData::cpu_time, StatCounters::cputime, DBG_IMPORTANT, debugs, StatCounters::dns, Mgr::IntervalActionData::dns_median_svc_time, StatCounters::hitSvcTime, Mgr::IntervalActionData::hitValidationAttempts, Mgr::IntervalActionData::hitValidationFailures, Mgr::IntervalActionData::hitValidationRefusalsDueToLocking, Mgr::IntervalActionData::hitValidationRefusalsDueToTimeLimit, Mgr::IntervalActionData::hitValidationRefusalsDueToZeroSize, StatCounters::icp, Mgr::IntervalActionData::icp_kbytes_recv, Mgr::IntervalActionData::icp_kbytes_sent, Mgr::IntervalActionData::icp_pkts_recv, Mgr::IntervalActionData::icp_pkts_sent, Mgr::IntervalActionData::icp_q_kbytes_recv, Mgr::IntervalActionData::icp_q_kbytes_sent, Mgr::IntervalActionData::icp_queries_recv, Mgr::IntervalActionData::icp_queries_sent, Mgr::IntervalActionData::icp_query_median_svc_time, Mgr::IntervalActionData::icp_query_timeouts, Mgr::IntervalActionData::icp_r_kbytes_recv, Mgr::IntervalActionData::icp_r_kbytes_sent, Mgr::IntervalActionData::icp_replies_queued, Mgr::IntervalActionData::icp_replies_recv, Mgr::IntervalActionData::icp_replies_sent, Mgr::IntervalActionData::icp_reply_median_svc_time, Mgr::IntervalActionData::median_select_fds, StatCounters::missSvcTime, N_COUNT_HIST, N_COUNT_HOUR_HIST, StatCounters::nearHitSvcTime, StatCounters::nearMissSvcTime, Mgr::IntervalActionData::page_faults, StatCounters::querySvcTime, StatCounters::replySvcTime, Mgr::IntervalActionData::sample_end_time, Mgr::IntervalActionData::sample_start_time, Mgr::IntervalActionData::select_fds, StatCounters::select_fds, StatCounters::select_fds_hist, Mgr::IntervalActionData::select_loops, StatCounters::select_time, server, Mgr::IntervalActionData::server_all_errors, Mgr::IntervalActionData::server_all_kbytes_in, Mgr::IntervalActionData::server_all_kbytes_out, Mgr::IntervalActionData::server_all_requests, Mgr::IntervalActionData::server_ftp_errors, Mgr::IntervalActionData::server_ftp_kbytes_in, Mgr::IntervalActionData::server_ftp_kbytes_out, Mgr::IntervalActionData::server_ftp_requests, Mgr::IntervalActionData::server_http_errors, Mgr::IntervalActionData::server_http_kbytes_in, Mgr::IntervalActionData::server_http_kbytes_out, Mgr::IntervalActionData::server_http_requests, Mgr::IntervalActionData::server_other_errors, Mgr::IntervalActionData::server_other_kbytes_in, Mgr::IntervalActionData::server_other_kbytes_out, Mgr::IntervalActionData::server_other_requests, statHistDeltaMedian(), StatCounters::svcTime, Mgr::IntervalActionData::swap_files_cleaned, Mgr::IntervalActionData::swap_ins, Mgr::IntervalActionData::swap_outs, Mgr::IntervalActionData::syscalls_disk_closes, Mgr::IntervalActionData::syscalls_disk_opens, Mgr::IntervalActionData::syscalls_disk_reads, Mgr::IntervalActionData::syscalls_disk_seeks, Mgr::IntervalActionData::syscalls_disk_unlinks, Mgr::IntervalActionData::syscalls_disk_writes, Mgr::IntervalActionData::syscalls_selects, Mgr::IntervalActionData::syscalls_sock_accepts, Mgr::IntervalActionData::syscalls_sock_binds, Mgr::IntervalActionData::syscalls_sock_closes, Mgr::IntervalActionData::syscalls_sock_connects, Mgr::IntervalActionData::syscalls_sock_reads, Mgr::IntervalActionData::syscalls_sock_recvfroms, Mgr::IntervalActionData::syscalls_sock_sendtos, Mgr::IntervalActionData::syscalls_sock_sockets, Mgr::IntervalActionData::syscalls_sock_writes, StatCounters::timestamp, tvSubDsec(), Mgr::IntervalActionData::unlink_requests, Mgr::IntervalActionData::wall_time, and XAVG.
Referenced by Mgr::IntervalAction::collect(), and statAvgDump().