Squid Web Cache: squid/src/mgr/IoAction.cc File Reference
IoAction.cc File Reference
#include "squid.h"
#include "base/TextException.h"
#include "IoStats.h"
#include "ipc/Messages.h"
#include "ipc/TypedMsgHdr.h"
#include "mgr/IoAction.h"
#include "SquidMath.h"
#include "Store.h"
#include "tools.h"
Functions
void GetIoStats (Mgr::IoActionData &stats)
void DumpIoStats (Mgr::IoActionData &stats, StoreEntry *sentry)
Function Documentation
DumpIoStats()
void DumpIoStats (Mgr::IoActionData & stats, StoreEntry * sentry)
Definition at line 208 of file stat.cc.
References Math::doublePercent(), Mgr::IoActionData::ftp_read_hist, Mgr::IoActionData::ftp_reads, IoStats::histSize, Mgr::IoActionData::http_read_hist, Mgr::IoActionData::http_reads, and storeAppendPrintf().
Referenced by Mgr::IoAction::dump().
GetIoStats()
void GetIoStats (Mgr::IoActionData & stats)
Definition at line 190 of file stat.cc.
References IoStats::Ftp, Mgr::IoActionData::ftp_read_hist, Mgr::IoActionData::ftp_reads, IoStats::histSize, IoStats::Http, Mgr::IoActionData::http_read_hist, Mgr::IoActionData::http_reads, IOStats, IoStats::read_hist, and IoStats::reads.
Referenced by Mgr::IoAction::collect().