Squid Web Cache: squid/src/base/IoManip.h File Reference
IoManip.h File Reference
#include "debug/Stream.h"
#include <iostream>
#include <iomanip>
#include <optional>
Classes
class RawPointerT< Pointer >
class AsHex< Integer >
class AsList< Container >
std::ostream manipulator to print containers as flat lists
class AtMostOnce< T >
class WithExtras< T >
Helps prints T object using object's T::printWithExtras() method.
Functions
template<class Pointer >
RawPointerT< Pointer > RawPointer (const char *label, const Pointer &ptr)
convenience wrapper for creating RawPointerT<> objects
template<class Pointer >
RawPointerT< Pointer > RawPointer (const Pointer &ptr)
convenience wrapper for creating RawPointerT<> objects without a label
template<class Pointer >
std::ostream & operator<< (std::ostream &os, const RawPointerT< Pointer > &pd)
prints RawPointerT<>, dereferencing the io_manip pointer if possible
template<class Integer >
std::ostream & operator<< (std::ostream &os, const AsHex< Integer > number)
template<class Integer >
AsHex< Integer > asHex (const Integer n)
a helper to ease AsHex object creation
void PrintHex (std::ostream &, const char *data, size_t n)
Prints the first n data bytes using hex notation. Does nothing if n is 0.
template<typename Container >
std::ostream & operator<< (std::ostream &os, const AsList< Container > &manipulator)
template<typename Container >
auto asList (const Container &c)
a helper to ease AsList object creation
template<class T >
auto & operator<< (std::ostream &os, AtMostOnce< T > &a)
template<class T >
auto & operator<< (std::ostream &os, const WithExtras< T > &a)
writes T object to the given stream using object's T::printWithExtras() method
Function Documentation
asHex()
template<class Integer > AsHex< Integer > asHex (const Integer n) inline
Definition at line 169 of file IoManip.h.
Referenced by Security::ErrorDetail::ErrorDetail(), Fs::Ufs::UFSSwapDir::addDiskRestore(), asQosConfigHex(), StoreEntry::attachToDisk(), ExceptionErrorDetail::brief(), Security::ErrorDetail::brief(), Fs::Ufs::UFSStoreState::close(), Fs::Ufs::UFSStoreState::closeCompleted(), Fs::Ufs::UFSStrategy::create(), Rock::SwapDir::createStoreIO(), Rock::SwapDir::createUpdateIO(), Fs::Ufs::UFSSwapDir::DirClean(), Comm::DoSelect(), Fs::Ufs::UFSSwapDir::dumpEntry(), Fs::Ufs::RebuildState::getNextFile(), idnsALookup(), idnsCheckQueue(), idnsGrokReply(), idnsPTRLookup(), idnsSendSlaveAAAAQuery(), Fs::Ufs::UFSStoreState::ioCompletedNotification(), ipcache_gethostbyname(), ldap_escape_value(), Security::ServerOptions::loadDhParams(), Acl::ConnMark::match(), ACLTimeData::match(), Fs::Ufs::UFSStrategy::open(), Rock::SwapDir::openStoreIO(), operator<<(), Security::ParseProtocolVersionBase(), RandomUuid::print(), Fs::Ufs::UFSStoreState::read_(), Fs::Ufs::UFSStoreState::readCompleted(), Fs::Ufs::RebuildState::rebuildFromSwapLog(), Ssl::ReportAndForgetErrors(), Ssl::Bio::stateChanged(), storeDirSwapLog(), storeSwapOutFileClosed(), storeSwapOutStart(), TestIoManip::testAsHex(), Fs::Ufs::UFSSwapDir::unlinkFile(), Ipc::StoreMap::validateHit(), ExceptionErrorDetail::verbose(), Fs::Ufs::UFSStoreState::write(), and Fs::Ufs::UFSStoreState::writeCompleted().
asList()
template<typename Container > auto asList (const Container & c) inline
Definition at line 246 of file IoManip.h.
Referenced by Acl::Node::dumpWhole().
operator<<() [1/5]
template<class T > auto & operator<< (std::ostream & os, AtMostOnce< T > & a) inline
Prints AtMostOnce argument if needed. The argument is not constant to prevent wrong usage:
/* Compiler error: cannot bind non-const lvalue reference to an rvalue */
os << AtMostOnce(x);
Definition at line 285 of file IoManip.h.
References AtMostOnce< T >::print().
operator<<() [2/5]
template<class Integer > std::ostream & operator<< (std::ostream & os, const AsHex< Integer > number) inline
Definition at line 142 of file IoManip.h.
operator<<() [3/5]
template<typename Container > std::ostream & operator<< (std::ostream & os, const AsList< Container > & manipulator) inline
Definition at line 237 of file IoManip.h.
References AsList< Container >::print().
operator<<() [4/5]
template<class Pointer > std::ostream & operator<< (std::ostream & os, const RawPointerT< Pointer > & pd) inline
Definition at line 88 of file IoManip.h.
References Debug::Extra(), RawPointerT< Pointer >::label, RawPointerT< Pointer >::nilText, RawPointerT< Pointer >::onExtraLine, and RawPointerT< Pointer >::ptr.
operator<<() [5/5]
template<class T > auto & operator<< (std::ostream & os, const WithExtras< T > & a) inline
Definition at line 303 of file IoManip.h.
References WithExtras< T >::toPrint.
PrintHex()
void PrintHex (std::ostream & os, const char * data, size_t n)
Definition at line 16 of file IoManip.cc.
References assert.
Referenced by Raw::print(), and PrintSecret().
RawPointer() [1/2]
template<class Pointer > RawPointerT< Pointer > RawPointer (const char * label, const Pointer & ptr) inline
Definition at line 73 of file IoManip.h.
Referenced by finishAndDeleteFetch(), getRoundRobinParent(), getWeightedRoundRobinParent(), neighborsUdpAck(), operator<<(), peerDigestCheck(), peerNoteDigestLookup(), ConnStateData::serveDelayedError(), and Security::PeerConnector::sslCrtvdHandleReply().
RawPointer() [2/2]
template<class Pointer > RawPointerT< Pointer > RawPointer (const Pointer & ptr) inline
Definition at line 81 of file IoManip.h.