Squid Web Cache: squid/src/acl/Ip.cc File Reference
Ip.cc File Reference
#include "squid.h"
#include "acl/Checklist.h"
#include "acl/Ip.h"
#include "acl/SplayInserter.h"
#include "cache_cf.h"
#include "ConfigParser.h"
#include "debug/Stream.h"
#include "ip/tools.h"
#include "MemBuf.h"
#include "wordlist.h"
#include <algorithm>
Classes
struct IpAclDumpVisitor
Macros
#define SCAN_ACL1_6 "%[0123456789ABCDEFabcdef:]-%[0123456789ABCDEFabcdef:]/%[0123456789]"
#define SCAN_ACL2_6 "%[0123456789ABCDEFabcdef:]-%[0123456789ABCDEFabcdef:]%c"
#define SCAN_ACL3_6 "%[0123456789ABCDEFabcdef:]/%[0123456789]"
#define SCAN_ACL4_6 "%[0123456789ABCDEFabcdef:]/%c"
#define SCAN_ACL1_4 "%[0123456789.]-%[0123456789.]/%[0123456789.]"
#define SCAN_ACL2_4 "%[0123456789.]-%[0123456789.]%c"
#define SCAN_ACL3_4 "%[0123456789.]/%[0123456789.]"
#define SCAN_ACL4_4 "%[0123456789.]/%c"
Functions
static std::ostream & operator<< (std::ostream &os, acl_ip_data *value)
reports acl_ip_data using squid.conf ACL value format
static int aclIpAddrNetworkCompare (acl_ip_data *const &p, acl_ip_data *const &q)
Macro Definition Documentation
SCAN_ACL1_4
#define SCAN_ACL1_4 "%[0123456789.]-%[0123456789.]/%[0123456789.]"
Definition at line 238 of file Ip.cc.
SCAN_ACL1_6
#define SCAN_ACL1_6 "%[0123456789ABCDEFabcdef:]-%[0123456789ABCDEFabcdef:]/%[0123456789]"
Definition at line 233 of file Ip.cc.
SCAN_ACL2_4
#define SCAN_ACL2_4 "%[0123456789.]-%[0123456789.]%c"
Definition at line 239 of file Ip.cc.
SCAN_ACL2_6
#define SCAN_ACL2_6 "%[0123456789ABCDEFabcdef:]-%[0123456789ABCDEFabcdef:]%c"
Definition at line 234 of file Ip.cc.
SCAN_ACL3_4
#define SCAN_ACL3_4 "%[0123456789.]/%[0123456789.]"
Definition at line 240 of file Ip.cc.
SCAN_ACL3_6
#define SCAN_ACL3_6 "%[0123456789ABCDEFabcdef:]/%[0123456789]"
Definition at line 235 of file Ip.cc.
SCAN_ACL4_4
#define SCAN_ACL4_4 "%[0123456789.]/%c"
Definition at line 241 of file Ip.cc.
SCAN_ACL4_6
#define SCAN_ACL4_6 "%[0123456789ABCDEFabcdef:]/%c"
Definition at line 236 of file Ip.cc.
Function Documentation
aclIpAddrNetworkCompare()
static int aclIpAddrNetworkCompare (acl_ip_data *const & p, acl_ip_data *const & q) static
Definition at line 147 of file Ip.cc.
References acl_ip_data::addr1, acl_ip_data::addr2, Ip::Address::applyMask(), debugs, Ip::Address::isAnyAddr(), acl_ip_data::mask, and Ip::Address::matchIPAddr().
Referenced by ACLIP::match().
operator<<()
static std::ostream & operator<< (std::ostream & os, acl_ip_data * value) static
Definition at line 131 of file Ip.cc.
References acl_ip_data::toSBuf().