Squid Web Cache: squid/src/LoadableModules.cc File Reference
LoadableModules.cc File Reference
#include "squid.h"
#include "debug/Messages.h"
#include "LoadableModule.h"
#include "LoadableModules.h"
#include "sbuf/List.h"
Functions
static void LoadModule (const SBuf &fname)
void LoadableModulesConfigure (const SBufList &names)
dynamically load named libraries, in the listed order
Function Documentation
LoadableModulesConfigure()
void LoadableModulesConfigure (const SBufList & names)
Definition at line 28 of file LoadableModules.cc.
References debugs, Important, and LoadModule().
Referenced by mainInitialize(), and mainReconfigureFinish().
LoadModule()
static void LoadModule (const SBuf & fname) static
Definition at line 16 of file LoadableModules.cc.
References DBG_IMPORTANT, and debugs.
Referenced by LoadableModulesConfigure().