Squid Web Cache: squid/src/log/file/log_file_daemon.cc File Reference
log_file_daemon.cc File Reference
#include "squid.h"
#include "compat/unistd.h"
#include <cassert>
#include <cerrno>
#include <csignal>
#include <cstring>
#include "helper/protocol_defines.h"
Macros
#define LOGFILE_BUF_LEN 65536
Functions
static void rotate (const char *path, int rotate_count)
int main (int argc, char *argv[])
Macro Definition Documentation
LOGFILE_BUF_LEN
#define LOGFILE_BUF_LEN 65536
Definition at line 33 of file log_file_daemon.cc.
Function Documentation
main()
int main (int argc, char * argv[])
The commands:
L<data>
- logfile data R
- rotate file T
- truncate file O
- repoen file F
- flush file r<n>
- set rotate count to <n> b<n>
- 1 = buffer output, 0 = don't buffer output
Definition at line 93 of file log_file_daemon.cc.
References assert, LOGFILE_BUF_LEN, rotate(), xclose(), xopen(), and xstrerr().
rotate()
static void rotate (const char * path, int rotate_count) static
Definition at line 36 of file log_file_daemon.cc.
References assert, MAXPATHLEN, and xstrerr().
Referenced by main().