Squid Web Cache: squid/src/log/File.cc File Reference
File.cc File Reference
#include "squid.h"
#include "debug/Messages.h"
#include "fatal.h"
#include "fde.h"
#include "log/File.h"
#include "log/ModDaemon.h"
#include "log/ModStdio.h"
#include "log/ModSyslog.h"
#include "log/ModUdp.h"
#include "log/TcpLogger.h"
#include "sbuf/SBuf.h"
Functions
CBDATA_CLASS_INIT (Logfile)
Logfile * logfileOpen (const char *path, size_t bufsz, int fatal_flag)
void logfileClose (Logfile *lf)
void logfileRotate (Logfile *lf, int16_t rotateCount)
void logfileWrite (Logfile *lf, const char *buf, size_t len)
void logfilePrintf (Logfile *lf, const char *fmt,...)
void logfileLineStart (Logfile *lf)
void logfileLineEnd (Logfile *lf)
void logfileFlush (Logfile *lf)
Function Documentation
CBDATA_CLASS_INIT()
CBDATA_CLASS_INIT (Logfile)
logfileClose()
void logfileClose (Logfile * lf)
Definition at line 92 of file File.cc.
References debugs, Logfile::f_close, Logfile::f_flush, Important, and Logfile::path.
Referenced by accessLogClose(), FormattedLog::close(), icapLogClose(), netdbSaveState(), and storeLogClose().
logfileFlush()
void logfileFlush (Logfile * lf)
Definition at line 139 of file File.cc.
References Logfile::f_flush.
Referenced by logfile_mod_daemon_close(), logfile_mod_stdio_rotate(), and logfile_mod_stdio_writeline().
logfileLineEnd()
void logfileLineEnd (Logfile * lf)
Definition at line 132 of file File.cc.
References Logfile::f_lineend, and Logfile::sequence_number.
Referenced by accessLogLogTo(), Security::KeyLog::record(), and storeLog().
logfileLineStart()
void logfileLineStart (Logfile * lf)
Definition at line 126 of file File.cc.
References Logfile::f_linestart.
Referenced by accessLogLogTo(), Security::KeyLog::record(), and storeLog().
logfileOpen()
Logfile * logfileOpen (const char * path, size_t bufsz, int fatal_flag)
Definition at line 40 of file File.cc.
References debugs, Important, logfile_mod_daemon_open(), logfile_mod_stdio_open(), logfile_mod_syslog_open(), logfile_mod_udp_open(), and Log::TcpLogger::Open().
Referenced by accessLogInit(), icapLogOpen(), netdbSaveState(), FormattedLog::open(), and storeLogOpen().
logfilePrintf()
void logfilePrintf (Logfile * lf, const char * fmt, ...)
Definition at line 114 of file File.cc.
References SBuf::c_str(), SBuf::clear(), SBuf::length(), logfileWrite(), and SBuf::vappendf().
Referenced by Log::Format::HttpdCombined(), Log::Format::HttpdCommon(), netdbSaveState(), Security::KeyLog::record(), Log::Format::SquidCustom(), Log::Format::SquidIcap(), Log::Format::SquidNative(), Log::Format::SquidReferer(), Log::Format::SquidUserAgent(), and storeLog().
logfileRotate()
void logfileRotate (Logfile * lf, int16_t rotateCount)
Definition at line 101 of file File.cc.
References DBG_IMPORTANT, debugs, Logfile::f_rotate, and Logfile::path.
Referenced by icapLogRotate(), FormattedLog::rotate(), and storeLogRotate().
logfileWrite()
void logfileWrite (Logfile * lf, const char * buf, size_t len)
Definition at line 108 of file File.cc.
References Logfile::f_linewrite.
Referenced by logfilePrintf().