Squid Web Cache: squid/include/md5.h File Reference
md5.h File Reference
Classes
struct SquidMD5Context
Macros
#define SQUID_MD5_DIGEST_LENGTH 16
Typedefs
typedef struct SquidMD5Context SquidMD5_CTX
Functions
SQUIDCEXTERN void SquidMD5Init (struct SquidMD5Context *context)
SQUIDCEXTERN void SquidMD5Update (struct SquidMD5Context *context, const void *buf, unsigned len)
SQUIDCEXTERN void SquidMD5Final (uint8_t digest[16], struct SquidMD5Context *context)
SQUIDCEXTERN void SquidMD5Transform (uint32_t buf[4], uint32_t const in[16])
Macro Definition Documentation
SQUID_MD5_DIGEST_LENGTH
#define SQUID_MD5_DIGEST_LENGTH 16
Definition at line 66 of file md5.h.
Typedef Documentation
SquidMD5_CTX
typedef struct SquidMD5Context SquidMD5_CTX
Function Documentation
SquidMD5Final()
SQUIDCEXTERN void SquidMD5Final (uint8_t digest[16], struct SquidMD5Context * context)
Referenced by authDigestNonceEncode(), crypt_md5(), DigestCalcHA1(), DigestCalcResponse(), md5_calc(), md5sum(), PidFilenameHash(), storeKeyPublic(), storeKeyPublicByRequestMethod(), wccp2_check_security(), and wccp2_update_md5_security().
SquidMD5Init()
SQUIDCEXTERN void SquidMD5Init (struct SquidMD5Context * context)
Definition at line 73 of file md5.c.
References SquidMD5Context::buf, and SquidMD5Context::bytes.
Referenced by authDigestNonceEncode(), crypt_md5(), DigestCalcHA1(), DigestCalcResponse(), md5_calc(), md5sum(), PidFilenameHash(), storeKeyPublic(), storeKeyPublicByRequestMethod(), wccp2_check_security(), and wccp2_update_md5_security().
SquidMD5Transform()
SQUIDCEXTERN void SquidMD5Transform (uint32_t buf[4], uint32_t const in[16])
Definition at line 181 of file md5.c.
References F1, F2, F3, F4, and MD5STEP.
Referenced by SquidMD5Final(), and SquidMD5Update().
SquidMD5Update()
SQUIDCEXTERN void SquidMD5Update (struct SquidMD5Context * context, const void * buf, unsigned len)
Definition at line 89 of file md5.c.
References SquidMD5Context::buf, SquidMD5Context::bytes, byteSwap, SquidMD5Context::in, and SquidMD5Transform().
Referenced by authDigestNonceEncode(), crypt_md5(), DigestCalcHA1(), DigestCalcResponse(), md5_calc(), md5sum(), PidFilenameHash(), storeKeyPublic(), storeKeyPublicByRequestMethod(), wccp2_check_security(), and wccp2_update_md5_security().