Squid Web Cache: squid/lib/md5.cc File Reference
md5.cc File Reference
#include "squid.h"
#include "md5.h"
Macros
#define byteSwap(buf, words)
#define F1(x, y, z) (z ^ (x & (y ^ z)))
#define F2(x, y, z) F1(z, x, y)
#define F3(x, y, z) (x ^ y ^ z)
#define F4(x, y, z) (y ^ (x | ~z))
#define MD5STEP(f, w, x, y, z, in, s) (w += f(x,y,z) + in, w = (w<<s | w>>(32-s)) + x)
Functions
void SquidMD5Init (struct SquidMD5Context *ctx)
void SquidMD5Update (struct SquidMD5Context *ctx, const void *_buf, unsigned len)
void SquidMD5Final (unsigned char digest[16], struct SquidMD5Context *ctx)
void SquidMD5Transform (uint32_t buf[4], uint32_t const in[16])
Macro Definition Documentation
byteSwap
#define byteSwap (buf, words)
Definition at line 65 of file md5.cc.
F1
#define F1 (x, y, z) (z ^ (x & (y ^ z)))
Definition at line 166 of file md5.cc.
F2
#define F2 (x, y, z) F1(z, x, y)
Definition at line 167 of file md5.cc.
F3
#define F3 (x, y, z) (x ^ y ^ z)
Definition at line 168 of file md5.cc.
F4
#define F4 (x, y, z) (y ^ (x | ~z))
Definition at line 169 of file md5.cc.
MD5STEP
#define MD5STEP (f, w, x, y, z, in, s) (w += f(x,y,z) + in, w = (w<<s | w>>(32-s)) + x)
Definition at line 172 of file md5.cc.
Function Documentation
SquidMD5Final()
void SquidMD5Final (unsigned char digest[16], struct SquidMD5Context * ctx)
Definition at line 130 of file md5.cc.
References SquidMD5Context::buf, SquidMD5Context::bytes, byteSwap, SquidMD5Context::in, and SquidMD5Transform().
SquidMD5Init()
void SquidMD5Init (struct SquidMD5Context * ctx)
Definition at line 73 of file md5.cc.
References SquidMD5Context::buf, and SquidMD5Context::bytes.
Referenced by authDigestNonceEncode(), crypt_md5(), DigestCalcHA1(), DigestCalcResponse(), md5_calc(), md5sum(), PidFilenameHash(), storeKeyPublic(), storeKeyPublicByRequestMethod(), wccp2_check_security(), and wccp2_update_md5_security().
SquidMD5Transform()
void SquidMD5Transform (uint32_t buf[4], uint32_t const in[16])
Definition at line 181 of file md5.cc.
References F1, F2, F3, F4, and MD5STEP.
Referenced by SquidMD5Final(), and SquidMD5Update().
SquidMD5Update()
void SquidMD5Update (struct SquidMD5Context * ctx, const void * _buf, unsigned len)
Definition at line 89 of file md5.cc.
References SquidMD5Context::buf, SquidMD5Context::bytes, byteSwap, SquidMD5Context::in, and SquidMD5Transform().
Referenced by authDigestNonceEncode(), crypt_md5(), DigestCalcHA1(), DigestCalcResponse(), md5_calc(), md5sum(), PidFilenameHash(), storeKeyPublic(), storeKeyPublicByRequestMethod(), wccp2_check_security(), and wccp2_update_md5_security().