Squid Web Cache: squid/test-suite/mem_hdr_test.cc File Reference
mem_hdr_test.cc File Reference
#include "squid.h"
#include "Generic.h"
#include "mem_node.h"
#include "stmem.h"
#include <iostream>
#include <sstream>
Functions
static void testLowAndHigh ()
static void testSplayOfNodes ()
static void testHdrVisit ()
int main (int, char *[])
Function Documentation
main()
int main (int , char * [])
Definition at line 95 of file mem_hdr_test.cc.
References assert, mem_node::InUseCount(), testHdrVisit(), testLowAndHigh(), and testSplayOfNodes().
testHdrVisit()
static void testHdrVisit () static
Definition at line 75 of file mem_hdr_test.cc.
References assert, Splay< V >::begin(), Splay< V >::end(), for_each(), mem_hdr::getNodes(), safe_free, mem_hdr::write(), and xstrdup.
Referenced by main().
testLowAndHigh()
static void testLowAndHigh () static
Definition at line 20 of file mem_hdr_test.cc.
References assert, mem_hdr::endOffset(), mem_hdr::hasContigousContentRange(), mem_hdr::lowestOffset(), safe_free, mem_hdr::write(), and xstrdup.
Referenced by main().
testSplayOfNodes()
static void testSplayOfNodes () static
Definition at line 44 of file mem_hdr_test.cc.
References assert, Splay< V >::destroy(), Splay< V >::find(), Splay< V >::finish(), Splay< V >::insert(), StoreIOBuffer::length, mem_node::nodeBuffer, mem_hdr::NodeCompare, and Splay< V >::start().
Referenced by main().