Squid Web Cache: squid/src/mem/forward.h File Reference
forward.h File Reference
#include "mem/AllocatorProxy.h"
#include <iosfwd>
Namespaces
namespace Mem
Memory Management.
Typedefs
typedef void FREE(void *)
Enumerations
enum mem_type {
MEM_NONE , MEM_32B_BUF , MEM_64B_BUF , MEM_128B_BUF ,
MEM_256B_BUF , MEM_512B_BUF , MEM_1K_BUF , MEM_2K_BUF ,
MEM_4K_BUF , MEM_8K_BUF , MEM_16K_BUF , MEM_32K_BUF ,
MEM_64K_BUF , MEM_MD5_DIGEST , MEM_MAX
}
Types of memory pool which do not yet use MEMPROXY_CLASS() API.
Functions
void Mem::Init ()
void Mem::Stats (StoreEntry *)
void Mem::CleanIdlePools (void *unused)
void Mem::Report (std::ostream &)
void Mem::PoolReport (const PoolStats *, const PoolMeter *, std::ostream &)
void memClean (void)
Main cleanup handler.
void memInitModule (void)
void memCleanModule (void)
void memConfigure (void)
void * memAllocate (mem_type)
Allocate one element from the typed pool.
void * memAllocBuf (size_t net_size, size_t *gross_size)
void * memReallocBuf (void *buf, size_t net_size, size_t *gross_size)
void memFree (void *, int type)
Free a element allocated by memAllocate()
void memFreeBuf (size_t size, void *)
FREE * memFreeBufFunc (size_t size)
int memInUse (mem_type)
Variables
const size_t squidSystemPageSize
Typedef Documentation
FREE
typedef void FREE(void *)
Deprecated:
use MEMPROXY_CLASS instead.
Definition at line 37 of file forward.h.
Enumeration Type Documentation
mem_type
enum mem_type
Enumerator
MEM_NONE
MEM_32B_BUF
MEM_64B_BUF
MEM_128B_BUF
MEM_256B_BUF
MEM_512B_BUF
MEM_1K_BUF
MEM_2K_BUF
MEM_4K_BUF
MEM_8K_BUF
MEM_16K_BUF
MEM_32K_BUF
MEM_64K_BUF
MEM_MD5_DIGEST
MEM_MAX
Definition at line 40 of file forward.h.
Function Documentation
memAllocate()
void * memAllocate (mem_type type)
Definition at line 122 of file old_api.cc.
References Mem::Allocator::alloc(), assert, and GetPool().
Referenced by memAllocBuf(), netdbBinaryExchange(), Ftp::Gateway::parseListing(), and storeKeyDup().
memAllocBuf()
void * memAllocBuf (size_t net_size, size_t * gross_size)
Definition at line 46 of file minimal.cc.
References HugeBufCountMeter, HugeBufVolumeMeter, MEM_NONE, memAllocate(), memFindBufSizeType(), and xmalloc.
Referenced by Ftp::CtrlChannel::CtrlChannel(), PoolingAllocator< Value >::allocate(), String::allocBuffer(), MemBlob::memAlloc(), memReallocBuf(), Helper::Client::openSessions(), statefulhelper::openSessions(), and Rock::IoState::writeToDisk().
memClean()
void memClean (void)
Definition at line 328 of file old_api.cc.
References Mem::PoolStats::chunks_inuse, MemPools::clean(), Config, debugs, MemPools::GetInstance(), Mem::GlobalStats(), Mem::PoolStats::items_inuse, SquidConfig::limit, SquidConfig::MemPools, and MemPools::setIdleLimit().
Referenced by SquidShutdown().
memCleanModule()
void memCleanModule (void)
memConfigure()
void memConfigure (void)
Set to configured value first
Definition at line 254 of file old_api.cc.
References Config, DBG_IMPORTANT, debugs, MemPools::GetInstance(), SquidConfig::limit, SquidConfig::mem_pools, SquidConfig::MemPools, SquidConfig::onoff, and MemPools::setIdleLimit().
Referenced by configDoConfigure().
memFree()
void memFree (void * memory, int type)
Definition at line 61 of file minimal.cc.
References assert, Mem::Allocator::freeOne(), GetPool(), and xfree.
Referenced by Ftp::Gateway::~Gateway(), memFree128B(), memFree16K(), memFree1K(), memFree256B(), memFree2K(), memFree32B(), memFree32K(), memFree4K(), memFree512B(), memFree64B(), memFree64K(), memFree8K(), memFreeBuf(), netdbBinaryExchange(), Ftp::Gateway::parseListing(), and storeKeyFree().
memFreeBuf()
void memFreeBuf (size_t size, void * buf)
Definition at line 67 of file minimal.cc.
References HugeBufCountMeter, HugeBufVolumeMeter, MEM_NONE, memFindBufSizeType(), memFree(), size, and xfree.
Referenced by Ftp::CtrlChannel::~CtrlChannel(), MemBlob::~MemBlob(), Helper::SessionBase::~SessionBase(), MemBuf::clean(), String::clean(), PoolingAllocator< Value >::deallocate(), and memReallocBuf().
memFreeBufFunc()
FREE * memFreeBufFunc (size_t size)
Definition at line 79 of file minimal.cc.
References cxx_xfree(), cxx_xfree(), HugeBufCountMeter, HugeBufVolumeMeter, memFree128B(), memFree16K(), memFree1K(), memFree256B(), memFree2K(), memFree32B(), memFree32K(), memFree4K(), memFree512B(), memFree64B(), memFree64K(), memFree8K(), myFree(), and size.
Referenced by MemBuf::freeFunc(), and Rock::IoState::writeToDisk().
memInitModule()
void memInitModule (void)
memInUse()
int memInUse (mem_type type)
Definition at line 344 of file old_api.cc.
References Mem::Allocator::getInUseCount(), and GetPool().
memReallocBuf()
void * memReallocBuf (void * buf, size_t net_size, size_t * gross_size)
Definition at line 54 of file minimal.cc.
References memAllocBuf(), memFreeBuf(), and xrealloc().
Referenced by MemBuf::grow(), and Ftp::Client::handleControlReply().
Variable Documentation
squidSystemPageSize
const size_t squidSystemPageSize extern