Squid Web Cache: squid/src/MessageDelayPools.h File Reference
MessageDelayPools.h File Reference
#include "acl/Acl.h"
#include "base/RefCount.h"
#include "DelayBucket.h"
#include "DelayPools.h"
#include "sbuf/SBuf.h"
Classes
class MessageDelayPool
class MessageDelayPools
class MessageDelayConfig
represents configuration for response delay pools
Macros
#define free_response_delay_pool_access(X)
#define dump_response_delay_pool_access(X, Y, Z)
Typedefs
typedef RefCount< MessageBucket > MessageBucketPointer
Functions
void free_response_delay_pool_parameters (MessageDelayConfig *cfg)
void dump_response_delay_pool_parameters (StoreEntry *entry, const char *, MessageDelayConfig &cfg)
void parse_response_delay_pool_parameters (MessageDelayConfig *cfg)
void parse_response_delay_pool_access (MessageDelayConfig *cfg)
Macro Definition Documentation
dump_response_delay_pool_access
#define dump_response_delay_pool_access (X, Y, Z)
Definition at line 107 of file MessageDelayPools.h.
free_response_delay_pool_access
#define free_response_delay_pool_access (X)
Definition at line 106 of file MessageDelayPools.h.
Typedef Documentation
MessageBucketPointer
typedef RefCount<MessageBucket> MessageBucketPointer
Definition at line 21 of file MessageDelayPools.h.
Function Documentation
dump_response_delay_pool_parameters()
void dump_response_delay_pool_parameters (StoreEntry * entry, const char * , MessageDelayConfig & cfg) inline
Definition at line 116 of file MessageDelayPools.h.
References MessageDelayConfig::dumpResponseDelayPoolParameters().
free_response_delay_pool_parameters()
void free_response_delay_pool_parameters (MessageDelayConfig * cfg) inline
Definition at line 110 of file MessageDelayPools.h.
References MessageDelayConfig::freePools().
parse_response_delay_pool_access()
void parse_response_delay_pool_access (MessageDelayConfig * cfg) inline
Definition at line 128 of file MessageDelayPools.h.
References MessageDelayConfig::parseResponseDelayPoolAccess().
parse_response_delay_pool_parameters()
void parse_response_delay_pool_parameters (MessageDelayConfig * cfg) inline
Definition at line 122 of file MessageDelayPools.h.
References MessageDelayConfig::parseResponseDelayPool().