Squid Web Cache: squid/lib/snmplib/mib.c File Reference
mib.c File Reference
#include "squid.h"
#include "asn1.h"
#include "snmp.h"
#include "parse.h"
#include "snmp_api.h"
#include "snmp_impl.h"
#include "snmp_pdu.h"
#include "snmp_session.h"
#include "snmp_vars.h"
#include "util.h"
Functions
static struct snmp_mib_tree * get_symbol (oid *objid, int objidlen, struct snmp_mib_tree *subtree, char *buf)
void init_mib (char *file)
static struct snmp_mib_tree * find_rfc1066_mib (struct snmp_mib_tree *root)
static int lc_cmp (const char *s1, const char *s2)
static int parse_subtree (struct snmp_mib_tree *subtree, char *input, oid *output, int *out_len)
int read_objid (char *input, oid *output, int *out_len)
void print_objid (oid *objid, int objidlen)
void sprint_objid (char *buf, oid *objid, int objidlen)
void print_oid_nums (oid *O, int len)
Variables
oid RFC1066_MIB [] = {1, 3, 6, 1, 2, 1}
unsigned char RFC1066_MIB_text [] = ".iso.org.dod.internet.mgmt.mib"
struct snmp_mib_tree * Mib
Function Documentation
find_rfc1066_mib()
static struct snmp_mib_tree * find_rfc1066_mib (struct snmp_mib_tree * root) static
Definition at line 107 of file mib.c.
References snmp_mib_tree::child_list, snmp_mib_tree::next_peer, NULL, RFC1066_MIB, and snmp_mib_tree::subid.
Referenced by read_objid().
get_symbol()
static struct snmp_mib_tree * get_symbol (oid * objid, int objidlen, struct snmp_mib_tree * subtree, char * buf) static
Definition at line 285 of file mib.c.
References snmp_mib_tree::child_list, get_symbol(), snmp_mib_tree::label, snmp_mib_tree::next_peer, NULL, and snmp_mib_tree::subid.
Referenced by get_symbol(), print_objid(), and sprint_objid().
init_mib()
void init_mib (char * file)
Definition at line 97 of file mib.c.
References Mib, NULL, and read_mib().
lc_cmp()
static int lc_cmp (const char * s1, const char * s2) static
Definition at line 126 of file mib.c.
References s1, xisupper, and xtolower.
Referenced by parse_subtree().
parse_subtree()
static int parse_subtree (struct snmp_mib_tree * subtree, char * input, oid * output, int * out_len) static
Definition at line 153 of file mib.c.
References snmp_mib_tree::child_list, snmp_mib_tree::label, lc_cmp(), MAX_SUBID, snmp_mib_tree::next_peer, NULL, parse_subtree(), snmplib_debug(), snmp_mib_tree::subid, and xisdigit.
Referenced by parse_subtree(), and read_objid().
print_objid()
void print_objid (oid * objid, int objidlen)
Parameters
objidlen number of subidentifiers
Definition at line 263 of file mib.c.
References get_symbol(), Mib, and snmplib_debug().
print_oid_nums()
void print_oid_nums (oid * O, int len)
Definition at line 320 of file mib.c.
read_objid()
int read_objid (char * input, oid * output, int * out_len)
Parameters
out_len number of subid's in "output"
Definition at line 230 of file mib.c.
References find_rfc1066_mib(), Mib, NULL, parse_subtree(), RFC1066_MIB, and snmplib_debug().
sprint_objid()
void sprint_objid (char * buf, oid * objid, int objidlen)
Parameters
objidlen number of subidentifiers
Definition at line 276 of file mib.c.
References get_symbol(), and Mib.
Variable Documentation
Mib
struct snmp_mib_tree* Mib
Definition at line 94 of file mib.c.
Referenced by init_mib(), print_objid(), read_objid(), and sprint_objid().
RFC1066_MIB
oid RFC1066_MIB[] = {1, 3, 6, 1, 2, 1}
Definition at line 92 of file mib.c.
Referenced by find_rfc1066_mib(), and read_objid().
RFC1066_MIB_text
unsigned char RFC1066_MIB_text[] = ".iso.org.dod.internet.mgmt.mib"
Definition at line 93 of file mib.c.