Squid Web Cache: squid/src/mime.h File Reference
mime.h File Reference
Functions
void mimeInit (char *filename)
const char * mimeGetContentEncoding (const char *fn)
const char * mimeGetContentType (const char *fn)
const char * mimeGetIconURL (const char *fn)
char mimeGetTransferMode (const char *fn)
bool mimeGetDownloadOption (const char *fn)
bool mimeGetViewOption (const char *fn)
Function Documentation
mimeGetContentEncoding()
const char * mimeGetContentEncoding (const char * fn)
Definition at line 195 of file mime.cc.
References MimeEntry::content_encoding, dash_str, and mimeGetEntry().
Referenced by Ftp::Gateway::appendSuccessHeader().
mimeGetContentType()
const char * mimeGetContentType (const char * fn)
Definition at line 181 of file mime.cc.
References MimeEntry::content_type, dash_str, and mimeGetEntry().
Referenced by Ftp::Gateway::appendSuccessHeader(), and MimeIcon::load().
mimeGetDownloadOption()
bool mimeGetDownloadOption (const char * fn)
Definition at line 216 of file mime.cc.
References MimeEntry::download_option, and mimeGetEntry().
Referenced by Ftp::Gateway::htmlifyListEntry().
mimeGetIconURL()
const char * mimeGetIconURL (const char * fn)
Definition at line 162 of file mime.cc.
References SBuf::append(), SBuf::c_str(), SBuf::clear(), Config, SquidConfig::icons, internalLocalUri(), SBuf::isEmpty(), mimeGetIcon(), null_string, and SquidConfig::use_short_names.
Referenced by Ftp::Gateway::htmlifyListEntry().
mimeGetTransferMode()
char mimeGetTransferMode (const char * fn)
Definition at line 209 of file mime.cc.
References mimeGetEntry(), and MimeEntry::transfer_mode.
Referenced by ftpSendType().
mimeGetViewOption()
bool mimeGetViewOption (const char * fn)
Definition at line 223 of file mime.cc.
References mimeGetEntry(), and MimeEntry::view_option.
Referenced by Ftp::Gateway::htmlifyListEntry().
mimeInit()
void mimeInit (char * filename)
Definition at line 235 of file mime.cc.
References BUFSIZ, CurrentException(), DBG_IMPORTANT, debugs, Important, MimeIcon::load(), mimeFreeMemory(), MimeTable, MimeTableTail, MimeEntry::next, O_TEXT, MimeEntry::theIcon, w_space, xstrerr(), and xstrncpy().
Referenced by mainInitialize(), and mainReconfigureFinish().