Squid Web Cache: squid/src/mime_header.cc File Reference
mime_header.cc File Reference
#include "squid.h"
#include "debug/Stream.h"
#include "mime_header.h"
#include "sbuf/SBuf.h"
Functions
size_t headersEnd (const char *mime, size_t l, bool &containsObsFold)
size_t headersEnd (const SBuf &buf, bool &containsObsFold)
Function Documentation
headersEnd() [1/2]
size_t headersEnd (const char * mime, size_t l, bool & containsObsFold)
Scan for the end of mime header block.
Which is one of the following octet patterns:
CRLF CRLF, or
CRLF LF, or
LF CRLF, or
LF LF or, if mime header block is empty:
LF or
CRLF
Also detects whether a obf-fold pattern exists within the mime block
CR*LF (SP / HTAB)
Parameters
containsObsFold will be set to true if obs-fold pattern is found.
Definition at line 17 of file mime_header.cc.
Referenced by detailEntryEnd(), Http::One::Parser::grabMimeBlock(), headersEnd(), headersEnd(), HttpHeader::Isolate(), Http::Message::parse(), Rock::HeaderUpdater::parseReadBytes(), TestHttpReply::testSanityCheckFirstLine(), and TestHttpRequest::testSanityCheckStartLine().
headersEnd() [2/2]
size_t headersEnd (const SBuf & buf, bool & containsObsFold)
Definition at line 68 of file mime_header.cc.
References headersEnd(), SBuf::length(), and SBuf::rawContent().