Squid Web Cache: squid/src/log/ModDaemon.h File Reference
ModDaemon.h File Reference
Functions
int logfile_mod_daemon_open (Logfile *lf, const char *path, size_t bufsz, int fatal_flag)
Function Documentation
logfile_mod_daemon_open()
int logfile_mod_daemon_open (Logfile * lf, const char * path, size_t bufsz, int fatal_flag)
Definition at line 210 of file ModDaemon.cc.
References SquidConfig::buffered_logs, BUFSIZ, cbdataInternalLock(), Config, Logfile::data, DBG_IMPORTANT, debugs, _l_daemon::eol, eventAdd(), Logfile::f_close, Logfile::f_flush, Logfile::f_lineend, Logfile::f_linestart, Logfile::f_linewrite, Logfile::f_rotate, fatal(), IPC_STREAM, ipcCreate(), SquidConfig::Log, logfile_mod_daemon_append(), logfile_mod_daemon_close, logfile_mod_daemon_flush, logfile_mod_daemon_lineend, logfile_mod_daemon_linestart, logfile_mod_daemon_rotate, logfile_mod_daemon_writeline, logfileFlushEvent(), _l_daemon::nbufs, SquidConfig::onoff, _l_daemon::pid, _l_daemon::rfd, SquidConfig::rotateNumber, Ip::Address::setLocalhost(), Log::TheConfig, _l_daemon::wfd, xcalloc(), xfree, and xmalloc.
Referenced by logfileOpen().