Squid Web Cache: squid/src/comm/ModEpoll.cc File Reference
ModEpoll.cc File Reference
#include "squid.h"
#include "base/CodeContext.h"
#include "base/IoManip.h"
#include "comm/Loops.h"
#include "fde.h"
#include "globals.h"
#include "mgr/Registration.h"
#include "StatCounters.h"
#include "StatHist.h"
#include "Store.h"
#include <cerrno>
Macros
#define DEBUG_EPOLL 0
Functions
static void commEPollRegisterWithCacheManager (void)
static const char * epolltype_atoi (int x)
static void commIncomingStats (StoreEntry *sentry)
Variables
static int kdpfd = -1
static int max_poll_time = 1000
static struct epoll_event * pevents
Macro Definition Documentation
DEBUG_EPOLL
#define DEBUG_EPOLL 0
Definition at line 45 of file ModEpoll.cc.
Function Documentation
commEPollRegisterWithCacheManager()
static void commEPollRegisterWithCacheManager (void) static
Definition at line 192 of file ModEpoll.cc.
References commIncomingStats, and Mgr::RegisterAction().
commIncomingStats()
static void commIncomingStats (StoreEntry * sentry) static
Definition at line 200 of file ModEpoll.cc.
References StatHist::dump(), StatCounters::select_fds_hist, StatCounters::select_loops, statCounter, statHistIntDumper, and storeAppendPrintf().
epolltype_atoi()
static const char * epolltype_atoi (int x) static
Definition at line 86 of file ModEpoll.cc.
Variable Documentation
kdpfd
int kdpfd = -1 static
Definition at line 52 of file ModEpoll.cc.
max_poll_time
int max_poll_time = 1000 static
Definition at line 53 of file ModEpoll.cc.
pevents
struct epoll_event* pevents static
Definition at line 55 of file ModEpoll.cc.