Squid Web Cache: squid/src/comm/ModPoll.cc File Reference
ModPoll.cc File Reference
#include "squid.h"
#include "anyp/PortCfg.h"
#include "comm/Connection.h"
#include "comm/Loops.h"
#include "fd.h"
#include "fde.h"
#include "globals.h"
#include "ICP.h"
#include "mgr/Registration.h"
#include "SquidConfig.h"
#include "StatCounters.h"
#include "Store.h"
#include <cerrno>
Macros
#define POLLRDNORM POLLIN
#define POLLWRNORM POLLOUT
#define howmany(x, y) (((x)+((y)-1))/(y))
#define NBBY 8
#define FD_MASK_BYTES sizeof(fd_mask)
#define FD_MASK_BITS (FD_MASK_BYTES*NBBY)
Functions
static int fdIsTcpListen (int fd)
static int fdIsUdpListen (int fd)
static int fdIsDns (int fd)
static int comm_check_incoming_poll_handlers (int nfds, int *fds)
static void comm_poll_dns_incoming (void)
static void comm_poll_udp_incoming (void)
static void comm_poll_tcp_incoming (void)
static void commPollRegisterWithCacheManager (void)
static void commIncomingStats (StoreEntry *sentry)
Variables
static int MAX_POLL_TIME = 1000
static OBJH commIncomingStats
Macro Definition Documentation
FD_MASK_BITS
#define FD_MASK_BITS (FD_MASK_BYTES*NBBY)
Definition at line 50 of file ModPoll.cc.
FD_MASK_BYTES
#define FD_MASK_BYTES sizeof(fd_mask)
Definition at line 49 of file ModPoll.cc.
howmany
#define howmany (x, y) (((x)+((y)-1))/(y))
Definition at line 44 of file ModPoll.cc.
NBBY
#define NBBY 8
Definition at line 47 of file ModPoll.cc.
POLLRDNORM
#define POLLRDNORM POLLIN
Definition at line 34 of file ModPoll.cc.
POLLWRNORM
#define POLLWRNORM POLLOUT
Definition at line 37 of file ModPoll.cc.
Function Documentation
comm_check_incoming_poll_handlers()
static int comm_check_incoming_poll_handlers (int nfds, int * fds) static
Definition at line 120 of file ModPoll.cc.
References DBG_IMPORTANT, debugs, fd_table, getCurrentTime(), incoming_sockets_accepted, MAXTCPLISTENPORTS, pfds, POLLRDNORM, POLLWRNORM, StatCounters::selects, statCounter, and StatCounters::syscalls.
Referenced by comm_poll_dns_incoming(), comm_poll_tcp_incoming(), and comm_poll_udp_incoming().
comm_poll_dns_incoming()
static void comm_poll_dns_incoming (void) static
Definition at line 456 of file ModPoll.cc.
References comm_check_incoming_poll_handlers(), StatCounters::comm_dns, SquidConfig::comm_incoming, Config, SquidConfig::CommIncoming::dns, DnsSocketA, DnsSocketB, Comm::Incoming::finishPolling(), Comm::Incoming::startPolling(), and statCounter.
comm_poll_tcp_incoming()
static void comm_poll_tcp_incoming (void) static
Definition at line 207 of file ModPoll.cc.
References comm_check_incoming_poll_handlers(), SquidConfig::comm_incoming, StatCounters::comm_tcp, Config, Comm::Incoming::finishPolling(), HttpPortList, Comm::IsConnOpen(), MAXTCPLISTENPORTS, Comm::Incoming::startPolling(), statCounter, and SquidConfig::CommIncoming::tcp.
comm_poll_udp_incoming()
static void comm_poll_udp_incoming (void) static
Definition at line 185 of file ModPoll.cc.
References comm_check_incoming_poll_handlers(), SquidConfig::comm_incoming, StatCounters::comm_udp, Config, Comm::Connection::fd, Comm::Incoming::finishPolling(), icpIncomingConn, icpOutgoingConn, Comm::IsConnOpen(), Comm::Incoming::startPolling(), statCounter, and SquidConfig::CommIncoming::udp.
commIncomingStats()
static void commIncomingStats (StoreEntry * sentry) static
Definition at line 492 of file ModPoll.cc.
References StatCounters::comm_dns, StatCounters::comm_tcp, StatCounters::comm_udp, StatHist::dump(), Comm::Incoming::Factor, Comm::Incoming::history, Comm::Incoming::interval, statCounter, statHistIntDumper, and storeAppendPrintf().
commPollRegisterWithCacheManager()
static void commPollRegisterWithCacheManager (void) static
Definition at line 478 of file ModPoll.cc.
References commIncomingStats, and Mgr::RegisterAction().
fdIsDns()
static int fdIsDns (int fd) static
Definition at line 97 of file ModPoll.cc.
References DnsSocketA, and DnsSocketB.
fdIsTcpListen()
static int fdIsTcpListen (int fd) static
Definition at line 109 of file ModPoll.cc.
References HttpPortList.
fdIsUdpListen()
static int fdIsUdpListen (int fd) static
Definition at line 85 of file ModPoll.cc.
References Comm::Connection::fd, icpIncomingConn, and icpOutgoingConn.
Variable Documentation
commIncomingStats
OBJH commIncomingStats static
Definition at line 56 of file ModPoll.cc.
Referenced by commDevPollRegisterWithCacheManager(), commEPollRegisterWithCacheManager(), and commPollRegisterWithCacheManager().
MAX_POLL_TIME
int MAX_POLL_TIME = 1000 static
Definition at line 41 of file ModPoll.cc.