Squid Web Cache: squid/src/log/ModStdio.h File Reference
ModStdio.h File Reference
Functions
int logfile_mod_stdio_open (Logfile *lf, const char *path, size_t bufsz, int fatal_flag)
Function Documentation
logfile_mod_stdio_open()
int logfile_mod_stdio_open (Logfile * lf, const char * path, size_t bufsz, int fatal_flag)
Definition at line 177 of file ModStdio.cc.
References l_stdio_t::buf, l_stdio_t::bufsz, Config, Logfile::data, DBG_IMPORTANT, debugs, DISK_ERROR, SquidConfig::effectiveUser, Logfile::f_close, Logfile::f_flush, Logfile::f_lineend, Logfile::f_linestart, Logfile::f_linewrite, Logfile::f_rotate, fatalf(), l_stdio_t::fd, file_open(), logfile_mod_stdio_close(), logfile_mod_stdio_flush(), logfile_mod_stdio_lineend(), logfile_mod_stdio_linestart(), logfile_mod_stdio_rotate(), logfile_mod_stdio_writeline(), MYNAME, O_TEXT, Logfile::path, xcalloc(), xmalloc, and xstrerr().
Referenced by logfileOpen().