Squid Web Cache: squid/src/log/ModUdp.h File Reference
ModUdp.h File Reference
Functions
int logfile_mod_udp_open (Logfile *lf, const char *path, size_t bufsz, int fatal_flag)
Function Documentation
logfile_mod_udp_open()
int logfile_mod_udp_open (Logfile * lf, const char * path, size_t bufsz, int fatal_flag)
Definition at line 135 of file ModUdp.cc.
References l_udp_t::buf, l_udp_t::bufsz, comm_connect_addr(), Comm::COMM_ERROR, COMM_NONBLOCKING, comm_open(), Config, Logfile::data, DBG_IMPORTANT, debugs, SquidConfig::effectiveUser, Logfile::f_close, Logfile::f_flush, Logfile::f_lineend, Logfile::f_linestart, Logfile::f_linewrite, Logfile::f_rotate, FALSE, Logfile::fatal, fatalf(), l_udp_t::fd, Logfile::flags, GetHostWithPort(), Ip::Address::isIPv4(), logfile_mod_udp_close(), logfile_mod_udp_flush(), logfile_mod_udp_lineend(), logfile_mod_udp_linestart(), logfile_mod_udp_rotate(), logfile_mod_udp_writeline(), Logfile::path, safe_free, Ip::Address::setAnyAddr(), Ip::Address::setIPv4(), xcalloc(), xmalloc, xstrdup, and xstrerr().
Referenced by logfileOpen().