Squid Web Cache: squid/src/adaptation/icap/ModXact.cc File Reference
ModXact.cc File Reference
#include "squid.h"
#include "AccessLogEntry.h"
#include "adaptation/Answer.h"
#include "adaptation/History.h"
#include "adaptation/icap/Client.h"
#include "adaptation/icap/Config.h"
#include "adaptation/icap/History.h"
#include "adaptation/icap/Launcher.h"
#include "adaptation/icap/ModXact.h"
#include "adaptation/icap/ServiceRep.h"
#include "adaptation/Initiator.h"
#include "auth/UserRequest.h"
#include "base/TextException.h"
#include "base64.h"
#include "comm.h"
#include "comm/Connection.h"
#include "error/Detail.h"
#include "error/ExceptionErrorDetail.h"
#include "http/ContentLengthInterpreter.h"
#include "HttpHeaderTools.h"
#include "HttpReply.h"
#include "MasterXaction.h"
#include "parser/Tokenizer.h"
#include "sbuf/Stream.h"
Functions
CBDATA_NAMESPACED_CLASS_INIT (Adaptation::Icap, ModXact)
CBDATA_NAMESPACED_CLASS_INIT (Adaptation::Icap, ModXactLauncher)
void prepareLogWithRequestDetails (HttpRequest *, const AccessLogEntryPointer &)
Variables
static constexpr auto TheBackupLimit = BodyPipe::MaxCapacity
Function Documentation
CBDATA_NAMESPACED_CLASS_INIT() [1/2]
CBDATA_NAMESPACED_CLASS_INIT (Adaptation::Icap , ModXact)
CBDATA_NAMESPACED_CLASS_INIT() [2/2]
CBDATA_NAMESPACED_CLASS_INIT (Adaptation::Icap , ModXactLauncher)
prepareLogWithRequestDetails()
void prepareLogWithRequestDetails (HttpRequest * request, const AccessLogEntryPointer & aLogEntry)
Definition at line 322 of file client_side.cc.
References AccessLogEntry::adapt, AccessLogEntry::Headers::adapted_request, HttpRequest::adaptLogHistory(), assert, MemBuf::buf, AccessLogEntry::cache, MemBuf::clean(), Config, HttpRequest::dnsWait, HttpRequest::error, HttpRequest::extacl_user, AccessLogEntry::CacheDetails::extuser, Http::Message::header, AccessLogEntry::headers, AccessLogEntry::hier, HttpRequest::hier, AccessLogEntry::http, Http::Message::http_ver, AccessLogEntry::icap, HttpRequest::icapHistory(), MemBuf::init(), AccessLogEntry::AdaptationDetails::last_meta, Adaptation::History::lastMeta, SquidConfig::log_mime_hdrs, AccessLogEntry::HttpDetails::method, HttpRequest::method, SquidConfig::onoff, HttpHeader::packInto(), AccessLogEntry::IcapLogEntry::processingTime, AccessLogEntry::Headers::request, AccessLogEntry::request, MemBuf::reset(), String::termedBuf(), AccessLogEntry::HttpDetails::version, and xstrdup.
Referenced by Adaptation::Icap::ModXact::finalizeLogInfo(), and ClientHttpRequest::logRequest().
Variable Documentation
TheBackupLimit
constexpr auto TheBackupLimit = BodyPipe::MaxCapacity static constexpr
Definition at line 45 of file ModXact.cc.
Referenced by Adaptation::Icap::ModXact::canBackupEverything(), Adaptation::Icap::ModXact::decideOnPreview(), and Adaptation::Icap::ModXact::estimateVirginBody().