Squid Web Cache: Helper Namespace Reference
Helper Namespace Reference
helper protocol primitives
Classes
class ChildConfig
class Client
class Reply
class Request
class ReservationId
a (temporary) lock on a (stateful) helper channel
class Session
class SessionBase
represents a single helper process
class Xaction
Holds the required data to serve a helper request.
Typedefs
using ClientPointer = RefCount< Client >
using StatefulClientPointer = RefCount< statefulhelper >
Enumerations
enum ResultCode {
Unknown , Okay , Error , BrokenHelper ,
TimedOut , TT
}
enumeration value for the helper response 'result' field.
Functions
std::ostream & operator<< (std::ostream &, const Reply &)
std::ostream & operator<< (std::ostream &os, const ReservationId &id)
Typedef Documentation
ClientPointer
using Helper::ClientPointer = typedef RefCount<Client>
Definition at line 28 of file forward.h.
StatefulClientPointer
using Helper::StatefulClientPointer = typedef RefCount<statefulhelper>
Definition at line 29 of file forward.h.
Enumeration Type Documentation
ResultCode
enum Helper::ResultCode
Enumerator
Unknown
Okay
Error
BrokenHelper
TimedOut
TT
Definition at line 16 of file ResultCode.h.
Function Documentation
operator<<() [1/2]
std::ostream & Helper::operator<< (std::ostream & os, const Reply & r)
Definition at line 254 of file Reply.cc.
References BrokenHelper, MemBuf::content(), NotePairs::empty(), Error, MemBuf::hasContent(), Helper::Reply::notes, Okay, Helper::Reply::other(), NotePairs::print(), Helper::Reply::result, TimedOut, TT, and Unknown.
operator<<() [2/2]
std::ostream & Helper::operator<< (std::ostream & os, const ReservationId & id) inline
Definition at line 39 of file ReservationId.h.