Squid Web Cache: AnyP Namespace Reference
AnyP Namespace Reference
Classes
class Bracketed
class Host
either a domain name (as defined in DNS RFC 1034) or an IP address
class PortCfg
class ProtocolVersion
class TrafficMode
class Uri
class UriScheme
Typedefs
typedef RefCount< PortCfg > PortCfgPointer
using KnownPort = uint16_t
validated/supported port number; these values are never zero
using Port = std::optional< KnownPort >
validated/supported port number (if any)
Enumerations
enum ProtocolType {
PROTO_NONE = 0 , PROTO_HTTP , PROTO_FTP , PROTO_HTTPS ,
PROTO_COAP , PROTO_COAPS , PROTO_WAIS , PROTO_ICP ,
PROTO_HTCP , PROTO_URN , PROTO_WHOIS , PROTO_ICY ,
PROTO_TLS , PROTO_SSL , PROTO_AUTHORITY_FORM , PROTO_UNKNOWN ,
PROTO_MAX
}
Functions
std::ostream & operator<< (std::ostream &, const Host &)
std::ostream & operator<< (std::ostream &, const Bracketed &)
std::ostream & operator<< (std::ostream &os, ProtocolType const &p)
std::ostream & operator<< (std::ostream &os, const ProtocolVersion &v)
std::ostream & operator<< (std::ostream &os, const Uri &url)
std::ostream & operator<< (std::ostream &os, const UriScheme &scheme)
Variables
const char * ProtocolType_str []
Typedef Documentation
KnownPort
using AnyP::KnownPort = typedef uint16_t
Definition at line 23 of file UriScheme.h.
Port
using AnyP::Port = typedef std::optional<KnownPort>
Definition at line 26 of file UriScheme.h.
PortCfgPointer
typedef RefCount<PortCfg> AnyP::PortCfgPointer
Definition at line 18 of file forward.h.
Enumeration Type Documentation
ProtocolType
enum AnyP::ProtocolType
List of all protocols known and supported. This is a combined list. It is used as type-codes where needed and the AnyP::ProtocolType_Str array of strings may be used for display
Enumerator
PROTO_NONE
PROTO_HTTP
PROTO_FTP
PROTO_HTTPS
PROTO_COAP
PROTO_COAPS
PROTO_WAIS
PROTO_ICP
PROTO_HTCP
PROTO_URN
PROTO_WHOIS
PROTO_ICY
PROTO_TLS
PROTO_SSL
PROTO_AUTHORITY_FORM
PROTO_UNKNOWN
PROTO_MAX
Definition at line 23 of file ProtocolType.h.
Function Documentation
operator<<() [1/6]
std::ostream & AnyP::operator<< (std::ostream & os, const Bracketed & hostWrapper)
prints Host value without square brackets around an IPv6 address (even when the Host value is an IPv6 address);
See also
Bracketed
Definition at line 98 of file Host.cc.
References AnyP::Bracketed::host, and AnyP::Host::ip().
operator<<() [2/6]
std::ostream & AnyP::operator<< (std::ostream & os, const Host & host)
prints Host value without square brackets around an IPv6 address (even when the Host value is an IPv6 address);
See also
Bracketed
Definition at line 79 of file Host.cc.
References Assure, AnyP::Host::domainName(), AnyP::Host::ip(), and MAX_IPSTRLEN.
operator<<() [3/6]
std::ostream & AnyP::operator<< (std::ostream & os, const ProtocolVersion & v) inline
Definition at line 94 of file ProtocolVersion.h.
References AnyP::ProtocolVersion::major, AnyP::ProtocolVersion::minor, AnyP::ProtocolVersion::protocol, and ProtocolType_str.
operator<<() [4/6]
std::ostream & AnyP::operator<< (std::ostream & os, const Uri & url) inline
Definition at line 204 of file Uri.h.
References AnyP::Uri::absolutePath(), AnyP::Uri::authority(), AnyP::Uri::getScheme(), AnyP::UriScheme::image(), PROTO_NONE, and PROTO_URN.
operator<<() [5/6]
std::ostream & AnyP::operator<< (std::ostream & os, const UriScheme & scheme) inline
Definition at line 79 of file UriScheme.h.
References AnyP::UriScheme::image().
operator<<() [6/6]
std::ostream & AnyP::operator<< (std::ostream & os, ProtocolType const & p) inline
Display the registered Protocol Type (in upper case). If the protocol is not a registered AnyP::ProtocolType nothing will be displayed. The caller is responsible for any alternative text.
Definition at line 51 of file ProtocolType.h.
References PROTO_MAX, PROTO_NONE, and ProtocolType_str.
Variable Documentation
ProtocolType_str
const char* AnyP::ProtocolType_str[] extern
Referenced by HttpHeader::addVia(), HttpStateData::buildRequestPrefix(), Security::ServerOptions::createSigningContexts(), ACLProtocolData::dump(), dump_generic_port(), Log::Format::HttpdCombined(), Log::Format::HttpdCommon(), AnyP::UriScheme::Init(), Security::ServerOptions::initServerContexts(), operator<<(), operator<<(), ACLProtocolData::parse(), Security::NegotiationHistory::printTlsVersion(), and urlInitialize().