Squid Web Cache: Math Namespace Reference
Math Namespace Reference
Functions
int intPercent (const int a, const int b)
int64_t int64Percent (const int64_t a, const int64_t b)
double doublePercent (const double, const double)
int intAverage (const int, const int, int, const int)
double doubleAverage (const double, const double, int, const int)
Variables
hbase_f Log
hbase_f Exp
hbase_f Null
Function Documentation
doubleAverage()
double Math::doubleAverage (const double cur, const double newD, int N, const int max)
Definition at line 31 of file SquidMath.cc.
References cur, and max().
Referenced by peerCountMcastPeersAbort().
doublePercent()
double Math::doublePercent (const double a, const double b)
Definition at line 25 of file SquidMath.cc.
Referenced by DumpAvgStat(), DumpInfo(), DumpIoStats(), GetInfo(), snmp_prfSysFn(), Store::Controller::stat(), MemStore::stat(), Transients::stat(), statByteHitRatio(), statCPUUsage(), Fs::Ufs::UFSSwapDir::statfs(), Rock::SwapDir::statfs(), statRequestHitDiskRatio(), statRequestHitMemoryRatio(), and statRequestHitRatio().
int64Percent()
int64_t Math::int64Percent (const int64_t a, const int64_t b)
Definition at line 19 of file SquidMath.cc.
Referenced by Rock::Rebuild::failure().
intAverage()
int Math::intAverage (const int cur, const int newI, int n, const int max)
Definition at line 40 of file SquidMath.cc.
References cur, and max().
Referenced by helperReturnBuffer(), helperStatefulHandleRead(), neighborUpdateRtt(), and peerCountHandleIcpReply().
intPercent()
int Math::intPercent (const int a, const int b)
Definition at line 13 of file SquidMath.cc.
References int.
Referenced by clientdbDump(), dump_peers(), dumpMallocStats(), and Fs::Ufs::UFSSwapDir::statfs().
Variable Documentation
Exp
double Math::Exp
Definition at line 20 of file StatHist.cc.
Referenced by StatHist::logInit().
Log
double Math::Log
Definition at line 19 of file StatHist.cc.
Referenced by StatHist::logInit().
Null
double Math::Null
Definition at line 21 of file StatHist.cc.
Referenced by StatHist::enumInit().