Squid Web Cache: Adaptation Namespace Reference
Adaptation Namespace Reference
Namespaces
namespace Ecap
namespace Icap
Classes
class AccessCheck
class AccessRule
class Answer
summarizes adaptation service answer for the noteAdaptationAnswer() API
class AnswerCall
class Config
class DynamicGroupCfg
DynamicServiceGroup configuration to remember future dynamic chains.
class DynamicServiceChain
a temporary service chain built upon another service request
class History
collects information about adaptations related to a master transaction
class Initiate
class Initiator
class Iterator
iterates services in ServiceGroup, starting adaptation launchers
class Message
class Service
class ServiceChain
a group of services that must be used one after another
class ServiceConfig
class ServiceFilter
information used to search for adaptation services
class ServiceGroup
class ServicePlan
class ServiceSet
class SingleService
Typedefs
typedef std::vector< Adaptation::AccessRule * > AccessRules
typedef RefCount< Service > ServicePointer
typedef RefCount< ServiceConfig > ServiceConfigPointer
typedef RefCount< ServiceGroup > ServiceGroupPointer
typedef UnaryMemFunT< Initiator, Answer, const Answer & > AnswerDialer
typedef std::vector< Adaptation::ServicePointer > Services
typedef std::vector< ServiceGroupPointer > Groups
Enumerations
enum Method { methodNone , methodReqmod , methodRespmod , methodOptions }
enum VectPoint { pointNone , pointPreCache , pointPostCache }
enum SrvBehaviour { srvBlock , srvBypass , srvWait , srvForce }
Functions
AccessRules & AllRules ()
AccessRule * FindRule (const AccessRule::Id &id)
AccessRule * FindRuleByGroupId (const String &groupId)
std::ostream & operator<< (std::ostream &os, const Answer &answer)
std::ostream & operator<< (std::ostream &os, const DynamicGroupCfg &cfg)
const char * methodStr (Method)
const char * vectPointStr (VectPoint)
Services & AllServices ()
ServicePointer FindService (const Service::Id &key)
void DetachServices ()
detach all adaptation services from current configuration
std::ostream & operator<< (std::ostream &, const ServiceFilter &)
std::ostream & operator<< (std::ostream &os, const ServicePlan &p)
Groups & AllGroups ()
ServiceGroupPointer FindGroup (const ServiceGroup::Id &id)
Variables
const char * crlf = "\r\n"
Typedef Documentation
AccessRules
typedef std::vector<Adaptation::AccessRule*> Adaptation::AccessRules
Definition at line 47 of file AccessRule.h.
AnswerDialer
typedef UnaryMemFunT<Initiator, Answer, const Answer &> Adaptation::AnswerDialer
Definition at line 20 of file Initiate.cc.
Groups
typedef std::vector<ServiceGroupPointer> Adaptation::Groups
Definition at line 153 of file ServiceGroups.h.
ServiceConfigPointer
typedef RefCount<ServiceConfig> Adaptation::ServiceConfigPointer
Definition at line 35 of file forward.h.
ServiceGroupPointer
typedef RefCount<ServiceGroup> Adaptation::ServiceGroupPointer
Definition at line 36 of file forward.h.
ServicePointer
typedef Service::Pointer Adaptation::ServicePointer
Definition at line 34 of file forward.h.
Services
typedef std::vector<Adaptation::ServicePointer> Adaptation::Services
Definition at line 70 of file Service.h.
Enumeration Type Documentation
Method
enum Adaptation::Method
Enumerator
methodNone
methodReqmod
methodRespmod
methodOptions
Definition at line 17 of file Elements.h.
SrvBehaviour
enum Adaptation::SrvBehaviour
Enumerator
srvBlock
srvBypass
srvWait
srvForce
Definition at line 19 of file Elements.h.
VectPoint
enum Adaptation::VectPoint
Enumerator
pointNone
pointPreCache
pointPostCache
Definition at line 18 of file Elements.h.
Function Documentation
AllGroups()
Adaptation::Groups & Adaptation::AllGroups ()
Definition at line 324 of file ServiceGroups.cc.
Referenced by Adaptation::Config::clear(), Adaptation::Config::DumpServiceGroups(), Adaptation::AccessRule::finalize(), Adaptation::Config::Finalize(), FindGroup(), Adaptation::Config::FreeServiceGroups(), Adaptation::Config::ParseServiceGroup(), and Adaptation::Config::removeService().
AllRules()
Adaptation::AccessRules & Adaptation::AllRules ()
Definition at line 61 of file AccessRule.cc.
Referenced by Adaptation::AccessCheck::check(), Adaptation::Config::clear(), Adaptation::Config::DumpAccess(), Adaptation::Config::Finalize(), FindRule(), FindRuleByGroupId(), Adaptation::Config::FreeAccess(), Adaptation::Config::ParseAccess(), and Adaptation::Config::removeRule().
AllServices()
Adaptation::Services & Adaptation::AllServices ()
Definition at line 61 of file Service.cc.
References TheServices.
Referenced by DetachServices(), Adaptation::Config::dumpService(), Adaptation::Config::finalize(), Adaptation::Ecap::Config::finalize(), Adaptation::Config::Finalize(), and FindService().
DetachServices()
void Adaptation::DetachServices ()
Definition at line 78 of file Service.cc.
References AllServices(), and Adaptation::Service::detach().
Referenced by Adaptation::Config::freeService().
FindGroup()
Adaptation::ServiceGroupPointer Adaptation::FindGroup (const ServiceGroup::Id & id)
Definition at line 331 of file ServiceGroups.cc.
References AllGroups().
Referenced by Adaptation::AccessRule::group(), Adaptation::AccessCheck::isCandidate(), ACLAdaptationServiceData::parse(), and Adaptation::AccessCheck::topGroup().
FindRule()
Adaptation::AccessRule * Adaptation::FindRule (const AccessRule::Id & id)
Definition at line 69 of file AccessRule.cc.
References AllRules().
Referenced by Adaptation::AccessCheck::checkCandidates(), and Adaptation::AccessCheck::topGroup().
FindRuleByGroupId()
Adaptation::AccessRule * Adaptation::FindRuleByGroupId (const String & groupId)
Definition at line 81 of file AccessRule.cc.
References AllRules().
Referenced by Adaptation::Config::ParseAccess().
FindService()
Adaptation::ServicePointer Adaptation::FindService (const Service::Id & key)
Definition at line 68 of file Service.cc.
References AllServices().
Referenced by Adaptation::ServiceGroup::at(), Adaptation::AccessRule::finalize(), Adaptation::Config::finalize(), and Adaptation::DynamicServiceChain::Split().
methodStr()
const char * Adaptation::methodStr (Adaptation::Method method)
Definition at line 15 of file Elements.cc.
References methodOptions, methodReqmod, and methodRespmod.
Referenced by Adaptation::Icap::ServiceRep::checkOptions(), Adaptation::ServiceConfig::methodStr(), operator<<(), and Adaptation::ServiceConfig::parse().
operator<<() [1/4]
std::ostream & Adaptation::operator<< (std::ostream & os, const ServiceFilter & filter)
Definition at line 66 of file ServiceFilter.cc.
References Adaptation::ServiceFilter::method, methodStr(), Adaptation::ServiceFilter::point, and vectPointStr().
operator<<() [2/4]
std::ostream & Adaptation::operator<< (std::ostream & os, const Answer & answer) inline
Definition at line 54 of file Answer.h.
References Adaptation::Answer::print().
operator<<() [3/4]
std::ostream & Adaptation::operator<< (std::ostream & os, const DynamicGroupCfg & cfg) inline
Definition at line 39 of file DynamicGroupCfg.h.
References Adaptation::DynamicGroupCfg::id.
operator<<() [4/4]
std::ostream & Adaptation::operator<< (std::ostream & os, const ServicePlan & p) inline
Definition at line 148 of file ServiceGroups.h.
References Adaptation::ServicePlan::print().
vectPointStr()
const char * Adaptation::vectPointStr (Adaptation::VectPoint point)
Definition at line 39 of file Elements.cc.
References pointPostCache, and pointPreCache.
Referenced by operator<<(), Adaptation::ServiceConfig::parse(), and Adaptation::ServiceConfig::vectPointStr().
Variable Documentation
crlf
const char * Adaptation::crlf = "\r\n" extern
Definition at line 12 of file Elements.cc.