Squid Web Cache: Time Namespace Reference
Time Namespace Reference
Time and Date handling tools.
Classes
class Engine
event class for doing synthetic time etc
Functions
time_t ParseIso3307 (const char *)
Convert from ISO 3307 style time: YYYYMMDDHHMMSS or YYYYMMDDHHMMSS.xxx.
const char * FormatRfc1123 (time_t)
time_t ParseRfc1123 (const char *)
Convert from RFC 1123 style time: "www, DD MMM YYYY hh:mm:ss ZZZ".
const char * FormatStrf (time_t)
const char * FormatHttpd (time_t)
Function Documentation
FormatHttpd()
const char * Time::FormatHttpd (time_t t)
Display time as a formatted human-readable string. Time string syntax used is that of Apache httpd. "DD/MMM/YYYY:hh:mm:ss zzzz"
Output is only valid until next call to this function.
Definition at line 116 of file gadgets.cc.
Referenced by ErrorState::compileLegacyCode(), dump_peers(), Log::Format::HttpdCombined(), Log::Format::HttpdCommon(), and Log::Format::SquidUserAgent().
FormatRfc1123()
const char * Time::FormatRfc1123 (time_t t)
Display time as a formatted human-readable string. Time string syntax used is from RFC 1123 "www, DD MMM YYYY hh:mm:ss GMT"
Output is only valid until next call to this function.
Definition at line 202 of file rfc1123.cc.
References RFC1123_STRFTIME.
Referenced by ErrorState::compileLegacyCode(), ErrorState::Dump(), DumpAvgStat(), DumpCountersStats(), DumpInfo(), Adaptation::Icap::ModXact::makeRequestHeaders(), HttpHeader::putTime(), and refreshCheck().
FormatStrf()
const char * Time::FormatStrf (time_t t)
Display time as a formatted human-readable string. Time syntax is "YYYY/MM/DD hh:mm:ss"
Output is only valid until next call to this function.
Definition at line 100 of file gadgets.cc.
ParseIso3307()
time_t Time::ParseIso3307 (const char * buf)
Definition at line 18 of file iso3307.cc.
References ASCII_DIGIT.
Referenced by ftpReadMdtm().
ParseRfc1123()
time_t Time::ParseRfc1123 (const char * str)
Definition at line 159 of file rfc1123.cc.
References parse_date().
Referenced by HttpHeader::getTime(), and HttpHeader::getTimeOrTag().