Squid Web Cache: Log::Format Namespace Reference
Log::Format Namespace Reference
Enumerations
enum log_type {
CLF_UNKNOWN , CLF_COMBINED , CLF_COMMON , CLF_CUSTOM ,
CLF_ICAP_SQUID , CLF_REFERER , CLF_SQUID , CLF_USERAGENT ,
CLF_NONE
}
Functions
void SquidNative (const AccessLogEntryPointer &al, Logfile *logfile)
Native Squid Format Display.
void SquidIcap (const AccessLogEntryPointer &al, Logfile *logfile)
Display log details in Squid ICAP format.
void SquidUserAgent (const AccessLogEntryPointer &al, Logfile *logfile)
Display log details in useragent format.
void SquidReferer (const AccessLogEntryPointer &al, Logfile *logfile)
Display log details in Squid old refererlog format.
void SquidCustom (const AccessLogEntryPointer &al, CustomLog *log)
Log with a local custom format.
void HttpdCommon (const AccessLogEntryPointer &al, Logfile *logfile)
Log with Apache httpd common format.
void HttpdCombined (const AccessLogEntryPointer &al, Logfile *logfile)
Log with Apache httpd combined format.
Enumeration Type Documentation
log_type
enum Log::Format::log_type
Enumerator
CLF_UNKNOWN
CLF_COMBINED
CLF_COMMON
CLF_CUSTOM
CLF_ICAP_SQUID
CLF_REFERER
CLF_SQUID
CLF_USERAGENT
CLF_NONE
Definition at line 26 of file Formats.h.
Function Documentation
HttpdCombined()
void Log::Format::HttpdCombined (const AccessLogEntryPointer & al, Logfile * logfile)
Definition at line 22 of file FormatHttpdCombined.cc.
References HttpRequest::auth_user_request, LogTags::c_str(), AccessLogEntry::cache, AccessLogEntry::HttpDetails::clientReplySz, AccessLogEntry::HttpDetails::code, AccessLogEntry::CacheDetails::code, HierarchyLogEntry::code, Config, MemBuf::content(), dash_str, Time::FormatHttpd(), AccessLogEntry::getLogClientIp(), AccessLogEntry::getLogMethod(), HttpHeader::getStr(), Http::Message::header, AccessLogEntry::headers, AccessLogEntry::hier, hier_code_str, AccessLogEntry::http, MemBuf::init(), SquidConfig::log_mime_hdrs, logfilePrintf(), AnyP::ProtocolVersion::major, MAX_IPSTRLEN, MessageSizes::messageTotal(), AnyP::ProtocolVersion::minor, SquidConfig::onoff, AccessLogEntry::packReplyHeaders(), PRId64, AnyP::ProtocolVersion::protocol, AnyP::ProtocolType_str, Format::QuoteMimeBlob(), Format::QuoteUrlEncodeUsername(), Http::REFERER, AccessLogEntry::Headers::request, AccessLogEntry::request, safe_free, squid_curtime, SQUIDSBUFPH, SQUIDSBUFPRINT, AccessLogEntry::url, Http::USER_AGENT, Auth::UserRequest::username(), and AccessLogEntry::HttpDetails::version.
Referenced by accessLogLogTo(), and logfileLineStart().
HttpdCommon()
void Log::Format::HttpdCommon (const AccessLogEntryPointer & al, Logfile * logfile)
Definition at line 22 of file FormatHttpdCommon.cc.
References HttpRequest::auth_user_request, LogTags::c_str(), AccessLogEntry::cache, AccessLogEntry::HttpDetails::clientReplySz, AccessLogEntry::HttpDetails::code, AccessLogEntry::CacheDetails::code, HierarchyLogEntry::code, Config, MemBuf::content(), dash_str, Time::FormatHttpd(), AccessLogEntry::getLogClientIp(), AccessLogEntry::getLogMethod(), AccessLogEntry::headers, AccessLogEntry::hier, hier_code_str, AccessLogEntry::http, MemBuf::init(), SquidConfig::log_mime_hdrs, logfilePrintf(), AnyP::ProtocolVersion::major, MAX_IPSTRLEN, MessageSizes::messageTotal(), AnyP::ProtocolVersion::minor, SquidConfig::onoff, AccessLogEntry::packReplyHeaders(), PRId64, AnyP::ProtocolVersion::protocol, AnyP::ProtocolType_str, Format::QuoteMimeBlob(), Format::QuoteUrlEncodeUsername(), AccessLogEntry::Headers::request, AccessLogEntry::request, safe_free, squid_curtime, SQUIDSBUFPH, SQUIDSBUFPRINT, AccessLogEntry::url, Auth::UserRequest::username(), and AccessLogEntry::HttpDetails::version.
Referenced by accessLogLogTo(), and logfileLineStart().
SquidCustom()
void Log::Format::SquidCustom (const AccessLogEntryPointer & al, CustomLog * log)
Definition at line 20 of file FormatSquidCustom.cc.
References MemBuf::buf, log(), logfilePrintf(), and MemBuf::reset().
Referenced by accessLogLogTo(), and logfileLineStart().
SquidIcap()
void Log::Format::SquidIcap (const AccessLogEntryPointer & al, Logfile * logfile)
Definition at line 23 of file FormatSquidIcap.cc.
References HttpRequest::auth_user_request, AccessLogEntry::IcapLogEntry::bytesRead, AccessLogEntry::cache, current_time, AccessLogEntry::getExtUser(), AccessLogEntry::getLogClientFqdn(), AccessLogEntry::IcapLogEntry::hostAddr, AccessLogEntry::icap, logfilePrintf(), MAX_IPSTRLEN, AccessLogEntry::IcapLogEntry::outcome, PRId64, Format::QuoteUrlEncodeUsername(), AccessLogEntry::IcapLogEntry::reqMethod, AccessLogEntry::request, AccessLogEntry::IcapLogEntry::reqUri, AccessLogEntry::IcapLogEntry::resStatus, safe_free, AccessLogEntry::CacheDetails::ssluser, String::termedBuf(), Ip::Address::toStr(), AccessLogEntry::IcapLogEntry::trTime, tvToMsec(), and Auth::UserRequest::username().
Referenced by accessLogLogTo(), and logfileLineStart().
SquidNative()
void Log::Format::SquidNative (const AccessLogEntryPointer & al, Logfile * logfile)
Definition at line 22 of file FormatSquidNative.cc.
References HttpRequest::auth_user_request, LogTags::c_str(), AccessLogEntry::cache, AccessLogEntry::HttpDetails::clientReplySz, AccessLogEntry::HttpDetails::code, AccessLogEntry::CacheDetails::code, HierarchyLogEntry::code, Config, MemBuf::content(), AccessLogEntry::HttpDetails::content_type, current_time, dash_str, AccessLogEntry::getExtUser(), AccessLogEntry::getLogClientIp(), AccessLogEntry::getLogMethod(), AccessLogEntry::headers, AccessLogEntry::hier, hier_code_str, AccessLogEntry::http, MemBuf::init(), SquidConfig::log_mime_hdrs, logfilePrintf(), MAX_IPSTRLEN, MessageSizes::messageTotal(), SquidConfig::onoff, AccessLogEntry::packReplyHeaders(), HierarchyLogEntry::ping, PRId64, Format::QuoteMimeBlob(), Format::QuoteUrlEncodeUsername(), Comm::Connection::remote, AccessLogEntry::Headers::request, AccessLogEntry::request, safe_free, SQUIDSBUFPH, SQUIDSBUFPRINT, AccessLogEntry::CacheDetails::ssluser, HierarchyLogEntry::tcpServer, ping_data::timedout, Ip::Address::toStr(), AccessLogEntry::CacheDetails::trTime, tvToMsec(), AccessLogEntry::url, and Auth::UserRequest::username().
Referenced by accessLogLogTo(), and logfileLineStart().
SquidReferer()
void Log::Format::SquidReferer (const AccessLogEntryPointer & al, Logfile * logfile)
Definition at line 18 of file FormatSquidReferer.cc.
References current_time, Format::Dash, AccessLogEntry::getLogClientIp(), HttpHeader::getStr(), Http::Message::header, SBuf::isEmpty(), logfilePrintf(), MAX_IPSTRLEN, Http::REFERER, AccessLogEntry::request, SQUIDSBUFPH, SQUIDSBUFPRINT, and AccessLogEntry::url.
Referenced by accessLogLogTo(), and logfileLineStart().
SquidUserAgent()
void Log::Format::SquidUserAgent (const AccessLogEntryPointer & al, Logfile * logfile)
Definition at line 18 of file FormatSquidUseragent.cc.
References Time::FormatHttpd(), AccessLogEntry::getLogClientIp(), HttpHeader::getStr(), Http::Message::header, logfilePrintf(), MAX_IPSTRLEN, AccessLogEntry::request, squid_curtime, and Http::USER_AGENT.
Referenced by accessLogLogTo(), and logfileLineStart().