Squid Web Cache: ProxyProtocol::One Namespace Reference
ProxyProtocol::One Namespace Reference
Functions
static const auto & Magic ()
magic octet prefix for PROXY protocol version 1
static Parsed Parse (const SBuf &buf)
extracts PROXY protocol v1 header from the given buffer
static void ExtractIp (Parser::Tokenizer &tok, Ip::Address &addr)
static void ExtractPort (Parser::Tokenizer &tok, Ip::Address &addr, const bool trailingSpace)
static void ParseAddresses (Parser::Tokenizer &tok, Header::Pointer &header)
Function Documentation
ExtractIp()
void ProxyProtocol::One::ExtractIp (Parser::Tokenizer & tok, Ip::Address & addr) static
Definition at line 64 of file Parser.cc.
References SBuf::c_str(), Ip::Address::GetHostByName(), CharacterSet::HEXDIG, and TexcHere.
Referenced by ParseAddresses().
ExtractPort()
void ProxyProtocol::One::ExtractPort (Parser::Tokenizer & tok, Ip::Address & addr, const bool trailingSpace) static
Definition at line 82 of file Parser.cc.
References port, Ip::Address::port(), and TexcHere.
Referenced by ParseAddresses().
Magic()
static const auto & ProxyProtocol::One::Magic () static
Definition at line 34 of file Parser.cc.
Referenced by Parse().
Parse()
ProxyProtocol::Parsed ProxyProtocol::One::Parse (const SBuf & buf) static
parses PROXY protocol v1 header from the buffer
Definition at line 123 of file Parser.cc.
References CharacterSet::complement(), CharacterSet::CR, Magic(), ParseAddresses(), CharacterSet::rename(), Parser::Tokenizer::skip(), and TexcHere.
ParseAddresses()
void ProxyProtocol::One::ParseAddresses (Parser::Tokenizer & tok, Header::Pointer & header) static
Definition at line 99 of file Parser.cc.
References ExtractIp(), ExtractPort(), and TexcHere.
Referenced by Parse().