Squid Web Cache: Http Namespace Reference
Http Namespace Reference
Namespaces
namespace One
common part of ParseBws() and ParseStrctBws()
Classes
class ContentLengthInterpreter
class HeaderLookupTable_t
class HeaderTableRecord
class Message
common parts of HttpRequest and HttpReply
class StateFlags
class StatusLine
class Stream
class Tunneler
class TunnelerAnswer
Typedefs
typedef RefCount< Http::Message > MessagePointer
typedef RefCount< Http::Stream > StreamPointer
typedef enum Http::_method_t MethodType
Enumerations
enum _method_t {
METHOD_NONE = 0 , METHOD_GET , METHOD_POST , METHOD_PUT ,
METHOD_HEAD , METHOD_CONNECT , METHOD_TRACE , METHOD_OPTIONS ,
METHOD_DELETE , METHOD_LINK , METHOD_UNLINK , METHOD_CHECKOUT ,
METHOD_CHECKIN , METHOD_UNCHECKOUT , METHOD_MKWORKSPACE , METHOD_VERSION_CONTROL ,
METHOD_REPORT , METHOD_UPDATE , METHOD_LABEL , METHOD_MERGE ,
METHOD_BASELINE_CONTROL , METHOD_MKACTIVITY , METHOD_PROPFIND , METHOD_PROPPATCH ,
METHOD_MKCOL , METHOD_COPY , METHOD_MOVE , METHOD_LOCK ,
METHOD_UNLOCK , METHOD_SEARCH , METHOD_PRI , METHOD_PURGE ,
METHOD_OTHER , METHOD_ENUM_END
}
enum HdrType {
enumBegin_ = 0 , ACCEPT = enumBegin_ , ACCEPT_CHARSET , ACCEPT_ENCODING ,
ACCEPT_LANGUAGE , ACCEPT_RANGES , AGE , ALLOW ,
ALTERNATE_PROTOCOL , AUTHENTICATION_INFO , AUTHORIZATION , CACHE_CONTROL ,
CACHE_STATUS , CDN_LOOP , CONNECTION , CONTENT_BASE ,
CONTENT_DISPOSITION , CONTENT_ENCODING , CONTENT_LANGUAGE , CONTENT_LENGTH ,
CONTENT_LOCATION , CONTENT_MD5 , CONTENT_RANGE , CONTENT_TYPE ,
COOKIE , COOKIE2 , DATE , ETAG ,
EXPECT , EXPIRES , FORWARDED , FROM ,
HOST , IF_MATCH , IF_MODIFIED_SINCE , IF_NONE_MATCH ,
IF_RANGE , IF_UNMODIFIED_SINCE , KEEP_ALIVE , KEY ,
LAST_MODIFIED , LINK , LOCATION , MAX_FORWARDS ,
MIME_VERSION , NEGOTIATE , ORIGIN , PRAGMA ,
PRIORITY , PROXY_AUTHENTICATE , PROXY_AUTHENTICATION_INFO , PROXY_AUTHORIZATION ,
PROXY_CONNECTION , PROXY_SUPPORT , PUBLIC , RANGE ,
REFERER , REQUEST_RANGE , RETRY_AFTER , SERVER ,
SET_COOKIE , SET_COOKIE2 , TE , TITLE ,
TRAILER , TRANSFER_ENCODING , TRANSLATE , UNLESS_MODIFIED_SINCE ,
UPGRADE , USER_AGENT , VARY , VIA ,
WWW_AUTHENTICATE , X_FORWARDED_FOR , X_SQUID_ERROR , HDR_X_ACCELERATOR_VARY ,
X_NEXT_SERVICES , SURROGATE_CAPABILITY , SURROGATE_CONTROL , FRONT_END_HTTPS ,
FTP_COMMAND , FTP_ARGUMENTS , FTP_PRE , FTP_STATUS ,
FTP_REASON , OTHER , BAD_HDR , enumEnd_
}
enum class HdrFieldType {
ftInvalid , ftInt , ftInt64 , ftStr ,
ftDate_1123 , ftETag , ftPCc , ftPContRange ,
ftPRange , ftPSc , ftDate_1123_or_ETag
}
enum HdrKind {
None = 0 , ListHeader = 1 , RequestHeader = 1 << 1 , ReplyHeader = 1 << 2 ,
HopByHopHeader = 1 << 3 , Denied304Header = 1 << 4 , GeneralHeader = RequestHeader | ReplyHeader , EntityHeader = RequestHeader | ReplyHeader
}
enum StatusCode {
scNone = 0 , scContinue = 100 , scSwitchingProtocols = 101 , scProcessing = 102 ,
scEarlyHints = 103 , scUploadResumptionSupported = 104 , scOkay = 200 , scCreated = 201 ,
scAccepted = 202 , scNonAuthoritativeInformation = 203 , scNoContent = 204 , scResetContent = 205 ,
scPartialContent = 206 , scMultiStatus = 207 , scAlreadyReported = 208 , scImUsed = 226 ,
scMultipleChoices = 300 , scMovedPermanently = 301 , scFound = 302 , scSeeOther = 303 ,
scNotModified = 304 , scUseProxy = 305 , scTemporaryRedirect = 307 , scPermanentRedirect = 308 ,
scBadRequest = 400 , scUnauthorized = 401 , scPaymentRequired = 402 , scForbidden = 403 ,
scNotFound = 404 , scMethodNotAllowed = 405 , scNotAcceptable = 406 , scProxyAuthenticationRequired = 407 ,
scRequestTimeout = 408 , scConflict = 409 , scGone = 410 , scLengthRequired = 411 ,
scPreconditionFailed = 412 , scContentTooLarge = 413 , scUriTooLong = 414 , scUnsupportedMediaType = 415 ,
scRequestedRangeNotSatisfied = 416 , scExpectationFailed = 417 , scMisdirectedRequest = 421 , scUnprocessableEntity = 422 ,
scLocked = 423 , scFailedDependency = 424 , scTooEarly = 425 , scUpgradeRequired = 426 ,
scPreconditionRequired = 428 , scTooManyRequests = 429 , scRequestHeaderFieldsTooLarge = 431 , scUnavailableForLegalReasons = 451 ,
scInternalServerError = 500 , scNotImplemented = 501 , scBadGateway = 502 , scServiceUnavailable = 503 ,
scGatewayTimeout = 504 , scHttpVersionNotSupported = 505 , scVariantAlsoNegotiates = 506 , scInsufficientStorage = 507 ,
scLoopDetected = 508 , scNotExtended = 510 , scNetworkAuthenticationRequired = 511 , scInvalidHeader = 600 ,
scHeaderTooLarge = 601
}
Functions
std::ostream & operator<< (std::ostream &, const TunnelerAnswer &)
const SBuf & MethodStr (const MethodType m)
AnyP::ProtocolVersion ProtocolVersion (unsigned int aMajor, unsigned int aMinor)
HTTP version label information.
AnyP::ProtocolVersion ProtocolVersion ()
bool any_HdrType_enum_value (const Http::HdrType id)
match any known header type, including OTHER and BAD
bool any_valid_header (const Http::HdrType id)
match any valid header type, including OTHER but not BAD
bool any_registered_header (const Http::HdrType id)
std::ostream & operator<< (std::ostream &, HdrType)
const char * StatusCodeString (const Http::StatusCode status)
bool Is1xx (const int sc)
whether this is an informational 1xx response status code
bool Is4xx (const int sc)
whether this is a client error 4xx response status code
bool ProhibitsContentLength (const StatusCode sc)
whether this response status code prohibits sending Content-Length
bool IsReforwardableStatus (StatusCode)
whether to send the request to another peer based on the current response status code
SBuf SlowlyParseQuotedString (const char *description, const char *start, size_t length)
ConnStateData * NewServer (const MasterXactionPointer &xact)
create a new HTTP connection handler; never returns NULL
Variables
const SBuf MethodType_sb [] = {SBuf()}
const HeaderLookupTable_t HeaderLookupTable
Typedef Documentation
MessagePointer
typedef RefCount<Http::Message> Http::MessagePointer
Definition at line 22 of file forward.h.
MethodType
typedef enum Http::_method_t Http::MethodType
StreamPointer
typedef RefCount<Http::Stream> Http::StreamPointer
Definition at line 25 of file forward.h.
Enumeration Type Documentation
_method_t
enum Http::_method_t
Enumerator
METHOD_NONE
METHOD_GET
METHOD_POST
METHOD_PUT
METHOD_HEAD
METHOD_CONNECT
METHOD_TRACE
METHOD_OPTIONS
METHOD_DELETE
METHOD_LINK
METHOD_UNLINK
METHOD_CHECKOUT
METHOD_CHECKIN
METHOD_UNCHECKOUT
METHOD_MKWORKSPACE
METHOD_VERSION_CONTROL
METHOD_REPORT
METHOD_UPDATE
METHOD_LABEL
METHOD_MERGE
METHOD_BASELINE_CONTROL
METHOD_MKACTIVITY
METHOD_PROPFIND
METHOD_PROPPATCH
METHOD_MKCOL
METHOD_COPY
METHOD_MOVE
METHOD_LOCK
METHOD_UNLOCK
METHOD_SEARCH
METHOD_PRI
METHOD_PURGE
METHOD_OTHER
METHOD_ENUM_END
Definition at line 21 of file MethodType.h.
HdrFieldType
enum class Http::HdrFieldType strong
possible types for http header fields
Enumerator
ftInvalid
to catch nasty errors with hdr_id<->fld_type clashes
ftInt
ftInt64
ftStr
ftDate_1123
ftETag
ftPCc
ftPContRange
ftPRange
ftPSc
ftDate_1123_or_ETag
Definition at line 126 of file RegisteredHeaders.h.
HdrKind
enum Http::HdrKind
Enumerator
None
ListHeader
RequestHeader
ReplyHeader
HopByHopHeader
Denied304Header
GeneralHeader
EntityHeader
Definition at line 140 of file RegisteredHeaders.h.
HdrType
enum Http::HdrType
recognized or "known" header fields; and the RFC which defines them (or not) http://www.iana.org/assignments/message-headers/message-headers.xhtml
Enumerator
enumBegin_
ACCEPT
RFC 7231
ACCEPT_CHARSET
RFC 7231
ACCEPT_ENCODING
RFC 7231
ACCEPT_LANGUAGE
RFC 7231
ACCEPT_RANGES
RFC 7233
AGE
RFC 9111
ALLOW
RFC 7231
ALTERNATE_PROTOCOL
GFE custom header we may have to erase
AUTHENTICATION_INFO
RFC 2617
AUTHORIZATION
RFC 7235, 4559
CACHE_CONTROL
RFC 9111
CACHE_STATUS
draft-ietf-httpbis-cache-header
CDN_LOOP
RFC 8586
CONNECTION
RFC 7230
CONTENT_BASE
obsoleted RFC 2068
CONTENT_DISPOSITION
RFC 2183, 6266
CONTENT_ENCODING
RFC 7231
CONTENT_LANGUAGE
RFC 7231
CONTENT_LENGTH
RFC 7230
CONTENT_LOCATION
RFC 7231
CONTENT_MD5
deprecated, RFC 2616
CONTENT_RANGE
RFC 7233
CONTENT_TYPE
RFC 7231
COOKIE
RFC 6265 header we may need to erase
COOKIE2
obsolete RFC 2965 header we may need to erase
DATE
RFC 7231
ETAG
RFC 7232
EXPECT
RFC 7231
EXPIRES
RFC 9111
FORWARDED
RFC 7239
FROM
RFC 7231
HOST
RFC 7230
IF_MATCH
RFC 7232
IF_MODIFIED_SINCE
RFC 7232
IF_NONE_MATCH
RFC 7232
IF_RANGE
RFC 7233
IF_UNMODIFIED_SINCE
RFC 7232
KEEP_ALIVE
obsoleted RFC 2068 header we may need to erase
KEY
experimental RFC Draft draft-fielding-http-key-02
LAST_MODIFIED
RFC 7232
LINK
RFC 5988
LOCATION
RFC 7231
MAX_FORWARDS
RFC 7231
MIME_VERSION
RFC 2045, 7231
NEGOTIATE
experimental RFC 2295. Why only this one from 2295?
ORIGIN
PRAGMA
deprecated RFC 7234 header
PRIORITY
RFC 9218
PROXY_AUTHENTICATE
RFC 7235
PROXY_AUTHENTICATION_INFO
RFC 2617
PROXY_AUTHORIZATION
RFC 7235
PROXY_CONNECTION
obsolete Netscape header we may need to erase.
PROXY_SUPPORT
RFC 4559
PUBLIC
RFC 2068
RANGE
RFC 7233
REFERER
RFC 7231
REQUEST_RANGE
some clients use this, sigh
RETRY_AFTER
RFC 7231
SERVER
RFC 7231
SET_COOKIE
RFC 6265 header we may need to erase
SET_COOKIE2
obsoleted RFC 2965 header we may need to erase
TE
RFC 7230
TITLE
TRAILER
RFC 7230
TRANSFER_ENCODING
RFC 7230
TRANSLATE
IIS custom header we may need to erase
UNLESS_MODIFIED_SINCE
IIS custom header we may need to erase
UPGRADE
RFC 7230
USER_AGENT
RFC 7231
VARY
RFC 7231
VIA
RFC 7230
WWW_AUTHENTICATE
RFC 7235, 4559
X_FORWARDED_FOR
obsolete Squid custom header, RFC 7239
X_SQUID_ERROR
Squid custom header on generated error responses
HDR_X_ACCELERATOR_VARY
obsolete Squid custom header.
X_NEXT_SERVICES
Squid custom ICAP header
SURROGATE_CAPABILITY
W3C Edge Architecture Specification
SURROGATE_CONTROL
W3C Edge Architecture Specification
FRONT_END_HTTPS
MS Exchange custom header we may have to add
FTP_COMMAND
Internal header for FTP command
FTP_ARGUMENTS
Internal header for FTP command arguments
FTP_PRE
Internal header containing leading FTP control response lines
FTP_STATUS
Internal header for FTP reply status
FTP_REASON
Internal header for FTP reply reason
OTHER
internal tag value for "unknown" headers
BAD_HDR
Invalid header
enumEnd_
Definition at line 21 of file RegisteredHeaders.h.
StatusCode
enum Http::StatusCode
These basic HTTP reply status codes are defined by RFC 2616 unless otherwise stated. The IANA registry for HTTP status codes can be found at: http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
Enumerator
scNone
scContinue
scSwitchingProtocols
scProcessing
scEarlyHints
scUploadResumptionSupported
scOkay
scCreated
scAccepted
scNonAuthoritativeInformation
scNoContent
scResetContent
scPartialContent
scMultiStatus
scAlreadyReported
scImUsed
scMultipleChoices
scMovedPermanently
scFound
scSeeOther
scNotModified
scUseProxy
scTemporaryRedirect
scPermanentRedirect
scBadRequest
scUnauthorized
scPaymentRequired
scForbidden
scNotFound
scMethodNotAllowed
scNotAcceptable
scProxyAuthenticationRequired
scRequestTimeout
scConflict
scGone
scLengthRequired
scPreconditionFailed
scContentTooLarge
scUriTooLong
scUnsupportedMediaType
scRequestedRangeNotSatisfied
scExpectationFailed
scMisdirectedRequest
scUnprocessableEntity
scLocked
scFailedDependency
scTooEarly
scUpgradeRequired
scPreconditionRequired
scTooManyRequests
scRequestHeaderFieldsTooLarge
scUnavailableForLegalReasons
scInternalServerError
scNotImplemented
scBadGateway
scServiceUnavailable
scGatewayTimeout
scHttpVersionNotSupported
scVariantAlsoNegotiates
scInsufficientStorage
scLoopDetected
scNotExtended
scNetworkAuthenticationRequired
scInvalidHeader
Squid header parsing error.
scHeaderTooLarge
Header too large to process.
Definition at line 20 of file StatusCode.h.
Function Documentation
any_HdrType_enum_value()
bool Http::any_HdrType_enum_value (const Http::HdrType id) inline
Definition at line 204 of file RegisteredHeaders.h.
References enumBegin_, and enumEnd_.
Referenced by HeaderManglers::find(), and operator<<().
any_registered_header()
bool Http::any_registered_header (const Http::HdrType id) inline
match any registered header type (headers squid knows how to handle), thus excluding OTHER and BAD
Definition at line 219 of file RegisteredHeaders.h.
References ACCEPT, and OTHER.
any_valid_header()
bool Http::any_valid_header (const Http::HdrType id) inline
Definition at line 211 of file RegisteredHeaders.h.
References ACCEPT, and BAD_HDR.
Referenced by HttpHeader::clean(), and httpHeaderFieldStatDumper().
Is1xx()
bool Http::Is1xx (const int sc) inline
Definition at line 94 of file StatusCode.h.
References scContinue, and scOkay.
Referenced by HttpStateData::processReplyHeader(), and ProhibitsContentLength().
Is4xx()
bool Http::Is4xx (const int sc) inline
Definition at line 96 of file StatusCode.h.
References scBadRequest, and scInternalServerError.
IsReforwardableStatus()
bool Http::IsReforwardableStatus (StatusCode s)
Definition at line 281 of file StatusCode.cc.
References Config, SquidConfig::onerror, SquidConfig::retry, scBadGateway, scForbidden, scGatewayTimeout, scInternalServerError, scNotImplemented, and scServiceUnavailable.
Referenced by TunnelStateData::checkRetry(), HttpStateData::haveParsedReplyHeaders(), and FwdState::reforward().
MethodStr()
const SBuf & Http::MethodStr (const MethodType m) inline
Definition at line 100 of file MethodType.h.
References MethodType_sb.
Referenced by clientReplyContext::purgeEntry().
NewServer()
ConnStateData * Http::NewServer (const MasterXactionPointer & xact)
Definition at line 392 of file Http1Server.cc.
Referenced by httpAccept().
operator<<() [1/2]
std::ostream & Http::operator<< (std::ostream & os, const TunnelerAnswer & answer)
Definition at line 19 of file HttpTunnelerAnswer.cc.
References Http::TunnelerAnswer::conn, CbcPointer< Cbc >::get(), Http::TunnelerAnswer::leftovers, SBuf::length(), ErrorState::page_id, Http::TunnelerAnswer::peerResponseStatus, scNone, and Http::TunnelerAnswer::squidError.
operator<<() [2/2]
std::ostream & Http::operator<< (std::ostream & s, HdrType id)
Definition at line 64 of file RegisteredHeaders.cc.
References any_HdrType_enum_value(), HeaderLookupTable, Http::HeaderLookupTable_t::lookup(), and Http::HeaderTableRecord::name.
ProhibitsContentLength()
bool Http::ProhibitsContentLength (const StatusCode sc) inline
Definition at line 98 of file StatusCode.h.
References Is1xx(), and scNoContent.
Referenced by Http::ContentLengthInterpreter::applyStatusCodeRules(), and HttpReply::removeIrrelevantContentLength().
ProtocolVersion() [1/2]
AnyP::ProtocolVersion Http::ProtocolVersion () inline
HTTP version label information.
Squid being conditionally compliant with RFC 7230 on both client and server connections the default value is HTTP/1.1.
Definition at line 32 of file ProtocolVersion.h.
References AnyP::PROTO_HTTP.
Referenced by netdbExchangeState::netdbExchangeState(), Http::One::TeChunkedParser::TeChunkedParser(), ErrorState::BuildHttpReply(), clientReplyContext::buildReplyHeader(), Downloader::buildRequest(), HttpStateData::buildRequestPrefix(), HttpRequest::canHandle1xx(), HttpRequest::checkEntityFraming(), Http::StatusLine::clean(), clientReplyContext::cloneReply(), HttpStateData::continueAfterParsingHeader(), HttpStateData::forwardUpgrade(), HttpReply::httpMsgParseError(), Ftp::HttpReplyWrapper(), Http::StatusLine::init(), HttpReply::make304(), HttpReply::MakeConnectionEstablished(), ConnStateData::parseHttpRequest(), Http::One::RequestParser::parseHttpVersionField(), Ftp::Server::parseOneRequest(), parsePortProtocol(), Http::One::ResponseParser::parseResponseFirstLine(), Http::Message::persistent(), Http::One::Server::processParsedRequest(), HttpStateData::processReplyHeader(), HttpReply::redirect(), HttpReply::setHeaders(), ConnStateData::splice(), and CacheManager::start().
ProtocolVersion() [2/2]
AnyP::ProtocolVersion Http::ProtocolVersion (unsigned int aMajor, unsigned int aMinor) inline
Definition at line 19 of file ProtocolVersion.h.
References AnyP::PROTO_HTTP.
SlowlyParseQuotedString()
SBuf Http::SlowlyParseQuotedString (const char * description, const char * start, size_t length) private
Parses an HTTP quoted-string sequence (RFC 9110, Section 5.6.4).
Parameters
a brief human-friendly description of the string being parsed
start input buffer (an opening double-quote is expected at *start)
length is the number of characters in the given buffer
Returns
string contents with open/closing quotes stripped and any quoted-pairs decoded
Avoid this slow function on performance-sensitive code paths. TODO: Replace with an efficient, SBuf-friendly implementation.
See also
httpHeaderParseQuotedString() for a String-friendly function.
Definition at line 268 of file HttpHeader.cc.
References Here, httpHeaderParseQuotedString(), StringToSBuf(), and ToSBuf().
Referenced by SlowlyParseQuotedField().
StatusCodeString()
const char * Http::StatusCodeString (const Http::StatusCode status)
Definition at line 15 of file StatusCode.cc.
References debugs, scAccepted, scAlreadyReported, scBadGateway, scBadRequest, scConflict, scContentTooLarge, scContinue, scCreated, scEarlyHints, scExpectationFailed, scFailedDependency, scForbidden, scFound, scGatewayTimeout, scGone, scHeaderTooLarge, scHttpVersionNotSupported, scImUsed, scInsufficientStorage, scInternalServerError, scInvalidHeader, scLengthRequired, scLocked, scLoopDetected, scMethodNotAllowed, scMisdirectedRequest, scMovedPermanently, scMultipleChoices, scMultiStatus, scNetworkAuthenticationRequired, scNoContent, scNonAuthoritativeInformation, scNone, scNotAcceptable, scNotExtended, scNotFound, scNotImplemented, scNotModified, scOkay, scPartialContent, scPaymentRequired, scPermanentRedirect, scPreconditionFailed, scPreconditionRequired, scProcessing, scProxyAuthenticationRequired, scRequestedRangeNotSatisfied, scRequestHeaderFieldsTooLarge, scRequestTimeout, scResetContent, scSeeOther, scServiceUnavailable, scSwitchingProtocols, scTemporaryRedirect, scTooManyRequests, scUnauthorized, scUnavailableForLegalReasons, scUnprocessableEntity, scUnsupportedMediaType, scUpgradeRequired, scUriTooLong, scUseProxy, and scVariantAlsoNegotiates.
Referenced by Http::StatusLine::packedLength(), Http::StatusLine::packInto(), and Http::StatusLine::reason().
Variable Documentation
HeaderLookupTable
const HeaderLookupTable_t Http::HeaderLookupTable
Definition at line 60 of file RegisteredHeaders.cc.
Referenced by HttpHeaderEntry::HttpHeaderEntry(), clientFollowXForwardedForCheck(), HeaderManglers::dumpAccess(), HeaderManglers::dumpReplacement(), HttpHeader::findEntry(), HttpHeader::findLastEntry(), HttpHeader::getETag(), HttpHeader::getInt(), HttpHeader::getInt64(), HttpHeader::getLastStr(), HttpHeader::getList(), HttpHeader::getList(), HttpHeader::getStr(), HttpHeader::getStrOrList(), HttpHeader::getTime(), HttpHeader::getTimeOrTag(), HttpHeader::hasNamed(), httpHeaderFieldStatDumper(), httpHeaderInitModule(), httpHeaderNoteParsedEntry(), httpHeaderStoreReport(), operator<<(), ACLHTTPHeaderData::parse(), HttpHeaderEntry::parse(), parse_HeaderWithAclList(), HttpHeader::putInt(), HttpHeader::putInt64(), HttpHeader::putStr(), HttpHeader::putTime(), HttpHeader::removeHopByHopEntries(), HeaderManglers::track(), HttpHeader::update(), and HttpHeader::updateOrAddStr().
MethodType_sb
const SBuf Http::MethodType_sb = {SBuf()}
Definition at line 57 of file stub_libhttp.cc.
Referenced by HttpRequestMethod::image(), and MethodStr().