Squid Web Cache: Snmp Namespace Reference
Snmp Namespace Reference
Classes
class Forwarder
class Inquirer
class Pdu
class Request
SNMP request.
class Response
class Session
snmp_session wrapper add pack/unpack feature
class Var
Functions
void SendResponse (Ipc::RequestId, const Pdu &)
Function Documentation
SendResponse()
void Snmp::SendResponse (Ipc::RequestId requestId, const Pdu & pdu)
Definition at line 97 of file Forwarder.cc.
References snmp_pdu::command, Ipc::Port::CoordinatorAddr(), DBG_CRITICAL, debugs, snmp_pdu::errstat, Must, MYNAME, Snmp::Response::pack(), Snmp::Response::pdu, Ipc::SendMessage(), SNMP_ERR_GENERR, snmp_free_pdu(), SNMP_PDU_RESPONSE, and snmpAgentResponse().
Referenced by Ipc::Strand::handleSnmpRequest().