Squid Web Cache: Rock Namespace Reference
Rock Namespace Reference
Classes
class DbCellHeader
class HeaderUpdater
class IoState
class LoadingEntry
smart StoreEntry-level info pointer (hides anti-padding LoadingParts arrays)
class LoadingFlags
low-level anti-padding storage class for LoadingEntry and LoadingSlot flags
class LoadingParts
class LoadingSlot
smart db slot-level info pointer (hides anti-padding LoadingParts arrays)
class ReadRequest
class Rebuild
class StoreFileSystem
,
class SwapDir
class SwapDirRr
initializes shared memory segments used by Rock::SwapDir
class WriteRequest
Typedefs
typedef sfileno SlotId
db cell number, starting with cell 0 (always occupied by the db header)
typedef uint64_t IoXactionId
unique (within a given IoState object scope) I/O transaction identifier
Functions
std::ostream & operator<< (std::ostream &os, const HeaderUpdater::IoCbParams &params)
static bool DoneLoading (const int64_t loadingPos, const int64_t dbSlotLimit)
static bool DoneValidating (const int64_t validationPos, const int64_t dbSlotLimit, const int64_t dbEntryLimit)
Typedef Documentation
IoXactionId
typedef uint64_t Rock::IoXactionId
Definition at line 36 of file forward.h.
SlotId
typedef sfileno Rock::SlotId
Definition at line 33 of file forward.h.
Function Documentation
DoneLoading()
static bool Rock::DoneLoading (const int64_t loadingPos, const int64_t dbSlotLimit) static
Definition at line 81 of file RockRebuild.cc.
Referenced by Rock::Rebuild::Stats::completed(), and Rock::Rebuild::doneLoading().
DoneValidating()
static bool Rock::DoneValidating (const int64_t validationPos, const int64_t dbSlotLimit, const int64_t dbEntryLimit) static
Definition at line 87 of file RockRebuild.cc.
References opt_store_doublecheck.
Referenced by Rock::Rebuild::Stats::completed(), and Rock::Rebuild::doneValidating().
operator<<()
std::ostream & Rock::operator<< (std::ostream & os, const HeaderUpdater::IoCbParams & params) inline
Definition at line 77 of file RockHeaderUpdater.h.
References Rock::HeaderUpdater::IoCbParams::buf, and Rock::HeaderUpdater::IoCbParams::size.