Squid Web Cache: ErrorPage Namespace Reference
ErrorPage Namespace Reference
Classes
class Build
state and parameters shared by several ErrorState::compile*() methods
class BuildErrorPrinter
pretty-prints error page/deny_info building error
Functions
static std::ostream & operator<< (std::ostream &os, const BuildErrorPrinter &context)
static const char * IsDenyInfoUri (const int page_id)
static void ImportStaticErrorText (const int page_id, const char *text, const SBuf &inputLocation)
add error page template to the global index
static void ValidateStaticError (const int page_id, const SBuf &inputLocation)
validate static error page
Function Documentation
ImportStaticErrorText()
static void ErrorPage::ImportStaticErrorText (const int page_id, const char * text, const SBuf & inputLocation) static private
Definition at line 1537 of file errorpage.cc.
References assert, error_text, text, ValidateStaticError(), and xstrdup.
Referenced by errorInitialize().
IsDenyInfoUri()
static const char * ErrorPage::IsDenyInfoUri (const int page_id) static private
Returns
deny_info URL if the given page is a deny_info page with a URL
nullptr otherwise
Definition at line 253 of file errorpage.cc.
References SBuf::at(), ERR_MAX, error_page_count, and ErrorDynamicPages.
Referenced by ErrorState::BuildHttpReply(), and ErrorState::validate().
operator<<()
static std::ostream & ErrorPage::operator<< (std::ostream & os, const BuildErrorPrinter & context) inline static private
Definition at line 139 of file errorpage.cc.
References ErrorPage::BuildErrorPrinter::print().
ValidateStaticError()
static void ErrorPage::ValidateStaticError (const int page_id, const SBuf & inputLocation) static private
Definition at line 1546 of file errorpage.cc.
References ErrorState::inputLocation, Http::scNone, and ErrorState::validate().
Referenced by errorInitialize(), and ImportStaticErrorText().