Squid Web Cache: Mgr Namespace Reference
Mgr Namespace Reference
Cache Manager API.
Classes
class Action
class ActionCreator
class ActionParams
Cache Manager Action parameters extracted from the user request.
class ActionPasswordList
list of cachemgr password authorization definitions. Currently a POD.
class ActionProfile
hard-coded Cache Manager action configuration, including Action creator
class ActionWriter
class ClassActionCreator
creates Action using supplied Action::Create method and command
class Command
combined hard-coded action profile with user-supplied action parameters
class CountersAction
implement aggregated 'counters' action
class CountersActionData
store traffic and resource counters
class Filler
provides Coordinator with a local cache manager response
class Forwarder
class FunAction
class FunActionCreator
creates FunAction using ActionCreator API
class IndexAction
class InfoAction
implement aggregated 'info' action
class InfoActionData
class Inquirer
class IntervalAction
implement aggregated interval actions
class IntervalActionData
class IntParam
class IoAction
implement aggregated 'io' action
class IoActionData
store size histograms of network read() from peer server
class MenuAction
returns available Cache Manager actions and their access requirements
class OfflineToggleAction
changes offline mode
class QueryParam
class QueryParams
class ReconfigureAction
reconfigures Squid
class Request
cache manager request
class Response
class RotateAction
starts log rotation
class ServiceTimesAction
implement aggregated 'service_times' action
class ServiceTimesActionData
store service times for 5 and 60 min
class ShutdownAction
shuts Squid down
class StoreIoAction
implement aggregated 'store_io' action
class StoreIoActionData
Store IO interface data.
class StoreToCommWriter
class StringParam
Typedefs
typedef RefCount< Action > ActionPointer
typedef RefCount< ActionProfile > ActionProfilePointer
typedef RefCount< ActionCreator > ActionCreatorPointer
typedef RefCount< Command > CommandPointer
typedef ActionPointer() ClassActionCreationHandler(const CommandPointer &cmd)
Enumerations
enum class Protected { no , yes }
whether default cachemgr_passwd configuration denies the Action
enum class Atomic { no , yes }
whether Action::dump() writes the entire report before returning
enum class Format { informal , yaml }
whether Action report uses valid YAML or unspecified/legacy formatting
Functions
void OpenKidSection (StoreEntry *, Format)
void CloseKidSection (StoreEntry *, Format)
std::ostream & operator<< (std::ostream &os, const ActionProfile &profile)
void RegisterBasics ()
Registers profiles for the actions above; TODO: move elsewhere?
std::ostream & operator<< (std::ostream &, const Command &)
void RegisterAction (char const *action, char const *desc, OBJH *handler, Protected, Atomic, Format)
void RegisterAction (const char *const action, const char *const desc, OBJH *handler, int pw_req_flag, int atomic)
wrapper for legacy Format-unaware function-based action registration code
void RegisterAction (char const *action, char const *desc, ClassActionCreationHandler *handler, Protected, Atomic, Format)
void RegisterAction (const char *const action, const char *const desc, ClassActionCreationHandler *handler, int pw_req_flag, int atomic)
wrapper for legacy Format-unaware class-based action registration code
Typedef Documentation
ActionCreatorPointer
typedef RefCount<ActionCreator> Mgr::ActionCreatorPointer
Definition at line 33 of file forward.h.
ActionPointer
typedef RefCount<Action> Mgr::ActionPointer
Definition at line 31 of file forward.h.
ActionProfilePointer
typedef RefCount<ActionProfile> Mgr::ActionProfilePointer
Definition at line 32 of file forward.h.
ClassActionCreationHandler
typedef ActionPointer() Mgr::ClassActionCreationHandler(const CommandPointer &cmd)
Definition at line 36 of file forward.h.
CommandPointer
typedef RefCount<Command> Mgr::CommandPointer
Definition at line 34 of file forward.h.
Enumeration Type Documentation
Atomic
enum class Mgr::Atomic strong
Enumerator
no
yes
Definition at line 27 of file ActionFeatures.h.
Format
enum class Mgr::Format strong
Enumerator
informal
yaml
Definition at line 30 of file ActionFeatures.h.
Protected
enum class Mgr::Protected strong
Enumerator
no
yes
Definition at line 24 of file ActionFeatures.h.
Function Documentation
CloseKidSection()
void Mgr::CloseKidSection (StoreEntry * entry, Format format)
finishes writing a portion of the report specific to the current process
See also
OpenKidSection()
Definition at line 156 of file Action.cc.
References informal, KidIdentifier, storeAppendPrintf(), and yaml.
Referenced by Mgr::FunAction::dump(), Mgr::InfoAction::dump(), and statObjects().
OpenKidSection()
void Mgr::OpenKidSection (StoreEntry * entry, Format format)
starts writing a portion of the report specific to the current process
See also
CloseKidSection()
Definition at line 144 of file Action.cc.
References informal, KidIdentifier, storeAppendPrintf(), and yaml.
Referenced by Mgr::FunAction::dump(), and Mgr::InfoAction::dump().
operator<<() [1/2]
std::ostream & Mgr::operator<< (std::ostream & os, const Command & cmd)
Definition at line 15 of file Command.cc.
References Mgr::Command::profile.
operator<<() [2/2]
std::ostream & Mgr::operator<< (std::ostream & os, const ActionProfile & profile) inline
Definition at line 49 of file ActionProfile.h.
References Mgr::ActionProfile::name.
RegisterAction() [1/4]
void Mgr::RegisterAction (char const * action, char const * desc, ClassActionCreationHandler * handler, Protected protection, Atomic atomicity, Format format)
Creates a class-based action profile and adds it to the cache manager collection (once across all calls with the same action name).
Definition at line 68 of file Registration.cc.
References debugs, CacheManager::GetInstance(), and CacheManager::registerProfile().
RegisterAction() [2/4]
void Mgr::RegisterAction (char const * action, char const * desc, OBJH * handler, Protected protection, Atomic atomicity, Format format)
Creates a function-based action profile and adds it to the cache manager collection (once across all calls with the same action name).
Definition at line 54 of file Registration.cc.
References debugs, CacheManager::GetInstance(), and CacheManager::registerProfile().
Referenced by carpRegisterWithCacheManager(), commDevPollRegisterWithCacheManager(), commEPollRegisterWithCacheManager(), commPollRegisterWithCacheManager(), eventInit(), externalAclRegisterWithCacheManager(), fqdncacheRegisterWithCacheManager(), httpHeaderRegisterWithCacheManager(), Mem::Init(), Dns::Init(), ipcacheRegisterWithCacheManager(), neighborsRegisterWithCacheManager(), netdbInit(), Configuration::Parse(), peerSourceHashRegisterWithCacheManager(), peerUserHashRegisterWithCacheManager(), redirectInit(), refreshRegisterWithCacheManager(), RegisterAction(), RegisterAction(), RegisterBasics(), AsyncJob::RegisterWithCacheManager(), DelayPools::RegisterWithCacheManager(), DiskDaemonDiskIOModule::registerWithCacheManager(), DiskThreadsIOStrategy::registerWithCacheManager(), FwdState::RegisterWithCacheManager(), PconnModule::registerWithCacheManager(), SBufStatsAction::RegisterWithCacheManager(), statRegisterWithCacheManager(), storeDigestInit(), storeLogRegisterWithCacheManager(), storeRegisterWithCacheManager(), TestCacheManager::testRegister(), and ClientDbRr::useConfig().
RegisterAction() [3/4]
void Mgr::RegisterAction (const char *const action, const char *const desc, ClassActionCreationHandler * handler, int pw_req_flag, int atomic) inline
Definition at line 46 of file Registration.h.
References informal, no, RegisterAction(), and yes.
RegisterAction() [4/4]
void Mgr::RegisterAction (const char *const action, const char *const desc, OBJH * handler, int pw_req_flag, int atomic) inline
Definition at line 28 of file Registration.h.
References informal, no, RegisterAction(), and yes.
RegisterBasics()
void Mgr::RegisterBasics ()
Definition at line 150 of file BasicActions.cc.
References Mgr::IndexAction::Create(), Mgr::MenuAction::Create(), Mgr::ShutdownAction::Create(), Mgr::ReconfigureAction::Create(), Mgr::RotateAction::Create(), Mgr::OfflineToggleAction::Create(), and RegisterAction().
Referenced by CacheManager::GetInstance().