Squid Web Cache: squid/src/auth/negotiate/wrapper/negotiate_wrapper.cc File Reference
negotiate_wrapper.cc File Reference
#include "squid.h"
#include "base64.h"
#include "compat/pipe.h"
#include "compat/unistd.h"
#include <cerrno>
#include <cstring>
#include <cstdlib>
#include <ctime>
Macros
#define xmalloc malloc
#define xstrdup strdup
#define xfree free
#define PROGRAM "negotiate_wrapper"
#define VERSION "1.0.1"
#define MAX_AUTHTOKEN_LEN 65535
Functions
static const char * LogTime ()
static void usage ()
static void closeFds (FILE *a, FILE *b, FILE *c, FILE *d)
static int processingLoop (FILE *FDKIN, FILE *FDKOUT, FILE *FDNIN, FILE *FDNOUT)
int main (int argc, char *const argv[])
Variables
static const unsigned char ntlmProtocol [] = {'N', 'T', 'L', 'M', 'S', 'S', 'P', 0}
Macro Definition Documentation
MAX_AUTHTOKEN_LEN
#define MAX_AUTHTOKEN_LEN 65535
Definition at line 59 of file negotiate_wrapper.cc.
PROGRAM
#define PROGRAM "negotiate_wrapper"
Definition at line 54 of file negotiate_wrapper.cc.
VERSION
#define VERSION "1.0.1"
Definition at line 56 of file negotiate_wrapper.cc.
xfree
#define xfree free
Definition at line 50 of file negotiate_wrapper.cc.
xmalloc
#define xmalloc malloc
Definition at line 44 of file negotiate_wrapper.cc.
xstrdup
#define xstrdup strdup
Definition at line 47 of file negotiate_wrapper.cc.
Function Documentation
closeFds()
static void closeFds (FILE * a, FILE * b, FILE * c, FILE * d) static
Definition at line 93 of file negotiate_wrapper.cc.
Referenced by main().
LogTime()
static const char * LogTime (void) static
Definition at line 65 of file negotiate_wrapper.cc.
Referenced by main(), and processingLoop().
main()
int main (int argc, char *const argv[])
Definition at line 281 of file negotiate_wrapper.cc.
References closeFds(), debug_enabled, LogTime(), processingLoop(), PROGRAM, strerror(), usage(), VERSION, xclose(), and xmalloc.
processingLoop()
static int processingLoop (FILE * FDKIN, FILE * FDKOUT, FILE * FDNIN, FILE * FDNOUT) static
Definition at line 106 of file negotiate_wrapper.cc.
References assert, base64_decode_final(), base64_decode_init(), BASE64_DECODE_LENGTH, base64_decode_update(), debug_enabled, LogTime(), MAX_AUTHTOKEN_LEN, ntlmProtocol, PROGRAM, safe_free, strerror(), xfree, and xmalloc.
Referenced by main().
usage()
static void usage (void) static
Definition at line 82 of file negotiate_wrapper.cc.
Referenced by main().
Variable Documentation
ntlmProtocol
const unsigned char ntlmProtocol[] = {'N', 'T', 'L', 'M', 'S', 'S', 'P', 0} static
Definition at line 62 of file negotiate_wrapper.cc.
Referenced by processingLoop().