Squid Web Cache: squid/src/ip/NfMarkConfig.cc File Reference
NfMarkConfig.cc File Reference
#include "squid.h"
#include "base/IoManip.h"
#include "ConfigParser.h"
#include "ip/NfMarkConfig.h"
#include "parser/Tokenizer.h"
#include "sbuf/Stream.h"
#include <limits>
Functions
static nfmark_t getNfmark (Parser::Tokenizer &tokenizer, const SBuf &token)
Function Documentation
getNfmark()
static nfmark_t getNfmark (Parser::Tokenizer & tokenizer, const SBuf & token) static
Definition at line 19 of file NfMarkConfig.cc.
References Parser::Tokenizer::buf(), Parser::Tokenizer::int64(), TexcHere, and ToSBuf().
Referenced by Ip::NfMarkConfig::Parse().