Squid Web Cache: squid/src/Notes.cc File Reference
Notes.cc File Reference
#include "squid.h"
#include "AccessLogEntry.h"
#include "acl/FilledChecklist.h"
#include "acl/Gadgets.h"
#include "acl/Tree.h"
#include "client_side.h"
#include "ConfigParser.h"
#include "globals.h"
#include "http/Stream.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "parser/Tokenizer.h"
#include "sbuf/Stream.h"
#include "sbuf/StringConvert.h"
#include "SquidConfig.h"
#include "Store.h"
#include "StrList.h"
#include <algorithm>
#include <ostream>
#include <string>
Functions
static void AppendTokens (NotePairs::Entries &entries, const SBuf &key, const SBuf &val, const CharacterSet &delimiters)
Function Documentation
AppendTokens()
static void AppendTokens (NotePairs::Entries & entries, const SBuf & key, const SBuf & val, const CharacterSet & delimiters) static
Definition at line 344 of file Notes.cc.
References CharacterSet::complement().
Referenced by NotePairs::addStrList(), and NotePairs::expandListEntries().