Squid Web Cache: squid/lib/ntlmauth/ntlmauth.h File Reference
ntlmauth.h File Reference
#include "ntlmauth/support_endian.h"
Classes
struct _strhdr
struct _lstring
struct _ntlmhdr
struct _ntlm_negotiate
struct _ntlm_challenge
struct _ntlm_authenticate
Macros
#define NTLM_MAX_FIELD_LENGTH 300 /* max length of an NTLMSSP field */
#define NTLM_BLOB_BUFFER_SIZE 10240
#define NTLM_REQUEST_INIT_RESPONSE 0x100000
#define NTLM_REQUEST_ACCEPT_RESPONSE 0x200000
#define NTLM_REQUEST_NON_NT_SESSION_KEY 0x400000
#define NTLM_ANY 0
#define NTLM_NEGOTIATE 1
#define NTLM_CHALLENGE 2
#define NTLM_AUTHENTICATE 3
#define NTLM_NEGOTIATE_UNICODE 0x0001
#define NTLM_NEGOTIATE_ASCII 0x0002
#define NTLM_NEGOTIATE_REQUEST_TARGET 0x0004
#define NTLM_NEGOTIATE_REQUEST_SIGN 0x0010
#define NTLM_NEGOTIATE_REQUEST_SEAL 0x0020
#define NTLM_NEGOTIATE_DATAGRAM_STYLE 0x0040
#define NTLM_NEGOTIATE_USE_LM 0x0080
#define NTLM_NEGOTIATE_USE_NETWARE 0x0100
#define NTLM_NEGOTIATE_USE_NTLM 0x0200
#define NTLM_NEGOTIATE_DOMAIN_SUPPLIED 0x1000
#define NTLM_NEGOTIATE_WORKSTATION_SUPPLIED 0x2000
#define NTLM_NEGOTIATE_THIS_IS_LOCAL_CALL 0x4000
#define NTLM_NEGOTIATE_ALWAYS_SIGN 0x8000
#define NTLM_NONCE_LEN 8
#define NTLM_CHALLENGE_TARGET_IS_DOMAIN 0x10000
#define NTLM_CHALLENGE_TARGET_IS_SERVER 0x20000
#define NTLM_CHALLENGE_TARGET_IS_SHARE 0x40000
#define NTLM_CHALLENGE_HEADER_OFFSET (sizeof(ntlm_challenge)-256)
Typedefs
typedef struct _strhdr strhdr
typedef struct _lstring lstring
typedef struct _ntlmhdr ntlmhdr
typedef struct _ntlm_negotiate ntlm_negotiate
typedef struct _ntlm_challenge ntlm_challenge
typedef struct _ntlm_authenticate ntlm_authenticate
Enumerations
enum class NtlmError {
None = 0 , ServerError , ProtocolError , LoginEror ,
UntrustedDomain , NotConnected , SspiError , BadNtGroup ,
BadRequest , InternalError , BlobError , BadProtocol
}
Functions
void ntlm_dump_ntlmssp_flags (const uint32_t flags)
NtlmError ntlm_validate_packet (const ntlmhdr *packet, const int32_t type)
lstring ntlm_fetch_string (const ntlmhdr *packet, const int32_t packet_length, const strhdr *str, const uint32_t flags)
void ntlm_add_to_payload (const ntlmhdr *packet_hdr, char *payload, int *payload_length, strhdr *hdr, const char *toadd, const uint16_t toadd_length)
void ntlm_make_nonce (char *nonce)
void ntlm_make_challenge (ntlm_challenge *ch, const char *domain, const char *domain_controller, const char *challenge_nonce, const int challenge_nonce_len, const uint32_t flags)
NtlmError ntlm_unpack_auth (const ntlm_authenticate *auth, char *user, char *domain, const int32_t size)
Macro Definition Documentation
NTLM_ANY
#define NTLM_ANY 0
Definition at line 68 of file ntlmauth.h.
NTLM_AUTHENTICATE
#define NTLM_AUTHENTICATE 3
Definition at line 71 of file ntlmauth.h.
NTLM_BLOB_BUFFER_SIZE
#define NTLM_BLOB_BUFFER_SIZE 10240
Definition at line 21 of file ntlmauth.h.
NTLM_CHALLENGE
#define NTLM_CHALLENGE 2
Definition at line 70 of file ntlmauth.h.
NTLM_CHALLENGE_HEADER_OFFSET
#define NTLM_CHALLENGE_HEADER_OFFSET (sizeof(ntlm_challenge)-256)
Definition at line 149 of file ntlmauth.h.
NTLM_CHALLENGE_TARGET_IS_DOMAIN
#define NTLM_CHALLENGE_TARGET_IS_DOMAIN 0x10000
Definition at line 133 of file ntlmauth.h.
NTLM_CHALLENGE_TARGET_IS_SERVER
#define NTLM_CHALLENGE_TARGET_IS_SERVER 0x20000
Definition at line 134 of file ntlmauth.h.
NTLM_CHALLENGE_TARGET_IS_SHARE
#define NTLM_CHALLENGE_TARGET_IS_SHARE 0x40000
Definition at line 135 of file ntlmauth.h.
NTLM_MAX_FIELD_LENGTH
#define NTLM_MAX_FIELD_LENGTH 300 /* max length of an NTLMSSP field */
Definition at line 18 of file ntlmauth.h.
NTLM_NEGOTIATE
#define NTLM_NEGOTIATE 1
Definition at line 69 of file ntlmauth.h.
NTLM_NEGOTIATE_ALWAYS_SIGN
#define NTLM_NEGOTIATE_ALWAYS_SIGN 0x8000
Definition at line 115 of file ntlmauth.h.
NTLM_NEGOTIATE_ASCII
#define NTLM_NEGOTIATE_ASCII 0x0002
Definition at line 104 of file ntlmauth.h.
NTLM_NEGOTIATE_DATAGRAM_STYLE
#define NTLM_NEGOTIATE_DATAGRAM_STYLE 0x0040
Definition at line 108 of file ntlmauth.h.
NTLM_NEGOTIATE_DOMAIN_SUPPLIED
#define NTLM_NEGOTIATE_DOMAIN_SUPPLIED 0x1000
Definition at line 112 of file ntlmauth.h.
NTLM_NEGOTIATE_REQUEST_SEAL
#define NTLM_NEGOTIATE_REQUEST_SEAL 0x0020
Definition at line 107 of file ntlmauth.h.
NTLM_NEGOTIATE_REQUEST_SIGN
#define NTLM_NEGOTIATE_REQUEST_SIGN 0x0010
Definition at line 106 of file ntlmauth.h.
NTLM_NEGOTIATE_REQUEST_TARGET
#define NTLM_NEGOTIATE_REQUEST_TARGET 0x0004
Definition at line 105 of file ntlmauth.h.
NTLM_NEGOTIATE_THIS_IS_LOCAL_CALL
#define NTLM_NEGOTIATE_THIS_IS_LOCAL_CALL 0x4000
Definition at line 114 of file ntlmauth.h.
NTLM_NEGOTIATE_UNICODE
#define NTLM_NEGOTIATE_UNICODE 0x0001
Definition at line 103 of file ntlmauth.h.
NTLM_NEGOTIATE_USE_LM
#define NTLM_NEGOTIATE_USE_LM 0x0080
Definition at line 109 of file ntlmauth.h.
NTLM_NEGOTIATE_USE_NETWARE
#define NTLM_NEGOTIATE_USE_NETWARE 0x0100
Definition at line 110 of file ntlmauth.h.
NTLM_NEGOTIATE_USE_NTLM
#define NTLM_NEGOTIATE_USE_NTLM 0x0200
Definition at line 111 of file ntlmauth.h.
NTLM_NEGOTIATE_WORKSTATION_SUPPLIED
#define NTLM_NEGOTIATE_WORKSTATION_SUPPLIED 0x2000
Definition at line 113 of file ntlmauth.h.
NTLM_NONCE_LEN
#define NTLM_NONCE_LEN 8
Definition at line 130 of file ntlmauth.h.
NTLM_REQUEST_ACCEPT_RESPONSE
#define NTLM_REQUEST_ACCEPT_RESPONSE 0x200000
Definition at line 27 of file ntlmauth.h.
NTLM_REQUEST_INIT_RESPONSE
#define NTLM_REQUEST_INIT_RESPONSE 0x100000
Definition at line 26 of file ntlmauth.h.
NTLM_REQUEST_NON_NT_SESSION_KEY
#define NTLM_REQUEST_NON_NT_SESSION_KEY 0x400000
Definition at line 28 of file ntlmauth.h.
Typedef Documentation
lstring
typedef struct _lstring lstring
We use this to keep data/length couples.
ntlm_authenticate
typedef struct _ntlm_authenticate ntlm_authenticate
Authentication request sent by client in response to challenge
ntlm_challenge
typedef struct _ntlm_challenge ntlm_challenge
Challenge request sent by server.
ntlm_negotiate
typedef struct _ntlm_negotiate ntlm_negotiate
Negotiation request sent by client
ntlmhdr
typedef struct _ntlmhdr ntlmhdr
This is an header common to all packets, it's used to discriminate among the different packet signature types.
strhdr
typedef struct _strhdr strhdr
String header. String data resides at the end of the request
Enumeration Type Documentation
NtlmError
enum class NtlmError strong
Enumerator
None
ServerError
ProtocolError
LoginEror
UntrustedDomain
NotConnected
SspiError
BadNtGroup
BadRequest
InternalError
BlobError
BadProtocol
Definition at line 31 of file ntlmauth.h.
Function Documentation
ntlm_add_to_payload()
void ntlm_add_to_payload (const ntlmhdr * packet_hdr, char * payload, int * payload_length, strhdr * hdr, const char * toadd, const uint16_t toadd_length)
Append a string to the NTLM packet payload.
Adds something to the payload. The caller must guarantee that there is enough space in the payload string to accommodate the added value. payload_length and hdr will be modified as a side-effect.
Definition at line 165 of file ntlmauth.cc.
References htole16, htole32, _strhdr::len, _strhdr::maxlen, and _strhdr::offset.
Referenced by ntlm_make_challenge().
ntlm_dump_ntlmssp_flags()
void ntlm_dump_ntlmssp_flags (uint32_t flags)
Debug dump the given flags field to stderr
Dumps NTLM flags to standard error for debugging purposes
Definition at line 30 of file ntlmauth.cc.
References NTLM_CHALLENGE_TARGET_IS_DOMAIN, NTLM_CHALLENGE_TARGET_IS_SERVER, NTLM_CHALLENGE_TARGET_IS_SHARE, NTLM_NEGOTIATE_ALWAYS_SIGN, NTLM_NEGOTIATE_ASCII, NTLM_NEGOTIATE_DATAGRAM_STYLE, NTLM_NEGOTIATE_DOMAIN_SUPPLIED, NTLM_NEGOTIATE_REQUEST_SEAL, NTLM_NEGOTIATE_REQUEST_SIGN, NTLM_NEGOTIATE_REQUEST_TARGET, NTLM_NEGOTIATE_THIS_IS_LOCAL_CALL, NTLM_NEGOTIATE_UNICODE, NTLM_NEGOTIATE_USE_LM, NTLM_NEGOTIATE_USE_NETWARE, NTLM_NEGOTIATE_USE_NTLM, NTLM_NEGOTIATE_WORKSTATION_SUPPLIED, NTLM_REQUEST_ACCEPT_RESPONSE, NTLM_REQUEST_INIT_RESPONSE, and NTLM_REQUEST_NON_NT_SESSION_KEY.
ntlm_fetch_string()
lstring ntlm_fetch_string (const ntlmhdr * packet, const int32_t packet_size, const strhdr * str, const uint32_t flags)
Retrieve a string from the NTLM packet payload.
Fetches a string from the authentication packet. The lstring data-part may point to inside the packet itself or a temporary static buffer. It's up to the user to memcpy() that if the value needs to be used in any way that requires a tailing \0. (can check whether the value is there though, in that case lstring.length == -1).
String may be either ASCII or UNICODE depending on whether flags contains NTLM_NEGOTIATE_ASCII
Definition at line 98 of file ntlmauth.cc.
References debug(), _lstring::l, le16toh, le32toh, _strhdr::len, NTLM_MAX_FIELD_LENGTH, NTLM_NEGOTIATE_ASCII, _strhdr::offset, _lstring::str, and xisprint.
Referenced by ntlm_unpack_auth().
ntlm_make_challenge()
void ntlm_make_challenge (ntlm_challenge * ch, const char * domain, const char * domain_controller, const char * challenge_nonce, const int challenge_nonce_len, const uint32_t flags)
Generate a challenge request Blob to be sent to the client. Will silently truncate the domain value at 2^16-1 bytes if larger.
Prepares a challenge packet to be sent to the client
Note
domain should be upper_case
Definition at line 210 of file ntlmauth.cc.
References _ntlm_challenge::challenge, _ntlm_challenge::context_high, _ntlm_challenge::context_low, _ntlm_challenge::flags, _ntlm_challenge::hdr, htole32, ntlm_add_to_payload(), NTLM_CHALLENGE, _ntlm_challenge::payload, _ntlmhdr::signature, _ntlm_challenge::target, and _ntlmhdr::type.
Referenced by main().
ntlm_make_nonce()
void ntlm_make_nonce (char * nonce)
Generate a challenge request nonce.
Definition at line 196 of file ntlmauth.cc.
References NTLM_NONCE_LEN.
Referenced by main().
ntlm_unpack_auth()
NtlmError ntlm_unpack_auth (const ntlm_authenticate * auth, char * user, char * domain, const int32_t size)
Unpack username and domain out of a packet payload.
Unpack the strings in an NTLM authentication response from client. The caller is responsible for initializing the user and domain buffers this function will only insert data if the packet contains any. Otherwise the buffers will be left untouched.
Return values
NtlmError::None username present, maybe also domain.
NtlmError::ProtocolError packet type is not an authentication packet.
NtlmError::LoginEror no username.
NtlmError::BlobError domain field is apparently larger than the packet.
Definition at line 247 of file ntlmauth.cc.
References BlobError, debug(), _ntlm_authenticate::domain, _ntlm_authenticate::flags, _ntlm_authenticate::hdr, _lstring::l, le32toh, _strhdr::len, _ntlm_authenticate::lmresponse, LoginEror, None, NTLM_AUTHENTICATE, ntlm_fetch_string(), NTLM_MAX_FIELD_LENGTH, ntlm_validate_packet(), _ntlm_authenticate::ntresponse, _strhdr::offset, ProtocolError, _ntlm_authenticate::sessionkey, size, _lstring::str, _ntlm_authenticate::user, and _ntlm_authenticate::workstation.
Referenced by main().
ntlm_validate_packet()
NtlmError ntlm_validate_packet (const ntlmhdr * hdr, const int32_t type)
Validate the packet type matches one we want.
Check the validity of a decoded NTLM packet.
Return values
NtlmError::None Packet is okay
NtlmError::BlobError Packet is not even an NTLMSSP packet at all.
NtlmError::ProtocolError Packet is not the expected type.
Definition at line 67 of file ntlmauth.cc.
References BlobError, debug(), le32toh, None, NTLM_ANY, ProtocolError, _ntlmhdr::signature, and _ntlmhdr::type.
Referenced by main(), and ntlm_unpack_auth().