Squid Web Cache: squid/src/mem/old_api.cc File Reference
old_api.cc File Reference
#include "squid.h"
#include "base/PackableStream.h"
#include "ClientInfo.h"
#include "dlink.h"
#include "event.h"
#include "fs_io.h"
#include "icmp/net_db.h"
#include "md5.h"
#include "mem/Allocator.h"
#include "mem/Pool.h"
#include "mem/Stats.h"
#include "MemBuf.h"
#include "mgr/Registration.h"
#include "SquidConfig.h"
#include "Store.h"
#include <iomanip>
Classes
struct PoolMeta
Functions
static void memFree32B (void *)
static void memFree64B (void *)
static void memFree128B (void *)
static void memFree256B (void *)
static void memFree512B (void *)
static void memFree1K (void *)
static void memFree2K (void *)
static void memFree4K (void *)
static void memFree8K (void *)
static void memFree16K (void *)
static void memFree32K (void *)
static void memFree64K (void *)
static Mem::Allocator *& GetPool (size_t type)
static void memDataInit (mem_type type, const char *name, size_t size, int, bool doZero)
void * memAllocate (mem_type type)
Allocate one element from the typed pool.
void memFree (void *p, int type)
Free a element allocated by memAllocate()
static mem_type memFindBufSizeType (size_t net_size, size_t *gross_size)
void * memAllocBuf (size_t net_size, size_t *gross_size)
void * memReallocBuf (void *oldbuf, size_t net_size, size_t *gross_size)
void memFreeBuf (size_t size, void *buf)
void memConfigure (void)
static mem_type & operator++ (mem_type &aMem)
void memClean (void)
Main cleanup handler.
int memInUse (mem_type type)
static void cxx_xfree (void *ptr)
FREE * memFreeBufFunc (size_t size)
Variables
static double xm_time = 0
static double xm_deltat = 0
static Mem::Meter HugeBufCountMeter
static Mem::Meter HugeBufVolumeMeter
static double clean_interval = 15.0
Function Documentation
cxx_xfree()
static void cxx_xfree (void * ptr) static
Definition at line 424 of file old_api.cc.
References xfree.
Referenced by memFreeBufFunc().
GetPool()
static Mem::Allocator *& GetPool (size_t type) static
Definition at line 60 of file old_api.cc.
References Mem::Init(), and MEM_MAX.
Referenced by Mem::Init(), memAllocate(), memDataInit(), memFree(), and memInUse().
memAllocate()
void * memAllocate (mem_type type)
Definition at line 122 of file old_api.cc.
References Mem::Allocator::alloc(), assert, and GetPool().
Referenced by memAllocBuf(), netdbBinaryExchange(), Ftp::Gateway::parseListing(), and storeKeyDup().
memAllocBuf()
void * memAllocBuf (size_t net_size, size_t * gross_size)
Definition at line 192 of file old_api.cc.
References HugeBufCountMeter, HugeBufVolumeMeter, MEM_NONE, memAllocate(), memFindBufSizeType(), and xmalloc.
Referenced by memReallocBuf().
memClean()
void memClean (void)
Definition at line 328 of file old_api.cc.
References Mem::PoolStats::chunks_inuse, MemPools::clean(), Config, debugs, MemPools::GetInstance(), Mem::GlobalStats(), Mem::PoolStats::items_inuse, SquidConfig::limit, SquidConfig::MemPools, and MemPools::setIdleLimit().
Referenced by SquidShutdown().
memConfigure()
void memConfigure (void)
Set to configured value first
Definition at line 254 of file old_api.cc.
References Config, DBG_IMPORTANT, debugs, MemPools::GetInstance(), SquidConfig::limit, SquidConfig::mem_pools, SquidConfig::MemPools, SquidConfig::onoff, and MemPools::setIdleLimit().
Referenced by configDoConfigure().
memDataInit()
static void memDataInit (mem_type type, const char * name, size_t size, int , bool doZero) static
Definition at line 109 of file old_api.cc.
References assert, GetPool(), memPoolCreate, size, and Mem::Allocator::zeroBlocks().
Referenced by Mem::Init().
memFindBufSizeType()
static mem_type memFindBufSizeType (size_t net_size, size_t * gross_size) static
Definition at line 138 of file old_api.cc.
References MEM_128B_BUF, MEM_16K_BUF, MEM_1K_BUF, MEM_256B_BUF, MEM_2K_BUF, MEM_32B_BUF, MEM_32K_BUF, MEM_4K_BUF, MEM_512B_BUF, MEM_64B_BUF, MEM_64K_BUF, MEM_8K_BUF, MEM_NONE, and size.
Referenced by memAllocBuf(), and memFreeBuf().
memFree()
void memFree (void * p, int type)
Definition at line 130 of file old_api.cc.
References assert, Mem::Allocator::freeOne(), and GetPool().
Referenced by memFree128B(), memFree16K(), memFree1K(), memFree256B(), memFree2K(), memFree32B(), memFree32K(), memFree4K(), memFree512B(), memFree64B(), memFree64K(), memFree8K(), and memFreeBuf().
memFree128B()
void memFree128B (void * p) static
Definition at line 364 of file old_api.cc.
References MEM_128B_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree16K()
void memFree16K (void * p) static
Definition at line 406 of file old_api.cc.
References MEM_16K_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree1K()
void memFree1K (void * p) static
Definition at line 382 of file old_api.cc.
References MEM_1K_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree256B()
void memFree256B (void * p) static
Definition at line 370 of file old_api.cc.
References MEM_256B_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree2K()
void memFree2K (void * p) static
Definition at line 388 of file old_api.cc.
References MEM_2K_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree32B()
void memFree32B (void * p) static
Definition at line 352 of file old_api.cc.
References MEM_32B_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree32K()
void memFree32K (void * p) static
Definition at line 412 of file old_api.cc.
References MEM_32K_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree4K()
void memFree4K (void * p) static
Definition at line 394 of file old_api.cc.
References MEM_4K_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree512B()
void memFree512B (void * p) static
Definition at line 376 of file old_api.cc.
References MEM_512B_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree64B()
void memFree64B (void * p) static
Definition at line 358 of file old_api.cc.
References MEM_64B_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree64K()
void memFree64K (void * p) static
Definition at line 418 of file old_api.cc.
References MEM_64K_BUF, and memFree().
Referenced by memFreeBufFunc().
memFree8K()
void memFree8K (void * p) static
Definition at line 400 of file old_api.cc.
References MEM_8K_BUF, and memFree().
Referenced by memFreeBufFunc().
memFreeBuf()
void memFreeBuf (size_t size, void * buf)
Definition at line 231 of file old_api.cc.
References HugeBufCountMeter, HugeBufVolumeMeter, MEM_NONE, memFindBufSizeType(), memFree(), size, and xfree.
Referenced by memReallocBuf().
memFreeBufFunc()
FREE * memFreeBufFunc (size_t size)
Definition at line 430 of file old_api.cc.
References cxx_xfree(), HugeBufCountMeter, HugeBufVolumeMeter, memFree128B(), memFree16K(), memFree1K(), memFree256B(), memFree2K(), memFree32B(), memFree32K(), memFree4K(), memFree512B(), memFree64B(), memFree64K(), memFree8K(), and size.
memInUse()
int memInUse (mem_type type)
Definition at line 344 of file old_api.cc.
References Mem::Allocator::getInUseCount(), and GetPool().
memReallocBuf()
void * memReallocBuf (void * oldbuf, size_t net_size, size_t * gross_size)
Definition at line 207 of file old_api.cc.
References memAllocBuf(), and memFreeBuf().
operator++()
static mem_type & operator++ (mem_type & aMem) static
Definition at line 273 of file old_api.cc.
Variable Documentation
clean_interval
double clean_interval = 15.0 static
Definition at line 244 of file old_api.cc.
Referenced by Mem::CleanIdlePools().
HugeBufCountMeter
Mem::Meter HugeBufCountMeter static
Definition at line 52 of file old_api.cc.
Referenced by memAllocBuf(), memFreeBuf(), memFreeBufFunc(), and Mem::Stats().
HugeBufVolumeMeter
Mem::Meter HugeBufVolumeMeter static
Definition at line 53 of file old_api.cc.
Referenced by memAllocBuf(), memFreeBuf(), memFreeBufFunc(), and Mem::Stats().
xm_deltat
double xm_deltat = 0 static
Definition at line 45 of file old_api.cc.
Referenced by DumpMallocStatistics(), Mem::PoolReport(), and Mem::Report().
xm_time
double xm_time = 0 static
Definition at line 44 of file old_api.cc.
Referenced by DumpMallocStatistics(), and Mem::Report().