Squid Web Cache: squid/compat/openssl.h File Reference
openssl.h File Reference
#include <algorithm>
Macros
#define OPENSSL_LH_delete lh_delete
#define OPENSSL_LH_strhash lh_strhash
#define OPENSSL_VERSION SSLEAY_VERSION
#define OpenSSL_version SSLeay_version
#define TLS_client_method SSLv23_client_method
#define TLS_server_method SSLv23_server_method
#define X509_STORE_CTX_set0_untrusted X509_STORE_CTX_set_chain
#define X509_getm_notAfter X509_get_notAfter
#define X509_getm_notBefore X509_get_notBefore
#define X509_set1_notAfter X509_set_notAfter
#define X509_set1_notBefore X509_set_notBefore
Functions
const unsigned char * ASN1_STRING_get0_data (const ASN1_STRING *x)
void * BIO_get_data (BIO *table)
void BIO_set_data (BIO *table, void *data)
void BIO_set_init (BIO *table, int init)
int BIO_get_init (BIO *table)
RSA * EVP_PKEY_get0_RSA (EVP_PKEY *pkey)
const SSL_CIPHER * SSL_CIPHER_find (SSL *ssl, const unsigned char *ptr)
const unsigned char * SSL_SESSION_get_id (const SSL_SESSION *s, unsigned int *len)
size_t SSL_get_client_random (const SSL *ssl, unsigned char *outStart, size_t outSizeMax)
size_t SSL_SESSION_get_master_key (const SSL_SESSION *session, unsigned char *outStart, size_t outSizeMax)
void X509_get0_signature (ASN1_BIT_STRING **psig, X509_ALGOR **palg, const X509 *x)
X509 * X509_STORE_CTX_get0_cert (X509_STORE_CTX *ctx)
STACK_OF (X509) *X509_STORE_CTX_get0_untrusted(X509_STORE_CTX *ctx)
int X509_VERIFY_PARAM_get_depth (const X509_VERIFY_PARAM *param)
X509_VERIFY_PARAM * SSL_get0_param (SSL *ssl)
void SQUID_OPENSSL_init_ssl (void)
Macro Definition Documentation
OPENSSL_LH_delete
#define OPENSSL_LH_delete lh_delete
Definition at line 128 of file openssl.h.
OPENSSL_LH_strhash
#define OPENSSL_LH_strhash lh_strhash
Definition at line 129 of file openssl.h.
OPENSSL_VERSION
#define OPENSSL_VERSION SSLEAY_VERSION
Definition at line 133 of file openssl.h.
OpenSSL_version
#define OpenSSL_version SSLeay_version
Definition at line 134 of file openssl.h.
TLS_client_method
#define TLS_client_method SSLv23_client_method
Definition at line 196 of file openssl.h.
TLS_server_method
#define TLS_server_method SSLv23_server_method
Definition at line 200 of file openssl.h.
X509_getm_notAfter
#define X509_getm_notAfter X509_get_notAfter
Definition at line 247 of file openssl.h.
X509_getm_notBefore
#define X509_getm_notBefore X509_get_notBefore
Definition at line 248 of file openssl.h.
X509_set1_notAfter
#define X509_set1_notAfter X509_set_notAfter
Definition at line 249 of file openssl.h.
X509_set1_notBefore
#define X509_set1_notBefore X509_set_notBefore
Definition at line 250 of file openssl.h.
X509_STORE_CTX_set0_untrusted
#define X509_STORE_CTX_set0_untrusted X509_STORE_CTX_set_chain
Note that all of the calls in this next group were renamed, or had the new name added at the same time as X509_STORE_CTX_get0_untrusted was implemented, in all supported OpenSSL-compatible libraries
Definition at line 246 of file openssl.h.
Function Documentation
ASN1_STRING_get0_data()
const unsigned char * ASN1_STRING_get0_data (const ASN1_STRING * x) inline
Definition at line 54 of file openssl.h.
Referenced by Ssl::findIssuerUri().
BIO_get_data()
void * BIO_get_data (BIO * table) inline
Definition at line 62 of file openssl.h.
Referenced by bio_sbuf_ctrl(), bio_sbuf_puts(), bio_sbuf_write(), Ssl::PeekingPeerConnector::checkForPeekAndSplice(), Ssl::PeekingPeerConnector::checkForPeekAndSpliceMatched(), ConnStateData::doPeekAndSpliceStep(), ConnStateData::getSslContextDone(), Ssl::PeekingPeerConnector::initialize(), Ssl::PeekingPeerConnector::noteNegotiationError(), Ssl::PeekingPeerConnector::noteWantWrite(), Security::PeerConnector::recordNegotiationDetails(), Security::NegotiationHistory::retrieveNegotiatedInfo(), squid_bio_ctrl(), squid_bio_destroy(), squid_bio_read(), squid_bio_write(), squid_ssl_info(), ConnStateData::startPeekAndSplice(), and Ssl::PeekingPeerConnector::startTunneling().
BIO_get_init()
int BIO_get_init (BIO * table) inline
Definition at line 82 of file openssl.h.
Referenced by squid_bio_ctrl().
BIO_set_data()
void BIO_set_data (BIO * table, void * data) inline
Definition at line 68 of file openssl.h.
Referenced by Ssl::BIO_new_SBuf(), bio_sbuf_create(), squid_bio_create(), squid_bio_ctrl(), and squid_bio_destroy().
BIO_set_init()
void BIO_set_init (BIO * table, int init) inline
Definition at line 74 of file openssl.h.
Referenced by Ssl::BIO_new_SBuf(), bio_sbuf_create(), and squid_bio_ctrl().
EVP_PKEY_get0_RSA()
RSA * EVP_PKEY_get0_RSA (EVP_PKEY * pkey) inline
Definition at line 104 of file openssl.h.
Referenced by mimicExtensions().
SQUID_OPENSSL_init_ssl()
void SQUID_OPENSSL_init_ssl (void) inline
Definition at line 308 of file openssl.h.
Referenced by Ssl::Initialize(), and main().
SSL_CIPHER_find()
const SSL_CIPHER * SSL_CIPHER_find (SSL * ssl, const unsigned char * ptr) inline
Definition at line 139 of file openssl.h.
Referenced by applyTlsDetailsToSSL().
SSL_get0_param()
X509_VERIFY_PARAM * SSL_get0_param (SSL * ssl) inline
Definition at line 300 of file openssl.h.
Referenced by Ssl::VerifyConnCertificates().
SSL_get_client_random()
size_t SSL_get_client_random (const SSL * ssl, unsigned char * outStart, size_t outSizeMax) inline
Definition at line 157 of file openssl.h.
References assert.
Referenced by Security::CommunicationSecrets::getClientRandom().
SSL_SESSION_get_id()
const unsigned char * SSL_SESSION_get_id (const SSL_SESSION * s, unsigned int * len) inline
Definition at line 147 of file openssl.h.
Referenced by Security::CommunicationSecrets::getSessionId(), and store_session_cb().
SSL_SESSION_get_master_key()
size_t SSL_SESSION_get_master_key (const SSL_SESSION * session, unsigned char * outStart, size_t outSizeMax) inline
Definition at line 178 of file openssl.h.
References assert.
Referenced by Security::CommunicationSecrets::getMasterKey().
STACK_OF()
STACK_OF (X509) inline
Definition at line 237 of file openssl.h.
Referenced by Ssl::certificateMatchesProperties(), Ssl::CertValidationMsg::composeRequest(), Ssl::HasMatchingSubjectName(), ssl_free_CertChain(), ssl_verify_cb(), Ssl::CertValidationMsg::tryParsingResponse(), Security::ServerOptions::updateContextClientCa(), and VerifyCtxCertificates().
X509_get0_signature()
void X509_get0_signature (ASN1_BIT_STRING ** psig, X509_ALGOR ** palg, const X509 * x) inline
Definition at line 219 of file openssl.h.
Referenced by Ssl::X509_get_signature().
X509_STORE_CTX_get0_cert()
X509 * X509_STORE_CTX_get0_cert (X509_STORE_CTX * ctx) inline
Definition at line 230 of file openssl.h.
Referenced by completeIssuers(), and ssl_verify_cb().
X509_VERIFY_PARAM_get_depth()
int X509_VERIFY_PARAM_get_depth (const X509_VERIFY_PARAM * param) inline
Definition at line 292 of file openssl.h.
Referenced by completeIssuers().