Squid Web Cache: squid/include/parse.h File Reference
parse.h File Reference
#include "snmp_vars.h"
Classes
struct enum_list
struct snmp_mib_tree
Macros
#define TYPE_OTHER 0
#define TYPE_OBJID 1
#define TYPE_OCTETSTR 2
#define TYPE_INTEGER 3
#define TYPE_NETADDR 4
#define TYPE_IPADDR 5
#define TYPE_COUNTER 6
#define TYPE_GAUGE 7
#define TYPE_TIMETICKS 8
#define TYPE_OPAQUE 9
#define TYPE_NULL 10
Functions
void init_mib (char *)
int read_objid (char *, oid *, int *)
void print_objid (oid *, int)
void sprint_objid (char *, oid *, int)
void print_variable (oid *, int, struct variable_list *)
void sprint_variable (char *, oid *, int, struct variable_list *)
void sprint_value (char *, oid *, int, struct variable_list *)
void print_value (oid *, int, struct variable_list *)
void print_oid_nums (oid *, int)
struct snmp_mib_tree * read_mib (char *)
Macro Definition Documentation
TYPE_COUNTER
#define TYPE_COUNTER 6
Definition at line 68 of file parse.h.
TYPE_GAUGE
#define TYPE_GAUGE 7
Definition at line 69 of file parse.h.
TYPE_INTEGER
#define TYPE_INTEGER 3
Definition at line 65 of file parse.h.
TYPE_IPADDR
#define TYPE_IPADDR 5
Definition at line 67 of file parse.h.
TYPE_NETADDR
#define TYPE_NETADDR 4
Definition at line 66 of file parse.h.
TYPE_NULL
#define TYPE_NULL 10
Definition at line 72 of file parse.h.
TYPE_OBJID
#define TYPE_OBJID 1
Definition at line 63 of file parse.h.
TYPE_OCTETSTR
#define TYPE_OCTETSTR 2
Definition at line 64 of file parse.h.
TYPE_OPAQUE
#define TYPE_OPAQUE 9
Definition at line 71 of file parse.h.
TYPE_OTHER
#define TYPE_OTHER 0
Definition at line 62 of file parse.h.
TYPE_TIMETICKS
#define TYPE_TIMETICKS 8
Definition at line 70 of file parse.h.
Function Documentation
init_mib()
void init_mib (char * file)
Definition at line 97 of file mib.c.
References Mib, NULL, and read_mib().
print_objid()
void print_objid (oid * objid, int objidlen)
Parameters
objidlen number of subidentifiers
Definition at line 263 of file mib.c.
References get_symbol(), Mib, and snmplib_debug().
print_oid_nums()
void print_oid_nums (oid * O, int len)
Definition at line 320 of file mib.c.
print_value()
void print_value (oid * , int , struct variable_list *)
print_variable()
void print_variable (oid * , int , struct variable_list *)
read_mib()
struct snmp_mib_tree * read_mib (char * filename)
Definition at line 1038 of file parse.c.
References build_tree(), NULL, parse(), snmplib_debug(), and xstrerr().
Referenced by init_mib().
read_objid()
int read_objid (char * input, oid * output, int * out_len)
Parameters
out_len number of subid's in "output"
Definition at line 230 of file mib.c.
References find_rfc1066_mib(), Mib, NULL, parse_subtree(), RFC1066_MIB, and snmplib_debug().
sprint_objid()
void sprint_objid (char * buf, oid * objid, int objidlen)
Parameters
objidlen number of subidentifiers
Definition at line 276 of file mib.c.
References get_symbol(), and Mib.
sprint_value()
void sprint_value (char * , oid * , int , struct variable_list *)
sprint_variable()
void sprint_variable (char * , oid * , int , struct variable_list *)