Squid Web Cache: squid/src/peer_userhash.h File Reference
peer_userhash.h File Reference
Functions
CachePeer * peerUserHashSelectParent (PeerSelector *)
Function Documentation
peerUserHashSelectParent()
CachePeer * peerUserHashSelectParent (PeerSelector * ps)
Definition at line 155 of file peer_userhash.cc.
References assert, HttpRequest::auth_user_request, debugs, peerHTTPOkay(), PeerSelector::request, ROTATE_LEFT, UserHashPeers(), and Auth::UserRequest::username().
Referenced by PeerSelector::selectSomeParent().