Squid Web Cache: squid/src/security/PeerOptions.h File Reference
PeerOptions.h File Reference
#include "base/YesNoNone.h"
#include "ConfigParser.h"
#include "security/Context.h"
#include "security/forward.h"
#include "security/KeyData.h"
#include "security/Session.h"
Classes
class Security::PeerOptions
TLS squid.conf settings for a remote server peer.
struct Security::PeerOptions::flags_
flags governing Squid internal TLS operations
class Security::FuturePeerContext
A combination of PeerOptions and the corresponding Context.
Namespaces
namespace Security
Network/connection security abstraction layer.
Macros
#define free_securePeerOptions(x) Security::ProxyOutgoingConfig().clear()
#define dump_securePeerOptions(e, n, x) do { PackableStream os_(*(e)); os_ << n; (x).dumpCfg(os_,""); os_ << '\n'; } while (false)
Functions
PeerOptions & Security::ProxyOutgoingConfig ()
configuration options for DIRECT server access
void parse_securePeerOptions (Security::PeerOptions *)
Macro Definition Documentation
dump_securePeerOptions
#define dump_securePeerOptions (e, n, x) do { PackableStream os_(*(e)); os_ << n; (x).dumpCfg(os_,""); os_ << '\n'; } while (false)
Definition at line 171 of file PeerOptions.h.
free_securePeerOptions
#define free_securePeerOptions (x) Security::ProxyOutgoingConfig().clear()
Definition at line 170 of file PeerOptions.h.
Function Documentation
parse_securePeerOptions()
void parse_securePeerOptions (Security::PeerOptions * opt)
Definition at line 810 of file PeerOptions.cc.
References ConfigParser::NextToken(), Security::PeerOptions::parse(), and Security::PeerOptions::parseOptions().