Squid Web Cache: squid/src/security/PeerOptions.cc File Reference
PeerOptions.cc File Reference
#include "squid.h"
#include "base/Packable.h"
#include "debug/Stream.h"
#include "fatal.h"
#include "globals.h"
#include "parser/Tokenizer.h"
#include "Parsing.h"
#include "security/PeerOptions.h"
#include "ssl/support.h"
#include <bitset>
Classes
struct ssl_option
set of options we can parse and what they map to
Functions
static const char * loadSystemTrustedCa (Security::ContextPointer &ctx)
void parse_securePeerOptions (Security::PeerOptions *opt)
Variables
static struct ssl_option ssl_options []
Function Documentation
loadSystemTrustedCa()
static const char * loadSystemTrustedCa (Security::ContextPointer & ctx) static
Definition at line 679 of file PeerOptions.cc.
References debugs, and Security::ErrorString().
Referenced by Security::PeerOptions::updateContextCa().
parse_securePeerOptions()
void parse_securePeerOptions (Security::PeerOptions * opt)
Definition at line 810 of file PeerOptions.cc.
References ConfigParser::NextToken(), Security::PeerOptions::parse(), and Security::PeerOptions::parseOptions().
Variable Documentation
ssl_options
struct ssl_option ssl_options[] static
Referenced by Security::PeerOptions::parseOptions().