Squid Web Cache: squid/src/peer_userhash.cc File Reference
peer_userhash.cc File Reference
#include "squid.h"
#include "auth/UserRequest.h"
#include "base/RunnersRegistry.h"
#include "CachePeer.h"
#include "CachePeers.h"
#include "globals.h"
#include "HttpRequest.h"
#include "mgr/Registration.h"
#include "neighbors.h"
#include "peer_userhash.h"
#include "PeerSelectState.h"
#include "SquidConfig.h"
#include "Store.h"
#include <cmath>
Classes
class PeerUserHashRr
reacts to RegisteredRunner events relevant to this module
Macros
#define ROTATE_LEFT(x, n) (((x) << (n)) | ((x) >> (32-(n))))
Functions
static auto & UserHashPeers ()
userhash peers ordered by their userhash weight
static void peerUserHashRegisterWithCacheManager (void)
static int peerSortWeight (const void *a, const void *b)
static void peerUserHashInit (void)
DefineRunnerRegistrator (PeerUserHashRr)
CachePeer * peerUserHashSelectParent (PeerSelector *ps)
static void peerUserHashCachemgr (StoreEntry *sentry)
Variables
static OBJH peerUserHashCachemgr
Macro Definition Documentation
ROTATE_LEFT
#define ROTATE_LEFT (x, n) (((x) << (n)) | ((x) >> (32-(n))))
Definition at line 30 of file peer_userhash.cc.
Function Documentation
DefineRunnerRegistrator()
DefineRunnerRegistrator (PeerUserHashRr)
peerSortWeight()
static int peerSortWeight (const void * a, const void * b) static
Definition at line 44 of file peer_userhash.cc.
References CachePeer::weight.
Referenced by peerUserHashInit().
peerUserHashCachemgr()
static void peerUserHashCachemgr (StoreEntry * sentry) static
Definition at line 208 of file peer_userhash.cc.
References storeAppendPrintf(), and UserHashPeers().
peerUserHashInit()
static void peerUserHashInit (void) static
Definition at line 52 of file peer_userhash.cc.
References assert, CurrentCachePeers(), double, int, PEER_PARENT, peerSortWeight(), peerUserHashRegisterWithCacheManager(), ROTATE_LEFT, and UserHashPeers().
Referenced by PeerUserHashRr::syncConfig(), and PeerUserHashRr::useConfig().
peerUserHashRegisterWithCacheManager()
static void peerUserHashRegisterWithCacheManager (void) static
Definition at line 137 of file peer_userhash.cc.
References peerUserHashCachemgr, and Mgr::RegisterAction().
Referenced by peerUserHashInit().
peerUserHashSelectParent()
CachePeer * peerUserHashSelectParent (PeerSelector * ps)
Definition at line 155 of file peer_userhash.cc.
References assert, HttpRequest::auth_user_request, debugs, peerHTTPOkay(), PeerSelector::request, ROTATE_LEFT, UserHashPeers(), and Auth::UserRequest::username().
Referenced by PeerSelector::selectSomeParent().
UserHashPeers()
static auto & UserHashPeers () static
Definition at line 34 of file peer_userhash.cc.
Referenced by peerUserHashCachemgr(), peerUserHashInit(), and peerUserHashSelectParent().
Variable Documentation
peerUserHashCachemgr
OBJH peerUserHashCachemgr static
Definition at line 40 of file peer_userhash.cc.
Referenced by peerUserHashRegisterWithCacheManager().