Squid Web Cache: squid/src/mem/PoolChunked.cc File Reference
PoolChunked.cc File Reference
#include "squid.h"
#include "mem/PoolChunked.h"
#include "mem/Stats.h"
#include <cassert>
#include <cstring>
Macros
#define MEM_MAX_MMAP_CHUNKS 2048
#define MEM_PAGE_SIZE 4096
#define MEM_MIN_FREE 32
#define MEM_MAX_FREE 65535 /* unsigned short is max number of items per chunk */
Functions
static int memCompChunks (MemChunk *const &, MemChunk *const &)
static int memCompObjChunks (void *const &, MemChunk *const &)
Variables
time_t squid_curtime
Macro Definition Documentation
MEM_MAX_FREE
#define MEM_MAX_FREE 65535 /* unsigned short is max number of items per chunk */
Definition at line 23 of file PoolChunked.cc.
MEM_MAX_MMAP_CHUNKS
#define MEM_MAX_MMAP_CHUNKS 2048
Definition at line 20 of file PoolChunked.cc.
MEM_MIN_FREE
#define MEM_MIN_FREE 32
Definition at line 22 of file PoolChunked.cc.
MEM_PAGE_SIZE
#define MEM_PAGE_SIZE 4096
Definition at line 21 of file PoolChunked.cc.
Function Documentation
memCompChunks()
static int memCompChunks (MemChunk *const & chunkA, MemChunk *const & chunkB) static
Definition at line 80 of file PoolChunked.cc.
References MemChunk::objCache.
Referenced by MemChunk::MemChunk(), and MemChunk::~MemChunk().
memCompObjChunks()
static int memCompObjChunks (void *const & obj, MemChunk *const & chunk) static
Definition at line 92 of file PoolChunked.cc.
References MemPoolChunked::chunk_size, MemChunk::objCache, and MemChunk::pool.
Referenced by MemPoolChunked::convertFreeCacheToChunkFreeCache().
Variable Documentation
squid_curtime
time_t squid_curtime extern
Definition at line 20 of file stub_libtime.cc.