Squid Web Cache: squid/src/protos.h File Reference
protos.h File Reference
Functions
void shut_down (int)
void rotate_logs (int)
void reconfigure (int)
Function Documentation
reconfigure()
void reconfigure (int sig)
Definition at line 706 of file main.cc.
References do_reconfigure, reconfigure(), and ReconfigureSignal.
Referenced by Mgr::ReconfigureAction::dump(), mainInitialize(), reconfigure(), watch_child(), WIN32_IpAddrChangeMonitor(), and WIN32_svcHandler().
rotate_logs()
void rotate_logs (int sig)
Definition at line 692 of file main.cc.
References do_rotate, rotate_logs(), and RotateSignal.
Referenced by Mgr::RotateAction::dump(), mainInitialize(), rotate_logs(), watch_child(), and WIN32_svcHandler().
shut_down()
void shut_down (int sig)
Definition at line 747 of file main.cc.
References do_shutdown, shut_down(), shutdown_status, and ShutdownSignal.
Referenced by Mgr::ShutdownAction::dump(), mainInitialize(), shut_down(), and WIN32_svcHandler().