Squid Web Cache: squid/src/ip/QosConfig.cc File Reference
QosConfig.cc File Reference
#include "squid.h"
#include "acl/Gadgets.h"
#include "base/IoManip.h"
#include "base/PackableStream.h"
#include "base/TextException.h"
#include "cache_cf.h"
#include "comm/Connection.h"
#include "compat/cmsg.h"
#include "compat/socket.h"
#include "ConfigParser.h"
#include "fde.h"
#include "globals.h"
#include "hier_code.h"
#include "ip/QosConfig.h"
#include "ip/tools.h"
#include "Parsing.h"
#include "sbuf/Stream.h"
#include "Store.h"
#include <cerrno>
#include <limits>
Functions
CBDATA_CLASS_INIT (acl_tos)
CBDATA_CLASS_INIT (acl_nfmark)
template<class Integer >
static auto asQosConfigHex (const Integer n)
helper function for printing Ip::Qos::Config mark and tos values
void dump_QosConfig (StoreEntry *const entry, const char *const directiveName, const Ip::Qos::Config &config)
Function Documentation
asQosConfigHex()
template<class Integer > static auto asQosConfigHex (const Integer n) static
Definition at line 455 of file QosConfig.cc.
References asHex().
Referenced by Ip::Qos::Config::dumpConfigLine().
CBDATA_CLASS_INIT() [1/2]
CBDATA_CLASS_INIT (acl_nfmark)
CBDATA_CLASS_INIT() [2/2]
CBDATA_CLASS_INIT (acl_tos)
dump_QosConfig()
void dump_QosConfig (StoreEntry *const entry, const char *const directiveName, const Ip::Qos::Config & config)
Definition at line 632 of file QosConfig.cc.
References Ip::Qos::Config::dumpConfigLine().