Squid Web Cache: squid/src/auth/basic/RADIUS/radius-util.cc File Reference
radius-util.cc File Reference
#include "squid.h"
#include "auth/basic/RADIUS/radius-util.h"
#include "compat/netdb.h"
#include "compat/socket.h"
#include "md5.h"
#include <cctype>
#include <csignal>
#include <ctime>
Functions
static int good_ipaddr (char *addr)
static uint32_t ipstr2long (char *ip_str)
uint32_t get_ipaddr (char *host)
Variables
char util_sccsid []
Function Documentation
get_ipaddr()
uint32_t get_ipaddr (char * host)
Definition at line 139 of file radius-util.cc.
References good_ipaddr(), ipstr2long(), and xgethostbyname().
Referenced by main().
good_ipaddr()
static int good_ipaddr (char * addr) static
Definition at line 66 of file radius-util.cc.
Referenced by get_ipaddr().
ipstr2long()
static uint32_t ipstr2long (char * ip_str) static
Definition at line 98 of file radius-util.cc.
Referenced by get_ipaddr().
Variable Documentation
util_sccsid
char util_sccsid[]
Initial value:
=
    "@(#)util.c 1.5 Copyright 1992 Livingston Enterprises Inc\n"
    "       2.1 Copyright 1997 Cistron Internet Services B.V."
Definition at line 43 of file radius-util.cc.