Squid Web Cache: squid/src/redirect.h File Reference
redirect.h File Reference
#include "helper.h"
Enumerations
enum TimeoutAction { toutActBypass , toutActFail , toutActRetry , toutActUseConfiguredResponse }
Functions
void redirectInit (void)
void redirectShutdown (void)
void redirectReconfigure ()
void redirectStart (ClientHttpRequest *, HLPCB *, void *)
void storeIdStart (ClientHttpRequest *, HLPCB *, void *)
Enumeration Type Documentation
TimeoutAction
enum TimeoutAction
Enumerator
toutActBypass
toutActFail
toutActRetry
toutActUseConfiguredResponse
Definition at line 16 of file redirect.h.
Function Documentation
redirectInit()
void redirectInit (void)
Definition at line 334 of file redirect.cc.
References SquidConfig::UrlHelperTimeout::action, Config, Helper::ChildConfig::defaultQueueSize, IPC_STREAM, Helper::Client::Make(), SquidConfig::onoff, SquidConfig::onUrlRewriteTimeout, Format::Format::parse(), SquidConfig::Program, Helper::ChildConfig::queue_size, SquidConfig::redirect, SquidConfig::redirectChildren, SquidConfig::redirector_bypass, SquidConfig::redirector_extras, redirectorExtrasFmt, redirectors, redirectStats, Mgr::RegisterAction(), SquidConfig::UrlHelperTimeout::response, SquidConfig::store_id, SquidConfig::store_id_bypass, SquidConfig::storeId_extras, SquidConfig::storeIdChildren, storeIdExtrasFmt, storeIds, storeIdStats, SquidConfig::Timeout, toutActRetry, toutActUseConfiguredResponse, and SquidConfig::urlRewrite.
Referenced by mainInitialize(), mainRotate(), and redirectReconfigure().
redirectReconfigure()
void redirectReconfigure ()
Definition at line 434 of file redirect.cc.
References redirectInit(), and redirectShutdown().
Referenced by mainReconfigureFinish().
redirectShutdown()
void redirectShutdown (void)
TODO: Temporary unified helpers Shutdown When and if needed for more helpers a separated shutdown method will be added for each of them.
Definition at line 407 of file redirect.cc.
References helperShutdown(), redirectorExtrasFmt, redirectors, shutting_down, storeIdExtrasFmt, and storeIds.
Referenced by mainRotate(), redirectReconfigure(), and SquidShutdown().
redirectStart()
void redirectStart (ClientHttpRequest * http, HLPCB * handler, void * data)
Definition at line 286 of file redirect.cc.
References NotePairs::add(), assert, Config, constructHelperQuery(), debugs, Helper::Reply::notes, Helper::Okay, SquidConfig::onoff, redirectHandleReply, SquidConfig::redirector_bypass, redirectorBypassed, redirectorExtrasFmt, redirectors, Helper::Reply::result, and ClientHttpRequest::uri.
Referenced by clientRedirectAccessCheckDone(), and ClientRequestContext::clientRedirectStart().
storeIdStart()
void storeIdStart (ClientHttpRequest * http, HLPCB * handler, void * data)
Handles the StoreID feature helper starting. For now it cannot be done using the redirectStart method.
Definition at line 312 of file redirect.cc.
References NotePairs::add(), assert, Config, constructHelperQuery(), debugs, Helper::Reply::notes, Helper::Okay, SquidConfig::onoff, Helper::Reply::result, SquidConfig::store_id_bypass, storeIdBypassed, storeIdExtrasFmt, storeIdHandleReply, storeIds, and ClientHttpRequest::uri.
Referenced by clientStoreIdAccessCheckDone(), and ClientRequestContext::clientStoreIdStart().