Squid Web Cache: squid/src/RemovalPolicy.h File Reference
RemovalPolicy.h File Reference
#include "cbdata.h"
Classes
class RemovalPolicySettings
class RemovalPolicyNode
class RemovalPolicy
class RemovalPolicyWalker
class RemovalPurgeWalker
Typedefs
typedef RemovalPolicy * REMOVALPOLICYCREATE(wordlist *args)
Functions
RemovalPolicy * createRemovalPolicy (RemovalPolicySettings *settings)
Typedef Documentation
REMOVALPOLICYCREATE
typedef RemovalPolicy * REMOVALPOLICYCREATE(wordlist *args)
Definition at line 80 of file RemovalPolicy.h.
Function Documentation
createRemovalPolicy()
RemovalPolicy * createRemovalPolicy (RemovalPolicySettings * settings)
Definition at line 1671 of file store.cc.
References RemovalPolicySettings::args, _storerepl_entry::create, DBG_IMPORTANT, debugs, fatalf(), storerepl_list, RemovalPolicySettings::type, and _storerepl_entry::typestr.
Referenced by Fs::Ufs::UFSSwapDir::parse(), TestUfs::testUfsDefaultEngine(), and TestUfs::testUfsSearch().