Squid Web Cache: squid/src/ResolvedPeers.h File Reference
ResolvedPeers.h File Reference
#include "base/RefCount.h"
#include "comm/Connection.h"
#include "mem/AllocatorProxy.h"
#include <iosfwd>
#include <limits>
#include <utility>
Classes
class ResolvedPeerPath
class ResolvedPeers
class PeerConnectionPointer
Functions
std::ostream & operator<< (std::ostream &, const ResolvedPeers &)
summarized ResolvedPeers (for debugging)
std::ostream & operator<< (std::ostream &os, const PeerConnectionPointer &dest)
Function Documentation
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const ResolvedPeers & peers)
Definition at line 220 of file ResolvedPeers.cc.
References ResolvedPeers::destinationsFinalized, ResolvedPeers::empty(), and ResolvedPeers::size().
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const PeerConnectionPointer & dest) inline
Definition at line 159 of file ResolvedPeers.h.
References PeerConnectionPointer::print().