Squid Web Cache: squid/include/rfc2617.h File Reference
rfc2617.h File Reference
Macros
#define HASHLEN 16
#define HASHHEXLEN 32
Typedefs
typedef char HASH[HASHLEN]
typedef char HASHHEX[HASHHEXLEN+1]
Functions
void DigestCalcHA1 (const char *pszAlg, const char *pszUserName, const char *pszRealm, const char *pszPassword, const char *pszNonce, const char *pszCNonce, HASH HA1, HASHHEX SessionKey)
void DigestCalcResponse (const HASHHEX HA1, const char *pszNonce, const char *pszNonceCount, const char *pszCNonce, const char *pszQop, const char *pszMethod, const char *pszDigestUri, const HASHHEX HEntity, HASHHEX Response)
void CvtHex (const HASH Bin, HASHHEX Hex)
void CvtBin (const HASHHEX Hex, HASH Bin)
Macro Definition Documentation
HASHHEXLEN
#define HASHHEXLEN 32
Definition at line 28 of file rfc2617.h.
HASHLEN
#define HASHLEN 16
Definition at line 26 of file rfc2617.h.
Typedef Documentation
HASH
typedef char HASH[HASHLEN]
Definition at line 27 of file rfc2617.h.
HASHHEX
typedef char HASHHEX[HASHHEXLEN+1]
Definition at line 29 of file rfc2617.h.
Function Documentation
CvtBin()
void CvtBin (const HASHHEX Hex, HASH Bin) extern
Definition at line 49 of file rfc2617.cc.
References HASHHEXLEN, and HASHLEN.
CvtHex()
void CvtHex (const HASH Bin, HASHHEX Hex) extern
Definition at line 28 of file rfc2617.cc.
References HASHHEXLEN, and HASHLEN.
Referenced by authDigestNonceEncode(), DigestCalcHA1(), and DigestCalcResponse().
DigestCalcHA1()
void DigestCalcHA1 (const char * pszAlg, const char * pszUserName, const char * pszRealm, const char * pszPassword, const char * pszNonce, const char * pszCNonce, HASH HA1, HASHHEX SessionKey) extern
Definition at line 88 of file rfc2617.cc.
References CvtHex(), HASHHEXLEN, SquidMD5Final(), SquidMD5Init(), and SquidMD5Update().
Referenced by LDAPHHA1(), and TextHHA1().
DigestCalcResponse()
void DigestCalcResponse (const HASHHEX HA1, const char * pszNonce, const char * pszNonceCount, const char * pszCNonce, const char * pszQop, const char * pszMethod, const char * pszDigestUri, const HASHHEX HEntity, HASHHEX Response) extern
Definition at line 126 of file rfc2617.cc.
References CvtHex(), HASHHEXLEN, SquidMD5Final(), SquidMD5Init(), and SquidMD5Update().