Squid Web Cache: squid/src/dns/rfc2671.cc File Reference
rfc2671.cc File Reference
#include "squid.h"
#include "dns/rfc1035.h"
#include "dns/rfc2671.h"
Functions
int rfc2671RROptPack (char *buf, size_t sz, ssize_t edns_sz)
Function Documentation
rfc2671RROptPack()
int rfc2671RROptPack (char * buf, size_t sz, ssize_t edns_sz)
Definition at line 14 of file rfc2671.cc.
References rfc1035_rr::_class, min(), rfc1035_rr::name, rfc1035_rr::rdata, rfc1035_rr::rdlength, RFC1035_MAXHOSTNAMESZ, RFC1035_TYPE_OPT, rfc1035RRPack(), SQUID_UDP_SO_RCVBUF, rfc1035_rr::ttl, and rfc1035_rr::type.
Referenced by rfc1035BuildAQuery(), rfc1035BuildPTRQuery(), and rfc3596BuildHostQuery().