Squid Web Cache: squid/src/fs/rock/RockRebuild.cc File Reference
RockRebuild.cc File Reference
#include "squid.h"
#include "base/AsyncJobCalls.h"
#include "compat/unistd.h"
#include "debug/Messages.h"
#include "fs/rock/RockDbCell.h"
#include "fs/rock/RockRebuild.h"
#include "fs/rock/RockSwapDir.h"
#include "fs_io.h"
#include "globals.h"
#include "md5.h"
#include "sbuf/Stream.h"
#include "SquidMath.h"
#include "Store.h"
#include "tools.h"
#include <array>
#include <cerrno>
#include <cstring>
Classes
class Rock::LoadingFlags
low-level anti-padding storage class for LoadingEntry and LoadingSlot flags
class Rock::LoadingEntry
smart StoreEntry-level info pointer (hides anti-padding LoadingParts arrays)
class Rock::LoadingSlot
smart db slot-level info pointer (hides anti-padding LoadingParts arrays)
class Rock::LoadingParts
Namespaces
namespace Rock
Functions
CBDATA_NAMESPACED_CLASS_INIT (Rock, Rebuild)
static bool Rock::DoneLoading (const int64_t loadingPos, const int64_t dbSlotLimit)
static bool Rock::DoneValidating (const int64_t validationPos, const int64_t dbSlotLimit, const int64_t dbEntryLimit)
template<class T >
T::Owner * createOwner (const char *dirPath, const char *sfx, const int64_t limit, const bool resuming)
static bool ZeroedSlot (const MemBuf &buf)
Function Documentation
CBDATA_NAMESPACED_CLASS_INIT()
CBDATA_NAMESPACED_CLASS_INIT (Rock , Rebuild)
createOwner()
template<class T > T::Owner * createOwner (const char * dirPath, const char * sfx, const int64_t limit, const bool resuming) inline
Definition at line 219 of file RockRebuild.cc.
References Ipc::Mem::Segment::Name(), Ipc::Mem::Owner< Class >::Old(), and shm_new.
ZeroedSlot()
static bool ZeroedSlot (const MemBuf & buf) static
whether the given slot buffer is likely to have nothing but zeros, as is common to slots in pre-initialized (with zeros) db files
Definition at line 517 of file RockRebuild.cc.
References MemBuf::content(), and MemBuf::contentSize().
Referenced by Rock::Rebuild::importEntry().