Squid Web Cache: squid/src/SBufStatsAction.cc File Reference
SBufStatsAction.cc File Reference
#include "squid.h"
#include "base/PackableStream.h"
#include "ipc/Messages.h"
#include "ipc/TypedMsgHdr.h"
#include "mgr/Registration.h"
#include "sbuf/Stats.h"
#include "SBufStatsAction.h"
Functions
static StatHist * makeDestructTimeHist ()
creates a new size-at-destruct-time histogram
static StatHist & collectSBufDestructTimeStats ()
the SBuf size-at-destruct-time histogram
static StatHist & collectMemBlobDestructTimeStats ()
the MemBlob size-at-destruct-time histogram
static void recordSBufSizeAtDestruct (const size_t sz)
record the size an SBuf had when it was destructed
static void recordMemBlobSizeAtDestruct (const size_t sz)
record the size a MemBlob had when it was destructed
static void statHistSBufDumper (StoreEntry *sentry, int, double val, double size, int count)
Function Documentation
collectMemBlobDestructTimeStats()
static StatHist & collectMemBlobDestructTimeStats () static
Definition at line 35 of file SBufStatsAction.cc.
References makeDestructTimeHist().
Referenced by SBufStatsAction::collect(), and recordMemBlobSizeAtDestruct().
collectSBufDestructTimeStats()
static StatHist & collectSBufDestructTimeStats () static
Definition at line 27 of file SBufStatsAction.cc.
References makeDestructTimeHist().
Referenced by SBufStatsAction::collect(), and recordSBufSizeAtDestruct().
makeDestructTimeHist()
static StatHist * makeDestructTimeHist () static
Definition at line 19 of file SBufStatsAction.cc.
References StatHist::logInit().
Referenced by collectMemBlobDestructTimeStats(), and collectSBufDestructTimeStats().
recordMemBlobSizeAtDestruct()
static void recordMemBlobSizeAtDestruct (const size_t sz) static
Definition at line 50 of file SBufStatsAction.cc.
References collectMemBlobDestructTimeStats(), and StatHist::count().
Referenced by SBufStatsAction::RegisterWithCacheManager().
recordSBufSizeAtDestruct()
static void recordSBufSizeAtDestruct (const size_t sz) static
Definition at line 43 of file SBufStatsAction.cc.
References collectSBufDestructTimeStats(), and StatHist::count().
Referenced by SBufStatsAction::RegisterWithCacheManager().
statHistSBufDumper()
static void statHistSBufDumper (StoreEntry * sentry, int , double val, double size, int count) static
Definition at line 84 of file SBufStatsAction.cc.
References size, and storeAppendPrintf().
Referenced by SBufStatsAction::dump().