Squid Web Cache: squid/src/sbuf/Stream.h File Reference
Stream.h File Reference
#include "base/PackableStream.h"
#include "sbuf/SBuf.h"
Classes
class SBufStream
Functions
template<typename... Args>
SBuf ToSBuf (Args &&... args)
slowly stream-prints all arguments into a freshly allocated SBuf
Function Documentation
ToSBuf()
template<typename... Args> SBuf ToSBuf (Args &&... args) inline
Definition at line 63 of file Stream.h.
References SBufStream::buf().
Referenced by PeerPoolMgr::PeerPoolMgr(), RegexPattern::RegexPattern(), Store::SwapMetaUnpacker::SwapMetaUnpacker(), Note::Value::Value(), Comm::TcpAcceptor::acceptInto(), aclParseAccessLine(), aclParseAclList(), addAltNameWithSubjectCn(), Acl::OptionExtractor::advance(), Format::Format::assemble(), Notes::banReservedKey(), Ftp::ErrorDetail::brief(), ExceptionErrorDetail::brief(), SysErrorDetail::brief(), ConfigParser::cachePeer(), Store::SwapMetaView::checkExpectedLength(), ConfigParser::closeDirective(), comm_apply_flags(), HttpUpgradeProtocolAccess::configureGuard(), MemStore::copyFromShm(), Ssl::CertificateDb::Create(), ConfigParser::CurrentLocation(), Ssl::CertificateDb::deleteRow(), Auth::UserRequest::denyMessageFromHelper(), Acl::ConnMark::dump(), Acl::OptionExtractor::extractOne(), Acl::FinalizedParameterizedNode< Parent >::FinalizePoolLabel(), FromNanoseconds(), getNfmark(), GetOtherPid(), ProxyProtocol::Header::getValues(), GoIntoBackground(), Store::ParsingBuffer::growSpace(), Ssl::CertValidationHelper::Init(), ProxyProtocol::IntegerToFieldType(), KeyString(), Ssl::CertificateDb::load(), Ssl::Lock::lock(), main(), main(), Acl::Make(), makeTraceable(), Acl::ServerNameCheck::match(), ProxyProtocol::NameToFieldType(), ErrorState::noteBuildError_(), ConfigParser::optionalKvPair(), Acl::OptionsParser::parse(), Configuration::Parse(), Acl::AllOf::parse(), ACLAtStepData::parse(), Acl::ConnMark::parse(), Format::Token::parse(), ProxyProtocol::Two::Parse(), Ip::NfMarkConfig::Parse(), Store::Disks::Parse(), parse_cache_log_message(), parse_obsolete(), parse_peer(), parse_port_option(), parse_time_t(), ParseAclWithAction(), parseBytesOptionValue(), parseBytesUnits(), Ip::Qos::Config::parseConfigLine(), ParseDebugMessageId(), FormattedLog::parseOptions(), Security::ParseProtocolVersionBase(), parseQuotedStringSuffix(), Ssl::CrtdMessage::parseRequest(), Http::One::ResponseParser::ParseResponseStatus(), HttpReply::parseTerminatedPrefix(), parseTimeLine(), parseTimeUnit(), ParseUnsignedDecimalInteger(), CacheManager::ParseUrl(), PidFileDescription(), Parser::Tokenizer::prefix(), processActivity(), Ipc::Port::receive(), Ipc::QuestionerId::rejectAnswerIfStale(), Ssl::CertificateDb::save(), sendSignal(), Acl::SetKey(), FormattedLog::setLogformat(), Parser::Tokenizer::skipRequired(), SlowlyParseQuotedField(), Http::SlowlyParseQuotedString(), StepValue(), Acl::OptionsParser::supportedOption(), File::sysCallFailure(), TestUri::testEncoding(), TestRandomUuid::testTextRepresentation(), TestRandomUuid::testUniqueness(), ThrowErrors(), ThrowIfAlreadyRunningWith(), ConfigParser::token(), ToNanoSeconds(), Ssl::CertValidationMsg::tryParsingResponse(), Parser::Tokenizer::udec64(), Ssl::Lock::unlock(), StoreEntry::updateOnNotModified(), Ftp::ErrorDetail::verbose(), ExceptionErrorDetail::verbose(), Ssl::CertificateDb::writeSize(), xatoui(), and xatoull().