Squid Web Cache: squid/src/mgr/ServiceTimesAction.cc File Reference
ServiceTimesAction.cc File Reference
#include "squid.h"
#include "base/TextException.h"
#include "ipc/Messages.h"
#include "ipc/TypedMsgHdr.h"
#include "mgr/ServiceTimesAction.h"
#include "Store.h"
#include "tools.h"
Functions
void GetServiceTimesStats (Mgr::ServiceTimesActionData &stats)
void DumpServiceTimesStats (Mgr::ServiceTimesActionData &stats, StoreEntry *sentry)
Function Documentation
DumpServiceTimesStats()
void DumpServiceTimesStats (Mgr::ServiceTimesActionData & stats, StoreEntry * sentry)
Definition at line 805 of file stat.cc.
References Mgr::ServiceTimesActionData::cache_hits5, Mgr::ServiceTimesActionData::cache_hits60, Mgr::ServiceTimesActionData::cache_misses5, Mgr::ServiceTimesActionData::cache_misses60, Mgr::ServiceTimesActionData::count, Mgr::ServiceTimesActionData::dns_lookups5, Mgr::ServiceTimesActionData::dns_lookups60, Mgr::ServiceTimesActionData::http_requests5, Mgr::ServiceTimesActionData::http_requests60, Mgr::ServiceTimesActionData::icp_queries5, Mgr::ServiceTimesActionData::icp_queries60, Mgr::ServiceTimesActionData::near_hits5, Mgr::ServiceTimesActionData::near_hits60, Mgr::ServiceTimesActionData::not_modified_replies5, Mgr::ServiceTimesActionData::not_modified_replies60, Mgr::ServiceTimesActionData::seriesSize, and storeAppendPrintf().
Referenced by Mgr::ServiceTimesAction::dump().
GetServiceTimesStats()
void GetServiceTimesStats (Mgr::ServiceTimesActionData & stats)
Definition at line 777 of file stat.cc.
References Mgr::ServiceTimesActionData::cache_hits5, Mgr::ServiceTimesActionData::cache_hits60, Mgr::ServiceTimesActionData::cache_misses5, Mgr::ServiceTimesActionData::cache_misses60, Mgr::ServiceTimesActionData::dns_lookups5, Mgr::ServiceTimesActionData::dns_lookups60, Mgr::ServiceTimesActionData::http_requests5, Mgr::ServiceTimesActionData::http_requests60, Mgr::ServiceTimesActionData::icp_queries5, Mgr::ServiceTimesActionData::icp_queries60, Mgr::ServiceTimesActionData::near_hits5, Mgr::ServiceTimesActionData::near_hits60, Mgr::ServiceTimesActionData::not_modified_replies5, Mgr::ServiceTimesActionData::not_modified_replies60, PCTILE_DNS, PCTILE_HIT, PCTILE_HTTP, PCTILE_ICP_QUERY, PCTILE_MISS, PCTILE_NH, PCTILE_NM, Mgr::ServiceTimesActionData::seriesSize, and statPctileSvc().
Referenced by Mgr::ServiceTimesAction::collect().