Squid Web Cache: squid/src/ipc/SharedListen.cc File Reference
SharedListen.cc File Reference
#include "squid.h"
#include "base/AsyncCallbacks.h"
#include "base/TextException.h"
#include "comm.h"
#include "comm/Connection.h"
#include "globals.h"
#include "ipc/Kids.h"
#include "ipc/Messages.h"
#include "ipc/Port.h"
#include "ipc/SharedListen.h"
#include "ipc/StartListening.h"
#include "ipc/TypedMsgHdr.h"
#include "tools.h"
#include <list>
#include <map>
Classes
class PendingOpenRequest
holds information necessary to handle JoinListen response
Typedefs
typedef std::map< Ipc::RequestId::Index, PendingOpenRequest > SharedListenRequestMap
maps ID assigned at request time to the response callback
typedef std::list< PendingOpenRequest > DelayedSharedListenRequests
accumulates delayed requests until they are ready to be sent, in FIFO order
Functions
static Ipc::RequestId::Index AddToMap (const PendingOpenRequest &por)
static void SendSharedListenRequest (const PendingOpenRequest &por)
static void kickDelayedRequest ()
Variables
static SharedListenRequestMap TheSharedListenRequestMap
static DelayedSharedListenRequests TheDelayedRequests
Typedef Documentation
DelayedSharedListenRequests
typedef std::list<PendingOpenRequest> DelayedSharedListenRequests
Definition at line 41 of file SharedListen.cc.
SharedListenRequestMap
typedef std::map<Ipc::RequestId::Index, PendingOpenRequest> SharedListenRequestMap
Definition at line 37 of file SharedListen.cc.
Function Documentation
AddToMap()
static Ipc::RequestId::Index AddToMap (const PendingOpenRequest & por) static
registers the given request in the collection of pending requests
Returns
the registration key
Definition at line 48 of file SharedListen.cc.
References assert, and TheSharedListenRequestMap.
Referenced by SendSharedListenRequest().
kickDelayedRequest()
static void kickDelayedRequest () static
Definition at line 130 of file SharedListen.cc.
References debugs, SendSharedListenRequest(), TheDelayedRequests, and TheSharedListenRequestMap.
Referenced by Ipc::SharedListenJoined().
SendSharedListenRequest()
static void SendSharedListenRequest (const PendingOpenRequest & por) static
Definition at line 117 of file SharedListen.cc.
References Ipc::OpenListenerParams::addr, AddToMap(), Ipc::Port::CoordinatorAddr(), debugs, Ipc::SharedListenRequest::mapId, Ipc::SharedListenRequest::pack(), PendingOpenRequest::params, Ipc::SharedListenRequest::params, and Ipc::SendMessage().
Referenced by Ipc::JoinSharedListen(), and kickDelayedRequest().
Variable Documentation
TheDelayedRequests
DelayedSharedListenRequests TheDelayedRequests static
Definition at line 42 of file SharedListen.cc.
Referenced by Ipc::JoinSharedListen(), kickDelayedRequest(), and Ipc::SharedListenJoined().
TheSharedListenRequestMap
SharedListenRequestMap TheSharedListenRequestMap static
Definition at line 38 of file SharedListen.cc.
Referenced by AddToMap(), Ipc::JoinSharedListen(), kickDelayedRequest(), and Ipc::SharedListenJoined().