Squid Web Cache: squid/src/snmp_core.h File Reference
snmp_core.h File Reference
#include "acl/Data.h"
#include "acl/ParameterizedNode.h"
#include "cache_snmp.h"
#include "comm/forward.h"
#include "ip/forward.h"
#include "snmp_vars.h"
Classes
struct _mib_tree_entry
class Acl::SnmpCommunityCheck
an "snmp_community" ACL
Namespaces
namespace Acl
Macros
#define SNMP_REQUEST_SIZE 4096
#define MAX_PROTOSTAT 5
Typedefs
typedef variable_list *() oid_ParseFn(variable_list *, snint *)
typedef struct _mib_tree_entry mib_tree_entry
typedef oid *() instance_Fn(oid *name, snint *len, mib_tree_entry *current, oid_ParseFn **Fn)
Enumerations
enum AggrType {
atNone = 0 , atSum , atAverage , atMax ,
atMin
}
Functions
struct snmp_pdu * snmpAgentResponse (struct snmp_pdu *PDU)
AggrType snmpAggrType (oid *Current, snint CurrentLen)
const char * snmpDebugOid (oid *Name, snint Len, MemBuf &outbuf)
void addr2oid (Ip::Address &addr, oid *Dest)
void oid2addr (oid *Dest, Ip::Address &addr, u_int code)
Variables
Comm::ConnectionPointer snmpOutgoingConn
PF snmpHandleUdp
Macro Definition Documentation
MAX_PROTOSTAT
#define MAX_PROTOSTAT 5
Definition at line 24 of file snmp_core.h.
SNMP_REQUEST_SIZE
#define SNMP_REQUEST_SIZE 4096
Definition at line 23 of file snmp_core.h.
Typedef Documentation
instance_Fn
typedef oid *() instance_Fn(oid *name, snint *len, mib_tree_entry *current, oid_ParseFn **Fn)
Definition at line 28 of file snmp_core.h.
mib_tree_entry
typedef struct _mib_tree_entry mib_tree_entry
Definition at line 27 of file snmp_core.h.
oid_ParseFn
typedef variable_list *() oid_ParseFn(variable_list *, snint *)
Definition at line 26 of file snmp_core.h.
Enumeration Type Documentation
AggrType
enum AggrType
Enumerator
atNone
atSum
atAverage
atMax
atMin
Definition at line 29 of file snmp_core.h.
Function Documentation
addr2oid()
void addr2oid (Ip::Address & addr, oid * Dest)
Definition at line 1077 of file snmp_core.cc.
References debugs, Ip::Address::getInAddr(), INETADDRESSTYPE_IPV4, INETADDRESSTYPE_IPV6, Ip::Address::isIPv6(), size, and snmpDebugOid().
Referenced by client_Inst().
oid2addr()
void oid2addr (oid * Dest, Ip::Address & addr, u_int code)
Definition at line 1109 of file snmp_core.cc.
References debugs, size, and snmpDebugOid().
Referenced by client_Inst(), and snmp_meshCtblFn().
snmpAgentResponse()
struct snmp_pdu * snmpAgentResponse (struct snmp_pdu * PDU)
Definition at line 471 of file snmp_core.cc.
References snmp_pdu::command, debugs, snmp_pdu::errindex, snmp_pdu::errstat, variable_list::name, variable_list::name_length, variable_list::next_variable, snmp_pdu::reqid, SNMP_ERR_NOERROR, SNMP_ERR_NOSUCHNAME, snmp_pdu_create(), SNMP_PDU_GET, SNMP_PDU_GETNEXT, SNMP_PDU_RESPONSE, snmp_var_free(), snmp_var_new(), snmpTreeGet(), snmpTreeNext(), snmp_pdu::variables, and xfree.
Referenced by Snmp::SendResponse(), and snmpConstructReponse().
snmpAggrType()
AggrType snmpAggrType (oid * Current, snint CurrentLen)
Definition at line 584 of file snmp_core.cc.
References _mib_tree_entry::aggrType, atNone, debugs, mib_tree_head, MYNAME, _mib_tree_entry::name, and snmpTreeEntry().
Referenced by Snmp::Pdu::aggregate(), and Snmp::Pdu::fixAggregate().
snmpDebugOid()
const char * snmpDebugOid (oid * Name, snint Len, MemBuf & outbuf)
Definition at line 1051 of file snmp_core.cc.
References MemBuf::append(), MemBuf::content(), and MemBuf::reset().
Referenced by addr2oid(), oid2addr(), snmp_meshCtblFn(), snmp_netDnsFn(), snmp_netFqdnFn(), snmp_netIpFn(), snmp_sysFn(), snmpAddNode(), snmpTreeGet(), and snmpTreeNext().
Variable Documentation
snmpHandleUdp
PF snmpHandleUdp extern
Referenced by snmpHandleUdp(), and snmpPortOpened().
snmpOutgoingConn
Comm::ConnectionPointer snmpOutgoingConn extern
Definition at line 40 of file snmp_core.cc.
Referenced by snmpClosePorts(), snmpOpenPorts(), and snmpPortOpened().