Squid Web Cache: squid/lib/snmplib/snmplib_debug.c File Reference
snmplib_debug.c File Reference
#include "squid.h"
#include <stdarg.h>
#include "snmp_debug.h"
Functions
void snmplib_debug (int lvl, const char *fmt,...)
Variables
void(* snmplib_debug_hook)(int, char *,...) = NULL
Function Documentation
snmplib_debug()
void snmplib_debug (int lvl, const char * fmt, ...) extern
Definition at line 21 of file snmplib_debug.c.
References BUFSIZ, NULL, and snmplib_debug_hook.
Referenced by build_tree(), parse_subtree(), print_error(), print_objid(), read_mib(), read_objid(), snmp_build(), snmp_coexist_V2toV1(), snmp_fix_pdu(), snmp_msg_Decode(), snmp_msg_Encode(), snmp_pdu_clone(), snmp_pdu_create(), snmp_pdu_decode(), snmp_pdu_encode(), snmp_var_DecodeVarBind(), and snmp_var_EncodeVarBind().
Variable Documentation
snmplib_debug_hook
void(* snmplib_debug_hook) (int, char *,...) (int , char * , ...) = NULL
Definition at line 18 of file snmplib_debug.c.
Referenced by snmplib_debug().