Squid Web Cache: squid/include/snmp_api.h File Reference
snmp_api.h File Reference
Macros
#define SNMP_DEFAULT_COMMUNITY_LEN 0 /* to get a default community name */
#define SNMP_DEFAULT_RETRIES 3
#define SNMP_DEFAULT_TIMEOUT 1
#define SNMP_DEFAULT_REMPORT 0
#define SNMP_DEFAULT_PEERNAME NULL
#define SNMP_DEFAULT_ENTERPRISE_LENGTH 0
#define SNMP_DEFAULT_TIME 0
#define SNMP_DEFAULT_MAXREPETITIONS 5
#define SNMP_DEFAULT_MACREPEATERS 0
Functions
u_char * snmp_parse (struct snmp_session *, struct snmp_pdu *, u_char *, int)
int snmp_build (struct snmp_session *, struct snmp_pdu *, u_char *, int *)
Macro Definition Documentation
SNMP_DEFAULT_COMMUNITY_LEN
#define SNMP_DEFAULT_COMMUNITY_LEN 0 /* to get a default community name */
Definition at line 41 of file snmp_api.h.
SNMP_DEFAULT_ENTERPRISE_LENGTH
#define SNMP_DEFAULT_ENTERPRISE_LENGTH 0
Definition at line 46 of file snmp_api.h.
SNMP_DEFAULT_MACREPEATERS
#define SNMP_DEFAULT_MACREPEATERS 0
Definition at line 49 of file snmp_api.h.
SNMP_DEFAULT_MAXREPETITIONS
#define SNMP_DEFAULT_MAXREPETITIONS 5
Definition at line 48 of file snmp_api.h.
SNMP_DEFAULT_PEERNAME
#define SNMP_DEFAULT_PEERNAME NULL
Definition at line 45 of file snmp_api.h.
SNMP_DEFAULT_REMPORT
#define SNMP_DEFAULT_REMPORT 0
Definition at line 44 of file snmp_api.h.
SNMP_DEFAULT_RETRIES
#define SNMP_DEFAULT_RETRIES 3
Definition at line 42 of file snmp_api.h.
SNMP_DEFAULT_TIME
#define SNMP_DEFAULT_TIME 0
Definition at line 47 of file snmp_api.h.
SNMP_DEFAULT_TIMEOUT
#define SNMP_DEFAULT_TIMEOUT 1
Definition at line 43 of file snmp_api.h.
Function Documentation
snmp_build()
int snmp_build (struct snmp_session * session, struct snmp_pdu * pdu, u_char * packet, int * out_length)
Definition at line 106 of file snmp_api.c.
References snmp_session::community, snmp_session::community_len, NULL, snmp_pdu::reqid, snmp_msg_Encode(), snmplib_debug(), and snmp_session::Version.
Referenced by Snmp::Forwarder::sendError(), Snmp::Inquirer::sendResponse(), and snmpConstructReponse().
snmp_parse()
u_char * snmp_parse (struct snmp_session * session, struct snmp_pdu * pdu, u_char * data, int length)
Definition at line 129 of file snmp_api.c.
References snmp_session::community, snmp_session::community_len, NULL, snmp_msg_Decode(), snmp_session::Version, and xmalloc.
Referenced by snmpDecodePacket().