Squid Web Cache: squid/include/snmp_api_error.h File Reference
snmp_api_error.h File Reference
Macros
#define SNMPERR_GENERR -1
#define SNMPERR_BAD_LOCPORT -2 /* local port was already in use */
#define SNMPERR_BAD_ADDRESS -3
#define SNMPERR_BAD_SESSION -4
#define SNMPERR_TOO_LONG -5 /* data too long for provided buffer */
#define SNMPERR_ASN_ENCODE -6
#define SNMPERR_ASN_DECODE -7
#define SNMPERR_PDU_TRANSLATION -8
#define SNMPERR_OS_ERR -9
#define SNMPERR_INVALID_TXTOID -10
#define SNMPERR_UNABLE_TO_FIX -11
#define SNMPERR_UNSUPPORTED_TYPE -12
#define SNMPERR_PDU_PARSE -13
#define SNMPERR_PACKET_ERR -14
#define SNMPERR_NO_RESPONSE -15
#define SNMPERR_LAST -16 /* Last error message */
Functions
const char * snmp_api_error (int)
int snmp_api_errno (void)
const char * api_errstring (int)
void snmp_set_api_error (int)
Macro Definition Documentation
SNMPERR_ASN_DECODE
#define SNMPERR_ASN_DECODE -7
Definition at line 46 of file snmp_api_error.h.
SNMPERR_ASN_ENCODE
#define SNMPERR_ASN_ENCODE -6
Definition at line 45 of file snmp_api_error.h.
SNMPERR_BAD_ADDRESS
#define SNMPERR_BAD_ADDRESS -3
Definition at line 41 of file snmp_api_error.h.
SNMPERR_BAD_LOCPORT
#define SNMPERR_BAD_LOCPORT -2 /* local port was already in use */
Definition at line 40 of file snmp_api_error.h.
SNMPERR_BAD_SESSION
#define SNMPERR_BAD_SESSION -4
Definition at line 42 of file snmp_api_error.h.
SNMPERR_GENERR
#define SNMPERR_GENERR -1
Definition at line 39 of file snmp_api_error.h.
SNMPERR_INVALID_TXTOID
#define SNMPERR_INVALID_TXTOID -10
Definition at line 49 of file snmp_api_error.h.
SNMPERR_LAST
#define SNMPERR_LAST -16 /* Last error message */
Definition at line 57 of file snmp_api_error.h.
SNMPERR_NO_RESPONSE
#define SNMPERR_NO_RESPONSE -15
Definition at line 55 of file snmp_api_error.h.
SNMPERR_OS_ERR
#define SNMPERR_OS_ERR -9
Definition at line 48 of file snmp_api_error.h.
SNMPERR_PACKET_ERR
#define SNMPERR_PACKET_ERR -14
Definition at line 54 of file snmp_api_error.h.
SNMPERR_PDU_PARSE
#define SNMPERR_PDU_PARSE -13
Definition at line 53 of file snmp_api_error.h.
SNMPERR_PDU_TRANSLATION
#define SNMPERR_PDU_TRANSLATION -8
Definition at line 47 of file snmp_api_error.h.
SNMPERR_TOO_LONG
#define SNMPERR_TOO_LONG -5 /* data too long for provided buffer */
Definition at line 43 of file snmp_api_error.h.
SNMPERR_UNABLE_TO_FIX
#define SNMPERR_UNABLE_TO_FIX -11
Definition at line 51 of file snmp_api_error.h.
SNMPERR_UNSUPPORTED_TYPE
#define SNMPERR_UNSUPPORTED_TYPE -12
Definition at line 52 of file snmp_api_error.h.
Function Documentation
api_errstring()
const char * api_errstring (int snmp_errnumber)
Definition at line 93 of file snmp_api_error.c.
References snmp_api_error().
snmp_api_errno()
int snmp_api_errno (void)
Definition at line 87 of file snmp_api_error.c.
References snmp_errno.
snmp_api_error()
const char * snmp_api_error (int err)
Definition at line 76 of file snmp_api_error.c.
References api_errors, SNMPERR_GENERR, and SNMPERR_LAST.
Referenced by api_errstring().
snmp_set_api_error()
void snmp_set_api_error (int x)
Definition at line 70 of file snmp_api_error.c.
References snmp_errno.
Referenced by asn_build_header_with_truth(), asn_build_int(), asn_build_length(), asn_build_objid(), asn_build_string(), asn_build_unsigned_int(), asn_parse_header(), asn_parse_int(), asn_parse_length(), asn_parse_objid(), asn_parse_string(), asn_parse_unsigned_int(), snmp_coexist_V2toV1(), snmp_fix_pdu(), snmp_pdu_clone(), snmp_pdu_create(), snmp_pdu_decode(), snmp_var_clone(), snmp_var_DecodeVarBind(), snmp_var_EncodeVarBind(), and snmp_var_new().