Squid Web Cache: squid/lib/snmplib/snmp_api_error.c File Reference
snmp_api_error.c File Reference
#include "squid.h"
#include "snmp_api_error.h"
Functions
void snmp_set_api_error (int x)
const char * snmp_api_error (int err)
int snmp_api_errno (void)
const char * api_errstring (int snmp_errnumber)
Variables
int snmp_errno = 0
static const char * api_errors [17]
Function Documentation
api_errstring()
const char * api_errstring (int snmp_errnumber)
Definition at line 93 of file snmp_api_error.c.
References snmp_api_error().
snmp_api_errno()
int snmp_api_errno (void)
Definition at line 87 of file snmp_api_error.c.
References snmp_errno.
snmp_api_error()
const char * snmp_api_error (int err)
Definition at line 76 of file snmp_api_error.c.
References api_errors, SNMPERR_GENERR, and SNMPERR_LAST.
Referenced by api_errstring().
snmp_set_api_error()
void snmp_set_api_error (int x)
Definition at line 70 of file snmp_api_error.c.
References snmp_errno.
Referenced by asn_build_header_with_truth(), asn_build_int(), asn_build_length(), asn_build_objid(), asn_build_string(), asn_build_unsigned_int(), asn_parse_header(), asn_parse_int(), asn_parse_length(), asn_parse_objid(), asn_parse_string(), asn_parse_unsigned_int(), snmp_coexist_V2toV1(), snmp_fix_pdu(), snmp_pdu_clone(), snmp_pdu_create(), snmp_pdu_decode(), snmp_var_clone(), snmp_var_DecodeVarBind(), snmp_var_EncodeVarBind(), and snmp_var_new().
Variable Documentation
api_errors
const char* api_errors[17] static
Initial value:
= {
    "Unknown Error",
    "Generic Error",
    "Invalid local port",
    "Unknown host",
    "Unknown session",
    "Too Long",
    "Encoding ASN.1 Information",
    "Decoding ASN.1 Information",
    "PDU Translation error",
    "OS Error",
    "Invalid Textual OID",
    "Unable to fix PDU",
    "Unsupported SNMP Type",
    "Unable to parse PDU",
    "Packet Error",
    "No Response From Host",
    "Unknown Error"
}
Definition at line 46 of file snmp_api_error.c.
Referenced by snmp_api_error().
snmp_errno
int snmp_errno = 0
Definition at line 44 of file snmp_api_error.c.
Referenced by snmp_api_errno(), and snmp_set_api_error().