Squid Web Cache: squid/lib/snmplib/snmp_vars.c File Reference
snmp_vars.c File Reference
#include "squid.h"
#include "asn1.h"
#include "snmp.h"
#include "snmp_api_error.h"
#include "snmp_msg.h"
#include "snmp_pdu.h"
#include "snmp_vars.h"
#include "util.h"
Macros
#define PARSE_ERROR { snmp_var_free(Var); return(NULL); }
Functions
struct variable_list * snmp_var_new (oid *Name, int Len)
struct variable_list * snmp_var_new_integer (oid *Name, int Len, int ival, unsigned char type)
struct variable_list * snmp_var_clone (struct variable_list *Src)
void snmp_var_free (struct variable_list *Ptr)
u_char * snmp_var_EncodeVarBind (u_char *Buffer, int *BufLenP, variable_list *VarList, int Version)
u_char * snmp_var_DecodeVarBind (u_char *Buffer, int *BufLen, struct variable_list **VarP, int Version)
Macro Definition Documentation
PARSE_ERROR
#define PARSE_ERROR { snmp_var_free(Var); return(NULL); }
Function Documentation
snmp_var_clone()
struct variable_list * snmp_var_clone (struct variable_list * Src)
Definition at line 166 of file snmp_vars.c.
References variable_list::name, variable_list::name_length, NULL, snmp_set_api_error(), SNMPERR_OS_ERR, variable_list::string, variable_list::val, variable_list::val_len, xfree, and xmalloc.
Referenced by snmp_fix_pdu().
snmp_var_DecodeVarBind()
u_char * snmp_var_DecodeVarBind (u_char * Buffer, int * BufLen, struct variable_list ** VarP, int Version)
Definition at line 368 of file snmp_vars.c.
References ASN_CONSTRUCTOR, ASN_INTEGER, ASN_NULL, ASN_OBJECT_ID, ASN_OCTET_STR, asn_parse_header(), asn_parse_int(), asn_parse_objid(), asn_parse_string(), asn_parse_unsigned_int(), ASN_PRIMITIVE, ASN_SEQUENCE, ASN_UNIVERSAL, int, variable_list::integer, MAX_NAME_LEN, variable_list::name, variable_list::name_length, variable_list::next_variable, NULL, variable_list::objid, PARSE_ERROR, SMI_COUNTER32, SMI_COUNTER64, SMI_ENDOFMIBVIEW, SMI_GAUGE32, SMI_IPADDRESS, SMI_NOSUCHINSTANCE, SMI_NOSUCHOBJECT, SMI_OPAQUE, SMI_TIMETICKS, snmp_set_api_error(), snmp_var_new(), SNMPERR_OS_ERR, SNMPERR_PDU_PARSE, SNMPERR_UNSUPPORTED_TYPE, snmplib_debug(), variable_list::string, variable_list::type, variable_list::val, variable_list::val_len, and xmalloc.
Referenced by snmp_msg_Decode().
snmp_var_EncodeVarBind()
u_char * snmp_var_EncodeVarBind (u_char * Buffer, int * BufLenP, variable_list * VarList, int Version)
Definition at line 259 of file snmp_vars.c.
References asn_build_exception(), asn_build_header(), asn_build_int(), asn_build_null(), asn_build_objid(), asn_build_string(), asn_build_unsigned_int(), ASN_CONSTRUCTOR, ASN_INTEGER, ASN_NULL, ASN_OBJECT_ID, ASN_OCTET_STR, ASN_PRIMITIVE, ASN_SEQUENCE, ASN_UNIVERSAL, variable_list::integer, variable_list::name, variable_list::name_length, variable_list::next_variable, NULL, variable_list::objid, SMI_COUNTER32, SMI_COUNTER64, SMI_ENDOFMIBVIEW, SMI_GAUGE32, SMI_IPADDRESS, SMI_NOSUCHINSTANCE, SMI_NOSUCHOBJECT, SMI_OPAQUE, SMI_TIMETICKS, snmp_set_api_error(), SNMP_VERSION_1, SNMPERR_UNSUPPORTED_TYPE, snmplib_debug(), variable_list::string, variable_list::type, variable_list::val, and variable_list::val_len.
Referenced by snmp_msg_Encode().
snmp_var_free()
void snmp_var_free (struct variable_list * Ptr)
Definition at line 227 of file snmp_vars.c.
References variable_list::integer, variable_list::name, variable_list::string, variable_list::val, and xfree.
Referenced by snmp_free_pdu(), and snmpAgentResponse().
snmp_var_new()
struct variable_list * snmp_var_new (oid * Name, int Len)
Definition at line 109 of file snmp_vars.c.
References ASN_NULL, variable_list::name, variable_list::name_length, NULL, snmp_set_api_error(), SNMPERR_OS_ERR, variable_list::type, xfree, and xmalloc.
Referenced by snmp_add_null_var(), snmp_confFn(), snmp_meshCtblFn(), snmp_meshPtblFn(), snmp_var_DecodeVarBind(), snmp_var_new_integer(), and snmpAgentResponse().
snmp_var_new_integer()
struct variable_list * snmp_var_new_integer (oid * Name, int Len, int ival, unsigned char type)
Definition at line 151 of file snmp_vars.c.
References int, variable_list::integer, snmp_var_new(), variable_list::type, variable_list::val, variable_list::val_len, and xmalloc.
Referenced by snmp_confFn(), snmp_meshCtblFn(), snmp_meshPtblFn(), snmp_netDnsFn(), snmp_netFqdnFn(), snmp_netIpFn(), snmp_prfProtoFn(), snmp_prfSysFn(), and snmp_sysFn().