Squid Web Cache: squid/include/snmp_coexist.h File Reference
snmp_coexist.h File Reference
Functions
int snmp_coexist_V2toV1 (struct snmp_pdu *)
int snmp_coexist_V1toV2 (struct snmp_pdu *)
Function Documentation
snmp_coexist_V1toV2()
int snmp_coexist_V1toV2 (struct snmp_pdu *)
snmp_coexist_V2toV1()
int snmp_coexist_V2toV1 (struct snmp_pdu * PDU)
Definition at line 108 of file coexistance.c.
References snmp_pdu::command, snmp_pdu::max_repetitions, snmp_pdu::non_repeaters, SNMP_PDU_GET, SNMP_PDU_GETBULK, SNMP_PDU_GETNEXT, snmp_set_api_error(), SNMPERR_PDU_TRANSLATION, and snmplib_debug().
Referenced by snmpDecodePacket().