Squid Web Cache: squid/lib/snmplib/snmp_api.c File Reference
snmp_api.c File Reference
#include "squid.h"
#include "asn1.h"
#include "snmp.h"
#include "snmp-internal.h"
#include "snmp_error.h"
#include "snmp_impl.h"
#include "snmp_msg.h"
#include "snmp_pdu.h"
#include "snmp_session.h"
#include "snmp_vars.h"
#include "snmp_api.h"
#include "snmp_api_error.h"
#include "snmp_api_util.h"
#include "util.h"
Functions
int snmp_build (struct snmp_session *session, struct snmp_pdu *pdu, u_char *packet, int *out_length)
u_char * snmp_parse (struct snmp_session *session, struct snmp_pdu *pdu, u_char *data, int length)
Function Documentation
snmp_build()
int snmp_build (struct snmp_session * session, struct snmp_pdu * pdu, u_char * packet, int * out_length)
Definition at line 106 of file snmp_api.c.
References snmp_session::community, snmp_session::community_len, NULL, snmp_pdu::reqid, snmp_msg_Encode(), snmplib_debug(), and snmp_session::Version.
Referenced by Snmp::Forwarder::sendError(), Snmp::Inquirer::sendResponse(), and snmpConstructReponse().
snmp_parse()
u_char * snmp_parse (struct snmp_session * session, struct snmp_pdu * pdu, u_char * data, int length)
Definition at line 129 of file snmp_api.c.
References snmp_session::community, snmp_session::community_len, NULL, snmp_msg_Decode(), snmp_session::Version, and xmalloc.
Referenced by snmpDecodePacket().