Squid Web Cache: squid/compat/socket.h File Reference
socket.h File Reference
Macros
#define MSG_NOSIGNAL 0
Functions
int xaccept (int socketFd, struct sockaddr *sa, socklen_t *saLength)
POSIX accept(2) equivalent.
int xbind (int socketFd, const struct sockaddr *sa, socklen_t saLength)
POSIX bind(2) equivalent.
int xconnect (int socketFd, const struct sockaddr *sa, socklen_t saLength)
POSIX connect(2) equivalent.
int xgetsockopt (int socketFd, int level, int optionName, void *optionValue, socklen_t *optionLength)
POSIX getsockopt(2) equivalent.
int xgetsockname (int socketFd, struct sockaddr *sa, socklen_t *saLength)
POSIX getsockname(2) equivalent.
int xlisten (int socketFd, int backlog)
POSIX listen(2) equivalent.
ssize_t xrecv (int socketFd, void *buf, size_t bufLength, int flags)
POSIX recv(2) equivalent.
ssize_t xrecvfrom (int socketFd, void *buf, size_t bufLength, int flags, struct sockaddr *from, socklen_t *fromLength)
POSIX recvfrom(2) equivalent.
ssize_t xsend (int socketFd, const void *buf, size_t bufLength, int flags)
POSIX send(2) equivalent.
ssize_t xsendto (int socketFd, const void *buf, size_t bufLength, int flags, const struct sockaddr *to, socklen_t toLength)
POSIX sendto(2) equivalent.
int xsetsockopt (int socketFd, int level, int option, const void *value, socklen_t valueLength)
POSIX setsockopt(2) equivalent.
int xsocket (int domain, int type, int protocol)
POSIX socket(2) equivalent.
Macro Definition Documentation
MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
Definition at line 56 of file socket.h.
Function Documentation
xaccept()
int xaccept (int socketFd, struct sockaddr * sa, socklen_t * saLength) inline
Definition at line 62 of file socket.h.
Referenced by Comm::TcpAcceptor::acceptInto(), ipc_thread_1(), and ipcCreate().
xbind()
int xbind (int socketFd, const struct sockaddr * sa, socklen_t saLength) inline
Definition at line 68 of file socket.h.
Referenced by commBind(), and Ip::Intercept::ProbeForTproxy().
xconnect()
int xconnect (int socketFd, const struct sockaddr * sa, socklen_t saLength) inline
Definition at line 74 of file socket.h.
Referenced by comm_connect_addr(), main(), IcmpPinger::Open(), wccp2ConnectionOpen(), and wccpConnectionOpen().
xgetsockname()
int xgetsockname (int socketFd, struct sockaddr * sa, socklen_t * saLength) inline
Definition at line 80 of file socket.h.
Referenced by Comm::TcpAcceptor::acceptInto(), comm_local_port(), Ipc::ImportFdIntoComm(), ipc_thread_1(), ipcCreate(), Comm::ConnOpener::lookupLocalAddress(), main(), wccp2ConnectionOpen(), and wccpConnectionOpen().
xgetsockopt()
int xgetsockopt (int socketFd, int level, int optionName, void * optionValue, socklen_t * optionLength) inline
Definition at line 92 of file socket.h.
Referenced by comm_connect_addr(), Ip::Qos::getTosFromServer(), and Ip::Intercept::NetfilterInterception().
xlisten()
int xlisten (int socketFd, int backlog) inline
Definition at line 86 of file socket.h.
Referenced by ipcCreate(), and Comm::TcpAcceptor::setListen().
xrecv()
ssize_t xrecv (int socketFd, void * buf, size_t bufLength, int flags) inline
Definition at line 98 of file socket.h.
Referenced by ipc_thread_1(), ipc_thread_2(), ipcCreate(), IcmpPinger::Open(), and IcmpPinger::Recv().
xrecvfrom()
ssize_t xrecvfrom (int socketFd, void * buf, size_t bufLength, int flags, struct sockaddr * from, socklen_t * fromLength) inline
Definition at line 104 of file socket.h.
Referenced by authenticate(), comm_udp_recvfrom(), Icmp4::Recv(), and Icmp6::Recv().
xsend()
ssize_t xsend (int socketFd, const void * buf, size_t bufLength, int flags) inline
Definition at line 110 of file socket.h.
Referenced by authenticate(), IcmpSquid::Close(), comm_udp_send(), ipc_thread_1(), ipc_thread_2(), ipcCreate(), ipcSend(), main(), IcmpPinger::Open(), IcmpPinger::SendResult(), wccp2AssignBuckets(), and wccp2HereIam().
xsendto()
ssize_t xsendto (int socketFd, const void * buf, size_t bufLength, int flags, const struct sockaddr * to, socklen_t toLength) inline
Definition at line 116 of file socket.h.
Referenced by comm_udp_sendto(), Icmp4::SendEcho(), and Icmp6::SendEcho().
xsetsockopt()
int xsetsockopt (int socketFd, int level, int option, const void * value, socklen_t valueLength) inline
Definition at line 122 of file socket.h.
Referenced by comm_apply_flags(), comm_set_transparent(), comm_set_v6only(), commConfigureLinger(), commSetBindAddressNoPort(), commSetReuseAddr(), commSetTcpRcvbuf(), ftpOpenListenSocket(), Ip::Qos::getTosFromServer(), ipcCreate(), mcastJoinGroups(), mcastSetTtl(), Ip::Intercept::ProbeForTproxy(), Comm::TcpAcceptor::setListen(), SetSocketOption(), Ip::Qos::setSockNfmark(), Ip::Qos::setSockTos(), ConnStateData::start(), and wccp2ConnectionOpen().
xsocket()
int xsocket (int domain, int type, int protocol) inline
Definition at line 128 of file socket.h.
Referenced by comm_open_uds(), comm_openex(), Eui::Eui48::lookup(), main(), Icmp4::Open(), Icmp6::Open(), and Ip::Intercept::ProbeForTproxy().