Squid Web Cache: squid/test-suite/splay.cc File Reference
splay.cc File Reference
#include "squid.h"
#include "splay.h"
#include "util.h"
#include <cstdlib>
#include <functional>
#include <random>
Classes
class intnode
class SplayCheck
Functions
static int compareintvoid (void *const &a, void *const &n)
static int compareint (intnode *const &a, intnode *const &b)
static void destintvoid (void *&data)
static void destint (intnode *&data)
static int compareintref (intnode const &a, intnode const &b)
static void destintref (intnode &)
int main (int, char *[])
Function Documentation
compareint()
static int compareint (intnode *const & a, intnode *const & b) static
Definition at line 45 of file splay.cc.
References intnode::i.
Referenced by main().
compareintref()
static int compareintref (intnode const & a, intnode const & b) static
Definition at line 121 of file splay.cc.
References intnode::i.
Referenced by main().
compareintvoid()
static int compareintvoid (void *const & a, void *const & n) static
Definition at line 37 of file splay.cc.
References intnode::i.
Referenced by main().
destint()
static void destint (intnode *& data) static
Definition at line 115 of file splay.cc.
Referenced by main().
destintref()
static void destintref (intnode &) static
Definition at line 127 of file splay.cc.
Referenced by main().
destintvoid()
static void destintvoid (void *& data) static
Definition at line 108 of file splay.cc.
References xfree.
Referenced by main().
main()
int main (int , char * [])
Definition at line 131 of file splay.cc.
References SplayCheck::BeginWalk(), compareint(), compareintref(), compareintvoid(), destint(), destintref(), destintvoid(), Splay< V >::destroy(), SplayCheck::ExpectedFail, Splay< V >::finish(), intnode::i, Splay< V >::insert(), Splay< V >::size(), Splay< V >::start(), SplayCheck::VisitNode(), SplayCheck::VisitNodeRef(), SplayCheck::VisitVoid(), and xcalloc().