Squid Web Cache: squid/src/SquidIpc.h File Reference
SquidIpc.h File Reference
Namespaces
namespace Ip
Functions
pid_t ipcCreate (int type, const char *prog, const char *const args[], const char *name, Ip::Address &local_addr, int *rfd, int *wfd, void **hIpc)
Function Documentation
ipcCreate()
pid_t ipcCreate (int type, const char * prog, const char *const args[], const char * name, Ip::Address & local_addr, int * rfd, int * wfd, void ** hIpc)
Definition at line 63 of file ipc.cc.
References ipc_params::args, assert, comm_close, comm_connect_addr(), Comm::COMM_ERROR, COMM_NOCLOEXEC, comm_open(), comm_open_listener(), comm_udp_recv(), comm_udp_send(), commSetCloseOnExec(), commSetNonBlocking(), commUnsetFdTimeout(), Config, ipc_params::crfd, ipc_params::cwfd, DBG_CRITICAL, DBG_IMPORTANT, debugs, DebugStream(), err_string, Debug::Extra(), fd_open(), FD_PIPE, fd_table, Ip::Address::FreeAddr(), hello_buf, hello_buf, HELLO_BUF_SZ, hello_string, hello_string, hIpc, Ip::Address::InitAddr(), IPC_CHECK_FAIL, IPC_FIFO, IPC_NONE, IPC_TCP_SOCKET, ipc_thread_1(), IPC_UDP_SOCKET, IPC_UNIX_DGRAM, IPC_UNIX_STREAM, ipcCloseAllFD(), ipcCloseAllFD(), ipc_params::local_addr, logsFlush(), no_suid(), ok_string, opt_no_daemon, pid, pkHelper, ipc_params::prog, ipc_params::PS, PutEnvironment(), requirePathnameExists(), ResyncDebugLog(), rfc1738_escape, Ip::Address::setEmpty(), SquidConfig::sleep_after_fork, SQUID_MAXFD, TheProcessKind, ipc_params::type, xaccept(), xclose(), xgetsockname(), xlisten(), xread(), xrecv(), xsend(), xsetsockopt(), xstrerr(), and xwrite().
Referenced by DiskdIOStrategy::init(), logfile_mod_daemon_open(), IcmpSquid::Open(), Helper::Client::openSessions(), statefulhelper::openSessions(), and unlinkdInit().