Squid Web Cache: squid/src/SquidString.h File Reference
SquidString.h File Reference
#include "base/TextException.h"
#include "debug/Stream.h"
#include "sbuf/forward.h"
#include <ostream>
Classes
class String
Macros
#define SQUIDSTRINGPH "%.*s"
#define SQUIDSTRINGPRINT(s) (s).psize(),(s).rawBuf()
Functions
std::ostream & operator<< (std::ostream &os, String const &aString)
bool operator< (const String &a, const String &b)
const char * checkNullString (const char *p)
int stringHasWhitespace (const char *)
int stringHasCntl (const char *)
char * strwordtok (char *buf, char **t)
Macro Definition Documentation
SQUIDSTRINGPH
#define SQUIDSTRINGPH "%.*s"
Definition at line 22 of file SquidString.h.
SQUIDSTRINGPRINT
#define SQUIDSTRINGPRINT (s) (s).psize(),(s).rawBuf()
Definition at line 23 of file SquidString.h.
Function Documentation
checkNullString()
const char * checkNullString (const char * p)
Definition at line 406 of file String.cc.
operator<()
bool operator< (const String & a, const String & b) inline
Definition at line 180 of file SquidString.h.
References String::cmp().
operator<<()
std::ostream & operator<< (std::ostream & os, String const & aString) inline
Definition at line 174 of file SquidString.h.
References String::rawBuf(), and String::size().
stringHasCntl()
int stringHasCntl (const char * s)
Definition at line 301 of file String.cc.
Referenced by urlCanonicalCleanWithoutRequest().
stringHasWhitespace()
int stringHasWhitespace (const char * s)
Definition at line 294 of file String.cc.
References w_space.
Referenced by AnyP::Uri::parse().
strwordtok()
char * strwordtok (char * buf, char ** t)
Definition at line 321 of file String.cc.
References error(), and xisspace.
Referenced by Helper::Reply::finalize(), Ssl::Helper::Init(), Ssl::CertValidationHelper::Init(), parseManyConfigFiles(), and Helper::Reply::parseResponseKeys().