Squid Web Cache: squid/src/ssl/helper.cc File Reference
helper.cc File Reference
#include "squid.h"
#include "../helper.h"
#include "anyp/PortCfg.h"
#include "base/AsyncCallbacks.h"
#include "cache_cf.h"
#include "fs_io.h"
#include "helper/Reply.h"
#include "Parsing.h"
#include "sbuf/Stream.h"
#include "SquidConfig.h"
#include "ssl/cert_validate_message.h"
#include "ssl/Config.h"
#include "ssl/helper.h"
#include "wordlist.h"
#include <limits>
Classes
class Ssl::GeneratorRequestor
Initiator of an Ssl::Helper query.
class Ssl::GeneratorRequest
A pending Ssl::Helper request, combining the original and collapsed queries.
class submitData
Namespaces
namespace Ssl
Typedefs
typedef std::unordered_map< SBuf, GeneratorRequest * > Ssl::GeneratorRequests
Ssl::Helper query:GeneratorRequest map.
Functions
static void Ssl::HandleGeneratorReply (void *data, const ::Helper::Reply &reply)
receives helper response
static GeneratorRequests & Ssl::TheGeneratorRequests ()
pending Ssl::Helper requests (to all certificate generator helpers combined)
static std::ostream & operator<< (std::ostream &os, const Ssl::GeneratorRequest &gr)
prints Ssl::GeneratorRequest for debugging
static void sslCrtvdHandleReplyWrapper (void *data, const ::Helper::Reply &reply)
Function Documentation
operator<<()
static std::ostream & operator<< (std::ostream & os, const Ssl::GeneratorRequest & gr) static
Definition at line 73 of file helper.cc.
References SBuf::id, Ssl::GeneratorRequest::query, Ssl::GeneratorRequest::requestors, and InstanceId< Class, ValueType >::value.
sslCrtvdHandleReplyWrapper()
static void sslCrtvdHandleReplyWrapper (void * data, const ::Helper::Reply & reply) static
Definition at line 270 of file helper.cc.
References AsyncCallback< Answer >::answer(), assert, Helper::BrokenHelper, submitData::callback, DBG_IMPORTANT, debugs, Helper::Error, Ssl::CrtdMessage::getBody(), Ssl::CertValidationHelper::HelperCache, Ssl::CrtdMessage::OK, Helper::Okay, Ssl::CrtdMessage::parse(), Ssl::CertValidationMsg::parseResponse(), submitData::query, AsyncCallback< Answer >::release(), Ssl::CrtdMessage::REPLY, ScheduleCallHere, and submitData::ssl.
Referenced by Ssl::CertValidationHelper::Submit().