Squid Web Cache: squid/lib/sspi/sspwin32.h File Reference
sspwin32.h File Reference
Macros
#define SECURITY_WIN32
#define NTLM_PACKAGE_NAME "NTLM"
#define NEGOTIATE_PACKAGE_NAME "Negotiate"
#define WINNT_SECURITY_DLL "security.dll"
#define WIN2K_SECURITY_DLL "secur32.dll"
#define SSP_BASIC 1
#define SSP_NTLM 2
#define SSP_MAX_CRED_LEN 848
#define SSP_DEBUG 0
#define SSP_OK 1
#define SSP_ERROR 2
Typedefs
typedef char * SSP_blobP
Functions
HMODULE LoadSecurityDll (int, const char *)
void UnloadSecurityDll (void)
Macro Definition Documentation
NEGOTIATE_PACKAGE_NAME
#define NEGOTIATE_PACKAGE_NAME "Negotiate"
Definition at line 19 of file sspwin32.h.
NTLM_PACKAGE_NAME
#define NTLM_PACKAGE_NAME "NTLM"
Definition at line 18 of file sspwin32.h.
SECURITY_WIN32
#define SECURITY_WIN32
Definition at line 17 of file sspwin32.h.
SSP_BASIC
#define SSP_BASIC 1
Definition at line 42 of file sspwin32.h.
SSP_DEBUG
#define SSP_DEBUG 0
Definition at line 47 of file sspwin32.h.
SSP_ERROR
#define SSP_ERROR 2
Definition at line 50 of file sspwin32.h.
SSP_MAX_CRED_LEN
#define SSP_MAX_CRED_LEN 848
Definition at line 45 of file sspwin32.h.
SSP_NTLM
#define SSP_NTLM 2
Definition at line 43 of file sspwin32.h.
SSP_OK
#define SSP_OK 1
Definition at line 49 of file sspwin32.h.
WIN2K_SECURITY_DLL
#define WIN2K_SECURITY_DLL "secur32.dll"
Definition at line 40 of file sspwin32.h.
WINNT_SECURITY_DLL
#define WINNT_SECURITY_DLL "security.dll"
Definition at line 39 of file sspwin32.h.
Typedef Documentation
SSP_blobP
typedef char* SSP_blobP
Definition at line 37 of file sspwin32.h.
Function Documentation
LoadSecurityDll()
HMODULE LoadSecurityDll (int mode, const char * SSP_Package)
Definition at line 104 of file sspwin32.cc.
References _AcceptSecurityContext, _AcquireCredentialsHandle, _CompleteAuthToken, _DeleteSecurityContext, _FreeContextBuffer, _FreeCredentialsHandle, _InitializeSecurityContext, _QueryContextAttributes, _QuerySecurityPackageInfo, cbMaxToken, hModule, NTLM_mode, pClientBuf, pServerBuf, SSP_BASIC, SSP_NTLM, SSP_Package_InUse, UnloadSecurityDll(), WIN2K_SECURITY_DLL, WINNT_SECURITY_DLL, xcalloc(), and xstrdup.
Referenced by main(), and main().
UnloadSecurityDll()
void UnloadSecurityDll (void)
Definition at line 77 of file sspwin32.cc.
References _AcceptSecurityContext, _AcquireCredentialsHandle, _CompleteAuthToken, _DeleteSecurityContext, _FreeContextBuffer, _FreeCredentialsHandle, _InitializeSecurityContext, _QueryContextAttributes, _QuerySecurityPackageInfo, _AUTH_SEQ::fHaveCredHandle, _AUTH_SEQ::fHaveCtxtHandle, _AUTH_SEQ::hcred, _AUTH_SEQ::hctxt, hModule, NTLM_asServer, pClientBuf, pServerBuf, SSP_Package_InUse, and xfree.
Referenced by LoadSecurityDll(), main(), and main().