Squid Web Cache: squid/src/stat.cc File Reference
stat.cc File Reference
#include "squid.h"
#include "AccessLogEntry.h"
#include "CacheDigest.h"
#include "CachePeer.h"
#include "CachePeers.h"
#include "client_side.h"
#include "client_side_request.h"
#include "comm/Connection.h"
#include "comm/Loops.h"
#include "event.h"
#include "fd.h"
#include "fde.h"
#include "format/Token.h"
#include "globals.h"
#include "http/Stream.h"
#include "HttpRequest.h"
#include "IoStats.h"
#include "mem/Pool.h"
#include "mem/Stats.h"
#include "mem_node.h"
#include "MemBuf.h"
#include "MemObject.h"
#include "mgr/CountersAction.h"
#include "mgr/FunAction.h"
#include "mgr/InfoAction.h"
#include "mgr/IntervalAction.h"
#include "mgr/IoAction.h"
#include "mgr/Registration.h"
#include "mgr/ServiceTimesAction.h"
#include "neighbors.h"
#include "PeerDigest.h"
#include "SquidConfig.h"
#include "SquidMath.h"
#include "stat.h"
#include "StatCounters.h"
#include "Store.h"
#include "store_digest.h"
#include "StoreClient.h"
#include "tools.h"
#include "auth/UserRequest.h"
#include "DelayId.h"
#include "ssl/support.h"
#include "comm.h"
#include "StoreSearch.h"
Classes
class StatObjectsState
Macros
#define XAVG(X) (dt ? (double) (f->X - l->X) / dt : 0.0)
Typedefs
typedef int STOBJFLT(const StoreEntry *)
Functions
static const char * describeStatuses (const StoreEntry *)
static void statAvgTick (void *notused)
static void statAvgDump (StoreEntry *, int minutes, int hours)
static double statPctileSvc (double, int, int)
static void statStoreEntry (MemBuf *mb, StoreEntry *e)
static double statCPUUsage (int minutes)
void GetAvgStat (Mgr::IntervalActionData &stats, int minutes, int hours)
void DumpAvgStat (Mgr::IntervalActionData &stats, StoreEntry *sentry)
void GetInfo (Mgr::InfoActionData &stats)
void DumpInfo (Mgr::InfoActionData &stats, StoreEntry *sentry)
void DumpMallocStatistics (StoreEntry *sentry)
void GetCountersStats (Mgr::CountersActionData &stats)
void DumpCountersStats (Mgr::CountersActionData &stats, StoreEntry *sentry)
void GetServiceTimesStats (Mgr::ServiceTimesActionData &stats)
void DumpServiceTimesStats (Mgr::ServiceTimesActionData &stats, StoreEntry *sentry)
void GetIoStats (Mgr::IoActionData &stats)
void DumpIoStats (Mgr::IoActionData &stats, StoreEntry *sentry)
static void statUtilization (StoreEntry *e)
const char * storeEntryFlags (const StoreEntry *entry)
static void statObjects (void *data)
static void statObjectsStart (StoreEntry *sentry, STOBJFLT *filter)
static void stat_objects_get (StoreEntry *sentry)
static int statObjectsVmFilter (const StoreEntry *e)
static void stat_vmobjects_get (StoreEntry *sentry)
static int statObjectsOpenfdFilter (const StoreEntry *e)
static void statOpenfdObj (StoreEntry *sentry)
static void statRegisterWithCacheManager (void)
static void statCountersInitSpecial (StatCounters *C)
static void statCountersInit (StatCounters *C)
void statInit (void)
static void statCountersHistograms (StoreEntry *sentry)
static void statCountersDump (StoreEntry *sentry)
static void statPeerSelect (StoreEntry *sentry)
static void statDigestBlob (StoreEntry *sentry)
StatCounters * snmpStatGet (int minutes)
bool statSawRecentRequests ()
double statRequestHitRatio (int minutes)
double statRequestHitMemoryRatio (int minutes)
double statRequestHitDiskRatio (int minutes)
double statByteHitRatio (int minutes)
static void statClientRequests (StoreEntry *s)
Variables
static OBJH stat_objects_get
static OBJH stat_vmobjects_get
static OBJH statOpenfdObj
static EVH statObjects
static OBJH statCountersDump
static OBJH statPeerSelect
static OBJH statDigestBlob
static OBJH statUtilization
static OBJH statCountersHistograms
static OBJH statClientRequests
StatCounters CountHist [N_COUNT_HIST]
static int NCountHist = 0
static StatCounters CountHourHist [N_COUNT_HOUR_HIST]
static int NCountHourHist = 0
unsigned int mem_pool_alloc_calls
unsigned int mem_pool_free_calls
Macro Definition Documentation
XAVG
#define XAVG (X) (dt ? (double) (f->X - l->X) / dt : 0.0)
Definition at line 863 of file stat.cc.
Typedef Documentation
STOBJFLT
typedef int STOBJFLT(const StoreEntry *)
Definition at line 67 of file stat.cc.
Function Documentation
describeStatuses()
static const char * describeStatuses (const StoreEntry * entry) static
Definition at line 242 of file stat.cc.
References LOCAL_ARRAY, StoreEntry::mem_status, memStatusStr, StoreEntry::ping_status, pingStatusStr, StoreEntry::store_status, storeStatusStr, StoreEntry::swap_status, and swapStatusStr.
Referenced by statStoreEntry().
DumpAvgStat()
void DumpAvgStat (Mgr::IntervalActionData & stats, StoreEntry * sentry)
Definition at line 1001 of file stat.cc.
References Mgr::IntervalActionData::aborted_requests, Mgr::IntervalActionData::average_select_fd_period, Mgr::IntervalActionData::client_http_all_median_svc_time, Mgr::IntervalActionData::client_http_errors, Mgr::IntervalActionData::client_http_hit_median_svc_time, Mgr::IntervalActionData::client_http_hits, Mgr::IntervalActionData::client_http_kbytes_in, Mgr::IntervalActionData::client_http_kbytes_out, Mgr::IntervalActionData::client_http_miss_median_svc_time, Mgr::IntervalActionData::client_http_nh_median_svc_time, Mgr::IntervalActionData::client_http_nm_median_svc_time, Mgr::IntervalActionData::client_http_requests, Mgr::IntervalActionData::count, Mgr::IntervalActionData::cpu_time, Mgr::IntervalActionData::dns_median_svc_time, Math::doublePercent(), Time::FormatRfc1123(), Mgr::IntervalActionData::hitValidationAttempts, Mgr::IntervalActionData::hitValidationFailures, Mgr::IntervalActionData::hitValidationRefusalsDueToLocking, Mgr::IntervalActionData::hitValidationRefusalsDueToTimeLimit, Mgr::IntervalActionData::hitValidationRefusalsDueToZeroSize, Mgr::IntervalActionData::icp_kbytes_recv, Mgr::IntervalActionData::icp_kbytes_sent, Mgr::IntervalActionData::icp_pkts_recv, Mgr::IntervalActionData::icp_pkts_sent, Mgr::IntervalActionData::icp_q_kbytes_recv, Mgr::IntervalActionData::icp_q_kbytes_sent, Mgr::IntervalActionData::icp_queries_recv, Mgr::IntervalActionData::icp_queries_sent, Mgr::IntervalActionData::icp_query_median_svc_time, Mgr::IntervalActionData::icp_query_timeouts, Mgr::IntervalActionData::icp_r_kbytes_recv, Mgr::IntervalActionData::icp_r_kbytes_sent, Mgr::IntervalActionData::icp_replies_queued, Mgr::IntervalActionData::icp_replies_recv, Mgr::IntervalActionData::icp_replies_sent, Mgr::IntervalActionData::icp_reply_median_svc_time, Mgr::IntervalActionData::median_select_fds, Mgr::IntervalActionData::page_faults, Mgr::IntervalActionData::sample_end_time, Mgr::IntervalActionData::sample_start_time, Mgr::IntervalActionData::select_fds, Mgr::IntervalActionData::select_loops, Mgr::IntervalActionData::server_all_errors, Mgr::IntervalActionData::server_all_kbytes_in, Mgr::IntervalActionData::server_all_kbytes_out, Mgr::IntervalActionData::server_all_requests, Mgr::IntervalActionData::server_ftp_errors, Mgr::IntervalActionData::server_ftp_kbytes_in, Mgr::IntervalActionData::server_ftp_kbytes_out, Mgr::IntervalActionData::server_ftp_requests, Mgr::IntervalActionData::server_http_errors, Mgr::IntervalActionData::server_http_kbytes_in, Mgr::IntervalActionData::server_http_kbytes_out, Mgr::IntervalActionData::server_http_requests, Mgr::IntervalActionData::server_other_errors, Mgr::IntervalActionData::server_other_kbytes_in, Mgr::IntervalActionData::server_other_kbytes_out, Mgr::IntervalActionData::server_other_requests, storeAppendPrintf(), Mgr::IntervalActionData::swap_files_cleaned, Mgr::IntervalActionData::swap_ins, Mgr::IntervalActionData::swap_outs, Mgr::IntervalActionData::syscalls_disk_closes, Mgr::IntervalActionData::syscalls_disk_opens, Mgr::IntervalActionData::syscalls_disk_reads, Mgr::IntervalActionData::syscalls_disk_seeks, Mgr::IntervalActionData::syscalls_disk_unlinks, Mgr::IntervalActionData::syscalls_disk_writes, Mgr::IntervalActionData::syscalls_selects, Mgr::IntervalActionData::syscalls_sock_accepts, Mgr::IntervalActionData::syscalls_sock_binds, Mgr::IntervalActionData::syscalls_sock_closes, Mgr::IntervalActionData::syscalls_sock_connects, Mgr::IntervalActionData::syscalls_sock_reads, Mgr::IntervalActionData::syscalls_sock_recvfroms, Mgr::IntervalActionData::syscalls_sock_sendtos, Mgr::IntervalActionData::syscalls_sock_sockets, Mgr::IntervalActionData::syscalls_sock_writes, Mgr::IntervalActionData::unlink_requests, and Mgr::IntervalActionData::wall_time.
Referenced by Mgr::IntervalAction::dump(), and statAvgDump().
DumpCountersStats()
void DumpCountersStats (Mgr::CountersActionData & stats, StoreEntry * sentry)
Definition at line 1440 of file stat.cc.
References Mgr::CountersActionData::aborted_requests, Mgr::CountersActionData::cd_kbytes_recv, Mgr::CountersActionData::cd_kbytes_sent, Mgr::CountersActionData::cd_local_memory, Mgr::CountersActionData::cd_memory, Mgr::CountersActionData::cd_msgs_recv, Mgr::CountersActionData::cd_msgs_sent, Mgr::CountersActionData::cd_times_used, Mgr::CountersActionData::client_http_errors, Mgr::CountersActionData::client_http_hit_kbytes_out, Mgr::CountersActionData::client_http_hits, Mgr::CountersActionData::client_http_kbytes_in, Mgr::CountersActionData::client_http_kbytes_out, Mgr::CountersActionData::client_http_requests, Mgr::CountersActionData::cpu_time, Time::FormatRfc1123(), Mgr::CountersActionData::hitValidationAttempts, Mgr::CountersActionData::hitValidationFailures, Mgr::CountersActionData::hitValidationRefusalsDueToLocking, Mgr::CountersActionData::hitValidationRefusalsDueToTimeLimit, Mgr::CountersActionData::hitValidationRefusalsDueToZeroSize, Mgr::CountersActionData::icp_kbytes_recv, Mgr::CountersActionData::icp_kbytes_sent, Mgr::CountersActionData::icp_pkts_recv, Mgr::CountersActionData::icp_pkts_sent, Mgr::CountersActionData::icp_q_kbytes_recv, Mgr::CountersActionData::icp_q_kbytes_sent, Mgr::CountersActionData::icp_queries_recv, Mgr::CountersActionData::icp_queries_sent, Mgr::CountersActionData::icp_query_timeouts, Mgr::CountersActionData::icp_r_kbytes_recv, Mgr::CountersActionData::icp_r_kbytes_sent, Mgr::CountersActionData::icp_replies_queued, Mgr::CountersActionData::icp_replies_recv, Mgr::CountersActionData::icp_replies_sent, Mgr::CountersActionData::icp_times_used, Mgr::CountersActionData::page_faults, Mgr::CountersActionData::sample_time, Mgr::CountersActionData::select_loops, Mgr::CountersActionData::server_all_errors, Mgr::CountersActionData::server_all_kbytes_in, Mgr::CountersActionData::server_all_kbytes_out, Mgr::CountersActionData::server_all_requests, Mgr::CountersActionData::server_ftp_errors, Mgr::CountersActionData::server_ftp_kbytes_in, Mgr::CountersActionData::server_ftp_kbytes_out, Mgr::CountersActionData::server_ftp_requests, Mgr::CountersActionData::server_http_errors, Mgr::CountersActionData::server_http_kbytes_in, Mgr::CountersActionData::server_http_kbytes_out, Mgr::CountersActionData::server_http_requests, Mgr::CountersActionData::server_other_errors, Mgr::CountersActionData::server_other_kbytes_in, Mgr::CountersActionData::server_other_kbytes_out, Mgr::CountersActionData::server_other_requests, storeAppendPrintf(), Mgr::CountersActionData::swap_files_cleaned, Mgr::CountersActionData::swap_ins, Mgr::CountersActionData::swap_outs, Mgr::CountersActionData::unlink_requests, and Mgr::CountersActionData::wall_time.
Referenced by Mgr::CountersAction::dump(), and statCountersDump().
DumpInfo()
void DumpInfo (Mgr::InfoActionData & stats, StoreEntry * sentry)
Definition at line 554 of file stat.cc.
References APP_SHORTNAME, StoreEntry::append(), StoreInfoStats::Part::available(), Mgr::InfoActionData::avg_client_http_requests, Mgr::InfoActionData::avg_icp_messages, Mgr::InfoActionData::avg_loop_time, Mgr::InfoActionData::biggest_fd, Mgr::InfoActionData::byte_hit_ratio5, Mgr::InfoActionData::byte_hit_ratio60, Mgr::InfoActionData::cache_hits5, Mgr::InfoActionData::cache_hits60, Mgr::InfoActionData::cache_misses5, Mgr::InfoActionData::cache_misses60, StoreInfoStats::Part::capacity, SquidConfig::client_db, Mgr::InfoActionData::client_http_clients, Mgr::InfoActionData::client_http_requests, Config, Mgr::InfoActionData::count, StoreInfoStats::Part::count, Mgr::InfoActionData::cpu_time, Mgr::InfoActionData::cpu_usage, Mgr::InfoActionData::cpu_usage5, Mgr::InfoActionData::cpu_usage60, Mgr::InfoActionData::current_time, Mgr::InfoActionData::dns_lookups5, Mgr::InfoActionData::dns_lookups60, Math::doublePercent(), Time::FormatRfc1123(), Mgr::InfoActionData::gb_freed_count, Mgr::InfoActionData::gb_saved_count, Mem::GlobalStats(), Mgr::InfoActionData::htcp_pkts_recv, Mgr::InfoActionData::htcp_pkts_sent, Mgr::InfoActionData::http_requests5, Mgr::InfoActionData::http_requests60, Mgr::InfoActionData::icp_pkts_recv, Mgr::InfoActionData::icp_pkts_sent, Mgr::InfoActionData::icp_queries5, Mgr::InfoActionData::icp_queries60, Mgr::InfoActionData::icp_replies_queued, Mgr::InfoActionData::max_fd, Mgr::InfoActionData::maxrss, StoreInfoStats::Part::meanObjectSize(), StoreInfoStats::mem, StoreInfoStats::mem_object_count, Mgr::InfoActionData::near_hits5, Mgr::InfoActionData::near_hits60, Mgr::InfoActionData::not_modified_replies5, Mgr::InfoActionData::not_modified_replies60, Mgr::InfoActionData::num_fd_free, Mgr::InfoActionData::number_fd, SquidConfig::onoff, StoreInfoStats::Swap::open_disk_fd, Mgr::InfoActionData::opening_fd, Mgr::InfoActionData::page_faults, Mgr::InfoActionData::request_failure_ratio, Mgr::InfoActionData::request_hit_disk_ratio5, Mgr::InfoActionData::request_hit_disk_ratio60, Mgr::InfoActionData::request_hit_mem_ratio5, Mgr::InfoActionData::request_hit_mem_ratio60, Mgr::InfoActionData::request_hit_ratio5, Mgr::InfoActionData::request_hit_ratio60, Mgr::InfoActionData::reserved_fd, Mgr::InfoActionData::select_loops, service_name, StoreInfoStats::Part::size, SQUID_BUILD_INFO, Mgr::InfoActionData::squid_start, SQUIDSBUFPH, SQUIDSBUFPRINT, Mgr::InfoActionData::store, StoreInfoStats::store_entry_count, storeAppendPrintf(), StoreInfoStats::swap, Mgr::InfoActionData::total_accounted, Mgr::InfoActionData::unlink_requests, Mgr::InfoActionData::up_time, and version_string.
Referenced by Mgr::InfoAction::dump().
DumpIoStats()
void DumpIoStats (Mgr::IoActionData & stats, StoreEntry * sentry)
Definition at line 209 of file stat.cc.
References Math::doublePercent(), Mgr::IoActionData::ftp_read_hist, Mgr::IoActionData::ftp_reads, IoStats::histSize, Mgr::IoActionData::http_read_hist, Mgr::IoActionData::http_reads, and storeAppendPrintf().
Referenced by Mgr::IoAction::dump().
DumpMallocStatistics()
void DumpMallocStatistics (StoreEntry * sentry)
Definition at line 764 of file stat.cc.
References current_dtime, storeAppendPrintf(), xm_deltat, and xm_time.
Referenced by Mgr::InfoAction::dump().
DumpServiceTimesStats()
void DumpServiceTimesStats (Mgr::ServiceTimesActionData & stats, StoreEntry * sentry)
Definition at line 806 of file stat.cc.
References Mgr::ServiceTimesActionData::cache_hits5, Mgr::ServiceTimesActionData::cache_hits60, Mgr::ServiceTimesActionData::cache_misses5, Mgr::ServiceTimesActionData::cache_misses60, Mgr::ServiceTimesActionData::count, Mgr::ServiceTimesActionData::dns_lookups5, Mgr::ServiceTimesActionData::dns_lookups60, Mgr::ServiceTimesActionData::http_requests5, Mgr::ServiceTimesActionData::http_requests60, Mgr::ServiceTimesActionData::icp_queries5, Mgr::ServiceTimesActionData::icp_queries60, Mgr::ServiceTimesActionData::near_hits5, Mgr::ServiceTimesActionData::near_hits60, Mgr::ServiceTimesActionData::not_modified_replies5, Mgr::ServiceTimesActionData::not_modified_replies60, Mgr::ServiceTimesActionData::seriesSize, and storeAppendPrintf().
Referenced by Mgr::ServiceTimesAction::dump().
GetAvgStat()
void GetAvgStat (Mgr::IntervalActionData & stats, int minutes, int hours)
Definition at line 865 of file stat.cc.
References Mgr::IntervalActionData::aborted_requests, StatCounters::allSvcTime, assert, Mgr::IntervalActionData::average_select_fd_period, StatCounters::client_http, Mgr::IntervalActionData::client_http_all_median_svc_time, Mgr::IntervalActionData::client_http_errors, Mgr::IntervalActionData::client_http_hit_median_svc_time, Mgr::IntervalActionData::client_http_hits, Mgr::IntervalActionData::client_http_kbytes_in, Mgr::IntervalActionData::client_http_kbytes_out, Mgr::IntervalActionData::client_http_miss_median_svc_time, Mgr::IntervalActionData::client_http_nh_median_svc_time, Mgr::IntervalActionData::client_http_nm_median_svc_time, Mgr::IntervalActionData::client_http_requests, CountHist, CountHourHist, Mgr::IntervalActionData::cpu_time, StatCounters::cputime, DBG_IMPORTANT, debugs, StatCounters::dns, Mgr::IntervalActionData::dns_median_svc_time, StatCounters::hitSvcTime, Mgr::IntervalActionData::hitValidationAttempts, Mgr::IntervalActionData::hitValidationFailures, Mgr::IntervalActionData::hitValidationRefusalsDueToLocking, Mgr::IntervalActionData::hitValidationRefusalsDueToTimeLimit, Mgr::IntervalActionData::hitValidationRefusalsDueToZeroSize, StatCounters::icp, Mgr::IntervalActionData::icp_kbytes_recv, Mgr::IntervalActionData::icp_kbytes_sent, Mgr::IntervalActionData::icp_pkts_recv, Mgr::IntervalActionData::icp_pkts_sent, Mgr::IntervalActionData::icp_q_kbytes_recv, Mgr::IntervalActionData::icp_q_kbytes_sent, Mgr::IntervalActionData::icp_queries_recv, Mgr::IntervalActionData::icp_queries_sent, Mgr::IntervalActionData::icp_query_median_svc_time, Mgr::IntervalActionData::icp_query_timeouts, Mgr::IntervalActionData::icp_r_kbytes_recv, Mgr::IntervalActionData::icp_r_kbytes_sent, Mgr::IntervalActionData::icp_replies_queued, Mgr::IntervalActionData::icp_replies_recv, Mgr::IntervalActionData::icp_replies_sent, Mgr::IntervalActionData::icp_reply_median_svc_time, Mgr::IntervalActionData::median_select_fds, StatCounters::missSvcTime, N_COUNT_HIST, N_COUNT_HOUR_HIST, StatCounters::nearHitSvcTime, StatCounters::nearMissSvcTime, Mgr::IntervalActionData::page_faults, StatCounters::querySvcTime, StatCounters::replySvcTime, Mgr::IntervalActionData::sample_end_time, Mgr::IntervalActionData::sample_start_time, Mgr::IntervalActionData::select_fds, StatCounters::select_fds, StatCounters::select_fds_hist, Mgr::IntervalActionData::select_loops, StatCounters::select_time, server, Mgr::IntervalActionData::server_all_errors, Mgr::IntervalActionData::server_all_kbytes_in, Mgr::IntervalActionData::server_all_kbytes_out, Mgr::IntervalActionData::server_all_requests, Mgr::IntervalActionData::server_ftp_errors, Mgr::IntervalActionData::server_ftp_kbytes_in, Mgr::IntervalActionData::server_ftp_kbytes_out, Mgr::IntervalActionData::server_ftp_requests, Mgr::IntervalActionData::server_http_errors, Mgr::IntervalActionData::server_http_kbytes_in, Mgr::IntervalActionData::server_http_kbytes_out, Mgr::IntervalActionData::server_http_requests, Mgr::IntervalActionData::server_other_errors, Mgr::IntervalActionData::server_other_kbytes_in, Mgr::IntervalActionData::server_other_kbytes_out, Mgr::IntervalActionData::server_other_requests, statHistDeltaMedian(), StatCounters::svcTime, Mgr::IntervalActionData::swap_files_cleaned, Mgr::IntervalActionData::swap_ins, Mgr::IntervalActionData::swap_outs, Mgr::IntervalActionData::syscalls_disk_closes, Mgr::IntervalActionData::syscalls_disk_opens, Mgr::IntervalActionData::syscalls_disk_reads, Mgr::IntervalActionData::syscalls_disk_seeks, Mgr::IntervalActionData::syscalls_disk_unlinks, Mgr::IntervalActionData::syscalls_disk_writes, Mgr::IntervalActionData::syscalls_selects, Mgr::IntervalActionData::syscalls_sock_accepts, Mgr::IntervalActionData::syscalls_sock_binds, Mgr::IntervalActionData::syscalls_sock_closes, Mgr::IntervalActionData::syscalls_sock_connects, Mgr::IntervalActionData::syscalls_sock_reads, Mgr::IntervalActionData::syscalls_sock_recvfroms, Mgr::IntervalActionData::syscalls_sock_sendtos, Mgr::IntervalActionData::syscalls_sock_sockets, Mgr::IntervalActionData::syscalls_sock_writes, StatCounters::timestamp, tvSubDsec(), Mgr::IntervalActionData::unlink_requests, Mgr::IntervalActionData::wall_time, and XAVG.
Referenced by Mgr::IntervalAction::collect(), and statAvgDump().
GetCountersStats()
void GetCountersStats (Mgr::CountersActionData & stats)
Definition at line 1358 of file stat.cc.
References Mgr::CountersActionData::aborted_requests, StatCounters::aborted_requests, StatCounters::all, StatCounters::attempts, StatCounters::cd, Mgr::CountersActionData::cd_kbytes_recv, Mgr::CountersActionData::cd_kbytes_sent, Mgr::CountersActionData::cd_local_memory, Mgr::CountersActionData::cd_memory, Mgr::CountersActionData::cd_msgs_recv, Mgr::CountersActionData::cd_msgs_sent, Mgr::CountersActionData::cd_times_used, StatCounters::client_http, Mgr::CountersActionData::client_http_errors, Mgr::CountersActionData::client_http_hit_kbytes_out, Mgr::CountersActionData::client_http_hits, Mgr::CountersActionData::client_http_kbytes_in, Mgr::CountersActionData::client_http_kbytes_out, Mgr::CountersActionData::client_http_requests, Mgr::CountersActionData::cpu_time, StatCounters::cputime, current_time, StatCounters::errors, StatCounters::failures, StatCounters::files_cleaned, StatCounters::ftp, StatCounters::hit_kbytes_out, StatCounters::hits, StatCounters::hitValidation, Mgr::CountersActionData::hitValidationAttempts, Mgr::CountersActionData::hitValidationFailures, Mgr::CountersActionData::hitValidationRefusalsDueToLocking, Mgr::CountersActionData::hitValidationRefusalsDueToTimeLimit, Mgr::CountersActionData::hitValidationRefusalsDueToZeroSize, StatCounters::http, StatCounters::icp, Mgr::CountersActionData::icp_kbytes_recv, Mgr::CountersActionData::icp_kbytes_sent, Mgr::CountersActionData::icp_pkts_recv, Mgr::CountersActionData::icp_pkts_sent, Mgr::CountersActionData::icp_q_kbytes_recv, Mgr::CountersActionData::icp_q_kbytes_sent, Mgr::CountersActionData::icp_queries_recv, Mgr::CountersActionData::icp_queries_sent, Mgr::CountersActionData::icp_query_timeouts, Mgr::CountersActionData::icp_r_kbytes_recv, Mgr::CountersActionData::icp_r_kbytes_sent, Mgr::CountersActionData::icp_replies_queued, Mgr::CountersActionData::icp_replies_recv, Mgr::CountersActionData::icp_replies_sent, Mgr::CountersActionData::icp_times_used, StatCounters::ins, ByteCounter::kb, StatCounters::kbytes_in, StatCounters::kbytes_out, StatCounters::kbytes_recv, StatCounters::kbytes_sent, CacheDigest::mask_size, StatCounters::memory, StatCounters::msgs_recv, StatCounters::msgs_sent, StatCounters::other, StatCounters::outs, Mgr::CountersActionData::page_faults, StatCounters::page_faults, StatCounters::pkts_recv, StatCounters::pkts_sent, StatCounters::q_kbytes_recv, StatCounters::q_kbytes_sent, StatCounters::queries_recv, StatCounters::queries_sent, StatCounters::query_timeouts, StatCounters::r_kbytes_recv, StatCounters::r_kbytes_sent, StatCounters::refusalsDueToLocking, StatCounters::refusalsDueToTimeLimit, StatCounters::refusalsDueToZeroSize, StatCounters::replies_queued, StatCounters::replies_recv, StatCounters::replies_sent, StatCounters::requests, rusage_cputime(), rusage_pagefaults(), Mgr::CountersActionData::sample_time, Mgr::CountersActionData::select_loops, StatCounters::select_loops, StatCounters::server, Mgr::CountersActionData::server_all_errors, Mgr::CountersActionData::server_all_kbytes_in, Mgr::CountersActionData::server_all_kbytes_out, Mgr::CountersActionData::server_all_requests, Mgr::CountersActionData::server_ftp_errors, Mgr::CountersActionData::server_ftp_kbytes_in, Mgr::CountersActionData::server_ftp_kbytes_out, Mgr::CountersActionData::server_ftp_requests, Mgr::CountersActionData::server_http_errors, Mgr::CountersActionData::server_http_kbytes_in, Mgr::CountersActionData::server_http_kbytes_out, Mgr::CountersActionData::server_http_requests, Mgr::CountersActionData::server_other_errors, Mgr::CountersActionData::server_other_kbytes_in, Mgr::CountersActionData::server_other_kbytes_out, Mgr::CountersActionData::server_other_requests, squid_getrusage(), statCounter, store_digest, StatCounters::swap, Mgr::CountersActionData::swap_files_cleaned, Mgr::CountersActionData::swap_ins, Mgr::CountersActionData::swap_outs, StatCounters::times_used, StatCounters::timestamp, tvSubDsec(), StatCounters::unlink, Mgr::CountersActionData::unlink_requests, and Mgr::CountersActionData::wall_time.
Referenced by Mgr::CountersAction::collect(), and statCountersDump().
GetInfo()
void GetInfo (Mgr::InfoActionData & stats)
Definition at line 431 of file stat.cc.
References Mem::PoolMeter::alloc, Mgr::InfoActionData::avg_client_http_requests, Mgr::InfoActionData::avg_icp_messages, Mgr::InfoActionData::avg_loop_time, Biggest_FD, Mgr::InfoActionData::biggest_fd, Mgr::InfoActionData::byte_hit_ratio5, Mgr::InfoActionData::byte_hit_ratio60, Mgr::InfoActionData::cache_hits5, Mgr::InfoActionData::cache_hits60, Mgr::InfoActionData::cache_misses5, Mgr::InfoActionData::cache_misses60, StatCounters::client_http, Mgr::InfoActionData::client_http_clients, Mgr::InfoActionData::client_http_requests, StatCounters::clients, Mem::PoolMeter::mgb_t::count, Mgr::InfoActionData::cpu_time, Mgr::InfoActionData::cpu_usage, Mgr::InfoActionData::cpu_usage5, Mgr::InfoActionData::cpu_usage60, Mgr::InfoActionData::current_time, current_time, Mem::Meter::currentLevel(), Mgr::InfoActionData::dns_lookups5, Mgr::InfoActionData::dns_lookups60, Math::doublePercent(), fdNFree(), Mem::PoolMeter::gb_freed, Mgr::InfoActionData::gb_freed_count, Mem::PoolMeter::gb_saved, Mgr::InfoActionData::gb_saved_count, Store::Controller::getStats(), Mem::GlobalStats(), StatCounters::htcp, Mgr::InfoActionData::htcp_pkts_recv, Mgr::InfoActionData::htcp_pkts_sent, Mgr::InfoActionData::http_requests5, Mgr::InfoActionData::http_requests60, StatCounters::icp, Mgr::InfoActionData::icp_pkts_recv, Mgr::InfoActionData::icp_pkts_sent, Mgr::InfoActionData::icp_queries5, Mgr::InfoActionData::icp_queries60, Mgr::InfoActionData::icp_replies_queued, Mgr::InfoActionData::max_fd, Mgr::InfoActionData::maxrss, Mem::PoolStats::meter, Mgr::InfoActionData::near_hits5, Mgr::InfoActionData::near_hits60, Mgr::InfoActionData::not_modified_replies5, Mgr::InfoActionData::not_modified_replies60, Mgr::InfoActionData::num_fd_free, Number_FD, Mgr::InfoActionData::number_fd, Opening_FD, Mgr::InfoActionData::opening_fd, Mgr::InfoActionData::page_faults, PCTILE_DNS, PCTILE_HIT, PCTILE_HTTP, PCTILE_ICP_QUERY, PCTILE_MISS, PCTILE_NH, PCTILE_NM, StatCounters::pkts_recv, StatCounters::pkts_sent, StatCounters::replies_queued, request_failure_ratio, Mgr::InfoActionData::request_failure_ratio, Mgr::InfoActionData::request_hit_disk_ratio5, Mgr::InfoActionData::request_hit_disk_ratio60, Mgr::InfoActionData::request_hit_mem_ratio5, Mgr::InfoActionData::request_hit_mem_ratio60, Mgr::InfoActionData::request_hit_ratio5, Mgr::InfoActionData::request_hit_ratio60, StatCounters::requests, RESERVED_FD, Mgr::InfoActionData::reserved_fd, Store::Root(), rusage_cputime(), rusage_maxrss(), rusage_pagefaults(), Mgr::InfoActionData::select_loops, StatCounters::select_loops, squid_getrusage(), Squid_MaxFD, squid_start, Mgr::InfoActionData::squid_start, statByteHitRatio(), statCounter, statCPUUsage(), statPctileSvc(), statRequestHitDiskRatio(), statRequestHitMemoryRatio(), statRequestHitRatio(), Mgr::InfoActionData::store, Mgr::InfoActionData::total_accounted, tvSubDsec(), StatCounters::unlink, Mgr::InfoActionData::unlink_requests, and Mgr::InfoActionData::up_time.
Referenced by Mgr::InfoAction::collect().
GetIoStats()
void GetIoStats (Mgr::IoActionData & stats)
Definition at line 191 of file stat.cc.
References IoStats::Ftp, Mgr::IoActionData::ftp_read_hist, Mgr::IoActionData::ftp_reads, IoStats::histSize, IoStats::Http, Mgr::IoActionData::http_read_hist, Mgr::IoActionData::http_reads, IOStats, IoStats::read_hist, and IoStats::reads.
Referenced by Mgr::IoAction::collect().
GetServiceTimesStats()
void GetServiceTimesStats (Mgr::ServiceTimesActionData & stats)
Definition at line 778 of file stat.cc.
References Mgr::ServiceTimesActionData::cache_hits5, Mgr::ServiceTimesActionData::cache_hits60, Mgr::ServiceTimesActionData::cache_misses5, Mgr::ServiceTimesActionData::cache_misses60, Mgr::ServiceTimesActionData::dns_lookups5, Mgr::ServiceTimesActionData::dns_lookups60, Mgr::ServiceTimesActionData::http_requests5, Mgr::ServiceTimesActionData::http_requests60, Mgr::ServiceTimesActionData::icp_queries5, Mgr::ServiceTimesActionData::icp_queries60, Mgr::ServiceTimesActionData::near_hits5, Mgr::ServiceTimesActionData::near_hits60, Mgr::ServiceTimesActionData::not_modified_replies5, Mgr::ServiceTimesActionData::not_modified_replies60, PCTILE_DNS, PCTILE_HIT, PCTILE_HTTP, PCTILE_ICP_QUERY, PCTILE_MISS, PCTILE_NH, PCTILE_NM, Mgr::ServiceTimesActionData::seriesSize, and statPctileSvc().
Referenced by Mgr::ServiceTimesAction::collect().
snmpStatGet()
StatCounters * snmpStatGet (int minutes)
Definition at line 1683 of file stat.cc.
References CountHist.
Referenced by snmp_prfProtoFn().
stat_objects_get()
static void stat_objects_get (StoreEntry * sentry) static
Definition at line 382 of file stat.cc.
References statObjectsStart().
stat_vmobjects_get()
static void stat_vmobjects_get (StoreEntry * sentry) static
Definition at line 394 of file stat.cc.
References statObjectsStart(), and statObjectsVmFilter().
statAvgDump()
static void statAvgDump (StoreEntry * sentry, int minutes, int hours) static
Definition at line 856 of file stat.cc.
References DumpAvgStat(), and GetAvgStat().
Referenced by statDigestBlob(), and statUtilization().
statAvgTick()
static void statAvgTick (void * notused) static
Definition at line 1273 of file stat.cc.
References Config, COUNT_INTERVAL, CountHist, CountHourHist, StatCounters::cputime, current_time, DBG_CRITICAL, debugs, eventAdd(), SquidConfig::high_memory, SquidConfig::high_pf, SquidConfig::high_rptm, int, N_COUNT_HIST, N_COUNT_HOUR_HIST, NCountHist, NCountHourHist, StatCounters::page_faults, PCTILE_HTTP, rusage_cputime(), rusage_pagefaults(), squid_getrusage(), statAvgTick(), statCounter, statPctileSvc(), StatCounters::timestamp, tvSubDsec(), and SquidConfig::warnings.
Referenced by statAvgTick(), and statInit().
statByteHitRatio()
double statByteHitRatio (int minutes)
Definition at line 1740 of file stat.cc.
References StatCounters::all, assert, StatCounters::cd, StatCounters::client_http, CountHist, DBG_IMPORTANT, debugs, Math::doublePercent(), ByteCounter::kb, StatCounters::kbytes_in, StatCounters::kbytes_out, StatCounters::kbytes_recv, N_COUNT_HIST, and StatCounters::server.
Referenced by GetInfo(), and snmp_prfProtoFn().
statClientRequests()
static void statClientRequests (StoreEntry * s) static
Definition at line 1776 of file stat.cc.
References ClientHttpRequest::al, assert, HttpRequest::auth_user_request, LogTags::c_str(), AccessLogEntry::cache, ClientActiveRequests, Server::clientConnection, current_time, dash_str, dlink_node::data, DelayId::DelayClient(), HttpRequest::extacl_user, Comm::Connection::fd, fd_table, ClientHttpRequest::getConn(), StoreEntry::getMD5Text(), dlink_list::head, Server::inBuf, Comm::IsConnOpen(), SBuf::length(), Comm::Connection::local, ClientHttpRequest::loggingTags(), MAX_IPSTRLEN, dlink_node::next, Pipeline::nrequests, ClientHttpRequest::Out::offset, ClientHttpRequest::out, Server::pipeline, PRId64, SBuf::rawContent(), Comm::Connection::remote, ClientHttpRequest::req_sz, ClientHttpRequest::request, ClientHttpRequest::Out::size, String::size(), SBuf::spaceSize(), sslGetUserEmail(), AccessLogEntry::CacheDetails::start_time, storeAppendPrintf(), ClientHttpRequest::storeEntry(), String::termedBuf(), Ip::Address::toUrl(), tvSubDsec(), ClientHttpRequest::uri, and Auth::UserRequest::username().
statCountersDump()
static void statCountersDump (StoreEntry * sentry) static
Definition at line 1350 of file stat.cc.
References DumpCountersStats(), and GetCountersStats().
statCountersHistograms()
static void statCountersHistograms (StoreEntry * sentry) static
Definition at line 1327 of file stat.cc.
References StatCounters::allSvcTime, StatCounters::client_http, StatCounters::dns, StatHist::dump(), StatCounters::hitSvcTime, StatCounters::icp, StatCounters::missSvcTime, StatCounters::nearHitSvcTime, StatCounters::nearMissSvcTime, StatCounters::querySvcTime, StatCounters::replySvcTime, StatCounters::select_fds_hist, statCounter, storeAppendPrintf(), and StatCounters::svcTime.
statCountersInit()
static void statCountersInit (StatCounters * C) static
Definition at line 1242 of file stat.cc.
References assert, and statCountersInitSpecial().
Referenced by statInit().
statCountersInitSpecial()
static void statCountersInitSpecial (StatCounters * C) static
Definition at line 1210 of file stat.cc.
References StatCounters::allSvcTime, CacheDigestHashFuncCount, StatCounters::cd, StatCounters::client_http, StatCounters::comm_dns, StatCounters::comm_tcp, StatCounters::comm_udp, StatCounters::dns, StatHist::enumInit(), StatCounters::hitSvcTime, StatCounters::icp, INCOMING_DNS_MAX, INCOMING_TCP_MAX, INCOMING_UDP_MAX, Comm::Incoming::init(), StatHist::logInit(), StatCounters::missSvcTime, StatCounters::nearHitSvcTime, StatCounters::nearMissSvcTime, StatCounters::on_xition_count, StatCounters::querySvcTime, StatCounters::replySvcTime, StatCounters::select_fds_hist, and StatCounters::svcTime.
Referenced by statCountersInit().
statCPUUsage()
static double statCPUUsage (int minutes) static
Definition at line 1702 of file stat.cc.
References assert, CountHist, Math::doublePercent(), N_COUNT_HIST, and tvSubDsec().
Referenced by GetInfo().
statDigestBlob()
static void statDigestBlob (StoreEntry * sentry) static
Definition at line 1611 of file stat.cc.
References statAvgDump(), statCountersDump, statCountersHistograms, statPeerSelect, storeAppendPrintf(), and storeDigestReport().
statInit()
void statInit (void)
Definition at line 1250 of file stat.cc.
References ClientActiveRequests, COUNT_INTERVAL, CountHist, CountHourHist, debugs, eventAdd(), dlink_list::head, N_COUNT_HIST, N_COUNT_HOUR_HIST, statAvgTick(), statCounter, statCountersInit(), statRegisterWithCacheManager(), and dlink_list::tail.
Referenced by mainInitialize().
statObjects()
static void statObjects (void * data) static
Definition at line 325 of file stat.cc.
References StoreEntry::append(), MemBuf::buf, StoreEntry::buffer(), StoreEntry::checkDeferRead(), MemBuf::clean(), Mgr::CloseKidSection(), StoreEntry::complete(), Config, StoreSearch::currentItem(), EBIT_TEST, ENTRY_ABORTED, eventAdd(), StatObjectsState::filter, StoreEntry::flags, StoreEntry::flush(), Mgr::informal, MemBuf::init(), StoreSearch::isDone(), SquidConfig::objectsPerBucket, StatObjectsState::sentry, MemBuf::size, statObjects, statStoreEntry(), SquidConfig::Store, StatObjectsState::theSearch, and StoreEntry::unlock().
statObjectsOpenfdFilter()
static int statObjectsOpenfdFilter (const StoreEntry * e) static
Definition at line 400 of file stat.cc.
References StoreEntry::mem_obj, MemObject::SwapOut::sio, and MemObject::swapout.
Referenced by statOpenfdObj().
statObjectsStart()
static void statObjectsStart (StoreEntry * sentry, STOBJFLT * filter) static
Definition at line 369 of file stat.cc.
References eventAdd(), StatObjectsState::filter, StoreEntry::lock(), Store::Root(), Store::Controller::search(), StatObjectsState::sentry, statObjects, and StatObjectsState::theSearch.
Referenced by stat_objects_get(), stat_vmobjects_get(), and statOpenfdObj().
statObjectsVmFilter()
static int statObjectsVmFilter (const StoreEntry * e) static
Definition at line 388 of file stat.cc.
References StoreEntry::mem_obj.
Referenced by stat_vmobjects_get().
statOpenfdObj()
static void statOpenfdObj (StoreEntry * sentry) static
Definition at line 412 of file stat.cc.
References statObjectsOpenfdFilter(), and statObjectsStart().
statPctileSvc()
static double statPctileSvc (double pctile, int interval, int which) static
Definition at line 1626 of file stat.cc.
References StatCounters::allSvcTime, assert, StatCounters::client_http, CountHist, debugs, StatCounters::dns, StatCounters::hitSvcTime, StatCounters::icp, StatCounters::missSvcTime, N_COUNT_HIST, StatCounters::nearHitSvcTime, StatCounters::nearMissSvcTime, PCTILE_DNS, PCTILE_HIT, PCTILE_HTTP, PCTILE_ICP_QUERY, PCTILE_MISS, PCTILE_NH, PCTILE_NM, StatCounters::querySvcTime, statHistDeltaPctile(), and StatCounters::svcTime.
Referenced by GetInfo(), GetServiceTimesStats(), and statAvgTick().
statPeerSelect()
static void statPeerSelect (StoreEntry * sentry) static
Definition at line 1576 of file stat.cc.
References cacheDigestGuessStatsReport(), StatCounters::cd, CurrentCachePeers(), StatCounters::guess, StatCounters::icp, peerDigestStatsReport(), statCounter, storeAppendPrintf(), StatCounters::times_used, and xpercentInt().
statRegisterWithCacheManager()
static void statRegisterWithCacheManager (void) static
Definition at line 1165 of file stat.cc.
References Mgr::CountersAction::Create(), Mgr::InfoAction::Create(), Mgr::IoAction::Create(), Mgr::ServiceTimesAction::Create(), Mgr::IntervalAction::Create5min(), Mgr::IntervalAction::Create60min(), Auth::User::CredentialsCacheStats(), fde::DumpStats(), Mgr::RegisterAction(), stat_objects_get, stat_vmobjects_get, statClientRequests, statCountersHistograms, statDigestBlob, statOpenfdObj, statPeerSelect, and statUtilization.
Referenced by statInit().
statRequestHitDiskRatio()
double statRequestHitDiskRatio (int minutes)
Definition at line 1730 of file stat.cc.
References assert, StatCounters::client_http, CountHist, StatCounters::disk_hits, Math::doublePercent(), StatCounters::hits, and N_COUNT_HIST.
Referenced by GetInfo().
statRequestHitMemoryRatio()
double statRequestHitMemoryRatio (int minutes)
Definition at line 1720 of file stat.cc.
References assert, StatCounters::client_http, CountHist, Math::doublePercent(), StatCounters::hits, StatCounters::mem_hits, and N_COUNT_HIST.
Referenced by GetInfo().
statRequestHitRatio()
double statRequestHitRatio (int minutes)
Definition at line 1710 of file stat.cc.
References assert, StatCounters::client_http, CountHist, Math::doublePercent(), StatCounters::hits, N_COUNT_HIST, and StatCounters::requests.
Referenced by GetInfo(), and snmp_prfProtoFn().
statSawRecentRequests()
bool statSawRecentRequests ()
whether we processed any incoming requests in the last few minutes
See also
ClientHttpRequest::updateCounters()
Definition at line 1689 of file stat.cc.
References assert, StatCounters::client_http, CountHist, N_COUNT_HIST, NCountHist, StatCounters::requests, and statCounter.
Referenced by peerDnsRefreshCheck().
statStoreEntry()
static void statStoreEntry (MemBuf * mb, StoreEntry * e) static
Definition at line 307 of file stat.cc.
References MemBuf::append(), Packable::appendf(), describeStatuses(), StoreEntry::describeTimestamps(), StoreEntry::getMD5Text(), StoreEntry::locks(), StoreEntry::mem_obj, StoreEntry::refcount, MemObject::stat(), storeEntryFlags(), storePendingNClients(), StoreEntry::swap_dirn, and StoreEntry::swap_filen.
Referenced by statObjects().
statUtilization()
static void statUtilization (StoreEntry * e) static
Definition at line 127 of file stat.cc.
References NCountHist, NCountHourHist, statAvgDump(), statCountersDump, and storeAppendPrintf().
storeEntryFlags()
const char * storeEntryFlags (const StoreEntry * entry)
Definition at line 254 of file stat.cc.
References DELAY_SENDING, EBIT_TEST, ENTRY_ABORTED, ENTRY_BAD_LENGTH, ENTRY_DISPATCHED, ENTRY_FWD_HDR_WAIT, ENTRY_NEGCACHED, ENTRY_REVALIDATE_ALWAYS, ENTRY_REVALIDATE_STALE, ENTRY_SPECIAL, ENTRY_VALIDATED, StoreEntry::flags, int, KEY_PRIVATE, LOCAL_ARRAY, REFRESH_REQUEST, and RELEASE_REQUEST.
Referenced by StoreEntry::dump(), and statStoreEntry().
Variable Documentation
CountHist
StatCounters CountHist[N_COUNT_HIST]
Definition at line 117 of file stat.cc.
Referenced by GetAvgStat(), snmpStatGet(), statAvgTick(), statByteHitRatio(), statCPUUsage(), statInit(), statPctileSvc(), statRequestHitDiskRatio(), statRequestHitMemoryRatio(), statRequestHitRatio(), and statSawRecentRequests().
CountHourHist
StatCounters CountHourHist[N_COUNT_HOUR_HIST] static
Definition at line 119 of file stat.cc.
Referenced by GetAvgStat(), statAvgTick(), and statInit().
mem_pool_alloc_calls
unsigned int mem_pool_alloc_calls extern
mem_pool_free_calls
unsigned int mem_pool_free_calls extern
NCountHist
int NCountHist = 0 static
Definition at line 118 of file stat.cc.
Referenced by statAvgTick(), statSawRecentRequests(), and statUtilization().
NCountHourHist
int NCountHourHist = 0 static
Definition at line 120 of file stat.cc.
Referenced by statAvgTick(), and statUtilization().
stat_objects_get
OBJH stat_objects_get static
Definition at line 89 of file stat.cc.
Referenced by statRegisterWithCacheManager().
stat_vmobjects_get
OBJH stat_vmobjects_get static
Definition at line 90 of file stat.cc.
Referenced by statRegisterWithCacheManager().
statClientRequests
OBJH statClientRequests static
Definition at line 98 of file stat.cc.
Referenced by statRegisterWithCacheManager().
statCountersDump
OBJH statCountersDump static
Definition at line 93 of file stat.cc.
Referenced by statDigestBlob(), and statUtilization().
statCountersHistograms
OBJH statCountersHistograms static
Definition at line 97 of file stat.cc.
Referenced by statDigestBlob(), and statRegisterWithCacheManager().
statDigestBlob
OBJH statDigestBlob static
Definition at line 95 of file stat.cc.
Referenced by statRegisterWithCacheManager().
statObjects
EVH statObjects static
Definition at line 92 of file stat.cc.
Referenced by statObjects(), and statObjectsStart().
statOpenfdObj
OBJH statOpenfdObj static
Definition at line 91 of file stat.cc.
Referenced by statRegisterWithCacheManager().
statPeerSelect
OBJH statPeerSelect static
Definition at line 94 of file stat.cc.
Referenced by statDigestBlob(), and statRegisterWithCacheManager().
statUtilization
OBJH statUtilization static
Definition at line 96 of file stat.cc.
Referenced by statRegisterWithCacheManager().