Squid Web Cache: squid/src/stat.h File Reference
stat.h File Reference
Functions
void statInit (void)
double median_svc_get (int, int)
void pconnHistCount (int, int)
bool statSawRecentRequests ()
double statRequestHitRatio (int minutes)
double statRequestHitMemoryRatio (int minutes)
double statRequestHitDiskRatio (int minutes)
double statByteHitRatio (int minutes)
StatCounters * snmpStatGet (int)
Function Documentation
median_svc_get()
double median_svc_get (int , int)
pconnHistCount()
void pconnHistCount (int , int)
snmpStatGet()
StatCounters * snmpStatGet (int minutes)
Definition at line 1682 of file stat.cc.
References CountHist.
Referenced by snmp_prfProtoFn().
statByteHitRatio()
double statByteHitRatio (int minutes)
Definition at line 1739 of file stat.cc.
References StatCounters::all, assert, StatCounters::cd, StatCounters::client_http, CountHist, DBG_IMPORTANT, debugs, Math::doublePercent(), ByteCounter::kb, StatCounters::kbytes_in, StatCounters::kbytes_out, StatCounters::kbytes_recv, N_COUNT_HIST, and StatCounters::server.
Referenced by GetInfo(), and snmp_prfProtoFn().
statInit()
void statInit (void)
Definition at line 1249 of file stat.cc.
References ClientActiveRequests, COUNT_INTERVAL, CountHist, CountHourHist, debugs, eventAdd(), dlink_list::head, N_COUNT_HIST, N_COUNT_HOUR_HIST, statAvgTick(), statCounter, statCountersInit(), statRegisterWithCacheManager(), and dlink_list::tail.
Referenced by mainInitialize().
statRequestHitDiskRatio()
double statRequestHitDiskRatio (int minutes)
Definition at line 1729 of file stat.cc.
References assert, StatCounters::client_http, CountHist, StatCounters::disk_hits, Math::doublePercent(), StatCounters::hits, and N_COUNT_HIST.
Referenced by GetInfo().
statRequestHitMemoryRatio()
double statRequestHitMemoryRatio (int minutes)
Definition at line 1719 of file stat.cc.
References assert, StatCounters::client_http, CountHist, Math::doublePercent(), StatCounters::hits, StatCounters::mem_hits, and N_COUNT_HIST.
Referenced by GetInfo().
statRequestHitRatio()
double statRequestHitRatio (int minutes)
Definition at line 1709 of file stat.cc.
References assert, StatCounters::client_http, CountHist, Math::doublePercent(), StatCounters::hits, N_COUNT_HIST, and StatCounters::requests.
Referenced by GetInfo(), and snmp_prfProtoFn().
statSawRecentRequests()
bool statSawRecentRequests ()
whether we processed any incoming requests in the last few minutes
See also
ClientHttpRequest::updateCounters()
Definition at line 1688 of file stat.cc.
References assert, StatCounters::client_http, CountHist, N_COUNT_HIST, NCountHist, StatCounters::requests, and statCounter.
Referenced by peerDnsRefreshCheck().