Squid Web Cache: squid/src/StatHist.h File Reference
StatHist.h File Reference
#include "Store.h"
Classes
class StatHist
Typedefs
typedef double hbase_f(double)
function signature for in/out StatHist adaptation
typedef void StatHistBinDumper(StoreEntry *, int idx, double val, double size, int count)
function signature for StatHist dumping functions
Functions
double statHistDeltaMedian (const StatHist &A, const StatHist &B)
double statHistDeltaPctile (const StatHist &A, const StatHist &B, double pctile)
Variables
StatHistBinDumper statHistEnumDumper
StatHistBinDumper statHistIntDumper
Typedef Documentation
hbase_f
typedef double hbase_f(double)
Definition at line 16 of file StatHist.h.
StatHistBinDumper
typedef void StatHistBinDumper(StoreEntry *, int idx, double val, double size, int count)
Definition at line 19 of file StatHist.h.
Function Documentation
statHistDeltaMedian()
double statHistDeltaMedian (const StatHist & A, const StatHist & B)
Definition at line 91 of file StatHist.cc.
References statHistDeltaPctile().
Referenced by GetAvgStat(), and snmp_prfProtoFn().
statHistDeltaPctile()
double statHistDeltaPctile (const StatHist & A, const StatHist & B, double pctile)
Definition at line 97 of file StatHist.cc.
References StatHist::deltaPctile().
Referenced by statHistDeltaMedian(), and statPctileSvc().
Variable Documentation
statHistEnumDumper
StatHistBinDumper statHistEnumDumper
Definition at line 118 of file StatHist.h.
statHistIntDumper
StatHistBinDumper statHistIntDumper
Definition at line 119 of file StatHist.h.
Referenced by commIncomingStats(), commIncomingStats(), commIncomingStats(), and commIncomingStats().