Squid Web Cache: squid/compat/statvfs.h File Reference
statvfs.h File Reference
Classes
struct statvfs
Typedefs
typedef unsigned long fsblkcnt_t
typedef unsigned long fsfilcnt_t
Functions
int xstatvfs (const char *path, struct statvfs *buf)
Typedef Documentation
fsblkcnt_t
typedef unsigned long fsblkcnt_t
Definition at line 40 of file statvfs.h.
fsfilcnt_t
typedef unsigned long fsfilcnt_t
Definition at line 41 of file statvfs.h.
Function Documentation
xstatvfs()
int xstatvfs (const char * path, struct statvfs * buf)
Definition at line 22 of file statvfs.cc.
References statvfs::f_bavail, statvfs::f_bfree, statvfs::f_blocks, statvfs::f_bsize, statvfs::f_favail, statvfs::f_ffree, statvfs::f_files, statvfs::f_frsize, statvfs::f_fsid, statvfs::f_namemax, and STATFS_FRSIZE.
Referenced by fsBlockSize(), fsStats(), and main().