Squid Web Cache: squid/src/ipc/StoreMap.cc File Reference
StoreMap.cc File Reference
#include "squid.h"
#include "base/IoManip.h"
#include "ipc/StoreMap.h"
#include "sbuf/SBuf.h"
#include "SquidConfig.h"
#include "StatCounters.h"
#include "Store.h"
#include "store/Controller.h"
#include "store_key_md5.h"
#include "tools.h"
#include <chrono>
Classes
class ConservativeTimer
Functions
static SBuf StoreMapSlicesId (const SBuf &path)
static SBuf StoreMapAnchorsId (const SBuf &path)
static SBuf StoreMapFileNosId (const SBuf &path)
Function Documentation
StoreMapAnchorsId()
static SBuf StoreMapAnchorsId (const SBuf & path) static
Definition at line 31 of file StoreMap.cc.
References Ipc::Mem::Segment::Name().
Referenced by Ipc::StoreMap::Init().
StoreMapFileNosId()
static SBuf StoreMapFileNosId (const SBuf & path) static
Definition at line 37 of file StoreMap.cc.
References Ipc::Mem::Segment::Name().
Referenced by Ipc::StoreMap::Init().
StoreMapSlicesId()
static SBuf StoreMapSlicesId (const SBuf & path) static
Definition at line 25 of file StoreMap.cc.
References Ipc::Mem::Segment::Name().
Referenced by Ipc::StoreMap::Init().