Squid Web Cache: squid/src/repl/heap/store_heap_replacement.cc File Reference
store_heap_replacement.cc File Reference
#include "squid.h"
#include "heap.h"
#include "MemObject.h"
#include "Store.h"
#include "store_heap_replacement.h"
#include <cmath>
Functions
heap_key HeapKeyGen_StoreEntry_LFUDA (void *entry, double heap_age)
heap_key HeapKeyGen_StoreEntry_GDSF (void *entry, double heap_age)
heap_key HeapKeyGen_StoreEntry_LRU (void *entry, double heap_age)
Function Documentation
HeapKeyGen_StoreEntry_GDSF()
heap_key HeapKeyGen_StoreEntry_GDSF (void * entry, double heap_age)
Definition at line 93 of file store_heap_replacement.cc.
References debugs, double, StoreEntry::getMD5Text(), StoreEntry::lastref, StoreEntry::mem_obj, StoreEntry::refcount, size, MemObject::storeId(), and StoreEntry::swap_file_sz.
Referenced by createRemovalPolicy_heap().
HeapKeyGen_StoreEntry_LFUDA()
heap_key HeapKeyGen_StoreEntry_LFUDA (void * entry, double heap_age)
Definition at line 48 of file store_heap_replacement.cc.
References debugs, double, StoreEntry::getMD5Text(), StoreEntry::lastref, StoreEntry::mem_obj, StoreEntry::refcount, squid_curtime, and MemObject::storeId().
Referenced by createRemovalPolicy_heap().
HeapKeyGen_StoreEntry_LRU()
heap_key HeapKeyGen_StoreEntry_LRU (void * entry, double heap_age)
Definition at line 119 of file store_heap_replacement.cc.
References debugs, StoreEntry::getMD5Text(), StoreEntry::lastref, StoreEntry::mem_obj, and MemObject::storeId().
Referenced by createRemovalPolicy_heap().