Squid Web Cache: squid/src/store_rebuild.h File Reference
store_rebuild.h File Reference
#include "store_key_md5.h"
Classes
class StoreRebuildData
cache_dir(s) indexing statistics
class Progress
advancement of work that consists of (usually known number) of similar steps
Functions
std::ostream & operator<< (std::ostream &os, const Progress &p)
void storeRebuildStart (void)
void storeRebuildComplete (StoreRebuildData *)
void storeRebuildProgress (int sd_index, int total, int sofar)
bool storeRebuildLoadEntry (int fd, int diskIndex, MemBuf &buf, StoreRebuildData &counts)
loads entry from disk; fills supplied memory buffer on success
bool storeRebuildParseEntry (MemBuf &buf, StoreEntry &e, cache_key *key, StoreRebuildData &counts, uint64_t expectedSize)
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const Progress & p) inline
Definition at line 59 of file store_rebuild.h.
References Progress::print().
storeRebuildComplete()
void storeRebuildComplete (StoreRebuildData * dc)
Definition at line 132 of file store_rebuild.cc.
References assert, StoreRebuildData::bad_log_op, StoreRebuildData::badflags, SquidConfig::cacheSwap, StoreRebuildData::cancelcount, StoreRebuildData::clashcount, Config, counts, current_time, debugs, StoreRebuildData::dupcount, eventAdd(), StoreRebuildData::expcount, Debug::Extra(), Important, StoreRebuildData::invalid, Store::DiskConfig::n_configured, StoreRebuildData::objcount, RebuildProgress, safe_free, StoreRebuildData::scancount, StoreRebuildData::started(), StoreRebuildData::startTime, Store::Controller::store_dirs_rebuilding, storeCleanup(), storeCleanupComplete(), tvSubDsec(), StoreRebuildData::updateStartTime(), StoreRebuildData::validations, and StoreRebuildData::zero_object_sz.
Referenced by Store::Disks::init(), Rock::SwapDir::ioCompletedNotification(), and Rock::Rebuild::swanSong().
storeRebuildLoadEntry()
bool storeRebuildLoadEntry (int fd, int diskIndex, MemBuf & buf, StoreRebuildData & counts)
Definition at line 265 of file store_rebuild.cc.
References MemBuf::appended(), assert, DBG_IMPORTANT, debugs, StatCounters::disk, FD_READ_METHOD(), MemBuf::hasSpace(), StatCounters::reads, MemBuf::space(), MemBuf::spaceSize(), statCounter, StatCounters::syscalls, and xstrerr().
Referenced by Rock::Rebuild::loadOneSlot(), and Fs::Ufs::RebuildState::rebuildFromDirectory().
storeRebuildParseEntry()
bool storeRebuildParseEntry (MemBuf & buf, StoreEntry & e, cache_key * key, StoreRebuildData & counts, uint64_t expectedSize)
Parses the given Store entry metadata, filling e and key. Optimization: Both e and key parameters may be updated even on failures.
Parameters
buf memory containing serialized Store entry swap metadata (at least)
e caller's temporary StoreEntry object for returning parsed metadata
key caller's temporary Store entry key buffer; usable to set e.key
expectedSize either total entry size (including swap metadata) or 0
Return values
true success; e/key filled with parsed metadata
false failure; e/key ought to be ignored (may be filled/dirty)
Definition at line 286 of file store_rebuild.cc.
References StoreRebuildData::badflags, CurrentException(), DBG_IMPORTANT, debugs, EBIT_TEST, StoreEntry::flags, Important, hash_link::key, KEY_PRIVATE, StoreEntry::swap_file_sz, and Store::UnpackIndexSwapMeta().
Referenced by Rock::Rebuild::importEntry(), and Fs::Ufs::RebuildState::rebuildFromDirectory().
storeRebuildProgress()
void storeRebuildProgress (int sd_index, int total, int sofar)
Definition at line 214 of file store_rebuild.cc.
References SquidConfig::cacheSwap, Config, debugs, double, Important, Store::DiskConfig::n_configured, RebuildProgress, store_rebuild_progress::scanned, squid_curtime, and store_rebuild_progress::total.
Referenced by Rock::Rebuild::loadingSteps(), and Fs::Ufs::RebuildState::rebuildStep().
storeRebuildStart()
void storeRebuildStart (void)
Definition at line 192 of file store_rebuild.cc.
References SquidConfig::cacheSwap, Config, counts, Store::DiskConfig::n_configured, RebuildProgress, and xcalloc().
Referenced by storeInit().