Squid Web Cache: squid/src/store_swapout.cc File Reference
store_swapout.cc File Reference
#include "squid.h"
#include "base/IoManip.h"
#include "cbdata.h"
#include "CollapsedForwarding.h"
#include "globals.h"
#include "Store.h"
#include "StoreClient.h"
#include "mem_node.h"
#include "MemObject.h"
#include "SquidConfig.h"
#include "StatCounters.h"
#include "store/Disk.h"
#include "store/Disks.h"
#include "store_log.h"
#include "swap_log_op.h"
Functions
static void storeSwapOutStart (StoreEntry *e)
static void xfree_cppwrapper (void *x)
static bool doPages (StoreEntry *anEntry)
static void storeSwapOutFileClosed (void *data, int errflag, StoreIOState::Pointer self)
Variables
static StoreIOState::STIOCB storeSwapOutFileClosed
Function Documentation
doPages()
static bool doPages (StoreEntry * anEntry) static
Definition at line 90 of file store_swapout.cc.
References assert, MemObject::data_hdr, debugs, MemObject::endOffset(), mem_hdr::getBlockContainingLocation(), StoreIOBuffer::length, StoreEntry::mem_obj, memNodeWriteComplete(), mem_node::nodeBuffer, mem_hdr::NodeGet(), MemObject::SwapOut::queue_offset, MemObject::SwapOut::sio, SM_PAGE_SIZE, mem_node::start(), STORE_PENDING, StoreEntry::store_status, MemObject::swapout, StoreEntry::swappingOut(), and StoreIOState::write().
Referenced by StoreEntry::swapOut().
storeSwapOutFileClosed()
static void storeSwapOutFileClosed (void * data, int errflag, StoreIOState::Pointer self) static
Definition at line 270 of file store_swapout.cc.
References asHex(), assert, StoreEntry::checkCachable(), debugs, StoreEntry::disk(), DISK_NO_SPACE_LEFT, Store::Disk::diskFull(), Store::Disk::finalizeSwapoutFailure(), Store::Disk::finalizeSwapoutSuccess(), StoreEntry::mem_obj, StoreEntry::objectLen(), StatCounters::outs, StoreEntry::releaseRequest(), MemObject::SwapOut::sio, statCounter, STORE_LOG_SWAPOUT, storeConfigure(), storeDirSwapLog(), storeLog(), StoreEntry::storeWriterDone(), StatCounters::swap, StoreEntry::swap_dirn, StoreEntry::swap_file_sz, StoreEntry::swap_filen, MemObject::swap_hdr_sz, SWAP_LOG_ADD, StoreEntry::swap_status, MemObject::swapout, SWAPOUT_DONE, SWAPOUT_FAILED, StoreEntry::swappingOut(), StoreEntry::unlock(), and StoreEntry::url().
storeSwapOutStart()
static void storeSwapOutStart (StoreEntry * e) static
Definition at line 39 of file store_swapout.cc.
References asHex(), assert, StoreEntry::attachToDisk(), debugs, StoreEntry::getSerialisedMetaData(), StoreEntry::hasDisk(), StoreEntry::lock(), StoreEntry::mem_obj, MemObject::SwapOut::sio, STORE_LOG_SWAPOUTFAIL, storeCreate(), storeIOWrite(), storeLog(), storeSwapOutFileClosed, StoreEntry::swap_dirn, StoreIOState::swap_dirn, StoreEntry::swap_filen, StoreIOState::swap_filen, MemObject::swap_hdr_sz, StoreEntry::swap_status, MemObject::swapout, SWAPOUT_NONE, SWAPOUT_WRITING, StoreEntry::swapOutDecision(), MemObject::SwapOut::swImpossible, MemObject::SwapOut::swStarted, StoreEntry::url(), xfree, and xfree_cppwrapper().
Referenced by StoreEntry::swapOut().
xfree_cppwrapper()
static void xfree_cppwrapper (void * x) static
Definition at line 32 of file store_swapout.cc.
References xfree.
Referenced by storeSwapOutStart().
Variable Documentation
storeSwapOutFileClosed
StoreIOState::STIOCB storeSwapOutFileClosed static
Definition at line 29 of file store_swapout.cc.
Referenced by storeSwapOutStart().