Squid Web Cache: squid/src/store_io.cc File Reference
store_io.cc File Reference
#include "squid.h"
#include "MemObject.h"
#include "SquidConfig.h"
#include "Store.h"
#include "store/Disk.h"
#include "store/Disks.h"
Functions
StoreIOState::Pointer storeCreate (StoreEntry *e, StoreIOState::STIOCB *close_callback, void *callback_data)
StoreIOState::Pointer storeOpen (StoreEntry *e, StoreIOState::STIOCB *callback, void *callback_data)
void storeClose (StoreIOState::Pointer sio, int how)
void storeRead (StoreIOState::Pointer sio, char *buf, size_t size, off_t offset, StoreIOState::STRCB *callback, void *callback_data)
void storeIOWrite (StoreIOState::Pointer sio, char const *buf, size_t size, off_t offset, FREE *free_func)
Variables
StoreIoStats store_io_stats
Function Documentation
storeClose()
void storeClose (StoreIOState::Pointer sio, int how)
Definition at line 65 of file store_io.cc.
References StoreIOState::close(), StoreIOState::closing, debugs, and StoreIOState::flags.
Referenced by storeUnregister(), and StoreEntry::swapOutFileClose().
storeCreate()
StoreIOState::Pointer storeCreate (StoreEntry * e, StoreIOState::STIOCB * close_callback, void * callback_data)
Definition at line 25 of file store_io.cc.
References assert, StoreIoStats::calls, StoreIoStats::create, StoreIoStats::create_fail, debugs, StoreIoStats::select_fail, Store::Disks::SelectSwapDir(), store_io_stats, and StoreIoStats::success.
Referenced by storeSwapOutStart().
storeIOWrite()
void storeIOWrite (StoreIOState::Pointer sio, char const * buf, size_t size, off_t offset, FREE * free_func)
Definition at line 85 of file store_io.cc.
References size, and StoreIOState::write().
Referenced by storeSwapOutStart().
storeOpen()
StoreIOState::Pointer storeOpen (StoreEntry * e, StoreIOState::STIOCB * callback, void * callback_data)
Definition at line 58 of file store_io.cc.
References StoreEntry::disk(), and Store::Disk::openStoreIO().
Referenced by storeSwapInStart().
storeRead()
void storeRead (StoreIOState::Pointer sio, char * buf, size_t size, off_t offset, StoreIOState::STRCB * callback, void * callback_data)
Definition at line 79 of file store_io.cc.
References StoreIOState::read_(), and size.
Referenced by store_client::fileRead(), and Rock::HeaderUpdater::readMore().
Variable Documentation
store_io_stats
StoreIoStats store_io_stats
Definition at line 16 of file store_io.cc.
Referenced by Mgr::StoreIoAction::collect(), and storeCreate().