Squid Web Cache: squid/src/store_key_md5.h File Reference
store_key_md5.h File Reference
#include "hash.h"
#include "http/forward.h"
#include "store/forward.h"
Enumerations
enum KeyScope { ksDefault = 0 , ksRevalidation }
Functions
cache_key * storeKeyDup (const cache_key *)
cache_key * storeKeyCopy (cache_key *, const cache_key *)
void storeKeyFree (const cache_key *)
const cache_key * storeKeyScan (const char *)
const char * storeKeyText (const cache_key *)
const cache_key * storeKeyPublic (const char *, const HttpRequestMethod &, const KeyScope keyScope=ksDefault)
const cache_key * storeKeyPublicByRequest (HttpRequest *, const KeyScope keyScope=ksDefault)
const cache_key * storeKeyPublicByRequestMethod (HttpRequest *, const HttpRequestMethod &, const KeyScope keyScope=ksDefault)
const cache_key * storeKeyPrivate ()
int storeKeyHashBuckets (int)
Variables
HASHHASH storeKeyHashHash
HASHCMP storeKeyHashCmp
Enumeration Type Documentation
KeyScope
enum KeyScope
Enumerator
ksDefault
ksRevalidation
Definition at line 18 of file store_key_md5.h.
Function Documentation
storeKeyCopy()
cache_key * storeKeyCopy (cache_key * dst, const cache_key * src)
Definition at line 147 of file store_key_md5.cc.
References SQUID_MD5_DIGEST_LENGTH.
Referenced by htcpQuery(), and icpSetCacheKey().
storeKeyDup()
cache_key * storeKeyDup (const cache_key * key)
Definition at line 139 of file store_key_md5.cc.
References MEM_MD5_DIGEST, memAllocate(), and SQUID_MD5_DIGEST_LENGTH.
Referenced by StoreEntry::hashInsert().
storeKeyFree()
void storeKeyFree (const cache_key * key)
Definition at line 154 of file store_key_md5.cc.
References MEM_MD5_DIGEST, and memFree().
Referenced by StoreEntry::hashDelete().
storeKeyHashBuckets()
int storeKeyHashBuckets (int nbuckets)
Definition at line 160 of file store_key_md5.cc.
References nbuckets.
Referenced by Store::Disks::init().
storeKeyPrivate()
const cache_key * storeKeyPrivate ()
Definition at line 80 of file store_key_md5.cc.
References assert, KidIdentifier, pid, and SQUID_MD5_DIGEST_LENGTH.
Referenced by StoreEntry::setPrivateKey().
storeKeyPublic()
const cache_key * storeKeyPublic (const char * url, const HttpRequestMethod & method, const KeyScope keyScope = ksDefault)
Definition at line 95 of file store_key_md5.cc.
References HttpRequestMethod::id(), SQUID_MD5_DIGEST_LENGTH, SquidMD5Final(), SquidMD5Init(), and SquidMD5Update().
Referenced by accessLogReader(), StoreEntry::calcPublicKey(), icpGetCacheKey(), purgeEntriesByUrl(), and storeGetPublic().
storeKeyPublicByRequest()
const cache_key * storeKeyPublicByRequest (HttpRequest * request, const KeyScope keyScope = ksDefault)
Definition at line 110 of file store_key_md5.cc.
References HttpRequest::method, and storeKeyPublicByRequestMethod().
Referenced by StoreEntry::calcPublicKey(), neighborsDigestSelect(), and peerDigestLookup().
storeKeyPublicByRequestMethod()
const cache_key * storeKeyPublicByRequestMethod (HttpRequest * request, const HttpRequestMethod & method, const KeyScope keyScope = ksDefault)
Definition at line 116 of file store_key_md5.cc.
References debugs, HttpRequestMethod::id(), SBuf::isEmpty(), SBuf::length(), SBuf::rawContent(), SQUID_MD5_DIGEST_LENGTH, SquidMD5Final(), SquidMD5Init(), SquidMD5Update(), HttpRequest::storeId(), and HttpRequest::vary_headers.
Referenced by storeGetPublicByRequestMethod(), and storeKeyPublicByRequest().
storeKeyScan()
const cache_key * storeKeyScan (const char * buf)
Definition at line 32 of file store_key_md5.cc.
References SQUID_MD5_DIGEST_LENGTH.
storeKeyText()
const char * storeKeyText (const cache_key * key)
Definition at line 17 of file store_key_md5.cc.
References SQUID_MD5_DIGEST_LENGTH.
Referenced by Fs::Ufs::UFSSwapDir::addDiskRestore(), cacheDigestHashKey(), Store::Controller::evictIfFound(), StoreEntry::forcePublicKey(), Ipc::StoreMap::freeEntryByKey(), Store::Disks::get(), StoreEntry::getMD5Text(), StoreEntry::hashInsert(), htcpHandleTstResponse(), htcpQuery(), neighborsHtcpReply(), neighborsUdpAck(), Ipc::MemMap::openForReading(), Ipc::StoreMap::openForReading(), Ipc::StoreMap::openForUpdating(), Ipc::MemMap::openForWriting(), Ipc::StoreMap::openForWriting(), Ipc::StoreMap::openOrCreateForReading(), Store::Controller::peek(), purgeEntriesByUrl(), Fs::Ufs::RebuildState::rebuildFromSwapLog(), and Ipc::StoreMap::validateHit().
Variable Documentation
storeKeyHashCmp
HASHCMP storeKeyHashCmp extern
Referenced by cacheCreate(), StoreEntry::clearPublicKeyScope(), and Store::Disks::init().
storeKeyHashHash
HASHHASH storeKeyHashHash extern
Referenced by cacheCreate(), and Store::Disks::init().