Squid Web Cache: squid/src/store_swapin.h File Reference
store_swapin.h File Reference
Functions
void storeSwapInStart (store_client *)
Function Documentation
storeSwapInStart()
void storeSwapInStart (store_client * sc)
Definition at line 21 of file store_swapin.cc.
References assert, DBG_IMPORTANT, debugs, EBIT_TEST, store_client::entry, ENTRY_VALIDATED, StoreEntry::flags, StoreEntry::getMD5Text(), StoreEntry::hasDisk(), StoreEntry::mem_obj, StoreEntry::mem_status, NOT_IN_MEMORY, storeOpen(), storeSwapInFileClosed, store_client::swapin_sio, and StoreEntry::swapoutFailed().
Referenced by store_client::startSwapin().