Squid Web Cache: squid/src/store_digest.h File Reference
store_digest.h File Reference
Functions
void storeDigestInit (void)
void storeDigestNoteStoreReady (void)
void storeDigestDel (const StoreEntry *entry)
void storeDigestReport (StoreEntry *)
Function Documentation
storeDigestDel()
void storeDigestDel (const StoreEntry * entry)
Definition at line 166 of file store_digest.cc.
References assert, Config, CacheDigest::contains(), debugs, StoreDigestStats::del_count, StoreDigestStats::del_lost_count, SquidConfig::digest_generation, EBIT_TEST, StoreEntry::flags, StoreEntry::getMD5Text(), hash_link::key, KEY_PRIVATE, SquidConfig::onoff, CacheDigest::remove(), sd_stats, store_digest, and StoreEntry::url().
storeDigestInit()
void storeDigestInit (void)
Definition at line 126 of file store_digest.cc.
References SquidConfig::bits_per_entry, Config, DBG_IMPORTANT, debugs, SquidConfig::digest, SquidConfig::digest_generation, SquidConfig::onoff, SquidConfig::rebuild_period, Mgr::RegisterAction(), SquidConfig::rewrite_period, sd_state, store_digest, storeDigestCalcCap(), and storeDigestReport().
Referenced by storeInit().
storeDigestNoteStoreReady()
void storeDigestNoteStoreReady (void)
Definition at line 152 of file store_digest.cc.
References Config, SquidConfig::digest_generation, SquidConfig::onoff, storeDigestRebuildStart(), and storeDigestRewriteStart().
Referenced by storeCleanupComplete().
storeDigestReport()
void storeDigestReport (StoreEntry * e)
Definition at line 193 of file store_digest.cc.
References StoreDigestStats::add_coll_count, StoreDigestStats::add_count, cacheDigestReport(), Config, StoreDigestStats::del_count, SquidConfig::digest_generation, SquidConfig::onoff, StoreDigestStats::rej_coll_count, StoreDigestStats::rej_count, sd_stats, store_digest, storeAppendPrintf(), and xpercent().
Referenced by statDigestBlob(), and storeDigestInit().