Squid Web Cache: squid/src/store_swapin.cc File Reference
store_swapin.cc File Reference
#include "squid.h"
#include "globals.h"
#include "StatCounters.h"
#include "Store.h"
#include "store_swapin.h"
#include "StoreClient.h"
Functions
void storeSwapInStart (store_client *sc)
static void storeSwapInFileClosed (void *data, int errflag, StoreIOState::Pointer)
Variables
static StoreIOState::STIOCB storeSwapInFileClosed
Function Documentation
storeSwapInFileClosed()
static void storeSwapInFileClosed (void * data, int errflag, StoreIOState::Pointer) static
Definition at line 50 of file store_swapin.cc.
References store_client::_callback, assert, debugs, RefCount< C >::getRaw(), StatCounters::ins, store_client::noteSwapInDone(), store_client::Callback::pending(), statCounter, StatCounters::swap, and store_client::swapin_sio.
storeSwapInStart()
void storeSwapInStart (store_client * sc)
Definition at line 21 of file store_swapin.cc.
References assert, DBG_IMPORTANT, debugs, EBIT_TEST, store_client::entry, ENTRY_VALIDATED, StoreEntry::flags, StoreEntry::getMD5Text(), StoreEntry::hasDisk(), StoreEntry::mem_obj, StoreEntry::mem_status, NOT_IN_MEMORY, storeOpen(), storeSwapInFileClosed, store_client::swapin_sio, and StoreEntry::swapoutFailed().
Referenced by store_client::startSwapin().
Variable Documentation
storeSwapInFileClosed
StoreIOState::STIOCB storeSwapInFileClosed static
Definition at line 18 of file store_swapin.cc.
Referenced by storeSwapInStart().