Squid Web Cache: squid/src/store_log.cc File Reference
store_log.cc File Reference
#include "squid.h"
#include "debug/Messages.h"
#include "format/Token.h"
#include "HttpReply.h"
#include "log/File.h"
#include "MemObject.h"
#include "mgr/Registration.h"
#include "SquidConfig.h"
#include "Store.h"
#include "store_log.h"
Functions
void storeLog (int tag, const StoreEntry *e)
void storeLogRotate (void)
void storeLogClose (void)
static void storeLogRegisterWithCacheManager (void)
void storeLogOpen (void)
void storeLogTagsHist (StoreEntry *e)
Variables
static const char * storeLogTags []
static int storeLogTagsCounts [STORE_LOG_SWAPOUTFAIL+1]
static OBJH storeLogTagsHist
static Logfile * storelog = nullptr
static String str_unknown
Function Documentation
storeLog()
void storeLog (int tag, const StoreEntry * e)
Definition at line 38 of file store_log.cc.
References Http::Message::content_length, HttpReply::content_type, StoreEntry::contentLen(), current_time, HttpReply::date, HttpReply::expires, MemObject::freshestReply(), StoreEntry::getMD5Text(), MemObject::hasUris(), HttpRequestMethod::image(), HttpReply::last_modified, logfileLineEnd(), logfileLineStart(), logfilePrintf(), MemObject::logUri(), StoreEntry::mem_obj, MemObject::method, PRId64, String::size(), HttpReply::sline, SQUIDSBUFPH, SQUIDSBUFPRINT, SQUIDSTRINGPH, SQUIDSTRINGPRINT, Http::StatusLine::status(), storelog, storeLogTags, storeLogTagsCounts, str_unknown, StoreEntry::swap_dirn, StoreEntry::swap_filen, and String::termedBuf().
Referenced by StoreEntry::release(), storeSwapOutFileClosed(), and storeSwapOutStart().
storeLogClose()
void storeLogClose (void)
Definition at line 105 of file store_log.cc.
References logfileClose(), and storelog.
Referenced by mainReconfigureStart(), and SquidShutdown().
storeLogOpen()
void storeLogOpen (void)
Definition at line 123 of file store_log.cc.
References Config, debugs, Important, SquidConfig::Log, logfileOpen(), SquidConfig::store, storelog, and storeLogRegisterWithCacheManager().
Referenced by mainReconfigureFinish(), and storeInit().
storeLogRegisterWithCacheManager()
static void storeLogRegisterWithCacheManager (void) static
Definition at line 116 of file store_log.cc.
References Mgr::RegisterAction(), and storeLogTagsHist.
Referenced by storeLogOpen().
storeLogRotate()
void storeLogRotate (void)
Definition at line 96 of file store_log.cc.
References Config, SquidConfig::Log, logfileRotate(), SquidConfig::rotateNumber, and storelog.
Referenced by mainRotate().
storeLogTagsHist()
void storeLogTagsHist (StoreEntry * e)
Definition at line 136 of file store_log.cc.
References STORE_LOG_SWAPOUTFAIL, storeAppendPrintf(), storeLogTags, and storeLogTagsCounts.
Variable Documentation
storelog
Logfile* storelog = nullptr static
Definition at line 33 of file store_log.cc.
Referenced by storeLog(), storeLogClose(), storeLogOpen(), and storeLogRotate().
storeLogTags
const char* storeLogTags[] static
Initial value:
= {
    "CREATE",
    "SWAPIN",
    "SWAPOUT",
    "RELEASE",
    "SO_FAIL",
}
Definition at line 22 of file store_log.cc.
Referenced by storeLog(), and storeLogTagsHist().
storeLogTagsCounts
int storeLogTagsCounts[STORE_LOG_SWAPOUTFAIL+1] static
Definition at line 30 of file store_log.cc.
Referenced by storeLog(), and storeLogTagsHist().
storeLogTagsHist
OBJH storeLogTagsHist static
Definition at line 31 of file store_log.cc.
Referenced by storeLogRegisterWithCacheManager().
str_unknown
String str_unknown static
Definition at line 35 of file store_log.cc.
Referenced by storeLog().