Squid Web Cache: squid/compat/strerror.c File Reference
strerror.c File Reference
#include "squid.h"
Functions
char * strerror (int ern)
Variables
int sys_nerr
Function Documentation
strerror()
char * strerror (int ern)
Definition at line 22 of file strerror.c.
Referenced by ErrorState::compileLegacyCode(), ErrorState::Dump(), fileIteratorCreate(), main(), main(), processingLoop(), and xstrerr().
Variable Documentation
sys_nerr
int sys_nerr extern