Squid Web Cache: squid/src/sbuf/StringConvert.h File Reference
StringConvert.h File Reference
#include "sbuf/SBuf.h"
#include "SquidString.h"
Functions
SBuf StringToSBuf (const String &s)
create a new SBuf from a String by copying contents
String SBufToString (const SBuf &s)
Function Documentation
SBufToString()
String SBufToString (const SBuf & s) inline
create a new String from a SBuf by copying contents
Deprecated:
Definition at line 26 of file StringConvert.h.
References String::assign(), SBuf::length(), and SBuf::rawContent().
Referenced by ProxyProtocol::Header::getElem(), Mgr::ActionParams::pack(), Mgr::QueryParams::Parse(), CacheManager::ParseHeaders(), ParseParamValue(), CacheManager::ParseUrl(), and Note::printAsNoteDirective().
StringToSBuf()
SBuf StringToSBuf (const String & s) inline
Definition at line 17 of file StringConvert.h.
References String::rawBuf(), and String::size().
Referenced by HttpHeader::addVia(), Format::Format::assemble(), Adaptation::Ecap::XactionRep::blockVirgin(), clientInterpretRequestHeaders(), DelayId::DelayClient(), ACLHTTPHeaderData::match(), Ssl::ErrorDetailFile::parse(), Http::SlowlyParseQuotedString(), Adaptation::Iterator::start(), Adaptation::Iterator::step(), and HttpRequest::storeId().