Squid Web Cache: squid/src/String.cc File Reference
String.cc File Reference
#include "squid.h"
#include "mem/forward.h"
#include "sbuf/SBuf.h"
#include "SquidString.h"
#include <climits>
Functions
static bool nilCmp (const bool thisIsNilOrEmpty, const bool otherIsNilOrEmpty, int &result)
int stringHasWhitespace (const char *s)
int stringHasCntl (const char *s)
char * strwordtok (char *buf, char **t)
const char * checkNullString (const char *p)
Function Documentation
checkNullString()
const char * checkNullString (const char * p)
Definition at line 406 of file String.cc.
nilCmp()
static bool nilCmp (const bool thisIsNilOrEmpty, const bool otherIsNilOrEmpty, int & result) static
compare NULL and empty strings because str*cmp() may fail on NULL strings and because we need to return consistent results for strncmp(count == 0).
Definition at line 227 of file String.cc.
Referenced by String::caseCmp(), String::caseCmp(), String::cmp(), String::cmp(), and String::cmp().
stringHasCntl()
int stringHasCntl (const char * s)
Definition at line 301 of file String.cc.
Referenced by urlCanonicalCleanWithoutRequest().
stringHasWhitespace()
int stringHasWhitespace (const char * s)
Definition at line 294 of file String.cc.
References w_space.
Referenced by AnyP::Uri::parse().
strwordtok()
char * strwordtok (char * buf, char ** t)
Definition at line 321 of file String.cc.
References error(), and xisspace.
Referenced by Helper::Reply::finalize(), Ssl::Helper::Init(), Ssl::CertValidationHelper::Init(), parseManyConfigFiles(), and Helper::Reply::parseResponseKeys().