Squid Web Cache: store_client::Callback Struct Reference
store_client::Callback Struct Reference
#include <StoreClient.h>
Public Member Functions
Callback ()=default
Callback (STCB *, void *)
bool pending () const
Public Attributes
STCB * callback_handler = nullptr
where to deliver the answer
CallbackData cbData
the first STCB callback parameter
CodeContextPointer codeContext
Store client context.
AsyncCall::Pointer notifier
a scheduled asynchronous finishCallback() call (or nil)
Detailed Description
Definition at line 200 of file StoreClient.h.
Constructor & Destructor Documentation
Callback() [1/2]
store_client::Callback::Callback () default
Callback() [2/2]
store_client::Callback::Callback (STCB * function, void * data)
Definition at line 1083 of file store_client.cc.
Member Function Documentation
pending()
bool store_client::Callback::pending () const
Whether the copy() answer is needed/expected (by the client) and has not been computed (by us). False during (asynchronous) answer delivery to the STCB callback_handler.
Definition at line 1078 of file store_client.cc.
References callback_handler, and notifier.
Referenced by store_client::copy(), store_client::doCopy(), store_client::dumpStats(), store_client::fileRead(), StoreEntry::invokeHandlers(), store_client::noteNews(), store_client::noteSwapInDone(), store_client::readBody(), store_client::readHeader(), storeClientCopy2(), and storeSwapInFileClosed().
Member Data Documentation
callback_handler
STCB* store_client::Callback::callback_handler = nullptr
Definition at line 210 of file StoreClient.h.
Referenced by store_client::finishCallback(), store_client::noteNews(), pending(), and storeUnregister().
cbData
CallbackData store_client::Callback::cbData
Definition at line 211 of file StoreClient.h.
Referenced by store_client::finishCallback().
codeContext
CodeContextPointer store_client::Callback::codeContext
Definition at line 212 of file StoreClient.h.
Referenced by StoreEntry::invokeHandlers().
notifier
AsyncCall::Pointer store_client::Callback::notifier
Definition at line 215 of file StoreClient.h.
Referenced by store_client::dumpStats(), store_client::finishCallback(), store_client::noteNews(), pending(), and storeUnregister().
The documentation for this struct was generated from the following files:
squid/src/StoreClient.h
squid/src/store_client.cc