Squid Web Cache: squid/src/tests/stub_libmem.cc File Reference
stub_libmem.cc File Reference
#include "squid.h"
#include "tests/STUB.h"
#include "mem/Allocator.h"
#include "mem/AllocatorProxy.h"
#include "mem/forward.h"
#include "mem/Pool.h"
#include "mem/Stats.h"
Macros
#define STUB_API "mem/libmem.la"
Functions
void * memAllocBuf (size_t net_size, size_t *gross_size)
void * memReallocBuf (void *oldbuf, size_t net_size, size_t *gross_size)
void memFree (void *p, int)
Free a element allocated by memAllocate()
void memFreeBuf (size_t, void *buf)
static void cxx_xfree (void *ptr)
FREE * memFreeBufFunc (size_t)
int memInUse (mem_type) STUB_RETVAL(0) static MemPools tmpMemPools
Macro Definition Documentation
STUB_API
#define STUB_API "mem/libmem.la"
Definition at line 11 of file stub_libmem.cc.
Function Documentation
cxx_xfree()
static void cxx_xfree (void * ptr) static
Definition at line 65 of file stub_libmem.cc.
References xfree.
memAllocBuf()
void * memAllocBuf (size_t net_size, size_t * gross_size)
Definition at line 43 of file stub_libmem.cc.
References xmalloc.
Referenced by Ftp::CtrlChannel::CtrlChannel(), PoolingAllocator< Value >::allocate(), String::allocBuffer(), MemBlob::memAlloc(), Helper::Client::openSessions(), statefulhelper::openSessions(), and Rock::IoState::writeToDisk().
memFree()
void memFree (void * p, int type)
Definition at line 63 of file stub_libmem.cc.
References xfree.
Referenced by Ftp::Gateway::~Gateway(), netdbBinaryExchange(), Ftp::Gateway::parseListing(), and storeKeyFree().
memFreeBuf()
void memFreeBuf (size_t size, void * buf)
Definition at line 64 of file stub_libmem.cc.
References xfree.
Referenced by Ftp::CtrlChannel::~CtrlChannel(), MemBlob::~MemBlob(), Helper::SessionBase::~SessionBase(), MemBuf::clean(), String::clean(), and PoolingAllocator< Value >::deallocate().
memFreeBufFunc()
FREE * memFreeBufFunc (size_t size)
Definition at line 66 of file stub_libmem.cc.
References cxx_xfree(), and myFree().
Referenced by MemBuf::freeFunc(), and Rock::IoState::writeToDisk().
memInUse()
int memInUse (mem_type type)
Definition at line 344 of file old_api.cc.
memReallocBuf()
void * memReallocBuf (void * oldbuf, size_t net_size, size_t * gross_size)
Definition at line 54 of file stub_libmem.cc.
References xrealloc().
Referenced by MemBuf::grow(), and Ftp::Client::handleControlReply().