Squid Web Cache: squid/src/tests/stub_libsslsquid.cc File Reference
stub_libsslsquid.cc File Reference
#include "squid.h"
#include "fatal.h"
#include "sbuf/Algorithms.h"
#include "sbuf/SBuf.h"
#include "tests/STUB.h"
#include "ssl/Config.h"
#include "ssl/context_storage.h"
#include "ssl/ErrorDetail.h"
#include "ssl/support.h"
Macros
#define STUB_API "ssl/libsslsquid.la"
Functions
const char * sslGetUserEmail (SSL *) STUB_RETVAL(nullptr) const char *sslGetUserAttribute(SSL *
const char const char * STUB_RETVAL (nullptr) const char *sslGetCAAttribute(SSL *
Macro Definition Documentation
STUB_API
#define STUB_API "ssl/libsslsquid.la"
Definition at line 19 of file stub_libsslsquid.cc.
Function Documentation
sslGetUserEmail()
const char * sslGetUserEmail (SSL *) const
STUB_RETVAL()
size_t HttpReply *STUB StoreEntry const KeyScope const HttpRequestMethod const KeyScope const char const RequestFlags const HttpRequestMethod const char const HttpRequestMethod & STUB_RETVAL (nullptr) const
Definition at line 58 of file stub_libsslsquid.cc.
References Ssl::asn1timeToString(), Ssl::BumpModeStr, Ssl::GenerateSslContext(), Ssl::GenerateSslContextUsingPkeyAndCertFromMemory(), Ssl::generateUntrustedCert(), Ssl::GetX509PEM, Ssl::HasMatchingSubjectName(), Ssl::HasSubjectName(), Ssl::setClientSNI(), STUB, STUB_RETVAL, and Ssl::verifySslCertificate().