Squid Web Cache: squid/src/tests/stub_liblog.cc File Reference
stub_liblog.cc File Reference
#include "squid.h"
#include "fde.h"
#include "log/File.h"
#include "tests/STUB.h"
#include "AccessLogEntry.h"
#include "log/access_log.h"
#include "log/Config.h"
#include "log/FormattedLog.h"
#include "log/Formats.h"
#include "log/ModDaemon.h"
#include "log/ModStdio.h"
#include "log/ModSyslog.h"
#include "log/ModUdp.h"
#include "log/TcpLogger.h"
Macros
#define STUB_API "log/liblog.la"
Functions
Logfile * logfileOpen (const char *, size_t, int) STUB_RETVAL(nullptr) void logfileClose(Logfile *) STUB void logfileRotate(Logfile *
Logfile int16_t STUB void logfileWrite (Logfile *, const char *, size_t) STUB void logfileFlush(Logfile *) STUB void logfilePrintf(Logfile *
Logfile int16_t STUB void const char STUB void logfileLineStart (Logfile *) STUB void logfileLineEnd(Logfile *) STUB namespace Log
int logfile_mod_daemon_open (Logfile *, const char *, size_t, int) STUB_RETVAL(0) int logfile_mod_stdio_open(Logfile *
int const char int STUB_RETVAL (0) int logfile_mod_syslog_open(Logfile *
Variables
int const char size_t
Macro Definition Documentation
STUB_API
#define STUB_API "log/liblog.la"
Definition at line 13 of file stub_liblog.cc.
Function Documentation
logfile_mod_daemon_open()
int logfile_mod_daemon_open (Logfile * lf, const char * path, size_t bufsz, int fatal_flag)
Definition at line 16 of file ModDaemon.cc.
logfileLineStart()
Logfile int16_t STUB void const char STUB void logfileLineStart (Logfile * lf)
Definition at line 61 of file stub_liblog.cc.
References Log::Format::HttpdCombined(), Log::Format::HttpdCommon(), Log::Format::SquidCustom(), Log::Format::SquidIcap(), Log::Format::SquidNative(), Log::Format::SquidReferer(), Log::Format::SquidUserAgent(), and STUB.
logfileOpen()
Logfile * logfileOpen (const char * path, size_t bufsz, int fatal_flag)
Definition at line 66 of file File.cc.
logfileWrite()
Logfile int16_t STUB void logfileWrite (Logfile * lf, const char * buf, size_t len)
Definition at line 69 of file File.cc.
STUB_RETVAL()
int const char int STUB_RETVAL (0)
Definition at line 89 of file stub_liblog.cc.
Variable Documentation
size_t
int const char int const char int const char size_t
Definition at line 83 of file stub_liblog.cc.
Referenced by MemBuf::grow(), main(), MainSafe(), rfc1035NameUnpack(), TestEvent::testDump(), Adaptation::Icap::ModXact::writePreviewBody(), and Adaptation::Icap::ModXact::writePrimeBody().