Squid Web Cache: squid/src/tests/stub_tools.cc File Reference
stub_tools.cc File Reference
#include "squid.h"
#include "src/tools.h"
#include "tests/STUB.h"
Macros
#define STUB_API "tools.cc"
Functions
void releaseServerSockets (void) STUB_NOP void dumpMallocStats(void) STUB void squid_getrusage(struct rusage *) STUB double rusage_cputime(struct rusage *) STUB_RETVAL(0) int rusage_maxrss(struct rusage *) STUB_RETVAL(0) int rusage_pagefaults(struct rusage *) STUB_RETVAL(0) void PrintRusage(void) STUB void death(int) STUB void BroadcastSignalIfAny(int &) STUB void sigusr2_handle(int) STUB void debug_trap(const char *) STUB void sig_child(int) STUB const char *getMyHostname(void) STUB_RETVAL(nullptr) const char *uniqueHostname(void) STUB_RETVAL(nullptr) void leave_suid(void) STUB_NOP void enter_suid(void) STUB void no_suid(void) STUB bool IamMasterProcess()
bool IamWorkerProcess ()
whether the current process handles HTTP transactions and such
bool IamDiskProcess () STUB_RETVAL_NOP(false) bool InDaemonMode() STUB_RETVAL_NOP(false) bool UsingSmp() STUB_RETVAL_NOP(false) bool IamCoordinatorProcess() STUB_RETVAL(false) bool IamPrimaryProcess() STUB_RETVAL(false) int NumberOfKids() STUB_RETVAL(0) void setMaxFD(void) STUB void setSystemLimits(void) STUB void squid_signal(int
whether the current process is dedicated to managing a cache_dir
bool SIGHDLR int STUB void logsFlush (void) STUB void debugObj(int
bool SIGHDLR int STUB void const char void ObjPackMethod STUB void parseEtcHosts (void) STUB int getMyPort(void) STUB_RETVAL(0) void setUmask(mode_t) STUB void strwordquote(MemBuf *
bool SIGHDLR int STUB void const char void ObjPackMethod STUB void const char *STUB void keepCapabilities (void) STUB pid_t WaitForOnePid(pid_t
Variables
int DebugSignal = -1
SBuf service_name (APP_SHORTNAME)
bool SIGHDLR int STUB void int
Macro Definition Documentation
STUB_API
#define STUB_API "tools.cc"
Definition at line 13 of file stub_tools.cc.
Function Documentation
IamDiskProcess()
bool IamDiskProcess ()
Referenced by IpcIoFile::close(), Rock::SwapDir::create(), Rock::SwapDir::doReportStat(), IpcIoFile::HandleMessagesAtStart(), IpcIoFile::HandleNotification(), Rock::Rebuild::IsResponsible(), IpcIoFile::open(), and SquidMain().
IamWorkerProcess()
bool IamWorkerProcess ()
Definition at line 47 of file stub_tools.cc.
Referenced by Store::Disk::active(), Ipc::Mem::Segment::Enabled(), htcpClosePorts(), htcpOpenPorts(), CollapsedForwarding::Init(), Store::Controller::init(), initializeSessionCache(), IpcIoFile::open(), Fs::Ufs::UFSSwapDir::openLog(), peerDNSConfigure(), serverConnectionsClose(), serverConnectionsOpen(), snmpClosePorts(), snmpConstructReponse(), snmpInit(), snmpOpenPorts(), SquidMain(), CacheManager::start(), Fs::Ufs::UFSSwapDir::unlinkdUseful(), and Ipc::Mem::RegisteredRunner::useConfig().
keepCapabilities()
bool SIGHDLR int STUB void const char void ObjPackMethod STUB void const char *STUB void keepCapabilities (void)
Referenced by setEffectiveUser().
logsFlush()
bool SIGHDLR int STUB void logsFlush (void)
Referenced by ipcCreate().
parseEtcHosts()
bool SIGHDLR int STUB void const char void ObjPackMethod STUB void parseEtcHosts (void)
Referenced by mainInitialize(), and mainReconfigureFinish().
releaseServerSockets()
void releaseServerSockets (void) const &
Definition at line 18 of file stub_tools.cc.
Referenced by fatal(), fatal_dump(), and SquidShutdown().
Variable Documentation
DebugSignal
int DebugSignal = -1
Definition at line 16 of file stub_tools.cc.
Referenced by masterCheckAndBroadcastSignals(), and masterSignaled().
int
bool SIGHDLR int STUB void int
Definition at line 66 of file stub_tools.cc.
service_name
SBuf service_name(APP_SHORTNAME) (APP_SHORTNAME)
Referenced by DumpInfo(), mainHandleCommandLineOption(), mainInitialize(), Instance::NamePrefix(), ProcessMacros(), WIN32_InstallService(), WIN32_RemoveService(), WIN32_sendSignal(), WIN32_SetServiceCommandLine(), WIN32_StartService(), and WIN32_Subsystem_Init().