Squid Web Cache: squid/src/tests/stub_libtime.cc File Reference
stub_libtime.cc File Reference
#include "squid.h"
#include "tests/STUB.h"
#include "time/Engine.h"
#include "time/gadgets.h"
Macros
#define STUB_API "time/libtime.la"
Functions
time_t getCurrentTime () STUB_RETVAL(0) int tvSubUsec(struct timeval
time_t struct timeval STUB_RETVAL (0) double tvSubDsec(struct timeval
time_t struct timeval struct timeval STUB_RETVAL (0.0) int tvSubMsec(struct timeval
time_t struct timeval struct timeval struct timeval STUB_RETVAL (0) void tvSub(struct timeval &
time_t struct timeval struct timeval struct timeval struct timeval const struct timeval const &STUB void tvAdd (struct timeval &, struct timeval const &, struct timeval const &) STUB void tvAssignAdd(struct timeval &
time_t struct timeval struct timeval struct timeval struct timeval const struct timeval const &STUB void struct timeval const &STUB std::ostream & operator<< (std::ostream &os, const timeval &) STUB_RETVAL(os) namespace Time
prints <seconds>.<microseconds>
Variables
double current_dtime = 0.0
the current UNIX time in seconds (with microsecond precision)
time_t squid_curtime = 0
the current UNIX time in seconds
Macro Definition Documentation
STUB_API
#define STUB_API "time/libtime.la"
Definition at line 11 of file stub_libtime.cc.
Function Documentation
getCurrentTime()
time_t getCurrentTime ()
Update squid_curtime (also current_time, and current_dtime)
Returns
new value of squid_curtime
Referenced by BandwidthBucket::BandwidthBucket(), DebugMessageHeader::DebugMessageHeader(), IcmpSquid::Close(), Helper::SessionBase::closePipesSafely(), Helper::SessionBase::closeWritePipeSafely(), comm_check_incoming_poll_handlers(), comm_check_incoming_select_handlers(), Fs::Ufs::UFSSwapDir::createDirectory(), IpcIoFile::DiskerHandleRequests(), Comm::DoSelect(), DelayPools::Init(), ipc_thread_1(), Rock::Rebuild::loadingSteps(), main(), netdbReloadState(), netdbSaveState(), IcmpPinger::Open(), Helper::Client::openSessions(), statefulhelper::openSessions(), Fs::Ufs::RebuildState::rebuildStep(), SquidMain(), storeDirWriteCleanLogs(), Time::Engine::tick(), unlinkdClose(), Rock::Rebuild::validationSteps(), and watch_child().
operator<<()
time_t struct timeval struct timeval struct timeval struct timeval const struct timeval const &STUB void struct timeval const &STUB std::ostream & operator<< (std::ostream & os, const timeval &)
Definition at line 28 of file stub_libtime.cc.
References STUB_RETVAL.
STUB_RETVAL() [1/3]
time_t struct timeval STUB_RETVAL (0)
STUB_RETVAL() [2/3]
time_t struct timeval struct timeval struct timeval STUB_RETVAL (0) &
STUB_RETVAL() [3/3]
time_t struct timeval struct timeval STUB_RETVAL (0. 0)
tvAdd()
time_t struct timeval struct timeval struct timeval struct timeval const struct timeval const &STUB void tvAdd (struct timeval & , struct timeval const & , struct timeval const &) &
Referenced by ping_data::deadline().
Variable Documentation
current_dtime
double current_dtime = 0.0
Definition at line 19 of file stub_libtime.cc.
Referenced by BandwidthBucket::BandwidthBucket(), FadingCounter::clear(), FadingCounter::count(), EventScheduler::dump(), DumpMallocStatistics(), HappyConnOpener::maybeOpenPrimeConnection(), SpareAllowanceGiver::recordAllowance(), BandwidthBucket::refillBucket(), Mem::Report(), EventScheduler::schedule(), ClientInfo::setWriteLimiter(), HappyOrderEnforcer::startedWaiting(), and EventScheduler::timeRemaining().
squid_curtime
time_t squid_curtime = 0
Definition at line 20 of file stub_libtime.cc.