Squid Web Cache: squid/src/tests/stub_store.cc File Reference
stub_store.cc File Reference
#include "squid.h"
#include "RequestFlags.h"
#include "tests/STUB.h"
#include "RemovalPolicy.h"
#include "Store.h"
Macros
#define STUB_API "store.cc"
Functions
RemovalPolicy * createRemovalPolicy (RemovalPolicySettings *) STUB_RETVAL(nullptr) StoreIoStats store_io_stats
size_t storeEntryInUse () STUB_RETVAL(0) void storeEntryReplaceObject(StoreEntry *
size_t HttpReply *STUB StoreEntry * storeGetPublic (const char *, const HttpRequestMethod &) STUB_RETVAL(nullptr) StoreEntry *storeGetPublicByRequest(HttpRequest *
size_t HttpReply *STUB StoreEntry const KeyScope STUB_RETVAL (nullptr) StoreEntry *storeGetPublicByRequestMethod(HttpRequest *
size_t HttpReply *STUB StoreEntry const KeyScope const HttpRequestMethod const KeyScope const char const RequestFlags const HttpRequestMethod const char const HttpRequestMethod time_t STUB_RETVAL (0) void storeAppendPrintf(StoreEntry *
size_t HttpReply *STUB StoreEntry const KeyScope const HttpRequestMethod const KeyScope const char const RequestFlags const HttpRequestMethod const char const HttpRequestMethod time_t const char STUB void storeAppendVPrintf (StoreEntry *, const char *, va_list) STUB int storeTooManyDiskFilesOpen(void) STUB_RETVAL(0) void storeHeapPositionUpdate(StoreEntry *
size_t HttpReply *STUB StoreEntry const KeyScope const HttpRequestMethod const KeyScope const char const RequestFlags const HttpRequestMethod const char const HttpRequestMethod time_t const char STUB void SwapDir *STUB void storeSwapFileNumberSet (StoreEntry *, sfileno) STUB void storeFsInit(void) STUB void storeFsDone(void) STUB void storeReplAdd(const char *
Variables
const char * storeStatusStr [] = { }
const char * pingStatusStr [] = { }
const char * memStatusStr [] = { }
const char * swapStatusStr [] = { }
Macro Definition Documentation
STUB_API
#define STUB_API "store.cc"
Definition at line 12 of file stub_store.cc.
Function Documentation
createRemovalPolicy()
RemovalPolicy * createRemovalPolicy (RemovalPolicySettings * settings)
Definition at line 1671 of file store.cc.
Referenced by storeInit().
storeAppendVPrintf()
size_t HttpReply *STUB StoreEntry const KeyScope const HttpRequestMethod const KeyScope const char const RequestFlags const HttpRequestMethod const char const HttpRequestMethod time_t const char STUB void storeAppendVPrintf (StoreEntry * e, const char * fmt, va_list ap)
Definition at line 433 of file store.cc.
storeEntryInUse()
size_t storeEntryInUse ()
storeGetPublic()
size_t HttpReply *STUB StoreEntry * storeGetPublic (const char * uri, const HttpRequestMethod & method)
Definition at line 404 of file store.cc.
References assert, debugs, StoreEntry::destroyMemObject(), Store::Disk::disconnect(), StoreEntry::disk(), StoreEntry::hasDisk(), StoreEntry::hashDelete(), and hash_link::key.
Referenced by StoreEntry::adjustVary().
storeSwapFileNumberSet()
size_t HttpReply *STUB StoreEntry const KeyScope const HttpRequestMethod const KeyScope const char const RequestFlags const HttpRequestMethod const char const HttpRequestMethod time_t const char STUB void SwapDir *STUB void storeSwapFileNumberSet (StoreEntry * , sfileno) const
STUB_RETVAL() [1/2]
size_t HttpReply *STUB StoreEntry const KeyScope const HttpRequestMethod const KeyScope const char const RequestFlags const HttpRequestMethod const char const HttpRequestMethod time_t STUB_RETVAL (0)
STUB_RETVAL() [2/2]
size_t HttpReply *STUB StoreEntry const KeyScope STUB_RETVAL (nullptr)
Variable Documentation
memStatusStr
const char* memStatusStr[] = { }
Definition at line 17 of file stub_store.cc.
Referenced by describeStatuses().
pingStatusStr
const char* pingStatusStr[] = { }
Definition at line 16 of file stub_store.cc.
Referenced by describeStatuses().
storeStatusStr
const char* storeStatusStr[] = { }
Definition at line 15 of file stub_store.cc.
Referenced by describeStatuses().
swapStatusStr
const char* swapStatusStr[] = { }
Definition at line 18 of file stub_store.cc.
Referenced by StoreEntry::attachToDisk(), and describeStatuses().