Squid Web Cache: squid/lib/ntlmauth/support_bits.cci File Reference
support_bits.cci File Reference
#include <cstring>
Macros
#define SQUID_LIBNTLMAUTH_SUPPORT_BITS_CCI
Functions
void uc (char *string)
void lc (char *string)
void hex_dump (unsigned char *data, int size)
Macro Definition Documentation
SQUID_LIBNTLMAUTH_SUPPORT_BITS_CCI
#define SQUID_LIBNTLMAUTH_SUPPORT_BITS_CCI
Definition at line 10 of file support_bits.cci.
Function Documentation
hex_dump()
void hex_dump (unsigned char * data, int size) inline
Definition at line 43 of file support_bits.cci.
References debug_enabled, hex_dump(), lc(), size, uc(), and xisalnum.
Referenced by hex_dump(), main(), and manage_request().
lc()
void lc (char * string) inline
Definition at line 33 of file support_bits.cci.
References xtolower.
Referenced by hex_dump(), main(), and manage_request().
uc()
void uc (char * string) inline
Definition at line 22 of file support_bits.cci.
References xtoupper.
Referenced by hex_dump().