Squid Web Cache: squid/src/ssl/support.cc File Reference
support.cc File Reference
#include "squid.h"
#include "acl/FilledChecklist.h"
#include "anyp/Host.h"
#include "anyp/PortCfg.h"
#include "anyp/Uri.h"
#include "fatal.h"
#include "fd.h"
#include "fde.h"
#include "globals.h"
#include "ip/Address.h"
#include "ipc/MemMap.h"
#include "security/CertError.h"
#include "security/Certificate.h"
#include "security/ErrorDetail.h"
#include "security/Session.h"
#include "SquidConfig.h"
#include "ssl/bio.h"
#include "ssl/Config.h"
#include "ssl/ErrorDetail.h"
#include "ssl/gadgets.h"
#include "ssl/support.h"
#include <cerrno>
Classes
class Ssl::OneNameMatcher
GeneralNameMatcher for matching a single AnyP::Host given at construction time.
Namespaces
namespace Ssl
Functions
static CertsIndexedList & Ssl::SquidUntrustedCerts ()
static void ssl_ask_password (SSL_CTX *context, const char *prompt)
static std::optional< AnyP::Host > ParseSubjectAltName (const GENERAL_NAME &san)
static int ssl_verify_cb (int ok, X509_STORE_CTX *ctx)
static int VerifyCtxCertificates (X509_STORE_CTX *ctx, STACK_OF(X509) *extraCerts)
static int ssl_dupAclChecklist (CRYPTO_EX_DATA *, CRYPTO_EX_DATA *, void *, int, long, void *)
static void ssl_freeAclChecklist (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
static void ssl_free_ErrorDetail (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
static void ssl_free_SslErrors (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
static void ssl_free_int (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
static void ssl_free_CertChain (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
static void ssl_free_X509 (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
static void ssl_free_SBuf (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
static void ssl_free_VerifyCallbackParameters (void *, void *ptr, CRYPTO_EX_DATA *, int, long, void *)
"free" function for the ssl_ex_index_verify_callback_parameters entry
static const char * ssl_get_attribute (X509_NAME *name, const char *attribute_name)
const char * sslGetUserAttribute (SSL *ssl, const char *attribute_name)
const char * sslGetCAAttribute (SSL *ssl, const char *attribute_name)
const char * sslGetUserEmail (SSL *ssl)
SBuf sslGetUserCertificatePEM (SSL *ssl)
SBuf sslGetUserCertificateChainPEM (SSL *ssl)
static X509 * findCertIssuerFast (Ssl::CertsIndexedList &list, X509 *cert)
static X509 * sk_x509_findIssuer (const STACK_OF(X509) *sk, X509 *cert)
slowly find the issuer certificate of a given cert using linear search
static X509 * findIssuerInCaDb (X509 *cert, const Security::ContextPointer &connContext)
static void completeIssuers (X509_STORE_CTX *ctx, STACK_OF(X509) &untrustedCerts)
add missing issuer certificates to untrustedCerts
static int untrustedToStoreCtx_cb (X509_STORE_CTX *ctx, void *)
static int bio_sbuf_create (BIO *bio)
static int bio_sbuf_destroy (BIO *bio)
static int bio_sbuf_write (BIO *bio, const char *data, int len)
static int bio_sbuf_puts (BIO *bio, const char *data)
static long bio_sbuf_ctrl (BIO *bio, int cmd, long, void *)
Variables
static int ssl_ex_index_verify_callback_parameters = -1
Function Documentation
bio_sbuf_create()
static int bio_sbuf_create (BIO * bio) static
Definition at line 1513 of file support.cc.
References BIO_set_data(), and BIO_set_init().
Referenced by Ssl::BIO_new_SBuf().
bio_sbuf_ctrl()
static long bio_sbuf_ctrl (BIO * bio, int cmd, long , void *) static
Definition at line 1548 of file support.cc.
References BIO_get_data(), and SBuf::clear().
Referenced by Ssl::BIO_new_SBuf().
bio_sbuf_destroy()
static int bio_sbuf_destroy (BIO * bio) static
Definition at line 1521 of file support.cc.
Referenced by Ssl::BIO_new_SBuf().
bio_sbuf_puts()
static int bio_sbuf_puts (BIO * bio, const char * data) static
Definition at line 1538 of file support.cc.
References SBuf::append(), BIO_get_data(), and SBuf::length().
Referenced by Ssl::BIO_new_SBuf().
bio_sbuf_write()
static int bio_sbuf_write (BIO * bio, const char * data, int len) static
Definition at line 1529 of file support.cc.
References SBuf::append(), and BIO_get_data().
Referenced by Ssl::BIO_new_SBuf().
completeIssuers()
static void completeIssuers (X509_STORE_CTX * ctx, STACK_OF(X509) & untrustedCerts) static
Definition at line 1352 of file support.cc.
References debugs, Ssl::findIssuerCertificate(), Security::LockingPointer< T, UnLocker, Locker >::get(), Security::LockingPointer< T, UnLocker, Locker >::resetAndLock(), Security::SelfSigned(), size, Ssl::SquidUntrustedCerts(), X509_STORE_CTX_get0_cert(), and X509_VERIFY_PARAM_get_depth().
Referenced by VerifyCtxCertificates().
findCertIssuerFast()
static X509 * findCertIssuerFast (Ssl::CertsIndexedList & list, X509 * cert) static
quickly find the issuer certificate of a certificate cert in the Ssl::CertsIndexedList list
Definition at line 1235 of file support.cc.
References Security::IssuedBy(), and Security::IssuerName().
Referenced by Ssl::findIssuerCertificate().
findIssuerInCaDb()
static X509 * findIssuerInCaDb (X509 * cert, const Security::ContextPointer & connContext) static
finds issuer of a given certificate in CA store of the given connContext
Returns
the cert issuer (after increasing its reference count) or nil
Definition at line 1270 of file support.cc.
References assert, DBG_IMPORTANT, debugs, and Security::ErrorString().
Referenced by Ssl::findIssuerCertificate().
ParseSubjectAltName()
static std::optional< AnyP::Host > ParseSubjectAltName (const GENERAL_NAME & san) static
Definition at line 263 of file support.cc.
References Ssl::AsnToSBuf(), Assure, debugs, AnyP::Host::ParseIp(), and AnyP::Host::ParseWildDomainName().
Referenced by Ssl::HasMatchingSubjectName().
sk_x509_findIssuer()
static X509 * sk_x509_findIssuer (const STACK_OF(X509) * sk, X509 * cert) static
Definition at line 1253 of file support.cc.
References Security::IssuedBy().
Referenced by Ssl::findIssuerCertificate().
ssl_dupAclChecklist()
static int ssl_dupAclChecklist (CRYPTO_EX_DATA * , CRYPTO_EX_DATA * , void * , int , long , void *) static
Definition at line 665 of file support.cc.
References assert.
Referenced by Ssl::Initialize().
ssl_free_ErrorDetail()
static void ssl_free_ErrorDetail (void * , void * ptr, CRYPTO_EX_DATA * , int , long , void *) static
Definition at line 685 of file support.cc.
Referenced by Ssl::Initialize().
ssl_free_int()
static void ssl_free_int (void * , void * ptr, CRYPTO_EX_DATA * , int , long , void *) static
Definition at line 702 of file support.cc.
Referenced by Ssl::Initialize().
ssl_free_SBuf()
static void ssl_free_SBuf (void * , void * ptr, CRYPTO_EX_DATA * , int , long , void *) static
Definition at line 731 of file support.cc.
Referenced by Ssl::Initialize().
ssl_free_SslErrors()
static void ssl_free_SslErrors (void * , void * ptr, CRYPTO_EX_DATA * , int , long , void *) static
Definition at line 693 of file support.cc.
Referenced by Ssl::Initialize().
ssl_free_VerifyCallbackParameters()
static void ssl_free_VerifyCallbackParameters (void * , void * ptr, CRYPTO_EX_DATA * , int , long , void *) static
Definition at line 740 of file support.cc.
Referenced by Ssl::Initialize().
ssl_free_X509()
static void ssl_free_X509 (void * , void * ptr, CRYPTO_EX_DATA * , int , long , void *) static
Definition at line 722 of file support.cc.
Referenced by Ssl::Initialize().
ssl_freeAclChecklist()
static void ssl_freeAclChecklist (void * , void * ptr, CRYPTO_EX_DATA * , int , long , void *) static
Definition at line 677 of file support.cc.
Referenced by Ssl::Initialize().
ssl_verify_cb()
static int ssl_verify_cb (int ok, X509_STORE_CTX * ctx) static
adjusts OpenSSL validation results for each verified certificate in ctx OpenSSL "verify_callback function" (OpenSSL_vcb_disambiguation)
Definition at line 346 of file support.cc.
References Acl::Answer::allowed(), DBG_IMPORTANT, debugs, ACLChecklist::fastCheck(), Filled(), Ssl::VerifyCallbackParameters::Find(), Security::LockingPointer< T, UnLocker, Locker >::get(), Ssl::GetErrorDescr(), Ssl::HasSubjectName(), Ssl::ParseAsSimpleDomainNameOrIp(), CbDataList< C >::push_back_unique(), Security::LockingPointer< T, UnLocker, Locker >::reset(), Security::LockingPointer< T, UnLocker, Locker >::resetAndLock(), server, ACLFilledChecklist::serverCert, SQUID_CERT_VALIDATION_ITERATION_MAX, SQUID_X509_V_ERR_CERT_CHANGE, SQUID_X509_V_ERR_DOMAIN_MISMATCH, SQUID_X509_V_ERR_INFINITE_VALIDATION, ssl_ctx_ex_index_dont_verify_domain, ssl_ex_index_cert_error_check, ssl_ex_index_server, ssl_ex_index_ssl_cert_chain, ssl_ex_index_ssl_error_detail, ssl_ex_index_ssl_errors, ssl_ex_index_ssl_peeked_cert, ssl_ex_index_ssl_validation_counter, ACLFilledChecklist::sslErrors, STACK_OF(), Ssl::TheConfig, and X509_STORE_CTX_get0_cert().
Referenced by Ssl::ConfigurePeerVerification().
untrustedToStoreCtx_cb()
static int untrustedToStoreCtx_cb (X509_STORE_CTX * ctx, void *) static
Validates certificates while consulting sslproxy_foreign_intermediate_certs but without using any dynamically downloaded intermediate certificates. OpenSSL "verification callback function" (OpenSSL_vcb_disambiguation)
Definition at line 1434 of file support.cc.
References debugs, and VerifyCtxCertificates().
Referenced by Ssl::useSquidUntrusted().
VerifyCtxCertificates()
static int VerifyCtxCertificates (X509_STORE_CTX * ctx, STACK_OF(X509) * extraCerts) static
Validates certificates while consulting sslproxy_foreign_intermediate_certs and, optionally, the given extra certificates.
Returns
whatever OpenSSL X509_verify_cert() returns
Definition at line 1386 of file support.cc.
References completeIssuers(), size, Ssl::SquidUntrustedCerts(), STACK_OF(), and X509_STORE_CTX_set0_untrusted.
Referenced by untrustedToStoreCtx_cb(), and Ssl::VerifyConnCertificates().
Variable Documentation
ssl_ex_index_verify_callback_parameters
int ssl_ex_index_verify_callback_parameters = -1 static
Definition at line 42 of file support.cc.
Referenced by Ssl::VerifyCallbackParameters::Find(), Ssl::Initialize(), and Ssl::VerifyCallbackParameters::New().