Squid Web Cache: squid/test-suite/syntheticoperators.cc File Reference
syntheticoperators.cc File Reference
#include "squid.h"
#include "mem_node.h"
#include "stmem.h"
#include <iostream>
Classes
class HasExplicit
class SyntheticOwnsExplicit
Functions
static void CheckHasExplicitWorks ()
static void CheckSyntheticWorks ()
int main (int, char *[])
Function Documentation
CheckHasExplicitWorks()
static void CheckHasExplicitWorks () static
Definition at line 95 of file syntheticoperators.cc.
References assert, HasExplicit::Assignments(), HasExplicit::Instances(), one, three, and two.
Referenced by main().
CheckSyntheticWorks()
static void CheckSyntheticWorks () static
Definition at line 127 of file syntheticoperators.cc.
References assert, HasExplicit::Assignments(), HasExplicit::Instances(), one, three, and two.
Referenced by main().
main()
int main (int , char * [])
Definition at line 154 of file syntheticoperators.cc.
References CheckHasExplicitWorks(), and CheckSyntheticWorks().