Squid Web Cache: squid/compat/tempnam.c File Reference
tempnam.c File Reference
#include "squid.h"
#include "compat/tempnam.h"
Macros
#define _tmp "/tmp/"
#define lengthof_tmp 5
#define LONG_BIT (CHAR_BIT * 4) /* assume sizeof(long) == 4 */
#define L_tmpmin (lengthof_tmp + 5) /* 5 chars for pid. */
#define TMP_BASE 16
Functions
static char * _tmpnam (void)
char * tempnam (const char *dir, const char *pfx)
Macro Definition Documentation
_tmp
#define _tmp "/tmp/"
Definition at line 34 of file tempnam.c.
L_tmpmin
#define L_tmpmin (lengthof_tmp + 5) /* 5 chars for pid. */
Definition at line 41 of file tempnam.c.
lengthof_tmp
#define lengthof_tmp 5
Definition at line 35 of file tempnam.c.
LONG_BIT
#define LONG_BIT (CHAR_BIT * 4) /* assume sizeof(long) == 4 */
Definition at line 38 of file tempnam.c.
TMP_BASE
#define TMP_BASE 16
Function Documentation
_tmpnam()
static char * _tmpnam (void) static
Definition at line 58 of file tempnam.c.
References _tmp, int, L_tmpmin, lengthof_tmp, NULL, pid, and TMP_BASE.
Referenced by tempnam().
tempnam()
char * tempnam (const char * dir, const char * pfx)
Definition at line 119 of file tempnam.c.
References _tmpnam().
Referenced by mail_warranty().