Squid Web Cache: squid/src/tests/testIoManip.cc File Reference
testIoManip.cc File Reference
#include "squid.h"
#include "base/IoManip.h"
#include "compat/cppunit.h"
#include "unitTestMain.h"
#include <cstdint>
#include <limits>
#include <sstream>
Classes
class TestIoManip
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestIoManip)
static void resetStream (std::ostringstream &dirty)
resets the given stream, including any formatting
template<typename Integer >
static std::string toStdString (const AsHex< Integer > &manipulator)
returns the result of printing the given manipulator
int main (int argc, char *argv[])
Function Documentation
CPPUNIT_TEST_SUITE_REGISTRATION()
CPPUNIT_TEST_SUITE_REGISTRATION (TestIoManip)
main()
int main (int argc, char * argv[])
Definition at line 187 of file testIoManip.cc.
References TestProgram::run().
resetStream()
static void resetStream (std::ostringstream & dirty) static
Definition at line 34 of file testIoManip.cc.
Referenced by TestIoManip::testAsHex().
toStdString()
template<typename Integer > static std::string toStdString (const AsHex< Integer > & manipulator) static
Definition at line 43 of file testIoManip.cc.
Referenced by TestIoManip::testAsHex().