Squid Web Cache: squid/src/tests/testAuth.cc File Reference
testAuth.cc File Reference
#include "squid.h"
#include "auth/Config.h"
#include "auth/Gadgets.h"
#include "auth/UserRequest.h"
#include "ConfigParser.h"
#include "testAuth.h"
#include "unitTestMain.h"
#include <iostream>
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestAuth)
CPPUNIT_TEST_SUITE_REGISTRATION (TestAuthConfig)
CPPUNIT_TEST_SUITE_REGISTRATION (TestAuthUserRequest)
static char const * find_proxy_auth (char const *type)
static Auth::Config * getConfig (char const *type_str)
static void setup_scheme (Auth::Config *scheme, char const **params, unsigned param_count)
static void fake_auth_setup ()
int main (int argc, char *argv[])
Variables
char const * stub_config
Function Documentation
CPPUNIT_TEST_SUITE_REGISTRATION() [1/3]
CPPUNIT_TEST_SUITE_REGISTRATION (TestAuth)
CPPUNIT_TEST_SUITE_REGISTRATION() [2/3]
CPPUNIT_TEST_SUITE_REGISTRATION (TestAuthConfig)
CPPUNIT_TEST_SUITE_REGISTRATION() [3/3]
CPPUNIT_TEST_SUITE_REGISTRATION (TestAuthUserRequest)
fake_auth_setup()
static void fake_auth_setup () static
Definition at line 108 of file testAuth.cc.
References authenticateInit(), getConfig(), Mem::Init(), NULL, setup_scheme(), and Auth::TheConfig.
Referenced by TestAuthConfig::create(), and TestAuthUserRequest::scheme().
find_proxy_auth()
static char const * find_proxy_auth (char const * type) static
Definition at line 50 of file testAuth.cc.
Referenced by TestAuthConfig::create(), and TestAuthUserRequest::scheme().
getConfig()
static Auth::Config * getConfig (char const * type_str) static
Definition at line 69 of file testAuth.cc.
References assert, Auth::Scheme::Find(), NULL, and Auth::TheConfig.
Referenced by fake_auth_setup().
main()
int main (int argc, char * argv[])
Definition at line 291 of file testAuth.cc.
References TestProgram::run().
setup_scheme()
static void setup_scheme (Auth::Config * scheme, char const ** params, unsigned param_count) static
Definition at line 94 of file testAuth.cc.
References ConfigParser::SetCfgLine(), Auth::TheConfig, w_space, and xstrdup.
Referenced by fake_auth_setup().
Variable Documentation
stub_config
char const* stub_config
Initial value:
="auth_param digest program /home/robertc/install/squid/libexec/digest_pw_auth /home/robertc/install/squid/etc/digest.pwd\n"
                         "auth_param digest children 5\n"
                         "auth_param digest realm Squid proxy-caching web server\n"
                         "auth_param digest nonce_garbage_interval 5 minutes\n"
                         "auth_param digest nonce_max_duration 30 minutes\n"
                         "auth_param digest nonce_max_count 50\n"
Definition at line 41 of file testAuth.cc.