Squid Web Cache: squid/src/tests/testSBuf.cc File Reference
testSBuf.cc File Reference
#include "squid.h"
#include "base/CharacterSet.h"
#include "base/TextException.h"
#include "compat/cppunit.h"
#include "event.h"
#include "HttpReply.h"
#include "MemObject.h"
#include "sbuf/Algorithms.h"
#include "sbuf/SBuf.h"
#include "sbuf/Stream.h"
#include "tests/SBufFindTest.h"
#include "unitTestMain.h"
#include <algorithm>
#include <iostream>
#include <stdexcept>
#include <unordered_map>
Classes
class TestSBuf
class SBufSubstrAutoTest
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestSBuf)
void eventAdd (const char *, EVH *, void *, double, int, bool)
static int sign (int v)
static void testComparisonStdFull (const char *left, const char *right)
static void testComparisonStdN (const char *left, const char *right, const size_t n)
static void testComparisonStdOneWay (const char *left, const char *right)
static void testComparisonStd (const char *s1, const char *s2)
int main (int argc, char *argv[])
Variables
static const char fox [] = "The quick brown fox jumped over the lazy dog"
static const char fox1 [] = "The quick brown fox "
static const char fox2 [] = "jumped over the lazy dog"
SBuf empty_sbuf
SBuf literal ("The quick brown fox jumped over the lazy dog")
Function Documentation
CPPUNIT_TEST_SUITE_REGISTRATION()
CPPUNIT_TEST_SUITE_REGISTRATION (TestSBuf)
eventAdd()
void eventAdd (const char * name, EVH * func, void * arg, double when, int weight, bool cbdata)
Definition at line 117 of file testSBuf.cc.
main()
int main (int argc, char * argv[])
Definition at line 1214 of file testSBuf.cc.
References TestProgram::run().
sign()
static int sign (int v) static
Definition at line 342 of file testSBuf.cc.
Referenced by TestSBuf::testComparisons(), testComparisonStdFull(), and testComparisonStdN().
testComparisonStd()
static void testComparisonStd (const char * s1, const char * s2) static
Definition at line 402 of file testSBuf.cc.
References s1, and testComparisonStdOneWay().
Referenced by TestSBuf::testComparisons().
testComparisonStdFull()
static void testComparisonStdFull (const char * left, const char * right) static
Definition at line 352 of file testSBuf.cc.
References sign().
Referenced by testComparisonStdOneWay().
testComparisonStdN()
static void testComparisonStdN (const char * left, const char * right, const size_t n) static
Definition at line 372 of file testSBuf.cc.
References sign().
Referenced by testComparisonStdOneWay().
testComparisonStdOneWay()
static void testComparisonStdOneWay (const char * left, const char * right) static
Definition at line 392 of file testSBuf.cc.
References min(), testComparisonStdFull(), and testComparisonStdN().
Referenced by TestSBuf::testComparisons(), and testComparisonStd().
Variable Documentation
empty_sbuf
SBuf empty_sbuf
Definition at line 132 of file testSBuf.cc.
Referenced by TestSBuf::testSBufConstructDestruct().
fox
const char fox[] = "The quick brown fox jumped over the lazy dog" static
Definition at line 125 of file testSBuf.cc.
Referenced by TestSBuf::testAppendf(), TestSBuf::testEqualityTest(), TestSBuf::testRawContent(), TestSBuf::testReserve(), TestSBuf::testSBufConstructDestruct(), TestSBuf::testSBufHash(), TestSBuf::testSBufLength(), and TestSBuf::testStdAlgorithm().
fox1
const char fox1[] = "The quick brown fox " static
Definition at line 126 of file testSBuf.cc.
Referenced by TestSBuf::testAppendCString(), TestSBuf::testAppendSBuf(), TestSBuf::testCopy(), TestSBuf::testRawSpace(), TestSBuf::testSBufHash(), TestSBuf::testSBufStream(), and TestSBuf::testStartsWith().
fox2
const char fox2[] = "jumped over the lazy dog" static
Definition at line 127 of file testSBuf.cc.
Referenced by TestSBuf::testAppendCString(), TestSBuf::testRawSpace(), TestSBuf::testSBufStream(), and TestSBuf::testStartsWith().
literal
SBuf literal("The quick brown fox jumped over the lazy dog") ("The quick brown fox jumped over the lazy dog")
Referenced by TestSBuf::testAppendCString(), TestSBuf::testChop(), TestSBuf::testConsume(), TestSBuf::testCopy(), TestSBuf::testFindFirstNotOf(), TestSBuf::testFindFirstOf(), TestSBuf::testGrow(), TestSBuf::testRawContent(), TestSBuf::testRawSpace(), TestSBuf::testRFindChar(), TestSBuf::testRFindSBuf(), TestSBuf::testSBufConstructDestruct(), TestSBuf::testSBufHash(), TestSBuf::testSBufStream(), TestSBuf::testStartsWith(), TestSBuf::testStringOps(), TestSBuf::testSubscriptOp(), TestSBuf::testSubscriptOpFail(), and TestSBuf::testSubstr().