Squid Web Cache: squid/src/tests/testRock.cc File Reference
testRock.cc File Reference
#include "squid.h"
#include "compat/cppunit.h"
#include "ConfigParser.h"
#include "DiskIO/DiskIOModule.h"
#include "fde.h"
#include "fs/rock/RockSwapDir.h"
#include "globals.h"
#include "HttpHeader.h"
#include "HttpReply.h"
#include "MemObject.h"
#include "RequestFlags.h"
#include "SquidConfig.h"
#include "Store.h"
#include "store/Disk.h"
#include "store/Disks.h"
#include "StoreFileSystem.h"
#include "StoreSearch.h"
#include "testStoreSupport.h"
#include "unitTestMain.h"
#include <stdexcept>
Classes
class TestRock
class MyTestProgram
customizes our test setup
Macros
#define TESTDIR "tr"
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestRock)
static void addSwapDir (TestRock::SwapDirPointer aStore)
static const char * storeId (const int i)
int main (int argc, char *argv[])
Macro Definition Documentation
TESTDIR
#define TESTDIR "tr"
Definition at line 37 of file testRock.cc.
Function Documentation
addSwapDir()
static void addSwapDir (TestRock::SwapDirPointer aStore) static
Definition at line 73 of file testRock.cc.
References allocate_new_swapdir(), SquidConfig::cacheSwap, Config, RefCount< C >::getRaw(), Store::DiskConfig::n_configured, and Store::DiskConfig::swapDirs.
Referenced by TestRock::setUp().
CPPUNIT_TEST_SUITE_REGISTRATION()
CPPUNIT_TEST_SUITE_REGISTRATION (TestRock)
main()
int main (int argc, char * argv[])
Definition at line 357 of file testRock.cc.
References TestProgram::run().
storeId()
static const char * storeId (const int i) static
Definition at line 155 of file testRock.cc.
Referenced by TestRock::createEntry(), and TestRock::getEntry().