Squid Web Cache: squid/src/tests/testTokenizer.cc File Reference
testTokenizer.cc File Reference
#include "squid.h"
#include "base/CharacterSet.h"
#include "compat/cppunit.h"
#include "parser/Tokenizer.h"
#include "unitTestMain.h"
Classes
class TestTokenizer
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestTokenizer)
int main (int argc, char *argv[])
Variables
SBuf text ("GET http://resource.com/path HTTP/1.1\r\n" "Host: resource.com\r\n" "Cookie: laijkpk3422r j1noin \r\n" "\r\n")
const CharacterSet alpha ("alpha","abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
const CharacterSet whitespace ("whitespace"," \r\n")
const CharacterSet crlf ("crlf","\r\n")
const CharacterSet tab ("tab","\t")
const CharacterSet numbers ("numbers","0123456789")
Function Documentation
CPPUNIT_TEST_SUITE_REGISTRATION()
CPPUNIT_TEST_SUITE_REGISTRATION (TestTokenizer)
main()
int main (int argc, char * argv[])
Definition at line 640 of file testTokenizer.cc.
References TestProgram::run().
Variable Documentation
alpha
const CharacterSet alpha("alpha","abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") ("alpha" , "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
Referenced by TestSBuf::testAppendStdString(), TestTokenizer::testTokenizerPrefix(), TestTokenizer::testTokenizerSkip(), and TestTokenizer::testTokenizerSuffix().
crlf
const CharacterSet crlf("crlf","\r\n") ("crlf" , "\r\n")
Referenced by TestTokenizer::testTokenizerPrefix(), and TestTokenizer::testTokenizerSuffix().
numbers
const CharacterSet numbers("numbers","0123456789") ("numbers" , "0123456789")
Referenced by TestTokenizer::testTokenizerPrefix(), and TestTokenizer::testTokenizerSuffix().
tab
const CharacterSet tab("tab","\t") ("tab" , "\t")
Referenced by TestTokenizer::testTokenizerPrefix().
text
SBuf text("GET http://resource.com/path HTTP/1.1\r\n" "Host: resource.com\r\n" "Cookie: laijkpk3422r j1noin \r\n" "\r\n") ("GET http://resource.com/path HTTP/1.1\r\n" "Host: resource.com\r\n" "Cookie: laijkpk3422r j1noin \r\n" "\r\n")
Referenced by Acl::NotNode::dump(), errorInitialize(), Ftp::Gateway::htmlifyListEntry(), ErrorPage::ImportStaticErrorText(), ipcache_entry::latestError(), Ssl::ParseAsSimpleDomainNameOrIp(), TestSBuf::testIterators(), TestTokenizer::testTokenizerPrefix(), TestTokenizer::testTokenizerSkip(), TestTokenizer::testTokenizerSuffix(), TestTokenizer::testTokenizerToken(), and Acl::Tree::treeDump().
whitespace
const CharacterSet whitespace("whitespace"," \r\n") ("whitespace" , " \r\n")
Referenced by Http::ContentLengthInterpreter::findDigits(), TestTokenizer::testTokenizerPrefix(), TestTokenizer::testTokenizerSkip(), TestTokenizer::testTokenizerSuffix(), and TestTokenizer::testTokenizerToken().