Squid Web Cache: squid/src/tests/testHttp1Parser.cc File Reference
testHttp1Parser.cc File Reference
#include "squid.h"
#include <cppunit/TestAssert.h>
#include "compat/cppunit.h"
#include "debug/Stream.h"
#include "http/one/RequestParser.h"
#include "http/RequestMethod.h"
#include "MemBuf.h"
#include "SquidConfig.h"
#include "unitTestMain.h"
Classes
class TestHttp1Parser
struct resultSet
Macros
#define private public
#define protected public
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestHttp1Parser)
static void testResults (int line, const SBuf &input, Http1::RequestParser &output, struct resultSet &expect)
int main (int argc, char *argv[])
Macro Definition Documentation
private
#define private public
Definition at line 13 of file testHttp1Parser.cc.
protected
#define protected public
Definition at line 14 of file testHttp1Parser.cc.
Function Documentation
CPPUNIT_TEST_SUITE_REGISTRATION()
CPPUNIT_TEST_SUITE_REGISTRATION (TestHttp1Parser)
main()
int main (int argc, char * argv[])
Definition at line 1198 of file testHttp1Parser.cc.
References TestProgram::run().
testResults()
static void testResults (int line, const SBuf & input, Http1::RequestParser & output, struct resultSet & expect) static
Definition at line 110 of file testHttp1Parser.cc.
References Http::One::Parser::buf_, SBuf::cmp(), SBuf::length(), resultSet::method, Http::One::RequestParser::method_, Http::One::Parser::msgProtocol_, resultSet::needsMore, Http::One::Parser::needsMoreData(), Http::One::RequestParser::parse(), resultSet::parsed, resultSet::parserState, Http::One::Parser::parseStatusCode, Http::One::Parser::parsingStage_, resultSet::status, resultSet::suffixSz, resultSet::uri, Http::One::RequestParser::uri_, and resultSet::version.
Referenced by TestHttp1Parser::testDripFeed(), TestHttp1Parser::testParseRequestLineInvalid(), TestHttp1Parser::testParseRequestLineMethods(), TestHttp1Parser::testParseRequestLineProtocols(), TestHttp1Parser::testParseRequestLineStrange(), and TestHttp1Parser::testParseRequestLineTerminators().