Squid Web Cache: squid/src/tests/testUfs.cc File Reference
testUfs.cc File Reference
#include "squid.h"
#include "compat/cppunit.h"
#include "DiskIO/DiskIOModule.h"
#include "fde.h"
#include "fs/ufs/UFSSwapDir.h"
#include "globals.h"
#include "HttpHeader.h"
#include "HttpReply.h"
#include "MemObject.h"
#include "RequestFlags.h"
#include "SquidConfig.h"
#include "Store.h"
#include "store/Disks.h"
#include "testStoreSupport.h"
#include "unitTestMain.h"
#include <stdexcept>
Classes
class TestUfs
Macros
#define TESTDIR "TestUfs_Store"
Typedefs
typedef RefCount< Fs::Ufs::UFSSwapDir > MySwapDirPointer
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestUfs)
static void addSwapDir (MySwapDirPointer aStore)
static void searchCallback (void *)
int main (int argc, char *argv[])
Variables
REMOVALPOLICYCREATE createRemovalPolicy_lru
static bool cbcalled
Macro Definition Documentation
TESTDIR
#define TESTDIR "TestUfs_Store"
Definition at line 27 of file testUfs.cc.
Typedef Documentation
MySwapDirPointer
typedef RefCount<Fs::Ufs::UFSSwapDir> MySwapDirPointer
Definition at line 48 of file testUfs.cc.
Function Documentation
addSwapDir()
static void addSwapDir (MySwapDirPointer aStore) static
Definition at line 52 of file testUfs.cc.
References allocate_new_swapdir(), SquidConfig::cacheSwap, Config, RefCount< C >::getRaw(), Store::DiskConfig::n_configured, and Store::DiskConfig::swapDirs.
Referenced by TestUfs::testUfsDefaultEngine(), and TestUfs::testUfsSearch().
CPPUNIT_TEST_SUITE_REGISTRATION()
CPPUNIT_TEST_SUITE_REGISTRATION (TestUfs)
main()
int main (int argc, char * argv[])
Definition at line 259 of file testUfs.cc.
References TestProgram::run().
searchCallback()
static void searchCallback (void *) static
Definition at line 62 of file testUfs.cc.
References cbcalled.
Referenced by TestUfs::testUfsSearch().
Variable Documentation
cbcalled
bool cbcalled static
Definition at line 59 of file testUfs.cc.
Referenced by searchCallback(), and TestUfs::testUfsSearch().
createRemovalPolicy_lru
REMOVALPOLICYCREATE createRemovalPolicy_lru extern
Definition at line 15 of file store_repl_lru.cc.
Referenced by TestUfs::commonInit().