Squid Web Cache: squid/src/tests/testStoreHashIndex.cc File Reference
testStoreHashIndex.cc File Reference
#include "squid.h"
#include "compat/cppunit.h"
#include "MemObject.h"
#include "SquidConfig.h"
#include "Store.h"
#include "store/Disks.h"
#include "StoreSearch.h"
#include "TestSwapDir.h"
Classes
class TestStoreHashIndex
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestStoreHashIndex)
static void addSwapDir (TestSwapDirPointer aStore)
static StoreEntry * addedEntry (Store::Disk *aStore, String name, String, String)
static void commonInit ()
static void searchCallback (void *)
Variables
static bool cbcalled
Function Documentation
addedEntry()
static StoreEntry * addedEntry (Store::Disk * aStore, String name, String , String) static
Definition at line 79 of file testStoreHashIndex.cc.
References SquidConfig::cacheSwap, Config, EBIT_CLR, ENTRY_VALIDATED, StoreEntry::expires, StoreEntry::flags, StoreEntry::hashInsert(), INDEXSD, StoreEntry::lastModified(), StoreEntry::lastref, Store::DiskConfig::n_configured, NOT_IN_MEMORY, PING_NONE, StoreEntry::ping_status, StoreEntry::refcount, StoreEntry::setMemStatus(), squid_curtime, STORE_OK, StoreEntry::store_status, StoreEntry::swap_dirn, StoreEntry::swap_file_sz, StoreEntry::swap_filen, StoreEntry::swap_status, SWAPOUT_DONE, String::termedBuf(), and StoreEntry::timestamp.
Referenced by TestStoreHashIndex::testSearch().
addSwapDir()
static void addSwapDir (TestSwapDirPointer aStore) static
Definition at line 39 of file testStoreHashIndex.cc.
References allocate_new_swapdir(), SquidConfig::cacheSwap, Config, RefCount< C >::getRaw(), Store::DiskConfig::n_configured, and Store::DiskConfig::swapDirs.
Referenced by TestStoreHashIndex::testMaxSize(), TestStoreHashIndex::testSearch(), and TestStoreHashIndex::testStats().
commonInit()
static void commonInit () static
Definition at line 110 of file testStoreHashIndex.cc.
References SquidConfig::avgObjectSize, Config, YesNoNone::defaultTo(), Mem::Init(), SquidConfig::maxObjectSize, SquidConfig::memShared, SquidConfig::objectsPerBucket, SquidConfig::Store, SquidConfig::store_dir_select_algorithm, and xstrdup.
Referenced by TestStoreHashIndex::testSearch().
CPPUNIT_TEST_SUITE_REGISTRATION()
CPPUNIT_TEST_SUITE_REGISTRATION (TestStoreHashIndex)
searchCallback()
static void searchCallback (void *) static
Definition at line 137 of file testStoreHashIndex.cc.
References cbcalled.
Referenced by TestStoreHashIndex::testSearch().
Variable Documentation
cbcalled
bool cbcalled static
Definition at line 134 of file testStoreHashIndex.cc.
Referenced by searchCallback(), and TestStoreHashIndex::testSearch().