Squid Web Cache: squid/src/auth/digest/file/text_backend.cc File Reference
text_backend.cc File Reference
#include "squid.h"
#include "auth/digest/file/text_backend.h"
Classes
struct _user_data
Typedefs
typedef struct _user_data user_data
Functions
static void my_free (void *p)
static void read_passwd_file (const char *passwordFile, int isHa1Mode)
void TextArguments (int argc, char **argv)
static const user_data * GetPassword (RequestData *requestData)
void TextHHA1 (RequestData *requestData)
Variables
static hash_table * hash = nullptr
static HASHFREE my_free
static char * passwdfile = nullptr
static int ha1mode = 0
static time_t change_time = 0
Typedef Documentation
user_data
typedef struct _user_data user_data
Function Documentation
GetPassword()
static const user_data * GetPassword (RequestData * requestData) static
Definition at line 164 of file text_backend.cc.
References change_time, ha1mode, hash, hash_lookup(), passwdfile, read_passwd_file(), _request_data::realm, and _request_data::user.
Referenced by TextHHA1().
my_free()
static void my_free (void * p) static
Definition at line 54 of file text_backend.cc.
References _user_data::ha1, _user_data::hash, hash_link::key, _user_data::passwd, and xfree.
read_passwd_file()
static void read_passwd_file (const char * passwordFile, int isHa1Mode) static
Definition at line 64 of file text_backend.cc.
References _user_data::ha1, hash, _user_data::hash, hash_create(), hash_join(), hash_string, hashFreeItems(), hashFreeMemory(), hash_link::key, my_free, _user_data::passwd, xcalloc(), xmalloc, xstrdup, and xstrerr().
Referenced by GetPassword().
TextArguments()
void TextArguments (int argc, char ** argv)
Definition at line 143 of file text_backend.cc.
References ha1mode, and passwdfile.
Referenced by ProcessArguments().
TextHHA1()
void TextHHA1 (RequestData * requestData)
Definition at line 189 of file text_backend.cc.
References DigestCalcHA1(), _request_data::error, GetPassword(), _user_data::ha1, _request_data::HHA1, _user_data::passwd, _request_data::realm, _request_data::user, and xstrncpy().
Referenced by GetHHA1().
Variable Documentation
change_time
time_t change_time = 0 static
Definition at line 45 of file text_backend.cc.
Referenced by GetPassword(), and main().
ha1mode
int ha1mode = 0 static
Definition at line 44 of file text_backend.cc.
Referenced by GetPassword(), and TextArguments().
hash
hash_table* hash = nullptr static
Definition at line 41 of file text_backend.cc.
Referenced by ipcache_entry::~ipcache_entry(), cacheDestroy(), cacheResetDigest(), client_entry(), clientdbDump(), do_subtree(), FileNameHash(), generateFakeSslCertificate(), get_token(), GetPassword(), init_node_hash(), Ipc::StoreMap::nameByKey(), PidFilenameHash(), and read_passwd_file().
my_free
HASHFREE my_free static
Definition at line 42 of file text_backend.cc.
Referenced by read_passwd_file().
passwdfile
char* passwdfile = nullptr static
Definition at line 43 of file text_backend.cc.
Referenced by GetPassword(), read_passwd_file(), and TextArguments().