Squid Web Cache: squid/src/base/TextException.cc File Reference
TextException.cc File Reference
#include "squid.h"
#include "base/TextException.h"
#include "sbuf/SBuf.h"
#include <iostream>
#include <sstream>
#include <unordered_map>
Typedefs
typedef std::runtime_error WhatString
a standard CoW string; avoids noise and circular dependencies of SBuf
typedef std::unordered_multimap< const void *, WhatString > WhatStrings
a collection of strings indexed by pointers to their creator objects
Functions
std::ostream & operator<< (std::ostream &os, const TextException &ex)
efficiently prints TextException
static std::ostream & CurrentException_ (std::ostream &os)
prints the current exception (which presence has been verified by the caller)
std::ostream & CurrentException (std::ostream &os)
prints active (i.e., thrown but not yet handled) exception
std::ostream & CurrentExceptionExtra (std::ostream &os)
Variables
static WhatStrings * WhatStrings_ = nullptr
requested what() strings of alive TextException objects
Typedef Documentation
WhatString
typedef std::runtime_error WhatString
Definition at line 18 of file TextException.cc.
WhatStrings
typedef std::unordered_multimap<const void*, WhatString> WhatStrings
Definition at line 21 of file TextException.cc.
Function Documentation
CurrentException()
std::ostream & CurrentException (std::ostream & os)
Definition at line 88 of file TextException.cc.
References CurrentException_().
Referenced by Comm::TcpAcceptor::acceptOne(), FwdState::advanceDestination(), TunnelStateData::advanceDestination(), StoreEntry::checkDisk(), Rock::IoState::close(), ConfigurationFailureMessage(), HttpStateData::decodeAndWriteReplyBody(), MemStore::get(), Security::KeyData::loadCertificates(), main(), mimeInit(), ACLRegexData::parse(), Ssl::ErrorDetailFile::parse(), AnyP::Uri::parse(), Http::StatusLine::parse(), store_client::parseHttpHeadersFromDisk(), parseOneConfigFile(), Ssl::CertValidationMsg::parseResponse(), ConnStateData::parseTlsHandshake(), ErrorPage::BuildErrorPrinter::print(), processNewRequest(), Ssl::readCertAndPrivateKeyFromMemory(), store_client::readHeader(), Ipc::Port::receiveOrIgnore(), setTraceability(), SquidMainSafe(), CacheManager::start(), storeRebuildParseEntry(), Store::Controller::syncCollapsed(), TerminationReason(), Store::Controller::updateOnNotModified(), and wccp2HandleUdp().
CurrentException_()
static std::ostream & CurrentException_ (std::ostream & os) static
Definition at line 70 of file TextException.cc.
References TextException::what().
Referenced by CurrentException(), and CurrentExceptionExtra().
CurrentExceptionExtra()
std::ostream & CurrentExceptionExtra (std::ostream & os)
If there is an active (i.e., thrown but not yet handled) exception, reports it on a dedicated DebugExtra line. Otherwise, does nothing.
Definition at line 99 of file TextException.cc.
References CurrentException_(), and Debug::Extra().
Referenced by OnTerminate().
operator<<()
std::ostream & operator<< (std::ostream & os, const TextException & ex)
Definition at line 61 of file TextException.cc.
References TextException::print().
Variable Documentation
WhatStrings_
WhatStrings* WhatStrings_ = nullptr static
Definition at line 24 of file TextException.cc.
Referenced by TextException::~TextException(), and TextException::what().