Squid Web Cache: squid/src/auth/digest/file/text_backend.h File Reference
text_backend.h File Reference
#include "auth/digest/file/digest_common.h"
Functions
void TextArguments (int argc, char **argv)
void TextHHA1 (RequestData *requestData)
Function Documentation
TextArguments()
void TextArguments (int argc, char ** argv) extern
Definition at line 143 of file text_backend.cc.
References ha1mode, and passwdfile.
Referenced by ProcessArguments().
TextHHA1()
void TextHHA1 (RequestData * requestData) extern
Definition at line 189 of file text_backend.cc.
References DigestCalcHA1(), _request_data::error, GetPassword(), _user_data::ha1, _request_data::HHA1, _user_data::passwd, _request_data::realm, _request_data::user, and xstrncpy().
Referenced by GetHHA1().