Squid Web Cache: squid/src/auth/toUtf.h File Reference
toUtf.h File Reference
#include "sbuf/forward.h"
Functions
SBuf Latin1ToUtf8 (const char *in)
converts ISO-LATIN-1 to UTF-8
SBuf Cp1251ToUtf8 (const char *in)
converts CP1251 to UTF-8
bool isValidUtf8String (const char *source, const char *sourceEnd)
returns whether the given input is a valid (or empty) sequence of UTF-8 code points
Function Documentation
Cp1251ToUtf8()
SBuf Cp1251ToUtf8 (const char * in)
Definition at line 37 of file toUtf.cc.
References SBuf::append().
isValidUtf8String()
bool isValidUtf8String (const char * source, const char * sourceEnd)
Returns
whether the given input is a valid (or empty) sequence of UTF-8 code points
Definition at line 172 of file toUtf.cc.
References isValidUtf8CodePoint(), and utf8CodePointLength().
Latin1ToUtf8()
SBuf Latin1ToUtf8 (const char * in)
Definition at line 16 of file toUtf.cc.
References SBuf::append().