Squid Web Cache: squid/compat/unistd.h File Reference
unistd.h File Reference
Functions
int xclose (int fd)
POSIX close(2) equivalent.
int xgethostname (char *name, size_t nameLength)
POSIX gethostname(2) equivalent.
int xopen (const char *filename, int oflag, int pmode=0)
POSIX open(2) equivalent.
int xread (int fd, void *buf, size_t bufSize)
POSIX read(2) equivalent.
int xwrite (int fd, const void *buf, size_t bufSize)
POSIX write(2) equivalent.
Function Documentation
xclose()
int xclose (int fd) inline
Definition at line 43 of file unistd.h.
Referenced by File::close(), Icmp::Close(), IcmpPinger::Close(), comm_close_complete(), Rock::SwapDir::create(), do_close(), file_close(), Ipc::Coordinator::handleCacheMgrRequest(), ipcCreate(), Eui::Eui48::lookup(), main(), main(), main(), CommIO::NotifyIOClose(), Ip::Intercept::PfInterception(), Ip::Intercept::ProbeForTproxy(), Mgr::Action::respond(), squidaio_cleanup_request(), squidaio_cleanup_request(), squidaio_do_close(), squidaio_do_close(), and Ssl::Lock::unlock().
xgethostname()
int xgethostname (char * name, size_t nameLength) inline
Definition at line 49 of file unistd.h.
Referenced by getMyHostname().
xopen()
int xopen (const char * filename, int oflag, int pmode = 0) inline
Definition at line 55 of file unistd.h.
Referenced by Rock::SwapDir::create(), do_open(), file_open(), Ssl::Lock::lock(), main(), main(), File::open(), Ip::Intercept::PfInterception(), Comm::SelectLoopInit(), and watch_child().
xread()
int xread (int fd, void * buf, size_t bufSize) inline
Definition at line 61 of file unistd.h.
Referenced by default_read_method(), do_read(), ipc_thread_1(), ipc_thread_2(), ipcCreate(), main(), IcmpPinger::Open(), File::readSmall(), squidaio_do_read(), Rock::Rebuild::start(), and unlinkdUnlink().
xwrite()
int xwrite (int fd, const void * buf, size_t bufSize) inline
Definition at line 67 of file unistd.h.
Referenced by comm_flush_updates(), Rock::SwapDir::create(), default_write_method(), do_write(), ipc_thread_1(), ipcCreate(), logfile_mod_udp_write(), IcmpPinger::Open(), squidaio_do_write(), unlinkdUnlink(), and File::writeAll().