Squid Web Cache: squid/src/urn.cc File Reference
urn.cc File Reference
#include "squid.h"
#include "AccessLogEntry.h"
#include "acl/FilledChecklist.h"
#include "base/TextException.h"
#include "cbdata.h"
#include "errorpage.h"
#include "FwdState.h"
#include "globals.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "icmp/net_db.h"
#include "MemBuf.h"
#include "mime_header.h"
#include "RequestFlags.h"
#include "Store.h"
#include "StoreClient.h"
#include "tools.h"
#include "urn.h"
Classes
class UrnState
struct url_entry
Functions
static url_entry * urnParseReply (const SBuf &, const HttpRequestMethod &)
static url_entry * urnFindMinRtt (url_entry *urls, const HttpRequestMethod &, int *rtt_ret)
void urnStart (HttpRequest *r, StoreEntry *e, const AccessLogEntryPointer &ale)
static int url_entry_sort (const void *A, const void *B)
static void urnHandleReply (void *data, StoreIOBuffer result)
Variables
static STCB urnHandleReply
static const char *const crlf = "\r\n"
Function Documentation
url_entry_sort()
static int url_entry_sort (const void * A, const void * B) static
Definition at line 213 of file urn.cc.
References url_entry::rtt.
Referenced by urnHandleReply().
urnFindMinRtt()
static url_entry * urnFindMinRtt (url_entry * urls, const HttpRequestMethod & , int * rtt_ret) static
Definition at line 93 of file urn.cc.
References assert, DBG_IMPORTANT, debugs, url_entry::host, url_entry::rtt, and url_entry::url.
Referenced by urnHandleReply().
urnHandleReply()
static void urnHandleReply (void * data, StoreIOBuffer result) static
Definition at line 230 of file urn.cc.
References UrnState::ale, Store::ParsingBuffer::appended(), SBuf::appendf(), store_client::atEof(), MemObject::baseReply(), StoreEntry::buffer(), url_entry::cached, StoreEntry::complete(), Store::ParsingBuffer::contentSize(), StoreIOBuffer::data, debugs, EBIT_TEST, UrnState::entry, ENTRY_ABORTED, ERR_URN_RESOLVE, StoreIOBuffer::error, errorAppendEntry(), StoreEntry::flags, StoreIOBuffer::flags, url_entry::flags, getMyHostname(), RefCount< C >::getRaw(), StoreEntry::isAccepting(), SBuf::length(), StoreIOBuffer::length, Http::LOCATION, StoreEntry::mem(), HttpRequest::method, UrnState::parsingBuffer, StoreIOBuffer::positionAt(), StoreEntry::replaceHttpReply(), UrnState::request, url_entry::rtt, safe_free, UrnState::sc, Http::scFound, Http::scNotFound, Http::scOkay, HttpReply::setHeaders(), Store::ParsingBuffer::space(), squid_curtime, storeClientCopy(), Store::ParsingBuffer::toSBuf(), ErrorState::url, StoreEntry::url(), url_entry::url, url_entry_sort(), UrnState::urlres_e, urnFindMinRtt(), urnHandleReply, urnParseReply(), visible_appname_string, and xstrdup.
urnParseReply()
static url_entry * urnParseReply (const SBuf & inBuf, const HttpRequestMethod & m) static
Definition at line 365 of file urn.cc.
References AnyP::Uri::absolute(), SBuf::c_str(), url_entry::cached, crlf, debugs, url_entry::flags, AnyP::Uri::host(), url_entry::host, netdbHostRtt(), netdbPingSite(), AnyP::Uri::parse(), url_entry::rtt, safe_free, SBufToCstring(), storeGetPublic(), url_entry::url, xcalloc(), xfree, xisspace, and xstrdup.
Referenced by urnHandleReply().
urnStart()
void urnStart (HttpRequest * r, StoreEntry * e, const AccessLogEntryPointer & ale)
Definition at line 206 of file urn.cc.
Referenced by FwdState::Start().
Variable Documentation
crlf
const char* const crlf = "\r\n" static
Definition at line 72 of file urn.cc.
Referenced by urnParseReply().
urnHandleReply
STCB urnHandleReply static
Definition at line 70 of file urn.cc.
Referenced by UrnState::start(), and urnHandleReply().