Squid Web Cache: squid/src/auth/UserRequest.cc File Reference
UserRequest.cc File Reference
#include "squid.h"
#include "acl/FilledChecklist.h"
#include "auth/Config.h"
#include "client_side.h"
#include "comm/Connection.h"
#include "fatal.h"
#include "format/Format.h"
#include "helper.h"
#include "helper/Reply.h"
#include "http/Stream.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "MemBuf.h"
#include "sbuf/Stream.h"
Functions
static void authenticateAuthUserRequestSetIp (Auth::UserRequest::Pointer auth_user_request, Ip::Address &ipaddr)
void authenticateAuthUserRequestRemoveIp (Auth::UserRequest::Pointer auth_user_request, Ip::Address const &ipaddr)
void authenticateAuthUserRequestClearIp (Auth::UserRequest::Pointer auth_user_request)
int authenticateAuthUserRequestIPCount (Auth::UserRequest::Pointer auth_user_request)
bool authenticateUserAuthenticated (const Auth::UserRequest::Pointer &auth_user_request)
static void authenticateAuthenticateUser (Auth::UserRequest::Pointer auth_user_request, HttpRequest *request, ConnStateData *conn, Http::HdrType type)
static Auth::UserRequest::Pointer authTryGetUser (Auth::UserRequest::Pointer auth_user_request, ConnStateData *conn, HttpRequest *request)
static Auth::ConfigVector & schemesConfig (HttpRequest *request, HttpReply *rep)
Function Documentation
authenticateAuthenticateUser()
static void authenticateAuthenticateUser (Auth::UserRequest::Pointer auth_user_request, HttpRequest * request, ConnStateData * conn, Http::HdrType type) static
Definition at line 236 of file UserRequest.cc.
References assert, Auth::UserRequest::authenticate(), and RefCount< C >::getRaw().
Referenced by Auth::UserRequest::authenticate().
authenticateAuthUserRequestClearIp()
void authenticateAuthUserRequestClearIp (Auth::UserRequest::Pointer auth_user_request)
Definition at line 172 of file UserRequest.cc.
References Auth::User::clearIp(), and Auth::UserRequest::user().
Referenced by ACLMaxUserIP::match().
authenticateAuthUserRequestIPCount()
int authenticateAuthUserRequestIPCount (Auth::UserRequest::Pointer auth_user_request)
Definition at line 179 of file UserRequest.cc.
References assert, Auth::User::ipcount, and Auth::UserRequest::user().
Referenced by ACLMaxUserIP::match().
authenticateAuthUserRequestRemoveIp()
void authenticateAuthUserRequestRemoveIp (Auth::UserRequest::Pointer auth_user_request, Ip::Address const & ipaddr)
Definition at line 161 of file UserRequest.cc.
References Auth::User::removeIp(), and Auth::UserRequest::user().
Referenced by ACLMaxUserIP::match().
authenticateAuthUserRequestSetIp()
static void authenticateAuthUserRequestSetIp (Auth::UserRequest::Pointer auth_user_request, Ip::Address & ipaddr) static
Definition at line 150 of file UserRequest.cc.
References Auth::User::addIp(), and Auth::UserRequest::user().
Referenced by Auth::UserRequest::authenticate().
authenticateUserAuthenticated()
bool authenticateUserAuthenticated (const Auth::UserRequest::Pointer & auth_user_request)
See Auth::UserRequest::authenticated()
Definition at line 190 of file UserRequest.cc.
References Auth::UserRequest::authenticated(), and Auth::UserRequest::valid().
Referenced by Auth::UserRequest::authenticate(), Auth::UserRequest::direction(), and ACLProxyAuth::matchProxyAuth().
authTryGetUser()
static Auth::UserRequest::Pointer authTryGetUser (Auth::UserRequest::Pointer auth_user_request, ConnStateData * conn, HttpRequest * request) static
Definition at line 244 of file UserRequest.cc.
References HttpRequest::auth_user_request, ConnStateData::getAuth(), Auth::User::notes, UpdateRequestNotes(), and Auth::UserRequest::user().
Referenced by Auth::UserRequest::authenticate(), and Auth::UserRequest::tryToAuthenticateAndSetAuthUser().
schemesConfig()
static Auth::ConfigVector & schemesConfig (HttpRequest * request, HttpReply * rep) static
Definition at line 479 of file UserRequest.cc.
References ACLChecklist::fastCheck(), Auth::Config::schemeAccess, Auth::Config::schemeLists, Auth::Config::schemes, Auth::TheConfig, and ACLFilledChecklist::updateReply().
Referenced by Auth::UserRequest::AddReplyAuthHeader().