Squid Web Cache: squid/src/acl/UserData.cc File Reference
UserData.cc File Reference
#include "squid.h"
#include "acl/Checklist.h"
#include "acl/Options.h"
#include "acl/UserData.h"
#include "ConfigParser.h"
#include "debug/Stream.h"
#include "globals.h"
#include "sbuf/Algorithms.h"
#include "util.h"
Functions
static bool CaseSensitiveSBufCompare (const SBuf &lhs, const SBuf &rhs)
static bool CaseInsensitveSBufCompare (const SBuf &lhs, const SBuf &rhs)
Function Documentation
CaseInsensitveSBufCompare()
static bool CaseInsensitveSBufCompare (const SBuf & lhs, const SBuf & rhs) static
Definition at line 69 of file UserData.cc.
References SBuf::caseCmp().
Referenced by ACLUserData::parse().
CaseSensitiveSBufCompare()
static bool CaseSensitiveSBufCompare (const SBuf & lhs, const SBuf & rhs) static
Definition at line 63 of file UserData.cc.
References SBuf::cmp().