Squid Web Cache: squid/src/auth/UserRequest.h File Reference
UserRequest.h File Reference
#include "AccessLogEntry.h"
#include "auth/AuthAclState.h"
#include "auth/Scheme.h"
#include "auth/User.h"
#include "dlink.h"
#include "helper/forward.h"
#include "HttpHeader.h"
#include "ip/Address.h"
Classes
class AuthUserIP
class Auth::UserRequest
Namespaces
namespace Auth
HTTP Authentication.
Macros
#define MAX_AUTHTOKEN_LEN 65535
Typedefs
typedef void AUTHCB(void *)
Enumerations
enum Auth::Direction { Auth::CRED_CHALLENGE = 1 , Auth::CRED_VALID = 0 , Auth::CRED_LOOKUP = -1 , Auth::CRED_ERROR = -2 }
Functions
void authenticateAuthUserRequestRemoveIp (Auth::UserRequest::Pointer, Ip::Address const &)
void authenticateAuthUserRequestClearIp (Auth::UserRequest::Pointer)
int authenticateAuthUserRequestIPCount (Auth::UserRequest::Pointer)
bool authenticateUserAuthenticated (const Auth::UserRequest::Pointer &)
Macro Definition Documentation
MAX_AUTHTOKEN_LEN
#define MAX_AUTHTOKEN_LEN 65535
Maximum length (buffer size) for token strings.
Definition at line 31 of file UserRequest.h.
Typedef Documentation
AUTHCB
typedef void AUTHCB(void *)
Definition at line 57 of file UserRequest.h.
Function Documentation
authenticateAuthUserRequestClearIp()
void authenticateAuthUserRequestClearIp (Auth::UserRequest::Pointer auth_user_request)
Definition at line 172 of file UserRequest.cc.
References Auth::User::clearIp(), and Auth::UserRequest::user().
Referenced by ACLMaxUserIP::match().
authenticateAuthUserRequestIPCount()
int authenticateAuthUserRequestIPCount (Auth::UserRequest::Pointer auth_user_request)
Definition at line 179 of file UserRequest.cc.
References assert, Auth::User::ipcount, and Auth::UserRequest::user().
Referenced by ACLMaxUserIP::match().
authenticateAuthUserRequestRemoveIp()
void authenticateAuthUserRequestRemoveIp (Auth::UserRequest::Pointer auth_user_request, Ip::Address const & ipaddr)
Definition at line 161 of file UserRequest.cc.
References Auth::User::removeIp(), and Auth::UserRequest::user().
Referenced by ACLMaxUserIP::match().
authenticateUserAuthenticated()
bool authenticateUserAuthenticated (const Auth::UserRequest::Pointer & auth_user_request)
See Auth::UserRequest::authenticated()
Definition at line 190 of file UserRequest.cc.
References Auth::UserRequest::authenticated(), and Auth::UserRequest::valid().
Referenced by Auth::UserRequest::authenticate(), Auth::UserRequest::direction(), and ACLProxyAuth::matchProxyAuth().