Squid Web Cache: squid/include/util.h File Reference
util.h File Reference
Functions
void Tolower (char *)
double xpercent (double part, double whole)
int xpercentInt (double part, double whole)
double xdiv (double nom, double denom)
const char * xitoa (int num)
const char * xint64toa (int64_t num)
const char * double_to_str (char *buf, int buf_size, double value)
Function Documentation
double_to_str()
const char * double_to_str (char * buf, int buf_size, double value)
Definition at line 77 of file util.cc.
Referenced by Mem::Report().
Tolower()
void Tolower (char * q)
Definition at line 28 of file util.cc.
References xtolower.
Referenced by CachePeer::CachePeer(), ipcache_entry::ipcache_entry(), fqdncacheAddEntryFromHosts(), idnsAddPathComponent(), internalHostname(), internalRemoteUri(), and ACLDomainData::parse().
xdiv()
double xdiv (double nom, double denom)
Definition at line 53 of file util.cc.
Referenced by cacheDigestReport(), httpHdrCcStatDumper(), httpHdrScStatDumper(), httpHdrScTargetStatDumper(), httpHeaderFieldStatDumper(), Mem::PoolReport(), and xpercent().
xint64toa()
const char * xint64toa (int64_t num)
Definition at line 69 of file util.cc.
References PRId64.
Referenced by HttpHeader::putInt64().
xitoa()
const char * xitoa (int num)
Definition at line 60 of file util.cc.
Referenced by Ssl::CertValidationMsg::composeRequest(), Ipc::Port::MakeAddr(), ProcessMacros(), and HttpHeader::putInt().
xpercent()
double xpercent (double part, double whole)
Definition at line 40 of file util.cc.
References xdiv().
Referenced by cacheDigestGuessStatsReport(), httpHeaderFldsPerHdrDumper(), httpHeaderStoreReport(), Mem::PoolReport(), refreshCountsStatsEntry(), refreshStats(), Mem::Report(), storeDigestReport(), CacheDigest::usedMaskPercent(), and xpercentInt().
xpercentInt()
int xpercentInt (double part, double whole)
Definition at line 46 of file util.cc.
References xpercent().
Referenced by cacheDigestReport(), cacheQueryReport(), peerDigestSetCBlock(), statPeerSelect(), and storeDigestResize().