Squid Web Cache: squid/src/auth/basic/SSPI/valid.cc File Reference
valid.cc File Reference
#include "squid.h"
#include "auth/basic/SSPI/valid.h"
#include "util.h"
#include <cwchar>
Functions
static int Valid_Group (char *UserName, char *Group)
int Valid_User (char *UserName, char *Password, char *)
Variables
char Default_NTDomain [DNLEN+1] = NTV_DEFAULT_DOMAIN
const char * errormsg
const char NTV_SERVER_ERROR_MSG [] = "Internal server error"
const char NTV_GROUP_ERROR_MSG [] = "User not allowed to use this cache"
const char NTV_LOGON_ERROR_MSG [] = "No such user or wrong password"
const char NTV_VALID_DOMAIN_SEPARATOR [] = "\\/"
Function Documentation
Valid_Group()
static int Valid_Group (char * UserName, char * Group) static
Definition at line 53 of file valid.cc.
References FALSE, NULL, and TRUE.
Referenced by Valid_User().
Valid_User()
int Valid_User (char * UserName, char * Password, char * Group)
Valid_User return codes.
Return values
0 User authenticated successfully.
1 Server error.
2 Group membership error.
3 Logon error; Incorrect password or username given.
Definition at line 120 of file valid.cc.
References debug(), Default_NTDomain, errormsg, NTAllowedGroup, NTDisAllowedGroup, NTV_DEFAULT_DOMAIN, NTV_GROUP_ERROR, NTV_GROUP_ERROR_MSG, NTV_LOGON_ERROR, NTV_LOGON_ERROR_MSG, NTV_NO_ERROR, NTV_SERVER_ERROR, NTV_SERVER_ERROR_MSG, NTV_VALID_DOMAIN_SEPARATOR, NULL, SSP_LogonUser(), UseAllowedGroup, UseDisallowedGroup, Valid_Group(), and xstrncpy().
Referenced by main().
Variable Documentation
Default_NTDomain
char Default_NTDomain[DNLEN+1] = NTV_DEFAULT_DOMAIN
Definition at line 43 of file valid.cc.
Referenced by process_options(), and Valid_User().
errormsg
const char* errormsg
Definition at line 44 of file valid.cc.
Referenced by main(), and Valid_User().
NTV_GROUP_ERROR_MSG
const char NTV_GROUP_ERROR_MSG[] = "User not allowed to use this cache"
Definition at line 47 of file valid.cc.
Referenced by Valid_User().
NTV_LOGON_ERROR_MSG
const char NTV_LOGON_ERROR_MSG[] = "No such user or wrong password"
Definition at line 48 of file valid.cc.
Referenced by Valid_User().
NTV_SERVER_ERROR_MSG
const char NTV_SERVER_ERROR_MSG[] = "Internal server error"
Definition at line 46 of file valid.cc.
Referenced by Valid_User().
NTV_VALID_DOMAIN_SEPARATOR
const char NTV_VALID_DOMAIN_SEPARATOR[] = "\\/"
Definition at line 49 of file valid.cc.
Referenced by Valid_User().