Squid Web Cache: squid/src/wccp2.h File Reference
wccp2.h File Reference
Functions
void parse_wccp2_method (int *v)
void free_wccp2_method (int *v)
void dump_wccp2_method (StoreEntry *e, const char *label, int v)
void parse_wccp2_amethod (int *v)
void free_wccp2_amethod (int *v)
void dump_wccp2_amethod (StoreEntry *e, const char *label, int v)
void parse_wccp2_service (void *v)
void free_wccp2_service (void *v)
void dump_wccp2_service (StoreEntry *e, const char *label, void *v)
int check_null_wccp2_service (void *v)
void parse_wccp2_service_info (void *v)
void free_wccp2_service_info (void *v)
void dump_wccp2_service_info (StoreEntry *e, const char *label, void *v)
Function Documentation
check_null_wccp2_service()
int check_null_wccp2_service (void * v)
Definition at line 2243 of file wccp2.cc.
References wccp2_service_list_head.
dump_wccp2_amethod()
void dump_wccp2_amethod (StoreEntry * e, const char * label, int v)
Definition at line 2138 of file wccp2.cc.
References DBG_CRITICAL, debugs, self_destruct(), storeAppendPrintf(), WCCP2_ASSIGNMENT_METHOD_HASH, and WCCP2_ASSIGNMENT_METHOD_MASK.
dump_wccp2_method()
void dump_wccp2_method (StoreEntry * e, const char * label, int v)
Definition at line 2090 of file wccp2.cc.
References DBG_CRITICAL, debugs, self_destruct(), storeAppendPrintf(), WCCP2_METHOD_GRE, and WCCP2_METHOD_L2.
dump_wccp2_service()
void dump_wccp2_service (StoreEntry * e, const char * label, void * v)
Definition at line 2217 of file wccp2.cc.
References debugs, wccp2_service_list_t::info, wccp2_service_list_t::next, wccp2_service_info_t::service, wccp2_service_info_t::service_id, storeAppendPrintf(), WCCP2_MD5_SECURITY, wccp2_service_list_t::wccp2_security_type, WCCP2_SERVICE_DYNAMIC, wccp2_service_list_head, and wccp2_service_list_t::wccp_password.
dump_wccp2_service_info()
void dump_wccp2_service_info (StoreEntry * e, const char * label, void * v)
Definition at line 2423 of file wccp2.cc.
References debugs, wccp2_service_list_t::info, wccp2_service_list_t::next, wccp2_service_info_t::port0, wccp2_service_info_t::port1, wccp2_service_info_t::port2, wccp2_service_info_t::port3, wccp2_service_info_t::port4, wccp2_service_info_t::port5, wccp2_service_info_t::port6, wccp2_service_info_t::port7, wccp2_service_info_t::service, wccp2_service_info_t::service_flags, wccp2_service_info_t::service_id, wccp2_service_info_t::service_priority, wccp2_service_info_t::service_protocol, storeAppendPrintf(), WCCP2_SERVICE_DST_IP_ALT_HASH, WCCP2_SERVICE_DST_IP_HASH, WCCP2_SERVICE_DST_PORT_ALT_HASH, WCCP2_SERVICE_DST_PORT_HASH, wccp2_service_list_head, WCCP2_SERVICE_PORTS_DEFINED, WCCP2_SERVICE_PORTS_SOURCE, WCCP2_SERVICE_SRC_IP_ALT_HASH, WCCP2_SERVICE_SRC_IP_HASH, WCCP2_SERVICE_SRC_PORT_ALT_HASH, WCCP2_SERVICE_SRC_PORT_HASH, and WCCP2_SERVICE_STANDARD.
free_wccp2_amethod()
void free_wccp2_amethod (int * v)
Definition at line 2154 of file wccp2.cc.
free_wccp2_method()
void free_wccp2_method (int * v)
Definition at line 2106 of file wccp2.cc.
free_wccp2_service()
void free_wccp2_service (void * v)
Definition at line 2239 of file wccp2.cc.
free_wccp2_service_info()
void free_wccp2_service_info (void * v)
Definition at line 2593 of file wccp2.cc.
parse_wccp2_amethod()
void parse_wccp2_amethod (int * method)
Parse wccp2_assignment_method option they can be '1' aka 'hash' or '2' aka 'mask' representing the integer numeric of the same.
Definition at line 2115 of file wccp2.cc.
References DBG_CRITICAL, debugs, ConfigParser::NextToken(), self_destruct(), WCCP2_ASSIGNMENT_METHOD_HASH, and WCCP2_ASSIGNMENT_METHOD_MASK.
parse_wccp2_method()
void parse_wccp2_method (int * method)
Parse wccp2_return_method and wccp2_forwarding_method options they can be '1' aka 'gre' or '2' aka 'l2' representing the integer numeric of the same.
Definition at line 2067 of file wccp2.cc.
References DBG_CRITICAL, debugs, ConfigParser::NextToken(), self_destruct(), WCCP2_METHOD_GRE, and WCCP2_METHOD_L2.
parse_wccp2_service()
void parse_wccp2_service (void * v)
Definition at line 2163 of file wccp2.cc.
References DBG_CRITICAL, DBG_IMPORTANT, debugs, empty_portlist, GetInteger(), ConfigParser::NextToken(), self_destruct(), wccp2_add_service_list(), wccp2_connected, WCCP2_MD5_SECURITY, WCCP2_NO_SECURITY, WCCP2_PASSWORD_LEN, WCCP2_SERVICE_DYNAMIC, WCCP2_SERVICE_STANDARD, and xstrncpy().
parse_wccp2_service_info()
void parse_wccp2_service_info (void * v)
Definition at line 2343 of file wccp2.cc.
References DBG_CRITICAL, DBG_IMPORTANT, debugs, fatalf(), GetInteger(), ConfigParser::NextToken(), parse_wccp2_service_flags(), parse_wccp2_service_ports(), self_destruct(), wccp2_connected, wccp2_get_service_by_id(), WCCP2_NUMPORTS, WCCP2_SERVICE_DYNAMIC, WCCP2_SERVICE_PORTS_DEFINED, and wccp2_update_service().