Squid Web Cache: squid/src/clients/WhoisGateway.cc File Reference
WhoisGateway.cc File Reference
#include "squid.h"
#include "clients/WhoisGateway.h"
#include "comm.h"
#include "comm/Read.h"
#include "comm/Write.h"
#include "errorpage.h"
#include "FwdState.h"
#include "HttpReply.h"
#include "HttpRequest.h"
#include "SquidConfig.h"
#include "StatCounters.h"
#include "Store.h"
#include "tools.h"
#include <cerrno>
Classes
class WhoisState
Functions
CBDATA_CLASS_INIT (WhoisState)
static void whoisWriteComplete (const Comm::ConnectionPointer &, char *buf, size_t, Comm::Flag, int, void *)
void whoisStart (FwdState *fwd)
static void whoisTimeout (const CommTimeoutCbParams &io)
static void whoisReadReply (const Comm::ConnectionPointer &conn, char *buf, size_t len, Comm::Flag flag, int xerrno, void *data)
static void whoisClose (const CommCloseCbParams &params)
Variables
static CLCB whoisClose
static CTCB whoisTimeout
static IOCB whoisReadReply
Function Documentation
CBDATA_CLASS_INIT()
CBDATA_CLASS_INIT (WhoisState)
whoisClose()
static void whoisClose (const CommCloseCbParams & params) static
Definition at line 184 of file WhoisGateway.cc.
References CommCommonCbParams::data, debugs, WhoisState::entry, CommCommonCbParams::fd, and StoreEntry::unlock().
whoisReadReply()
static void whoisReadReply (const Comm::ConnectionPointer & conn, char * buf, size_t len, Comm::Flag flag, int xerrno, void * data) static
Definition at line 95 of file WhoisGateway.cc.
References WhoisState::readReply().
whoisTimeout()
static void whoisTimeout (const CommTimeoutCbParams & io) static
Definition at line 87 of file WhoisGateway.cc.
References Comm::Connection::close(), CommCommonCbParams::conn, CommCommonCbParams::data, debugs, WhoisState::entry, and StoreEntry::url().
whoisWriteComplete()
static void whoisWriteComplete (const Comm::ConnectionPointer & , char * buf, size_t , Comm::Flag , int , void *) static
Definition at line 50 of file WhoisGateway.cc.
References xfree.
Referenced by whoisStart().
Variable Documentation
whoisClose
CLCB whoisClose static
Definition at line 43 of file WhoisGateway.cc.
Referenced by whoisStart().
whoisReadReply
IOCB whoisReadReply static
Definition at line 45 of file WhoisGateway.cc.
Referenced by WhoisState::readReply(), and whoisStart().
whoisTimeout
CTCB whoisTimeout static
Definition at line 44 of file WhoisGateway.cc.
Referenced by whoisStart().