Squid Web Cache: squid/src/wordlist.h File Reference
wordlist.h File Reference
#include "globals.h"
#include "sbuf/List.h"
#include <iterator>
Classes
class WordlistIterator
minimal iterator for read-only traversal of wordlist objects
class wordlist
Functions
const char * wordlistAdd (wordlist **, const char *)
void wordlistCat (const wordlist *, MemBuf *)
void wordlistDestroy (wordlist **)
destroy a wordlist
char * wordlistChopHead (wordlist **)
Function Documentation
wordlistAdd()
const char * wordlistAdd (wordlist ** list, const char * key)
Add a null-terminated c-string to a wordlist
Deprecated:
use SBufList.push_back(SBuf(word)) instead
Definition at line 25 of file wordlist.cc.
References wordlist::next.
Referenced by Adaptation::Icap::Options::TransferList::add(), ftpReadType(), Ssl::Helper::Init(), Ssl::CertValidationHelper::Init(), netdbPeerName(), ACLExternal::parse(), parse_externalAclHelper(), and parse_wordlist().
wordlistCat()
void wordlistCat (const wordlist * w, MemBuf * mb)
Concatenate a wordlist
Deprecated:
use SBufListContainerJoin(SBuf()) from sbuf/Algorithms.h instead
Definition at line 35 of file wordlist.cc.
References Packable::appendf().
Referenced by ErrorState::compileLegacyCode().
wordlistChopHead()
char * wordlistChopHead (wordlist ** wl)
Remove and destroy the first element while preserving and returning its key
Note
the returned key must be freed by the caller using safe_free
wl is altered so that it points to the second element
Returns
nullptr if pointed-to wordlist is nullptr.
Definition at line 44 of file wordlist.cc.
Referenced by ftpTraverseDirectory(), and wordlistDestroy().
wordlistDestroy()
void wordlistDestroy (wordlist ** list)
Definition at line 16 of file wordlist.cc.
References safe_free, and wordlistChopHead().
Referenced by Ftp::CtrlChannel::~CtrlChannel(), ErrorState::~ErrorState(), external_acl::~external_acl(), external_acl_data::~external_acl_data(), Ftp::Gateway::~Gateway(), Ftp::Relay::~Relay(), Adaptation::Icap::Options::TransferList::~TransferList(), configDoConfigure(), ftpTrySlashHack(), Ftp::Client::handleControlReply(), Adaptation::ServiceGroup::parse(), Auth::SchemeConfig::parse(), Ftp::Client::parseControlReply(), Ftp::Client::sendPassive(), Ssl::Helper::Shutdown(), Ssl::CertValidationHelper::Shutdown(), and Ftp::Relay::stopDirTracking().