Squid Web Cache: squid/compat/xstrerror.cc File Reference
xstrerror.cc File Reference
#include "squid.h"
#include "compat/xstrerror.h"
#include <cstring>
Functions
const char * xstrerr (int error)
Function Documentation
xstrerr()
const char * xstrerr (int error)
Provide the textual display of a system error number. A string is always returned. Where strerror() would have provided nullptr this will report the error as unknown. On MS Windows the native Win32 errors are also translated.
Definition at line 83 of file xstrerror.cc.
References BUFSIZ, error(), and strerror().
Referenced by _db_rotate_log(), Ftp::Server::AcceptCtrlConnection(), Ftp::Server::acceptDataConnection(), Comm::TcpAcceptor::acceptInto(), CpuAffinitySet::apply(), authenticate(), clientListenerConnectionOpened(), Server::clientWriteDone(), DiskdFile::close(), Fs::Ufs::UFSSwapDir::closeTmpSwapLog(), comm_apply_flags(), comm_connect_addr(), comm_local_port(), comm_open_uds(), comm_openex(), comm_set_transparent(), comm_set_v6only(), comm_udp_sendto(), commBind(), commConfigureLinger(), commSetBindAddressNoPort(), commSetCloseOnExec(), commSetNonBlocking(), commSetReuseAddr(), commSetTcpRcvbuf(), commUnsetNonBlocking(), DiskdFile::create(), Fs::Ufs::UFSSwapDir::createDirectory(), Rock::SwapDir::createError(), Ftp::Client::dataRead(), debugOpenLog(), Fs::Ufs::UFSSwapDir::DirClean(), DiskerOpen(), diskerWriteAttempts(), diskHandleRead(), diskHandleWrite(), Server::doClientRead(), Comm::ConnOpener::doConnect(), enter_suid(), TunnelStateData::Connection::error(), examine_select(), Rock::Rebuild::failure(), file_open(), FileRename(), fsBlockSize(), fsStats(), Ftp::Gateway::ftpAcceptDataConnection(), ftpOpenListenSocket(), getMyHostname(), Fs::Ufs::RebuildState::getNextFile(), Ip::Qos::getNfConnmark(), Ip::Qos::getTosFromServer(), GoIntoBackground(), htcpSend(), httpAccept(), httpsAccept(), icpHandleUdp(), idnsParseResolvConf(), idnsRead(), idnsSendQuery(), Ipc::ImportFdIntoComm(), DiskdIOStrategy::init(), SharedMemory::init(), Rock::SwapDir::ioCompletedNotification(), ipc_thread_1(), ipcCreate(), ipcSend(), leave_suid(), MimeIcon::load(), TemplateFile::loadFromFile(), logfile_mod_stdio_open(), logfile_mod_stdio_rotate(), logfile_mod_udp_open(), logfile_mod_udp_write(), logfileHandleWrite(), logfileWriteWrapper(), Eui::Eui48::lookup(), Comm::ConnOpener::lookupLocalAddress(), main(), main(), main(), mainChangeDir(), mainSetCwd(), makeTraceable(), Mmapping::map(), mcastJoinGroups(), mcastSetTtl(), mimeInit(), netdbSaveState(), Ip::Intercept::NetfilterInterception(), no_suid(), Adaptation::Icap::Xaction::noteCommRead(), Icmp4::Open(), Icmp6::Open(), IcmpPinger::Open(), MmappedFile::open(), DiskThreadsDiskFile::openDone(), Fs::Ufs::UFSSwapDir::openLog(), Fs::Ufs::UFSSwapDir::openTmpSwapLog(), operator<<(), parseEtcHosts(), parseManyConfigFiles(), parseOneConfigFile(), Fs::Ufs::UFSSwapDir::pathIsDirectory(), Ip::Intercept::PfInterception(), ProcessIsRunning(), DiskdFile::read(), read_mib(), read_passwd_file(), read_passwd_file(), IpcIoFile::readCompleted(), Ftp::Client::readControlReply(), Comm::ReadNow(), WhoisState::readReply(), HttpStateData::readReply(), Fs::Ufs::RebuildState::rebuildFromDirectory(), IcmpSquid::Recv(), requirePathnameExists(), rotate(), safeunlink(), Comm::SelectLoopInit(), DiskdIOStrategy::SEND(), Icmp4::SendEcho(), Icmp6::SendEcho(), IcmpSquid::SendEcho(), IcmpPinger::SendResult(), sendSignal(), Client::sentRequestBody(), Comm::TcpAcceptor::setListen(), setMaxFD(), Ip::Qos::setNfConnmark(), SetSocketOption(), Ip::Qos::setSockNfmark(), Ip::Qos::setSockTos(), setSystemLimits(), sigusr2_handle(), snmpHandleUdp(), squid_signal(), ConnStateData::start(), storeRebuildLoadEntry(), File::sysCallError(), CpuAffinitySet::undo(), unlinkdUnlink(), DiskdIOStrategy::unlinkFile(), Mmapping::unmap(), StoreEntry::vappendf(), SysErrorDetail::verbose(), watch_child(), wccp2AssignBuckets(), wccp2ConnectionOpen(), wccp2HereIam(), wccpHereIam(), UFSCleanLog::write(), DiskdFile::write(), MmappedFile::write(), Fs::Ufs::UFSSwapDir::writeCleanDone(), Ftp::Client::writeCommandCallback(), IpcIoFile::writeCompleted(), Log::TcpLogger::writeDone(), HttpControlMsgSink::wroteControlMsg(), Ftp::Server::wroteEarlyReply(), Ftp::Server::wroteReply(), and Ftp::Server::wroteReplyData().