Squid Web Cache: squid/compat/xstrto.cc File Reference
xstrto.cc File Reference
#include "squid.h"
#include "compat/xstrto.h"
#include <cerrno>
Macros
#define SQUID_XSTRTO_C_
Functions
static bool xstrtoul (const char *s, char **end, unsigned long *value, unsigned long min, unsigned long max)
bool xstrtoui (const char *s, char **end, unsigned int *value, unsigned int min, unsigned int max)
Macro Definition Documentation
SQUID_XSTRTO_C_
#define SQUID_XSTRTO_C_
Definition at line 10 of file xstrto.cc.
Function Documentation
xstrtoui()
bool xstrtoui (const char * s, char ** end, unsigned int * value, unsigned int min, unsigned int max)
Convert a c-string (or its prefix) into an unsigned integer.
Parameters
s input string
end like strtoul's "end" pointer
value pointer for result. Undefined on failure
min minimum accepted value
max maximum accepted value
If @end is nullptr, we assume the caller wants a "strict strtoul", and hence "15a" is rejected. In either case, the value obtained is compared for min-max compliance. Base is always 0, i.e. autodetect depending on @s.
Returns
true/false whether number was accepted. On failure, *value has undefined contents.
Definition at line 86 of file xstrto.cc.
References max(), min(), and xstrtoul().
Referenced by parse_acl_tos(), Ip::Qos::Config::parseConfigLine(), and process_options().
xstrtoul()
static bool xstrtoul (const char * s, char ** end, unsigned long * value, unsigned long min, unsigned long max) static
Definition at line 61 of file xstrto.cc.
References max(), and min().
Referenced by xstrtoui().