Squid Web Cache: squid/compat/xstring.cc File Reference
xstring.cc File Reference
#include "squid.h"
#include "compat/xalloc.h"
#include "compat/xstring.h"
#include <cerrno>
Functions
char * xstrdup (const char *s)
char * xstrncpy (char *dst, const char *src, size_t n)
char * xstrndup (const char *s, size_t n)
Function Documentation
xstrdup()
char * xstrdup (const char * s)
xstrdup() - same as strdup(3). Used for portability. Never returns nullptr; fatal on error.
Sets errno to EINVAL if a nullptr pointer is passed.
Define failure_notify to receive error message. otherwise perror() is used to display it.
Definition at line 16 of file xstring.cc.
References failure_notify, and xmalloc.
xstrncpy()
char * xstrncpy (char * dst, const char * src, size_t n)
Definition at line 37 of file xstring.cc.
Referenced by Logfile::Logfile(), accessLogLogTo(), String::append(), BindLDAP(), build_groups_DN_array(), Ftp::Gateway::checkAuth(), DiskdFile::create(), EvalBoolExpr(), fd_note(), Ssl::findIssuerUri(), getStringPrefix(), AnyP::Uri::host(), InitLDAP(), internalHostname(), internalRemoteUri(), LDAPHHA1(), local_printfx(), Fs::Ufs::UFSSwapDir::logFile(), MainSafe(), mainStartScript(), manage_request(), mimeInit(), DiskdFile::open(), OpenLDAP(), Format::Token::parse(), AnyP::Uri::parse(), parse_date(), parse_wccp2_service(), Ftp::Client::parseControlReply(), Ftp::Gateway::parseListing(), parseOneConfigFile(), Ipc::PathToAddress(), ResetLDAP(), HierarchyLogEntry::resetPeerNotes(), rfc1035BuildAQuery(), rfc1035BuildPTRQuery(), rfc3596BuildHostQuery(), SearchFilterLDAP(), SearchIPLDAP(), SearchLDAP(), Comm::TcpAcceptor::setListen(), TextHHA1(), unlinkdUnlink(), DiskdIOStrategy::unlinkFile(), ConfigParser::UnQuote(), urlCanonicalCleanWithoutRequest(), Valid_Global_Groups(), Valid_User(), wccp2_add_service_list(), wccp2_check_security(), wccp2_update_md5_security(), and xstrndup().
xstrndup()
char * xstrndup (const char * s, size_t n)
xstrndup() - Somewhat similar(XXX) to strndup(3): Allocates up to n bytes, while strndup(3) copies up to n bytes and allocates up to n+1 bytes to fit the terminating character. Assumes s is 0-terminated (another XXX).
Never returns nullptr; fatal on error.
Sets errno to EINVAL if a nullptr pointer or negative length is passed.
Define failure_notify to receive error message. otherwise perror() is used to display it.
Definition at line 56 of file xstring.cc.
References failure_notify, xmalloc, and xstrncpy().
Referenced by AnyP::Uri::cleanup(), ftpListParseParts(), Adaptation::Icap::Options::TransferList::parse(), HttpHdrSc::parse(), process_options(), ClientHttpRequest::setErrorUri(), ClientHttpRequest::setLogUriToRequestUri(), and ConfigParser::TokenParse().